Create Logzio detailed info
TykTechnologies/tyk-docs-hugo pull request #1021
Opened 2020-01-27 12:05 UTC by joshblakeley

We a lack of useful info about logzio pump so have fixed that.

2020-01-27 12:15 UTC, marksou approved these changes
LGTM

2020-01-27 13:00 UTC, joshblakeley commented
Cheers @marksou please merge

2020-02-01 14:33 UTC, letzya requested changes

2020-02-01 14:33 UTC, letzya commented on tyk-docs/content/tyk-configuration-reference/tyk-pump-configuration.md
> +
Would be good to put it in another code example since it’s the fields are probably under logzio but one might think that some of them are under meta

2020-02-01 15:43 UTC, joshblakeley commented on tyk-docs/content/tyk-configuration-reference/tyk-pump-configuration.md
> +
They're all under meta actually so will add them for clarity

2020-02-05 09:00 UTC, joshblakeley commented
@letzya ptal

2020-02-07 10:23 UTC, letzya commented on tyk-docs/content/tyk-configuration-reference/tyk-pump-configuration.md
> +More advanced fields:
can you put all these advanced fields in an example or declare they are under "meta". Don't think it's trivial to understand that

2020-02-10 16:16 UTC, letzya approved these changes

2020-02-12 10:31 UTC, merged