On prem links
TykTechnologies/tyk-docs-hugo pull request #1109
Opened 2020-03-10 14:29 UTC by marksou

2020-04-09 19:31 UTC, sedkis requested changes

2020-04-09 19:31 UTC, sedkis commented on tyk-docs/content/getting-started/installation/with-tyk-cloud/create-an-account.md
> +2. You'll then be taken to our [PoC or Pro Plan form](https://signup.tyk.io/api-gateway/cloud/#cloud). Proof of Concept is selected by default.
Actually Mark I don't think we want to link here the sign up page for step #2.  We'd prefer for users to sign up through step 1.

2020-04-09 19:31 UTC, sedkis commented on tyk-docs/content/getting-started/installation/with-tyk-multi-cloud/create-an-account.md
> +2. You'll then be taken to our [PoC or Pro Plan form](https://signup.tyk.io/api-gateway/cloud/#cloud). Select Pro Plan from the form.
Same goes here as previous comment.  

Also, should we make it more explicit that in order to use Multi-Cloud, they HAVE to select Pro Plan, as PoC plan doesn't enable multi-cloud?

2020-09-23 09:29 UTC, marksou commented on tyk-docs/content/getting-started/installation/with-tyk-multi-cloud/create-an-account.md
> +2. You'll then be taken to our [PoC or Pro Plan form](https://signup.tyk.io/api-gateway/cloud/#cloud). Select Pro Plan from the form.
@sedkis I think this PR is no longer required, as Tyk Cloud signup has superseeded the above?

2020-09-24 22:39 UTC, closed without merging