Add internal plugin description
TykTechnologies/tyk-docs-hugo pull request #1111
Opened 2020-03-10 18:02 UTC by marksou

2020-03-10 18:08 UTC, letzya commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +### Internal
it's not a plugin but a **config** and as such it shouldn't be in this page at all since it's in the "core setting" tab.

Also I would make the sentence a bit clearer to understand. Usually people are in a rush when breezing through docs and having 3 "to" and negative doesn't make it any easier "to set an endpoint to not be listened to by the "

2020-03-10 18:09 UTC, letzya requested changes
per my comments

2020-03-10 18:13 UTC, marksou commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +### Internal
I'm confused now as it's listed as a plugin from the Endpoint Designer?

2020-03-11 15:07 UTC, buger commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +This plugin allows you to set an endpoint to not be listened to by the Tyk Gateway, but can be called by other APIs by using the `tyk://` prefix.
Update it to be `tyk://self/` prefix

2020-03-11 15:08 UTC, buger commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +### Internal
We have both API level config variable, and per endpoint. 
When you set it for the endpoint, it does not get exposed to the user, but you still can use it via looping.

2020-03-11 16:10 UTC, marksou commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +This plugin allows you to set an endpoint to not be listened to by the Tyk Gateway, but can be called by other APIs by using the `tyk://` prefix.
@letzya are you happy to approve following @buger comments?

2020-09-23 09:34 UTC, marksou commented
Merging this as per @buger comments.

2020-09-23 09:34 UTC, merged