add example of JWKs url
TykTechnologies/tyk-docs-hugo pull request #1119
Opened 2020-03-18 16:06 UTC by sedkis

2020-03-18 18:32 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/your-apis/json-web-tokens.md
> +Set the cryptographic method to use and enter the key in the secrets text field (PEM Encoded), this can either be an **RSA public key** or an **HMAC shared secret**. If using a RSA Public Key you can
Does it sound like both shared secret and HMAC are in PEM? 

`Set the cryptographic method to use and enter the key in the secrets text field (PEM Encoded), this can either be an **RSA public key** or an **HMAC shared secret**.`

2020-03-18 22:51 UTC, letzya requested changes

2020-03-18 22:51 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/your-apis/json-web-tokens.md
> +You can also use a JWKS discovery endpoint, see option #3.
This is a bit confusing since you must to choose **RSA public key** so better to say something like - 

> "When using RSA public key method you can also have a JWK discovery endpoint, see option #3 for details"

Otherwise it feels like it relates to both methods

2020-03-18 22:51 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/your-apis/json-web-tokens.md
> +This /certs endpoint returns the following payload:
sorry what is this `/cert` endpoint?

2020-03-18 22:51 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/your-apis/json-web-tokens.md
> +This is a JWKS complaint payload.  If the issuer generates an ID Token or Access Token using OIDC or OAuth 2.0, the header will include the following kid, which matches the JWKS kid above.
change to JWKs

2020-03-19 15:27 UTC, sedkis commented on tyk-docs/content/basic-config-and-security/security/your-apis/json-web-tokens.md
> +This is a JWKS complaint payload.  If the issuer generates an ID Token or Access Token using OIDC or OAuth 2.0, the header will include the following kid, which matches the JWKS kid above.
Change what to JWKS?

2020-03-19 15:27 UTC, sedkis commented on tyk-docs/content/basic-config-and-security/security/your-apis/json-web-tokens.md
> +This /certs endpoint returns the following payload:
It's in the screenshot

2020-03-19 15:27 UTC, sedkis commented on tyk-docs/content/basic-config-and-security/security/your-apis/json-web-tokens.md
> +You can also use a JWKS discovery endpoint, see option #3.
Agreed - thankyou

2020-03-20 16:48 UTC, letzya approved these changes

2020-03-20 18:49 UTC, sedkis commented
@marksou please merge

2020-03-20 22:08 UTC, merged