adds a page for benchmarking
TykTechnologies/tyk-docs-hugo pull request #1141
Opened 2020-04-07 05:36 UTC by sedkis

2020-04-07 13:44 UTC, asoorm requested changes

2020-04-07 13:44 UTC, asoorm commented on tyk-docs/content/benchmarks/benchmarks.md
> +|     Hardware specs      |   Throughput (RPS)  |  99% Latency  |    EC2 Cost    |
`99% Latency` -> `P99 Latency`

2020-04-07 13:44 UTC, asoorm commented on tyk-docs/content/benchmarks/benchmarks.md
> +|     Hardware specs      |   Throughput (RPS)  |  99% Latency  |    EC2 Cost    |
I would also provide P95 in here also.

This is also completely unrealistic, where I would assume the machines are consuming 99% of the CPU. So maybe it's worth dropping the RPS, and showing P99 latency at 90% of max RPS?

e.g. t2.micro - provide P99 latency running 2659 RPS.

2020-04-07 13:44 UTC, asoorm commented on tyk-docs/content/benchmarks/benchmarks.md
> +*** link to AWS testing blog
Pending Blog Post

2020-04-07 13:53 UTC, asoorm commented on tyk-docs/content/benchmarks/benchmarks.md
> +|     Hardware specs      |   Throughput (RPS)  |  99% Latency  |    EC2 Cost    |
I would also caveat that you deployed Tyk in docker. So note that there is approx 10% performance overhead here.

2020-04-07 14:46 UTC, sedkis commented on tyk-docs/content/benchmarks/benchmarks.md
> +|     Hardware specs      |   Throughput (RPS)  |  99% Latency  |    EC2 Cost    |
@asoorm  re your comment, are you suggesting having a column that says “max throughput” and then another one that says “P99 latency at 90% throughput” ?

what is the benefit to an end user for reading this ?

2020-04-07 14:46 UTC, sedkis commented on tyk-docs/content/benchmarks/benchmarks.md
> +|     Hardware specs      |   Throughput (RPS)  |  99% Latency  |    EC2 Cost    |
noted the docker deploy comment and added

2020-04-07 14:54 UTC, asoorm commented on tyk-docs/content/benchmarks/benchmarks.md
> +|     Hardware specs      |   Throughput (RPS)  |  99% Latency  |    EC2 Cost    |
> @asoorm re your comment, are you suggesting having a column that says “max throughput” and then another one that says “P99 latency at 90% throughput” ?
> 
> what is the benefit to an end user for reading this ?

4 columns:

```
Max Throughput at P95, Max Throughput at P99
90% Throughput at P95, 90% Throughput at P99
```

The way it is currently presented - it will mean different things to different groups of people.

* If latency is a concern, users won't understand that by reducing throughput by a little bit, you can significantly reduce the latency. 
* The P99 value is phenomenally low. That's awesome and something to shout about. But there are far too many peeps that just look at the headline figures and come to the wrong conclusions. e.g they may thikn that our latency is bad without bothering to read full story.
* We don't currently show (via P95) what to expect in a normal, healthy transaction. So the P99, is basically showing worst case scenario, probably during a GC cycle.

2020-04-07 14:56 UTC, asoorm commented on tyk-docs/content/benchmarks/benchmarks.md
> +|     Hardware specs      |   Throughput (RPS)  |  99% Latency  |    EC2 Cost    |
It feels like we just need to present the full picture. This is what you can expect during normal operation. And during a GC cycle >P99, things might slow down by a bit

2020-04-07 15:10 UTC, matthewtanner91 commented on tyk-docs/content/benchmarks/benchmarks.md
> +> **Note:** The P99 Latency is a metric which means that 99% of all API requests experience a lower latency than the given figure.
I would outline something like: Simply put, this means that 99% of the time your latency will be lower than the number used here.

Probably still a better way to phrase it to make it accessible to those who still don't understand the terminology used in the pervious sentence. I think it is important to make sure that people really understand what is meant or they may think that you picked the fastest 1% for the metric which is opposite of the case here.

2020-05-05 19:44 UTC, sedkis commented on tyk-docs/content/benchmarks/benchmarks.md
> +*** link to AWS testing blog
Added

2020-05-05 19:44 UTC, sedkis commented on tyk-docs/content/benchmarks/benchmarks.md
> +> **Note:** The P99 Latency is a metric which means that 99% of all API requests experience a lower latency than the given figure.
Gotcha thanks

2020-05-05 19:44 UTC, sedkis commented on tyk-docs/content/benchmarks/benchmarks.md
> +|     Hardware specs      |   Throughput (RPS)  |  99% Latency  |    EC2 Cost    |
I understand - thanks.  @nerdydread has actually gotten some good metrics for us that we will add for P99 at 90% max capacity instead of 100%

2020-05-05 19:48 UTC, marksou approved these changes
LGTM

2020-05-05 19:55 UTC, sedkis commented
@marksou go ahead - also let me know if you prefer we move it to "Planning for production" ? im not sure

2020-05-06 08:06 UTC, merged