rewrite stuff
TykTechnologies/tyk-docs-hugo pull request #1319
Opened 2020-06-26 14:50 UTC by sedkis

The new content to be approved, everything else is just moving stuff around:
1) request plugins
<img width="901" alt="image" src="https://user-images.githubusercontent.com/8964621/85870130-a9cf4080-b79a-11ea-87c1-bc4311eb52e5.png">

2) supported auth languages
<img width="861" alt="image" src="https://user-images.githubusercontent.com/8964621/85870256-d3886780-b79a-11ea-8367-95a2bfabfc9e.png">

2020-06-26 15:40 UTC, letzya requested changes

2020-06-26 15:40 UTC, letzya commented on tyk-docs/content/plugins/request-plugins.md
> +You can have your plugin finish the request lifecycle and return a response to the requestor.
to clarify I'd add that you modify the response body.

2020-06-26 15:40 UTC, letzya commented on tyk-docs/content/plugins/response-plugins.md
> +- Tyk runs the full middleware chain, including any other rich plugins hooks like Pre, Post, Custom Authentication, etc.
maybe remove the word "rich"? since it applies to any plugin - go, jsvm etc.

2020-06-26 15:40 UTC, letzya commented on tyk-docs/content/plugins/response-plugins.md
> +Since Tyk 3.0 we have incorporated response hooks, this type of hook allows you to modify the response object before its being sent to the client. The flow is follows:
can you add a clarification that this called after the gw received a response from the upstream? unlike return override that never gets to the backend

2020-06-26 15:40 UTC, letzya commented on tyk-docs/content/plugins/request-plugins.md
> +There are 3 different phases in the [request lifecycle](/docs/getting-started/key-concepts/middleware-execution-order/) you can inject custom plugins, 4 if you include [Authentication plugins](/docs/
I personally would not say 3 and then 4, just 4 since auth hook is like any other hook.

Question - which "performance advantages to picking the correct phase,"?

2020-06-26 15:40 UTC, letzya commented on tyk-docs/content/plugins/request-plugins.md
> +| Can modify Token (metadata, quota, context-vars, tags, etc)|          | ✅          |          |
I still think it's confusing. maybe write "Can modify user session" - a session is a common term

context-vars - this is not part of the user session but the other way around. you can access the context using the request object and from the request, you get everything - session object, context-var, headers.
check https://site-dev.tykbeta.com/docs/plugins/rich-plugins/rich-plugins-data-structures/#sessionstate-session_stateproto

2020-06-26 15:56 UTC, sedkis commented on tyk-docs/content/plugins/request-plugins.md
> +| Can modify Token (metadata, quota, context-vars, tags, etc)|          | ✅          |          |
I've updated this!

2020-06-26 22:30 UTC, sedkis commented on tyk-docs/content/plugins/response-plugins.md
> +Since Tyk 3.0 we have incorporated response hooks, this type of hook allows you to modify the response object before its being sent to the client. The flow is follows:
Done:
`
Since Tyk 3.0 we have incorporated response hooks, this type of hook allows you to modify the response object sent by the upstream. The flow is follows:
`

2020-06-26 22:31 UTC, sedkis commented on tyk-docs/content/plugins/request-plugins.md
> +There are 3 different phases in the [request lifecycle](/docs/getting-started/key-concepts/middleware-execution-order/) you can inject custom plugins, 4 if you include [Authentication plugins](/docs/
Done

2020-06-26 22:31 UTC, sedkis commented on tyk-docs/content/plugins/request-plugins.md
> +There are 3 different phases in the [request lifecycle](/docs/getting-started/key-concepts/middleware-execution-order/) you can inject custom plugins, 4 if you include [Authentication plugins](/docs/
>Question - which "performance advantages to picking the correct phase,"?
The ones we spoke about on Slack!

2020-06-26 22:32 UTC, sedkis commented on tyk-docs/content/plugins/request-plugins.md
> +| Can modify Token (metadata, quota, context-vars, tags, etc)|          | ✅          |          |
Done!

2020-06-29 13:13 UTC, marksou approved these changes
👍

2020-06-29 14:15 UTC, merged

2020-06-30 11:15 UTC, letzya commented on tyk-docs/content/plugins/request-plugins.md
> +There are 3 different phases in the [request lifecycle](/docs/getting-started/key-concepts/middleware-execution-order/) you can inject custom plugins, 4 if you include [Authentication plugins](/docs/
I don't remember but you mean to fail sooner than later but regardless we should explain it here not just stating it vaguely.