add example for modsecurity waf in tyk
TykTechnologies/tyk-docs-hugo pull request #1322
Opened 2020-06-30 01:54 UTC by sedkis

2020-07-01 08:04 UTC, marksou approved these changes
GTG

2020-07-01 13:48 UTC, sedkis commented
go ahead @marksou

2020-07-02 18:44 UTC, janeves requested changes
Disclaimer should be at the top, host plugin script so its not on personal repo.

2020-07-02 18:44 UTC, janeves commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/waf-js-plugin.md
> +#### Disclaimer
This should be at the top to clarify expectations with this method of hooking into a WAF

2020-07-02 18:44 UTC, janeves commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/waf-js-plugin.md
> +title: WAF ModSecurity Plugin using JS
WAF plugin example utilizing Open Source ModSecurity and JS

2020-07-02 18:44 UTC, janeves commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/waf-js-plugin.md
> +curl https://gist.githubusercontent.com/sedkis/bae5e39c581d66b87d3ee81086fd95c5/raw/838751553221fddb284d67b027aa16128dda743e/waf.js | cat > middleware/waf.js
Can the script be hosted in the docs or at least not on your private gist so others can edit if needed?

2020-07-02 18:44 UTC, janeves commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/waf-js-plugin.md
> +root@670039a3e0b8:/opt/tyk-gateway# curl https://gist.githubusercontent.com/sedkis/bae5e39c581d66b87d3ee81086fd95c5/raw/838751553221fddb284d67b027aa16128dda743e/waf.js | cat > middleware/waf.js
Same as above

2020-07-02 18:44 UTC, janeves commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/waf-js-plugin.md
> +[waf.js source](https://gist.githubusercontent.com/sedkis/bae5e39c581d66b87d3ee81086fd95c5/raw/838751553221fddb284d67b027aa16128dda743e/waf.js)
Ditto

2020-07-14 18:52 UTC, sedkis commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/waf-js-plugin.md
> +curl https://gist.githubusercontent.com/sedkis/bae5e39c581d66b87d3ee81086fd95c5/raw/838751553221fddb284d67b027aa16128dda743e/waf.js | cat > middleware/waf.js
Yep, will move to Tyk custom-plugins repo

2020-07-15 21:13 UTC, matiasinsaurralde approved these changes
Awesome!

2020-07-16 13:27 UTC, sedkis commented
Requesting a merge - all requests have been made

2020-07-16 13:28 UTC, merged