updated #10 logging and monitoring
TykTechnologies/tyk-docs-hugo pull request #1337
Opened 2020-07-08 09:26 UTC by letzya

Also changed broken link

2020-07-08 09:50 UTC, asoorm requested changes
Couple of suggestions, mostly in relation to readability, grammar & spelling.

2020-07-08 09:50 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +Tyk provides information and feedback in varoius ways:
various

2020-07-08 09:50 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- Request analytics with different ways of [datailed recording](https://site-dev.tykbeta.com/docs/analytics-and-reporting/useful-debug-modes/) on the request level and the key level. Data per data, i
detailed

2020-07-08 09:50 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [OpenTracing](https://site-dev.tykbeta.com/docs/advanced-configuration/opentracing/) to allows services which have distributed tracing enabled for instrumentation to work seamless with Tyk gateway.
to allows -> to allow

2020-07-08 09:50 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [OpenTracing](https://site-dev.tykbeta.com/docs/advanced-configuration/opentracing/) to allows services which have distributed tracing enabled for instrumentation to work seamless with Tyk gateway.
>  for instrumentation to work seamless with Tyk gateway.

Not sure this makes sense

2020-07-08 09:50 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- Request analytics with different ways of [datailed recording](https://site-dev.tykbeta.com/docs/analytics-and-reporting/useful-debug-modes/) on the request level and the key level. Data per data, i
Is this url ok? `https://site-dev.tykbeta.com`

2020-07-08 09:50 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [OpenTracing](https://site-dev.tykbeta.com/docs/advanced-configuration/opentracing/) to allows services which have distributed tracing enabled for instrumentation to work seamless with Tyk gateway.
Is this URL ok? `https://site-dev.tykbeta.com`

2020-07-08 09:50 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Events handler](https://site-dev.tykbeta.com/docs/basic-config-and-security/report-monitor-trigger-events/) - Tyk has the ability to configure APIs with event handlers to log data or send webhook
Events handler -> Event Handlers

2020-07-08 09:50 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Events handler](https://site-dev.tykbeta.com/docs/basic-config-and-security/report-monitor-trigger-events/) - Tyk has the ability to configure APIs with event handlers to log data or send webhook
send webhook -> fire webhooks

2020-07-08 09:50 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +There are currently two built-in event handlers: eh_log_handler (Log handler – mainly for debugging) and eh_web_hook_handler (Web Hook Handler).
feel we need links to point to more info about the `eh_log_handler` and `eh_web_hook_handler`.

Also - I would put these in backticks.

2020-07-08 10:26 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +Tyk provides information and feedback in varoius ways:
so annoying the spell-checker ignores this editor

2020-07-08 10:31 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [OpenTracing](https://site-dev.tykbeta.com/docs/advanced-configuration/opentracing/) to allows services which have distributed tracing enabled for instrumentation to work seamless with Tyk gateway.
added commas (copied it from the doc. I also had to read this sentence a couple of times but it is correct)

2020-07-08 10:32 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- Request analytics with different ways of [datailed recording](https://site-dev.tykbeta.com/docs/analytics-and-reporting/useful-debug-modes/) on the request level and the key level. Data per data, i
@jlucktay told me, thanks

2020-07-08 10:33 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +There are currently two built-in event handlers: eh_log_handler (Log handler – mainly for debugging) and eh_web_hook_handler (Web Hook Handler).
I actually forgot to delete this line

2020-07-08 10:37 UTC, letzya commented
@asoorm if okay, can you please click resolve on the less trivial comments you made?

2020-07-08 11:30 UTC, asoorm commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Monitors and events](https://tyk.io/docs/basic-config-and-security/report-monitor-trigger-events/monitors/) - to actively monitor both users and organisation quotas and provides an easy way to not
Suggestion:

> to actively monitor both users and organisation quotas and provides an easy way to notify your stakeholders in case there's traffic abnormality pattern.

Active monitoring of both user & organisations. Provides simple means of notifying stakeholders in the case of traffic abnormalities.

2020-07-08 11:48 UTC, letzya commented
@marksou -  @asoorm reviewed, can you please merge?

2020-08-26 11:26 UTC, buger commented
@marksou lets fix links leading to staging env, and we can merge.

2020-08-26 11:40 UTC, marksou approved these changes

2020-08-26 11:41 UTC, merged