Customizing API Visibility for Dev Portal Catalog
TykTechnologies/tyk-docs-hugo pull request #1367
Opened 2020-07-24 14:49 UTC by nerdydread

Added details for how a user would dynamically show/hide API's on the developer portal.

2020-07-24 15:00 UTC, marksou approved these changes
👍

2020-07-24 18:00 UTC, sedkis requested changes
LGTM besides 1 comment - tested,  very easy to follow!  Thanks @nerdydread

2020-07-24 18:00 UTC, sedkis commented on tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
> +Please see the customised catalogue template ​​here​: https://gist.github.com/nerdydread/1c4f2c909e33591d7c63f805e8e3698d
Can we please host this somewhere official ?
Either hard-coded in the docs, as a collapsible block or somewhere else pleases

2020-07-27 14:53 UTC, sedkis approved these changes

2020-08-04 14:36 UTC, sedkis commented
@marksou  can we. merge please

2020-08-18 14:34 UTC, buger commented on tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
> +>>>>>>> fd0e9c9915af0453fcbb2f477232a68e632ded5a
I guess it is Github conflict?

2020-08-18 16:53 UTC, marksou commented on tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
> +>>>>>>> fd0e9c9915af0453fcbb2f477232a68e632ded5a
Sorted

2020-08-18 16:55 UTC, merged