Authorise endpoint API name clarification
TykTechnologies/tyk-docs-hugo pull request #1435
Opened 2020-09-15 10:22 UTC by joshblakeley

The Authorise client endpoint on the dashboard builds the URL to call the Gateway in the form: 

`config.Global().TykApi.Host + ":" + config.Global().TykApi.Port + "/" + apiID + "/tyk/oauth/authorize-client/"`

Where the APIID is read from the path of the dashboard endpoint. 

However the gateway API builds its path in the form:

`spec.Proxy.ListenPath + pathSeparator + "tyk/oauth/authorize-client{_:/?}"`

Meaning the dashboard should in fact pass the API name and not the ID, otherwise a 404 will be received.

2020-09-15 10:31 UTC, marksou approved these changes
👍

2020-09-15 11:04 UTC, letzya approved these changes

2020-09-15 11:05 UTC, letzya requested changes
@joshblakeley about `Unlike the other requests on this page, this should be the` - shouldn't it be api name everywhere? maybe if it's on the old cloud it needs id?

2021-03-01 11:18 UTC, buger commented
The way how it is currently described in the docs is the way how it should work. 
So I would rather treat it as a product bug. 
This API is actually using listen path as argument not the API_ID, but in context of our legacy cloud it is API ID (since internally listen path is API ID, and slug is using durign some weird nginx rewriting).

 This functionality can be considered broken on on-prem and Ara, it should use api_id instead. 

Create JIRA ticket https://tyktech.atlassian.net/browse/TT-1727

2021-03-01 11:18 UTC, closed without merging