Document Key and OAuth Client analytics endpoint
TykTechnologies/tyk-docs-hugo pull request #1460
Opened 2020-10-13 09:36 UTC by komalsukhani

Added docs of Key and OAuth client analytics endpoints.

2020-10-13 09:38 UTC, komalsukhani commented
@letzya These are the endpoints that use `KeyEndpoint` field you were asking about. Spotted on right time :)

2020-10-13 10:08 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/analytics.md
> +GET api/activity/keys/endpoint/7f3c3ca87376cabe/13/10/2020/14/10/2020 HTTP/1.1
@komalsukhani can we make it a bit clear? for example - what is `7f3c3ca87376cabe`? 
You can write the exact meaning of the api call in words - ```To get analytics of all APIs used by the key `7f3c3ca87376cabe` between October 13th 2020 and October 14th 2020, make the following call:```

2020-10-13 10:13 UTC, letzya requested changes

2020-10-13 10:13 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/analytics.md
> +| Type         | None            |
do we need these 3 empty lines?

2020-10-13 10:13 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/analytics.md
> +It returns analytics of the endpoints called using give OAuth Client ID.
rephrase "It returns analytics of the endpoints called using `" the given"` OAuth Client ID."

2020-10-13 10:13 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/analytics.md
> +#### Sample Request
again - write the example in words ``To get activity of all APIs used by OAuth client 27b35a9ed46e429eb2361e440cc4005c between October 13th 2020 and October 14th 2020, make the following call:```

2020-10-13 12:00 UTC, marksou commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/analytics.md
> +| Type         | None            |
I think this is just table formating, which is not pretty in markdown. The HTML should be fine.

2020-10-13 12:15 UTC, komalsukhani commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/analytics.md
> +| Type         | None            |
@letzya It's there on documentation of other Dashboard APIs [example](https://site-dev.tykbeta.com/docs/tyk-apis/tyk-dashboard-api/api-definitions/) 
For consistency I kept it as is.

2020-10-13 23:51 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/analytics.md
> +It returns analytics of the endpoints called using give OAuth Client ID.
@komalsukhani

2020-10-13 23:51 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/analytics.md
> +#### Sample Request
?

2020-10-13 23:53 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/analytics.md
> +GET api/activity/keys/endpoint/7f3c3ca87376cabe/13/10/2020/14/10/2020 HTTP/1.1
@komalsukhani why did you resolve this?

2020-10-14 14:43 UTC, letzya approved these changes

2021-02-08 11:10 UTC, merged