TT- 256 TT-959
TykTechnologies/tyk-docs-hugo pull request #1564
Opened 2021-02-22 21:21 UTC by gregdelhon

First version of the DCR docs. Needs more work and polishing.

2021-02-23 20:10 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +We will go into the specifics of how it works in the context of Tyk, but if you are interested in reading the full RFC, go to: http://www.rfc-editor.org/info/rfc7591
I would use this link instead. https://tools.ietf.org/html/rfc7591

2021-02-23 20:11 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +DCR is a way for you to integrate your developer portal with an external identity provider such as Keycloack, Gluu, Auth0, Okta etc...
Keycloack -> Keycloak

2021-02-23 20:16 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +The user won't see a difference, but when they register a client on the portal, Tyk will proxy that request to your identity provider(IdP) and you will be able to manage their access crendentials eit
The portal developer won't notice a difference. However when they create the app via Tyk Developer portal, Tyk will dynamically register that client with your authorization server. This means that it is the Authorization Server who will issue issue the Client ID and Client Secret for the app.

2021-02-23 20:19 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +This feature is optional and you can still have a great level of security only using tyk as your identity provider.
Swap `identity provider` for `authorization server`. Tyk is not an Identity Provider and has no concept of identities. An Identity Provider is a special type of OAuth2 authorization server.

2021-02-23 20:22 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +Other options include Azure, Amazon, Ping...
Spelling: Keycloak
I would put this list in Alphabetical Order, with Other being last?

2021-02-23 20:23 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +## Step 1: Create an API with JWT Authentification mode
Authentification -> Authentication

2021-02-23 20:26 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +In the "public key" section, make sure you enter your JWKS url. This should come from your identity provider.
<img width="218" alt="Screenshot 2021-02-23 at 20 24 10" src="https://user-images.githubusercontent.com/1465130/108903387-2b6ebb00-7615-11eb-8cc4-8f68ba55f5c3.png">

In the OpenID Connect Standard - It's called the `jwks_uri`. Not `jwks_url`.

This should come from your identity provider. You would typically find it in the `.well-known/openid-configuration` endpoint.

2021-02-23 20:39 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +* ``Password`` Your IdP (resource owner) password credentials as a grant type https://tools.ietf.org/html/rfc6749#section-1.3.3
Have each of these mechanisms been tested? 
It would be simpler to enable `Authorization Code`, `Client Credentials` and `Refresh Token` for MVP.

e.g. Why enable legacy Implicit & Password grants? Do we have a use-case for SAML 2 bearer assertion? How would that work? Do I still get a client_id and client_secret in the portal?

2021-02-23 20:43 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +* "Client secret basic" if the cleint uses HTTP basic
I feel like this is wrong. Here - the person configuring DCR - should be specifying which token endpoint auth methods they will permit. e.g. Do I want to allow public clients? Should I allow auth requests using client secret post or client secret basic?

The portal developer would then when creating their client would be restricted in terms of what kind of client they can create, and how they intend to authenticate with the API.

2021-02-23 20:46 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +There are more options for complex use cases, though you only need to pick Code or Token.
Can this be blank for client_credentials?

2021-02-23 20:47 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +This is the URL of your IDP. For example https://gluu.do.myproject
Why do I need this?

2021-02-23 20:49 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +Usually an extension of the Identity provider host URL
You will find this in the `.well-known/openid-configuration` under `registration_endpoint`.

It might be easier to just request the user provide their `.well-known/openid-configuration` document, and we introspect it to mine the fields we need?

2021-02-23 20:50 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +7. Initial ``registration access token`` (optional)
We could call it a `registration access token`. What is `Initial`?

2021-02-23 20:56 UTC, asoorm requested changes
Good start - a few comments & extra references: 

OpenID Connect Dynamic Client Registration 1.0 - for OpenID Connect relying parties. This spec should be used for almost all cases when we need to register apps with an OpenID Connect Identity Provider.

OAuth 2.0 Dynamic Client Registration Protocol - RFC 7591 - for simple OAuth 2.0 clients that don't need OpenID Connect features. e.g. mainly clients using the client credentials grant, but still need to be onboarded into an authorization server.

OAuth 2.0 Dynamic Client Registration Management Protocol - RFC 7592 - describes how to read, update or delete a client registration.

2021-02-24 09:17 UTC, gregdelhon commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +* ``Password`` Your IdP (resource owner) password credentials as a grant type https://tools.ietf.org/html/rfc6749#section-1.3.3
@matiasinsaurralde what do you think?

2021-02-24 09:22 UTC, gregdelhon commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +* "Client secret basic" if the cleint uses HTTP basic
Not sure I understand, why do you think this is wrong? Are you saying we shouldn't get the admin to set that and keep it to "none" as default?

2021-02-24 09:49 UTC, gregdelhon commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +There are more options for complex use cases, though you only need to pick Code or Token.
Good point, @ConsM did we make that field compulsory? I think we did but need to revert that and let users enable no entry.

2021-02-24 09:49 UTC, gregdelhon commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +This is the URL of your IDP. For example https://gluu.do.myproject
@matiasinsaurralde this one is probs for you

2021-02-24 09:56 UTC, gregdelhon commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +Usually an extension of the Identity provider host URL
Good suggestion, I am adding this to the backlog for when we move it to raava https://tyktech.atlassian.net/browse/TT-1696

2021-02-24 14:20 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +* "Client secret basic" if the cleint uses HTTP basic
The portal manager's role here is to decide or enforce what kind of clients & what auth mechanisms they wish to be enabled for the portal developer to choose from. So this should be a multi-select.

The portal developer knows whether they wish to create a public client or a confidential client.

---

So from the portal developer perspective, if there are multiple items checked - the portal developer should be able to create a public or confidential client - right from the developer portal. But if the `client secret post` or `client secret basic` are checked - then the portal developer should only be allowed to create a confidential client.

2021-02-24 14:31 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +# What is it?
Titles become anchor links

### What is it?

vs

### Dynamic Client Registration overview

2021-02-24 14:32 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +# Why should I use it?
can delete this title and leave it as a couple of paragraphs in the overview section.

2021-02-24 14:33 UTC, asoorm commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +# I have an identity provider, how can connect it?
### I have an identity provider, how can connect it? 

vs

### Enabling Dynamic Client Registration

2021-02-24 17:00 UTC, matiasinsaurralde commented on tyk-docs/content/tyk-developer-portal/dynamic-client-registration.md
> +* "Client secret basic" if the cleint uses HTTP basic
I don't think we can select multiple options, at least on the IDPs that we've tried, you can only pick one, so you select either `client_secret_post` or `client_secret_basic`, etc.

2021-05-04 20:03 UTC, marksou commented
@matiasinsaurralde is happy so I'm merging this as 3.2 being released

2021-05-04 20:03 UTC, merged