[TT-1869] Add link to Gateway API Page
TykTechnologies/tyk-docs-hugo pull request #1587
Opened 2021-03-17 10:06 UTC by marksou

2021-03-17 10:18 UTC, letzya requested changes

2021-03-17 10:18 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +The [Tyk Gateway API](/docs/tyk-gateway-api/) is the primary means for integrating your application with the Tyk API Gateway system. This
i'd add "REST" - `The Tyk-Gateway RESP APIs are the primary means...`

2021-03-17 10:18 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +In order to use the Gateway API, you'll need to set the `secret` parameter in your `tyk.conf` file.
"In order to use the Tyk getaway REST APIs,"

2021-03-17 11:25 UTC, marksou commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +The [Tyk Gateway API](/docs/tyk-gateway-api/) is the primary means for integrating your application with the Tyk API Gateway system. This
Updated

2021-03-17 11:25 UTC, marksou commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +In order to use the Gateway API, you'll need to set the `secret` parameter in your `tyk.conf` file.
Updated

2021-03-17 20:01 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +In order to use the Tyk Gateway REST API, you'll need to set the `secret` parameter in your `tyk.conf` file.
APIs

2021-03-17 20:01 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +The [Tyk Gateway REST API](/docs/tyk-gateway-api/) is the primary means for integrating your application with the Tyk API management platform. This
it's not a management platform

2021-03-22 10:46 UTC, marksou commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +The [Tyk Gateway REST API](/docs/tyk-gateway-api/) is the primary means for integrating your application with the Tyk API management platform. This
It's how we've been referring to it in the restructure. See last paragraph here - https://tyk.io/docs/apim/open-source/#tyk-gateway

2021-03-26 14:14 UTC, letzya requested changes
Sorry, couldn't see the changes

2021-03-26 14:14 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +The [Tyk Gateway API](/docs/tyk-gateway-api/) is the primary means for integrating your application with the Tyk API Gateway system. This
Why cant I see the update @marksou

2021-03-26 17:02 UTC, marksou commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +In order to use the Tyk Gateway REST API, you'll need to set the `secret` parameter in your `tyk.conf` file.
There is only one Gateway API?

2021-03-26 17:03 UTC, marksou commented
@letzya click on the second commit.

2021-03-29 18:33 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +In order to use the Tyk Gateway REST API, you'll need to set the `secret` parameter in your `tyk.conf` file.
/debug is another api

2021-03-29 18:41 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/gateway-api.md
> +The [Tyk Gateway REST API](/docs/tyk-gateway-api/) is the primary means for integrating your application with the Tyk API management platform. This
@marksou not sure I understand. can you add the quote here or just leave this as it's currently written in master and just add link to the swagger?

2021-04-06 13:08 UTC, letzya approved these changes

2021-04-06 13:10 UTC, merged