FIX : TT-1596 : Document new way of using headers
TykTechnologies/tyk-docs-hugo pull request #1594
Opened 2021-03-19 08:02 UTC by jay-deshmukh

- This PR makes a fix to document new way of using headers when debugging graphql apis with graphiql IDE on dashboard.

2021-03-19 09:49 UTC, marksou approved these changes

2021-03-22 15:05 UTC, letzya commented on tyk-docs/content/graphql/graphql-playground.md
> +  Debugging a GraphQL API might require additional headers to be passed to the requests while playing with the GraphiQL interface. (i.e. `Authorization` header in case of Authentication Token protect
@marksou can you please check the commas and full stops are placed correctly? thanks

2021-03-22 17:46 UTC, marksou commented on tyk-docs/content/graphql/graphql-playground.md
> +  Debugging a GraphQL API might require additional headers to be passed to the requests while playing with the GraphiQL interface. (i.e. `Authorization` header in case of Authentication Token protect
Done now.

2021-03-23 06:12 UTC, jay-deshmukh commented on tyk-docs/content/graphql/graphql-playground.md
> +  Debugging a GraphQL API might require additional headers to be passed to the requests while playing with the GraphiQL interface. (i.e. `Authorization` header in case of Authentication Token protect
Thanks @letzya and @marksou

2021-03-23 11:43 UTC, letzya commented
@marksou can we maybe add a screenshot of it?

2021-03-23 11:44 UTC, letzya requested changes
A screenshot can help

2021-03-30 11:08 UTC, merged