TT-2100 - SQL connection documentation and how to set it up
TykTechnologies/tyk-docs-hugo pull request #1623
Opened 2021-04-12 06:44 UTC by vaske

This PR brings on table SQL documentation and how to run local setup

2021-04-12 06:47 UTC, buger commented on tyk-docs/content/sql-configuration/configuration.md
> +go build -i && TYK_DB_CONFIGSTORAGE_TYPE="sqlite" TYK_DB_CONFIGSTORAGE_SQLDSN="/tmp/test.db"
Remove go build from here

2021-04-12 09:58 UTC, vaske commented on tyk-docs/content/sql-configuration/configuration.md
> +go build -i && TYK_DB_CONFIGSTORAGE_TYPE="sqlite" TYK_DB_CONFIGSTORAGE_SQLDSN="/tmp/test.db"
done ✅

2021-04-15 12:35 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +- `main` - Configuration storage (APIs, Policies, Users, User Groups, etc.)
Configuration -> Main

2021-04-15 12:40 UTC, furkansenharputlu requested changes
I think we should tell that old `mongo` configuration options are deprecated. Also we need to change all the configuration examples throughout the docs to new type of storage configuration to prevent new users to use old mongo configuration.

2021-04-15 12:40 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +- `logs` - Log storage (Log browser page) -
Log -> Logs

2021-04-15 12:40 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +By default Log storage and Analytics storage will use Configuration storage, if you not set them in config.
Log -> Logs

2021-04-15 12:40 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +Note that if legacy "mongo_url" in root config is set, it will use "legacy" mode, and will ignore `main` storage section.
"mongo_url" -> `mongo_url`

2021-04-19 21:34 UTC, furkansenharputlu requested changes

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +We have two provide two certificates to complete the X509 Client Authentication.
we have to..

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +* old configuration of Mongo DB was inside root element of tyk_analytics.conf file, recently it has moved to be like this
Mongo DB -> MongoDB

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "url"                       | TYK_STORAGE_MAIN_MONGO_URL      | string | "mongodb://{username}@{host}:{port}/{db}?authSource=$external&authMechanism=MONGODB-X509" |
should start with `TYK_DB_` and the others too

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "url"                       | TYK_STORAGE_MAIN_MONGO_URL      | string | "mongodb://{username}@{host}:{port}/{db}?authSource=$external&authMechanism=MONGODB-X509" |
there is not mongo url, instead we use `TYK_DB_STORAGE_MAIN_CONNECTIONSTRING`

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "pem_keyfile"           | TYK_STORAGE_MAIN_MONGO_SSL_PEMKeyfile      | string | "certificates/key.pem" |
_PEMKEYFILE

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "allow_invalid_hostnames" | TYK_STORAGE_MAIN_MONGO_SSL_AllowInvalidHostnames      | bool | true, false |
_ALLOWINVALIDHOSTNAMES

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "session_consistency"       | TYK_STORAGE_MAIN_MONGO_SSL_SessionConsistency      | string | "strong", "eventual", or "monotonic". default is "strong" |
should be capital `SESSIONCONSISTENCY`

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "batch_size"                | TYK_STORAGE_MAIN_MONGO_SSL_BatchSize      | int | Default "2000", min "100" |
should be capital

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +    "dsn": "user=root password=admin host=127.0.0.1 port=49691 sslmode=require"
dsn -> connection_string

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +TYK_DB_STORAGE_MAIN_DSN="user=root password=admin host=127.0.0.1 port=49691 sslmode=require"
TYK_DB_STORAGE_MAIN_CONNECTIONSTRING

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +    "dsn": "./test.db"
connection_string

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +    "dsn": "gorm:gorm@tcp(127.0.0.1:3306)/gorm?charset=utf8&parseTime=True&loc=Local"
connection_string

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +      "url": "mongodb://127.0.0.1:27017/schema_name",
no `url` here, instead `connection_string` in the same level with `type`

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/tyk-stack/tyk-manager/configuration/tyk-dashboard-configuration-options.md
> +                "url": "mongodb://tyk-mongo:27017/tyk_analytics",
move upper and rename as `connection_string`

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/tyk-stack/tyk-manager/configuration/tyk-dashboard-configuration-options.md
> +                "url": "mongodb://tyk-mongo:27017/tyk_analytics",
moving upper level and renaming to `connection_string`

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/tyk-stack/tyk-manager/configuration/tyk-dashboard-configuration-options.md
> +### mongo > ssl is a object inside Mongo where configuration settings for SSL should be included
..an object...

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/tyk-stack/tyk-manager/configuration/tyk-dashboard-configuration-options.md
> +**Note**
I think this formatting changes should not be in this PR because it makes the PR complex to review. Is there any chance you remove all in the PR? If you would like to add these refactors, you can send another PR after this

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/frequently-asked-questions/how-to-connect-to-documentdb.md
> +      "batch_size": 1
I don't know what should be the default value for `batch_size`

2021-04-19 21:34 UTC, furkansenharputlu commented on tyk-docs/content/frequently-asked-questions/how-to-connect-to-documentdb.md
> +      "batch_size": 1
See: https://github.com/TykTechnologies/tyk-docs/pull/1623/files#diff-777a075cd05d07f688dd5675236f657c5fbe997332ae4923861cfdab035349e7R87

2021-04-19 21:41 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +For SQLite you can omit DSN option, and it will use in-memory engine.
connection string

2021-04-19 21:41 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +       "dsn": "/tmp/test.db"
we should change this to `connection_string` in pump as well

2021-04-20 07:32 UTC, vaske commented on tyk-docs/content/tyk-stack/tyk-manager/configuration/tyk-dashboard-configuration-options.md
> +**Note**
I just removed empty space in such files, we should keep them polished not influent with not needed stuff

2021-04-20 07:34 UTC, vaske commented on tyk-docs/content/frequently-asked-questions/how-to-connect-to-documentdb.md
> +      "batch_size": 1
we can put min 100, it was set to 1 I just added changes not changes of values

2021-04-20 13:05 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "ca_file"               | TYK_DB_STORAGE_MAIN_MONGO_SSL_CAFile      | string | "certificates/ca.pem" |
CAFILE

2021-04-20 13:07 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "pem_keyfile"           | TYK_DB_STORAGE_MAIN_MONGO_SSL_PEMKEYFILE      | string | "certificates/key.pem" |
it is not `pem_keyfile`.  https://github.com/TykTechnologies/tyk-analytics/blob/78f8f9be02a06d37e396f4be5b2fc1fe53f94d9a/config/config.go#L200

2021-04-20 13:08 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "batch_size"                | TYK_DB_STORAGE_MAIN_MONGO_SSL_BATCHSIZE      | int | Default "2000", min "100" |
batchsize is not in ssl

2021-04-20 13:08 UTC, furkansenharputlu commented on tyk-docs/content/planning-for-production/mongodb-x509-client-authentication.md
> +| "session_consistency"       | TYK_DB_STORAGE_MAIN_MONGO_SSL_SESSIONCONSISTENCY      | string | "strong", "eventual", or "monotonic". default is "strong" |
SESSIONCONSISTENCY is not in ssl

2021-04-20 13:10 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +TYK_DB_MONGOURL=""
no need this

2021-04-20 13:15 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +## Logs
I think no need a separate section like this. It is confusing with Logs storage. We should mention this in line ~39

2021-04-20 13:16 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +## Logs
It can start like this:
`After you finish the storage configuration and start the dashboard you can check the logs:
....
`

2021-04-20 13:20 UTC, furkansenharputlu commented on tyk-docs/content/sql-configuration/configuration.md
> +      "batch_size": 1
2000 is the deafult value

2021-04-20 13:21 UTC, furkansenharputlu commented on tyk-docs/content/tyk-stack/tyk-manager/configuration/tyk-dashboard-configuration-options.md
> +### mongo > ssl > batch_size
not ssl

2021-04-20 13:22 UTC, furkansenharputlu commented on tyk-docs/content/frequently-asked-questions/how-to-connect-to-documentdb.md
> +      "batch_size": 100
default 2000

2021-04-25 18:22 UTC, lghiur approved these changes

2022-05-09 07:55 UTC, marksou commented
@vaske Can I ask you to have another look at this PR as I suspect we've covered this in the auto-sync config files for the GW and DB and the docs we did for v4.0

2022-05-09 08:21 UTC, vaske commented
@marksou I think you are right but have to ask @lghiur to double-check 🙏

2022-12-02 22:25 UTC, letzya commented
@vesko-tyk thanks for such an extensive pr but based on the messages about, can you please check if we can close this pr?

2023-01-10 10:01 UTC, letzya commented
@lghiur will own.

2023-01-11 12:02 UTC, letzya requested changes
Needs conflicts solving and re-review

2023-04-21 11:27 UTC, letzya commented
@lghiur is this planned to be sorted?

2023-07-10 17:38 UTC, letzya commented
closing for now.

2023-07-10 17:38 UTC, closed without merging