[TT-2524] Edit Dashboard section
TykTechnologies/tyk-docs-hugo pull request #1681
Opened 2021-05-25 09:46 UTC by marksou

2021-05-25 11:00 UTC, letzya commented
Can we add this as well

```
  "security": {
    "open_policy": {
      "enabled":true,
      "debug": true,
      "enable_api": true
    },
    "additional_permissions": {}
  },
```

2021-05-27 17:51 UTC, letzya requested changes

2021-05-27 17:51 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/additional-permissions.md
> +title: Additional Permissions API
@lghiur @marksou when you read it as outside it's not clear what  _"Additional Permissions"_ actually means. Do you think we can title it as "Additional Tyk Manager Permissions API"

2021-05-27 17:51 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/opa.md
> +title: Open Policy Agent API
I think adding "opa" is actually important.

2021-05-27 17:51 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/opa.md
> +This endpoint returns by defaul the initial set of OPA rules defined in your Tyk Dashboard, which are located in [schema/dashboard.rego](/docs/tyk-dashboard/opa-rules/) (accessible in Self-Managed in
typo defaul

2021-05-27 17:51 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-manager/open-policy-agent.md
> +1. From the **OPA Rules menu**. From the Dashboard Management menu, select OPA Rules. You can view and make any changes and select whether your OPA rules should be enabled or disabled.
"From" twice

2021-05-27 17:51 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-manager/open-policy-agent.md
> +OPA rules can only be accessed by admin role users in the Dashboard.
@marksou it should be Tyk manager isn't it?

2021-05-27 17:52 UTC, lghiur commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/opa.md
> +title: Open Policy Agent API
i think here it's described the acronym :) and not the API...that was the intent

2021-05-27 17:53 UTC, lghiur commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/additional-permissions.md
> +title: Additional Permissions API
where do we use Tyk Manager in other contexts? maybe Additional Tyk Dashboard user permissions API, not sure @buger ?

2021-05-27 17:54 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/opa.md
> +title: Open Policy Agent API
Good catch @lghiur !!!

2021-05-27 17:54 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/opa.md
> +title: Open Policy Agent API
so just revert this @marksou

2021-05-27 18:03 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-manager/open-policy-agent.md
> +1. From the **OPA Rules menu**. From the Dashboard Management menu, select OPA Rules. You can view and make any changes and select whether your OPA rules should be enabled or disabled.
"The advantage" shows up twice, sentence is messy

2021-05-28 08:01 UTC, marksou commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/opa.md
> +title: Open Policy Agent API
👍

2021-05-28 08:23 UTC, marksou commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/additional-permissions.md
> +title: Additional Permissions API
I'd be tempted to leave the title as it is, otherwise, it gets way too long. I added API to make it a bit more obvious. As it's listed under Dashboard API, it should be obvious why it's there

2021-05-28 09:14 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/opa.md
> +This endpoint returns by defaul the initial set of OPA rules defined in your Tyk Dashboard, which are located in [schema/dashboard.rego](/docs/tyk-dashboard/opa-rules/) (accessible in Self-Managed in
?

2021-08-04 11:11 UTC, lghiur approved these changes

2021-09-22 08:47 UTC, marksou commented on tyk-docs/content/tyk-stack/tyk-manager/open-policy-agent.md
> +OPA rules can only be accessed by admin role users in the Dashboard.
I don't think we've officially adopted that term yet. See https://tyk.io/gather-and-export-analytics/

2021-09-24 12:17 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-manager/open-policy-agent.md
> +* Control access for individual fields. For example, do not allow changing the API "active" status (e.g. deploy), unless you have a specific permission set (and make new permissions to be available t
@marksou what does this mean `(and make new permissions to be available to the Dashboard/API)`

2021-09-24 12:19 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/dashboard/create-user-groups.md
> +You can now create your own custom permissions using the [Additional Permissions API](/docs/tyk-dashboard-api/org/permissions/) or by updating the [`security.additional_permissions`](/docs/tyk-dashbo
we have the same text here `https://deploy-preview-1681--tyk-docs.netlify.app/docs/basic-config-and-security/security/dashboard/create-users/`

2021-10-20 21:50 UTC, letzya approved these changes

2021-10-21 07:13 UTC, merged

2021-10-21 07:14 UTC, marksou commented
/release to release-3.2

2021-10-21 07:15 UTC, marksou commented
/release to release-3.1