Update the doc with important consideratinos
TykTechnologies/tyk-docs-hugo pull request #1690
Opened 2021-06-04 14:28 UTC by letzya

2021-07-14 17:09 UTC, letzya commented
@marksou can you please merge?

2021-11-27 13:58 UTC, marksou commented
@letzya Can you approve please?

2022-05-09 15:21 UTC, craigtyk requested changes
small change suggested on line 11

2022-05-09 15:21 UTC, craigtyk commented on tyk-docs/content/shared/api-def-custom-analytics.md
> +- Since we are basically declaring headers' prefix as tags, Tyk, as expected from tags, will `also` add an aggregation point per tag in the aggregated analytics.
I'd remove "basically" and "as expected from tags" as unnecessary

2022-05-09 16:08 UTC, marksou commented on tyk-docs/content/shared/api-def-custom-analytics.md
> +- Since we are basically declaring headers' prefix as tags, Tyk, as expected from tags, will `also` add an aggregation point per tag in the aggregated analytics.
Have removed

2022-05-10 08:52 UTC, craigtyk approved these changes
lgtm, thanks

2022-05-10 08:55 UTC, merged

2022-05-10 08:55 UTC, marksou commented
/release to release-4

2022-05-10 08:57 UTC, marksou commented
/release to release-3.2

2022-05-10 09:21 UTC, marksou commented
/release to release-3.1

2022-05-10 09:24 UTC, marksou commented
/release to release-3-lts