[TD-361] First draft of Helm Chart changes
TykTechnologies/tyk-docs-hugo pull request #1705
Opened 2021-07-01 15:33 UTC by marksou

I've done the following:

- Created helm chart pages within the OSS and Self-Managed section.
- Added content as in the Helm Repo
- Added appropriate sections within the existing TIB, MDCB, and Tyk Cloud Hybrid Gateway pages
- Moved the Istio page under Kubernetes

2021-07-02 13:22 UTC, craigtyk requested changes
Updated structure is good and added pre-reqs help clarify what's needed. Some minor corrections requested but OK from my side to publish when complete.

2021-07-02 13:22 UTC, craigtyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/setup-master-data-centre.md
> +If you are deploying the Master Data Centre in an MDCB deployment then you can set the `mdcb.enabled` option in your `vuales.yaml` to true to add the MDCB component to your cluster.
correct to `values.yaml`

2021-07-02 13:22 UTC, craigtyk commented on tyk-docs/content/tyk-on-prem/installation/with-kubernetes/with-kubernetes.md
> +This is the preferred (and easiest) way to install Tyk Pro on Kubernetes. It will install Tyk in your Kubernetess cluster, where you can then add APIs to manage via either our Tyk Kubernetes Operator
Remove extra 's' at the end of the 2nd Kubernetes

2021-07-02 13:22 UTC, craigtyk commented on tyk-docs/content/tyk-on-prem/installation/with-kubernetes/with-helm-chart.md
> +## Introduction
Do we need further Introduction text beyond what's explained on parent page? @letzya @sedkis 
If not, we can remove Introduction header

2021-07-02 13:22 UTC, craigtyk commented on tyk-docs/content/tyk-on-prem/installation/with-kubernetes/with-helm-chart.md
> +If you are evaluating Tyk on Kubernetes, [contact us](https://tyk.io/about/contact/) to obtain an temporary licence.
Correct an -> a

2021-07-02 13:22 UTC, craigtyk commented on tyk-docs/content/tyk-on-prem/installation/with-kubernetes/with-helm-chart.md
> +## Prerequisites
Pleased to see clear prerequisites on each page. Thanks

2021-07-02 13:22 UTC, craigtyk commented on tyk-docs/content/tyk-on-prem/installation/with-kubernetes/with-helm-chart.md
> +## Other Tyk Components
Agree with moving the additional components details under their respective sections under Tyk Stack to minimise duplication.

2021-07-02 13:22 UTC, craigtyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +## Introduction
Additional intro needed beyond parent page summary? If not, header can be removed

2021-07-09 11:22 UTC, marksou commented on tyk-docs/content/tyk-on-prem/installation/with-kubernetes/with-kubernetes.md
> +This is the preferred (and easiest) way to install Tyk Pro on Kubernetes. It will install Tyk in your Kubernetess cluster, where you can then add APIs to manage via either our Tyk Kubernetes Operator
Done

2021-07-13 22:46 UTC, letzya commented on tyk-docs/content/tyk-on-prem/installation/kubernetes/kubernetes.md
> +We will explain in detail the installation using [Helm Charts]({{< ref "/content/tyk-on-prem/installation/kubernetes/helm-chart.md" >}})
This link doesnt work

2021-07-13 22:57 UTC, letzya commented on tyk-docs/content/tyk-on-prem/installation/kubernetes/helm-chart.md
> +This is the preferred (and easiest) way to install Tyk Self-Managed Pro on Kubernetes.
Self-Managed Pro?

2021-07-13 22:59 UTC, letzya commented on tyk-docs/content/tyk-on-prem/installation/kubernetes/helm-chart.md
> +kubectl apply -f deploy/dependencies/redis.yaml -n tyk
this is the old doc @marksou

2021-07-14 06:08 UTC, merged

2021-07-14 06:09 UTC, marksou commented
/release to release-3.2

2021-07-14 06:10 UTC, marksou commented
/release to release-3.1

2021-07-14 06:10 UTC, marksou commented
/release to release-3-lts