Helm katacoda update
TykTechnologies/tyk-docs-hugo pull request #1751
Opened 2021-09-08 10:47 UTC by craigtyk

2021-09-08 11:10 UTC, marksou approved these changes
LGTM

2021-09-08 11:55 UTC, letzya requested changes

2021-09-08 11:55 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +You can find full configuration details in the steps below.
This row is not showing up properly 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/3155222/132502951-ef3ad8ed-734b-4a86-88de-175b8acdbca2.png">

2021-09-08 11:55 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +### Step 1 - Add Tyk official Helm repo
this title starts straight after the interactive tutorial. Maybe, for clarity, we can add another level `### Step by step installation guild`  and then put the title of each step with heading level 4, `####` so if someone breeze through the page he should understand its structure.

2021-09-08 11:55 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +    data-katacoda-id="tyk-education/tyk-install-oss-k8s-helm"
will be good to change to bitnami Redis in our tutorial, whenever it's possible

2021-09-08 12:56 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +<div id="tyk-install-oss-k8s-helm"
is there a setting for `open in a separate window`?

2021-09-08 13:19 UTC, craigtyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +<div id="tyk-install-oss-k8s-helm"
Not for that specific session, the workaround would be to add a button that opened a new session in another window.

2021-09-08 13:20 UTC, craigtyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +You can find full configuration details in the steps below.
Good catch, this wasn't visible on my side. Will update

2021-09-08 13:26 UTC, craigtyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +### Step 1 - Add Tyk official Helm repo
aim was to have the tutorial under the installation header as a pre-step to follow along. If you think it's clearer for users, we can move this under it's own lv 2 header and keep only the steps under Installation

2021-09-08 15:20 UTC, craigtyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +You can find full configuration details in the steps below.
done

2021-09-08 15:20 UTC, craigtyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +### Step 1 - Add Tyk official Helm repo
done

2021-09-08 15:20 UTC, craigtyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +    data-katacoda-id="tyk-education/tyk-install-oss-k8s-helm"
agreed. noted to backlog for next version

2021-09-08 15:21 UTC, craigtyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +<div id="tyk-install-oss-k8s-helm"
impacts google analytics for the tutorial. will publish without for now but added to backlog for next update

2021-09-10 12:28 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-helm-chart.md
> +<div id="tyk-install-oss-k8s-helm"
thanks

2021-09-10 13:12 UTC, letzya approved these changes

2021-09-10 17:33 UTC, merged

2021-09-10 17:34 UTC, marksou commented
/release to release-3.2