Add SSE Proxy page
TykTechnologies/tyk-docs-hugo pull request #1766
Opened 2021-09-28 12:49 UTC by marksou

As per @rewsmith doc

2021-09-29 08:05 UTC, rewsmith approved these changes

2021-09-30 13:13 UTC, letzya requested changes

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +Tyk Gateway supports SSE proxying over HTTP, enabling a client to receive a stream of updates from a server over a long running HTTP connection.
@marksou I'd add a link to wiki on SSE

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +### Prerequisites
@marksou isn't it "Setup"?

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +- Enable SSE support on the Gateway by setting `http_server_options.enable_websockets` to true in your Gateway config file.
Suggest:
Enable SSE support on the Gateway: Set`http_server_options.enable_websockets` to true in Tyk Gateway config file.

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +- Set `http_server_options.read_timeout` and `http_server_options.write_timeout` to appropriately high values to prevent the connection between the User and the Gateway from being closed prematurely.
@rewsmith, what do you think about this:

To keep the _api consumer<-->gateway_ connection open, set `http_server_options.read_timeout` and `http_server_options.write_timeout` to appropriately high values (it's in milliseconds). By way of example, you could try setting both to `2000`, but this is for you to determine in your environment.

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* An SSE server.  For this example we will use [this server](https://github.com/kljensen/golang-html5-sse-example)
Instead of "this server" can we give it its real name? maybe `we will use the [golang-html5-sse-example]`

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* Ensure the Gateway configuration options detailed in the prerequisites have been set.
`Config fields per [setup above](./advanced-configuration/sse-proxy/)` 

(no passive voice)

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +    * Now set the `target_url` to be the example SSE server: `<host>:8000`, e.g. `http://host.docker.internal:8000`
suggest:

Set the `target_url` to the SSE server hostname and port, `<host>:8000` e.g. `http://host.docker.internal:8000`.

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* Ensure the Gateway configuration options detailed in the prerequisites have been set.
Suggest changing to numbers instead of bullet points

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +    * Hit save, and once the Gateway finishes reloading we can test the solution
Hit save is only if you are using the dashboard.
Suggest: `wait for the Gateway to reload the API before testing it`

2021-09-30 13:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* From the command line we can consume the service via tyk gateway using `curl`. Simply type `curl http://localhost:8080/sse/events/` and we should see a stream of updates from the server, similar to
Suggest:
To test the protected SSE service via the API in the Tyk Gateway run `curl http://localhost:8080/sse/events/` and you will see a stream of updates from the server. In this example, this is the output you should expect to see:

2021-10-01 12:17 UTC, rewsmith commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +- Set `http_server_options.read_timeout` and `http_server_options.write_timeout` to appropriately high values to prevent the connection between the User and the Gateway from being closed prematurely.
Agree, more accurate to use `api consumer` than `User`.  I would suggest a slight rewording though:

To maintain an open connection between the api consumer and gateway, set `http_server_options.read_timeout` and `http_server_options.write_timeout` to appropriately high values (in milliseconds). By way of example, you could try setting both to `2000`, but this is for you to determine in your environment.

2022-05-10 11:19 UTC, marksou commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +Tyk Gateway supports SSE proxying over HTTP, enabling a client to receive a stream of updates from a server over a long running HTTP connection.
Apart from the HTML spec, there's no definitive wiki on SSE, so probably not wise to link to anything.

2022-05-10 11:22 UTC, marksou commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +### Prerequisites
Changed

2022-05-10 11:23 UTC, marksou commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +- Set `http_server_options.read_timeout` and `http_server_options.write_timeout` to appropriately high values to prevent the connection between the User and the Gateway from being closed prematurely.
Changed

2022-05-10 11:28 UTC, marksou commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +- Enable SSE support on the Gateway by setting `http_server_options.enable_websockets` to true in your Gateway config file.
Done

2022-05-10 11:31 UTC, marksou commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* An SSE server.  For this example we will use [this server](https://github.com/kljensen/golang-html5-sse-example)
Done

2022-05-10 11:31 UTC, marksou commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* Ensure the Gateway configuration options detailed in the prerequisites have been set.
Done

2022-05-10 11:32 UTC, marksou commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +    * Hit save, and once the Gateway finishes reloading we can test the solution
Done

2022-05-10 11:33 UTC, marksou commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* From the command line we can consume the service via tyk gateway using `curl`. Simply type `curl http://localhost:8080/sse/events/` and we should see a stream of updates from the server, similar to
Done

2022-05-10 11:34 UTC, marksou commented
@rewsmith @letzya can you both please review again?

2022-05-11 13:51 UTC, rewsmith approved these changes

2022-12-06 09:20 UTC, rewsmith approved these changes
LGTM

2022-12-08 17:32 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* Ensure the Gateway configuration options detailed in the prerequisites are set.
@rewsmith what are the prereq?

2022-12-08 17:49 UTC, rewsmith commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* Ensure the Gateway configuration options detailed in the prerequisites are set.
The prereqs are detailed under Setup

2022-12-08 17:51 UTC, rewsmith commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* Ensure the Gateway configuration options detailed in the prerequisites are set.
I suppose to be clearer we could say `Ensure the Gateway configuration options detailed under Setup are set`

2022-12-08 17:53 UTC, letzya commented on tyk-docs/content/advanced-configuration/sse-proxy.md
> +* Ensure the Gateway configuration options detailed in the prerequisites are set.
```suggestion
* Ensure the Gateway configurations detailed in the Setup section are set.
```

2022-12-08 17:54 UTC, letzya approved these changes

2022-12-08 17:55 UTC, rewsmith approved these changes

2022-12-08 18:02 UTC, merged