[TT-3361] Deprecating the enable_health_checks option
TykTechnologies/tyk-docs-hugo pull request #1775
Opened 2021-10-05 11:41 UTC by fletcherjy

The enable_health_checks is deprecated so this PR is to update the documentation.

2021-10-05 14:04 UTC, buger commented on tyk-docs/content/planning-for-production/planning-for-production.md
> +In order to keep real-time health-check data and make it available to the Health-check API, Tyk needs to record information for every request, in a rolling window - this is an expensive operation and
I would put WAY more emphasis on it. 

Literally: Ensure that this option disabled.

2021-10-05 15:06 UTC, buger approved these changes

2021-10-05 15:06 UTC, buger commented on tyk-docs/content/shared/gateway-config.md
> +Deprecated. Setting this value to `true` will enable the health-check endpoint on /Tyk/health.
Lets wrap it to *bold*

2022-05-11 07:26 UTC, marksou commented on tyk-docs/content/shared/gateway-config.md
> +Deprecated. Setting this value to `true` will enable the health-check endpoint on /Tyk/health.
@buger Should this be done in the Tyk repo version now? I'll raise a PR there.

2022-05-11 07:40 UTC, marksou commented on tyk-docs/content/shared/gateway-config.md
> +Deprecated. Setting this value to `true` will enable the health-check endpoint on /Tyk/health.
@buger https://github.com/TykTechnologies/tyk/pull/4038

2023-01-11 17:40 UTC, zalbiraw requested changes

2023-01-11 17:40 UTC, zalbiraw commented on tyk-docs/content/planning-for-production/planning-for-production.md
> +In order to keep real-time health-check data and make it available to the Health-check API, Tyk needs to record information for every request, in a rolling window - this is an expensive operation and
I am confused. We discuss why we need it and we also discuss that its expensive. Then we say we are deprecating it? What happened to the health checks?

2023-01-11 19:15 UTC, letzya commented
@zalbiraw it is not deprecated in the code.

2023-03-13 21:07 UTC, closed without merging