Pump auto docs
TykTechnologies/tyk-docs-hugo pull request #1801
Opened 2021-10-29 18:59 UTC by zalbiraw

2021-10-29 18:59 UTC, zalbiraw commented
WIP

2021-11-08 20:18 UTC, sedkis requested changes

2021-11-08 20:18 UTC, sedkis commented on tyk-docs/content/shared/pump-config.md
> +### analytics_storage_config
I don't think these sub fields are documented, are they?

2021-11-09 19:32 UTC, zalbiraw commented on tyk-docs/content/shared/pump-config.md
> +### analytics_storage_config
Are you saying they should not be documented?

2021-11-10 15:55 UTC, sedkis approved these changes
LGTM

2021-11-17 22:16 UTC, merged

2021-11-17 22:16 UTC, marksou commented
/release to release-3.2

2021-11-18 15:39 UTC, marksou commented
/release to release-3.2

2022-01-26 09:53 UTC, buger commented
@marksou note that merge to 3.2 brought some SQL changes to dashboard too