MDCB update documentation {WIP Do not merge}
TykTechnologies/tyk-docs-hugo pull request #1815
Opened 2021-11-23 19:19 UTC by sredxny

2021-11-23 22:19 UTC, sredxny commented
@gregdelhon please take a look

2021-11-24 08:58 UTC, gregdelhon reviewed
Nice, just some minor changes.

2021-11-24 08:58 UTC, gregdelhon commented on tyk-docs/content/shared/mdcb-config.md
> +To specify the maximum number of groups that can be synced at the same time without affecting the operation of MDCB. 1000 by default. It's recommendable to modify this value only if you need more org
The defa

2021-11-24 08:58 UTC, gregdelhon commented on tyk-docs/content/shared/mdcb-config.md
> +To specify the maximum number of groups that can be synced at the same time without affecting the operation of MDCB. 1000 by default. It's recommendable to modify this value only if you need more org
The default value is 1000. We recommend keeping this value or increasing it if you need more concurrent org syncing.

2021-11-24 08:58 UTC, gregdelhon commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +Since MDCB v1.9.0 you can enable the full synchronization of api keys, certificates and oauth2 clients in advance, this means that it will synchronize all the resources when a new group of worker nod
From MDCB v1.9.0 you can enable the synchronisation of: 
- API Keys
- Certificates
- OAuth2.0 Clients

This synchronisation is done whenever a new group of worker is connected, making the nodes less dependant on the MDCB layer. 

It is recommended to use this feature with Tyk v4.1 to maintain data consistency across the datacenters. For more information about how to configure this feature refer to [the mdcb keys synchronizer configuration options](/docs/tyk-multi-data-centre/mdcb-configuration-options#sync_worker_config)

2021-11-24 12:04 UTC, gregdelhon approved these changes
Thanks for the update Mark - good to go IMO

2021-11-26 12:13 UTC, marksou commented
@gregdelhon do we need to release this with 4.0, or wait until 4.1?

2021-11-29 20:13 UTC, sredxny commented
@marksou this should be release with 4.1

2021-12-08 15:11 UTC, gregdelhon approved these changes

2022-05-16 15:02 UTC, marksou commented
@sredxny @andyo-tyk This needs reviewing again for adding any SQL support config options.

2022-05-16 22:50 UTC, sredxny commented
@tbuchaillot can you help please with the SQL documentation?

I think we need to:
- In some page mention that we support SQL in MDCB and a basic example on how to set it up.
- In the configuration options, put comments over each config option related to SQL and trigger the automated job that generates that file (we can have a meeting and I will show you how)

2022-05-17 17:49 UTC, sredxny commented
On Hold until gateway 4.1.0 is released. The funcitonality documented in this PR depends on that gw version.

2022-08-15 16:27 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +### MDCB Keys Synchronizer
This should be Synchroniser, not Synchroniser

2022-08-15 16:27 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +From MDCB v1.9.0 you can enable the synchronisation of:
MDCB v2.0.0, not MDCB v1.9.0

2022-08-15 16:27 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +This synchronisation is performed whenever a new group of worker is connected, making the nodes less dependant on the MDCB layer. For more information about how to configure this feature, see [the md
synchroniser, not synchronizer
workers, not worker

2022-08-15 16:27 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
>  1.  A Tyk Gateway instance(s) specially configured as slaves
1. One or more Tyk Gateways configured as workers

2022-08-15 16:27 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +The configuration of the synchronisation worker
Configuration of the MDCB Synchroniser functionality introduced in MDCB v2.0.0

2022-08-15 16:27 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +Enable the synchronisation worker
Enable the MDCB Synchroniser

2022-08-15 16:27 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +The maximum amount of keys that we can fetch per batch. Default value: 1000 keys per batch.
number, not amount

2022-08-15 16:27 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +To specify the maximum number of groups that can be synced at the same time without affecting the operation of MDCB. It is set to 1000 by default. We recommend only modifying this value if you requir
Change "To specify" for "Specifies" (to match previous lines)

2022-08-26 23:46 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +This synchronisation is performed whenever a new group of worker is connected, making the nodes less dependant on the MDCB layer. For more information about how to configure this feature, see [the md
done

2022-08-26 23:46 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +From MDCB v1.9.0 you can enable the synchronisation of:
done

2022-08-26 23:46 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +### MDCB Keys Synchronizer
done

2022-09-07 11:12 UTC, andyo-tyk requested changes

2022-09-07 11:12 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +1.  One or more Tyk Gateways instance(s) specially configured as slaves
This should be singular: "Gateway" not "Gateways" and please drop the word "specially"

2022-09-07 11:12 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +This synchronisation is performed whenever a new group of worker is connected, making the nodes less dependant on the MDCB layer. For more information about how to configure this feature, see [the md
Can we please capitalise MDCB in the link?
It should be "a new group of workers" not "a new group of worker"

2022-09-07 11:12 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
>  A Slave Data Centre consists of the following configuration:
Can we take this opportunity to replace the word Slave with Worker throughout this page (and replace Master with Controller)?

2022-09-07 11:12 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +Set to true to disable the Mongo storages default index creation. More detailed behaviour explained at https://tyk.io/docs/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config/#omitting-indexes.
Please replace:
Set to true to disable the Mongo storages default index creation. More detailed behaviour explained at
with
Set to true to disable default index creation in the Mongo storage. For more detail, please see:

2022-09-07 11:12 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +Allows the worker to synchronize hashed API keys. Set this to true if `hash_keys` is true in dashboard and gateway configuration.
Please replace "synchronize" with "synchronise"

2022-09-07 11:12 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +Specifies the maximum number of groups that can be synced at the same time without affecting the operation of MDCB. 1000 by default. It's recommendable to modify this value only if you need more org
Please change to this, to match the code comment:
Specifies the maximum number of Groups (worker GW clusters) that can be synchronised by MDCB at the same time. Increasing this value can affect the operation of MDCB so it is recommended that you only modify this value if you need to synchronise a higher number of datacenters. Default value: 1000.

2022-09-07 11:12 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +Specifies the time to wait before start syncing all the synchronization. It's especially useful to let the edge nodes synchronize APIs and Policies first before sync the other resources. Defaults to
Please change to this, to match the code comment:
Specifies the time (in seconds) that MDCB should wait before starting to synchronise workers with the controller. This is to allow the worker nodes to load APIs and policies from local Redis before synchronising the other resources. Default value: 2 seconds.

2022-09-07 11:12 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +Specifies a cooldown time between batches in seconds. 0 / disabled by default.
Please change to this:
Specifies a cooldown time (in seconds) that MDCB will wait between synchronising batches of resources to the workers. Default value: 0 (disabled).

2022-09-07 16:32 UTC, sredxny commented
@buger here we also replaced the terminology master by controller and slave by worker. This change implied even changes in the url's, please advice if there is any risk by doing this.

2022-09-08 08:00 UTC, andyo-tyk requested changes
That's great, thanks - just a couple of notes about terminology for RPC, which I believe is server-client, not controller-worker.

2022-09-08 08:00 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/setup-slave-data-centres.md
> +Lastly, we add the sections that enforce the RPC Worker mechanism:
This one perhaps should be "client" rather than "worker", as it's talking about RPC?

2022-09-08 08:00 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +3.  Local cache is checked for token, if it doesn't exist, attempt to copy token from RPC controller node (MDCB)
Again, this is RPC - I'm not sure that they are called controller-worker, think it's server-client?

2022-09-08 14:14 UTC, sredxny commented
I'll put this on-hold. Create a ticket and add it to the nearest sprint

2022-09-08 19:26 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +3.  Local cache is checked for token, if it doesn't exist, attempt to copy token from RPC controller node (MDCB)
then lets put this as:

`Local cache is checked for token, if it doesn't exist, attempt to copy token from MDCB`

2022-09-08 19:27 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/setup-slave-data-centres.md
> +Lastly, we add the sections that enforce the RPC Worker mechanism:
This is talking how to configure the slave gateway. Not the RPC connection as itself

2022-09-09 08:18 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +3.  Local cache is checked for token, if it doesn't exist, attempt to copy token from RPC controller node (MDCB)
Yes, that'd be much better.

2022-09-09 08:18 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/setup-slave-data-centres.md
> +Lastly, we add the sections that enforce the RPC Worker mechanism:
In that case, we should just remove "RPC".

2022-09-09 08:21 UTC, andyo-tyk commented
If we can just remove the two mentions of RPC as discussed above, then this is good to go.

2022-09-12 21:18 UTC, sredxny commented
@andyo-tyk requested changes are done

2022-09-13 05:56 UTC, andyo-tyk approved these changes
Thanks - that's much clearer now.

2022-09-13 08:56 UTC, merged

2022-09-13 08:57 UTC, marksou commented
/release to release-4.1