MDCB SQL storage
TykTechnologies/tyk-docs-hugo pull request #1898
Opened 2022-05-17 19:35 UTC by tbuchaillot

Adding a note in `Setup Master Data Centre` for SQL storage configuration.

The configuration options will be handled from code in another PR.

2022-05-18 10:09 UTC, marksou approved these changes
LGTM

2022-05-18 17:46 UTC, sredxny commented
Updated the config options for MDCB. I removed any reference to the synchronizer, as this feature will be published once Tyk v4.1 is released

2022-05-18 17:47 UTC, sredxny approved these changes
lgtm

2022-05-18 17:48 UTC, sredxny commented
@marksou I think this is ready to be published. Let us know if you need anything else. This PR complements the released of TIB v2.0 done this week

2022-05-18 17:48 UTC, sredxny commented
@andyo-tyk take a look please

2022-05-19 13:56 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
>  EnableKeyLogging prints the unhashed keys without obfuscate them in the logs
Please change this to:
EnableKeyLogging prints the unhashed keys (without obfuscating them) to the logs

2022-05-19 13:57 UTC, andyo-tyk requested changes
Please improve this wording, thanks.

2022-05-19 14:00 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +This is used to configure the conenction string for the storage.
Typo: please correct to "connection"

2022-05-19 14:03 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +auto configure based on currently MySQL version
Need to capitalise the first word, and I think there's also a typo. Perhaps should be:
Auto configure based on current MySQL version

....but auto configure what?

2022-05-19 14:04 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +drop & create when rename index, rename index not supported before MySQL 5.7, MariaDB
This needs to be capitalised, but is also not clear (to me).

2022-05-19 14:05 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +disable datetime precision, which not supported before MySQL 5.6
Needs to be capitalised, but also some rewording suggested:

Disable datetime precision; this is required for databases prior to MySQL 5.6 (which do not support datetime precision)

2022-05-19 14:06 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +disables implicit prepared statement usage
First word needs to be capitalised

2022-05-19 14:07 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +default size for string fields. By default set to: 256
Perhaps reword to something like this:

Set a default size for string fields; if this is not set then it will default to 256 characters.

2022-05-19 14:09 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +`change` when rename column, rename column not supported before MySQL 8, MariaDB
Again, this isn't completely clear what it does - is it just provided for users trying to SQL versions prior to MySQL8 and MariaDB?

2022-05-19 14:12 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
>  Sets the batch size for mongo results.
Mongo should be capitalised

2022-05-19 14:13 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
>  set to true if you don't want to store selective analytics
First word needs to be capitalised

2022-05-19 14:14 UTC, sredxny commented on tyk-docs/content/shared/mdcb-config.md
> +This is used to configure the conenction string for the storage.
@andyo-tyk in database terminology string connection is a very common word, and people configuring connection to databases know what it is

2022-05-19 14:14 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
>  Set to true to don't store aggregate analytics
So that it matches the previous feature, reword to:

"Set to true if you don't want to store aggregate analytics."

2022-05-19 14:16 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
>  Enable to generate aggregated per minute. By default it will generate aggregate data per hour. If this option is enabled, aggregate data will be generated per minute.
Perhaps simplify this to:

"Set this to true to aggregate the analytics per minute; if set to false then data will be aggregated per hour."

2022-05-19 14:20 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +if set to true then it will not store analytics for tags having prefix specified in the list. **Note**: Prefix “key-” is added in the list by default. This tag is added by gateway for keys.
The first word needs to be capitalised but perhaps reword this to:

"Use this field to define a list of tags for which you do not want to store analytics; any analytics that are generated and tagged by the gateway with a prefix in this list will be discarded.
Note that the prefix "key-" is automatically included in this list and is used by the gateway for keys."

2022-05-19 14:23 UTC, sredxny commented
@andyo-tyk I will make the changes. It requires changes in tyk-sink repo and then regenerate again the documentation.

2022-05-19 14:25 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
>   If number of tags in a document grows beyond `threshold_len_tag_list`, pump will throw a warning, it works for mongo aggregate pump. The warning will print top 5 common tag prefix. Default value is
Does this ONLY work for the Mongo Aggregate pump?
Is 'threshold_len_tag_list' the same as TYK_MDCB_THRESHOLDLENTAGLIST?

If both of these are "yes" perhaps reword to:
"When using the Mongo Aggregate Pump, configure this value for the Pump to throw a warning if the number of tags in a document grows beyond this limit. The warning will print top 5 common tag prefix. If this is not configured, a default value of 1000 will be used. To disable alerts set it to -1."

2022-05-19 14:26 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
>  If set, redis sentinel will authenticate using this password.
Capitalise Redis

2022-05-19 14:26 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
>  If set, a redis connection will be established with this user. If not set then it will defaults to the default redis user
Capitalise Redis

2022-05-19 14:28 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +### sync_worker_config
If this section relates to the synchroniser, I think we need to remove it until Tyk 4.1 is released?

2022-05-19 14:28 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +The maximum amount of keys that we can fetch per batch. Default value: 1000 keys per batch.
Should be "maximum number" not "maximum amount"

2022-05-19 14:30 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +To specify the maximum number of groups that can be synced at the same time without affecting the operation of MDCB. 1000 by default. It's recommendable to modify this value only if you need more org
Reword to:

"Specify the maximum number of groups that can be synced at the same time without affecting the operation of MDCB. 1000 by default. We recommend that you only modify this value if you need more org syncing at the same time."

2022-05-19 14:37 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +Specifies the time to wait before start syncing all the synchronization. It's especially useful to let the edge nodes synchronize APIs and Policies first before sync the other resources. Defaults to
Is "edge node" a "worker gateway"? For consistency in this document we should use "worker".
Is this option used to hold off the sync of resources other than APIs and Policies? So it's used to ensure that APIs and Policies are fully synched first? Why would we need to use this, does it not synchronise resources sequentially?

Perhaps reword to:

"The worker gateways synchronize APIs and Policies before other resources. Use this option to specify the time the worker should wait before starting the synchronization of those other resources to ensure that the critical sync (APIs and policies) has completed. Defaults to 2 seconds."

2022-05-19 14:40 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +This is used to configure the conenction string for the storage.
OK, cool. Just the typo then, please. :-)

Is it obvious how TYK_MDCB_ANALYTICSCONFIG_CONNECTIONSTRING works with TYK_MDCB_ANALYTICSCONFIG_MONGOURL, both of which claim to define the connection string?

2022-05-20 15:06 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
>  EnableKeyLogging prints the unhashed keys without obfuscate them in the logs
Agreed to leave this and other wording as it is because we intend to upgrade all the MDCB documentation in one go.

2022-05-20 15:07 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +This is used to configure the conenction string for the storage.
Agreed to leave this and other wording as it is because we intend to upgrade all the MDCB documentation in one go.

2022-05-20 15:08 UTC, andyo-tyk approved these changes

2022-05-20 15:17 UTC, sredxny commented
@marksou we are ready to go! Please let us know when its published ;)

2022-05-23 07:57 UTC, merged

2022-05-23 07:57 UTC, marksou commented
/release to release-4

2022-05-23 07:58 UTC, marksou commented
@sredxny @andyo-tyk now merged into v4 docs