Adding doc section for Mongo pumps indexes behavior
TykTechnologies/tyk-docs-hugo pull request #1899
Opened 2022-05-18 12:33 UTC by tbuchaillot

2022-05-18 13:01 UTC, marksou approved these changes
LGTM

2022-05-24 16:05 UTC, andyo-tyk requested changes
Proposed new wording; one question on behaviour for non-Mongo Pumps

2022-05-24 16:05 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +From Pump 1.5.2+, the Mongo Pumps indexes default behaviour is changed and the new configuration option `omit_index_creation` is available. This apply for `Mongo Pump`,`Mongo Aggregate Pump` and `Mon
From Pump 1.5.2+, a new configuration option `omit_index_creation` is available to allow control over the Pump's behavious with indexes.

This option (which can be set to 'true' or 'false') is applicable to the following Pumps: `Mongo Pump`,`Mongo Aggregate Pump` and `Mongo Selective Pump`; for any other Pump, the option does not exist.

2022-05-24 16:05 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +The behaviour now is:
The behaviour now depends upon the value of 'omit_index_creation' and the Pump in use, as follows:

2022-05-24 16:05 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +- If `omit_index_creation` is set to `true`, tyk-pump is not going to create any index for mongo pumps.
If `omit_index_creation` is set to `true`, tyk-pump will not create any indexes (for Mongo pumps).

2022-05-24 16:05 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +- If `omit_index_creation` is set to `false` (default) and you are using `DocumentDB`, tyk-pump is going to create the mongo indexes.
If `omit_index_creation` is set to `false` (default) and you are using `DocumentDB`, tyk-pump will create the Mongo indexes.

2022-05-24 16:05 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +- If `omit_index_creation` is set to `false` (default) and you are using `MongoDB`, we have 2 behaviors:
If 'omit_index_creation' is set to 'false' (default) and you are using 'MongoDB', the behaviour of tyk-pump depends upon whether the collection already exists:

2022-05-24 16:05 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +  - If the collection exists, tyk-pump is not going to create the indexes again.
If the collection already exists, tyk-pump will not create the indexes again.

2022-05-24 16:05 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +  - If the collection doesn't exist, tyk-pump is going to create the indexes.
If the collection does not already exist, tyk-pump will create the indexes.

2022-05-24 16:05 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +From Pump 1.5.2+, the Mongo Pumps indexes default behaviour is changed and the new configuration option `omit_index_creation` is available. This apply for `Mongo Pump`,`Mongo Aggregate Pump` and `Mon
Question: for non-Mongo pumps, does the option simply not exist (i.e. will throw an error if set) or is it simply ignored?

2022-06-08 16:41 UTC, sredxny approved these changes
lgtm

2022-06-27 17:20 UTC, tbuchaillot commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +From Pump 1.5.2+, the Mongo Pumps indexes default behaviour is changed and the new configuration option `omit_index_creation` is available. This apply for `Mongo Pump`,`Mongo Aggregate Pump` and `Mon
@andyo-tyk that option doesn't exist for other pumps, not every data store uses indexes nor has configurations about it. It's just for mongo pumps.

2022-06-27 17:27 UTC, tbuchaillot commented
@andyo-tyk please have another look 👍

2022-06-28 08:23 UTC, andyo-tyk approved these changes
All good now, thanks.

2022-06-28 08:46 UTC, tbuchaillot commented
@marksou can we merge it?

2022-06-28 09:37 UTC, merged

2022-06-28 09:39 UTC, marksou commented
/release to release-4

2022-06-28 09:42 UTC, marksou commented
/release to release-3.2

2022-06-28 09:46 UTC, marksou commented
/release to release-3.1

2022-06-28 09:49 UTC, marksou commented
/release to release-3-lts