[TT-1845]
TykTechnologies/tyk-docs-hugo pull request #1900
Opened 2022-05-19 16:32 UTC by AtiTyk

Body Transform documentation should be improved on "automated" JSON <-> XML transformation

2022-05-19 17:33 UTC, rewsmith requested changes

2022-05-19 17:33 UTC, rewsmith commented on tyk-docs/content/advanced-configuration/transform-traffic/request-body.md
> +Tyk also provides an `xmlMarshal` template to perform conversions in the opposit direction from JSON to XML.
fix typo `opposit` and add comma after direction
i.e. Tyk also provides an `xmlMarshal` template to perform conversions in the opposite direction, from JSON to XML.

2022-05-20 12:37 UTC, rewsmith approved these changes

2022-05-23 15:58 UTC, marksou approved these changes

2022-05-30 07:38 UTC, merged

2022-05-30 07:39 UTC, marksou commented
/release to release-4

2022-05-30 07:40 UTC, marksou commented
/release to release-3.2

2022-05-30 07:41 UTC, marksou commented
/release to release-3.1

2022-05-30 07:47 UTC, marksou commented
/release to release-3-lts