[TT-5508] Update with Postman service
TykTechnologies/tyk-docs-hugo pull request #1915
Opened 2022-06-10 08:29 UTC by marksou

2022-06-13 01:35 UTC, pagemag requested changes
Hi @marksou, please see some of my reviews. Thank you!

2022-06-13 01:35 UTC, pagemag commented on tyk-docs/content/advanced-configuration/websockets.md
> +1. From Postman, select **File > New > WebSocket Request**.
It should not be `File > New > WebSocket Request` but `Choose a Workspace > New > WebSocket Request`

2022-06-13 01:35 UTC, pagemag commented on tyk-docs/content/advanced-configuration/websockets.md
> +If your API uses an Authentication mode other than Open (Keyless), add the details in the Header tab.
Can we add an image of a sample on how to achieve this as there are customers asking on how to use headers when using websocket.

2022-06-20 10:30 UTC, marksou commented on tyk-docs/content/advanced-configuration/websockets.md
> +1. From Postman, select **File > New > WebSocket Request**.
@pagemag It's available from both. Which I admit is a bit strange!

2022-06-20 12:31 UTC, pagemag commented on tyk-docs/content/advanced-configuration/websockets.md
> +1. From Postman, select **File > New > WebSocket Request**.
Oh, I just saw that but I checked on the web version, there's no File.

2022-06-21 07:55 UTC, marksou commented on tyk-docs/content/advanced-configuration/websockets.md
> +1. From Postman, select **File > New > WebSocket Request**.
Ok, I'll add both methods :-)

2022-06-21 08:17 UTC, marksou commented on tyk-docs/content/advanced-configuration/websockets.md
> +If your API uses an Authentication mode other than Open (Keyless), add the details in the Header tab.
Added in latest commit.

2022-06-22 01:07 UTC, pagemag approved these changes
Thanks Mark! Approving the changes.

2022-06-22 06:23 UTC, merged

2022-06-22 06:24 UTC, marksou commented
/release to release-4

2022-06-22 06:25 UTC, marksou commented
/release to release-3.2

2022-06-22 06:27 UTC, marksou commented
/release to release-3.1

2022-06-22 06:28 UTC, marksou commented
/release to release-3-lts