[TT-5805] Update Circuit Breaker triggers
TykTechnologies/tyk-docs-hugo pull request #1939
Opened 2022-07-14 14:31 UTC by marksou

Hope I've understood this correctly :-)

2022-07-14 15:39 UTC, andyo-tyk commented
Almost.... :)

1) You need to add the `BreakerTriggered` event to the Event Type list at /docs/basic-config-and-security/report-monitor-trigger-events/event-types/
2) The system will actually create both the BreakerTriggered event and one of the new events (BreakerTripped or BreakerReset); these new events are the ones to which you can attach a webhook event in the dashboard. I think this needs some explanation...

- The `BreakerTriggered` event will come with a status code that tells you which event it was (tripped or reset)
- If the user wants to use the dashboard to connect their webhooks, then they must use the `BreakerTripped` and `BreakerReset` events - the dashboard does not use `BreakerTriggered`
- I'm wondering whether the new screenshot should be at the bottom of the page, as you do that bit last (after configuring the webhook, you have to attach it to the correct event)?

2022-07-15 10:21 UTC, marksou commented
Hi @andyo-tyk I've pushed some further changes after your comments.

2022-07-18 11:06 UTC, andyo-tyk requested changes
Re-worded the section on half-open state and some suggestions to clarify the different Circuit Breaker triggers.

2022-07-18 11:06 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
> +*   `BreakerTriggered`: When a circuit breaker trips, this event will be created along with either a `BreakerTripped`, or a `BreakerReset` event. A status code will indicate which of these events was
*   `BreakerTriggered`: This event will be created when either a `BreakerTripped`, or a `BreakerReset` event occurs; a status code in the metadata passed to the webhook will indicate which of these events was triggered. This event is not supported in the Tyk Dashboard, but is provided as an alternative to allow configuration of a single webhook for the two circuit breaker events.

2022-07-18 11:06 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
> +*   `BreakerTripped`: When a circuit breaker on a path trips and a service is taken offline. This can be set as a webhook event in the Dashboard
Probably don't need to add the second sentence, with my suggested rewording of BreakerTriggered - none of the other events state that they can be set in the Dashboard, so it looks a bit inconsistent.

2022-07-18 11:06 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
> +*   `BreakerReset`: When the circuit breaker comes back on-stream. This can be set as a webhook event in the Dashboard
Probably don't need to add the second sentence, with my suggested rewording of BreakerTriggered - none of the other events state that they can be set in the Dashboard, so it looks a bit inconsistent.

2022-07-18 11:06 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +In the Dashboard, the `BreakerTrigger` [event type]({{< ref "/content/basic-config-and-security/report-monitor-trigger-events/event-types.md" >}}) is not supported. Instead, you need to add a Webhook
```suggestion
The Dashboard supports the separate `BreakerTripped` and `BreakerReset` events, but not the combined `BreakerTrigger` [event type]({{< ref "/content/basic-config-and-security/report-monitor-trigger-events/event-types.md" >}}). You should use **API Designer > Advanced Options** to add a Webhook plugin to your endpoint for each event.
```

2022-07-18 11:06 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +The `BreakerTriggered` event cannot be configured via the Tyk Dashboard and you need to use Webhooks to specify the `BreakerTripped` and `BreakerReset` event. See [Configure with the Dashboard](#conf
```suggestion
The Dashboard supports the separate `BreakerTripped` and `BreakerReset` events, but not the combined `BreakerTrigger` event. See [Configure with the Dashboard](#configure-with-the-dashboard) for more details.
```

2022-07-18 11:06 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +Tyk has a built-in circuit breaker pattern as a path-based option. Our circuit breaker is rate-based, so if a sample size `x` of `y%` requests fail, the breaker will trip. The Gateway will stop **all
```suggestion
Tyk has a built-in circuit breaker pattern as a path-based option. Our circuit breaker is rate-based, so if a sample size `x` of `y%` requests fail, the breaker will trip.  This triggers an event which you can hook into to perform corrective or logging action. 

The Gateway will stop **all** inbound requests to that service for a pre-defined period of time (a recovery time-period). You can configure this recovery time-period using the `return_to_service_after` option in your API definition, or via the Dashboard.

Once a circuit breaker has been tripped, the Tyk Gateway will return a 503 "Service temporarily unavailable" error for any calls to the API until the end of the recovery time-period.

During the recovery time-period, the Tyk Gateway will periodically issue requests to the upstream service to check whether the path has been restored. If the gateway detects that the path has been reconnected, the circuit breaker will be automatically reset and the 'BreakerReset' event will be generated.

This behaviour is described as the circuit breaker being "half-open"; if the desired behaviour is to enforce the full recovery time period (i.e. to unblock the path only after the `return_to_service_after` time period) then you can disable the half-open operation by setting `disable_half_open_state` to `true`.

See [Configure with the API Definition](#configure-with-the-api-definition) or [Configure with the Dashboard](#configure-with-the-dashboard).
```

2022-07-18 15:43 UTC, andyo-tyk requested changes
Hi Mark,
Sorry, I've spotted a couple of typos (probably in what I proposed) and I think we can now simplify the description in the Event Types list.
Thanks,

2022-07-18 15:43 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +The Dashboard supports the separate `BreakerTripped` and `BreakerReset` events, but not the combined `BreakerTrigger` event. See [Configure with the Dashboard](#configure-with-the-dashboard) for more
Should be `BreakerTriggered` (probably my typo, sorry)

2022-07-18 15:43 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +The Dashboard supports the separate `BreakerTripped` and `BreakerReset` events, but not the combined `BreakerTrigger` [event type]({{< ref "/content/basic-config-and-security/report-monitor-trigger-e
Same here - it should be `BreakerTriggered`

2022-07-18 15:43 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
> +*   `BreakerTriggered`: This event will be created when either a `BreakerTripped`, or a `BreakerReset` event occurs; a status code in the metadata passed to the webhook will indicate which of these e
I think we can simplify this, as it's now well explained in the Circuit Breaker section, so I now suggest dropping the second sentence (and the full stop).

2022-07-18 15:43 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +During the recovery time-period, the Tyk Gateway will periodically issue requests to the upstream service to check whether the path has been restored. If the gateway detects that the path has been re
The formatting hasn't worked on this line for `BreakerReset`

2022-07-19 10:14 UTC, andyo-tyk approved these changes
Looks great to me - I'll stop fiddling now. :-)
Thanks Mark.

2022-07-19 10:17 UTC, merged

2022-07-19 10:18 UTC, marksou commented
/release to release-4

2022-07-19 10:20 UTC, marksou commented
/release to release-3.2

2022-07-19 10:21 UTC, marksou commented
/release to release-3.1

2022-07-19 10:23 UTC, marksou commented
/release to release-3-lts