Update MDCB configs to include synchroniser
TykTechnologies/tyk-docs-hugo pull request #1957
Opened 2022-08-12 20:44 UTC by sredxny

2022-08-15 16:27 UTC, andyo-tyk commented on tyk-docs/content/shared/mdcb-config.md
> +Set to true to disable the Mongo storages default index creation. More detailed behaviour explained at https://tyk.io/docs/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config/#omitting-indexes.
storage's

2022-08-29 12:48 UTC, tbuchaillot approved these changes

2022-09-01 11:26 UTC, marksou requested changes
Can we change all instances of "synchronization" to "synchronisation" as we use UK English.

2022-09-01 12:44 UTC, closed without merging

2022-09-01 12:44 UTC, sredxny commented
Closing in favor of https://github.com/TykTechnologies/tyk-docs/pull/1815