Language updates with Andy
TykTechnologies/tyk-docs-hugo pull request #1958
Opened 2022-08-16 13:30 UTC by marksou

2022-08-17 10:06 UTC, andyo-tyk requested changes
Awesome effort - just a few that you missed; I think there might be some more that will be visible once this is merged.

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/Authentication & Authorization/auth-code-grant-type.md
>  ## Request an authorization code
Should this be authorisation, or in code format?

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/Authentication & Authorization/json-web-tokens/split-token.md
> +Inside Tyk, create a virtual endpoint or API, listening to the path `/token`. This virtual endpoint is responsible for receiving the auth request from the client, and acting as an identity broker wit
This should be authorisation for consistency

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/Authentication & Authorization/oauth-2-0.md
> +3.  Tyk will check the OAuth authorize request for validity (i.e. Does the Client ID exist and is the request properly formed to the OAuth 2.0 standard).
Should this authorize be in `code` format?

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/dashboard/dashboard-api-security.md
> +The Dashboard API is secured using an `Authorization` header that must be added to each request that is made. The **Tyk Dashboard API Access Credentials** Authorization key can be found at the bottom
Should the second Authorization also be in code format?

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/plugins/auth-plugins/id-extractor.md
> +The main idea of the ID extractor is to reduce the number of calls made to your plugin and cache the API keys that have been already authorised by your authentication mechanism.This means that after
Missing space after full stop: mechanism.This

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/plugins/auth-plugins/id-extractor.md
> +The main idea of the ID extractor is to reduce the number of calls made to your plugin and cache the API keys that have been already authorised by your authentication mechanism.This means that after
Also, on line 31 below, there's a missed z in "you initialize the session object"

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-on-prem/installation/debian-ubuntu/analytics-pump.md
> +3. Run initalisation script to initialise environment
Typo: _initalisation_

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-on-prem/installation/debian-ubuntu/dashboard.md
> +3. Run initalisation script to initialise environment
Typo: _initalisation_

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-on-prem/installation/debian-ubuntu/debian-ubuntu.md
> +3. Run initalisation script to initialise environment
Typo: _initalisation_

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-on-prem/installation/debian-ubuntu/gateway.md
> +3. Run initalisation script to initialise environment
Typo: _initalisation_

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-on-prem/installation/install-tyk-ansible.md
> +3. Run initalisation script to initialise environment
Typo: _initalisation_

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/analytics-pump.md
> +3. Run initalisation script to initialise environment
Typo: _initalisation_

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
> +3. Run initalisation script to initialise environment
Typo: _initalisation_

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/gateway.md
> +3. Run initalisation script to initialise environment
Typo: _initalisation_

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/redhat-rhel-centos.md
> +3. Run initalisation script to initialise environment
Typo: _initalisation_

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/enterprise-developer-portal.md
> +* Create multiple organization and teams to segment your developer audience.
Missed an _organization_ here -  and should be plural, I think: organisations

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/enterprise-developer-portal.md
> +* Create multiple API catalogues to tailor API products and plans visibility to a certain audience.
Perhaps re-word this, moving "visibility" for readability, such as:
Create multiple API catalogues to tailor visibility of API products and plans to different audiences.

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/customise-menus.md
> +Admin users can create additional navigational menus and render them on any page of the live portal. This customization requires changes to a theme and is covered in the [Full customisation section](
Missed a _customization_ in the second sentence.

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-ansible.md
> +3. Run initalisation script to initialise environment
Typo: initalisation

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-debian-ubuntu.md
> +3. Run initalisation script to initialise environment
Typo: initalisation

2022-08-17 10:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-gateway/install/ce-redhat-rhel-centos.md
> +3. Run the initalisation script to initialise your environment
Typo: initalisation

2022-08-22 07:15 UTC, marksou commented on tyk-docs/content/basic-config-and-security/security/Authentication & Authorization/auth-code-grant-type.md
>  ## Request an authorization code
Code format

2022-08-22 07:18 UTC, marksou commented on tyk-docs/content/basic-config-and-security/security/Authentication & Authorization/oauth-2-0.md
> +3.  Tyk will check the OAuth authorize request for validity (i.e. Does the Client ID exist and is the request properly formed to the OAuth 2.0 standard).
It is, anything wrapped in `something` will be in code format when compiled in to site

2022-08-22 08:31 UTC, andyo-tyk approved these changes
Thanks for this, Mark - looks great.

2022-08-22 08:32 UTC, merged

2022-08-22 08:32 UTC, marksou commented
/release to release-4.1

2022-08-22 08:33 UTC, marksou commented
/release to release-4

2022-08-22 08:34 UTC, marksou commented
/release to release-3.2