[TT-6506] Improve distributed tracing docs
TykTechnologies/tyk-docs-hugo pull request #2010
Opened 2022-09-15 08:00 UTC by marksou

2022-09-16 08:56 UTC, andyo-tyk requested changes
Some suggested changes to improve readability and consistency.

2022-09-16 08:56 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/distributed-tracing/distributed-tracing.md
> +At the moment Tyk currently supports OpenTracing for distributed tracing. Support with OpenTelemetry is on the near-term roadmap for the Tyk API Gateway. If this is a valuable feature for you, please
"At the moment ... currently ..." -> can you please reword this?

2022-09-16 08:56 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/distributed-tracing/distributed-tracing.md
> +- [Zipkin]({{< ref "/content/advanced-configuration/distributed-tracing/zipkin.md" >}}). This tracer can also be used to send tracers to [New Relic]({{< ref "/content/advanced-configuration/distribut
This line doesn't look very good - why not put New Relic on its own bullet, given it has its own page linked?

Just below this, there's a line that reads:
"To enable distributed tracing, add the following tracing configuration on your `tyk.conf`"
I think this should probably be
_add ... to your `tyk.conf`_

2022-09-16 08:56 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/distributed-tracing/jaeger.md
> +At the moment Tyk currently uses [OpenTracing](https://opentracing.io/) with the [Jaeger client libraries](https://www.jaegertracing.io/docs/1.11/client-libraries/). Support for [OpenTelemetry](https
Again we have "at the moment" and "currently", this might be better as:

_Tyk uses [OpenTracing](https://opentracing.io/) with the [Jaeger client libraries](https://www.jaegertracing.io/docs/1.11/client-libraries/) to send Tyk Gateway traces to Jaeger._

I would include the OpenTelemetry bit in with the CNCF note, so will add a comment with it below.

2022-09-16 08:56 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/distributed-tracing/jaeger.md
> +The CNCF (Cloud Native Foundation) has archived the OpenTracing project and Jaeger has also deprecated their client libraries. This means that no new pull requests or feature requests are accepted in
I would put this in a "note" format and add in the reference to Open Telemetry being on Tyk's roadmap, perhaps:

##note
The CNCF (Cloud Native Foundation) has archived the OpenTracing project and Jaeger has deprecated their client libraries. This means that no new pull requests or feature requests are accepted into OpenTracing or Jaeger repositories.

While support for [OpenTelemetry](https://opentelemetry.io/) is on our near-term roadmap, you can continue to leverage OpenTracing to get timing and data from Tyk in your traces. More information can be found in our [community forum](https://community.tyk.io/t/faq-opentelemetry-distributed-tracing/5682).

2022-09-16 08:56 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/distributed-tracing/newrelic.md
> +At the moment Tyk currently uses [OpenTracing](https://opentracing.io/) to export distributed traces. Support for [OpenTelemetry](https://opentelemetry.io/) is on the near-term roadmap for us. More i
I would make this approximate to the suggested changes to the Jaeger page, adding in the note about CNCF (though without the reference to Jaeger deprecating their libraries!), perhaps:

Tyk uses New Relic's [Trace API](https://docs.newrelic.com/docs/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api/), implementing [OpenTracing](https://opentracing.io/) to send Tyk Gateway traces to NewRelic in the Zipkin format.

##note
The CNCF (Cloud Native Foundation) has archived the OpenTracing project; this means that no new pull requests or feature requests are accepted into the OpenTracing repositories.

While support for [OpenTelemetry](https://opentelemetry.io/) is on our near-term roadmap, you can continue to leverage OpenTracing to get timing and data from Tyk in your traces. More information can be found in our [community forum](https://community.tyk.io/t/faq-opentelemetry-distributed-tracing/5682).

2022-09-16 08:56 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/distributed-tracing/newrelic.md
> +[New Relic](https://newrelic.com/) has a Trace API that can be used to [import distributed traces in the OpenTracing/Zipkin format](https://docs.newrelic.com/docs/distributed-tracing/trace-api/report
This line is no longer needed.

2022-09-16 08:56 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/distributed-tracing/zipkin.md
> +At the moment Tyk currently uses [OpenTracing](https://opentracing.io/) with the [Zipkin Go tracer](https://zipkin.io/pages/tracers_instrumentation). Support for [OpenTelemetry](https://opentelemetry
I would make this approximate to the suggested changes to the New Relic page, adding in the note about CNCF, perhaps:

Tyk uses the [Zipkin Go tracer](https://zipkin.io/pages/tracers_instrumentation), implementing [OpenTracing](https://opentracing.io/) to send Tyk Gateway traces to Zipkin.

##note
The CNCF (Cloud Native Foundation) has archived the OpenTracing project; this means that no new pull requests or feature requests are accepted into the OpenTracing repositories.

While support for [OpenTelemetry](https://opentelemetry.io/) is on our near-term roadmap, you can continue to leverage OpenTracing to get timing and data from Tyk in your traces. More information can be found in our [community forum](https://community.tyk.io/t/faq-opentelemetry-distributed-tracing/5682).

2022-09-19 10:00 UTC, SonjaChevre commented on tyk-docs/content/advanced-configuration/distributed-tracing/distributed-tracing.md
> +- [Zipkin]({{< ref "/content/advanced-configuration/distributed-tracing/zipkin.md" >}}). This tracer can also be used to send tracers to [New Relic]({{< ref "/content/advanced-configuration/distribut
Yes that's right. Technically we really only support two "tracers" (the one from Zipkin and the one from Jaeger). but users probably don't care which tracer we support, they care about which observability tools they can integrate with.

So my suggestion - instead of "supported tracer", something like "supported observability back-end"? or "supported observability tool"?

2022-09-19 10:02 UTC, SonjaChevre commented
all great comments from @andyo-tyk! Looking forward to see the next iteration.

2022-09-27 10:54 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/distributed-tracing/distributed-tracing.md
> +- [Zipkin]({{< ref "/content/advanced-configuration/distributed-tracing/zipkin.md" >}}). This tracer can also be used to send tracers to [New Relic]({{< ref "/content/advanced-configuration/distribut
I think that "Supported observability tools" would be best.

2022-09-28 07:45 UTC, marksou commented on tyk-docs/content/advanced-configuration/distributed-tracing/distributed-tracing.md
> +At the moment Tyk currently supports OpenTracing for distributed tracing. Support with OpenTelemetry is on the near-term roadmap for the Tyk API Gateway. If this is a valuable feature for you, please
Changes made in new commit

2022-09-28 07:45 UTC, marksou commented on tyk-docs/content/advanced-configuration/distributed-tracing/distributed-tracing.md
> +- [Zipkin]({{< ref "/content/advanced-configuration/distributed-tracing/zipkin.md" >}}). This tracer can also be used to send tracers to [New Relic]({{< ref "/content/advanced-configuration/distribut
Changes made

2022-09-28 07:46 UTC, marksou commented on tyk-docs/content/advanced-configuration/distributed-tracing/jaeger.md
> +The CNCF (Cloud Native Foundation) has archived the OpenTracing project and Jaeger has also deprecated their client libraries. This means that no new pull requests or feature requests are accepted in
Changes made

2022-09-28 07:46 UTC, marksou commented on tyk-docs/content/advanced-configuration/distributed-tracing/newrelic.md
> +[New Relic](https://newrelic.com/) has a Trace API that can be used to [import distributed traces in the OpenTracing/Zipkin format](https://docs.newrelic.com/docs/distributed-tracing/trace-api/report
Changes made

2022-09-28 07:46 UTC, marksou commented on tyk-docs/content/advanced-configuration/distributed-tracing/zipkin.md
> +At the moment Tyk currently uses [OpenTracing](https://opentracing.io/) with the [Zipkin Go tracer](https://zipkin.io/pages/tracers_instrumentation). Support for [OpenTelemetry](https://opentelemetry
Changes made

2022-09-28 07:47 UTC, marksou commented on tyk-docs/content/advanced-configuration/distributed-tracing/jaeger.md
> +At the moment Tyk currently uses [OpenTracing](https://opentracing.io/) with the [Jaeger client libraries](https://www.jaegertracing.io/docs/1.11/client-libraries/). Support for [OpenTelemetry](https
Changes made

2022-09-28 07:47 UTC, marksou commented on tyk-docs/content/advanced-configuration/distributed-tracing/newrelic.md
> +At the moment Tyk currently uses [OpenTracing](https://opentracing.io/) to export distributed traces. Support for [OpenTelemetry](https://opentelemetry.io/) is on the near-term roadmap for us. More i
Changes made

2022-09-28 07:54 UTC, SonjaChevre approved these changes
LGTM, thanks!

2022-09-28 10:29 UTC, andyo-tyk approved these changes
That reads better and looks fantastic - thank you.

2022-09-28 11:30 UTC, merged

2022-09-28 11:30 UTC, marksou commented
/release to release-4.1

2022-09-28 11:33 UTC, marksou commented
/release to release-4

2022-09-28 11:34 UTC, marksou commented
/release to release-3.2

2022-09-28 11:40 UTC, marksou commented
/release to release-3.1

2022-09-28 11:43 UTC, marksou commented
/release to release-3-lts