Change Postman collection buttons to a link
TykTechnologies/tyk-docs-hugo pull request #2023
Opened 2022-10-12 07:54 UTC by marksou

Postman buttons no longer work properly after the addition of the Dashboard API. Changing to a link to the collections as a whole to replace the buttons.

2022-10-12 15:31 UTC, letzya commented
This page https://deploy-preview-2023--tyk-docs.netlify.app/docs/nightly/tyk-apis/ looks a bit odd without the links to the collection, I think it needs some clarification, Maybe move the last section to the top and add some explanation in each section?

2022-10-12 15:31 UTC, letzya requested changes
Added comment

2022-10-23 14:57 UTC, letzya requested changes
Per my message

2022-10-24 05:15 UTC, letzya requested changes
Per my message

2022-10-28 21:14 UTC, letzya requested changes
Per my comments

2022-10-28 21:14 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +Tyk's own APIs allow you to access to the following
Need more info here

2022-10-28 21:14 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +Our Gateway API is available as a [Postman Collection](#tyk-postman-collections) that you can use to test our Gateway endpoints.
Not just to test but also connect and control the gw.

2022-10-28 21:14 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
>  The Tyk Dashboard API allows much more fine-grained, secure and multi-user access to your Tyk cluster, and should be used to manage a database-backed Tyk node. The Tyk Dashboard API works seamlessly
Can we please remove "the two of them ..."

2022-10-28 21:14 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +We have a Postman public workspace where you can view, fork and test our Gateway and Dashboard APIs.
This sentence is being repeated 3-4 times...

2022-11-13 16:37 UTC, letzya requested changes
Per my comments

2022-11-13 16:37 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +We have a Postman public workspace where you can view, fork and test our Gateway and Dashboard APIs.
`We` again. Needs rewriting

2022-11-13 16:37 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +We have our own APIs and a Postman public workspace.
This page is not about postman it’s about our APIs. postman is just a tool to view them. Also needs to be 2-3 sentences

2022-11-13 16:37 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +The Tyk Dashboard API allows much more fine-grained, secure and multi-user access to your Tyk cluster, and should be used to manage a database-backed Tyk node. The Tyk Dashboard API works seamlessly
`The Tyk Dashboard API allows much more fine-grained` - full RBAC, not just "more"

2022-11-13 16:37 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +
Can we remove this section, we don't have this as a separate api or collection.

2022-11-13 16:37 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +This allows you to test, connect to and control your Gateway.
Add a link to the api page https://deploy-preview-2023--tyk-docs.netlify.app/docs/nightly/tyk-gateway-api/

explain that this is the latest released version of our API and if you are a postman user, click on the button above to get to the official tyk gateway collection.
(same for the dashboard)

2022-11-13 16:37 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +## Tyk Postman Collections
I think this section could look better as part of the one above, so maybe try to remove this title.

2022-11-14 09:53 UTC, letzya requested changes
.

2022-11-14 15:08 UTC, marksou commented on tyk-docs/content/tyk-apis/tyk-apis.md
> +This allows you to test, connect to and control your Gateway.
The title for each section is a link to the appropriate API

2022-11-25 18:27 UTC, letzya approved these changes

2022-11-25 18:34 UTC, letzya approved these changes

2022-11-25 18:35 UTC, merged

2022-11-25 18:36 UTC, letzya commented
/release to release-4.1