[TT-6408]
TykTechnologies/tyk-docs-hugo pull request #2055
Opened 2022-11-10 17:19 UTC by AtiTyk

Changing a part of the code.

2022-11-15 13:59 UTC, Yubee116 requested changes
Sorry wasn't clear the first time.

2022-11-15 13:59 UTC, Yubee116 commented on tyk-docs/content/plugins/supported-languages/golang-plugins/golang-plugins.md
> +// ctx.SetSession(r, session, true)
do not REPLACE previous lines 
only ADD these lines

// if compiling on GW version 4.0.1 and up, use this instead
// ctx.SetSession(r, session, true)

2022-11-15 16:42 UTC, marksou commented on tyk-docs/content/plugins/supported-languages/golang-plugins/golang-plugins.md
> +// ctx.SetSession(r, session, true)
Ati added the changes

2022-11-25 10:02 UTC, Yubee116 approved these changes

2022-11-25 10:06 UTC, Yubee116 approved these changes

2022-12-08 06:24 UTC, Yubee116 approved these changes

2022-12-08 13:51 UTC, merged