[DX-146] Remove free tier from the docs
TykTechnologies/tyk-docs-hugo pull request #2057
Opened 2022-11-11 15:04 UTC by AMM55

Remove cloud free from the docs

2022-11-11 15:14 UTC, marksou approved these changes

2022-11-11 15:20 UTC, letzya commented on tyk-docs/content/tyk-cloud/account-&-billing/plans.md
>  | 5-week free trial | This is for POC’s and those testing the Tyk platform.                               | The Tyk Cloud free is 5 weeks so that you would have enough time to work your way through a
Can you also change the text here "tyk cloud free is 5 weeks" - this is the wrong name. similar to my PR https://github.com/TykTechnologies/tyk-docs/pull/2056/files

2022-11-14 06:13 UTC, michellefernando9 approved these changes

2022-11-14 09:45 UTC, letzya commented on tyk-docs/content/tyk-cloud/account-&-billing/plans.md
> +| 5-week free trial | This is for POC’s and those testing the Tyk platform.                               | The Tyk Cloud has 5-week free trial so that you would have enough time to work your way thr
Do we need the “The” in the beginning?

2022-11-14 13:08 UTC, letzya requested changes
Agreed to remove "The"

2022-11-15 12:59 UTC, letzya approved these changes

2022-11-17 09:23 UTC, merged

2022-11-17 09:23 UTC, marksou commented
/release to release-4.1