Throttling update
TykTechnologies/tyk-docs-hugo pull request #2058
Opened 2022-11-14 06:09 UTC by michellefernando9

2022-11-14 08:10 UTC, marksou approved these changes, later dismissed
Looks good

2022-11-14 09:09 UTC, carlostyk approved these changes, later dismissed
Thank you!

2022-11-14 09:17 UTC, letzya commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-throttling.md
> +![Tyk API Gateway ottling](/docs/img/dashboard/system-management/throttling_update.png)
typo

2022-11-14 14:03 UTC, letzya requested changes
there's still a typo

2022-11-16 14:00 UTC, letzya approved these changes

2022-11-16 14:03 UTC, carlostyk approved these changes
Thank you!

2022-11-17 20:13 UTC, letzya commented
@marksou can you please merge?

2022-11-17 21:10 UTC, merged

2022-11-17 21:10 UTC, marksou commented
/release to release-4.1

2022-11-17 21:12 UTC, marksou commented
/release to release-4