Rate limiting
TykTechnologies/tyk-docs-hugo pull request #2064
Opened 2022-11-15 11:31 UTC by michellefernando9

2022-11-16 03:41 UTC, pagemag reviewed
The Throttling and rate limiting changes are okay. Just got a question if tyk-cloud article is meant to be deleted?

2022-11-16 03:41 UTC, pagemag commented on tyk-docs/content/tyk-cloud/tyk-cloud.md
> -title: "Tyk Cloud"
@michellefernando9 , Is this article meant to be deleted?

2022-11-16 06:02 UTC, michellefernando9 commented on tyk-docs/content/tyk-cloud/tyk-cloud.md
> -title: "Tyk Cloud"
@pagemag This has been added to the docs again.

2022-11-17 01:25 UTC, pagemag approved these changes
Approved!

2022-11-17 08:52 UTC, marksou approved these changes

2022-11-18 14:03 UTC, letzya commented
@michellefernando9 we have 2 similar  PRs https://github.com/TykTechnologies/tyk-docs/pull/2058, can you make them into one please?

2022-11-18 14:07 UTC, letzya commented
@michellefernando9 please check what we need from this PR as it's similar to https://github.com/TykTechnologies/tyk-docs/pull/2058 that was merged

2022-11-21 14:35 UTC, letzya requested changes
@michellefernando9 we have 2 similar PRs https://github.com/TykTechnologies/tyk-docs/pull/2058, can you make them into one please?

2022-11-23 13:08 UTC, letzya requested changes
per discussion

2022-11-24 07:34 UTC, michellefernando9 commented
Now that the changes have been made, I don't see the point in creating a new PR. Would be like doing the same work over and over again.

2022-11-24 07:54 UTC, marksou approved these changes

2022-12-06 20:29 UTC, letzya commented
fixed in another pr

2022-12-06 20:29 UTC, closed without merging