[TT-6141]
TykTechnologies/tyk-docs-hugo pull request #2068
Opened 2022-11-16 19:15 UTC by AtiTyk

Change 'all' to 'some'.

2022-11-17 11:15 UTC, Yubee116 approved these changes

2022-12-07 05:32 UTC, letzya requested changes

2022-12-07 05:32 UTC, letzya commented on tyk-docs/content/plugins/auth-plugins/id-extractor.md
> +The ID extractor works for some rich plugins: gRPC-based plugins, Python and Lua.
```suggestion
The ID extractor works the following rich plugins: gRPC-based plugins, Python and Lua.
```

2022-12-07 05:43 UTC, letzya approved these changes

2022-12-07 05:59 UTC, letzya commented
@buger do you know why it's failing?

2022-12-07 06:13 UTC, letzya approved these changes

2023-01-05 21:49 UTC, letzya approved these changes

2023-01-05 21:54 UTC, letzya approved these changes

2023-01-05 21:56 UTC, merged