made a small change to create the initial PR
TykTechnologies/tyk-docs-hugo pull request #2070
Opened 2022-11-17 17:29 UTC by Monica-Cedeno

2022-12-06 20:27 UTC, letzya requested changes
Need fixing of all references to images

2022-12-06 20:27 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +See their documentation for more detail: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app
```suggestion
Check [Microsoft's documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app) for more detail.
```

2022-12-06 20:27 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +    (/docs/img/azureAD/overview.png)
Please fix this so the image is added correctly throughout the page

2022-12-12 19:40 UTC, zalbiraw requested changes
I would redact the information in the screenshots

2022-12-12 19:40 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +    (/docs/img/azureAD/overview.png)
@Monica-Cedeno you need to add the square brackets with the description of the image before each image :)

2023-04-24 17:53 UTC, JRWu requested changes
Great work, just a couple minor suggestions as well as fixing the linking for the images.

2023-04-24 17:53 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![additional-url-added] (/docs/img/azureAD/openid_connect/additional_redirect_url_added)
Potentially missing extension to the file here?

2023-04-24 17:53 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![profile-configuration-additional-options] (/docs/img/azureAD/additional_options.png)
I believe the space is preventing the image from rendering correctly
i.e. it says
![profile-configuration-additional-options] (/docs/img/azureAD/additional_options.png)

When it should be
![profile-configuration-additional-options](/docs/img/azureAD/additional_options.png)

2023-04-24 17:53 UTC, JRWu commented on tyk-docs/static/img/azureAD/profile-configuration.png
Potentially should redact the secret field here

2023-04-24 17:53 UTC, JRWu commented on tyk-docs/static/img/azureAD/openid_connect/step_1.png
Potentially could redact the secret here

2023-04-24 20:20 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![additional-url-added] (/docs/img/azureAD/openid_connect/additional_redirect_url_added)
I removed the spacing here

2023-04-24 20:20 UTC, Monica-Cedeno commented on tyk-docs/static/img/azureAD/profile-configuration.png
I blurred it out

2023-04-24 20:20 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![profile-configuration-additional-options] (/docs/img/azureAD/additional_options.png)
I removed the spacing here as well

2023-04-24 20:20 UTC, Monica-Cedeno commented on tyk-docs/static/img/azureAD/openid_connect/step_1.png
I blurred this out too

2023-04-24 20:21 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +    (/docs/img/azureAD/overview.png)
square brackets and spacing was resolved

2023-04-25 13:12 UTC, JRWu submitted a review, later dismissed
Great work, just a couple more minor changes requested

2023-04-25 13:12 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![additional-url-added](/docs/img/azureAD/openid_connect/additional_redirect_url_added)
I think you're missing an extension here, the image is broken
instead of 
![additional-url-added](/docs/img/azureAD/openid_connect/additional_redirect_url_added)

try

![additional-url-added](/docs/img/azureAD/openid_connect/additional_redirect_url_added.png)

2023-04-25 13:12 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![additional-url-added](/docs/img/azureAD/openid_connect/additional_redirect_url_added)
i.e. add a .png after your filename additional_redirect_url_added to make it "additional_redirect_url_added.png"

2023-04-25 13:12 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +Check [Microsoft's documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app) for more detail.
I think this apostrophe in Microsoft's needs to be escaped since it's rendering like:

Microsoft&rsquo;s

2023-04-25 13:13 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +Check [Microsoft's documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app) for more detail.
Rendering like: Microsoft& rsquo;s

2023-04-25 14:02 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +Check [Microsoft's documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app) for more detail.
done

2023-04-25 14:02 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![additional-url-added](/docs/img/azureAD/openid_connect/additional_redirect_url_added)
good catch! thank you and done

2023-05-10 13:49 UTC, zalbiraw requested changes

2023-05-10 13:49 UTC, zalbiraw commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
I dont think you meant to change this?

2023-05-10 13:49 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +4. Go to Overview and add a secret in Client Credentials. Don't forget to copy the secret value- not the secretID.
```suggestion
4. Go to Overview and add a secret in Client Credentials. Don't forget to copy the secret value, not the secretID. 
```

2023-05-10 13:49 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +3. Under Profile Configuration, paste the secret value, clientID, and Discover URL from the Azure site.
```suggestion
3. Under Profile Configuration, paste the secret value, clientID, and well-known endpoint URL from the Azure site. 
```

2023-05-10 13:49 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +  - The Discover URL is created by Azure and can be located by selecting Endpoints on their site
```suggestion
  - The well-known endpoint URL is created by Azure and can be located by selecting Endpoints on their site
```

2023-05-10 13:49 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
>  8. Test that it works:
```suggestion
4. Test that it works:
```

2023-05-10 13:54 UTC, zalbiraw commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< include "api-def-custom-analytics" >}}
```suggestion
{{< include "api-def-custom-analytics" >}}
```

2023-05-10 13:54 UTC, zalbiraw commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< include "api-def-custom-analytics" >}}
```suggestion
{{< include "api-def-custom-analytics" >}}
```

2023-05-10 13:55 UTC, zalbiraw commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< include "api-def-custom-analytics" >}}
```suggestion
{{< include "api-def-custom-analytics" >}} 
```

2023-05-10 13:56 UTC, zalbiraw commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< include "api-def-custom-analytics" >}}
```suggestion
{{< include "api-def-custom-analytics" >}}

```

2023-05-10 14:03 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +* You already have authorised access to Tyk's Dashboard. If you haven't, [get the authorisation key by following this doc](/docs/basic-config-and-security/security/dashboard/create-users/#a-name-with
```suggestion
* You already have authorised access to Tyk's Dashboard. If you haven't, [get the authorisation key by following this doc](/docs/basic-config-and-security/security/dashboard/create-users/#create-a-dashboard-user-with-the-api).
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +* You already have authorised access to Tyk's Dashboard. If you haven't, [get the authorisation key by following this doc](/docs/basic-config-and-security/security/dashboard/create-users/#create-a-da
```suggestion
* You already have authorised access to Tyk's Dashboard. If you haven't, [get the authorisation key by following this doc]({{< ref "basic-config-and-security/security/dashboard/create-users/#create-a-dashboard-user-with-the-api">}}).
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +    ![redirect-url](/docs/img/azureAD/redirect-URL-1.png)
```suggestion
    ![redirect-url]({{< ref "img/azureAD/redirect-URL-1.png" >}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +    ![overview](/docs/img/azureAD/overview-1.png)
```suggestion
    ![overview]({{< ref "img/azureAD/overview-1.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +  ![profile-configuration](/docs/img/azureAD/profile-configuration-1.png)
```suggestion
  ![profile-configuration]({{< ref "img/azureAD/profile-configuration-1.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +  ![endpoints](/docs/img/azureAD/endpoints-11.png)
```suggestion
  ![endpoints]({{< ref "img/azureAD/endpoints-11.png" >}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![profile-configuration-additional-options](/docs/img/azureAD/additional-options.png)
```suggestion
![profile-configuration-additional-options]({{< ref "img/azureAD/additional-options.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![profile-configuration-raw-editor](/docs/img/azureAD/raw-editor.png)
```suggestion
![profile-configuration-raw-editor]({{< ref "img/azureAD/raw-editor.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![additional-url-added](/docs/img/azureAD/openid_connect/additional_redirect_url.png)
```suggestion
![additional-url-added]({{< ref "img/azureAD/openid_connect/additional_redirect_url.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-1](/docs/img/azureAD/openid_connect/step-1.png)
```suggestion
![openid-connect-step-1]({{< ref "img/azureAD/openid_connect/step-1.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-2](/docs/img/azureAD/openid_connect/step-2.png)
```suggestion
![openid-connect-step-2]({{< ref "img/azureAD/openid_connect/step-2.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-4](/docs/img/azureAD/openid_connect/step-4.png)
```suggestion
![openid-connect-step-3]({{< ref "img/azureAD/openid_connect/step-3.png">}})
![openid-connect-step-4]({{< ref "img/azureAD/openid_connect/step-4.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-5](/docs/img/azureAD/openid_connect/step-5.png)
```suggestion
![openid-connect-step-5]({{< ref "img/azureAD/openid_connect/step-5.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-5](/docs/img/azureAD/openid_connect/step-5.png)
```suggestion
![openid-connect-step-5]({{< ref "img/azureAD/openid_connect/step-5.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-6](/docs/img/azureAD/openid_connect/step-6.png)
```suggestion
![openid-connect-step-6]({{< ref "img/azureAD/openid_connect/step-6.png">}})
```

2023-05-10 15:20 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-5](/docs/img/azureAD/openid_connect/step-5.png)
```suggestion
![openid-connect-step-5]({{< ref "img/azureAD/openid_connect/step-5.png">}})
```

2023-05-10 15:30 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +    ![redirect-url]({{< ref "img/azureAD/redirect-URL-1.png" >}})
```suggestion
    ![redirect-url]({{< ref "/img/azureAD/redirect-URL-1.png" >}})
```

2023-05-10 15:35 UTC, zalbiraw requested changes

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +* You already have authorised access to Tyk's Dashboard. If you haven't, [get the authorisation key by following this doc]({{< ref "basic-config-and-security/security/dashboard/create-users/#create-a
```suggestion
* You already have authorised access to Tyk's Dashboard. If you haven't, [get the authorisation key by following this doc]({{< ref "/basic-config-and-security/security/dashboard/create-users/#create-a-dashboard-user-with-the-api">}}).
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +    ![redirect-url]({{< ref "img/azureAD/redirect-URL-1.png" >}})
```suggestion
    ![redirect-url]({{< ref "/img/azureAD/redirect-URL-1.png" >}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +    ![overview]({{< ref "img/azureAD/overview-1.png">}})
```suggestion
    ![overview]({{< ref "/img/azureAD/overview-1.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +  ![profile-configuration]({{< ref "img/azureAD/profile-configuration-1.png">}})
```suggestion
  ![profile-configuration]({{< ref "/img/azureAD/profile-configuration-1.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +  ![endpoints]({{< ref "img/azureAD/endpoints-11.png" >}})
```suggestion
  ![endpoints]({{< ref "/img/azureAD/endpoints-11.png" >}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![profile-configuration-additional-options]({{< ref "img/azureAD/additional-options.png">}})
```suggestion
![profile-configuration-additional-options]({{< ref "/img/azureAD/additional-options.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![profile-configuration-raw-editor]({{< ref "img/azureAD/raw-editor.png">}})
```suggestion
![profile-configuration-raw-editor]({{< ref "/img/azureAD/raw-editor.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![additional-url-added]({{< ref "img/azureAD/openid_connect/additional_redirect_url.png">}})
```suggestion
![additional-url-added]({{< ref "img/azureAD/openid_connect/additional_redirect_url.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-2]({{< ref "img/azureAD/openid_connect/step-2.png">}})
```suggestion
![openid-connect-step-2]({{< ref "/img/azureAD/openid_connect/step-2.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-1]({{< ref "img/azureAD/openid_connect/step-1.png">}})
```suggestion
![openid-connect-step-1]({{< ref "/img/azureAD/openid_connect/step-1.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-3]({{< ref "img/azureAD/openid_connect/step-3.png">}})
```suggestion
![openid-connect-step-3]({{< ref "/img/azureAD/openid_connect/step-3.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-4]({{< ref "img/azureAD/openid_connect/step-4.png">}})
```suggestion
![openid-connect-step-4]({{< ref "/img/azureAD/openid_connect/step-4.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-5]({{< ref "img/azureAD/openid_connect/step-5.png">}})
```suggestion
![openid-connect-step-5]({{< ref "/img/azureAD/openid_connect/step-5.png">}})
```

2023-05-10 15:35 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![openid-connect-step-6]({{< ref "img/azureAD/openid_connect/step-6.png">}})
```suggestion
![openid-connect-step-6]({{< ref "/img/azureAD/openid_connect/step-6.png">}})
```

2023-05-10 15:38 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +![additional-url-added]({{< ref "img/azureAD/openid_connect/additional_redirect_url.png">}})
```suggestion
![additional-url-added]({{< ref "/img/azureAD/openid_connect/additional_redirect_url.png">}})
```

2023-05-10 15:45 UTC, zalbiraw commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< include "api-def-custom-analytics" >}}
```suggestion
{{< include "api-def-custom-analytics" >}} 
```

2023-06-20 14:19 UTC, dcs3spp requested changes
Hi Monica, PR looks good. I have had a read through and made some comments/suggestions.

2023-06-20 14:19 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +* You already have authorised access to Tyk's Dashboard. If you haven't, [get the authorisation key by following this doc]({{< ref "/basic-config-and-security/security/dashboard/create-users/#create-
If you commit this suggestion I think it will fix the checks listed on the PR page

```suggestion
You already have authorised access to Tyk's Dashboard. If you haven't, get the authorisation key by following this [guide]({{< ref "basic-config-and-security/security/dashboard/create-users#create-a-dashboard-user-with-the-api">}}).
```

2023-06-20 14:19 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +4. Test that it works:
To be consistent with similar Tyk docs for [Auth0](https://tyk.io/docs/tyk-stack/tyk-manager/sso/sso-auth0-tib/#create-an-identity-management-profile-in-your-dashboard):
- Change step 4 so that it is a heading, e.g. Test your Azure Login 
- Add screenshots for Azure, similar to those used for [Auth0](https://tyk.io/docs/tyk-stack/tyk-manager/sso/sso-auth0-tib/#create-an-identity-management-profile-in-your-dashboard)

2023-06-20 14:19 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +{{< img src="/img/azureAD/raw-editor.png" alt="Profile Configuration - Raw-editor" >}}
Above the raw-editor image add a sentence explaining what the image represents

2023-06-20 14:19 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +Group mapping can be managed in Advanced Settings by passing an identity provider and selecting a Tyk User Group which can be created in the the User Groups section of
_Maybe consider editing to something like below_

Group mapping can be managed from Advanced Settings section of the Profile Configuration screen. 

(show Profile Configuration screen here)

As illustrated in the screen below the following information must be provided:
- Identity provider role
- Tyk User Group: This can be created from the User Groups section of the dashboard (reference a link to a page in tyk docs here to show how to create a user group). When creating your User Group, one can also select and adjust the permissions for each group. (add a link to existing docs that shows how to select and adjust permissions for a user group)

(include the screen that shows mapping from Azure identity to Tyk User group mapping here)

You can select the scopes you would like your request to include. By default, Tyk will provide the _connectid_ scope, anything additional must be requested.

<Maybe add a description of the other optional user group mapping fields here, e.g. Fallback user group ad custom group name>

2023-06-20 14:19 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +1. Add the redirect url found on the OpenID Connect site to the redirect urls found under the Web section
Show a screenshot of how to access the web section here, is it included somewhere on dashboard?

2023-06-20 14:19 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +For debugging purposes, you can find an example we created using the OpenID Connect playground.
Make this a new section, titled OpenID Connect example

2023-06-20 14:19 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +2. Copy the OpenID Connect endpoint
Accompany steps with additional screenshots, e.g. include a screenshot of the screen the user clicks edit on for the OpenID connect site where the Server Template dropdown exists.

Which screen do copy and paste the Client ID and Client Secret into?
Which screen do press Start on

2023-06-20 14:19 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +2. Copy the OpenID Connect endpoint
Add a space before step 2. When previewing in the browser all the number steps are displayed in one paragraph

2023-06-20 21:29 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +* You already have authorised access to Tyk's Dashboard. If you haven't, [get the authorisation key by following this doc]({{< ref "/basic-config-and-security/security/dashboard/create-users/#create-
```suggestion
* You already have authorised access to Tyk's Dashboard. If you haven't, [get the authorisation key by following this doc]({{< ref "basic-config-and-security/security/dashboard/create-users#create-a-dashboard-user-with-the-api">}}).
```

2023-07-11 20:53 UTC, letzya submitted a review, later dismissed
Lots of the images are still under the static directory. We could have helped but this PRalso has conflicts

2023-07-13 16:20 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +1. Add the redirect url found on the OpenID Connect site to the redirect urls found under the Web section
added

2023-07-13 18:01 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +2. Copy the OpenID Connect endpoint
added

2023-07-14 09:00 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< include "api-def-custom-analytics" >}}
This is not showing up. can you please review the preview link?

2023-07-14 09:00 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< include "api-def-custom-analytics" >}}
Also why do we need to move this to an include file

2023-07-14 17:24 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
> +4. Test that it works:
images and header added

2023-07-14 17:45 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< include "api-def-custom-analytics" >}}
that link was a part of the merge conflict which has since been resolved.

2023-07-14 18:09 UTC, zalbiraw approved these changes
LGTM

2023-07-17 09:42 UTC, dcs3spp approved these changes

2023-07-17 09:49 UTC, merged

2023-07-17 09:53 UTC, dcs3spp commented
/release to release-5.1

2023-07-17 09:53 UTC, dcs3spp commented
/release to release-5