Re-write of the MDCB docs
TykTechnologies/tyk-docs-hugo pull request #2093
Opened 2022-11-30 10:31 UTC by andyo-tyk

New content for the first page of the MDCB documentation - including links to nowhere in "Next Steps" (pages that need to be created)

2022-12-03 08:29 UTC, letzya commented
@andyo-tyk can you please look at the diff between the existing version and yours and confirm you want to remove all this content and links? 
Also - it's best if we have at least 3 links in a page to connect the users to other options

2022-12-04 18:34 UTC, letzya requested changes
Per my comments throughout Thr text

2022-12-04 18:34 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +## Tyk Controller
I don't think we use the term "controller" outside tyk cloud.
We usually use the term "control place data centre" or just "control plane"

2022-12-04 18:34 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +Here we will give an overview of the main elements of an MDCB solution, clarifying the terminology used by Tyk.
we don't explain "mdcb" but use it already. As such, maybe we should move the mdcb bullet to the top of this list?

2022-12-04 18:34 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- the backbone of the distributed Tyk deployment, connecting the different Gateway clusters back to the management cluster
```suggestion
- the backbone of the distributed Tyk deployment, connecting the different Gateway clusters back to the management control plane.
```

2022-12-04 18:34 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +Tyk’s Multi Data Centre Bridge (MDCB) is a separately licensed extension to the Tyk control plane that performs management and synchronisation of logically or geographically distributed clusters of T
Don't you want to use titles like "## Introduction"? this text is at the top of the page and looks like it is more readable with a title.

2022-12-13 23:50 UTC, letzya requested changes

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +Tyk’s Multi Data Centre Bridge (MDCB) is a separately licensed extension to the Tyk control plane that performs management and synchronisation of logically or geographically distributed clusters of T
`is a separately licensed extension to the Tyk control plane` - repeated again in line 50

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> -The communication between instances works through a compressed RPC TCP tunnel between the gateway and MDCB, it is incredibly fast and can handle 10,000's of transactions per second.
@andyo-tyk can we please make sure this info goes somewhere?

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +**Tyk Gateway**
```suggestion
### Tyk Gateway
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +**Tyk Gateway**
I suggest using header definitions instead of bold so we have a formated structure. Same for the following titles

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +**Redis**
```suggestion
### Redis
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +**MongoDB/SQL**
```suggestion
### MongoDB/SQL
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +**Multi Data Centre Bridge (MDCB)**
```suggestion
### Multi Data Centre Bridge (MDCB)
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +**Tyk Dashboard**
```suggestion
### Tyk Dashboard
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +**Tyk Pump**
```suggestion
### Tyk Pump
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +**Developer Portal**
```suggestion
### Developer Portal
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +## Tyk Controller
```suggestion
## Tyk Control plane
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +The Controller cluster is where the components required to create MDCB’s shared control plane are located and must consist of the following elements:
```suggestion
The control plane contains consists of the following elements:
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- Tyk Dashboard (used to configure and control the whole Tyk installation)
```suggestion
- **Tyk Dashboard** (used to configure and control the whole Tyk installation)
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- Tyk Gateway (this is refered to as the Management/Controller GW and will not service API transactions; it is important to ensure this is not public facing)
```suggestion
- **Tyk Gateway** - This gateway is configured without tags/segments so it can load all the available APIs. For this reason, it is referred to as `a management gateway`. It is used for keys and certificates creations and does not service API requests. As such, it is important to ensure there's no public access to it.
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- Tyk MDCB
```suggestion
- **Tyk MDCB**
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- High availability Redis data store (used as primary reference for the deployment)
```suggestion
- **Redis** - High availability Redis data store. This deployment should be backed up in case of failure. (Check this [doc]{{< ref "https://redis.io/docs/management/persistence/) for recommendation on Redis persistency >}}
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- A high availability persistent data store (e.g. MongoDB or SQL replica set)
```suggestion
- **MongoDB or SQL** - A persistent data store. Should be deployed and set up for redundancy and high availability 
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +To improve resilience and availability, multiple instances of each Tyk component should be deployed and load balanced within the cluster.
```suggestion
<br>
To improve resilience and availability, multiple instances of each Tyk component should be deployed and load-balanced within the cluster.
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +To improve resilience and availability, multiple instances of each Tyk component should be deployed and load balanced within the cluster.
Without this break this line continues the previous bullet https://github.com/TykTechnologies/tyk-docs/pull/2093/files?short_path=c4271bf#diff-c4271bf7c2fc706dc8a930992ce43b562dd17b714bbab72251e4c171f78b83a8

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- One or more Tyk Pumps can be deployed within the controller cluster to export transaction logs to your choice of external data sinks for further analytics and visualisation.
```suggestion
- **Tyk Pump** - Tyk Pumps can be deployed in the control plane to export analytics data (requests/responses) to your [data sink of choice]({{< ref "https://tyk.io/docs/tyk-stack/tyk-pump/other-data-stores/" >}}) for further analytics and visualisation.
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- A Tyk Developer Portal should be deployed within the controller cluster to enhance the end user experience when accessing your APIs; multiple Developer Portals can be deployed - for example for int
```suggestion
- **Tyk Developer Portal** - can be added to enhance the end-user experience when accessing your APIs; multiple Tyk Developer Portals can be deployed, for example for internal and external consumers.
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- A Tyk Developer Portal should be deployed within the controller cluster to enhance the end user experience when accessing your APIs; multiple Developer Portals can be deployed - for example for int
`multiple Tyk Developer Portals can be deployed, for example for internal and external consumers.` - @andyo-tyk are you sure about this?

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- One or more Tyk Gateway instance(s) specifically configured as Workers
```suggestion
- **Tyk gateway** - Tyk Gateway that is specifically configured as Workers. To provide resilience and availability deploy multiple Tyk Gateways with a load balancer.
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- A single Redis data store shared by all Gateways in the cluster
```suggestion
- **Redis** - A single Redis data store shared by all Gateways in the cluster. If you want this data centre to be resilient, available, and independent from its control plane during a disconnection event, it is advised to keep it persistent.
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +To improve resilience and availability, multiple instances of each Tyk component should be deployed and load balanced within the cluster.
not really needed since it was already mentioned above

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +To improve resilience and availability, multiple instances of each Tyk component should be deployed and load balanced within the cluster.
```suggestion
```

2022-12-13 23:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- One or more Tyk Pumps can be deployed within the worker cluster to export transaction logs to your choice of external data sinks for further analytics and visualisation.
```suggestion

- **Tyk Pump** - Optional. Tyk Pump that is specifically configured as [hybrid pump]({{< ref "release-notes/version-2.8/#custom-analytics-storage-engines-for-multi-cloud--enterprise-mdcb-users" >}}) can be deployed in the worker data centre. This pump will send analytics data (requests/responses) to external data sinks from within this local/regional data center and will help with further analytics and visualisation. 
```

2022-12-19 13:31 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +Here we will give an overview of the main elements of an MDCB solution, clarifying the terminology used by Tyk.
I don't think we should move the MDCB bullet to the top. I went straight to the abbreviation as this is the second page where we go into more detail looking inside the clusters that were introduced on the first page... however happy to add the full text first.

2022-12-19 15:06 UTC, andyo-tyk commented
> Also - it's best if we have at least 3 links in a page to connect the users to other options

I've got links at the bottom of each page - I was hoping that Mark would sort out directing them to the right pages as I wasn't sure what URLs to use.

2022-12-19 17:15 UTC, andyo-tyk reviewed
I've added comments to your suggestions.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +**Tyk Gateway**
OK

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- the backbone of the distributed Tyk deployment, connecting the different Gateway clusters back to the management cluster
I'm trying to be consistent with terminology - and specifically I am refering to clusters of components that are distributed (potentially in different data centres/regions) that carry API traffic and the fact that they all connect back to a single cluster of components that does the management.
So I don't disagree with you that the function of the "management cluster" is to provide the "control plane", but here I'm deliberately choosing to use the word cluster.
I've changed "gateway cluster" to "worker cluster" for consistency with the following sections.
I hope this makes sense.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +## Tyk Controller
I've modified this to Management Cluster to match the usage further up the page. Just trying to be consistent on this page. It can be changed easily later as and when a decision is made on naming. My preference is that the Tyk Gateway is just called Tyk Gateway - and it is the cluster/deployment that is assigned Controller/Worker or Management/Worker or Control Plane/Data Plane or whatever naming we come up with....

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +## Tyk Controller
Changed to "Management Cluster"

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +The Controller cluster is where the components required to create MDCB’s shared control plane are located and must consist of the following elements:
I agree, this was way too wordy. I've made some changes in common with the terminology used on the page.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- Tyk Dashboard (used to configure and control the whole Tyk installation)
I'm not sure it needs to be in bold, but have added this as requested.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- Tyk Gateway (this is refered to as the Management/Controller GW and will not service API transactions; it is important to ensure this is not public facing)
I thought to keep this simple and have removed all mention of it being "refered to as the management gateway". I have merged in your wording about keys/certificates.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- High availability Redis data store (used as primary reference for the deployment)
The suggested format for the link doesn't look right in the preview, so I've just gone for `[doc]("link")` .

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- One or more Tyk Pumps can be deployed within the controller cluster to export transaction logs to your choice of external data sinks for further analytics and visualisation.
As above, I've simplified the format of the link - and used the name Management Cluster for consistency.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +To improve resilience and availability, multiple instances of each Tyk component should be deployed and load balanced within the cluster.
I'd prefer to keep the notes about resilience/availability in a separate note below the list of components (for consistency with the Management Cluster above). I've added your comments about the Redis config.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- A Tyk Developer Portal should be deployed within the controller cluster to enhance the end user experience when accessing your APIs; multiple Developer Portals can be deployed - for example for int
That's my understanding, yes. But I'll remove it given your uncertainty.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- One or more Tyk Gateway instance(s) specifically configured as Workers
I'd prefer to keep the note about resilience/availability in a separate note below the list of components (for consistency with the Management Cluster above).

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- A single Redis data store shared by all Gateways in the cluster
I'd prefer to keep the note about resilience/availability in a separate note below the list of components (for consistency with the Management Cluster above).

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- One or more Tyk Pumps can be deployed within the worker cluster to export transaction logs to your choice of external data sinks for further analytics and visualisation.
I've embedded the full URL to the release notes, hope that's the right thing to do.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +Tyk’s Multi Data Centre Bridge (MDCB) is a separately licensed extension to the Tyk control plane that performs management and synchronisation of logically or geographically distributed clusters of T
Added

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +Tyk’s Multi Data Centre Bridge (MDCB) is a separately licensed extension to the Tyk control plane that performs management and synchronisation of logically or geographically distributed clusters of T
Good spot - it was originally only on line 50 but then I added the introduction sentence later and forgot to remove it. I've merged line 50 into this one.

2022-12-19 17:15 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> -The communication between instances works through a compressed RPC TCP tunnel between the gateway and MDCB, it is incredibly fast and can handle 10,000's of transactions per second.
I plan to have a separate section for "Advanced MDCB" - this page is intended as an introduction to MDCB following the concept of progressive disclosure.

2023-01-06 15:34 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> -The communication between instances works through a compressed RPC TCP tunnel between the gateway and MDCB, it is incredibly fast and can handle 10,000's of transactions per second.
I've added this in the new page:
tyk-docs/content/tyk-stack/tyk-multi-data-centre/advanced-mdcb/mdcb-technical-overview.md
(covered by draft PR #2145)

2023-01-06 15:36 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- High availability Redis data store (used as primary reference for the deployment)
I've now seen the Confluence advice on documentation and understand the <<ref>> markdown. I will revise the links.

2023-01-06 16:20 UTC, andyo-tyk commented
Changes made to correct the link style (to use ({{< ref ““ >}}) format).

2023-01-10 16:16 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-components.md
> +- **Tyk Gateway** (used for creation of keys and certificates, this does not service API requests; it is important to ensure there is no public access to it and it must not be tagged, zoned or sharde
```suggestion
- **Tyk Gateway** (used for creation of keys and certificates, this does not service API requests; it is important to ensure there is no public access to it and it must not be shared (tagged) as it "belongs" to the whole Tyk installation)
```

2023-01-10 16:19 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> -MDCB-worker gateways are tied to a single organisation in the Dashboard. This means that you can set up different teams as organisations in the Dashboard, and each team can run it's own set of Gatewa
This content is super important. Do we cover it somewhere?

2023-01-10 16:44 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> +- You can physically segment teams and environments within a single data centre, giving each team full control of its own cluster and server resources without the noisy neighbours you might experienc
```suggestion
- You can physically [segment teams and environments]({{< ref "/advanced-configuration/manage-multiple-environments/with-tyk-multi-cloud.md" >}}) within a single data centre, giving each team full control of its own cluster and server resources without the noisy neighbours you might experience in a standard self-managed deployment.
```

2023-01-10 17:00 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/tyk-multi-data-centre.md
> -MDCB-worker gateways are tied to a single organisation in the Dashboard. This means that you can set up different teams as organisations in the Dashboard, and each team can run it's own set of Gatewa
I think this should go in the proposed new "Advanced MDCB" section where we can explain in more detail this use case and how to configure it. I find the original wording unclear.

2023-01-11 10:10 UTC, letzya commented
> Changes made to correct the link style (to use ({{< ref ““ >}}) format).

Cannot see it in the diff

2023-01-12 02:05 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-example-minimising-latency.md
> + - [Advanced MDCB]({{< ref "/tyk-stack/tyk-multi-data-centre/advanced-mdcb/advanced-mdcb.md" >}})
@andyo-tyk this file doesnt seems to exist. Where did you wanted to redirect the user?

2023-01-12 11:12 UTC, andyo-tyk commented on tyk-docs/content/tyk-stack/tyk-multi-data-centre/mdcb-example-minimising-latency.md
> + - [Advanced MDCB]({{< ref "/tyk-stack/tyk-multi-data-centre/advanced-mdcb/advanced-mdcb.md" >}})
That's a new file - adding in a separate PR (mdcb-docs-rewrite-pt2). I'll delete that line and add it back in in the second PR.

2023-01-15 11:32 UTC, letzya requested changes

2023-01-15 11:32 UTC, letzya commented on tyk-docs/content/mdcb-example-minimising-latency.md
> +By deploying an MDCB Controller, however, they are able to centralise the management of their API Gateways and gain resilience against failure of different elements of the deployment - worker gateway
```suggestion
By using Tyk's Multi-Data Centre Bridge (MDCB), however, they are able to centralise the management of their API Gateways and gain resilience against failure of different elements of the deployment - worker gateways or control plane - improving the availability of their public APIs.
```

2023-01-15 11:32 UTC, letzya commented on tyk-docs/content/mdcb-example-minimising-latency.md
> +Without MDCB, Acme Global Bank would deploy a Tyk Gateway cluster in each data centre and then have the operational inconvenience of maintaining two separate instances of Tyk Dashboard to configure,
```suggestion
Without a dedicated solution for this multi-regions use case, Acme Global Bank would deploy a Tyk Gateway cluster in each data centre and then have the operational inconvenience of maintaining two separate instances of Tyk Dashboard to configure, secure and publish the APIs.
```

2023-01-16 09:19 UTC, andyo-tyk commented on tyk-docs/content/mdcb-example-minimising-latency.md
> +By deploying an MDCB Controller, however, they are able to centralise the management of their API Gateways and gain resilience against failure of different elements of the deployment - worker gateway
Makes sense.

2023-01-16 09:20 UTC, andyo-tyk commented on tyk-docs/content/mdcb-example-minimising-latency.md
> +Without MDCB, Acme Global Bank would deploy a Tyk Gateway cluster in each data centre and then have the operational inconvenience of maintaining two separate instances of Tyk Dashboard to configure,
Makes sense.

2023-01-18 16:08 UTC, letzya approved these changes

2023-01-18 16:08 UTC, merged

2023-01-18 16:32 UTC, letzya commented
/release to release-4.3