Technical SEO audit line 9 - 3XX redirect
TykTechnologies/tyk-docs-hugo pull request #2095
Opened 2022-12-01 15:02 UTC by madebyguie

Technical SEO audit - line 9 of document - redirects

2023-01-05 20:56 UTC, letzya requested changes
conflicts to resolve

2023-01-05 20:56 UTC, letzya commented on _redirects
> -/docs/basic-config-and-security/security/authentication-authorization/oauth2.0/refresh-token-grant/ /docs/basic-config-and-security/security/authentication-authorization/oauth2-0/refresh-token-grant
This file is auto-gen. need to remove it from the PR

2023-01-05 20:56 UTC, letzya commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +This plugin allows you to translate an outbound API interface to your internal structure of your services. See [URL Rewriting](/docs/transform-traffic/url-rewriting/) for more details.
Need to update it to use `{{< ref "" }}`

2023-01-05 20:56 UTC, letzya commented on tyk-docs/content/api-management/api-management.md
> +There are many open and closed source [Tyk components](/docs/tyk-stack/) that make up the various solutions.
change to `{{< ref "" >}}`

2023-01-05 20:56 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/Authentication & Authorization/json-web-tokens.md
> +If Tyk cannot find a `pol` claim, it will apply this Default Policy. Select a policy that gives access to this API we are protecting, or [go create one first](/docs/getting-started/create-security-po
change link to {{< ref "" >}}

2023-01-11 14:50 UTC, closed without merging

2023-01-11 14:50 UTC, itsmartins commented
Redundant PR