Add guides to monitor Tyk
TykTechnologies/tyk-docs-hugo pull request #2096
Opened 2022-12-01 16:17 UTC by sedkis

2022-12-02 16:43 UTC, letzya requested changes
Can you please add description and tags to `benchmarks.md` (copy them from `tyk-component-monitoring.md` and update accordingly)

2022-12-02 17:19 UTC, letzya requested changes

2022-12-02 17:19 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-component-monitoring.md
> +The Gateway & Redis are the only components that will have a high on demand performance requirement, that scales with your API traffic.
```suggestion
The Gateway & Redis are the only components that will have a high on-demand performance requirement, which needs to scale with your API traffic.
```

2022-12-02 17:19 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-component-monitoring.md
> +### CPU Utilisation
```suggestion
### Tyk Gateway CPU Utilisation
```

2022-12-02 17:19 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-monitoring.md
> +- are you committed to your SLOs?
```suggestion
- Are you committed to your SLOs?
```

2022-12-02 17:19 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-component-monitoring.md
> +```
```suggestion
```console
```

2022-12-02 17:19 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-monitoring.md
> +### Why Is It Important?
I don't recall having a standard to capitalize every word in the title, or am I wrong?

2022-12-02 17:19 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-monitoring.md
> +Infrastructure sizing, benchmarks, and scaling will be explained in [this section][1].
```suggestion
Infrastructure sizing, benchmarks, and scaling will be explained in [this section](({{< ref "/content/planning-for-production/benchmarks/ >}}).
```

2022-12-02 17:19 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-monitoring.md
> +[1]: /docs/planning-for-production/benchmarks/
```suggestion
```

2022-12-02 17:19 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-monitoring.md
> +Infrastructure sizing, benchmarks, and scaling will be explained in [this section][1].
Let netlify build this link

2022-12-06 14:29 UTC, sedkis commented on tyk-docs/content/planning-for-production/monitoring/tyk-monitoring.md
> +### Why Is It Important?
Done

2022-12-06 16:26 UTC, letzya approved these changes

2022-12-07 06:21 UTC, merged