Changelog for MDCB 2.0.4 release
TykTechnologies/tyk-docs-hugo pull request #2107
Opened 2022-12-06 18:03 UTC by tbuchaillot

Adding changelog logs for MDCB 2.0.4 release

https://github.com/TykTechnologies/tyk-sink/releases/tag/v2.0.4

2022-12-06 18:40 UTC, letzya requested changes

2022-12-06 18:40 UTC, letzya commented on tyk-docs/content/release-notes/mdcb/mdcb.md
> +## 2.0.4
Looks like this is a v2 page. Can you please rename the file and title and parent to match the format of the gateway and dashboard?  (we'd need also an alias for the url)
<img width="298" alt="image" src="https://user-images.githubusercontent.com/3155222/205994195-fc3153b5-071e-498f-b280-deac9d615c7f.png">

2022-12-06 18:41 UTC, tbuchaillot commented on tyk-docs/content/release-notes/mdcb/mdcb.md
> +## 2.0.4
@letzya as I understand, it's a whole changelog for the component - it's not a page for this version.

2022-12-06 18:42 UTC, tbuchaillot commented on tyk-docs/content/release-notes/mdcb/mdcb.md
> +## 2.0.4
if we rename it - the MDCB 2.0.4 page will have all the previous release notes too. It doesn't make sense to me tbh.

2022-12-06 18:53 UTC, letzya commented on tyk-docs/content/release-notes/mdcb/mdcb.md
> +## 2.0.4
we have pages per major and minor releases but not patches. On this page, we have only patches. the next release with 2.1 will need a new page so I'm suggesting this page be renamed to `MDCB v2.0`

2022-12-06 19:00 UTC, tbuchaillot commented on tyk-docs/content/release-notes/mdcb/mdcb.md
> +## 2.0.4
now I get it! I'll update

2022-12-06 19:36 UTC, tbuchaillot commented on tyk-docs/content/release-notes/mdcb/mdcb.md
> +## 2.0.4
![image](https://user-images.githubusercontent.com/25751713/206005836-992d049d-04a1-478e-9467-ea55e90b6d89.png)
👌

2022-12-07 11:10 UTC, andyo-tyk reviewed
Thanks Tomas - and good suggestion Yaara (the previous page was pulled together by Leo as we had nothing at all on Tyk.io before in terms of release notes for MDCB!).

2022-12-07 11:10 UTC, andyo-tyk approved these changes

2022-12-08 16:22 UTC, letzya approved these changes

2022-12-09 15:42 UTC, letzya approved these changes

2022-12-09 15:42 UTC, merged

2022-12-09 15:43 UTC, letzya commented
/release to release-4.3

2022-12-11 15:35 UTC, buger commented
/release to release-4.3