G seo technical content
TykTechnologies/tyk-docs-hugo pull request #2113
Opened 2022-12-09 09:28 UTC by itsmartins

2023-01-05 09:47 UTC, itsmartins commented
Mainly duplicated or missing H1 tags (just adapting the header level of some titles), resized large images and fixed some long meta descriptions.

2023-01-05 16:14 UTC, letzya requested changes

2023-01-05 16:14 UTC, letzya commented on tyk-docs/content/advanced-configuration/distributed-tracing/newrelic.md
> +description: "Create your own tracing implementation with Trace API, used to send distributed tracing data to New Relic, in the generic or Zipkin data format."
The new text is not clear to me. Can you please check it again

2023-01-05 16:14 UTC, letzya commented on tyk-docs/content/advanced-configuration/manage-multiple-environments/with-tyk-on-premises.md
> +## Instructions
Why is this title in the same level as the one above and not one level down with I.e. ###?

2023-01-05 16:14 UTC, letzya commented on tyk-docs/content/release-notes/version-2.4.md
> +## New in this release:
Why do we want this change?

2023-01-05 16:17 UTC, letzya requested changes

2023-01-05 16:17 UTC, letzya commented on tyk-docs/content/release-notes/version-2.5.md
> +## <a name="new"></a>New in this Release:
Agan, why do we change this?

2023-01-05 20:04 UTC, letzya requested changes

2023-01-05 20:04 UTC, letzya commented on tyk-docs/content/release-notes/version-3.2.md
> +## Bug fixes and minor changes
I'm not sure it's correct. It's on the same level as "what's new"

2023-01-05 20:04 UTC, letzya commented on tyk-docs/content/release-notes/version-3.2.md
> +## Updated Versions
same as the last message. it' level #

2023-01-05 20:04 UTC, letzya commented on tyk-docs/content/release-notes/version-3.2.md
> +## Upgrade process
again level 1, why to change it to level 2?

2023-01-05 20:34 UTC, letzya requested changes

2023-01-05 20:34 UTC, letzya commented on tyk-docs/content/shared/x-tyk-gateway.md
> -## TYK OAS API Object
Why do you want to remove this title? 
Also this is an auto-gen doc, we cannot edit it here. If we need to we need ti change the source

2023-01-05 20:34 UTC, letzya commented on tyk-docs/static/css/docs.css
> +.products h1,
what does this do?

2023-01-05 20:34 UTC, letzya commented on tyk-docs/content/release-notes/version-2.4.md
> +## New in this release:
ok, i understand level 1 looks odd

2023-01-09 18:16 UTC, itsmartins commented on tyk-docs/static/css/docs.css
> +.products h1,
This is to make sure all the titles in the home page were aligned. 
As it was missing a H1 tag, therefore I've changed what should have been a h1 which is the "Tyk API Management" title. And when it was changed, i've aligned it with the style to the other rules for the h2 tags.

This is an SEO requirement

2023-01-09 18:21 UTC, madebyguie commented on tyk-docs/content/release-notes/version-3.2.md
> +## Upgrade process
I've updated with the last commit all the titles for this page to be in the levels they should, but leaving only 1 # .

There should be only 1 level 1 in each page for SEO purposes, this is one of most important factors to make clear to google what this page is about.

2023-01-09 18:22 UTC, itsmartins commented on tyk-docs/content/release-notes/version-3.2.md
> +## Updated Versions
I've updated with the last commit all the titles for this page to be in the levels they should, but leaving only 1 # .

There should be only 1 level 1 in each page for SEO purposes, this is one of most important factors to make clear to google what this page is about.

2023-01-09 18:26 UTC, itsmartins commented on tyk-docs/content/shared/x-tyk-gateway.md
> -## TYK OAS API Object
The title was duplicated, the title for the page where this is used is in x-tyk-oas-doc.md.
This is a shared file within the "content" directory, are you sure is auto-gen doc, if it's within 'content'?

2023-01-09 18:28 UTC, itsmartins reviewed
I've updated this line. I think is better written.
The purpose of editing this is to shorten the meta description for SEO purposes

2023-01-09 18:29 UTC, itsmartins reviewed
I've updated the titles on this page to make sure that there is no repeated <h1> ( or # title ), as there can be only one, and as there was other h1 on the page I downgraded all the titles accrodingly

2023-01-09 18:29 UTC, itsmartins commented on tyk-docs/content/advanced-configuration/distributed-tracing/newrelic.md
> +description: "Create your own tracing implementation with Trace API, used to send distributed tracing data to New Relic, in the generic or Zipkin data format."
This has been fixed in the new commit

2023-07-19 21:27 UTC, letzya commented
closing till we can work on it. Ticket is updated in the subject

2023-07-19 21:27 UTC, closed without merging