ADd more explanation about rate limit
TykTechnologies/tyk-docs-hugo pull request #2114
Opened 2022-12-09 14:31 UTC by sedkis

2022-12-09 20:55 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +It also uses what's called a leaky bucket algorythm. In this case if the request rate is higher than the rate limit it will attempt to let through requests at the specified rate limit. It's important
add a link to this https://en.wikipedia.org/wiki/Leaky_bucket
isn't it `algorithm`

2022-12-09 20:57 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This uses redis to track the rate of incoming API calls. It's important to note that it blocks access to the API when the rate exceeds the rate limit. It's not like the leaky bucket algorythm, it doe
not so clear `before the 429s would stop.` - clarify what is this  http error code  and add link https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

2022-12-09 21:01 UTC, letzya requested changes
Please get another engineer to review it

2022-12-09 21:01 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +Redis rate limiter, which is 100% correct, but it also use dynamic window, which means that if there is user who abuse rate limit, it will not allow his requests, untill he start respecting rate limi
isn't it a sliding window?
Also add link to this https://developer.redis.com/develop/dotnet/aspnetcore/rate-limiting/sliding-window/

2022-12-17 19:51 UTC, zalbiraw requested changes

2022-12-17 19:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +tags: ["Rate Limit", "Rate Limiting", "Rate Limit Algos", "DRL"]
```suggestion
tags: ["Rate Limit", "Rate Limiting", "Rate Limit Algorithms", "DRL"]
```

2022-12-17 19:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +description: "Overview on Rate Limiting with the Tyk Gateway"
```suggestion
description: "Overview of Rate Limiting with the Tyk Gateway"
```

2022-12-17 19:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +It also uses what's called a leaky bucket algorythm. In this case if the request rate is higher than the rate limit it will attempt to let through requests at the specified rate limit. It's important
```suggestion
It also uses what's called a leaky bucket algorithm. In this case if the request rate is higher than the rate limit it will attempt to let through requests at the specified rate limit. It's important to note that this is the only rate limit method that uses this algorithm and that it will yield approximate results.
```

2022-12-17 19:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +1. Distributed Rate Limiter.  Most performant, not 100% perfect accuracy.  Recommended for most use cases.
```suggestion
1. Distributed Rate Limiter.  Most performant, not 100% perfect accuracy.  Recommended for most use cases. Uses the leaky bucket algorithm.
```

2022-12-17 19:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +2. Redis Rate Limiter.  Less performant, 100% perfect accuracy.
```suggestion
2. Redis Rate Limiter.  Less performant, 100% perfect accuracy. Uses the sliding window algorithm.
```

2022-12-17 19:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This relies on having a very fair load balancer since it assumes a well distributed load between all of the gateways.
```suggestion
This relies on having a fair load balancer since it assumes a well distributed load between all of the gateways.
```

2022-12-17 19:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This uses redis to track the rate of incoming API calls. It's important to note that it blocks access to the API when the rate exceeds the rate limit. It's not like the leaky bucket algorythm, it doe
```suggestion
This uses redis to track the rate of incoming API calls. It's important to note that it blocks access to the API when the rate exceeds the rate limit. Unlike the leaky bucket algorithm, it doesn't let API calls through until the rate drops below the rate limit for the period of time that the limit uses. For example if the rate limit is 3000/minute the call rate would have to be reduced below 3000 for a whole minute before the 429s would stop.
```

2022-12-17 19:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +Redis rate limiter, which is 100% correct, but it also use dynamic window, which means that if there is user who abuse rate limit, it will not allow his requests, untill he start respecting rate limi
```suggestion
Redis rate limiter, is 100% correct, but it uses the sliding window algorithm instead of the leaky bucket. This means that if there is a user who abuses the rate limit, this user's requests will be limited until they start respecting the rate limit. In other words, requests that return 429 (Rate Limit Exceeded) will count towards their rate limit counter.
```

2022-12-17 19:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +In case when you have small rate limit with big amount of servers, Gateway always switch to Redis rate limiter, which means that you can have only moving window algorithm in that case. And clients wh
I don't understand this.

2022-12-17 20:16 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +1. Distributed Rate Limiter.  Most performant, not 100% perfect accuracy.  Recommended for most use cases. Uses the leaky bucket algorithm.
```suggestion
1. Distributed Rate Limiter.  Most performant, not 100% perfect accuracy.  Recommended for most use cases. Uses the [leaky bucket algorithm](https://en.wikipedia.org/wiki/Leaky_bucket).
```

2022-12-17 20:16 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +Redis rate limiter, provides 100% accuracy, however instead of using the leaky bucket algorithm it uses the sliding window algorithm. This means that if there is a user who abuses the rate limit, thi
```suggestion
Redis rate limiter, provides 100% accuracy, however instead of using the leaky bucket algorithm it uses the sliding window algorithm. This means that if there is a user who abuses the rate limit, this user's requests will be limited until they start respecting the rate limit. In other words, requests that return [429 (Rate Limit Exceeded)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) will count towards their rate limit counter.
```

2022-12-17 20:16 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +2. Redis Rate Limiter.  Less performant, 100% perfect accuracy. Uses the sliding window algorithm.
```suggestion
2. Redis Rate Limiter.  Less performant, 100% perfect accuracy. Uses the [sliding window algorithm](https://developer.redis.com/develop/dotnet/aspnetcore/rate-limiting/sliding-window/).
```

2022-12-19 14:11 UTC, zalbiraw requested changes

2022-12-19 14:11 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +`TYK_GW_DRLTHRESHOLD`
We should also add the non-transactional to this.

2022-12-21 13:12 UTC, buger approved these changes

2022-12-21 13:44 UTC, zalbiraw approved these changes

2022-12-21 13:54 UTC, merged

2022-12-21 13:54 UTC, buger commented
/release to release-4.3