Added in all error codes documented so far for clients that have been asking for it
TykTechnologies/tyk-docs-hugo pull request #2128
Opened 2022-12-14 19:13 UTC by dle519

Very rough look of all the information obtained so far currently. Will be used for clients that have been asking for it for a long time. Should be able to clean it up in the future.

2022-12-16 16:03 UTC, letzya requested changes, later dismissed
Please update to use headings (##) instead of bold font (**)

2022-12-16 16:03 UTC, letzya commented on tyk-docs/content/error-codes/error-codes.md
> +**Error Code 400:**
```suggestion
## Error Code 400:
```

2022-12-16 16:04 UTC, letzya commented
@dle519 please assign this PR to a peer engineer for review

2022-12-27 19:03 UTC, vverbani commented
@dle519 not authorized to merge this PR unfortunately

2022-12-30 15:18 UTC, dle519 commented on tyk-docs/content/error-codes/error-codes.md
> +**Error Code 400:**
Updated!

2023-01-03 15:00 UTC, JRWu submitted a review, later dismissed
This is a good start at documenting the error codes. I think the user-added comments within parenthesis need to be elaborated on a bit further- think about it from the perspective of a new user. Are they going to understand what "policyUpdateHandler" means, or do they need more clarification? 

The tabbing is inconsistent- why is it only tabbed in some explanations but not other?

Perhaps try sorting the error messages per response code alphabetically- that way it's easier for users to read and consume. 

Additionally, and this might be a different piece of work- perhaps we should be adding potential resolutions to each error code, or descriptions on why they occur. End users who search for these error codes should be given a path to resolve the error- either through links to our documentation or a FAQ section illustrating the fix.

2023-01-03 15:00 UTC, JRWu commented on tyk-docs/content/error-codes/error-codes.md
> +date: 2022-12-13
Is this date accurate? Perhaps it would be more informative to specify what version(s) of Tyk this document covers.

2023-01-03 15:00 UTC, JRWu commented on tyk-docs/content/error-codes/error-codes.md
> +description: "Response codes that the gateway returns via an API"
I believe our stance is to use "Tyk Gateway", or capitalize Gateway when referencing it

https://tyktech.atlassian.net/wiki/spaces/MAR/pages/1428848683/Copywriting+at+Tyk+Our+house+style

2023-01-03 15:00 UTC, JRWu commented on tyk-docs/content/error-codes/error-codes.md
> +- TBD
What is TBD?

2023-01-03 15:00 UTC, JRWu commented on tyk-docs/content/error-codes/error-codes.md
> +- TBD
TBD Again, this acronym needs to be expanded upon or removed

2023-01-03 15:00 UTC, JRWu commented on tyk-docs/content/error-codes/error-codes.md
> +- ErrAPINotMigrated (oasEndpoint)
New users aren't going to understand what oasEndpoint is, perhaps elaborate on this point further?
What is this error?

2023-01-03 15:00 UTC, JRWu commented on tyk-docs/content/error-codes/error-codes.md
> +- Couldn’t decode instruction (policyUpdateHandler)
What is policyUpdateHandler? This should be more informative to the end user; what instruction couldn't be decoded?

2023-01-03 15:00 UTC, JRWu commented on tyk-docs/content/error-codes/error-codes.md
> +- TBD
TBD again

2023-01-03 15:00 UTC, JRWu commented on tyk-docs/content/error-codes/error-codes.md
> +  - JWT → id is in the ‘sub’ claim while the ‘kid’ claim in the header is not empty
Why is there tabbing here but not in the other error codes? Is there a reason why the formatting is different

2023-01-03 21:23 UTC, dle519 commented on tyk-docs/content/error-codes/error-codes.md
> +- TBD
I dont know what the exact acronym stands for but I read in the documentation that its convention for when the section is a WIP (work in progress).

2023-01-03 21:31 UTC, vverbani commented on tyk-docs/content/error-codes/error-codes.md
> +- TBD
to be determined?

2023-01-03 21:50 UTC, JRWu commented on tyk-docs/content/error-codes/error-codes.md
> +- TBD
If you've added all of the error codes & their respective messages TBD can be removed, it's not necessary to keep it here.

2023-01-03 22:04 UTC, dle519 commented on tyk-docs/content/error-codes/error-codes.md
> +- TBD
The information so far is all the error codes that I have found so far so there is still quite a lot of error codes that I haven't discovered yet. We are trying to publish what we have so far because clients have been asking for it so we thought a WIP might help them. Thats why the formatting of this looks very very rough at the moment since I am focusing on just getting the data out there.

2023-01-06 20:25 UTC, oluwaseyeayinla commented
@JRWu Good job. I like this approach showing relevant information very quickly. I think we should make some of the errors a bit more descriptive and readable. Things like testGRPCIgnore - no header, ErrImportWithTykExtension etc.

I also think we can expatiate on potential causes for very generic error messages e.g. Access to this API has been disallowed. I see you have done a couple with Key not authorised, OAuth and versioning. 

Access to this API has been disallowed
- Check if API definition is disabled
- Check if you are using the correct key/auth token
- Refer to some other error page or a doc link (if all fails)

The main aim would be to try not to repeat ourselves all over the page, since some errors have similarities in what to check or validate

2023-01-12 14:39 UTC, dle519 commented on tyk-docs/content/error-codes/error-codes.md
> +- TBD
added an acronym in parenthesis for it

2023-01-12 14:45 UTC, dle519 commented on tyk-docs/content/error-codes/error-codes.md
> +  - JWT → id is in the ‘sub’ claim while the ‘kid’ claim in the header is not empty
changed the format to be more consistent

2023-01-23 15:27 UTC, vverbani commented
1. */error-codes/error-codes/ URL should be error-response-codes
- This gets rid of the duplicate error-codes plus it better outlines the page for SEO/user readability purposes

2. I don't like how this page is listed as WIP and TBD (to be determined?)
we're in charge of this, clients don't need to know this portion imo. We can continue to work this on the backend and push content for this page after publishing the initial draft

- Instead, we can add a general statement something along the lines of ** as Tyk continues to scale, so will the error response codes. As such, we'll going to do our best to coordinate them on this page**

3. I don't like how the tables look. Some have descriptions while others don't. The part that mostly bothers me is that the same table is scattered. I think for a UI perspective it would look better if we did one of the following:

a. List all under one table, but move all the response messages with their descriptions to the top while the ones without descriptions are all moved to the bottom
b. Divide them into two tables, first with a description while second tables have no descriptions
Also why were some of these left blank. I realize they're self explanatory but could easily just write things like Your request is missing the 'api_id' key value pair

2023-03-09 18:37 UTC, vverbani requested changes
Just these 2 changes then it can be updated with branch / merged into branch 

@dle519 @letzya

2023-03-09 18:37 UTC, vverbani commented on tyk-docs/content/error-response-codes.md
> +| Code: | Text                                                                                    | Description
Just Code, not Code:

2023-03-09 18:37 UTC, vverbani commented on tyk-docs/content/error-response-codes.md
> +| x509  | Certificate signed by unknown authority                                                 | A client accessing Tyk with full ControlAPI access without a certificate.
Not a response code so I would get rid of x509

2023-03-09 18:43 UTC, letzya commented on tyk-docs/content/error-response-codes.md
> +| x509  | Certificate signed by unknown authority                                                 | A client accessing Tyk with full ControlAPI access without a certificate.
Not sure I understand

2023-03-09 18:44 UTC, letzya commented on tyk-docs/content/error-response-codes.md
> +This table contains the error codes that could possibly show up when using the Gateway. Each error code has a text and a description of what could have caused the error. **As Tyk continues to grow, s
Please reword to a formal tone

2023-03-09 18:44 UTC, letzya commented on tyk-docs/content/error-response-codes.md
> +This table contains the error codes that could possibly show up when using the Gateway. Each error code has a text and a description of what could have caused the error. **As Tyk continues to grow, s
maybe @chrisanderton  can advise

2023-03-09 18:45 UTC, letzya commented on tyk-docs/content/error-response-codes.md
> +| x509  | Certificate signed by unknown authority                                                 | A client accessing Tyk with full ControlAPI access without a certificate.
```suggestion                                                                                                                                                                                                                                                                                                                               |
```

2023-03-09 18:45 UTC, letzya commented on tyk-docs/content/error-response-codes.md
> +| Code: | Text                                                                                    | Description
```suggestion
| Code | Text                                                                                    | Description                                                                                                                                                                                                                                                                                                                                                                                                      |
```

2023-03-09 22:15 UTC, chrisanderton commented on tyk-docs/content/error-response-codes.md
> +This table contains the error codes that could possibly show up when using the Gateway. Each error code has a text and a description of what could have caused the error. **As Tyk continues to grow, s
Should we call them "Error response _status_ codes" to be consistent with [HTTP language](https://httpwg.org/specs/rfc9110.html#overview.of.status.codes)?

We could probably borrow some of that for the intro too..?

Probably shouldn't say "we'll do our best" as it doesn't inspire confidence. In the olden days, this kind of table would be generated directly from code, as the dictionary of codes and descriptions would be in a single file with constants and used consistently.. do we do that here?

<hr/>

Responses from the Gateway include a three-digit status code that describes the result of the request and the semantics of the response. The first digit of the status code defines the class of response. The error status codes used by the Gateway are defined in the table below.

- **1xx (Informational):** The request was received, continuing process
- **2xx (Successful)**: The request was successfully received, understood, and accepted
- **3xx (Redirection)**: Further action needs to be taken in order to complete the request
- [**4xx (Client Error)**](): The request contains bad syntax or cannot be fulfilled
- [**5xx (Server Error)**](): The server failed to fulfill an apparently valid request

2023-03-30 16:14 UTC, dle519 commented on tyk-docs/content/error-response-codes.md
> +This table contains the error codes that could possibly show up when using the Gateway. Each error code has a text and a description of what could have caused the error. **As Tyk continues to grow, s
To my knowledge, i dont think theres a table that can be generated directly from the code. These codes were manually found within the code so there could be still some error codes missing from this table.

2023-03-30 16:26 UTC, vverbani commented on tyk-docs/content/error-response-codes.md
> +This table contains the error codes that could possibly show up when using the Gateway. Each error code has a text and a description of what could have caused the error. **As Tyk continues to grow, s
This isn't auto generated. It would be amazing if it was - definitely feature request Jira ticket worthy for this (David maybe you can create a ticket for this).

This PR was more of to help our customers during their environment set up/debugging until we get a more automatic version up and running. On the Support/Post-sales side we've had a lot of customers ask for this

2023-04-11 17:01 UTC, vverbani commented on tyk-docs/content/error-response-codes.md
> +This table contains the error codes that could possibly show up when using the Gateway. Each error code has a text and a description of what could have caused the error. **As Tyk continues to grow, s
@letzya @dle519 @chrisanderton what are your thoughts? Can we move forward with the merge ?

2023-04-12 14:16 UTC, dle519 commented on tyk-docs/content/error-response-codes.md
> +This table contains the error codes that could possibly show up when using the Gateway. Each error code has a text and a description of what could have caused the error. **As Tyk continues to grow, s
looks good to merge for me!

2023-04-19 19:20 UTC, letzya commented
@dle519 please get peer review approval and change to "ready for review" if it's ready.

2023-04-19 19:27 UTC, letzya commented on tyk-docs/content/error-response-codes.md
> +description: "Error response codes that the Tyk Gateway (v4.3.0) returns via an API"
```suggestion
description: "Error response codes that the Tyk Gateway returns via an API"
```

2023-04-19 19:36 UTC, letzya commented on tyk-docs/content/error-response-codes.md
> +Responses from the Gateway include a three-digit status code that describes the result of the request and the semantics of the response. The first digit of the status code defines the class of respon
```suggestion
Tyk gateway responses include HTTP status codes that follow the [HTTP standard](https://datatracker.ietf.org/doc/html/rfc9110). They have three digits that describe the result of the request and the semantics of the response. The first digit defines the class of response as shown in the [list](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) below:
```

2023-04-19 19:37 UTC, letzya commented on tyk-docs/content/error-response-codes.md
> +
```suggestion

The error status codes (4xx and 5xx) used by Tyk Gateway are defined in the table below:
```

2023-04-21 14:59 UTC, vverbani approved these changes

2023-04-24 16:11 UTC, merged

2023-04-24 16:17 UTC, letzya commented
/release to release-5

2023-04-24 17:08 UTC, buger commented
/release to release-5