Custom plugins Rewrite
TykTechnologies/tyk-docs-hugo pull request #2135
Opened 2022-12-18 21:02 UTC by sedkis

Re-word the custom plugins bit to further declutter.

Simplify by making the navigation geared towards new starters, with an easy-walk-through tutorial of building and deploying their first custom plugin.

Also, recommend Go plugins as preferred plugin type.

2022-12-29 17:07 UTC, JRWu requested changes
Great draft, requesting minor punctuation/grammar changes as well as including extra links to enrich the draft.

2022-12-29 17:07 UTC, JRWu commented on tyk-docs/content/plugins.md
Should we align with the [Request Middleware Chain](https://tyk.io/docs/concepts/middleware-execution-order/)? 
i.e. Custom pre-middlewares, Auth layer, Custom post-auth middleware, Custom post-middlewares, response" 

Also from the API Definitions:
"pre"
"post"
"post_key_auth"
"auth_check"
"response" 
?

2022-12-29 17:07 UTC, JRWu commented on tyk-docs/content/plugins.md
> +*   [Golang native plugins]({{< ref "plugins/supported-languages/golang" >}})
We should move Golang to be the first option if we recommend Golang plugins & it also works nicer from an alphabetical standpoint:

 i.e.
Golang
Javascript
Python, Lua, gRPC (Rich Plugins)

2022-12-29 17:07 UTC, JRWu commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +title: Get Started with Custom Plugins
Perhaps we should make it

"Get Started with Custom Go Plugins"

2022-12-29 17:07 UTC, JRWu commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +this page takes you through getting started with your first Custom Plugin.
Perhaps could reword to:

"This section takes you through the development process of creating a Custom Go Plugin."

2022-12-29 17:07 UTC, JRWu commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +## Prerequisites
Should we also mention what OS/Architecture this guide is written for?

i.e. 
OSX (Intel)

2022-12-29 17:07 UTC, JRWu commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +1. We've bootstrapped our Tyk organization
Should add punctuation after "organization."

2022-12-29 17:07 UTC, JRWu commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +3. We've sent an API request to the Gateway, and modified the API request in-flight using the Custom Go Plugin
Should add punctuation after "Custom Go Plugin."

2022-12-29 17:07 UTC, JRWu commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +This command generates a production grade "bundle" from the sample Go plugin in the repo.
I think this is the first mention of "bundle" with respect to Custom Go Plugins here, perhaps we should have a link to [bundle documentation](https://tyk.io/docs/plugins/how-to-serve-plugins/plugin-bundles/) as well as caveats that illustrate naming convention of bundles and best practices around bundling & maintaining bundles for plugins.

2022-12-30 10:57 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +title: Get Started with Custom Plugins
I don't think so, I don't even want to make it look like a choice, we just want them using Go

2023-01-03 22:26 UTC, JRWu approved these changes
LGTM! Pulled & built docs locally, links and formatting look good.

2023-01-05 16:12 UTC, letzya requested changes

2023-01-05 16:12 UTC, letzya commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +title: Task 2 - Test Your Go Plugin
@sedkis can you please add tags?

2023-01-05 16:12 UTC, letzya commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +```
```suggestion
```json
```

2023-01-05 16:12 UTC, letzya commented on tyk-docs/content/plugins/plugin-types/auth-plugins/auth-plugins.md
> +url: "/plugins/auth-plugins"
Why do we have URL here? did you mean aliases?

2023-01-05 16:12 UTC, letzya commented on tyk-docs/content/plugins/plugin-types/auth-plugins/auth-plugins.md
> +url: "/plugins/auth-plugins"
We need tags

2023-01-05 17:51 UTC, sedkis commented
Sorted @letzya , thanks :)

2023-01-05 20:39 UTC, letzya requested changes

2023-01-05 20:39 UTC, letzya commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +tags: ["Test Plugin", "Test Custom Plugin"]
```suggestion
tags: ["Test Plugin", "Test Custom Plugin", "Tyk plugin", "Plugin", "Go plugin"]
```

2023-01-09 07:58 UTC, joshblakeley reviewed
V nice guide and docs touch up!

2023-01-09 07:58 UTC, joshblakeley commented on tyk-docs/content/plugins.md
> -*   [Python, Lua, gRPC (Rich Plugins)]({{< ref "plugins/supported-languages/rich-plugins" >}})
Worth stating whter they can have multiple hooks or are limited to one per API for example?

Also complicates things slightly but worth linking elsewhere to virtual endpoints in Go and JS?

2023-01-09 07:58 UTC, joshblakeley commented on tyk-docs/content/plugins.md
> +Tyk recommends using Go plugins for performance, flexibility, and nativity reasons (All Tyk components are written in Go).
Maybe better to explain why you would use particular plugin types based on their strengths? The categories they really break down into are:

i.e. Go - fast, native performance
JS, Python or Lua - simple with limited direct API when performance not important
gRPC - ultimate flexibility in language with some performance and management overheads

2023-01-09 07:58 UTC, joshblakeley commented on tyk-docs/content/plugins/get-started-selfmanaged/CICD.md
> +Getting ready for production, etc.
Do you need etc after a list of one thing?

2023-01-09 07:58 UTC, joshblakeley commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +This command generates a production grade "bundle" from the sample Go plugin in the repo.
100% sure this is "production grade"?

2023-01-09 07:58 UTC, joshblakeley commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +* A Tyk license (if deploying Self-Managed Tyk)
If deploying or self managed Tyk Pro

2023-01-09 07:58 UTC, joshblakeley commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +* A Tyk license (if deploying Self-Managed Tyk)
Would this also work for hybrid installs on cloud?

2023-01-09 07:58 UTC, joshblakeley commented on tyk-docs/content/plugins.md
> -*   [Python, Lua, gRPC (Rich Plugins)]({{< ref "plugins/supported-languages/rich-plugins" >}})
i.e. table section elsewhere could do with mentioning existence of the per path Go plugins - although annoyingly they cant load from bundles yet

2023-01-09 10:03 UTC, letzya requested changes

2023-01-09 10:03 UTC, letzya commented on tyk-docs/content/plugins/supported-languages/golang.md
> +  - /plugins/supported-languages/golang/
Why do we need to update the aliases? Have you moved the page?

2023-01-09 15:57 UTC, sedkis commented on tyk-docs/content/plugins/supported-languages/golang.md
> +  - /plugins/supported-languages/golang/
Yes

2023-01-09 15:57 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +* A Tyk license (if deploying Self-Managed Tyk)
Not OOTB for Hybrid, can add it later

2023-01-09 16:00 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/CICD.md
> +Getting ready for production, etc.
This page is unused, deleted it

2023-01-09 16:01 UTC, sedkis commented on tyk-docs/content/plugins.md
> +Tyk recommends using Go plugins for performance, flexibility, and nativity reasons (All Tyk components are written in Go).
Added

2023-01-09 16:02 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +This command generates a production grade "bundle" from the sample Go plugin in the repo.
Yes

2023-01-09 16:03 UTC, sedkis commented on tyk-docs/content/plugins.md
> -*   [Python, Lua, gRPC (Rich Plugins)]({{< ref "plugins/supported-languages/rich-plugins" >}})
I won't be mentioning per path go plugins yet, we can add a separate page for it, it adds too much complexity with not enough value

2023-01-09 16:05 UTC, sedkis commented on tyk-docs/content/plugins.md
> -*   [Python, Lua, gRPC (Rich Plugins)]({{< ref "plugins/supported-languages/rich-plugins" >}})
I'm not a fan of complicating things rn, can we push this improvement and look at adding more info in another iteration?

2023-01-09 16:10 UTC, joshblakeley approved these changes
Thanks again!

2023-01-10 12:45 UTC, sredxny reviewed
lgtm!!! awesome work 🚀

2023-01-10 12:45 UTC, sredxny commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +## 2. Bundle The Plugin
@sedkis should we put here as well how to generate a signed bundle?

2023-01-10 12:45 UTC, sredxny commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +## 2. Bundle The Plugin
or at least mention it? what do you think?

2023-01-10 17:11 UTC, zalbiraw requested changes

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins.md
>  *   The plugins used *must* be specified in an API definition and are not global across APIs.
```suggestion
*   To apply a custom plugin to an API you must modify the API definition and add the plugin information to one of the areas of the API Request Lifecycle mentioned above.
```

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins.md
> +*   [Python, Lua, gRPC (Rich Plugins)]({{< ref "plugins/supported-languages/rich-plugins" >}}) - gRPC - ultimate flexibility in language with some performance and management overheads
```suggestion
*   [Python, Lua, gRPC (Rich Plugins)]({{< ref "plugins/supported-languages/rich-plugins" >}}) - ultimate flexibility in the language of implementation, however, there are some performance and management overheads when compared to native GoLang plugins
```

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +## Introduction
```suggestion
```

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +Go plugins are the recommended plugin type and suitable for virtually most use cases.
```suggestion
Go plugins are the recommended plugin type and suitable for most use cases.
```

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/get-started.md
> +* A Tyk license (if deploying Self-Managed Tyk)
I would add a link to obtain a tyk self managed licenses and make a comment that they should use self managed while developing their plugin regardless of their deployment model.

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +Log on to the Tyk Dashboard on `http://localhost:3000` and follow the set up menu to bootstrap the Tyk organization.
We should modify the repo and add the bootstrap script to make things easier.

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +```
```suggestion
```json
    "custom_middleware": {
      "pre": [
        {
          "name": "AddFooBarHeader",
          "path": "/opt/tyk-gateway/middleware/CustomGoPlugin.so"
        }
      ],
      ...
      "driver": "goplugin"
    }
```
```

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +And then hit update!
```suggestion
And hit update!
```

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +### 2. Create an API
We should also pre-create this too. I can help add those two things to the repo

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/run.md
> +git checkout opensource
maybe we should have a `make opensource` and a `make` rather than cloning a different branch?

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/plugin-types/plugintypes.md
> +| Analytics Plugin | The final middleware to be executed during the response phase  |  Obfuscating sensitive data   |
```suggestion
| Pre (Request) | The first thing to be executed, before any middleware.  | IP Rate Limit plugins,  API Request enrichment      |
| Authentication | Replace Tyk's built in Authentication with your own business logic.  |  Interfacing with legacy Auth database  |
| Post-Auth (Request) | Executed immediately after authentication middleware  | Additional authentication      |
| Post (Request) | The final middleware to be executed during the "request" phase  |       |
| Response | Executed immediately after the reverse proxy is returned from the upstream API to Tyk  |    |
| Analytics Plugin | The final middleware to be executed during the response phase  |  Obfuscating sensitive data   |
```

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/plugin-types/plugintypes.md
> +| Analytics Plugin | The final middleware to be executed during the response phase  |  Obfuscating sensitive data   |
Adjusted the order to follow the order of execution

2023-01-10 17:11 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +## 2. Bundle The Plugin
maybe multi version bundles too?

2023-01-12 15:41 UTC, letzya commented
@sedkis this will be merged when you make the suggested changes

2023-01-13 13:40 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +## 2. Bundle The Plugin
I think that's all a good idea for v2, I would hate to slow down the this PR by increasing the scope. thoughts?

2023-01-13 13:43 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +### 2. Create an API
Not gonna do this as part of this PR - can certainly do it for next iteration.  Would rather ship as-is then increase scope.  Thoughts?

2023-01-13 13:44 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/run.md
> +git checkout opensource
we're in opinion territory here.

seeing as the open source stuff is not done yet anyways, its a WIP - can we have this conversation in v2?

2023-01-13 13:52 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +## 2. Bundle The Plugin
On second thought, I think a reference is a great idea.  Added the below:
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/8964621/212335754-7a51bc0d-c631-47e6-a290-815d8cffac61.png">

2023-01-13 13:54 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/run.md
> +git checkout opensource
Let's have the convo here:
https://github.com/TykTechnologies/tyk-docs/issues/2207

2023-01-13 13:58 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +## 2. Bundle The Plugin
And added note on multi version bundles:
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/8964621/212336918-c04dee1a-ae5c-4b0b-a419-cff2ef1262d9.png">

2023-01-13 14:09 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/deploy.md
> +## 2. Bundle The Plugin
in v2 I will work on streamlining this

2023-01-13 14:10 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +### 2. Create an API
v2 goal

2023-01-13 14:10 UTC, zalbiraw commented on tyk-docs/content/plugins/get-started-selfmanaged/run.md
> +git checkout opensource
perfect thanks

2023-01-13 15:31 UTC, sedkis commented
@letzya  resolved!

2023-01-13 18:30 UTC, zalbiraw approved these changes
LGTM

2023-01-19 20:13 UTC, letzya approved these changes

2023-01-19 20:13 UTC, merged

2023-01-19 20:13 UTC, sedkis commented on tyk-docs/content/plugins/get-started-selfmanaged/test.md
> +Log on to the Tyk Dashboard on `http://localhost:3000` and follow the set up menu to bootstrap the Tyk organization.
Noted for v2

2023-01-19 20:15 UTC, letzya commented
/release to release-4.3