[TT-7453] Modify OAS version creation as an atomic operation in OSS
TykTechnologies/tyk-docs-hugo pull request #2156
Opened 2023-01-04 14:18 UTC by furkansenharputlu

2023-01-04 14:25 UTC, lghiur commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +As the new version has been added and configured atomically, you can now call the Base API URL with the version header identifier, and you should be able to hit the upstream of the second API, provin
typo 'automatically'

2023-01-04 14:25 UTC, lghiur commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> -#### Check request response
I would keep these steps, to check request response and reload the gw

2023-01-04 14:26 UTC, furkansenharputlu commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +As the new version has been added and configured atomically, you can now call the Base API URL with the version header identifier, and you should be able to hit the upstream of the second API, provin
actually, it is meant to be `atomically` as it is an atomic operation.

2023-01-04 14:30 UTC, lghiur approved these changes

2023-01-04 15:26 UTC, titpetric approved these changes

2023-01-05 12:17 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
>  ```
```suggestion
```bash
```

2023-01-05 13:48 UTC, letzya requested changes

2023-01-05 13:48 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +| Resource URL | /tyk/apis/oas                                                                  |
```suggestion
| Resource URL | `/tyk/apis/oas`                                                                  |
```

2023-01-05 13:48 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +| Param        | Query Param: base_api_id, base_api_version_name, new_version_name, set_default |
```suggestion
| Param        | Query Param: `base_api_id`, `base_api_version_name`, `new_version_name`, `set_default` |
```

2023-01-06 08:57 UTC, furkansenharputlu commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +| Param        | Query Param: base_api_id, base_api_version_name, new_version_name, set_default |
@letzya In other places for params, there was no `` usage so I made it consistent.

2023-01-06 08:57 UTC, furkansenharputlu commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +| Resource URL | /tyk/apis/oas                                                                  |
@letzya In other places for paths, there was no `` usage so I made it consistent.

2023-01-06 09:06 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +| Resource URL | /tyk/apis/oas                                                                  |
Could you please check how it actually looks in the website? I think it's clearer this way since these are not words, they are key words used as Paramus.

2023-01-09 12:17 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +| Query Param. | Options: <br>- `base_api_id`: The base API ID which the new version will be linked to.<br>- `base_api_version_name`: The version name of the base API while creating the first version
```suggestion
| Query Param. | Options: <br>- `base_api_id`: The base API ID to which the new version will be linked.<br>- `base_api_version_name`: The version name of the base API while creating the first version. This doesn't have to be sent for the next versions but if it is set, it will override the base API version name.<br>- `new_version_name`: The version name of the created version.<br>- `set_default`: If true, the new version is set as default version.|
```

2023-01-09 12:18 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +```bash
```suggestion
```.curl
```

2023-01-09 12:18 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +```bash
```suggestion
```curl
```

2023-01-09 12:19 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +```bash
```suggestion
```.curl
```

2023-01-09 12:19 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +```bash
```suggestion
```curl
```

2023-01-09 12:19 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +```bash
```suggestion
```curl
```

2023-01-09 12:20 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +```bash
```suggestion
```curl
```

2023-01-09 12:20 UTC, letzya approved these changes

2023-01-09 12:29 UTC, merged