Add quick start section
TykTechnologies/tyk-docs-hugo pull request #2159
Opened 2023-01-05 00:04 UTC by zalbiraw

2023-01-05 19:04 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +weight: 1
why is it at the top of the list? I assumed it'll be added to the bottom.

2023-01-05 19:16 UTC, letzya requested changes
Can you move the

2023-01-05 19:16 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +Title: Proof of Concept
Not sure about this title? what do you think about _Quick start_? I created a commit, please rename the file name to `quick_start.md` and the name of the parent in the children pages

2023-01-05 19:16 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +At Tyk we understand that getting started with any tool can be overwhelming and time-consuming. This is why we built
```suggestion
At Tyk we understand that getting started with any tool can be overwhelming and time-consuming. This is the reason we created
```

2023-01-05 19:16 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +repositories. The idea is to provide an enriched environment with many integrations that can act as integration examples
```suggestion
projects. The idea is to provide an enriched environment with many integrations that can act as integration examples 
```

2023-01-05 19:16 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +These libraries are constantly being improved and are used by the Tyk engineers, if you have any questions or would like to
```suggestion
These open-source projects are actively being updated and improved. They are also being used daily by Tyk engineers. If you have questions or would like to 
```

2023-01-05 19:16 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +request an example of an specific integration or feature example you can submit a request to each of the repos respectively.
```suggestion
request us for a certain integration or to add a new example, please submit a request to each of the repos respectively. 
```

2023-01-05 19:16 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +request an example of an specific integration or feature example you can submit a request to each of the repos respectively.
Please add direct links to the request page in each repo

2023-01-05 19:16 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +Docker compose environment (tyk-demo)
What are these 2 lines?

2023-01-05 19:27 UTC, letzya requested changes

2023-01-05 19:27 UTC, letzya commented on tyk-docs/content/getting-started/proof-of-concept/tyk-k8s-demo.md
> +```
```suggestion
```console
```

2023-01-05 19:27 UTC, letzya commented on tyk-docs/content/getting-started/proof-of-concept/tyk-k8s-demo.md
> +```
```suggestion
```console
```

2023-01-05 19:27 UTC, letzya commented on tyk-docs/content/getting-started/proof-of-concept/tyk-k8s-demo.md
> +```
```suggestion
```console
```

2023-01-05 19:27 UTC, letzya commented on tyk-docs/content/getting-started/proof-of-concept/tyk-k8s-demo.md
> +## Usage
```suggestion
## Usage

### Start Tyk deployment
Create and start up the containers and the Tyk deployment
```

2023-01-05 19:27 UTC, letzya commented on tyk-docs/content/getting-started/proof-of-concept/tyk-k8s-demo.md
> +
```suggestion

### Stop Tyk deployment
Shut down up the containers and the Tyk deployment

```

2023-01-05 19:27 UTC, letzya commented on tyk-docs/content/getting-started/proof-of-concept/tyk-k8s-demo.md
> +```
```suggestion
```console
```

2023-01-05 19:27 UTC, letzya commented on tyk-docs/content/getting-started/proof-of-concept/tyk-k8s-demo.md
> +the repository [here](https://github.com/TykTechnologies/tyk-k8s-demo/issues).
We should also add an email of sales to contact us if they want a demo of tyk-pro

2023-01-05 21:40 UTC, zalbiraw commented on tyk-docs/content/getting-started/poc.md
> +weight: 1
I did not want people to go through the installation, create an api etc etc before looking at this. This will do everything for them. So it would be nice to have everything up then they can learn how to do it all after.

2023-01-05 21:42 UTC, zalbiraw commented on tyk-docs/content/getting-started/poc.md
> +weight: 1
I did not want the user to have to read through all the getting started content before they get to the tool that would just stand everything up for them. It would be awesome if they start with the POC and stand it up, then go through those sections to see how to configure them

2023-01-05 21:43 UTC, zalbiraw commented on tyk-docs/content/getting-started/poc.md
> +Title: Proof of Concept
I like this. Quick start is perfect.

2023-01-05 21:51 UTC, zalbiraw commented on tyk-docs/content/getting-started/poc.md
> +request us for a certain integration or to add a new example, please submit a request to each of the repos respectively.
```suggestion
request us to build a certain integration or to add a new example, please submit a request to each of the repos respectively. 
```

2023-01-05 21:52 UTC, zalbiraw commented on tyk-docs/content/getting-started/proof-of-concept/tyk-k8s-demo.md
> +the repository [here](https://github.com/TykTechnologies/tyk-k8s-demo/issues).
I thought of that but I was worried that we get spammed with random emails.

2023-01-05 21:56 UTC, zalbiraw commented on tyk-docs/content/getting-started/poc.md
> +Docker compose environment (tyk-demo)
I need to add the links to the sub pages here

2023-03-01 18:49 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +tags: ["Tyk Tutorials", "Getting Started", "POC", "Proof of Concept", "k8s", "docker", "Self Managed", "Open Source"]
```suggestion
tags: ["Tyk Tutorials", "Getting Started", "POC", "Proof of Concept", "Tyk PoC", "k8s", "docker", "Self Managed", "Open Source", "demo", "Tyk demo", "Tyk quick start"]
```

2023-03-01 18:49 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +description: "How to run a Tyk POC"
```suggestion
description: "Learn to deploy and run a Tyk deployment in minutes"
```

2023-03-01 18:49 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +the [tyk-demo](https://github.com/TykTechnologies/tyk-demo) and [tyk-k8s-demo](https://github.com/TykTechnologies/tyk-k8s-demo)
```suggestion
[tyk-demo](https://github.com/TykTechnologies/tyk-demo) and [tyk-k8s-demo](https://github.com/TykTechnologies/tyk-k8s-demo) 
```

2023-03-01 18:49 UTC, letzya commented on tyk-docs/content/getting-started/poc.md
> +Title: Proof of Concept
```suggestion
Title: Quick start
```

2023-03-01 18:49 UTC, letzya commented on tyk-docs/content/getting-started/proof-of-concept/tyk-k8s-demo.md
> +the repository [here](https://github.com/TykTechnologies/tyk-k8s-demo/issues).
ask the AMs what they want. We can add a button request demo

2023-03-01 18:49 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-demo.md
> +Title: Dockerized POC
Is this the title? usually, the path including the file name is the URL and it helps to understand if the file name is the same as the title. Also, the title is the name in the navigation, but up to you.

Also, if you want you can have a different name as follows
```
title: API Gateway Security | How to Secure API Gateways
linktitle: Security in Tyk
```

so in google you see `API Gateway Security | How to Secure API Gateways` and in the docs you see `Security in Tyk`
check this PR https://github.com/TykTechnologies/tyk-docs/pull/2190/files

2023-03-01 19:04 UTC, zalbiraw commented on tyk-docs/content/getting-started/quick-start.md
> +tags: ["Tyk Tutorials", "Getting Started", "POC", "Proof of Concept", "k8s", "docker", "Self Managed", "Open Source"]
```suggestion
tags: ["Tyk Tutorials", "Getting Started", "POC", "Proof of Concept", "Tyk PoC", "k8s", "docker", "Self Managed", "Open Source", "demo", "Tyk demo", "Tyk quick start"]
```

2023-03-01 19:04 UTC, zalbiraw commented on tyk-docs/content/getting-started/quick-start.md
> +description: "How to run a Tyk POC"
```suggestion
description: "Learn to deploy and run a Tyk deployment in minutes"
```

2023-03-01 19:04 UTC, zalbiraw commented on tyk-docs/content/getting-started/quick-start.md
> +the [tyk-demo](https://github.com/TykTechnologies/tyk-demo) and [tyk-k8s-demo](https://github.com/TykTechnologies/tyk-k8s-demo)
```suggestion
[tyk-demo](https://github.com/TykTechnologies/tyk-demo) and [tyk-k8s-demo](https://github.com/TykTechnologies/tyk-k8s-demo) 
```

2023-03-01 19:40 UTC, zalbiraw commented on tyk-docs/content/getting-started/quick-start/tyk-demo.md
> +Title: Dockerized POC
Thank you!

2023-03-01 20:50 UTC, JRWu requested changes
Looks great to me, minor changes requested

2023-03-01 20:50 UTC, JRWu commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +| Variable                    |        Default        | Comments                                                                 |
I would add a column here that states whether or not a variable is optional or not- lets assume the user has no prior knowledge of Tyk; what are the minimum settings required to get this up and running?

2023-03-01 20:50 UTC, JRWu commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +    - `GOOGLE_APPLICATION_CREDENTIALS` environment variable per [google's documentation](https://cloud.google.com/docs/authentication/application-default-credentials)
I think this apostrophe renders incorrectly as **& rsquo;**

2023-03-01 20:50 UTC, JRWu commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +title: Quick Start in k8s
Perhaps we can have title as

title: Quick Start in Kubernetes (k8s)

2023-03-01 20:50 UTC, JRWu commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +### Requirements
Should we say which OS this has been tested on? Linux? OSX? Docker for Windows? 

Potentially need to mention architecture as well, AMD64? ARM?

2023-03-01 21:05 UTC, zalbiraw commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +| Variable                    |        Default        | Comments                                                                 |
The script has defaults for minimal settings and will give errors if something is missing

2023-03-01 21:10 UTC, zalbiraw commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +    - `GOOGLE_APPLICATION_CREDENTIALS` environment variable per [google's documentation](https://cloud.google.com/docs/authentication/application-default-credentials)
I have no idea what you are reffering to

2023-03-01 21:11 UTC, zalbiraw commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +title: Quick Start in k8s
I did it to save space on the menu

2023-03-13 19:42 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +    - `GOOGLE_APPLICATION_CREDENTIALS` environment variable per [google's documentation](https://cloud.google.com/docs/authentication/application-default-credentials)
```suggestion
    - `GOOGLE_APPLICATION_CREDENTIALS` environment variable per [google documentation]({{< ref "https://cloud.google.com/docs/authentication/application-default-credentials" >}})
```

2023-03-13 19:43 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +    - `GOOGLE_APPLICATION_CREDENTIALS` environment variable per [google's documentation](https://cloud.google.com/docs/authentication/application-default-credentials)
fixed. please com,it suggestion

2023-03-14 10:12 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +tags: ["Tyk Tutorials", "Getting Started", "POC", "Proof of Concept", "Tyk PoC", "k8s", "Self Managed", "Open Source", "demo", "Tyk demo", "Tyk quick start"]
```suggestion
tags: ["Tyk Tutorials", "Getting Started", "POC", "Proof of Concept", "Tyk PoC", "k8s", "Self Managed", "Open Source", "demo", "Tyk demo", "Tyk quick start", "Kubernetes"]
```

2023-03-14 10:15 UTC, letzya approved these changes

2023-03-14 10:15 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +title: Quick Start in k8s
```suggestion
title: Quick Start in Kubernetes
```

2023-03-14 10:44 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +### Requirements
@zalbiraw

2023-03-14 10:52 UTC, letzya requested changes

2023-03-14 10:52 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +You can add any Tyk environments variables to the `.env` file and they will be mapped to the respective extraEnvs section in the helm charts.
```suggestion
The script has defaults for minimal settings in [this .env file]({{< "https://github.com/TykTechnologies/tyk-k8s-demo/blob/main/.env.example" >}}) and it will give errors if something is missing.
You can also add or change any Tyk environments variables in the `.env` file and they will be mapped to the respective `extraEnvs` section in the helm charts.
```

2023-03-14 10:52 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +## Variables
```suggestion
## Environments Variables
```

2023-03-14 10:52 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +| Variable                    |        Default        | Comments                                                                 |
Added suggestion. please resolve if you accept it

2023-03-14 10:52 UTC, letzya commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +```
```suggestion
```console
```

2023-03-14 14:23 UTC, JRWu approved these changes
LGTM!

2023-03-14 16:12 UTC, letzya approved these changes

2023-03-14 16:13 UTC, merged

2023-03-14 16:13 UTC, letzya commented
/release to release-4.3