[TT-7505] update usage of mockResponse query parameter
TykTechnologies/tyk-docs-hugo pull request #2161
Opened 2023-01-05 07:06 UTC by jeffy-mathew

https://tyktech.atlassian.net/browse/TT-7505

2023-01-05 08:42 UTC, lghiur approved these changes

2023-01-05 13:48 UTC, letzya requested changes

2023-01-05 13:48 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +| Param        | mockResponse           |
```suggestion
| Param        | `mockResponse`           |
```

2023-01-05 13:48 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +| Resource URL | /tyk/apis/oas/import   |
```suggestion
| Resource URL | `/tyk/apis/oas/import`   |
```

2023-01-05 13:48 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +```
```suggestion
```.curl
```

2023-01-05 13:48 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +| Resource URL | /tyk/apis/oas/{api-id}                                    |
```suggestion
| Resource URL | `/tyk/apis/oas/{api-id}`                                    |
```

2023-01-05 13:48 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +| Param        | Path Parameter: {api-id} Query Parameter: mockResponse    |
```suggestion
| Path Param |  `{api-id}`   |
|.Query Param | `mockResponse`    |
```

2023-01-05 13:48 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +In the OAS API Definition that you updated at [Update an API using just the OAS definition](#update-an-api-using-just-the-oas-definition), you also defined a JSON schema that describes the response f
Can you please update the link to use this format https://tyktech.atlassian.net/wiki/spaces/EN/pages/1888976900/Docs+contribution+guidelines+-+empower+you+to+write#6

2023-02-28 11:21 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +```
```suggestion
```curl
```

2023-02-28 13:35 UTC, letzya approved these changes

2023-02-28 13:36 UTC, merged