open a PR when config generator action is run
TykTechnologies/tyk-docs-hugo pull request #2166
Opened 2023-01-06 04:59 UTC by jeffy-mathew

2023-01-06 08:52 UTC, lghiur approved these changes

2023-01-06 14:57 UTC, letzya requested changes
Add me and Keith as reviewers

2023-01-06 14:57 UTC, letzya commented on .github/workflows/config_gen.yaml
> +        delete-branch: true
```suggestion
        delete-branch: true
        reviewers: letzya, Keithwachira
```

2023-01-09 11:22 UTC, letzya requested changes
I PM you about the commit messages. Hope it makes sense

2023-01-11 16:08 UTC, letzya approved these changes

2023-01-11 16:08 UTC, merged