Add on prem troubleshooting guides
TykTechnologies/tyk-docs-hugo pull request #2170
Opened 2023-01-06 14:24 UTC by vverbani

New page in the debugging series on troubleshooting guides for a tyk-self managed instance.

2023-01-06 15:04 UTC, letzya requested changes
reminder to get peer review

2023-01-06 15:04 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +4. Tyk Support (Paid SLA only)
no link

2023-01-06 15:04 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
```suggestion
```json
```

2023-01-06 15:08 UTC, vverbani commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +4. Tyk Support (Paid SLA only)
I left the Tyk support blank on purpose. Atm we get a bunch of spam tickets from non-SLA clients. SLA clients should already have this link during their signing/onboarding process

2023-01-06 15:10 UTC, vverbani commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
this was left without `json` on purpose. The json file should be in the `{"key": "value"}` format but in the above api return it's `{key: "value"}` and this gets flagged with bunch of red in the hugo html UI process.

2023-01-06 15:10 UTC, joshblakeley requested changes, later dismissed
Few notes to cover off. Only got helfway through but will revisit. Thanks for the effort so far - this will be awesome when published!

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +Debugging our on-prem environment is a challenging task by any means. Many moving pieces could be causing the error you see, i.e. gateway, dashboard, backend service, Mongo, Redis, Postgres, pump, lo
If this is in the docs I would recommend removing the opinion based language and leave things more neutral.

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +You should be doing two things from the beginning: isolating your components to see where the error is coming from and enabling debug logs to ensure you get all the information you need.
This is a nice starting point but language-wise would be better written as something like 

This guide should help a user of Tyks self managed pro offering in debugging common issues. A helpful way to go about this is by:
1.  Isolating your components to see where the error is coming 
2. enabling debug logs to ensure you get all the information you need

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +You should be doing two things from the beginning: isolating your components to see where the error is coming from and enabling debug logs to ensure you get all the information you need.
Also not clear to me what exactly isolating components means at this stage in the doc

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +## `/Hello` endpoint
lower case

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +The `/hello` endpoints are the quickest way to get a feel for if the overall environment is up and running.
endpoints? Is this a consistent tool across the stack, are there exceptions i.e. you can rewrite the name of this in gateway

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +You can call the same endpoint against both the gateway and the dashboard. The dashboard returns much less info but is still valuable regarding isolating issues.
Better still to say what information we expect from a call to each component and why we present it.

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +This gives you a clearer picture of whether the above components are working. While it doesn't give you the whole picture, it certainly narrows the field of vision that much more.
Opinionated language needs cleaning up.

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +Having debug logs turned on helps close the gap in which component is throwing the error.
Same again

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +Having debug logs turned on helps close the gap in which component is throwing the error.
Also not really anything concrete here. Why?

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +If you’re using a `*.env` for your configuration:
Address the k8s/helm case here too?

2023-01-06 15:10 UTC, joshblakeley commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +If you are using an older version of Tyk and running into an error, the issue might resolve if you upgrade.
What do we recommend here more explicitly?

2023-01-06 16:42 UTC, letzya requested changes

2023-01-06 16:42 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
Are you sure? not in my gw
<img width="967" alt="image" src="https://user-images.githubusercontent.com/3155222/211057240-ac1a251a-a86c-49c0-9c1c-f37abd7ec063.png">

2023-01-09 15:51 UTC, sedkis commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +If you are using an older version of Tyk and running into an error, the issue might resolve if you upgrade.
Add "Please see the latest version releases [here](release pages).  We recommend you to use the latest version of Tyk always.  Tyk is backwards compatible, upgrading to newer versions won't activate any features or change behaviour of your existing environment"

2023-01-16 11:19 UTC, vverbani commented
@joshblakeley Want to review the changes

2023-01-24 14:18 UTC, JRWu requested changes, later dismissed
Suggesting some rephrasing & content additions

2023-01-24 14:18 UTC, JRWu commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +Debugging our on-prem environment is a challenging task by any means. Many moving pieces could be causing the error you see, i.e. gateway, dashboard, backend service, Mongo, Redis, Postgres, pump, lo
Lets align with our stance on the nomenclature, could reword the Tyk components as

Tyk Gateway, Tyk Dashboard, Tyk Pump,

2023-01-24 14:18 UTC, JRWu commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +It's essential to note that our dashboard is built on top of our OSS, which means that the dashboard uses the Dashboard API to retrieve its data. This means you can use the developer tools on your br
Lets firm up our reference to the dashboard as Tyk Dashboard

2023-01-24 14:18 UTC, JRWu commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +You can find the full log levels in our documentation.
It would be helpful if we linked to an example or what TYK_LOGLEVEL represents here

2023-01-24 14:18 UTC, JRWu commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +The reason this endpoint is important is that components such as the Tyk Dashboard, RPC, or Redis can go down at any given point so it is useful to know if the Gateway is currently usable or not.
Lets adjust our language here, we don't want to say that the components can go down at any point because they're unlikely to- perhaps we could reword this to:

This endpoint is important as it allows for a user to isolate where a problem might be originating from. At a glance, the `/hello` endpoint reports the Tyk-Gateway's connectivity to the Tyk-Dashboard, Redis, or in enterprise/hybrid installations: MDCB (rpc).

2023-01-24 14:18 UTC, JRWu commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +The Gateway can still function if the Dashboard fails. This means that your API calls are still working as normal.
(Perhaps we could also expand a bit about what will work and what will not work if each component fails to connect?)
If the Tyk-Dashboard or RPC connectivity fails, the Tyk-Gateway will still function based on the last recieved configurations from those components respectively. If Redis fails, Tyk-Gateway will not be able to perform since it is a hard dependency.

2023-01-24 14:18 UTC, JRWu commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +Having Debug mode turned on is helpful when debugging because it throws more descriptive error messages.
Perhaps having an example here of what the different log levels represent would be useful, i.e.

INFO: *some log example here*

DEBUG: *some log example here*

2023-02-13 00:01 UTC, zalbiraw requested changes, later dismissed

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +This guide should help a user of Tyks self managed pro offering in debugging common issues. A helpful way to go about this is by:
```suggestion
This guide should help a user of Tyk's self managed offering in debugging common issues. A helpful way to go about this is by:
```

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +1. Isolating your components to see where the error is coming
```suggestion
1. Isolating your components to see where the error is coming from
```

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +The `/hello` health check endpoint against the Gateway is the quickest way in determining the status of your Tyk instance. You can find more information in our docs about the [Gateway Liveness health
```suggestion
Querying the gateway's `/hello` health endpoint is the quickest way to determine the status of your Tyk instance. You can find more information in our docs about the [Gateway Liveness health check]({{< ref "planning-for-production/ensure-high-availability/health-check" >}}).
```

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +This endpoint is important as it allows for a user to isolate where a problem might be originating from. At a glance, the `/hello` endpoint reports the Gateways connectivity to the Dashboard, Redis,
```suggestion
This endpoint is important as it allows the user to isolate the problem's origin. At a glance, the `/hello` endpoint reports the Gateways connectivity to Redis, and the control plane components eg. Dashboard, MDCB, Tyk Cloud. 
```

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +    "version":"v4.0.10",
Maybe have the latest version when you release the docs. It shows that we are actively working on our docs 🙃

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +If the Dashboard or RPC connectivity fails, the Gateway will still function based on the last received configurations from those components respectively. If Redis fails, Gateway will not be able to p
```suggestion
If the Dashboard or RPC connectivity fails (control plane components), the Gateway will still function based on the last received configurations from those components. However, if Redis fails, Gateway will go down since it is a hard dependency.
```

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +Having Debug mode turned on is helpful when debugging because it throws more descriptive error messages. For example, here are the different outputs you receive when calling an Open Keyless API with
```suggestion
Setting the log level to debug will allow for more descriptive logs that will give a better context around any issue you might be facing. For example, here are the different outputs you receive when calling an Open Keyless API with `info` and `debug` log level modes.
```

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +As shown above, the `debug` log level mode throws more information which will help during your debugging stage, i.e when the API call was started, when it was finished, how long it took for the call
```suggestion
As shown above, the `debug` log level mode provides more information which will help during your debugging stage, i.e when the API call was started, when it was finished, how long it took for the call to finish, the endpoint that was called, the upstream that was called, the organization that the API belongs to, and more.
```

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +If you’re using a `*.env` for your configuration:
```suggestion
If you’re using environment variables for your configuration:
```

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +If you’re using a `*.env` for your configuration:
```suggestion
If you’re using environment variables for your configuration:
```

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +## Versions/ Replicate
Why Replicate?

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +We recommend using the latest version of Tyk always. Tyk is backwards compatible, upgrading to newer versions won't activate any features or change behaviour of your existing environment
I would say latest LTS not latest, no?

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +It's essential to note that our Dashboard is built on top of our OSS, which means that the Dashboard uses the Dashboard API to retrieve its data. This means you can use the developer tools on your br
This does not make sense.

2023-02-13 00:01 UTC, zalbiraw commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +When using the Dashboard, you'll run into a common theme where something doesn't work on the Dashboard but will work when using the Tyk Gateway API.
I do think we should say "its a common theme"

2023-03-24 17:09 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
```suggestion
```bash
```

2023-03-24 17:09 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
```suggestion
```bash
```

2023-03-24 17:10 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
```suggestion
```json
```

2023-03-24 17:10 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
```suggestion
```json
```

2023-03-24 17:10 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
```suggestion
```yaml
```

2023-03-24 17:11 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
```suggestion
```yaml
```

2023-03-24 17:11 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
```suggestion
```yaml
```

2023-03-24 17:11 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +```
```suggestion
```yaml
```

2023-03-24 17:12 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +    "version":"v4.0.10",
```suggestion
    "version":"v5.0",
```

2023-03-24 17:13 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +    "version":"v4.0.10",
Changed to 5.0 thinking we'll push it next week

2023-05-30 12:16 UTC, letzya commented
@vverbani Hi, what do you need in order to get this done? Thanks

2023-09-07 15:37 UTC, letzya commented
@vverbani Hi, checking again, what do you need in order to get this done? happy to help

2023-11-01 20:55 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +It's essential to note that our Dashboard is built on top of our OSS, which means that the Dashboard uses the Dashboard API to retrieve its data. This means you can use the developer tools on your br
fixing now

2023-11-01 20:55 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +We recommend using the latest version of Tyk always. Tyk is backwards compatible, upgrading to newer versions won't activate any features or change behaviour of your existing environment
fixing

2023-11-01 20:55 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +## Versions/ Replicate
fixing

2023-11-01 21:05 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +When using the Dashboard, you'll run into a common theme where something doesn't work on the Dashboard but will work when using the Tyk Gateway API.
fixing

2023-11-01 21:07 UTC, letzya commented
This PR https://github.com/TykTechnologies/tyk-docs/pull/3492 - addresses all the comments from @zalbiraw  - Please review it so we can publish this pr

2023-11-02 08:31 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +When using the Dashboard, you'll run into a common theme where something doesn't work on the Dashboard but will work when using the Tyk Gateway API.
```suggestion
```

2023-11-02 08:31 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +
```suggestion
```

2023-11-02 08:32 UTC, letzya commented on tyk-docs/content/debugging-series/on-prem-debugging.md
> +When debugging an issue, in order to isolate the gateway from the Dashboard, try to do the same API call on both Tyk Dashboard and Tyk Gateway
```suggestion
When debugging an issue, in order to isolate the gateway from the Dashboard, try to call the same API ednpoint on both Tyk Dashboard and Tyk Gateway 
```

2023-11-02 09:04 UTC, letzya approved these changes

2023-11-02 09:06 UTC, merged

2023-11-02 09:06 UTC, letzya commented
/release to release-5.0

2023-11-02 09:12 UTC, letzya commented
/release to release-5

2023-12-20 15:41 UTC, letzya commented
/release to release-5.2

2023-12-20 15:44 UTC, letzya commented
/release to release-5.1