Deployment models for Tyk Self-managed
TykTechnologies/tyk-docs-hugo pull request #2173
Opened 2023-01-09 13:23 UTC by SonjaChevre

Bringing the content from https://tyktech.atlassian.net/wiki/spaces/EN/pages/1896841234/Deployment+models+for+Tyk+Self-managed to the external documentation

* added three diagrams for self-managed deployment
* updated the text on the licensing page for self-managed and renamed the title to "Licensing and deployment models"
* improved the licensing snippet for self-managed (from "free" to "free trial")

see also https://tyktech.atlassian.net/browse/DX-158

2023-01-09 16:01 UTC, letzya requested changes
Kindly please assign a peer to review and approve. Thanks

2023-01-09 16:09 UTC, letzya commented
I personally think that "Need more" is not clear enough that we one can have many regions, I would clearly state it.

2023-01-09 17:12 UTC, letzya reviewed
another comment is that it is not clear why the package is relevant for multiple teams. MAybe we should add links to the relevant docs? (link this one for mdcb https://tyk.io/docs/tyk-multi-data-centre/#organisational-benefits)

>

2023-01-10 09:23 UTC, SonjaChevre commented
@letzya I have addressed your change requests, please check

2023-01-10 09:26 UTC, SonjaChevre commented
@sedkis I have also added you officially as reviewer, because I couldn't find your comments :D

2023-01-12 09:10 UTC, sedkis commented on tyk-docs/content/tyk-on-premises/licensing.md
> +If you have teams working on two different projects, deployed in different environments, you might have 4 different environments (staging and prod for project number 1, staging and prod for project n
Or, you can take advantage of RBAC to onboard multiple teams onto the same environment as that is more price effective.  You can read more about that [here](link to a blog coming out this week about environments and RBAC)

2023-01-12 09:10 UTC, sedkis commented on tyk-docs/content/tyk-on-premises/licensing.md
> +We recommend a minimum of 2 gateways per environment. Rolling updates or blue green deployment might require additional gateways to ensure high availability during deployments.
"per environment for redundancy & fail over"

2023-01-12 14:18 UTC, letzya commented
@SonjaChevre do we want a link to the pricing page? https://tyk.io/price-comparison/

2023-01-12 14:18 UTC, letzya approved these changes
Suggest link to pricing

2023-01-12 14:37 UTC, letzya commented on tyk-docs/content/tyk-on-premises/licensing.md
> +When selecting a [Tyk Self-managed license](https://tyk.io/price-comparison), you can choose between three deployment models: [Launch]({{< ref "licensing.md#launch---perfect-to-get-started" >}}), [Fl
is this the link `licensing.md#flex---for-multiple-teams-within-a-single-data-centre-or-cloud`? in the preview I see https://tyk.io/docs/nightly/tyk-on-premises/licensing/?__hstc=76629258.0441fb021a60c922d72bfb9681eb1faf.1673279869058.1673531891531.1673534113789.4&__hssc=76629258.2.1673534113789&__hsfp=3974607804#flex---for-multiple-teams-within-a-single-data-centre-or-cloud

2023-01-12 14:38 UTC, letzya commented on tyk-docs/content/tyk-on-premises/licensing.md
> +When selecting a [Tyk Self-managed license](https://tyk.io/price-comparison), you can choose between three deployment models: [Launch]({{< ref "licensing.md#launch---perfect-to-get-started" >}}), [Fl
also I dont get diff link to flex and launch

2023-01-13 07:43 UTC, SonjaChevre commented on tyk-docs/content/tyk-on-premises/licensing.md
> +When selecting a [Tyk Self-managed license](https://tyk.io/price-comparison), you can choose between three deployment models: [Launch]({{< ref "licensing.md#launch---perfect-to-get-started" >}}), [Fl
not that was the link for "Tyk Self-managed license" - but that wasn't very clear. 
Changing it to "(see the pricing page to compare the licenses)"

2023-01-13 08:01 UTC, SonjaChevre commented on tyk-docs/content/tyk-on-premises/licensing.md
> +When selecting a [Tyk Self-managed license](https://tyk.io/price-comparison), you can choose between three deployment models: [Launch]({{< ref "licensing.md#launch---perfect-to-get-started" >}}), [Fl
`licensing.md#flex---for-multiple-teams-within-a-single-data-centre-or-cloud` - those are links to the same page, to quickly jump to the different deployment model. on my local environment the links work correctly, but not on the nightly build.

2023-01-13 11:06 UTC, letzya requested changes

2023-01-13 11:06 UTC, letzya commented on tyk-docs/content/tyk-on-premises/licensing.md
> +When selecting a [Tyk Self-managed license](https://tyk.io/price-comparison), you can choose between three deployment models: [Launch]({{< ref "licensing.md#launch---perfect-to-get-started" >}}), [Fl
also I dont get diff link to flex and launch

2023-01-13 11:30 UTC, letzya approved these changes

2023-01-13 11:30 UTC, merged

2023-01-13 11:30 UTC, letzya commented
/release to release-4.3