SEO content/keywords updates from Revpartners
TykTechnologies/tyk-docs-hugo pull request #2175
Opened 2023-01-09 17:46 UTC by itsmartins

Some copy/keyword updates done on few pages according with this updates request: https://docs.google.com/spreadsheets/d/16NvG_v9YKfxBhXWViaHImFKBzYjB4ztFor80b2KeTyY/edit#gid=0

Added some keywords in the content, and updated title and meta description for each page

2023-01-10 12:36 UTC, letzya commented on tyk-docs/assets/others/dashboard-swagger.yml
> +    ## <a name="introduction"></a> Introduction to API Dashboards
this page is auto-gen, we need to remove it from the doc. it is from the  dashboard repo

2023-01-10 19:45 UTC, letzya commented on tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
> +title: API Request Methods & API Gateway Transformation
2 titles? 
Also why do we need linktitle?

2023-01-10 19:58 UTC, letzya requested changes
We need to catchup

2023-01-10 19:58 UTC, letzya commented on tyk-docs/content/apim/open-source.md
> +title: Open Source API Developer Portal | Tyk Documentation
dont understand this change. why dev portal?

2023-01-10 19:58 UTC, letzya commented on tyk-docs/content/apim/open-source.md
> +description: Tyk is an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols. Get started today.
```suggestion
description: Tyk is an enterprise-grade open-source API Gateway, supporting REST, GraphQL, TCP and gRPC protocols. Get started today.
```

2023-01-10 19:58 UTC, letzya commented on tyk-docs/content/apim/open-source.md
> +diffTitle: true
is this something new? googling didn't help

2023-01-10 19:58 UTC, letzya commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
> +description: Tyk API will actively only allow a key to make x requests per y time period. This is critical to ensure your API does not get flooded with requests.
Can you explain this please? is this how we should start writing the descriptions? copy/paste a section from the page?

2023-01-10 19:58 UTC, letzya commented on tyk-docs/content/planning-for-production/ensure-high-availability/service-discovery.md
> +This is what the API discovery service module does.
I think you be reverted. not need to add API there. What is the reason for this anyway?

2023-01-10 19:58 UTC, letzya commented on tyk-docs/content/shared/tyk-gateway-features-include.md
> +Built from the ground up to be the fastest API gateway on the planet. It does not depend on a legacy proxy underneath. It has no 3rd party dependencies aside from Redis for distributed rate-limiting
why open source developer portal?

2023-01-11 14:39 UTC, letzya commented on tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
> +title: API Request Methods & API Gateway Transformation
```suggestion
```

2023-07-18 13:00 UTC, closed without merging

2023-07-18 13:01 UTC, dcs3spp commented
Closing and re=opening for SEO project.

See ticket https://tyktech.atlassian.net/browse/DX-483