Add Pump Support Coverage to LTS page
TykTechnologies/tyk-docs-hugo pull request #2183
Opened 2023-01-11 13:21 UTC by vverbani

This PR adds the Pump Support Coverage information to our LTS page.

2023-01-12 08:57 UTC, tbuchaillot approved these changes

2023-01-16 19:36 UTC, letzya requested changes

2023-01-16 19:36 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Our Tyk Identity Broker (TIB),  MDCB, and Operator components will not be a part of our long term support policy yet. We will continue to support all versions of these components, and will offer advi
```suggestion
Our Tyk Identity Broker (TIB),  MDCB, and Operator components are not part of our Long-Term Support policy yet. We will continue to support all versions of these components and will offer advice to clients on when to upgrade if necessary.
```

2023-01-24 13:40 UTC, vverbani commented
/release to release-4.3

2023-01-24 13:43 UTC, letzya requested changes

2023-01-24 13:43 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Our Tyk Identity Broker (TIB),  MDCB, and Operator components are not part of our Long-Term Support policy yet. We will continue to support all versions of these components and will offer advice to c
```suggestion
Our Tyk Identity Broker (TIB),  MDCB, and Operator components are not part of our Long-Term Support (LTS) policy yet. We will continue to support all versions of these components and will offer advice to clients on when to upgrade if necessary.
```

2023-01-24 14:05 UTC, vverbani commented
/release to release-4.3

2023-01-24 15:48 UTC, letzya approved these changes

2023-01-24 15:48 UTC, merged

2023-01-24 16:09 UTC, vverbani commented
/release to release-4.3