Update Helm Chart docs for tyk-helm-chart release v0.13.2
TykTechnologies/tyk-docs-hugo pull request #2185
Opened 2023-01-11 14:08 UTC by caroltyk

Update Helm Chart docs to reflect latest settings (https://github.com/TykTechnologies/tyk-helm-chart/pull/252):
- Default deployment kind=Deployment, ReplicaCount=1

2023-01-11 15:19 UTC, buraksekili commented on tyk-docs/content/tyk-oss/ce-helm-chart.md
> +Please note that by default, Gateway runs as Deployment and ReplicaCount is 1 because multiple instances of headless gateways won't sync API Definition.
```
because multiple instances of headless gateways won't sync API Definition.
```
we do not need to specify this part if gw is running as Deployment

2023-01-11 15:32 UTC, buraksekili commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
> +To ensure that your Gateway pods will not scale beyond your license allowance, set the Gateway's resource kind to *Deployment*
Gateway resource is already set to Deployment. users do not need to take any further actions to modify resource kind. Maybe instead of `set the Gateway's resource kind to *Deployment*`, we can say something like `please ensure that the Gateway's resource kind is *Deployment*`

2023-01-11 15:32 UTC, buraksekili commented on tyk-docs/content/tyk-oss/ce-helm-chart.md
> +Please note that by default, Gateway runs as Deployment and ReplicaCount is 1 because multiple instances of headless gateways won't sync API Definition.
on second thought, we may even remove this part completely. this part was added in order to inform users about possible synchronization issues if they are running GW in multiple nodes as DaemonSet which was the default kind for GW. Since we updated the default kind to Deployment, I do not think that we need to document this scenario.

2023-01-11 15:32 UTC, buraksekili commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
> +and the replica count to your license node limit. By default, the chart is configured to work with single node license: `gateway.kind=Deployment` and `gateway.replicaCount=1` in `values.yaml`. You ca
```suggestion
and the replica count to your license node limit. By default, the chart is configured to work with a single node license: `gateway.kind=Deployment` and `gateway.replicaCount=1`.
```

2023-01-11 16:23 UTC, caroltyk commented on tyk-docs/content/tyk-oss/ce-helm-chart.md
> +Please note that by default, Gateway runs as Deployment and ReplicaCount is 1 because multiple instances of headless gateways won't sync API Definition.
I've left this in so that users will not try to increase the replicaCount, or change it to DaemonSet.

2023-01-11 16:31 UTC, carolwkc commented on tyk-docs/content/tyk-oss/ce-helm-chart.md
> +Please note that by default, Gateway runs as Deployment and ReplicaCount is 1 because multiple instances of headless gateways won't sync API Definition.
how about this?
```suggestion
Please note that by default, Gateway runs as Deployment and ReplicaCount is 1. You should not update this part because multiple instances of headless gateways won't sync API Definition.
```

2023-01-11 16:33 UTC, carolwkc commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
> +To ensure that your Gateway pods will not scale beyond your license allowance, set the Gateway's resource kind to *Deployment*
```suggestion
To ensure that your Gateway pods will not scale beyond your license allowance, please ensure that the Gateway's resource kind is *Deployment*
```

2023-01-16 19:28 UTC, letzya requested changes

2023-01-16 19:28 UTC, letzya commented on tyk-docs/content/tyk-oss/ce-helm-chart.md
> +Please note that by default, Gateway runs as Deployment and ReplicaCount is 1. You should not update this part because multiple instances of headless gateways won't sync API Definition.
```suggestion
Please note that by default, Gateway runs as `Deployment` with `ReplicaCount` is 1. You should not update this part because multiple instances of OSS gateways won't sync the API Definition.
```

2023-01-16 19:28 UTC, letzya commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
> +To ensure that your Gateway pods will not scale beyond your license allowance, please ensure that the Gateway's resource kind is *Deployment*
```suggestion
To ensure that your Gateway pods will not scale beyond your license allowance, please ensure that the Gateway's resource kind is `Deployment`
```

2023-01-18 12:00 UTC, buraksekili approved these changes

2023-01-24 18:17 UTC, letzya approved these changes

2023-01-24 18:17 UTC, merged

2023-01-24 18:18 UTC, letzya commented
/release to release-4.3