added section in our tyk pump on our tyk analytics schema
TykTechnologies/tyk-docs-hugo pull request #2208
Opened 2023-01-13 16:55 UTC by LLe27

added details for each analytics data field for our schema sent from our tyk pump

2023-01-13 17:11 UTC, tbuchaillot approved these changes
LGTM

2023-01-15 16:02 UTC, letzya commented
Sorry for suggesting it only now but it looks like the same use case as our other configs which we autogen from the code? @zalbiraw what do you think?

2023-01-16 19:41 UTC, letzya requested changes
Per discussion, change schemas to fields

2023-01-16 19:41 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-analytics-schema.md
> +title: "Tyk Analytics Schema"
Per discussion, change schemas to fields in the file name, title and everywhere else.

2023-01-16 19:57 UTC, LLe27 commented on tyk-docs/content/tyk-stack/tyk-pump/tyk-analytics-schema.md
> +title: "Tyk Analytics Schema"
Added the requested change @letzya. Please review thank you!

2023-01-24 16:48 UTC, letzya approved these changes

2023-01-24 17:46 UTC, merged

2023-01-24 17:47 UTC, letzya commented
/release to release-4.3