[Enterprise developer portal] Add documentation for the Get started guides.
TykTechnologies/tyk-docs-hugo pull request #2211
Opened 2023-01-14 20:07 UTC by slega

## Related Issue (if applicable)

## Description
Add documentation for the Get started guides that will be available in 1.1.0 release of the enterprise developer portal.

## Motivation and Context
Documentation for new feature.

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [x] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [x] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-01-15 16:06 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-api-docs.md
> +description: ""
Tags and description are a must

2023-01-15 16:07 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-api-docs.md
> +title: "Manage Get started guides"
are you sure about this title?

2023-01-17 08:35 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-api-docs.md
> +title: "Manage Get started guides"
Yes. This is how they appear in the live portal. We have two types of docs for API Products: Open API Spec and the Get started guides.

2023-01-17 08:38 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-api-docs.md
> +description: ""
Fixed.

2023-01-17 09:38 UTC, konrad-sol approved these changes

2023-01-18 19:53 UTC, letzya requested changes
Sent you PM with comments

2023-02-01 15:48 UTC, sedkis approved these changes
LGTM

2023-02-01 19:37 UTC, letzya approved these changes

2023-02-01 19:37 UTC, merged

2023-02-02 07:20 UTC, slega commented
/release to release-4.3