Fix custom_analytics page link in api-def-common.md
TykTechnologies/tyk-docs-hugo pull request #2227
Opened 2023-01-19 15:56 UTC by tbuchaillot

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-01-19 16:12 UTC, letzya requested changes

2023-01-19 16:12 UTC, letzya commented on tyk-docs/content/shared/api-def-common.md
> +* `tag_headers`: This specifies a string array of HTTP headers values which turned to tags. For example if you include `X-Request-ID` header to `tag_headers`, for each incoming request it will includ
```suggestion
* `tag_headers`: This specifies a string array of HTTP headers values which turned into tags. For example, if you include the `X-Request-ID` header to `tag_headers`, for each incoming request it will include an `x-request-id-<header_value>` tag to request an analytic record. This functionality can be useful if you need analytics for request headers without the body content (Enabling detailed logging is another option, but it records the full request and response objects and consumes a lot more space). Check the page [custom Analytics Tags using HTTP Headers]({{< ref "/tyk-rest-api/api-definition-objects/custom-analytics/" >}}) for more important information.
```

2023-01-19 16:12 UTC, letzya commented on tyk-docs/content/shared/api-def-common.md
> +* `tag_headers`: This specifies a string array of HTTP headers values which turned to tags. For example if you include `X-Request-ID` header to `tag_headers`, for each incoming request it will includ
We need to use `ref`

2023-01-19 16:16 UTC, tbuchaillot commented on tyk-docs/content/shared/api-def-common.md
> +* `tag_headers`: This specifies a string array of HTTP headers values which turned to tags. For example if you include `X-Request-ID` header to `tag_headers`, for each incoming request it will includ
@letzya now we got this error https://github.com/TykTechnologies/tyk-docs/actions/runs/3960292373/jobs/6784245686#step:4:9

I don't think that's the right way ?

2023-01-19 16:23 UTC, letzya commented on tyk-docs/content/shared/api-def-common.md
> +* `tag_headers`: This specifies a string array of HTTP headers values which turned to tags. For example if you include `X-Request-ID` header to `tag_headers`, for each incoming request it will includ
Also, we should use the page path as the link, not the alias `tyk-apis/tyk-gateway-api/api-definition-objects)/custom-analytics` we only keep aliases because of google.

2023-01-19 16:26 UTC, tbuchaillot commented on tyk-docs/content/shared/api-def-common.md
> +* `tag_headers`: This specifies a string array of HTTP headers values which turned to tags. For example if you include `X-Request-ID` header to `tag_headers`, for each incoming request it will includ
@letzya so we should use ref with the old link? `/docs/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics/`? do we need to include the `.md` extension?

2023-01-19 16:28 UTC, letzya commented on tyk-docs/content/shared/api-def-common.md
> +* `tag_headers`: This specifies a string array of HTTP headers values which turned to tags. For example if you include `X-Request-ID` header to `tag_headers`, for each incoming request it will includ
I updated my suggestion you can just commit it

2023-01-19 16:41 UTC, letzya approved these changes

2023-01-19 16:41 UTC, merged

2023-01-19 17:00 UTC, letzya commented
/release to release-4.3

2023-01-26 11:44 UTC, letzya commented
/release to release-4.3