Added installation of Enterprise developer portal with Postgresql
TykTechnologies/tyk-docs-hugo pull request #2329
Opened 2023-02-17 04:07 UTC by Fadzli-fast

## Description
Added installation of Enterprise developer portal with postgreSQL using  docker-compose.yml and .env file

## Motivation and Context
There is no documented way for customers to deploy enterprise portal if they plan on using postgres. 

## Preview Link
<img width="554" alt="image" src="https://user-images.githubusercontent.com/106595158/219546615-4ff36605-5719-413e-83e0-7a4bb76aa90a.png">
<img width="554" alt="image" src="https://user-images.githubusercontent.com/106595158/219546672-44ddf561-acbd-47ee-9e09-bcf56a15be36.png">

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [x] Something else (please add if needs merging to production or not)

## Checklist

- [x] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I have added a preview link.

2023-03-02 10:30 UTC, slega requested changes
Please replace enterprise PostgreSql with PostgreSQL. I don't see any issues other than that.

2023-03-02 10:30 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +### Launch the Tyk Enterprise Developer portal with PostgreSql
It should be 'PostgreSQL', not 'PostgreSql'.

2023-03-02 10:43 UTC, Fadzli-fast commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +### Launch the Tyk Enterprise Developer portal with PostgreSql
Got it already made the changes

2023-03-02 10:43 UTC, slega approved these changes
LGTM

2023-03-03 15:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +This guide demonstrates two approaches for setting up and running the portal with a Postgres database: using docker-compose and using separate Docker containers.
```suggestion
This guide demonstrates two approaches for setting up and running the portal with a [Postgres database]({{< ref "https://www.postgresql.org/" >}}): using docker-compose and using separate Docker containers.
```

2023-03-03 17:04 UTC, merged

2023-03-03 17:04 UTC, letzya commented
/release to release-4.3