MDCB 2.1.0 release notes
TykTechnologies/tyk-docs-hugo pull request #2333
Opened 2023-02-20 16:17 UTC by tbuchaillot

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-02-20 16:30 UTC, sredxny requested changes, later dismissed

2023-02-20 16:30 UTC, sredxny commented on tyk-docs/content/release-notes/mdcb-2.1.md
> +- MDCB works without group id. This means that when an Edge Gateway doesn’t have a group, it will defaults to the `ungrouped` group. This has some fallbacks, as we can’t use the synchroniser for the
I think this line should be part of `Fixed`. As here mostly we add new config options

2023-02-20 16:30 UTC, sredxny commented on tyk-docs/content/release-notes/mdcb-2.1.md
> +- Added a new configuration option (`enable_ownership`) that allows MDCB filter APIs by API Ownership.
worth to describe the option? Or paste a link to the config option description? so people is aware of default value.

2023-02-20 16:33 UTC, tbuchaillot commented on tyk-docs/content/release-notes/mdcb-2.1.md
> +- MDCB works without group id. This means that when an Edge Gateway doesn’t have a group, it will defaults to the `ungrouped` group. This has some fallbacks, as we can’t use the synchroniser for the
@sredxny IMO, it's an added behavior - it was not a bug.

2023-02-20 16:40 UTC, tbuchaillot commented on tyk-docs/content/release-notes/mdcb-2.1.md
> +- Added a new configuration option (`enable_ownership`) that allows MDCB filter APIs by API Ownership.
@sredxny we never cross-link with the config option. What else would you add?

2023-02-20 18:44 UTC, letzya requested changes

2023-02-20 18:44 UTC, letzya commented on tyk-docs/content/release-notes/mdcb-2.1.md
> +- Added a new configuration option (`enable_ownership`) that allows MDCB filter APIs by API Ownership.
we should definitely add links. The main content should be outside the release notes so we don't need to have it twice. Is the option described in the doc?

2023-02-20 18:44 UTC, letzya commented on tyk-docs/content/release-notes/mdcb-2.1.md
> +- MDCB works without group id. This means that when an Edge Gateway doesn’t have a group, it will defaults to the `ungrouped` group. This has some fallbacks, as we can’t use the synchroniser for the
same comment - is this in the docs as well? we have a problem with the pump and MDCB of writing the content only in the release notes and then people might not find it

2023-02-24 23:56 UTC, sredxny commented on tyk-docs/content/release-notes/mdcb-2.1.md
> +- Added a new configuration option (`enable_ownership`) that allows MDCB filter APIs by API Ownership.
@tbuchaillot usually in the config page we described the config. how is useful, default value and if applies: how the behavior can change when combined with other options. Eg: synchronizer only works when we have enabled the sync in MDCB and worker gw.... So, a link to the config description is useful

2023-03-09 10:16 UTC, tbuchaillot commented on tyk-docs/content/release-notes/mdcb-2.1.md
> +- Added a new configuration option (`enable_ownership`) that allows MDCB filter APIs by API Ownership.
added link

2023-03-09 10:25 UTC, letzya approved these changes

2023-03-09 10:26 UTC, merged

2023-03-09 10:26 UTC, letzya commented
/release to release-4.3