Typo PORTAL_HOST_PORT to PORTAL_HOSTPORT
TykTechnologies/tyk-docs-hugo pull request #2359
Opened 2023-03-06 13:10 UTC by carlostyk

## Related Issue (if applicable)

## Description
 Changed PORTAL_HOST_PORT to PORTAL_HOSTPORT as in the code

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [X] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [X] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [X] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [X] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-06 13:38 UTC, letzya requested changes
Can you please verify the rest of the env vars?

2023-03-06 13:53 UTC, slega approved these changes
LGTM

2023-03-07 09:33 UTC, letzya approved these changes

2023-03-07 09:33 UTC, merged

2023-03-07 09:34 UTC, letzya commented
/release to release-4.3