updated exmplaes of grpc and documentation. A custom port is not required
TykTechnologies/tyk-docs-hugo pull request #2362
Opened 2023-03-06 20:28 UTC by sredxny

## Related Issue (if applicable)
None

## Description
When adding grpc services in Tyk is not required to set a custom port for each service, instead, the gateway can route correctly based in the service name. Hence, in this PR I update this information and simplify the examples 

## Motivation and Context
Give proper information, be consistent and simplify examples

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-06 20:58 UTC, letzya requested changes
Looks good 
Just 2 things
1. Please add some explanation based on your take away from the conversation that led to this pr.
2. Change Api to API throughout the pr

2023-03-06 20:58 UTC, letzya commented on tyk-docs/content/key-concepts/grpc-proxy.md
> +- Ensure that `strip listen path` is set to false in your Api.
API

2023-03-06 20:58 UTC, letzya commented on tyk-docs/content/key-concepts/grpc-proxy.md
> +- Ensure that `strip listen path` is set to false in your Api.
Worth explaining the reasons for it

2023-03-07 18:59 UTC, sredxny commented
made some changes

2023-03-09 08:50 UTC, tbuchaillot approved these changes
TIL 😄

2023-03-13 12:59 UTC, mativm02 approved these changes

2023-03-13 14:15 UTC, letzya approved these changes

2023-03-13 14:15 UTC, merged

2023-03-13 14:19 UTC, letzya commented
/release to release-4.3