Update setup-controller-data-centre.md
TykTechnologies/tyk-docs-hugo pull request #2376
Opened 2023-03-08 19:26 UTC by caroltyk

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-08 19:53 UTC, zalbiraw approved these changes
LGTM

2023-03-09 10:13 UTC, letzya requested changes

2023-03-09 10:13 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-components.md
> +The Tyk Dashboard liveness health check endpoint can be configured [here]({{< ref "tyk-dashboard/configuration/#health_check_endpoint_name" >}}).
```suggestion
The Tyk Dashboard liveness health check endpoint can be configured [here]({{< ref "tyk-dashboard/configuration#health_check_endpoint_name" >}}). 
```

2023-03-09 10:13 UTC, letzya commented on tyk-docs/content/planning-for-production/monitoring/tyk-components.md
> +The Tyk MDCB liveness health check endpoint can be configured [here]({{< ref "tyk-multi-data-centre/setup-controller-data-centre/#health-check" >}}).
```suggestion
The Tyk MDCB liveness health check endpoint can be configured [here]({{< ref "tyk-multi-data-centre/setup-controller-data-centre#health-check" >}}). 
```

2023-03-09 10:16 UTC, letzya approved these changes

2023-03-09 10:17 UTC, merged

2023-03-09 10:18 UTC, letzya commented
/release to release-4.3