Update update-api-with-oas.md
TykTechnologies/tyk-docs-hugo pull request #2382
Opened 2023-03-09 12:53 UTC by letzya

Rephrased to use OpenAPI Spec instead of OAS definiton

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-09 16:29 UTC, andyo-tyk reviewed
Comments added - some typos, some suggested changes.

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +### Tutorial: Update Tyk OAS API definition with an updated OpenAPI Specification
Perhaps "Update a Tyk OAS API with an updated OpenAPI Specification"?

I'm not sure that we need the word "definition" here.

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +While developing APIs, as developers, we constantly need to update the OpenAPI Specification that is either generated from our codebase, or built using some API design tools. Tyk allows you to update
1) I would delete the word "some", as it's a big vague.
2) For consistency, could you change "the Tyk API definition" to "a Tyk OAS API"?
3) There's a missing "a" before "fresh"
4) I'd add "the" before PATCH, and I'd also put PATCH in `code` format

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +For the sake of this tutorial, create a new API by sending this Tyk OAS API Definition [https://bit.ly/39tnXgO](https://bit.ly/39tnXgO) to the Gateway API endpoint (this is an example and contains th
Typo: "minimun" should be "minimum" - and I'd put "of" after it, before "required"

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Now let's assume you made some change in your OpenAPI Specification using some tool outside Tyk's domain. It could be for example adding a new path, changing description or any other change.
Perhaps there's a missing "the" between "changing" and "description"?

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +In this case we added a new endpoint, `POST /pet`, with a schema that validates the payload it receives (`requestBody.content.application/json.schema`) and a new security scheme (The OpenAPI Specific
Typo: repeatition -> repetition

I'd suggest that, instead of "In this case we added..." we say "In this example we will add..."

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +#### Update the Tyk API definition using just your updated OpenAPI Specification
Tyk OAS API

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Tyk allows you to update a Tyk OAS API definition by providing only your OpenAPI Specification using `PATH` request.
1) Again, I would remove the word "definition"
2) There's a typo: PATH -> PATCH
3) Again, I would add "the" before PATCH

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Tyk will update the OpenAPI Specification section in the Tyk OAS API dfintion.
Typo: dfintion
(though I would just delete the word :)

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Previously you updated the Tyk OAS API Definition with a new OpenAPI Specification, which is describing a security mechanism. In order for Tyk Gateway to use this security mechanism and start protect
1) I'd remove "defintion"
2) "In order to" or "In order for" is unnecessarily wordy: perhaps just say "For Tyk Gateway to use this security mechanism..."
3) missing "the" between "within" and "Tyk"
4) Typo: definiton -> definition

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +While updating a Tyk API OAS Definition using just the OpenAPI Specification, you can also give instructions to Tyk Gateway to explicitly allow access just to paths that are documented in the OAS API
Perhaps reword this to:
You can instruct the Tyk Gateway to allow access only to paths (endpoints) explicitly documented in the Tyk OAS API using the allow list functionality. If you pass the `allowList` query parameter during the `PATCH` operation, the allow list will be automatically configured according to the OpenAPI Specification in the payload.

 --> this perhaps gives the opportunity to add a link (to here? https://tyk.io/docs/tyk-apis/tyk-gateway-api/api-definition-objects/ip-whitelisting/)

2023-03-09 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +You have demonstrated that by using theOpenAPI specification, which can be either generated from your source code or created as part of design first approach, you can update and configure the Tyk OAS
Missing a space in "the OpenAPI specification"

Perhaps "a" or "your" before "design first approach"?

As above, I'd remove the word "Definition".

2023-03-09 18:16 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +While developing APIs, as developers, we constantly need to update the OpenAPI Specification that is either generated from our codebase, or built using some API design tools. Tyk allows you to update
1. I wrote **some** since there are many tools in the market and wasn't sure if I should name a few or not

2023-03-09 18:17 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +While developing APIs, as developers, we constantly need to update the OpenAPI Specification that is either generated from our codebase, or built using some API design tools. Tyk allows you to update
```suggestion
While developing APIs, as developers, we constantly need to update the OpenAPI Specification that is either generated from our codebase or built using some API design tools. Tyk allows you to update the Tyk OAS API definition with a fresh copy of your OpenAPI Specification using the PATCH HTTP method.
```

2023-03-09 18:22 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +While developing APIs, as developers, we constantly need to update the OpenAPI Specification that is either generated from our codebase or built using some API design tools. Tyk allows you to update
@andyo-tyk your message is gone, please re-review this bit. 
I used "some" since wasn't sure if I should name a few tools like swagger UI and stoplight or not. What do you think is best? essentially we want to say it's outside tyk's domain

2023-03-09 18:23 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +### Tutorial: Update Tyk OAS API definition with an updated OpenAPI Specification
```suggestion
### Tutorial: Update Tyk OAS API definition with an updated OpenAPI Specification
### Tutorial: Update a Tyk OAS API with an updated OpenAPI Specification
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +### Tutorial: Update Tyk OAS API definition with an updated OpenAPI Specification
I think we do since it's not an API, it's an API definition but I removed it

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +For the sake of this tutorial, create a new API by sending this Tyk OAS API Definition [https://bit.ly/39tnXgO](https://bit.ly/39tnXgO) to the Gateway API endpoint (this is an example and contains th
```suggestion
For the sake of this tutorial, create a new API by sending this Tyk OAS API Definition [https://bit.ly/39tnXgO](https://bit.ly/39tnXgO) to the Gateway API endpoint (this is an example that contains the very minimal required fields):
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Now let's assume you made some change in your OpenAPI Specification using some tool outside Tyk's domain. It could be for example adding a new path, changing description or any other change.
```suggestion
Now let's assume you made some changes in your OpenAPI Specification using some tool outside Tyk's domain. It could be for example adding a new path, changing the description or any other change.
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +In this case we added a new endpoint, `POST /pet`, with a schema that validates the payload it receives (`requestBody.content.application/json.schema`) and a new security scheme (The OpenAPI Specific
spot on!

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +In this case we added a new endpoint, `POST /pet`, with a schema that validates the payload it receives (`requestBody.content.application/json.schema`) and a new security scheme (The OpenAPI Specific
```suggestion
In this example we added a new endpoint, `POST /pet`, with a schema that validates the payload it receives (`requestBody.content.application/json.schema`) and a new security scheme (The OpenAPI Specification is in the code snippet in the next section, just to avoid repetition) 
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +#### Update the Tyk API definition using just your updated OpenAPI Specification
```suggestion
#### Update the Tyk 
OAS API using just your updated OpenAPI Specification
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Tyk allows you to update a Tyk OAS API definition by providing only your OpenAPI Specification using `PATH` request.
1. In the title we can be shorter but in the explanation, we should be accurate, why remove the word "definition"?

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Tyk allows you to update a Tyk OAS API definition by providing only your OpenAPI Specification using `PATH` request.
```suggestion
Tyk allows you to update a Tyk OAS API definition by providing only your OpenAPI Specification using the `PATCH` request.
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Tyk will update the OpenAPI Specification section in the Tyk OAS API dfintion.
```suggestion
As a result, Tyk will replace the existing OpenAPI Specification in the Tyk OAS API with the new OpenAPI Specification (from the payload).
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Previously you updated the Tyk OAS API Definition with a new OpenAPI Specification, which is describing a security mechanism. In order for Tyk Gateway to use this security mechanism and start protect
```suggestion
Previously you updated the Tyk OAS API Definition with a new OpenAPI Specification, which is describing a security mechanism. For Tyk Gateway to use this security mechanism and start protecting the API, the authentication mechanism needs to be *enabled* within the Tyk section in the Tyk OAS API definition.
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +While updating a Tyk API OAS Definition using just the OpenAPI Specification, you can also give instructions to Tyk Gateway to explicitly allow access just to paths that are documented in the OAS API
```suggestion
You can instruct the Tyk Gateway to allow access only to paths (endpoints) explicitly documented in the OpenAPI Specification, using the allow list functionality. If you pass the `allowList` query parameter during the PATCH operation, the allow list will be automatically configured.
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +While updating a Tyk API OAS Definition using just the OpenAPI Specification, you can also give instructions to Tyk Gateway to explicitly allow access just to paths that are documented in the OAS API
1. Changed it a bit as we were repeating ourselves.
2. This link shows fields of classic API def. Do we have OAS API def?

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +You have demonstrated that by using theOpenAPI specification, which can be either generated from your source code or created as part of design first approach, you can update and configure the Tyk OAS
```suggestion
You have demonstrated that by using the OpenAPI Specification, which can be either generated from your source code or created as part of a design-first approach, you can update and configure the Tyk OAS API Definition accordingly.
```

2023-03-09 18:41 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +You have demonstrated that by using theOpenAPI specification, which can be either generated from your source code or created as part of design first approach, you can update and configure the Tyk OAS
Just to explain about "definition":
1. It is really a definition, not an API, the API is the actual service. 
2. if it's not there, people could be mistaken with the Tyk APIs (which we also call "tyk oas" or "tyk OpenAPI specification")

2023-03-10 10:43 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +### Tutorial: Update Tyk OAS API definition with an updated OpenAPI Specification
On reflection, you're right, we do need something at the end of the sentence - I understand it's an OAS document (https://spec.openapis.org/oas/v3.1.0#openapi-document)... and I think we don't need it after Tyk OAS API, because we're actually talking about updating the API on the Gateway. 🤦 

```suggestion
### Tutorial: Update a Tyk OAS API with an updated OpenAPI Specification document 
```

2023-03-10 10:44 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +While developing APIs, as developers, we constantly need to update the OpenAPI Specification that is either generated from our codebase, or built using some API design tools. Tyk allows you to update
Looks good. 👍

2023-03-10 16:19 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +### Tutorial: Update Tyk OAS API definition with an updated OpenAPI Specification
Actually, I've done more research and this should be "OpenAPI document" (there's no such thing as an OpenAPI Specification document"

2023-03-10 17:29 UTC, andyo-tyk requested changes
Some (hopefully final) tweaks to improve readability.

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +description: "Updating Tyk OAS API definition following in your OpenAPI defintion"
```suggestion
description: "Updating Tyk OAS API following a change in your OpenAPI definition"
```

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +For the sake of this tutorial, create a new API by sending this Tyk OAS API Definition [https://bit.ly/39tnXgO](https://bit.ly/39tnXgO) to the Gateway API endpoint (this is an example that contains t
```suggestion
For the sake of this tutorial, create a new API by sending this [Tyk OAS API Document](https://bit.ly/39tnXgO) to the Gateway API endpoint (this is an example that contains the very minimal required fields):
```

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Now let's assume you made some change in your OpenAPI definition (as mentioned above, from code or a tool, outside Tyk's domain). The change could be for  adding a new path, changing a description or
```suggestion
Now let's assume you made a change in your OpenAPI definition (as mentioned above, from code or a tool, outside Tyk's domain). The change could be adding a new path, changing a description or anything that changes the definition of the API.
```

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +In this example we added a new endpoint, `POST /pet`, with a schema that validates the payload it receives (`requestBody.content.application/json.schema`) and a new security scheme (The OpenAPI defin
```suggestion
In this example we added a new endpoint, `POST /pet`, with a schema that validates the payload it receives (`requestBody.content.application/json.schema`) and a new security scheme (the OpenAPI definition is in the code snippet in the next section, just to avoid repetition) 
```

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Tyk allows you to update a Tyk OAS API definition by providing only your OpenAPI definition using `PATH` request.
```suggestion
You can update your Tyk OAS API definition very simply - by providing your OpenAPI definition as an OpenAPI document with the `PATH` request.
```

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Tyk will update the OpenAPI definition section in the Tyk OAS API dfintion.
```suggestion
Tyk will use the content of the OpenAPI document to update just the OpenAPI section in the Tyk OAS API definition.
```

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +Previously you updated the Tyk OAS API Definition with a new OpenAPI definition, which is describing a security mechanism. In order for Tyk Gateway to use this security mechanism and start protecting
```suggestion
Previously you updated the Tyk OAS API definition with a new OpenAPI definition, that describes a new security mechanism. In order for Tyk Gateway to start protecting the API using this authentication mechanism, it needs to be *enabled* within the Tyk section of the Tyk OAS API definition.
```

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +For that, together with the `PATCH` request you just performed, add the authentication query parameter `authentication=true`, that tells Tyk to automatically enable authentication, based on the setti
```suggestion
To do this you would add the query parameter `authentication=true` to the `PATCH` request you just performed; this tells Tyk to automatically enable authentication, based on the settings in the OpenAPI definition.
```

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +While updating a Tyk API OAS Definition using just the OpenAPI definition, you can also give instructions to Tyk Gateway to explicitly allow access just to paths that are documented in the OAS API De
```suggestion
Tyk Gateway's allow list function explicitly allows access just to paths that are documented in the Tyk OAS API definition. You can enable this when updating a Tyk API OAS definition using the `PATCH` method by passing the `allowList` query parameter with the payload.
```

2023-03-10 17:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +You have demonstrated that by using theOpenAPI definition, which can be either generated from your source code or created as part of design first approach, you can update and configure the Tyk OAS AP
```suggestion
You have demonstrated that by using just the OpenAPI definition, which can be either generated from your source code or created as part of design first approach using other tools, you can update and configure an existing Tyk OAS API Definition.
```

2023-03-10 17:46 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
> +You can update your Tyk OAS API definition very simply - by providing your OpenAPI definition as an OpenAPI document with the `PATH` request.
```suggestion
You can update your Tyk OAS API definition very simply - by providing your OpenAPI definition as an OpenAPI document with the `PATCH` request.
```

2023-03-10 17:52 UTC, andyo-tyk approved these changes
Looks great, thanks.

2023-03-10 17:53 UTC, merged