Add documentation for the DCR flow in the Enterprise developer portal.
TykTechnologies/tyk-docs-hugo pull request #2383
Opened 2023-03-09 19:02 UTC by slega

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-10 14:39 UTC, zalbiraw requested changes

2023-03-10 14:39 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +Tyk offers a standard and reliable way to work with identity providers through the Dynamic Client Registration protocol (DCR), which is an Internet Engineering Task Force protocol that establishes st
```suggestion
Tyk offers a standard and reliable way to work with identity providers through the Dynamic Client Registration protocol (DCR), which is an [Internet Engineering Task Force](https://www.ietf.org/) protocol that establishes standards for dynamically registering clients with authorization servers.
```

2023-03-10 14:39 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +
```suggestion
* [Gluu](https://gluu.org/docs/gluu-server/4.0/admin-guide/openid-connect/#dynamic-client-registration)
* [Curity](https://curity.io/docs/idsvr/latest/token-service-admin-guide/dcr.html)
* [Keycloak](https://gluu.org/docs/gluu-server/4.0/admin-guide/openid-connect/#dynamic-client-registration)
* [Okta](https://developer.okta.com/docs/reference/api/oauth-clients/)

```

2023-03-10 14:39 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +
This looks weird on the UI

2023-03-10 14:39 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +To avoid that, you need to create the NoOp API and policy that won't grant access to the APIs included in the API Product but will satisfy the requirement for a default policy.
What does NoOp stand for?

2023-03-10 15:19 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +To avoid that, you need to create the NoOp API and policy that won't grant access to the APIs included in the API Product but will satisfy the requirement for a default policy.
@zalbiraw  NoOp == No Operation. Good point, I'll make that explicit.

2023-03-10 15:21 UTC, carlostyk commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +To avoid that, you need to create the NoOp API and policy that won't grant access to the APIs included in the API Product but will satisfy the requirement for a default policy.
Yup that is a good one

2023-03-10 15:56 UTC, carlostyk approved these changes
Looks good to me 👍

2023-03-12 18:54 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +To avoid that, you need to create the NoOp API and policy that won't grant access to the APIs included in the API Product but will satisfy the requirement for a default policy.
Fixed, thanks folks

2023-03-12 18:58 UTC, zalbiraw approved these changes
LGTM!

2023-03-13 14:07 UTC, letzya requested changes

2023-03-13 14:07 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +```{.shell}
```suggestion
```curl
```

2023-03-13 14:07 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +```{.shell}
```suggestion
```curl
```

2023-03-13 14:07 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +```{.json}
```suggestion
```json
```

2023-03-13 14:14 UTC, letzya approved these changes

2023-03-13 14:14 UTC, merged

2023-03-13 14:14 UTC, letzya commented
/release to release-4.3

2023-03-13 20:02 UTC, zalbiraw commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
> +* [Keycloak](https://gluu.org/docs/gluu-server/4.0/admin-guide/openid-connect/#dynamic-client-registration)
@slega none of us caught this :(