WORK IN-PROGRESS Hybrid deployment in Tyk Cloud
TykTechnologies/tyk-docs-hugo pull request #2397
Opened 2023-03-15 11:53 UTC by SonjaChevre

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-15 12:22 UTC, letzya commented
changed for you to "draft" as in WIP

2023-03-16 10:03 UTC, carolwkc commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +The helm charts are also available on [ArtifactHub](https://artifacthub.io/packages/helm/tyk-helm/tyk-pro).
```suggestion
The helm charts are also available on [ArtifactHub](https://artifacthub.io/packages/helm/tyk-helm/tyk-hybrid).
```

2023-03-16 10:03 UTC, carolwkc commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +* *(optional)* `gateway.rpc.groupId`: if you have multiple data plane (e.g. in different regions), specify the data plane group (string) to which the gateway you are deploying belong
```suggestion
* *(optional)* `gateway.rpc.groupId`: if you have multiple data plane (e.g. in different regions), specify the data plane group (string) to which the gateway you are deploying belong. The data planes in the same group share one redis.
```

2023-03-16 10:03 UTC, carolwkc commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +* `image.tag`: `v4.3` (or any other version available in [dockerhub](https://hub.docker.com/r/tykio/tyk-gateway/tags))
```suggestion
* `gateway.image.tag`: `v4.3` (or any other version available in [dockerhub](https://hub.docker.com/r/tykio/tyk-gateway/tags))
```

2023-03-16 10:03 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +* `image.tag`: `v4.3` (or any other version available in [dockerhub](https://hub.docker.com/r/tykio/tyk-gateway/tags))
I think the page https://hub.docker.com/r/tykio/tyk-gateway/tags is a bit hard to follow. The tags are not ordered/filtered and there's no release information. Shall we consider adding image tag information to https://tyk.io/docs/release-notes/version-4.3/ @letzya ?

Got a look at https://hub.docker.com/_/kong and it looks more friendly. There's a list of currently supported image tags on Overview page. We can list or LTS and latest version there. I'll raise a separate suggestion to DevOps team :)

2023-03-17 10:17 UTC, letzya commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +* `image.tag`: `v4.3` (or any other version available in [dockerhub](https://hub.docker.com/r/tykio/tyk-gateway/tags))
Yes, we should definitely update our release notes.

2023-03-20 20:37 UTC, caroltyk requested changes
Thanks for the updates

2023-03-20 20:37 UTC, carolwkc commented on tyk-docs/assets/img/hybrid-gateway/tyk-cloud-dashboard-api-manager.png
shall we mask the name & url on this page too?

2023-03-20 20:37 UTC, carolwkc commented on tyk-docs/assets/img/hybrid-gateway/tyk-cloud-hybrid-connection-control-plane.png
shall we mask the name & url on this page too?

2023-03-20 20:37 UTC, carolwkc commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Before deploying your data plane, you will need to prepare the connection details to the control plane:
```suggestion
The hybrid data plane can connect to control plane in Tyk Cloud by using the Tyk Dashboard API Access Credentials. Follow the guides below to create a user (identity for hybrid data plane) and prepare the connection details:
```

suggest to give some context about why users need to create a user below

2023-03-20 20:37 UTC, carolwkc commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +  - Copy the **Tyk Dashboard API Access Credentials** for later use (`gateway.rpc.apiKey` setting in helm)
```suggestion
  - Copy the **Tyk Dashboard API Access Credentials** for later use (`api_key` setting in Docker, `gateway.rpc.apiKey` setting in helm)
```

2023-03-20 20:37 UTC, carolwkc commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +  - Copy the **Organisation ID** for later use (`gateway.rpc.rpcKey` setting in helm)
```suggestion
  - Copy the **Organisation ID** for later use (`rpc_key` setting in Docker, `gateway.rpc.rpcKey` setting in helm)
```

2023-03-20 20:37 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +### 1. Add the Tyk official Helm repo `tyk-helm` to your local Helm registry
```suggestion
### 1. Add the Tyk official Helm repo `tyk-helm` to your local Helm repository
```

2023-03-20 20:37 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +### 3. Get the template yaml for configuration
```suggestion
### 3. Get the default values.yaml for configuration
```

2023-03-20 20:37 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +* *(optional)* `group_id`: if you have multiple data plane (e.g. in different regions), specify the data plane group (string) to which the gateway you are deploying belong. The data planes in the sam
```suggestion
* *(optional)* `gateway.rpc.group_id`: if you have multiple data plane (e.g. in different regions), specify the data plane group (string) to which the gateway you are deploying belong. The data planes in the same group share one redis instance.
```

2023-03-20 20:37 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +* *(optional)* `gateway.sharding.enabled` and `gateway.sharding.tags`: you can enable sharding to selectively load APIs to specific gateways, using tags
```suggestion
* *(optional)* `gateway.sharding.enabled` and `gateway.sharding.tags`: you can enable sharding to selectively load APIs to specific gateways, using tags. By default, sharing is disabled and gateway will load all APIs.
```

2023-03-20 20:37 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +* `redis.pass`: password set in redis (`$REDIS_PASSWORD`)
```suggestion
* `redis.pass`: password set in redis (`$REDIS_PASSWORD`). Alternatively, you can use --set flag to set it during helm installation. For example --set redis.pass=$REDIS_PASSWORD.
```

2023-03-20 20:37 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +### 6. Install the helm chart
```suggestion
### 6. Install Hybrid data plane
```

2023-03-20 20:37 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +````
```suggestion
Note: you may need to port forward if you're testing on local machine, e.g. `kubectl port-forward service/gateway-svc-tyk-hybrid -n tyk 8080:443`

```console
curl http://hostname:8080/hello -i
````
```

2023-03-20 20:37 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
>  Now it is time to publish a new API [Task 5 - Deploy your Edge Gateway and add your first API]({{< ref "/content/tyk-cloud/getting-started-tyk-cloud/first-api.md" >}})
is this link correct?

2023-03-22 07:42 UTC, SonjaChevre commented on tyk-docs/assets/img/hybrid-gateway/tyk-cloud-dashboard-api-manager.png
good call - fixed

2023-03-22 07:47 UTC, SonjaChevre commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
>  Now it is time to publish a new API [Task 5 - Deploy your Edge Gateway and add your first API]({{< ref "/content/tyk-cloud/getting-started-tyk-cloud/first-api.md" >}})
yes, it goes to the page: https://tyk.io/docs/tyk-cloud/getting-started-tyk-cloud/first-api/ 
The page needs also to be improved in the future (e.g. removing "edge gateway" and making it more about configuring APIs in Tyk Cloud using Tyk Dashboard).

2023-03-22 09:24 UTC, caroltyk approved these changes
LGTM

2023-03-22 11:16 UTC, SonjaChevre commented
@letzya can you please merge?

2023-03-22 12:18 UTC, letzya commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Finally, from your console, send a HTTP call to the /hello endpoint of the gateway `gateway-svc-tyk-hybrid`:
```suggestion
Finally, from your terminal, send an HTTP call to the /hello endpoint of the gateway `gateway-svc-tyk-hybrid`:
```

2023-03-22 12:32 UTC, merged

2023-03-22 12:37 UTC, letzya commented
/release to release-4.3