fixed external OAuth documentation code snippet comments
TykTechnologies/tyk-docs-hugo pull request #2411
Opened 2023-03-21 14:23 UTC by lghiur

2023-03-21 14:33 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +        timeout: 60 # Tyk caches the introspection result until the timeout runs out. The value is in seconds
is 60 the default?

2023-03-21 14:43 UTC, andyo-tyk requested changes

2023-03-21 14:43 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +      cache: # Tyk caches the introspection response when enabled is set true inside the cache configuration of introspection
```suggestion
      cache: # Tyk will cache the introspection response when `cache.enabled` is set to `true`
```

2023-03-21 14:43 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +        timeout: 0 # Tyk caches the introspection result until the timeout runs out. The value is in seconds
```suggestion
        timeout: 0 # Length of time for which Tyk should cache the introspection result (seconds)
```

2023-03-21 19:04 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +        timeout: 0 # Tyk caches the introspection result until the timeout runs out. The value is in seconds
what does it mean zero timeout if the cache is enabled?

2023-03-21 19:04 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +        timeout: 0 # Length of time for which Tyk should cache the introspection result (seconds)
what does it mean zero timeout with cache enabled?

2023-03-22 09:48 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +        timeout: 0 # Length of time for which Tyk should cache the introspection result (seconds)
I wondered that! @lghiur?

2023-03-22 10:06 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +        timeout: 0 # Length of time for which Tyk should cache the introspection result (seconds)
It means that it is cached forever

2023-03-22 10:08 UTC, andyo-tyk requested changes, later dismissed

2023-03-22 10:08 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +        timeout: 0 # Length of time for which Tyk should cache the introspection result (seconds)
```suggestion
        timeout: 0 # Length of time for which Tyk should cache the introspection result; if set to zero (default) then cache does not expire (seconds)
```

2023-03-23 11:43 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +        timeout: 0 # Length of time for which Tyk should cache the introspection result (seconds). "0" means that the introspection result is cached by the end of life of the token
```suggestion
        timeout: 0 # The duration (in seconds) for which Tyk will retain the introspection outcome in its cache. If the value is "0", it indicates that the introspection outcome will be stored in the cache until the token's expiration.
```

2023-03-23 13:55 UTC, letzya approved these changes

2023-03-24 15:04 UTC, merged

2023-03-24 15:04 UTC, letzya commented
/release to release-4.3