add usage instructions for tyk-sync examples
TykTechnologies/tyk-docs-hugo pull request #2417
Opened 2023-03-22 13:34 UTC by pvormste

## Related Issue (if applicable)
https://tyktech.atlassian.net/browse/TT-8179

## Description
Add usage instructions for `tyk-sync examples`

## Motivation and Context
The usage of `tyk-sync` examples is currently undocumented and therefore hidden. This PR will change it.

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [x] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [x] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-23 09:02 UTC, tbuchaillot approved these changes
LGTM 🚀

2023-03-24 09:51 UTC, jay-deshmukh approved these changes

2023-03-24 15:53 UTC, letzya commented on tyk-docs/content/tyk-sync.md
> +```
```suggestion
```bash
```

2023-03-24 15:53 UTC, letzya commented on tyk-docs/content/tyk-sync.md
> +```
```suggestion
```bash
```

2023-03-24 15:53 UTC, letzya commented on tyk-docs/content/tyk-sync.md
> +```
```suggestion
```bash
```

2023-03-24 15:55 UTC, letzya commented on tyk-docs/content/tyk-sync.md
> +Usage:
Not sure I understand why we keep showing the help output. can we have the output of the show subcommand?

2023-03-24 15:55 UTC, letzya commented on tyk-docs/content/tyk-sync.md
> +```
```suggestion
```bash
```

2023-03-24 15:55 UTC, letzya commented on tyk-docs/content/tyk-sync.md
> +  tyk-sync examples publish [flags]
again, we don't need the help output, just the publish output

2023-03-24 15:56 UTC, letzya commented on tyk-docs/content/tyk-sync.md
> +```
```suggestion
```bash
```

2023-03-24 15:59 UTC, letzya commented on tyk-docs/content/tyk-sync.md
> +It's also possible to show more details about an example by using its location:
```suggestion
It's also possible to show more details about an example by using its location. For example, based on the output from `tyk-sync examples` above, we can use the location of the example "VAT number checker UDG" to get more information:
```

2023-03-24 15:59 UTC, letzya commented on tyk-docs/content/tyk-sync.md
> +```
```suggestion
```bash
```

2023-03-24 16:00 UTC, letzya requested changes
please update per comments

2023-03-27 16:17 UTC, agata-wit approved these changes

2023-03-27 16:17 UTC, buger commented
Maybe also include references from some UDG getting started page to this doc?

2023-03-27 16:20 UTC, agata-wit commented
> Maybe also include references from some UDG getting started page to this doc?

I don't think it's necessary for a couple of reasons:

- this page will be right under "Getting started" section in the navigation menu, it will really be the easiest thing ever to find it
- there's already quite a few links in here, adding more to content that can be easily seen in navigation menu seems redundant and will make the page more cluttered

2023-03-27 17:23 UTC, merged

2023-03-28 10:06 UTC, letzya commented
@agata-wit I agree with @buger - we need more links - it's not about humans finding it and if it's easy for them, but about crawlers and SEO. Can you please add links whenever possible?

2023-03-28 12:25 UTC, agata-wit commented
ok, we could also add some links on the main page: https://deploy-preview-2417--tyk-docs.netlify.app/docs/nightly/universal-data-graph/
I already expanded it with a few links like this: https://tyk.io/docs/universal-data-graph/  (at the bottom)
we could add one more there and be like: Try an example

I'll do it in a separate PR since this is merged already.