Update the Manage API Users page with the temp password capability
TykTechnologies/tyk-docs-hugo pull request #2421
Opened 2023-03-24 13:22 UTC by slega

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-24 15:50 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumers.md
> +If your use case requires adding a new organisation, see [step by step guide]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisa
```suggestion
If your use case requires adding a new organisation, see [step by step guide]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md" >}}). When an organisation is created, a default team tied to that organisation is automatically generated too. Teams and organisations can have different visibility when it comes to API Products and plans. This can be managed within the [catalogue section]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md" >}}).
```

2023-03-31 18:20 UTC, JRWu requested changes
Documentation changes read well to me, just added a couple comments that could be reviewed!

2023-03-31 18:20 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-users.md
> +tags: ["Tyk Developer Portal","Enterprise Portal","Managing access","API Consumers"]
Are we going to reposition the Enterprise Portal as the New Developer Portal?

2023-03-31 18:20 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-users.md
> +description: "How to manage your API Consumers"
Do we need to clarify if API Consumers is "Internal" or "External" or "Both"?

2023-03-31 18:32 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-users.md
> +description: "How to manage your API Consumers"
Both. I've just add a clarification

2023-03-31 18:32 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-users.md
> +tags: ["Tyk Developer Portal","Enterprise Portal","Managing access","API Consumers"]
Not at the moment

2023-03-31 18:40 UTC, JRWu approved these changes
LGTM!

2023-04-01 12:33 UTC, merged

2023-04-01 12:34 UTC, letzya commented
/release to release-5