Update upgrading-tyk.md - wip
TykTechnologies/tyk-docs-hugo pull request #2425
Opened 2023-03-24 19:14 UTC by letzya

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-04-03 10:28 UTC, andyo-tyk requested changes, later dismissed

2023-04-03 10:28 UTC, andyo-tyk commented on tyk-docs/content/upgrading-tyk.md
> +Please read this through before upgrading any of Tyk components.
```suggestion
Please read this through before upgrading any of your Tyk components.
```

2023-04-03 10:28 UTC, andyo-tyk commented on tyk-docs/content/upgrading-tyk.md
> +This page aims to provide guidance for upgrading Tyk products. When upgrading Tyk, you'd need to upgrade separately every component that you are using. To avoid confusion each product offering and wi
```suggestion
This page provides guidance for upgrading your Tyk installation. When upgrading Tyk, you need to consider every component (e.g. Gateway, Pump, Dashboard) separately taking into consideration the style of deployment you've implemented. We have structured this guide by deployment type (e.g. Self-Managed, Multi-DC) to keep all the information you need in one place.
```

2023-04-03 10:28 UTC, andyo-tyk commented on tyk-docs/content/upgrading-tyk.md
> +- We do not introduce breaking changes unless specifically stated in the release (and it rarely happens).
```suggestion
- We do not introduce breaking changes unless specifically stated in the release notes (and it rarely happens).
```

2023-04-03 10:28 UTC, andyo-tyk commented on tyk-docs/content/upgrading-tyk.md
> +- Upgrade does not overwrite your configuration files, however, it is a good practice to routinely back these files up (using a git or another tool), especially right before upgrading your software.
```suggestion
- Upgrade does not overwrite your configuration files, however, it is good practice to back these files up routinely (using git or another tool); we strongly recommend you take a backup before upgrading Tyk.
```

2023-04-03 10:28 UTC, andyo-tyk commented on tyk-docs/content/upgrading-tyk.md
> +- Upgradng essentially means pulling the new images from https://hub.docker.com/u/tykio, and linux packages from https://packagecloud.io/tyk/
```suggestion
- Upgrading essentially means pulling the new images from https://hub.docker.com/u/tykio, and linux packages from https://packagecloud.io/tyk/ 
```

2023-04-03 10:28 UTC, andyo-tyk commented on tyk-docs/content/upgrading-tyk.md
> +- You do not need to migrate or run migration scripts unless specifically stated in the release (and it rarely happens).
```suggestion
- You do not need to migrate or run migration scripts for your APIs, policies or other assets created in Tyk unless specifically stated in the release (and it rarely happens).
```

2023-04-03 10:28 UTC, andyo-tyk commented on tyk-docs/content/upgrading-tyk.md
> +- Check our [versioning and long-term-support policies]({{< ref "frequently-asked-questions/long-term-support-releases/" >}}) for more details on the way we release miajor, minor, new features, patch
```suggestion
- Check our [versioning and long-term-support policies]({{< ref "frequently-asked-questions/long-term-support-releases/" >}}) for more details on the way we release major and minor features, patches and how long we support each release.
```

2023-04-03 10:28 UTC, andyo-tyk commented on tyk-docs/content/upgrading-tyk.md
> +- If you experience any issues with the new version you pulled, please contact Tyk Support for assistance support@tyk.io
```suggestion
- If you experience any issues with the new version you pulled, please contact Tyk Support for assistance at support@tyk.io
```

2023-04-03 10:28 UTC, andyo-tyk commented on tyk-docs/content/upgrading-tyk.md
> +To upgrade the gateway simple pull/use the image you want to use from [docker hub](https://hub.docker.com/r/tykio/tyk-gateway/tags)
```suggestion
To upgrade the Gateway simply pull/use the image you want to use from [docker hub](https://hub.docker.com/r/tykio/tyk-gateway/tags) 
```

2023-07-14 11:31 UTC, dcs3spp commented on tyk-docs/content/upgrading-tyk.md
> +In a simple environment or a development environment, in which you can simple restart your gateways, do the follwing:
```suggestion
In a development environment, in which you can simply restart your gateways, do the following:
```

2023-07-14 11:32 UTC, dcs3spp commented on tyk-docs/content/upgrading-tyk.md
> +2. Update the image version in the docker dommand or script
```suggestion
2. Update the image version in the docker command or script
```

2023-07-14 11:35 UTC, dcs3spp commented on tyk-docs/content/upgrading-tyk.md
> +To get the list of image releases, for containerised deployments such as Docker and Kubernetes use [docker hub](https://hub.docker.com/r/tykio/tyk-gateway/tags)
```suggestion
To get the list of image releases for containerised deployments such as Docker and Kubernetes, please visit [docker hub](https://hub.docker.com/r/tykio/tyk-gateway/tags)
```

2023-07-14 11:35 UTC, dcs3spp commented on tyk-docs/content/upgrading-tyk.md
> +To get the list of image releases for containerised deployments such as Docker and Kubernetes, please visit [docker hub](https://hub.docker.com/r/tykio/tyk-gateway/tags)
```suggestion
To get the list of image releases for containerised deployments, such as Docker and Kubernetes, please visit [docker hub](https://hub.docker.com/r/tykio/tyk-gateway/tags)
```

2023-07-14 11:39 UTC, dcs3spp commented on tyk-docs/content/upgrading-tyk.md
> +#### Simple environment or a Dev environment
```suggestion
#### Development environment
```

2023-07-14 11:42 UTC, dcs3spp commented on tyk-docs/content/upgrading-tyk.md
> +```bash
```suggestion

```bash
$ docker run \
  --name tyk_gateway \
  --network tyk \
  -p 8080:8080 \
  -v $(pwd)/tyk.standalone.conf:/opt/tyk-gateway/tyk.conf \
  -v $(pwd)/apps:/opt/tyk-gateway/apps \
  docker.tyk.io/tyk-gateway/tyk-gateway:v5.0
```
```

2023-07-17 17:53 UTC, letzya commented on tyk-docs/content/upgrading-tyk.md
> +```bash
@dcs3spp sorry , can't understand the suggestion

2023-07-17 21:49 UTC, letzya commented on tyk-docs/content/upgrading-tyk.md
> -chmod +x start.sh
@OldStubbsy I removed the reference to start.sh, is that okay?

2023-07-17 21:50 UTC, letzya commented on tyk-docs/content/upgrading-tyk.md
> +### Ubuntu Upgrade
@OldStubbsy Can you please help with a command for this section

2023-07-18 12:04 UTC, sedkis approved these changes

2023-07-19 15:25 UTC, OldStubbsy approved these changes
Super!

2023-07-19 16:53 UTC, merged

2023-07-19 16:55 UTC, dcs3spp commented
/release to release-5.1

2023-07-19 16:58 UTC, dcs3spp commented
/release to release-5

2023-07-19 18:41 UTC, letzya commented
/release to release-5.1

2023-07-19 18:42 UTC, letzya commented
/release to release-5