Explain Operator Reconciliation
TykTechnologies/tyk-docs-hugo pull request #2431
Opened 2023-03-27 21:51 UTC by caroltyk

## Related Issue (if applicable)

## Description
Add new page to explain Operator Reconciliation

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-28 07:17 UTC, buraksekili reviewed
LGTM! thanks @caroltyk 
I just left small suggestions.

2023-03-28 07:17 UTC, buraksekili commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation.md
> +A [Kubernetes operator](https://www.redhat.com/en/topics/containers/what-is-a-kubernetes-operator) is an application-specific controller that extends the functionality of the Kubernetes API to create
```suggestion
> A [Kubernetes operator](https://www.redhat.com/en/topics/containers/what-is-a-kubernetes-operator) is an application-specific controller that extends the functionality of the Kubernetes API to create, configure, and manage instances of complex applications on behalf of a Kubernetes user.
```

Since it is a direct reference, we may want to add a quote to the paragraph.

2023-03-28 07:17 UTC, buraksekili commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation.md
> +Before diving into Tyk Operator reconciliation, let me briefly mention some technical details about how and when reconciliation happens. Reconciliation only happens when certain events happen on your
```suggestion
Before diving into Tyk Operator reconciliation, let's briefly mention some technical details about how and when reconciliation happens. Reconciliation only happens when certain events happen on your cluster or objects. Therefore, Reconciliation will **NOT** be triggered when there is an update or modification on Tyk’s side. It only watches certain Kubernetes events and is triggered based on them. Usually, the reconciliation happens when you modify a Kubernetes object or when the cache used by the controller expires - side note, controllers, in general, use cached objects to reduce the load in the Kube API server. Typically, caches expire in ~10 hours or so but the expiration time might change based on Operator configurations.
```

ups, my bad here 🙃

2023-03-28 07:17 UTC, buraksekili commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation.md
> +Tyk Operator will compare desired state of the Kubernetes object with the observed state in Tyk. If there are drift, Tyk Operator will update the actual state on Tyk with the desired state. In the re
```suggestion
Tyk Operator will compare desired state of the Kubernetes object with the observed state in Tyk. If there is a drift, Tyk Operator will update the actual state on Tyk with the desired state. In the reconciliation, Tyk Operator mainly controls three operations; DELETE, CREATE, and UPDATE.
```

2023-03-28 08:33 UTC, caroltyk commented
Thanks @buraksekili . I've applied the suggestions.

2023-03-28 08:40 UTC, buraksekili approved these changes

2023-03-28 10:03 UTC, caroltyk commented
Hi @andyo-tyk , if you could help review the language when you have time 🙇

2023-03-29 17:45 UTC, letzya requested changes
@caroltyk can you please add a link to another tyk doc? for example to install the operator? getting started with the operator? maybe a button?

2023-03-30 09:16 UTC, carolwkc commented
@letzya Links added

2023-03-30 11:21 UTC, letzya approved these changes

2023-03-30 11:21 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation.md
> +It is also useful to setup your CI/CD pipeline to automate changes of API Definitions in Git to be published to Tyk. See [Using Tyk Operator to enable GitOps with Tyk](https://tyk.io/docs/getting-sta
```suggestion
It is also useful to set up your CI/CD pipeline to automate changes of API Definitions in Git to be published to Tyk. See [Using Tyk Operator to enable GitOps with Tyk]({{< ref "getting-started/key-concepts/gitops-with-tyk" >}}) for the key concepts behind it.
```

2023-03-30 11:22 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation.md
> +It is also useful to setup your CI/CD pipeline to automate changes of API Definitions in Git to be published to Tyk. See [Using Tyk Operator to enable GitOps with Tyk](https://tyk.io/docs/getting-sta
@caroltyk per our guide we need to use "ref" for internal links

2023-03-30 13:12 UTC, merged

2023-03-31 16:54 UTC, letzya commented
/release to release-5