Add data-graphs-api.md
TykTechnologies/tyk-docs-hugo pull request #2433
Opened 2023-03-28 07:36 UTC by buraksezer

## Related Issue (if applicable)

This PR includes the documentation for the new Data Graphs API. Currently, it only covers importing an AsyncAPI document.  

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [x] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [x] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I have added a preview link.

2023-03-28 08:46 UTC, pvormste approved these changes

2023-03-28 12:27 UTC, agata-wit commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graphs-api.md
> +```
Maybe we could add that script that you can use in Postman? 
`pm.environment.set("asyncapi_document", JSON.stringify(`<AsyncAPI document>`))`
I think people will mostly use this collection via Postman anyway and it could be nice to be able to copy the script and just import yaml quickly. It could be a Note/Tip kind of an object in the docs.

2023-03-28 21:11 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graphs-api.md
> +The Dashboard exposes the `/api/data-graphs/data-sources/import` Dashboard API which allows you to import an AsyncAPI document.
Please add the release notes https://tyk.io/docs/release-notes/version-5.0/#tyk-dashboard a link to this to this page

2023-03-28 21:12 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graphs-api.md
> +### Import an AsyncAPI Document
This page is a dead-end - can we please add links to it?  asyncapi definition for start, and also to tyk docs

2023-03-28 21:28 UTC, letzya requested changes
per my comments

2023-03-29 09:44 UTC, letzya approved these changes

2023-03-29 09:44 UTC, merged

2023-03-29 09:44 UTC, letzya commented
/release to release-5