Fix links and improve content
TykTechnologies/tyk-docs-hugo pull request #2458
Opened 2023-03-30 18:26 UTC by letzya

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-03-31 07:12 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +In Tyk you will set this information and a other configuration values in an object called *Tyk API definition*. Once you create this API definition in Tyk Gateway, it can start serving your consumers
```suggestion
In Tyk you will set this information and other configuration values in an object called *Tyk API definition*. Once you create this API definition in Tyk Gateway, it can start serving your consumers and forward their requests to your API serve your APIs. In more technical terms, Tyk gateway will listen to requests (on the listen path) and [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy) them to your actual API (which is your backend service that listens on the target URL you set in the API definition) 
```

2023-03-31 07:13 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +You have an API with a running service and you want to use Tyk gateway in front of your API to protect and serve it.
```suggestion
You have an API with a running service and you want to use Tyk Gateway in front of your API to protect and serve it.
```

2023-03-31 07:15 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +In order for Tyk Gateway to do that, you need to configure it. The minimum information you would need to provide Tyk with is the **listen path** you want your consumers to use when calling your API v
```suggestion
In order for Tyk Gateway to do that, you need to configure it. The minimum information you would need to provide Tyk with is the **listen path** you want your consumers to use when calling your API via Tyk and your *API URL* (your service URL) for Tyk to send the request to. 
```

2023-03-31 07:17 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +Please choose the tab with the product you are using for a detail guide to create Tyk API definition:
```suggestion
Please choose the tab with the product you are using for a detailed guide to create Tyk API definition:
```

2023-03-31 07:19 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +Before you continue this tutorial, you need a running (Tyk OSS gateway)({{< ref "tyk-oss-gateway" >}}). Click the button for installting Tyk Gateway in your preferred way:
```suggestion
Before you continue this tutorial, you need a running (Tyk OSS gateway)({{< ref "tyk-oss-gateway" >}}). Click the button for installing Tyk Gateway in your preferred way:
```

2023-03-31 07:19 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +There are two ways to configure Tyk Gateway with an API definitions:
```suggestion
There are two ways to configure Tyk Gateway with an API definition:
```

2023-03-31 07:22 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +1. [Create an API with the Tyk Gateway API]({{< ref "#tutorial-create-an-api-with-the-tyk-gateway-api" >}}) - Tyk gateway provides API to provided various services among which are creating API defini
The usage of `provided` seems incorrect. Please apply the suggested changes if it looks okay to you.
```suggestion
1. [Create an API with the Tyk Gateway API]({{< ref "#tutorial-create-an-api-with-the-tyk-gateway-api" >}}) - Tyk Gateway offers APIs to provide various services, among which are creating API definitions.
```

2023-03-31 07:23 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +2. [Create an API in File-based Mode]({{< ref "#tutorial-create-an-api-in-file-based-mode" >}}) - By creating an API definiton file and load it to the gateway. This is demonstrated the section .
```suggestion
2. [Create an API in File-based Mode]({{< ref "#tutorial-create-an-api-in-file-based-mode" >}}) - By creating an API definiton file and load it to the gateway. This is demonstrated in the section.
```

2023-03-31 07:32 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +The Cloud is simply the SaaS version of the Self-Managed product, but there are a few differences. Please follow the [Cloud guide] ({{< ref "tyk-cloud/getting-started-tyk-cloud/first-api" >}}) to get
Also, the link that `[Cloud guide]` refers to does not work when I check the preview deployment. Is the reference format correct?
```suggestion
The Cloud is simply the SaaS version of the Self-Managed product, but there are a few differences. Please follow the [Cloud guide]({{< ref "tyk-cloud/getting-started-tyk-cloud/first-api" >}}) to get started.
```

2023-03-31 08:47 UTC, buraksekili approved these changes

2023-03-31 08:48 UTC, letzya commented on tyk-docs/content/getting-started/create-api.md
> +The Cloud is simply the SaaS version of the Self-Managed product, but there are a few differences. Please use the [cloud guide to create your first API]({{< ref "tyk-cloud/getting-started-tyk-cloud/f
@buraksekili what do you think about this?

2023-03-31 08:48 UTC, andyo-tyk commented
I'm still working on this one

2023-03-31 09:37 UTC, buraksekili commented on tyk-docs/content/getting-started/create-api.md
> +The Cloud is simply the SaaS version of the Self-Managed product, but there are a few differences. Please use the [cloud guide to create your first API]({{< ref "tyk-cloud/getting-started-tyk-cloud/f
Both of them look fine, and I am okay with both. Still, I'd prefer the first version: `Please make sure you follow the Cloud Get Started guide instead` because we mention differences between Self-Managed and Cloud at the beginning of the sentence. So, in my opinion, it is better to forward users to the Get Started guide instead of creating API guideline of Cloud (which looks like specific documentation of Cloud).

2023-03-31 10:47 UTC, andyo-tyk requested changes

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +You have an API with a running service and you want to use Tyk Gateway in front of your API to protect and serve it.
```suggestion
You have a running service with an API that you want your users to consume; you want to protect and manage access to that API using Tyk Gateway - how do you do that?
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +In order for Tyk Gateway to do that, you need to configure it. The minimum information you would need to provide Tyk with is the **listen path** you want your consumers to use when calling your API v
```suggestion
For Tyk Gateway to protect and [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy) calls to your upstream service, you need to configure an API on Tyk Gateway. The minimum information that Tyk requires is the **listen path** (which is a path on the Tyk Gateway URL that you want your consumers to call) and your **API URL** (which is the URL of your service to which Tyk should forward requests).
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +In order for Tyk Gateway to do that, you need to configure it. The minimum information you would need to provide Tyk with is the **listen path** you want your consumers to use when calling your API v
Should this be Target URL rather than API URL?

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +In Tyk you will set this information and other configuration values in an object called *Tyk API definition*. Once you create this API definition in Tyk Gateway, it can start serving your consumers a
```suggestion
This information and other configuration values are stored in an object called a *Tyk API definition*. Once you have created your Tyk API definition and deployed it in the Tyk Gateway, the Gateway can start serving your consumers, forwarding their requests to your upstream service's API.
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +The Cloud is simply the SaaS version of the Self-Managed product, but there are a few differences. Please use the [cloud guide to create your first API]({{< ref "tyk-cloud/getting-started-tyk-cloud/f
```suggestion
Tyk Cloud is the SaaS version of the Self-Managed product, though there are a few differences. Please use the Tyk Cloud [Getting Started guide]({{< ref "tyk-cloud/getting-started-tyk-cloud/first-api" >}}) to create your first API.
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +**Integration with your Open API documentation**
```suggestion
**Integration with your OpenAPI documentation**
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +In Tyk v4.1 we introduced an integration with [Open API Specification](https://swagger.io/specification/) (OAS) which is used as a new format for *Tyk API definition*. We call it object *Tyk OAS API
```suggestion
In Tyk v4.1 we introduced support for APIs defined according to the [OpenAPI Specification v3.0.3](https://spec.openapis.org/oas/v3.0.3) (OAS). This introduces a standard way to describe the vendor-agnostic elements of an API (the OpenAPI Definition, stored as an OpenAPI Document); we take this and add Tyk-specific configuration options to create the *Tyk OAS API Definition*. You can import your own OpenAPI document and Tyk will use this to generate the Tyk OAS API Definition. For a detailed tutorial on using OAS with Tyk Gateway, check out our guide to [creating a Tyk OAS API Definition]({{< ref "getting-started/using-oas-definitions/create-an-oas-api#tutorial-create-an-oas-api-with-the-tyk-gateway-api" >}}).
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +Before you continue this tutorial, you need a running [Tyk OSS gateway]({{< ref "tyk-oss-gateway" >}}). Click the button for installing Tyk Gateway in your preferred way:
```suggestion
Before you continue this tutorial, you will need a running [Tyk OSS gateway]({{< ref "tyk-oss-gateway" >}}). Click the button for instructions on how to install Tyk Gateway:
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +{{< button_left href="https://tyk.io/sign-up/#oss" color="green" content="Install tyk gateway" >}}
```suggestion
{{< button_left href="https://tyk.io/sign-up/#oss" color="green" content="Install Tyk Gateway" >}}
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +## API definition Creation Methods
```suggestion
## Creating an API on Tyk Gateway
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +1. [Create an API with the Tyk Gateway API]({{< ref "#tutorial-create-an-api-with-the-tyk-gateway-api" >}}) - Tyk Gateway offers APIs to provide various services among which are creating API definiti
```suggestion
1. [Create an API with the Tyk Gateway API]({{< ref "#tutorial-create-an-api-with-the-tyk-gateway-api" >}}) - Tyk Gateway has its own Gateway API which provides various services including the registering of Tyk API Definitions on the Gateway.
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +2. [Create an API in File-based Mode]({{< ref "#tutorial-create-an-api-in-file-based-mode" >}}) - By creating an API definiton file and load it to the gateway. This is demonstrated in the section.
```suggestion
2. [Create an API in File-based Mode]({{< ref "#tutorial-create-an-api-in-file-based-mode" >}}) - alternatively you can create a Tyk API Definition in a file and then load it to the Gateway. This is demonstrated in the section.
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +2. [Create an API in File-based Mode]({{< ref "#tutorial-create-an-api-in-file-based-mode" >}}) - By creating an API definiton file and load it to the gateway. This is demonstrated in the section.
"This is demonstrated in the section" - which section??

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
>  See our video for adding an API to the Open Source Gateway via the Gateway API and Postman:
```suggestion
See our video to see how easy it is to add an API to Tyk's Open Source Gateway using the Tyk Gateway API and Postman:
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +In order to use the Gateway API you will need an API key for your Gateway APIs and one command to create the API and make it live.
```suggestion
In order to use the Gateway API to create a Tyk API Definition you will need the API key for your deployment's Gateway API and then issue just one command to create the API and make it live.
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
>  Your Tyk Gateway API secret is stored in your `tyk.conf` file, the property is called `secret`, you will need to use this as a header called `x-tyk-authorization` to make calls to the Gateway API.
```suggestion
The API key to access your Tyk Gateway API is stored in your `tyk.conf` file; the property is called `secret`. You will need to provide this value in a header called `x-tyk-authorization` when making calls to the Gateway API.
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +A generated API ID will be added to Tyk API definition if it's not provided while creating an API with Tyk Gateway API.
```suggestion
All APIs deployed on Tyk Gateway are given a unique `API ID`; if you don't provide one in the Tyk API Definition when creating the API, then an `API ID` will be generated automatically.
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/shared/create-api-include.md
> +**Integration with your Open API documentation**
```suggestion
**Integration with your OpenAPI documentation**
```

2023-03-31 10:47 UTC, andyo-tyk commented on tyk-docs/content/shared/create-api-include.md
> +In Tyk v4.1 we introduced an integration with [Open API Specification](https://swagger.io/specification/) (OAS) which is used as a new format for *Tyk API definition*. We call it object *Tyk OAS API
```suggestion
In Tyk v4.1 we introduced support for APIs defined according to the [OpenAPI Specification v3.0.3](https://spec.openapis.org/oas/v3.0.3) (OAS). This introduces a standard way to describe the vendor-agnostic elements of an API (the OpenAPI Definition, stored as an OpenAPI Document); we take this and add Tyk-specific configuration options to create the *Tyk OAS API Definition*. You can import your own OpenAPI document and Tyk will use this to generate the Tyk OAS API Definition. For a detailed tutorial on using OAS with Tyk Gateway, check out our guide to [creating a Tyk OAS API Definition]({{< ref "getting-started/using-oas-definitions/create-an-oas-api#tutorial-create-an-oas-api-with-the-tyk-gateway-api" >}}).
```

2023-03-31 13:27 UTC, letzya commented on tyk-docs/content/getting-started/create-api.md
> +The Cloud is simply the SaaS version of the Self-Managed product, but there are a few differences. Please use the [cloud guide to create your first API]({{< ref "tyk-cloud/getting-started-tyk-cloud/f
ok i get you. I just didn't like the instruction `Please make sure you follow` , I'll ament

2023-03-31 13:30 UTC, letzya commented on tyk-docs/content/getting-started/create-api.md
> +In order for Tyk Gateway to do that, you need to configure it. The minimum information you would need to provide Tyk with is the **listen path** you want your consumers to use when calling your API v
in Tyk it's target url but here I wanted to use a generic name

2023-03-31 13:33 UTC, letzya commented on tyk-docs/content/getting-started/create-api.md
> +2. [Create an API in File-based Mode]({{< ref "#tutorial-create-an-api-in-file-based-mode" >}}) - By creating an API definiton file and load it to the gateway. This is demonstrated in the section.
My link disappeared. will fix t

2023-03-31 13:35 UTC, letzya commented on tyk-docs/content/getting-started/create-api.md
> +1. [Create an API with the Tyk Gateway API]({{< ref "#tutorial-create-an-api-with-the-tyk-gateway-api" >}}) - Tyk Gateway offers APIs to provide various services among which are creating API definiti
`has its own Gateway API` - should be `has its own APIs` @andyo-tyk

2023-04-04 11:22 UTC, andyo-tyk requested changes, later dismissed
A few more tweaks to improve readability that only became obvious when seeing it "live"

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +You have a running service with an API that you want your users to consume; you want to protect and manage access to that API using Tyk Gateway - how do you do that?
```suggestion
You have a running service with an API that you want your users to consume; you want to protect and manage access to that API using Tyk Gateway - how do you do that?  
<br>
```

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +For Tyk Gateway to protect and [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy) calls to your upstream service, you need to configure an API on Tyk Gateway. The minimum information that T
```suggestion
For Tyk Gateway to protect and [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy) calls to your upstream service, you need to configure an API on Tyk Gateway. The minimum information that Tyk requires is the **listen path** (which is a path on the Tyk Gateway URL that you want your consumers to call) and your **API URL** (which is the URL of your service to which Tyk should forward requests).  
<br>
```

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +You have a running service with an API that you want your users to consume; you want to protect and manage access to that API using Tyk Gateway - how do you do that?
Suggested new and blank lines to improve readability

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +This information and other configuration values are stored in an object called a *Tyk API definition*. Once you have created your Tyk API definition and deployed it in the Tyk Gateway, the Gateway ca
```suggestion
This information and other configuration values are stored in an object called a *Tyk API Definition*. Once you have created your Tyk API Definition and deployed it in the Gateway, Tyk can start serving your consumers, forwarding their requests to your upstream service's API.
```

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +Please choose the tab with the product you are using for a detailed guide to create Tyk API definition:
```suggestion
To reach a detailed guide to creating Tyk API Definitions, please choose the tab for the product you are using:
```

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +Tyk Cloud is the SaaS version of the Self-Managed product, though there are a few differences. Please use the Tyk Cloud [Getting Started guide]({{< ref "tyk-cloud/getting-started-tyk-cloud/first-api"
```suggestion
Tyk Cloud is the SaaS version of the Self-Managed product, though there are a few differences.  
<br>  
Please use the Tyk Cloud [Getting Started guide]({{< ref "tyk-cloud/getting-started-tyk-cloud/first-api" >}}) to create your first API.
```

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +**Note**
It looks really messy having both "Note" and "Integration with your OpenAPI documentation" (line 68) as titles in this note box. If we could delete this line (Note) then it would be good, but if the standard format in Tyk docs is that every note box has "Note" as a titel, then we should delete "Integration with your OpenAPI documentation".
So we should have one or the other, not both.

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
> +In Tyk v4.1 we introduced support for APIs defined according to the [OpenAPI Specification v3.0.3](https://spec.openapis.org/oas/v3.0.3) (OAS). This introduces a standard way to describe the vendor-a
```suggestion
In Tyk v4.1 we introduced support for APIs defined according to the [OpenAPI Specification v3.0.3](https://spec.openapis.org/oas/v3.0.3) (OAS).  
This introduces a standard way to describe the vendor-agnostic elements of an API (the OpenAPI Definition, stored as an OpenAPI Document); we take this and add Tyk-specific configuration options to create the *Tyk OAS API Definition*. You can import your own OpenAPI document and Tyk will use this to generate the Tyk OAS API Definition.  
For a detailed tutorial on using OAS with Tyk Gateway, check out our guide to [creating a Tyk OAS API Definition]({{< ref "getting-started/using-oas-definitions/create-an-oas-api#tutorial-create-an-oas-api-with-the-tyk-gateway-api" >}}).
```

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
>  To create the API, lets send a definition to the `apis` endpoint, which will return the status and version of your Gateway. Change the `x-tyk-authorization` value and `curl` domain name and port to b
```suggestion
To create the API, let's send a Tyk API definition to the `/apis` endpoint on your Tyk Gateway. Remember to change the `x-tyk-authorization` value (API key) in the header of your API call and set the domain name and port to target your Tyk Gateway in the `curl` command.
```

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api.md
>  We just sent an API definition to the Tyk `/apis` endpoint. API definitions are discussed in detail in the API section of this documentation. These objects encapsulate all of the settings for an API
```suggestion
We just registered a new API on your Tyk Gateway by sending a Tyk API definition to your Gateway's `/apis` endpoint.  
Tyk API definitions encapsulate all of the settings for an API within Tyk Gateway and are discussed in detail in the [API section]({{< ref "/tyk-gateway-api/api-definition-objects" >}}) of this documentation.
```

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/shared/create-api-include.md
> +**Note**
As on the other page, can we please either delete "Note" or "Integration with your OpenAPI documentation"?

2023-04-04 11:22 UTC, andyo-tyk commented on tyk-docs/content/shared/create-api-include.md
> +In Tyk v4.1 we introduced support for APIs defined according to the [OpenAPI Specification v3.0.3](https://spec.openapis.org/oas/v3.0.3) (OAS). This introduces a standard way to describe the vendor-a
```suggestion
In Tyk v4.1 we introduced support for APIs defined according to the [OpenAPI Specification v3.0.3](https://spec.openapis.org/oas/v3.0.3) (OAS).  
This introduces a standard way to describe the vendor-agnostic elements of an API (the OpenAPI Definition, stored as an OpenAPI Document); we take this and add Tyk-specific configuration options to create the *Tyk OAS API Definition*. You can import your own OpenAPI document and Tyk will use this to generate the Tyk OAS API Definition.  
For a detailed tutorial on using OAS with Tyk Gateway, check out our guide to [creating a Tyk OAS API Definition]({{< ref "getting-started/using-oas-definitions/create-an-oas-api#tutorial-create-an-oas-api-with-the-tyk-gateway-api" >}}).
```

2023-04-19 18:29 UTC, letzya commented on tyk-docs/content/shared/create-api-include.md
> +**Integration with your OpenAPI documentation**
```suggestion
**Note: Integration with your OpenAPI documentation**
```

2023-04-19 18:29 UTC, letzya commented on tyk-docs/content/shared/create-api-include.md
> +**Note**
```suggestion
```

2023-04-19 18:31 UTC, letzya commented on tyk-docs/content/shared/create-api-include.md
> +**Note**
done

2023-04-19 18:54 UTC, merged

2023-04-19 18:54 UTC, letzya commented
/release to release-5