WIP - Edits to GraphQL docs section
TykTechnologies/tyk-docs-hugo pull request #2459
Opened 2023-03-31 15:09 UTC by agata-wit

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-04-05 08:14 UTC, pvormste commented on tyk-docs/content/graphql/introspection.md
> +When [**creating a GraphQL proxy**]({{< ref "/graphql/creating-gql-api">}}) in Tyk Dashboard an introspection query is used to fetch the schema from the GraphQL upstream and display it in the schema
this one is rendering as `<strong>creating a GraphQL proxy</strong>` in the preview

2023-04-05 08:17 UTC, pvormste commented on tyk-docs/content/graphql/introspection.md
> +A GraphQL server can provide information about its schema. This functionality is called **introspection** and is achievable by sending an **introspection query** to the GraphQL server.
maybe we can also link to GraphQL spec here: https://spec.graphql.org/October2021/#sec-Introspection

2023-04-05 08:31 UTC, pvormste commented on tyk-docs/content/graphql/graphql-playground.md
> +When you are creating or editing your GraphQL API, any change you make can be tested using Tyk Dashboard built-in GraphiQL Playground.
Should we also mention that there is also an API Playground that can be enabled via API definition? Also listing the differences maybe

2023-04-05 09:28 UTC, agata-wit commented on tyk-docs/content/graphql/graphql-playground.md
> +When you are creating or editing your GraphQL API, any change you make can be tested using Tyk Dashboard built-in GraphiQL Playground.
Yes! I added this now!

2023-04-05 09:30 UTC, agata-wit commented on tyk-docs/content/graphql/introspection.md
> +A GraphQL server can provide information about its schema. This functionality is called **introspection** and is achievable by sending an **introspection query** to the GraphQL server.
TBH I don't want to give too many external links, because they take the user away from our page and move them to someone else's and that's a risk they won't come back.
In some cases those external links are necessary but I think in this page we can do without it.

2023-04-05 09:42 UTC, pvormste commented on tyk-docs/content/graphql/introspection.md
> +A GraphQL server can provide information about its schema. This functionality is called **introspection** and is achievable by sending an **introspection query** to the GraphQL server.
I do agree in general, but there are 2 reasons why I think it is a good idea to add it:
 1. Introspection is a concept that not many users are aware of, especially when using GraphQL for the first time. Our docs try to explain what GraphQL is so why not allow the user to read more about the introspection concept in the GraphQL Spec.
 2. The GraphQL spec is our baseline and people will try to figure out how compliant Tyk is with the spec. So it won't hurt to provide the references for faster access. In the end the GraphQL spec is just the spec and users will need to come back t our docs because the spec doesn't explain how to work with Tyk - so I don't see a risk that the user won't come back.

tl;dr: The spec is not our enemy :-)

2023-04-05 11:07 UTC, agata-wit commented on tyk-docs/content/graphql/introspection.md
> +A GraphQL server can provide information about its schema. This functionality is called **introspection** and is achievable by sending an **introspection query** to the GraphQL server.
Good points. You convinced me :) Added!

2023-04-11 09:01 UTC, pvormste approved these changes

2023-04-17 16:14 UTC, letzya commented on tyk-docs/content/graphql/creating-gql-api.md
> +In order to complete the next steps, you need to have the [Tyk Community Edition installed]({{< ref "tyk-oss-gateway" >}}).
```suggestion
In order to complete the next steps, you need to have the [Tyk OSS]({{< ref "tyk-oss-gateway" >}}) installed.
```

2023-04-18 19:35 UTC, letzya requested changes

2023-04-18 19:35 UTC, letzya commented on tyk-docs/content/graphql/complexity-limiting.md
> -    - /graphql/complexity-limiting/
@agata-wit FYI - not need for an alias that is identical to the the file name and path

2023-04-18 19:35 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/graphql-subscriptions.md
> +Starting with Tyk `4.3.0` the number of supported subscription protocols has been extended.
Not sure I understand what does this mean? 
Also can you write` v4.3.0`

2023-04-18 19:35 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/graphql-subscriptions.md
> +If the upstream subscription GQL API is protected please enable the authentication via query params to pass header through.
```suggestion
If the upstream subscription GraphQL API is protected please enable the authentication via query params to pass the header through.
```

2023-04-19 08:14 UTC, agata-wit commented on tyk-docs/content/graphql/complexity-limiting.md
> -    - /graphql/complexity-limiting/
What's not needed? The weight? Or the alias itself?

2023-04-19 08:18 UTC, agata-wit commented on tyk-docs/content/getting-started/key-concepts/graphql-subscriptions.md
> +Starting with Tyk `4.3.0` the number of supported subscription protocols has been extended.
I changed the sentence a bit to hopefully make it clearer and added the 'v' as well.

2023-04-19 18:13 UTC, letzya commented on tyk-docs/content/graphql/complexity-limiting.md
> -    - /graphql/complexity-limiting/
yes, I just saw you added it in the past so was letting you know I removed it from this page.

2023-04-19 18:14 UTC, letzya approved these changes

2023-04-19 18:14 UTC, merged

2023-04-19 18:15 UTC, letzya commented
/release to release-5