Update datadog docs
TykTechnologies/tyk-docs-hugo pull request #2478
Opened 2023-04-10 19:16 UTC by zalbiraw

## Related Issue (if applicable)

Update datadog docs about logs and analytics

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-04-17 15:25 UTC, JRWu approved these changes
LGTM, short and sweet

2023-04-17 20:08 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +To allow Datadog to read the Tyk logs correctly. We need to create a pipeline to process the data and allow Datadog to understand that data.
Please add something to clarify that you need a running tyk deployment that already sends data to datadog (with Datadog Agent)

2023-04-17 20:10 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +Next we will need to add processor to the pipeline. Select the Grok Parser processor type, give it a name and click on the `Parse My Logs` button and `Create` .
It is not clear that you need to expand the pipeline that you just created and there you can click to create the parser 

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/3155222/232598977-31126fde-cbbb-463d-9b31-27d4a15d5571.png">

2023-04-18 19:00 UTC, letzya requested changes
I added some content to tyk-docs/content/tyk-configuration-reference/tyk-pump-configuration/datadog.md

Please review my other comments

2023-04-18 19:00 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +title: Datadog logs show up under the error status
I don't fully understand the title. 
Also please add a description

2023-04-18 19:00 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +    parent: "Frequently Asked Questions"
Any reason for not putting this under `troubleshooting/tyk-pump/` section? or even better - move it to a section in `tyk-docs/content/tyk-configuration-reference/tyk-pump-configuration/datadog.md`

2023-04-19 14:59 UTC, zalbiraw commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +title: Datadog logs show up under the error status
```suggestion
title: Tyk logs scraped with Datadog agent show up as errors under Datadog logs 
```

2023-04-19 15:00 UTC, zalbiraw commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +    parent: "Frequently Asked Questions"
This is not part of the pump configuration. This has to do with datadog agent scraping logs and those logs not being parsed properly by dd

2023-04-19 18:16 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +    parent: "Frequently Asked Questions"
ok, so please put it under troubleshooting/tyk-pump/

2023-04-19 18:20 UTC, zalbiraw commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +    parent: "Frequently Asked Questions"
I think you miss understand this is not relevant to pump. It scraps all container logs.

2023-04-20 14:00 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +    parent: "Frequently Asked Questions"
ok gotcha.I think we need to make this clearer. 
his FAQ's title is about getting errors `Tyk logs scraped with Datadog agent show up as errors under Datadog` - maybe it should be `Send Tyk container logs to Datadogs `

2023-04-20 14:57 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +To allow Datadog Agent to scrape the logs of your Tyk deployment correctly.
```suggestion
With Datadog you can view logs of all your Tyk components.
To allow Datadog Agent to scrape the logs of your Tyk deployment correctly you need to create a pipeline in Datadog, to process and underst and this data.
```

2023-04-20 14:57 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +We need to create a pipeline to process the data and allow Datadog to understand that data.
```suggestion
```

2023-04-20 16:04 UTC, zalbiraw commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +    parent: "Frequently Asked Questions"
The question that the user would be asking is `why are tyk logs showing up as errors in my datadog logs` the datadog agent integration is going to pick up the tyk container logs by default and those by default will show up as errors. So maybe we can do `tyk container logs show up under the error status in Datadog logs`

2023-04-21 11:22 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +    parent: "Frequently Asked Questions"
ok, now i remember, I thought I disabled the collection of the logs in my configuration doc, but maybe it was just something i did in my test env

2023-04-21 11:24 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
> +title: Tyk logs scraped with Datadog agent show up as errors under Datadog logs
```suggestion
title: All tyk container logs show up under the error status in Datadog logs
```

2023-04-21 11:25 UTC, letzya approved these changes

2023-04-21 11:29 UTC, merged

2023-04-21 12:46 UTC, letzya commented
/release to release-5