added detailed instructions on upgrading control plane and edge gatew…
TykTechnologies/tyk-docs-hugo pull request #2484
Opened 2023-04-13 18:42 UTC by LLe27

…ays on tyk cloud

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-04-19 19:07 UTC, letzya commented
@LLe27 FYI this needs peer review

2023-04-20 12:30 UTC, LLe27 commented
Thanks @letzya , submitted to slack for approval.

2023-05-15 10:06 UTC, letzya commented
@LLe27 can we please approve this?

2023-05-16 13:54 UTC, LLe27 commented
@letzya i'll reach out to some people and see if anyone can review

2023-05-16 14:50 UTC, vverbani requested changes

2023-05-16 14:50 UTC, vverbani commented on tyk-docs/content/tyk-cloud/environments-&-deployments/managing-gateways.md
> +{{< img src="/img/admin/cp-edge-upgrade-deployed.png" alt="Deploying notification" >}}
```suggestion
{{< img src="/img/admin/cp-edge-upgrade-deployed.png" alt="Deployed notification" >}}
```

2023-05-16 14:50 UTC, vverbani commented on tyk-docs/content/tyk-cloud/environments-&-deployments/managing-control-planes.md
> +{{< img src="/img/admin/cp-edge-upgrade-deployed.png" alt="Deploying notification" >}}
```suggestion
{{< img src="/img/admin/cp-edge-upgrade-deployed.png" alt="Deployed notification" >}}
```

2023-05-17 15:02 UTC, vverbani approved these changes

2023-05-17 15:02 UTC, merged