Update mdcb-components.md
TykTechnologies/tyk-docs-hugo pull request #2487
Opened 2023-04-14 09:48 UTC by caroltyk

1. Align the use of "Worker Gateway" and "Management Gateway" terminologies 
- We use different terms in the diagram and text, users have to make assumption to match "Worker Gateway" / "Management Gateway" in the diagram with the explanation in text which says "Tyk Gateway"
- Different diagrams use "Tyk Gateway" or "Worker Gateway" / "Management Gateway" at different places

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-04-14 09:51 UTC, caroltyk commented
@andyo-tyk @letzya 

Let's discuss first before I make any changes. Are the terms "Worker Gateway" and "Management Gateway" official in the context of MDCB? I'd propose not to use "Tyk Gateway" in the explanation on this page.

2023-04-14 10:24 UTC, andyo-tyk commented
Hey Carol,
There was method to the madness.
At this point in time, all the Gateways are the same - they are all Tyk Gateways - it is only in configuration and usage that they differ.
One is configured as the Management Gateway (or perhaps Control Plane Gateway would be better?), the others are configured as Worker Gateways (or perhaps Data Plane Gateway, or Edge Gateway, or Node, or.... (you know the story...)).
So I intentionally used "Tyk Gateway" to emphasise the fact that there is no special componentry for Control/Data planes, only that they are configured and used differently.

2023-04-14 10:31 UTC, andyo-tyk commented
I strongly recommend that you don't mention Management Gateway in the initial list of components, as this reinforces any thought that it's a different entity from Tyk Gateway.

The structure of the page was deliberate:

- High level view of MDCB, with one-line description of each component
- Then going into detail for Control Plane and Data Planes, explaining which components are mandatory, which are optional, and how they are used within THAT context (which is where we could say that the Tyk Gateway deployed in the Control Plane acts as the "Management Gateway" and similar for the Data Plane, that the Tyk Gateway deployed here acts as "Worker Gateway" (or whatever you want to call it).

On reflection, I agree that it would be better to be consistent in the diagrams - only use "Tyk Gateway" - and then in the descriptions of Control and Data Planes that's the place to introduce the Management/Worker/whatever terminology.

I hope this helps.

2023-04-14 11:07 UTC, caroltyk commented
There were 2 confusions I want to improve:
1. In the first diagram, "Tyk Gateway" is used in both control plane and data plane. The explanation of 'Tyk Gateway" below is for data plane only. We can talk about the different roles the gateway has in control plane & data plane?
2. In the Control Plane and Data Plane diagram, we use "Management Gateway" and "Worker Gateway" labels. I'd like to align the term used in diagram with the explanation below it.

2023-04-14 11:09 UTC, andyo-tyk commented
> 1. In the first diagram, "Tyk Gateway" is used in both control plane and data plane. The explanation of 'Tyk Gateway" below is for data plane only. We can talk about the different roles the gateway has in control plane & data plane?

Yes, I think we could definitely improve that one-liner. 👍 

> 2. In the Control Plane and Data Plane diagram, we use "Management Gateway" and "Worker Gateway" labels. I'd like to align the term used in diagram with the explanation below it.

Yes, agreed - that's what I was trying to say (but failed to get across succinctly) in my comment above.

2023-04-14 11:15 UTC, caroltyk commented
Thanks @andyo-tyk. There were 2 confusions I want to improve:
1. In the first diagram, "Tyk Gateway" is used in both control plane and data plane. The explanation of 'Tyk Gateway" below is for data plane only. It mentions "Worker Gateway" in the diagram too... 
Suggestions:
* Let's remove "no Worker Gateway" from the diagram to keep it simple
* Add a line in "Tyk Gateway": Only Data Plane will serve traffic for API consumers.

2. In the Control Plane and Data Plane diagram, we use "Management Gateway" and "Worker Gateway" labels. I'd like to align the term used in diagram with the explanation below it.
Suggestion:
* Use "Tyk Gateway" in diagram

2023-04-14 11:16 UTC, caroltyk commented
> > 1. In the first diagram, "Tyk Gateway" is used in both control plane and data plane. The explanation of 'Tyk Gateway" below is for data plane only. We can talk about the different roles the gateway has in control plane & data plane?
> 
> Yes, I think we could definitely improve that one-liner. 👍
> 
> > 2. In the Control Plane and Data Plane diagram, we use "Management Gateway" and "Worker Gateway" labels. I'd like to align the term used in diagram with the explanation below it.
> 
> Yes, agreed - that's what I was trying to say (but failed to get across succinctly) in my comment above.

lol, you were fast. I was trying to edit my comment as I saw your reply after I post it.

2023-04-14 14:46 UTC, andyo-tyk requested changes
A couple of corrections/rewording suggestions.

2023-04-14 14:46 UTC, andyo-tyk commented on tyk-docs/content/tyk-multi-data-centre/mdcb-components.md
> +- **Tyk MDCB** (used for propagation configurations to Data Plane gateways)
```suggestion
- **Tyk MDCB** (used for propagation of configurations - such as APIs and policies - to Data Plane gateways)
```

2023-04-14 14:46 UTC, andyo-tyk commented on tyk-docs/content/tyk-multi-data-centre/mdcb-components.md
> +- **Redis** (in-memery data store and message broker. High availability Redis data store that should be backed up in case of failure; this [document](https://redis.io/docs/management/persistence/) gi
```suggestion
- **Redis** (in-memory data store and message broker; a high availability Redis data store that should be backed up in case of failure; this [document](https://redis.io/docs/management/persistence/) gives recommendation on Redis persistency)
```

2023-04-14 14:46 UTC, andyo-tyk commented on tyk-docs/content/tyk-multi-data-centre/mdcb-components.md
> +- **MongoDB or SQL** (a persistent data store for configurations and analytics. It that should be deployed and set up for redundancy and high availability)
```suggestion
- **MongoDB or SQL** (a persistent data store for configurations and analytics; it should be deployed and set up for redundancy and high availability)
```

2023-04-17 09:53 UTC, caroltyk commented
Another question for discussion: 
Do we have different names for user of enterprise portal and end user of the API?

It is both called API consumers in the diagram but I wonder if we have better names to distinguish them.

2023-04-17 10:27 UTC, andyo-tyk commented
> Another question for discussion: Do we have different names for user of enterprise portal and end user of the API?
> 
> It is both called API consumers in the diagram but I wonder if we have better names to distinguish them.

Assuming we're talking about the end user of an API hosted on Tyk (rather than the Tyk REST API itself), then as far as I'm concerned these are the same persona. They are our customers' customers - they use the Dev Portal to find out about the APIs and get credentials to access them, then they use that information to make calls to the API endpoints on the Tyk Gateway (which proxies their calls to our customers' upstream services).

2023-09-07 15:52 UTC, letzya commented
@caroltyk is this ready for review (after our last discussion)?

2023-11-01 19:04 UTC, letzya commented
@caroltyk last comment was in April. I'm closing it but you can always open it and continue the work

2023-11-01 19:04 UTC, closed without merging