Update long-term-support-releases.md
TykTechnologies/tyk-docs-hugo pull request #2491
Opened 2023-04-18 22:56 UTC by caroltyk

## Related Issue (if applicable)

## Description
Update LTS information for Pump, MDCB, TIB, and Operator

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-04-19 19:05 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +To help assure backward compatibility we ensure that each version of Pump and other components we release works with the gateway and dashboard versions which is under long term support at that time.
```suggestion
To help assure backward compatibility we ensure that each version of Pump and other components we release works with the gateway and dashboard versions which are under LTS (long-term support) at that time. For example, we'd ensure Pump v1.7 is compatible with release v4 of Tyk gateway and Tyk Dashboard, and this increments with the LTS model.
```

2023-04-19 19:05 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +To help assure backward compatibility we ensure that each version of Pump and other components we release works with the gateway and dashboard versions which is under long term support at that time.
@caroltyk what do you think

2023-04-19 19:06 UTC, letzya requested changes
asked for changes

2023-04-19 22:57 UTC, caroltyk commented
> asked for changes

Updated

2023-04-21 11:49 UTC, letzya approved these changes

2023-04-21 11:49 UTC, merged

2023-04-21 11:49 UTC, letzya commented
/release to release-5