WIP: updated the instructions on how to utilize http tags
TykTechnologies/tyk-docs-hugo pull request #2500
Opened 2023-04-24 16:55 UTC by Monica-Cedeno

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-04-25 16:40 UTC, letzya requested changes
Please get a peer review. 
In the review be sure to check the preview to see the content including the existing one https://tyk.io/docs/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics/
Are you sure the content you add should come before the existing one?  seems it needs a bit more work

2023-04-25 16:41 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +With an API configured, click in to your newly created API and head to Advanced Options.
Advanced options where? gw? dashboard? we have oss users and users of REST apis. we need to write it with some context

2023-04-25 16:41 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +Navigate down to the Tag Headers section and pass in X-Request-Id to the Header Tag array.
```suggestion
Navigate down to the Tag Headers section and pass in `X-Request-Id` to the Header Tag array. 
```

2023-05-01 17:45 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +With an API configured, click in to your newly created API and head to Advanced Options.
I clarified that this is located in the dashboard and pushed that change

2023-05-01 17:45 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +Navigate down to the Tag Headers section and pass in X-Request-Id to the Header Tag array.
I added the `` and pushed the change. I also moved the preview to the top and the configuration explanation to the bottom.

2023-05-09 20:04 UTC, sedkis requested changes
Added a quick summary. besides that LGTM

2023-05-09 20:04 UTC, sedkis commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +This can be useful as you filter tags to gain additional information about how your API is being consumed.
```suggestion
This is useful if you wish to track aggregate API requests.  For example
- Show me all API requests where `tenant-id=123` 
- Show me all API requests where `user-id=abc`

And so-on.  We can now have Tyk track API requests which contain our business logic.
```

2023-05-09 20:04 UTC, sedkis approved these changes

2023-05-09 20:04 UTC, sedkis commented
@letzya  - can we merge this in pls?

2023-05-09 23:40 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +![Tag Headers](/docs/img/custom-analytics-tags/header-tags-1.png)
can you please change it to this format `{{< img src="/img/dashboard/system-management/jwt_default_policy.png" alt="Default JWT Policy" >}}` - it's using ourshortcodefor images. thanks

2023-05-09 23:49 UTC, letzya reviewed
once this is done, we can merge

2023-05-09 23:49 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +Configuration:
make it a header please

2023-05-10 17:19 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +![Tag Headers](/docs/img/custom-analytics-tags/header-tags-1.png)
made the changes

2023-05-10 17:19 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +Configuration:
done

2023-05-10 17:46 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< img src="/img/custom-analytics-tags/header-tags-1.png" alt="Tag Headers" >}}
why have we named the image header-tags-1.png and not header-tags.png

2023-05-10 17:46 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< img src="/img/custom-analytics-tags/postman-1" alt="Postman" >}}
can we name this image `postman-header-example`?

2023-05-10 17:46 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< img src="/img/custom-analytics-tags/headers-injected-as-tags-1.png" alt="Headers Injected" >}}
why have we added `1` to the image name?

2023-05-10 17:46 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< img src="/img/custom-analytics-tags/headers-injected-as-tags-1.png" alt="Headers Injected" >}}
Also is it possible to add better quality images?

2023-05-10 17:46 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +In Postman, pass in the header and provide a value for it and make some requests.
THis needs to be a bit more generic since people might not necessarily use postman (FYI @sedkis ).

For example - 
```
Using your preferred HTTP client, pass the X-Request-Id` header and then make some requests
```

2023-05-10 17:46 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< img src="/img/custom-analytics-tags/postman-1" alt="Postman" >}}
also, we need to screenshot the whole Postman window, as it looks out of context and not even Postman. I suggest using curl as an example, as we do in the rest of the docs `curl....-H "x-request-id: bla"`

2023-05-10 17:48 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< img src="/img/custom-analytics-tags/header-tags-1.png" alt="Tag Headers" >}}
Also - please move all the images under `assets/img` (static is used for other things)

2023-05-11 17:32 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< img src="/img/custom-analytics-tags/header-tags-1.png" alt="Tag Headers" >}}
renamed images and moved the folder to correct location

2023-05-11 17:33 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< img src="/img/custom-analytics-tags/postman-1" alt="Postman" >}}
changed image to reflect curl command rather than postman.

2023-05-11 17:33 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< img src="/img/custom-analytics-tags/headers-injected-as-tags-1.png" alt="Headers Injected" >}}
changed image names and added better quality images

2023-05-11 17:33 UTC, Monica-Cedeno commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +In Postman, pass in the header and provide a value for it and make some requests.
changed line 22 to be more generic

2023-05-11 18:07 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +![Tag Headers](/docs/img/custom-analytics-tags/header-tags-1.png)
i cant see the changes

2023-05-12 09:54 UTC, dcs3spp requested changes
Hi @Monica-Cedeno, I am Simon. I am new member of DX team as a technical writer. I have reviewed documentation and looks good to me. Liked the accompanying screenshots and detailed explanations of dashboard too.

I have suggested some minor changes, e.g. spelling and formatting.

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +`tag_headers` is a string array of HTTP headers which can be extracted and turned to tags.
```suggestion
`tag_headers` is a string array of HTTP headers that can be extracted and transformed into tags.
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +## Tags and Aggregated analytics
Updated Aggregated to lowercase for consistency across headings in the document.

```suggestion
## Tags and aggregated analytics
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +For example if you include `X-test-header` header in the `tag_headers` array, then, for each incoming request Tyk will add a `x-test-header-<header_value>` tag to the list of tags in the request anal
Maybe try to refactor into shorter sentences and backup with an example of the tag_headers array.

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +## When is it useful
```suggestion
## When is it useful?
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +
Add a prequel sentence to the use case bullet points in the next paragraph that I suggested in review

```suggestion
Example use cases are:

```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +If you need to record additional information from the request into the analytics, without enabling [detailed logging]({{<ref "tyk-oss-gateway/configuration#analytics_configenable_detailed_recording">
Maybe have each use case in a bullet point

```suggestion
- [Detailed logging]({{< ref "tyk-oss-gateway/configuration#analytics_configenable_detailed_recording">}}), records the full request and response objects. When enabled, detailed logging can make analytics information difficult to read and understand. Subsequently, custom analytics tags can be used to specify exactly what additional information is added from the request to accompany the analytics.
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +If you wish to track group of API requests.  For example
Make each use case a bullet point.

```suggestion
- If you wish to track a group of API requests. For example:

```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +Tag, by default, creates aggregations for the tags it records. Since we are making the header name that is recored part of the tag value, Tyk, will also add an aggregation point for that tag value in
Correct spelling mistake of recored (recorded) in this paragraph. 

Maybe explain briefly what is meant by aggregations before this paragraph.

`Tag, by default, creates aggregations for the tags it records`. Should this be a tag header by default creates aggregations for the tags it records?

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +### How to avoid creating aggregated analytics
```suggestion
### How to specify which tags are ignored for aggregated analytics?
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +If you don't want to have aggregation for these tags you can add them or their prefixes to `ignore_tag_prefix_list` in `pump.conf` in case the pump is writing the aggregated analytics to MongoDB. Alt
Consider adding an introduction sentence that explains that it is possible to specify which tags are ignored when writing to MongoDB. Something, like that suggested below. 

Maybe also add links to Tyk Pump and MDCB configuration docs that contain this configuration option for how to ignore tags.

```suggestion
It is possible to configure a list of tags that are ignored when writing aggregated analytics to MongoDB. This can be configured for Tyk Pump and MDCB.

- **Tyk Pump**: Add tags or their prefixes to `ignore_tag_prefix_list` in `pump.conf`.
- **MDCB**: Add tags or their prefixes to `ignore_tag_prefix_list` in `tyk_sink.conf` at root level. (Please note that this field is replacing `aggregates_ignore_tags` which is still working but will eventually be deprecated).
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +## Guide to set up and test tag headers in the dashboard
Consider using consistent headings for how to explanations, e.g. the previous section used the phrase how to

```suggestion
## How to set up and test tag headers in the dashboard?
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +## Guide to set up and test tag headers in the dashboard
Consider using consistent headings for how to explanations, e.g. the previous section used the phrase how to

```suggestion
## How to set up and test tag headers in the dashboard?
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +1. In the Dashboard, with an API configured, open your API and head to "Advanced Options".
Like this section with step by step explanation and accompanying screenshots. 

```suggestion
1. In the Dashboard, with an API configured, open your API and click on "Advanced Options".
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +3. Test: Using your preferred HTTP client, pass the `X-Team-Name` header and make a request to test out your work. For example, with curl run the following
```suggestion
3. Test: Using your preferred HTTP client, make a request that includes the `X-Team-Name` header. For example, with curl run the following:
```

2023-05-12 09:54 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +4. Check: Navigate back to the Dashboard and select the "Log Browser" to view the logged requests. Open the request record and in the "Gateway Metadata" section (on theright), you can find the "Tags"
```suggestion
4. Check: Navigate back to the Dashboard and select the "Log Browser" option to view the logged requests. Open the request record and in the "Gateway Metadata" section (on the right), you can find the "Tags" attached to our request. There you should see the header and value you sent in the request. You should also see that Tyk Gateway recorded it as a `tag`.
```

2023-05-12 11:26 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +Tag, by default, creates aggregations for the tags it records. Since we are making the header name that is recored part of the tag value, Tyk, will also add an aggregation point for that tag value in
no it's a tag. we create a "tag" from the values in "tah_header" array. There are tags created in a different way, for example - org id, API id, key hash (check the tags section in the image tyk-docs/assets/img/custom-analytics-tags/log-browser.png)

2023-05-12 11:39 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +For example if you include `X-test-header` header in the `tag_headers` array, then, for each incoming request Tyk will add a `x-test-header-<header_value>` tag to the list of tags in the request anal
this page has an example https://tyk.io/docs/tyk-apis/tyk-gateway-api/api-definition-objects/other-root-objects/

2023-05-12 11:41 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +If you need to record additional information from the request into the analytics, without enabling [detailed logging]({{<ref "tyk-oss-gateway/configuration#analytics_configenable_detailed_recording">
"When enabled, detailed logging can make analytics information difficult to read and understand. Subsequently," - this is not the case - the only issue is the space consumption

2023-05-12 11:45 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +If you need to record additional information from the request into the analytics, without enabling [detailed logging]({{<ref "tyk-oss-gateway/configuration#analytics_configenable_detailed_recording">
https://tyk.io/docs/tyk-multi-data-centre/mdcb-configuration-options/#ignore_tag_prefix_list

2023-05-12 11:45 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +If you don't want to have aggregation for these tags you can add them or their prefixes to `ignore_tag_prefix_list` in `pump.conf` in case the pump is writing the aggregated analytics to MongoDB. Alt
https://tyk.io/docs/tyk-multi-data-centre/mdcb-configuration-options/#ignore_tag_prefix_list

2023-05-12 11:48 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +For example if you include `X-test-header` header in the `tag_headers` array, then, for each incoming request Tyk will add a `x-test-header-<header_value>` tag to the list of tags in the request anal
pumps it's per pump - https://tyk.io/docs/tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables/#pumpssqlaggregatemetaignore_tag_prefix_list

2023-05-12 11:55 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +Example use cases are:
@dcs3spp This fits the content in lines 24-25, not here

2023-05-12 11:56 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +If you need to record additional information from the request into the analytics, without enabling [detailed logging]({{<ref "tyk-oss-gateway/configuration#analytics_configenable_detailed_recording">
the way it's written put emphasise on detailed logging and not on `If you need to record additional information from the request into the analytics,`

2023-05-15 12:34 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +`tag_headers` is a string array of HTTP headers that can be extracted and transformed into tags.
```suggestion
`tag_headers` is a string array of HTTP headers that can be extracted and transformed into [analytic tags]({{< ref "tyk-dashboard-analytics" >}})(statistics aggregated by tag, per hour).
```

2023-05-15 12:34 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +- If you need to record additional information from the request into the analytics, without enabling [detailed logging]({{<ref "tyk-oss-gateway/configuration#analytics_configenable_detailed_recording
```suggestion
- You need to record additional information from the request into the analytics. When enabling [detailed logging]({{<ref "tyk-oss-gateway/configuration#analytics_configenable_detailed_recording">}}). Tyk Gateway records the full request and response objects which consumes a lot of space. Using this config will save you this space and only record this header
```

2023-05-15 12:34 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +- If you wish to track a group of API requests. For example:
```suggestion
- You wish to track a group of API requests. For example:
```

2023-05-15 12:34 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +Tyk Gateway, by default, creates aggregations for the tags it records. Since we are making the header name that is recorded part of the tag value, Tyk, will also add an aggregation point for that tag
```suggestion
Tyk Gateway, by default, creates aggregations points for all the tags it records. Since we are making the header name that is recorded part of the tag value, Tyk, will also add an aggregation point for that tag value in the aggregated analytics, i.e. `x-test-header-<header_value>`.
```

2023-05-15 12:34 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +### How to specify which tags are ignored for aggregated analytics?
```suggestion
### How to avoid the creation of aggregation analytics?
```

2023-05-15 12:34 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +If you add to the tags list headers that are **unique** per request, like timestamp or [X-Request-Id]({{<ref "context-variables#the-available-context-variables-are" >}}), then Tyk Gateway will essent
what is this "\*_per request_"

2023-05-15 12:34 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +{{< warning success >}}
I think the warning should come after the explanation how to set the config fields in the pump and mdcb

2023-05-15 12:34 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +  If you don't want to have aggregation for these tags you can add them or their prefixes to `ignore_tag_prefix_list` in `pump.conf` in case the pump is writing the aggregated analytics to MongoDB. A
This text doesn't appear well in the preview

2023-05-16 11:36 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +  If you don't want to have aggregation for these tags you can add them or their prefixes to `ignore_tag_prefix_list` in `pump.conf` in case the pump is writing the aggregated analytics to MongoDB. A
@letzya do you want me to remove the backticks?

2023-05-17 08:27 UTC, dcs3spp submitted a review, later dismissed
LGTM, minor capitalisation suggestion then ready to merge

2023-05-17 08:27 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
> +This is done while writing the recorded *aggregated analytics* to the data stores. configure a list of tags that are ignored when writing *aggregated analytics* to MongoDB. This can be configured for
```suggestion
This is done while writing the recorded *aggregated analytics* to the data stores. Configure a list of tags that are ignored when writing *aggregated analytics* to MongoDB. This can be configured for Tyk Pump and MDCB.
```

2023-05-17 08:37 UTC, letzya approved these changes

2023-05-17 08:50 UTC, merged

2023-05-17 09:03 UTC, dcs3spp commented
/release to release-5