Update Redis & Database support info
TykTechnologies/tyk-docs-hugo pull request #2502
Opened 2023-04-24 23:36 UTC by caroltyk

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-04-25 16:47 UTC, letzya requested changes
Peer review please.
Also CI is red

2023-04-25 16:48 UTC, letzya commented on tyk-docs/content/tyk-on-premises.md
> +Tyk Gateway requires Redis for its operations. See [Redis]({{< ref "/planning-for-production/redis/#supported-versions">}}) for list of versions we support.
```suggestion
Tyk Gateway requires Redis for its operations. See [Redis]({{< ref "planning-for-production/redis#supported-versions">}}) for list of versions we support.
```

2023-04-27 12:11 UTC, letzya commented on tyk-docs/content/planning-for-production/database-settings/postgresql.md
> +From Tyk v4.0.0, Tyk supports the latest minor of following PostgreSQL versions:
Can we change the title to "Supported Versions" like we have in mongo?

2023-04-27 12:16 UTC, letzya commented on tyk-docs/content/tyk-dashboard/database-options.md
> +* Amazon DocumentDB
can we please have links to these mongos?

2023-04-27 12:16 UTC, letzya commented on tyk-docs/content/tyk-dashboard/database-options.md
> +* MongoDB 4.4.x
can we add direct link it to the "Supported Versions" of mongo instead of writing this version in 2 places? makes it harder to update the docs when we change the supported version.

2023-04-27 12:16 UTC, letzya commented on tyk-docs/content/tyk-dashboard/database-options.md
> +* PostgreSQL version 11.x, 12.x, 13.x, 14.x, 15.x
same here - add a direct link to the page of the supported versions "tyk-docs/content/planning-for-production/database-settings/postgresql.md"

2023-04-27 12:16 UTC, letzya commented on tyk-docs/content/tyk-on-premises.md
> +Tyk Dashboard reuqires a persistent datastore for its operations. By default MongoDB is used. From Tyk v4.0, we also support PostgreSQL. See [Database Options]({{< ref "/content/tyk-dashboard/databas
```suggestion
Tyk Dashboard reuqires a persistent datastore for its operations. By default MongoDB is used. From Tyk v4.0, we also support PostgreSQL. See [Database Options]({{< ref "tyk-dashboard/database-options.md" >}}) for a list of versions and drop-in replacements we support.
```

2023-04-27 12:16 UTC, letzya commented on tyk-docs/content/tyk-on-premises.md
> +Tyk Gateway requires Redis for its operations. See [Redis]({{< ref "planning-for-production/redis#supported-versions">}}) for list of versions we support.
```suggestion
Tyk Gateway requires Redis for its operations. See [supported Redis versions]({{< ref "planning-for-production/redis#supported-versions">}}) for the list of releases.
```

2023-04-27 22:06 UTC, caroltyk commented on tyk-docs/content/planning-for-production/database-settings/postgresql.md
> +From Tyk v4.0.0, Tyk supports the latest minor of following PostgreSQL versions:
Updated

2023-04-28 06:21 UTC, letzya commented on tyk-docs/content/planning-for-production/database-settings.md
> +See [Database options]({{< ref "/content/tyk-dashboard/database-options.md" >}}) for our supported database platforms.
```suggestion
See [Database options]({{< ref "tyk-dashboard/database-options.md" >}}) for our supported database platforms.
```

2023-04-28 06:21 UTC, letzya commented on tyk-docs/content/planning-for-production/database-settings.md
> +* [Redis]({{< ref "/content/planning-for-production/redis.md" >}})
```suggestion
* [Redis]({{< ref "planning-for-production/redis.md" >}})
```

2023-04-28 06:21 UTC, letzya commented on tyk-docs/content/planning-for-production/database-settings.md
> +* [MongoDB]({{< ref "/content/planning-for-production/database-settings/mongodb.md" >}})
```suggestion
* [MongoDB]({{< ref "planning-for-production/database-settings/mongodb.md" >}})
```

2023-04-28 06:21 UTC, letzya commented on tyk-docs/content/planning-for-production/database-settings.md
> +* [PostgreSQL]({{< ref "/content/planning-for-production/database-settings/postgresql.md" >}})
```suggestion
* [PostgreSQL]({{< ref "planning-for-production/database-settings/postgresql.md" >}})
```

2023-04-28 06:21 UTC, letzya commented on tyk-docs/content/tyk-dashboard/database-options.md
> +MongoDB is our default storage option. Please check [here]({{< ref "/content/planning-for-production/database-settings/mongodb.md" >}}) for the supported versions.
```suggestion
MongoDB is our default storage option. Please check [here]({{< ref "planning-for-production/database-settings/mongodb.md" >}}) for the supported versions.
```

2023-04-28 06:21 UTC, letzya commented on tyk-docs/content/tyk-dashboard/database-options.md
> +From Tyk 4.0, you can use PostgreSQL as your datastore. Please check [here]({{< ref "/content/planning-for-production/database-settings/postgresql.md" >}}) for the supported versions.
```suggestion
From Tyk 4.0, you can use PostgreSQL as your datastore. Please check [here]({{< ref "planning-for-production/database-settings/postgresql.md" >}}) for the supported versions.
```

2023-04-28 06:21 UTC, letzya commented on tyk-docs/content/tyk-on-premises.md
> +* Special notes for AtlasDB:
link

2023-04-28 06:22 UTC, letzya commented on tyk-docs/content/planning-for-production/redis.md
> +- Redis 6.0.x and 6.2.x
can we please get a reviewer to approve this

2023-04-28 08:48 UTC, caroltyk commented on tyk-docs/content/planning-for-production/redis.md
> +- Redis 6.0.x and 6.2.x
@buger @ilijabojanovic could you approve this?

2023-04-28 09:59 UTC, caroltyk commented
@letzya To avoid cyclic link and too many clicks for users, I've updated the pages with
- Version & support information mainly on "Database Options" page
- Configuration information mainly on respective MongoDB / PostgreSQL page

2023-04-28 13:01 UTC, letzya commented on tyk-docs/content/planning-for-production/database-settings.md
> +See [Database options]({{< ref "/content/tyk-dashboard/database-options.md" >}}) for our supported database platforms.
@caroltyk  we don't need `/content/` in the beginning

2023-04-28 13:08 UTC, letzya commented on tyk-docs/content/planning-for-production/database-settings.md
> +See [Database options]({{< ref "/content/tyk-dashboard/database-options.md" >}}) for our supported database platforms.
```suggestion
See [Database options]({{< ref "tyk-dashboard/database-options.md" >}}) for our supported database platforms.
```

2023-04-28 13:08 UTC, letzya commented on tyk-docs/content/planning-for-production/database-settings.md
> +See [Database options]({{< ref "/content/tyk-dashboard/database-options.md" >}}) for our supported database platforms.
Also, this line seems unnecessary. Isn't the next line enough?

2023-04-28 16:33 UTC, caroltyk commented on tyk-docs/content/planning-for-production/database-settings.md
> +See [Database options]({{< ref "/content/tyk-dashboard/database-options.md" >}}) for our supported database platforms.
Thanks 🙈

2023-05-12 13:11 UTC, rewsmith requested changes

2023-05-12 13:11 UTC, rewsmith commented on tyk-docs/content/tyk-dashboard/database-options.md
> +Note: Tyk works with MongoDB 3.x and above too, but we no longer test with MongoDB version older than 4.4 because it has been EOL
Suggest changing to read: Tyk works with MongoDB 3.x and above too, but we no longer test MongoDB versions prior to 4.4 since they are EOL

2023-05-12 13:11 UTC, rewsmith commented on tyk-docs/content/planning-for-production/redis.md
> +- Redis 6.0.x and 6.2.x
Just to confirm this is 6.0.x **and** 6.2.x, or should it be 6.0.x **to** 6.2.x?

2023-05-12 13:11 UTC, rewsmith commented on tyk-docs/content/tyk-on-premises.md
> +Tyk Dashboard reuqires a persistent datastore for its operations. By default MongoDB is used. From Tyk v4.0, we also support PostgreSQL. See [Database Options]({{< ref "tyk-dashboard/database-options
typo: reuqires

2023-05-12 13:22 UTC, caroltyk commented on tyk-docs/content/planning-for-production/redis.md
> +- Redis 6.0.x and 6.2.x
Since there's no 6.1, both would be the same

2023-05-12 13:49 UTC, rewsmith approved these changes
LGTM

2023-05-15 11:17 UTC, letzya approved these changes
Hass been approved by Andt S

2023-05-15 11:17 UTC, merged

2023-05-15 11:17 UTC, letzya commented
/release to release-5