[TT-8366] Update installation docs for the enterprise portal
TykTechnologies/tyk-docs-hugo pull request #2508
Opened 2023-04-27 17:08 UTC by slega

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-04-28 09:19 UTC, rewsmith requested changes

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +title: "Install Tyk Developer Enterprise Portal"
For consistency this title should read "Install Tyk Enterprise Developer Portal"

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +If you are interested in getting access contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Developer Enterprise Portal Beta>)
Change to "Tyk Enterprise Developer Portal Beta"

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +We deliver the Tyk Enterprise Developer Portal as a Docker container. To  install Tyk Enterprise Developer Portal, you need to launch the Docker image for the portal with a database to store the port
Grammar correction: "with a database to store the portal metadata. Optionally, you may decide to use S3 to store the portal CMS assets (image and theme files)

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +This guide explains how to install and bootstrap the Tyk Enterprise Developer Portal. On average, it should take around 5-10 minutes to intall it depending on your setup.
Fix Typo ("intall"): it should take around 5-10 minutes to install it depending on your setup

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +1. **[Launch the portal application in the bootstrap mode.]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-porta
Suggest changing the link title to "the Launching section" and also confirm the link is correct (I get a 404 in Preview mode) [the Installation section]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal.md" >}}

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +2. **[Bootstrap the portal.]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md" >}})** After you've launched the porta
This sentence is duplicated from the previous paragraph: "After you've launched the portal, it will wait for you to provide credentials for the admin user before it starts accepting traffic."

Be consistent, is it "admin user" or "super admin user"

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> -### With MySQL
Readers may associate the term "chart" with Helm, so better to use "diagram"

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-deployment-chart.png
Typo on Tyk Identity Broker: should say single sign-on, not sing-on

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +- **Email server**. The portal is capable of sending notifications to both admin users and developers when specific events happen within the portal. To enable this feature, you need to specify a conn
Grammar (add comma): To enable this feature, you need to specify a connection configuration to an email server or service, and configure other email settings

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +title: "Configure Tyk Developer Enterprise Portal"
Title should read "Configure Tyk Enterprise Developer Portal"

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +To configure the Tyk Enterprise Developer Portal, you can use either a config file or environment variables. The below table provides reference to all options availbe to you when configuring the port
correct typo "options availbe" to "options available"

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md
> +title: "Bootstrap Tyk Developer Enterprise Portal"
Tyk Enterprise Developer Portal

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md
> +## Bootstrapping the portal via the UI
Title incorrect, should be "Bootstrapping the portal via the API"

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md
> +This guide explains how to bootstrap the portal using both the portal UI and the bootstrap API.
Isn't it also possible to bootstrap using config/env vars? e.g. ADMIN_EMAIL and ADMIN_PASSWORD

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md
> +Note the `api_token` field. You can leverage it to other portal's API.
This could be clear.  I suggest changing this to a "success note" and amend to read "Take a note of the `api_token` field as you will need this to call other Portal APIs.

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md
> +On the login page, enter the super admin credentials for logging to the portal:
change to "logging into"

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md
> +Congratulations! Now you have fully functional portal.
Correct grammar "Now you have a fully functional portal."

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal.md
> +title: "Launching the Tyk Developer Enterprise Portal"
Tyk Enterprise Developer Portal

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +title: "Launch Tyk Developer Enterprise Portal with SQLite"
Tyk Enterprise Developer Portal

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +## Installing the Tyk Developer Enterprise Portal with SQLite
Tyk Enterprise Developer Portal

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer to the Configuration section in the Tyk Enterprise Developer Portal documentation
Suggest moving the Configuration section link to "please refer to the **Configuration section** in the ..."

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +This section outlines the process of launching the portal application with SQLite using a Docker container. By following this guide, you will learn how to effectively configure, launch, and dismantle
Not sure dismantle it the right term here (although I'm tempted to leave it). Maybe "shutdown" instead

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +If you want to clean up your environment or start the installation process from scratch, execute the following commands to stop and dismantle the portal container:
change "dismantle" to "remove"

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +This section outlines the process of launching the portal application with SQLite using docker-compose. By following this guide, you will learn how to effectively configure, launch, and dismantle the
Change dismantle

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +If you want to clean up your environment or start the installation process from scratch, execute the following commands to stop and dismantle the portal container:
Change dismantle as previous

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-mysql.md
> +title: "Launch Tyk Developer Enterprise Portal with MySQL"
Tyk Enterprise Developer Portal

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-mysql.md
> +## Installing the Tyk Developer Enterprise Portal with MySQL
Tyk Enterprise Developer Portal

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-mysql.md
> +This section outlines the process of launching the portal application with MySQL using a Docker container. By following this guide, you will learn how to effectively configure, launch, and dismantle
Change dismantle

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-mysql.md
> +If you want to clean up your environment or start the installation process from scratch, execute the following commands to stop and dismantle the portal container:
Change dismantle

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-mysql.md
> +This section outlines the process of launching the portal application with MySQL using docker-compose. By following this guide, you will learn how to effectively configure, launch, and dismantle the
Change dismantle

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-mysql.md
> +If you want to clean up your environment or start the installation process from scratch, execute the following commands to stop and dismantle the portal container:
Change dismantle

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +title: "Launch Tyk Developer Enterprise Portal with PostgreSQL"
Tyk Enterprise Developer Portal

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +## Installing the Tyk Developer Enterprise Portal with PostgreSQL
Tyk Enterprise Developer Portal

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +#### Create an init script for PostgreSQL
Looks like we missed a section, or this heading doesn't belong here at all

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +The next step is to launch the MySQL database for the portal. To achieve this, please follow these steps and execute the commands below:
Postgres not MySQL

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +```shell
Amend these commands for postgres

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +>**Note**: The above MySQL configuration is an example. You can customize deployment of your MySQL instance. Please refer to [the MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/charset-
Postgres not MySQL

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +```ini
Change to Postgres env vars

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +### Launch the portal with MySQL using Docker container
Postgres

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +If you want to clean up your environment or start the installation process from scratch, execute the following commands to stop and dismantle the portal container:
Change dismantle

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +### Launch the portal with MySQL using docker-compose
Update for postgres

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
> +If you want to clean up your environment or start the installation process from scratch, execute the following commands to stop and dismantle the portal container:
Change dismantle

2023-04-28 09:19 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-using-helm.md
> +title: "Launch Tyk Developer Enterprise Portal with helm chart"
Tyk Enterprise Developer Portal

2023-04-28 09:51 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +1. **[Launch the portal application in the bootstrap mode.]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-porta
Strangely it works fine on my local but gives 404 in the preview mode. I will follow up with the DX team on this

2023-04-28 09:54 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md
> +This guide explains how to bootstrap the portal using both the portal UI and the bootstrap API.
Nope, but we can treat that as a feature request

2023-04-28 10:44 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +This section outlines the process of launching the portal application with SQLite using a Docker container. By following this guide, you will learn how to effectively configure, launch, and dismantle
Yeah, 'stop and clean up' would work better

2023-04-28 13:09 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +1. **[Launch the portal application in the bootstrap mode.]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-porta
The link is not broken - it just leads to tyk.io. So it will be fine when we will release this to production.

2023-04-28 13:30 UTC, rewsmith approved these changes
LGTM

2023-04-28 15:25 UTC, letzya commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
> +If you are deploying the **Tyk Enterprise Developer Portal**, set the appropriate values under the `enterprisePortal` section in your `values.yaml`. Please visit [Tyk Enterprise Developer Portal inst
```suggestion
If you are deploying the **Tyk Enterprise Developer Portal**, set the appropriate values under the `enterprisePortal` section in your `values.yaml`. Please visit [Tyk Enterprise Developer Portal installation]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-using-helm#launch-the-tyk-enterprise-developer-portal-using-helm" >}}) for a step by step guide.
```

2023-04-28 15:25 UTC, letzya commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
> +If you are deploying the **Tyk Enterprise Developer Portal**, set the appropriate values under the `enterprisePortal` section in your `values.yaml`. Please visit [Tyk Enterprise Developer Portal inst
@slega i added the anchor back - please let me know if that ok with you? the link was broken since it had `.md`

2023-04-28 15:26 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md
> +This guide explains how to bootstrap the portal using both the portal UI and the bootstrap API.
FYI - we generate docs for the config and end vars docs

2023-04-28 15:27 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/bootstrapping-portal.md
> +You can continue configuring and customizing it either via the UI or the portal admin API. Please refer to [the Tyk Enterprise Developer Portal Concepts section]({{< ref "/content/tyk-stack/tyk-devel
```suggestion
You can continue configuring and customizing it either via the UI or the portal admin API. Please refer to [the Tyk Enterprise Developer Portal Concepts section]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/enterprise-portal-concepts.md" >}}) for further guidance.
```

2023-04-28 15:51 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +#### PORTAL_HOSTPORT
1. what about the env vars in this table - https://tyk.io/docs/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/#environment-variables-and-env-file
2. We have a certain way of doing this in tyk docs and for env vars - check https://tyk.io/docs/tyk-dashboard/configuration/  or https://tyk.io/docs/tyk-oss-gateway/configuration/ - i think these env vars belong in sach page. The best is to create a similar page to the gateway and dashboard with a similar title and later automate it like they do (also tib, pump and mdcb have that automation)

2023-04-28 15:51 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-using-helm.md
> +```
```suggestion
```bash
```

2023-04-28 15:51 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +If you intend to deploy the portal with the `fs` [type of storage]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md#portal_s
```suggestion
If you intend to deploy the portal with the `fs` [type of storage]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal_storage" >}}), it will be necessary to create three distinct volumes.
```

2023-04-28 15:51 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
> +If you intend to deploy the portal with the `fs` [type of storage]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md#portal_s
@slega 
1. no need for `/content/`
2. remove `.md` if you have anchor (in general there's no need for it)

2023-04-28 15:51 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md
> +To specify the portal SSO API secret, add the `PORTAL_API_SECRET` variable to [the portal .env file]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterpris
```suggestion
To specify the portal SSO API secret, add the `PORTAL_API_SECRET` variable to [the portal .env file]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#env-file" >}}):
```

2023-04-28 15:51 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md
> +To specify the portal SSO API secret, add the `PORTAL_API_SECRET` variable to [the portal .env file]({{< ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterpris
i added back the anchor. now it should work

2023-05-02 16:11 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +#### PORTAL_HOSTPORT
@letzya we don't have this automation at the moment - we can create it in the later releases. Also, I've selected this layout because for the portal we use EVs as a the generic way of configuring the portal. Also, the descriptions here https://tyk.io/docs/tyk-oss-gateway/configuration/ miss the options field where you can enumerate possible options.
Can we please keep this for now? I'll include the config page autogeneration to one of the next releases, then we can update the format to make it look like the other config options.

As, for the title, it forms a JTBD sequence -`Configure Tyk Enterprise Developer Portal` -> `Launch the Tyk Enterprise Developer Portal` -> `Bootstrap Tyk Enterprise Developer Portal` . I would like to keep.

Regarding the https://tyk.io/docs/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/#environment-variables-and-env-file : we dropped 4 of the variables from the first version of the portal. But since that version of the portal is used by a single customer, it's safe to drop them. These variables are only for bootstrapping the portal at the first launch. We introduced a new way of doing this in the `Bootstrap Tyk Enterprise Developer Portal` section.

2023-05-02 19:22 UTC, letzya commented
merging per @rewsmith approval

2023-05-02 19:22 UTC, merged

2023-05-02 19:23 UTC, letzya commented
/release to release-5

2023-05-02 19:59 UTC, letzya commented
/release to release-5

2023-05-03 06:29 UTC, buger commented
/release to release-5