Add global size limit for all apis
TykTechnologies/tyk-docs-hugo pull request #2544
Opened 2023-05-15 10:38 UTC by titpetric

## Related Issue (if applicable)

https://tyktech.atlassian.net/browse/TT-5186

## Description

Changes to document global added `max_request_body_size` option.

Docs for 5.1.

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [x] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [x] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-05-15 11:33 UTC, jeffy-mathew approved these changes

2023-05-15 13:25 UTC, dcs3spp requested changes, later dismissed
looks good to me

2023-05-15 13:25 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk supports forcing request size limits at the global, per-API and individual endpoint level.
```suggestion
Tyk supports forcing request size limits per API at the global and individual endpoint level.
```

2023-05-15 13:25 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +To add an per-API size limit, simply add:
```suggestion
To add a per API size limit, simply add:
```

2023-05-16 12:12 UTC, andyo-tyk requested changes
Trying to improve clarity on this page.

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk supports forcing request size limits per API at the global and individual endpoint level.
```suggestion
With Tyk, you are able to apply limits to the size of requests to your APIs; you might do this to protect your upstream services or even the gateway itself, for example, to avoid excessive memory usage or brute force attacks.

Tyk offers a flexible system of limiting request sizes ranging from globally applied limits across all APIs deployed on the gateway down to specific size limits for individual API endpoints.

All size limits are applied only to the request body and are stated in bytes.
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk will reject any request that exceeds the size you set.
```suggestion
Tyk compares each incoming API request with the configured rate limit(s) and will reject any request that exceeds the size you have set, returning an HTTP 400 error with the message "Request is too large".
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +### Global size limiting per API
```suggestion
### Applying a size limit for a specific API
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +To add a per API size limit, simply add:
```suggestion
You can optionally configure a request size limit (in bytes) to an API by adding `global_size_limit` to the `version` element of the API Definition, for example:
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +The setting must be added to the version element of your API Definition.
```suggestion
Remember that this is stated in bytes and is a limit for the size of the request body, excluding the headers.
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +The configuration of the global size limit value will be evaluated before
```suggestion
This size limit is applied (globally) for all endpoints _within an API_ and should not be confused with  `max_request_body_size` which is applied (globally) for all APIs deployed in the Organisation.
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +the specific path-based one.
```suggestion
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +### Global size limiting for all APIs
```suggestion
### Applying a size limit for all APIs in your Organisation
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +To add a global request body size limit, simply add:
```suggestion
You can optionally configure a request size limit (in bytes) that will be applied to all APIs on your Tyk Gateway by adding `max_request_body_size` to the [`http_server_options`]({{< ref "/tyk-oss-gateway/configuration#http_server_options" >}}) element of your `tyk.conf` Gateway configuration, for example:
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +The setting must be added to the
```suggestion
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +[http_server_options](https://tyk.io/docs/tyk-oss-gateway/configuration/#http_server_options)
```suggestion
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +element of tyk.conf. The configuration of this value will be evaluated
```suggestion
```

2023-05-16 12:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +before per-API or per-endpoint settings.
```suggestion
This Gateway-wide size limit will be evaluated before per-API or per-endpoint settings.
```

2023-05-19 10:05 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk will reject any request that exceeds the size you set.
Clearly that should say "compares the size of the body of each incoming API request with the configured maximum size(s)" (rather than "reate limit(s))

2023-05-30 10:46 UTC, andyo-tyk commented
This has been superceded by https://github.com/TykTechnologies/tyk-docs/pull/2601

2023-05-30 10:46 UTC, closed without merging