Update error-templates.md
TykTechnologies/tyk-docs-hugo pull request #2546
Opened 2023-05-15 13:15 UTC by andyo-tyk

Added note that it's not possible to use a template for HTTP 404

## Related Issue (if applicable)
https://github.com/TykTechnologies/tyk/issues/3566

## Description
Override messages for HTTP 404 are not supported

2023-05-15 13:16 UTC, lghiur approved these changes

2023-05-16 08:21 UTC, dcs3spp requested changes

2023-05-16 08:21 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/error-templates.md
> +Please note that it is not possible to override the default message for HTTP 404 errors, which indicate that the requested resource was not available (e.g. the requested URL does not exist).
@andyo-tyk  LGTM. Maybe consider the following suggestion:

```suggestion
Please note that it is not possible to override the default message for HTTP 404 errors. These errors indicate that the requested resource could not be found (e.g. the requested URL does not exist).
```

2023-05-17 09:16 UTC, dcs3spp approved these changes
lgtm

2023-05-17 09:19 UTC, dcs3spp commented
/release to release-5

2023-05-17 09:19 UTC, merged

2023-05-17 09:20 UTC, dcs3spp commented
/release to release-5