Add keycloak example setup
TykTechnologies/tyk-docs-hugo pull request #2548
Opened 2023-05-15 18:20 UTC by zalbiraw

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-05-15 19:53 UTC, Firaasss commented
Nice and easy to use w/ the instructions, can you please add a variable "REALM_NAME" in the path for the curl request to retrieve token ? /realms/**jwt**/protocol was tailored to your keycloak environment

2023-05-15 19:53 UTC, firaaasss commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +    curl -L --insecure -s -X POST 'https://KEYCLOAK_URL/realms/jwt/protocol/openid-connect/token' \
https://KEYCLOAK_URL/realms/REALM_ID/protocol/openid-connect/token

2023-05-15 19:54 UTC, Firaasss commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +    curl -L --insecure -s -X POST 'https://localhost:7001/realms/jwt/protocol/openid-connect/token' \
https://KEYCLOAK_URL/realms/REALM_ID/protocol/openid-connect/token

2023-05-15 20:07 UTC, zalbiraw commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +    curl -L --insecure -s -X POST 'https://KEYCLOAK_URL/realms/jwt/protocol/openid-connect/token' \
```suggestion
    curl -L --insecure -s -X POST 'https://KEYCLOAK_URL/realms/KEYCLOAK_REALM/protocol/openid-connect/token' \
```

2023-05-15 20:07 UTC, zalbiraw commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +    curl -L --insecure -s -X POST 'https://localhost:7001/realms/jwt/protocol/openid-connect/token' \
```suggestion
    curl -L --insecure -s -X POST 'https://KEYCLOAK_URL/realms/KEYCLOAK_REALM/protocol/openid-connect/token' \
```

2023-05-16 11:19 UTC, dcs3spp requested changes
LGTM @zalbriaw. Good clear explanations! I have made some minor suggestions in the review.

Maybe try and make the data entry screenshots slightly larger so that text labels are easier to read.

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +This will walk you through securing your APIs with JWTs via Keycloak.
```suggestion
This guide will walk you through securing your APIs with JWTs via Keycloak.
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +## Create an application in Keycloack
```suggestion
## Create an application in Keycloak
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +* An installment of [Keycloak](https://www.keycloak.org/)
```suggestion
 A [Keycloak](https://www.keycloak.org/) installation
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +   - Enable client authentication and Service account roles under Authentication flow
```suggestion
   - Enable client authentication and Service account roles under Authentication flow
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +{{< img src="/img/keycloak-jwt/create-client-step-3.png" alt="Add redirect URL rules" width="800px" height="400" >}}
```suggestion
{{< img src="/img/keycloak-jwt/create-client-step-3.png" alt="Add redirection URL rules" width="800px" height="400" >}}
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +{{< img src="/img/keycloak-jwt/create-api-step-1.png" alt="Create API" width="800px" height="400" >}}
```suggestion
{{< img src="/img/keycloak-jwt/create-api-step-1.png" alt="Create a new HTTP API" width="800px" height="400" >}}
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +   - Add your JSON Web Key Sets (JWKS) URL in the `Public Key` box. Which can be found through the well-known config endpoint or is typically `https://KEYCLOAK_URL/realms/KEYCLOAK_REALM/protocol/open
```suggestion
   - Add your JSON Web Key Sets (JWKS) URL in the `Public Key` box. This can be found through the well-known config endpoint or is typically `https://KEYCLOAK_URL/realms/KEYCLOAK_REALM/protocol/openid-connect/certs`.
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +4. Add default to API
```suggestion
4. Add default policy to API
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +{{< img src="/img/keycloak-jwt/create-api-step-4.png" alt="Add default Policy to API" width="800px" height="400" >}}
```suggestion
{{< img src="/img/keycloak-jwt/create-api-step-4.png" alt="Add default policy to API" width="800px" height="400" >}}
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +   - Test with curl
The url in the curl request example does not match the url in the API image. Maybe consider adding an explanation that the API URL (displayed in the image screenshot) has been added to `/etc/hosts`

Mention to the reader that they will need to replace _TOKEN_ with the `access_token` that they created earlier.

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +6. Generate your JWTs using curl and store them. These are keys you will use to access your services through the Tyk Gateway.
Maybe sentence here instructing the reader to replace _KEYCLOAK_URL_, _KEYCLOAK_REALM_ etc. with their values

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +   - Save API
```suggestion
   - Click on the update button to save API
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +
Add an explanation on how to get to the screen to enter details for JWT Authentication mode, JWT signing method and JWKS.

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +3. Create a policy to manage access to your API.
Add a brief introduction sentence of how to access this screen.

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +4. Add default to API
```suggestion
4. Add default policy to API
```

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +{{< img src="/img/keycloak-jwt/create-api-step-4.png" alt="Add default Policy to API" width="800px" height="400" >}}
In the screenshot maybe show the default policy being displayed in the drop down, as if it is about to be selected

2023-05-16 11:19 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +description: "How to secure your APIs with JWT with Keycloak"
```suggestion
description: "How to secure your APIs with JWT and Keycloak"
```

2023-05-16 13:30 UTC, zalbiraw commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +6. Generate your JWTs using curl and store them. These are keys you will use to access your services through the Tyk Gateway.
```suggestion
6. Generate your JWT using curl. This is the token will use to access your services through the Tyk Gateway. You can choose to generate your JWT by using either of the following methods. Make sure to replace the `KEYCLOAK_` prefixed parameters with the appropriate values.
```

2023-05-16 13:30 UTC, zalbiraw commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +   - Select JWT in the Authentication mode section.
```suggestion
   - Scroll to the Authentication mode section and select JWT from the list.
```

2023-05-16 13:56 UTC, zalbiraw commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +   - Test with curl
I dont want to add an explanation for the `/etc/hosts` because i would be making an assumption of what kind of deployment the user is running.

2023-05-16 13:59 UTC, zalbiraw commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +{{< img src="/img/keycloak-jwt/create-api-step-4.png" alt="Add default Policy to API" width="800px" height="400" >}}
The UI will make the picture more confusing unfortunately because of the search policy box. I am going to leave this one as is

2023-05-16 14:00 UTC, zalbiraw commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +1. Access to your Keycloak admin dashboard.
```suggestion
1. Access your Keycloak admin dashboard.
```

2023-05-22 15:18 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +      "access_token" : "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6MXp6bWw0SmNFd3FBdnBWdEFmV1dGS01hMWppYjR1MlFEM3lzaU81VVJrIn0.eyJleHAiOjE2ODQxNzIxNTUsImlhdCI6MTY4NDE3MTg1NSwianRpIjoiNTkzYzQ
@zalbiraw do we need to put the full token?

2023-05-29 15:17 UTC, zalbiraw commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens/jwt-keycloak.md
> +      "access_token" : "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6MXp6bWw0SmNFd3FBdnBWdEFmV1dGS01hMWppYjR1MlFEM3lzaU81VVJrIn0.eyJleHAiOjE2ODQxNzIxNTUsImlhdCI6MTY4NDE3MTg1NSwianRpIjoiNTkzYzQ
I left it in there in case someone wanted to decode it and look at it.

2023-06-02 08:11 UTC, dcs3spp approved these changes

2023-06-02 08:18 UTC, merged

2023-06-02 08:18 UTC, dcs3spp commented
/release to release-5