Added error responses for size limit checks
TykTechnologies/tyk-docs-hugo pull request #2550
Opened 2023-05-16 11:20 UTC by andyo-tyk

Added HTTP error codes and status messages from the size limit checking middleware here: https://github.com/TykTechnologies/tyk/blob/29d50289c48ba2fccacba5306dc8fb408be15e85/gateway/mw_request_size_limit.go#L35

2023-05-16 15:48 UTC, dle519 approved these changes

2023-05-16 15:52 UTC, dcs3spp requested changes

2023-05-16 15:52 UTC, dcs3spp commented on tyk-docs/content/error-response-codes.md
> +| 400  | Request is too large                                                                   | The request body exceeds the configured size limit for the API endpoint.
@andyo-tyk Should the request is too large be HTTP status code 413?

```suggestion
| 413  | Request is too large                                                                   | The request body exceeds the configured size limit for the API endpoint.                                                                                                                           |
```

2023-05-16 16:09 UTC, andyo-tyk commented on tyk-docs/content/error-response-codes.md
> +| 400  | Request is too large                                                                   | The request body exceeds the configured size limit for the API endpoint.
It should be... but it isn't. :(
So here I'm documenting what the code actually returns, rather than what it _should_ return.
Ref: https://github.com/TykTechnologies/tyk/blob/29d50289c48ba2fccacba5306dc8fb408be15e85/gateway/mw_request_size_limit.go#L35
It's "on my list" to correct these inconsistencies... but as they would be breaking changes we have to handle them carefully.

2023-05-17 09:27 UTC, dcs3spp commented on tyk-docs/content/error-response-codes.md
> +| 400  | Request is too large                                                                   | The request body exceeds the configured size limit for the API endpoint.
ok thanks @andyo-tyk

2023-05-17 09:33 UTC, dcs3spp approved these changes
lgtm

2023-05-17 10:19 UTC, merged

2023-05-17 10:19 UTC, dcs3spp commented
/release to release-5