Update pump-1.8.md
TykTechnologies/tyk-docs-hugo pull request #2591
Opened 2023-05-26 13:39 UTC by caroltyk

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-05-28 21:38 UTC, dcs3spp requested changes
PR looks good to me Carol.

Maybe briefly add description of what Prometheus pump separator issue was.

2023-05-28 21:38 UTC, dcs3spp commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Updated the default Hybrid Pump RPC pool size from 20 to 5 connections in order to reduce default CPU and Memory footprint.
```suggestion
- Updated the default Hybrid Pump RPC pool size from 20 to 5 connections in order to reduce default CPU and memory footprint
```

2023-05-28 21:38 UTC, dcs3spp commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed prometheus pump separator issue
Briefly describe what the Prometheus pump separator issue was

2023-05-30 08:03 UTC, carolwkc commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed prometheus pump separator issue
```suggestion
- Fixed an issue that when processing an analytics record with an API name or path containing the -- separator used to join label values (e.g., web--test-beta), an "inconsistent label cardinality" error occurs and causes tyk pump to crash
```

2023-06-06 13:45 UTC, dcs3spp approved these changes

2023-06-06 20:04 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Reverted a change from previous release that excluded GraphQL analytics records from tyk_analytics collection for Mongo Pump
do we have content in the docs that needs to be removed?

2023-06-06 20:49 UTC, letzya commented
we can merge it to master when approved

2023-06-06 21:10 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed MongoDB connection issue when using a complex password (with mongo-go driver)
should we elaborate a bit?

2023-06-06 21:30 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed an issue that when processing an analytics record with an API name or path containing the -- separator used to join label values (e.g., web--test-beta), an "inconsistent label cardinality" er
```suggestion
- Fixed an issue that when processing an analytics record with an API name or path containing the `--` separator used to join label values (e.g., `web--test-beta`), an "_inconsistent label cardinality_" error occurs and causes tyk pump to crash
```

2023-06-06 21:31 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed an issue that when processing an analytics record with an API name or path containing the -- separator used to join label values (e.g., web--test-beta), an "inconsistent label cardinality" er
what is the actual fix? can we explain it? We need to explain the issue and the solution

2023-06-06 21:32 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Updated the default Hybrid Pump RPC pool size from 20 to 5 connections in order to reduce default CPU and memory footprint
Can this affect users who rely on this default? maybe we can double-check with support?

2023-06-06 21:33 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Import and use latest storage library
Not sure I understand this sentence. Can we explain what storage lib means?

2023-06-06 21:33 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Updated default MongoDB driver to ‘mgo’
```suggestion
- Updated default MongoDB driver to `mgo`
```

2023-06-06 21:34 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Updated default MongoDB driver to ‘mgo’
what does this mean? are we changing the default? can we share the config section?

2023-06-06 21:35 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Updated the default Hybrid Pump RPC pool size from 20 to 5 connections in order to reduce default CPU and memory footprint
Can we link to the config page?

2023-06-06 21:37 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Pump name is now case-insensitive. It will override two or more pumps with same name but in different cases (e.g. “Mongo” / “mongo”)
do we have a clear and user-friendly error message for this?

2023-06-08 11:03 UTC, caroltyk commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Reverted a change from previous release that excluded GraphQL analytics records from tyk_analytics collection for Mongo Pump
@agata-wit @pvormste could you confirm?

2023-06-08 11:06 UTC, caroltyk commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Updated the default Hybrid Pump RPC pool size from 20 to 5 connections in order to reduce default CPU and memory footprint
@tbuchaillot have we update the config page with default value?

2023-06-08 11:11 UTC, caroltyk commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed MongoDB connection issue when using a complex password (with mongo-go driver)
Fixed MongoDB connection issue when using a password with URL escape characters (with mongo-go driver)

2023-06-08 11:18 UTC, caroltyk commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed an issue that when processing an analytics record with an API name or path containing the -- separator used to join label values (e.g., web--test-beta), an "inconsistent label cardinality" er
The solution for fix is difficult to explain in a release notes without going into details how the flow and code works: https://github.com/TykTechnologies/tyk-pump/pull/603.

2023-06-08 12:22 UTC, tbuchaillot commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Updated the default Hybrid Pump RPC pool size from 20 to 5 connections in order to reduce default CPU and memory footprint
@caroltyk it's updated on the hybrid pump code config - I don't know if we already regenerate the docs cc @mativm02

2023-06-08 15:06 UTC, carolwkc commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Import and use latest storage library
Import and use latest [storage library v1.0.5](https://github.com/TykTechnologies/storage/releases/tag/v1.0.5)

2023-06-08 15:10 UTC, caroltyk commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Updated the default Hybrid Pump RPC pool size from 20 to 5 connections in order to reduce default CPU and memory footprint
Checked it's there already. thanks.

### pumps.hybrid.meta.RPCPoolSize
EV: <b>TYK_PMP_PUMPS_HYBRID_META_RPCPOOLSIZE</b><br />
Type: `int`<br />

Hybrid pump connection pool size. Defaults to `5`.

2023-06-08 15:17 UTC, caroltyk commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Pump name is now case-insensitive. It will override two or more pumps with same name but in different cases (e.g. “Mongo” / “mongo”)
@mativm02

2023-06-08 17:58 UTC, mativm02 commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Pump name is now case-insensitive. It will override two or more pumps with same name but in different cases (e.g. “Mongo” / “mongo”)
@letzya there's no error message. We're overriding it because when you want to modify a pump config through environment variables, the Pump type (i.e. 'mongo') is written in uppercase by default ('MONGO'). There's no way to write it in lowercase through env vars.
So, let's say you have your 'mongo' pump in your config file and you want to update the `mongo_url` config through env vars. You'd use `TYK_PMP_PUMPS_MONGO_META_MONGOURL` to modify it. Pump will detect this, but will think you're trying to modify the 'MONGO' pump, when it's actually 'mongo', so an error will be thrown. That's why we implemented this change and I don't think an error message should be displayed, since both 'MONGO' and 'mongo' pumps are supposed to be the same one.

2023-06-21 16:07 UTC, dcs3spp commented
I have approved. Can one of the peer reviewers also approve so that this can be merged and released?

2023-06-21 16:26 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Pump name is now case-insensitive. It will override two or more pumps with same name but in different cases (e.g. “Mongo” / “mongo”)
gotcha! thanks

2023-06-21 16:27 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Reverted a change from previous release that excluded GraphQL analytics records from tyk_analytics collection for Mongo Pump
```suggestion
- Reverted a change from previous release that excluded GraphQL analytics records from `tyk_analytics` collection for Mongo Pump
```

2023-06-21 16:28 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +For MongoDB v5 and v6 users, please [set mongo driver type](https://github.com/TykTechnologies/tyk-pump#driver-type) to 'mongo-go'.
```suggestion
For MongoDB v5 and v6 users, please [set mongo driver type](https://github.com/TykTechnologies/tyk-pump#driver-type) to `mongo-go`.
```

2023-06-21 16:29 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +From 1.8.1, the default MongoDB driver it use is from [mgo](https://github.com/go-mgo/mgo). This is to align with default MongoDB driver of other Tyk components. This driver supports MongoDB versions
```suggestion
From pump v1.8.1, the default MongoDB driver it uses is [mgo](https://github.com/go-mgo/mgo). This is to align with the default MongoDB driver of other Tyk components. This driver supports MongoDB versions up to v4. If you are using a later version of MongoDB v5 or MongoDB v6, please [follow this guide to update the driver type](https://github.com/TykTechnologies/tyk-pump#driver-type) to [mongo-go](https://github.com/mongodb/mongo-go-driver).
```

2023-06-21 16:31 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +From 1.8.1, the default MongoDB driver it use is from [mgo](https://github.com/go-mgo/mgo). This is to align with default MongoDB driver of other Tyk components. This driver supports MongoDB versions
@caroltyk about `From pump v1.8.1, the default MongoDB driver it uses is [mgo]`  - did you mean to say that in  pump v1.8.1 we have a new config for the mongo drive and it is set to mgo?

2023-06-21 16:53 UTC, caroltyk commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed an issue that when processing an analytics record with an API name or path containing the -- separator used to join label values (e.g., web--test-beta), an "inconsistent label cardinality" er
The suggestion is applied

2023-06-21 16:59 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed an issue that when processing an analytics record with an API name or path containing the -- separator used to join label values (e.g., web--test-beta), an "inconsistent label cardinality" er
so for once, it doesn't say it's a Prometheus pump

2023-06-21 17:02 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed an issue that when processing an analytics record with an API name or path containing the -- separator used to join label values (e.g., web--test-beta), an "inconsistent label cardinality" er
@caroltyk what is the fix? or what happens now after we fix it if I have`--`

2023-06-21 17:10 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Reverted a change from previous release that excluded GraphQL analytics records from tyk_analytics collection for Mongo Pump
@caroltyk this is still outstanding

2023-06-21 17:15 UTC, dcs3spp commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Reverted a change from previous release that excluded GraphQL analytics records from tyk_analytics collection for Mongo Pump
We have discussed and think this is what it should read like. Is this ok?

```suggestion
- GraphQL analytics records were being excluded from the _tyk_analytics_ collection for Mongo Pump. This has been fixed so that GraphQL analytic records are now included as expected.
```

2023-06-21 17:24 UTC, dcs3spp commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Reverted a change from the previous release that excluded GraphQL analytics records from `tyk_analytics` collection for Mongo Pump
```suggestion
- GraphQL analytics records were being excluded from the _tyk_analytics_ collection for Mongo Pump. This has been fixed so that GraphQL analytic records are now included as expected.
```

2023-06-22 08:23 UTC, dcs3spp commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed an issue that when processing an analytics record with an API name or path containing the -- separator used to join label values (e.g., web--test-beta), an "inconsistent label cardinality" er
```suggestion
Fixed an issue in Prometheus pump when filtering fields , e.g. _API Name_, that contain `--` in their value. For example, `test--name`. Prometheus Pump filtered the field as two separate instances, e.g. `test` & `name`, instead of the expected `test--name`.
```

2023-06-22 08:24 UTC, dcs3spp commented
```suggestion
Fixed an issue in Prometheus pump when filtering fields , e.g. _API Name_, that contain `--` in their value. For example, `test--name`. Prometheus Pump filtered the field as two separate instances, e.g. `test` & `name`, instead of the expected `test--name`.
```
@carol, @matias, @letzya is this ok for the desription of the Prometheus Pump filtering issue?

2023-06-22 08:45 UTC, caroltyk commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Reverted a change from previous release that excluded GraphQL analytics records from tyk_analytics collection for Mongo Pump
@pvormste please help to confirm

2023-06-22 09:01 UTC, kofoworola commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Reverted a change from previous release that excluded GraphQL analytics records from tyk_analytics collection for Mongo Pump
@caroltyk jumping in here to help with this. Yes this copy looks good @dcs3spp

2023-06-22 12:59 UTC, dcs3spp commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Fixed an issue that when processing an analytics record with an API name or path containing the `--` separator used to join label values (e.g., `web--test-beta`), an "_inconsistent label cardinalit
```suggestion
- Fixed an issue in Prometheus pump when filtering fields , e.g. _API Name_, that contain `--` in their value. For example, `test--name`. Prometheus Pump filtered the field as two separate instances, e.g. `test` & `name`, instead of the expected `test--name`.
```

2023-06-22 13:01 UTC, dcs3spp approved these changes
Updated fix for Prometheus pump filtering

Fixed an issue in Prometheus pump when filtering fields, e.g. _API Name_, that contain _--_ in their value. For example, _test--name_. Prometheus Pump filtered the field as two separate instances, e.g. _test_ & _name_, instead of the expected _test--name_.

2023-06-22 13:18 UTC, letzya commented on tyk-docs/content/release-notes/pump-1.8.md
> +- Pump name is now case-insensitive. It will override two or more pumps with same name but in different cases (e.g. “Mongo” / “mongo”)
```suggestion
- Pump name is now case-insensitive. It will override two or more pumps with the same name but in different cases (e.g. _Mongo_ / _mongo_)
```

2023-06-22 13:58 UTC, mativm02 approved these changes
LGTM!

2023-06-22 14:07 UTC, dcs3spp approved these changes

2023-06-22 14:10 UTC, merged

2023-06-22 14:13 UTC, dcs3spp commented
/release to release-5

2023-06-22 14:13 UTC, dcs3spp commented
/release to release-5.1