Rewrite of the upstream cache control headers docs
TykTechnologies/tyk-docs-hugo pull request #2596
Opened 2023-05-29 15:42 UTC by titpetric

## Related Issue (if applicable)

https://tyktech.atlassian.net/browse/TT-9022

## Description

Better documents upstream cache behaviour. Editing for clarity, info...

## Motivation and Context

Adoption problems due to bad docs.

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-05-29 21:13 UTC, letzya commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +**x-tyk-cache-action-set-ttl**: If the header is present, Tyk uses the
if I do ctrl+f for "x-tyk-cache-action-set-ttl" - i see this info twice. why?

2023-05-29 21:14 UTC, letzya requested changes
Per comment. needs a bit of tidying up.
I also removed the DX writer and added a peer as a reviewer. Add Simon after it's approved.

2023-06-08 14:46 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +**x-tyk-cache-action-set-ttl**: If the header is present, Tyk uses the
it's referenced twice, one is the setting, one is the behaviour explanation

2023-06-08 14:54 UTC, titpetric commented
@andyo-tyk will open a new proposal, closing this PR.

2023-06-08 14:54 UTC, closed without merging