[TT-6486/TT-9036] update error response codes to have certificate has expired error
TykTechnologies/tyk-docs-hugo pull request #2599
Opened 2023-05-30 05:59 UTC by jeffy-mathew

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-05-30 10:49 UTC, andyo-tyk requested changes
Slight rewording suggested

2023-05-30 10:49 UTC, andyo-tyk commented on tyk-docs/content/error-response-codes.md
> +| 403  | Certificate has expired                                                                 | Please update the attached certificates that are currently valid and have not expired.
```suggestion
| 403  | Certificate has expired                                                                 | Please update the certificate with one that is currently valid and has not expired.                                                                                                  |
```

2023-05-31 13:52 UTC, andyo-tyk approved these changes

2023-05-31 13:59 UTC, dcs3spp approved these changes
lgtm

2023-06-01 12:13 UTC, merged