Improved wording of size limits
TykTechnologies/tyk-docs-hugo pull request #2601
Opened 2023-05-30 09:40 UTC by andyo-tyk

TT-9019
Added new gateway-level request body size limit
Improved flow and wording for the rest of the page.

2023-05-30 11:45 UTC, dcs3spp requested changes
Lgtm Andy. Have proof read with minor changes

2023-05-30 11:45 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +With Tyk, you are able to apply limits to the size of requests made to your HTTP APIs; you might do this to protect your upstream services or even the gateway itself, for example, to avoid excessive
```suggestion
With Tyk, you can apply limits to the size of requests made to your HTTP APIs to protect upstream services or even the gateway itself. For example, to avoid excessive memory usage or brute force attacks.
```

2023-05-30 11:45 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk compares each incoming API request with the configured maximum size(s) and will reject any request that exceeds the size you have set, returning an HTTP 400 error with the message "Request is too
Should it return HTTP 413?

2023-05-30 11:45 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk Cloud Classic automatically enforces a strict request size limit of 1MB an all inbound requests via our cloud architecture. This does not affect Multi-Cloud users.
```suggestion
Tyk Cloud Classic automatically enforces a strict request size limit of 1MB on all inbound requests via our cloud architecture. This does not affect Multi-Cloud users.
```

2023-05-30 11:45 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +You can optionally configure a request size limit (in bytes) that will be applied to all APIs on your Tyk Gateway by adding `max_request_body_size` to the `http_server_options` [element]({{< ref "/ty
```suggestion
You can optionally configure a request size limit (in bytes) that will be applied to all APIs on your Tyk Gateway by adding `max_request_body_size` to the `http_server_options` [element]({{< ref "/tyk-oss-gateway/configuration#http_server_options" >}}) of your `tyk.conf` Gateway configuration. For example:
```

2023-05-30 11:45 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +This limit is applied for all endpoints _within an API_, is evaluated after the Gateway-wide size limit and before any endpoint-specific size limit.
```suggestion
This limit is applied for all endpoints _within an API_. It is evaluated after the Gateway-wide size limit and before any endpoint-specific size limit.
```

2023-05-30 11:45 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk provides a _Request Size Limit_ middleware that can be configured per API endpoint, to give you the most granular control over request sizes.
```suggestion
Tyk provides a _Request Size Limit_ middleware that can be configured per API endpoint. This gives you the most granular control over request sizes.
```

2023-05-30 11:45 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +This limit will be applied after any Gateway-level or API-level size limits; as for all of the size limit options provided by Tyk, this value is given in bytes.
```suggestion
This limit will be applied after any Gateway-level or API-level size limits. For all of the size limit options provided by Tyk, this value is given in bytes.
```

2023-05-30 11:45 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +To enforce a request size limit for a specific API endpoint, you will use from your API Endpoint Designer:
```suggestion
From your API Endpoint Designer, to enforce a request size limit for a specific API endpoint:
```

2023-05-30 13:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +With Tyk, you are able to apply limits to the size of requests made to your HTTP APIs; you might do this to protect your upstream services or even the gateway itself, for example, to avoid excessive
What about:
```suggestion
With Tyk, you can apply limits to the size of requests made to your HTTP APIs. You might use this feature to protect your Tyk Gateway or upstream services from avoid excessive memory usage or brute force attacks.
```

2023-05-30 13:16 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +This limit will be applied after any Gateway-level or API-level size limits; as for all of the size limit options provided by Tyk, this value is given in bytes.
How about:
```suggestion
This limit will be applied after any Gateway-level or API-level size limits; in keeping with the other size limit options provided by Tyk, this value is given in bytes.
```

2023-05-30 13:17 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +To enforce a request size limit for a specific API endpoint, you will use from your API Endpoint Designer:
I missed this when I rewrote the page, how about:

```suggestion
You can enforce a request size limit for a specific API endpoint using the API Endpoint Designer:
```

2023-05-30 13:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk compares each incoming API request with the configured maximum size(s) and will reject any request that exceeds the size you have set, returning an HTTP 400 error with the message "Request is too
We return this (HTTP 413 Content Too Large) for the Gateway-level size limit, but I think we return (400 Request is too large) for the others... will check.

2023-05-30 14:57 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk compares each incoming API request with the configured maximum size(s) and will reject any request that exceeds the size you have set, returning an HTTP 400 error with the message "Request is too
So, turns out we return:
`413 Request Entity Too Large` for `max-request-body-size` check (Gateway-level)
`400 Request is too large` for the API-level and endpoint-level checks

I'll propose changes

2023-05-30 15:02 UTC, andyo-tyk reviewed
Added the error codes/messages for each size limit test

2023-05-30 15:02 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk compares each incoming API request with the configured maximum size(s) and will reject any request that exceeds the size you have set, returning an HTTP 400 error with the message "Request is too
```suggestion
Tyk compares each incoming API request with the configured maximum size(s) and will reject any request that exceeds the size you have set, returning an HTTP 4xx error as detailed below.
```

2023-05-30 15:02 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +This Gateway-wide size limit will be evaluated before per-API or per-endpoint settings.
```suggestion
This Gateway-wide size limit will be evaluated before per-API or per-endpoint settings. If this test fails, the Tyk Gateway will report `413 Request Entity Too Large`.
```

2023-05-30 15:02 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +This limit is applied for all endpoints _within an API_. It is evaluated after the Gateway-wide size limit and before any endpoint-specific size limit.
```suggestion
This limit is applied for all endpoints _within an API_. It is evaluated after the Gateway-wide size limit and before any endpoint-specific size limit. If this test fails, the Tyk Gateway will report `400 Request is too large`.
```

2023-05-30 15:02 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +This limit will be applied after any Gateway-level or API-level size limits; in keeping with the other size limit options provided by Tyk, this value is given in bytes.
```suggestion
This limit will be applied after any Gateway-level or API-level size limits; in keeping with the other size limit options provided by Tyk, this value is given in bytes. If this test fails, the Tyk Gateway will report `400 Request is too large`.
```

2023-06-01 13:25 UTC, dcs3spp approved these changes
lgtm

2023-06-01 15:22 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +#### Manually configuring the API Definition
```suggestion
#### Manually configuring the API Definition

```

2023-06-01 15:24 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +To add the _Request Size Limit_ middleware in your API Definition, simply add a new section to the `extended_paths` block of your API Definition configuration called `size_limits`:
```suggestion
To add the _Request Size Limit_ middleware to your API Definition, create a new section in the `extended_paths` block of your API Definition configuration called `size_limits`:
```

2023-06-01 15:24 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +#### Using the Tyk Dashboard
```suggestion
#### Using the Tyk Dashboard

```

2023-06-01 15:24 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +### Applying a size limit for a specific API endpoint
```suggestion
### Applying a size limit for a specific API endpoint

```

2023-06-01 15:24 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +### Applying a size limit for a specific API
```suggestion
### Applying a size limit for a specific API

```

2023-06-01 15:25 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +### Applying a size limit for all APIs on your Gateway
```suggestion
### Applying a size limit for all APIs on your Gateway

```

2023-06-01 15:25 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +Tyk Cloud Classic automatically enforces a strict request size limit of 1MB on all inbound requests via our cloud architecture. This does not affect Multi-Cloud users.
```suggestion
Tyk Cloud Classic enforces a strict request size limit of 1MB on all inbound requests via our cloud architecture. This does not affect Multi-Cloud users.
```

I mean there's no other way than automatically, it's redundant

2023-06-02 12:26 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +### Applying a size limit for all APIs on your Gateway
looks similar, did mean something else?

2023-06-02 12:26 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +### Applying a size limit for a specific API
looks similar, did mean something else?

2023-06-02 12:26 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +### Applying a size limit for a specific API endpoint
looks similar, did mean something else?

2023-06-02 12:27 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +#### Using the Tyk Dashboard
looks similar, did mean something else?

2023-06-02 12:27 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +#### Manually configuring the API Definition
looks similar, did mean something else?

2023-06-02 13:06 UTC, merged

2023-06-19 11:23 UTC, dcs3spp commented
/release to release-5.1