Release notes 5.1
TykTechnologies/tyk-docs-hugo pull request #2626
Opened 2023-06-05 08:35 UTC by dcs3spp

Release notes for 5.1 created for checking and proof reading

Need to update docker image links when available

2023-06-05 16:37 UTC, letzya commented on tyk-docs/content/release-notes/version-5.1.md
> +- Fixed an issue where the `global_size_limit` setting didn't enable request size limit middleware. Thanks to @PatrickTaibel for the contribution!
@dcs3spp do we @ names?

2023-06-05 16:38 UTC, letzya commented on tyk-docs/content/release-notes/version-5.1.md
> +- Added "HasOperation", "Operation" and "Variables" to GraphQL data source API definition for easier nesting
should we do `HasOperation` with back tick?

2023-06-05 16:47 UTC, letzya commented on tyk-docs/content/release-notes/version-5.1.md
> +- Fixed an issue where the `global_size_limit` setting didn't enable request size limit middleware. Thanks to @PatrickTaibel for the contribution!
Can we please link to the page that explains`global_size_limit` in length

2023-06-05 16:51 UTC, letzya commented on tyk-docs/content/release-notes/version-5.1.md
> +- Added two endpoints to the dashboard to support the retrieval of example API definitions. One for fetching all examples and another for fetching a single example.
do we have docs to explain it ? or just our swagger? @agata-wit

2023-06-05 16:54 UTC, letzya commented on tyk-docs/content/release-notes/version-5.1.md
> +- Added query param `apidef=true` to example detail endpoint in Dashboard API to retrieve the API definition of an example
add the endpoint name @agata-wit

2023-06-14 16:00 UTC, letzya commented on tyk-docs/content/release-notes/version-5.1.md
> +- Fixed an issue where the `global_size_limit` setting didn't enable request size limit middleware. Thanks to @PatrickTaibel for the contribution!
https://github.com/PatrickTaibel

2023-06-16 10:29 UTC, andyo-tyk commented
I'm preparing the long form content for Core APIM - but please can we avoid structuring the content by squad and definitely do not mention squad names, as they are meaningless to the user of these docs? I don't know if those are intended only as placeholders but we should remove those headers (Core APIM / API as Integration / Platform) before publication.

2023-06-16 11:08 UTC, dcs3spp commented
@andyo-tyk have removed the headings for core APIM etc.

2023-06-16 12:10 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +- Fixed an issue where API Ownership was not respected in traffic reports for the _API Activity Dashboard Requests_ and _Average Errors Over Time_ charts in the Tyk Dashboard. Note that it is not cur
Please can you replace this with the following, and move to the "Added" section for Dashboard?

```suggestion
- Added new `owned_analytics` user permission which restricts the user's access only to analytics relating to APIs they own. These are the _API Activity Dashboard Requests_ and _Average Errors Over Time_ charts in the Tyk Dashboard. Note that it is not currently possible to respect API Ownership in other aggregated charts
```

2023-06-16 12:15 UTC, dcs3spp commented
I am going to format front paragraph to add links and also adding contributors section. Will add the docker images once published

2023-06-16 15:42 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +- Added new `owned_analytics` user permission which restricts the user's access only to analytics relating to APIs they own. These are the _API Activity Dashboard Requests_ and _Average Errors Over T
Can you please move this up to c. line 127?

2023-06-17 09:46 UTC, andyo-tyk requested changes
- Some typos corrects / phrasing improved
- Spotted a duplicate in the change log
- The "squad name" headers should (IMHO) be removed from the top section as they don't add anything and are just Tyk terminology.

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +statistics from APIs that that own; we’ve called this “Owned Analytics”. Due to
Typo:

```suggestion
statistics from APIs that they own; we’ve called this “Owned Analytics”. Due to
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +## Core APIM
Please delete this - it's internal information (squad name) and meaningless to a user of the docs.

```suggestion
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +## API as Integration
Please delete this - it's internal information (squad name) and meaningless to a user of the docs.

```suggestion
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +tyk-sync. We now extended this feature and it is now possible to do this without
```suggestion
tyk-sync. We have now extended this feature and it is now possible to do this without
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +## Platform
Please delete this - it's internal information (squad name) and meaningless to a user of the docs.

```suggestion
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +This means it will generate the full schema as well as the data sources that are defined inside the OAS document.
```suggestion
This will generate the full schema as well as the data sources that are defined inside the OAS document.
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +size at
```suggestion
size using
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +The default RPC pool size is changed from 20 to 5. This can reduce the CPU and
```suggestion
We have reduced the default RPC pool size from 20 to 5. This can reduce the CPU and
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +Our Dashboard and Gateway are using [Golang 1.19](https://tip.golang.org/doc/go1.19) Programming Language ] starting with
```suggestion
Our Dashboard and Gateway are using [Golang 1.19](https://tip.golang.org/doc/go1.19) Programming Language starting with
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +tyk-sync. We now extended this feature and it is now possible to do this without
```suggestion
Tyk Sync. We have extended this feature and you can now do this without
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +Before this release, it was only possible to realize nested GraphQL stitching
```suggestion
Before this release, it was only possible to implement nested GraphQL stitching
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +providing the GraphQL body manually. We now extended the GraphQL data source so
```suggestion
providing the GraphQL body manually. We have now extended the GraphQL data source so
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +- Fixed an issue so that filtering by API respects API Ownership in three Dashboard charts.
```suggestion
- Fixed an issue so that filtering by API now respects API Ownership in three Dashboard charts.
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +- Improve performance when opening the portal page by pre-fetching required data by a few calls instead of thousands
This is a duplicate -> I think this one should be deleted, as it refers to Classic Portal

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +- Improve performance when opening the portal page by pre-fetching required data by a few calls instead of thousands.
```suggestion
- Improved performance when opening the Portal page by optimising the pre-fetching of required data
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +Special thanks go the Tyl community for their contributions in this release.
```suggestion
Special thanks to the following members of the Tyk community for their contributions in this release:
```

2023-06-17 09:46 UTC, andyo-tyk commented on tyk-docs/content/release-notes/version-5.1.md
> +Note: Upgrading the Golang version implies that all the Golang custom plugins that you are using need to be recompiled before migrating to v5.0 of the Gateway. Check our docs for more details [Golang
```suggestion
Please remember that the upgrade to the Golang version implies that all the Golang custom plugins that you are using need to be recompiled before migrating to v5.1 of the Gateway. Check our docs for more details [Golang Plugins]({{< ref "plugins/supported-languages/golang#upgrading-tyk" >}}).
```

2023-06-19 09:27 UTC, agata-wit commented on tyk-docs/content/release-notes/version-5.1.md
> +- Added two endpoints to the dashboard to support the retrieval of example API definitions. One for fetching all examples and another for fetching a single example.
Just swagger

2023-06-19 09:28 UTC, agata-wit approved these changes

2023-06-19 09:33 UTC, andyo-tyk approved these changes
Looking good.... :)

2023-06-19 09:39 UTC, agata-wit commented on tyk-docs/content/release-notes/version-5.1.md
> +- Added query param `apidef=true` to example detail endpoint in Dashboard API to retrieve the API definition of an example
I would love to but I can't push anything to the branch, it's protected.
@dcs3spp can you help?

2023-06-19 09:40 UTC, agata-wit commented on tyk-docs/content/release-notes/version-5.1.md
> +- Added query param `apidef=true` to example detail endpoint in Dashboard API to retrieve the API definition of an example
Line 121 should be: - Added an api/examples endpoint to Dashboard API that returns a list of available API examples that can later be imported into the Dashboard `GET /api/examples`
Line 122 should be: - Added an endpoint to Dashboard API that transforms an OpenAPI document into UDG config and publishes it in Dashboard `POST /api/data-graphs/data-sources/import`

2023-06-19 11:12 UTC, dcs3spp commented on tyk-docs/content/release-notes/version-5.1.md
> +- Fixed an issue where the `global_size_limit` setting didn't enable request size limit middleware. Thanks to @PatrickTaibel for the contribution!
Removed @ and updated with GHub profile link

2023-06-19 11:13 UTC, dcs3spp commented on tyk-docs/content/release-notes/version-5.1.md
> +- Added "HasOperation", "Operation" and "Variables" to GraphQL data source API definition for easier nesting
Updated

2023-06-19 11:13 UTC, dcs3spp commented on tyk-docs/content/release-notes/version-5.1.md
> +- Added query param `apidef=true` to example detail endpoint in Dashboard API to retrieve the API definition of an example
@agata-wit I have updated lines 121 and 122 for you

2023-06-19 11:17 UTC, dcs3spp commented on tyk-docs/content/release-notes/version-5.1.md
> +- Fixed an issue where the `global_size_limit` setting didn't enable request size limit middleware. Thanks to @PatrickTaibel for the contribution!
Is that this [page](https://tyk.io/docs/basic-config-and-security/control-limit-traffic/request-size-limits/#global-size-limiting-for-your-api)?

2023-06-23 09:30 UTC, buger commented on tyk-docs/content/release-notes/version-5.1.md
> +### Import UDG API from OAS 3.x
@dcs3spp do we have link to the doc here?

2023-06-23 09:31 UTC, buger commented on tyk-docs/content/release-notes/version-5.1.md
> +that, if you’re using GoPlugins, you’ll need to recompile these to maintain
@dcs3spp I think we had new docs for Go plugins as well?

2023-06-23 10:38 UTC, dcs3spp commented on tyk-docs/content/release-notes/version-5.1.md
> +### Import UDG API from OAS 3.x
Updated with link

2023-06-23 15:24 UTC, dcs3spp commented
Encountered rebase conflicts. Fixed and addressed by PR https://github.com/TykTechnologies/tyk-docs/pull/2765

2023-06-23 15:24 UTC, closed without merging