Add docs for EDP 1.4.0
TykTechnologies/tyk-docs-hugo pull request #2637
Opened 2023-06-07 00:59 UTC by slega

## Related Issue (if applicable)

## Description
Add docs for the 1.4.0 release of the portal:
- Update deployment diagram
- Add the `db` option for the storage config option
- Add FAQ about SQL support for the portal's CMS assets to the installation page

## Motivation and Context
1.4.0 release of the portal add support for SQL as a storage for CMS assets.

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [x] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [x] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-06-07 14:42 UTC, zalbiraw approved these changes
LGTM

2023-06-08 09:20 UTC, dcs3spp requested changes
Hi Sergei. The PR looks good to me. Made some minor suggestions

Once requested changes have been done and both peers have completed their reviews can this be released?

2023-06-08 09:20 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal.md
> +### Does the portal support SQL database for storing the portal's CMS assets?
```suggestion
### Does the portal support SQL databases for storing the portal's CMS assets?
```

2023-06-08 09:20 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +- `db` to use the portal's main database. In the `db` is selected as a storage type, the portal application will create appropriate structure in the database that is used to store the portal's metada
```suggestion
- `db` to use the portal's main database. If the `db` is selected as a storage type, the portal application will create appropriate structure in the database that 
```

2023-06-08 14:04 UTC, dcs3spp approved these changes

2023-06-12 07:40 UTC, carlostyk approved these changes
Looks good to me! Thank you.

2023-06-12 08:02 UTC, merged

2023-06-12 08:03 UTC, dcs3spp commented
/release to release-5