TT-9079: rename edge gateway wording to cloud data plane
TykTechnologies/tyk-docs-hugo pull request #2642
Opened 2023-06-07 09:25 UTC by mitjaziv

## Related Issue (if applicable)

TT-9079

## Description

Change rewords Edge Gateway to Cloud Data Planes in scope of Tyk Cloud usage.

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-06-07 10:43 UTC, komuw commented
@mitjaziv check;
- tyk-docs/content/tyk-on-premises/licensing.md line 42, 59
- tyk-docs/content/shared/dashboard-config.md line 1001, 1017
- tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md line 312, 314, 316
- CONTRIBUTING-TECHNICAL-GUIDE.md line 335

2023-06-07 11:51 UTC, mitjaziv commented
> @mitjaziv check;
> 
>     * tyk-docs/content/tyk-on-premises/licensing.md line 42, 59
> 
>     * tyk-docs/content/shared/dashboard-config.md line 1001, 1017
> 
>     * tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md line 312, 314, 316
> 
>     * CONTRIBUTING-TECHNICAL-GUIDE.md line 335

The change was intentionally targeting just Tyk Cloud scope.

2023-06-07 12:57 UTC, letzya commented on tyk-docs/content/tyk-cloud/environments-&-deployments.md
> +* [Cloud Data Planes]({{< ref "/content/tyk-cloud/environments-&-deployments/managing-gateways.md" >}})
```suggestion
* [Cloud Data Planes]({{< ref "tyk-cloud/environments-&-deployments/managing-gateways.md" >}})
```

2023-06-07 13:23 UTC, letzya commented on tyk-docs/content/tyk-cloud/environments-&-deployments.md
>  * [Control Planes]({{< ref "/content/tyk-cloud/environments-&-deployments/managing-control-planes.md" >}})
```suggestion
* [Control Planes]({{< ref "tyk-cloud/environments-&-deployments/managing-control-planes.md" >}})
```

2023-06-07 16:49 UTC, letzya commented on tyk-docs/content/tyk-cloud/securing-your-apis.md
> +Tyk can [sign the request with HMAC or RSA]({{< ref "/content/release-notes/version-2.9.md#hmac-request-signing" >}}), before sending it to the API target. This is an implementation of an [RFC Signin
```suggestion
Tyk can [sign the request with HMAC or RSA]({{< ref "/release-notes/version-2.9.md#hmac-request-signing" >}}), before sending it to the API target. This is an implementation of an [RFC Signing HTTP Messages(draft 10)](https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-10). This RFC was designed to provide authenticity of the digital signature of the client. In our flow, the Tyk Cloud Data Planes, as the client, using a certificate private key, will add a header signature to the request. The API, using a pre-agreed public key (based on a meaningful keyId identifier) will verify the authenticity of the request coming from your Tyk Cloud Data Plane.
```

2023-06-08 13:23 UTC, dcs3spp reviewed
Hi Mitja, Many thanks for including the link to the Jira ticket for context etc. I have the seen the discussion thread on the Jira ticket etc. In the meantime I have pulled the branch locally. 

All looks good apart from in content/tyk-cloud.md, I am trying to work out issue with badge link to `tyk-cloud/environments-deployments/managing-environments`

2023-06-08 13:23 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud.md
> +{{< badge title="Administration" href="tyk-cloud/environments-deployments/managing-environments" >}}
broken link when try locally

2023-06-08 13:53 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud.md
> +{{< badge title="Administration" href="tyk-cloud/environments-deployments/managing-environments" >}}
If an alias is added to the front matter for `tyk-docs/content/tyk-cloud/managing-environments.md` the badge link for managing environments works on the `content/tyk-cloud` page:

```markdown
---
title: "Managing Environments"
date: 2020-04-21
tags: ["Tyk Cloud", "Management"]
description: "How to manage your Tyk Cloud Environments"
menu:
  main:
    parent: "Environments & Deployments"
weight: 2
aliases:
  - tyk-cloud/environments-&-deployments/managing-environments
  - /tyk-cloud/environments-deployments/managing-environments
```

2023-06-15 13:55 UTC, letzya commented
FYI - @SonjaChevre and I are discussing this. We'll update here when we have a decision.

2023-06-15 13:58 UTC, letzya commented on tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/first-api.md
> +  2. Scroll to the **Segment Tags (Node Segmentation)** setting and add the cloud data plane tag (edge) you saw when creating the Cloud Data Plane.
@mitjaziv if it's not hard - could you please add a screenshot here? I feel it can really help

2023-06-15 13:59 UTC, letzya commented on tyk-docs/content/tyk-cloud/environments-&-deployments.md
> +* [Cloud Data Planes]({{< ref "/content/tyk-cloud/environments-&-deployments/managing-gateways.md" >}})
@mitjaziv

2023-06-15 14:04 UTC, letzya commented on tyk-docs/content/tyk-cloud.md
> +Create and manage your Control Plane and Cloud Data Plane deployments
@SonjaChevre shouldn't it be `Cloud control Plane`?

2023-06-15 15:01 UTC, SonjaChevre commented on tyk-docs/content/tyk-cloud.md
> +Create and manage your Control Plane and Cloud Data Plane deployments
all control planes in Tyk Cloud are "Cloud Control Planes", so I think it is not necessary to add it here. But maybe somewhere at top / another intro page where we talk about Tyk Cloud, we should add this information (Control planes are run deployed and managed in the Cloud, you get two options...)

2023-06-16 11:04 UTC, letzya commented on tyk-docs/content/tyk-cloud.md
> +Create and manage your Control Plane and Cloud Data Plane deployments
```suggestion
Create and manage your Cloud Control Plane and Cloud Data Plane deployments
```

2023-06-16 11:05 UTC, letzya commented on tyk-docs/content/tyk-cloud.md
> +Create and manage your Control Plane and Cloud Data Plane deployments
@mitjaziv @SonjaChevre please update to clarify it's a cloud cp (not all users of the docs are cloud users, as discussed)

2023-06-16 11:07 UTC, letzya commented on tyk-docs/content/tyk-cloud.md
> +{{< badge title="Administration" href="tyk-cloud/environments-deployments/managing-environments" >}}
@dcs3spp is this resolved?

2023-06-16 11:09 UTC, letzya commented on tyk-docs/content/tyk-cloud.md
> +{{< badge title="Administration" href="tyk-cloud/teams-&-users/" >}}
@dcs3spp can you please use the alias without the &

2023-06-16 11:10 UTC, letzya commented on tyk-docs/content/tyk-cloud/account-billing/plans.md
> +| Launch            | For single teams with low traffic, mostly small businesses                          | This plan includes all of the features of the Tyk Stack. You can have **[custom domains]({{
```suggestion
| Launch            | For single teams with low traffic, mostly small businesses                          | This plan includes all of the features of the Tyk Stack. You can have **[custom domains]({{< ref "tyk-cloud/using-custom-domains" >}})** and **[plugins]({{< ref "tyk-cloud/using-plugins" >}})** along with standard support                                                                                                                                                                                                                    |
```

2023-06-16 11:10 UTC, letzya commented on tyk-docs/content/tyk-cloud/account-billing/plans.md
> +| Grow              | For single teams with high traffic                                                  | This plan includes all of the features of the Tyk Stack. In this plan, you have **[Hybrid G
@dcs3spp @mitjaziv please don't use the `.md`

2023-06-16 11:10 UTC, letzya commented on tyk-docs/content/tyk-cloud/account-billing/plans.md
> +| Grow              | For single teams with high traffic                                                  | This plan includes all of the features of the Tyk Stack. In this plan, you have **[Hybrid G
```suggestion
| Grow              | For single teams with high traffic                                                  | This plan includes all of the features of the Tyk Stack. In this plan, you have **[Hybrid Gateways]({{< ref "tyk-cloud/environments-deployments/hybrid-gateways" >}})** as an add on. Standard support is provided                                                                                                                                                                                                   |
```

2023-06-16 11:11 UTC, letzya commented on tyk-docs/content/tyk-cloud/account-billing/retirement.md
> +Your plan will go into [retirement]({{< ref "tyk-cloud/troubleshooting-&-support/glossary.md#retirement" >}}) in the following scenarios:
@dcs3spp change to alias without & throughout the PR please

2023-06-16 11:11 UTC, letzya commented on tyk-docs/content/tyk-cloud/account-billing/upgrade-free-trial.md
> +During the free trial we give you the same access as our Enterprise Global plan. When you come to the end of your free trial, you may want to subscribe to a plan such as 'Proof of Concept' which only
```suggestion
During the free trial we give you the same access as our Enterprise Global plan. When you come to the end of your free trial, you may want to subscribe to a plan such as 'Proof of Concept' which only allows 1 Environment, Cloud Control Plane and Cloud Data Plane. If you had an excess of these set up during your free trial, you would need to remove the appropriate amount of Environments etc from your Organisation in order to start the paid plan. But don't worry, we'll let you know what you need to remove when you go to purchase a plan. 
```

2023-06-16 11:13 UTC, letzya requested changes
Throughtout the PR:
1. Please use an alias in the links that have & 
2. Please add cloud before `Control plane` 
3. Remove `.md` from URLs
4. Capitalise `Data Plane`

2023-06-16 14:52 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud.md
> +{{< badge title="Administration" href="tyk-cloud/teams-&-users/" >}}
@letzya pushed changes up to the PR branch

2023-06-16 15:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/account-billing/plans.md
> +| Grow              | For single teams with high traffic                                                  | This plan includes all of the features of the Tyk Stack. In this plan, you have **[Hybrid G
@letzya I have pushed changes to update this.

2023-06-16 15:13 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/account-billing/plans.md
> +| Grow              | For single teams with high traffic                                                  | This plan includes all of the features of the Tyk Stack. In this plan, you have **[Hybrid G
I have pushed changes to remove the .md

2023-06-19 12:20 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/account-billing/retirement.md
> +Your plan will go into [retirement]({{< ref "tyk-cloud/troubleshooting-&-support/glossary.md#retirement" >}}) in the following scenarios:
Tried for troubleshooting-&-support in the glossary.md file but does not work, received 404 status error

2023-06-19 12:22 UTC, dcs3spp requested changes
Looks good Mitja, I fixed a broken link in cloud environments badge in /content/tyk-cloud.md

I think there is a suggestion to add a screenshot (https://github.com/TykTechnologies/tyk-docs/pull/2642#discussion_r1231062860)

2023-06-21 06:36 UTC, mitjaziv commented on tyk-docs/content/tyk-cloud/account-billing/plans.md
> +| Grow              | For single teams with high traffic                                                  | This plan includes all of the features of the Tyk Stack. In this plan, you have **[Hybrid G
@letzya `.md` was there before?

@dcs3spp thanks for fixing it.

2023-06-21 06:38 UTC, mitjaziv commented on tyk-docs/content/tyk-cloud.md
> +Create and manage your Control Plane and Cloud Data Plane deployments
@letzya @SonjaChevre UX does not now the term `Cloud Control Plane` so let's take this discussion offline, and tackle it in separate PR, because if this is changed in the docs it also needs to be changed in UI.

2023-06-21 06:49 UTC, mitjaziv commented on tyk-docs/content/tyk-cloud/account-billing/retirement.md
> +Your plan will go into [retirement]({{< ref "tyk-cloud/troubleshooting-&-support/glossary.md#retirement" >}}) in the following scenarios:
If this is not yet finished, I would suggest to tackle it in separate PR, as this is not part of the original ticket.

2023-06-21 07:26 UTC, mitjaziv commented on tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/first-api.md
> +  2. Scroll to the **Segment Tags (Node Segmentation)** setting and add the cloud data plane tag (edge) you saw when creating the Cloud Data Plane.
https://github.com/TykTechnologies/tyk-docs/pull/2746

2023-06-21 16:32 UTC, dcs3spp approved these changes

2023-06-21 16:38 UTC, letzya commented on tyk-docs/content/tyk-cloud/configuration-options.md
> +- [Securing your APIs]({{< ref "tyk-cloud/securing-your-apis.md" >}})
```suggestion
- [Securing your APIs]({{< ref "tyk-cloud/securing-your-apis" >}})
```

2023-06-21 17:24 UTC, letzya commented on tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-org.md
> +Our demo setup will quickly configure your first deployment setup automatically, creating your first team, control plane and cloud data plane.
```suggestion
Our demo setup will quickly configure your first deployment setup automatically, creating your first team, Cloud Control Plane and Cloud Data Plane.
```

2023-06-21 17:33 UTC, letzya approved these changes

2023-06-21 17:46 UTC, merged

2023-06-28 22:41 UTC, letzya commented
needs merging to latest, after it's released in tyk cloud

2023-06-29 07:05 UTC, mitjaziv commented
> needs merging to latest, after it's released in tyk cloud

Tyk Cloud v1.10.0 was already released.

2023-07-07 14:41 UTC, letzya commented
@dcs3spp we need to release this

2023-07-08 14:33 UTC, letzya commented
/release to release-5.1

2023-07-08 14:33 UTC, letzya commented
/release to release-5.0

2023-07-08 14:37 UTC, letzya commented
/release to release-5

2023-07-10 10:58 UTC, dcs3spp commented
/release to release-5