[5.1] Plugin docs update
TykTechnologies/tyk-docs-hugo pull request #2653
Opened 2023-06-08 08:13 UTC by titpetric

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](../CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](../CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-06-08 09:09 UTC, jeffy-mathew commented on tyk-docs/content/plugins/supported-languages/golang.md
> +follow the guide here.
do we need to link go workspace docs here https://go.dev/ref/mod#workspaces

2023-06-08 10:56 UTC, furkansenharputlu commented on tyk-docs/content/plugins/supported-languages/golang.md
> +To build compatible plugins, the gateway dependency that tyk_plugin uses
`tyk_plugin`

2023-06-08 10:57 UTC, furkansenharputlu commented on tyk-docs/content/plugins/supported-languages/golang.md
> +into `tyk` and run `git rev-parse HEAD`. To synchronize the gateway
what if we show the commands in their own line?

2023-06-08 11:21 UTC, dcs3spp requested changes
lgtm
Made minor suggestions, e.g. introduce section headings for initialising plugins 5.1+ and initialising plugin < 5.1

2023-06-08 11:21 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +1. your plugin sources (using `tyk_plugin`),
```suggestion
1. Your plugin sources (using `tyk_plugin`)
```

2023-06-08 11:21 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +2. tyk gateway source for the release (using `tyk`)
```suggestion
2. Tyk gateway source for the release (using `tyk`)
```

2023-06-08 11:21 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
>  #### Initialise plugin
```suggestion
#### Initialise plugin for Gateway 5.1+
```

2023-06-08 11:21 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +For versions before 5.1:
Create a new section for initialising plugin for gateway < 5.1

```suggestion
#### Initialise plugin for gateway < 5.1
```
 
Currently the tab shows an example sequence of commands for 3.2 etc. Do we need to add tabs for 4.3, 4.2 etc.?

2023-06-08 17:19 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +into `tyk` and run `git rev-parse HEAD`. To synchronize the gateway
I know what you mean, but unconvinced. There's some thing outside of 5.1 docs we're addressing around git commits (e.g. do we link the commits for particular versions and provide docs like the 3.2.1 below, for 4+ 5+?) so the area can be handled there. Let's do the style comment there too :)

2023-06-08 17:22 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +follow the guide here.
```suggestion
follow the guide below. To find out more about Go workspaces, visit the [official documentation](https://go.dev/ref/mod#workspaces).
```

2023-06-08 17:23 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +To build compatible plugins, the gateway dependency that tyk_plugin uses
```suggestion
To build compatible plugins, the gateway dependency that `tyk_plugin` uses
```

2023-06-08 17:38 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +For versions before 5.1:
@dcs3spp the commit links issue is known and out of scope, asked for some jira housekeeping to file and link the ticket for that

2023-06-08 17:41 UTC, titpetric commented
@dcs3spp @andyo-tyk  - 5.0 is our LTS build, do we need to point it out specifically? What version am I being encouraged to use by default, 5.1 or LTS? Should we maybe rephrase <5.1 as LTS?

2023-06-13 16:36 UTC, andyo-tyk commented
I think it's fine to refer to "Tyk version 5.1 or later" and "Prior to Tyk version 5.1"

2023-06-13 16:46 UTC, dcs3spp approved these changes
Looks good to me. Let me know once peers reviewed

2023-06-19 18:11 UTC, jeffy-mathew commented on tyk-docs/content/plugins/supported-languages/golang.md
> +1. Your plugin sources (using `tyk_plugin`)
recently we came across an issue when two plugins built with same module name were referenced in different APIs. 
shall we also add a warning to use different module name for different plugins?

2023-06-19 18:12 UTC, jeffy-mathew commented on tyk-docs/content/plugins/supported-languages/golang.md
> +For more information about go workspaces, check out the [official
duplicate? https://github.com/TykTechnologies/tyk-docs/pull/2653/files#diff-cd04863da6612d95d2230bb7db6708b118fd855623b2e082c8122f01ba881a23R41

2023-06-19 19:21 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +For more information about go workspaces, check out the [official
It's a different link, one is the docs, another is the tutorial.

2023-06-19 19:24 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +1. Your plugin sources (using `tyk_plugin`)
out of scope, can discuss in docs refinement for plugins area, or as a general errata

2023-06-23 06:29 UTC, jeffy-mathew approved these changes

2023-06-23 09:57 UTC, dcs3spp commented
/release to release-5.1

2023-06-23 10:04 UTC, merged

2023-06-23 10:06 UTC, dcs3spp commented
/release to release-5.1

2023-06-23 10:10 UTC, dcs3spp commented
/release to release-5