[DX-359] Find all menu that are more than 4 levels deep in the feature/new-nav
TykTechnologies/tyk-docs-hugo pull request #2672
Opened 2023-06-13 11:23 UTC by Keithwachira

## Related Issue (if applicable)

DX-359
## Description
We have added a GitHub action that will fail if we have menu items that are more than 4 levels deep. It will also display all this menu items in a table

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-06-13 11:41 UTC, dcs3spp requested changes
Minor change of renaming the action from Example

Apologies Keith, I am not too familiar with GoLang or the yaml package used. Is the yaml:"path" annotation a required mandatory attribute or is it optional?

In the [menu.yaml](https://github.com/TykTechnologies/tyk-docs/blob/feature/new-nav/tyk-docs/data/menu.yaml) on branch feature/new-nav the Directory menu items do not contain a path.

I am guessing that it is optional since the GoLang script does not raise an error/exception and prints the table in the GitHub check, yes?

2023-06-13 11:41 UTC, dcs3spp commented on .github/workflows/levels.yml
> +    name: Example
GH Action looks good to me Keith. Should we rename the name of the gh action job

```suggestion
    name: Check-menu-max-levels
```

2023-06-13 11:41 UTC, dcs3spp commented on scripts/levels/main.go
> +type MenuItem struct {
Apologies Keith, I am not too familiar with GoLang or the yaml package used. Is the `yaml:"path"` annotation a required mandatory attribute or is it optional? 

In the [menu.yaml](https://github.com/TykTechnologies/tyk-docs/blob/feature/new-nav/tyk-docs/data/menu.yaml) on branch feature/new-nav the Directory menu items do not contain a path.

I am guessing that it is optional since the GoLang script does not raise an error/exception and prints the table in the GitHub check, yes?

2023-06-13 11:50 UTC, yurisasuke commented on scripts/levels/main.go
> +type MenuItem struct {
it is optional. You remember that in some cases we also have Pages with empty paths.

2023-06-13 13:35 UTC, dcs3spp approved these changes
looks good to me

2023-06-13 15:23 UTC, letzya commented on scripts/levels/main.go
> +	data, err := os.ReadFile("../../tyk-docs/data/menu.yaml")
@Keithwachira should we maybe put an absolute path?

2023-06-13 15:24 UTC, letzya commented on scripts/levels/main.go
> +		log.Fatal(err)
can we add wording before the err so we have a tracing of the line that logged this issue?

2023-06-13 15:25 UTC, letzya commented on scripts/levels/main.go
> +		log.Fatal(err)
same, add a few words, i.e. "Unmarshal menu failed with this error:"

2023-06-13 15:25 UTC, letzya commented on scripts/levels/main.go
> +		log.Fatal(err)
"failed to load menu.yaml with this error:"

2023-06-13 15:25 UTC, letzya commented on scripts/levels/main.go
> +	data, err := os.ReadFile("../../tyk-docs/data/menu.yaml")
Put the file name as const var

2023-06-13 15:35 UTC, letzya commented on scripts/levels/main.go
> +type MenuItem struct {
@dcs3spp we might have a directory with a URL path

2023-06-13 15:38 UTC, letzya commented on .github/workflows/levels.yml
> +name: Check maximum nesting level is not passed
can we please rename this to something clearer like `navigation-levels.yam`

2023-06-13 15:39 UTC, letzya commented on scripts/levels/main.go
> +	max := 3
Can we use env var here so we set it in the GH action and avoid building the code?

2023-06-13 15:47 UTC, Keithwachira commented on .github/workflows/levels.yml
> +name: Check maximum nesting level is not passed
I have renamed it to navigation-levels.yml

2023-06-13 15:56 UTC, Keithwachira commented on scripts/levels/main.go
> +	data, err := os.ReadFile("../../tyk-docs/data/menu.yaml")
Is we use an absolute path I think it will be hard to test in different environments. Eg localhost ?

2023-06-13 15:58 UTC, Keithwachira commented on scripts/levels/main.go
> +	data, err := os.ReadFile("../../tyk-docs/data/menu.yaml")
Done

2023-06-13 16:07 UTC, letzya commented on .github/workflows/navigation-levels.yml
> +      - name: Check maximum level is not passed
```suggestion
      - name: Check navigation level does not exceed the defined maximum
```

2023-06-13 16:08 UTC, letzya commented on .github/workflows/navigation-levels.yml
> +          cd scripts/levels
also rename the directory name to `navigation-levels`

2023-06-13 16:09 UTC, letzya commented on scripts/levels/main.go
> +	data, err := os.ReadFile("../../tyk-docs/data/menu.yaml")
good point!!!

2023-06-13 16:13 UTC, Keithwachira commented on scripts/levels/main.go
> +	max := 3
on it

2023-06-15 04:28 UTC, Keithwachira commented on scripts/levels/main.go
> +	max := 3
Done

2023-06-15 04:33 UTC, Keithwachira commented on .github/workflows/navigation-levels.yml
> +          cd scripts/levels
Done

2023-06-15 04:38 UTC, Keithwachira commented on scripts/levels/main.go
> +		log.Fatal(err)
done

2023-06-15 04:38 UTC, Keithwachira commented on scripts/levels/main.go
> +		log.Fatal(err)
done

2023-06-16 08:56 UTC, letzya commented on .github/workflows/navigation-levels.yml
> +      - name: Check navigation level does not exceed the defined maximum
```suggestion
      - name: Check navigation level does not exceed the defined maximum of {{ $MAX_LEVELS }}
```

2023-06-16 09:00 UTC, letzya commented on scripts/navigation-levels/main.go
> +		log.Fatalf("The menuitem listed above are more than %d levels deep", *useMax)
```suggestion
		log.Fatalf("The docs pages listed above are more than %d levels deep. Please fix it", *useMax)
```

2023-06-16 18:26 UTC, letzya commented on scripts/levels/main.go
> +		log.Fatal(err)
@Keithwachira I can't see that

2023-06-16 18:26 UTC, letzya commented on scripts/levels/main.go
> +		log.Fatal(err)
@Keithwachira I can't see that

2023-06-16 18:26 UTC, letzya commented on scripts/navigation-levels/main.go
> +		log.Fatalf("The docs pages listed above are more than %d levels deep. Please fix it", *useMax)
```suggestion
		log.Fatalf("The docs pages listed above are more than %d levels deep. Please fix it", *useMax)
```
```suggestion
		log.Fatalf("the docs pages listed above are more than %d levels deep. Please fix it", *useMax)
```

2023-06-16 18:28 UTC, letzya approved these changes

2023-06-19 23:08 UTC, letzya approved these changes

2023-06-19 23:08 UTC, merged