Add subscription protos
TykTechnologies/tyk-docs-hugo pull request #2677
Opened 2023-06-13 16:51 UTC by zalbiraw

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-06-13 17:27 UTC, dcs3spp requested changes

2023-06-13 17:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/graphql-subscriptions.md
Good overview added for the new section for how to setup new subscription types via API definition. 

Maybe in the table add another column that shows what configuration (GraphQL proxy-only, UDG, GraphQL Federation) each subscription type can map to?

Add example API definitions for graphql-ws, graphql-transport-ws and SSE

2023-06-13 17:56 UTC, zalbiraw commented on tyk-docs/content/getting-started/key-concepts/graphql-subscriptions.md
> Maybe in the table add another column that shows what configuration (GraphQL proxy-only, UDG, GraphQL Federation) each subscription type can map to?

Yes, that is a great idea. I will add that.

> Add example API definitions for graphql-ws, graphql-transport-ws and SSE

We can add an example of the section but these are just the possible values to a single field. Add a whole API definition will be an overkill and maybe confusing

2023-06-15 14:56 UTC, dcs3spp approved these changes

2023-06-15 15:15 UTC, merged

2023-06-15 15:16 UTC, dcs3spp commented
/release to release-5

2023-06-15 15:21 UTC, dcs3spp commented
/release to release-4-3

2023-06-15 15:23 UTC, dcs3spp commented
/release to release-4.3

2023-06-15 15:24 UTC, dcs3spp commented
/release to release-5.1