[TT-9022] Restructured and clarified caching documentation (take 2)
TykTechnologies/tyk-docs-hugo pull request #2687
Opened 2023-06-15 14:00 UTC by andyo-tyk

Improved the caching docs, split over multiple pages for clarity

2023-06-15 15:11 UTC, dcs3spp commented
Have cloned the fork and build locally. I am getting link ref errors:

- REF_NOT_FOUND: Ref "basic-config-and-security/reduce-latency/caching/global-cache"
- REF_NOT_FOUND: Ref "basic-config-and-security/reduce-latency/caching/advanced-cache"

2023-06-15 15:13 UTC, dcs3spp reviewed
Have cloned the fork and build locally. I am getting link ref errors:

- REF_NOT_FOUND: Ref "basic-config-and-security/reduce-latency/caching/global-cache"
- REF_NOT_FOUND: Ref "basic-config-and-security/reduce-latency/caching/advanced-cache"

The paths look correct. I will try and review what I can on GHub and investigate the links issue

2023-06-16 06:22 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +"cache_options": {
This code block is missing some closing brackets

2023-06-16 06:22 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +}
Missing closing bracket

2023-06-16 06:22 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +If you are using Tyk Dashboard, you can configure these settings within the Advanced Settings section of the API Desinger. You should select **Enable upstream cache control** and deselect **Global ca
"Desinger" -> Designer

2023-06-16 08:00 UTC, dcs3spp requested changes
Good overview on key caching concepts and a clear structure with a good over section.

Maybe add a couple of sentences to overview/introduction paragraph to link into sidebar menu structure, e.g. optimisation, upstream etc.

Remove draft field in the front matter so that hugo build processes the pages in prod.

Made minor suggestions in comments

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> + - the [basic]({{< ref "basic-config-and-security/reduce-latency/caching/global-cache">}}) approach is to enable caching for all requests to an API for which it is safe to do so. This is termed "Glob
```suggestion
the [basic]({{< ref "basic-config-and-security/reduce-latency/caching/global-cache">}}) approach is to enable caching for all requests to an API for which it is safe to do so. This is termed "Global" or "[Safe Request]({{< ref "caching#safe-requests">}})" caching and is applied at the API (rather than endpoint) level. Please note that the scope is restricted to the API definition, it is not globally applied across the portfolio of APIs deployed on your Tyk Gateway.
```

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +draft: true
remove draft so hugo will see it as production page

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +draft: true
remove draft: true so hugo will see it as a production page

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +You can configure Tyk to cache only responses with certain HTTP status codes (e.g. 200 OK) for example to save caching error responses. You can configure multiple status codes that will be cached for
```suggestion
You can configure Tyk to cache only responses with certain HTTP status codes (e.g. 200 OK), for example to save caching error responses. You can configure multiple status codes that will be cached for an API, but note that this applies only to APIs that return with an HTTP status code in the response.
```

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> + - the [basic]({{< ref "basic-config-and-security/reduce-latency/caching/global-cache">}}) approach is to enable caching for all requests to an API for which it is safe to do so. This is termed "Glob
Should there be a side menu sub menu item called basic API caching or global caching?

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +The `cache_by_headers` configuration is not currently exposed in the Dashboard UI, so it must be enabled though either the raw API editor or the Dashboard API.
Is there a link to existing docs that could be included here for how to enable the configuration in raw API editor or Dashboard API?

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +For example, to create a cache entry for each response to a `POST` request to your API's `addBooks` endpoint that contains the string `my_match_pattern` in the body of the request, you would set:
general question, is a legal regex pattern in catch_key_regex equivalent to a regex in golang, yes?

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +<<<<<<<<< IMAGE >>>>>>>>>
I know that you mentioned that there was an image to add

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +## Configuring the Cache via the Dashboard
Should we extract this out into a sidebar menu also?

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +You can optionally choose to cache more selectively so that only a subset of endpoints within the API will be cached, or more granularly so that a separate entry will be created for each response mat
```suggestion
You can optionally choose to cache more selectively so that only a subset of endpoints within the API will be cached. Alternatively you can cache more granularly so that a separate entry will be created for each response matching different parameters, for example specific header or body content values.
```

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +draft: true
remove draft item so hugo sees that as a product page during build

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +This approach gives the most granular control as it will also only cache responses based on the request method. So if you only want `OPTIONS` requests to be cached, and return cache control headers o
```suggestion
This approach gives the most granular control as it will also only cache responses based on the request method. For example, it is possible to cache only `OPTIONS` request methods for a path and return associated cache control headers. Subsequently, only `OPTIONS` request methods are cached for the specified path. Other methods are ignored for the specified path.
```

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +If you are using Tyk Dashboard, you can configure these settings within the Advanced Settings section of the API Desinger. You should select **Enable upstream cache control** and deselect **Global ca
```suggestion
If you are using Tyk Dashboard, you can configure these settings within the Advanced Settings section of the API Designer. You should select **Enable upstream cache control** and deselect **Global cache**, then follow the steps for per-path caching.
```

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +If you are using Tyk Dashboard, you can configure these settings within the Advanced Settings section of the API Desinger. You should select **Enable upstream cache control** and deselect **Global ca
Should a screenshot be added here, for how to configure in the Dashboard?

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/invalidate-cache.md
> +draft: true
remove draft: true so that when do a hugo build, hugo will include the page in a production build

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
> +draft: true
remove draft: true so that when do a hugo build, hugo will include the page in a production build

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
> +For [multi-data centre]({{< ref "tyk-multi-data-centre/mdcb-components#redis">}})  deployments, the Data Planes have a locally deployed Redis, enabling them to have a localised cache close to the tra
```suggestion
For [multi-data centre]({{< ref "tyk-multi-data-centre/mdcb-components#redis">}}) deployments, the Data Planes have a locally deployed Redis. This enables them to have a localised cache close to the traffic-serving Gateways.
```

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
> +```{.copyWrapper}
Should there be an opening { and can is ```{json} now used?

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +### Caching with Tyk
I like the overview paragraph concept here since it gives a greater structure to the document. Maybe could add links to the Invalidate cache, optimise-cache and upstream-controlled-cache sections here in a final paragraph of the section? Something along the lines of:

With Tyk it is also possible to perfom the following caching operations:
- Invalid cache
- Cache optimisation
- Upstream cache configuration to control which response are cached for which request methods

2023-06-16 08:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +## Cache Terminology and Features
I like this section to explain key caching concepts

2023-07-05 13:45 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +If you are using Tyk Dashboard, you can configure these settings within the Advanced Settings section of the API Desinger. You should select **Enable upstream cache control** and deselect **Global ca
```suggestion
If you are using Tyk Dashboard, you can configure these settings within the Advanced Settings section of the API Designer. You should select **Enable upstream cache control** and deselect **Global cache** then follow the steps for per-path caching.
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +## Cache Terminology and Features
Do you mean that you would prefer this to be renamed?

Perhaps to:
```suggestion
## Key Concepts
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +draft: true
```suggestion
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +The `cache_by_headers` configuration is not currently exposed in the Dashboard UI, so it must be enabled though either the raw API editor or the Dashboard API.
No, I don't think so.

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +For example, to create a cache entry for each response to a `POST` request to your API's `addBooks` endpoint that contains the string `my_match_pattern` in the body of the request, you would set:
That's possibly a question for @davegarvey

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +      }
```suggestion
      }
    ]
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +     ]
```suggestion
     ]
   }
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +draft: true
```suggestion
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +## Configuring the Cache via the Dashboard
A separate page? If you like.

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/invalidate-cache.md
> +draft: true
```suggestion
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
> +draft: true
```suggestion
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
> +},
```suggestion
  }
}
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
> +```{.copyWrapper}
```suggestion
```{json}
{
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +draft: true
```suggestion
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +This approach gives the most granular control as it will also only cache responses based on the request method. So if you only want `OPTIONS` requests to be cached, and return cache control headers o
```suggestion
This approach gives the most granular control as it will also only cache responses based on the request method.

For example, if you only want to cache requests made with the `OPTIONS` method, you can configure the upstream cache control accordingly and return cache control headers only in those responses. With this configuration, Tyk will cache only those responses, not those for other methods for the same path.
```

2023-07-05 14:04 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +}
```suggestion
  }
}
```

2023-07-05 14:54 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +## Cache Terminology and Features
Apologies @andyo-tyk it was a general comment that I liked the new section that you added for introducing key terminology and features. Could rename to key concepts if you like?

2023-07-07 14:31 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +For example, to create a cache entry for each response to a `POST` request to your API's `addBooks` endpoint that contains the string `my_match_pattern` in the body of the request, you would set:
I think it can be any string, rather than having to be a classic regex (per the example)

2023-07-07 14:33 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +## Configuring the Cache via the Dashboard
The style I've taken here matches that elsewhere in docs, so I'd rather just get this published and further optimisation can occur later if required.

2023-07-07 14:53 UTC, andyo-tyk reviewed
Minor tweaks

2023-07-07 14:53 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +1.  **Caching middleware**: select this to enable the cache middleware
```suggestion
1. **Enable caching**: select this to enable the cache middleware
```

2023-07-07 14:53 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +**Step 1**: configure the API level caching options as follows
```suggestion
**Step 1**: configure the API level caching options from the **Advanced Options** tab in the Endpoint Designer as follows
```

2023-07-07 14:53 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +4.  **Cache all safe requests**: ensure that this is not selected
```suggestion
4.  **Cache all safe requests**: ensure that this is **not** selected
```

2023-07-07 14:53 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +<<<<<<<<< IMAGE >>>>>>>>>
```suggestion
{{< img src="/img/dashboard/endpoint-designer/cache-options.png" alt="Cache Options" >}}

```

2023-07-10 16:46 UTC, dcs3spp approved these changes

2023-07-10 16:47 UTC, dcs3spp approved these changes
lgtm

2023-07-10 17:08 UTC, dcs3spp approved these changes
lgtm

2023-07-11 12:20 UTC, andyo-tyk reviewed
Some final tweaks to wording

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +There are two approaches to configure caching for an API deployed with Tyk.
```suggestion
There are two approaches to configure caching for an API deployed with Tyk:
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +the [basic]({{< ref "basic-config-and-security/reduce-latency/caching/global-cache">}}) approach is to enable caching for all requests to an API for which it is safe to do so. This is termed "Global"
```suggestion
 - the [basic]({{< ref "basic-config-and-security/reduce-latency/caching/global-cache">}}) approach is to enable caching for all requests to an API for which it is safe to do so. This is termed "Global" or "[Safe Request]({{< ref "caching#safe-requests">}})" caching and is applied at the API (rather than endpoint) level. Please note that the scope is restricted to the API definition, it is not globally applied across the portfolio of APIs deployed on your Tyk Gateway.
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +Using the per-endpoint approach, you can selectively cache the responses to all requests, only those from specific paths or only responses with specific status codes returned by the API. You can even
```suggestion
Using the advanced per-endpoint approach, you can selectively cache the responses to all requests, only those from specific paths or only responses with specific status codes returned by the API. You can even cache dynamically based upon instruction from the upstream service received within the response.
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +Cache keys are used to differentiate cached responses, such that slight variations in the request can generate different cache keys. Depending how you configure the cache, this can enable API Clients
```suggestion
Cache keys are used to differentiate cached responses, such that slight variations in the request can generate different cache keys. This enables you to configure the cache so that different API Clients receive different cached responses when accessing the same API endpoint.
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +The value stored in the cache is a base64 encoded string of the response body. When a subsequent request matches the cache key (a cache hit), Tyk decodes the cache value and  returns this to the API
```suggestion
The value stored in the cache is a base64 encoded string of the response body. When a subsequent request matches the cache key (a **cache hit**), Tyk decodes the cache value and  returns this to the API Client that made the request.
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +By default Tyk maintains its response cache with a separate entry for each combination of API key (if authorisation is enabled), request method and request path. Dynamic caching is a more flexible me
```suggestion
By default Tyk maintains its response cache with a separate entry for each combination of API key (if authorisation is enabled), request method and request path. Dynamic caching is a more flexible method of caching API responses based on header or body content rather than just the request method and path. This allows for more granular caching control and maintainance of separate caches for different users or request properties.
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +For example, to enable the global cache only for HTTP 200 responses you would set:
```suggestion
For example, to enable global caching for all safe requests to an API, only storing HTTP 200 responses, with a 10 second TTL, you would set:
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +3.  **Cache only these status codes** to set which [response codes]({{< ref "caching#cache-response-codes">}}) to cache (remember to click **Add** after entering a response code)
```suggestion
3.  **Cache only these status codes** to set which [response codes]({{< ref "caching#cache-response-codes">}}) to cache (ensure that you click **ADD** after entering each response code so that it is added to the list)
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +For example, to cache each value in the `Unique-User-Id` header of your API response separately you would set:
```suggestion
For example, to cache each value in the custom `Unique-User-Id` header of your API response separately you would set:
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +1. **Enable caching**: select this to enable the cache middleware
```suggestion
1. **Enable caching** to enable the cache middleware
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +2.  **Cache timeout**: configure the timeout (in seconds) for cached requests
```suggestion
2.  **Cache timeout** to configure the timeout (in seconds) for cached requests
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +3.  **Cache only these status codes**: decide which HTTP status codes should be cached (remember to click **Add** after entering a code to add it to the list)
```suggestion
3.  **Cache only these status codes** is where you list which HTTP status codes should be cached (remember to click **Add** after entering a code to add it to the list)
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +4.  **Cache all safe requests**: ensure that this is **not** selected
```suggestion
4.  **Cache all safe requests** ensure that this is **not** selected
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +To set up upstream cache control, you must configure a the `cache_options` in the API definition as follows:
```suggestion
To set up upstream cache control, you must configure `cache_options` in the API definition as follows:
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
> +The upstream server also controls the duration that Tyk should cache the response (Time-To-Live or TTL).
```suggestion
The upstream server also controls the length of time that Tyk should cache the response (Time-To-Live or TTL).
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/invalidate-cache.md
> +This is achieved by calling the cache invalidate API endpoints. These are available on both the Dashboard and Gateway APIs. The URLs differ slightly, but they have the same effect. For Dashboard-mana
```suggestion
This is achieved by calling one of the dedicated cache invalidation API endpoints. There is a cache invalidation endpoint in both the Tyk Dashboard API and Tyk Gateway API; the URLs differ slightly, but they have the same effect.

For Dashboard-managed deployments, it’s recommended to call the Dashboard API version, as this will handle the delivery of the message to all Gateways in the cluster.
```

2023-07-11 12:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
> +For high-traffic systems that make heavy use of caching as well as rate limiting, it can make sense to use a separate Redis database for cache storage, at the expense of increased deployment footprin
```suggestion
For high-traffic systems that make heavy use of caching, it can make sense to use separate Redis databases for cache storage and for API keys, at the expense of increased deployment footprint.
```

2023-07-11 13:16 UTC, andyo-tyk reviewed
Final tweaks to improve readability.

2023-07-11 13:32 UTC, dcs3spp submitted a review, later dismissed
lgtm

2023-07-11 13:33 UTC, dcs3spp approved these changes
lgtm

2023-07-11 13:33 UTC, merged

2023-07-11 14:28 UTC, dcs3spp commented
/release to release-5.1

2023-07-11 14:29 UTC, dcs3spp commented
/release to release-5