[DX-369]use show parameter and path to hide red lines and add config param to hide them
TykTechnologies/tyk-docs-hugo pull request #2691
Opened 2023-06-15 15:46 UTC by Keithwachira

## Related Issue (if applicable)

## Description
We should be able to hide and show the red lines in menu items that do not have paths. I have added a value in showEmptyPages that can be used to show or hide the red lines. I also use the show value in directory and the .path value in pages menu to hide and show this red lines.

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-06-16 09:12 UTC, letzya commented on scripts/menu_generator.py
> +            if path is not None:
test for length

2023-06-16 09:39 UTC, letzya commented on scripts/menu_generator.py
> +        elif menu_category == "Tab":
also tabs can be hidden

2023-06-16 09:39 UTC, letzya requested changes
improve per comments

2023-06-16 11:35 UTC, Keithwachira commented on scripts/menu_generator.py
> +            if path is not None:
Done

2023-06-16 11:52 UTC, Keithwachira commented on scripts/menu_generator.py
> +        elif menu_category == "Tab":
Done

2023-06-22 16:08 UTC, dcs3spp approved these changes
PR looks good to me Keith

2023-06-29 09:52 UTC, merged