[DX-403] Synchroniser feature with MDCB - Awaiting Terminology Confirmation
TykTechnologies/tyk-docs-hugo pull request #2750
Opened 2023-06-21 12:53 UTC by caroltyk

## Related Issue (if applicable)

Publish related information to public docs:

https://tyktech.atlassian.net/wiki/spaces/EN/pages/1789788217/MDCB+Synchroniser?focusedCommentId=2093678711

https://tyktech.atlassian.net/wiki/spaces/SA/pages/2086535196/Enabling+MDCB+Synchronizer+for+Hybrid+Customers

[Preview](https://deploy-preview-2750--tyk-docs.netlify.app/docs/nightly/planning-for-production/ensure-high-availability/synchroniser)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)
[Preview](https://deploy-preview-2750--tyk-docs.netlify.app/docs/nightly/planning-for-production/ensure-high-availability/synchroniser)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-06-22 11:55 UTC, letzya commented
I'll review the terminology here

2023-06-22 12:02 UTC, dcs3spp requested changes
PR is looking good and I like the use of animated gifs.

I am not sure about the [terminology usage](https://tyktech.slack.com/archives/C51P42LLT/p1687358614194319) regarding using data plane/control plane, worker gateway and management layer etc. 

I have reviewed and made some suggestions/comments.

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +In order to process API requests successfully the worker Gateways need resources such as API keys, certificates, and OAuth clients.
```suggestion
In order to process API requests the worker Gateways need resources such as API keys, certificates, and OAuth clients. To ensure high availability these resources need to be synchronised between worker Gateways.
```

Is there an existing image that we can add here (or link), to accompany this paragraph to illustrate the concept of controller gateway publishing/subscribing events to worker gateways for resource synchronisation between redis storage?

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Tyk Gateway v4.1 introduces an improved synchroniser functionality within Multi Data Centre Bridge (MDCB) v2.0.3. Prior to this release, the API keys, certificates and OAuth clients required by worke
```suggestion
Prior to Tyk Gateway v4.1, the API keys, certificates and OAuth clients required by worker Gateways were synchronised from the controller Gateway on-demand. With Gateway v4.1 and MDCB v2.0.3 we introduced proactive synchronisation of these resources to the worker Gateways when they start up.
````

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +This change improves resilience in case the MDCB link or controller Gateway is unavailable, because the worker Gateways can continue to operate independently using the resources stored locally. There
```suggestion
This change improves resilience when the MDCB link or controller Gateway is unavailable. This is because the worker Gateways can continue to operate independently using the resources stored locally. There is also a performance improvement, since worker Gateways do not have to make network requests to retrieve resources from the controller Gateway when an API is first called.
```

Does startup time increase as a result of synchronising when workers first startup?

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +### How does worker Gateways get resources from MDCB control plane
```suggestion
### How does worker Gateways get resources from MDCB control plane?
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Every time that a key is updated or removed the management layer emits a signal to all the cluster gateways to update the key accordingly.
Not a review comment but a question out of interest. Is it the case that worker gateways subscribe to synchronisation events published by the Controller Gateway (publish/subscribe or pub/sub model)? If should we use publish / subscribe terms instead of / with signals?

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +If Synchroniser is disabled, the resources were pulled by the worker Gateways on-demand and not in advance. It means that first it checks if the resource lives in the local redis and if it doesn’t ex
If this is configurable, should we add a link to the corresponding configuration parameter for this here too in addition to the section below?

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +- In a situation where MDCB or the management redis is down or having issues then the worker gateway would be affected as well, which is not desired.
```suggestion
This introduces a single point of failure. When the MDCB or controller Gateway fails then the worker Gateways are also affected.
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +{{< img src="/img/mdcb/synchroniser-after.gif" alt="Without Synchroniser" width="1000" >}}
I like the idea of using the animated gifs :) 

Double checking if the flow is correct for synchroniser-after.gif (on-demand synchronisation). Should it be:

1. API request made
2. Worker Gateway -> Management Layer
3. Management Layer -> Worker Gateway response
4. Worker Data Centre -> Client

Shouldn't this image show that the API Client does not receive a response since this method of synchronisation introduces a single point of failure with the management layer?

Should we add a label for the requester as API Client?

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +If Synchroniser is enabled, API keys, certificates and OAuth clients are synchronised and stored in the local Redis server in advance, and since dashboard v4.1.0 a signal is emitted when when one of
If this is configurable should we link to the configuration parameter in the docs here too, inclusive of the section below?

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +- Local Redis sizing: if you have a lot of keys / resources to be synchronised, please review sizing of the local redis
```suggestion
- Size of local Redis storage: If there are a lot of keys / resources to be synchronised this will increase the size of local Redis storage.
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +- Data residency: Groups will be ignored when synchronizing- all keys (and oauth clients etc) will be propagated to all Redis instances, this might matter for customers who have a single control plan
```suggestion
- Data residency: Groups will be ignored when synchronising resources. All keys and oauth-clients etc. will be propagated to all Redis instances in the worker Gateways. This should be considered for those customers who have a single control plane but multiple clusters of worker Gateways connected. In this scenario all Redis instances in the Worker Gateways will receive all the keys. This has implications if you have data residency requirements.
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Synchroniser feature is disabled by default. To enable it, please configure both the worker Gateways and MDCB control plane accordingly.
```suggestion
The synchroniser feature is disabled by default. To enable it, please configure both the worker Gateways and MDCB control plane accordingly.
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +`"slave_options":{ "synchroniser_enabled":true }`
Not a review comment but a question. Should we matchup terms with config parameters for new future features? For example should we have config option of `worker_gateway_options` to match the terminology in this document? Or, replace the term worker Gateway with slave Gateway?

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Also, if you are running a cluster of Gateways, you must have a GroupID set in order for the Synchronizer to work properly, otherwise keys will not propagate.
```suggestion
If you are running a cluster of Gateways, you must have a _GroupID_ configured for synchronisation to work properly and propagate keys.
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +**Worker Gateway configuration**
```suggestion
**1. Worker Gateway configuration**
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +**MDCB Control Plane configuration**
```suggestion
**2. MDCB Control Plane configuration**
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Then, configure MDCB Control Plane. The most simple configuration to enable this feature via MDCB config file looks like:
```suggestion
Configure the MDCB Control Plane. The most simple configuration to enable this feature in the MDCB config file is:
```

Maybe add a link here to MDCB config section of the docs

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +All the authentication keys created in the management layer are replicated exactly the same to the worker DCs no matter which authentication method is being used: JWT, custom keys, Auth tokens, open
What is DC an abbreviation for? Maybe use etc. instead of so on

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +In an MDCB environment, the quotas and rates limits are stored locally per worker cluster, it means that they are not synchronised with others worker clusters or the management layer.
```suggestion
In an MDCB environment, the quotas and rates limits are stored locally per worker cluster. This means that they are not synchronised with others worker clusters or the management layer.
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Please see [MDCB configuration options](https://tyk.io/docs/tyk-multi-data-centre/mdcb-configuration-options/#sync_worker_config) for reference
```suggestion
Please see [MDCB configuration options](https://tyk.io/docs/tyk-multi-data-centre/mdcb-configuration-options/#sync_worker_config) for reference.
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +If API keys were used and hash key is disabled, please also set these additional configurations on following components:
```suggestion
If API keys were used and hash key is disabled, please also set these additional configurations for the following components:
```

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Please contact us if you want to enable Synchroniser for your Tyk Cloud deployment.
Should we add a link to contact us page?

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +A: You could check the MDCB log message to know about when synchronisation started and finished:
Should we add a description for how to check MDCB log messages?

2023-06-22 12:02 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +A: Synchronisation will be triggered once the TTL of worker Gateway expired. Default is 3 minutes. TTL value can be set via [sync_worker_config.group_key_ttl]({{< ref "/tyk-multi-data-centre/mdcb-con
```suggestion
A: Synchronisation will be triggered once the Time To Live (TTL) of a worker Gateway has expired. The default expiry duration is 3 minutes. The Time To Live (TTL) value can be set via [sync_worker_config.group_key_ttl]({{< ref "/tyk-multi-data-centre/mdcb-configuration-options#sync_worker_configgroup_key_ttl" >}})
```

2023-06-29 09:28 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +In order to process API requests successfully the worker Gateways need resources such as API keys, certificates, and OAuth clients.
@sredxny could you help to check this suggestion?

2023-06-29 09:31 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +This change improves resilience in case the MDCB link or controller Gateway is unavailable, because the worker Gateways can continue to operate independently using the resources stored locally. There
@sredxny please confirm about the startup time

2023-06-29 09:36 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Every time that a key is updated or removed the management layer emits a signal to all the cluster gateways to update the key accordingly.
@sredxny could you confirm?

2023-06-29 09:38 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +A: You could check the MDCB log message to know about when synchronisation started and finished:
@sredxny Is there special steps worth mentioning here?

2023-06-29 09:55 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Please contact us if you want to enable Synchroniser for your Tyk Cloud deployment.
User would need to raise a support request, or self-service via the new `tykctl` tool. (https://tyktech.slack.com/archives/CJ0RERGV8/p1688032151004299?thread_ts=1688031567.395859&cid=CJ0RERGV8)

@letzya @Keithwachira Is configuration through `tykctl` tool ready for public use? If yes could you provide instruction specific to turning on synchroniser feature?

2023-07-03 16:08 UTC, sredxny commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +In order to process API requests successfully the worker Gateways need resources such as API keys, certificates, and OAuth clients.
nope, we do not have an image for that. We might need help from the UI team to create it

2023-07-03 16:08 UTC, sredxny commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +This change improves resilience in case the MDCB link or controller Gateway is unavailable, because the worker Gateways can continue to operate independently using the resources stored locally. There
no, the startup time is not affected. As the synchroniser works as a parallel job that start to run and MDCB/gateways are available to receive and process requests in the meantime

2023-07-03 16:08 UTC, sredxny commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Every time that a key is updated or removed the management layer emits a signal to all the cluster gateways to update the key accordingly.
ummm interesting, I think this is more like what terminology we want to use. Usually publish/subscribe is used for real-time messaging systems. In this case we aim to do something similar so I agree, but again, in the end it depends on which terminology we agree to use

2023-07-03 16:08 UTC, sredxny commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +A: You could check the MDCB log message to know about when synchronisation started and finished:
no really. It's  the same as the gateway and dashboard, and  will depend on the setup of the customer (they might print it in the terminal, a file, etc)

2023-07-06 08:08 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +In order to process API requests successfully the worker Gateways need resources such as API keys, certificates, and OAuth clients.
@dcs3spp Shall we handle this as separate PR?

2023-07-06 08:13 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Every time that a key is updated or removed the management layer emits a signal to all the cluster gateways to update the key accordingly.
@dcs3spp @sredxny To me, pull/emits denotes more a direct interaction between the management layer and cluster gateways, while pub/sub may mean there is an intermediary layer handling the topics that get published/subscribed. WDYT? Which one is a more accurate description?

2023-07-06 15:09 UTC, letzya commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Please contact us if you want to enable Synchroniser for your Tyk Cloud deployment.
no it's not

2023-07-06 18:05 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +If Synchroniser is disabled, the resources were pulled by the worker Gateways on-demand and not in advance. It means that first it checks if the resource lives in the local redis and if it doesn’t ex
```suggestion
If [Synchroniser]({{< ref "/tyk-multi-data-centre/mdcb-configuration-options#sync_worker_configenabled" >}}) is disabled, the resources were pulled by the worker Gateways on-demand and not in advance. It means that first it checks if the resource lives in the local redis and if it doesn’t exist then it tries to pull it from the management layer to store it locally.
```

2023-07-06 18:06 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +If Synchroniser is enabled, API keys, certificates and OAuth clients are synchronised and stored in the local Redis server in advance, and since dashboard v4.1.0 a signal is emitted when when one of
```suggestion
If [Synchroniser]({{< ref "/tyk-multi-data-centre/mdcb-configuration-options#sync_worker_configenabled" >}}) is enabled, API keys, certificates and OAuth clients are synchronised and stored in the local Redis server in advance, and since dashboard v4.1.0 a signal is emitted when when one of those resources is created, modified or deleted, it allows the worker DCs to respond accordingly, the transmitted information is: type of resource, action (create, update, delete), if hashed (in the case of keys), and resource Id so the changes are applied.
```

2023-07-06 18:15 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Please contact us if you want to enable Synchroniser for your Tyk Cloud deployment.
```suggestion
Please [contact us](https://support.tyk.io/hc/en-gb) if you want to enable Synchroniser for your Tyk Cloud deployment.
```

2023-07-06 18:18 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Please contact us if you want to enable Synchroniser for your Tyk Cloud deployment.
updated

2023-07-06 18:18 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +All the authentication keys created in the management layer are replicated exactly the same to the worker DCs no matter which authentication method is being used: JWT, custom keys, Auth tokens, open
```suggestion
All the authentication keys created in the management layer are replicated exactly the same to the data planes no matter which authentication method is being used: JWT, custom keys, Auth tokens, open ID, mTLS etc.
```

2023-07-06 18:22 UTC, carolwkc commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +{{< img src="/img/mdcb/synchroniser-after.gif" alt="Without Synchroniser" width="1000" >}}
I've linked the wrong gif here
```suggestion
{{< img src="/img/mdcb/synchroniser-before.gif" alt="Without Synchroniser" width="1000" >}}
```

2023-07-06 18:22 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +{{< img src="/img/mdcb/synchroniser-after.gif" alt="Without Synchroniser" width="1000" >}}
updated

2023-07-06 18:23 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +`"slave_options":{ "synchroniser_enabled":true }`
I think we cannot update the config option name due to backward compatibility reason

2023-07-06 18:27 UTC, letzya commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Please contact us if you want to enable Synchroniser for your Tyk Cloud deployment.
Are you sure about this contact endpoint?

2023-07-06 18:37 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Please contact us if you want to enable Synchroniser for your Tyk Cloud deployment.
Is it not? I got it from the cloud console

2023-07-10 16:17 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Every time that a key is updated or removed the management layer emits a signal to all the cluster gateways to update the key accordingly.
status update: waiting for diagram updates from designer

2023-07-13 18:14 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Every time that a key is updated or removed the management layer emits a signal to all the cluster gateways to update the key accordingly.
Ok, if the architecture is direct interaction (like RPC?) between management layer and cluster gateways then yep pull/emits make more sense

2023-07-17 11:37 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Every time that a key is updated or removed the management layer emits a signal to all the cluster gateways to update the key accordingly.
The gif has been updated with "data plane" and "control plane"

2023-07-17 15:30 UTC, dcs3spp approved these changes

2023-07-17 15:33 UTC, dcs3spp commented
@caroltyk Many thanks!!! PR looks good to me!!! If @sredxny and @letzya are ok with it, I'll do a merge and release

2023-07-18 09:29 UTC, caroltyk commented
> @caroltyk Many thanks!!! PR looks good to me!!! If @sredxny and @letzya are ok with it, I'll do a merge and release
> 
> Is this for release 5.1 only, or 5..1 and 5 LTS?

@dcs3spp It is existing feature that is available from Tyk 4.1, so all v5.x can be applied

2023-07-18 14:06 UTC, sredxny commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Prior to Tyk Gateway v4.1, the API keys, certificates and OAuth clients required by worker Gateways were synchronised from the controller Gateway on-demand. With Gateway v4.1 and MDCB v2.0.3 we intro
@caroltyk should we mention that it's an optional feature? and that by default it will continue working as before? (on-demand)

2023-07-18 14:06 UTC, sredxny commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +- Data residency: Groups will be ignored when synchronising resources. All keys and oauth-clients etc. will be propagated to all Redis instances in the worker Gateways. This should be considered for
what do you think about saying this like: 

_The synchronization of resources does not support the application of this feature to specific groups. Instead, all keys, oauth-clients, etc. will be propagated to all Redis instances in the worker Gateways, without any differentiation based on groups._

i think the sentence: groups will be ignored might be misunderstood?

2023-07-18 14:06 UTC, sredxny commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +FOOBAR must be unique per cluster.
basically all the gateways in the same cluster have the same group id

2023-07-18 14:42 UTC, caroltyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +Prior to Tyk Gateway v4.1, the API keys, certificates and OAuth clients required by worker Gateways were synchronised from the controller Gateway on-demand. With Gateway v4.1 and MDCB v2.0.3 we intro
```suggestion
Prior to Tyk Gateway v4.1, the API keys, certificates and OAuth clients required by worker Gateways were synchronised from the controller Gateway on-demand. With Gateway v4.1 and MDCB v2.0.3 we introduced a new configurable option that user may choose to have proactive synchronisation of these resources to the worker Gateways when they start up.
```

2023-07-18 14:44 UTC, carolwkc commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +- Data residency: Groups will be ignored when synchronising resources. All keys and oauth-clients etc. will be propagated to all Redis instances in the worker Gateways. This should be considered for
```suggestion
- Data residency: The synchronization of resources does not support the application of this feature to specific groups. Instead, all keys, oauth-clients, etc. will be propagated to all Redis instances in the worker Gateways, without any differentiation based on groups. This should be considered for those customers who have a single control plane but multiple clusters of worker Gateways connected. In this scenario all Redis instances in the Worker Gateways will receive all the keys. This has implications if you have data residency requirements.
```

2023-07-18 14:46 UTC, carolwkc commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +FOOBAR must be unique per cluster.
```suggestion
```

2023-07-18 14:53 UTC, sredxny approved these changes

2023-07-18 16:51 UTC, letzya commented
Still under review, please don't merge.

2023-07-25 13:12 UTC, letzya commented
@caroltyk any update since our last discussion?
Also this needs an update in menu.yaml

2023-08-03 09:10 UTC, letzya commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +- Size of local Redis storage: If there are a lot of keys / resources to be synchronised this will increase the size of local Redis storage. The data stored in Redis, including keys, OAuth clients, a
```suggestion
- Size of local Redis storage: If there are a lot of keys / resources to be synchronised this will increase the size of local Redis storage. The data stored in Redis, including keys, OAuth clients, and certificates, is passed to the Redis instance of each data plane. This is a characteristic of the synchronisation mechanism and occurs regardless of whether these elements are being actively used on a given data plane. Keep in mind that even if certain resources are not being utilized in a specific data plane, they are still stored and maintained in sync by the Multi Data Centre Bridge (MDCB). Therefore, if your system has a large volume of keys, OAuth clients, and certificates, this could increase the storage requirements and network traffic between your data planes. It's essential to consider these factors when designing and scaling your system.
```

2023-08-03 09:13 UTC, letzya commented on tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
> +- Data residency: The synchronization of resources does not support the application of this feature to specific groups. Instead, all keys, oauth-clients, etc. will be propagated to all Redis instance
```suggestion
- Data residency: The synchronization of resources does not support the application of this feature to specific groups. Instead, all keys, oauth-clients, etc. will be propagated to all Redis instances in the worker Gateways, without any differentiation based on groups. This should be considered for those customers who have a single control plane but multiple clusters of worker Gateways connected. In this scenario, all Redis instances in the Worker Gateways will receive all the keys. This aspect should be taken into account if you have specific data residency requirements.
```

2023-08-03 09:16 UTC, letzya requested changes
@dcs3spp Approved the content but the file needs to move to a path identical to the menu.yaml

2023-08-03 16:05 UTC, dcs3spp approved these changes
Thanks for updating the menu.yaml @caroltyk 
PR lgtm

2023-08-03 16:10 UTC, merged

2023-08-03 16:11 UTC, dcs3spp commented
/release to release-5