[TT-5866] Correcting typos, minor improvements to wording
TykTechnologies/tyk-docs-hugo pull request #2801
Opened 2023-06-30 11:37 UTC by andyo-tyk

This probably needs updating (given it references Tyk 2.7) but taking this opportunity for a simple refresh.

No technical changes, does not need peer review, can be published immediately.

Prompted by TT-5866.

2023-06-30 11:48 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +If you were to just test Tyk as a pass-through auth proxy, we can see that 4k requests per second (rps) is easily handled:
```suggestion
If you were to just test Tyk as a pass-through auth proxy, we can see that 4000 RPS (requests per second) is easily handled:
```

2023-06-30 11:49 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +This configuration has analytics recording disabled, but we are still authenticating the inbound request. As you can see, we easily handle the 4k rps mark and we can go further with more optimisation
```suggestion
This configuration has analytics recording disabled, but we are still authenticating the inbound request. As you can see, we easily handle the 4k RPS mark and we can go further with more optimisation.
```

2023-06-30 11:52 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +You may set ulimits in a container using the `--ulimit` option. See [Docker documentation]({{< ref "https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit" >}}) f
```suggestion
You may set *ulimits* in a container using the `--ulimit` option. See *Docker* documentation for detail on [setting *ulimits*]( https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit)
```

2023-06-30 11:52 UTC, letzya requested changes, later dismissed
please commit my suggestions

2023-06-30 13:15 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production.md
> +If you were to just test Tyk as a pass-through auth proxy, we can see that 4k requests per second (rps) is easily handled:
Typically, when introducing terminology, you would write it out in full and then indicate the abbreviation. Agree the abbreviation should be capitalised.
```suggestion
If you were to just test Tyk as a pass-through auth proxy, we can see that 4k requests per second (RPS) is easily handled:
```

2023-06-30 13:17 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +If you were to just test Tyk as a pass-through auth proxy, we can see that 4k requests per second (rps) is easily handled:
this is trivial information in this context, it's a lot more known and clear than `pass-through auth proxy`

2023-06-30 13:17 UTC, andyo-tyk commented
@letzya I've committed two, but the other I disagree with and have proposed a slight tweak. If you insist we can go with yours. Please advise!

2023-06-30 13:21 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production.md
> +If you were to just test Tyk as a pass-through auth proxy, we can see that 4k requests per second (rps) is easily handled:
That's incidental (though I agree) - but if we're going to use an abbreviation it's good practice to expand it to avoid ambiguity. I'm not going to die on that hill, however, so will commit your suggestion. This page needs an overhaul/update anyway.

2023-07-04 09:36 UTC, dcs3spp commented on tyk-docs/content/planning-for-production.md
> +*   From Tyk v2.3 onwards it has been possible for a Dashboard to remotely change the config of a Gateway: this will cause the Gateway's configuration file to update.
```suggestion
*   From Tyk v2.3 onwards it has been possible for a Dashboard to remotely change the config of a Gateway. This will cause the Gateway's configuration file to update.
```

2023-07-04 09:39 UTC, dcs3spp approved these changes
lgtm

2023-07-04 09:43 UTC, merged

2023-07-04 09:48 UTC, dcs3spp commented
/release to release-5

2023-07-04 09:51 UTC, dcs3spp commented
/release to release-5.1