[TT-8298] Correct typos in import.md
TykTechnologies/tyk-docs-hugo pull request #2836
Opened 2023-07-05 14:53 UTC by andyo-tyk

Replaced apiid and apiname with the correct fields (api_id and api_name); fixed a couple of typos

2023-07-05 17:43 UTC, dcs3spp approved these changes
The changes in the examples for import organisation look ok to me. For this PR before merging and release will wait until peer review has happened. I am not sure why organisation was capitalised? Once peer reviewed let me know and we can merge and release.

2023-07-06 12:53 UTC, andyo-tyk commented
> The changes in the examples for import organisation look ok to me. For this PR before merging and release will wait until peer review has happened. I am not sure why organisation was capitalised? Once peer reviewed let me know and we can merge and release.

I capitalised Organisation, because here we are referring to a Tyk Organisation - rather than the user's organisation (company). The use of a "common word" for a Tyk concept isn't ideal, but it's what's been used for years so I would rather capitalise in an attempt to flag that it has a specific meaning.

2023-07-06 15:15 UTC, letzya commented
seeing this PR reminded me that we also have a swagger with these typos https://tyk.io/docs/dashboard-admin-api/

2023-07-06 15:18 UTC, letzya commented
> Organisation, because here we are referring to a Tyk Organisati

@andyo-tyk not sure I understand what you mean here. What is User Org and what is Tyk org?

2023-07-06 15:20 UTC, letzya commented
Also - why not merge new? @andyo-tyk

2023-07-06 15:50 UTC, andyo-tyk commented
Tyk Organisation - https://tyk.io/docs/basic-config-and-security/security/dashboard/organisations/#concept-dashboard-organisations
The word "organisation" is commonly used to refer to a company, so when I said "the user's organisation (company)" that's what I meant - https://dictionary.cambridge.org/dictionary/english/organization?q=organisation

2023-07-06 17:30 UTC, jeffy-mathew approved these changes

2023-07-06 18:24 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-admin-api/import.md
> +The Organisation object is the most fundamental object in a Tyk setup, all other ownership properties hang off the relationship between an Organisation and its APIs, Policies and API Tokens.
```suggestion
The [Organisation object]({{<ref "basic-config-and-security/security/dashboard/organisations#concept-dashboard-organisations" >}}) is the most fundamental object in a Tyk setup, all other ownership properties hang off the relationship between an Organisation and its APIs, Policies and API Tokens.
```

2023-07-06 18:24 UTC, letzya requested changes
Please add the admin API swagger changes as well to avoid confusion for the users

2023-07-07 11:09 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis/tyk-dashboard-admin-api/import.md
> +The Organisation object is the most fundamental object in a Tyk setup, all other ownership properties hang off the relationship between an Organisation and its APIs, Policies and API Tokens.
Happy to accept this - but note this was just something I noticed when modifying the page elsewhere. This wasn't a full review/rewrite of the page hence I didn't go looking for all the possible improvements on this page.

2023-07-07 11:10 UTC, andyo-tyk commented
> Please add the admin API swagger changes as well to avoid confusion for the users

?

2023-07-07 11:18 UTC, letzya commented on tyk-docs/content/tyk-apis/tyk-dashboard-admin-api/import.md
> +The Organisation object is the most fundamental object in a Tyk setup, all other ownership properties hang off the relationship between an Organisation and its APIs, Policies and API Tokens.
100%

2023-07-07 11:23 UTC, letzya commented
@andyo-tyk @jeffy-mathew  I added it, please review.

2023-07-11 11:23 UTC, dcs3spp commented
@andyo-tyk @jeffy-mathew Have the changes added by @letzya being reviewed? If ok I will then merge and release

2023-07-11 13:05 UTC, andyo-tyk commented
As far as I know, yes - need @letzya to confirm if there's anything outstanding.

2023-07-11 18:01 UTC, letzya commented
approved outside this chat

2023-07-11 18:01 UTC, merged