Update quick started and self managed to reflect agreed content for quickstart on Hack Day session
TykTechnologies/tyk-docs-hugo pull request #2843
Opened 2023-07-06 14:10 UTC by dcs3spp

Update quick started and self managed to reflect agreed content for quickstart on Hack Day session

2023-07-06 14:31 UTC, joshblakeley requested changes
Small note but looks good!

2023-07-06 14:31 UTC, joshblakeley commented on tyk-docs/content/getting-started/quick-start.md
> +1. `git clone https://github.com/TykTechnologies/tyk-pro-docker-demo && cd tyk-pro-docker-demo`
Can we change to something like 
```bash
git clone https://github.com/TykTechnologies/tyk-pro-docker-demo && cd tyk-pro-docker-demo
```

As that should get us a copy to clipboard option

2023-07-06 14:31 UTC, joshblakeley commented on tyk-docs/content/getting-started/quick-start.md
> +1. `git clone https://github.com/TykTechnologies/tyk-pro-docker-demo && cd tyk-pro-docker-demo`
Applies to all commands

2023-07-06 15:26 UTC, joshblakeley commented on tyk-docs/content/getting-started/quick-start.md
> +Then navigate to [http://localhost:3000](http://localhost:3000) and input the licence key we've emailed you
Worth pointing to https://tyk.io/sign-up/ if they dont yet have their key?

2023-07-06 15:32 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start.md
> +Then navigate to [http://localhost:3000](http://localhost:3000) and input the licence key we've emailed you
@joshblakeley Something like this?

```suggestion
Then navigate to [http://localhost:3000](http://localhost:3000) and input the licence key we've emailed you. If you do not have a key then please visit [https://tyk.io/sign-up/](https://tyk.io/sign-up/)
```

2023-07-06 15:37 UTC, joshblakeley commented on tyk-docs/content/getting-started/quick-start.md
> +Then navigate to [http://localhost:3000](http://localhost:3000) and input the licence key we've emailed you
yep so that in both spots should be good

2023-07-06 15:54 UTC, joshblakeley approved these changes

2023-07-06 15:57 UTC, dcs3spp commented
/release to release-5

2023-07-06 15:59 UTC, dcs3spp commented
/release to release-5.1

2023-07-06 16:06 UTC, merged

2023-07-06 16:08 UTC, dcs3spp commented
/release to release-5

2023-07-06 16:09 UTC, dcs3spp commented
/release to release-5.1

2023-07-07 08:38 UTC, letzya commented on tyk-docs/content/getting-started/quick-start.md
> +Then navigate to [http://localhost:3000](http://localhost:3000) and input the licence key we've emailed you. If you do not have a key then please visit [https://tyk.io/sign-up/](https://tyk.io/sign-u
We don't tend to put links as-is in the docs unless it serves the purpose. Any reason for that? (usually, we use a button or a label. Check this https://github.com/search?q=repo%3ATykTechnologies%2Ftyk-docs+%22ttps%3A%2F%2Ftyk.io%2Fsign-up%22&type=code)

2023-07-07 08:51 UTC, letzya commented on tyk-docs/content/getting-started/quick-start.md
> +Then navigate to [http://localhost:3000](http://localhost:3000) and input the licence key we've emailed you. If you do not have a key then please visit [https://tyk.io/sign-up/](https://tyk.io/sign-u
Also - why not use the https://tyk.io/sign-up/#self directly?