Create tyk-helm-chart-single-dc.md
TykTechnologies/tyk-docs-hugo pull request #2863
Opened 2023-07-10 21:57 UTC by caroltyk

## Related Issue (if applicable)

## Description

## Motivation and Context

## Preview Link

## Screenshots (if appropriate)

## Types of changes

- [ ] Fixing typo (please merge to production)
- [ ] Documenting a new feature (please merge to production)
- [ ] Documentation for future release (please do not merge to production)
- [ ] Something else (please add if needs merging to production or not)

## Checklist

- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I have added a preview link.

2023-07-11 10:05 UTC, dcs3spp requested changes
@caroltyk PR looking good and giving a detailed account of deploying the self managed new helm chart. I have some minor suggestions. Maybe add some values.yaml config examples for Tyk pump charts.

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +- the Tyk Gateway, an open source Enterprise API Gateway (supporting REST, GraphQL, TCP and gRPC protocols)
```suggestion
Tyk Gateway, an open source Enterprise API Gateway (supporting REST, GraphQL, TCP and gRPC protocols)
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +By default, this chart installs following components as subcharts on a [Kubernetes](https://kubernetes.io/) cluster using the [Helm](https://helm.sh/) package manager.
```suggestion
By default, this chart installs the following components as sub-charts on a [Kubernetes](https://kubernetes.io/) cluster using the [Helm](https://helm.sh/) package manager.
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +* Kuberentes 1.19+
Add links to Kubernetes and Helm installation instructions for consistency with Redis prerequisite
https://kubernetes.io/docs/setup/
https://helm.sh/docs/intro/install/

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +* Redis should already be installed or accessible by the gateway. For Redis installation instruction, please see https://tyk.io/docs/tyk-oss/ce-helm-chart/#recommended-via-bitnami-chart.
```suggestion
* [Redis](https://tyk.io/docs/tyk-oss/ce-helm-chart/#recommended-via-bitnami-chart) should already be installed or accessible by the gateway. 
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +You can update any value in your local `values.yaml` file and use `-f [filename]` flag to override default values during installation.
Maybe add an example of using the -f [filename] flag

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +Alternatively, you can use `--set` flag to set it in Tyk installation.
Maybe add an example of using the --set flag

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +* Set redis connection details first at `.Values.global.redis`
What does it mean by setting redis connection first and mongo second? Are there links to a config doc that can be added here and maybe add an example of `.Values.global.redis` for the reader

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +### Set Redis connection details (Required)
```suggestion
### Set Redis Connection Details (Required)
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +## Uninstalling the Chart
```suggestion
## Uninstalling The Chart
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +## Installing the Chart
```suggestion
## Installing The Chart
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +If you do not already have redis installed, you may use these charts provided by Bitnami
```suggestion
If you do not already have Redis installed, you may use these charts provided by Bitnami
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +### Set Mongo or PostgresSQL connection details (Required)
```suggestion
### Set Mongo or PostgresSQL Connection Details (Required)
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +If you have already installed mongo/postgresSQL, you can set the connection details in `global.mongo` and `global.postgres` section of values file respectively.
```suggestion
If you have already installed Mongo/PostgresSQL, you can set the connection details in `global.mongo` and `global.postgres` section of values file respectively.
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +>NOTE: Please make sure you are installing mongo/postgres versions that are supported by Tyk. Please refer to Tyk docs to get list of supported versions.
```suggestion
>NOTE: Please make sure you are installing Mongo/Postgres versions that are supported by Tyk. Please refer to Tyk docs to get list of supported versions.
```

Update above suggestion of link to supported versions.

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +<!-- BEGIN import from gateway doc -->
What do the BEGIN import  and END comments mean here and below? Should they be removed?

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +2. Set `global.tls.gateway`  to true.
```suggestion
2. Set `global.tls.gateway` to true.
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +1. Create a tls secret using your cert and key pair.
```suggestion
1. Create a TLS secret using your cert and key pair.
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +NOTE: [Here is](https://tyk.io/docs/planning-for-production/database-settings/) list of supported MongoDB versions. Please make sure you are installing mongo helm chart that matches these version.
```suggestion
NOTE: [Here is](https://tyk.io/docs/planning-for-production/database-settings/) list of supported MongoDB versions. Please make sure you are installing mongo helm chart that matches these versions.
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +<!-- END import from pump doc -->
Should this be removed?

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +<!-- BEGIN import from pump doc -->
Should this be removed?

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +<!-- END import from gateway doc -->
Should this be removed?

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +This will create a PodMonitor resource for your Pump instance.
```suggestion
This will create a _PodMonitor_ resource for your Pump instance.
```

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +#### Prometheus Pump
Maybe add yaml example values files similar to SQL Pump and Mongo pump to aid readability so the reader can see example values.yaml config

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +#### Uptime Pump
Maybe add yaml example values files similar to SQL Pump and Mongo pump to aid readability so the reader can see example values.yaml config

2023-07-11 10:05 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +#### Dashboard
Maybe add yaml example values files similar to SQL Pump and Mongo pump to aid readability so the reader can see example values.yaml config

2023-07-11 11:23 UTC, caroltyk commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +>NOTE: Please make sure you are installing mongo/postgres versions that are supported by Tyk. Please refer to Tyk docs to get list of supported versions.
```suggestion
>NOTE: Please make sure you are installing Mongo/Postgres versions that are supported by Tyk. Please refer to Tyk docs to get list of [supported versions]({{< ref "tyk-dashboard/database-options" >}}).
```

2023-07-11 11:26 UTC, caroltyk commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +* Kuberentes 1.19+
Fixed

2023-07-11 13:28 UTC, caroltyk commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +<!-- END import from gateway doc -->
updated

2023-07-11 13:30 UTC, carolwkc commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +You can update any value in your local `values.yaml` file and use `-f [filename]` flag to override default values during installation.
added link to helm docs for example

2023-07-11 13:31 UTC, caroltyk commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +#### Prometheus Pump
updated

2023-07-11 13:32 UTC, caroltyk commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +#### Uptime Pump
updated

2023-07-11 13:32 UTC, caroltyk commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +#### Dashboard
updated

2023-07-13 18:07 UTC, dcs3spp approved these changes

2023-07-13 18:08 UTC, dcs3spp submitted a review, later dismissed
lgtm

2023-07-13 18:09 UTC, dcs3spp approved these changes
lgtm

2023-07-13 18:10 UTC, merged

2023-07-13 18:11 UTC, dcs3spp commented
/release to release-5.1

2023-07-13 18:18 UTC, dcs3spp commented
/release to release-5