[DX-460] Fix mongoDB version compatibility with Tyk release 5.0.0 and 5.0.1
TykTechnologies/tyk-docs-hugo pull request #2881
Opened 2023-07-12 09:41 UTC by dcs3spp

Fix MongoDB version compatibility with Tyk release 5.0.0 and 5.0.1. Thanks for reporting, Asha Parulkar

https://tyktech.slack.com/archives/C51P42LLT/p1689153190425159

[DX-460](https://tyktech.atlassian.net/browse/DX-460)

2023-07-12 10:03 UTC, caroltyk requested changes
thanks for the update

2023-07-12 10:03 UTC, caroltyk commented on tyk-docs/content/shared/mongodb-versions-include.md
> +- MongoDB 4.4.x, 5.0.2+, 6.0.x (with mongo-go driver). Tyk 5.0.0 and 5.0.1 does not support mongoDB versions 5 or 6.
```suggestion
- MongoDB 4.4.x, 5.0.x, 6.0.x (with mongo-go driver). 

Note: mongo-go driver is available from Tyk 5.0.2.
```

For MongoDB version, it's 4.4.x, 5.0.x and 6.0.x. And it is supported with mongo-go driver.

We may add a note that mongo-go driver is available only from tyk 5.0.2.

2023-07-12 12:07 UTC, dcs3spp commented
Thanks @caroltyk, I have committed the suggestion.

2023-07-12 13:03 UTC, caroltyk approved these changes
👍

2023-07-13 17:33 UTC, merged

2023-07-13 17:34 UTC, dcs3spp commented
/release to release-5

2023-07-13 17:39 UTC, dcs3spp commented
/release to release-5.1