document multi_value_headers field
TykTechnologies/tyk-docs-hugo pull request #2913
Opened 2023-07-17 23:54 UTC by sredxny

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description
As part ot TT-851 we introduced a new field for the response plugins to handle the header properly. So, this PR add the documentation for that new field and explain how to use it

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-07-18 11:39 UTC, dcs3spp commented
@sredxny lgtm. Awaiting peer review

2023-07-19 12:11 UTC, caroltyk commented
@sredxny Please also update https://tyk.io/docs/plugins/supported-languages/rich-plugins/rich-plugins-data-structures/#responseobject-coprocess_response_objectproto with the new attribute, and cross link from this page. Thanks!

2023-07-19 21:24 UTC, letzya commented
@sredxny please update the PR with [labels](https://tyktech.atlassian.net/wiki/spaces/EN/pages/1888976900/The+Docs+Bible+-+A+Guide+For+The+Docs+Contributor#Label-PR) and preview etc. As explained here [the pr process ](https://tyktech.atlassian.net/wiki/spaces/EN/pages/1888976900/The+Docs+Bible+-+A+Guide+For+The+Docs+Contributor#PR-Process)

For now, setting this PR to draft, Hope that's ok

2023-07-28 01:38 UTC, sredxny commented
@letzya changed back to ready-to-review as I did the latest changes, labeled and pasted the link. Hopefully now it complies with the rules 🤞

2023-08-02 11:42 UTC, dcs3spp commented on tyk-docs/content/plugins/plugin-types/response-plugins.md
> +Starting from versions 5.0.4, 5.1.1, and 5.2, for our Go, Python and Ruby users we have introduced the `multi_value_headers` field to facilitate more flexible and efficient management of headers, par
```suggestion
Starting from versions 5.0.4 and 5.1.1+, for our Go, Python and Ruby users we have introduced the `multi_value_headers` field to facilitate more flexible and efficient management of headers, particularly for scenarios involving a single header key associated with multiple values.  The `multi_value_headers` field, similar to its predecessor, the `headers` field, is a key-value store. However, it can accommodate an array or list of string values for each key, instead of a single string value. This feature empowers you to represent multiple values for a single header key. Here's an example of how you might use `multi_value_headers`, using the Set-Cookie header which often has multiple values:
```

2023-08-02 13:52 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
> +This field is available for Go, Python and Ruby since tyk v5.0.4, 5.1.1 and 5.2.
```suggestion
This field is available for Go, Python and Ruby since tyk v5.0.4 and 5.1.1+
```

2023-08-02 14:17 UTC, letzya commented on tyk-docs/content/plugins/plugin-types/response-plugins.md
> +```
can we plese add `python` formatting?

2023-08-02 14:25 UTC, letzya commented on tyk-docs/content/plugins/plugin-types/response-plugins.md
> +In this example, Set-Cookie header has two associated values: `"sessionToken=abc123; HttpOnly; Secure"` and `"language=en-US; Secure"`.  To help you understand this further, let's see how `multi_valu
can we improve the example to show how we use it in the code? For example, the `headers` filed in the above example is part of the code `response.headers["injectedkey"] = "injectedvalue"`

![Uploading image.png…]()

2023-08-02 14:26 UTC, letzya requested changes, later dismissed
per comments

2023-08-03 08:16 UTC, dcs3spp approved these changes
@sredxny PR looks good to me. Once all approved I will merge and release

2023-08-03 13:46 UTC, dcs3spp commented
@caroltyk @letzya can you review to confirm ok and then I will merge

2023-08-03 13:52 UTC, letzya commented on tyk-docs/content/plugins/plugin-types/response-plugins.md
> +    new_header = response.multivalue_headers.add()
why is it multivalue_headers and not multi_value_headers?

2023-08-03 14:46 UTC, dcs3spp requested changes
Please replace multi_value_headers with multivalue_headers in the written text to reflect the field. name of the content

2023-08-03 15:08 UTC, dcs3spp approved these changes
thanks @sredxny for replace the `multivalue_headers` field in the written content

2023-08-03 15:10 UTC, caroltyk approved these changes

2023-08-03 15:14 UTC, dcs3spp approved these changes

2023-08-03 15:15 UTC, dcs3spp approved these changes

2023-08-03 15:16 UTC, merged

2023-08-03 15:17 UTC, dcs3spp commented
/release to release-5.1

2023-08-03 15:17 UTC, dcs3spp commented
/release to release-5