Create tyk-operator-reconciliation-troubleshooting.md
TykTechnologies/tyk-docs-hugo pull request #2918
Opened 2023-07-19 12:26 UTC by caroltyk

### For internal users - please add a Jira DX PR ticket to the subject!
[DX-493](https://tyktech.atlassian.net/browse/DX-493)
---
### Preview Link
https://deploy-preview-2918--tyk-docs.netlify.app/docs/nightly/tyk-stack/tyk-operator/tyk-operator-reconciliation-troubleshooting/

### Description

Explain "latestTransaction" - new status field for troubleshooting

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

[DX-493]: https://tyktech.atlassian.net/browse/DX-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-07-19 13:11 UTC, OldStubbsy approved these changes
Excellent!

2023-07-19 20:25 UTC, buraksekili commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation-troubleshooting.md
> +- `.status.latestTransaction.Error`: shows the message of an error if observed in the latest transaction.
ups, my mistake
```suggestion
- `.status.latestTransaction.error`: shows the message of an error if observed in the latest transaction.
```

2023-07-20 08:40 UTC, buraksekili approved these changes

2023-07-24 18:34 UTC, letzya commented
@caroltyk could you please follow the new guide and add the file to menu.yaml

2023-07-24 19:02 UTC, letzya requested changes, later dismissed

2023-07-24 19:02 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation-troubleshooting.md
> +> The [Status subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#status-subresource) in Kubernetes is a specialized endpoint that allows dev
```suggestion
> The [Status subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#status-subresource) in Kubernetes is a specialised endpoint that allows developers and operators to retrieve the real-time status of a specific Kubernetes resource. By querying this subresource, users can efficiently access essential information about a resource's current state, conditions, and other relevant details without fetching the entire resource, simplifying monitoring and aiding in prompt decision-making and issue resolution.
```

2023-07-24 19:02 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation-troubleshooting.md
> +From [Tyk Operator v0.15.0](https://github.com/TykTechnologies/tyk-operator/releases/tag/v0.15.0), we introduce a new status subresource in APIDefinition CRD, called _latestTransaction_ which holds i
```suggestion
From [Tyk Operator v0.15.0](https://github.com/TykTechnologies/tyk-operator/releases/tag/v0.15.0), we introduce a new status [subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#subresources) in APIDefinition CRD, called _latestTransaction_ which holds information about reconciliation status.
```

2023-07-24 19:02 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation-troubleshooting.md
> +```
```suggestion
```console
```

2023-07-24 19:02 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation-troubleshooting.md
> +```
```suggestion
```console
```

2023-07-24 19:02 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation-troubleshooting.md
> +```
```suggestion
```console
```

2023-07-24 19:02 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation-troubleshooting.md
> +```
```suggestion
```console
```

2023-07-24 19:02 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-reconciliation-troubleshooting.md
> +Instead of digging into Tyk Operator's logs, we can now diagnose this issue simply by looking at the `.status.latestTransaction` field. As `.status.latestTransaction.error` implies, the error is rela
```suggestion
Instead of digging into Tyk Operator's logs, we can now diagnose this issue simply by looking at the `.status.latestTransaction` field. As `.status.latestTransaction.error` implies, the error is related to *SecurityPolicy* dependency. 
```

2023-07-25 11:15 UTC, caroltyk commented
> @caroltyk could you please follow the new guide and add the file to menu.yaml

Updated menu and committed suggestions

2023-08-03 09:27 UTC, dcs3spp requested changes
@carol please check the path here ```/tyk-stack//tyk-operator/tyk-operator-reconciliation-troubleshooting``` in menu.yaml. It has double //. For new content files please ensure it exists under one of the created template folders

2023-08-03 09:27 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +          path: /tyk-stack//tyk-operator/tyk-operator-reconciliation-troubleshooting
@carol please check the path here ```/tyk-stack//tyk-operator/tyk-operator-reconciliation-troubleshooting```and for new content files please ensure it exists under one of the created template folders

2023-08-03 09:53 UTC, caroltyk commented on tyk-docs/data/menu.yaml
> +          path: /tyk-stack//tyk-operator/tyk-operator-reconciliation-troubleshooting
File location updated, please check

2023-08-04 16:47 UTC, dcs3spp approved these changes

2023-08-04 16:52 UTC, merged

2023-08-04 16:52 UTC, dcs3spp commented
/release to release-5.1