[TT-8515] Add documentation for GoPlugin ctx.GetOASDefinition
TykTechnologies/tyk-docs-hugo pull request #2933
Opened 2023-07-20 23:57 UTC by furkansenharputlu

Just copied and modified the doc for `ctx.GetDefinition` which is one heading above.

2023-07-21 13:09 UTC, andyo-tyk requested changes
Minor changes to improve clarity

2023-07-21 13:09 UTC, andyo-tyk commented on tyk-docs/content/plugins/supported-languages/golang.md
> +`ctx.GetOASDefinition` returns an OAS object, the Go data structure can be found [here](https://github.com/TykTechnologies/tyk/blob/master/apidef/oas/oas.go#L25)
```suggestion
`ctx.GetOASDefinition` returns an `OAS` object containing the Tyk OAS API definition. The Go data structure can be found [here](https://github.com/TykTechnologies/tyk/blob/master/apidef/oas/oas.go#L25)
```

2023-07-21 13:09 UTC, andyo-tyk commented on tyk-docs/content/plugins/supported-languages/golang.md
> +`ctx.GetDefinition` returns `nil` for Tyk OAS APIs and `ctx.GetOASDefinition` returns `nil` for Tyk Classic APIs.
```suggestion
`ctx.GetDefinition` returns `nil` if called from a Tyk OAS API and `ctx.GetOASDefinition` returns `nil` if called from a Tyk Classic API.
```

2023-07-21 15:02 UTC, andyo-tyk approved these changes
Great, thanks :)

2023-07-24 13:07 UTC, lghiur approved these changes

2023-07-24 16:31 UTC, dcs3spp approved these changes
lgtm

2023-09-05 09:37 UTC, merged