Tyk cloud quick start and overview improvements
TykTechnologies/tyk-docs-hugo pull request #2963
Opened 2023-07-25 19:58 UTC by SonjaChevre

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

@letzya: the new quick start for Tyk Cloud - please review
@mitjaziv: since I have was working on the doc, I made the change mentioned in https://tyktech.atlassian.net/browse/DX-527

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-07-26 09:23 UTC, dcs3spp requested changes
Hi @SonjaChevre This looks great and reads well. I have had a look through and made minor suggestions

2023-07-26 09:23 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +To beginn your Tyk Cloud journey, follow these simple steps to sign up for an account:
```suggestion
To begin your Tyk Cloud journey, follow these simple steps to sign up for an account:
```

2023-07-26 09:23 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Opt for the "Set up API platform automatically" option (You can still personalize your setup later).
```suggestion
* Opt for the "Set up API platform automatically" option (you can still personalize your setup later).
```

2023-07-26 09:23 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +## Step 2: Get started with your first API with Tyk Dashboard
Steps look good to me. For this section maybe add screenshot to accompany the steps

2023-07-26 09:23 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +This quick start guide has covered the essentials to get you up and running with Tyk Cloud. As you explore further, you might want to learn more about managing APIs in Tyk Dashboard or managing the i
Add links for managing APIs and managing infrastructure and environments

2023-07-26 14:57 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +This quick start guide has covered the essentials to get you up and running with Tyk Cloud. As you explore further, you might want to learn more about managing APIs in Tyk Dashboard or managing the i
will add links tomorrow morning and do a last check! thanks for your review.

2023-07-27 09:50 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +This quick start guide has covered the essentials to get you up and running with Tyk Cloud. As you explore further, you might want to learn more about managing APIs in Tyk Dashboard or managing the i
added all relevant links

2023-07-27 09:51 UTC, SonjaChevre commented
All good from my side, @dcs3spp please review the latest version.

2023-07-27 10:13 UTC, dcs3spp approved these changes
That's great thanks Sonja!!! Approved

2023-07-27 10:27 UTC, merged

2023-09-04 10:33 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          show: False
should have been true