Update for tyk-oss GA
TykTechnologies/tyk-docs-hugo pull request #3036
Opened 2023-08-01 14:46 UTC by caroltyk

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-01 17:05 UTC, dcs3spp requested changes
Many thanks @caroltyk for submitting the PR and including an overview in the description of changes,

Draft is looking good so far. I have reviewed the draft so far with minor suggestions. When the PR is ready check that have peer review and add label

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +* Redis should already be installed or accessible by the gateway. For Redis installation instruction, follow the [Redis installation](#set-redis-connection-details-required) guide below.
```suggestions
* Redis should already be installed or accessible by the gateway. For Redis installations instruction, follow the [Redis installation](#set-redis-connection-details-required) guide below.
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +For Redis you can use these rather excellent chart provided by [Bitnami](https://github.com/bitnami/charts/tree/main/bitnami/redis).
```suggestion
For Redis you can use these rather excellent charts provided by [Bitnami](https://github.com/bitnami/charts/tree/main/bitnami/redis).
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +but a quick start evaluation only. Use Bitnami redis or Official Redis Helm chart in any other case.
```suggestion
but a quick start evaluation only. Use Bitnami Redis or Official Redis Helm chart in any other case.
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +Another option for Redis, to get started quickly, is to use our *simple-redis* chart.
Is there a link available to the chart?

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +The Tyk Helm Chart can connect to `simple-redis` in the same namespace by default. You do not need to set redis address and password in `values.yaml`.
```suggestion
The Tyk Helm Chart can connect to `simple-redis` in the same namespace by default. You do not need to set Redis address and password in `values.yaml`.
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +#### Tyk Gateway version
```suggestion
#### Tyk Gateway Version
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +Set version of gateway at `tyk-gateway.gateway.image.tag`. You could find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio). Please check [Tyk Release notes]({{<ref
```suggestion
Set version of gateway at `tyk-gateway.gateway.image.tag`. You can find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio). Please check [Tyk Release notes]({{<ref "/release-notes">}}) carefully while upgrading or downgrading.
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
>  1. Create a tls secret using your cert and key pair.
```suggestion
1. Create a TLS secret using your cert and key pair.
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +Default service port of gateway is 8080. You can it at `global.servicePorts.gateway`.
```suggestion
Default service port of gateway is 8080. You can this at `global.servicePorts.gateway`.
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +Enabling `tyk-gateway.gateway.control.enabled` will allow you to run the [Gateway API]({{<ref "/tyk-gateway-api">}}) on a separate port, and protect it behind a firewall if needed.
```suggestion
Enabling `tyk-gateway.gateway.control.enabled` will allow you to run the [Gateway API]({{<ref "/tyk-gateway-api">}}) on a separate port and protect it behind a firewall if needed.
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +Tyk is working to provide a new set of helm charts, and will progressively roll them out at [tyk-charts](https://github.com/TykTechnologies/tyk-charts). It will provide component charts for all Tyk C
```suggestion
Tyk is working to provide a new set of Helm charts, and will progressively roll them out at [tyk-charts](https://github.com/TykTechnologies/tyk-charts). It will provide component charts for all Tyk Components, as well as umbrella charts as reference configurations for open source and Tyk Self Managed users.
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
>  To deploy Tyk OSS using the new helm chart, please use [tyk-oss](https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-oss) chart.
```suggestion
To deploy Tyk OSS using the new Helm chart, please use [tyk-oss](https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-oss) chart.
```

2023-08-01 17:05 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +tyk-oss provides the default deployment of the Tyk Open Source stack. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk Pum
```suggestion
Tyk-oss provides the default deployment of the Tyk Open Source stack. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk Pump, an analytics purger that moves the data generated by your Tyk gateways to any back-end.
```

2023-08-01 17:50 UTC, caroltyk commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +* Redis should already be installed or accessible by the gateway. For Redis installation instruction, follow the [Redis installation](#set-redis-connection-details-required) guide below.
```suggestion
* Redis should already be installed or accessible by the gateway. For Redis installations instruction, follow the [Redis installation](#set-redis-connection-details-required) guide below.
```

2023-08-01 17:52 UTC, caroltyk commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +Another option for Redis, to get started quickly, is to use our *simple-redis* chart.
```suggestion
Another option for Redis, to get started quickly, is to use our [*simple-redis*](https://artifacthub.io/packages/helm/tyk-helm/simple-redis) chart.
```

2023-08-03 08:36 UTC, buraksekili reviewed
LGTM overall, thanks! Please consider following minor suggestions

2023-08-03 08:36 UTC, buraksekili commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +This can be solved by instantiating a Persistent Volume as shared storage for the gateway instances. As each gateway is reload, they would get the API configurations from the same storage, solving th
```suggestion
This can be solved by instantiating a Persistent Volume as shared storage for the gateway instances. As each gateway is reloaded, they would get the API configurations from the same storage, solving the synchronisation issue between gateways. Also, the storage is persistent and can be designed to be not impacted by cluster failure, your API configurations can be maintained after pod restart.
```

2023-08-03 08:36 UTC, buraksekili commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +The following settings would generate 3 replicas of gateway that get Load Balanced behind the Azure Application Gateway. The gateway share the same persistent volume to store the APIs, policies, and
```suggestion
The following settings would generate 3 replicas of gateway that get Load Balanced behind the Azure Application Gateway. The gateway shares the same persistent volume to store the APIs, policies, and middleware config.
```

2023-08-03 08:36 UTC, buraksekili commented on tyk-docs/content/tyk-oss/setup-prometheus-pump.md
> +If you have Prometheus Operator enabled on the cluster, it would look for “PodMonitor” or “ServiceMonitor” resource and scrap from specified port. The only thing you would need to modify here is the
```suggestion
If you have Prometheus Operator enabled on the cluster, it would look for “PodMonitor” or “ServiceMonitor” resources and scrap from specified port. The only thing you would need to modify here is the helm release name for Prometheus Operator.
```

2023-08-03 08:49 UTC, andrei-tyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +By default, Gateway stores API configurations at /mnt/tyk-gateway/apps inside the Gateway container. There are a a few challenges:
"are a a few" (doubled "a"). 

However I would rewrite the sentence to better signify that it's a consequence of the place where the API configuration are stored. Something like "This presents a few chalenges:"

2023-08-03 08:50 UTC, andrei-tyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +- The configuration is not persistent. It got lost whenever pod restart
I think "It gets lost whenever a pod restarts" is the corect way of saying it.

2023-08-03 08:51 UTC, andrei-tyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +The same applies to Security Policies and middleware too which is stored at /mnt/tyk-gateway/policies and /mnt/tyk-gateway/middleware respectively.
The same applies to Security Policies and middleware**s** too which **are** stored at /mnt/tyk-gateway/policies and /mnt/tyk-gateway/middleware respectively.

2023-08-03 08:53 UTC, andrei-tyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +This can be solved by instantiating a Persistent Volume as shared storage for the gateway instances. As each gateway is reload, they would get the API configurations from the same storage, solving th
"to be not" is incorrect => "to not be"

 Also, the storage is persistent and can be designed **to not be** impacted by cluster failure, **therefore** your API configurations can be maintained after a pod restart.

2023-08-03 08:55 UTC, andrei-tyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +Check your Kubernetes platform what kind of persistent storage is supported. Some platform supports Dynamic Storage Provisioning so you (or the Cluster Admin) do not need to create a PersistentVolume
Check your Kubernetes platform **to see which** kind of persistent storage is supported.
You can often specify **the** type of storage through storageClassName.

2023-08-03 08:56 UTC, andrei-tyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +The following settings would generate 3 replicas of gateway that get Load Balanced behind the Azure Application Gateway. The gateway share the same persistent volume to store the APIs, policies, and
"midleware configs" as all the other elements of the enumeration are in plural form.

2023-08-03 08:58 UTC, andrei-tyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +When the files in /apps or /policies folder is updated, you have to reload your gateways to pickup the change. Operator can help you to manage reload of the cluster groups automatically after each AP
you use "files" (plural) and "pickup the change" (singular) => it would be better to either use "file" or "changes" to keep the form constant.

Operator can help you manage the reload of the cluster groups automatically after each API or policies resource update.

2023-08-03 09:00 UTC, andrei-tyk commented on tyk-docs/content/tyk-oss/setup-prometheus-pump.md
> +Also customise Prometheus Custom Metrics based on your analytics needs. We are using `tyk_http_requests_total` and `tyk_http_latency` described [here]({{<ref "/tyk-stack/tyk-pump/other-data-stores/mo
Also **you can** customise Prometheus Custom Metrics based on your analytics needs.

2023-08-03 09:02 UTC, andrei-tyk commented on tyk-docs/content/tyk-oss/setup-prometheus-pump.md
> +After some time, you can see that Prometheus is scraping from Tyk Pump successfully:
After some time, you can see that Prometheus is successfully scraping from Tyk Pump:

2023-08-03 09:13 UTC, dcs3spp requested changes
Updated with comment to move new content files in template folder structure to reflect new website. Update paths in menu.yaml to reflect new content location

2023-08-03 09:13 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +          path: /tyk-oss/setup-prometheus-pump
New content files should be placed in folder that reflects new tabs on website.
Use the correct path for new content files. 
- [Docs blog announcing. new website](https://boiler-room.tyk.io/posts/the-new-docs-website-is-out-223635)
- [New guide for PRs](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2118287411/Creating+Content+For+The+New+Tyk+Docs+Website)

2023-08-03 09:31 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +By default, Gateway stores API configurations at /mnt/tyk-gateway/apps inside the Gateway container. There are a a few challenges:
```suggestion
By default, Gateway stores API configurations at /mnt/tyk-gateway/apps inside the Gateway container. This presents a few challenges:
```

2023-08-03 09:31 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +- The configuration is not persistent. It got lost whenever pod restart
```suggestion
- The configuration is not persistent. It gets lost whenever a pod restarts
```

2023-08-03 09:32 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +The same applies to Security Policies and middleware too which is stored at /mnt/tyk-gateway/policies and /mnt/tyk-gateway/middleware respectively.
```suggestion
The same applies to Security Policies and middlewares too which are stored at /mnt/tyk-gateway/policies and /mnt/tyk-gateway/middleware respectively.
```

2023-08-03 09:33 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +This can be solved by instantiating a Persistent Volume as shared storage for the gateway instances. As each gateway is reload, they would get the API configurations from the same storage, solving th
```suggestion
This can be solved by instantiating a Persistent Volume as shared storage for the gateway instances. As each gateway is reloaded, they would get the API configurations from the same storage, solving the synchronisation issue between gateways. Also, the storage is persistent and can be designed to not be impacted by cluster failure, therefore your API configurations can be maintained after pod restart.
```

2023-08-03 09:34 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +Check your Kubernetes platform what kind of persistent storage is supported. Some platform supports Dynamic Storage Provisioning so you (or the Cluster Admin) do not need to create a PersistentVolume
```suggestion
Check your Kubernetes platform to see which kind of persistent storage is supported. Some platform supports Dynamic Storage Provisioning so you (or the Cluster Admin) do not need to create a PersistentVolume in advance. When an application requests storage through PersistentVolumeClaim, the corresponding persistent volume type would be provisioned. You can often specify the type of storage through storageClassName.
```

2023-08-03 09:34 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +The following settings would generate 3 replicas of gateway that get Load Balanced behind the Azure Application Gateway. The gateway share the same persistent volume to store the APIs, policies, and
```suggestion
The following settings would generate 3 replicas of gateway that get Load Balanced behind the Azure Application Gateway. The gateway shares the same persistent volume to store the APIs, policies, and middleware configs.
```

2023-08-03 09:35 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +When the files in /apps or /policies folder is updated, you have to reload your gateways to pickup the change. Operator can help you to manage reload of the cluster groups automatically after each AP
```suggestion
When the files in /apps or /policies folder is updated, you have to reload your gateways to pickup the changes. Operator can help you to manage the reload of the cluster groups automatically after each API or policies resource update.
```

2023-08-03 09:35 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-prometheus-pump.md
> +Also customise Prometheus Custom Metrics based on your analytics needs. We are using `tyk_http_requests_total` and `tyk_http_latency` described [here]({{<ref "/tyk-stack/tyk-pump/other-data-stores/mo
```suggestion
Also you can customise Prometheus Custom Metrics based on your analytics needs. We are using `tyk_http_requests_total` and `tyk_http_latency` described [here]({{<ref "/tyk-stack/tyk-pump/other-data-stores/monitor-apis-prometheus">}}) for illustration:
```

2023-08-03 09:36 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-prometheus-pump.md
> +After some time, you can see that Prometheus is scraping from Tyk Pump successfully:
```suggestion
After some time, you can see that Prometheus is successfully scraping from Tyk Pump:
```

2023-08-03 09:39 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +The following settings would generate 3 replicas of gateway that get Load Balanced behind the Azure Application Gateway. The gateway share the same persistent volume to store the APIs, policies, and
updated

2023-08-03 09:39 UTC, caroltyk commented on tyk-docs/content/tyk-oss/setup-multiple-gateways.md
> +This can be solved by instantiating a Persistent Volume as shared storage for the gateway instances. As each gateway is reload, they would get the API configurations from the same storage, solving th
updated

2023-08-03 12:04 UTC, caroltyk commented on tyk-docs/data/menu.yaml
> +          path: /tyk-oss/setup-prometheus-pump
Updated

2023-08-03 20:01 UTC, letzya commented
GA might not be clear to everyone

2023-08-04 13:07 UTC, dcs3spp approved these changes

2023-08-04 13:08 UTC, merged

2023-08-04 13:09 UTC, dcs3spp commented
/release to release-5.1