Add missing Tyk Pump configs to docs
TykTechnologies/tyk-docs-hugo pull request #3038
Opened 2023-08-01 17:42 UTC by n2linux

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-09-07 15:46 UTC, letzya commented
@n2linux is this PR close to ready? if yes, since there are new pages they need to be in another location but we, the DX team, will do it for you. Please let us know

2023-11-01 19:32 UTC, letzya commented
@n2linux Hi, looks like an important PR, could you maybe get it reviewed so we can release it?

2023-11-01 21:22 UTC, letzya commented on tyk-docs/content/tyk-configuration-reference/tyk-pump-configuration/elasticsearch.md
> +```
```suggestion
```bash
```

2023-11-10 13:15 UTC, dcs3spp commented
@n2linux Could you get this peer reviewed and then we can merge and release

2023-11-10 14:21 UTC, n2linux commented
🧉 @tbuchaillot and/or @matiasinsaurralde Could y'all review this and make sure these pump docs make sense so they can get merged? 🙏

2023-11-10 14:43 UTC, mativm02 requested changes
I suggested a small change, anyways it looks good 👍

2023-11-10 14:43 UTC, mativm02 commented on tyk-docs/content/tyk-configuration-reference/tyk-pump-configuration/elasticsearch.md
> +```
Close this JSON

2023-11-13 17:59 UTC, dcs3spp commented
Hi @n2linux, I have moved content files in the PR to tyk-docs/content/product-stack/tyk-pump/advanced-configurations/configure-data-sinks/ for new website. Will double check tomorrow, but I think we are close to merging and releasing this 👍

2023-11-14 12:28 UTC, merged

2023-11-14 12:28 UTC, dcs3spp commented
/release to release-5.2