Update for tyk-mdcb-data-plane GA
TykTechnologies/tyk-docs-hugo pull request #3052
Opened 2023-08-03 08:13 UTC by caroltyk

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-03 09:11 UTC, andrei-tyk approved these changes

2023-08-03 10:14 UTC, buraksekili approved these changes

2023-08-04 08:41 UTC, buraksekili commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +Tyk-mdcb-data-plane provides the default deployment of a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users. It will deploy the data plane components that remotely connect to a MDCB control
`Tyk-mdcb-data-plane` this part looks a bit unformatted in the preview. Should we quote it?

2023-08-04 08:42 UTC, buraksekili commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
>  * Kuberentes 1.19+
```suggestion
* Kubernetes 1.19+
```

2023-08-04 08:42 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +Tyk-mdcb-data-plane provides the default deployment of a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users. It will deploy the data plane components that remotely connect to a MDCB control
```suggestion
`tyk-mdcb-data-plane` provides the default deployment of a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users. It will deploy the data plane components that remotely connect to a MDCB control plane.
```

2023-08-04 08:44 UTC, buraksekili commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +  --set global.remoteControlPlane.enabled=true \
in mdcb-data-plane chart, `global.remoteControlPlane.enabled` is enabled by default. maybe, let's remove it - so, the first instruction to install the chart looks cleaner. What do you think?>

2023-08-04 08:47 UTC, buraksekili commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +2. Copy Key, Org ID, and Data Planes Connection String (MDCB) as global.remoteControlPlane's userApiKey, orgId, and connectionString respectively.
Should we quote it to indicate that the quoted part belongs to code piece? In the preview website, the formatting not clear for me. what do you think? If it is not important, just skip it.
```suggestion
2. Copy Key, Org ID, and Data Planes Connection String (MDCB) as `global.remoteControlPlane`'s userApiKey, orgId, and connectionString respectively.
```

2023-08-04 08:48 UTC, buraksekili commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +```bash```
Extra ``` causes incorrect formatting.

```suggestion
```bash
```

2023-08-04 08:49 UTC, buraksekili commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +    helm show values tyk-helm/tyk-mdcb-data-plane > values.yaml
```suggestion
helm show values tyk-helm/tyk-mdcb-data-plane > values.yaml
```

2023-08-04 08:50 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +  --set global.remoteControlPlane.enabled=true \
```suggestion
```

2023-08-04 08:52 UTC, buraksekili commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +  --set global.remoteControlPlane.useSSL=true \
As mentioned in https://github.com/TykTechnologies/tyk-docs/pull/3052/files#r1284155987, `useSSL` is enabled by default. Maybe we can simplify this helm command by removing default values in the command.

2023-08-04 08:53 UTC, buraksekili commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +  --set global.remoteControlPlane.sslInsecureSkipVerify=true \
As mentioned in https://github.com/TykTechnologies/tyk-docs/pull/3052/files#r1284155987, `useSSL` and `sslInsecureSkipVerify` are enabled by default. Maybe we can simplify this helm command by removing default values in the command.

2023-08-04 09:20 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +  --set global.remoteControlPlane.sslInsecureSkipVerify=true \
```suggestion
```

2023-08-04 10:00 UTC, dcs3spp requested changes
please refer to minor suggestions

2023-08-04 10:00 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +      # tls configuration for ingress
should this be uncommented?

2023-08-04 10:00 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +*Note: tyk-hybrid chart users*
Use info note shortcode here

2023-08-04 10:00 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +Please note that these provided charts must never be used in production or for anything
Maybe insert blank line here?

2023-08-04 10:00 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +      # tls configuration for ingress
should this be uncommented or removed?

2023-08-04 10:43 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +      # tls configuration for ingress
the other section is removed for clarity

2023-08-04 10:43 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +Please note that these provided charts must never be used in production or for anything
updated

2023-08-04 10:43 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +*Note: tyk-hybrid chart users*
updated

2023-08-04 10:43 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +      # tls configuration for ingress
updated

2023-08-04 11:10 UTC, dcs3spp approved these changes

2023-08-04 11:15 UTC, merged

2023-08-04 11:17 UTC, dcs3spp commented
/release to release-5.1

2023-08-04 11:22 UTC, dcs3spp commented
/release to release-5