[DX-604] Rename Menu Items for Tyk Helm Charts
TykTechnologies/tyk-docs-hugo pull request #3088
Opened 2023-08-07 12:13 UTC by dcs3spp

[DX-604](https://tyktech.atlassian.net/browse/DX-604)

Since the new website release the [new helm chart](https://tyk.io/docs/tyk-oss/ce-helm-chart-new/) deployment menu item may be too long for new website in release 5.1.

This PR suggests an alternative naming as seen in this [preview to add]()

2023-08-08 13:51 UTC, caroltyk commented
Thanks @dcs3spp . The current proposal looks good.
Could you apply the changes also to https://deploy-preview-3088--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments-deployments/hybrid-gateways/ and https://deploy-preview-3088--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments-deployments/hybrid-gateways-helm/?

2023-08-08 13:52 UTC, caroltyk requested changes
Thanks @dcs3spp . The current proposal looks good.
Could you apply the changes also to https://deploy-preview-3088--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments-deployments/hybrid-gateways/ and https://deploy-preview-3088--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments-deployments/hybrid-gateways-helm/?

2023-08-09 09:24 UTC, dcs3spp commented
> Thanks @dcs3spp . The current proposal looks good. Could you apply the changes also to https://deploy-preview-3088--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments-deployments/hybrid-gateways/ and https://deploy-preview-3088--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments-deployments/hybrid-gateways-helm/?

Thanks @caroltyk. Well spotted, yep I will create a separate PR for that.

2023-08-09 11:28 UTC, dcs3spp commented
> Thanks @dcs3spp . The current proposal looks good. Could you apply the changes also to https://deploy-preview-3088--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments-deployments/hybrid-gateways/ and https://deploy-preview-3088--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments-deployments/hybrid-gateways-helm/?

Thanks @caroltyk, well spotted. For those additional preview menu items it might be best to create a new PR. My thinking is that the deploy hybrid gateway menu item contains tutorials for both docker and helm charts. That would require refactoring in addition to renaming the menu items.

If you agree, then would it be possible to review the PR again for the original links and then I will release to release 5.1 An additional [question](https://tyktech.atlassian.net/browse/DX-604?focusedCommentId=42214) is also should release 5 be updated?

2023-08-10 19:59 UTC, caroltyk approved these changes
Thanks LGTM

2023-08-11 11:33 UTC, merged

2023-08-11 11:33 UTC, dcs3spp commented
/release to release-5.1