update link to quickstart tyk cloud
TykTechnologies/tyk-docs-hugo pull request #3091
Opened 2023-08-08 07:38 UTC by SonjaChevre

linking the "quicker" quickstart here

### Preview Link

### Description

Linking the new Tyk Cloud quickstart guide instead of the longer version.  

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-08 10:17 UTC, dcs3spp requested changes
Hi @SonjaChevre the PR is reading well!! I like the additional paragraph that promotes to customers that the Tyk Product stack is included with Tyk Cloud!

The quick start for Tyk Cloud currently refers back to this page. Should we include an additional link in this page that refers users to the getting started guide for Tyk Cloud: https://tyk.io/docs/nightly/tyk-cloud/getting-started/?

I included a suggestion in the comments

2023-08-08 10:17 UTC, dcs3spp commented on tyk-docs/content/getting-started/create-api.md
The quick start for Tyk Cloud currently refers back to this page. Should we include an additional link in this page that refers users to the getting started guide for Tyk Cloud: https://tyk.io/docs/nightly/tyk-cloud/getting-started/?

```suggestion
For an advanced step by step guide we recommend visiting our [Getting Started guide]({{< ref "/tyk-cloud/getting-started" >}}). This will explain advanced configuration steps relating to how to distribute your API across nodes, in addition to adding and testing your API.
```

2023-08-08 10:17 UTC, dcs3spp commented on tyk-docs/content/getting-started/create-api.md
> +Tyk cloud is a fully managed service that makes it easy for API teams to create, secure, publish and maintain APIs at any scale, anywhere in the world. Tyk Cloud includes everything you need to manag
I like the addition of this paragraph since it promotes to customers that Tyk Cloud includes the Tyk product stack components

2023-08-08 10:20 UTC, SonjaChevre commented on tyk-docs/content/getting-started/create-api.md
> +Tyk cloud is a fully managed service that makes it easy for API teams to create, secure, publish and maintain APIs at any scale, anywhere in the world. Tyk Cloud includes everything you need to manag
good ideas, thanks!

2023-08-08 10:35 UTC, dcs3spp approved these changes

2023-08-08 10:37 UTC, dcs3spp commented
Hi @SonjaChevre I have approved the PR. Let me know once [peer reviewed](https://tyktech.slack.com/archives/CJ0RERGV8/p1691481373548099) and I will merge and release

2023-08-09 08:13 UTC, SonjaChevre commented on tyk-docs/content/getting-started/create-api.md
> +Tyk cloud is a fully managed service that makes it easy for API teams to create, secure, publish and maintain APIs at any scale, anywhere in the world. Tyk Cloud includes everything you need to manag
```suggestion
Tyk Cloud is a fully managed service that makes it easy for API teams to create, secure, publish and maintain APIs at any scale, anywhere in the world. Tyk Cloud includes everything you need to manage your global API ecosystem: [Tyk Gateways]({{< ref "tyk-oss-gateway" >}}), [Tyk Dashboard]({{< ref "tyk-dashboard" >}}), [Tyk Developer Portal]({{< ref "tyk-developer-portal" >}}) and [Universal Data Graph]({{< ref "universal-data-graph" >}}). 
```

2023-08-09 08:25 UTC, mitjaziv approved these changes

2023-08-09 09:35 UTC, merged

2023-08-09 09:36 UTC, dcs3spp commented
/release to release-5.1

2023-08-09 09:42 UTC, dcs3spp commented
/release to release-5