[TT-9647]: Document hybrid data plane configuration for Tyk Cloud
TykTechnologies/tyk-docs-hugo pull request #3116
Opened 2023-08-10 08:43 UTC by komuw

### For internal users - please add a Jira DX PR ticket to the subject!
---
- https://tyktech.atlassian.net/browse/TT-9647

### Preview Link

### Description

- Document hybrid data plane configuration for Tyk Cloud.
  In Tyk Cloud, we recently(Ara v1.11.0)  released some changes that enables costumers to be able to quickly set up your Hybrids through the Tyk Cloud UI.
  That feature is not yet documented in https://tyk.io/docs/. This PR does that.
- There was already a section in the Tyk docs for [deploying hybrid gateways](https://tyk.io/docs/tyk-cloud/environments-deployments/hybrid-gateways/), this PR updates that page rather than create a new one.

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-10 10:41 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +
Should we add a warning here that this cannot be undone?

2023-08-10 11:39 UTC, dcs3spp requested changes
Hi @komuw Many thanks for updating the hybrid data plane configuration details.

PR looks good to me. I have made minor suggestions and made a suggestion of presenting the docker and helm config parameters in a table

Please make sure that PR is peer reviewed before we go ahead and merge

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Login to you Tyk Cloud account deployments section and click on `ADD HYBRID DATA PLANE`
```suggestion
Login to your Tyk Cloud account deployments section and click on `ADD HYBRID DATA PLANE`
```

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Fill in the details and then click `SAVE DATA PLANE CONFIG`
```suggestion
Fill in the details and then click _SAVE DATA PLANE CONFIG_
```

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Those details are;
```suggestion
Those details are:
```

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Those details are;
This might be better presented as a table with row headings _key_, _org_id_, _data_planes_connection_string (mdcb)_ to match screenshot. 

The table headings could be _Docker_ and _Helm_

The table cells would then be configuration parameter, e.g. api_key, gateway.rpc.apiKey

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +You can also click on `OPEN DETAILS`
```suggestion
You can also click on _OPEN DETAILS_
```

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +  {{< img src="/img/hybrid-gateway/tyk-cloud-hybrid-revealed-instructions.png" alt="Tyk Cloud hybrid detailed instructions" >}}
Remove space prefix

```suggestion
{{< img src="/img/hybrid-gateway/tyk-cloud-hybrid-revealed-instructions.png" alt="Tyk Cloud hybrid detailed instructions" >}}
```

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +To remove the hybrid data plane configuration, navigate to the page of the hybrid data plane you want to remove and click `OPEN DETAILS`
```suggestion
To remove the hybrid data plane configuration, navigate to the page of the hybrid data plane you want to remove and click _OPEN DETAILS_
```

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Then click on `REMOVE DATA PLANE CONFIGS`
```suggestion
Then click on _REMOVE DATA PLANE CONFIGS_
```

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +confirm the removal
```suggestion
Confirm the removal by clicking _DELETE HYBRID DATA PLANE_
```

2023-08-10 11:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +
Could insert a warning after the heading _Remove hybrid data plane configuration_ and include the sentence  _ _To remove the hybrid data plane configuration....._ within the warning

Something like this?

```suggestion
{{< warning success >}}
**Warning**

Please note the action of removing a hybrid data plane configuration cannot be undone.

To remove the hybrid data plane configuration, navigate to the page of the hybrid data plane you want to remove and click _OPEN DETAILS_

{{< /warning >}}
```

2023-08-11 07:39 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +
fixed in https://github.com/TykTechnologies/tyk-docs/pull/3116/commits/0e5d1bb7038bcd7127bf6a92f2fefe44828a4086

2023-08-11 07:50 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Those details are;
added the table in https://github.com/TykTechnologies/tyk-docs/pull/3116/commits/2fb88ce0a8eb854c38189f8c26adb5147942022b

2023-08-11 11:30 UTC, dcs3spp approved these changes

2023-08-11 11:32 UTC, dcs3spp commented
@komuw Many thanks that's great! I have approved the PR. Once PR has being peer reviewed I'll merge and release for you

2023-08-11 11:37 UTC, SonjaChevre commented
thanks @komuw for your work on this, I will have time to review it on Monday morning.

2023-08-14 06:35 UTC, SonjaChevre approved these changes
Looks good to me! can be published :) 

A side note: the page is becoming quite long - maybe we should split it in multiple parts in the future - what do you think @dcs3spp ?

Thanks @SonjaChevre  
Could split the page in future to have subsections for docker and helm charts, maybe?

2023-08-15 06:11 UTC, komuw commented
> @komuw Many thanks that's great! I have approved the PR. Once PR has being peer reviewed I'll merge and release for you

@dcs3spp PR has been peer reviewed and approved.

2023-08-15 09:36 UTC, excieve reviewed
Just a small typo :)

2023-08-15 09:36 UTC, excieve commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +This will reveal instructions that you can use to connect your hybrid data plane to TyK Cloud.
```suggestion
This will reveal instructions that you can use to connect your hybrid data plane to Tyk Cloud.
```

2023-08-15 10:42 UTC, merged

2023-08-15 10:42 UTC, dcs3spp commented
/release to release-5.1

2023-08-15 10:50 UTC, dcs3spp commented
/release to release-5