[DX-492] Added worked example for OPA Additional Permissions
TykTechnologies/tyk-docs-hugo pull request #3120
Opened 2023-08-11 09:53 UTC by rewsmith

### For internal users - please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/DX-492

---
### Preview Link

https://deploy-preview-3116--tyk-docs.netlify.app/docs/tyk-dashboard/opa-permissions-example

### Description
Following feedback from a customer that they were unable to understand how to implement an OPA rule using Additional Permissions, this change provides a worked end-to-end example.

#### Screenshots (if appropriate)

## Checklist

- [ x] I have added a **preview link** to the PR description.
- [ x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ x] Make sure you have started *your change* off *our latest `master`*.
- [ x] I **labelled** the PR

2023-08-11 18:08 UTC, dcs3spp requested changes
Hi @rewsmith many thanks for contributing the worked example for OPA permissions. 

The PR looks good to me. I have had a read through and made some minor suggestions.

Please take a look at the [New Guide](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2118287411/Creating+Content+For+The+New+Tyk+Docs+Website) for creating PR content on the new website.

For PRs that include new content files there is an additional step for CI checks to pass.

Since the new website has been released there is now a menu.yaml file that maps the menu structure. There are new fixed folders in _tyk-docs/content_ folder added for the purpose of storing fresh content. These folders are explained in the above guide and correspond to the top nav bar navigation tabs. The purpose of each tab is explained [here](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2120187942/New+Docs+Information+Architecture+and+Content+Sections)

The new content file in the PR needs to be placed in one of the new folders, maybe in _product stack -> dashboard -> troubleshooting section_ or _developer support -> frequently asked questions?_

Then it needs to be referenced in the menu.yaml file. The guide gives an example [here](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2118287411/Creating+Content+For+The+New+Tyk+Docs+Website#Adding-A-New-Page)

Once changes have been made let me know if you need any help with the menu.yaml aspect

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +Tyk's [RBAC]({{< ref "tyk-dashboard/rbac.md" >}}) includes out of the box permissions to Write, Read, and Deny access to API Definitions, but what if we want to distinguish between those users who ca
```suggestion
Tyk's [RBAC]({{< ref "tyk-dashboard/rbac.md" >}}) includes out of the box permissions to Write, Read, and Deny access to API Definitions, but what if we want to distinguish between those users who can create APIs and those users who can edit or update APIs? Essentially, we want to extend Tyk's out of the box RBAC to include more fine grained permissions that prevent an `API Editor` role from creating new APIs, but allow them to edit or update existing APIs.
```

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +In order to add the new role/permissions use the following payload.  Remember to set the `authorization` header to your Tyk Dashboard API Access Credentials secret from your user profile on the Dashb
```suggestion
In order to add the new role/permissions use the following payload.  Remember to set the `authorization` header to your Tyk Dashboard API Access Credentials secret, obtained from your user profile on the Dashboard UI
```

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +```{.copyWrapper}
```suggestion
```console
```

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +```
```suggestion
```json
```

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +In order to add the new role/permissions use the following payload.  Remember to set the `authorization` header to your Tyk Dashboard API Access Credentials secret from your user profile on the Dashb
Should we add the reminder as a note?

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +This assumes no other additional permissions already exist.  If you're adding to existing permissions you'll want to send a GET to `/api/org/permissions` first, and then add the new permission to the
Does a PUT request to `/api/org/permissions` not replace the entire additional permissions list?

Instead of fetching the list via GET and then replacing with PUT request?

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +### Add OPA Rule
```suggestion
### Add Open Policy Agent (OPA) Rule
```

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +	request_permission[_] = "ResetPassword"
Why is ResetPassword and above rules included in example for disabling API editor permission, or is that to prevent other users from gaining access via security loophole? For example, could it be:

```suggestion
deny[x] {
  input.user.user_permissions["api_editor"]
  request_permission[_] == "apis"
  request_intent == "create"
  x := "API Editors not allowed to create APIs."
}
```

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +3. Add OPA Rule
```suggestion
3. Add Open Policy Agent Rule
```

2023-08-11 18:08 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +To create the `API Editor` role with additional permissions send a PUT Request to the [Dashboard Additional Permissions API endpoint]({{< ref "tyk-dashboard-api/org/permissions.md" >}}) `/api/org/per
```suggestion
To include the `API Editor` role with additional permissions, send a PUT Request to the [Dashboard Additional Permissions API endpoint]({{< ref "tyk-dashboard-api/org/permissions.md" >}}) `/api/org/permissions`
```

2023-08-14 08:36 UTC, rewsmith commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +In order to add the new role/permissions use the following payload.  Remember to set the `authorization` header to your Tyk Dashboard API Access Credentials secret from your user profile on the Dashb
Makes sense yes, I'll make the change

2023-08-14 08:39 UTC, rewsmith commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +This assumes no other additional permissions already exist.  If you're adding to existing permissions you'll want to send a GET to `/api/org/permissions` first, and then add the new permission to the
A PUT request will replace the entire permissions list yes, and that's why I'm suggesting a GET request first such that any existing permissions can be incorporated.  Basically trying to protect against any existing permissions being overwritten/lost

2023-08-14 08:47 UTC, rewsmith commented on tyk-docs/content/tyk-dashboard/opa-permissions-example.md
> +	request_permission[_] = "ResetPassword"
ResetPassword is only included as part of an example full updated rule set and isn't part of the change itself.  I included the example complete updated rule set to hopefully make the required change clearer.  That set, if the default rule set changes in future, this example will be out of date

2023-08-14 10:33 UTC, rewsmith commented
@dcs3spp As well as accepting your changes I've moved the content file to the same directory as the other OPA files under /product-stack/tyk-dashboard/advanced-configurations/open-policy-agent, and added a corresponding entry into menu.yaml.  There's a couple of comments in the conversation to agree on, and then hopefully we're good to merge.

2023-08-15 13:58 UTC, dcs3spp commented
> https://deploy-preview-3116--tyk-docs.netlify.app/docs/tyk-dashboard/opa-permissions-example

Thanks @rewsmith Almost there, when I try and use the preview link to navigate to the example I cannot see it in the OPA examples in the menu

https://deploy-preview-3116--tyk-docs.netlify.app/docs/nightly/

2023-08-15 15:55 UTC, dcs3spp approved these changes

2023-08-15 15:56 UTC, dcs3spp commented
@rewsmith I have approved. If we could get a peer review accepted then I think we are ready to merge this

2023-08-22 20:26 UTC, kemal-sahbaz approved these changes

2023-08-25 15:16 UTC, merged

2023-08-25 15:17 UTC, dcs3spp commented
/release to release-5.1