[TT-9748] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #3121
Opened 2023-08-11 10:01 UTC by Tyk-ITS

Triggered by: titpetric

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: master

Note: Documentation bundle for the 5.2 release. Please review.

JIRA: https://tyktech.atlassian.net/browse/TT-9748

2023-08-11 16:04 UTC, dcs3spp requested changes
PR looks good using the new workflow system. Many thanks! 

I have had a read through and made some suggestions relating to the API for dashboard, dashboard-admin and gateway. I also had a look through the x-tyk-gateway file

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          required: true
Should required status be false here? The summary implies that the date range is optional.

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: resolve daily
What is the purpose of the resolution query parameter? It can only accept the value 'day'? Does it refer to the time interval that system statistics are sampled for? For example, daily, monthly, yearly.

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: entity to get stats about
```suggestion
          description: The entity for which stats should be retrieved
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/gateway-swagger.yml
> +    description: Check health check of the Gateway and loaded APIs
```suggestion
    description: Check health status of the Gateway and loaded APIs
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Location contains versioning location information. It can be one of the following:
```suggestion
Location refers where the API version is included. It can be one of the following:
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +- `header`,
```suggestion
- `header`
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +- `url-param`,
```suggestion
- `url-param`
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +- `url`.
```suggestion
- `url`
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +StripVersioningData is a boolean flag, if set to `true`, the API responses will be stripped of versioning data.
```suggestion
StripVersioningData is a boolean flag. If set to `true`, the API responses will be stripped of versioning data.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +### **VersionToID**
I think this is already in release but, if it is possible to rename, then suggest

```suggestion
### APIVersion
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +ID is the API ID for the version set in Name.
```suggestion
ID is the ID of the versioned API.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Enabled enables Service Discovery.
```suggestion
Enables Service Discovery.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +QueryEndpoint is the endpoint to call, this would usually be Consul, etcd or Eureka K/V store.
```suggestion
QueryEndpoint is the endpoint to call. This would usually be a Consul, etcd or Eureka K/V store.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +ParentDataPath is the namespace of the where to find the nested value, if `useNestedQuery` is `true`. In the above example, it would be `node.value`. You would change the `dataPath` setting to be `ho
```suggestion
ParentDataPath is the namespace of the parent path that contains the nested value, if `useNestedQuery` is `true`. In the above example you would change the `dataPath` setting to be `hostname`, since this is where the host name data resides in the JSON string. Tyk automatically assumes that `dataPath` in this case is in a string-encoded JSON object and will try to deserialize it.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +CacheTimeout is the timeout of a cache value when a new data is loaded from a discovery service.
```suggestion
CacheTimeout is the cache timeout value for when new data is loaded from a discovery service.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Setting it too low will cause Tyk to call the SD service too often, setting it too high could mean that failures are not recovered from quickly enough.
```suggestion
Setting it too low will cause Tyk to call the discovery service too often. Setting it too high could mean that failures are not recovered from quickly enough.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Deprecated: The field is deprecated, usage needs to be updated to configure caching.
Should we include a link for users to explain how they configure caching?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Cache holds cache related flags.
Maybe update with examples of cache related flags or are those detailed in the Tyk Classic API definition section below?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +TargetPath is to set a target path to append to the discovered endpoint, since many SD services only provide host and port data. It is important to be able to target a specific resource on that host.
```suggestion
TargetPath appends a target path to the discovered endpoint, since many SD services only provide host and port data. It is important to be able to target a specific resource on that host.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Certificate contains the certificate mapped to the domain.
Is this the name of a certificate pem file?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Tyk classic API definition: `certificate_pinning_disabled`.
```suggestion
Tyk classic API definition: `certificate_pinning_enabled`.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Header contains configurations for the header value auth source, it is enabled by default.
```suggestion
Header contains configurations for the header value auth source. It is enabled by default.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +### **AuthSources**
Could this be used as a configuration field within HMAC and OIDS configs, instead of repeating the field names for header, cookie etc. there?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +SegregateByClientId is a boolean flag. If set to `true, the policies will be applied to a combination of Client ID and User ID.
```suggestion
SegregateByClientId is a boolean flag. If set to `true`, the policies will be applied to a combination of Client ID and User ID.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Providers contains a list of authorised providers and their Client IDs, and matched policies.
```suggestion
Providers contains a list of authorised providers with their Client IDs and matched policies.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Default value is 0, ie if regexpMatchIndex is not provided ID is matched from index 0.
```suggestion
Default value is 0, i.e. if regexpMatchIndex is not provided ID is matched from index 0.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Driver configures which custom plugin to be used.
```suggestion
Driver configures which custom plugin should be used.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +- `otto`,
```suggestion
- `otto`
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +- `python`,
```suggestion
- `python`
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +- `lua`,
```suggestion
- `lua`
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +- `grpc`,
```suggestion
- `grpc`
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +- `goplugin`.
```suggestion
- `goplugin`
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Debug is a boolean flag, If set to `true`, this option produces log files for the CORS middleware.
```suggestion
Debug is a boolean flag. If set to `true`, this option produces log files for the CORS middleware.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +AllowedMethods holds a list of methods to allow access via.
```suggestion
AllowedMethods holds a list of allowed HTTP methods, e.g. ['GET', 'PUT, 'POST']
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +### **PrePlugin**
Not sure if it would be possible to rename this as _PreAuthenticationPlugin_ so it is consistent with `PostAuthenticationPlugin`

```suggestion
### **PreAuthenticationPlugin**
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Enabled enables Method Transform for the given path and method.
Where is the path field in TransformRequestMethod?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Enabled enables transform request/request body middleware.
Should this read:

```suggestion
Enabled enables transform request/response body middleware.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +**Field: `format` (`object`)**
Should this be of type string, based on the description, e.g. 'xml' or 'json'?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Path file path for the template.
```suggestion
Path is the file path for the template.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Body base64 encoded representation of the template.
```suggestion
Body is the base64 encoded representation of the template.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +CacheResponseCodes contains a list of valid response codes for responses that are okay to add to the cache.
```suggestion
CacheResponseCodes contains a list of valid response codes for responses that are ok to add to the cache.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +If unset or zero, the response will returned with http status 422 Unprocessable Entity.
```suggestion
If unset or zero, the response will be returned with http status 422 Unprocessable Entity.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Path is the path to js file.
```suggestion
Path is the path to the js file.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/x-tyk-gateway.md
> +Body is the js function to execute encoded in base64 format.
```suggestion
Body is the js function to execute, encoded in base64 format.
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
> +Note that if `hash_keys` is also set to `true` then the keyID will not be provided for APIs secured using basic auth. In this scenario the only search option would be to use key hash
Does this section mean that if `disable_key_actions_by_username` is set to `true` then keys cannot be retrieved for the user that is encoded in the basic auth string for the request?

If `disable_key_actions_by_username` is activated then keys can only be retrieved by keyID or key hash. However, to retrieve keys by key hash, the `hash_keys` configuration parameter must also be activated. Is my understanding correct?

_Note that if `hash_keys` is also set to `true` then the keyID will not be provided for APIs secured using basic auth. In this scenario the only search option would be to use key hash_

Should this read `In this scenario the only search option would be to use key hash` to allow for the scenario for searching only by keyIDs?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +
What are the configuration parameters for open telemetry?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +                      apiid: 5fa2db834e07444f760b7ceb314209fb
Is this a breaking change since these have been renamed? Should we use camel case?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        The id field in the definition is auto-generated by Tyk and cannot be set by the user.
Why is `apiid` not being referenced here, since it was renamed in dashboard-admin-swagger.yml. Is it also auto generated?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      summary: 'Get system usage info with license entitlements. Return history for current year and last year if no date query parameters are provided.'
```suggestion
      summary: 'Get system usage info with license entitlements for a specified date range. Return history for current and previous year if no date query parameters are provided.'
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        - name: start_day
```suggestion
        - name: start_date
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: start day
```suggestion
          description: start date
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        - name: end_day
```suggestion
        - name: end_date
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: end day
```suggestion
          description: end date
```

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        - name: entity
Currently, users can retrieve only stats for apis.  Will there be more entities pipelined as a future feature?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  /api/system/stats:
Should the endpoint require authorisation? For example, is it available to all users within the organisation or should there be restrictions based on the users role so that they can only retrieve system statistics for APIs that they have access to?

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        max_usage:
Maybe include descriptions for the usage properties

2023-08-11 16:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        license_entitlement_active:
Not sure if this is possible at this stage, but could we rename this to `active_licenses`?

2023-08-17 11:50 UTC, titpetric commented on tyk-docs/content/shared/gateway-config.md
> +
@zalbiraw I'm asuming the doc generator doesn't stomach this as it's an external definition (`otel.`)

2023-08-17 12:02 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        license_entitlement_active:
no, the time to raise it up was at implementation time in DX check, however, i think the current version is ok as:

- it semantically groups the values together,
- clearly separate of other values,
- `active_` is an unwanted prefix (naming of values)

however, consistency was missed, if we have:

- `max_active_usage`
- `max_usage`

^ `usage_<avg/min/max>(_active)?` would be consistent with license_entitlement and preferred. @jeffy-mathew  wdyt

2023-08-17 12:15 UTC, titpetric commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +                      apiid: 5fa2db834e07444f760b7ceb314209fb
It's a fix from what I remember, but we need to fix the AccessDefinition to also define `apiid` `apiname`...

https://github.com/TykTechnologies/tyk-analytics/blob/master/swagger-admin.yml#L2044C14-L2044C14

@jeffy-mathew

2023-08-17 12:22 UTC, titpetric commented on tyk-docs/assets/others/gateway-swagger.yml
> +    description: Check health check of the Gateway and loaded APIs
PR: https://github.com/TykTechnologies/tyk/pull/5430

2023-08-17 13:38 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        The id field in the definition is auto-generated by Tyk and cannot be set by the user.
The assumption is that the apiid can be set by the user, @jeffy-mathew to confirm

2023-08-17 13:38 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  /api/system/stats:
@jeffy-mathew missing docs, or missing implementation? Suggestion makes sense, the call should be behind auth

2023-08-17 13:39 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        - name: start_day
Can't change `name`, as it would require a code change.

2023-08-17 13:44 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        license_entitlement_active:
This would be a hard breaking change (UI needs to be aware of before/after, etc.) and we are a bit too late to implement something better.

2023-08-17 13:49 UTC, titpetric commented on tyk-docs/content/shared/dashboard-config.md
> +Note that if `hash_keys` is also set to `true` then the keyID will not be provided for APIs secured using basic auth. In this scenario the only search option would be to use key hash
Clarified in the ticket implementing it: https://tyktech.atlassian.net/browse/TT-9184

2023-08-17 13:51 UTC, titpetric commented on tyk-docs/content/shared/gateway-config.md
> +
@sredxny @tbuchaillot this otel.Config structure needs to be unpacked into the `config` package, to enable automated config docs generation. That requires implementing some sort of translation/conversion helper from config.OpenTelemetry into otel.Config.

2023-08-17 16:58 UTC, zalbiraw commented on tyk-docs/content/shared/gateway-config.md
> +
Yes it can't unless you guys it a dependency path. 

Here is an example. https://github.com/TykTechnologies/tyk-config-info-generator/blob/main/src/config.json#L9

2023-08-17 17:04 UTC, zalbiraw commented on tyk-docs/content/shared/gateway-config.md
> +
But even if you add that, it will look for the struct that equals with `Config` so you'd also have to change the main structs name from `OpenTelemetry` to `Config`

https://github.com/TykTechnologies/opentelemetry/blob/main/config/config.go#L3C6-L3C19

2023-08-22 08:46 UTC, jeffy-mathew commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +                      apiid: 5fa2db834e07444f760b7ceb314209fb
@dcs3spp @titpetric it's a miss from updating oas spec. 
even though this import feature is broken for a long time, we've changed this to `api_id` and `api_name` in this [PR](https://github.com/TykTechnologies/tyk-analytics/pull/3302/files)

2023-08-22 08:48 UTC, jeffy-mathew commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        The id field in the definition is auto-generated by Tyk and cannot be set by the user.
@dcs3spp `apiid`/`api_id` in the previous context was concerning policies. Here it's about the API definition and we allow users to have custom `api_id`, I assume that's why `api_id` is not referenced here.

2023-08-22 08:51 UTC, jeffy-mathew commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: resolve daily
@dcs3spp it can accept only `day` for now. we've plans to add monthly resolution later

2023-08-22 08:52 UTC, jeffy-mathew commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        - name: entity
yes, `dataplanes`, `gateways` are being added by platform squad

2023-08-22 08:57 UTC, jeffy-mathew commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  /api/system/stats:
@titpetric it's a doc miss. `/system/stats` requires authorization

2023-09-07 13:30 UTC, dcs3spp commented
Closing ready for approving docs for OTel and /system/stats

2023-09-14 17:34 UTC, dcs3spp approved these changes

2023-09-14 17:34 UTC, merged