Improved clarity for key lifetime
TykTechnologies/tyk-docs-hugo pull request #3129
Opened 2023-08-14 16:26 UTC by andyo-tyk

Improved visibility and clarity of the default value for session_lifetime and that this means an infinite lifetime (keys will not be deleted)

2023-08-15 10:29 UTC, dcs3spp requested changes
PR lgtm Andy, added minor suggestion. Once peer reviewed we can merge and release

2023-08-15 10:30 UTC, dcs3spp approved these changes

2023-08-28 06:13 UTC, lghiur approved these changes

2023-08-29 09:47 UTC, merged

2023-08-29 09:47 UTC, dcs3spp commented
/release to release-5.1

2023-08-29 09:48 UTC, dcs3spp commented
/release to release-5