Create how-to-backup-tyk-cloud-deployment.md
TykTechnologies/tyk-docs-hugo pull request #3134
Opened 2023-08-15 04:19 UTC by ashaparulkar

As per ZD 16673, customer wants to know tyk-cloud-deployment backup procedure.

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-15 10:18 UTC, dcs3spp requested changes
Hi @ashaparulkar,

Thanks for submitting the PR with FAQs relating to backing up Tyk Dashboard configurations within a Tyk Cloud deployment.

I have fixed the build errors. It was because of a future date in the content header section. I updated to UTC date.

I have pushed the change and tweaked the content to add headers and some reference links. These changes I have also pushed to the PR branch.

PR looks good to me. Have reviewed and made some minor changes.

Please also request a peer review and then I think we are near merging and releasing

2023-08-15 10:18 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +The dashboard configurations are managed by Tyk via environment variables and these will only change if you submit a [support ticket](https://support.tyk.io/hc/en-gb/articles/8671452599708-Ticket-Sub
Should we remove this sentence?

`There will be tickets like this one, as well as internal ones to track what was changed and what request brought about the change.`

2023-08-15 10:18 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +For this, Tyk Sync can be used with the appropriate command to initiate a rollback. Only APIs and Policies can be rolled back using this method. Keys are not accounted for. Additionally, a restoratio
Can Tyk Sync be used to rollback and is there a link that we can add here?

2023-09-06 07:06 UTC, SonjaChevre reviewed
hey!

sorry it has taken so much time to review, I was on holiday. 

@ashaparulkar thanks for creating this pull request! it's so great having support engineers contribute content and questions - I'm sure you get a lot of questions from users and it makes sense to answer them in the documentation.

I have added a couple of suggestions to make it easier for users to read. let me know if you have a questions on those.

Also I think it would make sense if somebody from the sre team would review. Maybe @alienor could help with that or help us find the right person? About the frequency of back-ups, ...

2023-09-06 07:06 UTC, SonjaChevre commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +title: How to Backup Tyk Dashboard Configurations Within A Tyk Cloud Deployment
"How to Backup Tyk Dashboard Configurations Within A Tyk Cloud Deployment" makes it seems like the user has to be active to set up back-up. Can we rephrase to something like "How are Tyk Dashboard backups managed in Tyk Cloud"?

2023-09-06 07:06 UTC, SonjaChevre commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +title: How to Backup Tyk Dashboard Configurations Within A Tyk Cloud Deployment
Or maybe even simpler (and enabling us to extend later to dev portal): How are backups managed in Tyk Cloud?

2023-09-06 07:06 UTC, SonjaChevre commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +
It would be great to split into two questions:

1) How are configurations of Tyk Dashboard managed?

talking about policies, keys and APIs being regularly backed up (do we have a time for this? how often we do back-ups? is this in a SLA maybe?)

2) What about custom Tyk Dashboard configuration?

(Do I understand correcly that we don't do back-ups and just rely on information in tickets for restoring?)

2023-09-06 07:06 UTC, SonjaChevre commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +The dashboard configurations are managed by Tyk via environment variables and these will only change if you submit a [support ticket](https://support.tyk.io/hc/en-gb/articles/8671452599708-Ticket-Sub
I'm also in favour of removing it

2023-09-06 07:06 UTC, SonjaChevre commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +#### It is crucial to track and audit changes made to the Tyk Dashboard configurations. How can I log and implement an audit trail for these changes? Are there specific tools or settings within Tyk G
that's not really a back-up topic - thought it is linked to custom configurations. I would rename the question like this:

"How can I track and audit changes made to Tyk Dashboard configurations"?

2023-09-06 07:06 UTC, SonjaChevre commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +If you have a self-managed Tyk instance you can enable [audit_logging]({{< ref "/tyk-dashboard/configuration#auditenabled" >}}). This tracks the actions performed by a user once they are logged into
it doesn't help the cloud users to tell them that something is not available for them in Tyk Cloud ;)
I would simply remove this sentence.

2023-09-06 07:06 UTC, SonjaChevre commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +#### In the event of a configuration error or an undesirable change, is there a built-in mechanism to rollback to a previous configuration for an API or a Policy? Please advise on the available optio
If there's a configuration error or an unwanted change, can I easily revert to a previous API or Policy configuration? What are the options or best practices for effective rollbacks?

2023-09-06 07:06 UTC, SonjaChevre commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
> +For this, Tyk Sync can be used with the appropriate command to initiate a rollback. Only APIs and Policies can be rolled back using this method. Keys are not accounted for. Additionally, a restoratio
that would be the link for Tyk Sync: https://tyk.io/docs/tyk-sync/

> For this, Tyk Sync can be used with the appropriate command to initiate a rollback. Only APIs and Policies can be rolled back using this method. Keys are not accounted for.

You can configure Tyk Sync to synchronise APIs and Policies with any version control system, like GitHub or GitLab and use it to perform roll back. Keys are not synchronised with Tyk Sync.

2023-09-19 05:25 UTC, ashaparulkar commented
@SonjaChevre , thanks for your review and suggestions.
@dcs3spp , I have corrected the PR incorporating the peer review suggestions.

2023-10-10 11:09 UTC, dcs3spp approved these changes

2023-10-10 11:13 UTC, dcs3spp commented
@ashaparulkar Many thanks for submitting changes. I have approved the PR. If @SonjaChevre also approves I'll merge and release

2023-10-11 11:26 UTC, SonjaChevre approved these changes
just a last suggestion for improvement, otherwise good for me! (therefore already approving it)

2023-10-11 11:26 UTC, SonjaChevre commented on tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
>  Tracking changes to Dashboard configurations will need to be done through submitting a [support ticket](https://support.tyk.io/hc/en-gb/articles/8671452599708-Ticket-Submission-Guide). As mentioned e
```suggestion
To track changes in Dashboard configurations, please submit a [support ticket](https://support.tyk.io/hc/en-gb/articles/8671452599708-Ticket-Submission-Guide). No configuration changes will occur without your explicit request.
```

2023-10-12 12:00 UTC, dcs3spp commented
> just a last suggestion for improvement, otherwise good for me! (therefore already approving it)

Many thanks @SonjaChevre, I have committed your suggestion for improvement and will merge and release.

2023-10-12 12:02 UTC, merged

2023-10-12 12:03 UTC, dcs3spp commented
/release to release-5.2