Asha ara mdcb
TykTechnologies/tyk-docs-hugo pull request #3148
Opened 2023-08-16 04:20 UTC by ashaparulkar

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-17 08:49 UTC, dcs3spp requested changes
Thanks @ashaparulkar,

PR looks good. Please request a peer review from member of MDCB team to confirm. Once we have peer review I think we can merge and release

2023-08-17 08:49 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/tyk-cloud-mdcb-supported-versions.md
> +This page list down the supported MDCB version for hybrid setup
```suggestion
This page lists the supported MDCB version for hybrid setup
```

2023-09-13 08:57 UTC, sredxny commented on tyk-docs/content/tyk-cloud/tyk-cloud-mdcb-supported-versions.md
> +| v3.0.0    | v3.0.0  | v1.7.5-ara |
@ashaparulkar any ide why is required `v1.7.5-ara` and not `v1.7.5`? what does this special tag contains?

2023-09-15 01:45 UTC, ashaparulkar commented on tyk-docs/content/tyk-cloud/tyk-cloud-mdcb-supported-versions.md
> +| v3.0.0    | v3.0.0  | v1.7.5-ara |
@sredxny , I just copied the supported mdcb versions from https://github.com/TykTechnologies/tyk-cloud-release-bundles/blob/main/prod/latest/home.json , do you want me modify it in this PR from v1.7.5-ara to v1.7.5.

2023-09-18 10:57 UTC, excieve commented on tyk-docs/content/tyk-cloud/tyk-cloud-mdcb-supported-versions.md
> +| v3.0.0    | v3.0.0  | v1.7.5-ara |
You can look up the versions available on the Cloud here: https://github.com/TykTechnologies/tyk-cloud-release-bundles/blob/main/prod/latest/home.json. All the items in the `bundles` list that have `deprecated: false` are available.

2023-09-18 11:02 UTC, excieve commented on tyk-docs/content/tyk-cloud/tyk-cloud-mdcb-supported-versions.md
> +| v3.0.0    | v3.0.0  | v1.7.5-ara |
```
❯ cat prod/latest/home.json | jq '.bundles[]|select(.deprecated==false)|.components'
{
  "DashboardVersion": "v5.2.0",
  "GatewayVersion": "v5.2.0",
  "MDCBVersion": "v2.4.0",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.13"
}
{
  "DashboardVersion": "v5.1.2",
  "GatewayVersion": "v5.1.2",
  "MDCBVersion": "v2.3.0",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.13"
}
{
  "DashboardVersion": "v5.1.1",
  "GatewayVersion": "v5.1.1",
  "MDCBVersion": "v2.3.0",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.13"
}
{
  "DashboardVersion": "v5.1.0",
  "GatewayVersion": "v5.1.0",
  "MDCBVersion": "v2.3.0",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v5.0.5",
  "GatewayVersion": "v5.0.5",
  "MDCBVersion": "v2.2.0",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.13"
}
{
  "DashboardVersion": "v5.0.4",
  "GatewayVersion": "v5.0.4",
  "MDCBVersion": "v2.2.0",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.12"
}
{
  "DashboardVersion": "v5.0.3",
  "GatewayVersion": "v5.0.3",
  "MDCBVersion": "v2.2.0",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v5.0.2",
  "GatewayVersion": "v5.0.2",
  "MDCBVersion": "v2.2.0",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v5.0.1",
  "GatewayVersion": "v5.0.1",
  "MDCBVersion": "v2.1.1",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v5.0.0",
  "GatewayVersion": "v5.0.0",
  "MDCBVersion": "v2.1.1",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v4.3.3",
  "GatewayVersion": "v4.3.3",
  "MDCBVersion": "v2.1.0",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v4.3.2",
  "GatewayVersion": "v4.3.2",
  "MDCBVersion": "v2.0.4",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v4.3.1",
  "GatewayVersion": "v4.3.1",
  "MDCBVersion": "v2.0.4",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v4.3.0",
  "GatewayVersion": "v4.3.0",
  "MDCBVersion": "v2.0.4",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v4.2.4",
  "GatewayVersion": "v4.2.4",
  "MDCBVersion": "v2.0.3",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v4.2.3",
  "GatewayVersion": "v4.2.2",
  "MDCBVersion": "v2.0.3",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v4.0.10",
  "GatewayVersion": "v4.0.10",
  "MDCBVersion": "v2.0.4",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v4.0.9",
  "GatewayVersion": "v4.0.9",
  "MDCBVersion": "v2.0.3",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v4.0.8",
  "GatewayVersion": "v4.0.8",
  "MDCBVersion": "v2.0.3",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.2.7"
}
{
  "DashboardVersion": "v3.2.3",
  "GatewayVersion": "v3.2.3",
  "MDCBVersion": "v1.8.1",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.0.15"
}
{
  "DashboardVersion": "v3.0.9",
  "GatewayVersion": "v3.0.9",
  "MDCBVersion": "v1.7.11",
  "MservVersion": "v0.9.9-beta.4",
  "RedisVersion": "6.0.15"
} 
```

2023-09-19 01:25 UTC, ashaparulkar commented
Thanks @excieve , @sredxny for review.
@dcs3spp , I have corrected the PR after peer review

2023-10-10 12:09 UTC, dcs3spp approved these changes

2023-10-10 12:13 UTC, dcs3spp commented
@ashaparulkar Many thanks for submitting the changes.

@sredxny or @excieve would you be able to re-review and then we can merge and release.

2023-10-10 17:50 UTC, excieve reviewed
@dcs3spp It looks like something went wrong with the merges as the original version of the change appears to be back. Could you please check it?

2023-10-11 08:13 UTC, excieve commented
> @dcs3spp It looks like something went wrong with the merges as the original version of the change appears to be back. Could you please check it?

Ignore me, it looks good to me.

2023-10-11 08:19 UTC, excieve approved these changes

2023-10-11 12:15 UTC, sredxny approved these changes
LGTM 🚀

2023-10-12 11:48 UTC, merged

2023-10-12 11:48 UTC, dcs3spp commented
/release to release-5.2