[TT-9648]: Document Tyk Cloud SSO(single sign-on)
TykTechnologies/tyk-docs-hugo pull request #3154
Opened 2023-08-17 08:55 UTC by komuw

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-18 09:39 UTC, komuw commented
Thanks to Mitja, since this documentation is basically taken from https://tyktech.atlassian.net/wiki/spaces/EN/pages/2036564149/Single+sign-on

2023-08-18 17:18 UTC, dcs3spp requested changes
PR looks good to me komu. I have made some minor suggestions and will merge and release once these have been completed and a peer review has been done

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +## What is SSO
```suggestion
## What is SSO?
```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +Single sign-on (SSO) is an authentication process which allows users to login to multiple services and applications with one ID and one set of credentials.
```suggestion
Single sign-on (SSO) is an authentication process which allows users to login to multiple services and applications with one set of credentials.

```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +To be able to configure Single sign-on authentication, an SSO entitlement needs to be enabled in the subscription plan.
```suggestion
To be able to configure Single Sign-On authentication, an SSO entitlement needs to be enabled in the subscription plan. 
```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +These credentials are stored with an identity provider(IdP). An identity provider (IdP) is a service that stores and manages digital identities. Companies can use these services to allow their employ
```suggestion
These credentials are stored with an Identity Provider(IdP). An Identity Provider (IdP) is a service that stores and manages digital identities. Companies can use these services to allow their employees or users to connect with the resources they need. 
```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +| Field name             | Explanation                                                                                                                     |
I like that you have presented this in a table @komuw instead of using a list. In the explanation column rows, could you replace `It is used` with `Used`

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +| DIscovery URL          | It is used for initialization of the authentication flow. The value can be found in your chosen IdP provider's configuration.   |
```suggestion
| Discovery URL          | Used to initialise the authentication flow. This URL can be found in your chosen IdP provider's configuration.  |
```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +| Only registered users  | It is a check-box that defines which users are allowed to use SSO. If checked, only users who are already registered in Tyk Cloud are allowed to login with SSO. Else if un-
```suggestion
| Only registered users  | A check-box that defines which users are allowed to use SSO. If checked, only users who are already registered in Tyk Cloud are allowed to login with SSO. If un-checked, new users will be added to Tyk Cloud in the _Default_ user group upon successful registration. |
```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +| Default User Group ID  | It defines the group which the new user will be added to.                                                                       |
Does this mean that new users are allocated to this group by default after registering? 

```suggestion
| Default User Group ID  | The ID of the user group that new users are allocated to by default upon registration.                                                                       |
```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +            - title: "Tyk Cloud Single sign-on(SSO)"
```suggestion
            - title: "Tyk Cloud Single Sign-On (SSO)"
```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +Once the new profile has been added, you also need to add the authentication URL & callback URL to the configuration of your chosen IdP provider.
```suggestion
As illustrated below an authentication and callback URL will be generated, once the new profile has been added. You need to add these URLs to the configuration of your chosen IdP provider.

```

Should we add explanations for what the authentication URL and callback URL are used for here? For example, the callback URL is the URL that users are redirected to after successful authentication.

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +The fields to fill and their explanation are:
The table below explains the fields that should be completed:

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +Edit the fields you would like to change and then click on the _SAVE PROFIE_ button.
```suggestion
Edit the fields you would like to change and then click on the _SAVE PROFILE_ button.
```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +On the confirmation window, confirm by clicking the _Delete profile_ button.
```suggestion
On the confirmation window, confirm by clicking the _DELETE PROFILE_ button.
```

2023-08-18 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +On the confirmation window, confirm by clicking the _Delete profile_ button.
```suggestion
On the confirmation window, confirm by clicking the _DELETE PROFILE_ button.
```

2023-08-21 07:45 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +On the confirmation window, confirm by clicking the _Delete profile_ button.
fixed in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/9d7ff0e895238e76be8f977551c66c190dff3738

2023-08-21 07:47 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +The fields to fill and their explanation are:
fixed in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/86ffc05d2871fb79c50bb4490f1e655a5df7704e

2023-08-21 07:49 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +| Field name             | Explanation                                                                                                                     |
fixed in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/e89ec3b6ba464ea2b735e4c7fd96e23be57efa8c

2023-08-21 08:34 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +The Auth URL is your custom SSO login URL whereas Callback URL is the URL that the SSO provider will callback to, after the user authenticates.
@mitjaziv is my explanation for auth & callback url clear & correct?

2023-08-21 08:34 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +Once the new profile has been added, you also need to add the authentication URL & callback URL to the configuration of your chosen IdP provider.
fixed in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/c339d7ecab0fe281e54e9f2a08485cf60e0bd8df

2023-08-21 10:55 UTC, SonjaChevre reviewed
looking really good - I like how detailed it is!
I have added a couple of notes for small improvements.

2023-08-21 10:55 UTC, SonjaChevre commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +title: "Tyk Cloud Single sign-on(SSO)"
Tyk Cloud Single Sign-On (SSO) or Tyk Cloud single sign-on (SSO)

2023-08-21 10:55 UTC, SonjaChevre commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +These credentials are stored with an Identity Provider(IdP). An Identity Provider (IdP) is a service that stores and manages digital identities. Companies can use these services to allow their employ
These credentials **are securely stored** with an Identity Provider (IdP).

2023-08-21 10:55 UTC, SonjaChevre commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +Single sign-on (SSO) is an authentication process which allows users to login to multiple services and applications with one set of credentials.
Single Sign-On (SSO) is an authentication process that empowers users to access various services and applications using a single set of credentials. This streamlines the login experience by eliminating the need to remember multiple usernames and passwords for different platforms.

2023-08-21 10:55 UTC, SonjaChevre commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +If you are interested in getting access, contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Cloud Single sign on>)
contact your account manager or reach out to our [support]

2023-08-21 10:55 UTC, SonjaChevre commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +To add a new SSO profile, login to Tyk Cloud Dashboard, navigate to the _Profile_ list and click on the _ADD PROFILE_ button.
login to Tyk Cloud
(not Tyk Cloud Dashboard, I don't think we name it like this in the public doc)

2023-08-21 21:55 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +title: "Tyk Cloud Single sign-on(SSO)"
fixed inhttps://github.com/TykTechnologies/tyk-docs/pull/3154/commits/907b9e1f57b0dfff7a0c15314243aea94ffad450

2023-08-21 21:56 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +These credentials are stored with an Identity Provider(IdP). An Identity Provider (IdP) is a service that stores and manages digital identities. Companies can use these services to allow their employ
fixed in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/907b9e1f57b0dfff7a0c15314243aea94ffad450

2023-08-21 21:56 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +Single sign-on (SSO) is an authentication process which allows users to login to multiple services and applications with one set of credentials.
fixed in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/907b9e1f57b0dfff7a0c15314243aea94ffad450

2023-08-21 21:56 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +If you are interested in getting access, contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Cloud Single sign on>)
fixed in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/767c43c1684b1a2dedc6303f789aac2adac2dee8

2023-08-21 21:57 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +To add a new SSO profile, login to Tyk Cloud Dashboard, navigate to the _Profile_ list and click on the _ADD PROFILE_ button.
fixed in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/439b40c26cc1e592657dfc1ddfb301684600fa4a

2023-08-21 21:58 UTC, komuw commented
> looking really good - I like how detailed it is! I have added a couple of notes for small improvements.

Thanks for reviewing. I've addressed the feedback.

2023-08-22 07:38 UTC, SonjaChevre approved these changes

2023-08-24 07:48 UTC, mitjaziv commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +The Auth URL is your custom SSO login URL whereas Callback URL is the URL that the SSO provider will callback to, after the user authenticates.
There are multiple URL's:
- Auth/Login URL: Is the URL for staring the Login Flow 
- Discover URL: Is the URL for IDP discovery, reading configuration etc...
- Callback URL: Is the URL called after successful authentication
- Redirect URL: Is the URL where user gets redirected after successful authentication/authorization

2023-08-24 07:50 UTC, mitjaziv commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +| Discovery URL          | Used to initialise the authentication flow. This URL can be found in your chosen IdP provider's configuration.  |
Discovery URL is used for reading IDP's openid configuration.

2023-08-24 09:53 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +| Discovery URL          | Used to initialise the authentication flow. This URL can be found in your chosen IdP provider's configuration.  |
i've updated the definitions in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/8987e7436216a3256bcf7307f4bfa43bfeb25552

2023-08-24 09:54 UTC, komuw commented on tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
> +The Auth URL is your custom SSO login URL whereas Callback URL is the URL that the SSO provider will callback to, after the user authenticates.
i've updated the definitions in https://github.com/TykTechnologies/tyk-docs/pull/3154/commits/8987e7436216a3256bcf7307f4bfa43bfeb25552  

I've only included auth url and callback url since they are the only ones that we show to the user on the details page.

2023-08-25 07:42 UTC, mitjaziv approved these changes
Thank you Komu, looks great! 🚀

2023-08-25 15:30 UTC, dcs3spp approved these changes

2023-08-25 15:33 UTC, merged

2023-08-25 15:35 UTC, dcs3spp commented
/release to release-5.1