Restructure Dashboard Analytics page
TykTechnologies/tyk-docs-hugo pull request #3166
Opened 2023-08-18 11:19 UTC by caroltyk

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-18 12:05 UTC, dcs3spp requested changes
Hi @caroltyk, I have had a read through the PR relating to dashboard analytics and PR looking good. I like the table that has been added and have made some minor suggestions. 

I pushed some commits to the branch that relate to content that was in the page before this PR was created. For that, I updated 2 ref links to remove `/content` prefix and updated heading capitalisation.

2023-08-18 12:05 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +```{.shell}
```suggestion
```json
```

2023-08-18 12:05 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +## 2. SQL aggregate pump
```suggestion
## 2. SQL Aggregate Pump
```

2023-08-18 12:05 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +## 3. Configuring a Tyk SQL uptime pump
```suggestion
## 3. Configuring a Tyk SQL Uptime Pump
```

2023-08-18 12:05 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +This is the default option offered by Tyk, because it is configured to store the most important analytics details which will satisfy the needs of the most of our clients. This allows your system to s
```suggestion
This is the default option offered by Tyk, because it is configured to store the most important analytics details which will satisfy the needs of most of our clients. This allows your system to save database space and reporting is faster, consuming less resources.
```

2023-08-18 12:05 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
>  Let's discuss these pumps, their configs, matching collections and relevant dashboard setting,to view this data.
```suggestion
Let's discuss these pumps, their configs, matching collections and relevant dashboard settings, to view this data.
```

2023-08-18 12:05 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +When using one of our [supported SQL platforms]({{< ref "/content/tyk-dashboard/database-options.md#introduction" >}}), Tyk offers 3 types of SQL pumps:
```suggestion
When using one of our [supported SQL platforms]({{< ref "tyk-dashboard/database-options#introduction" >}}), Tyk offers 3 types of SQL pumps:
```

2023-08-18 12:21 UTC, caroltyk commented
Thanks @dcs3spp for the updates! I'll ask for peer review now.

2023-08-18 13:16 UTC, dcs3spp requested changes
@caroltyk I've completed review of the new content since my previous review within minor suggestions

2023-08-18 13:16 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +```{.json}
```suggestion
```json
```

2023-08-18 13:16 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +```{.shell}
```suggestion
```json
```

2023-08-18 13:16 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +  “storage” : {
```suggestion
  "storage" : {
```

2023-08-18 13:16 UTC, dcs3spp commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +    “analytics”: {
```suggestion
    "analytics": {
```

2023-08-29 10:07 UTC, tbuchaillot commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +You need to set `enable_aggregate_lookups` to `false`
enable_aggregate_lookups true here

2023-08-29 10:07 UTC, tbuchaillot commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +You need to set `enable_aggregate_lookups` to `false`
Pretty similar to The [enable_aggregate_lookups: true]({{< ref "tyk-dashboard/configuration#enable_aggregate_lookups" >}}) field must be set in the Dashboard configuration file, in order for the Dashboard to query and display the aggregated data that `sql aggregate` saved to SQL Database.

2023-08-29 11:07 UTC, caroltyk commented on tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
> +You need to set `enable_aggregate_lookups` to `false`
Thanks - updated as discussed

2023-08-29 11:18 UTC, tbuchaillot approved these changes

2023-08-29 15:14 UTC, caroltyk commented
@dcs3spp all suggestions are added.

2023-08-31 09:53 UTC, dcs3spp approved these changes

2023-08-31 09:58 UTC, merged

2023-08-31 09:59 UTC, dcs3spp commented
/release to release-5.1

2023-08-31 09:59 UTC, dcs3spp commented
/release to release-5