[TT-6727] Restructured and clarified wording for Basic Auth
TykTechnologies/tyk-docs-hugo pull request #3167
Opened 2023-08-18 13:16 UTC by andyo-tyk

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link
TBC

### Description
To address TT-6727
Restructured and improved the wording to improve clarity.

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-18 17:08 UTC, dcs3spp requested changes
Thanks for restructuring this document @andyo-tyk 

Structure looks better moving the explanation of the concepts for Basic Authentication to the beginning of the document. 

I have reviewed with minor suggestions

2023-08-18 17:08 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +Basic Authentication is a standard authentication mechanism supported by every standards-compliant HTTP server, it is also supported by almost every single web browser, which makes it an excellent ac
```suggestion
Basic Authentication is a standard authentication mechanism supported by every standards-compliant HTTP server. It is also supported by almost every single web browser, which makes it an excellent access control method for smaller APIs.
```

2023-08-18 17:08 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +Aa API request made using Basic Authentication will have an `Authorization` header that contains the API key.
I have read the [create a basic authentication section](https://deploy-preview-3167--tyk-docs.netlify.app/docs/nightly/basic-config-and-security/security/authentication-authorization/basic-auth/#create-a-basic-authentication-user) below. 

Does the `Authorization` header contain the key or the username and password that is somehow mapped to a key?

2023-08-18 17:08 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +## What is Basic Authentication?
Yep, I can see why you have restructured. In the current live website this section is at the end of the page.

2023-08-18 17:08 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +You can use the Tyk Dashboard to create an access keywith Basic Authentication simply select the API for which you selected Basic Authentication and, in the Authentication tab, you can see that Basic
```suggestion
You can use the Tyk Dashboard to create an access key with Basic Authentication. Simply select the API for which you want to use Basic Authentication with. In the Authentication tab you should see that Basic Authentication settings are automatically displayed.
```

2023-08-18 17:08 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +We have full tutorials to guide you to [create an API Key]({{< ref "getting-started/create-api-key" >}}) via the Dashboard.
```suggestion
We have full tutorials to guide you through the process of [creating an API Key]({{< ref "getting-started/create-api-key" >}}) via the Dashboard.
```

2023-08-18 17:08 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +The value of `Authorization` will be in the form:
```suggestion
The value of the `Authorization` header will be in the form:
```

2023-08-21 10:08 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +Aa API request made using Basic Authentication will have an `Authorization` header that contains the API key.
The section you linked is the method to register a key within the Gateway (i.e. to store valid credentials).
In the Authorization header, you need to provide valid credentials, which the Gateway then checks against its list.

2023-08-21 10:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +You can use the Tyk Dashboard to create an access keywith Basic Authentication simply select the API for which you selected Basic Authentication and, in the Authentication tab, you can see that Basic
```suggestion
You can use the Tyk Dashboard to register a Basic Authentication key that can then be used to access your API. 

When you select the API, you can see that Basic Authentication settings are automatically displayed in the Authentication tab:
```

2023-08-21 10:13 UTC, andyo-tyk reviewed
I think this is clearer

2023-08-22 08:07 UTC, dcs3spp approved these changes

2023-08-22 08:08 UTC, dcs3spp commented
@andyo-tyk I've approved PR. Once @lghiur or @furkansenharputlu complete a peer review will merge and release

2023-08-23 09:34 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +tags: ["Authentication", "Security", "Basic Auth"]
```suggestion
tags: ["Authentication", "Security", "Basic Authentication"]
```

2023-08-23 09:36 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +> In the context of an HTTP transaction, basic access authentication is a method for an HTTP user agent to provide a user name and password when making a request. HTTP Basic authentication implementa
Is this a needed citation? "Obviating" is making me pick up a thesaurus

2023-08-23 09:39 UTC, titpetric commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +Basic Authentication is a standard authentication mechanism supported by every standards-compliant HTTP server. It is also supported by almost every single web browser, which makes it an excellent ac
```suggestion
Basic Authentication is a standard authentication mechanism implemented by HTTP servers, clients and web browsers. This makes it an excellent access control method for smaller APIs.
```

2023-08-23 12:29 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +> In the context of an HTTP transaction, basic access authentication is a method for an HTTP user agent to provide a user name and password when making a request. HTTP Basic authentication implementa
Agreed - I was trying to make minimal content change while improving clarity, but I didn't see the point of this quote. Happy to remove it.

2023-08-28 06:15 UTC, lghiur approved these changes

2023-08-29 09:58 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +> In the context of an HTTP transaction, basic access authentication is a method for an HTTP user agent to provide a user name and password when making a request. HTTP Basic authentication implementa
Will merge once comment resolved.

2023-08-29 10:01 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +> In the context of an HTTP transaction, basic access authentication is a method for an HTTP user agent to provide a user name and password when making a request. HTTP Basic authentication implementa
```suggestion
```

2023-08-29 10:02 UTC, andyo-tyk reviewed
Implementing suggestions from Tit's review

2023-08-31 09:41 UTC, merged

2023-08-31 09:41 UTC, dcs3spp commented
/release to release-5.1

2023-08-31 09:42 UTC, dcs3spp commented
/release to release-5