Update dashboard.md
TykTechnologies/tyk-docs-hugo pull request #3170
Opened 2023-08-21 13:52 UTC by carlostyk

Shell - psql installation fixes
Made some changes to make the installation procedure work, removed some extra steps.

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-21 17:18 UTC, dcs3spp requested changes
Thanks for updating a fix to the content @carlostyk. PR looks good and I have made minor suggestions in comments

2023-08-21 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
> +*   Follow the steps provided in this link [Getting started on Red Hat (RHEL / CentOS)]({{< ref "/content/tyk-on-premises/redhat-rhel-centos.md" >}}) to install and configure Tyk dependencies.
```suggestion
Follow the steps provided in this link [Getting started on Red Hat (RHEL / CentOS)]({{< ref "tyk-on-premises/redhat-rhel-centos.md" >}}) to install and configure Tyk dependencies.
```

2023-08-21 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
> +Start MongoDB, if you are using it as the database:
Yep, this is a good idea, saves the users time instead of reading through a separate document from link

2023-08-21 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
> +Replace `<Redis Hostname>`, `<Mongo IP Address>`and `<Mongo Port>` with your own values to run this script.
```suggestion
Replace `<Redis Hostname>`, `<Mongo IP Address>` and `<Mongo Port>` with your own values to run this script.
```

2023-08-21 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
> +With this values your are configuring the following:
```suggestion
With these values your are configuring the following:
```

2023-08-21 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
> +When using postgreSQL you may run into "failed SASL auth (FATAL: password authentication failed for user...)" error. To solve this:
```suggestion
When using PostgreSQL you may receive the error: "failed SASL auth (FATAL: password authentication failed for user...)". To solve this:
```

2023-08-21 17:18 UTC, dcs3spp commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
> +Go to the file  `../pg_hba.conf `and change the connection method from `scram-sha-256` to `md5 `.
Should we give an absolute path to the `pga_hba.conf` file or update this to request the reader to update their `pga_hba.conf` file and include a location where it is likely to exist? What is the name of the configuration parameter that they should update in pga_hba.conf, is it _password_encryption_?

2023-08-22 07:36 UTC, carlosvillanua commented on tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
> +Go to the file  `../pg_hba.conf `and change the connection method from `scram-sha-256` to `md5 `.
I was thinking in that too, so the the absolute path should be /var/lib/pgsql/13/data/pg_hba.conf but if they are using another version of PostgreSQL it could change. 

So the change can be made with - sudo nano /var/lib/pgsql/13/data/pg_hba.conf

I have two images that could be used for reference for the change. It is actually the METHOD column that they would need to change 
![pg_hba conf pre](https://github.com/TykTechnologies/tyk-docs/assets/101631546/df07c311-03a5-47d3-be29-102946220be8)
![pg_hba conf post](https://github.com/TykTechnologies/tyk-docs/assets/101631546/61435894-d302-4ae6-9415-93faf32c629f)

2023-08-23 10:08 UTC, dcs3spp approved these changes

2023-08-23 10:09 UTC, dcs3spp commented
Approved and awaiting peer review

2023-08-31 15:43 UTC, padiazg approved these changes
LGTM

2023-09-01 13:26 UTC, merged

2023-09-01 13:27 UTC, dcs3spp commented
/release to release-5.1

2023-09-01 13:27 UTC, dcs3spp commented
/release to release-5