[TT-9675] Advanced cache clarifications
TykTechnologies/tyk-docs-hugo pull request #3171
Opened 2023-08-21 16:27 UTC by andyo-tyk

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link
TBA

### Description
Further improvement to the cache documentation, with particular focus on advanced cache config

** Note: currently pending screenshots from 5.2 **

2023-08-22 10:56 UTC, dcs3spp requested changes
Hi @andyo-tyk thanks for submitting PR.

PR looks good, I've made some minor suggestions. Once updated and we have a peer review, will merge and release

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +Safe request caching at the API level is enabled by setting the `cache_all_safe_requests` option to `true`, or by checking the equivalent checkbox in the Dashboard UI.
Is it worthwhile adding on a sentence with something like...

```suggestion
Safe request caching at the API level is enabled by setting the `cache_all_safe_requests` option to `true`, or by checking the equivalent checkbox in the Dashboard UI. This will enable safe request caching on all endpoints for an API.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
> +We define a <b>safe request</b> as any category of API request that is considered cacheable without causing any undesired side effects or security concerns. These are requests made using the HTTP met
```suggestion
We define a <b>safe request</b> as any category of API request that is considered cacheable without causing any undesired side effects or security concerns. These are requests made using the HTTP methods `GET`, `HEAD` or `OPTIONS` that do not modify data and can be safely cached for performance gains (i.e. they should be idempotent and so are good candidates for caching). If these methods are not idempotent for your API, then you should not use safe request caching.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +_On this page we describe the use of Tyk's API response cache at the advanced Endpoint level; for details on the API level (Global) cache you should refer to [this]({{< ref "/basic-config-and-securit
For consistency should we remove the italics from the paragraph

```suggestion
On this page we describe how to configure Tyk's API response cache per endpoint within an API. For details on the API level (Global) cache you should refer to the [global-cache]({{< ref "/basic-config-and-security/reduce-latency/caching/global-cache">}}) configuration page.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +        "widget",
does the format of endpoints accept '/', e.g. for longer endpoint paths, /widgets/:widget_id?

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +For ultimate control over what Tyk caches, you should use the advanced configuration options for the per-endpoint cache. You can separately configure, for each HTTP method for an endpoint: an individ
Maybe we could use bullet points for
- an individual TTL (timeout)
- a list of HTTP response codes that should be cached
- cache only requests containing specific data
etc.

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +The fields within `advance_cache_config` provide Tyk with the precise details of how you wish to cache calls to that endpoint (combination of HTTP method and path).
```suggestion
The fields within `advance_cache_config` provide Tyk with the precise details of how you wish to cache calls to that endpoint:
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> -The `advance_cache_config` configuration is not currently exposed in the Dashboard UI, so it must be enabled though either the raw API editor or the Dashboard API.
```suggestion
The `advance_cache_config` configuration is not currently exposed in the Dashboard UI, so it must be enabled through either the raw API editor or the Dashboard API. 
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +**Step 1**: configure the API level caching options from the **Advanced Options** tab in the Endpoint Designer as follows
```suggestion
**Step 1**: configure the API level caching options from the **Advanced Options** tab in the Endpoint Designer as follows:
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +  3. **Cache only these status codes** is where you list which HTTP status codes should be cached (remember to click **Add** after entering a code to add it to the list)
```suggestion
 **Cache only these status codes** is where you list which HTTP status codes should be cached. Remember to click **Add** after entering a code to add it to the list.
```

Maybe add full stops to end of each list item

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +  4. **Cache all safe requests** ensure that this is **not** selected
If the user selects this option then will all endpoints for an API be cached?

```suggestion
  4. **Cache all safe requests** ensure that this is **not** selected, otherwise the responses from all endpoints for the API will be cached.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> + - `path` - must match an endpoint/path provided in the `cache` list
For bullet points maybe style as follows, so that have _term: Sentence._

```suggestion
 - `path`: Must match an endpoint/path provided in the `cache` list.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +  4. **Cache all safe requests** ensure that this is **not** selected
Same as commented above, should we add a sentence explaining why it should not be selected

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +**Step 3**: configure the Advanced Cache (timeout and HTTP response codes) for each combination of path and method as required. If you don't need to set a specific timeout for an endpoint you can lea
```suggestion
**Step 3**: Configure the Advanced Cache (timeout and HTTP response codes) for each combination of path and method as required. If you don't need to set a specific timeout for an endpoint you can leave this blank and Tyk will use the cache timeout configured previously.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +**Step 2**: go into the Endpoint Designer tab and for the path(s) you want to cache, select the Advanced Cache plugin from the drop-down list.
```suggestion
**Step 2**: go into the Endpoint Designer tab and for the path(s) you want to cache, select the Advanced Cache plugin from the drop-down list.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +Body value match caching is not currently exposed in the Dashboard UI, so it must be enabled though either the raw API editor or the Dashboard API.
Maybe add a link or an example of which Dashboard API endpoint to use to achieve this?

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +_On this page we describe the use of Tyk's API response cache at the API level (Global); for details on the more advanced Endpoint level cache you should refer to [this]({{< ref "/basic-config-and-se
Should we remove the italics for consistency?

```suggestion
_On this page we describe the use of Tyk's API response cache at the API level (Global); for details on the more advanced Endpoint level cache you should refer to [this]({{< ref "/basic-config-and-security/reduce-latency/caching/advanced-cache">}}) page._
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> + - `cache_all_safe_requests`: Set to `true` to apply the caching rules to all requests using `GET`, `HEAD` and `OPTIONS` HTTP methods
```suggestion
 - `cache_all_safe_requests`: Set to `true` to apply the caching rules to all requests using `GET`, `HEAD` and `OPTIONS` HTTP methods.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> + - `cache_by_headers`: used to create multiple cache entries based on the value of a [header value](#selective-caching-by-header-value) of your choice
Maybe make the bullet points consistent styling with sentence case and adding .
```suggestion
 - `cache_by_headers`: Used to create multiple cache entries based on the value of a [header value](#selective-caching-by-header-value) of your choice.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +If you set `cache_all_safe_requests` to true, then the cache will be global and *all* inbound requests made to the API will be evaluated by the caching middleware. This is great for simple APIs, but
```suggestion
If you set `cache_all_safe_requests` to true, then the cache will be global and *all* inbound requests made to the API will be evaluated by the caching middleware. This is great for simple APIs, but for most, a finer-grained control is required. This control will over-ride any per-endpoint cache configuration.
```

2023-08-22 10:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> +The `cache_by_headers` configuration is not currently exposed in the Dashboard UI, so it must be enabled though either the raw API editor or the Dashboard API.
Maybe add a link or example for which endpoint in Dashboard API can be used to achieve this

2023-08-22 13:52 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +_On this page we describe the use of Tyk's API response cache at the advanced Endpoint level; for details on the API level (Global) cache you should refer to [this]({{< ref "/basic-config-and-securit
I've added this deliberately, but you're the docs owner so if you prefer them removed, I will remove them.

2023-08-22 13:52 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +        "widget",
No idea.

2023-08-22 13:53 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +The fields within `advance_cache_config` provide Tyk with the precise details of how you wish to cache calls to that endpoint (combination of HTTP method and path).
This is deliberate.

2023-08-22 13:53 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> + - `path` - must match an endpoint/path provided in the `cache` list
Would have been more helpful if you'd proposed the change for all.

2023-08-22 13:58 UTC, andyo-tyk reviewed
More changes from Simon's code review

2023-08-22 13:58 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +**Step 1**: configure the API level caching options from the **Advanced Options** tab in the Endpoint Designer as follows
```suggestion
**Step 1**: configure the API level caching options from the **Advanced Options** tab in the Endpoint Designer
```

2023-08-22 13:58 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> + - `cache_key_regex` - pattern match for selective caching by body value
```suggestion
 - `cache_key_regex`: Pattern match for selective caching by body value
```

2023-08-22 13:58 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> + - `cache_response_codes` - HTTP responses codes to be cached (for example `200`)
```suggestion
 - `cache_response_codes`: HTTP responses codes to be cached (for example `200`)
```

2023-08-22 13:58 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> + - `timeout` - given in seconds (if not provided, the timeout configured in `cache_timeout` will be used)
```suggestion
 - `timeout`: Given in seconds (if not provided, the timeout configured in `cache_timeout` will be used)
```

2023-08-22 13:58 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +For ultimate control over what Tyk caches, you should use the advanced configuration options for the per-endpoint cache. You can separately configure, for each HTTP method for an endpoint: an individ
```suggestion
For ultimate control over what Tyk caches, you should use the advanced configuration options for the per-endpoint cache. You can separately configure, for each HTTP method for an endpoint: an individual TTL (timeout) define; a list of HTTP response codes that should be cached; you can even provide a pattern match to cache only requests containing specific data (this is explained [here](#selective-caching-by-body-value)).
```

2023-08-22 13:58 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +  4. **Cache all safe requests** ensure that this is **not** selected
Yes, that's been stated repeatedly on these pages thought it was overkill

2023-08-22 13:58 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +  4. **Cache all safe requests** ensure that this is **not** selected
```suggestion
  4. **Cache all safe requests** ensure that this is **not** selected, otherwise the responses from all endpoints for the API will be cached.
```

2023-08-22 13:58 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
> + - `cache_by_headers`: used to create multiple cache entries based on the value of a [header value](#selective-caching-by-header-value) of your choice
```suggestion
 - `cache_by_headers`: Used to create multiple cache entries based on the value of a [header value](#selective-caching-by-header-value) of your choice
```

2023-08-22 15:45 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> -The `advance_cache_config` configuration is not currently exposed in the Dashboard UI, so it must be enabled though either the raw API editor or the Dashboard API.
This note has been removed in 5.2.

2023-08-22 15:46 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +**Step 2**: go into the Endpoint Designer tab and for the path(s) you want to cache, select the Advanced Cache plugin from the drop-down list.
I don't see what's changed in this suggestion.

2023-08-22 15:49 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +Body value match caching is not currently exposed in the Dashboard UI, so it must be enabled though either the raw API editor or the Dashboard API.
They need to edit the API definition directly, there isn't a specific Dashboard API endpoint for this.

2023-08-23 10:15 UTC, dcs3spp approved these changes

2023-08-23 10:16 UTC, dcs3spp commented
Approved, waiting for peer review before merge and release

2023-08-28 06:17 UTC, lghiur approved these changes

2023-09-05 08:57 UTC, merged