[TT-9849] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #3173
Opened 2023-08-22 15:40 UTC by Tyk-ITS

Triggered by: sredxny

Included:

Tyk Gateway: true
Tyk Dashboard: false
Tyk MDCB false
Tyk Pump false

Intended for: master

Note: <none>

JIRA: https://tyktech.atlassian.net/browse/TT-9849

2023-08-22 16:20 UTC, dcs3spp requested changes
Thanks @sredxny for submitting the PR that includes the _Open Telemetry_ config package.

I made some minor suggestions relating to paragraphs that included line breaks across sections. The only other issue was making the config descriptions consistent with the description style of other sections, e.g. starts with capital letter and ends with full stop.

For example:
_resource_name is the name of the resource that will be used to identify the resource.
Defaults to "tyk"_

Could become:

The name of the resource that will be used to identify the resource.
Defaults to "tyk".

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Section for configuring Opentelemetry
```suggestion
Section for configuring OpenTelemetry
```

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +enabled is a flag that can be used to enable or disable the trace exporter.
For consistency with the other config package sections. Ensure that each description ends with capitals and .

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +- "b3": b3 is a propagator serializes SpanContext to/from B3 multi Headers format.
```suggestion
- "b3": b3 is a propagator serializes SpanContext to/from B3 multi Headers format.
```

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Sampling defines the configurations to use in the sampler
```suggestion
Sampling defines the configurations to use in the sampler.
```

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +AlwaysOn, AlwaysOff and TraceIDRatioBased. It defaults to AlwaysOn
```suggestion
AlwaysOn, AlwaysOff and TraceIDRatioBased. It defaults to AlwaysOn.
```

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +it defaults to 0.5
Update so it is capitalised: It

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +sampling_rate is a parameter for the TraceIDRatioBased sampler type. It represents
Fix broken sentence across lines and make into paragraph

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +parent_based is a rule that makes sure that if we decide to record data
Fix broken sentences across lines so that forms paragraph

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +It defaults to false
```suggestion
It defaults to false.
```

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `transformRequestBody` ([TransformBody](#transformbody))**
What is the reason for the rename? The field is `trandformRequestBody`. Why has the link changed to TransformBody and #transformbody anchor?

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **TransformBody**
Why has this been renamed?

2023-08-22 16:20 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables transform request/request body middleware.
Should this be :

```suggestion
Enabled enables transform request/response body middleware.
```

2023-08-22 19:01 UTC, sredxny commented on tyk-docs/content/shared/gateway-config.md
> +enabled is a flag that can be used to enable or disable the trace exporter.
@dcs3spp Does this applies as well for lines like:

```
// Cert_file is the path to the cert file.
CertFile string `json:"cert_file"`
```
?

or for this use-cases it should start with lowercase?

2023-08-22 19:03 UTC, sredxny commented on tyk-docs/content/shared/gateway-config.md
> +- "b3": b3 is a propagator serializes SpanContext to/from B3 multi Headers format.
no changes suggested in here

2023-08-22 19:11 UTC, sredxny commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **TransformBody**
@dcs3spp not really, sure, this change was already in master branch but is not related to open telemetry config options (which is what am documenting here). Maybe @titpetric  knows?

2023-08-22 19:11 UTC, sredxny commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables transform request/request body middleware.
also not related to opentelemetry documentation.

2023-08-22 19:12 UTC, sredxny commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `transformRequestBody` ([TransformBody](#transformbody))**
not releated to opentelemetry configs

2023-08-22 19:29 UTC, sredxny commented
In order to make the changes is required to:
- Make the changes in the opentelemetry repo, merge and do a realease
- Import the released version of openetelemetry in the gateway and merge
- trigger the doc generator.

So far I created the PR in the opentelemetry repo and sent to review.

2023-09-07 13:31 UTC, dcs3spp commented
Closing ready for approving docs for OTel and /system/stats

2023-09-07 13:31 UTC, closed without merging