[DX-615] Release Notes For Tyk GW + Dashboard
TykTechnologies/tyk-docs-hugo pull request #3174
Opened 2023-08-23 10:17 UTC by dcs3spp

This PR contains new release notes format generated from Chat GTP and items in the changelog have been refined so that the benefit of fixes, additions, updates etc. are explained to users. It will be used for release 5.2.

It contains separate release notes for Tyk Dashboard and Tyk Gateway.

[DX-615](https://tyktech.atlassian.net/browse/DX-615)

[Preview Release Notes Changelog for Tyk Dashboard](https://deploy-preview-3174--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-dashboard/release-notes/version-5.2/)

[Preview Release Notes Changelog for Tyk Gateway](https://deploy-preview-3174--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/release-notes/version-5.2/)

[DX-615]: https://tyktech.atlassian.net/browse/DX-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-24 18:42 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          show: True
can we for now remove`Release highlights and upgrades`? since there's only one directory under the release notes we don't need it

2023-08-25 15:27 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +### Breaking Changes
maybe we can put it at the top?

2023-08-29 11:23 UTC, letzya commented
@dcs3spp I think we need to work a bit on the upgrade messaging. Maybe I missed it but can't see the link to this important page - https://tyk.io/docs/upgrading-tyk/ (or is it in another page?)

2023-08-29 11:28 UTC, letzya commented
@dcs3spp can we move the release notes page to the top https://deploy-preview-3174--tyk-docs.netlify.app/docs/nightly/release-notes/

2023-08-29 14:50 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +### Breaking Changes
Done

2023-08-29 16:26 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +          show: True
Where are placing the separate release note documents for Tyk Gateway and Tyk Dashboard?

2023-08-30 15:46 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +          show: True
Done, I've moved the release notes into the product-stack release notes section for Tyk Gateway

2023-08-31 11:30 UTC, carolwkc requested changes

2023-08-31 11:30 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added a new feature that allows clients to send API requests and retrieve the trace ID from the response headers. This feature is available when OpenTelemetry is [enabled]({{< ref "tyk-oss-gateway/
```suggestion
- Added a new feature that allows clients to send API requests and retrieve the trace ID from the response headers. This feature is available when OpenTelemetry is [enabled]({{< ref "tyk-oss-gateway/configuration#opentelemetryenabled" >}}) and simplifies debugging API requests, empowering users to seamlessly correlate and analyse data for a specific trace in any opentelemetry backend like [Jaeger](https://www.jaegertracing.io/).
```

2023-08-31 11:30 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added enhanced usage reporting. Tyk Dashboard now offers expanded usage reporting, giving customers valuable insights into their _hybrid_ and _standard_ Gateways. With this addition, users can effi
```suggestion
- Added enhanced Gateway usage reporting. Tyk Dashboard now offers expanded usage reporting, giving customers valuable insights into their _hybrid_ and _standard_ Gateways. With this addition, users can efficiently monitor deployed gateways and track monthly maximum Gateway usage.
```

2023-08-31 11:30 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for improved gateway visibility. MDCB now helps monitor connected gateways and groups. This facilitates smoother operations and ensures accurate setup. Features such as edge gateway v
```suggestion
- Added support for enhanced Gateway usage reporting. MDCB v2.4 and Gateway v5.2 can now report number of connected gateways and groups. Features such as edge gateway visualisation is available in Dashboard for enhanced monitoring of your deployment.
```

2023-08-31 13:11 UTC, agata-wit requested changes

2023-08-31 13:11 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Adding a new data source is simpler. The default value for the data source name is pre-filled, saving time. The data source name is prefilled in the format _fieldName_typeName_, with _typeName_ bei
Can you remove "with _typeName_ being _Query_, _Mutation_ _or_ _Subscription_" ? This is not correct, typeName can be anything really, not only query, mutation, subscription.

2023-08-31 13:11 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Updated the screen for configuring and saving UDG data sources. The additional _Update_ button has been removed and when _Save_ is clicked the data source configuration is persisted. Saving a UDG d
```suggestion
- Updated the screen for configuring and saving UDG data sources. The _Save_ button has been replaced with _Save & Update API_ button and users no longer need to additionally click _Update_ at the top of the screen to persist changes. Saving a UDG data source is now simpler and quicker.
```

2023-08-31 16:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added a new feature that allows clients to send API requests and retrieve the trace ID from the response headers. This feature is available when OpenTelemetry is [enabled]({{< ref "tyk-oss-gateway/
Many thanks @caroltyk I have updated as suggested

2023-08-31 16:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Adding a new data source is simpler. The default value for the data source name is pre-filled, saving time. The data source name is prefilled in the format _fieldName_typeName_, with _typeName_ bei
Many thanks @agata-wit

Would this be ok?

```suggestion
- Adding a new data source is simpler. The default value for the data source name is pre-filled, saving time. The data source name is pre-filled in the format _fieldName_typeName_, with _typeName_ being the name of any GraphQL type.
```

2023-08-31 16:13 UTC, dcs3spp commented
Many thanks for providing feedback and suggestions @agata-wit @caroltyk.

I have made suggested changes and requested a second review

2023-09-01 07:23 UTC, agata-wit requested changes

2023-09-01 07:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Adding a new data source is simpler. The default value for the data source name is pre-filled, saving time. The data source name is prefilled in the format _fieldName_typeName_, with _typeName_ bei
Yup, that would be fine.

2023-09-01 07:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added an optimised query execution engine for GraphQL, activated by setting [opentelemetry.enabled]({{< ref "tyk-oss-gateway/configuration#opentelemetryenabled" >}}) to _true_. This integration enh
I don't understand this one. OTel has nothing to do with optimised query execution engine. We haven't done anything like that.

2023-09-01 07:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for using [request context variables]({{< ref "context-variables#the-available-context-variables-are" >}}) in UDG global or data source headers. This feature enables customising reque
```suggestion
- Added support for using [request context variables]({{< ref "context-variables#the-available-context-variables-are" >}}) in UDG global or data source headers. This feature enables much more advanced header management for UDG and allows users to extract header information from an incoming request and passing it to upstream data sources.
```

2023-09-01 07:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for simpler configuration of global headers for any UDG. These headers will be forwarded to all data sources by default, enhancing control over data flow.
```suggestion
- Added support for configuration of global headers for any UDG. These headers will be forwarded to all data sources by default, enhancing control over data flow.
```

2023-09-01 11:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added an optimised query execution engine for GraphQL, activated by setting [opentelemetry.enabled]({{< ref "tyk-oss-gateway/configuration#opentelemetryenabled" >}}) to _true_. This integration enh
Ok many thanks @agata-wit for catching this. I'll check the Jira tickets on Confluence to see where this item originated from and will update with the details here

2023-09-01 12:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added an optimised query execution engine for GraphQL, activated by setting [opentelemetry.enabled]({{< ref "tyk-oss-gateway/configuration#opentelemetryenabled" >}}) to _true_. This integration enh
@agata-wit This was generated from ChatGTP using [TT-8809](https://tyktech.atlassian.net/browse/TT-8809) description/heading and release note _Added tracing to graphql execution for grapqhl proxy only and UDG_

Would this suggestion be better?

```suggestion
- Added OpenTelemetry support for GraphQL. This is activated by setting [opentelemetry.enabled]({{< ref "tyk-oss-gateway/configuration#opentelemetryenabled" >}}) to _true_. This integration enhances observability by enabling GQL traces in any OpenTelemetry backend, like [Jaeger](https://www.jaegertracing.io/), granting users comprehensive insights into the execution process, such as request times.
```

2023-09-01 13:30 UTC, dcs3spp commented
Many thanks @agata-wit for adding the summary paragraph on the confluence page. I have integrated the summary into the PR and I am thinking of adding [links](https://tyktech.slack.com/archives/G01CKTY1YAK/p1693574505544099?thread_ts=1693307835.894889&cid=G01CKTY1YAK) to the graphql transport protocols.

2023-09-01 16:11 UTC, andyo-tyk requested changes
Sorry I'm late :(

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added a new endpoint, _/system/stats_, to provide API insights and operations statistics. These statistics include _Create_, _Read_, _Update_, and _Delete_ operations. This feature equips managers
Which ticket does this come from? Is it Portal?

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added support for historical API insights. This is a useful feature for account managers, providing a historical record of the total number of APIs and active APIs. License compliance can be effect
This is a feature for Tyk Account Managers... so I don't think needs to be included as a highlight in the release notes.

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added support for API developers to easily configure both request and response body transformations for more precise data management. Define input data, craft transformation templates and test them
This is specifically the addition of support for Response Body Transforms (and adding Request Body Transforms to the UI) when working with Tyk OAS APIs - we've had this for Tyk Classic APIs for a long time. The way the AI has written this suggests it's a whole new feature for Tyk.

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Adding a new data source is simpler. The default value for the data source name is pre-filled, saving time. The data source name is pre-filled in the format _fieldName_typeName_, with _typeName_ be
Perhaps with should start with something to indicate that this is related to when working with UDG? @agata-wit

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Updated the API creation process in Tyk Dashboard so that users remain on the same screen after saving. This means users can continue editing without having to navigate back to the screen to make s
```suggestion
- Improved the flow when creating an API within the API Designer so that you remain on the same screen after saving. This means you can continue editing without having to navigate back to the screen to make subsequent changes.
```

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Updated the API creation process in Tyk Dashboard so that users remain on the same screen after saving. This means users can continue editing without having to navigate back to the screen to make s
I've changed "users" to "you" as I understood that was the preferred voice, but I may be wrong? Anyhow, above suggestion is (I think) clearer.

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Update the Dashboard with enhanced API usage visibility. A new chart has been introduced on the _License Statistics_ page, presenting the number of deployed _Data Planes_. This addition enables use
I think this bullet should be combined with the one above - basically we've improved the Nodes & Licences page in the Dashboard:

- We've renamed it to License Statistics (sic)
- We've added charts to show number of APIs (total and active), number of Data Planes, volume of API traffic
- The charts are flexible (per the first bullet on line 46)

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue where _advanced_cache_config_ data was absent in the _Raw Editor_. This fix now ensures visibility of this data. Furthermore, API modifications in the _Designer_ no longer lead to da
Can `advanced_cache_config` be shown in `code` format, given it's a field name?

The fix actually provides access to this field, not just visibility - previously it wasn't possible to configure this part of the API definition from within the API Designer. Note that the Timeout field is new in this release.

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a potential security vulnerability where static and dynamic mTLS requests,with expired certificates, could be proxied upstream.
```suggestion
- Fixed a potential security vulnerability where static or dynamic mTLS requests with expired certificates could be proxied upstream.
```

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue in Tyk Dashboard where duplicate API names and listen paths could be created. Configurations are now unique.
Which ticket is this?

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +Thanks to PatrickTaibel for fixing an issue where global_size_limit was not enabling request size limit middleware.
None for Core APIM

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added the ability for Custom Plugin developers to access the OAS API Definition through the newly introduced _ctx.getOASDefinition_ function. This enhancement simplifies development, without permit
```suggestion
- Added the ability for Custom GoPlugin developers using Tyk OAS APIs to access the API Definition from within their plugin. The newly introduced _ctx.getOASDefinition_ function provides read-only access to the OAS API Definition and enhances the flexibility of plugins.
```

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for API Developers to effortlessly configure the Body response transform middleware for specific OAS API endpoints using the operationID of an OAS Path. This enhancement ensures strea
```suggestion
- Added support for API Developers using Tyk OAS APIs to configure a body transform middleware that operates on API responses. This enhancement ensures streamlined and selective loading of the middleware based on configuration, enabling precise response data customization at the per-endpoint level.
```

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for enhanced Gateway usage reporting. MDCB v2.4 and Gateway v5.2 can now report number of connected gateways and groups. Features such as edge gateway visualisation is available in Da
```suggestion
- Added support for enhanced Gateway usage reporting. MDCB v2.4 and Gateway v5.2 can now report the number of connected gateways and data planes. Features such as data plane gateway visualisation is available in Dashboard for enhanced monitoring of your deployment.
```

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for enhanced Gateway usage reporting. MDCB v2.4 and Gateway v5.2 can now report number of connected gateways and groups. Features such as edge gateway visualisation is available in Da
I believe we're going with "data plane", not "edge". @caroltyk

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Thanks to PatrickTaibel for fixing an issue where global_size_limit was not enabling request size limit middleware.
None for Core APIM

2023-09-01 16:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed an issue in where duplicate API names and listen paths could be created. Configurations are now unique.
Again, not sure which ticket this relates to?

2023-09-01 16:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added support for API developers to easily configure both request and response body transformations for more precise data management. Define input data, craft transformation templates and test them
Ok thanks for spotting that Andy, so this should go in Update/Changed section, yes?

2023-09-01 16:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue where _advanced_cache_config_ data was absent in the _Raw Editor_. This fix now ensures visibility of this data. Furthermore, API modifications in the _Designer_ no longer lead to da
Something like....

```suggestion
- Fixed an issue where `advanced_cache_config` data was absent in the _Raw Editor_. This fix now ensures that `advanced_cache_config` can be configured. Furthermore, API modifications in the _Designer_ no longer lead to data loss, safeguarding cache configuration consistency. The UI now offers a clear view of advanced cache settings, including the new Timeout field and Cache response codes fields.
```

2023-09-01 16:57 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Thanks to PatrickTaibel for fixing an issue where global_size_limit was not enabling request size limit middleware.
Ok, thanks @andyo-tyk I have removed the community contribution section

2023-09-01 17:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added support for API developers to easily configure both request and response body transformations for more precise data management. Define input data, craft transformation templates and test them
I'd suggest it goes in Added because, for Tyk OAS, it's a new capability.

2023-09-01 17:02 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added support for historical API insights. This is a useful feature for account managers, providing a historical record of the total number of APIs and active APIs. License compliance can be effect
Thanks @andyo-tyk I have removed it from the release notes

2023-09-01 17:06 UTC, andyo-tyk requested changes
Sorry, I wasn't clear enough in my summary which bits were for Gateway and which were for Dashboard.

2023-09-01 17:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +### Track Usage Of License APIs, Gateways And Distributed Data Planes Over Time
This is a Dashboard feature - should be on the other page.

2023-09-01 17:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +### Configure Caching For Each API Endpoint
The first part of this (the ability to configure the per-endpoint timeout) is in the Gateway, the second part is Dashboard only.
I'd suggest cutting this down in the Gateway release note and putting the whole paragraph in the Dashboard one.

2023-09-01 17:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +### New Middleware Supports Request/Response Body Transformations
The change in the Gateway is the ability to configure Response Body Transforms for Tyk OAS APIs (we already have support for Request Body Transforms in the Gateway).

It's all new in the Dashboard UI, I'm sorry I wasn't clear previously.

2023-09-01 17:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added a new endpoint, _/system/stats_, to provide API insights and operations statistics. These statistics include _Create_, _Read_, _Update_, and _Delete_ operations. This feature equips managers
@andyo-tyk This one was derived from https://tyktech.atlassian.net/browse/TT-9607

2023-09-01 17:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Adding a new data source is simpler. The default value for the data source name is pre-filled, saving time. The data source name is pre-filled in the format _fieldName_typeName_, with _typeName_ be
@andyo-tyk @agata-wit 

Something like:

```suggestion
- Adding a new UDG data source is simpler. The default value for the data source name is pre-filled, saving time. The data source name is pre-filled in the format _fieldName_typeName_, with _typeName_ being the name of any GraphQL type.
```

or

```suggestion
- Adding a new data source is simpler when working with UDG. The default value for the data source name is pre-filled, saving time. The data source name is pre-filled in the format _fieldName_typeName_, with _typeName_ being the name of any GraphQL type.
```

or something else...

2023-09-01 17:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Update the Dashboard with enhanced API usage visibility. A new chart has been introduced on the _License Statistics_ page, presenting the number of deployed _Data Planes_. This addition enables use
Not sure on this one. My feeling is if we combined it into one paragraph it might be too lengthy. If we reduced the description to combine both bullet points we might lose some of the benefits in the description.

2023-09-01 17:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue in Tyk Dashboard where duplicate API names and listen paths could be created. Configurations are now unique.
@andyo-tyk This one is https://tyktech.atlassian.net/browse/TT-9747

2023-09-01 17:17 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed an issue in where duplicate API names and listen paths could be created. Configurations are now unique.
@andyo-tyk This one is https://tyktech.atlassian.net/browse/TT-9747

2023-09-01 17:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +### Track Usage Of License APIs, Gateways And Distributed Data Planes Over Time
Thanks @andyo-tyk I've moved it into release summary of Dashboard release notes

2023-09-01 17:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +### Configure Caching For Each API Endpoint
Thanks @andyo-tyk for suggestion. Good spot, I've added full paragraph to dashboard release note summary and reduced the Gateway release note summary.

2023-09-01 17:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +Thanks to PatrickTaibel for fixing an issue where global_size_limit was not enabling request size limit middleware.
Ok, thanks @andyo-tyk I have removed the community contribution section from Dashboard release notes

2023-09-01 17:30 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +### New Middleware Supports Request/Response Body Transformations
@andyo-tyk So in the gateway release note this feature should be in the changed/updated section of the changelog, yes?

And in the dashboard release notes this feature should be in the added section, yes?

2023-09-01 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +### New Middleware Supports Request/Response Body Transformations
I'd put it in the "Added" section in both, as it's new functionality.

2023-09-01 17:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +### Reference Tyk OAS API Definition Fom Within Your Custom Go Plugins
```suggestion
### Reference Tyk OAS API Definition From Within Your Custom Go Plugins
```

(spotted a typo)

2023-09-01 18:04 UTC, andyo-tyk requested changes
More suggestions following @dcs3spp's feedback

2023-09-01 18:04 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added a new endpoint, _/system/stats_, to provide API insights and operations statistics. These statistics include _Create_, _Read_, _Update_, and _Delete_ operations. This feature equips managers
OK, I understand. I would rephrase as follows and move this to the bottom of the list of Added features.

```suggestion
- Added a new endpoint, _/system/stats_, to provide insight and operational statistics on total and active APIs deployed. The endpoint's flexible date filtering options, equip users to obtain comprehensive insights into usage trends.
```

2023-09-01 18:04 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Update the Dashboard with enhanced API usage monitoring. Users now benefit from an insightful chart on the _Licensing Statistics_ page, detailing: maximum, minimum, average API counts, in addition
```suggestion
- Updated the Dashboard with enhanced API usage monitoring. Users now benefit from an insightful chart on the _Licensing Statistics_ page, detailing: maximum, minimum and average counts of created and active APIs. Flexible date filtering, license limit reference lines and the ability to toggle between line and bar graphs empowers users to monitor usage effortlessly, ensuring license adherence.
```

2023-09-01 18:04 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added enhanced Gateway usage reporting. Tyk Dashboard now offers expanded usage reporting, giving customers valuable insights into their _hybrid_ and _standard_ Gateways. With this addition, users
I'd move this down in the Added section too, the body transform and UDG features are probably more interesting.

2023-09-01 18:04 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Update the Dashboard with enhanced API usage visibility. A new chart has been introduced on the _License Statistics_ page, presenting the number of deployed _Data Planes_. This addition enables use
OK, understood.

In that case how about:

```suggestion
- A new chart has been introduced on the _License Statistics_ page that presents the number of deployed _Data Planes_. This addition enables users to easily monitor their _Data Plane_ usage and  nearness to their contract limits.
```

Not sure whether I prefer nearness, closeness or proximity (probably not the last, as it's not a physical distance, but is a reference to how near a deployment is to its maximum (contractually allowed) number of Data Planes.

2023-09-01 18:04 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue where _advanced_cache_config_ data was absent in the _Raw Editor_. This fix now ensures visibility of this data. Furthermore, API modifications in the _Designer_ no longer lead to da
Yes... though I've realised that italics have been used throughout the release notes so it's a design choice: should we tag code fragments with`code` or _code_? If the former then we need to go through and make the appropriate changes.

2023-09-01 18:04 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue in Tyk Dashboard where duplicate API names and listen paths could be created. Configurations are now unique.
Ah, OK - the expected/reported behaviour in the ticket didn't make sense. :-)

For clarity perhaps:

```suggestion
- Fixed an issue in Tyk Dashboard where duplicate APIs could be created with the same names and listen paths if you clicked multiple times on the _save_ button in the API Designer. Now, when you save your new API, you are taken to the list of APIs.
```

2023-09-01 18:04 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed an issue in where duplicate API names and listen paths could be created. Configurations are now unique.
This isn't a Gateway change -> there's only a PR for the Dashboard UI.

2023-09-04 08:35 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added a new endpoint, _/system/stats_, to provide API insights and operations statistics. These statistics include _Create_, _Read_, _Update_, and _Delete_ operations. This feature equips managers
Done

2023-09-04 09:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for enhanced Gateway usage reporting. MDCB v2.4 and Gateway v5.2 can now report number of connected gateways and groups. Features such as edge gateway visualisation is available in Da
Ok thanks @andyo-tyk I'll commit the suggestion

2023-09-04 09:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Thanks to PatrickTaibel for fixing an issue where global_size_limit was not enabling request size limit middleware.
Done, community contribution removed

2023-09-04 09:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed an issue in where duplicate API names and listen paths could be created. Configurations are now unique.
Thanks @andyo-tyk , I've moved this to Dashboard release note

2023-09-04 09:29 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added support for API developers to easily configure both request and response body transformations for more precise data management. Define input data, craft transformation templates and test them
Thanks @andyo-tyk, I have updated changelog description in Dashboard release note to mention that this relates to Tyk OAS

2023-09-04 09:34 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +### New Middleware Supports Request/Response Body Transformations
Thanks @andyo-tyk. I have updating the heading of the release summary item to make it clearer that this is new for Tyk OAS API. The changelog item is now present (on both Dashboard and Gateway release notes), within the added section.

2023-09-04 10:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added enhanced Gateway usage reporting. Tyk Dashboard now offers expanded usage reporting, giving customers valuable insights into their _hybrid_ and _standard_ Gateways. With this addition, users
Thanks @andyo-tyk have moved those items down in the added section

2023-09-04 10:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue where _advanced_cache_config_ data was absent in the _Raw Editor_. This fix now ensures visibility of this data. Furthermore, API modifications in the _Designer_ no longer lead to da
Thanks @andyo-tyk I have updated to use _code_ styling for consistency with other changelog items. I have pushed the change and made it clearer that the fix makes it possible to configure this part of the API

2023-09-04 16:30 UTC, letzya requested changes
`Release highlights and upgrades` - is shown with a red box. We need to remember to unset this env var

2023-09-04 16:30 UTC, letzya commented on tyk-docs/content/release-notes/version-5.2.md
> +## Changelog for Tyk Gateway:
Why the titles of the gw and the dashboard are different?

2023-09-04 16:30 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added a new endpoint, _/system/stats_, to provide API insights and operations statistics. These statistics include _Create_, _Read_, _Update_, and _Delete_ operations. This feature equips managers
I think we should have a separate section for Api changes, as you suggested. Having such title makes it very clear and we can give a link to our postman collection

2023-09-04 16:30 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        - title: "Tyk Gateway v5.2"
THis should be the first in the list.

2023-09-04 16:30 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        - title: "Tyk Gateway v5.2"
Also, the order of all the releases should be high to low. Since these releases are very old, maybe we can add a directory named `old releases` and move it to there?

2023-09-04 16:30 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          show: True
thanks. so now for the dashboard?

2023-09-04 16:30 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +### Breaking Changes
```suggestion
## Breaking Changes
```

2023-09-04 16:32 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +# Tyk Dashboard (Licensed) 5.2 Release Notes
I think we should remove `(licensed)` from the title. We can move it to a line below with body font size.

2023-09-04 16:32 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +# Tyk Gateway (Open-Source) 5.2 Release Notes
I think we should remove `(ope-source)` from the title. We can move it to a line below with body font size

2023-09-04 16:34 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +### Track Usage Of License APIs, Gateways And Distributed Data Planes Over Time
@dcs3spp when I look at the preview i don't see much difference between H2 and H3, they seem on the same level. What do you think?

2023-09-04 16:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +### Track Usage Of License APIs, Gateways And Distributed Data Planes Over Time
This should be the last item in the list of Highlights - the other two are more interesting for users.

2023-09-04 16:45 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +With the release of Tyk Gateway 5.2, we're introducing a powerful new feature: OpenTelemetry Tracing. Over the next year, we'll be deprecating OpenTracing. We recommend migrating to OpenTelemetry for
In my browser (Safari) this warning is not wrapping, so it looks really bad; it also seems to be in a code block as it gives me the option to copy to clipboard...

![image](https://github.com/TykTechnologies/tyk-docs/assets/99968932/171c7875-bcd0-4446-97d1-b25fd4b1a569)

2023-09-04 16:47 UTC, andyo-tyk commented on tyk-docs/data/menu.yaml
> +          show: True
Are all the old notes going to be moved? In the preview we've got most of them in Developer Support and now a few (very old) ones for Gateway in the Product Stack.

2023-09-04 16:57 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +### Track Usage Of License APIs, Gateways And Distributed Data Planes Over Time
Thanks @andyo-tyk I have moved it to end of release highlights section for dashboard

2023-09-04 16:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +### Breaking Changes
done

2023-09-04 17:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +# Tyk Gateway (Open-Source) 5.2 Release Notes
done

2023-09-04 17:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +# Tyk Dashboard (Licensed) 5.2 Release Notes
done

2023-09-04 17:09 UTC, dcs3spp commented on tyk-docs/content/release-notes/version-5.2.md
> +## Changelog for Tyk Gateway:
Done

2023-09-04 17:10 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +        - title: "Tyk Gateway v5.2"
Done

2023-09-04 17:15 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +        - title: "Tyk Gateway v5.2"
Done

2023-09-04 17:16 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +          show: True
Have created placed the older release notes in an older releases sidebar folder in Product Stack

2023-09-04 18:11 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          show: True
@andyo-tyk since we had shared release notes we can't easily moved the last release notes under GW or dashboard without splitting them, so we'll probably do it in another pr separately

2023-09-04 18:14 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +With the release of Tyk Gateway 5.2, we're introducing a powerful new feature: OpenTelemetry Tracing. Over the next year, we'll be deprecating OpenTracing. We recommend migrating to OpenTelemetry for
yes, same for me

2023-09-04 18:15 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        - title: "Tyk Gateway v5.2"
@dcs3spp still not done, 5.2 needs to be first

2023-09-04 18:18 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        - title: "Tyk Gateway v5.2"
can't see this

2023-09-05 08:09 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +        - title: "Tyk Gateway v5.2"
Moved older releases into new folder for review comment

![Screenshot](https://github.com/TykTechnologies/tyk-docs/assets/12863448/28f954d7-d821-4fa7-ab2d-e02fbd089b47)

2023-09-05 12:55 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Adding a new data source is simpler. The default value for the data source name is pre-filled, saving time. The data source name is pre-filled in the format _fieldName_typeName_, with _typeName_ be
I like the second one! Vote for that :)

2023-09-05 12:57 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added an optimised query execution engine for GraphQL, activated by setting [opentelemetry.enabled]({{< ref "tyk-oss-gateway/configuration#opentelemetryenabled" >}}) to _true_. This integration enh
Yeah, this makes sense now :)

2023-09-05 17:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added a new endpoint, _/system/stats_, to provide API insights and operations statistics. These statistics include _Create_, _Read_, _Update_, and _Delete_ operations. This feature equips managers
Done

2023-09-05 17:21 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +### Track Usage Of License APIs, Gateways And Distributed Data Planes Over Time
Thanks @letzya I have updated headings so uses H2 and H4 to make the headings different.

2023-09-05 17:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +With the release of Tyk Gateway 5.2, we're introducing a powerful new feature: OpenTelemetry Tracing. Over the next year, we'll be deprecating OpenTracing. We recommend migrating to OpenTelemetry for
Thanks @andyo-tyk @letzya I have fixed and updated

2023-09-05 18:10 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        - title: "Tyk Gateway v5.2"
5.2 needs to be before old in the order

2023-09-05 18:12 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- [docker image to pull](https://hub.docker.com/layers/tykio/tyk-gateway/v5.2.0/images/sha256-075df4d840b452bfe2aa9bad8f1c1b7ad4ee06a7f5b09d3669f866985b8e2600?tab=vulnerabilities)
what is this link? You need to log in for it. Since It should be a direct link to the released image maybe it's best to leave it empty?

2023-09-05 18:12 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- [source code](https://github.com/TykTechnologies/tyk/releases/tag/v5.1.2)
just be sure this is changed to 5.2...

2023-09-05 18:19 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +We're thrilled to bring you some exciting enhancements and crucial fixes to improve your experience of Tyk Gateway.
```suggestion
We're thrilled to bring you some exciting enhancements and crucial fixes to improve your experience with Tyk Gateway. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#changelog">}}) below.
```

2023-09-05 18:20 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support to configure OpenTelemetry [sampling types]({{< ref "tyk-oss-gateway/configuration#opentelemetrysampling" >}}) (probabilistic, rate limiting, and adaptive) in the Tyk Gateway. This al
names  need to be italic throughout the doc

2023-09-06 08:30 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +        - title: "Tyk Gateway v5.2"
Done

2023-09-06 08:31 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- [source code](https://github.com/TykTechnologies/tyk/releases/tag/v5.1.2)
Before merging the PR the link will need to be updated to refer to the tag for release 5.2. Same for the docker image links

2023-09-06 08:48 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support to configure OpenTelemetry [sampling types]({{< ref "tyk-oss-gateway/configuration#opentelemetrysampling" >}}) (probabilistic, rate limiting, and adaptive) in the Tyk Gateway. This al
Done

2023-09-06 09:17 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- [docker image to pull](https://hub.docker.com/layers/tykio/tyk-gateway/v5.2.0/images/sha256-075df4d840b452bfe2aa9bad8f1c1b7ad4ee06a7f5b09d3669f866985b8e2600?tab=vulnerabilities)
Yep the link is the direct download link for developers to use the docker image

2023-09-06 11:20 UTC, caroltyk requested changes

2023-09-06 11:20 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- A new chart has been introduced on the _License Statistics_ page that presents the number of deployed _Data Planes_. This addition enables users to easily monitor their _Data Plane_ usage and  near
This is duplicated with "- Added enhanced Gateway usage reporting. Tyk Dashboard now offers expanded usage reporting, giving customers valuable insights into their _hybrid_ and _standard_ Gateways. With this addition, users can efficiently monitor deployed gateways and track monthly maximum Gateway usage.".

2023-09-06 11:20 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a critical issue in MDCB deployments, relating to _Control Plane_ stability. The _Control Plane_ Gateway was found to crash with a panic when creating a Tyk OAS API. The bug has been addresse
Please move this to Gateway change log.

```suggestion
- Fixed a critical issue in MDCB v2.3 deployments, relating to _Data Plane_ stability. The _Data Plane_ Gateway with version older than v5.1 was found to crash with a panic when creating a Tyk OAS API. The bug has been addressed, ensuring stability and reliability in such deployments.
```

2023-09-06 11:20 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +In this version, we're introducing a new feature called OpenTelemetry Tracing. This addition gives you improved visibility into how API requests are processed. It's designed to help with plugin devel
```suggestion
In this version, we're introducing the support for OpenTelemetry Tracing. This addition gives you improved visibility into how API requests are processed. It's designed to help you with monitoring and troubleshooting APIs, identify bottlenecks, latency issues, and errors in your API calls. For detailed information and guidance, you can check out our OpenTelemetry Tracing resource.
```

2023-09-06 11:20 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for [configuring]({{< ref "tyk-oss-gateway/configuration#opentelemetry" >}}) distributed tracing behaviour of Tyk Gateway. This includes enabling tracing, configuring exporter types,
```suggestion
- Added support for [configuring]({{< ref "tyk-oss-gateway/configuration#opentelemetry" >}}) distributed tracing behaviour of Tyk Gateway. This includes enabling tracing, configuring exporter types, setting the URL of the tracing backend to which data is to be sent, customising headers, and specifying enhanced connectivity for HTTP, HTTPS and gRPC. Subsequently, users have precise control over tracing behaviour in Tyk Gateway.
```

2023-09-06 11:20 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added trace and span attributes to simplify identifying Tyk API and request meta-data per request. Example span attributes include: _tyk.api.id_, _tyk.api.name_, _tyk.api.orgid_, _tyk.api.tags_, _t
```suggestion
- Added span attributes to simplify identifying Tyk API and request meta-data per request. Example span attributes include: _tyk.api.id_, _tyk.api.name_, _tyk.api.orgid_, _tyk.api.tags_, _tyk.api.path_, _tyk.api.version_, _tyk.api.apikey_, _tyk.api.apikey.alias_ and _tyk.api.oauthid_. This allows users to use OpenTelemetry [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/README.md) to filter and create metrics for increased insight and observability.
```

2023-09-06 11:20 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support to configure OpenTelemetry [sampling types]({{< ref "tyk-oss-gateway/configuration#opentelemetrysampling" >}}) (probabilistic, rate limiting, and adaptive) in the Tyk Gateway. This al
```suggestion
- Added support to configure OpenTelemetry [sampling types and rates]({{< ref "tyk-oss-gateway/configuration#opentelemetrysampling" >}}) in the Tyk Gateway. This allows users to manage the need for collected detailed tracing information against performance and resource usage requirements.
```

2023-09-06 11:20 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added configuration parameter to enable/disable [detail_tracing]({{< ref "advanced-configuration/opentracing#step-2-enable-at-api-level" >}}) for Tyk Classic API.
Is it a correct link after restructuring the Distributed Tracing section?

2023-09-06 14:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added configuration parameter to enable/disable [detail_tracing]({{< ref "advanced-configuration/opentracing#step-2-enable-at-api-level" >}}) for Tyk Classic API.
OpenTel enabled link in paragraph line 70 was obtained from a related PR. Preview is [here](https://deploy-preview-3173--tyk-docs.netlify.app/docs/nightly/tyk-oss-gateway/configuration/#opentelemetryenabled)

The current link for enabling detailed_tracing is _advanced-configuration/opentracing#step-2-enable-at-api-level_, e.g. [in this preview](https://deploy-preview-3173--tyk-docs.netlify.app/docs/nightly/advanced-configuration/opentracing/#enabling-distributed-tracing)

@sredxny @mativm02 Is the path for enabling/disabling detailed tracing correct? If not what would be the correct link path?

2023-09-06 14:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support to configure OpenTelemetry [sampling types]({{< ref "tyk-oss-gateway/configuration#opentelemetrysampling" >}}) (probabilistic, rate limiting, and adaptive) in the Tyk Gateway. This al
Thanks @caroltyk I have updated PR with suggestion

2023-09-06 14:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added trace and span attributes to simplify identifying Tyk API and request meta-data per request. Example span attributes include: _tyk.api.id_, _tyk.api.name_, _tyk.api.orgid_, _tyk.api.tags_, _t
Thanks @caroltyk I have updated PR with suggestion

2023-09-06 14:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for [configuring]({{< ref "tyk-oss-gateway/configuration#opentelemetry" >}}) distributed tracing behaviour of Tyk Gateway. This includes enabling tracing, configuring exporter types,
Thanks @caroltyk I have updated PR with suggestion

2023-09-06 14:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +In this version, we're introducing a new feature called OpenTelemetry Tracing. This addition gives you improved visibility into how API requests are processed. It's designed to help with plugin devel
Thanks @caroltyk I have updated PR with suggestion

2023-09-06 14:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a critical issue in MDCB deployments, relating to _Control Plane_ stability. The _Control Plane_ Gateway was found to crash with a panic when creating a Tyk OAS API. The bug has been addresse
Thanks @caroltyk I have updated PR with suggestion

2023-09-06 14:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- A new chart has been introduced on the _License Statistics_ page that presents the number of deployed _Data Planes_. This addition enables users to easily monitor their _Data Plane_ usage and  near
Thanks @caroltyk I have removed one of the duplicates

2023-09-07 06:54 UTC, agata-wit submitted a review, later dismissed

2023-09-07 14:27 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a critical issue in MDCB deployments, relating to _Control Plane_ stability. The _Control Plane_ Gateway was found to crash with a panic when creating a Tyk OAS API. The bug has been addresse
Thanks @dcs3spp for moving this to gateway. Could you review the wording changes too?

2023-09-11 15:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a critical issue in MDCB deployments, relating to _Control Plane_ stability. The _Control Plane_ Gateway was found to crash with a panic when creating a Tyk OAS API. The bug has been addresse
Many thanks @caroltyk, I have updated the wording changes also.

2023-09-12 09:13 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added configuration parameter to enable/disable [detail_tracing]({{< ref "advanced-configuration/opentracing#step-2-enable-at-api-level" >}}) for Tyk Classic API.
https://deploy-preview-3212--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview/#step-2-enable-detailed-tracing-at-api-level-optional

2023-09-12 09:14 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added configuration parameter to enable/disable [detail_tracing]({{< ref "advanced-configuration/opentracing#step-2-enable-at-api-level" >}}) for Tyk Classic API.
The above is from latest PR #3212

2023-09-12 09:30 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added configuration parameter to enable/disable [detail_tracing]({{< ref "advanced-configuration/opentracing#step-2-enable-at-api-level" >}}) for Tyk Classic API.
Hi @caroltyk I have updated the link and CI link checks erroring. 

Once PR [#3225](https://github.com/TykTechnologies/tyk-docs/pull/3225) and [#3194](https://github.com/TykTechnologies/tyk-docs/pull/3194) have been merged then link check will pass

2023-09-12 09:58 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
using "tyk oas apis" could be confusing since we have official tyk oas apis...can we add the term "api definition"? @dcs3spp @andyo-tyk

2023-09-12 10:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
No, the term Tyk OAS API is used to differentiate from Tyk Classic API.

The "official Tyk OAS APIs" that you mention are, I think, the Swagger/OAS documentation of the Tyk Dashboard API and Tyk Gateway API? I think we need to change this term, rather than the one we are using in the product to describe client APIs.

2023-09-12 10:03 UTC, letzya requested changes
Per my messages, highlights need a slight adjustment

2023-09-12 10:25 UTC, andyo-tyk submitted a review, later dismissed
All good now, thanks.

2023-09-12 10:45 UTC, caroltyk approved these changes, later dismissed
Looks Good! Thank you.

2023-09-12 11:03 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
we can't, it's an industry standard.

2023-09-12 11:10 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
Sorry? I disagree.

It's not an industry standard to describe the OAS documents thart describe the Tyk Gateway API and Tyk Dashboard API as "Tyk OAS APIs". It's up to Tyk how we describe our product's API...

I've suggested before that it's confusing to describe the Tyk Gateway API and Tyk Dashboard API as "Tyk API", given that Tyk is an API management platform so there's a lot of use of the abbreviation "API".

I strongly recommend consistently using the full names for these management APIs to avoid any risk of them being confused with client APIs that are managed with the Dashboard/Gateway - which we now have two different ways of describing: via ther Tyk Classic API definition and the Tyk OAS API definition.

2023-09-12 13:35 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
MAybe I misunderstood but you just added the word "definition" -  `Tyk Classic API definition` and `Tyk OAS API definition` which is what I suggested. Can we add it to the PR?

2023-09-12 14:30 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
Perhaps make the change in the following paragraph?

"With this release we are adding the much requested _Body Transformations_ to the _Tyk OAS API Definition_."

2023-09-12 17:00 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
When reading this heading
@andyo-tyk @letzya 

_#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs_

it could be perceived by a new Tyk user that it could be performing a body transformation of a Tyk OAS schema.

How about having the title as:

_#### Added Configurable Middleware For Body Transformations For APIs managed by Tyk Gateway_

2023-09-12 18:00 UTC, zalbiraw commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
That won't work. We need to specify that this is related to our OAS APIs support. The following would though

#### Added Body Transformations Middleware  For Tyk managed OAS APIs

2023-09-13 08:48 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
Or @letzya @zalbiraw @andyo-tyk 

```suggestion
#### Added Configurable Middleware For Body Transformations For OAS APIs managed by Tyk Gateway
```

2023-09-13 09:37 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Support for WebSocket protocols between client and the Gateway has also been expanded. Instead of only supporting the _graphql-ws protocol_, which is becoming deprecated, we now also support _graphql
this is a good place to add a direct link to the docs that shows how to use it, instead of making the users search for it

2023-09-13 09:45 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Support for WebSocket protocols between client and the Gateway has also been expanded. Instead of only supporting the _graphql-ws protocol_, which is becoming deprecated, we now also support _graphql
Can we also add an external  link to websocket protocol? is this a good link @pvormste ? https://datatracker.ietf.org/doc/html/rfc6455

2023-09-13 09:50 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +In this version, we're introducing the support for _OpenTelemetry Tracing_, the new [open standard](https://opentelemetry.io/) for exposing observability data. This addition gives you improved visibi
@SonjaChevre @dcs3spp if we say `"you can check out our _OpenTelemetry Tracing_ resource."` we should be giving a link ;)

2023-09-13 09:52 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +This makes it possible to isolate faults within the request lifetime through inspecting API and Gateway meta-data. Additionally, performance bottlenecks can be identified within the request lifetime.
```suggestion
*OpenTelemetry* makes it possible to isolate faults within the request lifetime through inspecting API and Gateway meta-data. Additionally, performance bottlenecks can be identified within the request lifetime. API owners and developers can use this feature to understand how their APIs are being used or processed within the Gateway.
```

2023-09-13 09:54 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +We offer support for integrating _OpenTelemetry_ traces with supported source tools such [Jaeger](https://www.jaegertracing.io/), [Dynatrace](https://www.dynatrace.com/support/help/extend-dynatrace/o
@dcs3spp TBH, I think that as a user, I'd expect here to get direct links to the pages in which you can set up tyk with jaeger/newrelic/dynatrace, and not external links which will not help me understand how to use them with tyk.

2023-09-13 09:55 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +With the release of _Tyk Gateway 5.2_, we're introducing a powerful new feature: _OpenTelemetry Tracing_. Over the next year, we'll be deprecating _OpenTracing_. We recommend migrating to _OpenTeleme
`With the release of _Tyk Gateway 5.2_, we're introducing a powerful new feature: _OpenTelemetry Tracing_.` - feels a bit repeated reading this sentence just after i finished reading the exact same thing

2023-09-13 09:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Support for WebSocket protocols between client and the Gateway has also been expanded. Instead of only supporting the _graphql-ws protocol_, which is becoming deprecated, we now also support _graphql
Adding this one for _graphql-transport-ws_ 

https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

2023-09-13 09:58 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +We're thrilled to bring you some exciting enhancements and crucial fixes to improve your experience of Tyk Dashboard.
can we add another sentence like in the gw? `We’re thrilled to bring you some exciting enhancements and crucial fixes to improve your experience with Tyk Gateway. For a comprehensive list of changes, please refer to the detailed [changelog](...)below.`

2023-09-13 10:00 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +With this release we are adding the much requested _Body Transformations_ to _Tyk OAS_. You can now configure middleware for both request and response body transformations and - as a _Tyk Dashboard_
We need a link to that new doc

2023-09-13 10:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +In this version, we're introducing the support for _OpenTelemetry Tracing_, the new [open standard](https://opentelemetry.io/) for exposing observability data. This addition gives you improved visibi
@letzya Many thanks

@SonjaChevre I've added the link ready. Once [#3194](https://github.com/TykTechnologies/tyk-docs/pull/3194) is merged then CI link checks will be ok

2023-09-13 10:26 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +We're thrilled to bring you some exciting enhancements and crucial fixes to improve your experience of Tyk Dashboard.
Done

2023-09-13 10:29 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +With the release of _Tyk Gateway 5.2_, we're introducing a powerful new feature: _OpenTelemetry Tracing_. Over the next year, we'll be deprecating _OpenTracing_. We recommend migrating to _OpenTeleme
Done

2023-09-13 10:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Support for WebSocket protocols between client and the Gateway has also been expanded. Instead of only supporting the _graphql-ws protocol_, which is becoming deprecated, we now also support _graphql
Done

2023-09-13 10:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +We offer support for integrating _OpenTelemetry_ traces with supported source tools such [Jaeger](https://www.jaegertracing.io/), [Dynatrace](https://www.dynatrace.com/support/help/extend-dynatrace/o
Done

2023-09-13 11:43 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Support for WebSocket protocols between client and the Gateway has also been expanded. Instead of only supporting the _graphql-ws protocol_, which is becoming deprecated, we now also support [_graphq
format issue

2023-09-13 12:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Support for WebSocket protocols between client and the Gateway has also been expanded. Instead of only supporting the _graphql-ws protocol_, which is becoming deprecated, we now also support _graphql
Done

2023-09-13 13:48 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +With this release we are adding the much requested _Body Transformations_ to _Tyk OAS_. You can now configure middleware for both request and response body transformations and - as a _Tyk Dashboard_
Done

2023-09-13 13:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Support for WebSocket protocols between client and the Gateway has also been expanded. Instead of only supporting the _graphql-ws protocol_, which is becoming deprecated, we now also support [_graphq
@letzya I've updated italics in the PR to use * instead of _

2023-09-13 15:49 UTC, zalbiraw commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
Reads well to me

2023-09-13 15:54 UTC, letzya approved these changes

2023-09-13 17:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +In this version, we're introducing the support for _OpenTelemetry Tracing_, the new [open standard](https://opentelemetry.io/) for exposing observability data. This addition gives you improved visibi
@letzya @SonjaChevre  Ci links are now ok

2023-09-14 12:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
No, I'm sorry, but we are consistently using the term Tyk OAS API for an API that is composed of an OAS Document and the Tyk vendor specific config in x-tyk-api-gateway.

The ONLY way that I want us to refer to such APIs is as Tyk OAS APIs and, similarly, for any that use Tyk's traditional vendor-specific API definition, we refer to these as Tyk Classic APIs.

There is a clear distinction between:
API - Application Programming Interface - the endpoints that are exposed by a system/service
OAS - Open API Specification - an open standard way to describe the vendor-agnostic aspects of a service (i.e. an API)
OpenAPI Document - a JSON or YAML file containing an OAS-compliant description of an API
API Definition - the description of an API that can be processed by Tyk and used to configure the Tyk Gateway to proxy and manage requests to an upstream service
Tyk Classic API definition - Tyk's vendor specific API definition
Tyk OAS API definition - an API definition consisting of a combination of an OpenAPI Document and Tyk vendor specific elements
Tyk Classic API - an instance, on Tyk Dashboard/Gateway, of an API configured via a Tyk Classic API definition
Tyk OAS API - an instance, on Tyk Dashboard/Gateway, of an API configured via a Tyk OAS API definition

Tyk components are designed with their own management APIs (see definition above):
Tyk Gateway API
Tyk Dashboard API

We have OAS-compliant definitions of both of these APIs, which should correctly be termed:
Tyk Gateway API OAS Document
Tyk Dashboard API OAS Document

We cannot say "OAS APIs managed by Tyk"

2023-09-14 12:47 UTC, andyo-tyk commented
I withdraw my approval if line 18 is changed from
#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs

This is factually correct.

2023-09-14 14:55 UTC, dcs3spp commented
@andyo-tyk Can you check line 18 after latest commit?

2023-09-14 18:31 UTC, letzya requested changes

2023-09-14 18:31 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Configurable Middleware For Body Transformations For Tyk OAS APIs
```suggestion
#### Added Body Transform Middleware to Tyk OAS API definitions
```

2023-09-14 18:39 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added Body Transform Middleware to Tyk OAS API Definitions
```suggestion
#### Added Body Transform Middleware to Tyk OAS API Definition
```

2023-09-14 18:42 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added support for API Developers using *Tyk OAS APIs* to [configure]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#transformbody" >}}) a body transform middleware that operates on API respons
```suggestion
- Added support for API Developers using *Tyk OAS API Definition* to [configure]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#transformbody" >}}) a body transform middleware that operates on API responses. This enhancement ensures streamlined and selective loading of the middleware based on configuration, enabling precise response data customisation at the per-endpoint level.
```

2023-09-14 18:47 UTC, letzya approved these changes

2023-09-14 18:49 UTC, letzya submitted a review, later dismissed

2023-09-14 18:50 UTC, letzya approved these changes

2023-09-14 18:56 UTC, letzya approved these changes

2023-09-14 19:00 UTC, merged