add docs for graphql-transport-ws
TykTechnologies/tyk-docs-hugo pull request #3180
Opened 2023-08-25 11:12 UTC by pvormste

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

This PR adds the documentation for the `graphql-transport-ws` protocol. It also removes an info box where it is mentioned that Tyk only supports the `graphql-ws` protocol.

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2023-08-25 12:53 UTC, buraksezer approved these changes

2023-08-25 15:08 UTC, dcs3spp requested changes
PR looks good @pvormste. I have made minor suggestions. Once done we can merge

2023-08-25 15:08 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +Tyk supports GraphQL via WebSockets using the protocols `graphql-transport-ws` or `graphql-ws` between client and Tyk Gateway.
```suggestion
Tyk supports GraphQL via WebSockets using the protocols _graphql-transport-ws_ or _graphql-ws_ between client and Tyk Gateway.
```

2023-08-25 15:08 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +In order to upgrade the HTTP connection for a GraphQL API to WebSockets by using the `graphql-transport-ws` protocol, the request should contain following headers:
```suggestion
In order to upgrade the HTTP connection for a GraphQL API to WebSockets by using the _graphql-transport-ws_ protocol, the request should contain following headers:
```

2023-08-25 15:08 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +Before sending Queries, Mutations, or Subscriptions via WebSockets the connection needs to be initialized:
```suggestion
The connection needs to be initialised before sending Queries, Mutations, or Subscriptions via WebSockets:
```

2023-08-25 15:08 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +For Queries and Mutations, the Tyk Gateway will respond with a `complete` message including the GraphQL response inside the payload.
Maybe include an example complete message here

2023-08-25 15:08 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +For Subscriptions, the Tyk Gateway will respond with a stream of `next` messages containing the GraphQL response inside the payload until the data stream ends with a `complete` message. It can happen
Maybe add an example after this paragraph

2023-08-25 15:08 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +Be aware of those behaviors:
Capitalise each bullet point and end each one with .

2023-08-25 15:08 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +  - if no `connection_init` message is sent after 15 seconds after opening the connection, then the connection will be closed
```suggestion
- If no `connection_init` message is sent after 15 seconds after opening, then the connection will be closed.
```

2023-08-25 15:08 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +**Sending queries**
Maybe include these under and examples heading?

2023-08-25 15:08 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +For Queries and Mutations, the Tyk Gateway will respond with a `complete` message including the GraphQL response inside the payload.
```suggestion
For Queries and Mutations, the Tyk Gateway will respond with a `complete` message, including the GraphQL response inside the payload.
```

2023-08-28 11:17 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +Tyk supports GraphQL via WebSockets using the protocols `graphql-transport-ws` or `graphql-ws` between client and Tyk Gateway.
Done!

2023-08-28 11:17 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +In order to upgrade the HTTP connection for a GraphQL API to WebSockets by using the `graphql-transport-ws` protocol, the request should contain following headers:
Done!

2023-08-28 11:18 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +Before sending Queries, Mutations, or Subscriptions via WebSockets the connection needs to be initialized:
Done!

2023-08-28 11:19 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +For Queries and Mutations, the Tyk Gateway will respond with a `complete` message including the GraphQL response inside the payload.
I thought about it, but I came to the conclusion that this would add visual noise to the docs without adding much value as those response messages are not very exciting to read.
Let me know what you think!

2023-08-28 11:19 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +For Subscriptions, the Tyk Gateway will respond with a stream of `next` messages containing the GraphQL response inside the payload until the data stream ends with a `complete` message. It can happen
Same as before ^

2023-08-28 11:19 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +Be aware of those behaviors:
Done!

2023-08-28 11:20 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +  - if no `connection_init` message is sent after 15 seconds after opening the connection, then the connection will be closed
Done!

2023-08-28 11:20 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +**Sending queries**
Good idea, added an example heading!

2023-08-28 11:20 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +For Queries and Mutations, the Tyk Gateway will respond with a `complete` message including the GraphQL response inside the payload.
Done!

2023-08-29 09:40 UTC, dcs3spp commented on tyk-docs/content/graphql/graphql-websockets.md
> +For Queries and Mutations, the Tyk Gateway will respond with a `complete` message including the GraphQL response inside the payload.
Is the _complete_ message something like:

```json
{
    "complete": { 
        "response": { "graphQL": "a response" }
}
```

2023-08-29 11:37 UTC, agata-wit approved these changes
Good from my side

2023-08-29 14:27 UTC, pvormste commented on tyk-docs/content/graphql/graphql-websockets.md
> +For Queries and Mutations, the Tyk Gateway will respond with a `complete` message including the GraphQL response inside the payload.
The complete message looks like this:
```
{ "id": "1": "type": "complete" }
```
The protocol can be found here: https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

2023-08-30 09:32 UTC, agata-wit commented on tyk-docs/content/graphql/graphql-websockets.md
> +For Queries and Mutations, the Tyk Gateway will respond with a `complete` message including the GraphQL response inside the payload.
@dcs3spp I've added the sample message.

2023-08-31 10:12 UTC, dcs3spp approved these changes

2023-09-05 09:43 UTC, merged