[TT-9769] Rename helm charts
TykTechnologies/tyk-docs-hugo pull request #3183
Opened 2023-08-28 10:30 UTC by komalsukhani

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

Rename helm charts as follow
- tyk-stack (formerly called tyk-single-dc)

- tyk-control-plane (formerly called tyk-mdcb-control-plane)

- tyk-data-plane (formerly called tyk-mdcb-data-plane)

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-29 08:37 UTC, dcs3spp requested changes
PR looks good, however there is a broken link reported in the CI checks. If look in the output this references `tyk-self-managed/tyk-helm-chart-single-dc`

It could be that this is referenced somewhere else still after being removed from the menu.yaml?

2023-08-31 13:56 UTC, caroltyk approved these changes

2023-10-03 15:10 UTC, letzya commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-tyk-stack.md
> +aliases:
@dcs3spp we cant just rename a url, we need to move it to the appropriate location.

2023-10-03 15:12 UTC, letzya commented on tyk-docs/data/menu.yaml
>              - title: "Tyk new Helm chart"
@caroltyk are you sure about the "New"? shouldn't we add a message that it's new, in the body of the page? and in the release notes?

2023-10-03 15:15 UTC, letzya requested changes
release label is missing  + other comments in the PR

2023-10-19 10:45 UTC, komalsukhani commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-tyk-stack.md
> +aliases:
Sorry. Will fix it.

2023-10-19 11:07 UTC, letzya commented
@dcs3spp flagging out an issue with renaming a file

2023-10-24 11:19 UTC, letzya commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +`tyk-hybrid` will be deprecated soon. Please use our new Helm Chart for Tyk Hybrid Data Plane at [tyk-data-plane]({{<ref "/tyk-cloud/environments-deployments/hybrid-gateways">}}) instead.
```suggestion
`tyk-hybrid` will be deprecated soon. Please use our new Helm Chart for Tyk Hybrid Data Plane at [tyk-data-plane]({{<ref "tyk-cloud/environments-deployments/hybrid-gateways">}}) instead. 
```

2023-10-24 16:26 UTC, letzya commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +To deploy Tyk Self Managed (for single data center) using the new helm chart, please use [tyk-stack](https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-stack) chart.
@caroltyk why don't we send them to artifact hub? and give the GH link as a side note?

2023-10-24 16:35 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-tyk-stack.md
> +aliases:
Fixed and moved to tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md

2023-10-24 16:36 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
>              - title: "Tyk new Helm chart"
@letzya as discussed resolving the comment and can raise a new PR later

2023-10-25 22:37 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +To deploy Tyk Self Managed (for single data center) using the new helm chart, please use [tyk-stack](https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-stack) chart.
@letzya We have tracking on GH so we could get more information there, don't we?

2023-11-01 10:38 UTC, dcs3spp approved these changes

2023-11-01 10:39 UTC, merged

2023-11-01 10:39 UTC, dcs3spp commented
/release to release-5.2