[TT-7979] Adding docs page: How to instrument plugins with OpenTelemetry
TykTechnologies/tyk-docs-hugo pull request #3184
Opened 2023-08-28 13:04 UTC by mativm02

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?modal=detail&selectedIssue=TT-9797
### Description

I'm adding a new page in the Plugins section to let the users know how to instrument them with our OpenTelemetry library.  Most of the content has been extracted from this confluence page: https://tyktech.atlassian.net/l/cp/eYWqgmAC
Please, let me know if this is an appropriate section to put this content in, and whether I'm missing something or not.
#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-29 14:30 UTC, dcs3spp requested changes
PR looks @mativm02. I have added some minor suggestions. Once suggestions and peer review performed then we can merge.

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +## Prerequesites
```suggestion
## Prerequisites
```

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +- Go (at the moment it's the only supported language)
Is there a specific version of Go required, e.g. 1.19?

```suggestion
- Go
```

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +- Gateway instance with OpenTelemetry and DetailedTracing enabled:
Maybe add a brief sentence explaining what enabling detailed tracing does?

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +The function takes three parameters:
Maybe insert a blank line before this paragraph.

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +```go
Before the code example, add one or two sentences that explain what it shows.

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +This updated span will then appear in the traces as `AddFooBarHeader Testing` with an **OK Status**. The second parameter receives a description, but this one is only valid for **ERROR** status.
```suggestion
This updated span will then appear in the traces as `AddFooBarHeader Testing` with an **OK Status**.

The second parameter of the `SetStatus` method can accept a description parameter that is valid for **ERROR** statuses.
```

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +You can set attributes on your spans, enriching each trace with additional, context-specific information by using the `SetAttributes()` function.
```suggestion
The `SetAttributes()` function allows you to set attributes on your spans, enriching each trace with additional, context-specific information.
```

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +How the `go_plugin` attribute looks in Jaeger:
```suggestion
The illustration below, shows how the `go_plugin` attribute looks in Jaeger:
```

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +To better trace the execution of your plugin, you can create additional spans for each function execution. By using context propagation, you can link these spans, creating a detailed trace that cover
```suggestion
To effectively trace the execution of your plugin, you can create additional spans for each function execution. By using context propagation, you can link these spans, creating a detailed trace that covers multiple function calls. This allows you to better understand the sequence of operations, pinpoint performance bottlenecks, and analyze application behaviour.
```

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +How this new child span looks in Jaeger:
```suggestion
The illustration below, shows how this new child looks in Jaeger:
```

2023-08-29 14:30 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +In OpenTelemetry, it's essential to understand the distinction between recording an error and setting the span status to error. The `RecordError()` function records an error as an exception span even
How is the exception span event raised? Does it raise an error like in a try...catch block or is it published to subscribers/listeners?

2023-08-29 15:09 UTC, carolwkc commented on tyk-docs/content/plugins/otel-plugins.md
> +$ go get github.com/TykTechnologies/opentelemetry
is there any requirement on go version?

2023-08-29 15:09 UTC, caroltyk commented on tyk-docs/content/plugins/otel-plugins.md
> +
Suggest adding an introduction: 

By instrumenting your custom plugins with Tyk's OpenTelemetry library, you can gain additional insights into custom plugin behaviour like time spent and exit status. Read on to see some examples of creating span and setting attributes for your custom plugins.

2023-08-29 15:10 UTC, caroltyk commented
Look good @mativm02 . Added some minor comments.

2023-08-29 15:20 UTC, mativm02 commented on tyk-docs/content/plugins/otel-plugins.md
> +- Go (at the moment it's the only supported language)
@dcs3spp AFAIK there is not, but we've been testing it using 1.19 - maybe it'd be worth it to recommend users to use it (or a higher one)

2023-08-29 15:27 UTC, mativm02 commented on tyk-docs/content/plugins/otel-plugins.md
> +In OpenTelemetry, it's essential to understand the distinction between recording an error and setting the span status to error. The `RecordError()` function records an error as an exception span even
@dcs3spp you can use a try...catch block in your code (actually, the Go's equivalent) and if there's an exception, you can record the error and stop the execution of the plugin. Then, in your span, you'll see the error description and some more useful information (take a look at the last image)

2023-08-29 15:28 UTC, mativm02 commented on tyk-docs/content/plugins/otel-plugins.md
> +$ go get github.com/TykTechnologies/opentelemetry
@caroltyk we've been building and testing it using Go v1.19, so I added it as a recommended version (or higher ones). It should also work with older versions as well (1.17 and 1.18 at least)

2023-08-29 15:32 UTC, mativm02 commented
@dcs3spp @caroltyk Thanks for the suggestions, guys! I've already applied them, let me know how it looks now :)

2023-08-31 08:33 UTC, tbuchaillot requested changes

2023-08-31 08:33 UTC, tbuchaillot commented on tyk-docs/content/plugins/otel-plugins.md
> +  "detailed_tracing":true
this configuration doesn't exist here - it's at API level

2023-08-31 08:33 UTC, tbuchaillot commented on tyk-docs/content/plugins/otel-plugins.md
> +By instrumenting your custom plugins with Tyk's OpenTelemetry library, you can gain additional insights into custom plugin behaviour like time spent and exit status. Read on to see some examples of c
@mativm02 isn't the time spent information already there without needing extra instrumentation? The user will be able to see the span for the go plugin independently if they add more info or not.

2023-08-31 08:33 UTC, tbuchaillot commented on tyk-docs/content/plugins/otel-plugins.md
> +`trace.NewSpanFromContext()` is a function that helps you create a new span from the current request context. When called, it returns two values: a fresh context with the newly created span embedded
I'd the three params here as the function signature

2023-08-31 10:09 UTC, dcs3spp approved these changes

2023-08-31 12:43 UTC, mativm02 commented on tyk-docs/content/plugins/otel-plugins.md
> +By instrumenting your custom plugins with Tyk's OpenTelemetry library, you can gain additional insights into custom plugin behaviour like time spent and exit status. Read on to see some examples of c
@tbuchaillot that's correct, but you can see it in a more granular way if you add multiple spans (you can know how much time each span/function took to finish) - let me make a small modification

2023-08-31 12:48 UTC, mativm02 commented on tyk-docs/content/plugins/otel-plugins.md
> +  "detailed_tracing":true
@tbuchaillot but this is a prerequisite:

> Gateway instance with OpenTelemetry and DetailedTracing enabled

I think it's worth it to keep it there just to let the user know what we're talking about in that sentence

2023-08-31 13:57 UTC, tbuchaillot requested changes

2023-08-31 13:57 UTC, tbuchaillot commented on tyk-docs/content/plugins/otel-plugins.md
> +```json
@mativm02 this configuration doesn't exist

2023-08-31 14:42 UTC, tbuchaillot commented on tyk-docs/content/plugins/otel-plugins.md
> +At the API level add this configuration:
I'd specify it's in the API definition instead of "At the API level".  What do you think @dcs3spp ?

2023-09-04 07:38 UTC, tbuchaillot approved these changes

2023-09-04 12:36 UTC, letzya commented on tyk-docs/content/plugins/otel-plugins.md
> +  - "/plugins/otel-plugins"
@dcs3spp 
1. Why do we need this alias?
2. The file is not in the correct file path

2023-09-04 12:38 UTC, letzya commented
@dcs3spp Added a comment. Please check before merging this pr

2023-09-04 12:51 UTC, mativm02 commented on tyk-docs/content/plugins/otel-plugins.md
> +  - "/plugins/otel-plugins"
@letzya 

1. I copied it from the other plugin files from the same path (`how-to-serve-plugins.md`, `supported-languages.md`, etc.) but didn't find any explanation of this in the [Contributor Guide](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) - should we remove this?
2. I put this file where all the plugin documentation is located. What would be the correct file path? 🤔

2023-09-04 12:58 UTC, dcs3spp requested changes
lgtm I spotted something that I missed in previous review, making **Note** into note box with green border outline

2023-09-04 12:58 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +**Note**: DetailedTracing is required to see the plugin spans in the traces.
Update this so it appears in a note bounded box

2023-09-04 13:12 UTC, dcs3spp commented on tyk-docs/content/plugins/otel-plugins.md
> +  - "/plugins/otel-plugins"
Hi @mativm02 Aliases are used when a page is moved to a new file location. There is a note about it in this section of the [contributors guide](https://tyktech.atlassian.net/wiki/spaces/EN/pages/1888976900/The+Docs+Bible+-+A+Guide+For+The+Docs+Contributor#New-Website-Content-Guidelines%5BhardBreak%5D). They allow a file to be accessed by different URLs (aliases). In the above case the alias can be removed in lines 8-9.

2023-09-04 13:14 UTC, dcs3spp commented
> @dcs3spp Added a comment. Please check before merging this pr

@letzya

What is the required file path for _tyk-docs/content/plugins/otel-plugins.md_?

2023-09-05 10:07 UTC, SonjaChevre commented on tyk-docs/content/plugins/otel-plugins.md
> +- Gateway instance with OpenTelemetry and DetailedTracing enabled
would be great to add a link to the general OTel documentation for Tyk Gateway here -> for cross reference.

2023-09-05 13:05 UTC, mativm02 commented on tyk-docs/content/plugins/otel-plugins.md
> +- Gateway instance with OpenTelemetry and DetailedTracing enabled
@SonjaChevre thanks! We'll wait for Sredny's documentation to be merged so we can add this.

2023-09-06 15:25 UTC, caroltyk commented
@mativm02 is it the latest PR? The configurations for detailed_tracing is not updated yet

`
"opentelemetry": {
  "enabled": true,
  "detailed_tracing":true
}
`

2023-09-11 17:31 UTC, dcs3spp approved these changes
lgtm @mativm02 Once a peer review has been approved by @SonjaChevre and @caroltyk we can merge

2023-09-12 12:27 UTC, caroltyk approved these changes
LGTM thanks!

2023-09-13 06:03 UTC, SonjaChevre commented
hi @mativm02 and @dcs3spp,
I have spotted two minor things:

the colon is red, making it looks like an error:
<img width="703" alt="Screenshot 2023-09-13 at 08 00 14" src="https://github.com/TykTechnologies/tyk-docs/assets/17831497/4899acb2-fd50-4f37-892b-317c744b607f">

Character issue with Official OpenTelemetry&rsquo;s Go SDK
<img width="705" alt="Screenshot 2023-09-13 at 08 00 33" src="https://github.com/TykTechnologies/tyk-docs/assets/17831497/3d8131d5-06c2-4bb2-b22b-fe26f497c4ee">

Once fixed, good for me! thanks

2023-09-13 17:09 UTC, merged

2023-12-06 13:08 UTC, dcs3spp commented
/release to release-5.1