AAI 5.2 docs
TykTechnologies/tyk-docs-hugo pull request #3185
Opened 2023-08-28 13:23 UTC by agata-wit

### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-29 09:10 UTC, dcs3spp requested changes
Many thanks @agata-wit. Suggested some minor changes but overall PR looks good to me.

2023-08-29 09:10 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/concepts/header_management.md
> +                        "datasource1": "$tyk_context.jwt_claims_datasource1"
Should we briefly explain the naming scheme, e.g. datasource1, datasource2 etc?

2023-08-29 09:10 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/concepts/header_management.md
> +In cases where user sets the same header name both for a global and data source header, but different values, the value set at data source header level takes priority.
```suggestion
If a header has a value at the data source and global level, then the data source value takes precedence.
```

2023-08-29 09:10 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/concepts/header_management.md
> +`global` header name is used both for global level and data source level header, but the values are different. Value `data-source-value` will take priority over `global-header-value` and in the end t
```suggestion
The `global` header name is used globally and there is also a data source level header, with a different value. Value `data-source-value` will take priority over `global-header-value`, resulting in the following headers being sent to the data source:
```

2023-08-29 09:10 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/datasources/rest.md
> +4. Click *Save & Update API* button to persist the configuration and generate a REST resolver, which will resolve this field at runtime.
```suggestion
4. Click the *Save & Update API* button to persist the configuration and generate a REST resolver, to  resolve this field at runtime.
```

2023-08-29 09:10 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/datasources/rest.md
> +5. Click *Save & Update API* button to persist the configuration and generate a REST resolver, which will resolve this field at runtime.
```suggestion
5. Click the *Save & Update API* button to persist the configuration and generate a REST resolver, to resolve this field at runtime.
```

2023-08-29 09:10 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/udg-getting-started/connect-datasource.md
> + When using Tyk Dashboard UI data source name will be created automatically by concatenating the field name and the type name with an underscore symbol in between. This name is editable and can be ch
```suggestion
When configuring a datasource name with Tyk Dashboard, a default name is created automatically by concatenating the field name and the GraphQL type name with an underscore symbol in between. For example, _getUserById_Query_. This name is editable and can be changed by the user.
```

2023-08-29 09:10 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/udg-getting-started/connect-datasource.md
> +It is important to save datasource configuration in order to reflect the changes in your API definition.
```suggestion
It is important to save the datasource configuration in order to reflect the changes in your API definition.
```

2023-08-29 09:10 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/concepts/header_management.md
> +With Tyk v5.2 the possibilities of managing headers for Universal Data Graph and all its data sources have been extended.
```suggestion
With Tyk v5.2 the possibilities of managing headers for Universal Data Graph and all associated data sources have been extended.
```

2023-08-29 11:40 UTC, agata-wit commented on tyk-docs/content/universal-data-graph/concepts/header_management.md
> +                        "datasource1": "$tyk_context.jwt_claims_datasource1"
There's no naming scheme as such. Users can use whatever header names they want. This is just an example, no real convention needs to be followed.

2023-08-29 14:05 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/concepts/header_management.md
> +                        "datasource1": "$tyk_context.jwt_claims_datasource1"
Ah I think I get it, I was trying to understand how the GW distinguishes between a global and data source header from the config, for example:

```json
                "config": {
                    "headers": {
                        "a": "different-value",
                        "b": "$tyk_context.jwt_claims_datasource_global"
```

How do I know which is global (a or b)? 

I think the way it works is it depends on the where the headers config item exists, yes?
For example if it is in the API endpoint level then it is a datsource header, otherwise it is global?

2023-08-30 09:16 UTC, agata-wit commented on tyk-docs/content/universal-data-graph/concepts/header_management.md
> +                        "datasource1": "$tyk_context.jwt_claims_datasource1"
None of those is a global header. Global header are defined in a different section, it's explained earlier in the doc. All the headers in your example are defined in a data source headers section, so all of them are only applicable for THAT data source.
However if `global_headers` section also has a header name "a" then "a" value from global headers section will be ignored and the "a" value from data source section will be used.

2023-08-31 11:39 UTC, dcs3spp commented on tyk-docs/content/universal-data-graph/concepts/header_management.md
> +                        "datasource1": "$tyk_context.jwt_claims_datasource1"
Many thanks @agata-wit I've read through the changes and yep that makes more sense. I'll approve the PR and if we can get a peer review approved then I think we are ready for release

2023-08-31 11:40 UTC, dcs3spp approved these changes

2023-08-31 11:50 UTC, dcs3spp commented
@agata-wit I've approved. Once peer reviewed I think is ready for release

2023-09-01 08:20 UTC, agata-wit commented
@dcs3spp it's been peer reviewed in Confluence before I dropped it here.

2023-09-04 08:55 UTC, kofoworola approved these changes

2023-09-04 08:58 UTC, jay-deshmukh approved these changes

2023-09-05 08:53 UTC, merged