TT-7903 added otel in distributed tracing section
TykTechnologies/tyk-docs-hugo pull request #3186
Opened 2023-08-29 00:50 UTC by sredxny

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-29 01:14 UTC, sredxny commented on tyk-docs/content/advanced-configuration/opentracing.md
> +For more in-depth information on the configuration options available, please refer to our [OpenTelemetry Configuration Details Page](https://tyk.io/docs/tyk-oss-gateway/configuration/#opentelemetry).
This links should be updated once we re-generate and release the config options of otel

2023-08-29 08:24 UTC, tbuchaillot commented on tyk-docs/content/advanced-configuration/opentracing.md
> +After enabling OpenTelemetry at the gateway level, activate it for the specific APIs you want to monitor. Edit the respective API definition to set `detailed_tracing` to `true`.
What `detailed_tracing ` do? How does an API trace looks with and without detailed_tracing enabled?

2023-08-29 08:24 UTC, tbuchaillot commented on tyk-docs/content/advanced-configuration/opentracing.md
> +#### Customizing Tracing
What's the customizable part of this?

2023-08-29 08:25 UTC, tbuchaillot commented on tyk-docs/content/advanced-configuration/opentracing.md
> +- `tyk.api.path`: API listen path
Please add as well resource attributes

2023-08-29 08:26 UTC, tbuchaillot commented on tyk-docs/content/advanced-configuration/opentracing.md
> +Tyk supports context propagation and configurable sampling strategies ("AlwaysOn", "AlwaysOff", "TraceIDRatioBased").
How can you set different ratios? How does this affect the traces? More info

2023-08-29 09:23 UTC, dcs3spp requested changes
PR looks good to me @sredxny. I made some minor suggestions. Once review comments have been addressed we can merge the PR.

2023-08-29 09:23 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/opentracing.md
> +Alternatively, you can use the equivalent environment variable to enable OpenTelemetry.
Name and link the equivalent environment variable here

2023-08-29 09:23 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/opentracing.md
> +After enabling OpenTelemetry at the gateway level, activate it for the specific APIs you want to monitor. Edit the respective API definition to set `detailed_tracing` to `true`.
similar to comment above, what kind of information will detailed tracing log and maybe include an example of an API trace.

2023-08-29 09:23 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/opentracing.md
> +- `tyk.api.name`: API name
For consistent styling with other bullet points end the bullet points below with .
```suggestion
- `tyk.api.name`: API name.
```

2023-08-29 09:23 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/opentracing.md
> +When tagging is enabled in the API definition, tags are added as another span attribute, keyed as `tyk.api.tags`.
```suggestion
When tagging is enabled in the API definition, tags are added as another span attribute. These are keyed as `tyk.api.tags`.
```

2023-09-01 02:53 UTC, sredxny commented
@tbuchaillot @dcs3spp lets close this, and review https://github.com/TykTechnologies/tyk-docs/pull/3212

There I addressed all your comments, and also contains the new structure of the distributed tracing section

2023-09-01 02:53 UTC, closed without merging

2023-09-01 02:53 UTC, sredxny commented
closing in favor of: https://github.com/TykTechnologies/tyk-docs/pull/3212