[WIP] [DX-678] OpenTelemetry tracing integration
TykTechnologies/tyk-docs-hugo pull request #3190
Opened 2023-08-29 15:08 UTC by mativm02

### For internal users - please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?modal=detail&selectedIssue=TT-9797
---
### Preview Link

https://deploy-preview-3190--tyk-docs.netlify.app/docs/nightly/advanced-configuration/distributed-tracing/otel_jaeger/
### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-08-31 09:08 UTC, dcs3spp requested changes
Hi @mativm02 Thanks for submitting the draft PR. Looks good so far. I have made some minor suggestions

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +**Prerequisites:**
```suggestion
## Prerequisites
```

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +- Docker installed on your machine
Add external link to docker installation here and remove step 1

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +Also, you can modify the `exporter` value to `http` if you want to use the HTTP protocol instead of gRPC.
Add a blank line before this paragraph

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +  health_check:
Is this a parent element of the items on the next line

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +**NOTE**: Indicate the folder containing your APIs by setting the TYK_APPS environment variable. By default, the apps folder in the Docker Compose file's location will be used for loading the APIs.
I like that you have explained what the default apps folder is in the docker-compose file. Add a link to the docs for TYK_APPS environment variable and use a shortcode for the note to display the note in a green border.

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +# Deploying Tyk Gateway with OpenTelemetry and Jaeger on Kubernetes
Should this be added as a separate page?

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +**Note:** The Jaeger UI will be available at `jaeger-all-in-one-query:16686`.
Use shortcodes for note so it is displayed in green border

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +1. Tyk Configuration - Enable OpenTelemetry in Tyk by setting environment variables:
How does this the json sample below relate to configuring OpenTelemetry by environment variables. Is it somewhere within a helm chart?

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +TYK_GW_OPENTELEMETRY_ENABLED=true
Are these environment variables set in bash shell or within a helm chart? If they are included within a bash shell should they be exported?

2023-08-31 09:08 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +1. Tyk Configuration - Enable OpenTelemetry in Tyk by setting environment variables:
Make steps 1 and 2 headings for consistency with other section, e.g.

#### 1. Configure OpenTelemetry in Tyk by setting environment variables:

#### 2. Install/Upgrade Tyk using Helm:

2023-09-01 12:49 UTC, mativm02 commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +  health_check:
@dcs3spp no, it's not the parent, it's just an empty field. I got this configuration from: https://tyktech.atlassian.net/wiki/spaces/EN/pages/2110062656/Install+the+latest+Opentelemetry+Enabled+Tyk+Gateway+Jaeger#Docker-Installation

2023-09-01 13:04 UTC, mativm02 commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +# Deploying Tyk Gateway with OpenTelemetry and Jaeger on Kubernetes
@dcs3spp I was thinking of dividing the pages depending on the tracing backend (Jaeger, New Relic, Dynatrace). So this Jaeger page would contain content about Jaeger (using Docker and Kubernetes). What do you think?

2023-09-01 13:11 UTC, mativm02 commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +TYK_GW_OPENTELEMETRY_ENABLED=true
@dcs3spp added `export` keywords, thanks

2023-09-01 13:37 UTC, mativm02 commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +1. Tyk Configuration - Enable OpenTelemetry in Tyk by setting environment variables:
@dcs3spp I'll investigate this one too - will update this comment when I have more info. Thanks!

2023-09-01 13:47 UTC, mativm02 commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +1. Tyk Configuration - Enable OpenTelemetry in Tyk by setting environment variables:
@dcs3spp done! Let me know how it looks now

2023-09-01 13:48 UTC, mativm02 commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +- Docker installed on your machine
done!

2023-09-01 14:05 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +# Deploying Tyk Gateway with OpenTelemetry and Jaeger on Kubernetes
Ok yep, be mindful of the structure so that it keeps in synch with the structure that @sredxny is working on. There was a PR created [here](https://github.com/TykTechnologies/tyk-docs/pull/3194) that fixed an issue with link errors that Sredny encountered

2023-09-02 02:16 UTC, sredxny commented
@mativm02 what about if we add an overview page? just like a main page where we mention that we support x, y, z integration and then start to develop each of them? @dcs3spp

2023-09-04 12:11 UTC, mativm02 commented
> @mativm02 what about if we add an overview page? just like a main page where we mention that we support x, y, z integration and then start to develop each of them? @dcs3spp

@sredxny what do you think about adding a heading in https://github.com/TykTechnologies/tyk-docs/pull/3212 named "Supported Integrations" where you mention each supported backend, with a hypertext to redirect users to the respective pages? I think it'd be better than creating a whole page just to redirect users 🤔

2023-09-05 11:06 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/distributed-tracing/otel_jaeger.md
> +1. Tyk Configuration - Enable OpenTelemetry in Tyk by setting environment variables:
Thanks @mativm02 I have had a look at preview link. For consistent styling we should to the same for the sub steps in section 2: Configure OpenTelemetry Collector so that the formatting is consistent

2023-09-07 17:25 UTC, dcs3spp commented
Closing since replaced by this PR (https://github.com/TykTechnologies/tyk-docs/pull/3225) to use the new OTel structure

2023-09-07 17:26 UTC, dcs3spp commented
Closing since replaced by this PR (https://github.com/TykTechnologies/tyk-docs/pull/3225) to use the new OTel structure

2023-09-07 17:26 UTC, closed without merging