TT-7903 DX-661 document otel tracing concepts
TykTechnologies/tyk-docs-hugo pull request #3212
Opened 2023-09-01 02:50 UTC by sredxny

### https://tyktech.atlassian.net/browse/DX-661
---
### Preview Link

### Description
Added a page to explain the otel tracing concepts.  Details of what is expected can be found in https://tyktech.atlassian.net/browse/TT-9797

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-09-01 09:34 UTC, caroltyk requested changes
Looks good overall! Added some clarifications comments.

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +After enabling OpenTelemetry at the gateway level, you can activate it for specific APIs you wish to monitor. To do so, edit the respective API definition and set the `detailed_tracing` option to eit
Is it an optional step, since detailed_tracing should have a default value set to false?

```suggestion
### Step 2: Enable Detailed Tracing at API Level (Optional)
After enabling OpenTelemetry at the gateway level, you can activate detailed tracing for specific APIs you wish to monitor. To do so, edit the respective API definition and set the `detailed_tracing` option to either true or false.
```

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +
Would be nice to have an example screenshot

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +
Would be nice to have an example screenshot

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +## Enabling OpenTelemetry in Two Steps
Let's explain how to configure connection to opentelemetry backend first. Provide links to example integrations here.

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +In OpenTelemetry, resource attributes provide contextual information about the entity that produced the telemetry data. Unlike span attributes, which are specific to individual operations (e.g., requ
Suggest to move "Span Attributes" section before "Resource Attributes", since in this description, it's making reference to span attributes.

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +When tagging is enabled in the API definition, tags are added as another span attribute. These are keyed as `tyk.api.tags`.
```suggestion
- `tyk.api.tags`: If tagging is enabled in the API definition, the tags are added here.
```

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Tyk supports context propagation as well as configurable sampling strategies through the Sampling configuration structure. Below are the options you can customize:
```suggestion
### Context Propagation
Tyk supports context propagation 

### Sampling Strategies
Tyk supports configurable sampling strategies through the Sampling configuration structure. Below are the options you can customize:
```

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Tyk supports context propagation as well as configurable sampling strategies through the Sampling configuration structure. Below are the options you can customize:
Please add explanation for context propagation. Anything to configure there?

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Tyk supports context propagation as well as configurable sampling strategies through the Sampling configuration structure. Below are the options you can customize:
Please add which field to configure for sampling strategy.

2023-09-01 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/distributed-tracing-overview.md
> +Tyk currently supports OpenTelemetry and OpenTracing for distributed tracing. Support for OpenTelemetry is available since Tyk 5.2+. If this is a valuable feature for you, please leave a comment on t
```suggestion
Tyk currently supports OpenTelemetry and OpenTracing for distributed tracing. Support for OpenTelemetry is available since Tyk 5.2+. If you have any comments and suggestions for this feature, please leave a comment on this [community forum post](https://community.tyk.io/t/faq-opentelemetry-distributed-tracing/5682).
```

2023-09-01 12:31 UTC, mativm02 requested changes
Overall, it looks good. Only one change was requested.

Anyways, I would add some images since it seems a bit empty. You may show differences between detailed and not detailed traces, span attributes, and so on.

2023-09-01 12:31 UTC, mativm02 commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +After enabling OpenTelemetry at the gateway level, you can activate it for specific APIs you wish to monitor. To do so, edit the respective API definition and set the `detailed_tracing` option to eit
I was about to write the same. I'd specify that this is optional and, if possible, add images (or a description, maybe?) showing the differences between a not detailed tracing and a detailed one. What do you think @sredxny?

EDIT: I saw you're already explaining the differences below. Still, I would clarify that this step is optional :)

2023-09-01 17:09 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Tyk supports context propagation as well as configurable sampling strategies through the Sampling configuration structure. Below are the options you can customize:
@caroltyk nothing to configure here, only sampling (type, rate, parentBased) which are described below. So, you think we should remove the text and jump directly into the explanation of the configs?

2023-09-01 17:19 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +## Enabling OpenTelemetry in Two Steps
@caroltyk we have a different ticket to document integrations, do you think it should go in a different page and here only set a link? This is the ticket https://tyktech.atlassian.net/browse/TT-9797

2023-09-01 19:58 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +## Enabling OpenTelemetry in Two Steps
We can provide a link here.

2023-09-01 20:21 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Tyk supports context propagation as well as configurable sampling strategies through the Sampling configuration structure. Below are the options you can customize:
@sredxny I'd like to separate Context Propagation & Sampling Strategies as two Advanced Capabilities. For context propagation, just want to expand a bit about what does it mean.

2023-09-02 02:24 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +## Enabling OpenTelemetry in Two Steps
@caroltyk agree, so far I cannot add the link as the page doesn't exist yet, and I need a valid url otherwise the project doesn't compile. So, I will leave it on-hold until we merge the work from @mativm02 and we can add a valid link

2023-09-05 09:50 UTC, SonjaChevre reviewed
looking really good and detailed! a couple of small improvements from my side

2023-09-05 09:50 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
>  description: Overview page to introduce OpenTelemetry in Tyk
OpenTelemetry is always in one word, like this:

title: "OpenTelemetry"
tags: ["otel", "opentelemetry"]

2023-09-05 09:50 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Since v5.2.+ Tyk now supports OpenTelemetry, a robust observability framework for cloud-native software. Enhance your API Gateway's monitoring capabilities with customizable traces and metrics.
Since version 5.2 of Tyk Gateway, you can now leverage the power of OpenTelemetry, a robust observability framework designed for cloud-native software. Enhance your API Gateway's monitoring capabilities with distributed tracing. 


(note: I removed metrics from the text, because we are not yet exposing OTel metrics from Tyk Gateway)

2023-09-05 09:50 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +### Step 2: Enable at API Level (Optional)
Enable detailed tracing at API level (optional)

2023-09-05 09:50 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +After enabling OpenTelemetry at the gateway level, you have the optional step of activating it for specific APIs you wish to monitor. If you choose to do this, edit the respective API definition and
it makes it sound like you have to do it to get the trace for your API, but that's only required for detailed tracing, right?

So I would say something like: "After enabling OpenTelemetry at the gateway level, you have the optional step of activating detailed tracing for specific APIs you wish to get more details from."

2023-09-05 09:50 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Span attributes offer information about a specific operation within a trace, such as a single API request. They can include metrics like how long an individual middleware took to execute, the HTTP me
"They can include metrics like how long an individual middleware took to execute," => the span attributes doesn't contain metrics, those are only meta data.
But the span itself has a duration. Maybe you want to add a one liner about what a span is before you talk about span attributes?

"A span is a named, timed operation that represents an operation. Multiple spans represent different parts of the workflow and are pieced together to create a trace."

2023-09-05 10:39 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Setting detailed_tracing to `false` will generate a single span that encapsulates the entire request lifecycle. This span will include attributes and tags but will lack finer details. Specifically, i
it will not show spans for the individual middleware executions. 

(using metrics here is confusing, because OTel use the concept of metrics in a different way)

2023-09-05 10:56 UTC, dcs3spp requested changes
Hi @sredxny PR looking good. I have made minor suggestions

2023-09-05 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Before proceeding with the following steps, ensure that you have configured your OpenTelemetry backend as well as any necessary integrations. To configure your first integration with the OpenTelemetr
Add the _here_ link

```suggestion
Before proceeding with the following steps, ensure that you have configured your OpenTelemetry backend as well as any necessary integrations. Further information on how to configure your first integration with the OpenTelemetry collector is available [here](<link>).
```

2023-09-05 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +With `detailed_tracing` set to `true`, OpenTelemetry will create a span for each middleware involved in the request processing. These spans will offer detailed insights such as the time each middlewa
```suggestion
With `detailed_tracing` set to `true`, OpenTelemetry will create a span for each middleware involved in the request processing. These spans will offer detailed insights such as the time each middleware took to execute and the sequence in which they were invoked. The spans are displayed in a waterfall model, revealing the hierarchy and sequence of middleware execution. This includes: pre-middlewares, post-middlewares, the round trip to the upstream server and the response middlewares. The illustration below shows an example trace:
```

2023-09-05 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +In OpenTelemetry, resource attributes provide contextual information about the entity that produced the telemetry data. Unlike span attributes, which are specific to individual operations (e.g., requ
```suggestion
In OpenTelemetry, resource attributes provide contextual information about the entity that produced the telemetry data. These are associated with the service or application as a whole. Conversely, span attributes are associated with specific operations, such as API requests.
```

2023-09-05 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +### Context Propagation
Maybe add an additional line between these two headings

2023-09-05 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +- **tracecontext**: This option supports the W3C Trace Context format. More information can be found at [W3C Trace Context](https://www.w3.org/TR/trace-context/).
```suggestion
- **tracecontext**: This option supports the [W3C Trace Context](https://www.w3.org/TR/trace-context/) format.
```

2023-09-05 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +- **b3**: This option serializes `SpanContext` to/from the B3 multi Headers format.
What is the B3 headers format? Should we add a link here?

2023-09-05 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Tyk supports configurable sampling strategies through the Sampling configuration structure. Below are the options you can customize:
```suggestion
Tyk supports configuring the following sampling strategies via the Sampling configuration structure:
```

2023-09-05 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +This option is useful for ensuring the sampling consistency between parent and child spans. Specifically, if a parent span is sampled, all its child spans will be sampled as well. This setting is par
```suggestion
This option is useful for ensuring the sampling consistency between parent and child spans. Specifically, if a parent span is sampled, all it's child spans will be sampled as well. This setting is particularly effective when used with `TraceIDRatioBased`, as it helps to keep the entire transaction story together. Using `ParentBased` with `AlwaysOn` or `AlwaysOff` may not be as useful, since in these cases, either all or no spans are sampled. The default value is `false`. Configuration options include:
```

2023-09-05 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +For more in-depth information on the configuration options available, please refer to our [OpenTelemetry Configuration Details Page](https://tyk.io/docs/tyk-oss-gateway/configuration/#opentelemetry).
Use relative links instead of absolute URLs

```suggestion
For more in-depth information on the configuration options available, please refer to our [OpenTelemetry Configuration Details Page]({{< ref "tyk-oss-gateway/configuration#opentelemetry" >}}).
```

2023-09-08 18:24 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
>  description: Overview page to introduce OpenTelemetry in Tyk
done!

2023-09-08 18:25 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +### Step 2: Enable at API Level (Optional)
done!

2023-09-08 18:28 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +After enabling OpenTelemetry at the gateway level, you have the optional step of activating it for specific APIs you wish to monitor. If you choose to do this, edit the respective API definition and
makes sense! applied the change

2023-09-08 18:31 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Since v5.2.+ Tyk now supports OpenTelemetry, a robust observability framework for cloud-native software. Enhance your API Gateway's monitoring capabilities with customizable traces and metrics.
makes sense, done

2023-09-08 18:47 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Before proceeding with the following steps, ensure that you have configured your OpenTelemetry backend as well as any necessary integrations. To configure your first integration with the OpenTelemetr
@dcs3spp that link is a link to the work being done by @mativm02 I guess we must merge first his job so I can point to a valid link?

2023-09-08 18:48 UTC, sredxny commented
@SonjaChevre @caroltyk @dcs3spp I did the changes, please take another look and let me know your toughts

2023-09-11 08:22 UTC, dcs3spp approved these changes
lgtm @sredxny @mativm02 Please remember to update the link in parent branch once both your PRs have been merged

2023-09-11 08:47 UTC, SonjaChevre reviewed
just spotted one last thing: the page title is Open Telemetry instead of OpenTelemetry.
Otherwise, LGTM!

2023-09-11 08:47 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
>  title: "Open Telemetry"
OpenTelemetry

2023-09-11 17:26 UTC, SonjaChevre approved these changes

2023-09-11 17:35 UTC, merged