[DX-658] Create PR For API Security Best Practice
TykTechnologies/tyk-docs-hugo pull request #3216
Opened 2023-09-01 15:10 UTC by dcs3spp

[DX-658](https://tyktech.atlassian.net/browse/DX-658)

2023-10-11 12:40 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/api-security/overview.md
> +description: "API security best practices"
We need a slightly longer and clearer description for the search engines and scrapers to analyse.

2023-10-12 15:45 UTC, letzya reviewed
@dcs3spp what is the reason this article is split into multiple pages?

2023-10-30 09:31 UTC, davegarvey commented on tyk-docs/content/api-management/manage-apis/api-security/authorisation-levels.md
> +The client sends a _POST_ request using the path `/graphql` and body data containing a GraphQL query. The path `/graphql` is static and requires function level authorisation. The GraphQL query contai
The formatting for the HTTP method should be as code, as per previous entries.

2023-10-30 09:35 UTC, davegarvey commented on tyk-docs/content/api-management/manage-apis/api-security/authorisation-levels.md
> +All object types and fields contained in the query are checked against the API’s GraphQL schema, to ensure they are valid. In this case, the object type is `profile`, and the fields are `id` and `nam
Should be a bullet point

2023-10-30 09:35 UTC, davegarvey commented on tyk-docs/content/api-management/manage-apis/api-security/authorisation-levels.md
> +Field-based permissions can also be used, to authorise client access of individual fields available in the schema. In this case, `id` and `name`.
Should be a bullet point

2023-10-30 09:54 UTC, davegarvey commented on tyk-docs/content/api-management/manage-apis/api-security/overview.md
> +description: "API security best practices"
Perhaps "API security best practices using API management"?

2023-10-30 10:01 UTC, davegarvey commented on tyk-docs/content/api-management/manage-apis/api-security/resource-consumption.md
> +**Enforce Network-Level Security**: Problematic clients can be prevented from accessing the API by [blocking their address]({{< ref "tyk-apis/tyk-gateway-api/api-definition-objects/ip-blacklisting" >
Perhaps "allow addresses" should be "allowed addresses". In the original doc it was "allow addresses", as per here, but having read it back I think it reads better as "allowed addresses". I've updated the original doc.

2023-10-30 10:02 UTC, davegarvey requested changes
I've made a few minor points. Otherwise, I think it's good to go.

2023-11-07 14:12 UTC, dcs3spp commented on tyk-docs/content/api-management/manage-apis/api-security/resource-consumption.md
> +**Enforce Network-Level Security**: Problematic clients can be prevented from accessing the API by [blocking their address]({{< ref "tyk-apis/tyk-gateway-api/api-definition-objects/ip-blacklisting" >
done

2023-11-07 14:12 UTC, dcs3spp commented on tyk-docs/content/api-management/manage-apis/api-security/overview.md
> +description: "API security best practices"
done

2023-11-07 14:14 UTC, dcs3spp commented on tyk-docs/content/api-management/manage-apis/api-security/authorisation-levels.md
> +The client sends a _POST_ request using the path `/graphql` and body data containing a GraphQL query. The path `/graphql` is static and requires function level authorisation. The GraphQL query contai
done

2023-11-07 14:17 UTC, dcs3spp commented on tyk-docs/content/api-management/manage-apis/api-security/authorisation-levels.md
> +All object types and fields contained in the query are checked against the API’s GraphQL schema, to ensure they are valid. In this case, the object type is `profile`, and the fields are `id` and `nam
Done

2023-11-07 14:17 UTC, dcs3spp commented on tyk-docs/content/api-management/manage-apis/api-security/authorisation-levels.md
> +Field-based permissions can also be used, to authorise client access of individual fields available in the schema. In this case, `id` and `name`.
Done

2023-11-07 16:55 UTC, letzya commented
looks good! @davegarvey @dcs3spp should we also add a link to your OWASP blog?

2023-11-07 16:59 UTC, letzya commented on tyk-docs/data/menu.yaml
> +    path: /api-management/manage-apis/api-security/overview
Are you sure this file path is correct?

2023-11-07 17:00 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        path: /api-management/manage-apis/api-security/authentication
Shouldn't all the pages be under a certain directory?

2023-11-07 17:03 UTC, letzya requested changes
per comments

2023-11-07 17:05 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +    path: /api-management/manage-apis/api-security/overview
🤔 Currently there is no content in the APIM section. Can add an small overview page explaining that this section relates to suggesting best practices for API management. And add link to security overview page in there?

2023-11-07 17:10 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +        path: /api-management/manage-apis/api-security/authentication
if do that then that implies there will be other api-security content in future. If that is the case then could have this structure:

/api-management/manage-apis/api-security/api-security-best-practices-using-apim/ and have all the content files for the article in that folder?

2023-11-07 20:47 UTC, letzya commented on tyk-docs/data/menu.yaml
> +    - title: "API Security Best Practice"
```suggestion
    - title: "API Securitye"
```
```suggestion
    - title: "API Security"
```

2023-11-08 09:56 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +    path: /api-management/manage-apis/api-security/overview
Done

2023-11-08 09:56 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +        path: /api-management/manage-apis/api-security/authentication
Done

2023-11-08 10:06 UTC, merged

2023-11-08 10:06 UTC, dcs3spp commented
/release to release-5.2

2023-11-29 11:31 UTC, dcs3spp commented
/release to release-5.1