remove SVG error in docs's hugo build
TykTechnologies/tyk-docs-hugo pull request #3221
Opened 2023-09-04 10:53 UTC by yurisasuke

### For internal users - please add a Jira DX PR ticket to the subject!

DX-198
---
### Description
- Since gif and svg don't need to be resized we should exclude them from the hugo build error. that shows the message such as `Wrong image type /docs/nightly/img/2.10/tyk_operator2.svg`

2023-09-04 14:28 UTC, dcs3spp requested changes
Hi @Keithwachira How does this fix the issue?

2023-09-04 15:51 UTC, yurisasuke commented
> Hi @Keithwachira How does this fix the issue?



> Hi @Keithwachira How does this fix the issue?

I added this line  `{{ else if in (slice "svg" "gif" ) .MediaType.SubType }}` that checks if the image is a gif or svg and skips displaying a warning for such images

2023-09-05 08:28 UTC, dcs3spp approved these changes

2023-09-05 08:45 UTC, merged

2023-09-05 08:46 UTC, yurisasuke commented
/release to release-5.1