Update and added steps ce-redhat-rhel-centos.md
TykTechnologies/tyk-docs-hugo pull request #3235
Opened 2023-09-06 21:35 UTC by carlostyk

Updated and added the steps to make it easy to follow and up to date. There were some steps missing. Tested the installation in my RHEL machine and works nicely.

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-09-07 09:00 UTC, dcs3spp requested changes
Carlos PR looks good to me, I have suggested minor changes. One the changes have been addressed and a peer review has been performed then we can merge and release.

2023-09-07 09:00 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +## Step 2: Install Python
Maybe insert a new line here before heading

2023-09-07 09:00 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +Create a file named `/etc/yum.repos.d/tyk_tyk-gateway.repo` that contains the repository configuration settings for YUM repositories `tyk_tyk-gateway` and `tyk_tyk-gateway-source` used to download pa
```suggestion
Create a file named `/etc/yum.repos.d/tyk_tyk-gateway.repo` that contains the repository configuration settings for YUM repositories `tyk_tyk-gateway` and `tyk_tyk-gateway-source` used to download packages from the specified URLs. This includes GPG key verification and SSL settings, on a Linux system.
```

2023-09-07 09:00 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +*(you may be asked to accept the GPG key for our two repos and when the package installs, hit yes to continue)*
Maybe make this a note

2023-09-07 09:00 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +### Step 5: Start Redis
Should this heading be ## Step 5: Start Redis so it is consistent styling?

```suggestion
## Step 5: Start Redis
```

2023-09-07 09:00 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +In many cases Redis will not be running, so let's start those:
```suggestion
If Redis is not running then start it using the following command:
```

2023-09-07 09:00 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +3. [Create an API Key]({{< ref "getting-started/create-api-key" >}})
How is this different from previous version?

2023-09-07 09:38 UTC, carlostyk commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +3. [Create an API Key]({{< ref "getting-started/create-api-key" >}})
mmmm I don't remember changing that one... It should be the same

2023-09-07 09:42 UTC, carlostyk commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +*(you may be asked to accept the GPG key for our two repos and when the package installs, hit yes to continue)*
Good idea! Changed it.

2023-09-07 11:51 UTC, dcs3spp approved these changes

2023-09-07 19:11 UTC, zalbiraw reviewed
I will test on RHEL 7 and give the ok

2023-09-07 19:11 UTC, zalbiraw commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
Is dnf available on RHEL and CentOS 7?

2023-09-07 19:41 UTC, carlostyk commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
Nope, focused on RHEL8.8 and didn't test that one, as you mentioned I am going to point to EPEL link for that installation as done in the past. The user can follow the dependecies installation from their site

2023-09-07 19:41 UTC, carlostyk commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
Thank you!!

2023-09-12 09:49 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
@carlostyk @zalbiraw Is this resolved and ready for peer approval?

2023-09-12 09:54 UTC, carlostyk commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
@dcs3spp - I will work on it and go with option 1, remove the installation of dependencies and keep only the configuration needed for Tyk.

2023-09-13 17:13 UTC, zalbiraw requested changes
LGTM. Just 2 quick updates required.

2023-09-13 17:13 UTC, zalbiraw commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +## Step 7: Start the Tyk Gateway
```suggestion
## Step 6: Start the Tyk Gateway
```

2023-09-13 17:13 UTC, zalbiraw commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +## Step 6: Configuring The Gateway
```suggestion
## Step 5: Configuring The Gateway 
```

2023-09-13 19:29 UTC, carlostyk commented
@zalbiraw thank you! All set then! Once you approve @dcs3spp can merge. Thank you!!

2023-09-14 10:50 UTC, dcs3spp commented
> @zalbiraw thank you! All set then! Once you approve @dcs3spp can merge. Thank you!!

Many thanks both
@carlostyk I've approved. For GHub to allow the merge, @zalbiraw can you approve and then I will merge

2023-09-14 11:19 UTC, carlostyk commented
@zalbiraw @dcs3spp I promise I do more than RHEL 😅. I had a discussion with James and Josh and made it specific for RHEL 8 which is the most used and point to the different instructions if othe distributions are preferred

2023-09-14 13:53 UTC, dcs3spp requested changes
Hi @carlostyk, Thanks for keeping me informed of the changes. I have made some minor suggestions

2023-09-14 13:53 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +*   Ensure port `8080` is open: this is used in this guide for Gateway traffic (the API traffic to be proxied).
```suggestion
*   Ensure port `8080` is open for Gateway traffic (the API traffic to be proxied).
```

2023-09-14 13:53 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +*   The Tyk Gateway has a dependencie on Redis find [here](https://tyk.io/docs/planning-for-production/redis/#supported-versions) the supported versions. Follow the steps provided by Red Hat to make
```suggestion
*   The Tyk Gateway has a [dependency](https://tyk.io/docs/planning-for-production/redis/#supported-versions) on Redis. Follow the steps provided by Red Hat to make the installation of Redis, conducting a [search](https://access.redhat.com/search/?q=redis) for the correct version and distribution.
```

2023-09-14 13:53 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +```bash
I think the text is more bolder and clearer when using _console_ styling

2023-09-14 13:53 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +```bash
I think the text looks clearer and bolder with _console_ styling rather than _bash_ styling

2023-09-14 13:53 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +```bash
I think the text is clearer and bolder when using _console_ styling rather than _bash_

2023-09-14 13:58 UTC, carlostyk commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +*   Ensure port `8080` is open: this is used in this guide for Gateway traffic (the API traffic to be proxied).
Thank you,!

2023-09-14 15:43 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
> +```bash
@carlostyk Looking at the PR [preview](https://deploy-preview-3235--tyk-docs.netlify.app/docs/nightly/tyk-oss/ce-redhat-rhel-centos/) text styled with bash is more difficult to read 

```suggestion
```console
```

2023-09-14 15:49 UTC, dcs3spp approved these changes

2023-09-14 15:51 UTC, dcs3spp commented
@carlostyk Thanks for updating with suggested changes. I have approved the PR. @zalbiraw if everything is ok can you also approve to unblock the merge and then I'll merge and release?

2023-09-14 18:58 UTC, zalbiraw commented
Sorry for extending this but I thought I'd add the updates to ce-debian-ubuntu.md as well. I also flipped the sell and ansible sections

2023-09-14 19:05 UTC, zalbiraw approved these changes

2023-09-14 20:05 UTC, carlostyk commented
Thanks a lot @zalbiraw and @dcs3spp for all the help. Next up the on-prem installation :D

2023-10-05 14:15 UTC, dcs3spp approved these changes
lgtm

2023-10-05 14:26 UTC, dcs3spp commented
@carlostyk Is this ok to merge re Ansible [issue](https://tyktech.slack.com/archives/C044R3ZTN6L/p1696515565660309?thread_ts=1694711511.500249&cid=C044R3ZTN6L)

2023-10-05 14:38 UTC, carlostyk commented
@dcs3spp we can merge it for now. It is just that I didn't review ansible but should be OK

2023-10-05 14:44 UTC, merged

2023-10-05 14:44 UTC, dcs3spp commented
/release to release-5.2

2023-10-05 14:48 UTC, dcs3spp commented
/release to release-5