Asha advanced caching
TykTechnologies/tyk-docs-hugo pull request #3253
Opened 2023-09-14 08:50 UTC by ashaparulkar

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-09-14 10:28 UTC, dcs3spp requested changes
Hi @ashaparulkar 

Has this been created because there is a new format for caching config introduced?

2023-09-14 10:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +                "cache": [
@ashaparulkar @andyo-tyk Where is the 60 second timeout, is this the default?

2023-09-14 10:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +"version_data": {
@ashaparulkar @andyo-tyk Is this a new format since the original content was written

2023-09-19 01:04 UTC, ashaparulkar commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +                "cache": [
@dcs3spp , From Raw API definition I can see timeout and these other parameters under cache_options.
 ```
   "cache_options": {
      "cache_timeout": 60,
      "enable_cache": true,
      "cache_all_safe_requests": false,
      "cache_response_codes": [],
      "enable_upstream_cache_control": false,
      "cache_control_ttl_header": "",
      "cache_by_headers": []
    }
```

2023-09-19 01:08 UTC, ashaparulkar commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +                "cache": [
@dcs3spp , 
> Has this been created because there is a new format for caching config introduced?
No idea about new caching config format. But from Raw API definition I can see, "extended_paths" is under version_data.versions.<your version>, instead of under cache_options (mentioned in document).

2023-10-04 11:58 UTC, dcs3spp commented
Closing since this has been merged in another release by Andy

2023-10-04 11:58 UTC, closed without merging