[DX-695] Updating steps for redhat-rhel-centos.md
TykTechnologies/tyk-docs-hugo pull request #3261
Opened 2023-09-14 22:08 UTC by carlostyk

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-05 13:54 UTC, dcs3spp requested changes
Hi Carlos, PR is looking good to me!!!

Made some very minor suggestions, relating to structure and updating tyk.io/docs links to use *ref* links.

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +Select the prefer way of installing Tyk by selecting **Shell** or **Ansible** tab for instructions.
```suggestion

Select the preferred way of installing Tyk by selecting **Shell** or **Ansible** tab for instructions.
```

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +Tyk Gateway has a [dependency](https://tyk.io/docs/planning-for-production/redis/#supported-versions) on Redis. Follow the steps provided by Red Hat to make the installation of Redis, conducting a [s
Use relative links, e.g. {{< ref "/planning-for-production/redis#supported-versions" >}}

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +Tyk Dashboard has a dependency on a storage database that can be [PostgreSQL](https://tyk.io/docs/planning-for-production/database-settings/postgresql/) or [MongoDB](https://tyk.io/docs/planning-for-
Use relative links, e.g. {{< ref "/planning-for-production/database-settings/postgresql" >}}

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +Check the PostgreSQL supported [versions](https://tyk.io/docs/planning-for-production/database-settings/postgresql/). Follow the steps provided by [PostgreSQL](https://www.postgresql.org/download/lin
Use relative links, e.g. {{< ref "/planning-for-production/database-settings/postgresql" >}}

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +Check the MongoDB supported [versions](https://tyk.io/docs/planning-for-production/database-settings/postgresql/). Follow the steps provided by [MongoDB](https://www.mongodb.com/docs/manual/tutorial/
Use relative links, e.g. {{< ref "/planning-for-production/database-settings/postgresql" >}}

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +For a production environment, we recommend that the Tyk Gateway, Tyk Dashboard and Tyk Pump are installed on separate machines. If installing multiple Tyk Gateways, you should install each on a separ
```suggestion
For a production environment, we recommend that the Tyk Gateway, Tyk Dashboard and Tyk Pump are installed on separate machines. If installing multiple Tyk Gateways, you should install each on a separate machine. See [Planning for Production]({{< ref "planning-for-production" >}}) for more details.
```

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +## Supported Distributions
If the CentOS and RHEL versions are the same for shell and Ansible, maybe include one supported distributions table before the tabs sentence (_Select the preferred way of installing Tyk by selecting Shell or Ansible tab for instructions_)

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +You can install Tyk on RHEL or CentOS using our YUM repositories, follow the guides and tutorials in this section to have Tyk up and running in no time.
```suggestion
You can install Tyk on RHEL or CentOS using our YUM repositories. Follow the guides and tutorials in this section to have Tyk up and running in no time.
```

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +## Getting Started
Is the content for the _shell_ tab split into 2 sections, i.e.

- Install and Configure Dependencies (currently the section named Getting Started)
- Install Tyk Self-Managed on Red Hat (RHEL) / CentOS?

If so then maybe rename _Getting Started_ to 

```Suggestion
## Install and Configure Dependencies
```

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +### Installing Redis
```suggestion
### Redis
```

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +### Installing PostgreSQL or MongoDB
```suggestion
### Storage Database
```

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +### Installing PostgreSQL
```suggestion
### Install PostgreSQL
```

2023-10-05 13:54 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +### Configuring PostgreSQL
```suggestion
Configure PostgreSQL
```

2023-10-09 09:22 UTC, carlostyk commented on tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
> +Check the MongoDB supported [versions](https://tyk.io/docs/planning-for-production/database-settings/postgresql/). Follow the steps provided by [MongoDB](https://www.mongodb.com/docs/manual/tutorial/
Done, Thank you!

2023-11-09 14:08 UTC, dcs3spp approved these changes

2023-11-09 14:14 UTC, dcs3spp commented
See that links are fixed. Have approved. Ok to merge?

2023-11-22 20:11 UTC, zalbiraw approved these changes
LGTM

2023-11-23 14:16 UTC, merged

2023-11-23 14:16 UTC, dcs3spp commented
/release to release-5.2

2023-11-23 14:16 UTC, dcs3spp commented
/release to release-5.1

2023-11-23 14:24 UTC, dcs3spp commented
/release to release-5