Update partitioned-policies.md
TykTechnologies/tyk-docs-hugo pull request #3276
Opened 2023-09-21 06:35 UTC by behcio

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-09-22 10:13 UTC, dcs3spp reviewed
Hi @behcio Why was the text removed from the PR? Is this targeted for a specific release?

2023-09-25 09:55 UTC, behcio commented
> Hi @behcio Why was the text removed from the PR? Is this targeted for a specific release?

This PR was created as part of the training Yaara gave me on the docs. It's a work in progress, so I'll change it to a draft.

2023-10-13 08:17 UTC, behcio commented
Please note that these changes in the docs are still not released. Hence the `future-release` label.

2023-10-17 09:38 UTC, dcs3spp requested changes
Hi @behico, PR looks good to me. I have made some minor suggestions. Once the changes have been made will merge and release

2023-10-17 09:38 UTC, dcs3spp commented on tyk-docs/content/graphql/field-based-permissions.md
> +By default all *Types* and *Fields* will be unchecked. By checking a *Type* or *Field* you will disallow to use it for any GraphQL operation associated with the key.
```suggestion
### Block list

By default all *Types* and *Fields* will be unchecked. By checking a *Type* or *Field* you will disallow to use it for any GraphQL operation associated with the key.
```

2023-10-17 09:38 UTC, dcs3spp commented on tyk-docs/content/graphql/field-based-permissions.md
> +4. Enable either **Block list** or **Allow list**. It's not possible to have both enabled at the same time.
Is the default behaviour to have *Blocked List* switch enabled with the *Allow List* switch hidden? 
If the *Block List* switch is disabled does this then display and enable the *Allow List* switch?

If so, maybe add an explanation of this in bullet point 4.

2023-10-17 09:38 UTC, dcs3spp commented on tyk-docs/content/graphql/field-based-permissions.md
> +For example, the settings from the screenshot below would block `code` and `countries` fields in `Continent` type as well as `latt` and `longt` fields in `Coordinates` type from usage.
```suggestion
For example, the settings illustrated below would block the following:
- `code` and `countries` fields in `Continent` type.
- `latt` and `longt` fields in `Coordinates` type.
```

2023-10-17 09:38 UTC, dcs3spp commented on tyk-docs/content/graphql/field-based-permissions.md
> +By default all *Types* and *Fields* will be unchecked. By checking a *Type* or *Field* you will allow to use it for any GraphQL operation associated with the key.
```suggestion
By default all *Types* and *Fields* will be unchecked. By checking a *Type* or *Field* you will allow it to be used for any GraphQL operation associated with the key.
```

2023-10-17 09:38 UTC, dcs3spp commented on tyk-docs/content/graphql/field-based-permissions.md
> +For example, the settings from the screenshot below would only allow `code` field in `Continent` type as well as `code` and `name` fields in `Language` to be used. Note that since no query is allowed
```suggestion
For example, the settings illustrated below would only allow the following:
- `code` field in `Continent` type.
- `code` and `name` fields in `Language` type.

Note that the `Query` type is unchecked. Subsequently, you will not be able to run any query.
```

2023-10-17 13:38 UTC, behcio commented on tyk-docs/content/graphql/field-based-permissions.md
> +4. Enable either **Block list** or **Allow list**. It's not possible to have both enabled at the same time.
By default neither of the switches is enabled but both are displayed at all times.
However, adding a note that enabling one switch automatically disables the other (if the other was enabled in the first place) as further explanation to `It's not possible to have both enabled at the same time` indeed makes sense.

2023-10-17 13:51 UTC, behcio commented on tyk-docs/content/graphql/field-based-permissions.md
> +By default all *Types* and *Fields* will be unchecked. By checking a *Type* or *Field* you will disallow to use it for any GraphQL operation associated with the key.
I completely agree with this change but I don't know why `### Block list` was missing in the first place. It's there in commit `6e4da30dcb878755cf60791c443abfb52b1a5714`, line 160. Weird

2023-10-17 14:00 UTC, behcio commented on tyk-docs/content/graphql/field-based-permissions.md
> +For example, the settings from the screenshot below would only allow `code` field in `Continent` type as well as `code` and `name` fields in `Language` to be used. Note that since no query is allowed
I like the bullet points here. 
However, I feel some meaning is lost by this change. I wanted to emphasise that having no checked fields in `Query` causes the `Query` type to be unchecked which subsequently makes the user unable to run any query. You could say the first part of this chain is missing.

2023-10-17 14:26 UTC, behcio commented
@dcs3spp, I applied changes with your suggestions in mind. Please take a look.

2023-10-18 08:14 UTC, agata-wit approved these changes

2023-10-19 09:33 UTC, dcs3spp approved these changes
Many thanks @behico for submitting changes. I have approved the PR. Is this scheduled for release 5.2.3?

2023-10-19 11:56 UTC, behcio commented
> Many thanks @behico for submitting changes. I have approved the PR. Is this scheduled for release 5.2.3?

Rather 5.3.0, but @agata-wit would be the best person to ask.

2023-10-20 12:53 UTC, behcio commented
> Many thanks @behico for submitting changes. I have approved the PR. Is this scheduled for release 5.2.3?

Release 5.3.0

2023-11-01 21:11 UTC, letzya commented
@dcs3spp why don't we merge this to master?

2023-11-02 09:49 UTC, merged