release note, no docker link
TykTechnologies/tyk-docs-hugo pull request #3306
Opened 2023-09-29 16:44 UTC by letzya

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description

#### Screenshots (if appropriate)

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-04 13:51 UTC, andyo-tyk requested changes
Added some suggestions

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +Our minor releases are supported until our next minor comes out. This would be R5.3 scheduled in Q4 if this goes ahead as planned. If not, 5.2 will remain in support until our next LTS version comes
While this boilerplate text is usually correct - on this occasion there is no R5.3 scheduled in Q4 (due to the Product and Engineering focus on test automation)

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +If you are on a 5.2.0 please upgrade asap and if you are on an older version skip 5.2.0 and upgrade directly to this release.
ASAP should be capitalised

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +##### This page contains all release notes for version 5.2.X displayed in a reverse chronological order
```suggestion
##### This page contains all release notes for version 5.2.X displayed in reverse chronological order
```

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### This page contains all release notes for version 5.2.X displayed in a reverse chronological order
```suggestion
##### This page contains all release notes for version 5.2.X displayed in reverse chronological order
```

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Our minor releases are supported until our next minor comes out. This would be R5.3 scheduled in Q4 if this goes ahead as planned. If not, 5.2 will remain in support until our next LTS version comes
As for the Dashboard, no R5.3 is currently scheduled.

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Release Date 29 Sep 2023
There's no "Release Date" on the Dashboard page - is this deliberate?

It's also the wrong date :)

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed a bug that occurs during Gateway reload where the Gateway would continue to load new API definitions even if policies failed to load; this would leave the customer at risk of an APIs being in
```suggestion
- Fixed a bug that occurs during Gateway reload where the Gateway would continue to load new API definitions even if policies failed to load. This led to a risk that an API could be invoked without the associated policies (for example, describing access control or rate limts) having been loaded. Now Tyk offers a configurable retry for resource loading, ensuring that a specified number of attempts will be made to load resources (APIs and policies). If a resource fails to load, an error will be logged and the Gateway reverts to its last working configuration.
```

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Enhance message quality by eliminating unnecessary messages
I feel this needs more context - which messages? where?

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- We've included the previously missing attributes, `http.response.body.size` and `http.request.body.size`, in both Tyk HTTP spans and upstream HTTP spans. This addition enables users to gain better
I feel this needs some introduction to explain that it relates to OTel (does it?)

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed a bug where *Tyk Dashboard* or *Tyk Gateway* APIs would not allow you to modify a key that provides access rights to an inactive API
```suggestion
- Fixed a bug where, if you created a Key which provided access to an inactive or draft API, you would be unable to subsequently modify that Key (via the Dashboard or directly via the Tyk Gateway API)
```

I think this should be in "Fixed" not "Changed"

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Remove the extra chunked transfer encoding that was added unnecessarily to `rawResponse` analytics
```suggestion
- Removed the extra chunked transfer encoding that was added unnecessarily to `rawResponse` analytics
```

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed an issue in GraphQL APIs, where [headers]({{< ref "graphql/gql-headers" >}}) were not properly forwarded upstream for [GQL/UDG subscriptions]({{< ref "getting-started/key-concepts/graphql-sub
```suggestion
- Fixed an issue with GraphQL APIs, where [headers]({{< ref "graphql/gql-headers" >}}) were not properly forwarded upstream for [GQL/UDG subscriptions]({{< ref "getting-started/key-concepts/graphql-subscriptions" >}}).
```

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Resolved a bug in HTTP GraphQL APIs where, when the [Persist GraphQL middleware]({{< ref "graphql/persisted-queries" >}}) was used in combination with [Response Body Transform]({{< ref "advanced-co
```suggestion
- Resolved a bug with HTTP GraphQL APIs where, when the [Persist GraphQL middleware]({{< ref "graphql/persisted-queries" >}}) was used in combination with [Response Body Transform]({{< ref "advanced-configuration/transform-traffic/response-body" >}}), the response's body transformation was not being executed.
```

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Update TykTechnologies/gorm to v1.21 in Tyk Gateway
```suggestion
- Updated TykTechnologies/gorm to v1.21 in Tyk Gateway 
```

2023-10-04 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +tags: ["Release notes", "v5.2", "5.2.0", "5.2", "changelog"]
Do you plan to add all versions in here?

2023-10-04 17:19 UTC, dcs3spp requested changes
Release notes 5.2.1 PR looking good. Have made some minor suggestions

2023-10-04 17:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added support to Tyk Dashboard API so that Tyk Sync can fully support Tyk OAS API Definitions; this will be enabled from Tyk Sync version 1.4.1.
```suggestion
- Added support to Tyk Dashboard API so that Tyk Sync can fully support Tyk OAS API Definitions. This will be enabled from Tyk Sync version 1.4.1.
```

2023-10-04 17:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a bug in *Tyk Dashboard* UI where pagination in the APIs screen was breaking for API of type GraphQL/UDG and resulted in the page failing to load data and displaying a 'No data to display' me
```suggestion
- Fixed a bug in *Tyk Dashboard* UI where pagination in the APIs screen was breaking for API of type GraphQL/UDG. This resulted in the page failing to load data and displaying a 'No data to display' message.
```

2023-10-04 17:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue where the "Add GraphQL Operation" checkbox in the GraphQL data source configuration screen couldn't be disabled, even when no operation was added. Now, its state can be adjusted base
```suggestion
- Fixed an issue where the 'Add GraphQL Operation' checkbox in the GraphQL data source configuration screen couldn't be disabled, even when no operation was added. Now, its state can be adjusted based on the presence of GraphQL operations and variables.
```

2023-10-04 17:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Fixed (3 changes):
```suggestion
#### Fixed:
```

2023-10-04 17:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +#### Added (1 change)
```suggestion
#### Added
```

2023-10-04 17:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +#### Changed (3 change):
```suggestion
#### Changed:
```

2023-10-04 17:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +#### Fixed (6 changes):
```suggestion
#### Fixed:
```

2023-10-04 17:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +#### Dependencies (1 change):
```suggestion
#### Dependencies:
```

2023-10-05 14:17 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +Our minor releases are supported until our next minor comes out. This would be R5.3 scheduled in Q4 if this goes ahead as planned. If not, 5.2 will remain in support until our next LTS version comes
This was released as part of 5.2.0 per @allaneyles request and I just moved it to the top. FYI @dcs3spp

2023-10-05 14:17 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue where the "Add GraphQL Operation" checkbox in the GraphQL data source configuration screen couldn't be disabled, even when no operation was added. Now, its state can be adjusted base
what's the difference

2023-10-05 15:18 UTC, caroltyk requested changes

2023-10-05 15:18 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +##### Fixed (2 changes):
```suggestion
##### Fixed (3 changes):
```

2023-10-05 15:26 UTC, caroltyk requested changes

2023-10-05 15:26 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Fixed (6 changes):
```suggestion
##### Fixed (7 changes):

- Fixed a memory leak issue in Gateway 5.2.0 if opentelemetry is enabled. It was caused by multiple otelhttp handler being created. We have updated to use single instance of otelhttp handler in 5.2.1 to improve performance under high traffic load.

```

2023-10-05 15:31 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Our minor releases are supported until our next minor comes out. This would be R5.3 scheduled in Q4 if this goes ahead as planned. If not, 5.2 will remain in support until our next LTS version comes
@dcs3spp

2023-10-05 15:33 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +#### Dependencies (1 change):
@dcs3spp can you please remind me why you want to remove it

2023-10-05 15:37 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed a bug that occurs during Gateway reload where the Gateway would continue to load new API definitions even if policies failed to load. This led to a risk that an API could be invoked without t
```suggestion
- Fixed a bug that occurs during Gateway reload where the Gateway would continue to load new API definitions even if policies failed to load. This led to a risk that an API could be invoked without the associated policies (for example, describing access control or rate limits) having been loaded. Now Tyk offers a configurable retry for resource loading, ensuring that a specified number of attempts will be made to load resources (APIs and policies). If a resource fails to load, an error will be logged and the Gateway reverts to its last working configuration.
```

2023-10-05 15:42 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- We've included the previously missing attributes, `http.response.body.size` and `http.request.body.size`, in both Tyk HTTP spans and upstream HTTP spans. This addition enables users to gain better
```suggestion
- For OpenTelemetry users, we've included much-needed attributes, `http.response.body.size` and `http.request.body.size`, in both Tyk HTTP spans and upstream HTTP spans. This addition enables users to gain better insight into incoming/outgoing request/response sizes within their traces.
```

2023-10-05 15:43 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- We've included the previously missing attributes, `http.response.body.size` and `http.request.body.size`, in both Tyk HTTP spans and upstream HTTP spans. This addition enables users to gain better
@caroltyk @SonjaChevre what do you think about this? 
Also - have we updated the doc with this? (https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview/)

2023-10-05 15:43 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- We've included the previously missing attributes, `http.response.body.size` and `http.request.body.size`, in both Tyk HTTP spans and upstream HTTP spans. This addition enables users to gain better
check my change below

2023-10-05 15:45 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed a bug where *Tyk Dashboard* or *Tyk Gateway* APIs would not allow you to modify a key that provides access rights to an inactive API
why "via dashboard" without the word "api"? did you want it to include ui and api?

2023-10-05 15:45 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed a bug where *Tyk Dashboard* or *Tyk Gateway* APIs would not allow you to modify a key that provides access rights to an inactive API
also `Key` needs to be lowercase

2023-10-05 17:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue where the "Add GraphQL Operation" checkbox in the GraphQL data source configuration screen couldn't be disabled, even when no operation was added. Now, its state can be adjusted base
Suggestion uses single quotation style to be consistent with other changelog items

2023-10-05 17:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +#### Dependencies (1 change):
Suggested to remove since the changelog  is under the heading of the Patch release note title

2023-10-06 09:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +Our minor releases are supported until our next minor comes out. This would be R5.3 scheduled in Q4 if this goes ahead as planned. If not, 5.2 will remain in support until our next LTS version comes
Updated support lifetime statement for Tyk dashboard

2023-10-06 09:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +Our minor releases are supported until our next minor comes out. This would be R5.3 scheduled in Q4 if this goes ahead as planned. If not, 5.2 will remain in support until our next LTS version comes
Updated support lifetime statement for Tyk Gateway

2023-10-06 13:15 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed a bug where *Tyk Dashboard* or *Tyk Gateway* APIs would not allow you to modify a key that provides access rights to an inactive API
after you answer me and I commit your changes I will move it

2023-10-06 13:29 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +tags: ["Release notes", "v5.2", "5.2.0", "5.2", "changelog"]
was thinking about that, is this a problem?

2023-10-06 13:29 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +##### This page contains all release notes for version 5.2.X displayed in a reverse chronological order
```suggestion
##### This page contains all release notes for version 5.2.X displayed in reverse chronological order
```

2023-10-06 13:30 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +##### This page contains all release notes for version 5.2.X displayed in a reverse chronological order
no idea why  this one is outdated @andyo-tyk

2023-10-06 13:31 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +If you are on a 5.2.0 please upgrade asap and if you are on an older version skip 5.2.0 and upgrade directly to this release.
```suggestion
If you are on a 5.2.0 please upgrade ASAP and if you are on an older version skip 5.2.0 and upgrade directly to this release. 
```

2023-10-06 13:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +tags: ["Release notes", "v5.2", "5.2.0", "5.2", "changelog"]
I don't have an opinion.... just that I spotted it has different variations of 5.2, but not 5.2.1...

2023-10-06 13:54 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed a bug where *Tyk Dashboard* or *Tyk Gateway* APIs would not allow you to modify a key that provides access rights to an inactive API
I was trying to show that it can be via Tyk Dashboard API or Tyk Dashboard UI... but you're right, we should be explicit.

```suggestion
- Fixed a bug where, if you created a key which provided access to an inactive or draft API, you would be unable to subsequently modify that Key (via the Tyk Dashboard UI, Tyk Dashboard API or Tyk Gateway API)
```

2023-10-06 15:26 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +tags: ["Release notes", "v5.2", "5.2.0", "5.2", "changelog"]
good spot, now it does

2023-10-06 15:29 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Release Date 29 Sep 2023
fixed already

2023-10-06 15:36 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Enhance message quality by eliminating unnecessary messages
I agree. I changed it to "log messages" but we could be clearer @sredxny ?

2023-10-06 16:41 UTC, andyo-tyk approved these changes
Fine by me, thanks.

2023-10-06 16:57 UTC, caroltyk approved these changes
Looks good to me

2023-10-09 11:52 UTC, dcs3spp approved these changes

2023-10-09 12:08 UTC, lghiur approved these changes

2023-10-09 12:08 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +##### Configure Caching For Each API Endpoint
@letzya @andyo-tyk we added just the timeout field, this title can be a bit missleading?

2023-10-09 12:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +##### Configure Caching For Each API Endpoint
@lghiur , something like this?

```suggestion
Configure Caching Timeouts Per API Endpoint and Enable Advanced Caching Options From Within Dashboard
```

or 

```suggestion
Extended Caching Configuration
```

2023-10-09 12:17 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +##### Configure Caching For Each API Endpoint
First one looks good to me (if it's not too long).

2023-10-09 14:16 UTC, agata-wit requested changes

2023-10-09 14:16 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
>  - Fixed an issue in *Tyk Dashboard* where duplicate APIs could be created with the same names and listen paths if you clicked multiple times on the *save* button in the API Designer. Now, when you sa
```suggestion
- Fixed an issue in *Tyk Dashboard* where duplicate APIs could be created with the same names and listen paths if you clicked multiple times on the *save* button in the API Designer. Now, this is not possible anymore and there is no risk of creating multiple APIs with the same name.
```

2023-10-09 14:17 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
>  - Fixed an issue in *Tyk Dashboard* where duplicate APIs could be created with the same names and listen paths if you clicked multiple times on the *save* button in the API Designer. Now, when you sa
Few lines above we're writing that we changed the "go back to APIs list after Save" behaviour, so this last sentence doesn't make sense.

2023-10-10 12:01 UTC, agata-wit approved these changes

2023-10-10 14:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +<<- [docker image to pull](https://hub.docker.com/layers/tykio/tyk-gateway/v5.2.1/images/blabla)>>
```suggestion
- [docker image to pull](https://hub.docker.com/layers/tykio/tyk-gateway/v5.2.1/images/sha256-47cfffda64ba492f79e8cad013a476f198011f5a97cef32464f1f47e1a9be9a2?context=explore)
```

2023-10-10 14:58 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +<<[docker image to pull](https://hub.docker.com/layers/tykio/tyk-dashboard/v5.2.0/images/bla)>>
```suggestion
- [docker image to pull](https://hub.docker.com/layers/tykio/tyk-dashboard/v5.2.1/images/sha256-2f9d8af0e57f7fe4afb618dcf34772c001104dc0ec62a27541d12dc9ae90d5c8?context=explore)
```

2023-10-10 14:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +##### Release Date 10 Oct 2023 <<update>>
```suggestion
##### Release Date 10 Oct 2023
```

2023-10-10 15:00 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Release Date 10 Oct 2023 <<update>>
```suggestion
##### Release Date 10 Oct 2023
```

2023-10-10 15:48 UTC, merged

2023-10-10 15:48 UTC, dcs3spp commented
/release to release-5.2