DX-729 - OTel improvements & Datadog guide
TykTechnologies/tyk-docs-hugo pull request #3321
Opened 2023-10-04 08:56 UTC by SonjaChevre

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description
1. Improved OTel overview page
2. Create a new guide for Datadog integration

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2023-10-04 11:38 UTC, dcs3spp requested changes
Many thanks for submitting the PR Sonja and adding the OTel Datadog config doc. I have had a look through and PR looks good to me. Have suggested some minor grammar changes. After changes made and peer review performed will release.

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/distributed-tracing-overview.md
> +Distributed tracing is a monitoring and diagnostic technique used in software systems to track and visualize the path of requests as they traverse multiple microservices or components. In the context
```suggestion
Distributed tracing is a monitoring and diagnostic technique used in software systems to track and visualize the path of requests as they traverse multiple microservices or components. In the context of an API gateway, distributed tracing helps capture and analyse the journey of API requests across various services, providing valuable insights into performance bottlenecks, latency issues and the overall health of the system.
```

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Starting from Tyk Gateway version 5.2, you can leverage the power of OpenTelemetry, an open-source observability framework designed for cloud-native software, to enhance your API monitoring with end-
```suggestion
Starting from Tyk Gateway version 5.2, you can leverage the power of OpenTelemetry, an open-source observability framework designed for cloud-native software. This enhances your API monitoring with end-to-end distributed tracing.
```

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +For further guidance on configuring your observability back-end, explore our guides for [Datadog]({{< ref "otel_datadog" >}}), [Dynatrace]({{< ref "otel_dynatrace" >}}), [Jaeger]({{< ref "otel_jaeger
```suggestion
For further guidance on configuring your observability back-end, explore our guides for [Datadog]({{< ref "otel_datadog" >}}), [Dynatrace]({{< ref "otel_dynatrace" >}}), [Jaeger]({{< ref "otel_jaeger" >}}) and [New Relic]({{< ref "otel_new_relic" >}}).
```

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Tyk Gateway exposes a helpful set of *span attributes* and *resource attributes* with the generated spans. These attributes helpful to understand your API requests better. To get a clearer picture, y
```suggestion
Tyk Gateway exposes a helpful set of *span attributes* and *resource attributes* with the generated spans. These attributes provide useful insights for analysing your API requests. A clear analysis can be obtained by observing the specific actions and associated context within each request/response. This is where span and resource attributes play a significant role.
```

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Resource attributes provide contextual information about the entity that produced the telemetry data. Tyk exposes following resource attributes:
In the context of Tyk OpenTelemetry what entity(s) produce the telemetry data? Is it a Gateway instance?

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/distributed-tracing-overview.md
> +tags: ["distributed tracing", "opentelemetry", "opentracing", "traces"]
```suggestion
tags: ["distributed tracing", "OpenTelemetry", "OpenTracing", "traces"]
```

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_datadog.md
> +This guide explains how to configure Tyk API Gateway and the OpenTelemetry Collector to collect distributed traces in Datadog. It follows the [reference documentation from Datadog](https://docs.datad
```suggestion
This guide explains how to configure Tyk API Gateway and the OpenTelemetry Collector to collect distributed traces in Datadog. It follows the reference documentation from [Datadog](https://docs.datadoghq.com/opentelemetry/otel_collector_datadog_exporter/?tab=onahost).
```

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_datadog.md
> +* An [API key from Datadog](https://docs.datadoghq.com/account_management/api-app-keys/#add-an-api-key-or-client-token). An API key looks like this: `6c35dacbf2e16aa8cda85a58d9015c3c`.
```suggestion
- An [API key from Datadog](https://docs.datadoghq.com/account_management/api-app-keys/#add-an-api-key-or-client-token). For example, `6c35dacbf2e16aa8cda85a58d9015c3c`. 
```

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_datadog.md
> +* Your [Datadog site](https://docs.datadoghq.com/getting_started/site/#access-the-datadog-site). Examples: `datadoghq.com`, `us3.datadoghq.com`, `datadoghq.eu`.
```suggestion
- Your [Datadog site](https://docs.datadoghq.com/getting_started/site/#access-the-datadog-site). Examples are: `datadoghq.com`, `us3.datadoghq.com` and `datadoghq.eu`. 
```

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_datadog.md
> +If you don't have any APIs configured yet, create a subdirectory called `apps` in the current directory. Create a new file `apidef-hello-world.json` and copy this simple API definition:
Maybe add a sentence explaining that example is keyless and only serves for testing and not production?

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_datadog.md
> +```yaml
Should we remove the comments from the docker-compose example?

2023-10-04 11:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_datadog.md
> +- Data Ingestion Delays: Be patient, as there could be some delay in data ingestion. Wait for 10 seconds to see if traces eventually appear, as this is the timeout we have configured in the batch pro
```suggestion
- Data Ingestion Delays: Be patient, as there could be some delay in data ingestion. Wait for 10 seconds to see if traces eventually appear, as this is the timeout we have configured in the batch processing of the OpenTelemetry collector within step 1.
```

2023-10-04 12:12 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
> +Resource attributes provide contextual information about the entity that produced the telemetry data. Tyk exposes following resource attributes:
yes, the Gateway instance

2023-10-04 12:21 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_datadog.md
> +```yaml
I think the comments are helpful, would like to keep them there.

2023-10-04 12:23 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_datadog.md
> +If you don't have any APIs configured yet, create a subdirectory called `apps` in the current directory. Create a new file `apidef-hello-world.json` and copy this simple API definition:
```suggestion
If you don't have any APIs configured yet, create a subdirectory called `apps` in the current directory. Create a new file `apidef-hello-world.json` and copy this very simple API definition for testing purposes:
```

2023-10-05 08:28 UTC, caroltyk approved these changes
LGTM!

2023-10-05 08:35 UTC, dcs3spp approved these changes

2023-10-05 08:39 UTC, merged

2023-10-05 08:39 UTC, dcs3spp commented
/release to release-5.2