OAS Jobs-To-Be-Done tidy up
TykTechnologies/tyk-docs-hugo pull request #3322
Opened 2023-10-04 09:06 UTC by andyo-tyk

### For internal users - please add a Jira DX PR ticket to the subject!
---
### Preview Link

### Description
Tidying up the OAS section of Manage APIs (JTBD)
Improving signposting of Early Access status

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-05 16:27 UTC, dcs3spp requested changes
PR looks good to me, made some minor suggestions

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
> +Tyk OAS API support is currently in [Early Access]({{< ref "/content/frequently-asked-questions/using-early-access-features.md" >}}) and some Tyk features are not yet supported. You can see the statu
```suggestion
Tyk OAS API support is currently in [Early Access]({{< ref "/frequently-asked-questions/using-early-access-features" >}}) and some Tyk features are not yet supported. You can see the status of what is and isn't yet supported [here]({{< ref "/getting-started/using-oas-definitions/oas-reference.md" >}}).
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
> +You will also need to have ‘admin’ or ‘api’ rights if RBAC is enabled.
Should we add a link to how to enable RBAC?

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
> +You will also need to have ‘admin’ or ‘api’ rights if RBAC is enabled.
Should we add a link to how to enable RBAC?

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
> +2. Create a blank file called `simple_api.json`, this will be used to store your OpenAPI Document
```suggestion
2. Create a blank file called `simple_api.json` to store your OpenAPI Document
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +Tyk OAS API support is currently in [Early Access]({{< ref "/content/frequently-asked-questions/using-early-access-features.md" >}}) and some Tyk features are not yet supported. You can see the statu
```suggestion
Tyk OAS API support is currently in [Early Access]({{< ref "/frequently-asked-questions/using-early-access-features.md" >}}) and some Tyk features are not yet supported. You can see the status of what is and isn't yet supported [here]({{< ref "/getting-started/using-oas-definitions/oas-reference" >}}). 
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +You will also need to have ‘admin’ or ‘api’ rights if RBAC is enabled.
Maybe add a link to how to enable RBAC?

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +| Param        | Query param: `allowList`  |
Maybe name the Property column Query Param, what do you think?

```suggestion
| Query Param        | `allowList`  |
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +You created a Tyk OAS API that which tells your Tyk Gateway to allow access just on the paths that are defined in the OpenAPI Document.
```suggestion
You created a Tyk OAS API that tells your Tyk Gateway to allow access only to the paths defined in the OpenAPI Document.
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +| Param        | Query param: `validateRequest`   |
Maybe name property, Query Param, what do you think?

```suggestion
| Query Param        | `validateRequest`   |
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +Go to the `/apps` folder of your Tyk Gateway installation (by default in `/var/tyk-gateway`),and check the newly created Tyk OAS API Definition.
```suggestion
Go to the `/apps` folder of your Tyk Gateway installation (by default in `/var/tyk-gateway`) and check the newly created Tyk OAS API Definition.
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +For more information on how Tyk builds the `middleware.operations` structure to configure middleware, see [Paths]({{< ref "/content/getting-started/key-concepts/paths.md" >}}).
```suggestion
For more information on how Tyk builds the `middleware.operations` structure to configure middleware, see [Paths]({{< ref "/getting-started/key-concepts/paths" >}}).
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +| Param        | Query param: `mockResponse`  |
Maybe have property column named Query Param?

```suggestion
| Query Param        | `mockResponse`  |
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +For more information on how Tyk builds the `middleware.operations` structure to configure middleware, see [Paths]({{< ref "/content/getting-started/key-concepts/paths.md" >}}).
```suggestion

For more information on how Tyk builds the `middleware.operations` structure to configure middleware, see [Paths]({{< ref "/getting-started/key-concepts/paths" >}}).
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
> +The process for importing from an existing Tyk API definition or SOAP WSDL definition is explained [here]({{< ref "/getting-started/import-apis#import-apis-via-the-dashboard" >}}). The import functio
```suggestion
The process for importing from an existing Tyk API definition or SOAP WSDL definition is explained [here]({{< ref "/getting-started/import-apis#import-apis-via-the-dashboard" >}}). The import function will now accept an existing Tyk OAS API definition. The process is the same as for a Tyk Classic API definition.
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/moving-to-oas.md
> +The answer is: possibly. The key question is whether there is anything you currently use in your Tyk Classic APIs that isn’t yet supported by our Tyk OAS APIs. Tyk OAS API support is currently in [Ea
```suggestion
The answer is: possibly. The key question is whether there is anything you currently use in your Tyk Classic APIs that isn’t yet supported by our Tyk OAS APIs. Tyk OAS API support is currently in [Early Access]({{< ref "/frequently-asked-questions/using-early-access-features" >}}) and some Tyk features are not yet supported. You can see the status of what is and isn't yet supported [here]({{< ref "/getting-started/using-oas-definitions/oas-reference" >}}).
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
> +Tyk Gateway is extremely flexible with a great many features that you can use to configure and optimise the handling of requests to your APIs. During the Early Access phase, we are gradually rolling
```suggestion
Tyk Gateway is extremely flexible with a great many features that you can use to configure and optimise the handling of requests to your APIs. During the Early Access phase, we are gradually rolling out support for all of the configuration that is available through Tyk Classic API definitions into the new Tyk OAS API Definition format. Unfortunately we are not quite there yet, though popular requested features have been implemented.
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
> +Tyk OAS API support is currently in [Early Access]({{< ref "/content/frequently-asked-questions/using-early-access-features.md" >}}) and some Tyk features are not yet supported. You can see the statu
```suggestion
Tyk OAS API support is currently in [Early Access]({{< ref "/frequently-asked-questions/using-early-access-features" >}}) and some Tyk features are not yet supported. You can see the status of what is and isn't yet supported [here]({{< ref "/getting-started/using-oas-definitions/oas-reference" >}}). 
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
> +You will also need to have ‘admin’ or ‘api’ rights if RBAC is enabled.
Maybe add link to how to enable RBAC?

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
> +{{< tab_start "Updating with a new Tyk OAS API Definition" >}}
```suggestion
{{< tab_start "Updating an API with a new Tyk OAS API Definition" >}}
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
> +Following the instructions to [create a Tyk OAS API]({{< ref "getting-started/using-oas-definitions/create-an-oas-api" >}}), create a new API by sending [this](https://bit.ly/39tnXgO) Tyk OAS API Def
```suggestion
Following the instructions to [create a Tyk OAS API]({{< ref "getting-started/using-oas-definitions/create-an-oas-api" >}}), create a new API by sending [this](https://bit.ly/39tnXgO) Tyk OAS API Definition to the Gateway API endpoint. This is an example that contains the minimum required fields.
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
> +Let's say that you have updated your API definition by adding details of the `POST /pet` path of the Petstore API.
Will the POST request create an API definition, instead of update it?

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
> +Following the instructions to [create a Tyk OAS API]({{< ref "getting-started/using-oas-definitions/create-an-oas-api" >}}), create a new API by sending [this](https://bit.ly/39tnXgO) Tyk OAS API Def
```suggestion
Following the instructions to [create a Tyk OAS API]({{< ref "getting-started/using-oas-definitions/create-an-oas-api" >}}), create a new API by sending [this](https://bit.ly/39tnXgO) Tyk OAS API Definition to the Gateway API endpoint. This is an example that contains the minimal required fields.
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +Tyk OAS API support is currently in [Early Access]({{< ref "/content/frequently-asked-questions/using-early-access-features.md" >}}) and some Tyk features are not yet supported. You can see the statu
```suggestion
Tyk OAS API support is currently in [Early Access]({{< ref "/frequently-asked-questions/using-early-access-features" >}}) and some Tyk features are not yet supported. You can see the status of what is and isn't yet supported [here]({{< ref "/getting-started/using-oas-definitions/oas-reference" >}}). 
{{< /note >}}
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +### Tutorial 1: Create a versioned API using the Tyk Gateway API (or Tyk Dashboard API)
```suggestion
### Tutorial 1: Create a versioned API using the Tyk Gateway API or Tyk Dashboard API
```

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +You will also need to have ‘admin’ or ‘api’ rights if RBAC is enabled.
Maybe link to how to enable RBAC?

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +| Param        | Query param (options): <br>- `base_api_id`: The API ID of the Base API to which the new version will be linked.<br>- `base_api_version_name`: The version name of the base API while c
Maybe keep the Query Param property name and remove from Query Param from description column?

2023-10-05 16:27 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +In Step 3 we created a new API and automatically linked it to the Base API. You can verify that this new API is a Version API and not a Base API by inspecting the headers returned when you retrieve t
```suggestion
In Step 3 we created a new API and automatically linked it to the Base API. You can verify that this new API is a Version API and not a Base API by inspecting the headers returned when you retrieve the details of the API from the Tyk Gateway API. This can be achieved by issuing a `GET` request to the `/apis/oas/` endpoint passing your new API's API-ID as a path parameter:
```

2023-10-06 11:25 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
> +You will also need to have ‘admin’ or ‘api’ rights if RBAC is enabled.
I'll add a link to the RBAC page

2023-10-06 14:05 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
> +You will also need to have ‘admin’ or ‘api’ rights if RBAC is enabled.
Done

2023-10-06 14:07 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +You will also need to have ‘admin’ or ‘api’ rights if RBAC is enabled.
Done

2023-10-06 14:20 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +| Param        | Query param (options): <br>- `base_api_id`: The API ID of the Base API to which the new version will be linked.<br>- `base_api_version_name`: The version name of the base API while c
I've tidied up these tables across the whole PR so that they are consistent in formatting & layout. The reason for the parameter type in the "description" column is for consistency.

2023-10-06 14:24 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +In Step 3 we created a new API and automatically linked it to the Base API. You can verify that this new API is a Version API and not a Base API by inspecting the headers returned when you retrieve t
I've made an alternative change to wording to split up this long sentence.

2023-10-10 11:34 UTC, lghiur approved these changes

2023-10-10 11:34 UTC, lghiur commented on tyk-docs/content/getting-started/import-apis.md
> +### Import APIs via the Dashboard
should we differenciate between Dashboard UI and API ?

2023-10-10 11:34 UTC, lghiur commented on tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
> +| Tyk Dashboard API     | 3000     | `api/apis/oas`  | `authorization`       | From Dashboard User Profile      |
maybe capital A -> `Authorization` as a standard

2023-10-10 11:34 UTC, lghiur commented on tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
> +| Resource URL | `/tyk/apis/oas/{API-ID}/export`          |
do we need dashboard API row in here as well?

2023-10-10 11:34 UTC, lghiur commented on tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
> +* When using the Tyk Dashboard API, you can find your credentials key from your **User Profile > Edit Profile > Tyk Dashboard API Access Credentials**:
some of repeating docs, can be extracted into a partial template and included where needed.

2023-10-10 12:58 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
> +* When using the Tyk Dashboard API, you can find your credentials key from your **User Profile > Edit Profile > Tyk Dashboard API Access Credentials**:
I did wonder about that, but didn't know how to do it - so just copied and pasted. Maybe something to implement in a future re-write?

2023-10-10 12:58 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
> +| Tyk Dashboard API     | 3000     | `api/apis/oas`  | `authorization`       | From Dashboard User Profile      |
```suggestion
| Tyk Dashboard API     | 3000     | `api/apis/oas`  | `Authorization`       | From Dashboard User Profile      |
```

2023-10-10 13:04 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
> +| Tyk Dashboard API     | 3000     | `api/apis/oas`  | `authorization`       | From Dashboard User Profile      |
```suggestion
| Tyk Dashboard API     | 3000     | `api/apis/oas`  | `Authorization`       | From Dashboard User Profile      |
```

2023-10-10 13:05 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
> +| Tyk Dashboard API     | 3000     | `x-tyk-authorization` | From Dashboard User Profile      |
```suggestion
| Tyk Dashboard API     | 3000     | `Authorization` | From Dashboard User Profile      |
```

2023-10-10 13:06 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
> +When making calls to the Tyk Dashboard API you'll need to set the domain name and port for your environment and, in the API request header, must provide credentials in the `x-tyk-authorization` field
```suggestion
When making calls to the Tyk Dashboard API you'll need to set the domain name and port for your environment and, in the API request header, must provide credentials in the `Authorization` field for Tyk to authorise your request, as follows:
```

2023-10-10 13:10 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
> +| Tyk Dashboard API     | 3000     | `api/apis/oas`  | `authorization`       | From Dashboard User Profile      |
```suggestion
| Tyk Dashboard API     | 3000     | `api/apis/oas`  | `Authorization`       | From Dashboard User Profile      |
```

2023-10-10 13:15 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
> +| Resource URL | `/tyk/apis/oas/{API-ID}/export`          |
No - this is covered in the "Differences between using the Tyk Dashboard API and Tyk Gateway API" section above. The examples are consistent in that they detail using the Tyk Gateway API - to use Tyk Dashboard API you just apply the changes from the "Differences" section.

2023-10-10 13:16 UTC, andyo-tyk commented on tyk-docs/content/getting-started/import-apis.md
> +### Import APIs via the Dashboard
```suggestion
### Import APIs via the Dashboard UI
```

2023-10-10 13:18 UTC, andyo-tyk commented on tyk-docs/content/getting-started/import-apis.md
> +### Import APIs via the Dashboard
Yes, agreed - I've committed a change to add "UI" here

2023-10-10 13:23 UTC, andyo-tyk commented
DX-743 raised for this PR

2023-10-10 14:20 UTC, dcs3spp approved these changes

2023-10-10 14:21 UTC, merged

2023-10-10 14:21 UTC, dcs3spp commented
/release to release-5.2

2023-10-12 06:22 UTC, letzya reviewed
Better to remove leading "/", "content" and ".md"

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
> +Tyk OAS API support is currently in [Early Access]({{< ref "/content/frequently-asked-questions/using-early-access-features.md" >}}) and some Tyk features are not yet supported. You can see the statu
```suggestion
Tyk OAS API support is currently in [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}) and some Tyk features are not yet supported. You can see the status of what is and isn't yet supported [here]({{< ref "getting-started/using-oas-definitions/oas-reference" >}}). 
```

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
> +For example, given the base Tyk OAS API used [here]({{< ref "/getting-started/using-oas-definitions/update-an-oas-api#tutorial-3-update-tyk-oas-api-definition-with-an-updated-openapi-definition" >}})
```suggestion
For example, given the base Tyk OAS API used [here]({{< ref "getting-started/using-oas-definitions/update-an-oas-api#tutorial-3-update-tyk-oas-api-definition-with-an-updated-openapi-definition" >}}) we can enable the `allowList` middleware with this `PATCH` command:
```

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
> +```.json
```suggestion
```yaml
```

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
> +```json
```suggestion
```yaml
```

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
> +```.json
```suggestion
```yaml
```

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
> +```.curl
Better if we remove all dots from code block highlighting for consistency

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
> +```json
```suggestion
```yaml 
```

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
> +```.json
```suggestion
```yaml
```

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
> +Tyk OAS API support is currently in [Early Access]({{< ref "/frequently-asked-questions/using-early-access-features" >}}) and some Tyk features are not yet supported. You can see the status of what i
```suggestion
Tyk OAS API support is currently in [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}) and some Tyk features are not yet supported. You can see the status of what is and isn't yet supported [here]({{< ref "getting-started/using-oas-definitions/oas-reference" >}}).
```

2023-10-12 06:22 UTC, letzya commented on tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
> +You will also need to have ‘admin’ or ‘api’ rights if [RBAC]({{< ref "/tyk-dashboard/rbac.md" >}}) is enabled.
```suggestion
You will also need to have ‘admin’ or ‘api’ rights if [RBAC]({{< ref "tyk-dashboard/rbac" >}}) is enabled.
```

2023-11-27 17:33 UTC, dcs3spp commented
/release to release-5.1