[TT-10117] Update documentation for 5.0 LTS
TykTechnologies/tyk-docs-hugo pull request #3350
Opened 2023-10-09 08:24 UTC by buger

Triggered by: lghiur

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: 5.0 LTS

Note: Release notes for 5.0.6

JIRA: https://tyktech.atlassian.net/browse/TT-10117

2023-10-09 08:28 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  version: 4.3.0
```suggestion
  version: 5.0.0
```

Not necessary change (we don't update this version on source)...

2023-10-09 08:29 UTC, titpetric commented on tyk-docs/assets/others/gateway-swagger.yml
> +  version: 4.3.0
```suggestion
  version: 5.0.0
```

2023-10-09 09:32 UTC, dcs3spp requested changes
lgtm, only version update from 4.3.0

2023-10-09 09:32 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  version: 4.3.0
Should the version be 4.3?

2023-10-09 09:32 UTC, dcs3spp commented on tyk-docs/assets/others/gateway-swagger.yml
> +  version: 4.3.0
Should the version for 5.0 LTS be 5.0.x?

2023-10-09 09:32 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Deprecated: The field is deprecated, usage needs to be updated to configure caching.
What field should be used instead to configure caching timeout..is it the cache field at line 200?

```summary
Deprecated: The field is deprecated. Please use *service_discovery.cache_timeout* to configure caching timeout.
```

2023-10-09 09:32 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  version: 4.3.0
Should the version for 5.0 LTS be 5.0.x?

2023-10-09 09:48 UTC, lghiur approved these changes

2023-10-09 09:48 UTC, lghiur commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  version: 4.3.0
```suggestion
  version: 5.0.6
```

2023-10-17 08:08 UTC, lghiur approved these changes

2023-10-17 08:08 UTC, lghiur commented on tyk-docs/assets/others/gateway-swagger.yml
> +  version: 4.3.0
```suggestion
  version: 5.0.6
```

2023-10-17 09:45 UTC, dcs3spp approved these changes

2023-10-17 09:48 UTC, merged