[TT-10177] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #3351
Opened 2023-10-09 08:24 UTC by buger

Triggered by: lghiur

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: master

Note: Docs updates for 5.2.1

JIRA: https://tyktech.atlassian.net/browse/TT-10177

2023-10-09 09:37 UTC, dcs3spp requested changes
lgtm, minor change suggested relating to the version used on swagger files

2023-10-09 09:37 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  version: 5.0.0
```suggestion
  version: 5.2.1
```

2023-10-09 09:37 UTC, dcs3spp commented on tyk-docs/assets/others/gateway-swagger.yml
> +  version: 5.1.0
```suggestion
  version: 5.2.1
```

2023-10-10 15:23 UTC, dcs3spp approved these changes

2023-10-10 16:00 UTC, merged

2023-10-10 16:01 UTC, dcs3spp commented
/release to release-5.2

2023-10-11 08:11 UTC, letzya commented on tyk-docs/content/shared/gateway-config.md
> +### resource_sync
@dcs3spp why do we have only a description?

2023-10-11 08:49 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +### resource_sync
@letzya This a description for the config entity. The sentence is an overview for what the entity represents.

Then the items below are the attributes of that entity, e.g. resource_sync.retry_attempts and resource_sync.interval