[TT-9891] Improved clarity on key lifetime controls
TykTechnologies/tyk-docs-hugo pull request #3355
Opened 2023-10-09 15:26 UTC by andyo-tyk

### Preview Link
TBC

### Description
Improved explanation of the interactions between `session_lifetime`, `global_session_lifetime`, `force_global_session_lifetime` and `session_lifetime_respects_key_expiration`.

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-10 11:18 UTC, dcs3spp requested changes
PR looks good to me. I like the idea of including the table for assigned key lifetime for the different configurations!

Added couple of minor suggestions and once a peer review has been approved I'll merge and release.

2023-10-10 11:18 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
> +### Summary of key lifetime (deletion) configuration
```suggestion
### Summary of key lifetime precedence
```

2023-10-10 11:18 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
> +| `force_global_session_lifetime` | `session_lifetime_respects_key_expiration` | Lifetime assigned to key (in seconds)     |
```suggestion
| `force_global_session_lifetime` | `session_lifetime_respects_key_expiration` | Assigned lifetime |
```

2023-10-10 11:18 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
> +
```suggestion

The table below shows the key lifetime assigned for the different permutations of `force_global_session_lifetime` and  `session_lifetime_respects_key_expiration` configuration parameters.
```

2023-10-10 14:27 UTC, dcs3spp approved these changes

2023-10-10 19:04 UTC, furkansenharputlu commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
> +If you want to the key to be deleted when it expires (i.e. to use the expiry configured in `expires` within the key to control deletion) then you must set a non-zero value in `session_lifetime` and c
shouldn't this be "if you want the key to be deleted..."

2023-10-10 19:08 UTC, furkansenharputlu commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
> +To enable this global lifetime, you must also set the [force_global_session_lifetime]({{< ref "tyk-oss-gateway/configuration#force_global_session_lifetime" >}}) parameter in the `tyk.conf` file.
I don't know why but when I click the `Display rich diff` button to preview the changes the links are not working. Is it a problem in the display mode or actually a misuse of link notation?

2023-10-10 19:09 UTC, furkansenharputlu reviewed
Added minor comments. Technical-wise, LGTM.

2023-10-11 14:33 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
> +If you want to the key to be deleted when it expires (i.e. to use the expiry configured in `expires` within the key to control deletion) then you must set a non-zero value in `session_lifetime` and c
Oops 🤦

2023-10-11 14:34 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
> +To enable this global lifetime, you must also set the [force_global_session_lifetime]({{< ref "tyk-oss-gateway/configuration#force_global_session_lifetime" >}}) parameter in the `tyk.conf` file.
I think it's a Hugo thing - you need to go via the Netlify [link](https://deploy-preview-3355--tyk-docs.netlify.app/docs/nightly/basic-config-and-security/security/authentication-authorization/physical-key-expiry/) to check links.

2023-10-11 14:34 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
> +If you want to the key to be deleted when it expires (i.e. to use the expiry configured in `expires` within the key to control deletion) then you must set a non-zero value in `session_lifetime` and c
```suggestion
If you want the key to be deleted when it expires (i.e. to use the expiry configured in `expires` within the key to control deletion) then you must set a non-zero value in `session_lifetime` and configure both `session_lifetime_respects_key_expiration:true` and `force_global_session_lifetime:false`.
```

2023-10-12 09:09 UTC, furkansenharputlu approved these changes

2023-10-12 11:35 UTC, merged

2023-10-12 11:36 UTC, dcs3spp commented
/release to release-5.2