[TT-9703] - Update Tyk Pump Configurations docs for Helm charts
TykTechnologies/tyk-docs-hugo pull request #3383
Opened 2023-10-16 09:25 UTC by buraksekili

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>
Changes needed as part of this ticket: https://tyktech.atlassian.net/browse/TT-9703
---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-17 08:58 UTC, dcs3spp requested changes
Many thanks for submitting PR Burak. The PR looks good to me. I have made some minor suggestions. Once changes have been made will merge and release

2023-10-17 08:58 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +[Setup Dashboard Analytics]({{< ref "/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config" >}}).
```suggestion
[Setup Dashboard Analytics]({{< ref "/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config" >}}) page. 
```

2023-10-17 08:58 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +> To explore the list of supported backends for Tyk Pump, please visit [Other Data Stores for Tyk Pump]({{< ref "/tyk-stack/tyk-pump/other-data-stores" >}}).
```suggestion
> To explore the list of supported backends for Tyk Pump, please visit [other data stores for Tyk Pump]({{< ref "/tyk-stack/tyk-pump/other-data-stores" >}}). 
```

2023-10-17 17:03 UTC, caroltyk requested changes
Thank you for making the change. Looks good with some terminology updates.

2023-10-17 17:03 UTC, carolwkc commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +| Postgres Pump             | Add `postgres` to `pump.backend`, and add connection details for postgres under `.postgres`.               |
```suggestion
| SQL Pump             | Add `postgres` to `pump.backend`, and add connection details for postgres under `.global.postgres`.               |
```

2023-10-17 17:03 UTC, carolwkc commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +| Postgres Aggregate Pump   | Add `postgres-aggregate` to `.pump.backend`, and add connection details for postgres under `.global.postgres`.    |
```suggestion
| SQL Aggregate Pump   | Add `postgres-aggregate` to `.pump.backend`, and add connection details for postgres under `.global.postgres`.    |
```

2023-10-17 17:03 UTC, carolwkc commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +| Postgres Pump             | Add `postgres` to `pump.backend`, and add connection details for postgres under `.postgres`.               |
To be consistent with name used in https://tyk.io/docs/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config/, let's call it SQL Pump and SQL Aggregate Pump

2023-10-17 17:03 UTC, caroltyk commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +2. postgres: Used to set Postgres pump for uptime analytics. Postgres Pump should be enabled.
```suggestion
2. postgres: Used to set SQL pump for uptime analytics. SQL Pump should be enabled.
```

2023-10-17 17:15 UTC, buraksekili commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +| Postgres Pump             | Add `postgres` to `pump.backend`, and add connection details for postgres under `.postgres`.               |
After considering the discussion at https://github.com/TykTechnologies/tyk-charts/pull/126#discussion_r1356390323, we've opted for Postgres based on the insights shared.  Do you think we should go with SQL? If so, further changes are needed on the charts.

2023-10-18 14:49 UTC, caroltyk commented
@buraksekili should it be merge to https://github.com/TykTechnologies/tyk-docs/pull/3183?

2023-10-19 18:18 UTC, letzya commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +[Setup Dashboard Analytics]({{< ref "/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config" >}}) page.
```suggestion
[Setup Dashboard Analytics]({{< ref "tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config" >}}) page. 
```

2023-10-19 18:19 UTC, letzya commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +> To explore the list of supported backends for Tyk Pump, please visit [other data stores for Tyk Pump]({{< ref "/tyk-stack/tyk-pump/other-data-stores" >}}).
```suggestion
> To explore the list of supported backends for Tyk Pump, please visit [other data stores for Tyk Pump]({{< ref "tyk-stack/tyk-pump/other-data-stores" >}}). 
```

2023-10-19 18:19 UTC, letzya commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
>  NOTE: [Here is](https://tyk.io/docs/planning-for-production/database-settings/) list of supported MongoDB versions. Please make sure you are installing mongo helm chart that matches these versions.
@dcs3spp would be good to update this to use ref

2023-10-19 18:21 UTC, letzya commented
@caroltyk I'm a bit worried about this duplication in the docs and the helm-chart. Would be nice if in the future we could have a similar flow to the one we have for config files - generate it from code and copy it over to the docs?

2023-10-24 11:12 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
>  NOTE: [Here is](https://tyk.io/docs/planning-for-production/database-settings/) list of supported MongoDB versions. Please make sure you are installing mongo helm chart that matches these versions.
Done

2023-10-25 22:29 UTC, caroltyk commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
> +| Postgres Pump             | Add `postgres` to `pump.backend`, and add connection details for postgres under `.postgres`.               |
That's a difficult question. It's how we name the pumps now unfortunately. I realised we do not support sqlite pump now... so that's fine, let's go with postgres pump and postgres aggregate pump.

2023-10-25 22:32 UTC, caroltyk approved these changes
LGTM. Thanks

2023-10-26 09:54 UTC, dcs3spp approved these changes

2023-10-26 10:48 UTC, dcs3spp commented
Ready for merge and release when Tyk Charts released

2023-11-01 10:23 UTC, merged

2023-11-01 10:23 UTC, dcs3spp commented
/release to release-5.2