Add Tyk Gateway and Tyk Dashboard Release Notes 5.2.2
TykTechnologies/tyk-docs-hugo pull request #3384
Opened 2023-10-16 13:14 UTC by dcs3spp

Initial 5.2.2 release notes for Gateway & Dashboard

The content has not been reviewed. If PMs can review and update ready for DX review.

2023-10-18 09:49 UTC, caroltyk approved these changes

2023-10-18 09:49 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added a new Dashboard configuration option `Allow_Unsafe_Oas`. This permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. This is not a recommended action due to the risk of i
@andyo-tyk Should this be removed 'Please note that `Allow_Unsafe_Oas` must be set to `True` to use Tyk OAS APIS with Tyk Sync.'?

2023-10-19 14:07 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added a new Dashboard configuration option `Allow_Unsafe_Oas`. This permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. This is not a recommended action due to the risk of i
```suggestion
- Added a new Dashboard configuration option `allow_unsafe_oas`. This permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. This is not a recommended action due to the risk of inconsistent behaviour and potential for breaking changes while Tyk OAS is in [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}). However, it is provided for early adopters and will be deprecated later.
```

2023-10-19 14:31 UTC, andyo-tyk requested changes
There are lots of weird capitalisations and conversion of all-caps into mixed case - I've suggested changes for most, but all the CVE references should be capitalised (it's an abbreviation).

Also one GW change is a community contribution so I think should be placed in that section.

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +If you are on a 5.2.0 we advise you to upgrade ASAP and if you are on an older version skip 5.2.0 and upgrade directly to this release.
Does this sentence actually make sense? I think the idea is to encourage users to go to the latest, whatever it is (i.e. not to have to keep updating this part of the page), but I'm not sure it's completely clear.

Perhaps:
```suggestion
If you are using a 5.2.x version, we advise you to upgrade ASAP to this latest release. If you are on an older version, you should skip 5.2.0 and upgrade directly to this release.
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue where Tyk would not store the *Policy Id* in the *Api Definition* for a policy that did not exist. When using *JWT Authentication*, the *JWT Default Policy Id* is stored in the *Api
API should always be in upper case - it is an abbreviation.

```suggestion
- Fixed an issue where Tyk would not store the *Policy Id* in the *API Definition* for a policy that did not exist. When using *JWT Authentication*, the *JWT Default Policy Id* is stored in the *API Definition*. If this policy had not been created in Tyk at the time the *API Definition* was created, Tyk Dashboard would invalidate the field in the *API Definition*. When the policy was later created, there would be no reference to it from the *API Definition*. This was a particular issue when using *Tyk Operator* to manage the creation of assets on Tyk.
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue in The Tyk Dashboard where a user did not correctly inherit all permissions from their user group, permitting visibility of identity management.
```suggestion
- Fixed an issue in The Tyk Dashboard where a user did not correctly inherit all permissions from their user group, incorrectly permitting visibility of Identity Management.
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +    - [Cve-2022-33082](https://nvd.nist.gov/vuln/detail/CVE-2022-33082)
All of these should be capitalised, I don't understand why they've been made mixed case?
```suggestion
    - [CVE-2022-33082](https://nvd.nist.gov/vuln/detail/CVE-2022-33082)
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue encountered with *Azure Saml2.0 Identity Provider* that was preventing users from authenticating.
Again, SAML has been made mixed case :(

```suggestion
- Fixed an issue encountered with *Azure SAML2.0 Identity Provider* that was preventing users from authenticating.
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a security vulnerability with the Tyk Dashboard API where the `Url_Version` query parameter was a potential target for a SQL injection attack. This addresses [Cve-2023-42284](https://nvd.nist
`url_version` is a parameter name - it's lower case - not sure why it's been made mixed case here?

```suggestion
- Fixed a security vulnerability with the Tyk Dashboard API where the `url_version` query parameter was a potential target for a SQL injection attack. This addresses [CVE-2023-42284](https://nvd.nist.gov/vuln/detail/CVE-2023-2284).
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a security vulnerability with the Tyk Dashboard API where the `Url_Version` query parameter was a potential target for a SQL injection attack. This addresses [Cve-2023-42283](https://nvd.nist
```suggestion
- Fixed a security vulnerability with the Tyk Dashboard API where the `url_version` query parameter was a potential target for a SQL injection attack. This addresses [CVE-2023-42283](https://nvd.nist.gov/vuln/detail/CVE-2023-40283).
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Renamed The Licence Limit To Licence Entitlement. Hide The Licence Entitlement Line From The Chart In Case Its Value Is Set To 0.
Weirdly this comment has every word capitalised!!

```suggestion
- On Tyk Dashboard's Licensing Statistics screen we have renamed the Licence Limit to Licence Entitlement. We've also improved the experience when there is no limit in the licence by hiding the Licence Entitlement line if no limit is set.
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +If you are on a 5.2.0 we advise you to upgrade ASAP and if you are on an older version skip 5.2.0 and upgrade directly to this release.
Same comment as for the Dashboard docs, so perhaps:

```suggestion
If you are using a 5.2.x version, we advise you to upgrade ASAP to this latest release. If you are on an older version, you should skip 5.2.0 and upgrade directly to this release.
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Added a new Dashboard configuration option `Allow_Unsafe_Oas`. This permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. This is not a recommended action due to the risk of i
This is a Dashboard feature, there are only minor changes in the GW behind the scenes to support this - I'm not sure if we need to call it out here.

```suggestion
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Implemented *Ulid Normalization*, replacing valid Ulid identifiers in the URL with a `{Ulid}` placeholder for analytics. This matches the pre-existing Uuid normalization. This is an open-source con
This has weird capitalisation - but is also a community contribution, so should be in the that section, AFAIK.

```suggestion
- Implemented *ULID Normalization*, replacing valid ULID identifiers in the URL with a `{ulid}` placeholder for analytics. This matches the existing UUID normalization. Thanks to [Mohammad Abdolirad](https://github.com/atkrad) for the contribution.
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed an issue where enforced timeout values were incorrect on a per-request basis. Since we enforced timeouts only at the transport level and created the transport only once within the value set b
Capitalisation of field names again??

```suggestion
- Fixed an issue where enforced timeout values were incorrect on a per-request basis. Since we enforced timeouts only at the transport level and created the transport only once within the value set by [max_conn_time]({{< ref "tyk-oss-gateway/configuration#max_conn_time" >}}), the timeout in effect was not deterministic. Timeouts larger than 0 seconds are now enforced for each request.
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed the following high priority Cves identified in the Gateway to provide increased protection against security vulnerabilities. Note that the logstash formatter timestamp is now in [RFC3339Nano]
Again, all of the CVEs should be capitalised in the following list.

```suggestion
- Fixed the following high priority CVEs identified in the Gateway to provide increased protection against security vulnerabilities. Note that the logstash formatter timestamp is now in [RFC3339Nano](https://www.rfc-editor.org/rfc/rfc3339) format.
```

2023-10-19 14:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed a potential race condition where the *Drl Manager* was not properly protected against concurrent read/write operations in some high load scenarios.
```suggestion
- Fixed a potential race condition where the *DRL Manager* was not properly protected against concurrent read/write operations in some high load scenarios.
```

2023-10-23 08:36 UTC, agata-wit approved these changes

2023-10-31 12:07 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +##### Release Date 27 Oct 2023
```suggestion
##### Release Date 31 Oct 2023
```

2023-10-31 12:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Release Date 27 Oct 2023
```suggestion
##### Release Date 31 Oct 2023
```

2023-10-31 15:38 UTC, andyo-tyk requested changes
Some rewording suggestions, added one (late) change that was missing from the log

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a security vulnerability with the Tyk Dashboard API where the `url_version` query parameter was a potential target for a SQL injection attack. This addresses [CVE-2023-42284](https://nvd.nist
```suggestion
- Fixed a security vulnerability with the Tyk Dashboard API where the `api_version` and `api_id` query parameters were potential targets for SQL injection attack.
```

CVEs were provisional - not actually raised

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed a security vulnerability with the Tyk Dashboard API where the `url_version` query parameter was a potential target for a SQL injection attack. This addresses [CVE-2023-42283](https://nvd.nist
```suggestion
```

Not required - merged with previous entry.

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue encountered with the *API Designer* where fields defined in *Uptime_Tests.Check_List* were not correctly handled. Uptime tests can now be safely handled for *Tyk Classic APIs* in the
```suggestion
- Fixed an issue encountered with the *API Designer* where fields defined in *Uptime_Tests.Check_List* were not correctly handled. Uptime tests can now be configured for *Tyk Classic APIs* using the *Raw API Definition* editor.
```

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed the following high priority Cves identified in the dashboard to provide increased protection against security vulnerabilities:
```suggestion
- Fixed the following high priority CVEs identified in the Tyk Dashboard, providing increased protection against security vulnerabilities:
```

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Added a new Dashboard configuration option `allow_unsafe_oas`. This permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. This is not a recommended action due to the risk of i
```suggestion
- Added a new Dashboard configuration option `allow_unsafe_oas`. This permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. This is not a recommended action due to the risk of inconsistent behaviour and potential for breaking changes while Tyk OAS is in [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}). This is provided for early adopters and will be deprecated later, once Tyk OAS reaches full maturity.
```

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue with MongoDB where Tyk could incorrectly grant access to an API using a key after that API had been deleted from the associated policy. This was due to the policy cleaning operation
```suggestion
- Fixed an issue when using MongoDB and [Tyk Security Policies]({{< ref "getting-started/key-concepts/what-is-a-security-policy" >}}) where Tyk could incorrectly grant access to an API after that API had been deleted from the associated policy. This was due to the policy cleaning operation that is triggered when an API is deleted from a policy in a MongoDB installation. With this fix, the policy cleaning operation will not remove the final (deleted) API from the policy; Tyk recognises that the API record is invalid and denies granting access rights to the key.
```

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- Fixed an issue in The Tyk Dashboard where a user did not correctly inherit all permissions from their user group, incorrectly permitting visibility of Identity Management.
```suggestion
- Fixed an issue in the Tyk Dashboard where a user might not correctly inherit all permissions from their user group, and could incorrectly be granted visibility of Identity Management.
```

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.2.0">}}) below.
Again, should this link to v5.2.2?

```suggestion
For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.2.2">}}) below.
```

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.2.0">}}) below.
Should this link to #Changelog-v5.2.2 instead?

```suggestion
For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.2.2">}}) below.
```

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed an issue with MongoDB where Tyk could incorrectly grant access to an API using a key after that API had been deleted from the associated policy. This was due to the policy cleaning operation
```suggestion
- Fixed an issue when using MongoDB and [Tyk Security Policies]({{< ref "getting-started/key-concepts/what-is-a-security-policy" >}}) where Tyk could incorrectly grant access to an API after that API had been deleted from the associated policy. This was due to the policy cleaning operation that is triggered when an API is deleted from a policy in a MongoDB installation. With this fix, the policy cleaning operation will not remove the final (deleted) API from the policy; Tyk recognises that the API record is invalid and denies granting access rights to the key.
```

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- Fixed the following high priority CVEs identified in the Gateway to provide increased protection against security vulnerabilities. Note that the logstash formatter timestamp is now in [RFC3339Nano]
```suggestion
- Fixed the following high priority CVEs identified in the Tyk Gateway, providing increased protection against security vulnerabilities. Note that the logstash formatter timestamp is now in [RFC3339Nano](https://www.rfc-editor.org/rfc/rfc3339) format.
```

2023-10-31 15:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +
```suggestion

- Fixed an issue where the Tyk Gateway logs would include sensitive information when the incorrect signature is provided in a request to an API protected by HMAC authentication.

```

2023-10-31 16:02 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
> +- [docker image TO ADD](https://hub.docker.com/layers/tykio/tyk-dashboard/v5.2.1/images/sha256-2f9d8af0e57f7fe4afb618dcf34772c001104dc0ec62a27541d12dc9ae90d5c8?context=explore)
- [docker image to pull](https://hub.docker.com/layers/tykio/tyk-dashboard/v5.2.2/images/sha256-c6e701e270ebb2fed815483723375c454d0479ae41b5be2e1a6198b8d1e1a154?context=explore)

2023-10-31 16:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- [docker image to ADD](https://hub.docker.com/layers/tykio/tyk-dashboard/v5.2.1/images/sha256-2f9d8af0e57f7fe4afb618dcf34772c001104dc0ec62a27541d12dc9ae90d5c8?context=explore)
```suggestion
- [docker image to pull](https://hub.docker.com/layers/tykio/tyk-gateway/v5.2.2/images/sha256-84d9e083872c78d854d3b469734ce40b7e77b9963297fe7945e214a0e6ccc614?context=explore)
```

2023-10-31 16:57 UTC, andyo-tyk approved these changes
Great, thanks.

2023-10-31 17:03 UTC, merged

2023-10-31 17:03 UTC, dcs3spp commented
/release to release-5.2