Add release notes for the EDP.
TykTechnologies/tyk-docs-hugo pull request #3407
Opened 2023-10-18 19:36 UTC by slega

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-19 13:04 UTC, dcs3spp requested changes
Hi Sergie, I am not sure whether this is ready for review yet?

Just in case, I have created a ticket and done an initial review.  Overall content looks good and release highlights are detailed.

- I have made some suggestions and comments on existing PR content.  
- For the change-log items add a sentence or two explaining how each added feature/fix benefits the customer. 
- Update release notes to include the section headings from the release notes template so that new Tyk release notes are consistently structured and formatted. 

There is a new template for release notes that is available on GHub here (https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md)  that I think Yarra has provided previously.  This is markdown file that contains section headings and guidance notes as comments. We also have this template in confluence (https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Release+Notes+Template)

There is also an example release notes for [Gateway](https://tyk.io/docs/product-stack/tyk-gateway/release-notes/version-5.2/) and [Dashboard](https://tyk.io/docs/product-stack/tyk-dashboard/release-notes/version-5.2/)

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +This release introduce a variety of features to achieve better developer experience. Additionally, we've included support for the S3 storage type as well as some bug fixes.
```suggestion
This release introduce a variety of features to improve developer experience. Additionally, we've included support for the S3 storage type as well as some bug fixes.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +Now API Consumers can [create organizations]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md">}}) and securely share c
```suggestion
Now API Consumers can [create organizations]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations">}}) and securely share credentials between their teammates. In greater detail:
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- API providers can configure whether they allow API consumers to request an upgrade to their accounts for an organizational account.
```suggestion
- API Providers can configure whether they allow API consumers to request an upgrade to their accounts for an organizational account. 
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- API Providers can manually accept, reject, or configure to accept all such request to accepted by default.
```suggestion
- API Providers can manually accept, reject or configure to accept all such request to accepted by default.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +API Providers can add [Get started guides]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-product
```suggestion
API Providers can add [Get started guides]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products">}}) to API Products for better developer experiences:
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- API Providers can add the Get started guides to API Products to speed-up onboarding of API Consumers.
```suggestion
- API Providers can add the **Get started guides** to API Products to speed-up onboarding of API Consumers.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- API Providers can use HTML or Markdown editors for authoring content for API Consumers such as the Get started guides and blog posts.
```suggestion
- API Providers can use HTML or Markdown editors for authoring content for API Consumers such as the *Get started guides* and blog posts.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +API Providers can select which blogs posts to display on an API Product page using [the tags feature]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-
```suggestion
API Providers can select which blogs posts to display on an API Product page using [the tags feature]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products#step-4-add-tags-to-blogs-and-api-products">}}). To achieve that, an API Provider can specify tags for both API Products and blog posts. Blog posts that match tags with an API Product are displayed in the 'Related blog content' section in the API Product page. This offers API Providers greater control over what blog posts to display on their API Product page.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +We added [S3 support]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md#portal_storage">}}) for the portal assets storage (the
```suggestion
We added [S3 support]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal_storage">}}) for the portal assets storage (themes, images, OAS files). This update enhances the extensibility of our platform, allowing you to choose different storage solutions to better align with your specific needs.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +## Added
```suggestion

## Added
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Added the [organization management capability]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md">}}) for API Consumer
```suggestion
- Added the [organization management capability]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations">}}) for API Consumers.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Added the [Get started guides]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products.md">}})
```suggestion
- Added the [Get started guides]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products">}}) for API Products
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Added support for [`s3` storage type]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md#portal_storage">}}) for the portal's
```suggestion
- Added support for [S3 storage]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal_storage">}}) for the portal's assets storage.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Added [tags]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products.md#step-4-add-tags-to-blog
```suggestion
- Added [tags]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products#step-4-add-tags-to-blogs-and-api-products">}}) for API Products and blog posts.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Fixed a bug in the DCR flow when scope from an API Product were not assigned to the oAuth2.0 client.
Explain how this caused an issue for the issue and how the customer benefits

```suggestion
- Fixed an issue in the DCR flow when scopes from an API Product were not assigned to the OAuth2.0 client.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Fixed the bootstrap process to print JWT instead of the portal’s internal auth token when bootstrapping the portal.
Does this print 'JWT' to hide portal's token or does it print an actual JWT instead of Portal's internal auth token?

Explain how this caused an issue for the issue and how the customer benefits

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- The portal hadn't removed plans and products that are fetched from a Tyk Dashboard instance that was disconnected from the portal instance. This fix resolves this problem.
```suggestion
- Fixed an issue where  plans and products were not removed for Tyk Dashboard instances that were disconnected from the portal instance. Subsequently, after this fix plans and products are only displayed for available Tyk Dashboard instances.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +# Changelog
For the added change log items add a sentence summarising how each feature benefits the customer.

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +This release is primarily focused on the better deployment support for Kubernetes and a variety of features to achieve better developer experience.
```suggestion
This release is primarily focused on improved deployment support for Kubernetes and a variety of features to achieve better developer experience.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +The Tyk Enterprise Developer Portal is now available in Kubernetes and customer can launch it using our [helm charts]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/insta
```suggestion
The Tyk Enterprise Developer Portal is now available in Kubernetes and customer can launch it using our [helm charts]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-using-helm">}}). This feature makes the portal Kubernetes friendly by adding liveness, readiness probes, graceful shutdown and changing the portal lifecycle so that it’s possible to set an initial user and bootstrap the portal via APIs.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +API Providers can [configure Single Sign-on]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md">}}) for the Enterprise developer portal so that
```suggestion
API Providers can [configure Single Sign-on]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso">}}) for the Enterprise developer portal so that it’s possible to login developers and admins to the portal user 3rd party IdP.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +## API Analytics for API Consumers
Add a concluding sentence that explains how these new tags benefit the customer, e.g. with a use case.

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- List available API Products;
```suggestion
- List available API Products.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Change the content and description;
```suggestion
- Change the content and description.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +This feature enables the admin users to manage API Products:
```suggestion
This feature provides an API to make it easier for admin users to manage their API Products:
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Add API specs to APIs.
What is meant buy API specs? Does it mean OAS schema?

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +This feature enables API Provides to secure the portal with [HTTPs]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md#portal_t
```suggestion
This feature enables API Provides to secure the portal with [HTTPs]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal_tls_enable">}}).
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +## Add a config option to set the log level
```suggestion
## Add enhanced logging configuration
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +This new setting allows API Provides to set the [log level]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md#portal_log_level
```suggestion
This new setting allows API Providers to set the logging [level]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal_log_level">}}) and [format]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal_log_format">}}). This offers API Providers more control over the logging behaviour of their APIs.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +## Added
```suggestion

## Added
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Added Kubernetes support and [helm charts]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-using-helm.md"
```suggestion
- Added Kubernetes support and [helm charts]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-using-helm">}}).
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Added [Single Sign-on]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md">}}) for API Consumers and admin users.
```suggestion
- Added [Single Sign-on]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso">}}) for API Consumers and admin users.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Added organisation and application metadata to auth tokens and oAuth2.0 clients.
```suggestion
- Added organisation and application metadata to auth tokens and OAuth2.0 clients.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Added [TLS]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md#portal_tls_enable">}}) support.
```suggestion
- Added [TLS]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal_tls_enable">}}) support.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Added the config option to set the [log level]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md#portal_log_level">}}) and [
```suggestion
- Added config options to set the logging [level]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal_log_level">}}) and [format]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal_log_format">}}). This offers API Providers more control over the logging behaviour of their APIs.
```

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Fixed copy in the admin application on the Application page.
Explain here what the problem was with the copy feature from the user's perspective? How was it fixed and how does the fixed copy feature now behave.

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Fixes the DCR issue when developer wants to delete an app with two DCR products from different catalogues.  In that case, the client was deleted from IdP but the app is not deleted from the Portal.
```suggestion
- Fixes an issue with DCR that was encountered when a developer deletes an app with two DCR products from different catalogues.  In that case, the client was deleted from IdP but the app was not deleted from the Portal.
```
Add a sentence that explanation that explains how the fix now behaves.

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Fixes wrong path to the executable in .service file.
Update to explain how this was a problem from the user's perspective (what behaviour did the user observe when this was a problem) and how does the fix now behave.

2023-10-19 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +# Changelog
For each item in the Added section of the change-log add a sentence that explains how the new feature benefits the customer

2023-10-21 00:22 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +# Changelog
It's a draft PR, not intended for a review

2023-10-21 00:23 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +# Changelog
They are already described in details in the release highlights

2023-10-21 00:27 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Fixed the bootstrap process to print JWT instead of the portal’s internal auth token when bootstrapping the portal.
Neither. This implementation printed the internal auth token which is no accepted by the portal's APIs. The customer can actually use this token to authenticate in the APIs.

2023-10-21 00:28 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +## API Analytics for API Consumers
It's interim implementation. The real value comes in the next release.

2023-10-21 00:29 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Add API specs to APIs.
It means a link to an Open API specification.

2023-10-21 00:30 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +# Changelog
Again, they are already described in the release highlights.

2023-10-23 08:41 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Fixed the bootstrap process to print JWT instead of the portal’s internal auth token when bootstrapping the portal.
```suggestion
- Fixed a security issue with the bootstrap process to print _JWT_ instead of the portal’s internal auth token when bootstrapping the portal.
```

2023-10-25 08:38 UTC, dcs3spp requested changes
Hi Sergei, For the changelog need a summary sentence to explain the beneift/impact to the customer. 

This requirement has come from James in release notes user research

https://tyktech.atlassian.net/wiki/spaces/EN/pages/1923514430/Release+notes+improvement+-+research?focusedCommentId=2172158026#Understand-why-release-notes-are-important-for-clients

2023-10-26 13:08 UTC, dcs3spp requested changes
Hi @slega,

I have looked through new change-logs added for 1.3.0 - 1.7.0 and really detailed with good explanations. The fixes sections of the change-log also have good explanation. Need to get links added once the docs are available, maybe in a different iteration / PR when the docs are available??

I’ve made some minor grammar suggestions. The only other thing that I have seen is that the headings might need updated so that change-log appears in the right sidebar crumb-trail. Maybe try reducing the heading level to 

<hash character><hash character> Changelog
<hash character><hash character><hash character> Added etc. etc.

The new website has a dedicated folder for EDP at
_tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes_ 

If we can move the release notes into that folder and update menu.yaml 

 While looking at the section headings, I have also spotted something which I will add to review comments relating to consistent structure of Tyk Release Notes.

Across Tyk components, aiming to have the same section headings. An example is (https://tyk.io/docs/product-stack/tyk-gateway/release-notes/version-5.2/)

On the release notes guidelines (https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes) and the Ghub template that Yaara sent (https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md) there are some section headings missing.

Following short sections need to be added to provide consistent structure for EDP. They can be copied from the provided markdown template and updated.

Release date (can be copy and pasted from the GHub markdown template and updated)
Breaking changes (can be copy and pasted from the GHub markdown template and updated)
Future breaking changes
Upgrade instructions
Downloads (link to docker image for EDP?)

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.7.0.md
> +- Fixed the bug where developers and apps of an organization were not deleted when the organization was deleted.
```suggestion
- Fixed the bug where developers and apps of an organisation were not deleted when the organisation was deleted.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.7.0.md
> +- Fixed the bug where developers and apps of an organization were not deleted when the organization was deleted.
```suggestion
- Fixed the bug where developers and apps of an organisation were not deleted when the organisation was deleted.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +Now the Tyk Enterprise Developer portal can use multiple identity providers (IdPs) for OAuth2.0 via the Dynamic Client Registration flow. If your company has multiple oAuth2.0 providers now you can u
```suggestion
Now the Tyk Enterprise Developer portal can use multiple identity providers (IdPs) for OAuth2.0 via the Dynamic Client Registration flow. If your company has multiple OAuth2.0 providers now you can utilize them all for oAuth2.0 authentication. For instance, if your company uses different IdPs for different products (e.g. one for the U.S. and another for the EU) you can now achieve that with Tyk.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +You can download all CMS content with just one API call with the brand new API endpoint GET /pages/all/content-blocks that returns all content blocks for all pages. Now migration between environments
```suggestion
You can download all CMS content with just one API call with the brand new API endpoint *GET* */pages/all/content-blocks* that returns all content blocks for all pages. Now migration between environments and deployment is much easier.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +## Display-only support for API Products with the custom authentication
```suggestion
## Display-only support for API Products with custom authentication
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +This new capability you can display on the portal APIs use your own custom authentication mechanisms. We appreciate that many customer use their own auth mechanisms and even though at the moment we c
```suggestion
This new capability allows you to display on the portal the APIs that use your own custom authentication mechanisms. We appreciate that many customer use their own auth mechanisms and even though at the moment we cannot create credentials for custom authentication schemas, we still want to support customers using these.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +- Added support for multiple IdPs of the OAuth2.0 flow. If a customer has multiple oAuth2.0 providers now they can utilize them all for oAuth2.0 authentication with Tyk.
```suggestion
- Added support for multiple IdPs of the OAuth2.0 flow. If a customer has multiple OAuth2.0 providers now they can utilise them all for OAuth2.0 authentication with Tyk.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +- Added support for API Products that use Mutual TLS. Now API Provider can surface their API Products that use Mutual TLS authentication on the portal and developer can request access to them.
```suggestion
- Added support for API Products that use Mutual TLS. Now API Providers can surface their API Products that use Mutual TLS authentication on the portal and developer can request access to them.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +- Added display-only support for API Products with the custom authentication so that API Providers can expose on the portal their APIs that use custom auth for documentation purposes.
```suggestion
- Added display-only support for API Products with custom authentication. This allows API Providers to expose on the portal their APIs that use custom authentication for documentation purposes. 
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +- Simplified the connection settings to the portal assets storage (where all images, themes, and other CMS files are stored) to help our customers get up to speed quicker. We are well aware that inst
```suggestion
- Simplified the connection settings to the portal assets storage (where all images, themes, and other CMS files are stored) to help our customers get up to speed quicker. We are well aware that installing and configuring on-premise software can be tricky, especially when it comes to infrastructure, storage and databases. Hence, we have decided to ease this burden for you:
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +  - We also simplified setting for the s3 storage: now you need only to configure connection settings to the bucket and the portal will handle the rest.
```suggestion
  - We also simplified setting up S3 storage: now you need only to configure connection settings to the bucket and the portal will handle the rest.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +  - Added the ability to disable the theme upload capability. Since we don’t validate the theme content it might have viruses and other malicious software. So, super secure environments, we added a s
```suggestion
  - Added the ability to disable the theme upload capability. Since we don’t validate the theme content it might have viruses and other malicious software. So, to provide super secure environments, we added a setting to disable the theme upload via the UI and API:
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +  - Fixed the Users API resource which allowed to enter any value into the Provider and Role fields.
```suggestion
  - Fixed the Users API resource which allowed any value to be entered into the Provider and Role fields.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +  - Fixed the bug where theme unpacking required unnecessary write permission to the /tmp folder.
```suggestion
 - Fixed the bug where theme unpacking required unnecessary write permission to the */tmp* folder.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
> +With this new option, Tyk Enterprise Developer portal can be configured to use untrusted certificates when connecting the Tyk Dashboard which helps a lot to run local quick and easy PoC.
```suggestion
With this new option, Tyk Enterprise Developer portal can be configured to use untrusted certificates when connecting the Tyk Dashboard which helps run local PoCs, quickly and easily.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
> +It also allows adding access API Products to existing credentials. This way, if an API Consumer wants to add a new API Product to an existing credential, they can simply do it without the need to rec
```suggestion
It also allows adding access to API Products to existing credentials. This way, if an API Consumer wants to add a new API Product to an existing credential, they can simply do it without the need to recreate them from scratch.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
> +The improved oAuth2.0 allows API Providers to configure oAuth2.0 with scope to policy mapping and default No-Operation policies reducing the number of steps configure oAuth2.0 product in the Dashboar
Is it with or without (heading mentions without) 

```suggestion
The improved OAuth2.0 allows API Providers to configure OAuth2.0 with scope to policy mapping and default No-Operation policies reducing the number of steps configure OAuth2.0 product in the Dashboard in the IdP by 17 steps from 19 to just 2 actions.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
> +- Added improved oAuth2.0 flow without the scope to policy mapping which makes it literally 10 times easier to configure oAuth2.0 with Tyk.
```suggestion
- Added improved OAuth2.0 flow without the scope to policy mapping which makes it much easier to configure OAuth2.0 with Tyk.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
> +- Added the Status and Last synced columns that to the API Provider page to make easier to digest status of each API Provider.
```suggestion
- Added the Status and Last synced columns to the API Provider page to make easier to digest status of each API Provider.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
> +- Added new admins APIs for the Get started guides, Open API Specifications, and API Providers to enable migration of configurations between different environments of the portal.
```suggested
- Added new admins APIs for the Get started guides, Open API Specifications and API Providers to enable migration of configurations between different environments of the portal.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
> +  - Add secure and httpOnly flags to session cookie to .
Should this be something like:

```suggestion
  - Add secure and httpOnly flags to enhace the security of session cookies.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
> +  - Fixed the bug where the Users API resource which allowed to enter any value into the Provider and Role fields.
```suggestion
  - Fixed the bug with the Users API resource where it was possible to enter any value in the Provider and Role fields.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
> +  - Issue when theme unpacking required write permission to the /tmp folder is now resolved and the write permission is no longer required.
```suggestion
  - The issue encountered with theme unpacking requiring write permission to the /tmp folder is now resolved. Write permission is no longer required.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
> +Up until now the portal didn't support SQL as a storage for the portal’s assets: OAS files, themes, images, etc. Therefore, customers had to use at least two types of storage:
```suggestion
Until recently, SQL storage was not supported for the portal’s assets: OAS files, themes, images, etc. Therefore, customers had to use at least two types of storage:
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
> +- SQL for the portal’s metadata (users, products, access requests, etc);
```suggestion
- SQL for the portal’s metadata (users, products, access requests, etc).
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
> +With this new feature, customers can simply use the same SQL database (MySQL, MariaDB, PostgreSQL) for both assets and metadata. To use the [`db` storage type]({{<ref "/content/tyk-stack/tyk-develope
```suggestion
With this new feature, customers can simply use the same SQL database (MySQL, MariaDB, PostgreSQL) for both assets and metadata. To use the `db` [storage type]({{<ref "/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md#portal_storage">}}) just set the `PORTAL_STORAGE=db` for environment variables or `"Storage": "db"` in a config file and you are good to go!
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
> +## Response status code filters in the API analytics for developers
```suggestion
## Response status code added to API analytics filters
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
> +API Consumers now can filter API analytics by response status codes. This allows them to analyze traffic and error rate for specific response code for their API Products.
```suggestion
API Consumers now can filter API analytics by response status codes. This allows them to analyse traffic and error rate for specific response code for their API Products.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
> +We introduced display-only support for basic APIs. That means API Providers can publish documentation for the basic auth APIs but developers cannot use the portal to get access to the basic auth APIs
```suggestion
We introduced display-only support for basic APIs. That means API Providers can publish documentation for the basic auth APIs. However, developers cannot use the portal to get access to the basic auth APIs.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
> +  - ZipSlip vulnerability is now resolved.
Add link to CVE (https://nvd.nist.gov/vuln/detail/CVE-2023-27475) and include in security fixes section of changelog.

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +We added new **API Analytics UI** for developers which extends self-service capabilities for developers with an ability to analyze performance of the APIs which they consume as we well as traffic com
```suggestion
We added the new **API Analytics UI** which extends self-service capabilities for developers. This provides developers with an ability to analyse performance of the APIs which they consume, in addition to traffic composition for their apps. 
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +The **API Analytics UI** has four tabs that help developers to navigate between different analytical views available for them:
```suggestion
The **API Analytics UI** has four tabs that help developers to navigate different analytical views:
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- **The overview tab** provides overarching view on the API Products consumed by a developer. This tab has all information that’s need to quickly digest the current state of API Products, including t
```suggestion
- **The overview tab** provides an overarching view on the API Products consumed by a developer. This tab has all information needed to quickly digest the current state of API Products, including: total traffic, number of errors, error breakdown by response code and top APIs by error code.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- **The Total API Calls tab** enables developers to analyze traffic from their application to the APIs they consume and how it’s changing over time;
```suggestion
- **The Total API Calls** tab enables developers to analyse traffic from their application to the APIs they consume and how it’s changing over time.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- **The Errors tab** makes the information about total errors and error rate available for developers. Here developers can identify any issue with the APIs which they consume without filling any supp
```suggestion
- **The Errors** tab provides developers with information relating to total errors and error rates. Here developers can identify any issues with the APIs which they consume without filling any support tickets. Developers can switch between the total number of error and error rates.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- Create new themes;
```suggestion
- Create new themes.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- Update existing themes;
```suggestion
- Update existing themes.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +## Better error logging for the DCR and SSO flows
```suggestion
## Enhanced error logging for DCR and SSO flows
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +We introduced more verbose error logging for the DCR flow and for Single Sign-On to help customers set up the SSO and DCR faster. This is especially important for complex environments with highly cus
```suggestion
We introduced more verbose error logging for the DCR flow and for Single Sign-On to help customers set up the SSO and DCR faster. This is especially important for complex environments with highly customised or non-standard IdPs.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- Added API Consumer Analytics to digest summary analytics for developers' applications so that developers can analyze performance of the APIs which they consume.
```suggestion
- Added API Consumer Analytics to digest summary analytics for developers' applications so that developers can analyse performance of the APIs which they consume.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- Added better error logging in all places where the DCR flow is used and provides a log structure including status code from an IdP to help API Providers to debug DCR integrations.
```suggestion
- Added enhanced error logging in all places where the DCR flow is used. A log structure is now provided, including the status code from an IdP to help API Providers to debug DCR integrations.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- Added better error logging to the SSO flow which makes setting up SSO much easier task.
```suggestion
- Added enhanced error logging to the SSO flow to facilitate setting up SSO.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- Fixed grammar in the Provider menu Ui.
```suggestion
- Fixed grammar in the Provider menu UI.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- Fixed the link to the Access requests menu item in the portal admin dashboard.
```suggestion
- Fixed broken link to the Access requests menu item in the portal admin dashboard.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +  - Add form validation in the checkout flow;
```suggestion
  - Add form validation in the checkout flow.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +  - Fixes the 'Add to cart' button in the API Product page;
Expand slightly to explain what was the issue with the Add cart button

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +  - Add form validation in the checkout flow;
```suggestion
  - Add form validation in the checkout flow.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
> +- Fixes to the shopping cart flow:
```suggestion
- Fixes to the shopping cart flow were made as follows:
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Add API specs to APIs.
```suggestion
- Add link to Open API specification for APIs.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Fixed grammar in the copy in the admin application on the Application page.
```suggestion
- Fixed grammar in the copy section of the admin application on the Application page.
```

2023-10-26 13:08 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Fixed a bug issue with the bootstrap process to print _JWT_ instead of the portal’s internal auth token when bootstrapping the portal.
```suggestion
- Fixed a bug with the bootstrap process to print _JWT_ instead of the portal’s internal auth token when bootstrapping the portal.
```

2023-10-26 15:15 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.7.0.md
> +- Fixed the bug where developers and apps of an organization were not deleted when the organization was deleted.
This is duplicated suggestion. The fix is already applied.

2023-10-26 15:17 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +Now the Tyk Enterprise Developer portal can use multiple identity providers (IdPs) for OAuth2.0 via the Dynamic Client Registration flow. If your company has multiple oAuth2.0 providers now you can u
Fixed.

2023-10-26 15:18 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +## Display-only support for API Products with the custom authentication
This is a duplicated suggestion. The fix is already applied.

2023-10-26 15:19 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +You can download all CMS content with just one API call with the brand new API endpoint GET /pages/all/content-blocks that returns all content blocks for all pages. Now migration between environments
This is a duplicated suggestion. The fix is already applied.

2023-10-26 15:19 UTC, slega commented on tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/release-notes/portal-1.7.0.md
> +- Fixed the bug where developers and apps of an organization were not deleted when the organization was deleted.
This is duplicated suggestion. The fix is already applied.

2023-11-02 12:00 UTC, dcs3spp approved these changes

2023-11-02 12:04 UTC, merged

2023-11-02 12:04 UTC, dcs3spp commented
/release to release-5.2

2023-11-17 15:01 UTC, dcs3spp commented
/release to release-5.1