Tyk Charts release notes
TykTechnologies/tyk-docs-hugo pull request #3413
Opened 2023-10-20 16:45 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-23 04:02 UTC, komalsukhani commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `insecureSkipVerify` option for the `tyk-k8s-bootstrap`
I think we have `sslInsecureSkipVerify` as listed below and not `insecureSkipVerify` for bootstrap

2023-10-23 04:02 UTC, komalsukhani commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed default value of `storage.s3.endpoint` and `storage.s3.bucket`
I am not sure about this change if we did that. 
@andrei-tyk Do you remember?

2023-10-23 17:29 UTC, dcs3spp requested changes
Hi Carol, many thanks for submitting the helm release notes for review. Overall, I think the PR provides good detail and overview for all the charts. I have made some suggestions:

- Consistent capitalisation of Pump, Gateway and Dashboard.
- For change-log items where applicable add links to internal/external docs and ensure that benefit of additions/changes/fixes are explained to the user.
- For global secret change log items across charts ensure the README link is in all
- See further specific comments in change-log items

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +##### Security enhancements
```suggestion
##### Security Enhancements
```

Update other headings to use sentence case for consistency

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +This version introduces a few security enhancements. It adds configuration options to configure SSL in dashboard, and support of `insecureSkipVerify` option for all charts to bypass verification for
Add links to the docs to these new features

```suggestion
This version introduces a few security enhancements. It adds configuration options to configure SSL in dashboard and support of `insecureSkipVerify` option for all charts to bypass verification for self-signed certificates. For security best practices, we now support use of secret to pass sensitive fields including admin credentials, license keys, database connection string and remote control plane connection details via secrets.
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +This version enhances Gateway charts by introducing more parameters, like `containerPort`, `enalyticsEnabled`, `analyticsConfigType`, `hashkeyFunction` for Gateway.
Add links to the docs for these new parameters

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +##### Added
Is there links available that we can add for the change-log items?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
```suggestion
- Added support for `containerSecurityContext` configuration. This is required as *K8s* and *OpenShift* versions require some of these values to be set.
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `.global.mongo.driver` to configure which Mongo Driver to use.
What are the available options, can we link to docs if available? Or alternatively add here if not available?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed use the resources specified in values.yaml
What was the issue and how was it fixed? How did the fix benefit the user?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +##### Added
In the changelog items in this component and the remaining components below: add links to corresponding documentation (internal/documentation) where available and ensure that each changelog item includes an explanation of how it benefits the user

Ensure all change log items consistently end with .

Ensure Gateway and Pump are consistently capitalised in the release note

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
Maybe add external link to relevant documentation here?

```suggestion
- Added support for `containerSecurityContext` configuration. This is required as *K8s* and *OpenShift* versions require some of these values to be set.
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added `insecureSkipVerify` option for gateway under `gateway.tls` section.
Add further explanation of what this does and why the user might need it

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Removed setting of obsolete environment variable TYK_GW_OPTIMISATIONSUSEASYNCSESSIONWRITE
Is this deprecated and will it be a breaking change?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added `Horizontal Pod Autoscaler` specs for gateway deployments, allowing users to easily enable automatic scaling by CPU utilisation, memory utilisation, or custom metrics.
```suggestion
- Added `Horizontal Pod Autoscaler` specs for gateway deployments, allowing users to easily enable automatic scaling by CPU utilisation, memory utilisation or custom metrics.
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.- Added `containerPort` parameter for gateway to al
```suggestion
- Added support for `containerSecurityContext` configuration. This is required as K8s and OpenShift versions require some of these values to be set.- Added `containerPort` parameter for gateway to allow for different values to be set for port and targetPort
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
```suggestion
- Added support for `containerSecurityContext` configuration. This is required as K8s and OpenShift versions require some of these values to be set.
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed duplicate setting of `TYK_DB_ENABLEAGGREGATELOOKUPS` environment variabe.
Add explanation of the issue, i.e. what in what way was the environment variable setting duplicated? What does the behaviour of the fix now enable for the user?

```suggestion
- Fixed duplicate setting of `TYK_DB_ENABLEAGGREGATELOOKUPS` environment variable.
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed value of TYK_DB_TYKAPI_HOST environment variable
Add explanation of the issue, i.e. in what way was value faulty? What does the behaviour of the fix now enable for the user?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed gateway port name in dashboard deployment
Add explanation of the issue, in what way was the port name faulty? What does the behaviour of the fix now enable for the user?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Make tyk-bootstrap image repository information configurable
What is the attribute that needs to be configured to allow this? Can we link to any docs anywhere?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `kind` for portal. User can choose to deploy Tyk developer portal as StatefulSet or Deployment. Default as StatefulSet.
```suggestion
- Added parameter `kind` for portal. User can choose to deploy Tyk Developer Portal as StatefulSet or Deployment. Default as StatefulSet.
```

Capitalise remaining instances below for Tyk Developer Portal

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `extraVolume` and `extraVolumeMount`.
How does this benefit users? What is the use case?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for setting Portal licence and storage connection string via `global.secrets.useSecretName`
Is it possible to set both the license and storage connection string with this config value?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
```suggestion
- Added support for `containerSecurityContext` configuration. This is required as K8s and OpenShift versions require some of these values to be set.
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for Portal storage type `db` in `storage.type`.
Can we link to docs here? What are the existing storage type settings other than database? What type of information is stored in the database?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed environment variable setting for s3 storage
What environment variable was faulty and what issue was this causing for users? How does the fix now help users?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `.global.mongo.driver` to configure which Mongo Driver to use.
Maybe link to docs for supported driver settings?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `kind` for portal. User can choose to deploy Tyk developer portal as StatefulSet or Deployment. Default as StatefulSet.
Can we link to docs here if available? If not add a brief explanation of what StatefulSet and Deployment do.

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added `global.remoteControlPlane.useSecretName` parameter to allows user to pass control plane connection details via Kubernetes secrets. For detail uses of secrets, see [README](https://github.com
```suggestion
- Added `global.remoteControlPlane.useSecretName` parameter to allow users to pass control plane connection details via Kubernetes secrets. For further details regarding uses of secrets, see [README](https://github.com/TykTechnologies/tyk-charts/blob/main/tyk-stack/README.md)
```

Add README link to other change-log items above that use `global.secrets.useSecretName`.

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added `global.remoteControlPlane.useSecretName` parameter to allows user to pass control plane connection details via Kubernetes secrets. For detail uses of secrets, see [README](https://github.com
```suggestion
- Added `global.remoteControlPlane.useSecretName` parameter to allow users to pass control plane connection details via Kubernetes secrets. For detail uses of secrets, see [README](https://github.com/TykTechnologies/tyk-charts/blob/main/tyk-stack/README.md)
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
```suggestion
- Added support for `containerSecurityContext` configuration. This is required as K8s and OpenShift versions require some of these values to be set.
```

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for Portal storage type `db` in `storage.type`.
Same as previously commented, what are the other values for `storage.type` other than database storage? What information is stored in the database? Are there any docs that we can link to?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Changed default storageType to `postgres`
What was previous default storage type and how does this change benefit users? Did the majority of users request the change?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Changed default pump backend to `prometheus` and `global.StorageType`
What was previous default storage type and how does this change benefit users? Did the majority of users request the change?

2023-10-23 17:29 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed default value of `storage.s3.endpoint` and `storage.s3.bucket`
What was the previous default values for `storage.s3.endpoint` and `storage.s3.bucket` that was causing an issue for users? What are the new default values and how does this help users?

2023-10-24 11:26 UTC, letzya commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
good place to add an external link

2023-10-24 13:11 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +##### Security enhancements
Suggestion committed

2023-10-24 13:11 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.- Added `containerPort` parameter for gateway to al
Suggestion committed

2023-10-24 13:12 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
Suggestion committed

2023-10-24 13:13 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added `global.remoteControlPlane.useSecretName` parameter to allows user to pass control plane connection details via Kubernetes secrets. For detail uses of secrets, see [README](https://github.com
Suggestion committed

2023-10-24 22:52 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +This version introduces a few security enhancements. It adds configuration options to configure SSL in dashboard, and support of `insecureSkipVerify` option for all charts to bypass verification for
Updated

2023-10-24 22:56 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +This version enhances Gateway charts by introducing more parameters, like `containerPort`, `enalyticsEnabled`, `analyticsConfigType`, `hashkeyFunction` for Gateway.
Updated

2023-10-24 23:04 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `.global.mongo.driver` to configure which Mongo Driver to use.
Updated

2023-10-24 23:05 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
Updated

2023-10-24 23:09 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed use the resources specified in values.yaml
Updated

2023-10-24 23:14 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +##### Added
Updated

2023-10-24 23:16 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added `insecureSkipVerify` option for gateway under `gateway.tls` section.
Updated

2023-10-24 23:19 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
Updated

2023-10-24 23:20 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Removed setting of obsolete environment variable TYK_GW_OPTIMISATIONSUSEASYNCSESSIONWRITE
This environment variable is not used by Tyk anymore so we do not need to set it.

2023-10-24 23:21 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added `Horizontal Pod Autoscaler` specs for gateway deployments, allowing users to easily enable automatic scaling by CPU utilisation, memory utilisation, or custom metrics.
Updated

2023-10-24 23:22 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
Updated

2023-10-24 23:22 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed duplicate setting of `TYK_DB_ENABLEAGGREGATELOOKUPS` environment variabe.
Fixed

2023-10-24 23:29 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed value of TYK_DB_TYKAPI_HOST environment variable
Updated

2023-10-24 23:34 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed gateway port name in dashboard deployment
Updated

2023-10-24 23:35 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `insecureSkipVerify` option for the `tyk-k8s-bootstrap`
This line is removed

2023-10-24 23:38 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Make tyk-bootstrap image repository information configurable
Updated

2023-10-24 23:39 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `kind` for portal. User can choose to deploy Tyk developer portal as StatefulSet or Deployment. Default as StatefulSet.
Updated

2023-10-24 23:40 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `extraVolume` and `extraVolumeMount`.
Updated

2023-10-24 23:41 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for setting Portal licence and storage connection string via `global.secrets.useSecretName`
yes. User just need to set one secret. Added link to docs on how to configure the secret for different credential or secret values.

2023-10-24 23:43 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
Updated

2023-10-25 00:04 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed environment variable setting for s3 storage
Updated

2023-10-25 00:04 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for Portal storage type `db` in `storage.type`.
Updated

2023-10-25 00:05 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `.global.mongo.driver` to configure which Mongo Driver to use.
Updated

2023-10-25 00:07 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `kind` for portal. User can choose to deploy Tyk developer portal as StatefulSet or Deployment. Default as StatefulSet.
Updated

2023-10-25 00:08 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
Updated

2023-10-25 00:08 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for Portal storage type `db` in `storage.type`.
Updated

2023-10-25 00:09 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Changed default storageType to `postgres`
It was mongo previously. The commercial team has decided to recommend Postgres as default over MongoDB.

2023-10-25 00:25 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Changed default pump backend to `prometheus` and `global.StorageType`
Updated

2023-10-25 00:25 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Changed default storageType to `postgres`
Updated

2023-10-25 00:32 UTC, carolwkc commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed default value of `storage.s3.endpoint` and `storage.s3.bucket`
Removed. Found that this change was not from v1 release.

2023-10-25 00:32 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed default value of `storage.s3.endpoint` and `storage.s3.bucket`
This line is not required now.

2023-10-26 08:54 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added `Horizontal Pod Autoscaler` specs for gateway deployments, allowing users to easily enable automatic scaling by CPU utilisation, memory utilisation or custom metrics.
```suggestion
- Added `Horizontal Pod Autoscaler` specs for Gateway deployments, allowing users to easily enable automatic scaling by CPU utilisation, memory utilisation or custom metrics.
```

2023-10-26 08:55 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added `Horizontal Pod Autoscaler` specs for gateway deployments, allowing users to easily enable automatic scaling by CPU utilisation, memory utilisation or custom metrics.
```suggestion
- Added `Horizontal Pod Autoscaler` specs for Gateway deployments, allowing users to easily enable automatic scaling by CPU utilisation, memory utilisation or custom metrics.
```

2023-10-26 09:01 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added support for `containerSecurityContext` configuration. This is required as k8s and openshift versions require some of these values to be set.
Should we also add the OpenShift link? https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/authentication_and_authorization/managing-pod-security-policies

2023-10-26 09:09 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Fixed gateway port name in dashboard deployment
Hi Carol, has this item now been removed from the change-log?

- Fixed gateway port name in dashboard deployment

2023-10-26 09:27 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Removed setting of obsolete environment variable TYK_GW_OPTIMISATIONSUSEASYNCSESSIONWRITE
Ok thanks Carol, anything such as that we can mention in deprecated changes section 

https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Deprecations

2023-10-26 09:34 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `.global.mongo.driver` to configure which Mongo Driver to use.
```suggestion
- Added parameter `.global.mongo.driver` to configure which [Mongo Driver]({{< ref "/tyk-dashboard/configuration#mongo_driver" >}}) to use.
```

2023-10-26 09:42 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +- Added parameter `.global.mongo.driver` to configure which [Mongo Driver]({{< ref "/tyk-dashboard/configuration#mongo_driver" >}}) to use.
```suggestion
- Added parameter `.global.mongo.driver` to configure which [Mongo Driver](https://tyk.io/docs/tyk-dashboard/configuration/#mongo_driver) to use.
```

2023-10-26 09:50 UTC, dcs3spp reviewed
Hi @caroltyk Carol many thanks for updating PR with those changes. I think we are almost there with this

- README links broken? Is the README available yet or will that be added on GHub when this Change-Log is added also?

- Should we also add _OpenShift_ links for security Context? (https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/authentication_and_authorization/managing-pod-security-policies). Currently K8s link has been added

There is a deprecated changes section that we should maybe use to mention the removal
 of obsolete environment variable TYK_GW_OPTIMISATIONSUSEASYNCSESSIONWRITE. This is the link from the template.
 
https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Deprecations

 Has this been removed? - Fixed gateway port name in dashboard deployment
 
 I have noticed there are 2 links use a BASE URL of https://tyk.io/docs/nightly. Can they be replaced to use base url https://tyk.io/docs?

2023-10-26 10:14 UTC, carolwkc commented
> Hi @caroltyk Carol many thanks for updating PR with those changes. I think we are almost there with this
> 
> * README links broken? Is the README available   yet or will that be added on GHub when this Change-Log is added also?

The README links is not yet available until we merge the changes to main branch. It will be added when this release notes is published.

> * Should we also add _OpenShift_ links for security Context? (https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/authentication_and_authorization/managing-pod-security-policies). Currently K8s   link has been added


Thanks. Updated.

> 
> There is a deprecated changes section that we should maybe use to mention the removal  of obsolete environment variable TYK_GW_OPTIMISATIONSUSEASYNCSESSIONWRITE. This is the link from the template.   https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Deprecations


TYK_GW_OPTIMISATIONSUSEASYNCSESSIONWRITE has been deprecated for a long time and is not initiated by the release, so I think we do not need to add it here.

> 
>  Has this been removed? - Fixed gateway port name in dashboard deployment    I have noticed there are 2 links use a BASE URL of https://tyk.io/docs/nightly. Can they be replaced to use base url https://tyk.io/docs?


Thanks. Updated.

2023-10-26 10:46 UTC, dcs3spp approved these changes
yessssss, many thanks @caroltyk. PR looks good to me

2023-10-26 15:41 UTC, letzya commented
@dcs3spp @caroltyk  in the template we also have **Dependencies**  section. JUst a reminder in case we updated a dependency

2023-10-26 15:43 UTC, letzya commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +## tyk-pump-1.1.0
@caroltyk @dcs3spp silly question - why do we have the titles with hyphens? in the GW we have a properly capitalised title https://github.com/TykTechnologies/tyk/releases/tag/v5.2.1

2023-10-26 15:44 UTC, dcs3spp commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +## tyk-pump-1.1.0
@letzya @caroltyk I think these are the chart names, yes?

2023-10-26 15:46 UTC, dcs3spp commented
> @dcs3spp @caroltyk in the template we also have **Dependencies** section. JUst a reminder in case we updated a dependency

@caroltyk were there dependency updates?

2023-10-26 15:48 UTC, letzya commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +## tyk-pump-1.1.0
In the release page in tyk-charts, this is the title `Tyk Chart v1.0.0`
It looks clearer as follows
## Tyk Pump v1.1.0

2023-10-26 16:46 UTC, dcs3spp commented
@caroltyk Before update the RNon GHub remember to include Open Source ([Mozilla Public License](https://github.com/TykTechnologies/tyk/blob/master/LICENSE.md)) statement below each release note header 

An example is on the [release notes guidelines](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Title%3A-Tyk-%3C%3Cproduct-name%3E%3E-X.Y-Release-Notes) and [Tyk Gateway release notes ](https://tyk.io/docs/product-stack/tyk-gateway/release-notes/version-5.2/)

2023-10-26 23:16 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-charts-release-notes.md
> +## tyk-pump-1.1.0
These are chart names.

For helm chart, I see the usual customs is to have the chart name followed by versions. The top helm chart projects (https://github.com/topics/helm-charts) follow this patterns: "kube-prometheus-stack-52.1.0", "argo-rollouts-2.32.1", "airflow-8.8.0"

Non-helm chart projects are more varied (https://github.com/topics/cncf): "Kubernetes v1.25.15" "v1.8.0" "Fluentd 1.1.0"

2023-10-26 23:17 UTC, caroltyk commented
> > @dcs3spp @caroltyk in the template we also have **Dependencies** section. JUst a reminder in case we updated a dependency
> 
> @caroltyk were there dependency updates?

No there is no change in dependency

2023-10-26 23:20 UTC, caroltyk commented
> @caroltyk Before update the RNon GHub remember to include Open Source ([Mozilla Public License](https://github.com/TykTechnologies/tyk/blob/master/LICENSE.md)) statement below each release note header
> 
> An example is on the [release notes guidelines](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Title%3A-Tyk-%3C%3Cproduct-name%3E%3E-X.Y-Release-Notes) and [Tyk Gateway release notes ](https://tyk.io/docs/product-stack/tyk-gateway/release-notes/version-5.2/)

👌 updated

2023-10-27 07:43 UTC, komalsukhani approved these changes

2023-10-27 08:10 UTC, dcs3spp commented
> https://deploy-preview-3413--tyk-docs.netlify.app/docs/nightly/developer-support/tyk-charts-release-notes

Approved

@caroltyk do you want me to close the PR or shall we wait until day of release?

2023-10-27 13:20 UTC, caroltyk commented
Thanks a lot @dcs3spp . I have copied content to GH and saved as draft. This PR can be closed.

2023-10-27 14:47 UTC, dcs3spp commented
Thans @caroltyk 👌 closing the PR

2023-10-27 14:47 UTC, closed without merging