[TT-10301] Added explanation of allow-unsafe-oas
TykTechnologies/tyk-docs-hugo pull request #3418
Opened 2023-10-23 16:00 UTC by andyo-tyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-24 08:27 UTC, andyo-tyk commented on tyk-docs/content/tyk-sync.md
> +- Support for importing, converting and publishing Swagger/OpenAPI JSON files (OpenAPI 2.0 and 3.0 are supported) to Tyk Classic APIs.
```suggestion
- Support for importing, converting and publishing Swagger/OpenAPI JSON files as Tyk Classic APIs (OpenAPI 2.0 and 3.0 are supported).
```

2023-10-24 10:50 UTC, dcs3spp requested changes
Hi Andy, PR looks good to me. Made minor suggestion of adding links to config doc for allow-unsafe-oas option

2023-10-24 10:50 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> +In Tyk Dashboard 5.2.2 we added a new configuration option `allow_unsafe_oas` which permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. In Tyk Sync 1.4.1 we added a new flag `
Add link to docs for configuration of allow_unsafe_oas

2023-10-24 11:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-sync.md
> +In Tyk Dashboard 5.2.2 we added a new configuration option `allow_unsafe_oas` which permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. In Tyk Sync 1.4.1 we added a new flag `
It will need to link to here /tyk-dashboard/configuration#allow_unsafe_oas (though that won't exist until 5.2.2 docs are published)

```suggestion
In Tyk Dashboard 5.2.2 we added a new [configuration option]({{< ref "tyk-dashboard/configuration#allow_unsafe_oas" >}}) `allow_unsafe_oas` which permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. In Tyk Sync 1.4.1 we added a new flag `--allow-unsafe-oas` to work with a Dashboard configured with this option enabled. This is not recommended action due to the risk of inconsistent behaviour and potential for breaking changes while Tyk OAS is in Early Access, but is provided for early adopters and will be deprecated later.
```

2023-10-24 13:17 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> +In Tyk Dashboard 5.2.2 we added a new configuration option `allow_unsafe_oas` which permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. In Tyk Sync 1.4.1 we added a new flag `
Can a PR be raised to provide the docs for 5.2.2?

2023-10-24 13:17 UTC, dcs3spp reviewed
Can a PR be raised to add the docs for 5.2.2 so that the link to. the config docs for allow-unsafe-oas is available?

2023-10-24 15:05 UTC, andyo-tyk commented
> Can a PR be raised to add the docs for 5.2.2 so that the link to. the config docs for allow-unsafe-oas is available?

It will be, of course, per standard process.

2023-10-25 07:23 UTC, andyo-tyk commented on tyk-docs/content/tyk-sync.md
> +In Tyk Dashboard 5.2.2 we added a new configuration option `allow_unsafe_oas` which permits the modification of Tyk OAS APIs via the Tyk Classic API endpoints. In Tyk Sync 1.4.1 we added a new flag `
Also 5.0.7. Jira tickets raised (TT-10347, TT-10348)

2023-10-25 08:37 UTC, furkansenharputlu approved these changes
LGTM

2023-10-25 08:44 UTC, tbuchaillot approved these changes

2023-10-31 09:49 UTC, dcs3spp approved these changes

2023-10-31 09:54 UTC, dcs3spp approved these changes

2023-10-31 09:55 UTC, merged

2023-10-31 09:55 UTC, dcs3spp commented
/release to release-5.2

2023-10-31 10:07 UTC, dcs3spp commented
/release to release-5