Improve Tyk Classic Dev Portal landing page
TykTechnologies/tyk-docs-hugo pull request #3419
Opened 2023-10-23 16:56 UTC by andyo-tyk

Improved consistency of naming
Improved sign-posting to Enterprise Developer Portal

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description
Improved consistency of naming
Improved sign-posting to Enterprise Developer Portal
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-23 17:05 UTC, andyo-tyk commented on tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
> +The Tyk Classic Developer Portal is available to Pro (On-Premises), Cloud Classic and Multi-Cloud users.
```suggestion
The Tyk Classic Developer Portal is available to Tyk Self-Managed and Tyk Cloud users.
```

2023-10-24 10:46 UTC, dcs3spp requested changes
PR looks good to me Andy. Have made some minor suggestion and then can merge and release

2023-10-24 10:46 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
> -The Tyk Classic Developer Portal is less feature-rich than the Tyk Enterprise developer portal. It doesn't provide audience management, full UI customisation including custom JS insertion and custom
```suggestion
The Tyk Classic Developer Portal is less feature-rich than the Tyk Enterprise Developer Portal. It doesn't provide audience management, full UI customisation including custom JS insertion and custom page templates, forums and blog features, grouping APIs into API Product and other enterprise-grade features. Still, it is perfectly suitable for primary use cases.
```

2023-10-24 10:46 UTC, dcs3spp commented on tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
> +The Tyk Classic Developer Portal is suitable for primary use cases, however if you want a more feature-rich experience then you should consider the [Tyk Enterprise Developer Portal]({{< ref "tyk-deve
```suggestion
The Tyk Classic Developer Portal is suitable for primary use cases, however if you want a more feature-rich experience then you should consider the [Tyk Enterprise Developer Portal]({{< ref "tyk-developer-portal/tyk-enterprise-developer-portal" >}}). This provides audience management, full UI customisation including custom JS insertion and custom page templates, forums and blog features, grouping APIs into API Products and other enterprise-grade features.
```

2023-10-24 11:11 UTC, andyo-tyk commented on tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
> -The Tyk Classic Developer Portal is less feature-rich than the Tyk Enterprise developer portal. It doesn't provide audience management, full UI customisation including custom JS insertion and custom
I was sure that I had capitalised Developer Portal - so agree with that one, however API Products should be plural here, so I'll modify and commit the suggestion.

2023-10-24 12:07 UTC, andyo-tyk commented on tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
> +The Tyk Classic Developer Portal is suitable for primary use cases, however if you want a more feature-rich experience then you should consider the [Tyk Enterprise Developer Portal]({{< ref "tyk-deve
I think this comma is necessary because "other enterprise-grade features" is not related to "grouping APIs", so prefer to leave it in. This PR is only intended as a quick clean up re: terminology - one day it probably needs a re-write but not today IMHO.

2023-10-24 12:08 UTC, andyo-tyk commented on tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
> -The Tyk Classic Developer Portal is less feature-rich than the Tyk Enterprise developer portal. It doesn't provide audience management, full UI customisation including custom JS insertion and custom
This appears to be a suggestion on the original text which I've replaced, so will close this one.

2023-10-24 14:54 UTC, dcs3spp approved these changes
lgtm

2023-10-24 15:11 UTC, merged

2023-10-24 15:11 UTC, dcs3spp commented
/release to release-5.2

2023-10-24 15:12 UTC, dcs3spp commented
/release to release-5