Adding header_matches example for advanced url rewrites.
TykTechnologies/tyk-docs-hugo pull request #3420
Opened 2023-10-23 17:41 UTC by JRWu

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link
When deploying docs locally, the changes can be viewed here:
[http://localhost:1313/docs/nightly/transform-traffic/url-rewriting/#header-match-example](http://localhost:1313/docs/nightly/transform-traffic/url-rewriting/#header-match-example)

### Description
Adding advanced url rewrite example for header_matches, showcasing the notation required to reference the matched header.

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2023-10-23 18:54 UTC, Firaasss approved these changes

2023-10-24 09:02 UTC, dcs3spp requested changes
Hi Jia, PR looks good. Made minor suggestion.

2023-10-24 09:02 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +You can route inbound API requests to Tyk to various based on the presence and content of a header. Suppose you have a header in the format of `store-id:1234`. Depending on the value of store-id you
_You can route inbound API requests to Tyk to various ? based on the presence and content of a header. Suppose you have a header in the format of `store-id:1234`. Depending on the value of store-id you might wish to change the target URL._

Routing to various upstream endpoints?

2023-10-30 14:43 UTC, JRWu commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +You can route inbound API requests to Tyk to various based on the presence and content of a header. Suppose you have a header in the format of `store-id:1234`. Depending on the value of store-id you
Great catch, have updated the verbiage to "... to various upstream hosts or endpoints based on the presence ..."

2023-10-31 10:43 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +i.e. For example, if you have the following curl request:
```suggestion
For example, if you have the following curl request:
```

2023-10-31 10:49 UTC, dcs3spp approved these changes

2023-10-31 10:50 UTC, merged

2023-10-31 10:50 UTC, dcs3spp commented
/release to release-5.2

2023-10-31 10:53 UTC, dcs3spp commented
/release to release-5