Patch Dev Support Release Summary With Link To Helm Charts
TykTechnologies/tyk-docs-hugo pull request #3422
Opened 2023-10-24 08:09 UTC by dcs3spp

Patch Dev Support Release Summary With Link To Helm Charts

2023-10-24 22:33 UTC, caroltyk requested changes
Thank you @dcs3spp , just correcting the hyperlink

2023-10-24 22:33 UTC, caroltyk commented on tyk-docs/content/developer-support/tyk-release-summary/overview.md
> +Release notes for our helm charts can be found at our [GitHub repository](https://github.com/TykTechnologies/tyk-charts/releases.)
Extra dot in the link
```suggestion
Release notes for our helm charts can be found at our [GitHub repository](https://github.com/TykTechnologies/tyk-charts/releases)
```

2023-10-26 08:35 UTC, dcs3spp commented
> Thank you @dcs3spp , just correcting the hyperlink

Many thanks @caroltyk, have requested re-review

2023-10-26 14:15 UTC, caroltyk approved these changes

2023-10-26 14:35 UTC, merged

2023-10-26 14:35 UTC, dcs3spp commented
/release to release-5.2

2023-10-26 14:41 UTC, dcs3spp commented
/release to release-5