Update tyk-sync.md
TykTechnologies/tyk-docs-hugo pull request #3423
Opened 2023-10-24 12:17 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

1. Rewrite feature list as tables to make it easier to compare difference between Tyk OSS and Tyk Dashboard
2. Provide guidelines and examples on which command to use for each feature
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-24 15:07 UTC, dcs3spp requested changes
Many thanks for submitting PR Carol. I have reviewed and suggested minor changes. Once updated and peer review has nee done we can merge into parent branch.

Can you update the PR title to include the Jira ticket [TT-10301]

2023-10-24 15:07 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync works with Git and any CI/CD tool to ensure that only versioned changes are loaded into your Tyk Environment.  After an API developer has configured and tested the APIs locally, he can use "
What is meant by version the final API configurations?

```suggestion
Tyk Sync works with Git and any CI/CD tool to ensure that only versioned changes are loaded into your Tyk Environment.  After an API developer has configured and tested the APIs locally, he can use "tyk-sync dump" to convert the APIs to transportable format. Following GitOps standard practises, the API developer should create a Pull-Request on Git for a peer review and version the final API configurations. To sync configurations from Git to a target Tyk installation, use *tyk-sync sync*, *tyk-sync publish* or *tyk-sync update* in the deployment pipeline.
```

2023-10-24 15:07 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> -- Update APIs and Policies on remote Tyk Dashboards
Add or remove . to/from all bullet points for consistency

2023-10-24 15:07 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> -- Synchronise a Tyk Dashboard's APIs and Policies with your VCS (one-way, definitions are written to the Dashboard)
```suggestion
- Synchronise Tyk Dashboard's APIs and Policies with your VCS (one-way, definitions are written to the Dashboard)
```

2023-10-24 15:07 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> -- Synchronise a Tyk Community Edition Gateway APIs with those stored in a VCS (one-way, definitions are written to the Gateway)
```suggestion
- Synchronise Tyk Community Edition Gateway APIs with those stored in a VCS (one-way, definitions are written to the Gateway)
```

2023-10-24 15:07 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> +| Feature                                                                    | Tyk OSS | Tyk Dashboard | Example |
Maybe add an introduction section that explains what this table shows

2023-10-24 15:07 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> -- Support for Tyk Classic and Tyk OAS APIs (see note)
```suggestion
- Support for Tyk Classic and Tyk OAS APIs (see note below)
```

2023-10-24 22:22 UTC, caroltyk commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync works with Git and any CI/CD tool to ensure that only versioned changes are loaded into your Tyk Environment.  After an API developer has configured and tested the APIs locally, he can use "
Thanks, the suggestion is applied. Versioning: I meant version control it in Git. Rewritten for better clarity.

2023-10-24 22:23 UTC, caroltyk commented on tyk-docs/content/tyk-sync.md
> -- Update APIs and Policies on remote Tyk Dashboards
These lines are removed.

2023-10-24 22:23 UTC, caroltyk commented on tyk-docs/content/tyk-sync.md
> -- Synchronise a Tyk Dashboard's APIs and Policies with your VCS (one-way, definitions are written to the Dashboard)
This line is removed

2023-10-24 22:23 UTC, caroltyk commented on tyk-docs/content/tyk-sync.md
> -- Synchronise a Tyk Community Edition Gateway APIs with those stored in a VCS (one-way, definitions are written to the Gateway)
This line is removed

2023-10-24 22:24 UTC, caroltyk commented on tyk-docs/content/tyk-sync.md
> +| Feature                                                                    | Tyk OSS | Tyk Dashboard | Example |
Added: "Tyk Sync works with the Open Source *Tyk Gateway* and *Tyk Dashboard* installation. The table below shows features available for each installation type."

2023-10-24 22:24 UTC, caroltyk commented on tyk-docs/content/tyk-sync.md
> -- Support for Tyk Classic and Tyk OAS APIs (see note)
Updated in table

2023-10-25 08:00 UTC, tbuchaillot approved these changes

2023-10-26 08:20 UTC, dcs3spp approved these changes

2023-10-26 08:39 UTC, merged

2023-11-27 16:56 UTC, dcs3spp commented
/release to release-5.1