Update tyk-helm-tyk-stack.md
TykTechnologies/tyk-docs-hugo pull request #3441
Opened 2023-10-25 23:42 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

Update docs for new Tyk Charts release:
1. Setting up Gateway HPA
2. Setting up secrets for secret fields
3. Setting up Enterprise Portal
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-10-26 08:11 UTC, dcs3spp requested changes
Thanks for submitting PR Carol. PR looks good to me. I've made some minor suggestions. When done and a peer review is completed we can merge.

2023-10-26 08:11 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +If Tyk Dashboard bootstrapping is enabled, Tyk Dashboard admin will be bootstrapped according to `global.adminUser` field.
Wen bootstrapped does it mean that it will use the privileges/permissions associated with the Dashboard admin user?

```suggestion
If Tyk Dashboard bootstrapping is enabled, Tyk Dashboard admin will be bootstrapped according to the `global.adminUser` field.
```

2023-10-26 08:11 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +[`APISecret`](https://tyk.io/docs/tyk-oss-gateway/configuration/#secret) field configures a header value used in every
```suggestion
The [`APISecret`](https://tyk.io/docs/tyk-oss-gateway/configuration/#secret) field configures a header value used in every
interaction with Tyk Gateway API.
```

2023-10-26 08:11 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Enterprise Portal supports different storage options for the portal's CMS assets. Please see the [Enterprise Portal Storage settings] page for all the available options. Most of them can be setup in
Add reference link to enterprise portal storage settings page

2023-10-26 08:11 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +For other [Enterprise Portal configurations]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration">}}), it can be set by using environment v
```suggestions

Other [Enterprise Portal configurations]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration">}}) can be set by using environment variables with `extraEnvs` fields, e.g.:
```

2023-10-26 08:21 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +If Tyk Dashboard bootstrapping is enabled, Tyk Dashboard admin will be bootstrapped according to `global.adminUser` field.
It means we'll create the admin user in Database with the given user details

2023-10-26 08:21 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +If Tyk Dashboard bootstrapping is enabled, Tyk Dashboard admin will be bootstrapped according to `global.adminUser` field.
```suggestion
If Tyk Dashboard bootstrapping is enabled, Tyk Dashboard admin user will be created according to the `global.adminUser` field.
```

2023-10-26 08:25 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Enterprise Portal supports different storage options for the portal's CMS assets. Please see the [Enterprise Portal Storage settings] page for all the available options. Most of them can be setup in
```suggestion
Enterprise Portal supports different storage options for the portal's CMS assets. Please see the [Enterprise Portal Storage settings]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration/#portal-settings">}}) page for all the available options. Most of them can be setup in corresponding `storage` section:
```

2023-10-26 08:25 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +For other [Enterprise Portal configurations]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration">}}), it can be set by using environment v
```suggestion
Other [Enterprise Portal configurations]({{<ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration">}}) can be set by using environment variables with `extraEnvs` fields, e.g.:
```

2023-10-26 09:13 UTC, andrei-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +- Tyk Enterprise Portal, a full-fledged CMS-like system for API providers to publish, monetise and drive the adoption of APIs.
Shouldn't we have Developer portal here?

2023-10-26 09:14 UTC, andrei-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal License
Shouldn't we have Developer portal here?

2023-10-26 09:14 UTC, andrei-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal Admin Password
Shouldn't we have Developer portal here?

2023-10-26 09:14 UTC, andrei-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal Storage Connection String
Shouldn't we have Developer portal here?

2023-10-26 09:14 UTC, andrei-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +### Tyk Enterprise Portal Configurations
Shouldn't we have Developer portal here?

2023-10-27 07:04 UTC, slega requested changes

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +- Tyk Enterprise Portal, a full-fledged CMS-like system for API providers to publish, monetise and drive the adoption of APIs.
It should be Tyk Developer Enterprise Portal

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal License
It should be Tyk Developer Enterprise Portal

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +In order to refer Tyk Enterprise Portal license through Kubernetes secret, please use `global.secrets.useSecretName`,
It should be Tyk Developer Enterprise Portal

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +In order to refer Tyk Enterprise Portal's admin password through Kubernetes secret,
Ditto

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal Admin Password
Tyk Developer Enterprise Portal

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal Storage Connection String
Tyk Developer Enterprise Portal

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +### Tyk Enterprise Portal Configurations
It should be Tyk Developer Enterprise Portal

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal License (Required)
It should be Tyk Developer Enterprise Portal

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +To enable Enterprise Portal, set `global.components.devPortal` to true, and configure below inside `tyk-dev-portal` section.
It should be Tyk Developer Enterprise Portal

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Enterprise Portal License is required. It can be set up in `tyk-dev-portal.license` or through secret `global.secrets.useSecretName`. The secret should contain a key called DeveloperPortalLicense.
Tyk Developer Enterprise Portal

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Enterprise Portal supports different storage options for the portal's CMS assets. Please see the [Enterprise Portal Storage settings]({{<ref "tyk-stack/tyk-developer-portal/enterprise-developer-porta
We need to make it more verbose. Not every user or customer knows that are CMS assets:

Tyk Enterprise Portal supports different storage options for storing the portal's CMS assets such as images, theme files and Open API Specification files.

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Enterprise Portal supports different storage options for the portal's CMS assets. Please see the [Enterprise Portal Storage settings]({{<ref "tyk-stack/tyk-developer-portal/enterprise-developer-porta
What does it mean "Most of them"? Specifically, which options can and cannot be configured?

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +    # Supported types: fs, s3, db
All types of storage are mutually exclusive. In other words, only one of them can be used at time. The below explanation makes it confusing to a user: it looks like I have to setup all of them. Moreover, if a user will copy that configuration, it guaranteed that the portal won't start.

Therefore:
- Please split this into three sections explaining each option separately: `fs`, `db` and `persistence`
- Also, please provide explanation about what each of the options means to the end-user:
 - `fs`: the portal's assets will be stored on the filesystem, therefore a persistent volume claim will be created.
 - `s3`: the portal's assets will be stored in a S3 volume.
 - `db`: the portal's assets will be stored in the main portal's database.

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +      retryDelay: 5000
The database connection settings are not related to the storage configuration. A user has to specify connection setting to their database regardless which storage type is selected. Why are they in this section?

2023-10-27 07:04 UTC, slega commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +    database:
Where is the `db` storage type?

2023-10-27 14:32 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +- Tyk Enterprise Portal, a full-fledged CMS-like system for API providers to publish, monetise and drive the adoption of APIs.
```suggestion
- Tyk Developer Enterprise Portal, a full-fledged CMS-like system for API providers to publish, monetise and drive the adoption of APIs.
```

2023-10-27 14:32 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +|Tyk Enterprise Portal| false| global.components.devPortal |
```suggestion
| Tyk Developer Enterprise Portal | false| global.components.devPortal | 
```

2023-10-27 14:33 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal License
```suggestion
#### Tyk Developer Enterprise Portal License
```

2023-10-27 14:33 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +In order to refer Tyk Enterprise Portal license through Kubernetes secret, please use `global.secrets.useSecretName`,
```suggestion
In order to refer Tyk Developer Enterprise Portal license through Kubernetes secret, please use `global.secrets.useSecretName`, 
```

2023-10-27 14:33 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal Admin Password
```suggestion
#### Tyk Developer Enterprise Portal Admin Password
```

2023-10-27 14:34 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +In order to refer Tyk Enterprise Portal's admin password through Kubernetes secret,
```suggestion
In order to refer Tyk Developer Enterprise Portal's admin password through Kubernetes secret, 
```

2023-10-27 14:34 UTC, carolwkc commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal Storage Connection String
```suggestion
#### Tyk Developer Enterprise Portal Storage Connection String
```

2023-10-27 14:34 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +### Tyk Enterprise Portal Configurations
```suggestion
### Tyk Developer Enterprise Portal Configurations
```

2023-10-27 14:34 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +To enable Enterprise Portal, set `global.components.devPortal` to true, and configure below inside `tyk-dev-portal` section.
```suggestion
To enable Tyk Developer Enterprise Portal, set `global.components.devPortal` to true, and configure below inside `tyk-dev-portal` section.
```

2023-10-27 14:34 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +#### Enterprise Portal License (Required)
```suggestion
#### Tyk Developer Enterprise Portal License (Required)
```

2023-10-27 14:35 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Enterprise Portal License is required. It can be set up in `tyk-dev-portal.license` or through secret `global.secrets.useSecretName`. The secret should contain a key called DeveloperPortalLicense.
```suggestion
Tyk Developer Enterprise Portal License is required. It can be set up in `tyk-dev-portal.license` or through secret `global.secrets.useSecretName`. The secret should contain a key called DeveloperPortalLicense.
```

2023-10-27 14:36 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Enterprise Portal supports different storage options for the portal's CMS assets. Please see the [Enterprise Portal Storage settings]({{<ref "tyk-stack/tyk-developer-portal/enterprise-developer-porta
```suggestion
Tyk Enterprise Portal supports different storage options for storing the portal's CMS assets such as images, theme files and Open API Specification files. Please see the [Enterprise Portal Storage settings]({{<ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration#portal-settings">}}) page for all the available options. Helm chart supports the setting of following fields in values.yaml `storage` section:
```

2023-10-30 23:15 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +    # Supported types: fs, s3, db
updated

2023-10-30 23:15 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +      retryDelay: 5000
@andrei-tyk

2023-10-30 23:17 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +    database:
database. it corresponds to portal storage config:

PORTAL_STORAGE

Config file: Storage
Type: string
Options:

fs to use file system storage type;
db to use the portal’s main database. If the db is selected as a storage type, the portal application will create appropriate structure in the database that
s3 to use S3 volume for storing the portal assets.
Description: Defines which type of storage to use for the portal’s CMS assets. Not required. If it is not specified, the default value is fs.

2023-11-01 09:05 UTC, andrei-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +- Tyk Dashboard, a license based component that provides GUI management interface and analytics platform for Tyk.
Since GUI = graphical user interface , GUI management interface sounds redundant.

2023-11-01 09:07 UTC, andrei-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +interaction with Tyk Gateway API.
duplicated row

2023-11-01 09:24 UTC, andrei-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +You can enable autoscaling of gateway by `--set tyk-gateway.gateway.autoscaling.enabled=true`. By default, it will enable `Horizontal Pod Autoscaler` resource with target average CPU utilisation at 6
"of the gateway" is correct

2023-11-01 09:29 UTC, andrei-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +      retryDelay: 5000
This is an oversight by me which was probably ported from the old version of the helmcharts. Thank you for the explanation @slega. We should create a ticket to update this @caroltyk

2023-11-01 09:50 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +- Tyk Dashboard, a license based component that provides GUI management interface and analytics platform for Tyk.
updated

2023-11-01 09:54 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +interaction with Tyk Gateway API.
oops thanks for spotting

2023-11-01 09:54 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +You can enable autoscaling of gateway by `--set tyk-gateway.gateway.autoscaling.enabled=true`. By default, it will enable `Horizontal Pod Autoscaler` resource with target average CPU utilisation at 6
updated

2023-11-02 09:55 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +      retryDelay: 5000
this will be fixed in next release

2023-11-02 10:43 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +If you use filesystem as storage, please set `tyk-dev-portal.storage.type` to `fs`, and configure `tyk-dev-portal.storage.persistence` to mount an existing persistent volume to Tyk Enterprise Develop
```suggestion
If you use the file system as storage, please set `tyk-dev-portal.storage.type` to `fs`, and configure `tyk-dev-portal.storage.persistence` to mount an existing persistent volume to Tyk Enterprise Developer Portal.
```

2023-11-02 10:46 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +- Tyk Dashboard, a license based component that provides graphical management interface and analytics platform for Tyk.
```suggestion
Tyk Dashboard, a license based component that provides a graphical management interface and analytics platform for Tyk.
```

2023-11-02 10:48 UTC, dcs3spp approved these changes

2023-11-02 11:25 UTC, merged

2023-11-02 11:25 UTC, dcs3spp commented
/release to release-5.2