Add the session management and audit log settings for the EDP.
TykTechnologies/tyk-docs-hugo pull request #3502
Opened 2023-11-02 20:14 UTC by slega

### For internal users - Please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/DX-783

---

### Preview Link

<br>

### Description
Add documentations for the following config options:
- PORTAL_THEMING_DISABLE_UPLOAD
- PORTAL_MAX_UPLOAD_SIZE
- PORTAL_DCR_LOG_ENABLED
- PORTAL_AUDIT_LOG_ENABLE
- PORTAL_AUDIT_LOG_PATH
- PORTAL_SESSION_NAME
- PORTAL_SESSION_SECURE
- PORTAL_SESSION_HTTPONLY
- PORTAL_SESSION_KEY
- PORTAL_SESSION_LIFETIME
- PORTAL_TLS_ENABLE
- PORTAL_TLS_CERTIFICATES
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2023-11-03 17:33 UTC, JRWu requested changes
Looks great, just requesting a couple minor changes

2023-11-03 17:33 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +*Config file:** Session.LifeTime <br/>
Minor formatting suggestion- I believe this is a typo, should be two stars  i.e. **Config file:** in order to render properly

2023-11-03 17:33 UTC, JRWu commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +#### PORTAL_TLS_CERTIFICATES
Should we also include what format of cert file the certificate must be in as well just so prospects don't get confused? I know the dashboard has a section in the documentation ([linked here](https://tyk.io/docs/basic-config-and-security/security/tls-and-ssl/#using-tyk-certificate-storage)) that illustrates what formatting must be applied to the certificates.

2023-11-07 10:03 UTC, dcs3spp requested changes
Hi @slega,

Many thanks for submitting the PR with updated config settings.

PR looks good to me with some minor suggestions. Once suggestions have been committed and peer review comment addressed then we can merge and release.

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +Raw responses from the Identity Providers may contain sensitive information therefore we recommend enabling this option only for debugging purposes. Available options are:
```suggestion
Raw responses from the Identity Providers may contain sensitive information, therefore we recommend enabling this option only for debugging purposes. Available options are:
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +This section explains how to configure the audit log in the portal. When the audit log enabled, each admins' action will leave a trace in the portal.log file located at in the directory specified by
```suggestion
This section explains how to configure the audit log in the portal. When the audit log is enabled, each admins' action will leave a trace in the *portal.log* file located at in the directory specified by the `PORTAL_AUDIT_LOG_ENABLE` setting.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +This section explains how to configure the session management settings in the portal. Using the below setting, you can configure:
```suggestion
This section explains how to configure session management for the portal. Using the settings below, you can configure:
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +- The name of the portal's session cookie;
```suggestion
- Name of the portal's session cookie.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +- The cookie encryption key;
```suggestion
- Cookie encryption key.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +- Various aspects of cookie security such as should it be sent only over a TLS-encrypted connection and is accessible by Javascript API on the client-side;
```suggestion
- Various aspects of cookie security, including: should it be sent using an TLS-encrypted connection and is it accessible by Javascript API on the client-side?
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +**Description**: Sets the `HttpOnly` attribute on the portal's cookie which controls is the portal's cookie is only accessible by the server and not by javascript on the client side.
```suggestion
**Description**: Sets the `HttpOnly` attribute on the portal's cookie which controls if the cookie is only accessible at the server and not by Javascript on the client side.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +**Description**: The lifetime of the portal's cookie in seconds. the default value is 3600 seconds.
```suggestion
**Description**: The lifetime of the portal's cookie in seconds. The default value is 3600 seconds.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +**Description**: Enables TLS. The default value is false.
```suggestion
**Description**: Enables TLS. The default value is `false`.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +This section provides a reference for the TLS configuration settings to enable connection to the portal's UI over https.
```suggestion
This section explains the TLS configuration settings to enable connection to the portal's UI over HTTPS.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +**Description**: Enables or disables connection over https. When TLS is enabled, the portal will expect a TLS certificate to be provided via PORTAL_TLS_CERTIFICATES.
```suggestion
**Description**: Enables or disables connection over https. When TLS is enabled, the portal will expect a TLS certificate to be provided via *PORTAL_TLS_CERTIFICATES*.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +When TLS is enabled and no certificates provided, the portal won't start. The default value is `false`.
```suggestion
When TLS is enabled and no certificates are provided, the portal won't start. The default value is `false`.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +**Description**: A json-formatted string that provides hostname and paths to a cert and a key file. To work correctly, the portal need the following properties in the config string:
```suggestion
**Description**: A JSON formatted string that provides the hostname , in addition to the paths to a TLS certificate and key file:
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +- `Name`: a hostname of the portal, should match with the hostname of the certificate file.
Do we need specify Common Name(CN) / Subject Alternative Name (SAN) in certificate for matching hostname?

- `Name`: The hostname of the portal. This should match with the Common Name (CN) or Subject Alternative Name (SAN) specified in the certificate file.

```suggestion
- `Name`: The hostname of the portal. This should match with the hostname of the certificate file.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +- `CertFile`: a path to a TLS certificate file for the specified hostname.
```suggestion
- `CertFile`: The path to a TLS certificate file for the specified hostname.
```

2023-11-07 10:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +- `KeyFile`: a path to a TlS key file for the specified hostname.
```suggestion
- `KeyFile`: The path to a TLS key file for the specified hostname.
```

2023-11-07 20:53 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
> +#### PORTAL_TLS_CERTIFICATES
@JRWu the documentation you've provided is for Mutual TLS for upstream / downstream. The documentation for the dashboard doesn't specify the format: https://tyk.io/docs/basic-config-and-security/security/tls-and-ssl/. But I've added the format (.crt) for the certificates.

2023-11-08 15:30 UTC, JRWu approved these changes
LGTM!

2023-11-08 15:33 UTC, dcs3spp approved these changes
Hi Sergei, PR looks good to me

2023-11-08 15:35 UTC, merged

2023-11-08 15:35 UTC, dcs3spp commented
/release to release-5.2