[DX-772] Tyk DX OWASP
TykTechnologies/tyk-docs-hugo pull request #3506
Opened 2023-11-03 18:01 UTC by dcs3spp

[DX-772](https://tyktech.atlassian.net/browse/DX-772) Update Tyk DX OWASP content

2023-11-10 12:51 UTC, dcs3spp commented
Hi @davegarvey When you get chance would you be able to review?

2023-11-10 16:16 UTC, davegarvey reviewed
I've submitted comments on the document @dcs3spp

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +The Open Web Application Security Project (OWASP) provides a top ten threat awareness document compiled by security experts. For more details on the OWASP project visit [https://www.owasp.org](https:
The link here is to the final part of the series. Perhaps it would be better to link to the introductory post instead - https://tyk.io/blog/res-owasp-api-security-intro/

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +Tyk supports managing BOLA by implementing object-level authorization through the following mechanisms:
These points are fine, but the best BOLA solution is for the API to handle the object authorisation itself. I think this is important enough to include here, so that the reader understands how relevant it is. The other points are more useful in supporting the API-driven authz approach. They also tend to be more relevant to function or property-level authorisation instead of object-level.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 3 - Excessive data exposure
Is this PR meant to be aligning the content with OWASP 2023? If so, no.3 should be connected to 'property level authz', as per https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa3-broken-object-property-level-authorization.md

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 3 - Excessive data exposure
The new content is aligned, but the heading is using the older terminology

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 6 - Mass Assignment
Mass assignment is now more aligned with the new no.3, BOLPA. The new no.6, like no.1, now requires an API-driven solution, as APIM can only have a limited impact. The problems originate from client behavior in the context of the system behind the API, so it's difficult to mitigate in a generic fashion. I think the best an APIM system can do is ensure that the client is authenticated, so that the API can then perform any additional contextual checks.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 6 - Mass Assignment
I'm beginning to think that this is a larger job than this PR. It needs further thought to structure it correctly and make the right points. The research team have an item in the backlog to perform this work.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +The Open Web Application Security Project (OWASP) provides a top ten threat awareness document compiled by security experts. For more details on the OWASP project visit [https://www.owasp.org](https:
The link is still going to part 10 of the series. As per the previous comment, I would change to go to the introduction instead.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +Rest APIs provide endpoints that return all properties of an object in the reponse, some of which could contain sensitive data. Conversely, GraphQL APIs requests allow the clients to specificy which
Change "Rest" to "REST"

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +Rest APIs provide endpoints that return all properties of an object in the reponse, some of which could contain sensitive data. Conversely, GraphQL APIs requests allow the clients to specificy which
Change "GraphQL APIs requests" to "GraphQL API requests"

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +Rest APIs provide endpoints that return all properties of an object in the reponse, some of which could contain sensitive data. Conversely, GraphQL APIs requests allow the clients to specificy which
"specificy" > "specify"

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +Rest APIs provide endpoints that return all properties of an object in the reponse, some of which could contain sensitive data. Conversely, GraphQL APIs requests allow the clients to specificy which
Not sure I agree with
> Subsequently, these require greater effort from the attacker to discover

As GraphQL APIs come with introspection endpoints which typically document how to interact with the API, including all the types and fields, making it easy to understand which objects and properties are available. Though these endpoints can be disabled to prevent such discovery.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Circuit breaker]({{< ref "advanced-configuration/transform-traffic/endpoint-designer#circuit-breaker" >}})
It could be useful to add context for each of these points, to be clear how their help mitigate the issue.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +For Denial of Service (DoS) attacks it’s recommended to use 3rd party services which are built to handle such threats.
I would put emphasis on the reason for this, as the goal should be to prevent the requests from reaching your infrastructure, so it's no good trying to resolve with APIM. It needs a specialist solution.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- *Access Control*: Tyk has plugins that control access to API endpoints. They are known as [whitelist]({{< ref "advanced-configuration/transform-traffic/endpoint-designer#whitelist" >}}) and [blackl
Aren't "whitelist" and "blacklist" called "allowlist" and "blocklist" now?

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +On the premise that these business flows are application specific, the API owner is responsible for addressing the security issues posed by this threat. However, the Gateway can be used to validate p
Re "validate payloads", strictly speaking, the bulleted items are a mixture of validation and transformation, rather than just validation.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +This is application specific and is largely the responsibility of the API. However, Tyk Gateway can assist with this form of attack through [JSON schema validation]({{< ref "advanced-configuration/tr
remove extra `)`

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Policy Path-Based Permissions]({{< ref "security/security-policies/secure-apis-method-path" >}}) and the [Whitelist]({{< ref "advanced-configuration/transform-traffic/endpoint-designer#whitelist"
Check terminology - "whitelist" > "allowlist"

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Manipulate]({{< ref "advanced-configuration/transform-traffic/response-headers" >}}) response headers to remove or modify API sensitive information..
I think it's better to include the feature term in the link, rather than just the generic word "manipulate" i.e. start the sentence "Use [response header manipulation] to..."

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Manipulate]({{< ref "advanced-configuration/transform-traffic/response-body" >}}) the response body to remove or modify parts containing sensitive information.
Same as previous comment.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Mutual TLS]({{< ref "basic-config-and-security/security/mutual-tls" >}}) with both the clients and API to ensure that callers with explicitly whitelisted client certificates can connect to the end
I think we should find a better term than "whitelist", it's now common to avoid using this terminology if possible.

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Sunsetting]({{< ref "getting-started/key-concepts/versioning#sunsetting-api-versions" >}}) allows versions to be configured with an Expiry Time, ensuring that a version is sunset.
I would be clear about what "sunset" means. Rather than ending "is sunset", I would put "is not accessible after the expiry date".

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Key expiry]({{< ref "basic-config-and-security/control-limit-traffic/key-expiry" >}}) ensures that access to an API is short lived, with a per key configurable Time to Live.
As previous comment, I think this one could be better explained. What is "time to live"? What is the benefit of using it?

2023-11-10 16:16 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +In addition a good best practice is to consider any definition of done to include corresponding documentation updates.
"a good best practice" doesn't sound right. I would replace with "it is best practice", or something similar.

2023-11-10 17:07 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +The Open Web Application Security Project (OWASP) provides a top ten threat awareness document compiled by security experts. For more details on the OWASP project visit [https://www.owasp.org](https:
Thanks Dave, I've updated link

2023-11-10 17:08 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +Tyk supports managing BOLA by implementing object-level authorization through the following mechanisms:
Thanks Dave, have updated BOLA to highlight that it is reposnbility of API owner

2023-11-10 17:09 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 3 - Excessive data exposure
Thanks Dave, heading updated to _Broken Object Property Level Authorisation (BOPLA)_

2023-11-10 17:27 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 6 - Mass Assignment
Thanks Dave, heading updated to _Unrestricted Access To Sensitive Business Flows_

- Added explanation that application specification
- Have updated content here to recommend authorising endpoints. Also recommended pentesting.

2023-11-10 17:34 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +Rest APIs provide endpoints that return all properties of an object in the reponse, some of which could contain sensitive data. Conversely, GraphQL APIs requests allow the clients to specificy which
Thanks Dave, I have removed the statement:

> Subsequently, these require greater effort from the attacker to discover

2023-11-10 17:39 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +For Denial of Service (DoS) attacks it’s recommended to use 3rd party services which are built to handle such threats.
Thanks Dave, I have updated:

> For Denial of Service (DoS) attacks it is recommended to use specialist 3rd party services to prevent DoS attacks from reaching your infrastructure.

2023-11-10 17:51 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- *Access Control*: Tyk has plugins that control access to API endpoints. They are known as [whitelist]({{< ref "advanced-configuration/transform-traffic/endpoint-designer#whitelist" >}}) and [blackl
Thanks Dave, Yep 👍 found [here](https://github.com/OWASP/CheatSheetSeries/issues/556)

I have replaced whitelist & blacklist with allowlist & blocklist

2023-11-10 17:53 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +On the premise that these business flows are application specific, the API owner is responsible for addressing the security issues posed by this threat. However, the Gateway can be used to validate p
Thanks Dave, I have updated to:

> These business flows are application specific, being unique to the API's backend systems. Subsequently, the API owner is responsible for addressing the security issues posed by this threat. Furthermore, to discover points of exploitation and test IT security breaches, pentesting is recommended.

2023-11-10 17:57 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +This is application specific and is largely the responsibility of the API. However, Tyk Gateway can assist with this form of attack through [JSON schema validation]({{< ref "advanced-configuration/tr
Thanks Dave, I've removed extra )

2023-11-10 17:58 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Policy Path-Based Permissions]({{< ref "security/security-policies/secure-apis-method-path" >}}) and the [Whitelist]({{< ref "advanced-configuration/transform-traffic/endpoint-designer#whitelist"
Thanks Dave, I have updated

2023-11-10 18:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Manipulate]({{< ref "advanced-configuration/transform-traffic/response-headers" >}}) response headers to remove or modify API sensitive information..
Thanks Dave, I have updated.

2023-11-10 18:00 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Manipulate]({{< ref "advanced-configuration/transform-traffic/response-body" >}}) the response body to remove or modify parts containing sensitive information.
Thanks Dave, I have updated.

2023-11-10 18:03 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Mutual TLS]({{< ref "basic-config-and-security/security/mutual-tls" >}}) with both the clients and API to ensure that callers with explicitly whitelisted client certificates can connect to the end
Thanks Dave, I have replaced _whitelisted_ with _allowed_

2023-11-10 18:05 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +In addition a good best practice is to consider any definition of done to include corresponding documentation updates.
Thanks Dave, I have updated to:

> In addition, it is best practice to consider any definition of done to include corresponding documentation updates.

2023-11-13 09:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Sunsetting]({{< ref "getting-started/key-concepts/versioning#sunsetting-api-versions" >}}) allows versions to be configured with an Expiry Time, ensuring that a version is sunset.
Thanks Dave I have updated as follows:

> - [Sunsetting]({{< ref "getting-started/key-concepts/versioning#sunsetting-api-versions" >}}) allows versions to be configured with an Expiry Time, ensuring that a version is not accessible after the expiry date.

2023-11-13 09:57 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +- [Key expiry]({{< ref "basic-config-and-security/control-limit-traffic/key-expiry" >}}) ensures that access to an API is short lived, with a per key configurable Time to Live.
Thanks Dave, I have updated as follows:

> - [Key expiry]({{< ref "basic-config-and-security/control-limit-traffic/key-expiry" >}}) ensures that access to an API is short lived, with a per key configurable Time to Live (TTL) for which a token remains valid before it expires. The implementation of key expiry, with a configurable Time To Live (TTL), mitigates the impact of compromised tokens by narrowing the window of vulnerability. Setting a TTL reduces the time frame during which a compromised token could be exploited, enhancing overall security.

2023-11-16 11:28 UTC, davegarvey requested changes
Have left some comments

2023-11-16 11:28 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 2 - Broken User Authentication
This item should now be titled "Broken Authentication", as per https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa2-broken-authentication.md.
I would also review the usage of the term "user" in the body, and remove where it's inappropriately used, now that the section title is different.

2023-11-16 11:28 UTC, davegarvey commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 4 - Lack of resources & rate limiting
Should be titled "Unrestricted Resource Consumption", as per https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa4-unrestricted-resource-consumption.md

2023-11-16 17:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 2 - Broken User Authentication
Thanks Dave, I have updated the section title and removed the term "user" from the body.

2023-11-16 17:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
> +## 4 - Lack of resources & rate limiting
Thanks Dave I have updated the section title to "Unrestricted Resource Consumption"

2023-11-17 07:55 UTC, davegarvey approved these changes

2023-11-17 09:12 UTC, dcs3spp commented
Thanks for approving @davegarvey, I'll merge and release

2023-11-17 09:26 UTC, merged

2023-11-17 09:26 UTC, dcs3spp commented
/release to release-5.2

2023-11-17 09:35 UTC, dcs3spp commented
/release to release-5.1

2023-11-17 09:44 UTC, dcs3spp commented
/release to release-5