Update menu.yaml
TykTechnologies/tyk-docs-hugo pull request #3514
Opened 2023-11-07 20:51 UTC by letzya

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-11-08 12:30 UTC, dcs3spp requested changes
Thanks Yaara, the PR looks good to me. I have made minor suggestions and then think it is ready:

- Add SOAP and REST to tags
- Update yml to json in code block

Should the SOAP use case menu item appear after the other menu items in this section?

2023-11-08 12:30 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
> +Tag: ["body transform", "Header transform", "Response transform", "Request transform" ]
```suggestion
Tag: ["body transform", "Header transform", "Response transform", "Request transform", "SOAP", "REST" ]
```

2023-11-08 12:30 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
> +```yaml
```suggestion
```json
```

2023-11-08 12:34 UTC, letzya commented on tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
> +Tag: ["body transform", "Header transform", "Response transform", "Request transform" ]
I wonder if adding rest helps here. if you search "rest" in the docs, not sure this page should be connected to these results - what do you think?

2023-11-08 12:36 UTC, letzya commented on tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
> +```yaml
This was done on purpose. If I put json, the rendered page will show an error (since this one has a template which is not valid in json)

2023-11-08 12:37 UTC, letzya commented on tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
> +Tag: ["body transform", "Header transform", "Response transform", "Request transform" ]
```suggestion
Tag: ["body transform", "Header transform", "Response transform", "Request transform", "SOAP" ]
```

2023-11-08 12:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
> +```yaml
:ok:

2023-11-08 12:41 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
> +Tag: ["body transform", "Header transform", "Response transform", "Request transform" ]
For the purpose of SEO, yep could be useful :ok:

2023-11-08 12:43 UTC, dcs3spp approved these changes
Yaara PR looks good to me

2023-11-10 12:13 UTC, letzya commented on tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
> +Tag: ["body transform", "Header transform", "Response transform", "Request transform" ]
The term Rest is too generic (try to search it in the docs and you’ll see you get completely unrelated pages. many pages related to REST so it will just confuse Hugo.

2023-11-10 12:15 UTC, merged

2023-11-10 12:15 UTC, dcs3spp commented
/release to release-5.2

2023-11-15 09:30 UTC, dcs3spp commented
/release to release-5.1