[Dx-746] Add Tyk Plugin examples resources
TykTechnologies/tyk-docs-hugo pull request #3522
Opened 2023-11-08 17:09 UTC by dcs3spp

[DX-746](https://tyktech.atlassian.net/browse/DX-746)

2023-11-15 18:48 UTC, JRWu requested changes
Reads great, just requesting a couple minor changes and comments

2023-11-15 18:48 UTC, JRWu commented on tyk-docs/content/plugins/marketplace.md
> +## Blogs
There are a couple more you could add to the list here:
https://tyk.io/blog/how-to-configure-a-grpc-server-using-tyk/
https://tyk.io/blog/how-to-deploy-python-plugins-in-tyk-running-on-kubernetes/

Or we could potentially list the blog url with the plugin search here:
https://tyk.io/?s=plugin

2023-11-15 18:48 UTC, JRWu commented on tyk-docs/content/plugins/marketplace.md
> +Welcome to the Tyk Plugins Marketplace, dedicated to providing you with a curated list of resources that showcase how to develop Tyk Plugins.
Is marketplace the proper terminology here? Perhaps I'm being pedantic but other vendors associate marketplace with a page where you can pick and choose different plugins as opposed to a set of urls

2023-11-15 18:48 UTC, JRWu commented on tyk-docs/content/plugins/marketplace.md
> +- **Description**: Provides a docker-compose environment for developing your own custom plugins.
Perhaps we need to be more explicit and state that this is only for development of custom Go plugins

2023-11-16 16:11 UTC, dcs3spp commented on tyk-docs/content/plugins/marketplace.md
> +Welcome to the Tyk Plugins Marketplace, dedicated to providing you with a curated list of resources that showcase how to develop Tyk Plugins.
How about Tyk Plugins Hub?

2023-11-16 17:02 UTC, dcs3spp commented on tyk-docs/content/plugins/marketplace.md
> +## Blogs
Nice!!! Thanks @JRWu for including the other blogs content and search URL. I have added both resources and linked to the plugin search also.

2023-11-17 18:27 UTC, JRWu commented on tyk-docs/content/plugins/marketplace.md
> +## Blogs
Awesome, thank you

2023-11-17 18:28 UTC, JRWu commented on tyk-docs/content/plugins/marketplace.md
> +Welcome to the Tyk Plugins Marketplace, dedicated to providing you with a curated list of resources that showcase how to develop Tyk Plugins.
Love it

2023-11-17 18:30 UTC, JRWu requested changes
Just two more minor changes requested please

2023-11-17 18:30 UTC, JRWu commented on tyk-docs/content/plugins/plugin-hub.md
> +[Tyk Plugins]({{< ref "plugins" >}}) is a valuable asset in the Tyk API Platform. Plugins enable you to develop custom middleware for intercepted upstream API requests and responses. The resources in
I would say "are a valuable asset to ..." in the first sentence

And then ultimately rename Marketplace to Plugin Hub in this sntence

2023-11-20 09:32 UTC, dcs3spp commented on tyk-docs/content/plugins/plugin-hub.md
> +[Tyk Plugins]({{< ref "plugins" >}}) is a valuable asset in the Tyk API Platform. Plugins enable you to develop custom middleware for intercepted upstream API requests and responses. The resources in
Thanks @JRWu I have made the requested changes

2023-11-20 13:40 UTC, JRWu approved these changes
LGTM!

2023-11-20 15:22 UTC, merged

2023-11-20 15:22 UTC, dcs3spp commented
/release to release-5.2

2023-11-20 15:23 UTC, dcs3spp commented
/release to release-5.1