Add OAS for the EDP
TykTechnologies/tyk-docs-hugo pull request #3523
Opened 2023-11-08 20:32 UTC by slega

### For internal users - Please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/DX-790
[<br>]
---

### Preview Link

<br>

### Description
Add OAS for the EDP
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2023-11-09 12:01 UTC, dcs3spp requested changes
Many thanks for submitting the OAS API for Enterprise Developer Portal. I have had a look through the OAS specification and made some minor suggestions.

In the specification:
- Replace UID instances with UUID
- Replace oAuth2.0 instances with OAuth 2.0

There are some endpoints that return 422 status code to signify not found or bad request. Should those endpoints have an additional status code for 404 for not found. Then 422 is for unproccessable entity/bad request only?

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    The Tyk Enterprise Developer Portal Management API offers programmatic access to all portal resources that your instance of the portal manages. This API  repeats functionality of the user interfa
Remove additional space 

```suggestion
    The Tyk Enterprise Developer Portal Management API offers programmatic access to all portal resources that your instance of the portal manages. This API repeats functionality of the user interface and enables APIs consumers integrating their portal instances with their other IT systems such as billings, CRMs, ITSM systems and other software.
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    This API uses admin authorization token that is available for admin users of the portal in the profile page.
```suggestion
    This API requires an admin authorisation token that is available for admin users of the portal in the profile page.
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    This is the alpha version of OpenAPI Specification for the portal. Please take note that's a subject to change at any time up until it's released publicly.
```suggestion
    This is the alpha version of OpenAPI Specification for the portal. Please take note that it is subject to change at any time up until it is released publicly.
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +  version: "v1.8.0"
For OAS spec alpha version, should the version be v1.8.0-alpha.1 ?

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    description: "Developer applications and API credential for develoeprs"
```suggestion
    description: "Developer applications and API credential for developers"
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    description: "extend already existing models (User) by adding custom attributes"
```suggestion
    description: "Extend already existing models (User) by adding custom attributes"
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: This endpoint deletes an access request. If an access request is approved, its credentials will be revoked and removed from a gateway or an Identity provider
Consistent sentence casing

```suggestion
      description: This endpoint deletes an access request. If an access request is approved, its credentials will be revoked and removed from a gateway or an identity provider
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: This endpoint trigger approval of an access request. A call to this API will trigger creation of credentials in a gateway or an Identity Provider
```suggestion
      description: This endpoint triggers approval of an access request. A call to this API will trigger creation of credentials in a gateway or an Identity Provider
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: List all developer application
```suggestion
      description: List all developer applications
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Delete an application. The application, all its access requests, and credentials will be removed. Also, it will trigger removal of all credentials that belong to this application f
```suggestion
      description: Delete an application. The application, all it's access requests and credentials will be removed. Also, it will trigger removal of all credentials that belong to this application from a gateway and/or Identity Provider
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: This endpoint updates an application's data such as its name, description, redirect URI, and the user to whom this application belongs
```suggestion
      description: This endpoint updates an application's data such as its name, description, redirect URI and the user to whom this application belongs
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        - description: UID of this application
```suggestion
        - description: UUID of this application
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        description: ""
Should the description be empty?

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        - description: UID of this application
```suggestion
        - description: UUID of this application
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: This endpoint deletes an access request. If this access request was approved and has any credenitals attached to it then all of them will be removed and revoked in a gateway on an
("Identity Provider" & Gateway) or "identity provider"

```suggestion
      description: This endpoint deletes an access request. If this access request was approved and has any credenitals attached to it then all of them will be removed and revoked in a gateway on an identity provider
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        - description: UID of this application
Replace further occurrences of UID with UUID

```suggestion
        - description: UUID of this application
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: This endpoint deletes a credentials and removes an API key from the gateway or an oAuth2.0 client from the IdP
```suggestion
      description: This endpoint deletes credentials for an access request and removes an API key from the gateway or an OAuth2.0 client from the IdP
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Not found of bad request
```suggestion
          description: Not found or bad request
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: List all audience for this catalogue
```suggestion
      description: List all audiences for this catalogue
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      summary: List all audience for this catalogue
```suggestion
      summary: List all audiences for this catalogue
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Please note that this endpoint deletes an organisation but not its developers. When an organization is deleted, all users are moved to the Default organization. To completely erase
```suggestion
      description: Please note that this endpoint deletes an organisation but not its developers. When an organisation is deleted, all users are moved to the Default Organisation. To completely erase an organisation and all its users, delete the users first
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: This endpoint deletes a team from an organisation. Please note that developers that belong to that team won't be removed. Instead, they will moved to the default team of that organ
```suggestion
      description: This endpoint deletes a team from an organisation. Please note that developers that belong to that team won't be removed. Instead, they will moved to the default team of that organisation
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Update a team for an organisation by add or remove users, or changing the name of the team
```suggestion
      description: Update a team for an organisation by adding or removing users, or changing the name of the team
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Update a page including title. path, and status
```suggestion
      description: Update a page including title, path, and status
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Create a new content block for on page
```suggestion
      description: Create a new content block for a page
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      summary: Create a new content block for on page
```suggestion
      summary: Create a new content block for a page
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Delete a content blocks from this page
```suggestion
      description: Delete content blocks from this page
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      summary: Delete a content blocks from this page
```suggestion
      summary: Delete content blocks from this page
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Update a content block including the content itself and the name
```suggestion
      description: Update a content block including the content and name
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Update a plan including catalogue name, description, and oAuth2.0 scope
```suggestion
      description: Update a plan including catalogue name, description and OAuth2.0 scope
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: "Update a product including marketing description, display name, oAuth2.0 scope, and path"
```suggestion
      description: "Update a product including marketing description, display name, OAuth2.0 scope and path"
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Update description of an API including name, OAS URL, and description
```suggestion
      description: Update description of an API including name, OAS URL and description
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: List all tutorial for this API Product
```suggestion
      description: List all tutorials for this API Product
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      summary: List all tutorial for this API Product
```suggestion
      summary: List all tutorials for this API Product
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Update a tutorial page including its metadata and content
```suggestion
      description: Update a tutorial page including it's metadata and content
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Create a new API Provider. The new API Provider will have the 'Unknows' synchronization status until the first synchronization attempt
Not sure if Unknows is a typo? Should it be Unknown?

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: This endpoint delete an API Provider provider and removes all assests related to it such as API Products and Plans
```suggestions
      description: This endpoint deletes an API Provider provider and removes all assests related to it such as API Products and Plans
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Get metadata for a theme such as name, author, version, and status
```suggestion
      description: Get metadata for a theme such as name, author, version and status
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Activate a theme. When a new theme is activated, it becomes current theme for the Live portal and is displayed to all developers visiting the portal
```suggestion
      description: Activate a theme. When a new theme is activated, it becomes the current theme for the live portal and is displayed to all developers visiting the portal
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Not found or Issues when activating the theme
```suggestion
          description: Not found or issues were encountered activating the theme
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        If a theme with this name already exists in the portal, the uploaded theme will replace the existing theme. Otherwise, a new theme will be creted.
```suggestion
        If a theme with this name already exists in the portal, the uploaded theme will replace the existing theme. Otherwise, a new theme will be created.
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Update a user data such as email, name, identity provider, and organization
```suggestion
      description: Update a user data such as email, name, identity provider and organisation
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Get a extended attribute detail
```suggestion
      description: Get an extended attribute detail
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Get a extended attribute custom attributes
```suggestion
      description: Get a list of custom attributes for an extended model 
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Name this catalogue
```suggestion
          description: Name of this catalogue
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Human-readable description of this applicatoin
```suggestion
          description: Human-readable description of this application
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Redirect URL for oAuth2.0 authorization_code and PKCE grant types
```suggestion
          description: Redirect URL for OAuth2.0 authorization_code and PKCE grant types
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: "Hash of an auth token from the Tyk API Gateway. For oAuth2.0 credentials it's an empty string"
```suggestion
          description: "Hash of an auth token from the Tyk API Gateway. For OAuth2.0 credentials it's an empty string"
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Access token for Dynamic client registration that is associated with credentials. Has non-empty value only for oAuth2.0 credentials
```suggestion
          description: Access token for Dynamic client registration that is associated with credentials. Has non-empty value only for OAuth2.0 credentials
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: DCR client registration URI that is associated with credentials. Has non-empty value only for oAuth2.0 credentials
```suggestion
          description: DCR client registration URI that is associated with credentials. Has non-empty value only for OAuth2.0 credentials
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Cached client registration response from the Identity Provider. Has non-empty value only for oAuth2.0 credentials
```suggestion
          description: Cached client registration response from the Identity Provider. Has non-empty value only for OAuth2.0 credentials
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: oAuth2.0 client secret. Has non-empty value only for oAuth2.0 credentials
```suggestion
          description: OAuth2.0 client secret. Has non-empty value only for OAuth2.0 credentials
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Redirect URI for oAuth2.0 authorization_code and PKCE grant types
```suggestion
          description: Redirect URI for OAuth2.0 authorization_code and PKCE grant types
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: oAuth2.0 scope available to this credential. Has non-empty value only for oAuth2.0 credentials
```suggestion
          description: OAuth2.0 scope available to this credential. Has non-empty value only for OAuth2.0 credentials
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: oAuth2.0 `token_endpoint_auth_method` that this credential uses. Has non-empty value only for oAuth2.0 credentials
```suggestion
          description: OAuth2.0 `token_endpoint_auth_method` that this credential uses. Has non-empty value only for OAuth2.0 credentials
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +              description: "oAuth2.0 Grant types which is associated with this credential. Has non-empty value only for oAuth2.0 credentials"
```suggestion
              description: "OAuth2.0 Grant types which is associated with this credential. Has non-empty value only for OAuth2.0 credentials"
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: oAuth2.0 scopes that will be assigned to oAuth2.0 clients that use this plan. Should be comma-separated string
```suggestion
          description: OAuth2.0 scopes that will be assigned to OAuth2.0 clients that use this plan. Should be comma-separated string
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: oAuth2.0 scopes that will be assigned to oAuth2.0 clients that use this plan. Should be comma-separated string
```suggestion
          description: OAuth2.0 scopes that will be assigned to OAuth2.0 clients that use this plan. Should be comma-separated string
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: "oAuth2.0 scopes that will be assigned to oAuth2.0 clients that use this API Product. Should be comma-separated string"
replace oAuth2.0 occurrences after this with OAuth2.0

```suggestion
      description: "OAuth2.0 scopes that will be assigned to OAuth2.0 clients that use this API Product. Should be comma-separated string"
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: name of this API Product as it comes from the API Provider
```suggestion
          description: Name of this API Product as it comes from the API Provider
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Log output format. The `dev` format is more human-friednly but takes more space, `prod` is a json-like format that fits in production use cases but is difficult to read
```suggestion
          description: Log output format. The `dev` format is more human-friendly but takes more space, `prod` is a json-like format that fits in production use cases but is difficult to read
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Defines name of the cookir where the portal stores its session
```suggestion
          description: Defines name of the cookie where the portal stores its session
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Defines is SSL is enabled in the portal
```suggestion
          description: Defines if SSL is enabled in the portal
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Defines is the portal accepts self-signed certificates
```suggestion
          description: Defines if the portal accepts self-signed certificates
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Identifies if this
Description needs completing

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: unique string identifier for custom attribute
```suggestion
          description: Unique string identifier for custom attribute
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute value should be injected in the credentials metadata or not
Is this the correct description for AddToKeyMetadata?

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute should be displayed in the sign up form or not
```suggestion
          description: Indicates if this custom attribute should be displayed in the sign up form
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute value is required or not
```suggestion
          description: Indicates if this custom attribute value is required
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute value should be injected in the credentials metadata or not
```suggestion
          description: Indicates if this custom attribute value should be injected in the credentials metadata
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: if set to true the value for this default attribute will be injected in the credential metadata
```suggestion
          description: If set to true the value for this default attribute will be injected in the credential metadata
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: unique string identifier for custom attribute
```suggestion
          description: Unique string identifier for custom attribute
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute value is required or not
```suggestion
          description: Indicates if this custom attribute value is required or not
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute should be displayed in the sign up form or not
```suggestion
          description: Indicates if this custom attribute should be displayed in the sign up form or not
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: if set to true the value is set only once for the first time
```suggestion
          description: If set to true the value is set only once for the first time
```

2023-11-09 12:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api.md
> +parent: "Tyk Dashboard"
Should this be Tyk Dashboard?

2023-11-09 17:27 UTC, slega commented
@dcs3spp we don't have UUID. In the portal, currently IDs are sequential integers. Therefore, calling them UUID is incorrect and misleading.

2023-11-09 17:56 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    description: "Developer applications and API credential for develoeprs"
I forgot to remove this disclaimer.

2023-11-09 17:56 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +  version: "v1.8.0"
I removed the disclaimer as it is no longer valid.

2023-11-09 18:01 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        - description: UID of this application
UUID is a specific 128-bit implementation of a UID. In this specification, it's UID (an integer based identifier that is guaranteed to be unique for a specific class of resources). Hence, it's not UUID.

2023-11-09 18:01 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        - description: UID of this application
UUID is a specific 128-bit implementation of a UID. In this specification, it's UID (an integer based identifier that is guaranteed to be unique for a specific class of resources). Hence, it's not UUID.

2023-11-09 18:02 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        - description: UID of this application
UUID is a specific 128-bit implementation of a UID. In this specification, it's UID (an integer based identifier that is guaranteed to be unique for a specific class of resources). Hence, it's not UUID.

2023-11-09 19:02 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        description: ""
No, we don't need it at all. The request body schema has all needed descriptions in it.

2023-11-09 19:03 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Create a new API Provider. The new API Provider will have the 'Unknows' synchronization status until the first synchronization attempt
Yes, it's a typo.

2023-11-09 19:06 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: This endpoint delete an API Provider provider and removes all assests related to it such as API Products and Plans
Fixed.

2023-11-09 19:12 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api.md
> +parent: "Tyk Dashboard"
Fixed.

2023-11-09 19:16 UTC, slega commented
> Many thanks for submitting the OAS API for Enterprise Developer Portal. I have had a look through the OAS specification and made some minor suggestions.
> 
> In the specification:
> 
> * Replace UID instances with UUID
> * Replace oAuth2.0 instances with OAuth 2.0
> 
> There are some endpoints that return 422 status code to signify not found or bad request. Should those endpoints have an additional status code for 404 for not found. Then 422 is for unproccessable entity/bad request only?

@dcs3spp regarding the unprocessable entity status code: those APIs don't return 404. Even if a resource doesn't exist, they still return 422.

2023-11-09 19:29 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Identifies if this
Fixed.

2023-11-09 19:39 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute value should be injected in the credentials metadata or not
Fixed.

2023-11-09 19:39 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute should be displayed in the sign up form or not
Fixed.

2023-11-09 19:40 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute value should be injected in the credentials metadata or not
Fixed.

2023-11-09 19:40 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Weather this custom attribute value is required or not
Fixed.

2023-11-13 14:17 UTC, dcs3spp requested changes
PR looks good to me Sergei, if you can capitalise the Name sentence in the commented description I think we can merge this

2023-11-13 14:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: name of this API Product as it comes from the API Provider
@slega can this be capitalised to be consistent with line 4021 etc?

2023-11-14 15:35 UTC, dcs3spp approved these changes

2023-11-14 16:15 UTC, merged

2023-11-27 10:44 UTC, dcs3spp commented
/release to release-5.2

2023-11-27 10:46 UTC, dcs3spp commented
/release to release-5.1

2023-11-27 17:40 UTC, dcs3spp commented
/release to release-5.1