[DX-798] - Update CTA links on home page badges to refer to docs pages
TykTechnologies/tyk-docs-hugo pull request #3542
Opened 2023-11-10 16:56 UTC by dcs3spp

Update CTA links on home page badges to refer to docs pages

[DX-798](https://tyktech.atlassian.net/browse/DX-798)

2023-11-10 17:07 UTC, letzya submitted a review, later dismissed

2023-11-10 17:09 UTC, letzya commented
@dcs3spp  it doesn't work if I click on the homepage i get the old urls ...

2023-11-10 18:57 UTC, letzya requested changes
@dcs3spp it doesn't work if I click on the homepage i get the old urls ...

2023-11-11 01:22 UTC, yurisasuke commented
> @dcs3spp it doesn't work if I click on the homepage i get the old urls ...

@letzya  it is that @dcs3spp  has included the wrong preview link.It should be https://deploy-preview-3542--tyk-docs.netlify.app/docs/nightly/

2023-11-11 01:36 UTC, yurisasuke commented
Looks good. However you should change preview link to https://deploy-preview-3542--tyk-docs.netlify.app/docs/nightly/

2023-11-13 09:18 UTC, dcs3spp commented
> @dcs3spp it doesn't work if I click on the homepage i get the old urls ...

Thanks @Keithwachira. @letzya I have updated the preview link

2023-11-13 09:42 UTC, letzya commented on tyk-docs/data/tyk_components.json
>        "steps": "Only 4 steps",
```suggestion
      "steps": "Only 3 steps",
```

2023-11-13 09:43 UTC, letzya approved these changes
A small fix to the content - it's 3 steps for oss not 4

2023-11-13 11:48 UTC, merged

2023-11-13 11:48 UTC, dcs3spp commented
/release to release-5.2