[DX-809] Clean up the installation docs for the EDP, add installation guide for RHEL.
TykTechnologies/tyk-docs-hugo pull request #3562
Opened 2023-11-15 06:12 UTC by slega

https://tyktech.atlassian.net/browse/DX-809

---

### Preview Link

<br>

### Description
- Centralize all portal installation docs in `/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal`
- Structure all installation flavour based on the deployment type (Docker, Docker Compose, k8s, RHEL) instead of databases
- Add installation documentation for RHEL

#### Screenshots (if appropriate)
<br>

## Checklist

- [ x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2023-11-16 09:19 UTC, carlostyk commented
@slega my only comment would be the wording style and this is something that @dcs3spp would need to clarify. My preference would be to the point while explaining something technical for example:

_This guide provides a clear and concise, step-by-step recipe for launching the Tyk Enterprise Developer Portal using an RPM package in Red Hat environment (RHEL / CentOS)._
`This guide provides a step-by-step recipe for launching the Tyk Enterprise Developer Portal using an RPM package in Red Hat environment (RHEL / CentOS).`

_To start with, you need to download the portal package from [packagecloud.io](http://packagecloud.io/). To keep things organized, first create a directory where all installation assets (packages and config files) will be stored:_ 
`Download the portal package from [packagecloud.io](http://packagecloud.io/). Create a directory where all installation assets (packages and config files) will be stored:`

Technically looks good! So we could definitely ship it...

2023-11-16 15:02 UTC, carlostyk approved these changes
Looks good to me :) ! Thank you Sergei!!

2023-11-16 15:38 UTC, dcs3spp requested changes
Hi Sergei, PR looks good to me, I have made some minor suggestions. Could you request a peer review before we release

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Tyk Enterprise Developer Portal supports different storage options for storing the portal's CMS assets such as images, theme files and Open API Specification files. Please see the [Enterprise Develop
```suggestion
Tyk Enterprise Developer Portal supports different storage options for storing the portal's CMS assets such as images, theme files and Open API Specification files. Please see the [Enterprise Developer Portal Storage settings]({{<ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal-settings">}}) page for all the available options. 
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Other [Enterprise Developer Portal configurations]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration">}}) can be set by using environment variables with `extraEnvs` fields,
```suggestion
Other [Enterprise Developer Portal configurations]({{<ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration">}}) can be set by using environment variables with `extraEnvs` fields, e.g.:
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
> +For further guidance on launching the portal, please refer to one of the installation options: [Docker container]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise
```suggestion
For further guidance on launching the portal, please refer to one of the installation options: [Docker container]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker" >}}), [Docker Compose]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose" >}}), [Helm chart]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm" >}}), or [RPM package]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm" >}}).
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
> +2. **[Bootstrap the portal.]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md" >}})** After you've launched the portal, it will wait for you to provide credentia
```suggestion
2. **[Bootstrap the portal]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}})** After you've launched the portal, it will wait for you to provide credentials for the super admin user before it starts accepting traffic.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
> +Once you've created the super admin user, the portal will complete its installation process by creating the necessary database structure and initializing the required assets for its operations. You c
```suggestion
Once you've created the super admin user, the portal will complete its installation process by creating the necessary database structure and initialising the required assets for its operations. You can [bootstrap]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) the portal either through the UI or using the bootstrap API.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
> +Please refer to [the Bootstrapping section]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md" >}}) for implementing this step.
```suggestion
Please refer to [the Bootstrapping section]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) for implementing this step.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
> +During the bootstrap process, the portal will create the appropriate tables in the main database. The only thing required to enable SQL storage for the portal's assets is to specify the `db` [storage
```suggestion
During the bootstrap process, the portal will create the appropriate tables in the main database. The only thing required to enable SQL storage for the portal's assets is to specify the `db` [storage type]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_storage" >}}) either via a config file or an environment variable.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +Depending on your preferences, you can use MariaDB, MySQL, PostgreSQL, or SQLite as database.
```suggestion
Depending on your preferences, you can use MariaDB, MySQL, PostgreSQL or SQLite as database.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +In this recipe, the database and the portal container will run on the same network, with the database storing its data on a volume. The portal's CMS assets (images, files, themes) are stored in the d
```suggestion
In this recipe, the database and the portal containers will run on the same network, with the database storing it's data on a volume. The portal's CMS assets (images, files and themes) are stored in the database, although this guide provides links to the documentation to use a persistent volume or an S3 bucket as a storage medium for CMS assets.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +>**Note**: This document is just an example. Customize all fields, including the username, password, root password, database name, and more.
```suggestion
{{< warning success >}}
**Note**

This document is just an example. Customise all fields, including the username, password, root password, database name and more.
{{< /warning >}}
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer to [the Configuration section]({{< ref "/content/product-stack/tyk-enterprise-dev
```suggestion
Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer to the [configuration section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration" >}}) in the Tyk Enterprise Developer Portal documentation.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +Before launching the portal using docker-compose, you will need to create a `docker-compose.yaml` file. An example of the portal's docker-compose file is provided below, which you can use as a starti
```suggestion
Before launching the portal using docker-compose, you will need to create a `docker-compose.yaml` file. An example of the portal's docker-compose file is provided below, which you can use as a starting point and further customise to meet your specific requirements.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +Ensure that you replace `<tag>` with the specific version of the portal you intend to launch before executing the command, e.g. `tykio/portal:v1.7` for the portal v1.7. You can browse all available v
```suggestion
Ensure that you replace `<tag>` with the specific version of the portal you intend to launch before executing the command, e.g. `tykio/portal:v1.7` for the portal v1.7. You can browse all available versions on [Docker Hub](https://hub.docker.com/r/tykio/portal/tags) and in the [release notes section]({{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.7.0" >}}).
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +```shell
```suggestion
```console
docker-compose --env-file .env up -d
```
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first you are launching it. Follow [the bootstrapping section]
```suggestion
Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first time you are launching it. Follow the [bootstrapping section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) of the documentation to bootstrap the portal via the UI or the admin API. 
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +```shell
```suggestion
```console
docker-compose down
```
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer [the Configuration section]({{< ref "/content/product-stack/tyk-enterprise-develo
```suggestion
Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer the [configuration section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration" >}}) in the Tyk Enterprise Developer Portal documentation.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +The latest version of the portal is `tykio/portal:v1.3`, and you can browse all available versions on [Docker Hub](https://hub.docker.com/r/tykio/portal/tags).
```suggestion
The latest version of the portal is `tykio/portal:v1.3` and you can browse all available versions on [Docker Hub](https://hub.docker.com/r/tykio/portal/tags).

```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +```shell
```suggestion
```console
docker-compose --env-file .env up -d
```
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first you are launching it. Follow [the bootstrapping section]
```suggestion
Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first you are launching it. Follow the [bootstrapping section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) of the documentation to bootstrap the portal via the UI or the admin API.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +```shell
```suggestion
```console
docker-compose down
```
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +Here is an example of a sample environment file. For a comprehensive reference of environment variables,
```suggestion
Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer to the [configuration section({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration" >}})] in the Tyk Enterprise Developer Portal documentation.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +please refer to [the Configuration section({{< ref "/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md" >}})] in the Tyk Enterprise Developer Portal documentation.
remove the paragraph at line 213 and replace with suggestion above so appears in one paragraph

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +```shell
```suggestion
```console
docker-compose --env-file .env up -d
```
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first you are launching it. Follow [the bootstrapping section]
```suggestion
Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first time you are launching it. Follow the [bootstrapping section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) of the documentation to bootstrap the portal via the UI or the admin API.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +If you want to clean up your environment or start the installation process from scratch, execute the following commands to stop and stop and remove the portal container:
```suggestion
If you want to clean up your environment or start the installation process from scratch, execute the following commands to stop and remove the portal container:
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +```shell
```suggestion
```console
docker-compose down
```
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
> +```shell
```suggestion
```console
rm -rf /tmp/portal/db
```
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Depending on your preferences, you can use MariaDB, MySQL, PostgreSQL, or SQLite as database.
```suggestion
Depending on your preferences, you can use MariaDB, MySQL, PostgreSQL or SQLite as database.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +In this recipe, the database and the portal container will run on the same network, with the database storing its data on a volume. The portal's CMS assets (images, files, themes) are stored in the d
```suggestion
In this recipe, the database and the portal container will run on the same network, with the database storing its data on a volume. The portal's CMS assets (images, files and themes) are stored in the database, although this guide provides links to the documentation to use a persistent volume or an S3 bucket as a storage medium for CMS assets.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +>**Note**: This document is just an example. Customize all fields, including the username, password, root password, database name, and more.
```suggestion
{{< warning success >}}
**Note**  

This document is just an example. Customise all fields, including the username, password, root password, database name and more.

Be sure to update the connection DSN in the env-file accordingly.
{{< /warning >}}
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +> Be sure to update the connection DSN in the env-file accordingly.
remove this after applying the suggestion above

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```shell
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```container
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +>**Note**: The above PostgreSQL configuration is an example. You can customize deployment of your PostgreSQL instance. Please refer to [the PostgreSQL documentation](https://www.postgresql.org/docs/c
```suggestion
**Note**

{{< warning success >}}
The above PostgreSQL configuration is an example. You can customise deployment of your PostgreSQL instance. Please refer to [the PostgreSQL documentation](https://www.postgresql.org/docs/current/installation.html) for further guidance.
{{< /warning >}}
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer to [the Configuration section]({{< ref "/product-stack/tyk-enterprise-developer-p
```suggestion
Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer to the [configuration section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration" >}}) in the Tyk Enterprise Developer Portal documentation.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Ensure that you replace `<tag>` with the specific version of the portal you intend to launch before executing the command, e.g. `tykio/portal:v1.7` for the portal v1.7. You can browse all available v
```suggestion
Ensure that you replace `<tag>` with the specific version of the portal you intend to launch before executing the command, e.g. `tykio/portal:v1.7` for the portal v1.7. You can browse all available versions on [Docker Hub](https://hub.docker.com/r/tykio/portal/tags) and in the [release notes section]({{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.7.0" >}}).
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first you are launching it.
```suggestion
Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first time you are launching it.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Follow [the bootstrapping section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) of the documentation to bootstrap the portal via the UI or the admin API.
```suggestion
Follow the [bootstrapping section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) of the documentation to bootstrap the portal via the UI or the admin API.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +>**Note**: The above MySQL configuration is an example. You can customize deployment of your MySQL instance.
```suggestion
{{< warning success >}}
**Note**  

The above MySQL configuration is an example. You can customise deployment of your MySQL instance.

Please refer to the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/charset-applications.html) for further guidance.
{{< /warning >}}
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +> Please refer to [the MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/charset-applications.html) for further guidance.
remove this sentence after the above suggestion containing it has been applied.

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer [the Configuration section]({{< ref "/content/product-stack/tyk-enterprise-develo
```suggestion
Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer to the [configuration]({{< ref "/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md" >}}) section in the Tyk Enterprise Developer Portal documentation.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +You can browse all available versions on [Docker Hub](https://hub.docker.com/r/tykio/portal/tags) and in [the release notes section]{{< ref "product-stack/tyk-enterprise-developer-portal/release-note
```suggestion
You can browse all available versions on [Docker Hub](https://hub.docker.com/r/tykio/portal/tags) and in the [release notes]{{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.7.0" >}} section.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first you are launching it. Follow [the bootstrapping section]
```suggestion
Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first time you are launching it. Follow the [bootstrapping]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) section of the documentation to bootstrap the portal via the UI or the admin API.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
 ```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Here is an example of a sample environment file. For a comprehensive reference of environment variables,
```suggestion
Here is an example of a sample environment file. For a comprehensive reference of environment variables, please refer to the [configuration]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration" >}})] section in the Tyk Enterprise Developer Portal documentation.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +please refer to [the Configuration section({{< ref "/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md" >}})] in the Tyk Enterprise Developer Portal documentation.
remove this after applying the suggestion above.

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +You can browse all available versions on [Docker Hub](https://hub.docker.com/r/tykio/portal/tags) and in [the release notes section]{{< ref "product-stack/tyk-enterprise-developer-portal/release-note
```suggestion
You can browse all available versions on [Docker Hub](https://hub.docker.com/r/tykio/portal/tags) and in the [release notes]{{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.7.0" >}} section.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first you are launching it. Follow [the bootstrapping section]
```suggestion
Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first time you are launching it. Follow the [bootstrapping]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) section of the documentation to bootstrap the portal via the UI or the admin API.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +Since the SQLite data is persisted in the file system, you need to remove for a complete deletion of the portal:
```suggestion
Since the SQLite data is persisted in the file system, you need to remove the following file for a complete deletion of the portal:
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm.md
> +To install the portal using helm chart, you need to take the following steps:
```suggestion
To install the portal using helm charts, you need to take the following steps:
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm.md
> +In addition to value.yaml, you can also define the environment variables described in [the Configuration section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration.md" >}})
```suggestion
In addition to value.yaml, you can also define the environment variables described in the [configuration]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration" >}}) section to further customise your portal deployment. These environment variables can also be listed as a name value list under the `extraEnvs` section of the helm chart.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm.md
> +In case this is the first time you are launching the portal, it will be necessary to bootstrap it before you can use it. For detailed instructions, please refer to [the bootstrapping documentation]({
```suggestion
In case this is the first time you are launching the portal, it will be necessary to bootstrap it before you can use it. For detailed instructions, please refer to the [bootstrapping documentation]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}).
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +>**Note**: This document is just an example. Customize all fields, including the username, password, root password, database name, and more.
```suggestion
{{< warning success >}}
**Note**

This document is just an example. Customise all fields, including the username, password, root password, database name and more.

Be sure to update the connection DSN in the env-file accordingly.
{{< /warning >}}
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +> Be sure to update the connection DSN in the env-file accordingly.
Remove this sentence after applying the above suggestion containing it in the note.

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +To start with, you need to download the portal package from packagecloud.io. To keep things organized, first create a directory where all installation assets (packages and config files) will be store
```suggestion
To start with, you need to download the portal package from [packagecloud.io](https://packagecloud.io). To keep things organised, first create a directory where all installation assets (packages and config files) will be stored:
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +Next, download the portal package from [packagecloud.io](https://packagecloud.io/tyk/portal-unstable) by executing the below command
```suggestion
Next, download the portal package from [packagecloud.io](https://packagecloud.io/tyk/portal-unstable) by executing the command below.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +You can, however, customize the provided example and make more suitable for your need using [the configuration reference]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration"
```suggestion
You can, however, customise the provided example and make more suitable for your need using the [configuration]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration" >}}) reference.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +```shell
```suggestion
```console
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first you are launching it. Follow [the bootstrapping section]
```suggestion
Now the portal is running on port 3001, but it needs to be bootstrapped by providing credentials for the super admin user since it's the first you are launching it. Follow the [bootstrapping]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal" >}}) section of the documentation to bootstrap the portal via the UI or the admin API.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/overview.md
> +{{< badge read="10 mins" href="/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose" image="/img/docker.png" alt="Docker install">}}
```suggestion
{{< badge read="10 mins" href="/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose" image="/img/docker.png" alt="Docker-compose install">}}
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/overview.md
> +{{< badge read="10 mins" href="/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker" image="/img/docker.png" alt="Docker install">}}
```suggestion
{{< badge read="10 mins" href="product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker" image="/img/docker.png" alt="Docker install">}}
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +We added [S3 support]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_storage">}}) for the portal assets storage (themes, images, OAS files). This update enhances t
```suggestion
We added [S3 support]({{<ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_storage">}}) for the portal assets storage (themes, images, OAS files). This update enhances the extensibility of our platform, allowing you to choose different storage solutions to better align with your specific needs.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
> +- Added support for [S3 storage]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_storage">}}) for the portal's assets storage. Now our customers can use `s3` storag
```suggestion
- Added support for [S3 storage]({{<ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_storage">}}) for the portal's assets storage. Now our customers can use `s3` storage in addition to the filesystem which is especially important in Kubernetes environments.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +The Tyk Enterprise Developer Portal is now available in Kubernetes and customer can launch it using our [helm charts]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterpr
```suggestion
The Tyk Enterprise Developer Portal is now available in Kubernetes and customer can launch it using our [helm charts]({{<ref "product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm">}}). This feature makes the portal Kubernetes friendly by adding liveness, readiness probes, graceful shutdown and changing the portal lifecycle so that it’s possible to set an initial user and bootstrap the portal via APIs.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +This feature enables API Provides to secure the portal with [HTTPs]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_tls_enable">}}).
```suggestion
This feature enables API Provides to secure the portal with [HTTPs]({{<ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_tls_enable" >}}).
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +This new setting allows API Providers to set the logging [level]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_log_level">}}) and [format]({{<ref "/product-stack/
```suggestion
This new setting allows API Providers to set the logging [level]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_log_level" >}}) and [format]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_log_format" >}}). This offers API Providers more control over the logging behaviour of their APIs.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Added Kubernetes support and [helm charts]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm">}}).
```suggestion
- Added Kubernetes support and [helm charts]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm" >}}).
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Added [TLS]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_tls_enable">}}) support for the portal's UI.
```suggestion
- Added [TLS]({{<ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_tls_enable" >}}) support for the portal's UI.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
> +- Added config options to set the logging [level]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_log_level">}}) and [format]({{<ref "/product-stack/tyk-enterprise-
```suggestion
- Added config options to set the logging [level]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_log_level" >}}) and [format]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_log_format" >}}). This offers API Providers more control over the logging behaviour of their APIs.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
> +With this new feature, customers can simply use the same SQL database (MySQL, MariaDB, PostgreSQL) for both assets and metadata. To use the `db` [storage type]({{<ref "/content/product-stack/tyk-ente
```suggestion
With this new feature, customers can simply use the same SQL database (MySQL, MariaDB and PostgreSQL) for both assets and metadata. To use the `db` [storage type]({{< ref "/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md#portal_storage" >}}) just set the `PORTAL_STORAGE=db` for environment variables or `"Storage": "db"` in a config file and you are good to go!
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
> +  - By default, the portal uses the `db` [storage type]({{<ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_storage">}}) for storing its themes and other CMS assets and
```suggestion
  - By default, the portal uses the `db` [storage type]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_storage" >}}) for storing its themes and other CMS assets and it doesn’t require any additional configuration. This means, you can start the portal right away without specifying any additional setting for the assets storage.
```

2023-11-16 15:38 UTC, dcs3spp commented on tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
> +If you are deploying the **Tyk Enterprise Developer Portal**, set the appropriate values under the `enterprisePortal` section in your `values.yaml`. Please visit [Tyk Enterprise Developer Portal inst
```suggestion
If you are deploying the **Tyk Enterprise Developer Portal**, set the appropriate values under the `enterprisePortal` section in your `values.yaml`. Please visit [Tyk Enterprise Developer Portal installation]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm" >}}) for a step by step guide.
```

2023-11-16 17:25 UTC, slega commented
> Hi Sergei, PR looks good to me, I have made some minor suggestions.

Thanks for the review @dcs3spp ! I've applied the suggestion and the follow-up fixes you've proposed, please have a look.

Thanks!

2023-11-16 17:56 UTC, dcs3spp approved these changes

2023-11-16 17:57 UTC, merged

2023-11-16 17:57 UTC, dcs3spp commented
/release to release-5.2

2023-11-17 15:40 UTC, dcs3spp commented
/release to release-5.1