Update tyk-stack docs
TykTechnologies/tyk-docs-hugo pull request #3614
Opened 2023-11-21 02:12 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-11-21 10:24 UTC, dcs3spp requested changes
PR looks LGTM Carol, I have pushed some commits to the branch with a minor grammar change. I have added comment / suggestion relating to quickstart introduction

2023-11-21 10:24 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +Quick start using `tyk-stack` and Bitnami Redis and MongoDB chart
Explain what the overall purpose of the quick start is, something like:

```suggestion
The following quick starts guide explains how to use the Tyk Stack Helm chart to configure a Dashboard that includes:
- Tyk Pump to write analytics to MongoDB and Prometheus
- Redis for key storage

At the end of this quickstart Tyk Dashboard should be accessible through service `dashboard-svc-tyk-tyk-dashboard` at port `3000`.
```

2023-11-23 13:07 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +The following quick starts guide explains how to use the Tyk Stack Helm chart to configure a Dashboard that includes:
```suggestion
The following quick start guide explains how to use the Tyk Stack Helm chart to configure a Dashboard that includes:
```

2023-11-23 13:08 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +The following quick starts guide explains how to use the Tyk Stack Helm chart to configure a Dashboard that includes:
```suggestion
The following quick start guide explains how to use the Tyk Stack Helm chart to configure a Dashboard that includes:
```

2023-11-23 13:09 UTC, dcs3spp commented
@caroltyk Thanks for updating changes, is PR ready for release?

2023-12-01 10:32 UTC, caroltyk commented
> @caroltyk Thanks for updating changes, is PR ready for release?

Hi @dcs3spp , I'll add more changes to other helm chart related pages to Sync up the helm release status. Will need to wait for Tyk Charts 1.2 release too.

2023-12-04 06:56 UTC, komalsukhani commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +If Tyk is already bootstrapped, the application will bypass the creation of the Tyk Organization and Admin User, proceeding directly with the creation of Kubernetes Secrets.
@buraksekili We need to disable dashboard bootstrapping to bypass creation of org and admin user right?

2023-12-04 07:07 UTC, komalsukhani requested changes

2023-12-04 07:07 UTC, komalsukhani commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Kubernetes secrets can be referenced, and Kubernetes by itself configures values based on the referred secret.
```suggestion
Kubernetes secrets can be referenced, and Helm Chart by itself configures values based on the referred secret.
```
Do you mean Helm chart here?

2023-12-04 09:21 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +If Tyk is already bootstrapped, the application will bypass the creation of the Tyk Organization and Admin User, proceeding directly with the creation of Kubernetes Secrets.
If the organisation exists, we do not run tyk dashboard bootstrapping (creation of organisation and admin user). we do not need to disable bootstrapping explicitly.

2023-12-04 09:59 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +Kubernetes secrets can be referenced, and Kubernetes by itself configures values based on the referred secret.
@komalsukhani please see updates here:

1. https://github.com/TykTechnologies/tyk-docs/pull/3614/commits/8a166a0501d725eaa76a3691f3f2db252251ec44

2. https://github.com/TykTechnologies/tyk-docs/pull/3614/commits/80e48b55e6352e86be1bca9e7fb8fd049a8db0c0

3. https://github.com/TykTechnologies/tyk-docs/pull/3614/commits/0cecdb684f00c7cd066a740ef3981b1587a71414

2023-12-04 12:44 UTC, buraksekili commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +`Tyk-oss` provides the default deployment of the Tyk Open Source stack. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk P
You can ignore the suggestion if it is not suitable
```suggestion
`tyk-oss` provides the default deployment of the Tyk Open Source stack. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk Pump, an analytics purger that moves the data generated by your Tyk gateways to any back-end.
```

2023-12-05 09:35 UTC, dcs3spp approved these changes

2023-12-05 09:35 UTC, dcs3spp commented
@caroltyk I have approved. Awaiting approval from peer reviewers and will then merge and release

2023-12-06 07:48 UTC, komalsukhani approved these changes

2023-12-08 13:38 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  * [Kuberentes 1.19+](https://kubernetes.io/docs/setup/)
```suggestion
* [Kubernetes 1.19+](https://kubernetes.io/docs/setup/)
```

2023-12-08 16:16 UTC, merged

2023-12-08 16:16 UTC, dcs3spp commented
/release to release-5.2

2023-12-08 16:27 UTC, dcs3spp commented
/release to release-5.2

2023-12-08 16:37 UTC, dcs3spp commented
/release to release-5.1