[DX-841] Add release notes for the portal 1.8.0.
TykTechnologies/tyk-docs-hugo pull request #3619
Opened 2023-11-22 16:18 UTC by slega

### For internal users - Please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/DX-841
<br>

---

### Preview Link

<br>

### Description
- Add release notes for the portal 1.8.0
- Add the missing config option for the portal 1.8.0
- Fix typos in the portal's OAS
-->
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2023-11-23 10:33 UTC, dcs3spp requested changes
PR looks good to mer @slega Have made minor suggestions

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +We added capability to add addition data fields to the User model and set their behaviour. This way API Providers can:
```suggestion
We added capability to add additional data fields to the User model and set their behaviour. This way API Providers can:
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Create extend the User model with additional fields of one of four types:
```suggestion
Extend the User model with additional fields of one of four types:
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +All settings are available via [the admin API]({{< ref "product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api.md" >}}) and the UI.
```suggestion
All settings are available via the [admin API]({{< ref "product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api.md" >}}) and the UI.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +  - Force the portal to add the fields to the key metadata to make them available for the Custom plugins during API calls
```suggestion
  - Force the portal to add the fields to the key metadata to make them available to custom plugins during API calls
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +  - Can developers view the fields or are those available only for admin users
```suggestion
  - Determine if developers can view the fields or are they restricted to only admin users?
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +  - Can developer edit the fields
```suggestion
  - Can developers edit the fields?
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +All settings are available via [the admin API]({{< ref "product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api.md" >}}) and the UI.
```suggestion
All settings are available via the [admin API]({{< ref "product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api.md" >}}) and the UI.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +To create a custom attribute, it is enough to just define it in the custom attributes menu:
```suggestion
To create a custom attribute, define it in the custom attributes menu:
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +That is how it looks like in the user sign-up form:
```suggestion
This is how it looks like in the user sign-up form:
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- If credentials (cookie or client side certificates) are allowed
```suggestion
- Are credentials (cookie or client side certificates) allowed?
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- And max age of the preflight request cache.
```suggestion
- max age of the preflight request cache
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +These settings come in handy when the portal sits behind a proxy or a CDN and the portal admin needs to configure the CORS settings on the portal side so that the incoming call from a third party ori
```suggestion
These settings are useful when the portal sits behind a proxy or a CDN and the portal admin needs to configure the CORS settings on the portal side so that the incoming call from a third party origin (e.g. a CDN or a proxy) are not rejected by browser.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +To set the CORS configuration please refer to [the portal's configuration documentation]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration.md#cors-settings" >}}).
```suggestion
To set the CORS configuration please refer to the Portal's [configuration documentation]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration.md#cors-settings" >}}).
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +This way, you can make sure the portal has connectivity with the IdP before saving the OAuth2.0 settings and creating the first OAuth2.0 client.
```suggestion
This way, you can make sure the Portal has connectivity with the IdP before saving the OAuth2.0 settings and creating the first OAuth2.0 client.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +We enhanced our OAuth2.0 support by adding the capability to test connection to OAuth2.0 Identity providers (IdPs) when setting up OAuth2.0 with the Tyk Enterprise Developer Portal.
Is it possible to add a link to documentation for the new feature?

```suggestion
We enhanced our OAuth2.0 support by adding the capability to test connections to OAuth2.0 Identity providers (IdPs) when setting up OAuth2.0 with the Tyk Enterprise Developer Portal.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +In addition to the new connection testing functionality, we added one more tool to help customer to resolve complex integration issues when integrating with OAuth2.0 providers.
```suggestion
In addition to the new connection testing functionality, we added one more tool to help customer's resolve complex integration issues when integrating with OAuth2.0 providers.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +Now when the [PORTAL_DCR_LOG_ENABLED]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration.md#portal_dcr_log_enabled" >}}) environment variable is set to `true`, the portal wil
```suggestion
Now when the [PORTAL_DCR_LOG_ENABLED]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration.md#portal_dcr_log_enabled" >}}) environment variable is set to `true`, the portal will output not only the status and status code of the request to the IdP, but also actual payload returned by the IdP: 
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- [docker image to pull](https://hub.docker.com/layers/tykio/portal/v1.7.0/images/sha256-1204c9f2d53ac8cbf7230f7c73bd2edb117b33ec11547d595c58264301c9172b?context=explore)
This will need to be updated to use tag v1.8.0

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Added the capability to test connection to OAuth2.0 Identity providers menu to help the portal admin troubleshoot connectivity issues when configuring OAuth2.0 with the portal.
```suggestion
- Added the capability to test the connection to OAuth2.0 Identity providers menu to help the portal admin troubleshoot connectivity issues when configuring OAuth2.0 with the portal.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- When `PORTAL_DCR_LOG_ENABLED` is enabled the portal now returns not only the status and status code of the request to the IdP but also actual payload returned by the IdP
Add link here to config doc

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Fixed the bug where the session cookie were disclosing the username and role.
```suggestion
- Fixed the bug where the session cookie was disclosing the username and role.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Fixed the bug where the database credentials were printed in the log when bootstrapping the portal.
```suggestion
- Fixed the bug where the database credentials were printed in the logs when bootstrapping the portal.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Fixed the bug where the Forgot Password page did not reflect the current theme.
Add link to docs Forgot Password page
https://tyk.io/docs/tyk-developer-portal/tyk-enterprise-developer-portal/api-consumer-portal/reset-password/#introduction

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Fixed the bug where it was possible to remove the default organisation with resulted in the portal being non-operational.
```suggestion
- Fixed the bug where it was possible to remove the default organisation which resulted in the portal being non-operational.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Fixed the bug where the portal panicked when an IdP is not available when creating a new OAuth2.0 client.
```suggestion
- Fixed the bug where the portal panicked when an IdP is not available while creating a new OAuth2.0 client.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Fixed the bug where a developer could access API Products regardless access rights set by catalogs.
```suggestion
- Fixed the bug where a developer could access API Products regardless of the access rights set by catalogs.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Fixed the bug where the error wasn't displayed to an admin user when the theme validation fails when uploading a theme package.
```suggestion
- Fixed the bug where the error wasn't displayed to an admin user when the theme validation fails while uploading a theme package.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Fixed the bug where the live portal UI was broken when there are more than one OpenAPI specification attached to an API Product.
```suggestion
- Fixed the bug where the live portal UI was broken when there is more than one OpenAPI specification attached to an API Product.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
> +**Description**: A list of origin domains to allow access from. Wildcards are also supported, e.g. [`*.foo.com`] will allow access from any domain that ends with .foo.com.
```suggestion
**Description**: A list of origin domains to allow access from. Wildcards are also supported, e.g. [`*.foo.com`] will allow access from any domain that ends with *.foo.com*.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
> +**Description**: Headers that are allowed within a request. To apply this setting an array of the allowed headers. By default, no headers are allowed.
```suggestion
**Description**: Headers that are allowed within a request. To apply this setting, specify an array of the allowed headers. By default, no headers are allowed.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
> +**Description**: A list of methods to allow access via. To apply this setting an array of the allowed methods. By default, `GET` and `POST` methods are allowed.
```suggestion
**Description**: A list of methods that are allowed access access. To apply this setting specify an array of the allowed methods. By default, `GET` and `POST` methods are allowed.
```

2023-11-23 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +Occasionally, we may see a need to issue a critical fix if there is a systems down or a critical security defect. Here we would release this as soon as is physically possible, and the semantic versio
```suggestion
Occasionally, we may see a need to issue a critical fix if there is a systems down or a critical security defect. Here we would release this as soon as is physically possible and the semantic versioning would reflect a patch (1.3.1, 1.4.1 etc).
```

2023-11-23 18:07 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- [docker image to pull](https://hub.docker.com/layers/tykio/portal/v1.7.0/images/sha256-1204c9f2d53ac8cbf7230f7c73bd2edb117b33ec11547d595c58264301c9172b?context=explore)
Sure, I will update this PR once we have a tag for 1.8.0.

2023-11-23 18:09 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +All settings are available via [the admin API]({{< ref "product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api.md" >}}) and the UI.
A duplicate

2023-11-23 18:17 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- Fixed the bug where the Forgot Password page did not reflect the current theme.
Done

2023-11-23 18:17 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +- When `PORTAL_DCR_LOG_ENABLED` is enabled the portal now returns not only the status and status code of the request to the IdP but also actual payload returned by the IdP
Done

2023-11-24 09:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
> +We enhanced our OAuth2.0 support by adding the capability to test connection to OAuth2.0 Identity providers (IdPs) when setting up OAuth2.0 with the Tyk Enterprise Developer Portal.
@slega If this is a new feature has documentation been added to explain how to test connection to OAuth2.0 IdP? Can then link to it from release note

2023-11-27 10:12 UTC, dcs3spp approved these changes
Thanks for making the suggested changes @slega. I have approved and I will merge and release

2023-11-27 10:13 UTC, dcs3spp commented
/release to release-5.2

2023-11-27 10:13 UTC, dcs3spp commented
/release to release-5.1

2023-11-27 10:14 UTC, merged

2023-11-27 10:15 UTC, dcs3spp commented
/release to release-5.2

2023-11-27 10:15 UTC, dcs3spp commented
/release to release-5.1

2023-11-27 10:33 UTC, dcs3spp commented
/release to release-5.2

2023-11-27 10:51 UTC, dcs3spp commented
/release to release-5.2

2023-11-30 09:27 UTC, dcs3spp commented
/release to release-5.1