Release notes for 5.2.3 - second draft
TykTechnologies/tyk-docs-hugo pull request #3625
Opened 2023-11-24 11:46 UTC by andyo-tyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

Take 2 - something went screwy with the first attempt!

Added release notes section for 5.2.3
Pulled the list of "fixed CVEs" into a "Security" section for the previous, 5.2.2, release

---

### Preview Link

<br>

2023-11-24 12:16 UTC, dcs3spp requested changes
Thanks Andy, I've had a look through the change log and made minor suggestions.

2023-11-24 12:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Release Date XX Nov 2023
Update with release date

2023-11-24 12:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +<ul><li><details><summary>Python version not always correctly autodetected</summary>Fixed an issue where Tyk was not autodetecting the installed Python version if it had multiple digits in the minor
```suggestion
<ul><li><details><summary>Python version not always correctly autodetected</summary>Fixed an issue where Tyk was not autodetecting the installed Python version if it had multiple digits in the minor version (e.g. Python 3.11). The regular expression was updated to correctly identify Python versions 3.x and 3.x.x, improving compatibility and functionality.</details></li>
```

2023-11-24 12:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + <li><details><summary>Custom Authentication Plugin not working correctly with policies</summary> Fixed an issue where the session object generated when creating a Custom Key in a Go Plugin did not i
Maybe update the bots suggestion to highlight how fix benefits user. Something like???

```suggestion
 <li><details><summary>Custom Authentication Plugin not working correctly with security policies</summary> Fixed an issue where the session object generated when creating a Custom Key in a Go Plugin did not inherit parameters correctly from the Security Policy. Go plugins now inherit the correct parameters and authorisation behaves as expected.</details></li>
```

2023-11-24 12:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + <li><details><summary>Attaching a public key to an API definition for mTLS brings down the Gateway</summary> Fixed an issue where uploading a public key instead of a certificate into the certificate
```suggestion
 <li><details><summary>Attaching a public key to an API definition for mTLS brings down the Gateway</summary> Fixed an issue where uploading a public key instead of a certificate into the certificate store, and using that key for mTLS, caused all the Gateways that the APIs are published on to cease negotiating TLS. This fix improves the stability of the gateways and the successful negotiation of TLS.</details></li></ul>
```

2023-11-24 12:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +<ul><li><details><summary>Implemented a `tyk version` command that provides more details about the Tyk Gateway build</summary> This prints the release version, git commit, Go version used, architectu
Add link to related content page

2023-11-24 12:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + <li><details><summary>Added option to fallback to default API version</summary> Added new option for Tyk to use the default version of an API if the requested version does not exist. This is referre
Add links to new configuration options for Tyk OAS and Tyk Classic APIs

2023-11-24 12:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + <li><details><summary>Implemented a backoff limit for subscription connection retry</summary> Added a backoff limit for subscription connection retry to prevent excessive error messages when the ups
Should it be exponential backoff limit?

2023-11-24 12:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +The following High Priority CVEs are known to exist in this release:
Maybe check with Leo if we should include these on the release note

2023-11-24 12:23 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Release Date XX Nov 2023
Yes, when we have it

2023-11-24 12:23 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +<ul><li><details><summary>Python version not always correctly autodetected</summary>Fixed an issue where Tyk was not autodetecting the installed Python version if it had multiple digits in the minor
No, the issue was with double digit versions, e.g. 11.

2023-11-24 12:24 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + <li><details><summary>Custom Authentication Plugin not working correctly with policies</summary> Fixed an issue where the session object generated when creating a Custom Key in a Go Plugin did not i
Seems wordy and definitely repetitive - and hence written by an AI. I don't think it's necessary.

2023-11-24 12:25 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + <li><details><summary>Implemented a backoff limit for subscription connection retry</summary> Added a backoff limit for subscription connection retry to prevent excessive error messages when the ups
@agata-wit - one for you.

2023-11-24 12:25 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +The following High Priority CVEs are known to exist in this release:
What's the policy from Docs team?

2023-11-24 12:42 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Release Date XX Nov 2023
```suggestion
##### Release Date 21 Nov 2023
```

2023-11-24 15:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +The following High Priority CVEs are known to exist in this release:
Only fixed [dependency tracked](https://tyktech.atlassian.net/wiki/spaces/~178398131/pages/2064711762/Dependency+Track+-+A+User+Guide) external CVEs should be included in the release.

2023-11-24 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-gateway/v5.2.3/images/TBC?context=explore)
```suggestion
- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-gateway/v5.2.3/images/sha256-8a94658c8c52ddfe30f78c5438dd4308c4d019655d8af7773a33fdffda097992?context=explore)
```

2023-11-24 16:41 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Added
```suggestion
#### Added
```

2023-11-24 16:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + <li><details><summary>Implemented a backoff limit for subscription connection retry</summary> Added a backoff limit for subscription connection retry to prevent excessive error messages when the ups
```suggestion
 <li><details><summary>Implemented a backoff limit for GraphQL subscription connection retry</summary> Added a backoff limit for GraphQL subscription connection retry to prevent excessive error messages when the upstream stops working. The connection retries and linked error messages now occur in progressively longer intervals, improving error handling and user experience.</details></li></ul>
```

2023-11-24 16:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + <li><details><summary>Implemented a backoff limit for subscription connection retry</summary> Added a backoff limit for subscription connection retry to prevent excessive error messages when the ups
Just added "GraphQL" to make it a bit clearer

2023-11-24 16:55 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +<ul><li><details><summary>Implemented a `tyk version` command that provides more details about the Tyk Gateway build</summary> This prints the release version, git commit, Go version used, architectu
```suggestion
<ul><li><details><summary>Implemented a `tyk version` command that provides more details about the Tyk Gateway build</summary> This prints the release version, git commit, Go version used, architecture and other build details.</details></li>
```

2023-11-24 17:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +
<ul><li><details><summary>Mitigation for CVE-2023-44487</summary>Bumped golang.org/x/net to 0.17.0, updating the direct dependency to partially resolve CVE-2023-44487. As Go embeds this in the standard library, we only partially resolve the CVE due to an older Go version in use. To mitigate the vulnerability, users are advised to disable HTTP/2 at this time by setting `enable_http2` to `false`.</details></li></ul>

2023-11-24 17:04 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +
```suggestion
 <ul><li><details><summary>Mitigation for CVE-2023-44487</summary>Bumped golang.org/x/net to 0.17.0, updating the direct dependency to partially resolve CVE-2023-44487. As Go embeds this in the standard library, we only partially resolve the CVE due to an older Go version in use. To mitigate the vulnerability, users are advised to disable HTTP/2 at this time by setting `enable_http2` to `false`.</details></li></ul>
```

2023-11-24 17:09 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +#### Fixed
```suggestion

#### Fixed
```

2023-11-28 11:37 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +The following High Priority CVEs are known to exist in this release:
Removed CVEs from Changelog. See above comment

2023-11-28 14:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + <li><details><summary>Runtime log error incorrectly produced when using Go Plugin Virtual Endpoints</summary> Fixed a minor issue with Go Plugin virtual endpoints where a runtime log error was produ
```suggestion
 <li><details><summary>Runtime log error incorrectly produced when using Go Plugin Virtual Endpoints</summary> Fixed a minor issue with Go Plugin virtual endpoints where a runtime log error was produced from a request, even if the response was successful. Thanks to [uddmorningsun](https://github.com/uddmorningsun) for highlighting the [issue](https://github.com/TykTechnologies/tyk/issues/4197) and proposing a fix.</details></li>
```

2023-11-28 17:13 UTC, dcs3spp approved these changes

2023-11-28 17:22 UTC, merged

2023-11-28 17:22 UTC, dcs3spp commented
/release to release-5.2