[DX-847] Jaeger improvement
TykTechnologies/tyk-docs-hugo pull request #3639
Opened 2023-11-27 12:57 UTC by SonjaChevre

### Preview Link
* [OTel Jaeger Docker](https://deploy-preview-3639--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger/)
* [OTel Jaeger K8s](https://deploy-preview-3639--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s)
* [Exporting OpenTracing Distributed Traces to Jaeger](https://deploy-preview-3639--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-tracing/jaeger/)
* [Link added to Distributed Tracing in monitoring page](https://deploy-preview-3639--tyk-docs.netlify.app/docs/nightly/planning-for-production/monitoring#3-api-observability)
* [Link added to OTel tools from APIM Troubleshooting page](https://deploy-preview-3639--tyk-docs.netlify.app/docs/nightly/api-management/manage-apis/api-operations/api-observability)

<br>

### Description

* Improved text and structure of the OpenTelemetry Jaeger page
* Improved OpenTelemetry collector configuration to work with OTLP instead of Jaeger exporter (now deprecated)
* Improved the OpenTracing Jaeger page to reference and recommend the OpenTelemetry page

## Checklist

- [x] I have added a **preview link** to the PR description.
- [X] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2023-11-27 13:10 UTC, SonjaChevre commented
Note: the bot feedback about adding a brief explanation of why the Jaeger exporter is now deprecated is not relevant to this doc page

> 💡 General suggestions: The PR is well-structured and the changes are clear. The improvements in the documentation and configuration are beneficial for users. However, it would be helpful to include a brief explanation of why the Jaeger exporter is now deprecated and the benefits of using OTLP instead.

2023-11-27 13:18 UTC, mativm02 requested changes

2023-11-27 13:18 UTC, mativm02 commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +    endpoint: jaeger-all-in-one:4317
we're not exposing the port 4317 of the `jaeger-all-in-one` service [here](https://github.com/TykTechnologies/tyk-docs/blob/1347bfeb5ff221f594b7a725dc3846b2ecd9bd8d/tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md#option-1-using-docker-compose). I think 14250 is the right one.

2023-11-27 15:40 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +    endpoint: jaeger-all-in-one:4317
@mativm02 We should change the port we're exposing there. From [Jaeger docs](https://www.jaegertracing.io/docs/1.50/getting-started/#all-in-one), 4317 is for gRPC OTLP (which is correct now)

2023-11-27 15:41 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
>        endpoint: "jaeger-all-in-one-collector.observability.svc.cluster.local:14250"
We need to change this port as well

2023-11-28 10:51 UTC, dcs3spp requested changes
PR LGTM @SonjaChevre

I have made minor suggestions. Once requested changes and peer review addressed we can merge and release

2023-11-28 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +To enable Tyk Gateway to work seamlessly with OpenTelemetry, modify the Tyk configuration file (e.g., `tyk.conf`) and append the following OpenTelemetry settings:
```suggestion
To enable Tyk Gateway to work seamlessly with OpenTelemetry, modify the Tyk configuration file (`tyk.conf`) and append the following OpenTelemetry settings:
```

2023-11-28 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +Ensure to adjust the endpoint value to match the OpenTelemetry Collector's address. Optionally, switch the exporter value to http for HTTP protocol usage instead of gRPC.
```suggestion
Ensure that the endpoint value is adjusted to match the OpenTelemetry Collector's address. Optionally, switch the exporter value to http for HTTP protocol usage instead of gRPC.
```

2023-11-28 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-tracing/jaeger.md
> +We recommend to follow the guide [Exporting OpenTelemetry Distributed Traces to Jaeger]({{< ref "otel_jaeger" >}}) instead.
```suggestion
Subsequently, we recommend following this guide [Exporting OpenTelemetry Distributed Traces to Jaeger]({{< ref "otel_jaeger" >}}). 
```

2023-11-28 11:52 UTC, SonjaChevre commented
thanks @dcs3spp - I have also found an issue with the Kubernetes part of that page, will update it and then address your comments. will let you know when ready for the next round of review!

2023-11-28 15:19 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +    endpoint: jaeger-all-in-one:4317
hey @mativm02 and @tbuchaillot - I have reworked the whole guide to get rid of the OTel collector, since Jaeger doesn't need it anymore. I will create later another guide specific to the OpenTelemetry collector.

But since Jaeger is the tool for people to get start, I thought it would be nice to keep the "easiest" version without the OTel collector in that guide. Can you please take a quick look? I have tested both version in docker and Kubernetes and it worked fine.

2023-11-28 15:21 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +To enable Tyk Gateway to work seamlessly with OpenTelemetry, modify the Tyk configuration file (e.g., `tyk.conf`) and append the following OpenTelemetry settings:
I have reworked the documentation to remove the OpenTelemetry collector - and this part is no longer included.

2023-11-28 15:21 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +Ensure to adjust the endpoint value to match the OpenTelemetry Collector's address. Optionally, switch the exporter value to http for HTTP protocol usage instead of gRPC.
I have reworked the documentation to remove the OpenTelemetry collector - and this part is no longer included.

2023-11-28 15:23 UTC, SonjaChevre commented
hey @mativm02 and @tbuchaillot - I have reworked the whole guide to get rid of the OTel collector, since Jaeger doesn't need it anymore. I will create later another guide specific to the OpenTelemetry collector.

But since Jaeger is the tool for people to get started, I thought it would be nice to keep the "easiest" version without the OTel collector in that guide. Can you please take a quick look? I have tested both version in docker and Kubernetes and it works fine now. 

@dcs3spp please take a look at the whole page one more time, as I have made significant changes. 

thank you all!

2023-11-28 16:22 UTC, dcs3spp requested changes
PR looks good to me @SonjaChevre . Have suggested minor changes and a peer review

2023-11-28 16:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +This API definition sets up a basic API named Hello-World for testing purposes, configured to proxy requests to `http://echo.tyk-demo.com:8080/``.
```suggestion
This API definition sets up a basic API named Hello-World for testing purposes, configured to proxy requests to `http://echo.tyk-demo.com:8080/`.
```

2023-11-28 16:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +http://localhost:8080/hello-world/
should add curl statement here?

2023-11-28 16:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +- Access Jaeger at `http://localhost:16686``.
```suggestion
- Access Jaeger at *http://localhost:16686*.
```

2023-11-28 16:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +  - Click the 'Find Traces' button.
```suggestion
  - Click the *Find Traces* button.
```

2023-11-28 16:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +2. Install Jaeger Operator (see [Jaeger Operator Documentation](https://www.jaegertracing.io/docs/latest/operator/)).
```suggestion
2. Install [Jaeger Operator](https://www.jaegertracing.io/docs/latest/operator/)).
```

2023-11-28 16:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +Save the following API definition as `apidef-hello-world.yaml``:
```suggestion
Save the following API definition as `apidef-hello-world.yaml`:
```

2023-11-28 18:07 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +# ... Existing docker-compose.yml content for jaeger
@SonjaChevre I think the env for OTLP endpoint here should be changed from
    - TYK_GW_OPENTELEMETRY_ENDPOINT=otel-collector:4317
to:
    - TYK_GW_OPENTELEMETRY_ENDPOINT=jaeger-all-in-one:4317
(I didn't try it, let me know if I'm wrong here :D )

2023-11-29 04:00 UTC, letzya requested changes
Looks great! Love this content.
One thing i was thinking while reading is - "is it for me?" If I'm an oss user and if I'm a licensed users and if I'm the other one can I still use it or how can I still use it.

1. I suggest to make the fact this it's a guide for Tyk gateway oss more prominent in the beginning of the tutorial. 
2. We should  also suggest what to do if you are a licensed user. for example you can explain that for licensed users check the section below and add at the end of the page a section/heading for licensed users and just give them the links to follow page xyz (link to it) to deploy the dashboard instead of step 2 and connect to it instead of step 3

2023-11-29 04:00 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +1. Install from the cert-manager release manifest (required by Jaeger)
Is it "install from"?

2023-11-29 04:00 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +title: Exporting OpenTelemetry Distributed Traces to Jaeger
I think users will benefit from a simpler and shorter the title

2023-11-29 04:00 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +This guide provides comprehensive steps to configure Tyk API Gateway OSS with Jaeger, enabling efficient distributed tracing and amplifying API observability.
@dcs3spp  Could be great to have an external link to jaeger

2023-11-29 07:35 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +http://localhost:8080/hello-world/
added

2023-11-29 07:35 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +Save the following API definition as `apidef-hello-world.yaml``:
changed

2023-11-29 07:36 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +# ... Existing docker-compose.yml content for jaeger
good call, thanks! I forgot to update it

2023-11-29 07:36 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +1. Install from the cert-manager release manifest (required by Jaeger)
changed

2023-11-29 07:37 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +title: Exporting OpenTelemetry Distributed Traces to Jaeger
changed

2023-11-29 07:39 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +This guide provides comprehensive steps to configure Tyk API Gateway OSS with Jaeger, enabling efficient distributed tracing and amplifying API observability.
updated

2023-11-29 07:48 UTC, SonjaChevre commented
thanks @letzya!

I was wondering the same about OSS versus licensed users. For the moment, I have added something about OSS at the very beginning of the document. 

There are so many different variations for that tutorial:
* Docker or Kubernetes
* OSS or licensed users (self-managed, Tyk Cloud hybrid gateways and in the future Tyk Cloud hosted gateways)
* Jaeger, Grafana, Dynatrace, Datadog, ... (any observability vendors)

Let's talk about the best way to structure this next week (what should be split, what should stay on the same page, ...).

> Looks great! Love this content.
> 
> I'd like to suggest a few small additions please - One thing i was thinking while reading is -
> 
> * Who is this guide for? Is it for a poc? It says "comprehensive" does it mean it's for production?
> * is it for me? As an oss user? And if I'm a licensed user?
> * if I'm the other type of user, can I still use it or what else do I need to still use it.
> 
> 1. I suggest to add a few more words to clarify the intention of this guide. Is it a getting started? Is it a comprehensive guide ? Is the configuration good for production and only the setup of jaeger is simplified ?
> 2. Suggest to make the fact this it's a guide for **Tyk gateway oss** more prominent in the beginning of the tutorial.
> 3. We should  also suggest what to do if you are a licensed user. for example you can explain that for licensed users check the section below and add at the end of the page a section/heading for licensed users and just give them the links to follow page xyz (link to it) to deploy the dashboard instead of step 2 and connect to it instead of step 3

2023-11-30 12:41 UTC, mativm02 approved these changes
LGTM 🚀

2023-11-30 12:51 UTC, dcs3spp requested changes
Hi @SonjaChevre I have done another review on the updated comments. Will discuss the issue re target audience etc in meeting next week

2023-11-30 12:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +- Create a new file named `apidef-hello-world.json``.
```suggestion
- Create a new file named `apidef-hello-world.json`.
```

2023-11-30 12:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +- Copy the provided simple API definition below into the `apidef-hello-world.json`` file:
```suggestion
- Copy the provided simple API definition below into the `apidef-hello-world.json` file:
```

2023-11-30 12:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +docker compose up
```suggestion
docker-compose up
```

2023-11-30 12:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +``
```suggestion
```bash
```

2023-11-30 12:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +``
add extra closing backtick ```

2023-11-30 12:59 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +docker compose up
`docker-compose up` has been deprecated, the modern way to do it is `docker compose up`

from docker:
`Unlike Compose V1, Compose V2 integrates into the Docker CLI platform and the recommended command-line syntax is docker compose.`

https://docs.docker.com/engine/reference/commandline/compose_up/

2023-11-30 13:02 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> +``
done

2023-11-30 13:03 UTC, SonjaChevre commented
> Hi @SonjaChevre I have done another review on the updated comments. Will discuss the issue re target audience etc in meeting next week

thanks @dcs3spp I have done the changes, apart from the docker compose part (see explanation above).

2024-01-11 16:19 UTC, dcs3spp reviewed
@SonjaChevre

There was a [PR #3861](https://github.com/TykTechnologies/tyk-docs/pull/3861/files#diff-16ec0ce7e1a15342c38aa77a88a2a144199bd75ab5de67a99d6c6505a034581aR264)
recently merged for @buraksekili 
This PR splits the Docker and Kubernetes content which gives a clearer structure.

I have added some questions/comments in the PR that relates to above PR from @buraksekili. 

I will add the changes discussed by Rich yesterday.

I think the merge conflicts are a result of removing docker content from otel_jaeger.

2024-01-11 16:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +- kubectl and helm CLI tools installed
Add donwload links to kubectl helm CLI in prerequisites section

2024-01-11 16:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +description: "This guide explains how to integration Tyk Gateway with OpenTelemetry and Jager on Kubernetes to enhance API Observability"
```suggestion
description: "This guide explains how to integrate Tyk Gateway with OpenTelemetry and Jager on Kubernetes to enhance API Observability"
```

2024-01-11 16:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +helm upgrade tyk-otel tyk-helm/tyk-oss -n $NAMESPACE --create-namespace --devel \
Does this block need updating following Buraks PR  line 277 recently merged? https://github.com/TykTechnologies/tyk-docs/pull/3861/files

2024-01-11 16:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> -TYK_GW_OPENTELEMETRY_ENDPOINT=tyk-otel-collector-opentelemetry-collector:4317
Does this endpoint name need to be updated to match that recently merged in this PR https://github.com/TykTechnologies/tyk-docs/pull/3861/files#diff-16ec0ce7e1a15342c38aa77a88a2a144199bd75ab5de67a99d6c6505a034581aR264  (see line 264 in the files of the pR)

2024-01-12 07:38 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +- kubectl and helm CLI tools installed
added

2024-01-12 07:50 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
> -TYK_GW_OPENTELEMETRY_ENDPOINT=tyk-otel-collector-opentelemetry-collector:4317
the endpoint stays the same (in my version - we no longer use the OpenTelemetry collector as Jaeger has its own endpoint to receive the data). But other settings are needed - I have updated accordingly.

2024-01-12 07:51 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +helm upgrade tyk-otel tyk-helm/tyk-oss -n $NAMESPACE --create-namespace --devel \
updated

2024-01-12 12:46 UTC, dcs3spp commented
Thanks @SonjaChevre. The PR changes look good to me 🎉 

I have fixed the merge conflicts, before I go ahead and approve:

@SonjaChevre Would you be able to check the previews are ok after I fixed the merge conflicts?

- [Docker preview](https://deploy-preview-3639--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger/)
- [K8s preview](https://deploy-preview-3639--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s/)

@buraksekili Would you be able to peer review to check that the Docker and K8s guides above reflects the changes in your [PR #3861](https://deploy-preview-3861--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger/) that was recently merged.

2024-01-16 13:47 UTC, SonjaChevre commented
I'll re-try all the instructions tomorrow morning to make sure everything runs as expected.

2024-01-17 08:33 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +For Kubernetes instructions, please refer to [How to integrate with Jaeger on Docker]({{< ref "otel_jaeger" >}}).
I believe, it should be `Docker` instructions. If this is not the case, feel free to ignore my comment.
```suggestion
For Docker instructions, please refer to [How to integrate with Jaeger on Docker]({{< ref "otel_jaeger" >}}).
```

2024-01-17 08:33 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +  --set tyk-gateway.gateway.opentelemetry.endpoint="jaeger-all-in-one-collector.observability.svc.cluster.local:4317"
I am not familiar with Jaeger but previously, we suggested users to install OTel collector in `tyk` namespace, [here](https://deploy-preview-3861--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger/#2-install-the-opentelemetry-collector-via-helm). I guess, this is not required, right?

2024-01-17 08:33 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +  --from-literal "TYK_URL=http://gateway-svc-tyk-otel-tyk-gateway.tyk.svc.cluster.local:8080" \
Even though the service name is correct, adding `cluster.local` suffixes restrict the use case of the service address in k8s networking - for example, it won't work with different domain-name clusters. So, it'd better not to add it here.
```suggestion
  --from-literal "TYK_URL=http://gateway-svc-tyk-otel-tyk-gateway.tyk.svc:8080" \
```

2024-01-17 08:33 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +  --set tyk-gateway.gateway.opentelemetry.endpoint="jaeger-all-in-one-collector.observability.svc.cluster.local:4317"
```suggestion
  --set tyk-gateway.gateway.opentelemetry.endpoint="jaeger-all-in-one-collector.observability.svc:4317"
```

Also, as mentioned in the below comment, svc addresses can work without `cluster.local`. You can remove it if it looks okay to you as well.

2024-01-17 08:33 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +Next, navigate to Jaeger on `http://localhost:16686`, select the ´service´ called ´tyk-gateway´and click on the button ´Find traces´. You should see traces generated by Tyk:
```suggestion
Next, navigate to Jaeger on `http://localhost:16686`, select the ´service´ called ´tyk-gateway` and click on the button ´Find traces´. You should see traces generated by Tyk:
```

2024-01-17 09:04 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +  --set tyk-gateway.gateway.opentelemetry.endpoint="jaeger-all-in-one-collector.observability.svc.cluster.local:4317"
yes - since Jaeger has its own endpoint to ingest OpenTelemetry data, the use of an OpenTelemetry collector is no longer required. I removed it for simplicity and plan to add later another guide just for the OpenTelemetry collector.

2024-01-17 09:05 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +  --set tyk-gateway.gateway.opentelemetry.endpoint="jaeger-all-in-one-collector.observability.svc.cluster.local:4317"
thanks for the explanation, makes sense!

2024-01-17 09:06 UTC, SonjaChevre commented
thanks @buraksekili for the review!

2024-01-17 09:11 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
> +  --set tyk-gateway.gateway.opentelemetry.endpoint="jaeger-all-in-one-collector.observability.svc.cluster.local:4317"
thanks for the explanation!

2024-01-17 09:11 UTC, buraksekili approved these changes

2024-01-17 12:46 UTC, dcs3spp commented
many thanks @buraksekili for review, @SonjaChevre I will merge this tomorrow's PR review session

2024-01-18 09:05 UTC, dcs3spp approved these changes

2024-01-18 14:01 UTC, merged

2024-01-18 14:01 UTC, dcs3spp commented
/release to release-5.2