[DX-858] Add the Get started guide for the EDP.
TykTechnologies/tyk-docs-hugo pull request #3673
Opened 2023-12-01 19:32 UTC by slega

### For internal users - Please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/DX-858
<br>

---

### Preview Link
https://deploy-preview-3673--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-developer-portal/getting-started/enterprise-portal-concepts/
<br>

### Description
Add the Get started guide for the EDP.
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2023-12-05 13:04 UTC, letzya commented on tyk-docs/themes/tykio/layouts/docs_images_sitemap.xml
> +    <loc>https://tyk.io/docs//product-stack/tyk-enterprise-developer-portal/getting-started/publish-api-products-and-plans/</loc>
@dcs3spp how come we update this file in the PR?

2023-12-05 17:40 UTC, dcs3spp requested changes
Hi @slega PR looks good to me. I have added some minor suggestions. There is an issue highlighted in peer review regarding updating images in the site map that DX will need to investigate before merging and releasing.

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +In this section, you will learn how to customize the visual appearance of API Products and plans with the Tyk Enterprise Developer Portal. That includes:
```suggestion
In this section, you will learn how to customise the visual appearance of API Products and plans with the Tyk Enterprise Developer Portal. That includes:
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md
> +You can continue configuring and customizing it either via the UI or the portal admin API. Please refer to [the Tyk Enterprise Developer Portal Concepts section]({{< ref "/product-stack/tyk-enterpris
```suggestion
You can continue configuring and customising it either via the UI or the portal admin API. Please refer to [Tyk Enterprise Developer Portal Concepts]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/enterprise-portal-concepts.md" >}}) for further guidance.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +When integrating with Tyk, the Tyk policies will be imported into the Developer Portal. Depending on the configuration that’s been set in the policy section, the policy will either be imported as an
```suggestion
When integrating with Tyk, the Tyk policies will be imported into the Developer Portal. Depending on the configuration that’s been set in the policy section, the policy will either be imported as an API Product or a Plan. For further details check the [portal key concepts]({{< ref "product-stack/tyk-enterprise-developer-portal/getting-started/enterprise-portal-concepts" >}}) document.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +- A Tyk Self-Managed [installation]({{< ref "/content/tyk-self-managed/install.md" >}})
```suggestion
- A Tyk Self-Managed [installation]({{< ref "tyk-self-managed/install" >}})
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +- Have APIs [created in your Tyk installation]({{< ref "/content/getting-started/create-api.md" >}})
```suggestion
- Have APIs [created in your Tyk installation]({{< ref "getting-started/create-api" >}}.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +To create one, assuming you have one or more APIs already created.
```suggestion
The following steps explain how to create and import an API product from Tyk, assuming you have one or more APIs already created:
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +4. Under **Global limits and Quota**, select **Enforce access rights**. Ensure **Enforce usage quota** and **Enforce rate limit** are **not** selected.
For this explanation why is it recommended that these options are not selected? Are these production settings? @slega

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +2. Select an API, it doesn’t matter which API you select since the purpose of this policy is simply just to control the allowance. However, selecting an API is a required field which means you need t
```suggestion
2. Select an API. Please note that this a required field. The purpose of the policy explained in this guide is to control allowance, so you can select any API here.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +4.  To import the plans into the Developer portal, from the Tyk Portal admin app, click **Synchronise**.
```suggestion
4.  Click **Synchronise** to import the plans into the Developer portal, from the Tyk Portal admin app.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +Go to [Customize visual appearance of API Products and Plans]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans" >}}) to customize visual appearance
```suggestion
Visit [Customize visual appearance of API Products and Plans]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans" >}}) to learn how to customise the visual appearance of API Products and plans.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +If you are interested in getting access contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
```suggestion
If you are interested in getting access, contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +In the Tyk Enterprise Developer Portal, Organisations and Catalogues are used to segment the user base and make different APIs available to different user audiences according the business model.
```suggestion
In the Tyk Enterprise Developer Portal, Organisations and Catalogues are used to segment the user base and make different APIs available to different user audiences according to the business model.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +For instance, if the Account Management API is available only to trusted partners but the Payment API is available to every developer, that can be solved by creating two catalogs for these two APIs.
```suggestion
For example, assume the following scenario:

- Account Management API is available only to trusted partners
- Payment API is available to all developers

Subsequently, two catalogs can be created for these two APIs.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +Enterprise customers can use both APIs with the Enterprise plan that offers a higher user limit while any other customers (for instance, individual developers or hobbyists) have access only to the Pa
```suggestion
Customers subscribed to the enterprise plan can use both APIs, offering a higher user limit. Conversely, customers subscribed to the Free plan (individual developers or hobbyists) only have visibility of the Payment API.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +To achieve that, the API Provider uses two catalogues to implement their business model so that they can offer different experience to different customer audiences. This section explains to achieve t
```suggestion
To achieve that, the API Provider uses two catalogues to implement their business model so that they can offer different experiences for different customer audiences. This section explains how to achieve that using the Tyk Enterprise Developer Portal.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +The Tyk Enterprise Developer Portal uses Organisation aca Catalogues to segment access to APIs and plans. Therefore, the first thing is to create an organisation for your customers. If you don't want
@slega is aca a typo? _The Tyk Enterprise Developer Portal uses Organisation aca Catalogues_

Should it be _The Tyk Enterprise Developer Portal uses Organisations and Catalogues?_

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +In this guide, we will create the **B2B customer** organisation to fulfil the above business model. To do so, follow the below steps:
```suggestion
In this guide, we will create the **B2B customer** organisation to fulfill the above business model:
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +1. To create an organisation for the **B2B customer**, navigate From the **Organisations** menu and click on the **Add new organisation** button to add a new organisation.
```suggestion
1. To create an organisation for the **B2B customer**, navigate to the **Organisations** menu and click on the **Add new organisation** button.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +2. Enter the name of your new organisation and click on the **Save** button. A new default-team will be also automatically created that is tied to your new organisation.
```suggestion
2. Enter the name of your new organisation and click on the **Save** button. A new default-team will be automatically created and associated with your new organisation.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +If you want to edit the default team name you can do so by navigating to **Teams**, open up the team tied to the organisation you created, and edit the name as required.
```suggestion
You can edit the default team name by navigating to **Teams** and opening up the team associated with the organisation you created. This will allow you to edit the team name as required.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +By default, when the portal is [bootstrapped]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md" >}}) features two catalogues:
```suggestion
The default catalogues that are featured when the portal is [bootstrapped]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md" >}}) are:
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +- **Public** catalogues. A catalogue that is available to all developers.
```suggestion
- **Public** catalogues are available to all developers.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +- **Private** catalogues. A catalogue that is available only to logged in developers how have been assigned with access to that catalogue.
```suggestion
- **Private** catalogues are available only to logged in developers who have been assigned with access.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +You can create multiple public catalogues but since they will share the same level of access we advise to keep only one public catalogue.
```suggestion
While it is possible to create multiple public catalogues, we do not advise doing so. This is because multiple public catalogues will share the same level of access.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +   Finally, add plans and API Products to the created catalogue so that the select developer teams can view them.
```suggestion
   Finally, add plans and API Products to the created catalogue so that the selected developer teams can view them.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +You have successfully added can create multiple public catalogues but since they will share the same level of access we advise to keep only one public catalogue.
Should this be something like the following?:

```suggestion
You have successfully added a catalogue and associated a team with it. Furthermore, you have allocated plans and API products to this catalogue.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +Go to [Customize the sign-up form]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form" >}}) for the user sign-up form customization guide.
```suggestion
Visit [Customise the sign-up form]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form" >}}) for the user sign-up form customisation guide.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +description: "Make your API Products to standout by customizing their visual appearance"
```suggestion
description: "Make your API Products standout by customising their visual appearance"
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +If you are interested in getting access contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
```suggestion
If you are interested in getting access, contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +To customize the visual appearance of API Products, follow the following steps:
```suggestion
To customise the visual appearance of API Products:
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +1. Navigate to the **API Products** menu, select the product that you want to customize (the Payment API in example below). In this menu you can customize the following aspects of API Products:
```suggestion
1. Navigate to the **API Products** menu, select the product that you want to customise (the Payment API in example below). In this menu you can customise the following aspects of API Products:
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +- **Catalogue display name**: this is the name that will be displayed in the external catalogue.
Capitalise the first sentence of each of these bullet points

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +From that page you can also manage [OAuth2.0 settings]({{< ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md" >}}) and add [the Get started gu
```suggestion
From that page you can also manage [OAuth2.0 settings]({{< ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md" >}}) and add [Get started guides]({{< ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products" >}}) to your API Products, which is covered in the relevant sections.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +2. Once you have saved the changes by clicking on the **Save** button, you can view how the API Product looks like in the catalogue:
```suggestion
2. Save changes by clicking on the **Save** button. You should now be able to preview how the API Product will be displayed in the catalogue:
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +## Customize plans
```suggestion
Customise plans
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +1. To customize visual appearance of plans, open the **Plans** menu and select the plan you want to customize. You can customize the following settings:
```suggestion
1. To customise visual appearance of plans, open the **Plans** menu and select the plan you want to customise. You can customise the following settings:
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +- **Catalogue display name**: name of the that will be displayed in the API Product page.
```suggestion
- **Catalogue display name**: The name of the catalogue that will be displayed in the API Product page.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +- **Catalogues**: the catalogues in which this plan is available. Catalogues and organisation are be [covered]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-
```suggestion
- **Catalogues**: The catalogues in which this plan is available. Catalogues and organisation are [covered]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs" >}}) later within this getting started guide.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +- **Scope**: scope for the [OAuth2.0 settings]({{< ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md" >}}). Please refer to the [OAuth2.0 docu
```suggestion
- **Scope**: Scope for the [OAuth2.0 settings]({{< ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md" >}}). Please refer to the [OAuth2.0 documentation]({{< ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration" >}}) for further guidance.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +- **Auto-approve settings for access requests**: whether access requests for this plan should be approved automatically.
```suggestion
- **Auto-approve settings for access requests**: Determines if access requests for this plan should be approved automatically.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +- **Access request frequency**: defines how often developers can request access to a specific plan. This way the admins can prevent developers from creating too many keys and abusing their automatica
```suggestion
- **Access request frequency**: Defines how often developers can request access to a specific plan. This way the admins can prevent developers from creating too many keys and abusing their automatically approved plans.
```

What is the frequency measured in, days?

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +2. Customize the plan's visual appearance as need and then click on the **Save**. Now you can view the plan in the API Product page:
```suggestion
2. Customise the plan's visual appearance as required and then click on the **Save** button. Now you can view the plan in the API Product page: 
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +You have now customized the visual appearance of your API Product and plan. By following the above steps you can customize visual appearance of your other API Products and plans.
```suggestion
You have now customised the visual appearance of your API Product and plan. By following the above steps you can customise visual appearance of your other API Products and plans. 
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
> +Go to [Create API Consumer organisations and catalogues]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs" >}}) to create API Consumer organisations an
```suggestion
Visit the [create API Consumer organisations and catalogues]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs" >}}) section to learn how to create API consumer organisations and catalogues.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +title: "Customize the sign-up form"
```suggestion
title: "Customise the sign-up form"
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +description: "Customize the sign-up form and extend the data stored in the User profile"
```suggestion
description: "Customise the sign-up form and extend the data stored in the User profile"
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +If you are interested in getting access contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
```suggestion
If you are interested in getting access, contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +In this section, you will learn how to customize the sign-up form for your API Consumers and extend the data stored in the user profile.
```suggestion
In this section, you will learn how to customise the sign-up form for your API Consumers and extend the data stored in the user profile.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +- Add a new attribute to the User profile and make it available in the sign-up form.
```suggestion
- Add a new attribute to the user profile and make it available in the sign-up form.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +- Optionally, add description to it and set other parameters that suit your needs.
```suggestion
- Optionally, add a description and set other parameters that suit your requirements.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +To customize the sign-up form, you need to add new data attributes to the User model so that when a user profile is being created, those attributes will be recorded against the user profile.
```suggestion
To customise the sign-up form, you need to add new data attributes to the user model so that when a user profile is being created, those attributes will be recorded against the user profile.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +To start customizing the user sign-up form, navigate to the **Custom attributes** menu and the select the **User** model. Currently, it is possible to extend only the User model, in future releases w
```suggestion
To start customising the user sign-up form, navigate to the **Custom attributes** menu and the select the **User** model. Currently, it is possible to extend only the user model. In future releases we will add the same capabilities to other models.
```

What are the other models that this feature will be added to in future?

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +## Add a new attribute to the User model
Replace User model with user model

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +To add a new attribute to the User model, click on the **Add Custom attribute** button and then fill in properties of the new attribute:
Capitalise the first sentence in the bullet points below

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +- **Attribute ID**: a string that consists of letters (a-zA-Z), numbers (0-9), dashes, and underscores and is used to refer to this attribute in [the Admin APIs]({{< ref "/product-stack/tyk-enterpris
```suggestion
- **Attribute ID**: A string that consists of letters (a-zA-Z), numbers (0-9), dashes, and underscores. This is used to reference the attribute in the [Admin APIs]({{< ref "/product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api" >}}) screen.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +- **Description**: a rich text that is used to describe this attribute. It is also displayed in the UI.
```suggestion
- **Description**: Explains the intended usage of this attribute. It is also displayed in the UI.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +- **Type of attribute**: type of data that can be stored in this attribute. You cannot change value of this field once the attribute is created. The following data types are acceptable:
```suggestion
- **Type of attribute**: The type of data that can be stored in this attribute. You cannot change the value of this field once the attribute is created. The following data types are acceptable:
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +  - Dropdown (a list of value).
```suggestion
  - Dropdown (a list of values).
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +- **Enable validation**: defines if the portal should apply the regular expression defined in the **Validation Reg Exp** to validate value of this attribute when creating or updating a user profile.
```suggestion
- **Enable validation**: Determines if the portal should apply the regular expression defined in the **Validation Reg Exp** to validate the value of this attribute when creating or updating a user profile. It is available for the **String** data type only.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +- Fields that define the attribute's behavior:
Capitalise the first sentence of each bullet point below

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +  - Write once read many: defines if the value of the attribute can be changed after a user profile is created.
Replace defines in the bullet point items below with Determines, like for this example.

```suggestion
  - Write once read many: Determines if the value of the attribute can be changed after a user profile is created.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +For purpose of this guide, make sure to tick the **Required** and **Show on sign-up form** checkboxes and select the **Developers can only view the attribute** behavior.
```suggestion
For the purpose of this guide, make sure to tick the **Required** and **Show on sign-up form** checkboxes and select the **Developers can only view the attribute** option.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +Once you have created a new custom attribute and saved changes to the User model by clicking on th **Save** button, the new attribute is added to the user sign-up form.
```suggestion
The new attribute will be added to the user sign-up form, once you have created a new custom attribute and saved changes to the user model by clicking on the **Save** button.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +You have now added a custom attribute to the User model and made it appear in the user sign-up form. By following the above steps you can add more attributes of different types.
```suggestion
You have now added a custom attribute to the user model and made it appear in the user sign-up form. By following the above steps you can add more attributes of different types.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
> +Go to [Setup email notifications]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/setup-email-notifications" >}}) to setup email notifications guide which completes this tutor
```suggestion
Visit [Setup email notifications]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/setup-email-notifications" >}}) to learn how to setup email notifications guide, which completes this tutorial.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/enterprise-portal-concepts.md
> +Go to [Connect to the Tyk Dashboard]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider" >}}) to connect the portal with the Tyk Dashboard.
```suggestion
Visit the [connect to the Tyk Dashboard]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider" >}}) guide to learn how to connect the portal with tTyk Dashboard.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/getting-started-with-enterprise-portal.md
> +description: "This section provide concise guide for the basic configuration of the portal"
```suggestion
description: "This section provides a concise guide for the basic configuration of the portal"
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/getting-started-with-enterprise-portal.md
> +1. [Connect to a provider (Tyk Self Managed).]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider" >}})
```suggestion
1. [Connect to a provider (Tyk Self Managed)]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider" >}})
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/getting-started-with-enterprise-portal.md
> +2. [Create and import API Products and Plans in your Tyk Self Managed Instance.]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan" >}})
```suggestion
2. [Create and import API Products and Plans in your Tyk Self Managed Instance]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan" >}})
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/getting-started-with-enterprise-portal.md
> +3. [Create catalogs and developer audiences.]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs" >}})
```suggestion
3. [Create catalogs and developer audiences]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs" >}})
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/getting-started-with-enterprise-portal.md
> +4. [Publish API Products and Plans to the Developer portal so that API consumers can access them.]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans
```suggestion
4. [Publish API Products and Plans to the Developer portal so that API consumers can access them]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans" >}})
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +If you are interested in getting access contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
```suggestion
If you are interested in getting access, contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +The first step in getting started with the developer portal is to connect the portal to a provider. The current provider supported is Tyk Self Managed, although you can still use multiple instances o
Does this mean that currently only Tyk Self Managed can be used as a provider and that can connect to multiple instances of Tyk Self Managed to import their policies?

Add a link to the Getting Started guide section in this sentence _The 'Getting started guide' part shows you how to set up a policy and import it to the developer portal._

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +- A Tyk Self-Managed [installation]({{< ref "/content/tyk-self-managed/install.md" >}})
```suggestion
- A Tyk Self-Managed [installation]({{< ref "tyk-self-managed/install" >}})
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +- The Enterprise portal installed
```suggestion
- The Enterprise portal installed.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +- A login for the portal admin app
```suggestion
- A login for the portal admin app.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +2. Click Add provider
```suggestion
2. Click **Add provider**
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +| Gateway URL              | The gateway URL refers to the URL that the portal developers will send the queries and use the access credentials.
```suggestion
| Gateway URL              | The gateway URL refers to the URL that the portal developers will use for requesting queries and accessing credentials.  
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +| Secret                   | The Secret can be fetched from the Tyk Self-Managed / Tyk analytics dashboard. The procedure is as follows:  Go to the Tyk Dashboard. Navigate to Users. Select a user wit
Could we link to another page that describes these steps? If not I have added the suggestion below to highlight different screens and options involved.

```suggestion
| Secret                   | The Secret can be fetched from the Tyk Self-Managed / Tyk analytics dashboard. The procedure is as follows:  Go to the Tyk Dashboard. Navigate to *Users*. Select a user with the permissions you want to bring on to the portal. You can find the secret under *API Access Credentials. (Optional)*. You can find the organisation id listed under *Organisation ID* if your use case requires this. Please note that the Portal will share the same permissions that the user selected to provide the secret.   
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +| Policy tags              | This is an optional field that can be used to define which policies from Tyk will be imported to the portal. If a tag is defined here, it needs to also be defined in the
Add link to Publish API Products and plans to the public-facing portal.

What is the next journey and can we link to it?

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +### How to find the Secret and Org ID inside your Tyk Dashboard
```suggestion
### How to find the Secret and Org ID inside your Tyk Dashboard?
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +5.  From the **Actions** menu for your API, select Copy API ID
```suggestion
5.  From the **Actions** menu for your API, select **Copy API ID**.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +Go to [Create API Products and Plans]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan" >}}) to connect create API Products and plans.
```suggestion
Visit the [Create API Products and Plans]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan" >}}) guide to learn how to create API Products and plans.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/create-api-product-and-plan.md
> +   {{< img src="img/dashboard/portal-management/enterprise-portal/portal-add-policy.png" alt="Create a policy" >}}
Why has a space being added before each of the images below?

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
> +If you want to edit the default team name you can do so by navigating to **Teams**, open up the team tied to the organisation you created, and edit the name as required.
```suggestion
If you want to edit the default team name you can do so by navigating to **Teams**, open up the team associated withthe organisation you created and edit the name as required.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md
> +Please refer to [the email notification section]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/setup-email-notifications" >}}) for further instructions for setting up email
```suggestion
Please refer to the [email notification section]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/setup-email-notifications" >}}) for further instructions for setting up the email server.
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md
> +- Create [policies with enforced access right]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md" >}}) (API Product in the Portal)
```suggestion
- Create [policies with enforced access rights]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md" >}}) (API Product in the Portal)
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md
> +- Create one or more [policies with enforced rate limit and quota]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md" >}}) (Plan in the Portal)
```suggestion
- Create one or more [policies with enforced rate limit and quotas]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md" >}}) (Plan in the Portal)
```

2023-12-05 17:40 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +      - title: "Visual appearance customization"
```suggestion
      - title: "Visual appearance customisation"
```

2023-12-05 22:12 UTC, slega commented on tyk-docs/themes/tykio/layouts/docs_images_sitemap.xml
> +    <loc>https://tyk.io/docs//product-stack/tyk-enterprise-developer-portal/getting-started/publish-api-products-and-plans/</loc>
@letzya it's all autogenerated. Do I need to somehow change/update it?

2023-12-05 22:19 UTC, letzya commented on tyk-docs/themes/tykio/layouts/docs_images_sitemap.xml
> +    <loc>https://tyk.io/docs//product-stack/tyk-enterprise-developer-portal/getting-started/publish-api-products-and-plans/</loc>
no, my comment was to @dcs3spp , to chek why it happened

2023-12-05 22:23 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/getting-started-with-enterprise-portal.md
Do we have an alias for this? I didn't see an error in the ci, which is od if we don't have an alias

2023-12-06 10:27 UTC, dcs3spp commented on tyk-docs/themes/tykio/layouts/docs_images_sitemap.xml
> +    <loc>https://tyk.io/docs//product-stack/tyk-enterprise-developer-portal/getting-started/publish-api-products-and-plans/</loc>
@letzya @sergei Keith and I tried this morning on the PR branch doing a Hugo build via both the CLI and docker-compose. We could not replicate the URL being added to that XML file. The GHub history shows that until now it was last updated 17 months. 

@slega How were you building the PR?

<img width="1606" alt="Screenshot 2023-12-06 at 10 21 04" src="https://github.com/TykTechnologies/tyk-docs/assets/12863448/3d7d23b5-10ba-4d1a-823e-a9efdd5a8cb1">

2023-12-06 11:36 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md
> +You can continue configuring and customizing it either via the UI or the portal admin API. Please refer to [the Tyk Enterprise Developer Portal Concepts section]({{< ref "/product-stack/tyk-enterpris
@dcs3spp does it mean the ci breaks if we remove the `.md`?

2023-12-06 11:38 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
> +If you want to edit the default team name you can do so by navigating to **Teams**, open up the team tied to the organisation you created, and edit the name as required.
withthe - needs a space

2023-12-06 11:40 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +- Have APIs [created in your Tyk installation]({{< ref "/content/getting-started/create-api.md" >}})
actually I suggest to keep the text as part of the link, since for better SEO, if we put clear wording in the link, the crawler can better understand the link

2023-12-06 11:42 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +- Have APIs [created in your Tyk installation]({{< ref "/content/getting-started/create-api.md" >}})
@dcs3spp also do we need the prefix `/content/`?

2023-12-06 11:42 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md
> +You can continue configuring and customizing it either via the UI or the portal admin API. Please refer to [the Tyk Enterprise Developer Portal Concepts section]({{< ref "/product-stack/tyk-enterpris
also is it possible to remove the leading `/`?

2023-12-06 11:54 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +When integrating with Tyk, the Tyk policies will be imported into the Developer Portal. Depending on the configuration that’s been set in the policy section, the policy will either be imported as an
again, I suggest to keep the text as part of the link, since for better SEO, if we put clear wording in the link, the crawler can better understand the link - "Please refer to [Tyk Enterprise Developer Portal Concepts]"

2023-12-06 15:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md
> +You can continue configuring and customizing it either via the UI or the portal admin API. Please refer to [the Tyk Enterprise Developer Portal Concepts section]({{< ref "/product-stack/tyk-enterpris
Have tried locally and it worked for this link.

2023-12-06 16:15 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/getting-started-with-enterprise-portal.md
Yes there is an alias here that exists in tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/getting-started-with-enterprise-portal.md

[here](https://github.com/TykTechnologies/tyk-docs/pull/3673/files#diff-1545beec9a2d07e4aff640621d1de27fa73a9998174fb54dfcc2f9fd0f79f6e2)

2023-12-06 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/getting-started-with-enterprise-portal.md
Yes an alias exists in product-stack/tyk-enterprise-developer-portal/getting-started/getting-started-with-enterprise-portal.md

[here](https://github.com/TykTechnologies/tyk-docs/blob/68e1efdbd15716aed957cd0b502d2e7a68e0d424/tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/getting-started-with-enterprise-portal.md)

2023-12-06 16:54 UTC, dcs3spp commented on tyk-docs/themes/tykio/layouts/docs_images_sitemap.xml
> +    <loc>https://tyk.io/docs//product-stack/tyk-enterprise-developer-portal/getting-started/publish-api-products-and-plans/</loc>
As mentioned above tried to replicate the URL updating automatically with a CLI Hugo build and docker-compose build earlier. Could not replicate.

I have reverted the URL to the original value at _tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/publish-api-products-and-plans/_

The other updated url did not exist

2023-12-06 18:02 UTC, dcs3spp commented
@slega I have committed the suggestions I have made and reverted the update of the image sitemap to the correct URL. There are some comments / questions before merging

2023-12-08 12:39 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md
> +- Connect to a provider [Tyk Self-Managed]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider" >}})
```suggestion
- Connect to a provider [Tyk Self-Managed]({{< ref "product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider" >}})
```

2023-12-08 12:39 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md
> +- Create [policies with enforced access rights]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md" >}}) (API Product in the Portal)
```suggestion
- Create [policies with enforced access rights]({{< ref "product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan" >}}) (API Product in the Portal)
```

2023-12-08 12:40 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md
> +- Create [policies with enforced access rights]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md" >}}) (API Product in the Portal)
does this work?

2023-12-08 13:04 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md
> +- Create [policies with enforced access rights]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md" >}}) (API Product in the Portal)
have tested locally and both the previous commit and suggested commit work

2023-12-12 22:18 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
> +4. Under **Global limits and Quota**, select **Enforce access rights**. Ensure **Enforce usage quota** and **Enforce rate limit** are **not** selected.
@dcs3spp that's how the portal works:
- API Products are partitioned policies that provide an ACL but not quota/rate limits.
- Plans are partitioned policies that provide quota/rate limits but not an ACL.

This page is partially copied of the content we already have in [the API Management section](https://tyk.io/docs/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/create-api-product-and-plan/), so for consistency I would like to keep it as-is.

2023-12-12 22:18 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
> +The Tyk Enterprise Developer Portal uses Organisation aca Catalogues to segment access to APIs and plans. Therefore, the first thing is to create an organisation for your customers. If you don't want
Yep, a typo.

2023-12-12 22:32 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +| Policy tags              | This is an optional field that can be used to define which policies from Tyk will be imported to the portal. If a tag is defined here, it needs to also be defined in the
Added the link.

2023-12-12 22:32 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +The first step in getting started with the developer portal is to connect the portal to a provider. The current provider supported is Tyk Self Managed, although you can still use multiple instances o
This is the old copy but yes, you are right. I've rewritten this sentence to make clearer.

2023-12-14 11:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +| Policy tags              | This is an optional field that can be used to define which policies from Tyk will be imported to the portal. If a tag is defined here, it needs to also be defined in the
```suggestion
| Policy tags              | This is an optional field that can be used to define which policies from Tyk will be imported to the portal. If a tag is defined here, it needs to also be defined in the Policy section in the [Tyk Dashboard]({{< ref "/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan#create-and-import-an-api-product-from-tyk" >}}). If this field is left empty in both this provider section and in the policies within Tyk, then all policies will be imported from the Tyk instance. How to include the label in the policy section inside Tyk, is explained in [Publish API Products and plans]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/publish-api-products-and-plans" >}}) for the public-facing portal. |
```

2023-12-14 11:53 UTC, dcs3spp approved these changes

2023-12-14 11:55 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
> +| Policy tags              | This is an optional field that can be used to define which policies from Tyk will be imported to the portal. If a tag is defined here, it needs to also be defined in the
```suggestion
| Policy tags              | This is an optional field that can be used to define which policies from Tyk will be imported to the portal. If a tag is defined here, it needs to also be defined in the Policy section in the [Tyk Dashboard]({{< ref "product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan#create-and-import-an-api-product-from-tyk" >}}). If this field is left empty in both this provider section and in the policies within Tyk, then all policies will be imported from the Tyk instance. How to include the label in the policy section inside Tyk, is explained in [Publish API Products and plans]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/publish-api-products-and-plans" >}}) for the public-facing portal. |
```

2023-12-14 14:56 UTC, merged

2023-12-14 14:56 UTC, dcs3spp commented
/release to release-5.2

2023-12-14 14:56 UTC, dcs3spp commented
/release to release-5.1