[TT-10683] [5.2.4 docs] Document plugin compiler arguments
TykTechnologies/tyk-docs-hugo pull request #3676
Opened 2023-12-04 10:50 UTC by titpetric

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>
https://tyktech.atlassian.net/browse/TT-10683
---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-12-04 10:59 UTC, jeffy-mathew commented on tyk-docs/content/plugins/supported-languages/golang.md
> +Plugin ID argument: Providing a `plugin_id` argument enables hot
do we need to also mention that `plugin_id` helps with loading two plugins with same module name without issues? If two plugins have same module name and is built using tyk-plugin-compiler without using `plugin_id`, the second plugin would fail loading, right?

2023-12-04 12:47 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +Plugin ID argument: Providing a `plugin_id` argument enables hot
I added a paragraph for this particular case, also listed the warnings of the go plugin package and a golang issue about loading plugins twice. IMO we still should not advise people to use it without the leading warning, as it would be unsafe to do so, hence the few references around these restrictions.

2023-12-05 10:15 UTC, dcs3spp requested changes
@titpetric PR lgtm, added some minor suggestions and questions

2023-12-05 10:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +- Before 5.1: the plugin would be build in a filesystem path based on plugin_id,
```suggestion
- Before 5.1: the plugin would be built in a filesystem path based on plugin_id.
```

2023-12-05 10:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +- After 5.2.4: the plugin compiler adjusts the go module in use for the plugin,
```suggestion
- After 5.2.4: the plugin compiler adjusts the go module in use for the plugin.
```

2023-12-05 10:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +The `GOOS` and `GOARCH` options are respected as the base build
Is it worth mentioning for macOS to use linux/arm64 here following recent customer feedback?

2023-12-05 10:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +Plugin ID argument: Providing a `plugin_id` argument enables hot
Remove duplicate hot

```suggestion
Plugin ID argument: Providing a `plugin_id` argument enables
```

2023-12-05 10:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +2. plugin_id = optional, provides build uniqueness
Does this have the purpose of build id? If so could the name of the compiler parameter be build_id?

2023-12-05 10:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +- `DEBUG=1`, turns on debug output from the plugin compiler process.
```suggestion
- `DEBUG=1`: enables debug output from the plugin compiler process.
```

2023-12-05 10:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +- `GO_TIDY=1`, runs go mod tidy to resolve possible dependency issues.
```suggestion
- `GO_TIDY=1`: runs go mod tidy to resolve possible dependency issues.
```

2023-12-05 10:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +- `GO_GET=1`, invokes go get to retrieve the exact tyk gateway dependency.
```suggestion
- `GO_GET=1`: invokes go get to retrieve the exact Tyk gateway dependency.
```

2023-12-05 10:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +the plugin build go.mod file and imports to ensure a unique build.
So the problem is that the filesystem path cannot be used for a unique _.so_ file because it is trimmed yes? When plugin bundles are fetched from webserver are they also affected?

What is modified in the go.mod file and imports to ensure a unique build?

2023-12-05 18:21 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +the plugin build go.mod file and imports to ensure a unique build.
The package name of the plugin is modified. It doesn't matter particularly to what, just that the plugin id is included in the package name and in the final built .so file.

2023-12-05 18:28 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +2. plugin_id = optional, provides build uniqueness
Semantics, it could also be renamed to seed or something. As we're documenting existing state I'd leave it unless you feel stronger about it being a build id :)

2023-12-05 18:33 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +The `GOOS` and `GOARCH` options are respected as the base build
Which feedback? Plugin compiler is a cross build env and i don't have a mac, i don't think we provide anything other than linux/amd64 (cross compile env), and then only overriding goos/goarch via arguments allows to build arm64 targets, i wouldn't want to go into more detail for cross compilation here

2023-12-05 18:39 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/golang.md
> +the plugin build go.mod file and imports to ensure a unique build.
Bundles don't change behaviour, they are extracted on disk and the .so files loaded. Using plugin ids would require re-releasing the bundle with a different plugin id if we want the files to be reloadable, a few more steps to make that happen

2023-12-07 10:44 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +- Before 5.1: the plugin would be built in a filesystem path based on build_id,
```suggestion
- Before 5.1: the plugin would be built in a filesystem path based on build_id.
```

2023-12-07 10:45 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +- After 5.2.4: the plugin compiler adjusts the go module in use for the plugin,
```suggestion
- After 5.2.4: the plugin compiler adjusts the go module in use for the plugin.
```

2023-12-07 10:54 UTC, dcs3spp approved these changes
PR LGTM! Once @jeffy-mathew approved I will merge. I'll release when release 5.2.4 is ready

2023-12-07 11:25 UTC, jeffy-mathew approved these changes

2023-12-07 12:16 UTC, merged

2023-12-07 17:01 UTC, dcs3spp commented
/release to release-5.2