[TT-10662] Add docs to deploy Enterprise portal using new helm chart
TykTechnologies/tyk-docs-hugo pull request #3683
Opened 2023-12-05 07:38 UTC by komalsukhani

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-12-05 18:03 UTC, dcs3spp requested changes
@komalsukhani I have made minor suggestions to the draft so far. Also there are some CI checks that are erroring.

2023-12-05 18:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +Where `TYK_ORG` and `TYK_AUTH` are the Tyk Dashboard Organisation ID and the Tyk Dashboard API Access Credentials respectively. Which can be obtained under your profile in the Tyk Dashboard.
```suggestion
The environment variables `TYK_ORG` and `TYK_AUTH` are the Tyk Dashboard _Organisation ID_ and the Tyk Dashboard API _Access Credentials_ respectively. These can be obtained under your profile in the Tyk Dashboard.
```

2023-12-05 18:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +You must set the following values in the `values.yaml` or with `--set {field-name}={field-value}` with the helm upgrade command:
```suggestion
You must set the following values in the `values.yaml` or with `--set {field-name}={field-value}` using the helm upgrade command:
```

2023-12-05 18:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +This guide provides a clear and concise, step-by-step recipe for installing the Tyk Enterprise Developer Portal using new helm charts.
```suggestion
This guide provides a clear and concise, step-by-step guide for installing the Tyk Enterprise Developer Portal using the new helm charts.
```

2023-12-05 18:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +In addition to value.yaml, you can also define the environment variables described in [the Configuration section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration.md" >}})
Accompany this with an example of how to configure the environment variables in the extraEnvs section

```suggestion
In addition to values.yaml, you can also define the environment variables described in the [configuration section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration.md" >}}) to further customise your portal deployment. These environment variables can also be listed as a name value list under the `extraEnvs` section of the helm chart.
```

2023-12-05 18:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +Please refer to [this](({{<ref "deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md">}})) page to get details of all configuration options.
```suggestion
Please refer to this [guide](({{<ref "deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md">}})) for an explanation of all configuration options.
```

2023-12-06 08:42 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +In addition to values.yaml, you can also define the environment variables described in the [configuration section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration.md" >}})
```suggestion
In addition to `values.yaml`, you can also define the environment variables described in the [configuration section]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration.md" >}}) to further customise your portal deployment. These environment variables can also be listed as a name value list under the `extraEnvs` section of the helm chart.
```

2023-12-06 08:43 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +```console
`console` or `bash`? If `console` is intended, please ignore the comment
```suggestion
```bash
```

2023-12-06 11:35 UTC, caroltyk requested changes
Thank you for the updates. Added a suggestion in Introduction to explain difference between installing with tyk-stack and tyk-dev-portal

2023-12-06 11:35 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +To install the portal using helm charts, you need to take the following steps:
```suggestion
There are two ways to install Tyk Enterprise Developer Portal. You can enable `global.components.devPortal` during Tyk Self-Managed deployment by following the [Tyk Self-Managed installation instruction]({{ref "/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack"}}) using our `tyk-stack` umbrella chart. It will install Tyk Enterprise Developer Portal together with Tyk Gateway and Dashboard in the same namespace.

Alternatively, you can install Tyk Enterprise Developer Portal as standalone component using our `tyk-dev-portal` chart. This page provides a clear and concise, step-by-step guide for installing the Tyk Enterprise Developer Portal as standalone component using the new helm chart.

To install the portal using helm charts, you need to take the following steps:
```

2023-12-06 11:35 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +This guide provides a clear and concise, step-by-step guide for installing the Tyk Enterprise Developer Portal using the new helm charts.
Moved this to the upper paragraph.
```suggestion
```

2023-12-06 11:35 UTC, caroltyk commented on tyk-docs/data/menu.yaml
> +            category: Path
New helm chart should come before "Legacy helm chart"

2023-12-06 13:18 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
> +```console
Both works in similar way in this case.

2023-12-06 13:49 UTC, komalsukhani commented on tyk-docs/data/menu.yaml
> +            category: Path
Resolved in [50a966d](https://github.com/TykTechnologies/tyk-docs/pull/3683/commits/50a966d37971906696d07588322e463fe0fa7016)

2023-12-07 09:50 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +            category: Path
Category should be Page in menu.yaml

2023-12-07 16:40 UTC, dcs3spp approved these changes

2023-12-07 22:19 UTC, carolwkc approved these changes
LGTM

2023-12-08 16:33 UTC, merged

2023-12-08 16:33 UTC, dcs3spp commented
/release to release-5.2