[DX-878] tyk-charts-1.2.0-release-notes.md
TykTechnologies/tyk-docs-hugo pull request #3696
Opened 2023-12-07 01:02 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

for content review only, not to be merged. 
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-12-07 08:53 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +This version upgrades Tyk Gateway and Tyk Dashboard to v5.2.3 and Tyk Portal to 1.8.1.
Is Portal 1.8.1 ready to be used or should we go with 1.8.0?

2023-12-07 08:55 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Renamed environment variable names to be consistent with `envconfig` naming convention. The list of supported environment variables are documented at [tyk-k8s-bootstrap]([https://github.com/TykTech
```suggestion
- Renamed environment variable names to be consistent with `envconfig` naming convention. The list of supported environment variables are documented at [tyk-k8s-bootstrap](https://github.com/TykTechnologies/tyk-k8s-bootstrap).
```

2023-12-07 08:55 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
Since this is recently merged, it is not included in the release
```suggestion
```

2023-12-07 08:58 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Fixed value of dashboard.overrideHostname with gwHostName yaml anchor.
What do you think changing it as follows?
```suggestion
- Aligned the value of `dashboard.overrideHostname` with `gwHostName` yaml anchor.
```

2023-12-07 09:02 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Fixed TYK_DB_ENABLEAGGREGATELOOKUPS to `dashboard.enableAggregateLookups`.
Previously, setting TYK_DB_ENABLEAGGREGATELOOKUPS was mixed in the code. Even it was a configurable thing in values.yaml, we only update the environment variable under certain conditions, such as using specific backend storage. we fixed such complications. So, it'd be better to update this statement. My suggestion would be:

```suggestion
- Fixed setting TYK_DB_ENABLEAGGREGATELOOKUPS via `dashboard.enableAggregateLookups`.
```

Please ignore the suggestion if you think it is not explicit.

2023-12-07 09:03 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Updated default value for postgresql sslmode changed from empty to `disable`.
```suggestion
* Updated default value for PostgreSQL sslmode (`global.postgres.sslmode`) from empty to `disable`.
```

2023-12-07 09:04 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated set Default service type of Dashboard service from NodePort to ClusterIP.
```suggestion
- Updated default service type of Dashboard service from NodePort to ClusterIP.
```

2023-12-07 09:09 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed .cluster.local from service URL to allow for named cluster support.
In docs, there is variability in the use of the term `.cluster.local`, as it is sometimes quoted and sometimes not. Let's ensure consistency.

```suggestion
- Removed `.cluster.local` from service URL to allow for named cluster support.
```

2023-12-07 09:09 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Updated: Set Dashboard URL in Portal using service discovery.
```suggestion
* Updated seting Dashboard URL in Portal using service discovery.
```

2023-12-07 09:35 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed duplicate setting of TYK_DB_HOSTCONFIG_GATEWAYHOSTNAME in tyk-stack values.yaml. The value is set at tyk-dashboard.dashboard.hostConfig.overrideHostname.
```suggestion
- Removed duplicate setting of TYK_DB_HOSTCONFIG_GATEWAYHOSTNAME in tyk-stack values.yaml. The value is set at `tyk-dashboard.dashboard.hostConfig.overrideHostname`.
```

2023-12-07 09:36 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed `global.components.dashboard` flag as it was misleading. Adapted gateway to use a gateway-specific flag `tyk-gateway.gateway.useDashboardAppConfig`. Set `tyk-gateway.gateway.useDashboardApp
```suggestion
- Removed `global.components.dashboard` flag as it was misleading. Adapted gateway to use a gateway-specific flag `tyk-gateway.gateway.useDashboardAppConfig`. Set `tyk-gateway.gateway.useDashboardAppConfig` to true if gateway should connect to Dashboard for [app configurations](https://tyk.io/docs/tyk-oss-gateway/configuration/#use_db_app_configs).
```

2023-12-07 09:37 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added opentelemetry support at `gateway.opentelemetry`.
```suggestion
- Added OpenTelemetry support at `gateway.opentelemetry`.
```

2023-12-07 09:37 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated Default service type of Gateway service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalance
```suggestion
- Updated default service type of Gateway service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.  
```

2023-12-07 09:38 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* gateway pod should listen on port `.gateway.containerPort` instead of `global.servicePorts.gateway`.
```suggestion
- Gateway pod listens on port `.gateway.containerPort` instead of `global.servicePorts.gateway`.
```

2023-12-07 09:39 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added opentelemetry support at `tyk-gateway.gateway.opentelemetry`.
```suggestion
- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
```

2023-12-07 09:39 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the Default service type of Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalanc
```suggestion
- Updated the default service type of Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.
```

2023-12-07 09:40 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Fixed: Setup hybrid pump using secret values if user has set global.remoteControlPlane.useSecretName.
```suggestion
- Setting up hybrid pump using Kubernetes secret values if `global.remoteControlPlane.useSecretName` is set.
```

2023-12-07 09:40 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added opentelemetry support at `tyk-gateway.gateway.opentelemetry`.
```suggestion
- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.  
```

2023-12-07 09:43 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added In `tyk-gateway`, new fields (`dashboardConnectionString` and `policyConnectionString`) are introduced to set connection strings for Dashboard App Config and Policies when using Tyk Dashboard
```suggestion
- Added new fields (`dashboardConnectionString` and `policyConnectionString`) in `tyk-gateway`, that are introduced to set connection strings for Dashboard App Config and Policies when using Tyk Dashboard as a source.
```

2023-12-07 09:44 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Updated Gateway default image tag to v5.2.3.
```suggestion
- Updated default storage type in values.yaml from `fs` to `db`. The new default option does not require additional configuration to work.
- Updated: Move the database related variables in the values.yaml outside the section related to the storage of the assets inside enterprise portal.
- Updated secret metadata name to be dynamic so that it is possible to install multiple releases in the same namespace.
- Updated Gateway default image tag to v5.2.3.
```

2023-12-07 09:45 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
can we move it to `Removed` section?

2023-12-07 09:51 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
I think we're changing the service URL by removing '.cluster.local' instead of removing something

2023-12-07 11:05 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
that makes sense 👍

2023-12-07 11:07 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +*
will we mention here about the deprecated charts? or does `*` have special meaning?

2023-12-07 11:07 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +```
```suggestion
```yaml
```

2023-12-07 11:08 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- In `tyk-dashboard`, a new field (`tykApiHost`) allows configuring a custom service name for Tyk Gateway.
```suggestion
- In `tyk-dashboard`, a new field (`dashboard.tykApiHost`) allows configuring a custom service name for Tyk Gateway.
```

2023-12-07 11:08 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Fixed the issue that Dashboard version 5.0.2 or before failed to start because of missing configuration file (tyk_analytics.conf). In order to fix that, if the dashboard version is <= v5.0.2, it ru
```suggestion
- Fixed the issue that Dashboard version 5.0.2 or before failed to start because of missing configuration file (tyk_analytics.conf). In order to fix that, if the dashboard version is <= v5.0.2, it runs init-container to create empty tyk_analytics.conf file.
```

2023-12-07 11:09 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added opentelemetry support at `tyk-gateway.gateway.opentelemetry`.
```suggestion
- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
```

2023-12-07 13:22 UTC, dcs3spp requested changes
PR lgtm @caroltyk, I have added minor suggestions

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +##### Stable release of Tyk Stack, Tyk Dashboard, Tyk Developer Portal, and bootstrapping :tada:
```suggestion
##### Stable release of Tyk Stack, Tyk Dashboard, Tyk Developer Portal and bootstrapping :tada:
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Gateway and Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort
```suggestion
- Updated the default service type of Gateway and Pump from *NodePort* to *ClusterIP*. You can configure external access to a service with your desired method like changing service type to *NodePort*, *LoadBalancer* or configuring *Ingress*.
```
Briefly explain how this benefits users

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +*
good point @buraksekili, it is worth mentioning any deprecated helm charts here

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +This version enhances Gateway charts by introducing configurations for Opentelemetry. Their usage can be found in values.yaml:
```suggestion
This version enhances Gateway charts by introducing configurations for OpenTelemetry. Their usage can be found in values.yaml:
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +      # Type of the span processor to use
What are the valid values?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +      contextPropogation: tracecontext
What are the valid types of context propagator?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Bootstrapping Job do not fail if there is existing ORG found in dashboard storage. If the database has been bootstrapped already, the job will proceed with creating secret with Operator and Develop
Is this a fix rather than a change?

```suggestion
- Bootstrapping Job does not fail if there is existing ORG found in dashboard storage. If the database has been bootstrapped already, the job will proceed with creating secret with Operator and Developer Portal.
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
Should this be in the removed section?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed annotation `[sidecar.istio.io/inject:](http://sidecar.istio.io/inject:) “false”` from postInstall and preDelete job. If Tyk is deployed inside Istio service mesh, you can configure the requ
```suggestion
- Removed annotation `[sidecar.istio.io/inject:](http://sidecar.istio.io/inject:) “false”` from *postInstall* and *preDelete* jobs. If Tyk is deployed inside *Istio service mesh*, you can configure the required annotation for all jobs using values.yaml file.
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed unused fields from tyk-bootstrap chart values.yaml: `global.servicePorts`, `global.components`, `global.tls.gateway`.
```suggestion
- Removed unused fields from tyk-bootstrap chart values.yaml: `global.servicePorts` and `global.components`, `global.tls.gateway`.
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Fixed the issue that Dashboard version 5.0.2 or before failed to start because of missing configuration file (tyk_analytics.conf). In order to fix that, if the dashboard version is <= v5.0.2, it ru
```suggestion
- Fixed the issue that Dashboard version <= 5.0.2 failed to start because of missing configuration file (tyk_analytics.conf). In order to fix that, if the dashboard version is <= v5.0.2, it runs init-container to create empty tyk_analytics.conf file.
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed annotation `traffic.sidecar.istio.io/excludeInboundPorts` and `traffic.sidecar.istio.io/includeInboundPorts`. If Tyk is deployed inside Istio service mesh, you can configure the required an
```suggestion
- Removed annotation `traffic.sidecar.istio.io/excludeInboundPorts` and `traffic.sidecar.istio.io/includeInboundPorts`. If Tyk is deployed inside *Istio service mesh*, you can configure the required annotation using values.yaml file.
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Gateway and Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP*. You can configure external access to a service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.
```
Briefly explain how this benefits users

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Updated the default service type of Gateway and Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP*. You can configure external access to a service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.
```
Briefly explain how this benefits users

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Updated Gateway default image tag to v5.2.3.
- Updated Gateway default image tag to v5.2.3.

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
Is this a field in values.yaml and what are the valid values, true or false to eanable/disable?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the Default service type of Developer Portal service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP*. You can configure external access to a service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.
```
Briefly explain how this benefits users

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Updated seting Dashboard URL in Portal using service discovery.
```suggestion
- Updated setting Dashboard URL in Portal using service discovery.
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Used /live path for liveliness probe and /ready path for readiness probe.
What were the paths before?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Moved the database related variables in the values.yaml outside the section related to the storage of the assets inside enterprise portal.
```suggestion
- Moved the database related variables in the values.yaml outside the section related to the storage of the assets inside enterprise portal. This reduces confusion, facilitating database configuration.
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +##### Updated
In this section replace * bullets with - for consistency

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Removed field `global.bootstrap.devPortal`. You can now set both `global.components.bootstrap` and `tyk-bootstrap.bootstrap.devPortal` to true to enable portal bootstrapping.
Replace * with - for consistency

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `gateway.opentelemetry`.
Is this a field in values.yaml and what are the valid values, true or false to enable/disable?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated default service type of Gateway service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalance
```suggestion
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP*. You can configure external access to a service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.
```
Briefly explain how this benefits users

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Gateway pod listens on port `.gateway.containerPort` instead of `global.servicePorts.gateway`.
Explain what problem this was causing?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove `global.components.dashboard` flag as it was misleading. Adapted gateway to use a gateway-specific flag `gateway.useDashboardAppConfig`. Set `gateway.useDashboardAppConfig` to true if gatewa
```suggestion
- Removed `global.components.dashboard` flag as it was misleading. Adapted gateway to use a gateway-specific flag `gateway.useDashboardAppConfig`. Set `gateway.useDashboardAppConfig` to true if gateway should connect to Dashboard for [app configurations]([https://tyk.io/docs/tyk-oss-gateway/configuration/#use_db_app_configs](https://tyk.io/docs/tyk-oss-gateway/configuration/#use_db_app_configs)).
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Gateway and Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP*. You can configure external access to a service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.
```
Briefly explain how this benefits users

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
see previous comment regarding this

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
Should this be in removed section?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalanc
```suggestion
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP*. You can configure external access to a service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.
```
Briefly explain how this benefits users

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalanc
```suggestion
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP*. You can configure external access to a service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.
```
Briefly explain how this benefits users
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
Should this be in removed section?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Setting up hybrid pump using Kubernetes secret values if `global.remoteControlPlane.useSecretName` is set.
Add explanation of what problem this issue caused and how the fix benefits users.

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
see comment above in other changelog items where this appears

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added In `tyk-dashboard`, a new field (`tykApiHost`) allows configuring a custom service name for Tyk Gateway.
```suggestion
- Added In `tyk-dashboard`, a new field (`tykApiHost`) to allow configuring a custom service name for Tyk Gateway.
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated: Move the database related variables in the values.yaml outside the section related to the storage of the assets inside enterprise portal.
see comment above in changelog where this item appeared

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Changed: User can provide developer portal configurations via secret `tyk-dev-portal.useSecretName` instead of `global.secrets.useSecretName`. This is to make it easier to manage portal and dashboa
use *Update* for consistency and remove semicolons
replace * bullet with - below

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated: Move the database related variables in the values.yaml outside the section related to the storage of the assets inside enterprise portal.
```suggestion
- Updated values.yaml structure so that database related variables are outside the section related to the storage of the assets inside enterprise portal.
```

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
Should this be in removed section

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed support for `tyk-dashboard.dashboard.enableIstioIngress` field in values.yaml.
Why was this config item removed?

2023-12-07 13:22 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed `global.components.dashboard` flag as it was misleading. Adapted gateway to use a gateway-specific flag `tyk-gateway.gateway.useDashboardAppConfig`. Set `tyk-gateway.gateway.useDashboardApp
```suggestion
- Removed `global.components.dashboard` flag as it was misleading. Adapted gateway to use a gateway-specific flag `tyk-gateway.gateway.useDashboardAppConfig`. Set `tyk-gateway.gateway.useDashboardAppConfig` to true if gateway should connect to Dashboard for [app configurations]({{< ref "tyk-oss-gateway/configuration#use_db_app_configs" >}})
```

2023-12-07 13:51 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
Hi @dcs3spp , what it really does is changing the service URL from "{name}.{namespace}.svc.cluster.local" to "{name}.{namespace}.svc" so I think it's a change rather than removal

2023-12-07 22:27 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Gateway and Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort
```suggestion
- Updated the default service type of Gateway, Dashboard, Developer Portal, and Pump from *NodePort* to *ClusterIP* for better security. You can configure external access to a service with your desired method like changing service type to *NodePort*, *LoadBalancer* or configuring *Ingress*.
```

2023-12-07 22:29 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +*
Charts were deprecated in the last release

```suggestion
There are no deprecations in this release. 
```

2023-12-07 22:31 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +      # Type of the span processor to use
@buraksekili could you help to update the values.yaml?

2023-12-07 22:31 UTC, carolwkc commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +      contextPropogation: tracecontext
@buraksekili same as above

2023-12-07 22:32 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Bootstrapping Job do not fail if there is existing ORG found in dashboard storage. If the database has been bootstrapped already, the job will proceed with creating secret with Operator and Develop
The previous behaviour is not considered a bug, but was annoyingly strict.

2023-12-07 22:34 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Gateway and Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP* for better security. You can configure external access to a service with your desired method like changing service type to *NodePort*, *LoadBalancer*, or configuring *Ingress*.
```

2023-12-07 22:35 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
There are a lot of sub-fields under `opentelemetry` as shown in the highlight section

2023-12-07 22:35 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Updated Gateway default image tag to v5.2.3.
```suggestion
- Updated Gateway default image tag to v5.2.3.
```

2023-12-07 22:36 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the Default service type of Developer Portal service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP* for better security. You can configure external access to a service with your desired method like changing service type to *NodePort*, *LoadBalancer*, or configuring *Ingress*.
```

2023-12-07 22:37 UTC, carolwkc commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Used /live path for liveliness probe and /ready path for readiness probe.
```suggestion
* Updated liveliness probe from `/` to `/live` and readiness probe from `/` to `/ready`.
```

2023-12-07 22:38 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Removed field `global.bootstrap.devPortal`. You can now set both `global.components.bootstrap` and `tyk-bootstrap.bootstrap.devPortal` to true to enable portal bootstrapping.
```suggestion
- Removed field `global.bootstrap.devPortal`. You can now set both `global.components.bootstrap` and `tyk-bootstrap.bootstrap.devPortal` to true to enable portal bootstrapping.
```

2023-12-07 22:38 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `gateway.opentelemetry`.
there is a group of configuration available under `gateway.opentelemetry`, as shown in highlights

2023-12-07 22:39 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated default service type of Gateway service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalance
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP* for better security. You can configure external access to a service with your desired method like changing service type to NodePort, LoadBalancer, or configuring Ingress.
```

2023-12-07 22:41 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Gateway pod listens on port `.gateway.containerPort` instead of `global.servicePorts.gateway`.
```suggestion
- Fixed the issue that gateway container port needs to be the same as service port for gateway to work. This change configures Gateway pod listens on port `.gateway.containerPort` instead of `global.servicePorts.gateway`.
```

2023-12-07 22:41 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Gateway and Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort
```suggestion
- Updated the default service type of Gateway and Pump service from *NodePort* to *ClusterIP* for better security. You can configure external access to service with your desired method like changing service type to *NodePort*, *LoadBalancer*, or configuring *Ingress*.
```

2023-12-07 22:42 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Remove .cluster.local from service URL to allow for named cluster support.
see previous comments

2023-12-07 22:42 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
see previous comments

2023-12-07 22:43 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalanc
```suggestion
- Updated the default service type of Pump service from *NodePort* to *ClusterIP* for better security. You can configure external access to service with your desired method like changing service type to *NodePort*, *LoadBalancer*, or configuring *Ingress*.
```

2023-12-07 22:43 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Updated the default service type of Pump service from NodePort to ClusterIP. You can configure external access to service with your desired method like changing service type to NodePort, LoadBalanc
```suggestion
- Updated the default service type of Pump service from *NodePort* to *ClusterIP* for better security. You can configure external access to service with your desired method like changing service type to *NodePort*, *LoadBalancer*, or configuring *Ingress*.
```

2023-12-07 22:46 UTC, carolwkc commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Setting up hybrid pump using Kubernetes secret values if `global.remoteControlPlane.useSecretName` is set.
```suggestion
- Fixed the problem that Hybrid Pump was not setup correctly if remoteControlPlane connection details was set through secret. Setting up hybrid pump using Kubernetes secret values if `global.remoteControlPlane.useSecretName` is set.
```

2023-12-07 22:47 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Changed: User can provide developer portal configurations via secret `tyk-dev-portal.useSecretName` instead of `global.secrets.useSecretName`. This is to make it easier to manage portal and dashboa
```suggestion
- Updated developer portal configurations can be provided via secret `tyk-dev-portal.useSecretName` instead of `global.secrets.useSecretName`. This is to make it easier to manage portal and dashboard configuration separately.
```

2023-12-07 22:49 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed support for `tyk-dashboard.dashboard.enableIstioIngress` field in values.yaml.
```suggestion
- Removed support for `tyk-dashboard.dashboard.enableIstioIngress` field in values.yaml. Users can just set up all required annotations that works with their service mesh in values.yaml.
```

2023-12-07 22:49 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed `global.components.dashboard` flag as it was misleading. Adapted gateway to use a gateway-specific flag `tyk-gateway.gateway.useDashboardAppConfig`. Set `tyk-gateway.gateway.useDashboardApp
GitHub doesn't support the ref tag

2023-12-07 22:50 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
```suggestion
- Added OpenTelemetry support under `tyk-gateway.gateway.opentelemetry`.
```

2023-12-07 22:51 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `gateway.opentelemetry`.
```suggestion
- Added OpenTelemetry support under `gateway.opentelemetry`.
```

2023-12-07 22:51 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
```suggestion
- Added OpenTelemetry support under `tyk-gateway.gateway.opentelemetry`.
```

2023-12-07 22:51 UTC, carolwkc commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Added OpenTelemetry support at `tyk-gateway.gateway.opentelemetry`.
```suggestion
- Added OpenTelemetry support under `tyk-gateway.gateway.opentelemetry`.  
```

2023-12-08 09:31 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +      # Type of the span processor to use
Valid values for spanProcessorType are “simple” or “batch”.
```suggestion
      # Type of the span processor to use. Valid values are “simple” or “batch”.
```

2023-12-08 09:32 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +      contextPropogation: tracecontext
@buraksekili and typo in "contextPropogation" ?

2023-12-08 09:33 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +      contextPropogation: tracecontext
i guess we also have typo here. it should be `Propagation` instead of `Propogation`. I will address this on the tyk-charts as well.

In the meantime, the valid values for context propagator are "tracecontext" and "b3"

2023-12-08 10:45 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +      contextPropogation: tracecontext
```suggestion
      # Type of the context propagator to use. Valid values are "tracecontext" and "b3".
      contextPropagation: tracecontext
```

2023-12-08 10:46 UTC, buraksekili commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +      contextPropogation: tracecontext
addressed in 31e38c4aa53939cba18df6ac04796e753ca5453f

2023-12-08 12:26 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +- Removed `global.components.dashboard` flag as it was misleading. Adapted gateway to use a gateway-specific flag `tyk-gateway.gateway.useDashboardAppConfig`. Set `tyk-gateway.gateway.useDashboardApp
> GitHub doesn't support the ref tag

Yep forgot we are GitHub for Hem Charts release notes

2023-12-08 12:26 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Updated liveliness probe from `/` to `/live` and readiness probe from `/` to `/ready`.
```suggestion
- Updated liveliness probe from `/` to `/live` and readiness probe from `/` to `/ready`.
```

2023-12-08 12:27 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* Updated default storage type in values.yaml from `fs` to `db`. The new default option does not require additional configuration to work.
```suggestion
- Updated default storage type in values.yaml from `fs` to `db`. The new default option does not require additional configuration to work.
```

2023-12-08 12:27 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-charts-1.2.0-release-notes.md
> +* User can provide developer portal configurations via secret `useSecretName` instead of `global.secrets.useSecretName`. This is to make it easier to manage portal and dashboard configuration separat
```suggestion
- User can provide developer portal configurations via secret `useSecretName` instead of `global.secrets.useSecretName`. This is to make it easier to manage portal and dashboard configuration separately.
```

2023-12-08 12:31 UTC, dcs3spp approved these changes
Thanks @caroltyk PR LGTM

2023-12-08 16:31 UTC, dcs3spp commented
closing this PR, since it existed for purposes of review. The release notes are on GHub tyk-charts

2023-12-08 16:31 UTC, closed without merging