[DX-810] - Refactor LTS Page
TykTechnologies/tyk-docs-hugo pull request #3731
Opened 2023-12-11 17:10 UTC by dcs3spp

[DX-810](https://tyktech.atlassian.net/browse/DX-810)

[preview](https://deploy-preview-3731--tyk-docs.netlify.app/docs/nightly/frequently-asked-questions/long-term-support-releases/)

Initial content from LTS miro board

[DX-810]: https://tyktech.atlassian.net/browse/DX-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-19 17:12 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +date: 2023-12-11
@Keithwachira do we keep this? or do we use GH date?

2023-12-19 17:13 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +## Why Customers Love Long Term Support (LTS)?
Are we sure about this tone @dcs3spp ?

2023-12-19 17:17 UTC, yurisasuke commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +date: 2023-12-11
> @Keithwachira do we keep this? or do we use GH date?

@letzya we can still keep it although we use the github date as the default 
we have this line in the config `lastmod = ["lastmod", ":git",':fileModTime', "date", "publishDate"]`
that check if the date can be gotten from git if not it falls back to date parameter from the front matter

2023-12-19 23:56 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +We will release a new LTS Gateway version every 12 months which is upgraded to latest Golang version by default.
`We will release` ? why not `we release`. The future tense suggests it's a new policy but we don't say it's now

2023-12-19 23:59 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +We will release a new LTS Gateway version every 12 months which is upgraded to latest Golang version by default.
```suggestion
We release a new Gateway LTS version every 12 months which includes the latest Golang version.
```

2023-12-20 00:00 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Let's just remind ourselves of the benefits to a 12 month LTS window:
Again, not sure about this ToV

2023-12-20 00:04 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Let's just remind ourselves of the benefits to a 12 month LTS window:
```suggestion
The advantages of a 12-month Long-Term Support (LTS) window include:"
```

2023-12-20 00:05 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +If you have a requirement to run on a non supported version for longer than the LTS policy, we may be able to help - but this would require a discussion with your Account Manager.
```suggestion
If you need to operate on a version beyond the LTS policy, there might be options available. Please connect with your Account Manager for a discussion."
```

2023-12-20 00:08 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +## Why Customers Love Long Term Support (LTS)?
```suggestion
## What Makes Long-Term Support (LTS) So Valuable to Our Customers?
```

2023-12-20 00:13 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +As we release regularly, there will of course be other release issues throughout the year. These are NOT long term support releases. These releases offer new capability and are designed to appeal to
```suggestion
While we maintain a regular release schedule, it's important to clarify that these releases do not fall under the Long-Term Support (LTS) category. They introduce new capabilities, appealing to teams seeking the latest features upon release. However, these specific features become part of the subsequent LTS release.
```

2023-12-20 00:14 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +These releases are supported, but the support windows is small - they are supported only until the next release comes out and supersedes it. So if you want stabilty and regular patching then LTS rele
```suggestion
Although these releases receive support, it's essential to note their limited support duration, extending only until the arrival of the subsequent release that supersedes them. For users prioritizing stability and consistent patching, the LTS releases offer a more suitable choice.
```

2023-12-20 00:17 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +6. Breaking public function calls.
isn't #6 an example of #1?

2023-12-20 00:19 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Our default setting is NOT to introduce breaking changes, but sometimes it is necessary. If we do introduce breaking changes we have a collective choice to make; if we document the breaking change we
Not sure I get it. Is it ok to have a small breaking change in a minor? according to semver?

2023-12-20 00:20 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +According the the **Semantic Versioning** specification, a **MINOR** version is incremented when you add functionality in a backward compatible manner. In other words, if Tyk make changes to your sof
best to add a link to Semantic Versioning

2023-12-20 00:21 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +A patch, sometimes just called a fix, is a small piece of software that's used to correct a problem, usually called a bug, with an operating system or software program.
```suggestion
A patch, sometimes just called a fix, is a small piece of code that's used to correct a problem, usually called a bug, with an operating system or software program.
```

2023-12-20 00:22 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Patches are software and Operating System (OS) updates that address security vulnerabilities within a program or product. Tyk may choose to release updates to fix performance bugs, as well as to prov
Apologies, I don't understand the structure and purpose of the sentence - 
> Patches are software and Operating System (OS) updates that address security vulnerabilities within a program or product.

2023-12-20 00:28 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +1. What component versions might you need to leverage the very latest Tyk experience across the entire stack.
```suggestion
1. What component versions would you require to fully utilise the latest Tyk experience across the entire stack
```

2023-12-20 00:30 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +According the the **Semantic Versioning** specification, a **MINOR** version is incremented when you add functionality in a backward compatible manner. In other words, if Tyk make changes to your sof
```suggestion
According the the *Semantic Versioning* specification, a MINOR version is incremented when you add functionality in a backward compatible manner. In other words, if Tyk make changes to your software that do not break any existing functionality, you can increment the MINOR version number. For example, if you add new features or capabilities to your software without changing any existing functionality, you can increase the MINOR version number.
```

2023-12-20 00:32 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +The above compatibility matrix table will be included in future [release notes]({{< ref "product-stack/tyk-gateway/release-notes/overview" >}}) for Gateway for releases 5.3+. Furthermore, the release
```suggestion
The compatibility matrix table shown above will be part of upcoming [Gateway release notes]({{< ref "product-stack/tyk-gateway/release-notes/overview" >}}) for versions 5.3 and beyond. Additionally, these release notes will list tested third-party dependencies like *PostgreSQL, MongoDB, Redis*, and more."
```

2023-12-20 00:33 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Head [here]({{< ref "upgrading-tyk" >}}) to find them!
"here" is not good for SEO. it needs to be part of a sentence of the crawler can understand

2023-12-20 00:39 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +And don't forgeth, our brilliant Customer Success Teams and Account Managers are here to assist you with any issues - pleases refer to your SLA on the specifics of how we can help!
```suggestion
Please note, our dedicated Customer Success Teams and Account Managers are here to assist you with any concerns. For more details, check our [official Support Level Agreement]({{<ref "frequently-asked-questions/sla-policies" >}}) policy. For specific details related to your support agreement, please refer to your copy of the Service Level Agreement (SLA)."
```

2023-12-20 00:39 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +And don't forgeth, our brilliant Customer Success Teams and Account Managers are here to assist you with any issues - pleases refer to your SLA on the specifics of how we can help!
Not sure if it's correct. @vverbani can you please check?

2023-12-20 00:41 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Do you want to know when our next LTS is? And what might be in it? Subscribe to our mailing list [here]()!
```suggestion
To receive updates on our upcoming Long-Term Support (LTS) release schedule and its contents, feel free to subscribe to our [mailing list]()
```

2023-12-20 00:44 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +## Support Arrangements For Other Tyk Components
we didn't explain for which components the previous content was so this title is not so clear imho

2023-12-20 00:45 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +We strive to avoid any long term support arrangements for our Enterprise Portal. We run a regular 6 week release cadence which delivers new capability, extension of existing capability and bug fixes.
"We strive to avoid any long-term support arrangements" - we can't write this without explaining especially after we explained the opposite beforehand

2023-12-20 00:47 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Occasionally, we may see a need to issue a critical fix if there is a systems down time or a criticial security defect. Here would release this as as soon as physically possible and the semantic vers
should we improve this paragraph? not sure it's read well @dcs3spp

2023-12-20 00:49 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +The only exception to this policy is if we every need to release a breaking change. This would mean that we have to release a new major version (i.e. releasing version 2.0). In this exceptional circu
```suggestion
The only exception to this policy is if we ever need to release a breaking change. This would mean that we have to release a new major version (i.e. releasing version 2.0). In this exceptional circumstance we would support both the old major version and the new one concurrently for six months - please note that the old version only gets supported in terms of critical fixes, not new functionality. After six months, the previous major version falls out of support.
```

2023-12-20 00:50 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +The only exception to this policy is if we every need to release a breaking change. This would mean that we have to release a new major version (i.e. releasing version 2.0). In this exceptional circu
are we sure we can write "exceptional circumstance" at this stage?

2023-12-20 00:52 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +We strive to avoid any long term support arrangements for our Enterprise Portal. We run a regular 6 week release cadence which delivers new capability, extension of existing capability and bug fixes.
what does this mean `so in effect the entie Enterprise Portal is supported.`

2023-12-20 00:54 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +If you are using the Enterprise Portal on Tyk Cloud, we recommend you use the latest version at all times and we auto upgrade to that version on TYk Cloud. When a new release is launched, older versi
I don't quite understand this. "we recommend you use the latest" but we auto upgrade? is it because the user can manually downgrade after we upgraded them automatically?

2023-12-20 00:55 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +#### Other Components
```suggestion
#### Tyk Pump, Tyk Identity Broker, MDCB and Tyk Operator
```

2023-12-20 00:58 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Minor updates to Tyk Pump, Tyk Identity Broker (TIB), MDCB and Operator are deployable quickly with low risk and no breaking changes. Tyk will support the latest major.minor version (e.g. Pump 1.7) u
```suggestion
Minor updates to Tyk Pump, Tyk Identity Broker (TIB), MDCB and Tyk Operator are deployable swiftly with minimal risk and no breaking changes. Tyk will provide support for the latest *major.minor* version (e.g. Tyk Pump v1.7) until the subsequent *major.minor* version (e.g. Tyk Pump v1.8) is released, at which point support for the newer version will commence."
```

2023-12-20 01:05 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +To help assure backward compatibility we ensure that each version of Pump and other components we release works with the Gateway and Dashboard versions which are under Long Term Support (LTS) at that
```suggestion
To ensure backward compatibility, we confirm that each Pump release and other components are compatible with the Long-Term Support (LTS) versions of the Gateway and Dashboard. For instance, *Tyk Pump* v1.7 undergoes validation to ensure compatibility with release v4 of *Tyk Gateway* and *Tyk Dashboard*. This alignment persists under the LTS model. Following the semantic versioning convention, if there's a need for a fix in the *Tyk Pump* version, it will be labelled as a patch version (e.g., v1.7.1).
```

2024-01-09 14:18 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +We strive to avoid any long term support arrangements for our Enterprise Portal. We run a regular 6 week release cadence which delivers new capability, extension of existing capability and bug fixes.
```suggested
We strive to avoid any long term support arrangements for our Enterprise Portal. We run a regular 6 week release cadence which delivers new capability, extension of existing capability and bug fixes. Our policy is that we aim to avoid any breaking changes, so in effect the entire Enterprise Portal is supported. Here we'd increment out version as a minor version - 1.3.0, 1.4.0, 1.5.0 etc.
```

2024-01-09 16:19 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Occasionally, we may see a need to issue a critical fix if there is a systems down time or a criticial security defect. Here would release this as as soon as physically possible and the semantic vers
@letzya 

```suggestion
We strive to avoid any long term support arrangements for our Enterprise Portal. We run a regular 6 week release cadence to deliver new features, extend existing features and address bug fixes. Our policy is that we aim to avoid any breaking changes, so in effect the entire Enterprise Portal is supported. In these cases our version would be released as a minor version, e.g. 1.3.0, 1.4.0, 1.5.0 etc.

Critical fixes and security defects would be fixed and released urgently as a patch release, e.g. 1.3.1, 1.4.1, 1.5.1 etc.
```

2024-01-09 16:20 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Occasionally, we may see a need to issue a critical fix if there is a systems down time or a criticial security defect. Here would release this as as soon as physically possible and the semantic vers
@letzya revised paragraph received from @allaneyles via slack message

```suggestion
We support our release cadence with a critical fix process. This is invoked when a severity one incident is declared, usually defined as systems down time, no workaround or a critical security issue.

Our critical fix process commits to release as soon as possible and we issue a standalone fix outside of our normal cadence.
```

2024-01-09 16:35 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +According the the **Semantic Versioning** specification, a **MINOR** version is incremented when you add functionality in a backward compatible manner. In other words, if Tyk make changes to your sof
done

2024-01-10 12:43 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +If you are using the Enterprise Portal on Tyk Cloud, we recommend you use the latest version at all times and we auto upgrade to that version on TYk Cloud. When a new release is launched, older versi
@letzya revised comment from @allaneyles via slack message
```suggestion
If you are using Enterprise Portal on Tyk Cloud, we keep you safe, secure and up to date with the latest features by auto upgrading you to the latest version. When a new release is launched, older versions are immediately deprecated. If a customer wants to use a previous version, this is possible via rollback. However, if an issue arises on an older version our advice would be to upgrade to the latest version.
```

2024-01-10 16:12 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +6. Breaking public function calls.
Following slack message conversation with @allaneyles have removed list item 6 and amended list item 1 as follows:

_Breaking changes to Tyk Gateway API, Tyk Dashboard API or Tyk custom plugins interfaces. Tyk Gateway and Tyk Dashboard APIs include not just the endpoints, but also return error codes and messages, in addition to logging details. In summary, breaking changes involves anything where a user interacts with a Tyk product and might have to make changes to maintain functionality in response to a change we implement._

2024-01-10 23:40 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +## Support Arrangements For Other Tyk Components
@dcs3spp can you please help to rephrase the title? in the paragraph below we explain that "other" means "not tyk gw or tyk dashboard" but i think the title should be clearer

2024-01-10 23:43 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Occasionally, we may see a need to issue a critical fix if there is a systems down time or a criticial security defect. Here would release this as as soon as physically possible and the semantic vers
@dcs3spp is this Allan's version?

2024-01-10 23:49 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +If you are using the Enterprise Portal on Tyk Cloud, we recommend you use the latest version at all times and we auto upgrade to that version on TYk Cloud. When a new release is launched, older versi
```suggestion
I don't see much wrong with the sentence. But we can change to 'If you are using Enterprise Portal on Tyk Cloud, we keep you safe, secure, and up to date with the latest features by auto-upgrading you to the latest version. When a new release is launched, older versions are immediately deprecated. If a customer wants to use a previous version, this is possible via rollback; but if an issue arises on an older version our advice would be simply to upgrade to the latest version.
```

2024-01-10 23:49 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +If you are using the Enterprise Portal on Tyk Cloud, we recommend you use the latest version at all times and we auto upgrade to that version on TYk Cloud. When a new release is launched, older versi
much better

2024-01-10 23:58 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +3. Breaking plugin compiler for customer Go plugins after plugins have been recompiled.
```suggestion
3. Breaking changes in the Go plugin compiler for users' Go plugins after plugins have been recompiled.
```

2024-01-10 23:59 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +4. Crypto deprecations.
can we move this next to the other deprecation item #2

2024-01-11 10:18 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +4. Crypto deprecations.
What is the other deprecation item and does it relate to this PR?

2024-01-11 10:29 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +4. Crypto deprecations.
i wrote it under #4 and asked to put it near #2

2024-01-11 13:03 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +## Support Arrangements For Other Tyk Components
@letzya I've rephrased the section title to:

_LTS Support Policy For Components Other Than Tyk Gateway and Tyk Dashboard_

2024-01-11 13:10 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +4. Crypto deprecations.
Updated breaking changes list as follows:

_1. Breaking changes to Tyk APIs, including Tyk Gateway API, Tyk Dashboard API, MDCB and Tyk EDP and any other component which exposes APIs. Changes include not just the endpoints, but also behaviour and functionality, schemas, input parameters, return error codes and messages. The APIs are documented and published as an OpenAPI Spec document.
2. Breaking changes to Tyk custom plugins interfaces, breaking plugin compiler for customer Go plugins after plugins have been recompiled.
3. Breaking changes in the config files in all Tyk components, fields in the config files, environment variables used by Tyk components, APIs (function calls) of Tyk middleware, Go template interface.
4. Breaking changes in the Tyk Gateway and Tyk Dashboard log messages.
5. Deprecation of existing functionality or engines that breaks a key business process.
6. Crypto deprecations.
7. Changes to common names in certfiicates._

2024-01-11 14:35 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Our default setting is NOT to introduce breaking changes, but sometimes it is necessary. If we do introduce breaking changes we have a collective choice to make; if we document the breaking change we
Updated last paragraph of [Major Version](https://deploy-preview-3731--tyk-docs.netlify.app/docs/nightly/frequently-asked-questions/long-term-support-releases/#major-version) section to read:

_In summary, breaking changes involves anything with which a user interacts with a Tyk product and might have to make changes to maintain functionality in response to a change we implement. Subsequently, breaking changes are introduced in a major version, in accordance with the *Semantic Versioning* [specification](https://semver.org/)._

Also mentioned in slack conversation with Allan

2024-01-11 14:56 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Our default setting is NOT to introduce breaking changes, but sometimes it is necessary. If we do introduce breaking changes we have a collective choice to make; if we document the breaking change we
sure, are you going to amend the exisiting text?

2024-01-11 17:53 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Our default setting is NOT to introduce breaking changes, but sometimes it is necessary. If we do introduce breaking changes we have a collective choice to make; if we document the breaking change we
Done

2024-01-11 18:33 UTC, vverbani commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +And don't forgeth, our brilliant Customer Success Teams and Account Managers are here to assist you with any issues - pleases refer to your SLA on the specifics of how we can help!
This looks correct @letzya

2024-01-16 18:24 UTC, letzya requested changes
Waiting for the compatibility matrix to resolve.

2024-01-18 22:18 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +1. What component versions would you require to fully utilise the latest Tyk experience across the entire stack
```suggestion
1. **Recommended releases** - To ensure you get the most out of the latest Tyk experience, we'll provide information on which versions of different components across the entire stack you need.
```

2024-01-18 22:19 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +2. What components and versions remain backwards compatible with the new Gateway version.
```suggestion
2. **Backwards Compatibility** - We'll provide information on what components and versions remain backwards compatible with the new Tyk Dashboard and Tyk Gateway versions.
```

2024-01-19 10:45 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +| Gateway Version | Recommended Compatibility | Backwards Compatibility |
```suggestion
| Gateway Version | Recommended releases | Backwards Compatibility |
```

2024-01-19 10:48 UTC, letzya approved these changes

2024-01-19 16:26 UTC, andyo-tyk requested changes
Typos and a few suggestions.

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +1. It allows us to keep pace with Golang versions and other key dependency upgrades, which kees both our customers and your customers safe (low CVE).
```suggestion
1. It allows us to keep pace with Golang versions and other key dependency upgrades, which keeps both our customers and your customers safe (low CVE).
```

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +We offer a 24 month long term support offering for our Gateway LTS version. For the first 12 months we offer **full support** which means that we will fix every 7 weeks. After this 12 months period i
```suggestion
We offer a 24 month long term support offering for our Gateway LTS version. For the first 12 months we offer **full support** which means that we will fix every 7 weeks. After this 12 month period is up, we will revert to **maintenance support** for a further 12 months offering critical fixes and critical security patching only, with the cadence being on an 'as needed' basis.
```

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +In case there's a need to operate on a version beyond the established LTS policy, potential assistance may be available. However, this requires a discussion with your designated Account Manager."
```suggestion
In case there's a need to operate on a version beyond the established LTS policy, potential assistance may be available. However, this requires a discussion with your designated Account Manager.
```

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +| Version | Full Support Window | Maintenance Support Window | Completely Unsupported From |
"Completely unsupported" has a feeling of danger to it - how about "End of Life" or "Support Ends"

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +While we maintain a regular release schedule, it's important to clarify that these releases do not fall under the Long-Term Support (LTS) category. They introduce new capabilities, appealing to teams
```suggestion
While we maintain a regular release schedule, it's important to clarify that these releases do not fall under the Long Term Support (LTS) category. They introduce new capabilities, appealing to teams seeking the latest features upon release. However, these specific features become part of the subsequent LTS release.
```

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +As part of the release for the new Gateway LTS version we will commit to show everyone 2 compatibility dimensions:
```suggestion
As part of the release for the new Gateway LTS version we will commit to show everyone two compatibility dimensions:
```

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +The Tyk product is comprised of various components, such as Tyk Sync, Tyk Pump and Tyk Operator. Some of these components are more standalone than others, which allows us to operate different release
Wouldn't it be simpler just to say "we do not have a long term support policy"?

"Striving to avoid" means that, while we aim to avoid this, sometimes we might fail... which would mean (incorrectly) that there ARE long term support versions from time to time...

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +We strive to avoid any long term support arrangements for our Enterprise Portal. We run a regular 6 week release cadence which delivers new capability, extension of existing capability and bug fixes.
Same here for "strive to avoid" - I don't think it makes sense.

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +The only exception to this policy is if we ever need to release a breaking change. This would mean that we have to release a new major version (i.e. releasing version 2.0). In this exceptional circum
```suggestion
The only exception to this policy is if we ever need to release a breaking change. This would mean that we have to release a new major version (e.g. version 2.0). In this exceptional circumstance we would support both the old major version and the new one concurrently for six months - please note that the old version would only be supported in terms of critical fixes, not new functionality. After six months, the previous major version would fall out of support.
```

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +Minor updates to Tyk Pump, Tyk Identity Broker (TIB), MDCB and Tyk Operator are deployable swiftly with minimal risk and no breaking changes. Tyk will provide support for the latest *major.minor* ver
```suggestion
Minor updates to Tyk Pump, Tyk Identity Broker (TIB), MDCB and Tyk Operator are deployable swiftly with minimal risk and no breaking changes. Tyk will provide support for the latest *major.minor* version (e.g. Tyk Pump v1.7) until the subsequent *major.minor* version (e.g. Tyk Pump v1.8) is released, at which point support for the newer version will commence.
```

2024-01-19 16:26 UTC, andyo-tyk commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +To ensure backward compatibility, we confirm that each Pump release and other components are compatible with the Long-Term Support (LTS) versions of the Gateway and Dashboard. For instance, *Tyk Pump
```suggestion
To ensure backward compatibility, we confirm that each Pump release and other components are compatible with the Long Term Support (LTS) versions of the Gateway and Dashboard. For instance, *Tyk Pump* v1.8 underwent validation to ensure compatibility with release v5 of *Tyk Gateway* and *Tyk Dashboard*. This alignment persists under the LTS model. Following the semantic versioning convention, if there's a need for a fix in the *Tyk Pump* version, it would be labelled as a patch version (e.g. v1.8.1).
```

2024-01-24 17:08 UTC, letzya commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +The Tyk product is comprised of various components, such as Tyk Sync, Tyk Pump and Tyk Operator. Some of these components are more standalone than others, which allows us to operate different release
@allaneyles ?

2024-02-02 17:03 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +The Tyk product is comprised of various components, such as Tyk Sync, Tyk Pump and Tyk Operator. Some of these components are more standalone than others, which allows us to operate different release
@letzya @andyo-tyk

@allaneyles Has updated the support for [other Tyk components ](https://deploy-preview-4051--tyk-docs.netlify.app/docs/nightly/frequently-asked-questions/long-term-support-releases/#support-arrangements-for-other-tyk-components)

2024-02-02 17:04 UTC, dcs3spp commented on tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
> +We strive to avoid any long term support arrangements for our Enterprise Portal. We run a regular 6 week release cadence which delivers new capability, extension of existing capability and bug fixes.
@andyo-tyk

@allaneyles Has updated the support for [other Tyk components ](https://deploy-preview-4051--tyk-docs.netlify.app/docs/nightly/frequently-asked-questions/long-term-support-releases/#support-arrangements-for-other-tyk-components) Enterprise portal section is now removed.

2024-02-06 14:41 UTC, allaneyles commented
@dcs3spp addressing Chris A's comment. We should simply remove this text as its duplicative:

_We offer a 24 month long term support offering for our Gateway LTS version. For the first 12 months we offer full support which means that we will issue patches and updates on a 7-week schedule. After this 12 month period is up, we will revert to maintenance support for a further 12 months offering critical fixes and critical security patching only, with the cadence being on an 'as needed' basis._

2024-02-09 11:18 UTC, dcs3spp commented
> @dcs3spp addressing Chris A's comment. We should simply remove this text as its duplicative:
> 
> _We offer a 24 month long term support offering for our Gateway LTS version. For the first 12 months we offer full support which means that we will issue patches and updates on a 7-week schedule. After this 12 month period is up, we will revert to maintenance support for a further 12 months offering critical fixes and critical security patching only, with the cadence being on an 'as needed' basis._

Thanks @allaneyles I have removed the paragraph and preview is available [here](https://deploy-preview-4051--tyk-docs.netlify.app/docs/nightly/frequently-asked-questions/long-term-support-releases/)

2024-03-14 16:23 UTC, dcs3spp commented
Closing, this has been released in this [PR](https://github.com/TykTechnologies/tyk-docs/pull/4258) for ticket [DX-1189](https://tyktech.atlassian.net/browse/DX-1189). Released in separate PR as a precaution due to merge conflict encountered in this PR requiring manual merge

2024-03-14 16:23 UTC, closed without merging