[DX-890] sync 1.4 release notes
TykTechnologies/tyk-docs-hugo pull request #3732
Opened 2023-12-12 09:22 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

Add Release notes for Sync 1.4.2

---

### Preview Link

<br>

[preview](https://deploy-preview-3732--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-sync/release-notes/sync-1.4/)

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-12-12 12:06 UTC, dcs3spp requested changes
Thanks for submitting the first release notes for tyk-sync 1.4 @caroltyk.

I have committed some additional changes to the branch:
- OSS link added. I have added link to tagged release for tyk-sync 1.4.1 in [Downloads](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Downloads) section of release note. 
- Made some formatting updates to include expandable change-log items
- Added [release notes footer](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Release-Notes-Footer) section

Are there any[ 3rd party dependencies](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#3rd-Party-Dependencies-%26-Tools) for Tyk-sync?

If the changelogs are small, can we add the changelogs for v.1.4.1 & v1.4.0?

2023-12-12 14:01 UTC, tbuchaillot commented
> Thanks for submitting the first release notes for tyk-sync 1.4 @caroltyk.
> 
> I have committed some additional changes to the branch:
> 
> * OSS link added. I have added link to tagged release for tyk-sync 1.4.1 in [Downloads](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Downloads) section of release note.
> * Made some formatting updates to include expandable change-log items
> * Added [release notes footer](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Release-Notes-Footer) section
> 
> Are there any[ 3rd party dependencies](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#3rd-Party-Dependencies-%26-Tools) for Tyk-sync?
> 
> If the changelogs are small, can we add the changelogs for v.1.4.1 & v1.4.0?

@dcs3spp the only dependency for Sync is Go 1.19 if you build it yourself. If you are using the docker image, there is no dependency :)

2023-12-20 21:01 UTC, letzya commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +<summary>API definitions supported up to Tyk Gateway v5.2.3 </summary>
@caroltyk can we possiblly adjust this to fit the slightly improved [template](https://github.com/TykTechnologies/tyk-docs/blob/3c5921c1a90e709282301451f5512474062ab1a6/tyk-docs/assets/others/release-notes-template.md) ?

2023-12-20 21:04 UTC, letzya commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +
Since all the previous releases are in GH, can we please add a title at the bottom `Tyk Sync v1.3 and earlier can we found in this link...`?

2023-12-20 21:04 UTC, letzya commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +title: Sync v1.4
```suggestion
title: Tyk Sync v1.4
```

2023-12-20 21:05 UTC, letzya commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +menu:
```suggestion
```

2023-12-20 21:05 UTC, letzya commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +  main:
```suggestion```

2023-12-20 21:05 UTC, letzya commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +    parent: "Release Notes"
```suggestion
```

2023-12-20 21:06 UTC, letzya commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +weight: 300
```suggestion
```

2023-12-20 21:07 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          - title: "Sync v1.4"
```suggestion
          - title: "Tyk Sync v1.4"
```

2023-12-21 12:21 UTC, letzya commented
@caroltyk there was a conflict which I fixed for you in the PR

2024-01-04 21:36 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +<summary>API definitions supported up to Tyk Gateway v5.2.3 </summary>
sorry I don't get what's the difference?

2024-01-04 21:38 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +
Updated

2024-01-09 12:07 UTC, dcs3spp approved these changes

2024-01-09 12:08 UTC, merged

2024-01-09 12:08 UTC, dcs3spp commented
/release to release-5.2

2024-01-09 12:08 UTC, dcs3spp commented
/release to release-5.1