[DX-906]prevent 404 in version by creating version selector dynamically
TykTechnologies/tyk-docs-hugo pull request #3745
Opened 2023-12-14 07:27 UTC by yurisasuke

[DX-906]

[DX-906]: https://tyktech.atlassian.net/browse/DX-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-14 15:10 UTC, dcs3spp requested changes
Hi @Keithwachira PR LTGM. I have made some minor suggestions

2023-12-14 15:10 UTC, dcs3spp commented on scripts/page_available_since.py
> +# print(get_urls("latest_sitemap.xml"))
do we need to keep the comment?

2023-12-14 15:10 UTC, dcs3spp commented on scripts/page_available_since.py
> +            raise Exception("unable to fetch the sitemap")
does `raise_for_status` do this?

2023-12-14 15:10 UTC, dcs3spp commented on scripts/page_available_since.py
> +def replace_base_url(url: str):
```suggestion
def replace_base_url(url: str) -> str:
```

2023-12-14 15:10 UTC, dcs3spp commented on scripts/page_available_since.py
> +def get_urls(content: str):
```suggestion
def get_urls(content: str) -> list:
```

2023-12-14 15:10 UTC, dcs3spp commented on scripts/page_available_since.py
> +def process_and_write_to_file():
```suggestion
def process_and_write_to_file() -> None:
```

2023-12-14 15:10 UTC, dcs3spp commented on scripts/page_available_since.py
> +def get_site_maps():
```suggestion
def get_site_maps() -> dict:
```

2024-01-22 08:51 UTC, yurisasuke commented
replaced by https://github.com/TykTechnologies/tyk-docs/pull/3989

2024-01-22 08:51 UTC, closed without merging