Release note draft 5.2.5
TykTechnologies/tyk-docs-hugo pull request #3805
Opened 2023-12-19 13:56 UTC by andyo-tyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

2023-12-19 13:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> +##### Release Date 7 Dec 2023
```suggestion
##### Release Date 19 Dec 2023
```

2023-12-19 14:22 UTC, dcs3spp requested changes
PR LGTM. Requested minor suggestion to make changelog fix clearer

2023-12-19 14:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + Fixed an issue where custom keys over 24 characters in length were deleted from the Data Plane Redis on key update in distributed (MDCB) setups.
```suggestion
Fixed an issue where custom keys over 24 characters in length were deleted from the Data Plane Redis when a key was updated in distributed (MDCB) setups.
```

2023-12-19 14:25 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + Fixed an issue where custom keys over 24 characters in length were deleted from the Data Plane Redis on key update in distributed (MDCB) setups.
"key update" is an action/signal from MDCB. Please check this proposed change with @tbuchaillot or @sredxny

2023-12-19 14:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + Fixed an issue where custom keys over 24 characters in length were deleted from the Data Plane Redis on key update in distributed (MDCB) setups.
@tbuchaillot @sredxny ?

2023-12-19 15:28 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
> + Fixed an issue where custom keys over 24 characters in length were deleted from the Data Plane Redis on key update in distributed (MDCB) setups.
looks good to me!

2023-12-19 15:33 UTC, dcs3spp approved these changes

2023-12-19 15:33 UTC, dcs3spp commented
Before merging and releasing this need to add links to docker images for Gateway and Dashboard

2023-12-20 14:30 UTC, merged

2023-12-20 14:30 UTC, dcs3spp commented
/release to release-5.2