move configuration to env var folder and config docs to configuration…
TykTechnologies/tyk-docs-hugo pull request #3807
Opened 2023-12-19 22:54 UTC by letzya

… folder

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2023-12-19 23:12 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
>  date: 2022-02-08
@slega @dcs3spp  is this an auto-gen file ?

2023-12-20 11:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
>  date: 2022-02-08
I think it is manually updated @slega?

2023-12-20 12:00 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
>  date: 2022-02-08
Asking since we need to remove the first H2 heading, since it looks odd with the title and repetitive.
Also, in other config pages we use H3 for the titles of the fields so they'd show up in the right side nav

2023-12-29 10:10 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          show: True
```suggestion
          show: True
```

2024-01-04 13:08 UTC, dcs3spp approved these changes
PR LGTM. Will merge and release after review

2024-01-04 17:47 UTC, slega commented
I don't think this PR makes the menu titles in the EDP section self-consistent. At the moment, the menu titles are verbs because they form a user journey:
- Deploy
- Get started
- Manage users
- Manage APIs
- Customize look and feel

This PR makes it inconsistent: some titles are verbs and some are nouns which makes the menu look inconsistent. E.g.:
- Deploy -> verb, part of the user journey.
- Environment variables -> noun, detached from the user journey.

Also, the environment variables section is placed in the Deploy section because it's a part of the deployment journey. In other words, to deploy the portal a user needs first to create the config file or to specify the env vars. Hence, the configuration step preceding the deployment. If we place the configuration after the deployment step, then a user will have to navigate to the deployment section, then to the env vars and then back to the deployment so at least one additional jump.

To make it consistent, IMO the menu either needs to be expressed in terms of user journey or in some other consistent structure e.g.:
- Deploy
  - Configure
- Do something else

or 

- Deployment
- Configuration
- User management
- ...

2024-01-04 17:55 UTC, slega requested changes
I don't think this PR makes the menu titles in the EDP section self-consistent. At the moment, the menu titles are verbs because they form a user journey:
- Deploy
- Get started
- Manage users
- Manage APIs
- Customize look and feel

This PR makes it inconsistent: some titles are verbs and some are nouns which makes the menu look inconsistent. E.g.:
- Deploy -> verb, part of the user journey.
- Environment variables -> noun, detached from the user journey.

Also, the environment variables section is placed in the Deploy section because it's a part of the deployment journey. In other words, to deploy the portal a user needs first to create the config file or to specify the env vars. Hence, the configuration step preceding the deployment. If we place the configuration after the deployment step, then a user will have to navigate to the deployment section, then to the env vars and then back to the deployment so at least one additional jump.

To make it consistent, IMO the menu either needs to be expressed in terms of user journey or in some other consistent structure e.g.:
- Deploy
  - Configure
- Do something else

or 

- Deployment
- Configuration
- User management
- ...

2024-01-04 17:55 UTC, slega commented on tyk-docs/data/menu.yaml
> +          - title: "Content management"
Theme customization is not content management. Content management is for creating new pages and new content. This section is focused on the visual customization of the portal's theme, not on creating new content. Please use "Visual appearance customisation" title instead.

2024-01-04 17:55 UTC, slega commented on tyk-docs/data/menu.yaml
> +              path: /tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations
The User Management and API management are not configurations. A configuration IMO is something that is done once e.g. selecting a theme file storage or setting up SSO. The User Management and the API Management are consistent and frequently repeated **operational** processes. These sections don't describe configurations, they describe how to establish an operational process and are major value pillars. Hence, they are not configurations and should be place in a separate menu items.

2024-01-04 19:31 UTC, letzya commented
Deploy and get started should be in https://deploy-preview-3807--tyk-docs.netlify.app/docs/nightly/apim/ 
Environment variables - this is the name we used for env vars across tyk for all the components

2024-01-04 19:40 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          - title: "Content management"
If it's operations maybe this should also be moved to "[Deployment and Operations](https://tyk.io/docs/apim)" tab along with deploy and get started

2024-01-04 19:49 UTC, letzya commented on tyk-docs/data/menu.yaml
> +              path: /tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations
again, JTBD, so need to be in the "deployment & ops" tab.

2024-01-04 19:57 UTC, letzya commented on tyk-docs/data/menu.yaml
> +              path: /tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations
I removed the configuration dir for now

2024-01-05 09:41 UTC, letzya commented on tyk-docs/data/menu.yaml
> -      - title: "Visual appearance customisation"
BTW it is also not a verb.

2024-01-05 09:45 UTC, letzya commented on tyk-docs/data/menu.yaml
> -      - title: "Visual appearance customisation"
How about Customising UI Appearance

2024-01-05 09:45 UTC, letzya commented on tyk-docs/data/menu.yaml
> +      - title: "Content management"
```suggestion
      - title: "Customising UI appearance"
```

2024-01-05 09:48 UTC, letzya commented
@slega I removed the configuration. We still need the env var to be like other components. Can we merge this and then you can move this JTBD content to the dep&ops tab?

2024-01-16 11:46 UTC, merged

2024-01-16 11:47 UTC, dcs3spp commented
/release to release-5.2

2024-01-16 11:47 UTC, dcs3spp commented
/release to release-5.1