[Dx 914] Move Audit Log Content From Release Notes 2.8 To Content Page
TykTechnologies/tyk-docs-hugo pull request #3814
Opened 2023-12-20 15:36 UTC by dcs3spp

[DX-914](https://tyktech.atlassian.net/browse/DX-914)

[preview - to add](/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log)

2023-12-21 11:31 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          - title: "Audit Log Configuration"
```suggestion
          - title: "Audit Log"
```

2023-12-21 12:25 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +```bash
``` suggestion
```yaml
```

2023-12-21 12:38 UTC, letzya requested changes
@dcs3spp 
- I think it's best to remove the content from the release notes and add a link to this doc https://tyk.io/docs/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.8/#dashboard-audit-log-improvements
- We need to add links to the environment vars.
- Apparently, we have the same info in the env var page, so we need to think about what to do to avoid duplication of the same content.
  - https://tyk.io/docs/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.8/#dashboard-audit-log-improvements
   - https://tyk.io/docs/tyk-dashboard/configuration/#audit

2024-01-11 15:39 UTC, JRWu requested changes
Just requesting 1 addition to the document, otherwise looks great

2024-01-11 15:39 UTC, JRWu commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +The audit log contains audit records for all requests made to all endpoints under the `/api` route.
Perhaps we should mention that these instructions require a writable destination in order to function properly (relevant to K8s customers).

2024-01-12 14:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +The audit log contains audit records for all requests made to all endpoints under the `/api` route.
@JRWu I have pushed changes up to the PR as follows for the intro paragraph as follows:

_The audit log contains audit records for all requests made to all endpoints under the `/api` route. Audit logs are written to file in JSON or text format.

Subsequently, if hosting Tyk Dashboard within Tyk Cloud or a Kubernetes cluster, please ensure that the configured log file path is valid and writeable._

2024-01-15 18:08 UTC, JRWu commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +The audit log contains audit records for all requests made to all endpoints under the `/api` route.
@dcs3spp 
I would remove the "within Tyk Cloud" part, since consumers don't have that level of granular control, but otherwise this statement is good

2024-01-17 11:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +The audit log contains audit records for all requests made to all endpoints under the `/api` route.
@JRWu I have pushed up the change as follows:

_Subsequently, if hosting Tyk Dashboard within a Kubernetes cluster, please ensure that the configured log file path is valid and writeable_

When you get chance could you review and then if ok, could you approve?

2024-01-17 12:00 UTC, dcs3spp commented
@Jia Wu I have pushed up the requested change. Would you be able to re-review?

@Yaara Letz would you be able to re-review? I have pushed up the requested changes and raised a ticket with CoreAPIM to remove the duplicate content in config file and add link to this page.

2024-01-17 12:43 UTC, letzya commented
@dcs3spp will aim to check it today

2024-01-17 13:52 UTC, JRWu approved these changes
LGTM!

2024-01-17 21:34 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.8.md
> +There is a [new section]({{< ref "product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log" >}}) in the Tyk Dashboard config file where you can specify parameters for the audit log (co
@dcs3spp why do we have dashboard content in the GW RN?

2024-01-17 21:36 UTC, letzya reviewed
Except for a small comment, approved

2024-01-18 09:36 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.8.md
> +There is a [new section]({{< ref "product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log" >}}) in the Tyk Dashboard config file where you can specify parameters for the audit log (co
@letzya It remained since it was an old release note. Can create an additional ticket and remove it from this file in separate PR or adjust points of existing ticket?

2024-01-19 00:01 UTC, letzya approved these changes

2024-01-19 09:51 UTC, merged

2024-01-19 09:51 UTC, dcs3spp commented
/release to release-5.2

2024-01-19 09:52 UTC, dcs3spp commented
/release to release-5.1