Update getting-started-tyk-operator.md
TykTechnologies/tyk-docs-hugo pull request #3846
Opened 2024-01-04 10:29 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-01-04 14:19 UTC, dcs3spp reviewed
@caroltyk Is it ok for me to mark the current status of the PR as draft? 

Could *tyk-ingress-controller* be moved into *product-stack/tyk-operator/getting-started*, since it is new content?

https://tyktech.atlassian.net/wiki/spaces/EN/pages/2118287411/Creating+Content+For+The+New+Tyk+Docs+Website

https://tyktech.atlassian.net/wiki/spaces/EN/pages/2120187942/New+Docs+Information+Architecture+and+Content+Sections

2024-01-04 16:09 UTC, carolwkc commented
> @caroltyk Is it ok for me to mark the current status of the PR as draft?
> 
> Could _tyk-ingress-controller_ be moved into _product-stack/tyk-operator/_ and added as a menu item in menu.yaml since it is new content?
> 
> https://tyktech.atlassian.net/wiki/spaces/EN/pages/2118287411/Creating+Content+For+The+New+Tyk+Docs+Website
> 
> https://tyktech.atlassian.net/wiki/spaces/EN/pages/2120187942/New+Docs+Information+Architecture+and+Content+Sections

@dcs3spp the PR is ready for review

2024-01-04 16:43 UTC, dcs3spp requested changes
@caroltyk PR is looking good to me. I have reviewed the draft so far and made some minor suggestions. Once PR is ready for review, let me know and also request a peer review

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> + you may do so by setting the environment variable `WATCH_INGRESS_CLASS` in the operator manager deployment. See https://github.com/TykTechnologies/tyk-operator/blob/master/docs/installation/installa
The GHub URL link refers to https://tyk.io/docs/tyk-stack/tyk-operator/installing-tyk-operator/

Could replace with {{< ref "tyk-stack/tyk-operator/installing-tyk-operator" >}}?

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +# Ingress
Add front matter section with title, description and tags.

For SEO purposes remove H1 headings. H1 headings are used for page title in the markdown front matter.

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/getting-started-tyk-operator.md
> +- [Configure Tyk as Ingress Controller]({{< ref "/product-stack/tyk-operator/tyk-ingress-controller" >}})
```suggestion
- [Configure Tyk as Ingress Controller]({{< ref "product-stack/tyk-operator/tyk-ingress-controller" >}})
```

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +Tyk Operator offers an Ingress Controller, which dynamically manages ApiDefinition resources as per the ingress spec.
Is APIDefinition the correct term or should it be User's API Service to avoid confusion with APIDefinition for configuring a user's API service?

 ```suggestion
 Tyk Operator offers an Ingress Controller, which dynamically routes and load balances traffic to user's *APIService* resources.
 ```

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +Each path in an Ingress must have its own particular path type. Kubernetes offers three types of path types: `ImplementationSpecific`, `Exact`, and `Prefix`. Currently, not all path types are support
```suggestion
Each path in an Ingress must have its own particular [path type](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types). Kubernetes offers three types of path: `ImplementationSpecific`, `Exact`, and `Prefix`. Currently, the Tyk Ingress Controller does not support all path types. The table below illustrates the unsupported path types for [Sample HTTP Ingress Resource](#sample-http-ingress-resource) based on the examples in the [Kubernetes Ingress documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#examples).
```

Is #sample-http-ingress-resource a new content file?

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +# Configure Tyk Operator as Ingress Controller
Remove duplicate H1 heading for SEO purposes. The title in the front matter will be rendered by Hugo during the build.

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> + for API Management use-cases. Despite this, the community have built tooling, capabilities, dependencies,
```suggestion
 for API Management use-cases. Despite this, the community have built tooling, capabilities and dependencies
```

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> + of the standard Ingress Resource, by merging features of the ingress specification with that of the template.
Maybe add a final paragraph here to define what the APIDefinition represents with the example / sample. Does it create a default Tyk APIDefintion configuration for each ingress path that references the template?

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +The value of the `kubernetes.io/ingress.class` annotation that identifies Ingress objects to be processed.
```suggestion
The ingress class represents the value of the `kubernetes.io/ingress.class` annotation that identifies Ingress objects to be processed.
```

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +Tyk ingress controller can then handle the acme challenge where cert-manager edits the ingress resource.
```suggestion
Tyk ingress controller can then handle the acme challenge when cert-manager edits the ingress resource.
```

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +## Sample HTTPS Ingress resource
```suggestion
### Sample HTTPS Ingress resource
```

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +Each path in an Ingress must have its own particular path type. Kubernetes offers three types of path types: `ImplementationSpecific`, `Exact`, and `Prefix`. Currently, not all path types are support
Maybe add an external link to K8s documentation for external path types here. Is #sample-http-ingress-resource a new content file?

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/getting-started-tyk-operator.md
> +- [Configure Tyk Operator as Ingress Controller]({{< ref "/product-stack/tyk-operator/tyk-ingress-controller" >}})
```suggestion
- [Configure Tyk Operator as Ingress Controller]({{< ref "product-stack/tyk-operator/tyk-ingress-controller" >}})
```

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> + ApiDefinition custom resource, which brings Full-Lifecycle API Management capabilities to Kubernetes Ingress. A side effect of
Maybe add examples of API management capabilities that Tyk Ingress controller allows. Does this mean via the APIDefinition template feature that users can dynamically specify a template APIDefinition configuration for creation, securing APIs etc ingress paths that reference that API Definition template?

2024-01-04 16:43 UTC, dcs3spp commented on tyk-docs/content/tyk-on-prem/kubernetes-ingress.md
> +**Tyk Operator** offers an [Ingress Controller]({{<ref "product-stack/tyk-operator/tyk-ingress-controller">}}), which dynamically manages Tyk ApiDefinition resources as per the ingress spec.
Is APIDefinition the right term or should be it the user's APIService?

2024-01-04 21:41 UTC, caroltyk commented on tyk-docs/content/tyk-on-prem/kubernetes-ingress.md
> +**Tyk Operator** offers an [Ingress Controller]({{<ref "product-stack/tyk-operator/tyk-ingress-controller">}}), which dynamically manages Tyk ApiDefinition resources as per the ingress spec.
ApiDefinition is our custom resource name

2024-01-04 21:44 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +Tyk Operator offers an Ingress Controller, which dynamically manages ApiDefinition resources as per the ingress spec.
Tyk Operator is managing ApiDefinition resource (this is the name of our custom resource) according to user provided Ingress spec.

2024-01-04 21:45 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +# Configure Tyk Operator as Ingress Controller
```suggestion
```

2024-01-04 21:55 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> + ApiDefinition custom resource, which brings Full-Lifecycle API Management capabilities to Kubernetes Ingress. A side effect of
```suggestion
 ApiDefinition custom resource, which adds additional API Management capabilities, like security policy and rate limiting to Kubernetes Ingress. A side effect of
```

2024-01-04 21:57 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> + of the standard Ingress Resource, by merging features of the ingress specification with that of the template.
```suggestion
 of the standard Ingress Resource, by merging features of the ingress specification with that of the template.
 
 The following sections shows some example of Tyk ApiDefinition template and Ingress specification.
```

2024-01-04 22:01 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +The value of the `kubernetes.io/ingress.class` annotation that identifies Ingress objects to be processed.
```suggestion
The value of the `kubernetes.io/ingress.class` annotation identifies the IngressClass that will process Ingress objects.
```

2024-01-04 22:03 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +Each path in an Ingress must have its own particular path type. Kubernetes offers three types of path types: `ImplementationSpecific`, `Exact`, and `Prefix`. Currently, not all path types are support
#sample-http-ingress-resource links to the "Sample HTTP Ingress Resource" section on same page

2024-01-04 22:04 UTC, caroltyk commented
thanks for the review @dcs3spp . Comments addressed or replied.

2024-01-09 11:25 UTC, dcs3spp commented
Thanks @carol, I've approved. Can you arrange a peer review and then we can merge and release.

2024-01-09 11:31 UTC, dcs3spp approved these changes

2024-01-09 11:49 UTC, buraksekili approved these changes

2024-01-09 11:57 UTC, merged

2024-01-09 11:57 UTC, dcs3spp commented
/release to release-5.2

2024-01-09 11:57 UTC, dcs3spp commented
/release to release-5.1