[TT-10749] Update rate limit docs with leaky bucket option
TykTechnologies/tyk-docs-hugo pull request #3848
Opened 2024-01-04 17:17 UTC by titpetric

### Preview Link

<br>

### Description

This PR adds documentation for the new leaky bucket rate limiting option in Gateway 5.3 release.

It updates some false documentation:

- DRL implements token bucket and not leaky bucket (errata),
- RRL implements sliding window log (as opposed to sliding window counter), be accurate in naming

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-01-05 09:44 UTC, jeffy-mathew approved these changes
lgtm from a technical standpoint 👍

2024-01-05 09:52 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This uses redis to track the rate of incoming API calls. It's important to note that it blocks access to the API when the rate exceeds the rate limit. Unlike other algorithms, it doesn't let API call
@titpetric do we have specific info we can share about the hit in performances when users use this?

2024-01-05 09:58 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  The sentinel-based rate limiter delivers a smoother performance curve as rate-limit calculations happen off-thread, but a stricter time-out based cool-down for clients. For example, when a throttling
who is the standard RL? is it the default one, i.e. DRL?

2024-01-05 09:58 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  ##### Performance
Does this apply to both redis RL and Sentinel RL?

2024-01-05 12:52 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  The DRL rate limiter will be used automatically unless one of the other rate limit algorithms are explicitly enabled via configuration.
```suggestion
The Distributed  Rate Limiter will be used automatically unless one of the other rate limit algorithms are explicitly enabled via configuration.
```

DRL Rate Limiter is tautological

2024-01-05 13:08 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This is the default rate limiter in Tyk. It is the most performant, and the trade-off is that the limit is approximate, not exact. To use a less performant, exact rate limiter, review the Redis rate
```suggestion
This is the default rate limiter in Tyk. It is the most performant but has a trade-off that the limit applied is approximate, not exact. To use a less performant, exact rate limiter, review the Redis rate limiter below.
```

2024-01-05 13:08 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +Tyk offers the following rate limiting modes:
```suggestion
Tyk offers the following rate limiting algorithms to protect your APIs:
```

2024-01-05 13:08 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +It also uses what's called a token bucket algorithm. In this case if the request rate is higher than the rate limit it will attempt to let through requests at the specified rate limit. It's important
```suggestion
The DRL implements a token bucket algorithm. In this case if the request rate is higher than the rate limit it will attempt to let through requests at the specified rate limit. It's important to note that this is the only rate limit method that uses this algorithm and that it will yield approximate results.
```

2024-01-05 13:08 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This uses redis to track the rate of incoming API calls. It's important to note that it blocks access to the API when the rate exceeds the rate limit. Unlike other algorithms, it doesn't let API call
```suggestion
This uses Redis to track and limit the rate of incoming API calls. An important behaviour of this method is that it blocks access to the API when the rate exceeds the rate limit and does not let further API calls through until the rate drops below the specified rate limit. For example, if the rate limit is 3000/minute the call rate would have to be reduced below 3000 for a whole minute before the HTTP 429 responses stop.
For example, you can slow your connection throughput to regain entry into your rate limit. This is more of a “throttle” than a “block”.
```

2024-01-05 13:08 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  The sentinel-based rate limiter delivers a smoother performance curve as rate-limit calculations happen off-thread, but a stricter time-out based cool-down for clients. For example, when a throttling
Yes, DRL is default. Sentinel is (I believe) a sub-set of the Redis limiter.

2024-01-05 13:08 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  The sentinel-based rate limiter delivers a smoother performance curve as rate-limit calculations happen off-thread, but a stricter time-out based cool-down for clients. For example, when a throttling
```suggestion
As explained above, when using the Redis rate limiter, when a throttling action is triggered, requests are required to cool-down for the period of the rate limit.

The default behaviour with the Redis rate limiter is that the rate-limit calculations are performed on-thread.

The optional Redis Sentinel rate limiter delivers a smoother performance curve as rate-limit calculations happen off-thread, with a stricter time-out based cool-down for clients. 
```

2024-01-05 13:08 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +Redis rate limiter, provides 100% accuracy, however instead of using the token bucket algorithm it uses the sliding window log algorithm. This means that if there is a user who abuses the rate limit,
```suggestion
The Redis rate limiter provides 100% accuracy, however instead of using the token bucket algorithm it uses the sliding window log algorithm. This means that if there is a user who abuses the rate limit, this user's requests will be limited until they start respecting the rate limit. In other words, requests that return 429 will count towards their rate limit counter.
```

2024-01-08 11:23 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  ##### Performance
If you're referring to the non-transactional rate limit setting, yes, it applies to both RRL and RRL/sentinel.

2024-01-08 12:28 UTC, letzya commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  ##### Performance
I M not referring the text it. My question was - does the performance section refers to these two RLs? It is not clear to me.

2024-01-08 22:08 UTC, letzya commented
@titpetric we can merge this pr but I feel this page is quite lean. Would be good to share more in depth information with our users

2024-01-09 08:54 UTC, andyo-tyk commented
> @titpetric we can merge this pr but I feel this page is quite lean. Would be good to share more in depth information with our users

I agree - but this is one of many pages that needs a good boost. We plan a deeper/more thorough review of rate limiting later and I propose an overhaul of the documentation at the same time, rather than now.

2024-01-09 10:56 UTC, dcs3spp requested changes
@titpetric PR looks good to me. Have made some minor suggestions

2024-01-09 10:56 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This algorithm can be managed using the following configuration option [enable_redis_rolling_limiter]({{< ref "/tyk-oss-gateway/configuration.md#enable_redis_rolling_limiter" >}}).
```suggestion
This algorithm can be managed using the following configuration option [enable_redis_rolling_limiter]({{< ref "tyk-oss-gateway/configuration.md#enable_redis_rolling_limiter" >}}).
```

2024-01-09 10:56 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This option can be enabled using the following configuration option [enable_leaky_bucket_rate_limiter]({{< ref "/tyk-oss-gateway/configuration.md#enable_leaky_bucket_rate_limiter" >}}).
```suggestion
This option can be enabled using the following configuration option [enable_leaky_bucket_rate_limiter]({{< ref "tyk-oss-gateway/configuration.md#enable_leaky_bucket_rate_limiter" >}}).
```

2024-01-09 10:56 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  ##### Sentinel Rate Limiter
```suggestion
##### Redis Sentinel Rate Limiter
```

2024-01-09 10:56 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +### Redis rate limiter
```suggestion
### Redis Rate Limiter
```

2024-01-09 10:56 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  The Redis limiter is indeed slower than the DRL, but that performance can be improved by enabling the [enable_non_transactional_rate_limiter]({{< ref "/tyk-oss-gateway/configuration.md#enable_non_tra
Per review comment above add Redis Rate Limiter and Redis Sentinel Rate Limiter to this paragraph to make it clearer that this performance section relates to these two rate limiters.

2024-01-09 18:07 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  ##### Performance
It's a nested H5 (Performance) under a H3 (Redis Rate Limiters). Transactional behaviour is a flag, it's not it's own rate limiter

2024-01-11 09:46 UTC, dcs3spp approved these changes

2024-01-12 09:43 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  With the DRL, the gateways divide the rate limit evenly across all the gateways in the cluster (a cluster of gateway shares the same Redis.) These gateways store the running rate in memory and return
```suggestion
With the DRL, the configured rate limit is split (distributed) evenly across all the gateways in the cluster (a cluster of gateway shares the same Redis). These gateways store the running rate in memory and return [429 (Rate Limit Exceeded)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) when their share is used up.
```

2024-01-12 09:44 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  With the DRL, the gateways divide the rate limit evenly across all the gateways in the cluster (a cluster of gateway shares the same Redis.) These gateways store the running rate in memory and return
Sorry, could we please add this tweak, to improve the explanation of the Distributed Rate Limiter? (I missed it during my first pass through :(

2024-01-12 17:04 UTC, andyo-tyk approved these changes
I'm happy with this now.

2024-01-16 11:31 UTC, dcs3spp approved these changes
PR LGTM

2024-01-16 11:35 UTC, merged

2024-01-16 11:35 UTC, dcs3spp commented
/release to release-5.2

2024-01-16 11:36 UTC, dcs3spp commented
/release to release-5.1

2024-01-16 11:38 UTC, dcs3spp commented
/release to release-5