Operator release notes
TykTechnologies/tyk-docs-hugo pull request #3906
Opened 2024-01-12 14:35 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-01-15 14:02 UTC, letzya commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.16.md
> +## 0.16.0 Release Notes
```suggestion
## 0.16.0 Release Notes bla
```

2024-01-15 23:22 UTC, letzya commented
We missed the release date. Let's try to get it next time ready and merged before the release :)

2024-01-16 10:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.16.md
> +#### Upgrade instructions
```suggestions
#### Upgrade Instructions
```

2024-01-16 11:15 UTC, dcs3spp requested changes
Thanks @caroltyk PR looks good to me, made minor suggestions and then will merge and release. 

Double checking if the CVE on the release note is internally scanned CVE? If so then policy is to not include on release notes, only external CVEs should be included.

2024-01-16 11:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.16.md
> +  Added imagePullSecrets configuration for ServiceAccount in Tyk Operator Helm chart
Maybe update with a link for [imagePullSecrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) to external K8s site and add a sentence explaining purpose of what this change allows the user to do.

2024-01-16 11:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.16.md
> +Added to ApiDefinition CRD: support for UDG Global Header at [spec.graphql.engine.global_headers](https://doc.crds.dev/github.com/TykTechnologies/tyk-operator/tyk.tyk.io/ApiDefinition/v1alpha1@v0.16.
Is the _UDG Global Header_ feature only compatible with Tyk 5.2 and, if so should it be mentioned here?

2024-01-16 11:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.16.md
> +Fixed [CVE-2023-39325 (NVD)](https://nvd.nist.gov/vuln/detail/CVE-2023-39325)
Is this a dependency tracked CVE or an internal scanned CVE?

2024-01-16 12:05 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.16.md
> +  Added imagePullSecrets configuration for ServiceAccount in Tyk Operator Helm chart
```suggestion
  Added [imagePullSecrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) configuration for ServiceAccount in Tyk Operator Helm chart. It allows user to pull image from a private registry.
```

2024-01-16 12:05 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.16.md
> +Added to ApiDefinition CRD: support for UDG Global Header at [spec.graphql.engine.global_headers](https://doc.crds.dev/github.com/TykTechnologies/tyk-operator/tyk.tyk.io/ApiDefinition/v1alpha1@v0.16.
```suggestion
Added to ApiDefinition CRD: support for UDG Global Header at [spec.graphql.engine.global_headers](https://doc.crds.dev/github.com/TykTechnologies/tyk-operator/tyk.tyk.io/ApiDefinition/v1alpha1@v0.16.0#spec-graphql-engine-global_headers) object in ApiDefinition CRD. This feature is compatible with Tyk 5.2 or above.
```

2024-01-16 12:42 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.16.md
> +Fixed [CVE-2023-39325 (NVD)](https://nvd.nist.gov/vuln/detail/CVE-2023-39325)
It was reported by dependabot and dependency tracked

2024-01-16 14:02 UTC, dcs3spp approved these changes
@caroltyk PR looks good to me, I'll merge and release

2024-01-16 14:05 UTC, merged

2024-01-16 14:05 UTC, dcs3spp commented
/release to release-5.2

2024-01-16 14:06 UTC, dcs3spp commented
/release to release-5.1