[DX-964] Add release notes for EDP v1.8.3
TykTechnologies/tyk-docs-hugo pull request #3909
Opened 2024-01-16 00:52 UTC by slega

### For internal users - Please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/DX-964
<br>

---

### Preview Link

<br>

### Description
Add release notes for the EDP v1.8.3 and update the OAS for the admin APIs.
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2024-01-16 13:17 UTC, dcs3spp requested changes
Hi @slega PR looks good to me. Have made some minor suggestions on release notes content.

For the API minor suggestions added and not sure if it would be possible to update the naming style of schema items to match that used in Gateway, e.g remove hyphens from schema types.

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.3.md
> +- [The default theme package](https://github.com/TykTechnologies/portal-themes/blob/main/v1.8.2/default.zip)
Remember to update docker image and theme package download links before release

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.3.md
> +- Added [new admin API]({{< ref "product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api" >}}) for managing oAuth2.0 client types attached to API Products.
```suggestion
- Added [new admin API]({{< ref "product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api" >}}) for managing OAuth2.0 client types attached to API Products.
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.3.md
> +- Fixed the bug where the portal's Page menu allowed to pages with duplicated names of content-blocks leading to only one of the blocks being displayed.
Does this mean that Portal allowed pages to be created  with duplicate content-blocks, which meant that the last content block added was the only block displayed?

```suggestion
Fixed the bug where the Portal allowed pages to be created with duplicate content block names. Subsequently, only the last content block with the duplicate name was displayed.
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.3.md
> +- Fixed the bug where the portal's page renderer ignored content-blocks under the `if` statement with references to multiple content-blocks (e.g. `{{ if and .blocks.Block1.Content .blocks.Block2.Cont
```suggestion
- Fixed the bug where the portal's page renderer ignored content-blocks under the `if` statement with references to multiple content-blocks (e.g. `{{ if and .blocks.Block1.Content .blocks.Block2.Content .blocks.Block3.Content }}`). Subsequently, content that depended on these conditional blocks would not be rendered.
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.3.md
> +The 1.8.3 release addresses ten high-priority bugs and introduces new admin APIs for managing tags and oAuth2.0 client types attached to API Products.
```suggestion
The 1.8.3 release addresses ten high-priority bugs and introduces new admin APIs for managing tags and OAuth2.0 client types attached to API Products.
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-Tag-index:
Update to _Product-Tag-index_ to _ProductTagList_

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Detach a tag from this API Product
```suggestion
      description: Delete a tag from this API Product
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        - description: Name of a the tag
```suggestion
        - description: Name of the tag to delete
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      summary: Detach a tag from this API Product
```suggestion
      summary: Delete a tag from this API Product
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        - description: Name of a the tag
```suggestion
        - description: Name of the tag
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +            applicatison/json:
```suggestion
            application/json:
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      description: Detach a client type from this API Product
```suggestion
      description: Delete a client type from this API Product
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
```suggestion
          description: Client type deleted successfully
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
Add example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "404":
Add example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Not found
Client type not found

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
Client type successfully retrieved

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
Add an example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-ClientType-index:
Update Product-ClientType-index to ProductClientTypeList

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-ClientType-index-elem:
Update _Product-ClientType-index-elem_ to _ProductClientTypeListItem_

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-ClientType-show:
Update _Product-ClientType-show_ to _ProductClientTypeResponse_

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: represent grant types allowed by the client type
add an example for _GrantType_

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-ClientType-create:
Update _ProductClientTypeCreate_ 

The id attribute is present. Should there also be an attribute for the client type?

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
```suggestion
          description: Product tags retrieved successfully
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
add an example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      requestBody:
Add an example request body

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "201":
add example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
```suggestion
          description: Product tag created successfully
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "422":
add an example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
```suggestion
          description: Tag successfully deleted from product
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
Add example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "404":
Add example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Not found
```suggestion
The tag requested for deletion was not found
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
Add example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
Product tag was successfully retrieved

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      responses:
Should a 404 be raised here also?

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
```suggestion
          description: List of client types successfully retrieved
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
add an example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      requestBody:
add an example request body

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
```suggestion
          description: Client type successfully created for product
```

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "422":
Add an example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "201":
Add example response

2024-01-16 13:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
```suggestion
          description: Invalid payload encountered when creating client type. Request could not be processed
```

2024-01-16 14:47 UTC, slega commented
@dcs3spp the tags and OAuth2.0 clients types are not created by these APIs. They are *ATTACHED* to API Products meaning that they are created elsewhere (currently in the UI) and then ATTACHED to API Products using these APIs.

2024-01-16 15:42 UTC, dcs3spp commented
> @dcs3spp the tags and OAuth2.0 clients types are not created by these APIs. They are **ATTACHED** to API Products meaning that they are created elsewhere (currently in the UI) and then **ATTACHED** to API Products using these APIs.

@slega When you say attached in the UI, do you mean that the UI is responsible for storing the resources for tags and OAuth2.0 client types in backend storage?

If so, then should the API endpoints for maintaining tags and OAuth2.0 client types included in this PR be removed from the OAS schema?

2024-01-16 18:00 UTC, slega commented
> > @dcs3spp the tags and OAuth2.0 clients types are not created by these APIs. They are **ATTACHED** to API Products meaning that they are created elsewhere (currently in the UI) and then **ATTACHED** to API Products using these APIs.
> 
> @slega When you say attached in the UI, do you mean that the UI is responsible for storing the resources for tags and OAuth2.0 client types in backend storage?
> 
> If so, then should the API endpoints for maintaining tags and OAuth2.0 client types included in this PR be removed from the OAS schema?

No, I mean the tags and the client types are not created specifically for API products. They are attached to API Products and  are separate resources that currently are created via the UI (the admin API endpoints will be introduced in the later releases). One client type and one tag might be attached to multiple API Products. A client type or tag can be also detached from a product. So, in this case the wording is precise.

2024-01-18 18:27 UTC, dcs3spp commented
@slega Thanks again for discussion in the meet earlier. I will check through again tomorrow and will update you on the status

2024-01-19 10:52 UTC, dcs3spp requested changes
@slega I have looked re-reviewed after changes and noted the following:

**Tags /products/{product_id}/tags/{tag_name}** 

**Delete**
The example response for 404 shows an ok message in swagger editor
{
  "status": "ok"
}

**Get**
Shouldn't 404 error code be raised if the tag is not found in the GET tag endpoint? status code 200 is the only response code for Get endpoint.  
 
 
**Client Types /products/{product_id}/client_types/{client_type_id}** 
 
 **Get** 
 Shouldn’t a 404 status code be raised when either of the following is true?
* product not found
* client type not found

2024-01-19 10:52 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "404":
@slega The example response for 404 shows an ok message in swagger editor

```json
{
  "status": "ok"
}
```

2024-01-19 10:52 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      responses:
@slega Shouldn't 404 error code be raised if the tag is not found in the GET tag endpoint /products/{product_id}/tags/{tag_name}? Currently only status code 200 is raised

2024-01-19 10:52 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "404":
@slega The example 404 response for DELETE client type endpoint does not show not found error message. Instead it shows ok message

{
  "status": "ok"
}

2024-01-19 10:52 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      responses:
@slega Should a 404 status code also be raised here (/products/{product_id}/client_types/{client_type_id}) if:
- product not found
- client type not found

2024-01-23 13:45 UTC, slega commented
@slega I've added 404s to the specified resources + updated the links

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "422":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "404":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "201":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      responses:
@dcs3spp unfortunately the portal's framework doesn't allow for it. So, it should be raised but we can't implement it.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
Done

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io/ or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "201":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io/ or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "422":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io/ or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io/ or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "404":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io/ or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "200":
@dcs3spp the examples are defined in the response schema. You can validate this by opening the OAS in https://editor-next.swagger.io/ or any other OAS editor.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-Tag-index:
Done

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-ClientType-index:
Done

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-ClientType-index-elem:
Done

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-ClientType-show:
Done

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: represent grant types allowed by the client type
Done

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: OK
Done

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      requestBody:
@dcs3spp the example request body is defined in the schema.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      requestBody:
@dcs3spp the example request body is defined in the schema.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    Product-ClientType-create:
It was an unused model. I removed it/.

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Not found
Done

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      responses:
Done

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +      responses:
It's 404 - I've updated the OAS

2024-01-23 13:46 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        "404":
This is how works in reality - framework limitation.

2024-01-23 13:46 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.3.md
> +- [The default theme package](https://github.com/TykTechnologies/portal-themes/blob/main/v1.8.2/default.zip)
Done.

2024-01-23 14:17 UTC, dcs3spp requested changes
@slega Thanks for submitting the changes, adding 404 status codes. I have added suggestion to fix a typo and then will approve and release

2024-01-23 14:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Product tag is wot found
```suggestion
          description: Product tag is not found
```

2024-01-23 14:17 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Client type is wot found
```suggestion
          description: Client type is not found
```

2024-01-23 14:55 UTC, dcs3spp approved these changes
PR LGTM

2024-01-23 14:56 UTC, merged

2024-01-23 14:56 UTC, dcs3spp commented
/release to release-5.2

2024-01-23 14:58 UTC, dcs3spp commented
/release to release-5.1