[TT-8222] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #3924
Opened 2024-01-16 13:51 UTC by buger

Triggered by: titpetric

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: master

Note: Testing x-tyk-gateway generator in tyk-docs action, do not review.

JIRA: https://tyktech.atlassian.net/browse/TT-8222

2024-01-16 15:03 UTC, dcs3spp commented
@titpetric @lghiur This is marked as testing in PR description, so it should not be reviewed, yes?

2024-01-16 16:54 UTC, titpetric commented
@dcs3spp should i pay attention to the htmltest CI pipeline here? I'm unsure if it's failing because of the changes in the PR, or if it's like that by default

2024-01-16 17:02 UTC, titpetric commented
Preview links for generator comparison:

https://tyk.io/docs/tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc/ (current docs)
https://deploy-preview-3924--tyk-docs.netlify.app/nightly/docs/tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc/ (preview)

2024-01-16 17:30 UTC, dcs3spp commented
> @dcs3spp should i pay attention to the htmltest CI pipeline here? I'm unsure if it's failing because of the changes in the PR, or if it's like that by default

@titpetric I have clone the PR branch locally and done a _hugo build_ locally.

Hugo generates html files from the markdown at _tyk-docs/public/tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc/index.html_

The _htmltest_ CI pipeline checks for broken html links. 

One of the links broken in html is as shown below for map[string]interface

```html
<p>Type defined as <code>map[string]interface{}</code>, see <a href="map[string]interface%7b%7d">map[string]interface{}</a> definition.</p>
```
%7b%7d => {}

2024-01-17 14:31 UTC, titpetric commented
To aid review, these are the newly generated headings that need some scrutiny for language, formatting:

```
--- old.1	2024-01-17 15:29:46.926359641 +0100
+++ new.1	2024-01-17 15:29:11.066449900 +0100
@@ -1,8 +1,11 @@
 # Allowance
+# AllowanceType
+# APIDef
 # Authentication
 # AuthenticationPlugin
 # AuthSource
 # AuthSources
+# Basic
 # Cache
 # CachePlugin
 # CertificatePinning
@@ -11,10 +14,15 @@
 # CORS
 # CustomPlugin
 # CustomPluginAuthentication
+# CustomPlugins
+# DetailedActivityLogs
 # Domain
 # DomainToCertificate
 # EndpointPostPlugin
+# EndpointPostPlugins
 # EnforceTimeout
+# ExternalOAuth
+# ExtractCredentialsFromBody
 # FromOASExamples
 # GatewayTags
 # Global
@@ -23,16 +31,29 @@
 # IDExtractor
 # IDExtractorConfig
 # Info
+# Introspection
+# IntrospectionCache
+# JWT
+# JWTValidation
 # ListenPath
 # Middleware
 # MockResponse
 # MutualTLS
+# Notifications
+# OAS
+# OAuth
+# OAuthProvider
 # OIDC
 # Operation
+# Operations
+# Path
+# Paths
 # PinnedPublicKey
+# PinnedPublicKeys
 # PluginBundle
 # PluginConfig
 # PluginConfigData
+# Plugins
 # PostAuthenticationPlugin
 # PostPlugin
 # PrePlugin
@@ -40,17 +61,23 @@
 # ResponsePlugin
 # Scopes
 # ScopeToPolicy
+# SecurityScheme
+# SecuritySchemes
 # Server
 # ServiceDiscovery
 # ServiceDiscoveryCache
+# Signature
 # State
 # Test
+# Token
 # TransformBody
+# TransformHeaders
+# TransformHeaders
 # TransformRequestMethod
-# TYK OAS API Definition Object
+# TykExtensionConfigParams
 # Upstream
 # ValidateRequest
 # Versioning
 # VersionToID
 # VirtualEndpoint
-# x-tyk-gateway
+# XTykAPIGateway
```

2024-01-18 11:28 UTC, dcs3spp requested changes
@titpetric I am submitting review that I partially did before the PR content changed

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/assets/others/gateway-swagger.yml
> +  version: 5.2.0
version would beed to be 5.3.0

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# XTykAPIGateway
As discussed in meet replace H1 headings with H2 for the purposes of SEO and adjust levels in content accordingly.

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Info
H1 Heading to remove and replace as H2 or H3?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ID is the unique identifier of the API within Tyk.
Do we need to update with if it is autogenerated ID and/or specified by user?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `dbId` (`model.ObjectID`)**
not sure whether model.ObjectID is correct, that is a golang struct yes?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Upstream
H1 heading, update to H2 or H3 for SEO reasons

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ServiceDiscovery contains the configuration related to Service Discovery.
```suggestion
ServiceDiscovery contains the configuration related to service discovery.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Server
H1 heading

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
This is also mentioned at line 314. Can we link to it from the field?

```suggestion
ListenPath is the base path on Tyk to which requests for this API should
be sent. Tyk listens for any requests coming into the host at this
path, on the port that Tyk is configured to run on and processes these
accordingly.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ClientCertificates contains the configurations related to establishing static mutual TLS beetween the client and Tyk.
between typo 

```suggestion
ClientCertificates contains the configurations related to establishing static mutual TLS between the client and Tyk.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +GatewayTags contains segment tags to configure which GWs your APIs connect to.
```suggestion
GatewayTags contains segment tags to configure which gateways your APIs connect to.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Middleware
H1 heading to remove for SEO reasons

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# State
H1 heading to remove for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Versioning
H1 heading. Replace for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +`This API version does not seem to exist` error in this scenario.
Can this line appear on line 165 above

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +`This API version does not seem to exist` error in this scenario.
VersionID and Upstream removed

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# ServiceDiscovery
H1 heading needs replacing for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
ParentDataPath is the namespace of where to find the nested
value if `useNestedQuery` is `true`. In the above example, it
would be `node.value`. You would change the `dataPath` setting
to be `hostname`, since this is where the host name data
resides in the JSON string. Tyk automatically assumes that
`dataPath` in this case is in a string-encoded JSON object and
will try to deserialize it.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
PortDataPath is the port of the data path. In the above nested example, we can see that there is a separate `port` value for the service in the nested JSON. In this case, you can set the `portDataPath` value and Tyk will treat `dataPath` as the hostname and zip them together (this assumes that the hostname element does not end in a slash or resource identifier such as `/widgets/`). In the above example, the `portDataPath` would be `port`.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
UseTargetList should be set to `true` if you are using load balancing. Tyk will treat the data path as a list and inject it into the target list of your API definition.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
Setting it too low will cause Tyk to call the service discover service too often, setting it too high could mean that failures are not recovered from quickly enough.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition:.
```suggestion
Tyk classic API definition:
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
TargetPath is used to set a target path that will be appended to the discovered endpoint, since many service discovery services only provide host and port data. It is important to be able to target a specific resource on that host. Setting this value will enable that.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **ServiceDiscoveryCache**
This is removed, worth checking if it is still included and in same order

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition: `service_discovery.endpoint_returns_list`.
Not sure if this change is valid, should it still be `service_discover.endpoint_returns_list`?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Test
H1 heading to replace for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# MutualTLS
H1 heading, replace for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables/disables upstream mutual TLS for the API.
What is the default value and should we mention it?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# CertificatePinning
H1 heading to replace for SEO reasons

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **DomainToCertificate**
DomainToCertificate is removed, worth checking if reoredered. If not reordered, should it be removed?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
>  Enabled is a boolean flag, if set to `true`, it enables certificate pinning for the API.
Is there a default value and should we mention it?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
Should the blank line be removed?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **PinnedPublicKey**
Has this and Server being removed?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition: `pinned_public_keys`.
Not sure if this valid? was `domain`?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# ListenPath
Replace H1 heading for SEO reasons

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
```suggestion
ListenPath is the base path on Tyk to which requests for this API should be sent. Tyk listens out for any requests coming into the host at this path, on the port that Tyk is configured to run on and processes these accordingly.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Strip removes the inbound listen path (as accessed by the client) when generating the outgoing request (to the upstream service).
```suggestion
Strip, if set to `true`, removes the inbound listen path (as accessed by the client) when generating the outgoing request (to the upstream service).
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +- If stripListenPath is set to `true`, the `example` listen path is removed and the request would be proxied to `http://httpbin.org/get`.
Should this be the suggestion below since the field name is documented as _strip_?

```suggestion
- If strip is set to `true`, the `example` listen path is removed and the request would be proxied to `http://httpbin.org/get`.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +- If the client application sends a request to `http://acme.com/example/get` then the request will be proxied to `http://httpbin.org/example/get`
Not sure if should be strip or stripListenPath

```suggestion
- If the client application sends a request to `http://acme.com/example/get` and `strip` is set to `false`, then the request will be proxied to `http://httpbin.org/example/get`
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Authentication
H1 heading should be replaced for SEO reasons

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Authentication contains configuration about the authentication methods and security policies applied to requests.
```suggestion
Authentication contains configuration relating to authentication methods and security policies applied to requests.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +StripAuthorizationData ensures that any security tokens used for accessing APIs are stripped and not passed to the upstream.
```suggestion
StripAuthorizationData ensures that any security tokens used for accessing APIs are stripped and not passed upstream.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
BaseIdentityProvider enables the use of multiple authentication mechanisms. It provides the session object that determines access control, rate limits and usage quotas.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `securitySchemes` ([SecuritySchemes](#securityschemes))**
Double link link for new type

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# ClientCertificates
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **HMAC**
Potential conflict to check here due to ordering?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ClientCertificates contains the configurations related to establishing static mutual TLS beetween the client and Tyk.
```suggestion
ClientCertificates contains the configurations related to establishing static mutual TLS between the client and Tyk.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables static mTLS for the API.
Should this replace HMAC authentication mode?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -**Field: `header` ([AuthSource](#authsource))**
Why is header removed?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# GatewayTags
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +GatewayTags holds a list of segment tags that should apply for a gateway.
What is mean by segment tags in relation to the entire Gateway?

```suggestion
GatewayTags holds a list of segment tags that should be applied for the gateway.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -Tyk classic API definition: `auth_configs[x].header`.
Should this be removed?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables use of segment tags.
Is there a default value and should it be mentioned?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Domain
H1 content should be replaced for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled allow/disallow the usage of the domain.
Is there a default value and should it be mentioned?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# DetailedActivityLogs
Replace H1 heading for SEO reasons

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables/disables detailed activity logs.
Is there a default value and should it be mentioned?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Global
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Operations
Replace H1 heading for SEO purposes and Operations is suggested to hide since it is internal type?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Operations holds Operation definitions.
What do operation definitions involve? Do they relate to configuration for each endpoint URL?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as `map[string]interface{}`, see [map[string]interface{}](map[string]interface{}) definition.
The `map[string]interface{}` is the reason why the CI htmltest check has the error. correct map[string]interface{} to any

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# ServiceDiscoveryCache
H1 replace for SEO reasons

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled turns service discovery cache on or off.
Does it have a default value and should it be mentioned?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# DomainToCertificate
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# PinnedPublicKeys
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as `[]PinnedPublicKey`, see [PinnedPublicKey](PinnedPublicKey) definition.
Check link works here, in preview it is giving 404

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# HMAC
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the HMAC authentication mode.
Is there a default value and should we mention it?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# OIDC
H1 heading replace for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the OIDC authentication mode.
Does it have a default value and should we mention it?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `segregateByClientId` (`boolean`)**
Not sure if this is a typo?

```suggestion
**Field: `seggregateByClientId` (`boolean`)**
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SegregateByClientId is a boolean flag. If set to `true, the policies will be applied to a combination of Client ID and User ID.
Not sure if this is a typo? it is in OIDC which is not newly added config typo, but have raised it in the review

```suggestion
SeggregateByClientId is a boolean flag. If set to `true, the policies will be applied to a combination of Client ID and User ID.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition: `openid_options.segregate_by_client`.
same comment relating to potential typo for seggregate

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -**Field: `tags` (`[]string`)**
should the array link be combined?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the CustomPluginAuthentication authentication mode.
Is there a default value and should we mention it?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# CustomPluginAuthentication
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# SecuritySchemes
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SecuritySchemes holds security scheme values, filled with Import().
Is Import GoLang feature for importing GoLang packages? What are examples of security schemes?
 
```suggestion
SecuritySchemes holds security scheme values, filled with `import()`.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as `map[string]interface{}`, see [map[string]interface{}](map[string]interface{}) definition.
correct map[string]interface{} to any to avoid htmltest CI action build check error

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `driver` (`apidef.MiddlewareDriver`)**
type changed here? In PR preview does not have link

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# CORS
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
AllowCredentials indicates whether the request can include user credentials like cookies, HTTP authentication or client side SSL certificates.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
OptionsPassthrough is a boolean flag. If set to `true`, it will proxy the CORS OPTIONS pre-flight request directly to upstream, without authentication and any CORS checks. This means that pre-flight requests generated by web-clients such as SwaggerUI or the Tyk Portal documentation system will be able to test the API using trial keys.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +AllowedOrigins holds a list of origin domains to allow access from. Wildcards are also supported, e.g. `http://*.foo.com`
```suggestion
AllowedOrigins holds a list of origin domains to allow access from. Wildcards are also supported, e.g. `http://*.foo.com`.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# PrePlugin
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PrePlugin configures pre stage plugins.
Not sure if we can rename the type since already used in production, but could maybe update the description?

```suggestion
PrePlugin configures pre authentication plugins.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# PostAuthenticationPlugin
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# PostPlugin
Remove H1 headings for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# ResponsePlugin
Remove H1 for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Cache
Replace H1 headings for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
Does it have a default value and should it be mentioned?

```suggestion
Enabled turns global cache middleware on or off. It is still possible to enable caching on a per-path basis by explicitly setting the endpoint cache middleware
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank line

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
CacheAllSafeRequests caches responses to (`GET`, `HEAD`, `OPTIONS`) requests overrides per-path cache settings in versions, applies across versions.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank lines

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank lines

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank lines

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
remove blank lines

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# TransformHeaders
replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables Header Transform for the given path and method.
Does it have a default value and should it be mentioned?

```suggestion
Enabled enables header transformations for the given path and method.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `remove` (`[]string`)**
is this an example of array that needs combining or is that only for custom types?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `add` (`[]`[Header](#header))**
is this an example of array that needs combining?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# TransformHeaders
Replace H1 headings for SEO purposes

Is this a duplicate heading? See above section

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Provider
Replace H1 headings for SEO

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `clientToPolicyMapping` (`[]`[ClientToPolicy](#clienttopolicy))**
Is this an example of array that needs combining?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Scopes
Replace H1 for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `scopeToPolicyMapping` (`[]`[ScopeToPolicy](#scopetopolicy))**
Is this an example of arrays that need combining?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables custom authentication plugin.
Does it have a default value and should it be mentioned?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# PluginBundle
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the custom plugin bundles.
Does it have a default value and should it be mentioned?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables custom plugin config data.
Does it have a default value and should it be mentioned?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# PluginConfigData
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# CustomPlugins
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CustomPlugins is a list of CustomPlugin.
```suggestion
CustomPlugins is a list of custom plugins
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Header
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# ClientToPolicy
Replace H1 heading for SEO purposes

Cannot see this heading in list of sections included in PR comment. Should it be here?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# ScopeToPolicy
Replace H1 headings for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Source is the source from which ID to be extracted from.
```suggestion
Source is the source from which the ID is to be extracted from.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# CustomPlugin
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path is the path to shared object file in case of gopluign mode or path to js code in case of otto auth plugin.
```suggestion
Path is the path to shared object file in case of goplugin mode or path to js code in case of otto auth plugin.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# IDExtractorConfig
Replace H1 headings for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
````suggestion
RegexpMatchIndex is the index from which the ID is to be extracted after a match.
Default value is 0, ie if `regexpMatchIndex` is not provided then the ID is matched from index 0.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# OAuthProvider
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# JWTValidation
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables OAuth access token validation by introspection to a third party.
Is there a default value?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SigningMethod to verify signing method used in jwt - allowed values HMAC/RSA/ECDSA.
```suggestion
SigningMethod to verify signing method used in jwt. Valid values are:
- ECDSA 
- HMAC
- RSA
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
```suggestion
Source is the secret to verify signature. Valid values are:
- a base64 encoded static secret
- a valid JWK url in plain text
- a valid JWK url in base64 encoded format
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Introspection
Replace H1 heading for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables OAuth access token validation by introspection to a third party.
Does it have a default value?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +IdentityBaseField is the key showing where to find the user id in the claims. If it is empty, the `sub` key is looked at.
```suggestion
IdentityBaseField is the key showing where to find the user id in the claims. If it is empty, the `sub` key is inspected.
```

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# IntrospectionCache
Replace H1 headings for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `enabled` (`boolean`)**
requires description

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `providers` (`[]`[OAuthProvider](#oauthprovider))**
requires description

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# EndpointPostPlugins
replace H1 headings for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as `[]EndpointPostPlugin`, see [EndpointPostPlugin](EndpointPostPlugin) definition.
Require fields and accompanying descriptions for this type

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# APIDef
H1 heading replace for SEO. Previously mentioned that this should not be in PR

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Allowance
Replace H1 heading for SEO

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled is a boolean flag, if set to `true`, then individual allowances (allow, block, ignore) will be enforced.
Does these allowance boolean fields have a default value and should the default values be mentioned?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# AllowanceType
Replace H1 headings for SEO purposes

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as `int`, see [int](int) definition.
Missing **Field....** formatting

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# AuthSource
H1 heading replace for SEO

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the auth source.
default value?

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# AuthSources
H1 heading replace for SEO

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +# Basic
H1 heading replace for SEO

2024-01-18 11:28 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the basic authentication mode.
default?

2024-01-18 12:53 UTC, dcs3spp requested changes
@titpetric Here is the second review for the remaining content. This completes the review where I have checked for grammar and headings where possible.

- APIDef hidden as expected
- Operations does not exist, but Operation does. Is Operations missing or hidden?
- SecurityScheme I could not find but SecuritySchemes exists
- Fix links from htmltest action as discussed

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
```suggestion
ExtractCredentialsFromBody helps to extract username and password from body. In some cases, like dealing with SOAP, user credentials can be passed via request body.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled is a boolean flag. If set to `true`, the advanced caching plugin will be enabled.
default value?

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ExtractCredentialsFromBody configures extracting credentials from the request body.
```suggestion
ExtractCredentialsFromBody relates to configuring if credentials should be extracted from the request body.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables extracting credentials from body.
Does it have a default value and should it be mentioned?

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **ExtractCredentialsFromBody**
Does this relate to Basic Auth? The reason why, is I noticed is in this section there is this field for Tyk classic API definition. If so we should make it clear that only relates to BasicAuth

_Tyk classic API definition: `basic_auth.extract_from_body`_

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables getting a mock response from OAS examples or schemas documented in OAS.
Does it have a default value?

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `enabled` (`boolean`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `source` (`string`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `signingMethod` (`string`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `identityBaseField` (`string`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `skipKid` (`boolean`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `policyFieldName` (`string`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `clientBaseField` (`string`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `scopes` ([Scopes](#scopes))**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `defaultPolicies` (`[]string`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `issuedAtValidationSkew` (`uint64`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `notBeforeValidationSkew` (`uint64`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `expiresAtValidationSkew` (`uint64`)**
needs a description

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
```suggestion
IDPClientIDMappingDisabled prevents Tyk from automatically detecting the use of certain IDPs based on standard claims that they include in the JWT: `client_id`, `cid`, `clientId`. Setting this flag to `true` disables the mapping and avoids accidentally misidentifying the use of one of these IDPs if one of their standard values is configured in your JWT.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the mock response middleware.
Default?

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `headers` ([[]Header](#header))**
does this require combined array links for []T?

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +OAS holds the upstream OAS definition as well as adds functionality like custom JSON marshalling.
Noted OAS is a known issue and to skip. Suggesting description as follows

```suggestion
OAS configures the upstream OAS definition and adds functionality like custom JSON marshalling type defined as ``, see []() definition.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `enabled` (`boolean`)**
description to add and what is default value

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `allowedAuthorizeTypes` (`[]osin.AuthorizeRequestType`)**
description to add and should combined array links be added

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `refreshToken` (`boolean`)**
description to add and default value mention

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `authLoginRedirect` (`string`)**
description to add

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `notifications` ([Notifications](#notifications))**
description to add

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +TransformRequestHeaders allows you to transform request headers.
```suggestion
TransformRequestHeaders allows you to configure transforming request headers.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +TransformResponseHeaders allows you to transform response headers.
```suggestion
TransformRequestHeaders allows you to configure transforming response headers.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Operation holds a request operation configuration, allowances, tranformations, caching, timeouts and validation.
Are the fields for allowances, timeouts and validation described in this sentence included here for Operation?

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Path**
Noted after discussing in slack thread, skipping Path. Descriptions need adding for fields

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
>  ### **Operation**
Not sure if this relates to Operations section that should be skipped for now. Just in case I have reviewed this section

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
Noted in slack discussion to skip Paths section

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Plugins configures common settings for each plugin, allowances, transforms, caching and timeouts.
```suggestion
Plugins configures common settings for each plugin. This includes: allowances, transforms, caching and timeouts.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **SecurityScheme**
Noted in slack thread discussion to skip SecurityScheme section for now

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Signature**
Description needed for the fields in this section

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Token holds the values related to authentication tokens.
```suggestion
Token allows configuration related to authentication tokens.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the token based authentication mode.
does it have a default value?

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition: `auth_configs["authToken"].use_standard_auth`.
is this the correct config param name? could it be renamed to _auth_configs["authToken"].enable_ if not yet released?

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +EnableClientCertificate allows to create dynamic keys based on certificates.
```suggestion
EnableClientCertificate allows dynamic keys to be created from certificates.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Signature holds the configuration for verifying the signature of the token.
```suggestion
Signature allows configuration for how to verify the signature of the token.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables Method Transform for the given path and method.
default value?

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +TykExtensionConfigParams holds the essential configuration required for the Tyk Extension schema.
maybe add an explanation of ehat the Tyk extension schema is and link to existing content if present

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `UpstreamURL` (`string`)**
description to add

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **TykExtensionConfigParams**
descriptions to add for the fields in this section

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
```suggestion
ErrorResponseCode is the error code emitted when the request fails validation.
If unset or zero, a response will be returned with HTTP status 422 Unprocessable Entity.
```

2024-01-18 12:53 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **EndpointPostPlugin**
Should this be removed?

2024-01-18 14:24 UTC, letzya commented on tyk-docs/assets/others/gateway-swagger.yml
> +  version: 5.2.0
@titpetric out of interest, how come the version in the docs is 5.2.3 and your version is 5.2.0? which branch is this from?

2024-01-18 18:54 UTC, jeffy-mathew commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Operations holds Operation definitions.
do we need to mention that the value of key in this map is the `operationId` in OAS to identify the endpoint + method?

also `Operations` is not `map[string]interface{}`, it's `map[string]*Operation` https://github.com/TykTechnologies/tyk/blob/master/apidef/oas/operation.go#L15

2024-01-19 11:24 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition: `auth_configs["authToken"].use_standard_auth`.
Out of scope, this is released/preexisting (most of the docs are).

2024-01-19 11:44 UTC, titpetric commented on tyk-docs/assets/others/gateway-swagger.yml
> +  version: 5.2.0
@letzya this is from `master`, the docs updates are usually from the release branch (release-5.2 has 5.2.4 on it at the moment). Ignore it.

2024-01-19 11:52 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `dbId` (`model.ObjectID`)**
Fixed to be `string` (several other examples of the same kind).

2024-01-19 11:56 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **EndpointPostPlugin**
not removed, it's moved.

2024-01-19 12:09 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Operations holds Operation definitions.
@jeffy-mathew fixed the docgen for the operations type, operationId issue noted in https://tyktech.atlassian.net/browse/TT-11034

2024-01-19 12:52 UTC, titpetric commented
The issues related to the documentation generation have been addressed (x-tyk-gateway docs and config docs for all).

Additional issues filed for documentation improvements:

- https://tyktech.atlassian.net/browse/TT-11034
- https://tyktech.atlassian.net/browse/TT-11032

Closing this PR as it was available only for testing the updates to the various documentation generators and the changes required to build valid docs. Thank you @dcs3spp for your review time.

2024-01-19 12:52 UTC, closed without merging