[TT-11018]add API templates docs
TykTechnologies/tyk-docs-hugo pull request #3942
Opened 2024-01-18 11:23 UTC by jeffy-mathew

### For internal users - Please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/TT-11018

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-02-13 11:20 UTC, dcs3spp requested changes
PR LGTM, suggested minor changes

2024-02-13 11:20 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/templates.md
> +API Templates is a new feature designed to streamline the process of defining APIs using the OpenAPI Specification (OAS). These templates serve as a foundational or default structure for various segm
```suggestion
API Templates are a new feature designed to streamline the process of defining APIs using the OpenAPI Specification (OAS). These templates provide a default structure for various segments of an OAS API definition, enhancing the efficiency and consistency of API creation and importation.
```

2024-02-13 11:20 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/templates.md
> +To create an API template use `/api/assets` dashboard endpoint to create an Asset of kind `oas-template`.
Should maybe add a link to the endpoint here when available, or add a link to the Dashboard OAS API?

```suggestion
To create an API template use the `/api/assets` dashboard endpoint to create an *Asset* of kind `oas-template`.
```

2024-02-13 11:20 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/templates.md
> +    * For maps like OAS paths and different components, keys are added alongside existing ones in the template, if there are any key already existing in the template, they are replaced (request paylo
```suggestion
    - For maps like OAS paths and different components, keys are added alongside existing ones in the template, if a key already exists in the template, it is replaced (request payload has precedence).
```

2024-02-13 11:20 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/templates.md
> +    "data": {
So the data payload of an oas-template is the schema. Maybe this should be mentioned firstly in the introduction overview before a full example is given. Could we make the example collapsible using summary detail html tags to reduce example length?

2024-02-13 11:20 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/templates.md
> +Now, let's use this template while importing an OAS document. Let's use a petstore OAS example here.
Not sure if my understanding is correct so checking

When the oas-template is applied when importing an OAS document, then the endpoints and x-tyk-api-gateway definition are applied to the target OAS API? 

If so, then could mention/expand upon this in the introduction/overview section, before the reader gets to the example.

The benefit is that this same template can be applied to multiple OAS APIs, applying the endpoint paths in and x-tyk-api-gateway definition to the template.

2024-02-13 11:20 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/templates.md
> +
Summarise what the example has done here. Maybe make the example content expandable/collapsible using _html_ summary and _detail_ tags in the markdown

2024-02-26 12:03 UTC, titpetric commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/templates.md
> +API Templates is a new feature designed to streamline the process of defining APIs using the OpenAPI Specification (OAS). These templates serve as a foundational or default structure for various segm
API Templates *are* a new feature...?

2024-02-26 12:08 UTC, titpetric commented
Some plain language comments raised with write-good (vale):

```
 templates.md
 5:15    suggestion  Try to avoid using 'is'.        write-good.E-Prime  
 10:60   warning     'be applied' may be passive     write-good.Passive  
                     voice. Use active voice if you                      
                     can.                                                
 10:60   suggestion  Try to avoid using 'be'.        write-good.E-Prime  
 11:50   suggestion  Try to avoid using 'are'.       write-good.E-Prime  
 21:85   suggestion  Try to avoid using 'be'.        write-good.E-Prime  
 23:62   suggestion  Try to avoid using 'are'.       write-good.E-Prime  
 23:62   warning     'are added' may be passive      write-good.Passive  
                     voice. Use active voice if you                      
                     can.                                                
 23:122  suggestion  Try to avoid using 'are'.       write-good.E-Prime  
 23:134  warning     'already existing' is too       write-good.TooWordy 
                     wordy.                                              
 23:173  suggestion  Try to avoid using 'are'.       write-good.E-Prime  
 23:173  warning     'are replaced' may be passive   write-good.Passive  
                     voice. Use active voice if you                      
                     can.                                                
 25:68   warning     'it is' is too wordy.           write-good.TooWordy 
 25:71   suggestion  Try to avoid using 'is'.        write-good.E-Prime  
 27:290  suggestion  Try to avoid using 'is'.        write-good.E-Prime  
 596:88  suggestion  Try to avoid using 'being'.     write-good.E-Prime  
 600:13  suggestion  Try to avoid using 'are'.       write-good.E-Prime  
 600:28  warning     'only' is a weasel word!        write-good.Weasel   
 600:92  suggestion  Try to avoid using 'be'.        write-good.E-Prime  
 600:92  warning     'be applied' may be passive     write-good.Passive  
                     voice. Use active voice if you                      
                     can.                                                

✖ 0 errors, 7 warnings and 12 suggestions in 1 file.
```

I'd say out of this the main issue is that we should be using active voice, and reword some things like `how many items returned` to `the number of items returned` for clarity.

Do we have a better strategy for providing the example jsons? Can we stick that into it's own files and just link them? Use `curl -d @file.json` in the examples? It makes no sense to inline the full assets into the docs.

2024-03-07 12:16 UTC, andyo-tyk commented
I have reworked this PR - @jeffy-mathew @titpetric @dcs3spp please would you review again? 🙏 
The starting point for the preview is here: https://deploy-preview-3942--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview/

2024-03-07 13:11 UTC, dcs3spp requested changes
Thanks for updating the API templates docs @andyo-tyk , I have submitted second review with minor suggestions

2024-03-07 13:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview.md
> +An API template is a blueprint from which you can build new APIs - it is an incomplete Tyk OAS API definition JSON that you can use as the starting point when creating a new API on Tyk. There is no l
```suggestion
An API template is a blueprint from which you can build new APIs - it is an incomplete JSON representation of a Tyk OAS API definition that you can use as the starting point when creating a new API on Tyk. There is no limit to how much or how little of the API definition is pre-configured in the template (such that when you choose to create a new API without choosing a template, the blank API definition that you start from is itself a template).
```

2024-03-07 13:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-designer.md
> + - [Managing templates]({{< ref "product-stack/tyk-dashboard/advanced-configurations/templates/template-designer#" >}})
```suggestion
 - [Managing templates]({{< ref "product-stack/tyk-dashboard/advanced-configurations/templates/template-designer#managing-templates" >}})
```

2024-03-07 13:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-designer.md
> +From the **Import API** screen, if you select the OpenAPI **type** then you can create an API from an OpenAPI description or Tyk OAS API definition that you paste into the API Designer, or that is re
```suggestion
From the **Import API** screen, if you select the OpenAPI **type** then you can create an API using:
- OpenAPI description or Tyk OAS API definition that you paste into the API Designer
- A file that is either uploaded to Tyk Dashboard or accessed from a URL
```

2024-03-07 13:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-designer.md
> +You can delete a template from your Tyk Dashboard from the **API Template Details** screen, which you can access by selecting the template from the **API Templates** screen (either by clicking on the
```suggestion
You can delete a template from your Tyk Dashboard from the **API Template Details** screen. This screen can be accessed by selecting the template from the **API Templates** screen (either by clicking on the template name, or selecting **EDIT TEMPLATE** from the **ACTIONS** menu):
{{< img src="/img/dashboard/api-assets/api-templates/edit-template.png" alt="Accessing the API template" >}} 
```

2024-03-07 13:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-api.md
> + - `id`: a unique string type identifier for the template
```suggestion
 - `id`: a unique string type identifier for the template that can be autogenerated or specified by the user
```

2024-03-07 13:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview.md
> + - `id`: a unique string type identifier for the template
```suggestion
- `id`: a unique string type identifier for the template that can be autogenerated or specified by the user
```

2024-03-07 13:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview.md
> +When you use a template during the creation of an API where you [import]({{< ref "getting-started/using-oas-definitions/import-an-oas-api" >}}) the OpenAPI document or a full Tyk OAS API definition,
```suggestion
When you use a template during the creation of an API where you [import]({{< ref "getting-started/using-oas-definitions/import-an-oas-api" >}}) the OpenAPI document or a full Tyk OAS API definition, the template is combined with the imported OAS description. If the `x-tyk-api-gateway` extension exists in the template, it will be applied to the newly created API.
```

2024-03-07 13:18 UTC, dcs3spp commented
> I have reworked this PR - @jeffy-mathew @titpetric @dcs3spp please would you review again? 🙏 The starting point for the preview is here: https://deploy-preview-3942--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview/

@andyo-tyk I've submitted a second review

2024-03-18 12:19 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview.md
> +### Merging with an OpenAPI description or Tyk OAS API definition
Shall we name it `OpenAPI document` instead of `OpenAPI description`?

2024-03-18 13:05 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-api.md
> +You'll need to identify the template to be used during the import. You can use either its unique `id` or the database ID that was assigned when the template was [registered with Tyk Dashboard]({{< re
```suggestion
You'll need to identify the template to be used during the import. You can use either its unique `id` or the database ID that was assigned when the template was [registered with Tyk Dashboard]({{< ref "product-stack/tyk-dashboard/advanced-configurations/templates/template-api#registering-a-template-with-tyk-dashboard" >}}). You provide either the `id` or `_id ` in the `templateID` query parameter in the call to `/oapis/oas/import`.
```

2024-03-18 13:11 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-api.md
> + - `DBID`: a unique identifier assigned by Tyk when the template is registered in the Dashboard database
```suggestion
 - `_id`: a unique identifier assigned by Tyk when the template is registered in the Dashboard database
```

`_id` is the field that is used in json response for DB ID

2024-03-18 13:12 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview.md
> + - `DBID`: a unique identifier assigned by Tyk when the template is registered in the Dashboard database
```suggestion
 - `_id`: a unique identifier assigned by Tyk when the template is registered in the Dashboard database
```

2024-03-18 13:13 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-api.md
> +You'll need to identify the template to be used during the import. You can use either its unique `id` or the database ID that was assigned when the template was [registered with Tyk Dashboard]({{< re
```suggestion
You'll need to identify the template to be used during the import. You can use either its unique `id` or the database ID that was assigned when the template was [registered with Tyk Dashboard]({{< ref "product-stack/tyk-dashboard/advanced-configurations/templates/template-api#registering-a-template-with-tyk-dashboard" >}}). You provide either the `id` or `_id` in the `templateID` query parameter in the call to `/apis/oas`.
```

2024-03-19 11:37 UTC, dcs3spp commented
@andy I've resolved most comments apart from two suggestion comments [https://github.com/TykTechnologies/tyk-docs/pull/3942#discussion_r1516105273](https://github.com/TykTechnologies/tyk-docs/pull/3942#discussion_r1516105273) and [https://github.com/TykTechnologies/tyk-docs/pull/3942#discussion_r1516101045](https://github.com/TykTechnologies/tyk-docs/pull/3942#discussion_r1516101045)

2024-03-28 16:23 UTC, andyo-tyk reviewed
Improved wording

2024-03-28 16:23 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-designer.md
> +From the **Import API** screen, if you select the OpenAPI **type** then you can create an API from an OpenAPI description or Tyk OAS API definition that you paste into the API Designer, or that is re
```suggestion
From the **Import API** screen, if you select the OpenAPI **type** then you can create an API from an OpenAPI description or Tyk OAS API definition; choose the appropriate method to provide this to the Dashboard:
- paste the JSON into the text editor
- provide a plain text file containing the JSON
- provide a URL to the JSON
```

2024-03-28 16:23 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview.md
> +### Merging with an OpenAPI description or Tyk OAS API definition
No, this is deliberate: the description is the JSON, the document is the file containing the description

2024-03-28 16:26 UTC, andyo-tyk approved these changes

2024-03-28 17:01 UTC, dcs3spp approved these changes

2024-03-28 17:02 UTC, merged