Improved-URL-rewrite
TykTechnologies/tyk-docs-hugo pull request #3943
Opened 2024-01-18 11:35 UTC by andyo-tyk

DX ticket number to follow

---

### Preview Link

<br>

### Description
Improved the URL rewrite explanation, added Tyk OAS instructions, pending a video demonstration of the new UI

2024-01-18 16:27 UTC, dcs3spp requested changes
Andy, this is really detailed thanks!!!!! I have reviewed through content first and then will try to identify why CI check has error

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Tyk's [URL rewrite]({{< ref "/transform-traffic/url-rewriting" >}}) middleware uses the concepts of [triggers](#url-rewrite-triggers) and [rules](#url-rewrite-rules) to determine if the request (targ
```suggestion
Tyk's [URL rewrite]({{< ref "transform-traffic/url-rewriting" >}}) middleware uses the concepts of [triggers](#url-rewrite-triggers) and [rules](#url-rewrite-rules) to determine if the request (target) URL should be modified. These can be combined in flexible ways to create sophisticated logic to direct requests made to a single endpoint to various upstream services (or other APIs internally exposed within Tyk through [looping]({{< ref "advanced-configuration/transform-traffic/looping" >}})).
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +The key value is the content of a field in some element of the request; as such each key has a location (which element of the request) and a name (the name of the field within that element). For exam
Found this difficult to understand. Maybe the explanation of key location and example locations should appear first in this paragraph and then conclude the paragraph with the book example.

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Note that there is no key name when using the request body location, as the entire body (payload) of the request is used as the key value.
Maybe add sub section headings for these paragraphs and give an example request and result for each 

##### Request Body

##### Request Header

##### Request Path

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +When using the request header location, the key name is the normalised form of the header name: with capitalisation and use of `-` as separator. For example, the header name`customer_identifier` woul
```suggestion
When using the request header location, the key name is the normalised form of the header name: with capitalisation and use of `-` as separator. For example, the header name `customer_identifier` would be identified in a rule via the key name `Customer-Identifier`.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - [Context variables]({{< ref "/context-variables" >}}), extracted from the request at the start of the middleware chain, can be injected into the pattern regex using the `$tyk_context.` namespace
```suggestion
 - [Context variables]({{< ref "context-variables" >}}), extracted from the request at the start of the middleware chain, can be injected into the pattern regex using the `$tyk_context.` namespace
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +   - Note that you need to enable context variables for the API to be able to access them from the URL rewrite middleware
```suggestion
   - Note that you need to enable context variables for the API to be able to access them from the URL rewrite middleware.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - [Session metadata]({{< ref "/getting-started/key-concepts/session-meta-data" >}}), from the Tyk Session Object linked to the request, can be injected into the pattern regex using the `$tyk_meta.ME
```suggestion
 - [Session metadata]({{< ref "getting-started/key-concepts/session-meta-data" >}}), from the Tyk Session Object linked to the request, can be injected into the pattern regex using the `$tyk_meta.METADATA_KEY` namespace.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Percent-encoded (URL-encoded) characters can be used in the pattern regex when the key is the request path or path parameter
```suggestion
Percent-encoded (URL-encoded) characters can be used in the pattern regex when the key location is the request path or path parameter
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - request path / path parameter (i.e. components of the path itself)
Maybe have these as 2 different list items:

_- request path, e.g. /apis/books/
- request path parameter, e.g. /apis/books/11_

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - If the middleware is called with percent-encoded characters in the key, matching will first be attempted using the raw URL as provided
```suggestion
 - If the middleware is called with percent-encoded characters in the key, matching will first be attempted using the raw URL as provided.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - If there is no match, the percent-encoded characters will be replaced with their non-encoded form (e.g. `%2D` -> `-`) and checked again
```suggestion
 - If there is no match, the percent-encoded characters will be replaced with their non-encoded form (e.g. `%2D` -> `-`) and checked again.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Tyk does not check all combinations of encoded and decoded characters in the same string (so `my-test%2Durl` will only be checked as `my-test%2Durl` and `my-test-url`, it will not be checked against
```suggestion
Tyk does not check all permutations of encoded and decoded characters in the same string (so `my-test%2Durl` will only be checked as `my-test%2Durl` and `my-test-url`, it will not be checked against `my%2Dtest%2Durl` or `my%2Dtest-url`).
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +One or more advanced triggers can be configured alongside the basic trigger. These are processed in the order that they are defined in the API Definition. When using the API Designer in Tyk Dashboard
```suggestion
One or more advanced triggers can be configured alongside the basic trigger. These are processed in the order that they are defined in the API Definition. When using the API Designer in Tyk Dashboard, advanced triggers are automatically numbered in the order they are created and will be processed in numerical order.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +#### Advanced triggers
For this section is there existing example that can be linked to or can add example APIDefinition and screenshot to show what an advanced trigger looks like?

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Within advanced triggers, but not the basic trigger, each rule can be negated such that the rule is considered to have passed if the pattern does not match the key value.
What is an example of a rule negated?

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Each trigger (basic or advanced) defines a `rewriteTo` target.
Could this be summarised in a table below this paragraph and an example of rewriteTo values

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +
Maybe add subsection headings for basic and advanced triggers

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - For example, if the `pattern` to be matched is `""(\w+)/(\w+)"` then the regex will attempt to capture two word groups. The first of these will be given index 1 and the second will be index 2. You
Is there a full existing example that can be linked to or added that uses rewrite rules for basic trigger and advanced trigger

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +Tyk's [URL rewriter]({{< ref "/transform-traffic/url-rewriting" >}}) uses the concepts of triggers and rules to determine if the request (target) URL should be modified. These can be combined in flex
```suggestion
Tyk's [URL rewriter]({{< ref "transform-traffic/url-rewriting" >}}) uses the concepts of triggers and rules to determine if the request (target) URL should be modified. These can be combined in flexible ways to create sophisticated logic to direct requests made to a single endpoint to various upstream services (or other APIs internally exposed within Tyk).
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +URL rewrite triggers and rules are explained in detail [here]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}).
```suggestion
URL rewrite triggers and rules are explained in detail [here]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}).
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +If you're using the newer Tyk OAS APIs, then check out [this]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}) page.
```suggestion
If you're using the newer Tyk OAS APIs, then check out the [url-rewrite-tyk-oas]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}) page.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> + - pattern is fiction
also refer to match_rx in example?

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +Tyk's [URL rewriter]({{< ref "/transform-traffic/url-rewriting" >}}) uses the concepts of triggers and rules to determine if the request (target) URL should be modified. These can be combined in flex
```suggestion
Tyk's [URL rewriter]({{< ref "transform-traffic/url-rewriting" >}}) uses the concepts of triggers and rules to determine if the request (target) URL should be modified. These can be combined in flexible ways to create sophisticated logic to direct requests made to a single endpoint to various upstream services (or other APIs internally exposed within Tyk).
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +URL rewrite triggers and rules are explained in detail [here]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}).
```suggestion
URL rewrite triggers and rules are explained in detail [here]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}).
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +When working with Tyk OAS APIs the rules and triggers are configured in the [Tyk OAS API Definition]({{< ref "/tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually wi
```suggestion
When working with Tyk OAS APIs the rules and triggers are configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +If you're using the legacy Tyk Classic APIs, then check out [this]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic" >}}) page.
```suggestion
If you're using the legacy Tyk Classic APIs, then check out the [url-rewrite-tyk-classic]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic" >}}) page.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +The URl rewrite middleware can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appropriate `operationId` (as configured in t
```suggestion
The URL rewrite middleware can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appropriate `operationId` (as configured in the `paths` section of your OpenAPI Document).
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +For the basic trigger, you only need to enable the middleware (set `enabled:true`) and then configure the `pattern` and the `rewriteTo` (target) URL. The design of the Tyk OAS API Definition takes ad
Maybe add link to opeationID in OAS schema page https://swagger.io/specification/

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +< placeholder for video >
remember to add the link to the video

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/shared/api-def-version.md
> +* `version_data.{version-name}.extended_paths.url_rewrites`: Configuration for the [URL rewrite]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}) middleware.
```suggestion
* `version_data.{version-name}.extended_paths.url_rewrites`: Configuration for the [URL rewrite]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}) middleware.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +API requests can be redirected to other endpoints or APIs deployed on Tyk using the URL rewrite functionality. This allows requests to be redirected to internal APIs that are not directly exposed on
```suggestion
API requests can be redirected to other endpoints or APIs deployed on Tyk using the URL rewrite functionality. This allows requests to be redirected to internal APIs that are not directly exposed on the Gateway (for example to reduce complexity of the external interface or to perform additional processing or security checks before reaching sensitive upstream APIs). We refer to this practice as [looping]({{< ref "advanced-configuration/transform-traffic/looping" >}}). By performing the looping internally using the URL rewrite middleware, latency is reduced because the redirection is handled entirely within Tyk with no unnecessary external network calls.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +Tyk's URL rewrite middleware uses the concepts of [triggers]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-middleware#url-rewrite-triggers" >}}) and [rules]({{< ref "/product-stack/tyk-g
```suggestion
Tyk's URL rewrite middleware uses the concepts of [triggers]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-middleware#url-rewrite-triggers" >}}) and [rules]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-middleware#url-rewrite-rules" >}}). These can be combined in flexible ways to create sophisticated logic to direct requests made to a single endpoint to various upstream services (or other APIs internally exposed within Tyk).
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +More detail on URL Rewrite triggers and rules can be found [here]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}).
```suggestion
More detail on URL Rewrite triggers and rules can be found by consulting the [url-rewrite-middleware]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}) section.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +If you're using Tyk OAS APIs, then you can find details and examples of how to configure the URL rewrite middleware [here]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}).
```suggestion
If you're using Tyk OAS APIs, then you can find details and examples of how to configure the URL rewrite middleware in the [url-rewrite-tyk-oas]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}) section.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +If you're using Tyk Classic APIs, then you can find details and examples of how to configure the URL rewrite middleware [here]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic"
```suggestion
If you're using Tyk Classic APIs, then you can find details and examples of how to configure the URL rewrite middleware [url-rewrite-tyk-classic]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic" >}}) section.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +<!-- proposed "summary box" to be shown graphically on each middleware page
Is this a todo comment?

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> + - The URL Rewrite middleware is an optional stage in Tyk's API Request processing chain, sitting between the [Request Header Transform]({{< ref "/transform-traffic/request-headers" >}}) and [Respons
```suggestion
 - The URL Rewrite middleware is an optional stage in Tyk's API Request processing chain, sitting between the [Request Header Transform]({{< ref "transform-traffic/request-headers" >}}) and [Response Caching]({{< ref "basic-config-and-security/reduce-latency/caching" >}}) middleware.
```

2024-01-18 16:27 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> + - URL Rewrite can access both [session metadata]({{< ref "/getting-started/key-concepts/session-meta-data" >}}) and [request context variables]({{< ref "/context-variables" >}}).
```suggestion
 - URL Rewrite can access both [session metadata]({{< ref "getting-started/key-concepts/session-meta-data" >}}) and [request context variables]({{< ref "context-variables" >}}).
```

2024-01-18 19:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - request path / path parameter (i.e. components of the path itself)
We're documenting the behaviour, not defining it.

2024-01-18 20:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +   - Note that you need to enable context variables for the API to be able to access them from the URL rewrite middleware
I'm consistent: there's no full stop on any of the other bullet points.
Is Tyk style to ensure that all bullets are full sentences complete with full stop?

2024-01-18 20:04 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +#### Advanced triggers
No! The structure of these docs is deliberate: we now have two different API Definitions with different field names and ways to configure the middleware. We cannot have example APIDefs or screenshots here - they are not required if the explanation is good enough. Later I would like to bring in the content team to add some imagery, however don't have time right now.

2024-01-18 20:05 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Within advanced triggers, but not the basic trigger, each rule can be negated such that the rule is considered to have passed if the pattern does not match the key value.
It means that the rule is "true" if the pattern does NOT match the key value.

2024-01-18 20:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Each trigger (basic or advanced) defines a `rewriteTo` target.
I don't think it's necessary for just three options, then I think we'd need the table AND an explanation of the table. There are examples in the sub-pages for Tyk Classic and Tyk OAS.

2024-01-18 20:09 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - [Session metadata]({{< ref "/getting-started/key-concepts/session-meta-data" >}}), from the Tyk Session Object linked to the request, can be injected into the pattern regex using the `$tyk_meta.ME
```suggestion
 - [Session metadata]({{< ref "getting-started/key-concepts/session-meta-data" >}}), from the Tyk Session Object linked to the request, can be injected into the pattern regex using the `$tyk_meta.METADATA_KEY` namespace 
```

2024-01-18 20:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - For example, if the `pattern` to be matched is `""(\w+)/(\w+)"` then the regex will attempt to capture two word groups. The first of these will be given index 1 and the second will be index 2. You
That will be covered in the Tyk Classic/Tyk OAS sub-pages.

2024-01-18 20:13 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +If you're using the newer Tyk OAS APIs, then check out [this]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}) page.
```suggestion
If you're using the newer Tyk OAS APIs, then check out the [Tyk OAS]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}) page.
```

2024-01-18 20:14 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> + - key location is query parameter
```suggestion
 - key location is query parameter (`query_val_matches`)
```

2024-01-18 20:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> + - pattern is fiction
```suggestion
 - pattern  (`match_rx`) is fiction
```

2024-01-18 20:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> + - key name is genre
```suggestion
 - key name is "genre"
```

2024-01-18 20:16 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +    - pattern is `true``
```suggestion
    - pattern (`match_rx`) is `true``
```

2024-01-18 20:16 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +    - pattern is `true`
```suggestion
    - pattern (`match_rx`) is `true`
```

2024-01-18 20:17 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +    - key location is header parameter
```suggestion
    - key location is header parameter (`header_val_matches`)
```

2024-01-18 20:17 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +    - key location is session metadata
```suggestion
    - key location is session metadata (`session_meta_matches`)
```

2024-01-18 20:19 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +If you're using the legacy Tyk Classic APIs, then check out [this]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic" >}}) page.
```suggestion
If you're using the legacy Tyk Classic APIs, then check out the [Tyk Classic]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic" >}}) page.
```

2024-01-18 20:20 UTC, andyo-tyk commented on tyk-docs/content/shared/api-def-version.md
> +* `version_data.{version-name}.extended_paths.url_rewrites`: Configuration for the [URL rewrite]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}) middleware.
I don't know if this file is auto-generated from godocs... @titpetric, do you know?

2024-01-18 20:22 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +More detail on URL Rewrite triggers and rules can be found [here]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}).
```suggestion
More detail on URL Rewrite triggers and rules can be found by consulting the [URL Rewrite middleware]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}) section.
```

2024-01-18 20:22 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +If you're using Tyk OAS APIs, then you can find details and examples of how to configure the URL rewrite middleware [here]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}).
```suggestion
If you're using Tyk OAS APIs, then you can find details and examples of how to configure the URL rewrite middleware in the [Tyk OAS]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}) section.
```

2024-01-18 20:23 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +<!-- proposed "summary box" to be shown graphically on each middleware page
Yes

2024-01-18 20:25 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +If you're using Tyk Classic APIs, then you can find details and examples of how to configure the URL rewrite middleware [here]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic"
```suggestion
```

I think it's better to just combine them.

2024-01-18 20:33 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +The key value is the content of a field in some element of the request; as such each key has a location (which element of the request) and a name (the name of the field within that element). For exam
```suggestion
Each key has a _location_ (which indicates an element of the request),  most also have a _name_ (the name of the field within that element); the key value is the content of that field. For example, given the request `GET /asset?type=book&condition=new` if key _location_ is `query parameter` and the key _name_ is `type`, the key value would be `book`.
```

2024-01-18 20:34 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Note that there is no key name when using the request body location, as the entire body (payload) of the request is used as the key value.
I don't think this is required and might just lead to bloating of the content on the page. Would appreciate opinions from other reviewers.

2024-01-18 20:37 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +
Again, I'm not sure these are required and might just add to the visual clutter.

2024-01-18 20:42 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +For the basic trigger, you only need to enable the middleware (set `enabled:true`) and then configure the `pattern` and the `rewriteTo` (target) URL. The design of the Tyk OAS API Definition takes ad
```suggestion
For the basic trigger, you only need to enable the middleware (set `enabled:true`) and then configure the `pattern` and the `rewriteTo` (target) URL. The design of the Tyk OAS API Definition takes advantage of the `operationID` [defined in the OpenAPI Document]({{< ref "getting-started/key-concepts/paths#operation-id" >}}) that declares both the path and method required by the basic trigger.
```

2024-01-19 12:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +You can use the API Designer in the Tyk Designer to configure the URL rewrite middleware for your Tyk Classic API by following these steps.
```suggestion
You can use the API Designer in the Tyk Dashboard to configure the URL rewrite middleware for your Tyk Classic API by following these steps.
```

2024-01-20 10:23 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +The URl rewrite middleware can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appropriate `operationId` (as configured in t
```suggestion
The URl rewrite middleware (`urlRewrite`) can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appropriate `operationId` (as configured in the `paths` section of your OpenAPI Document).
```

2024-01-20 10:24 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +The URL rewrite middleware can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appropriate `operationId` (as configured in t
```suggestion
The URL rewrite middleware (`urlRewrite`) can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appropriate `operationId` (as configured in the `paths` section of your OpenAPI Document).
```

2024-01-23 11:49 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +   - Note that you need to enable context variables for the API to be able to access them from the URL rewrite middleware
```suggestion
```

Moving this to a "note" box

2024-01-23 11:49 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +
```suggestion

{{< note success >}}
**Note**  

When using Tyk Classic APIs, you must enable context variables for the API to be able to access them from the URL rewrite middleware. When using Tyk OAS APIs, the context variables are always available to the URL rewriter.
{{< /note >}}

```

2024-01-23 13:08 UTC, dcs3spp requested changes
PR LGTM after changes. I've fixed the CI checks, resolved comments and suggested minor changes relating to linking to Tyk Classic and Tyk OAS URL rewrite pages for further examples and removing H2 Overview headings.

2024-01-23 13:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +When using Tyk Classic APIs, you must enable context variables for the API to be able to access them from the URL rewrite middleware. When using Tyk OAS APIs, the context variables are always availab
Add links to how to enable context variables for Tyk Classic APIs.
- https://tyk.io/docs/tyk-apis/tyk-gateway-api/api-definition-objects/other-root-objects/
- https://tyk.io/docs/context-variables/#enable-context-variables

```suggestion
When using Tyk Classic APIs, you must enable context variables for the API to be able to access them from the URL rewrite middleware. Context variables can be enabled in the [Tyk Gateway]({{< ref "tyk-apis/tyk-gateway-api/api-definition-objects/other-root-objects" >}}) configuration file and via [Tyk Dashboard]({{< ref "context-variables#enable-context-variables" >}}). When using Tyk OAS APIs, the context variables are always available to the URL rewriter.
```

2024-01-23 13:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - For example, if the `pattern` to be matched is `""(\w+)/(\w+)"` then the regex will attempt to capture two word groups. The first of these will be given index 1 and the second will be index 2. You
```suggestion
 - For example, if the `pattern` to be matched is `""(\w+)/(\w+)"` then the regex will attempt to capture two word groups. The first of these will be given index 1 and the second will be index 2. You can reference these in the `rewriteTo` target using `$1` and `$2` such as: `"my/service?value1=$1&value2=$2"`. For further details consult the URL rewrite examples for [Tyk Classic APIs]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic" >}}) and [Tyk OAS APIs]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}})
```

2024-01-23 13:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - For example, if the first trigger fires based on a rule where the key is the query parameter "type", a context variable with the name `trigger-0-type-0` will be created and can be referenced in th
```suggestion
 - For example, if the first trigger fires based on a rule where the key is the query parameter "type", a context variable with the name `trigger-0-type-0` will be created and can be referenced in the `rewriteTo` target. For further details consult the URL rewrite examples for [Tyk Classic APIs]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic" >}}) and [Tyk OAS APIs]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}})
```

2024-01-23 13:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +## Overview
Remove H2 heading so that have page title, intro paragraph and section titles

2024-01-23 13:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +## Overview
Remove H2 heading so that have page title, intro paragraph and section titles

2024-01-23 13:08 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +## Overview of URL Rewriting
Remove H2 heading so have page title, intro paragraph and section headings

2024-01-23 13:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +## Overview
Remove H2 heading so have page title, intro paragraph and section headings

2024-01-23 13:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +If you're using the newer Tyk OAS APIs, then check out the [Tyk OAS]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}) page.
```suggestion
If you're using the newer Tyk OAS APIs, then check out the [Tyk OAS]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas" >}}) page.
```

2024-01-23 13:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +If you're using the legacy Tyk Classic APIs, then check out the [Tyk Classic]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic" >}}) page.
```suggestion
If you're using the legacy Tyk Classic APIs, then check out the [Tyk Classic]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic" >}}) page.
```

2024-01-23 13:12 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +More detail on URL Rewrite triggers and rules can be found by consulting the [URL Rewrite middleware]({{< ref "/product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}) section.
```suggestion
More detail on URL Rewrite triggers and rules can be found by consulting the [URL Rewrite middleware]({{< ref "product-stack/tyk-gateway/middleware/url-rewrite-middleware" >}}) section.
```

2024-01-23 16:30 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +## Overview
The reason for this is that it then appears in the right hand menu for easy navigation within the page

2024-01-23 16:32 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +When using Tyk Classic APIs, you must enable context variables for the API to be able to access them from the URL rewrite middleware. When using Tyk OAS APIs, the context variables are always availab
This is actually only relevant to Tyk Classic APIs, so I'll move the note to the appropriate sub-page.

2024-01-23 16:34 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - For example, if the first trigger fires based on a rule where the key is the query parameter "type", a context variable with the name `trigger-0-type-0` will be created and can be referenced in th
I don't know if this is necessary - I feel it's just going to add bloat: this page is intended to explain the workings of the middleware (which is independent of whether it's Tyk Classic or Tyk OAS).

2024-01-23 16:34 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +## Overview
The reason for this is that it then appears in the right hand menu for easy navigation within the page

2024-01-23 16:34 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +## Overview of URL Rewriting
The reason for this is that it then appears in the right hand menu for easy navigation within the page

2024-01-23 16:34 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +## Overview
The reason for this is that it then appears in the right hand menu for easy navigation within the page

2024-01-23 16:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +
```suggestion

If you want to use dynamic data from context variables, you must [enable]({{< ref "context-variables#enabling-context-variables-for-use-with-tyk-classic-apis" >}}) context variables for the API to be able to access them from the URL rewrite middleware.

```

2024-01-23 16:41 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +{{< note success >}}
```suggestion
```

2024-01-23 16:43 UTC, andyo-tyk reviewed
Move note re: enabling context variables to the Tyk Classic page

2024-01-23 16:43 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +**Note**
```suggestion
```

2024-01-23 16:43 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +
```suggestion
```

2024-01-23 16:43 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +When using Tyk Classic APIs, you must enable context variables for the API to be able to access them from the URL rewrite middleware. When using Tyk OAS APIs, the context variables are always availab
```suggestion
```

2024-01-23 16:43 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +{{< /note >}}
```suggestion
```

2024-01-23 16:49 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> + - For example, if the `pattern` to be matched is `""(\w+)/(\w+)"` then the regex will attempt to capture two word groups. The first of these will be given index 1 and the second will be index 2. You
I don't know if this is necessary - I feel it's just going to add bloat: this page is intended to explain the workings of the middleware (which is independent of whether it's Tyk Classic or Tyk OAS).

2024-01-25 12:00 UTC, dcs3spp reviewed
Thanks @andyo-tyk 

I have resolved comments apart from:
- Overview/intro heading removal
- Placeholder video

I added comments relating to removing H2 overview/intro headings. After DX discussion, thinking was to avoid adjacent page title and overview/intro section heading for improved visual appearance. Have added to the docs Confluence page yesterday
@letzya

2024-01-25 12:00 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +## Overview
> The reason for this is that it then appears in the right hand menu for easy navigation within the page

Thanks @andyo-tyk I added comment since in a previous DX discussion, thinking was to avoid adjacent page title and overview/intro section heading for improved visual appearance. Have added to the docs Confluence page yesterday
@letzya

2024-01-25 13:54 UTC, letzya commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +## Overview of URL Rewriting
```suggestion
```

2024-01-25 13:54 UTC, letzya commented on tyk-docs/data/menu.yaml
> +            - title: "Overview of URL Rewriting"
```suggestion
            - title: "Overview"
```

2024-01-25 14:35 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +## Overview
Understood - thanks for the guidance, I'll remove these from this and the other PRs.

2024-01-25 14:39 UTC, andyo-tyk reviewed
Removing unnecessary H2 headers

2024-01-25 14:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +## Overview
```suggestion
```

2024-01-25 14:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +## Overview
```suggestion
```

2024-01-25 14:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +## Overview
```suggestion
```

2024-01-25 15:38 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          - title: "API specification"
Not sure about this @andyo-tyk @dcs3spp

2024-01-25 16:31 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +
```suggestion

The configurations above are complete and valid Tyk OAS API Definitions that you can import into Tyk to try out the URL rewriter.
```

2024-01-25 16:36 UTC, andyo-tyk commented on tyk-docs/data/menu.yaml
> +          - title: "API specification"
I didn't change this, presume some sort of merge conflict that GH missed? 🤷

2024-01-25 16:37 UTC, andyo-tyk commented on tyk-docs/data/menu.yaml
> +          - title: "API specification"
Agree, this should be OpenAPI document

2024-01-25 16:37 UTC, andyo-tyk commented on tyk-docs/data/menu.yaml
> +          - title: "API specification"
Equally, I didn't add "Environment Variables" below, nothing to do with URL rewrite

2024-01-25 19:05 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          - title: "API specification"
@andyo-tyk thanks. what do you think if we change it to "EDP OpenAPI" or  "EDP OpenAPI Document"

2024-02-02 15:03 UTC, andyo-tyk reviewed
Minor improvements

2024-02-02 15:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +When working with Tyk Classic APIs the rules and triggers are configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashb
```suggestion
When working with Tyk Classic APIs the rules and triggers are configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 15:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +When working with Tyk OAS APIs the rules and triggers are configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually wit
```suggestion
When working with Tyk OAS APIs the rules and triggers are configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-15 16:15 UTC, dcs3spp commented
@andyo-tyk @letzya To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

2024-02-15 16:15 UTC, closed without merging

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +The flexibility of Tyk's URL rewriting mechanism allows for conditional rewrites based on the presence of certain headers or query parameters within the request, ensuring that the rewrite logic is ap
" of certain headers or query parameters within the request" - @andyo-tyk I would suggest to not limit ourselves just to these in the introduction? Maybe adding "and not only"

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Tyk's [URL rewrite]({{< ref "transform-traffic/url-rewriting" >}}) middleware uses the concepts of [triggers](#url-rewrite-triggers) and [rules](#url-rewrite-rules) to determine if the request (targe
`within Tyk` -> maybe we should say Tyk Gateway

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +## URL rewrite rules
I would propose to explain first Triggers concept and then explaining Rules. Just my thought

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +Note that there is no key name when using the request body location, as the entire body (payload) of the request is used as the key value.
should this be highlighted somehow?

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +You can redirect to a new hostname, but to do so you *must* specify the transport, e.g.
Better to say transport protocol, or just protocol, or a fully valid URL

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +```{.json}
@andyo-tyk do we want to provide a fully functional OAS API Definition?

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +```{.json}
```
{
  "info": {
    "title": "Books",
    "version": "1.0.0"
  },
  "openapi": "3.0.3",
  "security": [],
  "paths": {
    "/author": {
      "get": {
        "operationId": "authorget",
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {}
  },
  "x-tyk-api-gateway": {
    "info": {
      "name": "Books",
      "state": {
        "active": true,
        "internal": false
      }
    },
    "middleware": {
      "operations": {
        "authorget": {
          "urlRewrite": {
            "enabled": true,
            "pattern": "(\\w+)/(\\w+)",
            "rewriteTo": "library/service?value1=$1&value2=$2"
          }
        }
      }
    },
    "server": {
      "listenPath": {
        "strip": true,
        "value": "/books/"
      }
    },
    "upstream": {
      "url": "http://httpbin.org/"
    }
  }
}
```

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +```{.json}
This example has loads of syntax errors

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +```{.json}
Adding a complete working OAS API Definition
```
{
  "info": {
    "title": "Books",
    "version": "1.0.0"
  },
  "openapi": "3.0.3",
  "security": [],
  "paths": {
    "/author": {
      "get": {
        "operationId": "authorget",
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {}
  },
  "x-tyk-api-gateway": {
    "info": {
      "name": "Books",
      "state": {
        "active": true,
        "internal": false
      }
    },
    "middleware": {
      "operations": {
        "authorget": {
          "urlRewrite": {
            "enabled": true,
            "pattern": "(\\w+)/(\\w+)",
            "rewriteTo": "library/service?value1=$1&value2=$2",
            "triggers": [
              {
                "condition": "any",
                "rewriteTo": "library/service/author?genre=$tyk_context.trigger-0-genre-0",
                "rules": [
                  {
                    "in": "query",
                    "pattern": "fiction",
                    "negate": false,
                    "name": "genre"
                  }
                ]
              },
              {
                "condition": "all",
                "rewriteTo": "https://beta.library.com/books/author",
                "rules": [
                  {
                    "in": "header",
                    "pattern": "true",
                    "negate": false,
                    "name": "X-Enable-Beta"
                  }
                ]
              }
            ]
          }
        }
      }
    },
    "server": {
      "listenPath": {
        "strip": true,
        "value": "/books/"
      }
    },
    "upstream": {
      "url": "http://httpbin.org/"
    }
  }
}
```

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +< placeholder for video >
@andyo-tyk reminder on this one (should we remove it for now?)

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +            "triggers": [
this has some syntax errors. The triggers part

2024-03-12 08:09 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +            "triggers": [
```
"triggers": [
    {
      "on": "any",
      "options": {
        "query_val_matches": {
          "genre": {
            "match_rx": "fiction",
            "reverse": false
          }
        }
      },
      "rewrite_to": "library/service/author?genre=$tyk_context.trigger-0-genre-0"
    },
    {
      "on": "all",
      "options": {
        "header_matches": {
          "X-Enable-Beta": {
            "match_rx": "true",
            "reverse": false
          }
        },
        "session_meta_matches": {
          "beta_enabled": {
            "match_rx": "true",
            "reverse": false
          }
        }
      },
      "rewrite_to": "https://beta.library.com/books/author"
    }
  ]
```

2024-03-18 16:14 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/url-rewriting.md
> +The flexibility of Tyk's URL rewriting mechanism allows for conditional rewrites based on the presence of certain headers or query parameters within the request, ensuring that the rewrite logic is ap
I'll simplify this - thanks.

2024-03-18 16:16 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
> +## URL rewrite rules
I've ordered it Rules before Triggers because in order to explain what a Trigger does, you have to know what a rule is... but not vice versa. I'd prefer to leave it as-is.

2024-03-19 16:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +```{.json}
I've created a couple of working examples that the reader can copy and paste into Dashboard.

2024-03-19 17:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
> +```{.json}
As for basic trigger, I've created a working Tyk OAS API definition that the user can paste and go

2024-03-19 17:02 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +            "triggers": [
Thanks - updated.

2024-03-19 17:08 UTC, andyo-tyk commented on tyk-docs/data/menu.yaml
> +          - title: "API specification"
We should probably aim for consistency across all the Tyk product APIs.... and at the moment they aren't consistent:
Tyk Gateway (Open Source) > API documentation > Tyk Gateway Open API Documentation
Tyk Dashboard > API documentation > Tyk Dashboard API
Tyk Dashboard > API documentation > Tyk Dashboard Admin API
Tyk Enterprise Developer Portal > API documentation > OpenAPI Document

2024-03-19 17:08 UTC, andyo-tyk commented on tyk-docs/data/menu.yaml
> +          - title: "API specification"
I'll revert the inadvertent change in this PR

2024-03-20 08:52 UTC, andyo-tyk commented
Added screenshots in lieu of video for expediency - will replace these in the future. Shifted focus to https://github.com/TykTechnologies/tyk-docs/pull/4305 due to some conflicts.