Operator-0.17 release
TykTechnologies/tyk-docs-hugo pull request #4011
Opened 2024-01-23 15:42 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-01-23 17:08 UTC, dcs3spp requested changes, later dismissed
Thanks for submitting PR @caroltyk Content looks good, I added some question comments.

Are there any [dependencies / compatibilities](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md#dependencies) that can be added for Tyk Operator?

The _htmltest_ CI link check error will be fixed once the GraphQL link has been added:

```html
<details>
<summary>Added support of GraphQLIntrospectionConfig in ApiDefinition CRD </summary>

Added to ApiDefinition CRD: support of GraphQLIntrospectionConfig at [TBD](https://doc.crds.dev/github.com/TykTechnologies/tyk-operator/tyk.tyk.io/ApiDefinition/v1alpha1@v0.16.0#spec-analytics_plugin). See [GraphQL docs](TBD) for details.
</details>
```

2024-01-23 17:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-operator/v0.17.0/images/xxxxxxx?context=explore)
remember to update docker image download when ready for release

2024-01-23 17:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +Added to ApiDefinition CRD: support of GraphQLIntrospectionConfig at [TBD](https://doc.crds.dev/github.com/TykTechnologies/tyk-operator/tyk.tyk.io/ApiDefinition/v1alpha1@v0.16.0#spec-analytics_plugin
Will this be dependent upon another PR before release?

2024-01-23 17:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +##### Release date xxxxxxx
When is the scheduled release date?

2024-01-30 10:09 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +##### Release date xxxxxxx
It will be after 5.3 release (end of Feb)

2024-01-30 10:10 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +Added to ApiDefinition CRD: support of GraphQLIntrospectionConfig at [TBD](https://doc.crds.dev/github.com/TykTechnologies/tyk-operator/tyk.tyk.io/ApiDefinition/v1alpha1@v0.16.0#spec-analytics_plugin
It is dependent on Gateway 5.3 release which adds this field in APIDefinition.

However, there will be no documentation available (this field is added for future use only)

2024-01-30 19:52 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +Added to ApiDefinition CRD: support of GraphQLIntrospectionConfig at [TBD](https://doc.crds.dev/github.com/TykTechnologies/tyk-operator/tyk.tyk.io/ApiDefinition/v1alpha1@v0.16.0#spec-analytics_plugin
```suggestion
Added to ApiDefinition CRD: support of GraphQLIntrospectionConfig field at `graphql.introspection.disabled`. This feature will be enabled in future Tyk release.
```

2024-02-15 16:14 UTC, dcs3spp commented
@caroltyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update these and then open them again when ready for review.

2024-04-02 20:57 UTC, letzya commented
https://github.com/TykTechnologies/tyk-docs/pull/4011#issuecomment-1946447983

2024-04-05 12:38 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-operator/v0.17.0/images/xxxxxxx?context=explore)
updated

2024-04-05 12:38 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +##### Release date xxxxxxx
updated

2024-04-05 16:54 UTC, letzya approved these changes

2024-04-05 16:59 UTC, merged

2024-04-05 16:59 UTC, letzya commented
/release to release-5.3