Updated multiple middleware for OAS
TykTechnologies/tyk-docs-hugo pull request #4012
Opened 2024-01-23 16:20 UTC by andyo-tyk

### For internal users - Please add a Jira DX PR ticket to the subject!

### Preview Link

### Description
Updated and improved the docs, adding Tyk OAS, for:
- Circuit Breaker
- Enforced Timeout
- Request Method Transform
- Request Header Transform (API and endpoint level)

2024-01-23 18:18 UTC, dcs3spp requested changes
@andyo-tyk Thanks for submitting the updated middleware content for OAS.

So far I have reviewed 

- circuit breakers
- enforced timeouts
- circuit breaker tyk classic APIs
- circuit breaker tyk OAS APIs
- enforced timeout
- enforced timeout Tyk Classic
- request header transformations for tyk classic

I will continue to review the remaining content files tomorrow

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +In some scenarios the upstream service might recover more quickly than expected. Rather than being forced to wait until the end of the cooldown before reseting the circuit breaker (which will immedia
```suggestion
In some scenarios the upstream service might recover more quickly than expected. Rather than being forced to wait until the end of the cooldown before resetting the circuit breaker (which will immediately allow full access to the upstream service), the middleware supports a _half-open_ mode.
```

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +Circuit breakers are individual on a single Tyk Gateway, they do not centralise or pool back-end data. This ensures optimum speed of response and resilience to Gateway failure. This means that in a l
Does Circuit breakers are individual on a single Tyk Gateway mean that they operate on a single GW?

```suggestion
Circuit breakers operate on a single Tyk Gateway, they do not centralise or pool back-end data. This ensures optimum speed of response and resilience to Gateway failure. Subsequently, in a load balanced environment where multiple Tyk Gateways are used, some traffic can spill through even after the circuit breaker has tripped on one Gateway as other Gateways continue to serve traffic to the upstream before their own breakers trip.
```

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +For the generic `BreakerTriggered` event, the state change will be indicated in the `Status` field in the webhook template as follows:
Is there a link of explanation of the webhook template?

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
>  ## Overview
For refactoring/updating remove ##Overview heading and make this intro paragraph

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +## Overview
Remove ## Overview so have page title -> introduction paragraph and then section headings

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +In any system, a task or operation takes a certain period of time to complete. When a client makes a request to Tyk, it will be dependent upon the responsiveness of the upstream service before it can
```suggestion
In any system, a task or operation takes a certain period of time to complete. When a client makes a request to Tyk Gateway, it will be dependent upon the responsiveness of the upstream service before it can continue. If the upstream service is suffering from resource overload or congestion the response may be returned too late leading to unacceptable experience for the end user or even to instability in the system.
```

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +Tyk's Enforced Timeout middleware can be used to apply a maximum time that the Gateway will wait for a response before it terminates (or times out) the request. If the timeout expires, then Tyk will
How is the length of the timeout determined?

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-classic.md
> + - **Trigger threshold percentage**: The percentage of requests that can error before the breaker is tripped, this must be a value between 0.0 and 1.0
```suggestion
 - **Trigger threshold percentage**: The percentage of requests that can error before the breaker is tripped. This must be a value between 0.0 and 1.0
```

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-classic.md
> +The Dashboard supports the separate `BreakerTripped` and `BreakerReset` events, but not the combined `BreakerTriggered` [event type]({{< ref "basic-config-and-security/report-monitor-trigger-events/e
```suggestion
The Dashboard supports the separate `BreakerTripped` and `BreakerReset` events, but not the combined `BreakerTriggered` [event type]({{< ref "basic-config-and-security/report-monitor-trigger-events/event-types" >}}). You should use **API Designer > Advanced Options** to add a Webhook plugin to your endpoint for each event.
```

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> +## Overview
Remove ##Overview so have page title, intro paragraph followed by section headings

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> +When working with Tyk OAS APIs the circuit breaker is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within
```suggestion
When working with Tyk OAS APIs the circuit breaker is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). This can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-classic.md
> +When working with Tyk Classic APIs the enforced timeout is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboar
```suggestion
When working with Tyk Classic APIs the enforced timeout is configured in the Tyk Classic API Definition. This can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-classic.md
> +## Overview
Remove ## Overview H2 heading so have page title, intro paragraph and then section headings

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-oas.md
> +## Overview
Remove ##overview so have page title, intro paragraph followed by section headings

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-oas.md
> +When working with Tyk OAS APIs the enforced timeout is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within
```suggestion
When working with Tyk OAS APIs the enforced timeout is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). This can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-oas.md
> + < placeholder for video >
remember to add placeholder video

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
> +## Overview
Remove ##Overview heading so have page title, intro paragraph followed by section headings

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
> +When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition. This can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-23 18:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
> +The API-level and endpoint-level request header transforms are configured in different sections of the API definition, though have a common configuration.
```suggestion
The API-level and endpoint-level request header transforms are configured in different sections of the API definition and share a common configuration.
```

2024-01-23 20:42 UTC, letzya commented
@andyo-tyk this is a huge PR. It's hard to review such a big PR. Going forward, if possible (I appreciate that sometimes it's not), please avoid that. 
Also - it's for 5.3 right? could you please label it as such (so we know to merge to master but not to latest)

2024-01-24 09:24 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +Circuit breakers are individual on a single Tyk Gateway, they do not centralise or pool back-end data. This ensures optimum speed of response and resilience to Gateway failure. This means that in a l
That's my understanding, yes - I'll apply your suggestion and see what the technical/peer review thinks... :)

2024-01-24 09:25 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +For the generic `BreakerTriggered` event, the state change will be indicated in the `Status` field in the webhook template as follows:
I don't think so, but given that Tyk OAS won't initially support webhooks, I don't consider this in scope at the moment - it's a "to do".

2024-01-24 09:26 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +## Overview
As explained in other PRs, this title is to aid page navigation.

2024-01-24 09:26 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +Tyk's Enforced Timeout middleware can be used to apply a maximum time that the Gateway will wait for a response before it terminates (or times out) the request. If the timeout expires, then Tyk will
By configuring the middleware

2024-01-24 09:27 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-classic.md
> + - **Trigger threshold percentage**: The percentage of requests that can error before the breaker is tripped, this must be a value between 0.0 and 1.0
Deliberately not a full stop to avoid this bullet from requiring a full stop at the end - stylistic choice by the author - but if you're happy to have one then it can be added.

2024-01-24 09:27 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> +## Overview
As for every other page....

2024-01-24 09:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> +When working with Tyk OAS APIs the circuit breaker is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within
You really don't like semi-colons! By adding a full stop, the second sentence doesn't make sense stood alone (IMHO).

2024-01-24 09:30 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
> +The API-level and endpoint-level request header transforms are configured in different sections of the API definition, though have a common configuration.
I don't feel that "and" is the right word here - the first part of the phrase refers to a difference, the second to a similarity. I'll propose a re-phrasing.

2024-01-24 09:32 UTC, andyo-tyk commented
> @andyo-tyk this is a massive PR :). It's hard to review such a big PR. Going forward, if possible (I appreciate that sometimes it's not), please avoid that. Also - it's for 5.3 right? could you please label it as such (so we know to merge to master but not to latest)

Yes - and I've acknowledged and apologised for that in the DX ticket. I'm sorry that on this one occasion I haven't yet added the release version. It's pending peer/technical review so this omission isn't critical.

2024-01-24 09:34 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +In any system, a task or operation takes a certain period of time to complete. When a client makes a request to Tyk, it will be dependent upon the responsiveness of the upstream service before it can
```suggestion
In any system, a task or operation takes a certain period of time to complete. When a client makes a request to the Tyk Gateway, it will be dependent upon the responsiveness of the upstream service before it can continue. If the upstream service is suffering from resource overload or congestion the response may be returned too late leading to unacceptable experience for the end user or even to instability in the system.
```

2024-01-24 09:35 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
> +The API-level and endpoint-level request header transforms are configured in different sections of the API definition, though have a common configuration.
```suggestion
The API-level and endpoint-level request header transforms have a common configuration but are configured in different sections of the API definition.
```

2024-01-24 09:59 UTC, andyo-tyk reviewed
Corrected some copy/paste errors in Request Header OAS page

2024-01-24 09:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +The request method transform middleware (`transformRequestMethod`) can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appro
```suggestion
The request header transform middleware (`transformRequestHeaders`) can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appropriate `operationId` (as configured in the `paths` section of your OpenAPI Document).
```

2024-01-24 09:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +        "title": "example-request-method",
```suggestion
        "title": "example-request-header",
```

2024-01-24 09:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +            "name": "example-request-method",
```suggestion
            "name": "example-request-header",
```

2024-01-24 09:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +                "value": "/example-request-method/",
```suggestion
                "value": "/example-request-header/",
```

2024-01-24 09:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +## Configuring the Request Method Transform in the API Designer
```suggestion
## Configuring the Request Header Transform in the API Designer
```

2024-01-24 10:44 UTC, dcs3spp requested changes
PR LGTM, have made minor suggestions and made a suggestion of adding a file to content/shared for content shared in summary footer of some pages

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +## Overview
Remove ##Overview heading so have page title, intro paragraph followed by section headings

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within t
```suggestion
When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). This can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> + < placeholder for video >
Remember to add video

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-classic.md
> +## Overview
Remove H2 heading so have page title, intro paragraph and then section headings

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-classic.md
> +When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition. This can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
> +## Overview
Remove ##Overview heading so have page title, intro paragraph and then section headings

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
> +When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within t
```suggestion

When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). This can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
> +The request method transform middleware (`transformRequestMethod`) can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appro
Could add an external link to OpenAPI paths specification?

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/request-headers.md
> +## Overview
Remove ##Overview so that have page title, intro paragraph and section headings

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/request-headers.md
> +- [Context variables]({{< ref "context-variables" >}}), extracted from the request at the start of the middleware chain, can be injected into added headers using the `$tyk_context.` namespace
```suggestion
- [Context variables]({{< ref "context-variables" >}}) are extracted from the request at the start of the middleware chain and can be injected into added headers using the `$tyk_context.` namespace
```

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/request-headers.md
> +<!-- proposed "summary box" to be shown graphically on each middleware page
If these is going to be reused across pages we can place it in shared content folder?

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
> -This feature is very simple at the moment, and only changes the type of method, it does not handle the message data of the request body. However, a combination of method transform, context variables
```suggestion
This feature is very simple at the moment and only changes the type of method. It does not handle the message data of the request body. However, a combination of method transform, context variables and body transformations can be used to achieve a similar effect.
```

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
> +<!-- proposed "summary box" to be shown graphically on each middleware page
If this is repeated content, maybe we can included the shared content in content/shared file?

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
> +## Overview
Remove ## Overview heading so have page title, intro paragraph and then section headings

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/context-variables.md
> +## Overview
Remove ##Overview so have page title, intro paragraph and then section headings

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/context-variables.md
> +Context variables are extracted from the request at the start of the middleware chain. These values can be very useful for later transformation of request data, for example, in converting a Form-base
```suggestion
Context variables are extracted from the request at the start of the middleware chain. These values can be very useful for later transformation of request data, for example, in converting a form POST request into a JSON PUT request or to capture an IP address as a header.
```

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/context-variables.md
> +2. Open the API you want to add Context Variable to.
```suggestion
2. Open the API you want to add Context Variable to
```

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/context-variables.md
> +3. Select the `Advanced Options` tab and select `Enable context variables`
```suggestion
3. Click the `Advanced Options` tab and then select the `Enable context variables` option
```

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/context-variables.md
> +If not using a Tyk Dashboard, add the field `enable_context_vars` to your API definition file at root level and set it to `true`.
Can show or link to an example here?

2024-01-24 10:44 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +Tyk's Enforced Timeout middleware can be used to apply a maximum time that the Gateway will wait for a response before it terminates (or times out) the request. If the timeout expires, then Tyk will
@andyo-tyk How is the length of the configured timeout determined?

2024-01-24 14:00 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/request-headers.md
> +  - The Request Header Transform is configured at the per-endpoint level within the API Definition and is supported by the API Designer within the Tyk Dashboard.
```suggestion
  - The Request Header Transform can be configured at the per-endpoint or per-API level within the API Definition and is supported by the API Designer within the Tyk Dashboard. 
```

2024-01-24 14:25 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
> +You must also set a method and a request pattern to match against. These patterns can contain wildcards in the form of any string bracketed by curly braces. These wildcards are so they are human read
```suggestion
You must also set a method and a request pattern (endpoint) to match against. These patterns can contain wildcards in the form of any string bracketed by curly braces. These wildcards are so they are human readable and do not translate to variable names. Under the hood, a wildcard translates to the "match everything" regex of: `(.*)`.
```

2024-01-24 14:33 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
> +| Do Not Track                          | ✅               | ✅            |
Are the ticked features only available in Tyk OAS API Definition from v5.3+?

2024-01-24 16:06 UTC, andyo-tyk commented on tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
> +| Do Not Track                          | ✅               | ✅            |
The newly ticked ones are, yes. This needs to be updated/released as part of the 5.3.0 docs so that it reflects the state of the product at that point in time. If they look at older docs, they'll see the red crosses for unsupported features. This page might actually come out for 5.3.0 launch, I haven't decided yet.

2024-01-26 08:52 UTC, andyo-tyk reviewed
Removed H2 Overview titles

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> +## Overview
```suggestion
```

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-classic.md
> +## Overview
```suggestion
```

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-oas.md
> +## Overview
```suggestion
```

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
> +## Overview
```suggestion
```

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +## Overview
```suggestion
```

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-classic.md
> +## Overview
```suggestion
```

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
> +## Overview
```suggestion
```

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/request-headers.md
> +## Overview
```suggestion
```

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
> +## Overview
```suggestion
```

2024-01-26 08:52 UTC, andyo-tyk commented on tyk-docs/content/context-variables.md
> +## Overview
```suggestion
```

2024-01-26 08:54 UTC, andyo-tyk commented on tyk-docs/content/context-variables.md
> +If not using a Tyk Dashboard, add the field `enable_context_vars` to your API definition file at root level and set it to `true`.
I only made minor change to this file to accommodate changes elsewhere - this will need to be picked up in a separate docs update.

2024-01-26 08:55 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +## Overview
```suggestion
```

2024-01-26 08:56 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-classic.md
> +## Overview
```suggestion
```

2024-01-26 10:33 UTC, dcs3spp reviewed
PR LGTM, once placeholder video etc. added then let me know and I will then re-review and approve ✅

2024-02-02 15:01 UTC, andyo-tyk reviewed
Minor improvements

2024-02-02 15:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-classic.md
> +When working with Tyk Classic APIs the circuit breaker is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard
```suggestion
When working with Tyk Classic APIs the circuit breaker is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 15:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> +When working with Tyk OAS APIs the circuit breaker is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within
```suggestion
When working with Tyk OAS APIs the circuit breaker is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 15:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-classic.md
> +When working with Tyk Classic APIs the enforced timeout is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboar
```suggestion
When working with Tyk Classic APIs the enforced timeout is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 15:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-oas.md
> +When working with Tyk OAS APIs the enforced timeout is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within
```suggestion
When working with Tyk OAS APIs the enforced timeout is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 15:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
> +When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 15:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within t
```suggestion
When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 15:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-classic.md
> +When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 15:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
> +When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within t
```suggestion
When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-15 16:16 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-03-26 15:31 UTC, andrei-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
> +Tyk's Request Method Transform middleware allows you to modify the HTTP method of incoming requests to an API endpoint prior to the request being proxied to the upstream service. You might use this,
I don't think the backward compatibility example is the right one as such an use case would be incredibly rare (and maybe even bad practice). The example presented below with single POST api that then maps to PUT or DELETE on demand sounds like a better one.

2024-03-26 15:44 UTC, andrei-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +In some scenarios the upstream service might recover more quickly than expected. Rather than being forced to wait until the end of the cooldown before resetting the circuit breaker (which will immedi
The second sentence sounds ambiguous. We use "rather than" and we don't add the alternative (we only mention the alternative state). Sorry if it's subjective.

2024-03-26 15:45 UTC, andrei-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +In the _half-open_ mode, Tyk will periodically issue requests to the upstream service to check whether the path has been restored (while continuing to block client requests). If the Gateway detects t
I think "closed" might be a poor word choice. From an electrical engineering perspective you're right. From a API user closed sounds bad.

2024-03-26 15:54 UTC, andrei-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +Prioritizing critical tasks by setting timeouts ensures that essential tasks are completed before less urgent ones, maintaining system responsiveness.
I don't think it's right to name "tasks that have ran past the timeout period" less urgent as it's not always the case. We should infer that timeouts free resources to be used by the essential tasks and that system responsiveness is maintained as the system for example can tell the client "oh, an error ocurred" rather than keeping him in a neverending loop. If my comment is ambiguous please DM me and maybe I can use better wording when expressing my ideas.

2024-03-26 16:00 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> +You only need to enable the middleware (set `enabled:true`) and then configure the `threshold`, `sampleSize`, `coolDownPeriod` and `halfOpenStateEnabled`. The design of the Tyk OAS API Definition tak
operationID should be operationId , I think you mentioned in a previously PR that you are aware of it and that the typo is present in multiple PRs

2024-03-27 14:44 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +In the _half-open_ mode, Tyk will periodically issue requests to the upstream service to check whether the path has been restored (while continuing to block client requests). If the Gateway detects t
Guess what my degree is in... not Computer Science... 😆

2024-03-27 14:56 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
> +Tyk's Request Method Transform middleware allows you to modify the HTTP method of incoming requests to an API endpoint prior to the request being proxied to the upstream service. You might use this,
Perhaps something like "You might use this to map `POST` requests from clients to upstream services that support only `PUT` and `DELETE` operations, providing a modern interface to your users."?

2024-03-27 15:35 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +In some scenarios the upstream service might recover more quickly than expected. Rather than being forced to wait until the end of the cooldown before resetting the circuit breaker (which will immedi
This is given - with the explanation of the term "half-open" in the following paragraph, however I will tighten this up.

2024-03-27 15:41 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +In the _half-open_ mode, Tyk will periodically issue requests to the upstream service to check whether the path has been restored (while continuing to block client requests). If the Gateway detects t
I've elaborated on this - and made reference to the electrical circuit analogy used earlier on the page.

2024-03-27 16:53 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
> +Prioritizing critical tasks by setting timeouts ensures that essential tasks are completed before less urgent ones, maintaining system responsiveness.
Enforced timeout is configured per endpoint - the aim is to adjust this according to the _expected_ response time for the particular upstream service (which can represent a failure). I'll review and revise this.

2024-03-27 18:24 UTC, andrei-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +Thus, if the _sample size_ is set to 100 and the _failure rate_ is set to 0.5 (50%) then the circuit breaker will trip only when there have been a minimum of 100 requests made in the past 10 seconds
```suggestion
Thus, if the _sample size_ is set to 100 and the _failure rate_ is set to 0.5 (50%) then the circuit breaker will trip only when there have been a minimum of 100 requests made in the past 10 seconds of which at least 50 have failed (returned an `HTTP 500` or higher error).
```

2024-03-27 18:24 UTC, andrei-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +In some scenarios the upstream service might recover more quickly than the configured cooldown period. The middleware supports a _half-open_ mode that facilitates an early return-to-service so that y
```suggestion
In some scenarios the upstream service might recover more quickly than the configured cooldown period. The middleware supports a _half-open_ mode that facilitates an early return-to-service so that API clients do not have to wait until the end of the cooldown before the circuit breaker is reset.
```

2024-03-27 18:25 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> +Adding the circuit breaker to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
```suggestion
Adding the circuit breaker to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow these steps:
```

2024-03-27 18:25 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-oas.md
> +Adding the enforced timeout to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
```suggestion
Adding the enforced timeout to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow these steps:
```

2024-03-27 18:26 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +Adding and configuring the transforms to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
```suggestion
Adding and configuring the transforms to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow these steps:
```

2024-03-27 18:26 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
> +Adding the transform to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
```suggestion
Adding the transform to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow these steps:
```

2024-03-27 18:26 UTC, andrei-tyk approved these changes

2024-03-27 18:30 UTC, dcs3spp requested changes
@andyo-tyk PR LGTM, I have reviewed changes and made small fix suggestions. Once @andrei-tyk has peer approved also, we can merge ready for release.

2024-03-27 18:30 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
> +Adding the transform to your API endpoints is easy is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
Duplicate phrase:

```suggestion
Adding the transform to your API endpoints is easy when using the API Designer in the Tyk Dashboard:
```

2024-03-27 18:30 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +The rolling sample window is set to 10 seconds and the circuit breaker is designed to trip only if a user-configurable minimum number of samples (requests) fail within the window period, this is
Incomplete sentence

2024-03-27 18:30 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
> +Adding the circuit breaker to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
```suggestion
Adding the circuit breaker to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
```

2024-03-27 18:30 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
> +Adding the transform to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
```suggestion
Adding the transform to your API endpoints is easy when using the API Designer in the Tyk Dashboard:
```

2024-03-27 18:30 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-oas.md
> +Adding the enforced timeout to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
```suggestion
Adding the enforced timeout to your API endpoints is easy when using the API Designer in the Tyk Dashboard:
```

2024-03-27 18:30 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +In this example the Request Header Transform middleware has been configured forrequests to the `GET /status/200` endpoint. Any request received to that endpoint will have the `X-Static` header remove
```suggestion
In this example the Request Header Transform middleware has been configured for requests to the `GET /status/200` endpoint. Any request received to that endpoint will have the `X-Static` header removed and the `X-Secret` header added, with the value set to `the-secret-key-is-secret`.
```

2024-03-27 18:30 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
> +Adding and configuring the transforms to your API endpoints is easy when using the API Designer in the Tyk Dashboard, simply follow the following steps:
```suggestion
Adding and configuring the transforms to your API endpoints is easy when using the API Designer in the Tyk Dashboard:
```

2024-03-27 18:33 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
> +The rolling sample window is set to 10 seconds and the circuit breaker is designed to trip only if a user-configurable minimum number of samples (requests) fail within the window period, this is
```suggestion
The rolling sample window is set to 10 seconds and the circuit breaker is designed to trip only if a user-configurable minimum number of samples (requests) fail within the window period.

2024-03-27 18:36 UTC, dcs3spp approved these changes

2024-03-27 18:41 UTC, merged