[Dx-962] Add FAQ For How To Distribute Analytics Keys Across Redis Clusters
TykTechnologies/tyk-docs-hugo pull request #4018
Opened 2024-01-24 12:34 UTC by dcs3spp

[DX-962](https://tyktech.atlassian.net/browse/DX-962)

[preview-to add](/docs/nightly/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards)

2024-01-29 22:09 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +title: "How To Configure Tyk To Distribute Analytics Keys To Multiple Redis Shards"
As with the other FAQ - the title is the solution, not the problem. As a user, you wouldn't know to search for it or even know it's relevant to you. Please rewrite it to reflect the problem that "enable_multiple_analytics_keys" solves

2024-01-29 22:10 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +description: "Explains how to configure the Gateway and MDCB for distributing analytics to multiple Redis shards."
same as the comment above. Include the problem to the sentence.

2024-01-29 22:15 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +Tyk distributes analytics to Redis storage. A high volume of analytics traffic can decrease performance, since all analytics keys are stored within one Redis server.
We need to start with the problem. "...Do you have this pattren of CPU for your environment and wonder what could it be?..." then explain one possible reason and then explain the solution

2024-01-29 22:16 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +Tyk distributes analytics to Redis storage. A high volume of analytics traffic can decrease performance, since all analytics keys are stored within one Redis server.
also explain the graph in the image. What do we see in it.

2024-01-29 22:17 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +{{< img src="/img/faq/enable-multiple-analytics-keys/redis_distributed.png" >}}
sorry if I misunderstood- what do we want to show in the 2nd image

2024-01-29 22:18 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        path: /developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards
change the name of the file to suit the title and reflet the problem not the solution

2024-01-29 22:19 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +1. **Enable Redis Cluster Support**: Confirm that the *enable_cluster* configuration option is set to true in the [Tyk Gateway]({{< ref "tyk-oss-gateway/configuration#storageenable_cluster" >}}), [Ty
```suggestion
1. **Enable Redis Cluster Support**: Confirm that the `enable_cluster` configuration option is set to true in the [Tyk Gateway]({{< ref "tyk-oss-gateway/configuration#storageenable_cluster" >}}), [Tyk Dashboard]({{< ref "tyk-dashboard/configuration#enable_cluster" >}}) and [Tyk Pump]({{< ref "tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables#analytics_storage_configenable_cluster" >}}) configuration files. This setting activates the Redis cluster support within Tyk components.
```
```suggestion
1. **Enable Redis Cluster Support**: Confirm that the *enable_cluster* configuration option is set to true in the [Tyk Gateway]({{< ref "tyk-oss-gateway/configuration#storageenable_cluster" >}}), [Tyk Dashboard]({{< ref "tyk-dashboard/configuration#enable_cluster" >}}) and [Tyk Pump]({{< ref "tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables#analytics_storage_configenable_cluster" >}}) configuration files. This setting activates the Redis cluster support within Tyk components.
```

2024-01-29 22:22 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +1. **Enable Redis Cluster Support**: Confirm that the *enable_cluster* configuration option is set to true in the [Tyk Gateway]({{< ref "tyk-oss-gateway/configuration#storageenable_cluster" >}}), [Ty
not sure "active" is the right term. redis is a cluster. that's a fact. the setting makes sure tyk knows redis is a cluster and treats it as such when doing CRUD for keys in redis

2024-01-29 22:23 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +2. **Configure Redis Addresses**: Populate the *addrs* array in the [Tyk Gateway]({{< ref "tyk-oss-gateway/configuration#storageaddrs" >}}), [Tyk Dashboard]({{< ref "tyk-dashboard/configuration#redis
```suggestion
2. **Configure Redis Addresses**: Populate the `addrs` array in the [Tyk Gateway]({{< ref "tyk-oss-gateway/configuration#storageaddrs" >}}), [Tyk Dashboard]({{< ref "tyk-dashboard/configuration#redis_addrs" >}}) and [Tyk Pump]({{< ref "tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables#analytics_storage_configaddrs" >}}) configuration files (tyk.conf, tyk_analytics.conf and pump.conf) with the addresses of all Redis cluster nodes. This ensures that the Tyk components can interact with the entire Redis cluster. Please refer to the [configure Redis cluster]({{< ref "tyk-stack/tyk-gateway/configuration/redis-cluster#redis-cluster--tyk-gateway" >}}) guide for further details.
```

2024-01-29 22:25 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +2. **Configure Redis Addresses**: Populate the *addrs* array in the [Tyk Gateway]({{< ref "tyk-oss-gateway/configuration#storageaddrs" >}}), [Tyk Dashboard]({{< ref "tyk-dashboard/configuration#redis
"Redis Cluster" with capital C as it's the products name

2024-01-29 22:37 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +3. **Adjust Analytics Configuration**: In the Tyk Gateway configuration (tyk.conf), set [analytics_config.enable_multiple_analytics_keys]({{< ref "tyk-oss-gateway/configuration#analytics_configenable
```suggestion
3. **Adjust Analytics Configuration**: In the Tyk Gateway configuration (tyk.conf), set [analytics_config.enable_multiple_analytics_keys]({{< ref "tyk-oss-gateway/configuration#analytics_configenable_multiple_analytics_keys" >}}) to true. This option allows Tyk to distribute analytics data across Redis nodes, using multiple keys for the analytics. There's a corresponding option for Self Managed MDCB, also named [enable_multiple_analytics_keys]({{< ref "tyk-multi-data-centre/mdcb-configuration-options#enable_multiple_analytics_keys" >}}). Useful only if the gateways in the data plane are configured to send analytics to MDCB.
```

2024-01-29 22:38 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +3. **Adjust Analytics Configuration**: In the Tyk Gateway configuration (tyk.conf), set [analytics_config.enable_multiple_analytics_keys]({{< ref "tyk-oss-gateway/configuration#analytics_configenable
not sure I understand the title "adjust...", it's a configuration of a boolean not fine tunning

2024-01-29 22:40 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +5. **Monitor and Scale**: Continuously monitor the load on each Redis shard. If load imbalances are detected, you may need to reshard your Redis cluster or scale it to better distribute the keys and
Are you sure about #5?

2024-01-29 22:42 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +6. **Use a Separate Analytics Store**: For high analytics traffic, you can opt to use a dedicated Redis cluster for analytics by setting [enable_separate_analytics_store]({{< ref "tyk-oss-gateway/con
```suggestion
6. **Use a Separate Analytics Store**: For high analytics traffic, you can opt to use a dedicated *Redis Cluster* for analytics by setting [enable_separate_analytics_store]({{< ref "tyk-oss-gateway/configuration#enable_separate_analytics_store" >}}) to true in the Tyk Gateway configuration file (*tyk.conf*) and specifying the separate Redis cluster configuration in the `analytics_storage` section. Please consult the [separated analytics storage]({{< ref "tyk-stack/tyk-pump/separated-analytics-storage" >}}) guide for an example with *Tyk Pump* that can equally be applied to *Tyk Gateway*.
```

2024-01-29 22:42 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +6. **Use a Separate Analytics Store**: For high analytics traffic, you can opt to use a dedicated Redis cluster for analytics by setting [enable_separate_analytics_store]({{< ref "tyk-oss-gateway/con
field name - back ticks
name - italic

2024-01-29 22:45 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +## How To Distribute Analytics To Multiple Redis Shards
1. This is exactly like the title...after you change the title should be fine
2. As I was reading, I thought that maybe this section should be in key concepts or maybe something else. worth checking with Rich

2024-01-29 22:47 UTC, letzya requested changes
prt comments

2024-01-30 18:25 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +title: "How To Configure Tyk To Distribute Analytics Keys To Multiple Redis Shards"
updated

2024-01-30 18:25 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +description: "Explains how to configure the Gateway and MDCB for distributing analytics to multiple Redis shards."
updated

2024-01-30 18:25 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +Tyk distributes analytics to Redis storage. A high volume of analytics traffic can decrease performance, since all analytics keys are stored within one Redis server.
updated

2024-01-30 18:26 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +{{< img src="/img/faq/enable-multiple-analytics-keys/redis_distributed.png" >}}
updated

2024-01-30 18:26 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +        path: /developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards
updated

2024-01-30 18:30 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +1. **Enable Redis Cluster Support**: Confirm that the *enable_cluster* configuration option is set to true in the [Tyk Gateway]({{< ref "tyk-oss-gateway/configuration#storageenable_cluster" >}}), [Ty
updated

2024-01-30 18:32 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +3. **Adjust Analytics Configuration**: In the Tyk Gateway configuration (tyk.conf), set [analytics_config.enable_multiple_analytics_keys]({{< ref "tyk-oss-gateway/configuration#analytics_configenable
updated

2024-01-30 18:35 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how_to_distribute_analytics_to_multiple_redis_shards.md
> +5. **Monitor and Scale**: Continuously monitor the load on each Redis shard. If load imbalances are detected, you may need to reshard your Redis cluster or scale it to better distribute the keys and
updated

2024-01-31 10:36 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-by-distributing-analytics-keys-in-a-redis-cluster.md
> +1. **Enable Redis Cluster Support**: Confirm that the `enable_cluster` configuration option is set to true in the [Tyk Gateway]({{< ref "tyk-oss-gateway/configuration#storageenable_cluster" >}}), [Ty
Context of page should be assuming that Redis Cluster exists and is in use.
The context/problem should not be that a single Redis node has high CPU usage. That should be in a separate FAQ or mentioned in planning in production parent page.

2024-02-12 15:02 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +This FAQ explains how to configure Tyk to distribute analytic keys across multiple Redis instances.
"This FAQ explains how to configure" - not exactly. It also explains the reasons for the cpu load in only one node. Also, we can't write it half way through the page, doesn't make sense. 

Can we rephrase?

2024-02-12 15:03 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +{{< img src="/img/faq/enable-multiple-analytics-keys/redis_distributed.png" >}}
Can you please enforce withs of images? doesn't look good ATM

2024-02-12 15:11 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +The illustration below highlights the scenario where a single Redis node is exhibiting high CPU usage of 1.20% within a Redis Cluster. One possible reason for this could be that analytics are enabled
```suggestion
When you h
The illustration below highlights the scenario where a single Redis node is exhibiting high CPU usage of 1.20% within a Redis Cluster. One of the main possible reasons could be that Tyk Gateway is using only one node for storing the analytics. 

  analytics are enabled and the keys are being stored within a single Redis server.
```

2024-02-12 15:11 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +The illustration below highlights the scenario where a single Redis node is exhibiting high CPU usage of 1.20% within a Redis Cluster. One possible reason for this could be that analytics are enabled
PM

2024-02-12 15:12 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +{{< img src="/img/faq/enable-multiple-analytics-keys/redis_single.png" >}}
too big

2024-02-12 15:13 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +Tyk distributes analytics to Redis storage. A high volume of analytics traffic can decrease performance, since all analytics keys are stored within one Redis server.
`Tyk distributes analytics to Redis storage` - what does it mean? if it stores in one node, then what does it mean "Tyk distributes..."? do you mean store?

2024-02-12 15:15 UTC, letzya requested changes
Need more DX into it

2024-04-02 22:51 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +When a single Redis node within a Redis Cluster exhibits high CPU usage, it indicates that the CPU resources of that particular node are being heavily utilised compared to others in the cluster.
I think we should move the image redis_single.png to this section

2024-04-02 22:51 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +When a single Redis node within a Redis Cluster exhibits high CPU usage, it indicates that the CPU resources of that particular node are being heavily utilised compared to others in the cluster.
```suggestion
When a single Redis node within a Redis Cluster exhibits high CPU usage, it indicates that the CPU resources of that particular node are being heavily utilised compared to others in the cluster.

The illustration below highlights the scenario where a single Redis node is exhibiting high CPU usage of 1.20% within a Redis Cluster. 

{{< img src="/img/faq/enable-multiple-analytics-keys/redis_single.png" width="768" alt="analytics keys stored in one Redis server" >}}
```

2024-04-02 22:52 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +The illustration below highlights the scenario where a single Redis node is exhibiting high CPU usage of 1.20% within a Redis Cluster.
```suggestion
```

2024-04-02 22:52 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +{{< img src="/img/faq/enable-multiple-analytics-keys/redis_single.png" width="768" alt="analytics keys stored in one Redis server" >}}
```suggestion
```

2024-04-02 22:52 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +
```suggestion
```

2024-04-02 22:55 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +Tyk stores analytics in Redis storage. A high volume of analytics traffic can decrease performance, since all analytics keys are stored within one Redis server.
`Tyk stores analytics in Redis storage` - seems a bit too deep into the content, so say something so basic.

2024-04-17 15:47 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +Tyk stores analytics in Redis storage. A high volume of analytics traffic can decrease performance, since all analytics keys are stored within one Redis server.
updated

2024-04-17 15:49 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +Tyk distributes analytics to Redis storage. A high volume of analytics traffic can decrease performance, since all analytics keys are stored within one Redis server.
Updated in section *## How does storing keys within a single Redis server contribute to high CPU usage?*

2024-04-17 15:53 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
> +This FAQ explains how to configure Tyk to distribute analytic keys across multiple Redis instances.
Refactored introduction

2024-04-19 01:18 UTC, letzya approved these changes
@sedkis We created this FAQ following your thread in slack, could you please review it?

@joshblakeley in case you can review

2024-04-30 13:03 UTC, dcs3spp commented
Hi @sedkis would you be able to review the final Distributed Analytics FAQ and if ok I will merge and release

2024-05-02 14:01 UTC, sedkis approved these changes

2024-05-02 16:05 UTC, merged

2024-05-02 16:05 UTC, dcs3spp commented
/release to release-5.3

2024-05-02 16:06 UTC, dcs3spp commented
/release to release-5.2

2024-05-02 16:16 UTC, dcs3spp commented
/release to release-5.2

2024-05-02 16:31 UTC, dcs3spp commented
/release to release-5.1

2024-05-02 16:43 UTC, dcs3spp commented
/release to release-5.1