Improved Response Header Transform
TykTechnologies/tyk-docs-hugo pull request #4019
Opened 2024-01-24 14:36 UTC by andyo-tyk

### Preview Link

### Description
Improved documentation of Response Header Transform, added Tyk OAS

2024-01-25 10:51 UTC, dcs3spp requested changes
PR LGTM, have made minor suggestions.

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +## When to use response header transformation
Suggestion only

```suggestion
## Use cases for response header transformation
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +A common use of the response header transform is when a client requires specific headers for their application to function correctly. For example, a client may require a specific header to indicate t
```suggestion
A frequent use case for response header transformation is when a client requires specific headers for their application to function correctly. For example, a client may require a specific header to indicate the status of a request or to provide additional information about the response.
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +## Overview
Remove ##Overview heading so have page title, intro paragraphs and section headings

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +There are related [Request Header Transform]({{< ref "transform-traffic/request-headers" >}}) middleware (at API-level and endpoint-level) that provide the same functionality on the request from your
```suggestion
There are related [Request Header Transform]({{< ref "transform-traffic/request-headers" >}}) middleware (at API-level and endpoint-level) that provide the same functionality on the request from a client, prior to it being proxied to the upstream.
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +#### Customizing responses for specific clients
```suggestion
#### Customising responses for specific clients
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +#### Modifying response headers for dynamic performance optimization
```suggestion
#### Modifying response headers for dynamic performance optimisation
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +You can use response header transformation to dynamically optimize the performance of the API. For example, you may want to indicate to the client the maximum number of requests that they can make in
```suggestion
You can use response header transformation to dynamically optimise the performance of the API. For example, you may want to indicate to the client the maximum number of requests that they can make in a given time period. By doing so through the response headers, you can perform dynamic optimisation of the load on the upstream service without triggering the rate limiter and so avoiding errors being sent to the client.
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> + - The "delete header" functionality is intended to ensure that any header in the delete list is not present once the middleware completes so that, if a header on the list to be deleted is not origin
```suggestion
 - The "delete header" functionality is intended to ensure that any header in the delete list is not present once the middleware completes. If a header in the delete list is not present in the upstream response, the middleware will ignore the omission
```
Is it possible to log the occurrences where a header to delete is not present on the list?

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> + - The "add header" functionality will capitalise any header name provided, for example if you configure the middleware to append `x-request-id` it will be added to the response as `X-Request-Id`.
```suggestion
 - The "add header" functionality will capitalise any header name provided. For example, if you configure the middleware to append `x-request-id` it will be added to the response as `X-Request-Id`.
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +In the response middleware chain, the endpoint-level transform is applied before the API-level transform so if both middleware are enabled, the API-level transform will operate on the headers that ha
```suggestion
In the response middleware chain, the endpoint-level transform is applied before the API-level transform. Subsequently, if both middleware are enabled, the API-level transform will operate on the headers that have been added by the endpoint-level transform (and will not receive those that have been deleted by it).
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +- [Context variables]({{< ref "context-variables" >}}), extracted from the request at the start of the middleware chain, can be injected into added headers using the `$tyk_context.` namespace
Add full stops to the items in this list or remove from above lists for consistency.

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +
```suggestion
Further details and examples are available for how to configure the response header transform middleware for [Tyk OAS APIs]({< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas" >}}) and [Tyk Classic APIs]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-classic" >}})
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +<!-- proposed "summary box" to be shown graphically on each middleware page
Can use content/shared to do this

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +If you're using the newer Tyk OAS APIs, then check out the [Tyk OAS]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas" >}}) page.
```suggestion
If you're using the newer Tyk OAS APIs, then check out the [Tyk OAS]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas" >}}) page for how to configure Tyk to use dynamic data from context variables.
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +To configure a transformation of the response header for a specific endpoint you must add a new `transform_response_headers` object to the `extended_paths` section of your API definition.
```suggestion
To configure response header transformation for a specific endpoint you must add a new `transform_response_headers` object to the `extended_paths` section of your API definition.
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +If the API-level transform in the previous [example]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-classic#api-level-transform" >}}) is applied to the same API, then because the e
```suggestion
If the example [API-level]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-classic#api-level-transform" >}}) and [endpoint-level]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-classic#endpoint-level-transform" >}}) transforms are applied to the same API, then the `X-Secret` header will be added (by the endpoint-level transform first) and then removed (by the API-level transform). Subsequently, the result of the two transforms for a call to `GET /status/200` would be to add four headers:
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +< placeholder for image >
remember to add image

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +You must set an HTTP method and a request pattern (endpoint) to match against. These patterns can contain wildcards in the form of any string bracketed by curly braces. These wildcards are so they ar
Not sure if it was a typo, why is the endpoint in brackets? 

```suggestion
You must set an HTTP method and a request pattern for the endpoint to match against. These patterns can contain wildcards in the form of any string bracketed by curly braces. These wildcards are so they are human readable and do not translate to variable names. Under the hood, a wildcard translates to the "match everything" regex of: `(.*)`.
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +< placeholder for screenshot >
remember to add image

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
> +To append headers to, or delete headers from, all responses from your API (i.e. for all endpoints) you must add a new `transformResponseHeaders` object to the `middleware.global` section of the Tyk O
```suggestion
To append headers to, or delete headers from, all responses from your API endpoints you must add a new `transformResponseHeaders` object to the `middleware.global` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition.
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
> +If the API-level transform in the previous [example]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas#api-level-transform" >}}) is applied to the same API, then because the endpo
```suggestion
If the example [API-level]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas#api-level-transform" >}}) and [endpoint-level]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas#endpoint-level-transform" >}}) transforms are applied to the same API, then the `X-Secret` header will be added (by the endpoint-level transform first) and then removed (by the API-level transform). Subsequently, the result of the two transforms for a call to `GET /status/200` would be to add four headers:
```

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
> + < placeholder for video >
remember to add video

2024-01-25 10:51 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +
remove full stops in the list items below for consistency

2024-01-25 14:58 UTC, andyo-tyk reviewed
Removing H2 Overview headers plus a few tweaks based on review feedback

2024-01-25 14:58 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +## Overview
```suggestion
```

2024-01-25 14:58 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +## When to use response header transformation
This is stylistic - consistent across all of these updated middleware pages, intended for each page to flow:

- What it is
- When to use it
- How it works

2024-01-25 14:58 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> +
This is covered by lines 50 and 52.

2024-01-25 14:58 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +If you're using the newer Tyk OAS APIs, then check out the [Tyk OAS]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas" >}}) page.
This is a link to the sister page - i.e. if you've ended up on the Tyk Classic API page but are using Tyk OAS APIs. Each is intended to be standalone.

2024-01-25 14:58 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +## Overview
```suggestion
```

2024-01-25 14:58 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +You must set an HTTP method and a request pattern (endpoint) to match against. These patterns can contain wildcards in the form of any string bracketed by curly braces. These wildcards are so they ar
Because this is the first time we've used the term "request pattern" to mean "endpoint" - but this paragraph (taken from old docs) is talking specifically about the fact that the endpoint match treats it as a "request pattern". This isn't a typo.

2024-01-25 14:58 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
> +## Overview
```suggestion
```

2024-01-25 14:58 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
> +To append headers to, or delete headers from, all responses from your API (i.e. for all endpoints) you must add a new `transformResponseHeaders` object to the `middleware.global` section of the Tyk O
Here I am saying that we are talking about "all of the endpoints of your API", hence the wording, however I agree this could be clearer.

```suggestion
To append headers to, or delete headers from, responses from all endpoints defined for your API you must add a new `transformResponseHeaders` object to the `middleware.global` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition.
```

2024-01-25 15:35 UTC, andyo-tyk reviewed
Improved formatting consistency

2024-01-25 15:35 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> + - `path`: The path to match on
```suggestion
 - `path`: the path to match on
```

2024-01-25 15:35 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> + - `method`: The method to match on
```suggestion
 - `method`: the HTTP method to match on
```

2024-01-25 15:35 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> + - `delete_headers`: A list of the headers that should be deleted from the response
```suggestion
 - `delete_headers`: a list of the headers that should be deleted from the response
```

2024-01-25 15:35 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> + - `add_headers`: A list of headers, in key:value pairs, that should be added to the response
```suggestion
 - `add_headers`: a list of headers, in key:value pairs, that should be added to the response
```

2024-01-25 15:35 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
> + - The "add header" functionality will capitalise any header name provided, for example if you configure the middleware to append `x-request-id` it will be added to the response as `X-Request-Id`.
```suggestion
 - The "add header" functionality will capitalise any header name provided. For example, if you configure the middleware to append `x-request-id` it will be added to the response as `X-Request-Id`
```

2024-01-26 10:46 UTC, dcs3spp reviewed
Thanks Andy, I think just the videos and images needed now and then can approve. Let me know when images / videos added and I'll do a final check through. Once peer reviewed I think we can then approve.

2024-02-02 14:57 UTC, andyo-tyk reviewed
Minor improvements

2024-02-02 14:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the transformation is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 14:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
> +When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within t
```suggestion
When working with Tyk OAS APIs the transformation is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-08 12:18 UTC, andyo-tyk reviewed
Added missing section on `header_transform` middleware

2024-02-08 12:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +
```suggestion

### Fixing response headers that leak upstream server data
A middleware called `header_transform` was added in Tyk 2.1 specfically to allow you to  ensure that headers such as `Location` and `Link` reflect the outward facade of your API Gateway and also align with the expected response location to be terminated at the gateway, not the hidden upstream proxy.

This is configured by adding a new `rev_proxy_header_cleanup` object to the `response_processors` section of your API definition.

It has the following configuration:
 - `headers`: a list of headers in the response that should be modified
 - `target_host`: the value to which the listed headers should be updated
 
For example:
``` .json
{
    "response_processors": [
        {
            "name": "header_transform",
            "options": {
                "rev_proxy_header_cleanup": {
                    "headers": ["Link", "Location"],
                    "target_host": "http://TykHost:TykPort"
                }
            }
        }
    ]
}
```

2024-02-08 12:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +"response_processors":[{"name": "header_injector"}]
```suggestion
{
    "response_processors":[
        {"name": "header_injector"}
    ]
}
```

2024-02-08 12:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +```
```suggestion
``` .json
```

2024-02-08 12:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +## Configuring the Response Header Transform in the API Designer
```suggestion

In this example, the `Link` and `Location` headers will be modified from the server-generated response, with the protocol, domain and port of the value set in `target_host`.

This is not an often used feature of Tyk and has not been implemented in the Tyk Dashboard UI, nor in the [Tyk OAS API]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas" >}}).

## Configuring the Response Header Transform in the API Designer
```

2024-02-08 15:10 UTC, dcs3spp requested changes
Thanks Andy for submitting updates, I've reviewed the additional content

2024-02-08 15:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +This is not an often used feature of Tyk and has not been implemented in the Tyk Dashboard UI, nor in the [Tyk OAS API]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas" >}}).
```suggestion
This feature is rarely used and has not been implemented in the Tyk Dashboard UI, nor in the [Tyk OAS API]({{< ref "product-stack/tyk-gateway/middleware/response-header-tyk-oas" >}}).
```

2024-02-08 15:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
> +A middleware called `header_transform` was added in Tyk 2.1 specfically to allow you to  ensure that headers such as `Location` and `Link` reflect the outward facade of your API Gateway and also alig
```suggestion
A middleware called `header_transform` was added in Tyk 2.1 specfically to allow you to ensure that headers such as `Location` and `Link` reflect the outward facade of your API Gateway and also align with the expected response location to be terminated at the gateway, not the hidden upstream proxy.
```

2024-02-15 16:18 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-03-19 12:21 UTC, dcs3spp commented
Resolved review comments, awaiting images / video placeholders and peer approval

2024-03-20 15:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
> + < placeholder for video >
Will use screenshots for initial version

2024-03-20 16:27 UTC, andyo-tyk commented
@lghiur has concluded his peer review in this Jira ticket - https://tyktech.atlassian.net/browse/TT-11560

2024-03-20 16:34 UTC, dcs3spp approved these changes

2024-03-20 16:37 UTC, merged