Update tyk-helm-tyk-stack.md
TykTechnologies/tyk-docs-hugo pull request #4026
Opened 2024-01-25 12:32 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-01-25 17:21 UTC, dcs3spp requested changes
PR content LGTM, have made some suggestions and will discuss intro of tabs in scheduled content meet next week. This page could be part of a refactor that introduces separate pages for Postgres and MongoDB quickstart maybe

2024-01-25 17:21 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +We would need the PostgreSQL connection string for Tyk  installation. You can store it in a secret and provide the secret in installation later.
```suggestion
We require the PostgreSQL connection string for Tyk installation. This can be stored in a secret and will be used in installation later.
```

2024-01-25 17:21 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +>NOTE: Please make sure you are installing MongoDB or PostgreSQL versions that are supported by Tyk. Please refer to Tyk docs to get list of [supported versions]({{< ref "tyk-dashboard/database-optio
```suggestion
{{< note >}}
**Note**

Ensure that you are installing PostgreSQL versions that are supported by Tyk. Please consult the list of [supported versions]({{< ref "tyk-dashboard/database-options" >}}) that are compatible with Tyk.
{{< /note >}}
```

2024-01-25 17:21 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +We would need the MongoDB connection string for Tyk installation. You can store it in a secret and provide the secret in installation later.
```suggestion
We require the MongoDB connection string for Tyk installation. You can store it in a secret and provide the secret in installation later.
```

2024-01-25 17:21 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +>NOTE: Please make sure you are installing MongoDB or PostgreSQL versions that are supported by Tyk. Please refer to Tyk docs to get list of [supported versions]({{< ref "tyk-dashboard/database-optio
```suggestion
{{< note >}}
**Note**

Ensure that you are installing MongoDB versions that are supported by Tyk. Please consult the list of [supported versions]({{< ref "tyk-dashboard/database-options" >}}) that are compatible with Tyk.
{{< /note >}}
```

2024-01-25 17:21 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +See [helm repo](https://helm.sh/docs/helm/helm_repo/) for command documentation.
```suggestion
For further documentation relating to *helm* command usage, please refer to the [helm repo](https://helm.sh/docs/helm/helm_repo/).
```

2024-02-02 16:32 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +{{< tabs_start >}}
Could we move out each tab into a separate page maybe in a future iteration?

2024-02-06 16:53 UTC, dcs3spp commented
Hi @caroltyk is it possible to arrange a peer review before releasing this?

2024-02-13 09:06 UTC, carlostyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  - Tyk Pump to send analytics to PostgreSQL and Prometheus
If I am not mistaken, we won't be installing Prometheus with tyk-stack. This could be misleading for users since they may understand that it is needed for Tyk to run.

2024-02-13 09:07 UTC, carlostyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  - Tyk Pump to send analytics to MongoDB and Prometheus
Same comment as previous one. Prometheus isn't installed with Tyk-Stack, this could be misleading

2024-02-13 09:09 UTC, carlostyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +{{< tab_start "Quick Start with MongoDB" >}}
Add a note mentioning that if MongoDB is chosen as dependency then Ent Dev Portal cannot be installed in the Quickstart since it would need a Postgres.

2024-02-13 09:11 UTC, carlostyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  ## Installing The Chart
I would keep the Quick Start section and all below in different pages. If I read fast I think the quick start isn't that quick at all...

2024-02-13 09:11 UTC, carlostyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  ## Installing The Chart
You could make a single section with Chart configuration and then another one with tyk stack elements configuration.

2024-02-13 10:11 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  - Tyk Pump to send analytics to PostgreSQL and Prometheus
```suggestion
- Tyk Pump to send analytics to PostgreSQL. It also opens a metrics endpoint where Prometheus (if available) can scrape from.
```

2024-02-13 10:12 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  - Tyk Pump to send analytics to MongoDB and Prometheus
```suggestion
- Tyk Pump to send analytics to MongoDB. It also opens a metrics endpoint where Prometheus (if available) can scrape from.
```

2024-02-13 10:15 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  ## Installing The Chart
@dcs3spp There's no clear visual separation between the Quick start sections (the tabs) and the rest of the page. We need something to let users know the Quick start section has ended and the the rest is complete / comprehensive documentation.

Should we add another heading, separate them into two pages, or any other suggestions?

2024-02-13 16:25 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  ## Installing The Chart
@caroltyk suggested in previous [review](https://github.com/TykTechnologies/tyk-docs/pull/4026#discussion_r1476276501) adding quick starts as pages. How soon does the PR need releasing?
If it is needed soon then could use <hr> HTML tag in the markdown to separate the sections.

Another consideration is if the charts pages in this PR will be deprecated since we also have the [product stack](https://deploy-preview-4076--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-charts/overview/) section for Tyk Charts? For example there is:
- Windows with Helm chart
- Legacy Tyk Pro Helm chart

Should these existing pages be moved into the new product stack section for helm charts also?

2024-02-13 16:49 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  ## Installing The Chart
I think we can add a horizontal rule HTML now and release first.

We can have better solution (separate quick start pages) in the new product stack structure.

2024-02-13 18:18 UTC, dcs3spp reviewed
Hi @caroltyk Carol, thanks for discussing. Summary of changes before release:

- Remove status of new charts heading and refactor into linking sentence that summarises the status table.
- Add a H2 heading _What components are deployed with Tyk Stack Chart?_ to cover the section starting from:

_tyk-stack provides the default deployment of Tyk Self Managed on a Kubernetes cluster. It will deploy all required Tyk components with the settings provided in the values.yaml file._ and ending at _Also, you can set the version of each component through image.tag. You could find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio)._

Before each section on the right hand navigation menu include a HTML hr tag in the markdown so that the beginning and end of each section is clear to the reader.

2024-02-13 18:32 UTC, dcs3spp approved these changes

2024-02-13 18:34 UTC, dcs3spp reviewed
Add horizontal rule before each section. @carlostyk If you could do another peer review. Carol and I have discussed and made some structural changes as a short fix before the new product stack section of Tyk charts replaces this page.

2024-02-14 08:40 UTC, carlostyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +
This space only exists in the "PostgreSQL" tab but not in the MongoDB one. I would either delete it here or added in the other one.

2024-02-14 08:42 UTC, carlostyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
>  ## Installing The Chart
Love it! This more straight forward. Thank you for the fix!

2024-02-14 08:42 UTC, carlostyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +
Looks perfect thank you @caroltyk and @dcs3spp

2024-02-14 08:44 UTC, carlostyk requested changes

2024-02-14 08:44 UTC, carlostyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +
This space exists in the PostgreSQL tab but not in the MongoDB one. For consistency would remove this one or added in the other section.

2024-02-14 09:08 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +
I've added extra space in MongoDB section.

2024-02-14 12:55 UTC, carlostyk approved these changes
LGTM

2024-02-15 12:49 UTC, merged

2024-02-15 12:50 UTC, dcs3spp commented
/release to release-5.2