[DX-999] Updated allow and block list docs
TykTechnologies/tyk-docs-hugo pull request #4027
Opened 2024-01-25 12:54 UTC by andyo-tyk

### Preview Link
https://deploy-preview-4027--tyk-docs.netlify.app/docs/nightly/advanced-configuration/transform-traffic/endpoint-designer/
https://deploy-preview-4027--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/middleware/allow-list-middleware/
https://deploy-preview-4027--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/middleware/block-list-middleware/

### Description
Improved the allow list and block list docs, adding OAS

2024-01-25 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> +
```suggestion

The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the API-level response header transform.
```

2024-01-25 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> +
```suggestion

The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the API-level response header transform.
```

2024-01-25 16:32 UTC, andyo-tyk reviewed
Typos

2024-01-25 16:32 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> +The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the API-level response header transform.
```suggestion
The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the allow list feature.
```

2024-01-25 16:32 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> +The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the API-level response header transform.
```suggestion
The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the block list feature.
```

2024-01-30 10:32 UTC, dcs3spp requested changes
PR LGTM Andy. Made some minor suggestions:

- Grammar suggestions
- Remove ##Overview H2 headings
- Remember to add placeholder videos

then can approve and mark for release once peer reviewed

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +Adding an endpoint to the allow list will cause the entire API to become blocked except for endpoints on the allow list. Any non-specified routes will be blocked, and only those with the _allow list_
_ This is great if you wish to have very select access rules for your services._

Should it be _ This is great if you wish to have very fine grained select access rules for your services._?

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +Tyk Gateway does not actually maintain a list of allowed endpoints but rather works on the model whereby if the _allow list_ middleware is added to an endpoint then this will automatically enable a b
```suggestion
Tyk Gateway does not actually maintain a list of allowed endpoints but rather works on the model whereby if the _allow list_ middleware is added to an endpoint then this will automatically block all other endpoints.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +It is important, therefore, to ensure that if you enable the allow list feature by adding the middleware to any endpoint that you also add the middleware to any other endpoint to which you wish to ac
Could maybe use a note or warning to highlight this:

```suggestion
{{< warning success >}}
**Warning**  

If you enable the allow list feature by adding the middleware to any endpoint, ensure that you also add the middleware to any other endpoint for which you wish to accept requests.
{{< /warning >}}
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +<!-- proposed "summary box" to be shown graphically on each middleware page
remember to add details mentioned in the comment

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +tags: ["Allow list", "middleware", "per-endpoint", "Tyk Classic"]
```suggestion
tags: ["Allow list", "middleware", "per-endpoint", "Tyk Classic", "Tyk Classic APIs"]
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +## Overview
Remove H2 heading so have page title, intro paragraph and then section headings

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +Historically Tyk followed the out-dated whitelist/blacklist naming convention. We are working to remove this terminology from the product and documentation, however this configuration object currentl
```suggestion
Historically, Tyk followed the out-dated whitelist/blacklist naming convention. We are working to remove this terminology from the product and documentation, however this configuration object currently retains the old name.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +In this example the allow list middleware has been configured for HTTP `GET` and `PUT` requests to the `/status/200` endpoint. Requests to any other endpoints will be rejected with `HTTP 403 Forbidde
```suggestion
In this example the allow list middleware has been configured for HTTP `GET` and `PUT` requests to the `/status/200` endpoint. Requests to any other endpoints will be rejected with `HTTP 403 Forbidden`, unless they also have the allow list middleware enabled.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +Note:
Maybe use {{< note ...}} here

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> + - the allow list has been configured to be case sensitive, so calls to `GET /Status/200` will also be rejected
```suggestion
- The allow list has been configured to be case sensitive, so calls to `GET /Status/200` will also be rejected
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> + - the endpoint path has not been terminated with `$` so requests to, for example, `GET /status/200/foobar` will be allowed as the [regular expression pattern match]({{< ref "product-stack/tyk-gatewa
```suggestion
- The endpoint path has not been terminated with `$`. Thus requests to, for example, `GET /status/200/foobar` will be allowed as the [regular expression pattern match]({{< ref "product-stack/tyk-gateway/middleware/allow-list-middleware#endpoint-parsing" >}}) will recognise this as `GET /status/200`
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +From the **Endpoint Designer** add an endpoint that matches the path for which you want to allow access. Select the **Whitelist** plugin.
```suggestion
From the **Endpoint Designer**, add an endpoint that matches the path for which you want to allow access. Select the **Whitelist** plugin.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +Use the *save* or *create* buttons to save the changes and make the allow list middleware active.
```suggestion
Use the *save* or *create* buttons to save the changes and activate the allow list middleware active.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> +tags: ["Allow list", "middleware", "per-endpoint", "Tyk OAS"]
```suggestion
tags: ["Allow list", "middleware", "per-endpoint", "Tyk OAS", "Tyk OAS APIs"]
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> +## Overview
Remove H2 headings so have page title, then introduction paragraph followed by section headings.

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> +In this example the allow list middleware has been configured for HTTP `GET` and `PUT` requests to the `/status/200` endpoint. Requests to any other endpoints will be rejected with `HTTP 403 Forbidde
```suggestion
In this example the allow list middleware has been configured for HTTP `GET` and `PUT` requests to the `/status/200` endpoint. Requests to any other endpoints will be rejected with `HTTP 403 Forbidden`, unless they also have the allow list middleware enabled.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> + - the allow list has been configured to be case insensitive, so calls to `GET /Status/200` will be allowed
```suggestion
 - The allow list has been configured to be case insensitive, so calls to `GET /Status/200` will be allowed
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> + - the endpoint path has not been terminated with `$` so requests to, for example, `GET /status/200/foobar` will be allowed as the [regular expression pattern match]({{< ref "product-stack/tyk-gatewa
```suggestion
 - The endpoint path has not been terminated with `$`. Thus requests to, for example, `GET /status/200/foobar` will be allowed as the [regular expression pattern match]({{< ref "product-stack/tyk-gateway/middleware/allow-list-middleware#endpoint-parsing" >}}) will recognise this as `GET /status/200`
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> +## Configuring the allow list in the API Designer
```suggestion

## Configuring the allow list in the API Designer
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
> +If you are versioning your API are deprecating an endpoint then, instead of having to remove the functionality from your upstream service's API you can simply block access to it using the block list
```suggestion
If you are versioning your API and deprecating an endpoint then, instead of having to remove the functionality from your upstream service's API you can simply block access to it using the block list middleware.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
> +By default the block list is case-sensitive, so for example if you have defined the endpoint `/getuser` in your API definition then only calls to `/getuser` will be blocked: calls to `getUser` or `Ge
```suggestion
By default the block list is case-sensitive. For example, if you have defined the endpoint `/getuser` in your API definition then only calls to `/getuser` will be blocked: calls to `getUser` or `GetUser` will be allowed. You can configure the middleware to be case insensitive at the endpoint level.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
> +  - The Block List is an optional stage in Tyk's API Request processing chain, sitting between the [TBC]() and [TBC]() middleware.
One links available, remember to add details mentioned in comments

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> +tags: ["Block list", "middleware", "per-endpoint", "Tyk Classic"]
```suggestion
tags: ["Block list", "middleware", "per-endpoint", "Tyk Classic", "Tyk Classic APIs"]
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> +## Overview
Remove H2 overview heading so that have page title, introduction paragraph followed by section headings.

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> +Historically Tyk followed the out-dated whitelist/blacklist naming convention. We are working to remove this terminology from the product and documentation, however this configuration object currentl
```suggestion
Historically, Tyk followed the out-dated whitelist/blacklist naming convention. We are working to remove this terminology from the product and documentation, however this configuration object currently retains the old name.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> + - the block list has been configured to be case sensitive, so calls to `GET /Status/200` will not be rejected
```suggestion
 - The block list has been configured to be case sensitive, so calls to `GET /Status/200` will not be rejected
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> + - the endpoint path has not been terminated with `$` so requests to, for example, `GET /status/200/foobar` will be rejected as the [regular expression pattern match]({{< ref "product-stack/tyk-gatew
```suggestion
 - The endpoint path has not been terminated with `$`. Thus requests to, for example, `GET /status/200/foobar` will be rejected as the [regular expression pattern match]({{< ref "product-stack/tyk-gateway/middleware/block-list-middleware#endpoint-parsing" >}}) will recognise this as `GET /status/200`
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> +Use the *save* or *create* buttons to save the changes and make the block list middleware active.
```suggestion
Use the *save* or *create* buttons to save the changes and activate the block list middleware.
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> +tags: ["Block list", "middleware", "per-endpoint", "Tyk OAS"]
```suggestion
tags: ["Block list", "middleware", "per-endpoint", "Tyk OAS APIs"]
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> +## Overview
Remove H2 heading so have page title, introduction paragraph then section headings

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> + - the block list has been configured to be case insensitive, so calls to `GET /Status/200` will also be blocked
```suggestion
 - The block list has been configured to be case insensitive, so calls to `GET /Status/200` will also be blocked
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> + - the endpoint path has not been terminated with `$` so requests to, for example, `GET /status/200/foobar` will be rejected as the [regular expression pattern match]({{< ref "product-stack/tyk-gatew
```suggestion
 - The endpoint path has not been terminated with `$`. Thus requests to, for example, `GET /status/200/foobar` will be rejected as the [regular expression pattern match]({{< ref "product-stack/tyk-gateway/middleware/block-list-middleware#endpoint-parsing" >}}) will recognise this as `GET /status/200`
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> +## Configuring the block list in the API Designer
```suggestion

## Configuring the block list in the API Designer
```

2024-01-30 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-02-02 14:15 UTC, andyo-tyk reviewed
Multiple minor improvements

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +Adding an endpoint to the allow list will cause the entire API to become blocked except for endpoints on the allow list. Any non-specified routes will be blocked, and only those with the _allow list_
It's not quite this - more that you only want to allow access to the specific endpoints that are published on Tyk and no un-published endpoints that a user might stumble upon.

```suggestion
Adding an endpoint to the allow list will cause the entire API to become blocked except for endpoints on the allow list. Any non-specified routes will be blocked, and only those with the _allow list_ middleware in the Endpoint Designer will be allowed through. This is great if you wish to have very strict access rules for your services, limiting access to specific published endpoints.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +## Overview
```suggestion
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +Note:
I didn't want to because I don't want this to hit the reader in the face, it's more of an aside than a "PLEASE NOTE" (which I feel the {{< note >}} formatting provides. :)

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +Note:
I will, however, improve this slightly.
```suggestion
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> + - the allow list has been configured to be case sensitive, so calls to `GET /Status/200` will also be rejected
```suggestion
Note that the allow list has been configured to be case sensitive, so calls to `GET /Status/200` will also be rejected.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> + - the endpoint path has not been terminated with `$` so requests to, for example, `GET /status/200/foobar` will be allowed as the [regular expression pattern match]({{< ref "product-stack/tyk-gatewa
```suggestion
Note also that the endpoint path has not been terminated with `$`. Requests to, for example, `GET /status/200/foobar` will be allowed as the [regular expression pattern match]({{< ref "product-stack/tyk-gateway/middleware/allow-list-middleware#endpoint-parsing" >}}) will recognise this as `GET /status/200`.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> +## Overview
```suggestion
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> +When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within the `
```suggestion
When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> + - the allow list has been configured to be case insensitive, so calls to `GET /Status/200` will be allowed
```suggestion
Note that the allow list has been configured to be case insensitive, so calls to `GET /Status/200` will be allowed
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> + - the endpoint path has not been terminated with `$` so requests to, for example, `GET /status/200/foobar` will be allowed as the [regular expression pattern match]({{< ref "product-stack/tyk-gatewa
```suggestion
Note also that the endpoint path has not been terminated with `$`. Requests to, for example, `GET /status/200/foobar` will be allowed as the [regular expression pattern match]({{< ref "product-stack/tyk-gateway/middleware/allow-list-middleware#endpoint-parsing" >}}) will recognise this as `GET /status/200`.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> +## Overview
```suggestion
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> +When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition; this can be done manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> +Note:
```suggestion

```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> + - the block list has been configured to be case sensitive, so calls to `GET /Status/200` will not be rejected
```suggestion
Note that the block list has been configured to be case sensitive, so calls to `GET /Status/200` will not be rejected.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> + - the endpoint path has not been terminated with `$` so requests to, for example, `GET /status/200/foobar` will be rejected as the [regular expression pattern match]({{< ref "product-stack/tyk-gatew
```suggestion
Note also that the endpoint path has not been terminated with `$`. Requests to, for example, `GET /status/200/foobar` will be rejected as the [regular expression pattern match]({{< ref "product-stack/tyk-gateway/middleware/block-list-middleware#endpoint-parsing" >}}) will recognise this as `GET /status/200`.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> +## Overview
```suggestion
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> +When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}); this can be done manually within the `
```suggestion
When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> + - the block list has been configured to be case insensitive, so calls to `GET /Status/200` will also be blocked
```suggestion
Note that the block list has been configured to be case insensitive, so calls to `GET /Status/200` will also be blocked.
```

2024-02-02 14:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> + - the endpoint path has not been terminated with `$` so requests to, for example, `GET /status/200/foobar` will be rejected as the [regular expression pattern match]({{< ref "product-stack/tyk-gatew
```suggestion
Note also that the endpoint path has not been terminated with `$`. Requests to, for example, `GET /status/200/foobar` will be rejected as the [regular expression pattern match]({{< ref "product-stack/tyk-gateway/middleware/block-list-middleware#endpoint-parsing" >}}) will recognise this as `GET /status/200`.
```

2024-02-05 16:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +## Overview
Remove H2 overview heading

2024-02-05 17:00 UTC, andyo-tyk reviewed
Removed H2 Overview headings

2024-02-05 17:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +## Overview
```suggestion
```

2024-02-05 17:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
> +## Overview
```suggestion
```

2024-02-08 15:17 UTC, dcs3spp requested changes
PR LGTM Andy. I think this PR is ready apart from a peer review and placeholder videos.

2024-02-15 16:20 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-03-12 12:40 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +{{< warning success >}}
visually this is displayed with red, I think it should be orange/yellow

2024-03-12 12:40 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +By default the allow list is case-sensitive, so for example if you have defined the endpoint `/getuser` in your API definition then only calls to `/getuser` will be allowed: calls to `getUser` or `Ge
I would use more REST endpoints. Instead of `/getuser` to use `GET /user` and `GET /User`. this way we highlight the http method and also the endpoint is more REST

2024-03-12 12:40 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
> +By default the block list is case-sensitive. For example, if you have defined the endpoint `/getuser` in your API definition then only calls to `/getuser` will be blocked: calls to `getUser` or `GetU
I would use more REST endpoints. Instead of /getuser to use GET /user and GET /User. this way we highlight the http method and also the endpoint is more REST

2024-03-21 15:30 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +{{< warning success >}}
I'll change it from "warning" to "note" style

2024-03-21 16:21 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> +From the **Endpoint Designer** add an endpoint that matches the path for which you want to prevent access. Select the **Blacklist** plugin.
@andyo-tyk Should there be an image for this step?

2024-03-21 16:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
> +From the **Endpoint Designer** add an endpoint that matches the path for which you want to prevent access. Select the **Blacklist** plugin.
Deliberately omitted while we continue to use offensive terms in the UI, the instructions are clear enough IMHO

2024-03-21 16:29 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
> + < placeholder for video >
Agreed to revisit later in separate PR

2024-03-21 16:29 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> + < placeholder for video >
Agreed to revisit later in separate PR

2024-03-21 16:30 UTC, dcs3spp approved these changes

2024-03-21 16:31 UTC, merged