update mongo installation instructions
TykTechnologies/tyk-docs-hugo pull request #403
Opened 2018-04-27 17:07 UTC by asoorm

https://github.com/TykTechnologies/tyk-docs/issues/402

Updating Mongo Installation Docs for Ubuntu 14.04 and 16.04

2018-04-27 17:14 UTC, excieve requested changes
If both 14.04 and 16.04 are going to be mentioned here please make sure to test that both are working through these instructions.

2018-04-27 17:14 UTC, excieve commented on tyk-docs/content/get-started/with-tyk-on-premise/installation/on-ubuntu/installationubuntu.md
> +### Install MongoDb 3.6
I don't think we ever tested extensively on 3.6. Might work fine but not sure if we want to recommend it through this guide.

2018-04-27 17:14 UTC, excieve commented on tyk-docs/content/get-started/with-tyk-on-premise/installation/on-ubuntu/installationubuntu.md
> +echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
Should be `xenial` instead of `trusty` for 16.04.

2018-04-27 17:14 UTC, excieve commented on tyk-docs/content/get-started/with-tyk-on-premise/installation/on-ubuntu/installationubuntu.md
> +# sudo systemctl start mongod
These won't work on 14.04. It doesn't have systemd.

2018-04-27 17:20 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-on-premise/installation/on-ubuntu/installationubuntu.md
> +### Install MongoDb 3.6
what's the officially supported / tested version of mongo?

2018-04-27 17:23 UTC, excieve commented on tyk-docs/content/get-started/with-tyk-on-premise/installation/on-ubuntu/installationubuntu.md
> +### Install MongoDb 3.6
3.0 and 3.2

2018-04-27 17:34 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-on-premise/installation/on-ubuntu/installationubuntu.md
> +# sudo systemctl start mongod
oh yes... good spot

2018-04-27 18:15 UTC, asoorm commented
@excieve checked with both 14.04 and 16.04 against Mongo 3.2

2018-04-27 21:10 UTC, marksou approved these changes
Looks good to me.

2018-04-27 21:11 UTC, marksou approved these changes
Looks good to me.

2018-04-28 17:32 UTC, excieve approved these changes

2018-04-28 19:12 UTC, merged