Make it easier to find tyk demos
TykTechnologies/tyk-docs-hugo pull request #4030
Opened 2024-01-26 00:37 UTC by letzya

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-01-30 11:08 UTC, dcs3spp requested changes
PR LGTM, I've made minor suggestions relating to menu item names and grammar

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/getting-started-your-poc.md
> +If you've successfully completed the [Quick Start]({{<ref "getting-started/quick-start">}}), congratulations! This page is the **next step** in your Tyk journet and designed for users who are ready t
```suggestion
If you've successfully completed the [Quick Start]({{<ref "getting-started/quick-start">}}), congratulations! This page is the **next step** in your Tyk journey and designed for users who are ready to play with Tyk, learn more about Tyk's capabilities, services, and integration options.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/getting-started-your-poc.md
> +Use these projects as your **playground** to test, configure, experiment new features, try the various Tyk API definitions, and later for your day-to-day development of APIs. We hope you find them va
```suggestion
Use these projects as your **playground** to test, configure, experiment with new features and try the various Tyk API definitions for your day-to-day development of APIs. We hope you find them valuable. Feel free to reach out with any feedback.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-open-source-api-gateway/quick-start.md
> +New to Tyk Gateway? In this page you'll get started with the basics - install Tyk and test it's live in less than 2 minutes.
```suggestion
New to Tyk Gateway? In this page you'll get started with the basics - install Tyk and test it live in less than 2 minutes.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start.md
> +## Next Step - Proof of Concept
```suggestion
## Next Step - Proof of Concept (PoC)
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start.md
> +You have completed the quick start guide above and wonder what's next, please read below -
```suggestion
You have completed the quick start guide above and wonder what's next, please read below.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start.md
> +Head over to our **Tyk Demo** guides in [Kubernetes]({{<ref "getting-started/quick-start/tyk-k8s-demo">}}) or [Docker]({{<ref "getting-started/quick-start/tyk-demo">}}). These guides with zero to non
```suggestion
Head over to our **Tyk Demo** guides in [Kubernetes]({{<ref "getting-started/quick-start/tyk-k8s-demo">}}) or [Docker]({{<ref "getting-started/quick-start/tyk-demo">}}). These guides, with zero to none effort, will spin up the full Tyk infrastructure (Tyk stack) with examples of Tyk's capabilities and integrations out-of-the-box.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +If you are running a POC and would like an example of how to integrate a specific tool, you are welocmed to submit a [feature request](https://github.com/TykTechnologies/tyk-k8s-demo/issues/new/choos
```suggestion
If you are running a POC and would like an example of how to integrate a specific tool, you are welcome to submit a [feature request](https://github.com/TykTechnologies/tyk-k8s-demo/issues/new/choose)
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +  - [Prometheus](https://github.com/TykTechnologies/tyk-k8s-demo/tree/v3/src/deployments/prometheus): deploys Prometheus and starts up Tyk pPump to push analytics data from the Tyk platform to Promet
```suggestion
  - [Prometheus](https://github.com/TykTechnologies/tyk-k8s-demo/tree/v3/src/deployments/prometheus): deploys Prometheus and starts up Tyk Pump to push analytics data from the Tyk platform to Prometheus.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +  - [operator](https://github.com/TykTechnologies/tyk-k8s-demo/tree/v3/src/deployments/operator): deploys the *Tyk Operator* and its dependency [cert-manager](https://github.com/jetstack/cert-manager
```suggestion
- [Tyk Operator](https://github.com/TykTechnologies/tyk-operator)
  - [operator](https://github.com/TykTechnologies/tyk-k8s-demo/tree/v3/src/deployments/operator): deploys the *Tyk Operator* and it's dependency [cert-manager](https://github.com/jetstack/cert-manager).
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +  - [elasticsearch](https://github.com/TykTechnologies/tyk-k8s-demo/tree/v3/src/deployments/elasticsearch): deploys Elasticsearch and starts up Tyk pump to push analytics data from the Tyk platform t
```suggestion
  - [elasticsearch](https://github.com/TykTechnologies/tyk-k8s-demo/tree/v3/src/deployments/elasticsearch): deploys Elasticsearch and starts up Tyk Pump to push analytics data from the Tyk platform to Elasticsearch.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
> +The script has defaults for minimal settings in a [.env](https://github.com/TykTechnologies/tyk-k8s-demo/blob/v3/.env.example)file, and it will give errors if something is missing. You can also add o
```suggestion
The script has defaults for minimal settings in a [.env](https://github.com/TykTechnologies/tyk-k8s-demo/blob/v3/.env.example) file and it will give errors if something is missing. You can also add or change any Tyk environments variables in the `.env` file and they will be mapped to the respective `extraEnvs` section in the helm charts.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/monitoring/tyk-components.md
> +description: "Monitor Tyk components and their dependencies; How to set up monitoring and observability of your API kingdom"
```suggestion
description: "Monitor Tyk components and their dependencies; how to set up monitoring and observability of your API kingdom"
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/docker/docker-pro-demo.md
> +title: Tyk on a Simple Docker Compose
```suggestion
title: Running Tyk Within A Simple Docker Compose Stack
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/docker/docker-pro-demo.md
> +This is a guide to get started you PoC with Tyk using our project *Docker Pro Demo*
```suggestion
This is a guide to get you started with Tyk using our PoC project, *Docker Pro Demo*
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/docker/docker-pro-demo.md
> +This demo is NOT intended for production use or performance testing. The reason: It's Docker Compose-based, and the configuration files are not specifically tuned for performance testing or high load
```suggestion
This demo is NOT intended for production use or performance testing, since it uses docker compose and the configuration files are not specifically tuned for performance testing or high loads. Please visit the [Planning for Production]({{<ref "planning-for-production/">}}) page to learn how to configure settings for optimal performance.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/docker/docker-pro-demo.md
> +## Inroduction
```suggestion
## Introduction
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/tyk-on-premises/docker/docker-pro-demo.md
> +The Pro Docker demo does not provide access to the [Developer Portal]({{< ref "tyk-developer-portal/tyk-enterprise-developer-portal" >}}).
```suggestion
The Tyk Pro Docker demo does not provide access to the [Developer Portal]({{< ref "tyk-developer-portal/tyk-enterprise-developer-portal" >}}).
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/getting-started-your-poc.md
> +Each starts quickly by spinning up Tyk along with various deployment settings, architectures and integrations such as *MDCB, Tyk Operator, Keycloak, Jaeger, Prometheus* and more.
```suggestion

Each starts quickly by spinning up Tyk along with various deployment settings, architectures and integrations such as *MDCB, Tyk Operator, Keycloak, Jaeger, Prometheus* and more.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/getting-started-your-poc.md
> +Both repositories include *Postman collections*, that make it easy to explore and experience Tyk's features and functionality.
```suggestion

Both repositories include *Postman collections*, to facilitate exploration and experiencing Tyk's features and functionality.
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/content/getting-started/quick-start.md
> +The recommended way for starting your free trial is via *Docker*. Further instructions for installation docker are available [here](https://docs.docker.com/get-docker/).
```suggestion
The recommended way for starting your free trial is via *Docker*. Further instructions for installing with docker are available [here](https://docs.docker.com/get-docker/).
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +            - title: "Tyk Oon a Simple Docker Compose"
```suggestion
            - title: "Tyk On a Simple Docker Compose Stack"
```

2024-01-30 11:08 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +          - title: "Getting Started Your Tyk PoC"
```suggestion
          - title: "Getting Started (Your Tyk PoC)"
```

2024-01-30 18:28 UTC, letzya commented on tyk-docs/content/getting-started/quick-start.md
> +The recommended way for starting your free trial is via *Docker*. Further instructions for installation docker are available [here](https://docs.docker.com/get-docker/).
actually isn't it "docker installation" ?

2024-01-30 18:30 UTC, letzya commented on tyk-docs/content/getting-started/quick-start.md
> +The recommended way for starting your free trial is via *Docker*. Further instructions for installation docker are available [here](https://docs.docker.com/get-docker/).
```suggestion
The recommended way to start your free trial is via *Docker*. Follow the [instructions](https://docs.docker.com/get-docker/) to install *Docker*.
```

2024-01-30 18:33 UTC, letzya commented on tyk-docs/content/tyk-on-premises/docker/docker-pro-demo.md
> +title: Tyk on a Simple Docker Compose
Not sure

2024-01-30 18:39 UTC, letzya commented on tyk-docs/content/tyk-on-premises/docker/docker-pro-demo.md
> +This is a guide to get started you PoC with Tyk using our project *Docker Pro Demo*
but it's not "our poc", it's the user's poc.

2024-01-30 18:42 UTC, letzya commented on tyk-docs/content/getting-started/quick-start.md
> +Title: Quick Start (Free Trial)
```suggestion
Title: Quick Start - Free Trial
```

2024-01-30 18:42 UTC, letzya commented on tyk-docs/data/menu.yaml
> +      - title: "Quick Start (Free Trial)"
```suggestion
      - title: "Quick Start - Free Trial"
```

2024-01-30 18:45 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          - title: "Getting Started Your Tyk PoC"
why brackets

2024-01-30 21:27 UTC, letzya commented
what do you think about the new IA?

2024-01-31 14:15 UTC, dcs3spp approved these changes
Thanks @letzya PR LGTM

2024-01-31 22:06 UTC, letzya commented
@zalbiraw please have a look. We had a long session to sort this out and we plan to merge it tomorrow.

2024-02-01 11:29 UTC, dcs3spp commented
@zalbiraw would you be able to peer review?

2024-02-01 14:09 UTC, zalbiraw approved these changes
Looks good, the only suggestion I would make is also adding the POC section the hybrid and oss deployments for k8s. The library supports those deployment models as well not just self-managed.

2024-02-01 14:11 UTC, letzya commented
> Looks good, the only suggestion I would make is also adding the POC section the hybrid and oss deployments for k8s. The library supports those deployment models as well not just self-managed.

Yes, in the next sprint probably

2024-02-01 17:09 UTC, dcs3spp approved these changes

2024-02-01 17:11 UTC, merged

2024-02-01 17:11 UTC, dcs3spp commented
/release to release-5.2

2024-02-01 17:14 UTC, dcs3spp commented
/release to release-5.1