Improved Ignore Authentication
TykTechnologies/tyk-docs-hugo pull request #4031
Opened 2024-01-26 10:50 UTC by andyo-tyk

### Preview Link

### Description
Improved documentation of Ignore Auth middleware

2024-01-30 10:49 UTC, dcs3spp requested changes
PR LGTM Andy. I've added the following minor suggestions below, then once approved and peer reviewed we can mark PR as ready for release

- Minor grammar suggestions
- Remove H2 ## overview headings
- Remember to add placeholder video

2024-01-30 10:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
> +It is important to exercise caution when using the Ignore Authentication middleware, as it effectively disables Tyk's security features for the ignored paths. Only endpoints that are designed to be p
```suggestion
It is important to exercise caution when using the Ignore Authentication middleware, as it effectively disables Tyk's security features for the ignored paths. Only endpoints that are designed to be public or have independent security mechanisms should be configured to bypass authentication in this way. When combining Ignore Authentication with response transformations be careful not to inadvertently expose sensitive data or rely on authentication or session data that is not present.
```

2024-01-30 10:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
> +tags: ["ignore authentication", "ignore", "ignore auth", "authentication", "middleware", "per-endpoint", "Tyk Classic"]
```suggestion
tags: ["ignore authentication", "ignore", "ignore auth", "authentication", "middleware", "per-endpoint", "Tyk Classic", "Tyk Classic APIs"]
```

2024-01-30 10:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
> +When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition, either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-30 10:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
> + - the allow list has been configured to be case sensitive, so calls to `GET /Status/200` will not skip authentication
```suggestion
 - The allow list has been configured to be case sensitive, so calls to `GET /Status/200` will not skip authentication
```

2024-01-30 10:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
> +tags: ["ignore authentication", "ignore", "ignore auth", "authentication", "middleware", "per-endpoint", "Tyk OAS"]
```suggestion
tags: ["ignore authentication", "ignore", "ignore auth", "authentication", "middleware", "per-endpoint", "Tyk OAS", "Tyk OAS APIs"]
```

2024-01-30 10:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
> + - the allow list has been configured to be case sensitive, so calls to `GET /Status/200` will not skip authentication
```suggestion
 - The allow list has been configured to be case sensitive, so calls to `GET /Status/200` will not skip authentication
```

2024-01-30 10:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-02-02 14:02 UTC, andyo-tyk reviewed
Minor improvements

2024-02-02 14:02 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
> +When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition, either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 14:02 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
> +When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}) either manually within the `.json` file
```suggestion
When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-15 16:21 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-03-14 16:13 UTC, titpetric commented
Reopening for peer review

2024-03-19 08:14 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
> +#### Health and liveness endpoints
I expected a list of possible use cases here, but only one example is listed.

2024-03-19 08:17 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
> +#### Case sensitivity
The headings in this doc are a bit confusing

- h2 When to use [...]
    - h4 Health and liveliness endpoints
- h2 How ignore authentication works
    - h4 Case sensitivity

This produces a table of contents that doesn't seem balanced with information, suggesting to reorder/redefine the sections in order to make a sensible TOC

2024-03-19 08:19 UTC, titpetric approved these changes
LGTM from a technical perspective, left comments on heading/order in the overview doc.

2024-03-21 16:09 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
> +#### Health and liveness endpoints
I'm adding these retrospectively to existing (undocumented) features - if you can suggest others then please do. 🙏

2024-03-21 16:13 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
> +#### Case sensitivity
This is consistent across the various PRs. The reason I've not used every level of heading is that the style-sheet used for Tyk docs does not clearly show a difference between different levels so it's actually harder to read, even if the ToC becomes clearer... and the pages are intended to be short such that ToC is not so important.

2024-03-22 08:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
> + < placeholder for video >
I have added screenshots for now

2024-03-22 11:02 UTC, andyo-tyk commented
Closing, as this has been merged in https://github.com/TykTechnologies/tyk-docs/pull/4318

2024-03-22 11:02 UTC, closed without merging