[Dx 963] Add do_not_track Analytics FAQ
TykTechnologies/tyk-docs-hugo pull request #4032
Opened 2024-01-26 11:27 UTC by dcs3spp

[DX-963](https://tyktech.atlassian.net/browse/DX-963

[preview to add]()

2024-01-26 16:20 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +title: "When To Use do_not_track Analytics"
Would "do not track" look better?

2024-01-26 16:22 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +title: "When To Use do_not_track Analytics"
or maybe JTBD kind of a way. - "why you should not record request analytics"

2024-01-26 16:35 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +Tyk provides the *do_not_track* configuration parameter to disable tracking analytics at two levels:
```suggestion
Tyk provides the [do_not_track]({{<ref "advanced-configuration/transform-traffic/endpoint-designer/#do-not-track-endpoint">}}) configuration parameter to disable tracking analytics at two levels:
```

2024-01-26 16:43 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +- **Global**: Analytics are not tracked for all endpoints of an API.
```suggestion
- **Global**: Analytics are not tracked for all endpoints of an API.
```

2024-01-26 16:47 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +- **Global**: Analytics are not tracked for all endpoints of an API.
We have to be careful with the term "global". reading it I wasn't sure if it was per API or across all APIs.

2024-01-26 16:59 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +- **Global**: Analytics are not tracked for all endpoints of an API.
```suggestion
- **Per API**: Analytics are not tracked for all endpoints of an API.
```

2024-01-26 17:00 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +- **Global**: Analytics are not tracked for all endpoints of an API.
I think it's clearer to use the term "record" over "track" to explain the meaning

2024-01-26 17:01 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +- **Endpoint**: Analytics can be disabled for selected endpoints.
```suggestion
- **Endpoint**: Tyk Gateway will not record Analytics for requests to the selected endpoint. Other endpoints will be
tracked as normal.
```

2024-01-26 17:04 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +This can help reduce analytics traffic for systems that are under high load, exhibiting high traffic, e.g. social media platforms (Facebook, Instagram and Twitter), streaming services (YouTube, Netli
is this a good start to the paragraph `This can help`?

2024-01-26 17:15 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +In the image below we can see two APIs were setup within Tyk Dashboard for conducting a simple load test, to determine the total requests per second for each API:
```suggestion
In the screenshot below, of *Tyk Dashboard API screen* we can see two APIs, *track* and *notrack*. The APIs were created to conduct a simple load test, to show the gateway's RPS (requests per second) for each API:
```

2024-01-26 17:16 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +{{< img src="img/faq/do-not-track-usage-scenario/dashboard_apis_measured.png" alt="apis measured in Tyk Dashboard" >}}
```suggestion
{{< img src="img/faq/do-not-track-usage-scenario/dashboard_apis_measured.png" alt="apis measured in Tyk Dashboard" width="864" >}}
```

2024-01-26 17:16 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +{{< img src="img/faq/do-not-track-usage-scenario/dashboard_apis_measured.png" alt="apis measured in Tyk Dashboard" >}}
add to show you the format of the size

2024-01-26 17:18 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +We can see that **19253.75** requests per second was recorded for the *untracked* API; with **16743.6011** requests per second reported for the *tracked* API. The number of requests per seconds decre
```suggestion
We can see that **19,253.75** RPS was recorded for the *untracked* API; with **16,743.6011** RPS reported for the *tracked* API. The number of requests per second decreased by **13.0372%** when analytics was enabled. Subsequently, it is worthwhile monitoring traffic and system load and using this feature to improve performance. 
```

2024-01-26 17:22 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +This can help reduce analytics traffic for systems that are under high load, exhibiting high traffic, e.g. social media platforms (Facebook, Instagram and Twitter), streaming services (YouTube, Netli
The issue was observed when a user had a high load of CPU. So users need the FAQ to fix a problem and that's the problem. THey wouldn't know to connect the title or the content to that problem. 
So there are 2 problems - 
1. high load of CPU (we can add an image)
2. RPS is not high enough

First problem can be observed, second is more improvement or benefit than a problem. 

So to summaries, I think FAQ needs to start with the problem the user has

2024-01-26 17:23 UTC, letzya requested changes
The issue was observed when a user had a high load of CPU. So users need the FAQ to fix a problem and that's the problem. They wouldn't know how to connect the title or the content to that problem.
So there are 2 problems -
1. high load of CPU (we can add an image)
2. RPS is not high enough
The first problem can be observed, second is more improvement or benefit than a problem.

So to summarise, I think the FAQ needs to start with the problem the user has.

2024-01-29 11:49 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +- **Global**: Analytics are not tracked for all endpoints of an API.
updated

2024-01-29 11:49 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +title: "When To Use do_not_track Analytics"
updated

2024-01-29 11:49 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +This can help reduce analytics traffic for systems that are under high load, exhibiting high traffic, e.g. social media platforms (Facebook, Instagram and Twitter), streaming services (YouTube, Netli
updated

2024-01-30 20:37 UTC, letzya requested changes
@dcs3spp same comment as in the other ticket

2024-02-12 15:31 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk allows analytics to be recorded and stored in backend storage for API endpoints, via [Tyk Pump]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}). Example details include: the origina
```suggestion
Tyk allows analytics to be recorded and stored in backend storage for API endpoints, via [Tyk Pump]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}). 

Tyk allows you to keep track of how your APIs are used by recording the traffic it's processing and in the background, sending the analytics data to Redis and then, using *Tyk Pump* a [data sink]{{<ref "tyk-stack/tyk-pump/other-data-stores">}} of you choice. The [analytics data includes]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}})  details like originating host (where the request is coming from), which Tyk API version was used, HTTP method request, request path etc. This recording can sometimes introduce the problem of increased CPU load and reduced RPS (requests per second).
```

2024-02-12 15:31 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +{{< img src="/img/faq/enable-multiple-analytics-keys/redis_single.png" alt="High CPU load" width="864px" >}}
I don't think this image is relevant to this problem

2024-02-12 15:34 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk provides the [do_not_track]({{<ref "advanced-configuration/transform-traffic/endpoint-designer#do-not-track-endpoint">}}) configuration parameter to disable analytics recording at two levels:
Before introducing this field, we should explain it first. something like
"...record less info can reduce the load. Tyk allows you to decide which info is important and should be recorded and which can be skipped saving CPU cycles and storage...

2024-02-12 15:36 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk allows analytics to be recorded and stored in backend storage for API endpoints, via [Tyk Pump]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}). Example details include: the origina
We should also explain what is going to happen on this page 
"We are going to share with you config to easy this as well as an example that demonstrates this field ...."

2024-02-12 15:37 UTC, letzya requested changes
Needs more DX TLC

2024-03-01 17:02 UTC, letzya commented
@andyo-tyk since you looked into this topic. Any chance you can review this PR please?

2024-03-06 10:10 UTC, andyo-tyk reviewed
Added some comments/suggestions.

2024-03-06 10:10 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +In the *Tyk Dashboard API* screen below, there are two APIs, *track* and *notrack*. The APIs were created to conduct a simple load test, to show the gateway's RPS (requests per second) for each API:
I would be inclined to give these APIs slightly different names to avoid potential confusion with the `track` and `do_not_track` middleware / configurations.

Perhaps:
 - trackedAPI
 - untrackedAPI

2024-03-06 10:10 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk allows analytics to be recorded and stored in backend storage for API endpoints, via [Tyk Pump]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}). Example details include: the origina
I would avoid the use of the word "track" except when referring to the middleware (to minimise the risk of confusion)
I recommend we talk about how the Tyk Gateway generates "transaction records" or "analytics records" (where a transaction is an API request + response).
Then the Tyk Pump transfers the raw records to persistent storage (Mongo/SQL)
The Tyk Pump can also create aggregated data (using different data keys - API ID, access key, endpoint, response status code, location) and stores those in persistent storage
...and finally Tyk Dashboard can retrieve those data and provide analytics based on the aggregated data; it also provides the log browser that gives visibility to the raw transaction logs.

Notes:
 - by default the Gateway will generate transaction records for all APIs
 - you can selectively disable this using `do-not-track`: if this is employed then the Gateway does not generate transaction records for that API/endpoint, so there is nothing for Pump to pick up
 - the `track` middleware ONLY affects the "endpoint popularity" aggregated data generated by Pump

2024-04-03 18:51 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk provides the [do_not_track]({{<ref "advanced-configuration/transform-traffic/endpoint-designer#do-not-track-endpoint">}}) configuration parameter to disable analytics recording at two levels:
@dcs3spp

2024-04-03 18:54 UTC, letzya requested changes
@dcs3spp looks like it's waiting for updates from you. Feel free to close and do it in another sprint

2024-04-17 10:51 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk allows analytics to be recorded and stored in backend storage for API endpoints, via [Tyk Pump]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}). Example details include: the origina
updated

2024-04-17 10:51 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +{{< img src="/img/faq/enable-multiple-analytics-keys/redis_single.png" alt="High CPU load" width="864px" >}}
removed

2024-04-17 10:51 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk provides the [do_not_track]({{<ref "advanced-configuration/transform-traffic/endpoint-designer#do-not-track-endpoint">}}) configuration parameter to disable analytics recording at two levels:
updated

2024-04-17 10:56 UTC, andyo-tyk requested changes
Updated my review based on publication of the restructured/reworked analytics documentation. A couple of things that could/should be checked for consistency - plus some suggested improvements to the changes in this PR.

2024-04-17 10:56 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk Gateway allows analytics to be recorded and stored in backend storage (MongoDB/SQL) for all APIs by default, via [Tyk Pump]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}).
I recommend checking whether we consistently use the term "persistent storage" or "backend storage" or if we use them interchangeably (e.g. https://tyk.io/docs/tyk-dashboard/database-options/)

2024-04-17 10:56 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk Gateway generates transaction records for each API request and response, containing [analytics data]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}) relating to: the originating hos
I think that `tyk-analytics-record-fields.md` should probably sit in the Tyk Gateway part of the docs, as (if I understand correctly) it describes the transaction records/traffic logs generated by the Gateway. Yes, Pump picks them up and moves them around, but they are a Gateway artifact. That is, unless the records created by Gateway are actually different and this file describes them post-Pump (if, say, Pump enriches them somehow).

2024-04-17 10:56 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Users can selectively disable analytics using the [do_not_track]({{<ref "advanced-configuration/transform-traffic/endpoint-designer#do-not-track-endpoint">}}) configuration parameter. This can config
With Tyk OAS, we're planning to implement the "per-API" suppression of analytics creation slightly differently, inverting the logic so it is "enable/disable analytics" which seems more intuitive (and then you can selectively choose not to track individual endpoints if analytics is enabled for the API).

So, in anticipation of this I suggest:

```suggestion
Users can [selectively control]({{<ref "product-stack/tyk-gateway/middleware/do-not-track-middleware">}}) the generation of analytics :
```

2024-04-17 10:56 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +- **Per API**: Tyk Gateway will not record analytics for requests/responses of all endpoints of an API.
```suggestion
- **Per API**: Tyk Gateway will not create records for requests/responses for any endpoints of an API.
```

2024-04-17 10:56 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +- **Per Endpoint**: Tyk Gateway will not record analytics for requests for a specific endpoint. Other endpoints will be tracked as normal.
```suggestion
- **Per Endpoint**: Tyk Gateway will not create records for requests/responses for specific endpoints.
```

2024-04-17 10:56 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +When set, this prevents Tyk Gateway from generating the transaction records. Without transaction records, Tyk Pump will not transfer analytics to the chosen data sink. It's worth noting that the "tra
```suggestion
When set, this prevents Tyk Gateway from generating the transaction records. Without transaction records, Tyk Pump will not transfer analytics to the chosen data sink. It's worth noting that the ["track" middleware]({{< ref "product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint" >}}) exclusively influences the generation of *endpoint popularity* aggregated data by *Tyk Pump*.
```

2024-04-17 10:56 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Enabling [do_not_track]({{<ref "advanced-configuration/transform-traffic/endpoint-designer#do-not-track-endpoint">}}) disables recording of analytics per API or endpoint. This helps reduce CPU cycles
```suggestion
[Disabling]({{<ref "product-stack/tyk-gateway/middleware/do-not-track-middleware">}})  the creation of analytics (either per API or for specific endpoints) helps to reduce CPU cycles and network requests for systems that exhibit high load and traffic, e.g. social media platforms, streaming, financial services and trading platforms.
```

2024-04-17 11:00 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Users can selectively disable analytics using the [do_not_track]({{<ref "advanced-configuration/transform-traffic/endpoint-designer#do-not-track-endpoint">}}) configuration parameter. This can config
Ok thanks @andyo-tyk I'll update with suggestion

2024-04-17 11:31 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk Gateway allows analytics to be recorded and stored in backend storage (MongoDB/SQL) for all APIs by default, via [Tyk Pump]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}).
Thanks @andyo-tyk good spot!! I've updated the FAQ content to use persistent data store

2024-04-17 11:36 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk Gateway generates transaction records for each API request and response, containing [analytics data]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}) relating to: the originating hos
@andyo-tyk Looks like the Pump [analytics fields](https://tyk.io/docs/tyk-stack/tyk-pump/tyk-analytics-record-fields/) are based on raw request/response details. Could raise a separate ticket and then address the scope in a new PR.

2024-04-17 12:06 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk Gateway generates transaction records for each API request and response, containing [analytics data]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}) relating to: the originating hos
Yes, don't think it needs to be fixed in this PR, but something to check out.

2024-04-17 12:14 UTC, andyo-tyk requested changes
Final suggestions

2024-04-17 12:14 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +- **track**: Analytics are tracked for an API, i.e. *do_not_track* is false.
```suggestion
- **track**: Traffic to this API is tracked, i.e. transaction records are generated for each request/response.
```

2024-04-17 12:14 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +- **notrack**: Analytics are not tracked for an API, i.e. *do_not_track* is true.
```suggestion
- **notrack**: Traffic to this API is not tracked, i.e. transaction records are not generated for each request/response.
```

2024-04-17 12:14 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +100,000 requests were sent to each API and the total number of requests per second was measured. The results for the *tracked* API are displayed in the left pane terminal window; with the right pane
```suggestion
100,000 requests were sent to each API and the rate at which Tyk was able to handle those requests (number of requests per second) was measured. The results for the *tracked* API are displayed in the left pane terminal window; with the right pane showing the results for the *untracked* API.
```

2024-04-17 12:14 UTC, andyo-tyk commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Users can [selectively control]({{<ref "product-stack/tyk-gateway/middleware/do-not-track-middleware">}}) the generation of analytics :
```suggestion
Users can [selectively prevent]({{<ref "product-stack/tyk-gateway/middleware/do-not-track-middleware">}}) the generation of analytics:
```

2024-04-17 12:51 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk Gateway generates transaction records for each API request and response, containing [analytics data]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}) relating to: the originating hos
it's an auto gen pr so check where it's coming from.

2024-04-17 12:53 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +- **Global**: Analytics are not tracked for all endpoints of an API.
@dcs3spp was trying to find this text in the doc but couldn't, I also couldn't find `do_not_track` in the text at all. Why is that?

2024-04-17 13:01 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +- Displaying [analytics]({{< ref "tyk-dashboard-analytics" >}}) based on the aggregated data.
```suggestion
- **Aggregated analytics** - Displaying [analytics]({{< ref "tyk-dashboard-analytics" >}}) based on the aggregated data.
```

2024-04-17 13:02 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +- Browsing logs for the [raw transaction records]({{< ref "tyk-stack/tyk-manager/analytics/log-browser" >}}).
```suggestion
- [Log Broswer]({{< ref "tyk-stack/tyk-manager/analytics/log-browser" >}}) - Browsing logs for the raw transaction records.
```

2024-04-17 13:04 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +When set, this prevents Tyk Gateway from generating the transaction records. Without transaction records, Tyk Pump will not transfer analytics to the chosen persistent data store. It's worth noting t
you can't add " inside a relative link, like this:
> ["track" middleware]
Check the preview and see it's not working. We need CI to find it

2024-04-17 13:06 UTC, letzya commented on tyk-docs/assets/img/faq/do-not-track-usage-scenario/do_not_track_performance_impact.png
@dcs3spp any chance you can make this bigger? I can't see properly what you are trying to show

2024-04-17 13:07 UTC, letzya commented on tyk-docs/assets/img/faq/do-not-track-usage-scenario/dashboard_apis_measured.png
@dcs3spp any chance you can get a better quality screenshot? also a nicer one, without the grey line on the side? This looks zoomed in too much with the next one zoomed out too much.

2024-04-17 13:08 UTC, letzya approved these changes
A few small comments on the images and a link.
You made into a great FAQ!!!

2024-04-17 13:11 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +When set, this prevents Tyk Gateway from generating the transaction records. Without transaction records, Tyk Pump will not transfer analytics to the chosen persistent data store. It's worth noting t
thanks @letzya I've removed the surrounding quotes

2024-04-17 13:14 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +Tyk Gateway generates transaction records for each API request and response, containing [analytics data]({{< ref "tyk-stack/tyk-pump/tyk-analytics-record-fields" >}}) relating to: the originating hos
I think it's coming from pump so no need to do anything IMO. We say "Tyk Analytics Record" in the pump while in the GW it's part of the API def.

2024-04-17 16:29 UTC, andyo-tyk approved these changes
LGTM, thanks.

2024-04-18 11:54 UTC, dcs3spp commented on tyk-docs/content/developer-support/frequently-asked-questions/when_to_use_do_not_track.md
> +- **Global**: Analytics are not tracked for all endpoints of an API.
@letzya text was refactored for code review and improving FAQ since this commit was reviewed. I've restored `do_not_track` in a [later commit](https://github.com/TykTechnologies/tyk-docs/pull/4032/commits/b2bdf9b92a71b7bef7b7b5296da2b6a9bd8af008) now

2024-04-18 11:55 UTC, dcs3spp commented on tyk-docs/assets/img/faq/do-not-track-usage-scenario/do_not_track_performance_impact.png
@letzya The image was a screen shot from a video. I have zoomed and created separate images to show the results for both APIs

2024-04-18 11:55 UTC, dcs3spp commented on tyk-docs/assets/img/faq/do-not-track-usage-scenario/dashboard_apis_measured.png
@letzya The image was a screen shot from a video. I have uploaded a new image.

2024-04-19 00:56 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +We can see that **19,253.75** RPS was recorded for the *untracked* API; with **16,743.6011** RPS reported for the *tracked* API. The number of requests per second decreased by **13.0372%** when analy
```suggestion
We can see that **19,253.75** RPS was recorded for the *untracked* API; with **16,743.6011** RPS reported for the *tracked* API. The number of requests per second decreased by **~13%** when analytics was enabled.
```

2024-04-19 00:57 UTC, letzya commented on tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
> +### Summary
```suggestion
### Explaining the results
```

2024-04-19 01:02 UTC, letzya approved these changes

2024-04-19 10:12 UTC, merged

2024-04-19 10:18 UTC, dcs3spp commented
/release to release-5.3

2024-04-19 10:25 UTC, dcs3spp commented
/release to release-5.2

2024-04-19 10:28 UTC, dcs3spp commented
/release to release-5.1