[Dx 961] Refactor Planing For Production Page To Link To Distributed Analytics FAQs
TykTechnologies/tyk-docs-hugo pull request #4033
Opened 2024-01-26 12:28 UTC by dcs3spp

[DX-961](https://tyktech.atlassian.net/browse/DX-961) 

This involves refactoring the Analytics optimisations as commented in this [PR](https://github.com/TykTechnologies/tyk-docs/pull/3621/files). Part of this refactoring involves linking to the FAQs for:
- When to use do_not_track
- How to configure Tyk to distribute analytics across Redis shards.

Subsequently, this PR should not be merged until the following PRs have been merged:
- [FAQ enable_do_not_track](https://github.com/TykTechnologies/tyk-docs/pull/4032)
- [FAQ configure Tyk to distribute analytics across Redis Shards](https://github.com/TykTechnologies/tyk-docs/pull/4018)

2024-01-29 22:01 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +If using a Redis cluster under high load it is recommended that analytics are sent to distributed Redis shards. This can be configured using the *analytics_configenable_multiple_analytics_keys* param
```suggestion
If using a [Redis cluster](https://redis.io/docs/management/scaling/) under high load it is recommended that analytics are sent to distributed Redis shards. This can be configured using the *analytics_configenable_multiple_analytics_keys* parameter and following the process explained in this **[FAQ - PR #4018]**. Furthermore, analytics can also be disabled for an API or selected endpoints, as explained in this **[FAQ - PR #4032]**.
```

2024-01-29 22:02 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +If using a Redis cluster under high load it is recommended that analytics are sent to distributed Redis shards. This can be configured using the *analytics_configenable_multiple_analytics_keys* param
It is not good for SEO to use "this"

2024-01-30 20:51 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +In Tyk Gateway, using [protobuf]({{< ref "tyk-oss-gateway/configuration/#analytics_configserializer_type" >}}) serialisation, instead of msgpack can increase performance for sending and processing an
can you please add an external link to msgpack

2024-01-30 20:53 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +If using Tyk Cloud platform under high load, it is also recommended that analytics are stored within a local region. This means that a local Tyk Pump instance can store the analytics within a localis
@dcs3spp I do not understand this sentence:
>  "In this scenario the hybrid pump will be bypassed across the *Control Plane* and *Data Planes*, thus reducing load since no analytics traffic is sent across regions."

2024-01-30 20:54 UTC, letzya requested changes
A few comments but in general looks good!

2024-01-31 16:22 UTC, dcs3spp commented on tyk-docs/content/planning-for-production.md
> +If using Tyk Cloud platform under high load, it is also recommended that analytics are stored within a local region. This means that a local Tyk Pump instance can store the analytics within a localis
@letzya Updated sentence to read:

> This will reduce load since analytics traffic would not be sent across regions.

2024-01-31 16:22 UTC, dcs3spp commented on tyk-docs/content/planning-for-production.md
> +In Tyk Gateway, using [protobuf]({{< ref "tyk-oss-gateway/configuration/#analytics_configserializer_type" >}}) serialisation, instead of msgpack can increase performance for sending and processing an
updated

2024-02-15 14:09 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +If using a [Redis cluster](https://redis.io/docs/management/scaling/) under high load it is recommended that analytics are sent to distributed Redis shards. This can be configured using the *analytic
```suggestion
If using a [Redis cluster](https://redis.io/docs/management/scaling/) (in Tyk Self managed, with Hybrid Tyk Gateways or Tyk OSS) under high load it is recommended that analytics are sent to distributed Redis shards (instead of just one of the shards). This can be configured using the *analytics_configenable_multiple_analytics_keys* parameter and following the process explained in this **[FAQ - PR #4018]**. Furthermore, analytics can also be disabled for an API or selected endpoints, as explained in this **[FAQ - PR #4032]**.
```

2024-02-15 14:10 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +If using a [Redis cluster](https://redis.io/docs/management/scaling/) under high load it is recommended that analytics are sent to distributed Redis shards. This can be configured using the *analytic
maybe remove the FAQ wording, merge and add it later?

2024-02-15 14:13 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +In Tyk Gateway, using [protobuf]({{< ref "tyk-oss-gateway/configuration/#analytics_configserializer_type" >}}) serialisation, instead of [msgpack](https://msgpack.org) can increase performance for se
```suggestion
#### protobuf Serialisation
In Tyk Gateway, using [protobuf]({{< ref "tyk-oss-gateway/configuration/#analytics_configserializer_type" >}}) serialisation, instead of [msgpack](https://msgpack.org) can increase performance for sending and processing analytics. 
<br/>
**Note:** *protobuf* is not currently supported in *MDCB* deployment.
```

2024-02-15 14:14 UTC, letzya requested changes
2 suggestions and we can merge

2024-02-22 17:42 UTC, dcs3spp commented on tyk-docs/content/planning-for-production.md
> +If using a [Redis cluster](https://redis.io/docs/management/scaling/) under high load it is recommended that analytics are sent to distributed Redis shards. This can be configured using the *analytic
If this suggestion is ok with you then I will merge. and will add later:

```suggestion
If using a [Redis cluster](https://redis.io/docs/management/scaling/) under high load it is recommended that analytics are sent to distributed Redis shards. This can be configured by setting the [analytics_config.enable_multiple_analytics_keys]({{< ref "tyk-oss-gateway/configuration#analytics_configenable_multiple_analytics_keys" >}}) parameter to true. Furthermore, analytics can also be disabled for an API using the [do_not_track]({{< ref "tyk-apis/tyk-gateway-api/api-definition-objects/other-root-objects" >}}) configuration parameter. Alternatively, tracking for analytics can be disabled for selected endpoints using the [do not track endpoint plugin]({{< ref "advanced-configuration/transform-traffic/endpoint-designer#do-not-track-endpoint" >}}).
```

2024-04-03 18:25 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +If using Tyk Cloud platform under high load, it is also recommended that analytics are stored within a local region. This means that a local Tyk Pump instance can store the analytics within a localis
cant see this sentence. please check again 
>In this scenario the hybrid pump will be bypassed across the *Control Plane* and *Data Planes*, thus reducing load since no analytics traffic is sent across regions.

2024-04-16 15:09 UTC, dcs3spp commented on tyk-docs/content/planning-for-production.md
> +If using Tyk Cloud platform under high load, it is also recommended that analytics are stored within a local region. This means that a local Tyk Pump instance can store the analytics within a localis
> cant see this sentence. please check again
> 
> > In this scenario the hybrid pump will be bypassed across the _Control Plane_ and _Data Planes_, thus reducing load since no analytics traffic is sent across regions.

https://github.com/TykTechnologies/tyk-docs/pull/4033/commits/6dcf721739bbd005b19c6acab54c04ae5e229394

2024-04-16 17:59 UTC, letzya commented on tyk-docs/content/planning-for-production.md
> +If using Tyk Cloud platform under high load, it is also recommended that analytics are stored within a local region. This means that a local Tyk Pump instance can store the analytics within a localis
```suggestion
If using Tyk Cloud platform under high load, it is also recommended that analytics are stored within a local region. This means that a local Tyk Pump instance can send the analytics to a localised data sink, such as PostgreSQL or MongoDB (no need for the hybrid pump). This can reduce traffic costs since your analytics would not be sent across regions.
```

2024-04-16 17:59 UTC, letzya approved these changes

2024-04-16 18:00 UTC, letzya approved these changes

2024-04-16 18:15 UTC, letzya approved these changes

2024-04-16 18:16 UTC, merged

2024-04-16 18:17 UTC, letzya commented
/release to release-5.3

2024-04-16 18:18 UTC, letzya commented
/release to release-5.2

2024-04-16 18:20 UTC, letzya commented
/release to release-5.1