Release Notes 5.3 Tyk Gateway
TykTechnologies/tyk-docs-hugo pull request #4038
Opened 2024-01-26 17:19 UTC by dcs3spp

[preview - to add]()

2024-02-26 21:00 UTC, caroltyk commented
@dcs3spp added change log from Platform team

2024-02-27 12:41 UTC, dcs3spp commented
> @dcs3spp added change log from Platform team

Perfect, many thanks @caroltyk! Thanks for adding in the internal and external links in the changelog items too

2024-03-14 17:10 UTC, dcs3spp reviewed
Thanks @Eopayemi for adding the change-log items!! I have reviewed the current draft of the release notes for GW 5.3 so far:
- Update the summary Fixed changelog items to use the same casing as those in _Added_ and _Changed_ items. For example: FIXED
  - Enhanced Redis Token Management and Gateway Efficiency becomes:  Enhanced Redis token management and Gateway efficiency FIXED
- There is an error within the _Changed_ section with details nested under the item (Remove slug from the Tyk OAS API Definition) FIXED
- Compatibility Matrix table will need updating to reflect which Tyk components are compatible with [Gateway 5.3.0](https://deploy-preview-4038--tyk-docs.netlify.app/docs/nightly/developer-support/long-term-support-releases/)
- [Supported lifetime](https://deploy-preview-4038--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/release-notes/version-5.3/#support-lifetime) section needs updating with the supported lifetime for Gateway release 5.3
- Release date and links for docker images and source code tarballs need adding
- Links need adding to docs for new documented features, changed documented features etc.

2024-03-21 12:27 UTC, andyo-tyk requested changes
I've committed an update to the PR containing my suggested changes

2024-03-21 16:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Fixed an issue where the OAS-to-UDG converter was sometimes adding the 5.same field to an object type many times. This caused issues with the resulting GQL schema and made it non-compliant with GQL s
@andyo-tyk @agata-wit Is 5.same a typo?

2024-03-22 10:48 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Fixed an issue where the OAS-to-UDG converter was sometimes adding the 5.same field to an object type many times. This caused issues with the resulting GQL schema and made it non-compliant with GQL s
Yes

2024-03-22 13:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Fixed an issue where the OAS-to-UDG converter was sometimes adding the 5.same field to an object type many times. This caused issues with the resulting GQL schema and made it non-compliant with GQL s
```suggestion
Fixed an issue where the OAS-to-UDG converter was sometimes adding the same field to an object type many times. This caused issues with the resulting GQL schema and made it non-compliant with GQL specification.
```

2024-03-22 13:52 UTC, andyo-tyk approved these changes
I'm happy with the changes I've made 🤣

2024-03-25 14:52 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +In 5.3.0, we have simplified the configuration of response transform middleware. We encourage users to embrace the ‘global_headers’ mechanism as the ‘response_processors.header_injector’ is now an op
```suggestion
In 5.3.0, we have simplified the configuration of response transform middleware. We encourage users to embrace the `global_headers` mechanism as the `response_processors.header_injector` is now an optional setting and will be removed in a future release.
```

2024-03-25 14:57 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +
@dcs3spp @andyo-tyk I think we need a title here for 2 reasons:
1. in case we have more than one topic (so for other cases, not this release)
2. to guide the reader to keep reading in case they are scanning the page and make sure the topic stands out

Also - we should add a link to the actual upgrade instructions `/product-stack/tyk-gateway/release-notes/version-5.3/#upgrade-instructions`

2024-03-26 12:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +
@andyo-tyk @letzya I've updated and added link to upgrade instructions

2024-03-28 15:32 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +
```suggestion

##### Python plugin support
Starting from Tyk Gateway version v5.3.0, Python is no longer bundled with the official Tyk Gateway Docker image to reduce exposure to security vulnerabilities in the Python libraries.

Whilst the Gateway still supports Python plugins, you must [extend the image]({{< ref "plugins/supported-languages/rich-plugins/python/python#install-the-python-development-packages" >}}) to add the language support.
```

2024-03-28 15:33 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +As Tyk OAS transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot guarantee backward compatibility for versions pre-5.3.0. When upgrading t
```suggestion
##### Tyk OAS APIs not backward compatible with pre-5.3.0 Gateways

As Tyk OAS transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot guarantee backward compatibility for versions pre-5.3.0. When upgrading to 5.3.0, Tyk will automatically migrate existing Tyk OAS APIs to the [latest API definition format]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}}).
```

2024-03-28 18:38 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Whilst the Gateway still supports Python plugins, you must [extend the image]({{< ref "plugins/supported-languages/rich-plugins/python/python#install-the-python-development-packages" >}}) to add the
```suggestion
Whilst the Gateway still supports Python plugins, you will need to extend the Dockerfile and [rebuild the image]({{< ref "plugins/supported-languages/rich-plugins/python/python#install-the-python-development-packages" >}}) to use Python plugin with with Tyk Gateway.
```

2024-03-28 18:59 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +As Tyk OAS transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot guarantee backward compatibility for versions pre-5.3.0. When upgrading t
```suggestion
As [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot guarantee backward compatibility for versions pre-5.3.0. When upgrading to 5.3.0, Tyk will automatically migrate existing Tyk OAS APIs to the [latest API definition format]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}}).
```

2024-04-02 11:23 UTC, agata-wit requested changes, later dismissed

2024-04-02 11:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Added a new set of settings in the API definition called *introspection_config*. This enables users to have more control over introspection on a single GQL API level.
Can we remove this part completely? I mean yes, technically we added this setting but it does nothing yet. It is just in the API definition but has no impact on any behaviour in the GW nor in the Dashboard.

2024-04-02 11:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Enhanced UDG's handling of arrays of objects in OpenAPI Documents</summary>
```suggestion
<summary>Enhanced OAS-to-UDG converter handling of arrays of objects in OpenAPI Documents</summary>
```

2024-04-02 11:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Duplicate fields added by OAS-to-UDG translator</summary>
```suggestion
<summary>Duplicate fields added by OAS-to-UDG converter</summary>
```

2024-04-02 11:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Playground issues in Cloud/K8s deployments</summary>
```suggestion
<summary>GQL Playground issues related to encoding of request response</summary>
```

2024-04-02 11:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>OAS-to-UDG Converter issue with "json" Return Type</summary>
```suggestion
<summary>OAS-to-UDG converter issue with "JSON" return type</summary>
```

2024-04-02 11:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +OAS-to-UDG converter was unable to correctly process Tyk OAS API definitions where "json" was used as one of enum values. This issue is now fixed and whenever "json" is used as one of enums in the Op
```suggestion
OAS-to-UDG converter was unable to correctly process Tyk OAS API definitions where "JSON" was used as one of enum values. This issue is now fixed and whenever "JSON" is used as one of enums in the OpenAPI description, it will get correctly transformed into a custom scalar in GQL schema.
```

2024-04-02 11:23 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>GraphQL introspection issue with Allow List</summary>
```suggestion
<summary>GraphQL introspection issue when Allow/Block List enabled</summary>
```

2024-04-02 22:34 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +As [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot gua
```suggestion
This upgrade transitions Tyk OAS APIs out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}) to a [new internal format]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}}) as part of their move to General Availability. 

**Please Note:**
- Automatic Conversion: Upgrading automatically updates your Tyk OAS API definitions to the latest format used in v5.3.
- Non-Reversible Change: The format change is one-way within the product. Reverting requires restoring from a backup.

##### Gateway Compatibility

- Use gateways version 5.3.0 or newer with the v5.3.0 Control Plane. Older gateways may not function correctly with the updated Tyk OAS API definitions. 

#### Essential steps prior to upgrade

- Back-Up Your Environment;
- Export Tyk OAS API Definitions;
- Consult Upgrade Instructions: For a detailed upgrade process and further steps, refer to the [upgrade instructions guide](#upgrading-tyk).
```

2024-04-02 22:34 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +As [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot gua
@andyo-tyk what do you think?

2024-04-03 11:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +As [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot gua
@lghiur TBC re automatic conversion

2024-04-03 14:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Added a new set of settings in the API definition called *introspection_config*. This enables users to have more control over introspection on a single GQL API level.
@agata-wit I've removed it in GW release notes and if it is in Dashboard release notes I'll remove it there also

2024-04-04 10:14 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +As [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot gua
> - Automatic Conversion: Upgrading automatically updates your Tyk OAS API definitions to the [latest format]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}}) used in v5.3. <TBC - Laurentiu??>

- For OSS scenarion, when OAS API definitions are part of the file system, the upgrade doesn't autoamtically happen and users need to update their OAS API Definitions

> - Non-Reversible Change: The format change is one-way within the product. Reverting to your previous version requires restoring from a backup.

- This is only valid, if users upgrade to 5.3.0, they **Create new APIs** on 5.3.0 and then they decide to downgrade

2024-04-04 10:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +As [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot gua
@lghiur Thanks for reviewing. I have updated the suggestion. Does it look ok?

@letzya Are we still moving this to Dashboard Release Notes:


_##### Gateway Compatibility <Should be in Dashboard release notes TODO>
- Use gateways version 5.3.0 or newer with the v5.3.0 Control Plane. Older gateways may not function correctly with the updated Tyk OAS API definitions._

2024-04-04 10:43 UTC, ilijabojanovic approved these changes

2024-04-04 11:10 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +As [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot gua
@dcs3spp
> OAS API definitions that are part of the file system are not  ...

Maybe just say that for OSS users that store API Definitions on the file system

2024-04-05 08:30 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +- **Not Backwards Compatibility**
```suggestion
- **Not Backwards Compatible**
```

2024-04-05 10:17 UTC, merged