Release Notes 5.3 Tyk Dashboard
TykTechnologies/tyk-docs-hugo pull request #4039
Opened 2024-01-26 17:20 UTC by dcs3spp

[preview-to-add]()

2024-02-26 21:09 UTC, caroltyk commented
@dcs3spp Updated change log from platform team

2024-02-27 12:55 UTC, dcs3spp commented
> @dcs3spp Updated change log from platform team

Perfect, many thanks @caroltyk! Thanks for adding in the internal and external links in the changelog items too!

2024-03-20 15:39 UTC, dcs3spp reviewed
Thanks @Eopayemi for adding the Dashboard release notes!! I have reviewed the current draft of the release notes for 5.3 so far:

- Compatibility Matrix table will need updating to reflect which Tyk components are compatible with Dashboard FIXED
- Supported lifetime section needs updating with the supported lifetime for Dashboard release 5.3 FIXED
- Release date and links for docker images and source code tarballs need adding when available
- Links need adding to docs for new documented features, changed documented features etc.

2024-03-27 09:06 UTC, caroltyk approved these changes

2024-03-27 09:54 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<!-- Required. Use the following statement if there are no breaking changes, or explain if there are -->
@andyo-tyk Since the GW has breaking changes and it's a fundamental component, I think we should mention that with a link to the GW breaking changes

2024-03-28 18:50 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +As Tyk OAS transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot guarantee backward compatibility for versions pre-5.3.0. When upgrading t
```suggestion
#### Tyk OAS APIs not backward compatible with pre-5.3.0 Gateways

As Tyk OAS transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot guarantee backward compatibility for versions pre-5.3.0. When upgrading to 5.3.0, Tyk will automatically migrate existing Tyk OAS APIs to the [latest API definition format]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}}).
```

2024-03-28 18:58 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +As Tyk OAS transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot guarantee backward compatibility for versions pre-5.3.0. When upgrading t
```suggestion
As [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot guarantee backward compatibility for versions pre-5.3.0. When upgrading to 5.3.0, Tyk will automatically migrate existing Tyk OAS APIs to the [latest API definition format]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}}).
```

2024-03-28 19:14 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +Users are strongly advised to follow the recommended upgrade instructions provided by Tyk before applying any updates.
```suggestion
Users are strongly advised to follow the recommended [upgrade instructions](#upgrading-tyk) provided by Tyk before applying any updates.
```

2024-03-30 14:44 UTC, andyo-tyk requested changes
Suggested improvements to the "non-change-log" parts

2024-03-30 14:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +Given the time difference between your upgrade and the release of this version, we recommend customers verify the ongoing support of third-party dependencies they install, as their status may have ch
```suggestion
Given the potential time difference between your upgrade and the release of this version, we recommend users verify the ongoing support of third-party dependencies they install, as their status may have changed since the release.
```

2024-03-30 14:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +As [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), we cannot gua
```suggestion
As [Tyk OAS]({{< ref "getting-started/key-concepts/high-level-concepts">}}) transitions out of [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}), please note that backward compatibility cannot be guaranteed for versions prior to version 5.3.0. Upon upgrading to version 5.3.0, Tyk will automatically migrate Early Access Tyk OAS APIs to use the v5.3.0 [Tyk OAS API definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}}).
```

2024-03-30 14:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +Tyk OAS APIs using the 5.3.0 API definition may not work with pre-5.3.0 versions of Tyk Gateway and doing so could provoke unpredictable behaviour including potential crashes. We recommend retaining
```suggestion
It’s crucial to understand that Tyk OAS APIs using the v5.3.0 API definition may not function correctly with Tyk Gateway versions prior to v5.3.0. Attempting to do so may result in unpredictable behaviour, including potential crashes. To mitigate any risks, we strongly recommend retaining copies of existing Tyk OAS API definitions before proceeding with the upgrade, as it is not possible to rollback to previous versions after updating to the v5.3.0 API definition. 
```

2024-03-30 14:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +Users are strongly advised to follow the recommended [upgrade instructions](#upgrading-tyk) provided by Tyk before applying any updates.
```suggestion
Users are strongly advised to follow the recommended [upgrade instructions](#upgrading-tyk) before applying any updates.
```

2024-03-30 14:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| [GoLang](https://go.dev/dl/)                               | 1.19, 1.20, 1.21       | 1.19, 1.20, 1.21       | All our binaries|
```suggestion
| [GoLang](https://go.dev/dl/)                               | 1.21       | 1.21       | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go 1.21 | 
```

2024-03-30 14:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| OpenAPI JSON Schema  | v3.0.0...      | v3.0.0...          | Used by [Tyk OAS API definition](https://swagger.io/specification/)                | [3.0.3](https://spec.openapis.org/oas/v3.0.3)|
```suggestion
| [OpenAPI Specification]({{< ref "https://spec.openapis.org/oas/v3.0.3" >}}) | v3.0.x      | v3.0.x          | Supported by [Tyk OAS]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}})|
```

2024-04-03 11:51 UTC, dcs3spp commented
@buger @ilijabojanovic Could you review the release notes

2024-04-03 14:38 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +
```suggestion

### Deployment Options for Tyk Dashboard

#### Tyk Cloud
Tyk 5.3.0 will be available on Tyk Cloud in the coming weeks. We'll update this page once it's ready.


#### Self-Managed
This release is ready for installation on your own infrastructure.
```

2024-04-03 14:38 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +
@allaneyles

2024-04-03 14:43 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| [OpenAPI Specification]({{< ref "https://spec.openapis.org/oas/v3.0.3" >}}) | v3.0.x      | v3.0.x          | Supported by [Tyk OAS]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}})|
```suggestion
| [OpenAPI Specification](https://spec.openapis.org/oas/v3.0.3) | v3.0.x      | v3.0.x          | Supported by [Tyk OAS]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc" >}})|
```

2024-04-03 17:13 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +- Back-Up Your Environment;
```suggestion
- Back-Up Your Environment (this is the usual case with every release)
```

2024-04-03 17:28 UTC, allaneyles approved these changes

2024-04-03 17:28 UTC, allaneyles approved these changes

2024-04-04 10:43 UTC, ilijabojanovic approved these changes

2024-04-04 12:37 UTC, agata-wit submitted a review, later dismissed

2024-04-04 12:37 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + Introducing field-based permissions via the Dashboard specifically tailored for GraphQL APIs. Users can now define granular access control for API key holders based on types and fields from a GraphQ
```suggestion
 Introducing allow list in field-based permissions via the Dashboard specifically tailored for GraphQL APIs. Users can now define granular access control for API key holders based on types and fields from a GraphQL schema. This feature enhances security and flexibility in managing API access, providing a more tailored and secure experience for users.
```

2024-04-04 12:37 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +We have expanded our analytics capabilities by extending APIs for fetching graph analytics from SQL databases. Users can now gain valuable insights into error trends and usage patterns for GraphQL AP
```suggestion
#### GraphQL focused analytics
We have made the first step towards bringing our users GraphQL-focused monitoring capabilities. Users can now gain valuable insights into error trends and usage patterns for GraphQL APIs, when storing graph analytics in SQL databases. With the addition of popularity and error bar charts, users can delve deeper into their data, facilitating optimization and troubleshooting efforts.
```

2024-04-04 18:08 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.0 | MDCB v2.5     | MDCB v2.4.2 |
@andyo-tyk @caroltyk @lghiur  Does this mean that the backward compatibility of 2.4.x in the compatibility matrix table of release notes is incorrect?

2024-04-04 18:10 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - Tyk OAS APIs in Tyk Dashboard v5.3.0 are not [backwards compatible](https://en.wikipedia.org/wiki/Backward_compatibility#:~:text=Backward%20compatibility%20(sometimes%20known%20as,especially%20in
```suggestion
  - Tyk OAS APIs in Tyk Dashboard v5.3.0 are not [backwards compatible](https://tinyurl.com/3xy966xn). This means that the new Tyk OAS API format created by Tyk Gateway/Dashboard v5.3.X does not work with older versions of Tyk Gateway/Dashboard, i.e. you cannot export these API definitions from a v5.3.X Tyk Dashboard and import to an earlier version.
```

2024-04-04 18:14 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - This means that if you wish to downgrade or revert to your previous version of Tyk, you will need to restore these API definitions from a backup. Please use our guidance documentation for how to
```suggestion
  - This means that if you wish to downgrade or revert to your previous version of Tyk, you will need to restore these API definitions from a backup. Please go to the [backup]({{ < ref "#essential-steps-before-upgrade" >}}) section for guidance about Tyk APIs and Policies backup.
```

2024-04-04 18:37 UTC, allaneyles approved these changes

2024-04-04 18:45 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - This means that if you wish to downgrade or revert to your previous version of Tyk, you will need to restore these API definitions from a backup. Please go to the [backup]({{< ref "#essential-ste
```suggestion
  - This means that if you wish to downgrade or revert to your previous version of Tyk, you will need to restore these API definitions from a backup. Please go to the [backup]({{< ref "#upgrade-instructions" >}}) section for detailed instructions on backup before upgrading to v5.3.0.
```

2024-04-05 08:28 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +- **Not Backwards Compatibility**
```suggestion
- **Not Backwards Compatibile**
```

2024-04-05 08:29 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +- **Not Backwards Compatibility**
```suggestion
- **Not Backwards Compatible**
```

2024-04-05 08:30 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +- **Not Backwards Compatibility**
@dcs3spp

2024-04-05 08:36 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - This means that any Tyk OAS APIs created in any previous release (4.1.0-5.2.x) cannot work with the new Tyk Dashboard without being migrated to the new format.
```suggestion
  - This means that any Tyk OAS APIs created in any previous release (4.1.0-5.2.x) cannot work with the new Tyk Dashboard v5.3.X without being migrated to its [latest format]({{<ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc">}}).
```

2024-04-05 08:38 UTC, andyo-tyk approved these changes
Please consider these suggestions, which I think make the explanation even clearer.

2024-04-05 08:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.0 | MDCB v2.5     | MDCB v2.4.2 |
To the best of my knowledge - yes, we shouldn't claim compatibility for 2.4.x (though strictly I think it is compatible if working exclusively with Tyk Classic APIs... that's just adding unnecessary nuance).

2024-04-05 08:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +- **Not Backwards Compatibility**
```suggestion
- **No Backwards Compatibility with pre-5.3.0 versions**
```

This heading either contains a typo or needs adjustment, it could be:
 - No Backwards Compatibility
 - Not Backwards Compatible
or my suggested alternative :)

2024-04-05 08:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - Tyk OAS APIs in Tyk Dashboard v5.3.0 are not [backwards compatible](https://tinyurl.com/3xy966xn). This means that the new Tyk OAS API format created by Tyk Gateway/Dashboard v5.3.X does not work
```suggestion
  - Tyk OAS APIs in Tyk Dashboard v5.3.0 are not [backwards compatible](https://tinyurl.com/3xy966xn). This means that the new Tyk OAS API format used by Tyk Gateway/Dashboard v5.3.X does not work with older versions of Tyk Gateway/Dashboard, i.e. you cannot export these API definitions from a v5.3.X Tyk Dashboard and import to an earlier version.
```

2024-04-05 08:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - The upgrade is **not reversible**, i.e. you cannot use version 5.3.X Tyk OAS API definitions with an older version of Tyk Dashboard.
```suggestion
  - The upgrade of Tyk OAS API definitions is **not reversible**, i.e. you cannot use version 5.3.X Tyk OAS API definitions with an older version of Tyk Dashboard.
```

This bullet point might be better in the "After upgrade" section, as I feel it is refering to upgraded API definitions and fits nicely after the bullet that says "This means that you do not have to do anything..." as a reinforcement of the fact that this process will modify existing API definitions to the new format.

2024-04-05 08:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - MDCB users utilising Tyk OAS APIs **should wait for the release of MDCB v2.5** before upgrading Tyk Gateway and Dashboard to v5.3.0. This means Tyk OAS APIs will not be loaded with MDCB v2.4 or o
```suggestion
  - Tyk OAS APIs created in Tyk v5.3.0 will not be loaded by the data plane gateways if you are using MDCB v2.4 or older. This means that MDCB users already working with Tyk OAS APIs **must wait for the release of MDCB v2.5** before upgrading Tyk Gateway and Dashboard to v5.3.0. 
```

I think this reordering makes the behaviour clearer -> given that MDCB 2.4.x cannot handle 5.3.0 Tyk OAS API definitions, users must wait for MDCB 2.5.0

2024-04-05 08:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - For MDCB users using Tyk OAS APIs, Tyk Dashboard 5.3.0 will only work with Tyk Gateway v5.3.0 and MDCB v2.5.X. Older versions of Tyk Gateway may not function correctly with v5.3.0 Tyk OAS API def
```suggestion
  - Tyk OAS APIs managed by Tyk Dashboard v5.3.0 in a distributed deployment will only work with Tyk Gateway v5.3.0 and MDCB v2.5.X. Older versions of Tyk Gateway may not function correctly with v5.3.0 Tyk OAS API definitions.
```

Is this clearer?

2024-04-05 08:44 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.0 | MDCB v2.5     | MDCB v2.4.2 |
Yes please update to MDCB v2.5

2024-04-05 08:45 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - For MDCB users using Tyk OAS APIs, Tyk Dashboard 5.3.0 will only work with Tyk Gateway v5.3.0 and MDCB v2.5.X. Older versions of Tyk Gateway may not function correctly with v5.3.0 Tyk OAS API def
I wanted to start with MDCB, since if you are not, you can skip this sentence (exit ASAP in programming). 
Let's do this:
>For distributed deployments (i.e. MDCB), Tyk Dashboard v5.3.0 managing Tyk OAS APIs requires Tyk Gateway v5.3.0 and MDCB v2.5.X for proper functionality. Older versions of Tyk Gateway may experience compatibility issues with Tyk OAS API definitions from v5.3.0.

2024-04-05 08:47 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - For MDCB users using Tyk OAS APIs, Tyk Dashboard 5.3.0 will only work with Tyk Gateway v5.3.0 and MDCB v2.5.X. Older versions of Tyk Gateway may not function correctly with v5.3.0 Tyk OAS API def
```suggestion
For distributed deployments (i.e. MDCB), Tyk Dashboard v5.3.0 managing Tyk OAS APIs requires Tyk Gateway v5.3.0 and MDCB v2.5.X for proper functionality. Older versions of Tyk Gateway may experience compatibility issues with Tyk OAS API definitions from v5.3.0.
```

2024-04-05 08:47 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - For MDCB users using Tyk OAS APIs, Tyk Dashboard 5.3.0 will only work with Tyk Gateway v5.3.0 and MDCB v2.5.X. Older versions of Tyk Gateway may not function correctly with v5.3.0 Tyk OAS API def
@dcs3spp @andyo-tyk this is a mix of both

2024-04-05 08:48 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.0 | MDCB v2.5     | MDCB v2.4.2 |
```suggestion
| 5.3.0 | MDCB v2.5     | MDCB v2.5 |
```

2024-04-05 08:49 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.0 | MDCB v2.5     | MDCB v2.4.2 |
@caroltyk shouldn't we add a note that if you don't use Tyk OAS APIs, mdcb 2.4 is fine? (if that's actually correct)

2024-04-05 08:51 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - MDCB users utilising Tyk OAS APIs **should wait for the release of MDCB v2.5** before upgrading Tyk Gateway and Dashboard to v5.3.0. This means Tyk OAS APIs will not be loaded with MDCB v2.4 or o
you explain that `given that MDCB` is in the beginning, is the root but in the sentence, it's not. as before, since it's "given", it should be in the beginning

2024-04-05 08:58 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - MDCB users utilising Tyk OAS APIs **should wait for the release of MDCB v2.5** before upgrading Tyk Gateway and Dashboard to v5.3.0. This means Tyk OAS APIs will not be loaded with MDCB v2.4 or o
ok, accepting and then will add it

2024-04-05 09:00 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - For MDCB users using Tyk OAS APIs, Tyk Dashboard 5.3.0 will only work with Tyk Gateway v5.3.0 and MDCB v2.5.X. Older versions of Tyk Gateway may not function correctly with v5.3.0 Tyk OAS API def
@letzya It looks ok to me @andyo-tyk ?

2024-04-05 09:04 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +Tyk Dashboard v5.3.0 managing Tyk OAS APIs requires Tyk Gateway v5.3.0 and MDCB v2.5.X for proper functionality. Older versions of Tyk Gateway may experience compatibility issues with Tyk OAS API def
```suggestion
  - Tyk Dashboard v5.3.0 managing Tyk OAS APIs requires Tyk Gateway v5.3.0 and MDCB v2.5.X for proper functionality. Older versions of Tyk Gateway may experience compatibility issues with Tyk OAS API definitions from v5.3.0.
```

2024-04-05 09:09 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.0 | MDCB v2.5     | MDCB v2.4.2 |
@letzya Does it complicate things? I would recommend they upgrade the whole package together.

2024-04-05 09:18 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.0 | MDCB v2.5     | MDCB v2.4.2 |
but what if they can't? I think it's good to share this info, but we can do it later. Could you please check with @OldStubbsy for his professional opinion?

2024-04-05 09:35 UTC, letzya approved these changes
Go for it

2024-04-05 09:39 UTC, dcs3spp commented
Unable to merge because of GHub web interface does not display unresolved conversation. DX overriding merge requirements anf merging to main branch

2024-04-05 09:39 UTC, merged