Updated Internal Endpoint middleware
TykTechnologies/tyk-docs-hugo pull request #4046
Opened 2024-01-29 22:07 UTC by andyo-tyk

### Preview Link

### Description
Updated documentation of the Internal Endpoint middleware

2024-01-30 13:06 UTC, dcs3spp requested changes
PR LGTM Andy, I've suggested minor changes. Once images and placeholder videos are added and PR peer reviewed then willapprove and ready as ready for merge and release.

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +The [Internal Endpoint]({{< ref "product-stack/tyk-gateway/middleware/internal-endpoint-middleware" >}}) middleware instructs Tyk Gateway not to process external requests to the endpoint (which is a
```suggestion
The [Internal Endpoint]({{< ref "product-stack/tyk-gateway/middleware/internal-endpoint-middleware" >}}) middleware instructs Tyk Gateway to ignore processing external requests to the endpoint (which is a combination of HTTP method and path). Internal requests from other APIs will be processed.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-middleware.md
> +The Internal Endpoint middleware instructs Tyk Gateway not to process external requests to the endpoint (which is a combination of HTTP method and path). Internal requests from other APIs will be pro
```suggestion
The Internal Endpoint middleware instructs Tyk Gateway to ignore processing external requests to the endpoint (which is a combination of HTTP method and path). Internal requests from other APIs will be processed.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-middleware.md
> +When the Internal Endpoint middleware is configured for a specific endpoint, it instructs the gateway not to listen to requests originating outside Tyk that are made to that endpoint.
```suggestion
When the Internal Endpoint middleware is configured for a specific endpoint, it instructs the Gateway to ignore requests to the endpoint that originate from outside Tyk.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-middleware.md
> +An internal endpoint can be addressed using three different identifiers in using the format `tyk://{identifier}/{endpoint}`.
```suggestion
An internal endpoint can be addressed using three different identifiers in the format `tyk://{identifier}/{endpoint}`.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-middleware.md
> +A direct call to `/api1/endpoint1_int` will be rejected with `HTTP 403 Forbidden` as this is an internal endpoint.
```suggestion
An external request directed at `/api1/endpoint1_int` will be rejected with `HTTP 403 Forbidden`, since this is an internal endpoint.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-middleware.md
> +  - The Internal Endpoint middleware is an optional stage in Tyk's API Request processing chain, sitting between the [TBC]() and [TBC]() middleware.
When link content is available, remember to add here

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
> +When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs, the middleware is configured in the Tyk Classic API Definition either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
> +In this example the internal endpoint middleware has been configured for HTTP `GET` requests to the `/status/200` endpoint. Any calls made to this endpoint that originate outside Tyk (i.e. externally
```suggestion
In this example the internal endpoint middleware has been configured for HTTP `GET` requests to the `/status/200` endpoint. Any requests made to this endpoint that originate externally to Tyk will be rejected with `HTTP 403 Forbidden`. Conversely, the endpoint can be reached internally by another API at `tyk://<listen_path>/status/200`.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
> +< placeholder for image >
remember to add image

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
> +#### Step 1: Add an endpoint for the path and select the plugin
```suggestion
#### Step 1: Add an endpoint for the path and select the internal plugin
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
> +Use the *save* or *create* buttons to save the changes and make the middleware active.
```suggestion
Use the *save* or *create* buttons to save the changes and activate the middleware.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
> +tags: ["internal endpoint", "internal", "middleware", "per-endpoint", "Tyk OAS"]
```suggestion
tags: ["internal endpoint", "internal", "middleware", "per-endpoint", "Tyk OAS", "Tyk OAS APIs"]
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
> +When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}) either manually within the `.json` file
```suggestion
When working with Tyk OAS APIs, the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}) either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
> +Any calls made directly to `GET /example-internal-endpoint/anything` will be rejected, with Tyk returning `HTTP 403 Forbidden`.
```suggestion
Any calls made directly to `GET /example-internal-endpoint/anything` will be rejected, with Tyk returning `HTTP 403 Forbidden`, since the `/anything` endpoint is internal.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
> +The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the API-level response header transform.
```suggestion
The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the API-level internal endpoint middleware.
```

2024-01-30 13:06 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video when available.

2024-01-30 16:18 UTC, andyo-tyk reviewed
Adjusted suggestions following review

2024-01-30 16:18 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
> +The [Internal Endpoint]({{< ref "product-stack/tyk-gateway/middleware/internal-endpoint-middleware" >}}) middleware instructs Tyk Gateway not to process external requests to the endpoint (which is a
```suggestion
The [Internal Endpoint]({{< ref "product-stack/tyk-gateway/middleware/internal-endpoint-middleware" >}}) middleware instructs Tyk Gateway to ignore external requests to the endpoint (which is a combination of HTTP method and path). Internal requests from other APIs will be processed.
```

2024-01-30 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-middleware.md
> +The Internal Endpoint middleware instructs Tyk Gateway not to process external requests to the endpoint (which is a combination of HTTP method and path). Internal requests from other APIs will be pro
```suggestion
The Internal Endpoint middleware instructs Tyk Gateway to ignore external requests to the endpoint (which is a combination of HTTP method and path). Internal requests from other APIs will be processed.
```

2024-01-30 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-middleware.md
> +  - The Internal Endpoint middleware is an optional stage in Tyk's API Request processing chain, sitting between the [TBC]() and [TBC]() middleware.
This is intended to be a common visual "summary box" for all middleware - so will be completed at a later date. This is just a placeholder.

2024-01-30 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
> +#### Step 1: Add an endpoint for the path and select the plugin
I would want to put emphasis on the word `internal` here because it's a common word - but that's tricky as it's in the title... hence Ieft it out.

2024-01-30 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
> +tags: ["internal endpoint", "internal", "middleware", "per-endpoint", "Tyk OAS"]
I haven't put "Tyk OAS APIs" in any of the other pages - if you want this added then for consistency this should be in all of the middleware pages (and "Tyk Classic APIs" for all of the Tyk Classic pages). Do you want these labels added to all of the PRs?

2024-01-30 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
> +The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the API-level response header transform.
```suggestion
The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the internal endpoint middleware.
```

2024-02-01 11:18 UTC, dcs3spp requested changes
Thanks Andy! PR LGTM, have resolved comments apart from image and video to add. Once peer reviewed and image and video has been added then we can mark as ready for release. I'll mark the PR as draft until image and video added.

2024-02-02 14:00 UTC, andyo-tyk reviewed
Minor improvements

2024-02-02 14:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
> +When working with Tyk Classic APIs, the middleware is configured in the Tyk Classic API Definition either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs, the middleware is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 14:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
> +When working with Tyk OAS APIs, the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}) either manually within the `.json` fil
```suggestion
When working with Tyk OAS APIs, the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-15 16:22 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-03-22 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
> + < placeholder for video >
I've added screenshots at this time

2024-03-22 11:26 UTC, andyo-tyk commented
I spotted a typo and missing image in Ignore Auth, so picked these up in this PR as simple edits.

2024-03-22 11:34 UTC, dcs3spp approved these changes

2024-03-22 14:31 UTC, merged