Improved endpoint cache docs
TykTechnologies/tyk-docs-hugo pull request #4054
Opened 2024-01-30 17:53 UTC by andyo-tyk

### For internal users - Please add a Jira DX PR ticket to the subject!

---

### Preview Link

2024-02-01 10:13 UTC, dcs3spp requested changes
PR LGTM Andy. Have reviewed and made minor suggestions:
- Grammar checks
- Add video

Will mark the PR as draft until video added. Once minor suggestions and video has been added and PR peer reviewed will mark it as ready for merge and release.

2024-02-01 10:13 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +For details on the API-level cache you should refer to the [API-level cache]({{< ref "/basic-config-and-security/reduce-latency/caching/global-cache">}}) configuration page.
```suggestion
For details on the API-level cache you should refer to the [API-level cache]({{< ref "basic-config-and-security/reduce-latency/caching/global-cache">}}) configuration page.
```

2024-02-01 10:13 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +For each endpoint in your API that you enable the endpoint caching middleware, you can configure which response codes should be cached (for example, you might not want to cache error responses) and a
```suggestion
For each endpoint in your API with endpoint caching middleware enabled, you can configure which response codes should be cached (for example, you might not want to cache error responses) and also the refresh interval - or timeout - for the cache entries.
```

2024-02-01 10:13 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +  - The Endpoint Cache middleware is an optional stage in Tyk's API Request processing chain, sitting between the [TBC]() and [TBC]() middleware.
When links available remember to add proposed content here

2024-02-01 10:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> +When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs, the middleware is configured in the Tyk Classic API Definition either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
``

2024-02-01 10:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> +The [simple](#simple-endpoint-cache) option works with the API-level cache and allows you to select which endpoints are cached, but relies upon the cache timeout (refresh) configured at the API-level
```suggestion
The [simple](#simple-endpoint-cache) option works with the API-level cache and allows you to select which endpoints are cached, but relies upon the cache timeout (refresh) configured at the API-level. It will cache all responses received from the endpoint regardless of the HTTP response code for all [safe requests]({{< ref "basic-config-and-security/reduce-latency/caching#global-cache-safe-requests">}}).
```

2024-02-01 10:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> + - `cache_key_regex`: Pattern match for selective caching by body value
```suggestion
 - `cache_key_regex`: pattern match for selective caching by body value
```

2024-02-01 10:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> + - **Cache only these status codes** is where you list which HTTP status codes should be cached, clicking **Add** after entering a code to add it to the list
```suggestion
 - **Cache only these status codes** configures the list of HTTP status codes that should be cached, clicking **Add** after entering a code to add it to the list 
```

2024-02-01 10:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> +Body value match caching is not currently exposed in the Dashboard UI, so it must be enabled though either the raw API editor or the Dashboard API.
Is there a link that can be used for how to enable it in the Dashboard API?

```suggestion
Body value match caching is not currently exposed in the Dashboard UI, so it must be enabled through either the raw API editor or the Dashboard API. 
```

2024-02-01 10:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-02-02 13:57 UTC, andyo-tyk reviewed
Minor improvements

2024-02-02 13:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> +When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
When working with Tyk Classic APIs the middleware is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.

2024-02-02 13:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> + - **Cache only these status codes** is where you list which HTTP status codes should be cached, clicking **Add** after entering a code to add it to the list
```suggestion
 - **Cache only these status codes** is a list of HTTP status codes that should be cached, remember to click **Add** after entering each code to add it to the list 
```

2024-02-02 13:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
> +When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}) either manually within the `.json` file
```suggestion
When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-08 15:52 UTC, dcs3spp commented
@andyo-tyk I've foxed the CI checks in the PR, all checks now passing

2024-02-15 16:23 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-03-13 13:09 UTC, andrei-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +When you use the API-level cache, Tyk will maintain a cache entry for each combination of request method, request path (endpoint) and API key (if authentication is enabled) for an API. The Endpoint C
I feel the last sentence is a bit long and "repetitive" in terms of explaining what features we provide. However take this feedback with a pinch of salt given it comes from a non-native english speaker.

2024-03-13 13:14 UTC, andrei-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +#### API with multiple endpoints
I doubt selective cache is done with reducing cache size as a first priority. I think it's more about having different degrees of freshness for your endpoints e.g. if I want an endpoint to have only 5 mins old data at most or to not have cache at all etc

2024-03-13 13:21 UTC, andrei-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +It's important to note that you must disable the [cache all safe requests]({{< ref "/basic-config-and-security/reduce-latency/caching#global-cache-safe-requests">}}) feature of the API-level cache or
wouldn't it be more correct to have "It's important to note that cache_all_safe_requets feature must be disabled/not be enabled" given that the default state of the flag is false? the phrasing above assumes it's already enabled beforehand

2024-03-14 08:22 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> + - `method`: this method to match on
"the method to match on" ?

2024-03-14 08:26 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> +                "cache_key_regex": "shark",
maybe add a more "patern-ish" example like "\"id\":[^,]*" ?

2024-03-15 14:13 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> +Body value match caching is not currently exposed in the Dashboard UI, so it must be enabled through either the raw API editor or the Dashboard API.
configured might sound better than "enabled"

2024-03-15 14:16 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
> +The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the API-level response header transform.
this confuses me a bit, is this considered part of the response header transform?

2024-03-22 13:47 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +When you use the API-level cache, Tyk will maintain a cache entry for each combination of request method, request path (endpoint) and API key (if authentication is enabled) for an API. The Endpoint C
Thanks - I'll simplify it

2024-03-22 13:47 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
> +#### API with multiple endpoints
I've improved this example

2024-03-22 13:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> + - `method`: this method to match on
Will improve

2024-03-22 13:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
> +                "cache_key_regex": "shark",
To keep it simple I wanted an exact match: will update to `^shark$`

2024-03-22 13:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
> +The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the API-level response header transform.
No - that's a typo 🤦

2024-03-22 13:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
> + < placeholder for video >
Added screenshots for now

2024-03-22 14:47 UTC, dcs3spp approved these changes
@andyo-tyk PR LGTM! @andrei-tyk Would you be able to review if your requested changes have been addressed. Once approved I will merge into the main branch.

2024-03-26 09:42 UTC, andrei-tyk approved these changes

2024-03-26 10:05 UTC, merged