Updated mock response
TykTechnologies/tyk-docs-hugo pull request #4074
Opened 2024-02-01 18:26 UTC by andyo-tyk

### Preview Link

<br>

### Description
Updated Mock Response documentation to match other middleware, covering both Tyk Classic and Tyk OAS APIs

2024-02-01 18:33 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +- `X-Tyk-Accept-Example-Name`: This identified which example to select from an `examples` list
```suggestion
- `X-Tyk-Accept-Example-Name`: This identifies which example to select from an `examples` list
```

2024-02-02 08:35 UTC, lghiur approved these changes

2024-02-02 13:52 UTC, andyo-tyk reviewed
Minor improvement

2024-02-02 13:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> +The middleware is configured in the Tyk Classic API Definition, either manually within the `.json` file or from the API Designer in the Tyk Dashboard.
```suggestion
The middleware is configured in the Tyk Classic API Definition. You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-02 13:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +The middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}) either manually within the `.json` file or from the API Designer in th
```suggestion
The middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
```

2024-02-05 17:53 UTC, dcs3spp requested changes
PR LGTM Andy. I have made minor suggestions and will mark PR as draft until placeholder videos and images are added. If this could also be peer reviewed then can merge into master branch ready for release.

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/low-level-concepts.md
> +- [Authentication]({{< ref "getting-started/key-concepts/authentication" >}}) - with Tyk's OpenAPI implementation you have to option of delegating authentication to the upstream service, or handling
```suggestion
- [Authentication]({{< ref "getting-started/key-concepts/authentication" >}}) - with Tyk's OpenAPI implementation you have the option of delegating authentication to the upstream service, or handling it on the Tyk Gateway 
```

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
> +description: "Detail of the Mock Response middleware"
```suggestion
description: "Explains the Mock Response middleware"
```

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
> +When migrating from a legacy system to new APIs, mock responses can stand in to mimic the old system's outputs during the transitional phases. This provides continuity for client apps relying on the
```suggestion
When migrating from a legacy system to new APIs, mock responses can take precedence to mimic the old system's outputs during the transitional phases. This provides continuity for client apps relying on the old system while new APIs are built that will eventually replace the legacy hooks.
```

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
> +The ability for a gateway to return well-formed mocks when backend APIs are unavailable helps test disaster recovery plans. By intentionally taking APIs offline and verifying the mocks' surface inste
```suggestion
The ability for a gateway to return well-formed mocks when backend APIs are unavailable helps test disaster recovery plans. By intentionally taking APIs offline and verifying the mocks' surface instead, developers gain confidence in the gateway's fallback and business continuity capabilities
```

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
> +Test cases that rely on API interactions can mock those dependencies and provide virtual test data. This removes wait times for real API calls to complete during automated builds. Consumer testing ca
```suggestion
Test cases that rely on API interactions can mock those dependencies and provide virtual test data. This removes wait times for real API calls to complete during automated builds. Consumer testing can verify that provider APIs meet expected contracts using mocks in the CI pipeline. This ensures the contract remains intact across code changes before deployment. Front-end/client code can scale release cycles faster than backend APIs by using mocks to simulate planned API behaviors before they are ready.
```

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> +< TODO: add link to new allow_list middleware which should be here: product-stack/tyk-gateway/middleware/allow-list-tyk-classic#configuring-the-allow-list-in-the-api-designer >
Remember the TODO

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> +< TODO: add image >
Remember to add the image

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> +Once you have selected the Mock response middleware for the endpoint, you can configure the HTTP status code, headers and body to be included in the response. Remember to click **ADD** to add each he
```suggestion
Once you have selected the Mock response middleware for the endpoint, you can configure the HTTP status code, headers and body to be included in the response. Remember to click **ADD**, to add each header to the response.
```

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> +< TODO: add image >
Remember to add image

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +The schema properties may have an `example` field, in which case they will be used to build a mock response, however if there is no `example` value in the schema then default values are used to build
```suggestion
The schema properties may have an `example` field, in which case they will be used to build a mock response. However, if there is no `example` value in the schema then default values are used to build a response as follows:
```

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +  "name": "Foo",
Would the order be the same as that defined in the schema: lastName, name, id?

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +You can direct Tyk to configure the Mock Response middleware automatically from the examples and schema [defined](#example-responses-in-openapi-specification) in the OpenAPI description by enabling t
```suggestion
You can direct Tyk to configure the Mock Response middleware automatically from the examples and schema [defined](#example-responses-in-openapi-specification) in the OpenAPI description. This is can be done by enabling the middleware for an endpoint and configuring the `fromOASExamples` object within that.
```

2024-02-05 17:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +
remember to add the videos

2024-02-06 12:01 UTC, andyo-tyk reviewed
Adjusted terminology slightly to match the Dashboard UI, applied some changes suggested by reviewer

2024-02-06 12:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
> +When migrating from a legacy system to new APIs, mock responses can stand in to mimic the old system's outputs during the transitional phases. This provides continuity for client apps relying on the
```suggestion
When migrating from a legacy system to new APIs, mock responses can be used to emulate the old system's outputs during the transitional phases. This provides continuity for client apps relying on the old system while new APIs are built that will eventually replace the legacy hooks.
```

2024-02-06 12:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> +< TODO: add link to new allow_list middleware which should be here: product-stack/tyk-gateway/middleware/allow-list-tyk-classic#configuring-the-allow-list-in-the-api-designer >
This is pending the merge of another PR...

2024-02-06 12:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +Tyk can automatically populate the Mock Response middleware with [example values](#example-responses-in-openapi-specification) taken from the OpenAPI Document, or you can configure the response [manu
```suggestion
The Mock Response middleware has two modes of operation:
 - in the [basic mode](#manually-configuring-the-middleware-in-the-tyk-oas-api-definition), you can directly configure a response within the middleware in the Tyk extension (`x-tyk-api-gateway`) within the API definition. Tyk will give this response to all valid requests to the endpoint
 - in the [advanced mode](#automatically-configuring-the-middleware-from-the-openapi-document), Tyk will parse the [examples and schema](#example-responses-in-openapi-specification) in the OpenAPI description and use this to generate responses automatically depending on the [content of the request](#working-with-multiple-mock-responses-for-an-endpoint)
```

2024-02-06 12:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +The schema properties may have an `example` field, in which case they will be used to build a mock response, however if there is no `example` value in the schema then default values are used to build
```suggestion
The schema properties may have an `example` field, in which case they will be used to build a mock response. If there is no `example` value in the schema then default values are used to build a response as follows:
```

2024-02-06 12:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +  "lastName": "Bar",
```suggestion
    "name": "Foo",
```

2024-02-06 12:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +  "name": "Foo",
```suggestion
  "lastName": "Bar",
```

2024-02-06 12:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +The `mockResponse` object has the following configuration:
```suggestion
For basic operation, the `mockResponse` object has the following configuration:
```

2024-02-15 16:24 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-03-22 16:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +
Adding screenshots instead for now

2024-03-22 16:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +  "name": "Foo",
Apparently not

2024-03-22 22:47 UTC, dcs3spp requested changes
@andyo-tyk PR LGTM with minor suggestions:
- Should the description field in mock-response-openapi json field be empty in the examples?
- Json code snippets remove the space between back ticks so looks like: ```json
- Why replace OpenAPI document with OpenAPI description? Would this cause confusion in the examples since they include a description attribute in the example.
- Add anchor links for manual and automatic configuration of response middleware in API designer

I'll check the CI link errors and will wait for peer review from @lghiur before merging

2024-03-22 22:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-openapi.md
> +- `boolean` > `true`
is OAS number/float supported?

2024-03-22 22:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> +To enable mock response, you must first add the endpoint to a list - one of [allow list]({{< ref "product-stack/tyk-gateway/middleware/allow-list-middleware" >}}), [block list]({{< ref "product-stack
Should _white_list_ and _black_list_ be replaced by allow list and block list respectively, or are these fields automatically generated from allow list and black list?

2024-03-22 22:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +- in the [manual mode](#manually-configuring-the-middleware-in-the-tyk-oas-api-definition), you can directly configure a response within the middleware in the Tyk extension (`x-tyk-api-gateway`) with
for manual and automatic mode list items could maybe start as:

with [manual mode]...
with [advanced mode]...

2024-03-22 22:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +        "title": "example-mock-response1",
why the change for for title, name and path in the example?

2024-03-22 22:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +### Manual configuration
Add anchor links here and also for automatic configuration section. For example:

```suggestion
### Manual configuration {#manual}
```

2024-03-22 22:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +Select **ADD MIDDLEWARE** and choose the **Mock Response** middleware from the *Add Middleware* screen.
```suggestion
Select **ADD MIDDLEWARE** and choose **Mock Response** middleware from the *Add Middleware* screen.
``

2024-03-22 22:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +Select the **Tyk Classic mock response**
```suggestion
Select **Tyk Classic mock response**
```

2024-03-22 22:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +<br>Selecting this option will cause Tyk Dashboard to check for sample responses or schema in the OpenAPI description and will automatically add the Mock Response middleware for any endpoints that ha
Remove br tag and insert newline between paragraphs

2024-03-22 22:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +You can create and edit mock responses for multiple HTTP status codes by choosing a different state code from the drop down.
```suggestion
You can create and edit mock responses for multiple HTTP status codes by choosing a different status code from the drop down.
```

2024-03-22 23:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +- in the [automatic mode](#automatically-configuring-the-middleware-from-the-openapi-document), Tyk will parse the [examples and schema](product-stack/tyk-gateway/middleware/mock-response-openapi) in
The _examples and schema_ link needs to be a hugo reference rather than an external reference. This is what is causing of the htmltest CI errors:

```suggestion
- in the [automatic mode](#automatically-configuring-the-middleware-from-the-openapi-document), Tyk will parse the [examples and schema]({{< ref "product-stack/tyk-gateway/middleware/mock-response-openapi" >}}) in the OpenAPI description and use this to generate responses automatically depending on the [content of the request](#working-with-multiple-mock-responses-for-an-endpoint)
```

2024-03-22 23:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-openapi.md
> +The `exampleNames` for these two values have been configured as `first-example` and `second-example` and can be used to [invoke the desired response](product-stack/tyk-gateway/middleware/mock-respons
The _invoke the desired response_ link is specified as an external link rather than a hugo link to an internal content file. This is what is causing one of the htmltest CI errors:

```suggestion
The `exampleNames` for these two values have been configured as `first-example` and `second-example` and can be used to [invoke the desired response]({{< ref "product-stack/tyk-gateway/middleware/mock-response-tyk-oas#working-with-multiple-mock-responses-for-an-endpoint" >}}) from a mocked endpoint.
```

2024-03-23 12:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> +< TODO: add link to new allow_list middleware which should be here: product-stack/tyk-gateway/middleware/allow-list-tyk-classic#configuring-the-allow-list-in-the-api-designer >
Done

2024-03-23 12:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +        "title": "example-mock-response1",
Because there are three examples in this file and each can be copy-pasted into the user's Tyk deployment - that would be tricky if they all had the same name

2024-03-23 12:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +### Manual configuration
Why does this need a link? It's already a heading - so can be linked to AFAIK

2024-03-23 12:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> +To enable mock response, you must first add the endpoint to a list - one of [allow list]({{< ref "product-stack/tyk-gateway/middleware/allow-list-middleware" >}}), [block list]({{< ref "product-stack
This is behaviour of the product (which is what these instructions are documenting)

2024-03-23 12:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-openapi.md
> +- `boolean` > `true`
No idea, it'll be in the spec

2024-03-23 12:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +<br>Selecting this option will cause Tyk Dashboard to check for sample responses or schema in the OpenAPI description and will automatically add the Mock Response middleware for any endpoints that ha
```suggestion

Selecting this option will cause Tyk Dashboard to check for sample responses or schema in the OpenAPI description and will automatically add the Mock Response middleware for any endpoints that have suitable data.
```

2024-03-23 12:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +- in the [manual mode](#manually-configuring-the-middleware-in-the-tyk-oas-api-definition), you can directly configure a response within the middleware in the Tyk extension (`x-tyk-api-gateway`) with
```suggestion
- with [manual mode](#manually-configuring-the-middleware-in-the-tyk-oas-api-definition), you can directly configure a response within the middleware in the Tyk extension (`x-tyk-api-gateway`) within the API definition. Tyk will give this response to all valid requests to the endpoint
```

2024-03-23 12:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +- in the [automatic mode](#automatically-configuring-the-middleware-from-the-openapi-document), Tyk will parse the [examples and schema](product-stack/tyk-gateway/middleware/mock-response-openapi) in
```suggestion
- with [automatic mode](#automatically-configuring-the-middleware-from-the-openapi-document), Tyk will parse the [examples and schema](product-stack/tyk-gateway/middleware/mock-response-openapi) in the OpenAPI description and use this to generate responses automatically depending on the [content of the request](#working-with-multiple-mock-responses-for-an-endpoint)
```

2024-03-23 12:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
> +- in the [automatic mode](#automatically-configuring-the-middleware-from-the-openapi-document), Tyk will parse the [examples and schema]({{< ref "product-stack/tyk-gateway/middleware/mock-response-op
```suggestion
- with [automatic mode](#automatically-configuring-the-middleware-from-the-openapi-document), Tyk will parse the [examples and schema]({{< ref "product-stack/tyk-gateway/middleware/mock-response-openapi" >}}) in the OpenAPI description and use this to generate responses automatically depending on the [content of the request](#working-with-multiple-mock-responses-for-an-endpoint)
```

2024-03-24 11:49 UTC, dcs3spp approved these changes
PR LGTM! I've pushed a commit that fixes `` typo introduced by my previous code review suggestion in tyk-OAS config (Step 2: Select the Mock Response middleware). Approving PR and will merge and release after peer review

2024-03-25 16:35 UTC, lghiur approved these changes

2024-03-25 16:35 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
> +When working with Tyk OAS APIs, the mock response middleware is executed at the end of the request processing chain, immediately prior to the request being proxied to the upstream. For this case, all
@andyo-tyk maybe placing 2 bullet points here? one for OAS and one for Classic? or making OAS and classic bold? so that it doesn't just appear as a longer phrase but actual 2 different behaviours

2024-03-25 16:35 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-openapi.md
> +- `string` > `string`
@andyo-tyk maybe this would work better `string` > `"string"`

2024-03-25 16:48 UTC, dcs3spp commented
@andyo-tyk @lghiur Let me know when ready to merge into the main branch/ I'll close this [PR](https://github.com/TykTechnologies/tyk-docs/pull/4125) I previously raised to remove the legacy mock response pagesince @andyo-tyk has now addressed it in this PR.

2024-03-25 17:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
> +When working with Tyk OAS APIs, the mock response middleware is executed at the end of the request processing chain, immediately prior to the request being proxied to the upstream. For this case, all
I've reformatted this in my next commit

2024-03-25 18:05 UTC, merged