Joan-Tyk_Cloud_Platform-Free_Trial-Changes
TykTechnologies/tyk-docs-hugo pull request #4075
Opened 2024-02-02 10:25 UTC by JoanCamosTyk

Additional information has been added from the Introduction to Step 2. A new step has been added called "Step 3: Set up a Policy and Key" A new hyperlink has been added for more clarity.

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-02-02 10:48 UTC, SonjaChevre commented
Thanks @JoanCamosTyk! I’ll review it by Monday.

2024-02-04 12:26 UTC, SonjaChevre requested changes
great work! I have added a couple of comments and feedback. Let's discuss on Monday.

2024-02-04 12:26 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +This documentation is your gateway to effortlessly deploying and utilizing Tyk on our servers. This guide walks you through the process of creating your first API using the intuitive Tyk Dashboard, e
> This documentation is your gateway to effortlessly deploying and utilizing Tyk on our servers. 
Using "gateway" in this expression might be confusing for users (especially foreign speakers). Also the whole sentence doesn't add lots of value, so I would recommend removing it. 

> This guide walks you through the process of creating your first API using the intuitive Tyk Dashboard, eliminating the need for complex setup procedures.

This makes it sound like deploying Tyk Dashboard on premise is complex, which is not a message we want to push ;) At this stage users might still be unclear if they want to go for the cloud or self-managed version. 

Also I would add something about setting up the infrastructure (with Tyk Cloud, you get a dedicated instance which is an important differentiator). Something like this (feel free to improve):

> This guide walks you through the process of signing up with Tyk Cloud, setting up dedicated infrastructure in Tyk Cloud, then creating and securing your first API using Tyk Dashboard.

2024-02-04 12:26 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +Implementing a policy and key system is crucial when creating an API. In this step, we will show you how to do this.
* remove crucial
* create instead of implementing 
* add something about "securing your API" -> e.g. "create a policy to secure the API. (it is more important to tell the users what they get (secure) than telling them it is an important or crucial step.

2024-02-04 12:26 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +#### Implementing a Policy:
Create a policy instead of implementing

2024-02-04 12:26 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +#### Implementing a Key:
Create a key instead of implementing

2024-02-04 12:26 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +If this documentation is not clear to you, please watch this video on how to create your first API using the Tyk Dashboard:
Please remove the link for now. We should put it first on another platform (e.g. youtube), people would not feel safe clicking on a link that looks like this.

Also in the future this tutorial will change again, because we will use the OpenAPI section. So let's keep this (and the video) in mind when we do the next update.

2024-02-04 12:26 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +
Can you please add a step with screenshot in postman on how to access the API? on how to send a test request to validate that everything is right?

2024-02-06 08:37 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
>  * Customize your API settings, including authentication, rate limits, and caching, as per your requirements.
Just one last thing I have spotted: you can now remove this - as we show later how to set up the policy and keys

2024-02-06 08:38 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +#### Step 4: Validate the correctness of your API implementation
Something simpler (telling the user what they are going to do) like "Send a test API request to the secured endpoint"

2024-02-06 08:44 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Keep https://httpbin.org/ as the upstream URL and click on "Configure API."
the click on "Configure API" can we removed here - as you mention it below already

2024-02-06 08:45 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
>  * Customize your API settings, including authentication, rate limits, and caching, as per your requirements.
and also click "save" can be removed - as you need to stay on that screen to secure the API

2024-02-06 08:47 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Click on the buttons "Create Policy" and "Update."
"update" is not needed, once the policy is created, you can just navigate away.

2024-02-06 08:49 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +Congratulations! Your key has now been created!
maybe a screenshot would be nice - to see that the key has been generated. Also please add a note to tell the user to copy the "Key ID" as they will need it in the next step when testing the API.

2024-02-06 10:18 UTC, dcs3spp requested changes
Thanks for submitting updated Cloud Free Trial content @JoanCamosTyk 

PR looks good to me, I've suggested some minor changes. Once updated and peer review approved we can merge and release.

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Go to the "Configurations" section and add a Policy Name (eg., Default Policy httpbin).
```suggestion
* Go to the "Configurations" section and add a Policy Name (e.g., 'Default Policy httpbin').
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* In the "Access Rights" section, please select the previously created Policy (eg., Default Policy httpbin).
```suggestion
* In the "Access Rights" section, please select the previously created Policy (e.g., 'Default Policy httpbin').
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Click on the button "ADD KEY."
```suggestion
* Click on the button "ADD KEY".
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Go to the "Configurations" section and give your key an alias (eg., platform_team).
```suggestion
* Go to the "Configurations" section and give your key an alias (e.g., 'platform_team').
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Click on the button "Create Key."
```suggestion
* Click on the button "Create Key".
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +#### Step 4: Validate the correctness of your API implementation
```suggestion
## Step 4: Send a test API request to the secured endpoint
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +
Should we also add a curl example?

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Select the previously created API (eg.,httpbin).
```suggestion
* Select the previously created API (e.g., httpbin).
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* In Postman, choose "Send an API request."
```suggestion
* In Postman, choose "Send an API request".
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Copy the previously created "Key ID."
```suggestion
* Copy the previously created "Key ID".
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* On Postman, navigate to "Authorization" tab.
```suggestion
* On Postman, navigate to the "Authorization" tab.
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Change the authentication type from "Inherit auth from parent" to "API Key."
```suggestion
* Change the authentication type from "Inherit auth from parent" to "API Key".
```

2024-02-06 10:18 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +* Click the "Send button to submit the request.
```suggestion
* Click the "Send" button to submit the request.
```

2024-02-07 08:21 UTC, SonjaChevre commented on tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
> +
yes, good idea to add a curl example

2024-02-08 12:45 UTC, dcs3spp approved these changes

2024-02-08 12:47 UTC, dcs3spp reviewed
Thanks for submitting the PR @JoanCamosTyk and adding the Curl command example. I have approved the PR and updated so that step 4 appears in right hand nav menu.

Once @SonjaChevre has peer reviewed I'll release the PR into docs. 

Many thanks again!

2024-02-09 07:34 UTC, SonjaChevre commented
I have just made one last change: using the code formatting for curl.
Good for me, thanks @JoanCamosTyk and @dcs3spp !

2024-02-09 07:35 UTC, SonjaChevre approved these changes

2024-02-13 10:30 UTC, merged

2024-02-13 10:30 UTC, dcs3spp commented
/release to release-5.2

2024-02-13 10:43 UTC, dcs3spp commented
/release to release-5.1

2024-02-13 10:54 UTC, dcs3spp commented
/release to release-5