[DX-1015] Create Tyk Charts Product Stack Section
TykTechnologies/tyk-docs-hugo pull request #4076
Opened 2024-02-02 10:54 UTC by dcs3spp

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-02-06 12:45 UTC, dcs3spp reviewed
Hi @caroltyk, PR is looking good in the new structure. GHub will not allow me to submit review of request changes since I created the PR with the skeleton structure earlier. I have added comment suggestions and remember to add content to the release note, including any details of deprecations, dependencies etc.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +To deploy Tyk OSS using the new Helm chart, please use [tyk-oss]{{<ref "/product-stack/tyk-charts/tyk-oss-chart">}}
```suggestion
To deploy Tyk OSS using the new Helm chart, please use [tyk-oss]{{< ref "product-stack/tyk-charts/tyk-oss-chart" >}}
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +To deploy hybrid data planes using the new Helm chart, please use [tyk-data-plane]{{<ref "/product-stack/tyk-charts/tyk-data-plane-chart">}}
```suggestion
To deploy hybrid data planes using the new Helm chart, please use [tyk-data-plane]{{< ref "/product-stack/tyk-charts/tyk-data-plane-chart" >}}
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +To deploy Tyk Self Managed (for single data center) using the new helm chart, please use [tyk-stack]{{<ref "/product-stack/tyk-charts/tyk-stack-chart">}}
```suggestion
To deploy Tyk Self Managed (for single data center) using the new helm chart, please use [tyk-stack]{{< ref "product-stack/tyk-charts/tyk-stack-chart" >}}
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-5.3.md
> +<!--
Remember to add content for release notes 5.3 for Tyk Charts

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +title: Tyk Control Plane Chart
Remember to add content for Tyk Control Plane Chart

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +`tyk-data-plane` chart provides the default deployment of a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users. It will deploy the data plane components that remotely connect to a MDCB contr
```suggestion
The `tyk-data-plane` chart provides the default deployment of a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users. It will deploy the data plane components that remotely connect to a MDCB control plane.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk Pump, an analytics purger that moves the data generated by your Tyk gatew
```suggestion
It includes the following components:
- *Tyk Gateway*: An open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols.
- *Tyk Pump*: An analytics purger that moves the data generated by your Tyk gateways to any back-end storage. 

Furthermore, it has all the required modifications to easily connect to Tyk Cloud or Multi Data Center (MDCB) control plane.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +### Introduction
Update section title to What components are installed?

Previous section was introduction

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Also, you can set the version of each component through `image.tag`. You could find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio).
```suggestion
Also, you can set the version of each component through `image.tag`. You can find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio).
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +* Kubernetes 1.19+
For consistency use - for list items, e.g.

- Kubernetes 1.19+

and add links to Kubernetes and Helm download section.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +* Connection details to remote control plane. See the [section](#obtain-your-remote-control-plane-connection-details) below for how to obtain them from Tyk Cloud.
Does _Connection details to remote control plane._ mean: 

_A connection to the remote control plane should be configured?_

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +At the end of this quickstart Tyk Gateway should be accessible through service `gateway-svc-hybrid-dp-tyk-gateway` at port `8080`. Pump is also configured with Hybrid Pump which sends aggregated anal
```suggestion
At the end of this quickstart, Tyk Gateway should be accessible through service `gateway-svc-hybrid-dp-tyk-gateway` at port `8080`. Tyk Pump is also configured with Hybrid Pump, which sends aggregated analytics to Tyk Cloud, and Prometheus Pump which expose metrics locally at `:9090/metrics`.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +To install the chart from the Helm repository in namespace `tyk` with the release name `tyk-data-plane`:
```suggestion
To install the chart from the Helm repository in namespace `tyk` with the release name `tyk-data-plane`, issue the following commands:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +See [Configuration](#configuration) section for the available config options and modify your local `values.yaml` file accordingly. Then install the chart:
```suggestion
Consult the [Configuration](#configuration) section for the available configuration options and modify your local `values.yaml` file accordingly. Then install the chart by issuing the following command below:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +If you were using `tyk-hybrid` chart for existing release, you cannot upgrade directly. Please modify the `values.yaml` base on your requirements and install using the new `tyk-data-plane` chart.
Does this mean that tyk-hybrid chart users have to install the tyk-data-plane chart from scratch, a fresh install?

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +To get all configurable options with detailed comments:
```suggestion
To list all configurable options with detailed comments, issue the following command:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Tyk uses Redis for distributed rate-limiting and token storage. You may use the Bitnami chart to install or Tyk's `simple-redis` chart for POC purpose.
Add a link to Bitname chart here also

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +| `global.redis.passSecret.keyName` | key name to retrieve redis password from the secret |
```suggestion
| `global.redis.passSecret.keyName` | key name to retrieve Redis password from the secret |
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +You can reference the password secret generated by Bitnami chart by  `--set global.redis.passSecret.name=tyk-redis` and `--set global.redis.passSecret.keyName=redis-password`, or just set `global.red
Maybe give one full example of using helm install --set command here

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Please note that these provided charts must never be used in production or for anything
Add links to Bitnami Redis and official Redis chart here

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Kubernetes secrets can be referenced, and the chart will
make Kubernetes line part of the same paragraph in the Markdown file

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +in it. Then, this secret must be referenced via `global.secrets.useSecretName`.
move this line so that it is part of same paragraph above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +and `groupID` keys and refer to it in `global.remoteControlPlane.useSecretName`.
move this line into line 208 above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +where `foo-secret` should contain `orgId`, `userApiKey` and `groupID` keys in it.
can add an example of what this looks like?

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Redis password can also be provided via a secret. Store Redis password in Kubernetes secret and refer to this secret
```suggestion
The Redis password can also be provided via a secret. Store Redis password in Kubernetes secret and refer to this secret
```
and move the line below up into the same paragraph

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +```
Maybe add an example of how to refer to this secret after the yaml example

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Set version of gateway at `tyk-gateway.gateway.image.tag`. You can find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio). Please check [Tyk Release notes]({{<ref "
Maybe we should add specific link to Docker Gateway tags (https://hub.docker.com/r/tykio/tyk-gateway/tags)
and specific link to Tyk Gateway release notes product-stack/tyk-gateway/release-notes/overview/

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +You can enable autoscaling of the gateway by `--set tyk-gateway.gateway.autoscaling.enabled=true`. By default, it will enable `Horizontal Pod Autoscaler` resource with target average CPU utilisation
```suggestion
You can enable autoscaling of the gateway by `--set tyk-gateway.gateway.autoscaling.enabled=true`. By default, it will enable the `Horizontal Pod Autoscaler` resource with target average CPU utilisation at 60%, scaling between 1 and 3 instances. To customise those values you can modify the `tyk-gateway` section of `values.yaml` as shown below:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Set `tyk-gateway.gateway.control.enabled` to true will allow you to run the [Gateway API]({{<ref "/tyk-gateway-api">}}) on a separate port and protect it behind a firewall if needed.
```suggestion
Set `tyk-gateway.gateway.control.enabled` to true will allow you to run the [Gateway API]({{<ref "tyk-gateway-api">}}) on a separate port and protect it behind a firewall if needed.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Here is a reference of all [Tyk Gateway Configuration Options]({{<ref "/tyk-oss-gateway/configuration">}}).
```suggestion
For further details for configuring Tyk Gateway, please consult the [Tyk Gateway Configuration Options]({{<ref "tyk-oss-gateway/configuration">}}) guide.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +To enable Pump, set `global.components.pump` to true, and configure below inside `tyk-pump` section.
```suggestion
To enable Pump, set `global.components.pump` to true, and configure as detailed below inside `tyk-pump` section.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +| Pump                      | Configuration                                                                                              |
Do we need the table if we have the sections below?

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Add `prometheus` to `tyk-pump.pump.backend`, and add connection details for prometheus under `tyk-pump.pump.prometheusPump`.
Add example configuration file section here

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +To setup other backends for pump, refer to this [document](https://github.com/TykTechnologies/tyk-pump/blob/master/README.md#pumps--back-ends-supported) and add the required environment variables in
```suggestion
To setup other backends for Pump, refer to this [document](https://github.com/TykTechnologies/tyk-pump/blob/master/README.md#pumps--back-ends-supported) and add the required environment variables in `tyk-pump.pump.extraEnvs`
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +`tyk-oss` provides the default deployment of the Tyk Open Source stack. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk P
Move the explanations of Tyk Gateway and Tyk Pump into list items as previously suggested above.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +* Kubernetes 1.19+
Add external download links for Kubernetes and helm.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +To install the chart from the Helm repository in namespace `tyk` with the release name `tyk-oss`:
```suggestion
This section explains how to install the chart from the Helm repository in namespace `tyk` with the release name `tyk-oss`.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +First, add our Helm repo and get default values:
```suggestion
First, add our Helm repo and get default values, as shown in the commands listed below:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +See [Configuration](#configuration) section for the available config options and modify your local `values.yaml` file accordingly. Then install the chart:
Consult the [Configuration](#configuration) section for the available configuration options and modify your local `values.yaml` file accordingly. Then install the chart using the following command:

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +If you were using `tyk-headless` chart for existing release, you cannot upgrade directly. Please modify the `values.yaml` base on your requirements and install using the new `tyk-oss` chart.
```suggestion
If you were using `tyk-headless` chart for an existing release, you cannot upgrade directly. Please modify the `values.yaml` base on your requirements and install using the new `tyk-oss` chart.
```

Does this mean user has to do a fresh deploy using tyk-oss chart?

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +To get all configurable options with detailed comments:
```suggestion
To list all configurable options with detailed comments:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Tyk uses Redis for distributed rate-limiting and token storage. You may use the Bitnami chart to install or Tyk's `simple-redis` chart for POC purpose.
Add link to Bitnami chart here.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +| `global.redis.passSecret.keyName` | key name to retrieve redis password from the secret |
```suggestion
| `global.redis.passSecret.keyName` | key name to retrieve Redis password from the secret |
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +but a quick start evaluation only. Use Bitnami Redis or Official Redis Helm chart in any other case.
Add links to Bitnami Redi or Official Redis Helm charts here

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Kubernetes secrets can be referenced, and the chart will
Make this line part of the same sentence above.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +in it. Then, this secret must be referenced via `global.secrets.useSecretName`.
Make this line part of the same sentence above.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +```
Show an example of referencing this password below the yaml configuration

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +You can enable autoscaling of the gateway by `--set tyk-gateway.gateway.autoscaling.enabled=true`. By default, it will enable `Horizontal Pod Autoscaler` resource with target average CPU utilisation
```suggestion
You can enable autoscaling of the gateway by `--set tyk-gateway.gateway.autoscaling.enabled=true`. By default, it will enable the `Horizontal Pod Autoscaler` resource with target average CPU utilisation at 60%, scaling between 1 and 3 instances. To customise those values you can modify the tyk-gateway section of `values.yaml`, as shown below:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +* Multiple gateways do not share app configs
Replace * with - for consistency in these two list items.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +By default, Gateway stores API configurations at `/mnt/tyk-gateway/apps` inside the Gateway container. There are a a few challenges:
```suggestion
By default, the Gateway stores API configurations at `/mnt/tyk-gateway/apps` inside the Gateway container. There are a a few challenges:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +* The configuration is not persistent. It got lost whenever pod restart
```suggestion
* The configuration is not persistent, i.e. it will not be retained whenever a pod restarts.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +The same applies to security policies and middleware too which is stored at `/mnt/tyk-gateway/policies` and `/mnt/tyk-gateway/middleware` respectively.
```suggestion
The same applies to security policies and middleware too, which is stored at `/mnt/tyk-gateway/policies` and `/mnt/tyk-gateway/middleware` respectively.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +This can be solved by instantiating a Persistent Volume as shared storage for the gateway instances. As each gateway is reload, they would get the API configurations from the same storage, solving th
```suggestion
This can be solved by instantiating a Persistent Volume as shared storage for the gateway instances. As each gateway is reloaded, they would get the API configurations from the same storage, solving the synchronisation issue between gateways. Also, the storage is persistent and can be designed to be resilient against cluster failure, thus your API configurations can be retained after pod restart.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +See [Running multiple instances of Tyk Gateway]({{<ref "/deployment-and-operations/tyk-open-source-api-gateway/setup-multiple-gateways">}}) for a step-by-step guide on scaling Tyk Gateway on Kubernet
```suggestion
See [Running multiple instances of Tyk Gateway]({{<ref "deployment-and-operations/tyk-open-source-api-gateway/setup-multiple-gateways">}}) for a step-by-step guide on scaling Tyk Gateway on Kubernetes.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +#### Setting Environment Variable
```suggestion
#### Setting Environment Variables
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Here is a reference of all [Tyk Gateway Configuration Options]({{<ref "/tyk-oss-gateway/configuration">}}).
```suggestion
For further details for configuring Tyk Gateway, consult the [Tyk Gateway Configuration Options]({{<ref "/tyk-oss-gateway/configuration">}}) guide.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +|---------------------------|------------------------------------------------------------------------------------------------------------|
Do we need the table if we also have the sections below?

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Add `prometheus` to `tyk-pump.pump.backend`, and add connection details for prometheus under `tyk-pump.pump.prometheusPump`.
```suggestion
Add `prometheus` to `tyk-pump.pump.backend`, and add connection details for Prometheus under `tyk-pump.pump.prometheusPump`. 
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +To install Mongo you can use these rather excellent charts provided by Bitnami:
```suggestion
To install MongoDB you can use these rather excellent charts provided by Bitnami:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +(follow notes from the installation output to get connection details and update them in `values.yaml` file)
Refactor to make this sentence instead of brackets

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +NOTE: [Here is](https://tyk.io/docs/planning-for-production/database-settings/) list of supported MongoDB versions. Please make sure you are installing mongo helm chart that matches these version.
```suggestion
NOTE:  Please make sure you are installing a mongo helm chart that matches a supported [version](https://tyk.io/docs/planning-for-production/database-settings/).
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +*Important Note regarding MongoDB:* This helm chart enables the PodDisruptionBudget for MongoDB with an arbiter replica-count of 1. If you intend to perform system maintenance on the node where the M
Use the warning shortcut to render this as a warning.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Add following under the `global` section in `values.yaml`:
```suggestion
Add the following configuration under the `global` section in `values.yaml`:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +If you are using the SQL pumps in the tyk-oss installation you will require PostgreSQL installed for that as well.
```suggestion
If you are using the SQL Pumps in the tyk-oss installation you will require PostgreSQL installed for that as well.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +(follow notes from the installation output to get connection details and update them in `values.yaml` file)
Refactor to remove brackets and replace with sentence.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Add following under the `global` section in `values.yaml`:
```suggestion
Add the following configuration under the `global` section in `values.yaml`:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Uptime Pump can be configured by setting `tyk-pump.pump.uptimePumpBackend` in values.yaml file. It support the following values
```suggestion
Uptime Pump can be configured by setting `tyk-pump.pump.uptimePumpBackend` in values.yaml file. It supports the following values:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +1. mongo: Used to set mongo pump for uptime analytics. Mongo Pump should be enabled.
Make mongo pump capitals in first explanation sentence.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +2. postgres: Used to set postgres pump for uptime analytics. Postgres Pump should be enabled.
Make postgres pump capitals in first explanation sentence.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +`tyk-stack` provides the default deployment of Tyk Self Managed on a Kubernetes cluster. It will deploy all required Tyk components with the settings provided in the values.yaml file.
```suggestion
The `tyk-stack` chart provides the default deployment of Tyk Self Managed on a Kubernetes cluster. It will deploy all required Tyk components with the settings provided in the values.yaml file.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Also, you can set the version of each component through `image.tag`. You could find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio).
```suggestion
Also, you can set the version of each component through `image.tag`. You can find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio).
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +```
```suggestion
```bash
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +```
```suggestion
```bash
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +If you would like to use Enterprise Developer Portal, additional license is required:
```suggestion
If you would like to use Enterprise Developer Portal, an additional license is required:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +If you were using `tyk-pro` chart for existing release, you cannot upgrade directly. Please modify the values.yaml base on your requirements and install using the new `tyk-stack` chart.
This means that tyk-pro users have to do fresh deploy using tyk-stack chart?

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +To get all configurable options with detailed comments:
```suggestion
To list all configurable options with detailed comments:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +string and password respectively.
move this into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +`tyk-redis-master.tyk.svc:6379` (Tyk needs the name including the port)
move this into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +If you have already installed MongoDB or PostgreSQL, you can set the connection details in `global.mongo` and `global.postgres` section of values file respectively.
```suggestion
If you have already installed MongoDB or PostgreSQL, you can set the connection details in the `global.mongo` and `global.postgres` sections of the `values.yaml` file respectively.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Kubernetes secrets can be referenced, and the chart will
move this line into the sentence above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +If Tyk Dashboard bootstrapping is enabled, Tyk Dashboard admin user will be created according to the `global.adminUser` field.
```suggestion
If Tyk Dashboard bootstrapping is enabled, a Tyk Dashboard admin user will be created according to the `global.adminUser` field.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +> [!NOTE]
Use note and warning shortcodes

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +in it. Then, this secret must be referenced via `global.adminUser.useSecretName`.
move this line into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +in it. Then, this secret must be referenced via `global.adminUser.useSecretName`.
move this line into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +in it. Then, this secret must be referenced via `global.adminUser.useSecretName`.
move this line into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +in it. Then, this secret must be referenced via `global.adminUser.useSecretName`.
move this line into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +in it. Then, this secret must be referenced via `global.secrets.useSecretName`.
move this line into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +key in it. Then, this secret must be referenced via `global.secrets.useSecretName`.
move this line into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +> [!NOTE]
use the note shortcode here

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +the secret should contain a key called `DashLicense`.
move this line into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +please use `tyk-dev-portal.useSecretName`, where the secret should contain a key called
move this line into the line above

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +In order to refer Tyk Enterprise Developer Portal AWS S3 Access Key ID through Kubernetes secret,
Reafctor to read:

_In order to refer to the *Tyk Enterprise Developer Portal AWS S3 Access Key ID* using a Kubernetes secret, please use `tyk-dev-portal.useSecretName`, where the secret should contain a key called 
`DevPortalAwsAccessKeyId`._

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +In order to refer Tyk Enterprise Developer Portal connection string to the selected database through Kubernetes secret,
_In order to refer to the *Tyk Enterprise Developer Portal database connection string* using a Kubernetes secret,
please use `tyk-dev-portal.useSecretName`, where the secret should contain a key called 
`DevPortalAwsSecretAccessKey`._

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +> [!WARNING]
Use warning shortcode here

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +```
Include an short example of how to refer to the secret

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Redis password can also be provided via a secret. Store Redis password in Kubernetes secret and refer to this secret
_A Redis password can also be provided via a secret. Store the Redis password in a Kubernetes secret and refer to this secret via `global.redis.passSecret.name` and `global.redis.passSecret.keyName` field, as follows:_

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +#### MongoDB or Postgres connection strings
```suggestion
#### MongoDB or PostgreSQL connection strings
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Storage connection strings can also be provided via a secret. Store the connection string in Kubernetes secret and
_Storage connection strings can also be provided via a secret. Store the connection string in a Kubernetes secret and  refer to this secret via `global.{mongo,postgres}.connectionURLSecret.name` and `global.{mongo,postgres}.connectionURLSecret.keyName` field, as follows:_

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +- Postgres:
```suggestion
- PostgreSQL:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Configure below inside `tyk-gateway` section.
Refactor this to introduce what the section shows, something like:

This section explains how to configure the ty-gateway section for updating the Gateway version, enabling TLS, enabling autoscaling etc. etc.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Set version of gateway at `tyk-gateway.gateway.image.tag`. You can find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio). Please check [Tyk Release notes]({{<ref "
Use specific link to Docker Gateway tags and add link to Gateway Release Notes overview in product stack section

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +You can enable autoscaling of the gateway by `--set tyk-gateway.gateway.autoscaling.enabled=true`. By default, it will enable `Horizontal Pod Autoscaler` resource with target average CPU utilisation
```suggestion
You can enable autoscaling of the gateway by `--set tyk-gateway.gateway.autoscaling.enabled=true`. By default, it will enable the `Horizontal Pod Autoscaler` resource with target average CPU utilisation at 60%, scaling between 1 and 3 instances. To customise those values you can modify the tyk-gateway section of the `values.yaml` file as shown below:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +`tyk-stack` chart manages one Gateway Deployment in the same namespace as Tyk Dashboard. You can flexibly deploy additional gateways using `tyk-gateway` component chart. With gateway sharding, it is
```suggestion
The `tyk-stack` chart manages one Gateway deployment in the same namespace as Tyk Dashboard. You can flexibly deploy additional gateways using the `tyk-gateway` component chart. With gateway sharding, it is useful for:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +- Deploy Gateways in different networks,
```suggestion
- Deploying Gateways in different networks.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +- Deploy Gateways with different resources and autoscaling parameters,
```suggestion
- Deploying Gateways with different resources and autoscaling parameters.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +<!-- BEGIN import from pump doc -->
Remember to remove this comment

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +(follow notes from the installation output to get connection details and update them in `values.yaml` file)
refactor so this is a sentence rather than bracketed note

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +*Important Note regarding MongoDB:* This helm chart enables the PodDisruptionBudget for MongoDB with an arbiter replica-count of 1. If you intend to perform system maintenance on the node where the M
Use the warning shortcode here

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +NOTE: [Here is](https://tyk.io/docs/planning-for-production/database-settings/) list of supported MongoDB versions. Please make sure you are installing mongo helm chart that matches these versions.
Replace as suggested in previous review comment

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +(follow notes from the installation output to get connection details and update them in `values.yaml` file)
Refactor this to remove brackets and replace with sentence

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +  # Postgres connection string parameters.
In the yaml config example comments, replace postgres with PostgreSQL

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Uptime Pump can be configured by setting `pump.uptimePumpBackend` in values.yaml file. It support following values
```suggestion
Uptime Pump can be configured by setting `pump.uptimePumpBackend` in values.yaml file. It supports the following values:
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +1. mongo: Used to set mongo pump for uptime analytics. Mongo Pump should be enabled.
Capitalise mongo pump

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +2. postgres: Used to set postgres pump for uptime analytics. Postgres Pump should be enabled.
Capitalise postgres pump and mongo pump, replacing postgres with PostgreSQL

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Tyk Dashboard License is required. It can be set up in `global.license.dashboard` or through secret `global.secrets.useSecretName`. The secret should contain a key called DashLicense.
```suggestion
Tyk Dashboard License is required. It can be set up in `global.license.dashboard` or through secret `global.secrets.useSecretName`. The secret should contain a key called *DashLicense*.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +To enable bootstrapping, set `global.components.bootstrap` to `true`. It would run [tyk-k8s-bootstrap](https://github.com/TykTechnologies/tyk-k8s-bootstrap) to bootstrap `tyk-stack` and to create Kub
```suggestion
To enable bootstrapping, set `global.components.bootstrap` to `true`. It would run [tyk-k8s-bootstrap](https://github.com/TykTechnologies/tyk-k8s-bootstrap) to bootstrap `tyk-stack` and to create Kubernetes secrets that can be utilised in Tyk Operator and Tyk Enterprise Developer Portal.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +If Tyk is already bootstrapped, the application will bypass the creation of the Tyk Organization and Admin User, proceeding directly with the creation of Kubernetes Secrets.
```suggestion
If Tyk is already bootstrapped, the application will bypass the creation of the Tyk Organisation and Admin User, proceeding directly with the creation of Kubernetes Secrets.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +If you use database as storage, please set `tyk-dev-portal.storage.type` to `db`, and configure `tyk-dev-portal.database` section with database connection details.
```suggestion
If you use a database as storage, please set `tyk-dev-portal.storage.type` to `db`, and configure the `tyk-dev-portal.database` section with database connection details.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Tyk Enterprise Developer Portal supports different storage options for storing the portal's CMS assets such as images, theme files and Open API Specification files. Please see the [Enterprise Develop
```suggestion
Tyk Enterprise Developer Portal supports different storage options for storing the Portal's CMS assets such as images, theme files and Open API Specification files. Please see the [Enterprise Developer Portal Storage settings]({{<ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal-settings">}}) page for all the available options. 
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +`tyk-hybrid` chart is deprecated. Please use our Tyk Data Plane at [tyk-data-plane]({{<ref "tyk-cloud/environments-deployments/hybrid-gateways">}}) instead.
Make sure this is added to the release notes

```suggestion
The `tyk-hybrid` chart is deprecated. Please use our Tyk Data Plane at [tyk-data-plane]({{<ref "tyk-cloud/environments-deployments/hybrid-gateways">}}) instead. 
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
> +We recommend all users to migrate to `tyk-data-plane` Chart. Please review the [Configuration]({{<ref "/tyk-cloud/environments-deployments/hybrid-gateways#configuration">}}) section of the new helm c
```suggestion
We recommend that all users migrate to the `tyk-data-plane` Chart. Please review the [Configuration]({{<ref "/tyk-cloud/environments-deployments/hybrid-gateways#configuration">}}) section of the new helm chart and cross-check with your existing configurations while planning for migration. 
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +If you chose to use Helm, you can use Tyk Data Plane helm chart to manage installs of the hybrid gateways and Tyk Pump.
Add a link also to the Tyk Data Plane Helm chart

```suggestion
If you chose to use Helm, you can use the Tyk Data Plane helm chart to manage installs of the hybrid gateways and Tyk Pump.
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +If you chose to use Helm, you can use Tyk Open Source helm chart to manage installs of the Tyk Gateway and Tyk Pump.
Add a link to Tyk Open Source helm chart here and remove the last sentence at line 18.

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart.md
> +`tyk-headless` chart is deprecated. Please use our Tyk Chart for Tyk open source at [tyk-oss]({{<ref "/tyk-oss/ce-helm-chart-new">}}) instead.
Ensure the deprecation is added to the release notes

```suggestion
`tyk-headless` chart is deprecated. Please use our Tyk Chart for Tyk Open Source at [tyk-oss]({{<ref "/tyk-oss/ce-helm-chart-new">}}) instead. 
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/tyk-oss/ce-helm-chart.md
> +We recommend all users to migrate to `tyk-oss` Chart. Please review the [Configuration]({{<ref "/tyk-oss/ce-helm-chart-new">}}) section of the new helm chart and cross-check with your existing config
```suggestion
We recommend all users migrate to the `tyk-oss` Chart. Please review the [Configuration]({{<ref "/tyk-oss/ce-helm-chart-new">}}) section of the new helm chart and cross-check with your existing configurations while planning for migration. 
```

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +To deploy Tyk OSS using the new Helm chart, please use [tyk-oss]{{<ref "/product-stack/tyk-charts/tyk-oss-chart">}}
At time of review, links below are displaying incorrectly in preview

2024-02-06 12:45 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +If you chose to use Helm, you can use Tyk Stack helm chart to manage installs of all Tyk Dashboard, Gateway, Tyk Pump, and Tyk Enterprise Portal.
Maybe add the link to the Tyk Stack helm chart here and remove last sentence at line 17

```suggestion
If you chose to use Helm, you can use the Tyk Stack helm chart to manage installs of all Tyk Dashboard, Gateway, Tyk Pump and Tyk Enterprise Portal.
```

2024-02-06 13:09 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +To deploy Tyk OSS using the new Helm chart, please use [tyk-oss]{{<ref "/product-stack/tyk-charts/tyk-oss-chart">}}
fixed

2024-02-06 13:09 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +To deploy hybrid data planes using the new Helm chart, please use [tyk-data-plane]{{<ref "/product-stack/tyk-charts/tyk-data-plane-chart">}}
fixed

2024-02-06 13:09 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +To deploy Tyk Self Managed (for single data center) using the new helm chart, please use [tyk-stack]{{<ref "/product-stack/tyk-charts/tyk-stack-chart">}}
fixed

2024-02-06 13:10 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-5.3.md
> +<!--
WIP - The upper section of the release note is updated. Will add in change log next week.

2024-02-06 13:11 UTC, caroltyk commented on tyk-docs/content/tyk-oss/ce-helm-chart-new.md
> +If you chose to use Helm, you can use Tyk Open Source helm chart to manage installs of the Tyk Gateway and Tyk Pump.
updated

2024-02-06 13:12 UTC, caroltyk commented on tyk-docs/content/tyk-oss/ce-helm-chart.md
> +`tyk-headless` chart is deprecated. Please use our Tyk Chart for Tyk open source at [tyk-oss]({{<ref "/tyk-oss/ce-helm-chart-new">}}) instead.
This was added in previous release notes. Not related to coming release.

2024-02-06 13:12 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +To deploy Tyk OSS using the new Helm chart, please use [tyk-oss]{{<ref "/product-stack/tyk-charts/tyk-oss-chart">}}
fixed

2024-02-06 13:13 UTC, caroltyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
> +If you chose to use Helm, you can use Tyk Stack helm chart to manage installs of all Tyk Dashboard, Gateway, Tyk Pump, and Tyk Enterprise Portal.
updated

2024-02-15 14:31 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +              show: False
@caroltyk Should the "Tyk Stack Helm chart" page be removed. If so then I can create an alias to the new Tyk Stack Helm Chart. This would mean that when the user visits URL /deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack they get redirected to the new helm chart in product stack.

2024-02-15 14:54 UTC, dcs3spp reviewed
@caroltyk PR is looking good and structure is becoming established I think now.

- Control plane chart needed
- Release notes required
- Does the existing Tyk Stack Helm chart page need to be removed? If so I can remove it and setup a redirect from it's url to show the new chart in product stack? I noticed that the Tyk Stack Helm Chart has been marked as hidden in this PR's. menu.yaml file and left a comment in menu.yaml section of this PR.

I think that the ce-helm-chart-new should should be moved into Product stack underdeprecated folder. Why do we need to keep it in deployment and operations Kubernetes? Maybe we can discuss in a separate PR iteration?

2024-02-19 02:33 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +title: Tyk Control Plane Chart
Updated and ready for review

2024-02-19 02:35 UTC, caroltyk commented on tyk-docs/data/menu.yaml
> +              show: False
Yes please @dcs3spp

2024-02-19 03:10 UTC, caroltyk commented
> @caroltyk PR is looking good and structure is becoming established I think now.
> 
> * Control plane chart needed
> * Release notes required
> * Does the existing Tyk Stack Helm chart page need to be removed? If so I can remove it and setup a redirect from it's url to show the new chart in product stack? I noticed that the Tyk Stack Helm Chart has been marked as hidden in this PR's. menu.yaml file and left a comment in menu.yaml section of this PR.
> * We should also arrange a peer review
> 
> I think that the ce-helm-chart-new should should be moved into Product stack under a deprecated folder. Why do we need to keep it in deployment and operations Kubernetes? Maybe we can discuss in a separate PR iteration?

Thanks @dcs3spp . 
1, 2: Control plane chart and release notes are updated and sent for peer review.
3: tyk stack helm chart page can be removed, because I have create 2 separate quick start pages in deployment and operations.
4. I’ve updated content in ce-helm-chart-new. It contains the updated quick start guide for OSS now.

2024-02-19 08:20 UTC, komalsukhani requested changes

2024-02-19 08:20 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +<summary>Gateway: Enable Leaky Bucket Rate Limiter</summary>
Should we say `Support Leaky Bucket Rate Limiter` instead, as it is disabled by default. So saying Enable sounds a bit misleading?

2024-02-19 08:20 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +To enable it, set `gateway.pdb.enabled` to `true` and configure `gateway.pdb.minAvailable` and `gateway.pdb.maxUnavailable`.
```suggestion
To enable it, set `gateway.pdb.enabled` to `true` and configure `gateway.pdb.minAvailable` or `gateway.pdb.maxUnavailable`.
```

2024-02-19 08:20 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +You can enable Internal [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by field `tyk-dashboard.tib.enabled` to `true`.
```suggestion
You can enable Embedded [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by field `tyk-dashboard.tib.enabled` to `true`.
```
I think we call it `Embedded` TIB instead of internal in the tyk-docs

2024-02-19 08:20 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +<summary>New umbrella chart to Tyk Control Plane</summary>
```suggestion
<summary>New umbrella chart to deploy Tyk Control Plane</summary>
```

2024-02-19 08:20 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +Tyk uses Redis for distributed rate-limiting and token storage. You may use the Bitnami chart to install or Tyk's `simple-redis` chart for POC purpose.
```suggestion
Tyk uses Redis for distributed rate-limiting and token storage. You may use the Bitnami chart or Tyk's `simple-redis` to install chart for POC purpose.
```

2024-02-19 08:20 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +To enable bootstrapping, set `global.components.bootstrap` to `true`. It would run [tyk-k8s-bootstrap](https://github.com/TykTechnologies/tyk-k8s-bootstrap) to bootstrap `tyk-stack` and to create Kub
```suggestion
To enable bootstrapping, set `global.components.bootstrap` to `true`. It would run [tyk-k8s-bootstrap](https://github.com/TykTechnologies/tyk-k8s-bootstrap) to bootstrap `tyk-control-plane` and to create Kubernetes secrets that can be utilized in Tyk Operator and Tyk Developer Portal.
```

2024-02-19 08:20 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +<summary>Gateway: Enable Leaky Bucket Rate Limiter</summary>
@dcs3spp What do you think?

2024-02-19 08:21 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +You can enable Internal [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by field `tyk-dashboard.tib.enabled` to `true`.
@dcs3spp Is it correct?

2024-02-20 10:32 UTC, dcs3spp reviewed
Thanks for the suggestions @komalsukhani

I think you have raised some good points here and I have added some suggestions for consideration. Let me know if ok and then I will update the PR.

2024-02-20 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +<summary>Gateway: Enable Leaky Bucket Rate Limiter</summary>
@komalsukhani Yes, thanks good point and well spotted! Yes, something like this:

```suggestion
<summary>Gateway: Added support for configuring Leaky Bucket Rate Limiter</summary>
```

2024-02-20 10:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +You can enable Internal [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by field `tyk-dashboard.tib.enabled` to `true`.
Thanks @komalsukhani I have checked the [docs](https://tyk.io/docs/tyk-identity-broker/#what-is-tyk-identity-broker-tib) and they use _internal_ TIB for the scenario when it is embedded within the Tyk Dashboard. I think you have raised a good suggestion and so maybe we could add an explanation to mention that internal means that the TIB instance will be embedded within the Dashboard. Something like this?

```suggestion
You can enable Internal [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by setting field `tyk-dashboard.tib.enabled` to `true`. When enabled, TIB will be embedded within Tyk Dashboard.
```

2024-02-20 11:01 UTC, dcs3spp reviewed
Hi @caroltyk, release notes looking good. I have left some comments and suggestions. I will also review the control plane section that has been added

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +TBC - TT-10903: update gateway and dashboard haskeys values (#208)
Remember to update when confirmed and if confirmed add details

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +For users currently on vX.Y.Z, we strongly recommend promptly upgrading to the latest release. If you are working with an older version (lower major), it is advisable to bypass version X.Y.0 and proc
Update generic statement with version numbers here, i.e. replace X, Y and Z variable placeholders

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-vX.Y.0">}}) below.
Should the ref link be [changelog]({{< ref "#Changelog-vX.Y.0">}})?

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +Tyk Charts 1.3 adds support for a number of new Tyk features available from Tyk 5.3.0 like Leaky Bucket Rate Limiter, and configurations for OAS Validate examples, and OAS Validate Schema defaults.
```suggestion
Tyk Charts 1.3 adds support for a number of new Tyk features available from Tyk 5.3.0. These include: Leaky Bucket Rate Limiter, configurations for OAS Validate examples and OAS Validate Schema defaults.
```

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +Added built-in support for [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) resource for Tyk Gateway.
Add brief explanation in initial changelog to highlight why this support is beneficial to the user, e.g.

_Added built-in support for [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) resource for Tyk Gateway. This will enhance the reliability and availability of your applications, giving you some control over the disruption caused by scaling operations, updates or maintenance on your pods. To enable it, set `gateway.pdb.enabled` to `true` and configure `gateway.pdb.minAvailable` or `gateway.pdb.maxUnavailable`._

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +Allow users to configure worker gateway to work with [Tyk MDCB synchroniser]({{<ref "/product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser">}}) easily by setting `global.mdcbSynchro
```suggestion
Allow users to configure worker gateway to work with [Tyk MDCB synchroniser]({{<ref "product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser">}}) easily by setting `global.mdcbSynchronizer.enabled` in `tyk-data-plane`.
```

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +[Graph Pumps]({{<ref "/tyk-stack/tyk-pump/tyk-pump-configuration/graph-pump">}}) will be added when user add `mongo` or `postgres` to `pump.backend`. When user add `mongo` to `pump.backend`, Graph Mo
```suggestion
[Graph Pumps]({{<ref "tyk-stack/tyk-pump/tyk-pump-configuration/graph-pump">}}) will be added when the user adds `mongo` or `postgres` to `pump.backend`. When `mongo` is added to `pump.backend` the Graph MongoDB Pump will be enabled. When `postgres` is added to `pump.backend` the Graph SQL Pump and Graph SQL Aggregate Pump will be enabled.
```

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +A new [MDCB component chart](https://github.com/TykTechnologies/tyk-charts/tree/main/components/tyk-mdcb) to is added.
```suggestion
A new [MDCB component chart](https://github.com/TykTechnologies/tyk-charts/tree/main/components/tyk-mdcb) has been added to deploy MDCB. 
```

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +A new [Tyk Control Plane umbrella chart](https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-control-plane) to is added.
```suggestion
A new [Tyk Control Plane umbrella chart](https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-control-plane) has been added to deploy Tyk Control Plane. 
```

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +Tyk Charts 1.3.0 uses `mongo-go` as the default driver to connect to MongoDB. `mongo-go` driver is compatible with MongoDB 4.4.x and above. For MongoDB versions prior to 4.4, please change `global.mo
```suggestion
Tyk Charts 1.3.0 uses `mongo-go` as the default driver to connect to MongoDB. `mongo-go` driver is compatible with MongoDB 4.4.x and above. For MongoDB versions prior to 4.4, please change `global.mongo.driver` to `mgo`. We recommend reading [Choose a MongoDB driver]({{<ref "planning-for-production/database-settings/mongodb#choose-a-mongodb-driver">}}) when you need to change driver setting.
```

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +#### Security Fixes
Remove heading if no security fixes

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +##### Comunity Contributions
Remove community contributions heading if no community contributions

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +### API Documentation
Is it worth adding artifact hub link here? If not then we could remove this section heading from the release notes

2024-02-20 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +### Miscellaneous (Optional)
Remove if not needed

2024-02-20 12:28 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +<summary>Gateway: Enable Leaky Bucket Rate Limiter</summary>
Yes. That works.

2024-02-20 12:28 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +You can enable Internal [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by field `tyk-dashboard.tib.enabled` to `true`.
TIB is already embedded in Dashboard. If user enabled the flag, it will be used.

2024-02-20 16:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +Tyk is working to provide a new set of helm charts, and will progressively roll them out at [tyk-charts](https://github.com/TykTechnologies/tyk-charts). It will provide component charts for all Tyk C
Add link to available quick starts here

2024-02-22 13:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-5.3.md
> +<!--
Thanks for adding release note and changelog. Review has been added

2024-02-22 13:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +You can enable Internal [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by field `tyk-dashboard.tib.enabled` to `true`.
```suggestion
Thanks @komalsukhani I have checked the [docs](https://tyk.io/docs/tyk-identity-broker/#what-is-tyk-identity-broker-tib) and they use _internal_ TIB for the scenario when it is embedded within the Tyk Dashboard. I think you have raised a good suggestion and so maybe we could add an explanation to mention that internal means that the TIB instance will be embedded within the Dashboard. Something like this?

@komalsukhani 

Ok, I think we should use internal for consistency with the docs

```suggestion
You can enable Internal [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by setting field `tyk-dashboard.tib.enabled` to `true`.
```
```

2024-02-22 13:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +You can enable Internal [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by field `tyk-dashboard.tib.enabled` to `true`.
Ok thanks @komalsukhani. I think we should keep original use of internal for consistency with the docs. I'll resolve the conversation.

```suggestion
You can enable Internal [Tyk Identity Broker (TIB)]({{<ref "tyk-identity-broker">}}) in Tyk Dashboard by field `tyk-dashboard.tib.enabled` to `true`.
```

2024-02-22 15:05 UTC, dcs3spp reviewed
Thanks @caroltyk, all content files included now and reviewed, including the release notes and control plane chart. I have made commits for minor suggestions and moved the intro heading for what components are included in the charts to after the introduction sentence/paragraph.

I have also removed the legacy tyk stack helm chart page that was previously hidden. It's URL now redirects in this PR to product stack section as shown [here](https://deploy-preview-4076--tyk-docs.netlify.app/docs/nightly/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack/).

Once minor suggestions addressed and peer review approval given from @komalsukhani then we will release.

2024-02-22 15:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +Tyk uses Redis for distributed rate-limiting and token storage. You may use the Bitnami chart or Tyk's `simple-redis` to install chart for POC purpose.
Add a link to Bitnami chart here and Tyk's simple Redis chart

2024-02-22 15:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +but a quick start evaluation only. Use Bitnami Redis or Official Redis Helm chart in any other case.
Add links to Bitnami Redis and Official Redis Helm chart in this paragraph

2024-02-22 15:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +    # connectionStringSecret:
Should this line be uncommented or the description refactored to mention uncomment the section below?

2024-02-22 15:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +```
Maybe add an example of how to refer to this secret after the yaml example

2024-02-22 15:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +       keyName: "redisPassKey"
Should this be _mongoDBPassKey_?

2024-02-22 15:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +       keyName: "redisPassKey"
Should this be _postgrePassKey_?

2024-02-22 15:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +Set version of gateway at `tyk-gateway.gateway.image.tag`. You can find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio). Please check [Tyk Release notes]({{<ref "
Maybe we should add specific link to Docker Gateway tags (https://hub.docker.com/r/tykio/tyk-gateway/tags)
and specific link to Tyk Gateway release notes product-stack/tyk-gateway/release-notes/overview/

2024-02-22 16:21 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +              show: False
Ok thanks @caroltyk I've removed it in this PR

2024-02-26 10:37 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +Added built-in support for [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) resource for Tyk Gateway.
```suggestion
Added built-in support for [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) resource for Tyk Gateway. This will enhance the reliability and availability of your applications, giving you some control over the disruption caused by scaling operations, updates or maintenance on your pods. 
```

2024-02-27 13:26 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +       keyName: "redisPassKey"
good spot. corrected.

2024-02-27 13:26 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +       keyName: "redisPassKey"
good spot. corrected.

2024-02-27 13:54 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +TBC - TT-10903: update gateway and dashboard haskeys values (#208)
Updated at https://github.com/TykTechnologies/tyk-docs/pull/4076/commits/48a4796e21fcf3743af5da45942c3c179b31273b

2024-02-27 14:01 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +For users currently on vX.Y.Z, we strongly recommend promptly upgrading to the latest release. If you are working with an older version (lower major), it is advisable to bypass version X.Y.0 and proc
updated at https://github.com/TykTechnologies/tyk-docs/pull/4076/commits/7400cef11563cb0ed8d4a4b9ac8309c66f1988ae

2024-02-27 14:01 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-vX.Y.0">}}) below.
updated at https://github.com/TykTechnologies/tyk-docs/pull/4076/commits/7400cef11563cb0ed8d4a4b9ac8309c66f1988ae

2024-02-27 14:01 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +#### Security Fixes
updated at https://github.com/TykTechnologies/tyk-docs/pull/4076/commits/7400cef11563cb0ed8d4a4b9ac8309c66f1988ae

2024-02-28 11:23 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/overview.md
> +Tyk is working to provide a new set of helm charts, and will progressively roll them out at [tyk-charts](https://github.com/TykTechnologies/tyk-charts). It will provide component charts for all Tyk C
added

2024-02-28 11:27 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +Tyk uses Redis for distributed rate-limiting and token storage. You may use the Bitnami chart or Tyk's `simple-redis` to install chart for POC purpose.
updated

2024-02-28 11:37 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +but a quick start evaluation only. Use Bitnami Redis or Official Redis Helm chart in any other case.
updated

2024-02-28 11:39 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +    # connectionStringSecret:
@buraksekili can you make the necessary changes in the values.yaml file? Suggest to add instruction to uncomment the line below. Would this take precedence over the above values when uncommented?

2024-02-28 11:44 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +```
updated

2024-02-28 11:50 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +Set version of gateway at `tyk-gateway.gateway.image.tag`. You can find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio). Please check [Tyk Release notes]({{<ref "
updated

2024-02-29 15:52 UTC, dcs3spp reviewed
@caroltyk I have committed and pushed a lot of the suggestions, fixed line breaks and resolved a lot of the conversations.

The following changes requested are unresolved and once updated I think we are ready to release. @komalsukhani Can you peer review also and if your requested changes have been addressed could you approve? 

**Tyk-data-plane-chart**
- Add links to Bitnami Redis and official Redis chart
- Give full example of using helm install —set
- Add an example of secret (foo-secret)
- Add example of how to refer to redisPassKey secret
- Add link to Docker Gateway tags and specific link to Gateway Release Notes like did for control plane  Tyk-oss-chart
- Add link to Bitnami chart and Official Redis Helm Charts
- Add example of how to refer to redisPassKey secret

**Tyk-stack-chart**
- Add example of how to refer to redisPassKey secret
- Intro section explain what the section shows, something like this section explains how to configure the ty-gateway section for updating the Gateway version, enabling TLS, enabling autoscaling etc. etc. Add link to Docker Gateway tags and specific link to Gateway Release Notes like did for control plane

2024-03-01 11:49 UTC, komalsukhani requested changes

2024-03-01 11:49 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +Tyk Charts 1.3 adds support for a number of new Tyk features available from Tyk 5.3.0. These include: Configurations for OAS Validate examples and OAS Validate Schema defaults.
We have also added support of graph pumps.

2024-03-01 11:49 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +Tyk Charts 1.3 adds support for a number of new Tyk features available from Tyk 5.3.0. These include: Configurations for OAS Validate examples and OAS Validate Schema defaults.
If redis TLS PR gets merged, we also need to mention that here.

2024-03-01 11:49 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +Tje Redis password can also be provided via a secret. Store the Redis password in Kubernetes secret and refer to this secret via `global.redis.passSecret.name` and `global.redis.passSecret.keyName` f
```suggestion
The Redis password can also be provided via a secret. Store the Redis password in Kubernetes secret and refer to this secret via `global.redis.passSecret.name` and `global.redis.passSecret.keyName` field, as follows:
```

2024-03-01 11:49 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +- If the `tyk-bootstrap` chart is used to bootstrap the Tyk Dashboard, ensure that it has certificates to send requests to the Tyk Dashboard or enable `insecureSkipVerify` in the `tyk-bootstrap` char
```suggestion
- If the `tyk-bootstrap` chart is used to bootstrap the Tyk Dashboard, ensure that bootstrap app can validate certificate of Tyk Dashboard or enable `insecureSkipVerify` in the `tyk-bootstrap` chart.
```

2024-03-01 11:49 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +The `global.secrets.APISecret` field configures a [header value]({{ref "tyk-oss-gateway/configuration#secret"}}) used in every interaction with Tyk Gateway API.
```suggestion
The `global.secrets.APISecret` field configures a [header value]({{< ref "tyk-oss-gateway/configuration#secret" >}}) used in every interaction with Tyk Gateway API.
```

2024-03-01 11:49 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +*Add Custom Certificates*
```suggestion
*Add Custom CA Certificates*
```

2024-03-01 11:49 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +The `global.secrets.APISecret` field configures a [header value]({{ref "tyk-oss-gateway/configuration#secret"}}) used in every interaction with Tyk Gateway API.
```suggestion
The `global.secrets.APISecret` field configures a [header value]({{< ref "tyk-oss-gateway/configuration#secret" >}}) used in every interaction with Tyk Gateway API.
```

2024-03-08 10:44 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
> +Tyk Charts 1.3 adds support for a number of new Tyk features available from Tyk 5.3.0. These include: Configurations for OAS Validate examples and OAS Validate Schema defaults.
Updated release notes for the TLS change

2024-03-13 09:54 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Tyk uses Redis for distributed rate-limiting and token storage. You may use the Bitnami chart to install or Tyk's `simple-redis` chart for POC purpose.
added

2024-03-13 10:09 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +You can reference the password secret generated by Bitnami chart by  `--set global.redis.passSecret.name=tyk-redis` and `--set global.redis.passSecret.keyName=redis-password`, or just set `global.red
added

2024-03-13 10:09 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Please note that these provided charts must never be used in production or for anything
added

2024-03-13 10:17 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +where `foo-secret` should contain `orgId`, `userApiKey` and `groupID` keys in it.
added

2024-03-13 10:36 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +```
user don't need to refer to the secret. They just need to provide secret name and key name in yaml

2024-03-13 10:38 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +Set version of gateway at `tyk-gateway.gateway.image.tag`. You can find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio). Please check [Tyk Release notes]({{<ref "
updated

2024-03-13 10:38 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +* Kubernetes 1.19+
updated

2024-03-13 10:41 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +`tyk-oss` provides the default deployment of the Tyk Open Source stack. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk P
updated

2024-03-13 10:42 UTC, komalsukhani approved these changes

2024-03-13 10:42 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Tyk uses Redis for distributed rate-limiting and token storage. You may use the Bitnami chart to install or Tyk's `simple-redis` chart for POC purpose.
updated

2024-03-13 10:42 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +but a quick start evaluation only. Use Bitnami Redis or Official Redis Helm chart in any other case.
updated

2024-03-13 10:43 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +```
the yaml configuration is an example of referencing the password

2024-03-13 10:44 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +```
user just need to refer to the secret as shown in the yaml example

2024-03-13 10:44 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Configure below inside `tyk-gateway` section.
updated

2024-03-13 10:46 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +Set version of gateway at `tyk-gateway.gateway.image.tag`. You can find the list of version tags available from [Docker hub](https://hub.docker.com/u/tykio). Please check [Tyk Release notes]({{<ref "
updated

2024-03-13 10:49 UTC, caroltyk commented on tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
> +If you chose to use Helm, you can use Tyk Data Plane helm chart to manage installs of the hybrid gateways and Tyk Pump.
updated

2024-03-13 10:50 UTC, caroltyk commented
> @caroltyk I have committed and pushed all the suggestions, fixed line breaks and been through and resolved a lot of the conversations.
> 
> The following changes requested are unresolved and once updated we can release 🚀
> 
> **Tyk-data-plane-chart**
> 
> * Add links to Bitnami Redis and official Redis chart
> * Give full example of using helm install —set
> * Add an example of secret (foo-secret)
> * Add example of how to refer to redisPassKey secret
> * Add link to Docker Gateway tags and specific link to Gateway Release Notes like did for control plane
> 
> **Tyk-oss-chart**
> 
> * Add link to Bitnami chart and Official Redis Helm Charts
> * Add example of how to refer to redisPassKey secret
> 
> **Tyk-stack-chart**
> 
> * Add example of how to refer to redisPassKey secret
> * Intro section explain what the section shows, something like this section explains how to configure the ty-gateway section for updating the Gateway version, enabling TLS, enabling autoscaling etc. etc.   Add link to Docker Gateway tags and specific link to Gateway Release Notes like did for control plane
> 
> @komalsukhani Can you peer review also and if your requested changes have been addressed could you approve?

Thanks @dcs3spp the requested changes are updated

2024-03-19 12:48 UTC, dcs3spp commented
Thanks @caroltyk, I created the PR to help with setting up the structure so I am unable to approve. Could you take a final look through and if you are happy with structure etc would you be able to approve? Then I will merge and release

2024-03-19 15:44 UTC, caroltyk commented
Thank you @dcs3spp, I have approved the change now. Please wait for the release (same time with 5.3) before publishing.

2024-03-19 15:45 UTC, caroltyk approved these changes

2024-04-05 16:47 UTC, merged

2024-04-05 16:48 UTC, dcs3spp commented
/release to release-5.3

2024-04-30 14:59 UTC, dcs3spp commented
/release to release-5.2

2024-04-30 14:59 UTC, dcs3spp commented
/release to release-5.1