WIP Pump 1.9 release notes
TykTechnologies/tyk-docs-hugo pull request #4079
Opened 2024-02-02 18:23 UTC by n2linux

WIP release notes for Pump 1.9

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-02-05 14:39 UTC, dcs3spp commented
This looks excellent, many thanks @n2linux!!! There is a file named menu.yaml in the data directory. There is a section within it currently containing the Tyk Pump release notes for v1.8.

```yaml
      - title: "Release notes"
        category: Directory
        show: True
        menu:
          - title: "Pump v1.8"
            path: /release-notes/pump-1.8
            category: Page
            show: True
```

To fix the CI check would you be able to rename the pump release 1.9 file (within product-stack section) to pump-1.9 and update this part of the menu.yaml in your fork repo so that it looks similar to that shown below:

```yaml
      - title: "Release notes"
        category: Directory
        show: True
        menu:
          - title: "Pump v1.9"
            path:  /product-stack/tyk-pump/release-notes/pump-1.9
            category: Page
            show: True
          - title: "Pump v1.8"
            path: /release-notes/pump-1.8
            category: Page
            show: True
```

2024-02-06 13:01 UTC, dcs3spp requested changes
Thanks @n2linux for submitting Tyk Pump 1.9 release notes. PR looks good to me, I have made minor suggestions relating to:
- Remember to add release notes and downloads etc. when available
- Add links where and if possible in change-log to new config fields
- Grammar suggestions

I also previously reviewed the config documentation [PR](https://github.com/TykTechnologies/tyk-docs/pull/4066). 

@mativm02 had tagged me in the Pump source repository for the default mongo driver changes. However, the PR also contained additional changes. Could you tag me in the source repository when the changes have been made so that the config can be synchronised to the Tyk docs repository after [review](https://tyktech.slack.com/archives/C51P42LLT/p1707156605682019).

2024-02-06 13:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +MongoDB v4.4 will reach its [end of life support](https://www.mongodb.com/legal/support-policy/lifecycles) at the end February 2024. In order to support newer versions of MongoDB and align with newer
```suggestion
MongoDB v4.4 will reach its [end of life support](https://www.mongodb.com/legal/support-policy/lifecycles) at the end of February 2024. In order to support newer versions of MongoDB and align with newer versions of Tyk, we have changed the default MongoDB driver from [mgo](https://github.com/go-mgo/mgo) to [mongo-go](https://github.com/mongodb/mongo-go-driver). The `mongo-go` driver supports MongoDB versions greater or equal to v4. **If you are using a version of MongoDB less than v4, please [follow this guide](https://github.com/TykTechnologies/tyk-pump#driver-type) to update the driver type to `mgo`.**
```

2024-02-06 13:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +There has been a significant enhancement in Tyk Graph Pump with the removal of the dependency on the `enable_detailed_recording` setting. This change is designed to streamline operations, reduce stor
```suggestion
There has been a significant enhancement in Tyk Graph Pump with the removal of the dependency on the `enable_detailed_recording` setting. This change is designed to streamline operations, reduce storage requirements and enhance overall performance in production environments. By decoupling detailed recording from specific configuration options, Tyk Graph Pump now provides greater flexibility and control over data storage.
```

2024-02-06 13:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +#### Downloads - will change once we do the release
Remember to add this section

2024-02-06 13:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +<summary>Added backoff retry mechanism for Splunk pump</summary>
```suggestion
<summary>Added backoff retry mechanism for Splunk Pump</summary>
```

2024-02-06 13:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +Tyk Pump now has an expotential backoff retry mechanism for sending logs to Splunk. This mechanism mitigates the chance of losing logs if Pump should fail to send logs to Splunk. This fixes a bug whe
```suggestion
Tyk Pump now has an expotential backoff retry mechanism for sending logs to Splunk. This mechanism mitigates the chance of losing logs if Pump should fail to send logs to Splunk. This fixes a bug where Splunk responses were not being checked correctly and fixes a bug where Pump was not closing connections after receiving responses.
```

2024-02-06 13:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +For SQL databases, the GraphQL aggregated analytics record will now have a new `api_value` field so that analytics will be shown in the Dashboard correctly.
@n2linux Is there a link to documentation that can be added for the _api_value_ field?

2024-02-06 13:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +For SQL databases, the GraphQL aggregated analytics record will now have a new `api_value` field so that analytics will be shown in the Dashboard correctly.
@n2linux Should this read:

_For SQL databases, the GraphQL aggregated analytics record will now have a new `api_id` field so that analytics will be shown in the Dashboard correctly._ 

FIXED above

Add a link to documentation for api_id field

2024-02-06 13:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +- Fixed the following CVEs:
Are these CVEs internal or recommended by dependency manager?

2024-02-06 13:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +##### Release Date TDB
Remember to add release date

2024-02-13 10:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +### Support Lifetime
```suggestion
## Support Lifetime
```

2024-02-15 16:29 UTC, dcs3spp commented
@n2linux To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-02-29 11:27 UTC, dcs3spp commented
Awaiting minor suggestions and download links/release date when Pump 1.9 has finished regression

2024-03-21 22:05 UTC, caroltyk requested changes, later dismissed
Looks great @n2linux . Requested changes on some typos.

2024-03-21 22:05 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +| [MongoDB](https://www.mongodb.com/try/download/community)  | 4.4.x, 5.x, 6.x, and 7.0  | 4.4.x, 5.x, 6.x, and 7.0 | Used by Tyk Dashboard |
Please add Redis dependency too

2024-03-21 22:05 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +Our minor releases are supported until our next minor comes out. This would be v1.91 scheduled in Q2 if this goes ahead as planned.
1.9.1

2024-03-21 22:05 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +Pump can now send logs to an Amazon SQS instance. This was a [community contribution](https://github.com/TykTechnologies/tyk-pump/pull/740) co-authored by [masoudhaghbin](https://github.com/masoudhag
do you mean https://github.com/TykTechnologies/tyk-pump#SQS-config?

2024-03-21 22:17 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +</details>
Add this change to change log too?

2024-03-21 22:21 UTC, caroltyk commented
@dcs3spp @n2linux 

Not sure why on [preview](https://deploy-preview-4079--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-pump/release-notes/pump-1.9/) page I saw "Redis 7 Support" is mixed with SQS..

> Redis 7 Support
> Tyk Pump now support Redis v7 utilizing our [storage library v1.2.0](https://github.com/TykTechnologies/storage). Please follow [this guide](https://github.com/asdf) to set up an SQS pump.
>

2024-03-22 18:27 UTC, n2linux commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +| [MongoDB](https://www.mongodb.com/try/download/community)  | 4.4.x, 5.x, 6.x, and 7.0  | 4.4.x, 5.x, 6.x, and 7.0 | Used by Tyk Dashboard |
Done

2024-03-22 18:28 UTC, n2linux commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +Our minor releases are supported until our next minor comes out. This would be v1.91 scheduled in Q2 if this goes ahead as planned.
Fixed

2024-03-22 18:28 UTC, n2linux commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +Pump can now send logs to an Amazon SQS instance. This was a [community contribution](https://github.com/TykTechnologies/tyk-pump/pull/740) co-authored by [masoudhaghbin](https://github.com/masoudhag
Fixed

2024-03-22 18:28 UTC, n2linux commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +</details>
Added to Changed section

2024-03-26 13:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +</details>
@caroltyk @n2linux Thanks for adding in the community contribution change-log item and the security fixes. In the PR preview the headings of the sections are indented

2024-03-26 13:24 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
> +- Fixed the following CVEs:
@nerdydread Security fixes section is indented under changelog section in preview

2024-03-26 14:28 UTC, dcs3spp commented
> @dcs3spp @n2linux
> 
> Not sure why on [preview](https://deploy-preview-4079--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-pump/release-notes/pump-1.9/) page I saw "Redis 7 Support" is mixed with SQS..
> 
> > Redis 7 Support
> > Tyk Pump now support Redis v7 utilizing our [storage library v1.2.0](https://github.com/TykTechnologies/storage). Please follow [this guide](https://github.com/asdf) to set up an SQS pump.

@caroltyk is this fixed now?

2024-03-26 16:32 UTC, dcs3spp commented
@n2linux Thanks for submitting changes earlier. @caroltyk would you be able to review changes made by @n2linux 

I think we are close to having the PR ready for release:
- Awaiting downloads section with links
- Update with release date
- Update with links to docs for new api_id and api_value fields that are detailed in the changelog

2024-04-03 18:59 UTC, letzya commented
@caroltyk @n2linux  Your PR has been inactive without updates or interactions for over 2 weeks. As part of our ongoing housekeeping process to improve our review efficiency and maintain a focused queue, we have closed it. Please note that this action is purely procedural, and you are welcome to reopen your PR at any time when ready to proceed or require further review

2024-04-05 11:58 UTC, dcs3spp approved these changes
PR LGTM

2024-04-05 12:13 UTC, merged

2024-04-30 15:10 UTC, dcs3spp commented
/release to release-5.2

2024-04-30 15:11 UTC, dcs3spp commented
/release to release-5.1