Sync 1.4.3 release notes
TykTechnologies/tyk-docs-hugo pull request #4082
Opened 2024-02-05 13:21 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-02-06 14:16 UTC, dcs3spp requested changes
@caroltyk PR LGTM. Remember to add download for docker image when available.

Are there any dependencies and compatibilities that can be included for Tyk Sync?

Marking as draft until release date and docker image available

2024-02-06 14:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-sync/v1.4.3/images/TBC?context=explore)
Remember to add docker image

2024-02-06 14:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +Tyk Sync supports Tyk API definitions up to Tyk Gateway v5.3.0. Please use this version with Tyk Gateway v5.3.0+.
Do you mean use Tyk Sync 2.4.3+ for v5.3.0?

2024-02-06 14:36 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +Tyk Sync supports Tyk API definitions up to Tyk Gateway v5.3.0. Please use this version with Tyk Gateway v5.3.0+.
Tyk Sync 1.4.3+ will work with Tyk 5.3.0

2024-02-08 14:34 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +Tyk Sync supports Tyk API definitions up to Tyk Gateway v5.3.0. Please use this version with Tyk Gateway v5.3.0+.
Thanks @caroltyk 

Can we say:

```suggestion
Tyk Sync v1.4.3 offers backward compatibility with Tyk API definitions for Gateway versions prior to v5.3.0. Please use Tyk Sync v1.4.3+ for compatibility with Tyk API definitions for Tyk Gateway v5.3.0+.
```

2024-02-14 06:48 UTC, komalsukhani requested changes

2024-02-14 06:48 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +Tyk Sync is currently using the classic Dashboard API endpoints to migrate APIs. OAS API Category is not supported by Tyk Sync yet. Also, the use of [`--allow-unsafe-oas`]({{<ref "/tyk-sync">}}) flag
Users needs to set `allow-unsafe-oas` in Dashboard configuration.

2024-02-14 06:48 UTC, komalsukhani commented
@caroltyk We also fixed CVEs mentioned in this ticket https://tyktech.atlassian.net/browse/TT-11230

2024-02-14 09:32 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +Tyk Sync is currently using the classic Dashboard API endpoints to migrate APIs. OAS API Category is not supported by Tyk Sync yet. Also, the use of [`--allow-unsafe-oas`]({{<ref "/tyk-sync">}}) flag
```suggestion
Tyk Sync is currently using the classic Dashboard API endpoints to migrate APIs. OAS API Category is not supported by Tyk Sync yet. Also, Dashboard configuration [allow-unsafe-oas]({{<ref "/tyk-dashboard/configuration#allow_unsafe_oas">}}) and the use of [`--allow-unsafe-oas`]({{<ref "/tyk-sync">}}) flag in Tyk Sync is required for Tyk Sync to work with OAS API.
```

2024-02-14 09:36 UTC, caroltyk commented
> @caroltyk We also fixed CVEs mentioned in this ticket https://tyktech.atlassian.net/browse/TT-11230

@komalsukhani  
CVE added

2024-02-15 16:35 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-02-29 08:28 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +Tyk Sync is currently using the classic Dashboard API endpoints to migrate APIs. OAS API Category is not supported by Tyk Sync yet. Also, Dashboard configuration [allow-unsafe-oas]({{<ref "/tyk-dashb
```suggestion
Tyk Sync is currently using the classic Dashboard API endpoints to migrate OAS APIs. OAS API Category is not supported by Tyk Sync yet. Also, Dashboard configuration [allow-unsafe-oas]({{<ref "/tyk-dashboard/configuration#allow_unsafe_oas">}}) and the use of [--allow-unsafe-oas]({{<ref "/tyk-sync">}}) flag in Tyk Sync is required for Tyk Sync to work with OAS API.
```

2024-02-29 11:18 UTC, komalsukhani approved these changes

2024-04-03 18:27 UTC, letzya commented
@caroltyk Your PR has been inactive without updates or interactions since Feb 2024. As part of our ongoing housekeeping process to improve our review efficiency and maintain a focused queue, we have closed it. Please note that this action is purely procedural, and you are welcome to reopen your PR at any time when ready to proceed or require further review

2024-04-05 14:36 UTC, letzya commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +
The sentence about category is lost in the crowd and doesn't explain what it actually means.

2024-04-05 14:57 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
> +
@letzya updated wordings there

2024-04-05 16:10 UTC, letzya approved these changes

2024-04-05 16:37 UTC, dcs3spp approved these changes

2024-04-05 16:37 UTC, merged

2024-04-05 16:38 UTC, dcs3spp commented
/release to release-5.3