[DX-1034] Improved Request Validation middleware
TykTechnologies/tyk-docs-hugo pull request #4087
Opened 2024-02-05 16:59 UTC by andyo-tyk

## **User description**
### Preview Link
https://deploy-preview-4087--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/middleware/validate-request-middleware/

### Description
Added documentation of Tyk OAS Validate Request middleware, improved documentation of Tyk Classic Validate JSON middleware

___

## **Type**
documentation

___

## **Description**
- Added detailed documentation for the Request Validation middleware in Tyk Gateway
- Explained the purpose and benefits of using the Request Validation middleware
- Described when to use the Request Validation middleware
- Provided information on how request validation works in Tyk Gateway
- Added documentation for using the Request Validation middleware with Tyk Classic APIs
- Explained how to configure the middleware in the Tyk Classic API Definition
- Provided examples of configuring the middleware using JSON configuration and API Designer
- Added documentation for using the Request Validation middleware with Tyk OAS APIs
- Explained how to configure the middleware in the Tyk OAS API Definition
- Provided examples of configuring the middleware using JSON configuration and API Designer

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>validate-request-middleware.md</strong><dd><code>Improved documentation for Request Validation middleware in Tyk <br>Gateway</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
<li>Added detailed documentation for the Request Validation middleware in <br>Tyk Gateway<br> <li> Explained the purpose and benefits of using the Request Validation <br>middleware<br> <li> Described when to use the Request Validation middleware<br> <li> Provided information on how request validation works in Tyk Gateway

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4087/files#diff-afc0fd2a3134db966761645001fb346ecde5cc4c4b2708c10f0723d3785f54e1">+43/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>validate-request-tyk-classic.md</strong><dd><code>Added documentation for using Request Validation middleware with Tyk <br>Classic APIs</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-classic.md
<li>Added documentation for using the Request Validation middleware with <br>Tyk Classic APIs<br> <li> Explained how to configure the middleware in the Tyk Classic API <br>Definition<br> <li> Provided examples of configuring the middleware using JSON <br>configuration and API Designer

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4087/files#diff-85a21e28427868bbcdadddcecbf9e701f31c5df4434542233e7f81d84fcb5c5e">+79/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>validate-request-tyk-oas.md</strong><dd><code>Added documentation for using Request Validation middleware with Tyk <br>OAS APIs</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
<li>Added documentation for using the Request Validation middleware with <br>Tyk OAS APIs<br> <li> Explained how to configure the middleware in the Tyk OAS API <br>Definition<br> <li> Provided examples of configuring the middleware using JSON <br>configuration and API Designer

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4087/files#diff-a1293fab5ca25d551b1e27b05df28df73dc208715b7579bca919821a80cfe948">+139/-0</a>&nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table><hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `describe` tool scans the PR code changes, and generates a description for the PR - title, type, summary, walkthrough and labels. The tool can be triggered [automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) every time a new PR is opened, or can be invoked manually by commenting on a PR.

When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L46) related to the describe tool (`pr_description` section), use the following template:
```
/describe --pr_description.some_config1=... --pr_description.some_config2=...
```
With a [configuration file](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-app), use the following template:
```
[pr_description]
some_config1=...
some_config2=...
```

<table><tr><td><details> <summary><strong> Enabling\disabling automation </strong></summary><hr>

- When you first install the app, the [default mode](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) for the describe tool is:
```
pr_commands = ["/describe --pr_description.add_original_user_description=true" 
                         "--pr_description.keep_original_user_title=true", ...]
```
meaning the `describe` tool will run automatically on every PR, will keep the original title, and will add the original user description above the generated description. 

- Markers are an alternative way to control the generated description, to give maximal control to the user. If you set:
```
pr_commands = ["/describe --pr_description.use_description_markers=true", ...]
```
the tool will replace every marker of the form `pr_agent:marker_name` in the PR description with the relevant content, where `marker_name` is one of the following:
  - `type`: the PR type.
  - `summary`: the PR summary.
  - `walkthrough`: the PR walkthrough.

Note that when markers are enabled, if the original PR description does not contain any markers, the tool will not alter the description at all.
        

</details></td></tr>

<tr><td><details> <summary><strong> Custom labels </strong></summary><hr>

The default labels of the `describe` tool are quite generic: [`Bug fix`, `Tests`, `Enhancement`, `Documentation`, `Other`].

If you specify [custom labels](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md#handle-custom-labels-from-the-repos-labels-page-gem) in the repo's labels page or via configuration file, you can get tailored labels for your use cases.
Examples for custom labels:
- `Main topic:performance` - pr_agent:The main topic of this PR is performance
- `New endpoint` - pr_agent:A new endpoint was added in this PR
- `SQL query` - pr_agent:A new SQL query was added in this PR
- `Dockerfile changes` - pr_agent:The PR contains changes in the Dockerfile
- ...

The list above is eclectic, and aims to give an idea of different possibilities. Define custom labels that are relevant for your repo and use cases.
Note that Labels are not mutually exclusive, so you can add multiple label categories.
Make sure to provide proper title, and a detailed and well-phrased description for each label, so the tool will know when to suggest it.        

</details></td></tr>

<tr><td><details> <summary><strong> Inline File Walkthrough 💎</strong></summary><hr>

For enhanced user experience, the `describe` tool can add file summaries directly to the "Files changed" tab in the PR page.
This will enable you to quickly understand the changes in each file, while reviewing the code changes (diffs).

To enable inline file summary, set `pr_description.inline_file_summary` in the configuration file, possible values are:
- `'table'`: File changes walkthrough table will be displayed on the top of the "Files changed" tab, in addition to the "Conversation" tab.
- `true`: A collapsable file comment with changes title and a changes summary for each file in the PR.
- `false` (default): File changes walkthrough will be added only to the "Conversation" tab.
<tr><td><details> <summary><strong> Utilizing extra instr [...]

2024-02-06 15:19 UTC, dcs3spp requested changes
PR LGTM, detailed with examples. Made minor suggestions and remember to add images and video and arrange peer review.

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +Requests to your upstream services should meet the contract that you have defined for those APIs. Checking the content and format of incoming requests before they are passed to the upstream APIs can
```suggestion
Requests to your upstream services should meet the contract that you have defined for those APIs. Checking the content and format of incoming requests before they are passed to the upstream APIs can avoid unexpected errors and provide additional security to those services. Tyk's request validation middleware provides a way to validate the presence, correctness and conformity of HTTP requests to make sure they meet the expected format required by the upstream API endpoints.
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +Request validation enables cleaner backend APIs, better standardisation across consumers, easier API evolution, and reduced failure risk leading to higher end-to-end reliability.
```suggestion
Request validation enables cleaner backend APIs, better standardisation across consumers, easier API evolution and reduced failure risk leading to higher end-to-end reliability.
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +Validating incoming requests against a defined schema protects services from unintended consequences arising from bad input, such as SQL injection or buffer overflow errors, or other unintended failu
```suggestion
Validating incoming requests against a defined schema protects services from unintended consequences arising from bad input, such as SQL injection or buffer overflow errors, or other unintended failures caused by missing parameters or invalid data types. Offloading this security check to the API Gateway provides an early line of defence as potentially bad requests are not proxied to your upstream services.
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +You can ensure that client requests adhere to a defined contract specifying mandatory headers or parameters before sending requests upstream. Performing these validation checks in the API gateway all
```suggestion
You can ensure that client requests adhere to a defined contract specifying mandatory headers or parameters before sending requests upstream. Performing these validation checks in the API Gateway allows API developers to focus on core domain logic.
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +The incoming request is compared with a defined schema, which is a structured description of the expected format for requests to the endpoint. This request schema defines the required and optional el
```suggestion
The incoming request is compared with a defined schema, which is a structured description of the expected format for requests to the endpoint. This request schema defines the required and optional elements such as headers, path/query parameters, payloads and their data types. It acts as a contract for clients.
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +If the incoming request does not match the schema, it will be rejected with an `HTTP 422 Unprocessable Entity` error. This error code can be customised if required.
Is there a link that can be added for how to customise the error code?

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-classic.md
> +The [request validation]({{< ref "product-stack/tyk-gateway/middleware/validate-request-middleware" >}}) middleware provides a way to validate the presence, correctness, and conformity of HTTP reques
```suggestion
The [request validation]({{< ref "product-stack/tyk-gateway/middleware/validate-request-middleware" >}}) middleware provides a way to validate the presence, correctness and conformity of HTTP requests to make sure they meet the expected format required by the upstream API endpoints.
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +The [request validation]({{< ref "product-stack/tyk-gateway/middleware/validate-request-middleware" >}}) middleware provides a way to validate the presence, correctness, and conformity of HTTP reques
```suggestion
The [request validation]({{< ref "product-stack/tyk-gateway/middleware/validate-request-middleware" >}}) middleware provides a way to validate the presence, correctness and conformity of HTTP requests to make sure they meet the expected format required by the upstream API endpoints.
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +Tyk's request validation middleware automatically parses the schema for the request in the OpenAPI description part of the Tyk OAS API Definition and use this to compare against the incoming request.
```suggestion
Tyk's request validation middleware automatically parses the schema for the request in the OpenAPI description part of the Tyk OAS API Definition and uses this to compare against the incoming request.
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +The `parameters` field in the OpenAPI description is an array of `parameter objects` that each describe one parameter shared by all operations on that path (where an operation is a combination of HTT
```suggestion
The `parameters` field in the OpenAPI description is an array of `parameter objects` that each describe one parameter shared by all operations on that path. Here, an operation is defined as a combination of HTTP method and path, or, as Tyk calls it, an endpoint. Each `parameter` has two mandatory fields:
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +The `requestBody` field in the OpenAPI description is a [Request Body Object](https://swagger.io/docs/specification/describing-request-body/). This has two optional fields (`description` and `require
```suggestion
The `requestBody` field in the OpenAPI description is a [Request Body Object](https://swagger.io/docs/specification/describing-request-body/). This has two optional fields (`description` and `required`) plus the `content` section which allows you to define a schema for the expected payload. Different schemas can be declared for different media types that are identified by content-type (e.g. `application/json`, `application/xml` and `text/plain`).
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +When [importing]({{< ref "getting-started/using-oas-definitions/import-an-oas-api#tutorial-5-create-an-api-that-validates-the-request-payload" >}}) an OpenAPI Document to create a Tyk OAS API, you ca
What is the name of the option on the API Designer import screen?

```suggestion
When [importing]({{< ref "getting-started/using-oas-definitions/import-an-oas-api#tutorial-5-create-an-api-that-validates-the-request-payload" >}}) an OpenAPI Document to create a Tyk OAS API, you can automatically enable the request validation middleware for all endpoints in the Document that have defined schemas. If you are using the Tyk Dashboard API or Tyk Gateway API then you can do this by setting the `validateRequest=true` query parameter. Alternatively, if you are using the API Designer, select the option on the import screen.
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +The request validation middleware (`validateRequest`) can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appropriate `opera
Does this part _(as configured in the `paths` section of your OpenAPI Document)._ mean:

```suggestion
The request validation middleware (`validateRequest`) can be added to the `operations` section of the Tyk OAS Extension (`x-tyk-api-gateway`) in your Tyk OAS API Definition for the appropriate `operationId`. The `operationId` for an endpoint can be found within the `paths` section of your [OpenAPI specification](https://swagger.io/docs/specification/paths-and-operations/?sbsearch=operationIds).
```

2024-02-06 15:19 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-02-15 16:37 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-03-19 12:09 UTC, dcs3spp commented
@andyo-tyk I have resolved most review comments. Comments remain relate to[ adding link for how to resolve error code ](https://github.com/TykTechnologies/tyk-docs/pull/4087#discussion_r1479944939)and adding placeholder video

2024-03-19 12:11 UTC, dcs3spp commented
Re-closing PR. Commits can still be added and pushed up to the branch. Once changes have been pushed up to the branch, re-open the PR and then request follow up review

2024-03-24 14:23 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +If the incoming request does not match the schema, it will be rejected with an `HTTP 422 Unprocessable Entity` error. This error code can be customised if required.
That's part of the middleware config - it's explained in the respective Tyk Classic and Tyk OAS pages. No need for a link here, in the same way that we don't need a specific link for how you define the validation schema.

2024-03-25 16:33 UTC, dcs3spp requested changes
Thanks @andyo-tyk PR LGTM. Minor suggestion and one of the internal section links is broken. Once fixed and peer approved, I think this can be merged. I had another PR open to remove the hidden Request Validation page (/getting-started/key-concepts/request-validation).

2024-03-25 16:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +OpenAPI schema can reference other schemas defined elsewhere letting you write complex validations very efficiently since you don’t need to re-define the validation for a particular object every time
```suggestion
An OpenAPI schema can reference other schemas defined elsewhere ,letting you write complex validations very efficiently since you don’t need to re-define the validation for a particular object every time you wish to refer to it. Currently, Tyk only supports local references to schemas within the same API Definition.
```

2024-03-25 16:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +When you create a Tyk OAS API by importing your OpenAPI description, you can instruct Tyk to enable request validation [automatically](#automatically-enabling-the-request-validation-middleware) for a
Is the manually enable link correct?

2024-03-25 16:41 UTC, lghiur approved these changes

2024-03-25 16:41 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +When using the legacy [Tyk Classic APIs]({{< ref "product-stack/tyk-gateway/middleware/validate-request-tyk-classic" >}}), request validation is performed by the `Validate JSON` middleware which can
worth mentioning that this works only agains request body schema

2024-03-25 16:41 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +OpenAPI schema can reference other schemas defined elsewhere letting you write complex validations very efficiently since you don’t need to re-define the validation for a particular object every time
@andyo-tyk I think it's worth mentioning, that it can reference schemas defined elsewhere within the same documente. (as it can be external as well)

2024-03-25 17:27 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +When you create a Tyk OAS API by importing your OpenAPI description, you can instruct Tyk to enable request validation [automatically](#automatically-enabling-the-request-validation-middleware) for a
```suggestion
When you create a Tyk OAS API by importing your OpenAPI description, you can instruct Tyk to enable request validation [automatically](#automatically-enabling-the-request-validation-middleware) for all endpoints with defined schemas. If you are creating your API without import, or if you only want to enable request validation for some endpoints, you can [manually enable](#manually-enabling-the-request-validation-middleware) the middleware in the Tyk OAS API definition.
```

2024-03-25 17:34 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +When using the legacy [Tyk Classic APIs]({{< ref "product-stack/tyk-gateway/middleware/validate-request-tyk-classic" >}}), request validation is performed by the `Validate JSON` middleware which can
Validate JSON only works against request body - that's inclued in line 32.
Validate Request works against body and param schema - that's in line 30.
Did I miss something?

2024-03-26 06:13 UTC, lghiur approved these changes

2024-03-26 06:13 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
> +When using the legacy [Tyk Classic APIs]({{< ref "product-stack/tyk-gateway/middleware/validate-request-tyk-classic" >}}), request validation is performed by the `Validate JSON` middleware which can
all good, thanks

2024-03-26 09:37 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
> +OpenAPI schema can reference other schemas defined elsewhere letting you write complex validations very efficiently since you don’t need to re-define the validation for a particular object every time
```suggestion
An OpenAPI schema can reference other schemas defined elsewhere, letting you write complex validations very efficiently since you don’t need to re-define the validation for a particular object every time you wish to refer to it. Tyk only supports local references to schemas (within the same OpenAPI document).
```

2024-03-26 11:56 UTC, closed without merging

2024-03-26 11:56 UTC, dcs3spp commented
@andyo-tyk Closing PR and recreated to fix merge conflicts in this PR https://github.com/TykTechnologies/tyk-docs/pull/4330