[DX-1047] Add template structure for Go Plugins
TykTechnologies/tyk-docs-hugo pull request #4102
Opened 2024-02-07 17:44 UTC by dcs3spp

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

[DX-1047](https://tyktech.atlassian.net/browse/DX-1047)
---

### Preview Link

<br>

### Description

<br>

[preview](https://deploy-preview-4101--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/go-plugins/self-managed-deb)

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

[DX-1047]: https://tyktech.atlassian.net/browse/DX-1047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-02-15 16:40 UTC, dcs3spp commented
@allaneyles To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-03-01 18:00 UTC, dcs3spp reviewed
Hi @Monica-Cedeno I have had a read through self-managed-rpm section and content looks good! Review comments so far:

Is there some steps missing in bundling the plugins section:
- Upload the plugin bundle to a webserver
- [Configure Gateway](https://tyk.io/docs/plugins/how-to-serve-plugins/plugin-bundles/#global-parameters) to download plugins from the webserver
- Add the plugin bundle filename (e.g. my-plugin-bundle.zip)  as the ID in the Advanced options for an API in the Dashboard screen

Is the content the same for the _custom-plugins upgrade guide_ and the _upgrade strategy_ guide in self-managed-deb and self-managed-rpm?

For command terminal / shell code formatting examples use _bash_, e.g:

```suggestion
```bash
go get github.com/TykTechnologies/tyk@ffa83a27d3bf793aa27e5f6e4c7106106286699d
# In Gateway version 5.1, the Gateway and plugins transitioned to using Go modules builds and don’t use Go mod vendor anymore
go mod tidy
```
```

For JSON examples use _json_, e.g.:

```suggestion
```json
{
    "key": "value"
}
```
```

2024-03-06 05:18 UTC, Fadzli-fast commented
Hey @dcs3spp, allow to explain some parts from the guide

**Self-Managed RPM & DEB Guides
What is the action of the target package version step in the guide?** 

- This section is for users to identify the version that they are upgrading into after their initial discussion on which versions to upgrade to. Eg, the customer has decided to upgrade to version 5.2.5, isit available for their specific OS Rhel(el/7, el/8) or Ubuntu focal, bionic etc. 

**Images of building bundles, available versions of Tyk components are difficult to read**

- Will it be better removed? as its quite straight forward? This images are usually requested by APAC customers. eg Do you have an example of how it looks like?

**Upgrade Strategy
What is the deployment document that you wish to link to?**

- I believe its supposed to point to the [deployment page](https://tyk.io/docs/getting-started/installation/)

**Self-Managed Custom Go Plugins
Should the bundling guide be included for each go plugin initialisation sections rather than just the section for versions > 5.1?**

This is on assumption **IF** you are using bundles to ship your plugins, to avoid confusion I feel its better if the [bundling section ](https://tyk.io/docs/plugins/how-to-serve-plugins/plugin-bundles/#global-parameters) is added into the guide rather then creating a bunch of different instructions? eg **If you are using bundles to ship your plugins refer to link**

2024-03-06 17:22 UTC, dcs3spp reviewed
Many thanks @Fadzli-fast for answering the review questions!!!

I have created this [child PR](https://github.com/TykTechnologies/tyk-docs/pull/4195) based with new structure for merging into the original PR. I also removed the plugin bundles section from self-managed guides and replaced with link to existing documentation. @Fadzli-fast @Monica-Cedeno @nerdydread could you please **review** and if ok **approve** it so that I can merge it into the original DX-1047 PR?

The remainder of DX review summary is:

**Self-Managed Custom Go Plugins**
- Section headings do not match up with the version range in the table

**Pre-upgrade checks**
- For this line "Is the targeted version available on packagecloud.io or the intended version" Should it read "is the targeted version available on packagecloud.io or in local package repository?" 

**Self Managed RPM**
- A new image is required for available versions of Tyk components. Existing [image](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/go-plugins/self-managed-rpm/#check-upgradable-packages) is difficult to read.

**Self Managed Hybrid** 
- Thanks for uploading, the self managed hybrid guide is now available for me to review.

**Cloud Saas**
- Add supporting images to the guide
- Does the Go Plugins table match the section headings?
- Add link to guide for how to upgrade the Tyk Data Plane (Gateway)

2024-03-07 06:21 UTC, nerdydread commented
@dcs3spp Thank you for the feedback, changes have been applied in the following [commit](https://github.com/TykTechnologies/tyk-docs/commit/5a513cc8f27fe5dfbfeba92ec72d3adceef971b8).
> **Cloud Saas**
> 
>     * Add supporting images to the guide
> 
>     * Does the Go Plugins table match the section headings?
> 
>     * Is there a guide that can link to for how to upgrade the Tyk Data Plane (Gateway)
> 

- Added images for showing an example of a bundle’s contents.
- The table and section headings have been updated to match.  
- Removed the steps and linked to the existing guide for upgrading the Tyk Data Plane.  Added links to other existing docs for certain steps as some things were already well documented and this would cut down on the amount of duplication.

2024-03-12 15:07 UTC, dcs3spp commented
@allaneyles @Fadzli-fast @Monica-Cedeno @nerdydread I have reviewed the Hybrid upgrade guide and also updated the Hybrid and Cloud SaaS guides for formatting, added links and sub-section headings. In the Hybrid Gateway document I have also updated the definition of hybrid Gateway so that it relates to MongoDB or PostgreSQL.

The following is a summary of the DX review and a peer review should also be performed before this is released.

[**Self-Managed Custom Go Plugins**](http://localhost:1313/docs/nightly/developer-support/upgrading-tyk/self-managed/go-plugins/)
- Section headings do not match up with the version range in the table

[**Self Managed RPM**](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/self-managed/linux-distributions/self-managed-rpm/)
- A new image is required for available versions of Tyk components. Existing [image](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/go-plugins/self-managed-rpm/#check-upgradable-packages) is difficult to read.

[**Hybrid** - Moved into cloud section](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/hybrid/)
- Is definition of hybrid correct? Is hybrid also where client hosts a Gateway in 3rd party cloud provider or on their own server?
- Should the plugins be updated on the Management Gateway also?
- Go plugins section has image of plugin bundle files with year of 1979
- Go plugins section step 5 image needed for path 1 & path 3 to match version of upgrade represented by section heading
- Path 1 & Path 3 manifest.json file example does not contain both plugin .so files but path 2 does, why? Should this be updated for paths 1 & 3 to include both plugin .so files?
- Path 3 of Go Plugins: Are steps 7 & 10 duplicated?
- Go Plugins: Steps 7, 8, 9 & 10 are in different order across upgrade paths. Update with correct consistent recommended ordering.
- In Go plugins path 1 - 3 should the link for upgrading Hybrid Gateway(s) refer to this [section](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/hybrid/#3-upgrade-your-data-plane-hybrid-gateways)? I have added this as part of refactoring.
- Update Go plugin path section headings to match table, similar to Cloud SaaS.

[**Cloud Saas**](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/cloud-saas/)
- Go plugins section has image of plugin bundle files with year of 1979
- Go plugins section step 5 image needed for path 1 & path 3 to match version of upgrade represented by section heading
- Path 1 & Path 3 manifest.json file example does not contain both plugin .so files. Should this be updated for paths 1 & 3 to include both plugin .so files?
- Steps 7, 8 & 9 are in different order of Go plugins for [Paths 1 - 3](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/cloud-saas/#path-1) Should they be the same order?
- In go plugins paths 1-3 add a link for the step that involves upgrading to the Cloud Data Plane. Should it link to this [section](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/cloud-saas/#upgrading-cloud-data-planes)? I have added the link and double checking for code review
- Path 3 (Upgrade From Current Version >= 4.1.0 To Target Version >= 5.1.0) gives an example for upgrading to _Target Version > v4.20 and < v5.1.0_. Should this example be removed since it does not match the scenario represented by the path 3 section heading?

Are the Go plugins steps the same for Hybrid and Cloud Saas, or is it safer to have them as separate?

2024-03-13 05:14 UTC, Fadzli-fast commented
Hey @dcs3spp,

I have updated the ones below

```
[Self-Managed Custom Go Plugins](http://localhost:1313/docs/nightly/developer-support/upgrading-tyk/self-managed/go-plugins/)

Section headings do not match up with the version range in the table
```

Already changed it to be consistent with the other guides to avoid confusion.

```
[Self Managed RPM](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/self-managed/linux-distributions/self-managed-rpm/)

A new image is required for available versions of Tyk components. Existing [image](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/go-plugins/self-managed-rpm/#check-upgradable-packages) is difficult to read.
```

I have changed the screenshots to be more easier to read focusing on the example printout of the command.

Also made some change under databases with a [note](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/self-managed/linux-distributions/self-managed-rpm/#databases) stating that we dont own them and this a guide only.

Also removed screenshots for mongo restore as it wasnt helpful plus its hard to see.

2024-03-14 17:29 UTC, dcs3spp commented
Thanks @Fadzli-fast Images look much better in the linux Debian & Redhat section. I like the idea of adding the  note in databases backup!!!

2024-03-14 17:31 UTC, dcs3spp commented
@allaneyles @Fadzli-fast @Monica-Cedeno @nerdydread [Feedback](https://github.com/TykTechnologies/tyk-docs/pull/4102#issuecomment-1991875347) remaining is Hybrid & Cloud Saas

2024-03-20 17:27 UTC, nerdydread commented
Hey @dcs3spp I've made the following updates based on your feedback:
  
[Hybrid - Moved into cloud sub-menu](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/hybrid/)
- Is definition of hybrid correct? Is hybrid also where client hosts a Gateway in 3rd party cloud provider or on their own server?
I was copying/pasting between the SaaS and Hybrid document as they’re similar and missed some of the updates in my first pass.  This has been updated accordingly.
- Should the plugins be updated on the Management Gateway also?
No, the plugins aren’t needed on the Management Gateway as this Gateway doesn’t proxy any API traffic.
- Go plugins section has image of plugin bundle files with year of 1979
This is a result of the zip utility I used, it stripped the data modified value.  I’ve gone back and modified the Date Modified for each of the images so as to not be a source of confusion.  
- Go plugins section step 5 image needed for path 1 & path 3 to match version of upgrade represented by section heading
Updated this accordingly.
- Path 1 & Path 3 manifest.json file example does not contain both plugin .so files but path 2 does, why? Should this be updated for paths 1 & 3 to include both plugin .so files?
We introduced our [Go Plugin Loader](https://tyk.io/docs/product-stack/tyk-gateway/release-notes/version-4.1/#go-plugin-loader) functionality in 4.1.0 that allowed users to include multiple versions of a given plugin in the same bundle and the Gateway would then select the appropriate version to load.  This allows for users to include their target version and current version plugin in the same bundle package prior to upgrading so that post-upgrade, the Gateway can pull the appropriate version automatically.  For Path 1 (< 4.1.0), you have to upgrade the Gateway then load the target version plugin.   For Paths 2 and 3, the target version plugin can be bundled and pulled down by the Gateway prior to upgrading.  Path 3 has been updated to  include both .so files.
- Path 3 of Go Plugins: Are steps 7 & 10 duplicated?
This has been updated to be more clear.
- Go Plugins: Steps 7, 8, 9 & 10 are in diff. erent order across upgrade paths. Update with correct consistent recommended ordering.
Updated accordingly, the Go Plugin Loader functionality introduced in v4.1.0 is why the steps are different between Path 1 and Paths 2-3.
- In Go plugins path 1 - 3 should the link for upgrading Hybrid Gateway(s) refer to this[ section](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/hybrid/#3-upgrade-your-data-plane-hybrid-gateways)? I have added this as part of refactoring.
Yes this should link to the existing documentation on upgrading Cloud Control Planes.  This has been updated.
- Update Go plugin path section headings to match table, similar to Cloud SaaS.
This has been updated.

[Cloud Saas](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/cloud-saas/)
- Go plugins section has image of plugin bundle files with year of 1979
This has been updated as the zip utility I used at the time stripped the Date Modified attribute.
- Go plugins section step 5 image needed for path 1 & path 3 to match version of upgrade represented by section heading
This has been updated accordingly for each path.
- Path 1 & Path 3 manifest.json file example does not contain both plugin .so files. Should this be updated for paths 1 & 3 to include both plugin .so files?
Same answer as the Hybrid section above.   
- Steps 7, 8 & 9 are in different order of Go plugins for[ Paths 1 - 3](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/cloud-saas/#path-1) Should they be the same order?
Updated accordingly, the Go Plugin Loader functionality introduced in v4.1.0 is why the steps are different between Path 1 and Paths 2/3.
- In go plugins paths 1-3 add a link for the step that involves upgrading to the Cloud Data Plane. Should it link to this[ section](https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/cloud/cloud-saas/#upgrading-cloud-data-planes)? I have added the link and double checking for code review
Yes this should link to the existing documentation on upgrading Cloud Control Planes.  This has been updated.
- Path 3 (Upgrade From Current Version >= 4.1.0 To Target Version >= 5.1.0) gives an example for upgrading to Target Version > v4.20 and < v5.1.0. Should this example be removed since it does not match the scenario represented by the path 3 section heading?
This has been removed.
- Are the Go plugins steps the same for Hybrid and Cloud Saas, or is it safer to have them as separate?
They’re nearly identical, the only difference really is that SaaS deployments will use an S3 Bucket for plugin bundles while Hybrid deployments will use a file server.

2024-03-27 09:37 UTC, allaneyles approved these changes

2024-04-02 19:33 UTC, letzya commented
about cloud saas >=5.1.0 - we should check if this works with 5.3 and get confirmation for it @andyo-tyk

2024-04-15 15:14 UTC, letzya commented on tyk-docs/content/upgrading-tyk.md
> +- [Linux](#linux)
can we put the above in the same order of the content below?

2024-04-15 15:20 UTC, letzya requested changes
per my comment below the current upgrading tyk guide needs to be looked at. Currently it feels like it's disconnected from the new content.

2024-04-15 15:20 UTC, letzya commented on tyk-docs/content/upgrading-tyk.md
> -### Other installation choices
Where is this content? what is the purpose of this page? if it's an overview, shouldn't we have links to the content that was moved out of this page to another place?

Why did we leave k8s, help and docker but took out the rest?

2024-06-10 20:41 UTC, letzya commented on tyk-docs/content/upgrading-tyk.md
>  All our components adhere to a few common standards:
```suggestion
## Upgrade standards and recommendations
All our components adhere to a few common standards:
```

2024-06-10 20:56 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/upgrade-strategy.md
> +tags: ["Upgrade Strategy" ]
```suggestion
tags: ["Upgrade Strategy", "Upgrading Tyk options" ]
```

2024-06-10 20:58 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/upgrade-prerequisites.md
> +Consult our [upgrade strategy]({{< ref "developer-support/upgrading-tyk/upgrade-strategy" >}}) guidelines to help you decide between a [Rolling]({{< ref "developer-support/upgrading-tyk/upgrade-strat
```suggestion
Review our [upgrade strategy guidelines]({{< ref "developer-support/upgrading-tyk/upgrade-strategy" >}}) to decide between a [Rolling]({{< ref "developer-support/upgrading-tyk/upgrade-strategy#rolling-upgrade" >}}) or [Blue-Green]({{< ref "developer-support/upgrading-tyk/upgrade-strategy#blue-green" >}}) upgrade.
```

2024-06-10 21:00 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/upgrade-prerequisites.md
> +| Tyk Cloud        | [Cloud SaaS]({{< ref "developer-support/upgrading-tyk/cloud/cloud-saas" >}}) | Guide for Tyk Cloud SaaS (Software As A Service) |
@dcs3spp Not sure I don't get this. Why we have only linux here? where's docker and k8s?

2024-06-10 21:04 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
> +After reviewing your [upgrade pre-requisites]({{< ref "developer-support/upgrading-tyk/upgrade-prerequisites" >}}),
why pre-requisites and not prerequisites?

2024-06-10 21:06 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/upgrade-prerequisites.md
> +title: "Upgrade Pre-Requisites"
it's is read more as "Pre Upgrade Considerations" than "Upgrade Pre-Requisites" to me. What do you think

2024-06-10 21:10 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
> +## 1. Upgrade your Control Plane
@dcs3spp why do we repeat it hee if it was written in the saas

2024-06-10 21:13 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
> + | [1](#path-1)    | < 4.1.0         | < 4.1.0        |
```suggestion
 | [Path 1](#path-1)    | < 4.1.0         | < 4.1.0        |
```

2024-06-10 21:13 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
> + | [2](#path-2)    | < 4.1.0         | \>= 4.1.0      |
```suggestion
 | [Path 2](#path-2)    | < 4.1.0         | \>= 4.1.0      |
```

2024-06-10 21:13 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
> + | [3](#path-3)    | \>= 4.1.0       | \>=5.1.0       |
```suggestion
 | [Path 3](#path-3)    | \>= 4.1.0       | \>=5.1.0       |
```

2024-06-10 21:30 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/cloud-saas.md
> +3. Download the plugin compiler for the target version you’re upgrading to (e.g. 4.0.9).  See the Tyk Docker Hub [repo](https://hub.docker.com/r/tykio/tyk-plugin-compiler) for available versions.
```suggestion
3. Download the plugin compiler for the target version you’re upgrading to (e.g. 4.0.9).  See the Tyk Docker Hub [repo](https://hub.docker.com/r/tykio/tyk-plugin-compiler/tags) for available versions. 
```

2024-06-10 21:31 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/cloud-saas.md
> +3. Download the plugin compiler for the target version you’re upgrading to (e.g. 4.0.9).  See the Tyk Docker Hub [repo](https://hub.docker.com/r/tykio/tyk-plugin-compiler) for available versions.
```suggestion
3. Download the plugin compiler for the target version you’re upgrading to (e.g. for v5.3 `docker pull tykio/tyk-plugin-compiler:v5.3`).  See the Tyk Docker Hub [repo](https://hub.docker.com/r/tykio/tyk-plugin-compiler) for available versions. 
```

2024-06-10 21:45 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/cloud-saas.md
> +4. [Compile]({{< ref "plugins/supported-languages/golang#building-the-plugin">}}) your plugin using this compiler
@dcs3spp can we give a better link? more direct to the compile command?

2024-06-10 21:47 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/cloud-saas.md
> +Please refer to our supporting [video](https://tyk-1.wistia.com/medias/t0oamm63ae) below for further guidance.
is it "further guidance" ?

2024-06-10 21:51 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/cloud-saas.md
> +Please refer to our supporting [video](https://tyk-1.wistia.com/medias/t0oamm63ae) below for further guidance.
```suggestion
Please refer to our [upgrade guide video](https://tyk-1.wistia.com/medias/t0oamm63ae) below for visual guidance:
```

2024-06-10 21:55 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/cloud-saas.md
> +8. Validate that your plugin is working per your expectations as at this stage, your Gateway will be running the plugin for your current version still.
```suggestion
8. Ensure that your plugin is functioning as expected, as at this stage, your Gateway will still be running the plugin for the current version.
```

2024-06-10 21:57 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
> +- MDCB
Why don't we call it "control plane"?

2024-06-10 21:59 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
> +## 2. Upgrade your Go Plugins
@dcs3spp we need to underatand from Travis why this info is repeated in saas and hybrid. Do we have to have duplicated content?

2024-06-10 22:03 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
> +- **Docker**
now we have this section and also this page https://deploy-preview-4102--tyk-docs.netlify.app/docs/nightly/developer-support/upgrading-tyk/other-upgrade-options/docker/ - they essentially do the same thing. Can you please improve this to avoid dup of content?

2024-06-10 22:09 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/self-managed/linux-distributions/self-managed-deb.md
> +1. Tyk Gateway
@dcs3spp The order here is not consistent with the order we currently have in our docs.

2024-06-10 22:11 UTC, letzya requested changes
@dcs3spp Added a few comments. Also the order of the upgrade in self managed is not consistent. 
Could you kindly check why and re-review the whole content in holistic way to make sure the rest is consistent, the guide is flowing and the navigation makes sense (currently it needs work)

2024-06-14 15:06 UTC, Monica-Cedeno commented
this looks great. Thanks @letzya and @dcs3spp

2024-06-14 17:33 UTC, letzya commented on tyk-docs/data/menu.yaml
> +            - title: "Upgrade Tyk On Debian"
```suggestion
            - title: "Debian"
```

2024-06-14 17:34 UTC, letzya commented on tyk-docs/data/menu.yaml
> +            - title: "Upgrade Tyk On Redhat (Cent OS)"
```suggestion
            - title: "Redhat (Cent OS)"
```

2024-06-14 17:35 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          - title: "Docker"
```suggestion
          - title: "Docker - Tyk Gateway"
```

2024-06-14 17:35 UTC, letzya commented on tyk-docs/data/menu.yaml
> +          - title: "Helm Charts"
```suggestion
          - title: "Helm Chart - Tyk Gateway"
```

2024-06-17 23:32 UTC, letzya approved these changes

2024-06-17 23:35 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/go-plugins.md
> +date: 2024-03-1
```suggestion
date: 2024-06-17
```

2024-06-17 23:49 UTC, letzya commented on tyk-docs/content/developer-support/upgrading-tyk/go-plugins.md
> +docker run --rm -v `pwd`:/plugin-source \
```suggestion
docker run --rm -v "$(pwd)":/plugin-source \
```

2024-06-17 23:52 UTC, letzya commented on tyk-docs/content/upgrading-tyk.md
> +account the deployment style you've implemented (Docker, Helm, K8S, varios Linux distributions).
```suggestion
account the deployment style you've implemented (Docker, Helm, K8S, various Linux distributions).
```

2024-06-17 23:54 UTC, letzya commented on tyk-docs/content/upgrading-tyk.md
> +- **Preparations:** Before starting the upgrade make sure you have consulted the [preparation guidelines]({{< ref "developer-support/upgrading-tyk/preparations/upgrade-guidelines" >}})
```suggestion
- **Preparations:** Make sure you have consulted the [preparation guidelines]({{< ref "developer-support/upgrading-tyk/preparations/upgrade-guidelines" >}}) before starting the upgrade.
 
```

2024-06-18 11:16 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        path: /developer-support/upgrading-tyk
```suggestion
        path: /developer-support/upgrading-tyk/
```

2024-06-18 11:27 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        path: /developer-support/upgrading-tyk/
```suggestion
        path: /developer-support/upgrading-tyk
```

2024-06-18 11:34 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        path: /developer-support/upgrading-tyk
```suggestion
        path: /upgrading-tyk
```

2024-06-18 11:38 UTC, merged

2024-06-18 11:38 UTC, letzya commented
/release to release-5.3