Add Dashboard SSO with Keycloak doc
TykTechnologies/tyk-docs-hugo pull request #4105
Opened 2024-02-08 13:54 UTC by Yubee116

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

Currently, we don't have a guide for setting up SSO to the Dashboard with Keycloak. This [text](https://tyk.io/docs/advanced-configuration/integrate/sso/#sso-with-openid-connect-oidc) shows that we intended to but haven't gotten to it yet.
This PR adds the doc and updates the existing doc that used to say "will be added soon"
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2024-02-10 02:52 UTC, pagemag approved these changes
This is good. Thanks for documenting this Ubong!

2024-02-13 13:09 UTC, dcs3spp requested changes
Many thanks for submitting the the Keycloak single sign on guide Ubong which will complete the SSO guides.

PR looks good to me. I've left some comments / suggestions and then once done will approve and then merge and release.

2024-02-13 13:09 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-keycloak-sso.md
> +This is a walk-through of how you can use [Keycloak](https://www.keycloak.org) and our (internal/embedded) TIB to log in to your Dashboard. This guide assumes you have existing Keycloak and Tyk Pro E
```suggestion
This is a walk-through of how you can use [Keycloak](https://www.keycloak.org) and our (internal/embedded) Tyk Identity Broker (TIB) to log in to your Dashboard. This guide assumes you have existing Keycloak and Tyk Pro Environments.
```

2024-02-13 13:09 UTC, dcs3spp commented on tyk-docs/assets/img/keycloak-sso/test.md
> +
Why is there a markdown file type in assets/img?

2024-02-13 13:09 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-keycloak-sso.md
> +1. Log in to your Dashboard and select Identity Management, located under System Management
Similar to the Auth0 SSO guide, include screenshots for Identity Management and Create Profile pages to guide the user step by step

2024-02-13 13:09 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-keycloak-sso.md
> +   Tip: Retrieve the discovery endpoint of the realm from “Realm Settings” > “General” Tab > OpenID Endpoint Configuration
Where is the general tab in the image?

2024-02-13 13:09 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-keycloak-sso.md
> +3. Set the provider type as “OpenID connect”
```suggestion
3. Set the provider type as “OpenID Connect”
```

2024-02-13 13:09 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-keycloak-sso.md
> +2. Create a profile, give it a name, and select “Login to Tyk Dashboard”
Show accompanying images for steps 2 and 3.

2024-02-13 13:09 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-keycloak-sso.md
> +   {{< img src="/img/keycloak-sso/copy-callback-url.png" alt="Copy callback URL" width="800px" height="400">}}
How does the image relate to the text below: _Clients > The Client > “Settings” Tab_? 

In the image _Clients_ is visible in the sidebar menu and can see there is _General Settings_ in the right navigation menu. Where is _The Client_ and _Settings_ tab displayed in the image?

2024-02-13 13:09 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-keycloak-sso.md
> +   Clients > The Client > “Settings” Tab
Does this relate to how to access the Callback URL? If so then I would have 2 separate steps for copying the callback URL and adding the redirect URL to the Keycloak client.

Can the steps for retrieving the discovery URL and validating redirect URIs be added into the Keycloak's side section? This way it could make step 7 easier to follow, since it has two save operations

2024-02-15 15:24 UTC, dcs3spp approved these changes

2024-02-15 15:27 UTC, dcs3spp approved these changes
Many thanks @Yubee116 for the guide for Dashboard SSO with Keycloak. I have approved the PR and will now merge and release.

2024-02-15 15:28 UTC, merged

2024-02-15 15:31 UTC, dcs3spp commented
/release to release-5.2

2024-02-15 15:34 UTC, dcs3spp commented
/release to release-5.1