[DX-1052] Improved body transform
TykTechnologies/tyk-docs-hugo pull request #4106
Opened 2024-02-08 14:57 UTC by andyo-tyk

### Preview Link

### Description
Updated docs for request and response body transforms.
A couple of TBCs where I'm waiting to confirm functionality.
Also requires some screenshots/videos as with other OAS docs changes

2024-02-13 16:15 UTC, dcs3spp requested changes
Thanks for submitting improved body transform content Andy. PR LGTM, have made minor suggestions/comments. I have marked the PR as draft until videos and images available. Once done and peer reviewed will merge and release.

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-classic.md
> +< placeholder for image >
remember to add image

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-classic.md
> +If you have sample input data, you can use the Input box to add it, and then test it using the **Test** button. You will see the effect of the template on the sample input in the Output box.
```suggestion
If sample input data is available, you can use the Input box to add it, and then test it using the **Test** button. You will see the effect of the template on the sample input displayed in the Output box.
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +The design of the Tyk OAS API Definition takes advantage of the `operationID` defined in the OpenAPI Document that declares both the path and method for which the middleware should be added.
Could maybe an external link to OpenAPI document for operationID?

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +You should configure only one of `body` or `path` to indicate whether you are embedding the template within the middleware or storing it in a text file. The middleware will automatically select the c
In future implementation could this be refactored so that a new configuration parameter is introduced named _requestTransformTemplateSource_ which can have a value of either _body_ or _path_?

```suggestion
You should configure only one of `body` or `path` to indicate whether you are embedding the template within the middleware body or storing it in a text file. The middleware will automatically select the correct source based on which of these fields you complete. If both are provided, then `body` will take precedence and `path` will be ignored.
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +``` .json
```suggestion
```json
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +``` .go
```suggestion
```go
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +``` .json
```suggestion
```json
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> + < placeholder for video >
remember to add video

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
> + - `enable_session`: ***TBC*** set this to `true` to make session metadata available to the transform template
Remember to remove TBC once decided

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
> +In this example, the Response Body Transform middleware is directed to use the template located in the `file` at location `./templates/transform_test.tmpl`. The input (pre-transformation) response pa
Remember to remove TBC once determined

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
> +``` .json
```suggestion
```json
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
> +We removed the need to configure the `response_processors` element in Tyk 5.3.0.
Remember to add this in release 5.3.0 release note

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
> +< placeholder for image >
Remember to add image

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
> +< placeholder for image >
Remember to add image

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-oas.md
> +                    "transformRequestBody": {
should this be transformResponseBody?

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-oas.md
> +You can see that Tyk has swapped `value1` and `value2` and embedded the `X-Header` header and `param` query values into the body of the request.
```suggestion
You can see that Tyk has swapped `value1` and `value2` and embedded the `X-Header` header and `param` query values into the body of the response.
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .go
```suggestion
```go
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .go
```suggestion
```go
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .json
```suggestion
```json
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +Here we provide worked examples working with both [JSON]({{< ref "product-stack/tyk-gateway/references/go-templates#example-json-transformation-template" >}}) and [XML]({{< ref "product-stack/tyk-gat
Maybe refactor into shorter sentence:

```suggestion
Here we provide worked examples for both [JSON]({{< ref "product-stack/tyk-gateway/references/go-templates#example-json-transformation-template" >}}) and [XML]({{< ref "product-stack/tyk-gateway/references/go-templates#example-xml-transformation-template" >}}) formatted inputs. We also explain examples using the [jsonMarshal]({{< ref "product-stack/tyk-gateway/references/go-templates#xml-to-json-conversion-using-jsonmarshal" >}}) and [xmlMarshal]({{< ref "product-stack/tyk-gateway/references/go-templates#json-to-xml-conversion-using-xmlmarshal" >}}) helper functions.
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +```.json
```suggestion
```json
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +**Input**
Is this the request details?

```suggestion
**Request**
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +Imagine you have a published API that accepts the following request body, but your upstream service requires a few alterations, namely:
```suggestion
Imagine you have a published API that accepts the request listed below, but your upstream service requires a few alterations, namely:
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .go
```suggestion
```go
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .xml
```suggestion
```xml
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +**Input**
Is this the request details?

```suggestion
```**Request**```
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .xml
```suggestion
```xml
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .go
```suggestion
```go
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .json
```suggestion
```json
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .json
```suggestion
```json
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +``` .xml
```suggestion
```xml
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/request-body.md
> +This middleware changes only the payload and not the headers. You can, however, combine this with the [Request Header Transform]({{< ref "transform-traffic/request-headers" >}}) to apply more complex
```suggestion
This middleware changes only the payload and not the headers. You can, however, combine this with the [Request Header Transform]({{< ref "transform-traffic/request-headers" >}}) middleare to apply more complex transformation to requests.
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/request-body.md
> +There is a closely related [Response Body Transform]({{< ref "advanced-configuration/transform-traffic/response-body" >}}) middleware that provides the same functionality on the response from the ups
```suggestion
There is a closely related [Response Body Transform]({{< ref "advanced-configuration/transform-traffic/response-body" >}}) middleware that provides the same functionality on the response from the upstream, prior to it being returned to the client.
```

2024-02-13 16:15 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/request-body.md
> +Sometimes you might have a legacy API and need to migrate the transactions to a new upstream service but do not want to upgrade all the existing clients to the newer upstream API. Using request body
why transactions? In the scenario does the legacy API depend on an 3rd party upstream service whose API has been upgraded to a new version? Or is it that that the legacy API has changed, so using the GW to transform the client requests to be compatible with the new API?

```suggestion
Sometimes you might have a legacy API and need to migrate the requests to a new upstream service but do not want to upgrade all the existing clients to the newer upstream API. Using request body transformation, you can use the Gateway to convert the incoming legacy XML or JSON request structure into a newer, cleaner JSON format that your upstream services expect.
```

2024-02-15 16:38 UTC, dcs3spp commented
@andyo-tyk To facilitate reviewing the PR queue we are closing some PRs that are in draft status, e.g. awaiting docker images, videos, images etc. You can still update the PR and then open it again when ready for review.

cc: @letzya

2024-02-21 15:31 UTC, davegarvey commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> + - ***TBC*** [Session metadata]({{< ref "getting-started/key-concepts/session-meta-data" >}}), from the Tyk Session Object linked to the request, can be injected into the template using the `._tyk_me
Is the "TBC" meant to still be there?

2024-02-21 16:32 UTC, davegarvey commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +So if you make a request to `PUT /anything?param=foo`, configuring a header `X-Header`:`bar` and providing this request body:
Just a thought - these example requests could be shown in a standard format, such as HTTP:

```
PUT /anything?param=foo HTTP/1.1
Host: my-gateway.host
X-Header: bar
Content-Type: application/json
Content-Length: 48

{
    "value1": "world",
    "value2": "hello"
}
```

You could cut out the content type/length headers if you wanted to cut it down a bit.

2024-02-21 16:45 UTC, davegarvey commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> + - the pipe `|` joins together the things either side of it, which is typically input data on the left and a receiving command to process the data on the right, such as `jsonMarshal`
Could add an e.g. to the end here...

`{{ . | jsonMarshal }}`

2024-03-14 22:31 UTC, letzya commented
@dcs3spp sorry if I missed anything but  it's not clear to me as a reader, why was this PR closed

2024-03-15 11:07 UTC, dcs3spp commented
Reposting link to earlier comment so it easier to find. The earlier comment explains the reason the PR was closed.

https://github.com/TykTechnologies/tyk-docs/pull/4106#issuecomment-1946531017

2024-03-18 07:44 UTC, jeffy-mathew commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> +Tyk evaluates templates stored in files on startup, so if you make changes to a template you must remember to restart the gateway.
It is not necessary to restart the gateway, a hot reload must be triggered. 
In the case of dashboard, reload happens automatically on API change. OSS mode users need to issue a hot reload request.

2024-03-18 08:01 UTC, jeffy-mathew commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> +Tyk evaluates templates stored in files on startup, so if you make changes to a template you must remember to restart the gateway.
Found a bug wrt to this.
https://tyktech.atlassian.net/browse/TT-11632

2024-03-18 08:22 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +If using a template in a file (i.e. you configure `path` in the `transformRequestBody` object), remember that Tyk will load and evaluate the template when the Gateway starts up. If you modify the tem
same as above (ideally it should be done with a reload, not restart), let it be like this for now. we need to change this later once the behaviour is corrected. https://tyktech.atlassian.net/browse/TT-11632

2024-03-18 11:00 UTC, jeffy-mathew commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> + - ***TBC*** [Session metadata]({{< ref "getting-started/key-concepts/session-meta-data" >}}), from the Tyk Session Object linked to the request, can be injected into the template using the `._tyk_me
I tried using session metadata in transform repsonse body middleware and I can confirm that it's working.

2024-03-18 11:03 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +The `transformRequestBody` object has the following configuration:
Do we need to mention that session metadata is always available in this middleware. Previously in classic API definition, user had to explicitly `enable_session`

2024-03-18 11:17 UTC, jeffy-mathew commented
<img width="1432" alt="Screenshot 2024-03-18 at 12 15 21" src="https://github.com/TykTechnologies/tyk-docs/assets/8171046/03487bcf-37d1-44a0-8289-2f05c10490dd">
`See also` links in `Response Body Transformation` href points to `/product-stack/tyk-gateway/middleware/response-body-tyk-oas/)` but alt text is `Using the Request Body Transform middleware with Tyk OAS APIs`

2024-03-19 11:58 UTC, dcs3spp commented
@andyo-tyk I've resolved most comments. Comments remaining relate to:

- _We removed the need to configure the `response_processors` element in Tyk 5.3.0_, reminder to mention in release notes 
- Reminders to add placeholders and remove TBC
- Possible [error](https://github.com/TykTechnologies/tyk-docs/pull/4106#discussion_r1488086856) in example
- Add external link to OpenAPI document for operationID?
- Section heading [rename](https://github.com/TykTechnologies/tyk-docs/pull/4106#discussion_r1488118153)

2024-03-19 12:01 UTC, dcs3spp commented
Resolved most review suggestion comments and left comment detailing those comments remaining. Re-closing draft PR. Commits can still be made to the PR branch. When changes have been made reopen PR and request review

2024-03-26 14:50 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> +Tyk evaluates templates stored in files on startup, so if you make changes to a template you must remember to restart the gateway.
Closing this as the docs reflect the existing - though not desired - behaviour.

2024-03-26 15:46 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +The design of the Tyk OAS API Definition takes advantage of the `operationID` defined in the OpenAPI Document that declares both the path and method for which the middleware should be added.
I don't think it's necessary, as we have a link just above

2024-03-27 14:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
> +The `transformRequestBody` object has the following configuration:
On the middleware page, it says that session metadata is available to this transform.
On the Tyk Classic page it says that you have to `enable_session`.
For Tyk OAS there's no mention of a need to set anything, because it's automatically enabled.
--> my logic here is that the OAS and Classic pages are deliberately stand-alone so I don't want to mention things you *don't* have to do, only those that you *do*

2024-03-27 14:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-oas.md
> +                    "transformRequestBody": {
Yes, good spot of that typo!

2024-03-27 14:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +**Input**
No, it's the input to the Go template. This page is a reference guide to using Go templating.

2024-03-27 14:01 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
> +**Input**
See previous reply

2024-03-27 15:18 UTC, dcs3spp approved these changes
@andyo-tyk PR LGTM, once peer approved by @davegarvey and @jeffy-mathew, I will merge ready for release.

2024-03-28 15:10 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-oas.md
> +title: Using the Request Body Transform middleware with Tyk OAS APIs
This should be `Using the Response Body Transform middleware with Tyk OAS APIs`

2024-03-28 15:10 UTC, jeffy-mathew approved these changes

2024-04-02 08:13 UTC, davegarvey approved these changes

2024-04-03 09:30 UTC, dcs3spp commented
Closing, created a new [PR](https://github.com/TykTechnologies/tyk-docs/pull/4336) that fixes the merge conflicts which has now been merged

2024-04-03 09:30 UTC, closed without merging