[TT-10953] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #4114
Opened 2024-02-09 14:44 UTC by buger

Triggered by: dcs3spp

Included:

Tyk Gateway: false
Tyk Dashboard: false
Tyk MDCB false
Tyk Pump true

Intended for: master
Config info generator branch: main

Note: Test Pump config generator

JIRA: https://tyktech.atlassian.net/browse/TT-10953

2024-02-09 15:03 UTC, dcs3spp reviewed
@matiasinsaurralde This will need peer approval for the config additions and changes made in the Golang source before merge and release

2024-02-13 11:51 UTC, dcs3spp requested changes
@mativm02 I have reviewed the generated PR from the Pump config.go source.

After reviewing I have noticed the following:
- _analytics_storage_config_ docs are removed from the doc string comments, as illustrated in the PR [preview](https://deploy-preview-4114--tyk-docs.netlify.app/docs/nightly/tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables)
- There are some cases where all default environment prefixes are listed for a config section (see comments)

I think a peer review is required to confirm the additional config items are correct for Pump release 1.9 and that the removal of _analytics_storage_config_ docs, e.g. _analytics_storage_config.host_ etc. etc. is confirmed for release of Pump 1.9. If not the config.go source docstring comments need to be updated so that analytics_storage_config is included.

2024-02-13 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> -### analytics_storage_config.type
@mativm02 Why is analytics_storage_config docs not been generated from the config.go?

2024-02-13 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +Prefix for the environment variables that will be used to override the configuration.
Should this just list the default prefix for TYK_PMP_PUMPS_MONGOSELECTIVE_META instead of listing all defaults?

2024-02-13 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +ENV: <b>TYK_PMP_PUMPS_MONGOAGGREGATE_META_ENVPREFIX</b><br />
Should this just list the default for TYK_PMP_PUMPS_MONGOAGGREGATE_META instead of all the defaults?

2024-02-13 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +Prefix for the environment variables that will be used to override the configuration.
Should this just list the default for TYK_PMP_PUMPS_MONGOAGGREGATE_META instead of all the defaults?

2024-02-14 14:50 UTC, mativm02 commented on tyk-docs/content/shared/pump-config.md
> +Prefix for the environment variables that will be used to override the configuration.
@dcs3spp It's not possible at the moment. Remember that all Mongo Pumps (Mongo, selective, aggregate, etc.) are inheriting data from the same base struct config (to avoid code repeating).

2024-02-14 15:11 UTC, mativm02 commented on tyk-docs/content/shared/pump-config.md
> -### analytics_storage_config.type
@dcs3spp good catch 👀 it seems there's a bug in the config generator script, I'll take a look at it!

2024-02-14 15:48 UTC, mativm02 commented on tyk-docs/content/shared/pump-config.md
> -### analytics_storage_config.type
@dcs3spp https://github.com/TykTechnologies/tyk-config-info-generator/pull/6 I raised a PR, there's a configuration that needs to be changed. Once it's approved, I'll re-run the workflow!

2024-02-14 16:10 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> -### analytics_storage_config.type
Thanks @mativm02 let me know once you have re-run the workflow.

2024-02-15 12:41 UTC, dcs3spp requested changes
@mativm02 Nice!!! Changes came through to the same PR which is an advantage of using that new Ghub action.

Now we have analytics storage appearing in the PR. There are some small comments I have left regarding the changes this has introduced, that may require peer review to confirm. Then I think this is ready for merge and release.

2024-02-15 12:41 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +Use instead of the host value if you're running a cluster instance with multiple instances.
```suggestion
Use instead of the host value if you're running a Redis cluster with multiple instances.
```

or

Use instead of the host value if you're running a cluster with multiple instances.

2024-02-15 12:41 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +DB username.
Is it redis or database username?

2024-02-15 12:41 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +DB password.
Is it redis or database password?

2024-02-15 12:41 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +Database name.
Is it redis db name or database name?

2024-02-15 12:41 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +Set this to `true` to tell Pump to ignore database's cert validation.
Is it Redis or database's cert validation?

2024-02-15 12:41 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +Prefix for the environment variables that will be used to override the configuration.
Ok thanks @mativm02

2024-02-15 12:41 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> -Sentinel redis password.
Why was Redis removed? Can the analytics storage be a backend database suchas MySQL, PostgreSQL also? so Redis was removed so it is more generalised / generic?

2024-02-15 12:41 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +### analytics_storage_config.use_ssl
Are the remaining analytics_storage_config parameters down to line 4816 specific to new release of Pump 1.9?

2024-02-15 17:00 UTC, mativm02 commented on tyk-docs/content/shared/pump-config.md
> +DB username.
Pump only uses one database to fetch data (Redis). We want to make it more generic because, in the future, we plan to allow more options.

2024-02-15 17:02 UTC, mativm02 commented on tyk-docs/content/shared/pump-config.md
> +Use instead of the host value if you're running a cluster instance with multiple instances.
@dcs3spp I'll create a new PR in Pump's repo to change this. Let's make sure everything's okay there before running the docs generation workflow :)

2024-02-15 17:03 UTC, mativm02 commented on tyk-docs/content/shared/pump-config.md
> -Sentinel redis password.
Yes, Redis was removed so it's more generic. At the moment, we only allow Redis connections, but we're planning to allow more options.

2024-02-15 17:05 UTC, mativm02 commented on tyk-docs/content/shared/pump-config.md
> +### analytics_storage_config.use_ssl
Yes, they are!

2024-02-15 17:16 UTC, sredxny approved these changes

2024-02-15 17:17 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +### analytics_storage_config.use_ssl
Ok thanks @mativm02

2024-02-15 17:17 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> -Sentinel redis password.
Ok thanks @mativm02

2024-02-15 17:19 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +Use instead of the host value if you're running a cluster instance with multiple instances.
Ok thanks @mativm02 I'll keep the PR open and then after regression we can merge into this PR and then merge and release 👍

2024-02-27 13:33 UTC, mativm02 commented
@dcs3spp changes were done! Thanks for the suggestions

2024-02-27 17:05 UTC, dcs3spp approved these changes
Thanks @mativm02 PR LGTM and approved!

2024-03-05 17:51 UTC, merged