TT-11263 documented TYK_IB_SESSION_SECRET
TykTechnologies/tyk-docs-hugo pull request #4139
Opened 2024-02-13 20:22 UTC by sredxny

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-02-15 09:14 UTC, dcs3spp requested changes
@sredxny PR looks good to me. Left comments:
- Checking if there is a typo
- Recommend to reader what makes a strong secret

2024-02-15 09:14 UTC, dcs3spp commented on tyk-docs/content/tyk-identity-broker/getting-started.md
> +For a seamless and secure setup, start by generating a strong, unique secret string. This string will be your session secret. In a Linux, Unix, or MacOS environment, you can set this variable by runn
Can you recommend to the reader for what makes a strong secret.

2024-02-15 09:14 UTC, dcs3spp commented on tyk-docs/content/tyk-identity-broker/getting-started.md
> +### Configuring TYK_IB_SESSION_SECRET
Is this a typo  TYK_IB_SESSION_SECRET? Should it be  TYK_TIB_SESSION_SECRET?

2024-02-15 09:14 UTC, dcs3spp commented on tyk-docs/content/tyk-identity-broker/getting-started.md
> +To secure session cookies within Tyk Identity Broker (TIB) when integrating with social providers, setting the `TYK_IB_SESSION_SECRET` environment variable is crucial. This variable plays a pivotal r
Is this a typo  TYK_IB_SESSION_SECRET? Should it be  TYK_TIB_SESSION_SECRET?

Does this mean that the dashboard admin secret could be leaked to a 3rd party Identity Provider? If so maybe explain this.

2024-02-20 09:53 UTC, sredxny commented on tyk-docs/content/tyk-identity-broker/getting-started.md
> +### Configuring TYK_IB_SESSION_SECRET
@dcs3spp it's not a typo, the var is defined like that. It's the same when using embeded or standalone TIB

2024-02-20 09:54 UTC, sredxny commented on tyk-docs/content/tyk-identity-broker/getting-started.md
> +To secure session cookies within Tyk Identity Broker (TIB) when integrating with social providers, setting the `TYK_IB_SESSION_SECRET` environment variable is crucial. This variable plays a pivotal r
@dcs3spp good spot! am gathering info to know if it represents a security issue, so far I dont think so as in prod environments a lot of customers are already defining the configuration via env vars

2024-02-20 10:22 UTC, sredxny commented on tyk-docs/content/tyk-identity-broker/getting-started.md
> +For a seamless and secure setup, start by generating a strong, unique secret string. This string will be your session secret. In a Linux, Unix, or MacOS environment, you can set this variable by runn
done!

2024-02-20 11:19 UTC, dcs3spp commented on tyk-docs/content/tyk-identity-broker/getting-started.md
> +### Configuring TYK_IB_SESSION_SECRET
Ok thanks @sredxny

2024-02-20 11:21 UTC, dcs3spp approved these changes
Thanks @sredxny PR LGTM and approving. Once peer review and approval is complete, I'll merge ready for release.

2024-02-26 15:58 UTC, caroltyk commented on tyk-docs/content/tyk-identity-broker/getting-started.md
> +### Configuring TYK_IB_SESSION_SECRET
```suggestion
### Configure secret for hashing session cookies
```

2024-02-26 15:59 UTC, caroltyk requested changes
Thanks @sredxny . Left a suggestion for the heading, otherwise the PR looks good.

2024-02-26 16:07 UTC, carolwkc commented on tyk-docs/content/tyk-identity-broker/getting-started.md
> +To secure session cookies within Tyk Identity Broker (TIB) when integrating with social providers, setting the `TYK_IB_SESSION_SECRET` environment variable is crucial. This variable plays a pivotal r
> TIB falls back to using the Tyk Dashboard's admin_secret when it's embedded in the dashboard.

@sredxny does this behaviour apply for 5.3+ only?

2024-02-27 11:18 UTC, dcs3spp reviewed
@sredxny If you are ok with suggestion made @caroltyk could you commit the suggestion and then get approval from @caroltyk. Then we merge and release

2024-02-27 12:49 UTC, dcs3spp reviewed
@sredxny @caroltyk Should TYK_IB_SESSION_SECRET also be documented on this [page](https://tyk.io/docs/tyk-configuration-reference/tyk-identity-broker-configuration/#secret)?

2024-02-29 18:05 UTC, dcs3spp commented
@caroltyk Would you be able to peer review?

2024-03-05 16:22 UTC, caroltyk approved these changes
lgtm

2024-03-05 17:26 UTC, merged

2024-03-05 17:26 UTC, dcs3spp commented
/release to release-5.2

2024-03-05 17:27 UTC, dcs3spp commented
/release to release-5.1

2024-03-05 17:33 UTC, dcs3spp commented
/release to release-5