Update tyk-sync.md
TykTechnologies/tyk-docs-hugo pull request #4140
Opened 2024-02-13 23:55 UTC by caroltyk

Update Tyk Sync regarding compatibility with 5.3 OAS API

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-02-14 05:52 UTC, lghiur commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync supports you to work with [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts" >}}). Tyk Sync is currently using classic Dashboard API so the use of [allow-unsafe-oas]({
I would add a note that saying that this option will suffer changes in the future, and must be carefully used. Also I would wait for @andyo-tyk to review this,

2024-02-14 10:18 UTC, caroltyk commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync supports you to work with [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts" >}}). Tyk Sync is currently using classic Dashboard API so the use of [allow-unsafe-oas]({
Updated to mention this flag will be deprecated in future.

2024-02-15 09:25 UTC, dcs3spp requested changes
PR LGTM Carol, I have made small suggestion and after peer review will merge and release.

2024-02-15 09:25 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync does not work with Keys. See [Move Keys between environments]({{< ref "advanced-configuration/manage-multiple-environments/move-keys-between-environments" >}}) for details.
```suggestion
Tyk Sync does not work with keys. Please consult [move keys between environments]({{< ref "advanced-configuration/manage-multiple-environments/move-keys-between-environments" >}}) for further details.
```

2024-02-21 09:56 UTC, andyo-tyk requested changes
Suggested tweaks to wording - and a question re: Tyk OAS + OSS Gateway

2024-02-21 09:56 UTC, andyo-tyk commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync supports you to work with [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts" >}}). Tyk Sync is currently using classic Dashboard API so the use of [allow-unsafe-oas]({
```suggestion
Tyk Sync supports both [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts" >}}) and [Tyk Classic APIs]({{< ref "[ggetting-started/key-concepts/what-is-an-api-definition/#api-definition-types" >}}) when working with Tyk Dashboard, however at this time you must set the [allow-unsafe-oas]({{< ref "tyk-dashboard/configuration#allow_unsafe_oas" >}}) configuration in Dashboard, and the flag `--allow-unsafe-oas` when invoking Tyk Sync if you want to use Tyk Sync to migrate Tyk OAS APIs.

API Category is not currently supported in Tyk Sync for Tyk OAS APIs.
```

2024-02-21 09:56 UTC, andyo-tyk commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync supports you to work with [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts" >}}). Tyk Sync is currently using classic Dashboard API so the use of [allow-unsafe-oas]({
Question: here we're telling users to set `allow_unsafe_oas` to work with Tyk OAS APIs... but this is a Dashboard config, not relevant to OSS Gateway... so does Sync actually support Tyk OAS APIs for OSS users? (re: the table lower down the page that gives a green tick for OSS)

2024-02-21 09:56 UTC, andyo-tyk commented on tyk-docs/content/tyk-sync.md
> +`--allow-unsafe-oas` is an option provided for early adopters and will be deprecated later. Tyk Sync will be updated in a future release to use Dashboard API for OAS to bring you the full OAS API exp
```suggestion
`--allow-unsafe-oas` is a flag that is required for Tyk Sync to work with Tyk OAS APIs. This is a temporary measure provided for early adopters and will be deprecated later when Tyk Sync will be updated in a future release to bring you the full Tyk OAS API experience. 
```

2024-02-26 22:25 UTC, caroltyk commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync supports you to work with [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts" >}}). Tyk Sync is currently using classic Dashboard API so the use of [allow-unsafe-oas]({
@andyo-tyk Sync use classic API endpoints to create/update OAS APIs when working with OSS Gateway. The `allow_unsafe_oas` config might be required for OSS Gateway too, can you confirm if it was implemented in Gateway?

2024-02-27 11:28 UTC, dcs3spp approved these changes

2024-02-27 11:31 UTC, dcs3spp commented
Thanks @caroltyk I have approved. @andyo-tyk @lghiur, if the changes updated by @caroltyk for peer review are ok can they be approved ready for merge and release?

2024-03-05 17:43 UTC, dcs3spp commented
@andyo-tyk @lghiur 

@caroltyk Has made requested peer review changes, would you be able to approve if ok?

2024-03-06 09:52 UTC, andyo-tyk approved these changes
Fine by me, thanks.

2024-03-07 10:57 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync supports you to work with [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts" >}}). Tyk Sync is currently using classic Dashboard API so the use of [allow-unsafe-oas]({
> I would add a note that saying that this option will suffer changes in the future, and must be carefully used. Also I would wait for @andyo-tyk to review this,

@andyo-tyk @caroltyk @lghiur See there is a label on PR for 5.3.0 so double checking. This should not yet be released yet, yes?

2024-03-07 10:59 UTC, lghiur commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync supports you to work with [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts" >}}). Tyk Sync is currently using classic Dashboard API so the use of [allow-unsafe-oas]({
@dcs3spp as 5.3.0 is not out yet, no

2024-03-12 10:08 UTC, dcs3spp commented on tyk-docs/content/tyk-sync.md
> +Tyk Sync supports you to work with [Tyk OAS APIs]({{< ref "getting-started/key-concepts/high-level-concepts" >}}). Tyk Sync is currently using classic Dashboard API so the use of [allow-unsafe-oas]({
ok thanks @lghiur

2024-03-12 11:46 UTC, dcs3spp commented
@andyo-tyk @carol @lghiur I will merge and then release later for 5.3.0

2024-03-12 11:50 UTC, merged