ADD guide to configure OTel with Elasticsearch
TykTechnologies/tyk-docs-hugo pull request #4150
Opened 2024-02-14 15:32 UTC by SonjaChevre

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-02-15 08:29 UTC, carlostyk approved these changes
This looks very good. Thank you @SonjaChevre for migrating the doc to Tyk Documentation and make it better. Very valuable information.

2024-02-15 12:01 UTC, dcs3spp requested changes
A clear structure guide for configuring OTel with Elasticsearch. Many thanks for creating the guide @SonjaChevre and thanks for the peer review @carlostyk.

I have made minor suggestions and then I think that this is ready for merge and release.

2024-02-15 12:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
> +tags: ["distributed tracing", "OpenTelemetry", "Elastic", "Elasticsearch", "ELK"]
```suggestion
tags: ["distributed tracing", "OpenTelemetry", "Elastic", "Elasticsearch", "ELK", "API Observability", "Observability"]
```

2024-02-15 12:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
> +After enabling OpenTelemetry at the gateway level, you can activate detailed tracing for specific APIs by editing their respective API definitions. Set the `detailed_tracing` option to either true or
Is there a link that can be added for the detailed_tracing option?

```suggestion
After enabling OpenTelemetry at the Gateway level, you can activate detailed tracing for specific APIs by editing their respective API definitions. Set the `detailed_tracing` option to either true or false. By default, this setting is false.
```

2024-02-15 12:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
> +    endpoint: "ELASTIC_APM_SERVER_ENDPOINT_GOES_HERE" #without HTTPS://
would HTTP:// be accepted? Or does the comment mean exclude the protocol?

2024-02-15 12:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
> +  - On the menu on the right side, click on "APM / Services."
```suggestion
  - On the right menu, click on "APM / Services."
```

2024-02-15 12:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
> +- Explore OpenTelemetry Traces in Elasticsearch
Maybe remove this sentence since it is the same as the section heading

2024-02-15 12:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
> +- Tyk Gateway v5.2 or higher
Replace - with * or replace * with - for consistent list item style in markdown

2024-02-15 12:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
> +* Sign up for an Elastic account if you haven't already
Could add a link to sign up for elastic account here? https://www.elastic.co/

2024-02-15 12:22 UTC, SonjaChevre commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
> +    endpoint: "ELASTIC_APM_SERVER_ENDPOINT_GOES_HERE" #without HTTPS://
the comment mean to exclude the protocol - when you are in Elasticsearch and copy this value, it copies everything including https:// and you have to remove it for it to work.

Can you think of another way to phrase it?

2024-02-15 14:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
> +    endpoint: "ELASTIC_APM_SERVER_ENDPOINT_GOES_HERE" #without HTTPS://
@SonjaChevre would something like this be ok?

```suggestion
    endpoint: "ELASTIC_APM_SERVER_ENDPOINT_GOES_HERE" #exclude protocol, e.g. HTTPS:// or HTTP://
```

2024-02-22 16:32 UTC, dcs3spp approved these changes

2024-02-22 16:33 UTC, merged

2024-02-22 16:34 UTC, dcs3spp commented
/release to release-5.2

2024-02-22 16:35 UTC, dcs3spp commented
/release to release-5.1