[TT-11185] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #4152
Opened 2024-02-15 08:02 UTC by buger

Triggered by: lghiur

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: master
Config info generator branch: main

Note: Release 5.3.0 doc updates

JIRA: https://tyktech.atlassian.net/browse/TT-11185

2024-02-20 13:10 UTC, dcs3spp requested changes
@lghiur Thanks for creating the PR from the new workflow. 

So far I have reviewed the OAS schema specifications. I will do another review for the config updates.

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +    ApiDocument:
For each schema type ensure that each property has a description, description and also mention where applicable default value and if it is readonly.

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +      description: Update Organisation details. This operation will replace the existing Organisation details with those provided in the request payload. It is important to provide the entire object
```suggestion
      description: Update Organisation details. This operation will replace the existing Organisation details with those provided in the request payload. It is important to provide the entire OrganisationDocument object - for example include linked APIs - to avoid overwriting existing data with empty values.
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +              apis:
Following the statement given in the description, include full example of sub objects, e.g. languages, login_page etc

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +      description: Update Organisation details. This operation will replace the existing Organisation details with those provided in the request payload. It is important to provide the entire object
Should the version be bumped in this file also?

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                $ref: '#/components/schemas/ApiModifyKeySuccess'
Is it beneficial to add this change to changelog in release notes for 5.3, to notify users that would need to regenerate client SDK from the OAS spec?

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        name: apiID
add example for apiID parameter. Move the existing description as a description or summary for the path and then add a separate. description for the apiID parameter.

Suggested description for endpoint:

```suggestion
 API definitions can be assigned to user defined categories, thus allowing APIs to be filtered on the API list page.
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                $ref: '#/components/schemas/apiStatusMessage'
If we have updated ApiModifyKeySuccess, should we update apiStatusMessage to APIStatusMessage also?

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        - APIs
Other tags are OAS APIs, should this tag be updated to OAS APIs?

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: API categories
```suggestion
          description: List of all API categories are returned in the response
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: conflict on custom asset ID
```suggestion
          description: Duplicate custom asset ID encountered
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: asset not found
```suggestion
          description: Asset not found
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: cannot change db ID
```summary
          description: Cannot change db ID
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: asset not found
```suggestion
          description: Asset not found
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: conflict on custom asset ID
```suggestion
          description: Duplicate custom asset ID encountered
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: asset not found
```suggestion
          description: Asset not found
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      description: CategoriesPayload is a list of category names
Add an example for the schema

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +    AllCategoriesResponse:
Add an example for the schema

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +    ApiModifyKeySuccess:
Add an example for the schema

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +    ImportOrPatchFromURL:
Add an example for the schema and properties

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +    APIAccessManagementPayload:
Add an example for the schema and properties

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      type: boolean
Will this be a breaking change for existing clients who have generated SDKs and using string values "true" or "false"? Should this change be documented in release notes?

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: database id of asset
```suggestion
          description: Database id of asset
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: custom id of asset that can be provided while creation/updation.
```suggestion
          description: Custom id of asset that can be provided while creation/updation.
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: last updated time stamp
```suggestion
          description: Last updated time stamp
```

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      description: Enable/disable the authentication mechanism in your Tyk Gateway for your OAS API
Is this the correct description and schema reference for TemplateID?

2024-02-20 13:10 UTC, dcs3spp commented on tyk-docs/assets/others/gateway-swagger.yml
> +  version: 5.3.0
Is it only Dashboard that has had changes to the OAS schema?

2024-02-20 18:22 UTC, dcs3spp requested changes
@lghiur Thanks for generating the PR. I have added an additional review for the config files.

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
> +Redis SSL Cert file
Is a full absolute path accepted or is it just the file name? What type of cert files are accepted?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
> +Redis SSL Key file
Is a full absolute path accepted or is it just the file name? What type of cert key files are accepted?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
> +Redis SSL Max version
Similar to the new docs content in gateway-config.md what is the default value and what are the accepted versions?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
> +Redis SSL Min version
Similar to the new docs content in gateway-config.md what is the default value and what are the accepted versions?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Path to the cert file.
Is there a limit on the type of certificate files supported?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Path to the key file.
Is there a limit on the type of certificate key files supported?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Path to the cert file.
Is there a limit to the type of certificate files supported?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Path to the key file.
Is there a limit to the type of certificate key files supported?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Path to the cert file.
Is there a limit to the type of certificate files supported?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Path to the key file.
Is there a limit to the type of certificate key files supported?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +See more details https://tyk.io/docs/tyk-configuration-reference/kv-store/
Instead of an absolute URL is it possible to generate a URL from relative path, e.g. {{< ref "tyk-configuration-reference/kv-store" >}}

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +### oas_config
This section is also in Dashboard. Checking if it needs to be both Gateway & Dashboard?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +URL defines the upstream address (or Target URL) to which requests should be proxied.
```suggestion
URL defines the upstream address (or target URL) to which requests should be proxied.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +MutualTLS contains the configuration for establishment of mutual TLS between Tyk and the upstream server.
```suggestion
MutualTLS contains the configuration for establishing a mutual TLS connection between Tyk and the upstream server.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +path, on the port that Tyk is configured to run on, and processes these
```suggestion
path, on the port that Tyk is configured to run on and processes these
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +State holds configuration for the status of the API within Tyk - whether it is currently active and whether it is exposed externally.
```suggestion
State holds configuration for the status of the API within Tyk - whether it is currently active and exposed externally.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +`This API version does not seem to exist` error in this scenario.
Why has a line break occurred?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **VersionToID**
Why has the VersionToID section being deleted?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ParentDataPath is the namespace of the where to find the nested
Is there a way to reduce the line breaks?

```suggestion
ParentDataPath is the namespace of where to find the nested
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PortDataPath is the port of the data path. In the above nested example, we can see that there is a separate `port` value
Is there a way to reduce the line breaks?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +inject it into the target list of your API definition.
Is it possible to prevent the line break?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +failures are not recovered from quickly enough.
Is it possible to prevent the line break?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -Tyk classic API definition: `service_discovery.endpoint_returns_list`.
Why was the ServiceDiscoveryCache config section removed below?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +MutualTLS contains the configuration for establishment of mutual TLS between Tyk and the upstream server.
Is this duplicated above in this config file?

```suggestion
MutualTLS contains the configuration for establishing a mutual TLS connection between Tyk and the upstream server.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
>  DomainToCertificates maintains the mapping of domain to certificate.
Is there _[[]_ a typo?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **DomainToCertificate**
Should this be removed?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **Server**
Is this still included in the config?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +where hours, minutes, and seconds are denoted by 'h', 'm', and 's' respectively.
```suggestion
where hours, minutes and seconds are denoted by 'h', 'm' and 's' respectively.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +An empty value is interpreted as "0s", implying no rate limiting interval effectively disabling the API-level rate limit.
```suggestion
An empty value is interpreted as "0s", implying no rate limiting interval, which disables the API-level rate limit.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +this path, on the port that Tyk is configured to run on, and processes
```suggestion
this path, on the port that Tyk is configured to run on and processes
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Strip removes the inbound listen path (as accessed by the client) when generating the outgoing request (to the upstream service).
```suggestion
Strip removes the inbound listen path (as accessed by the client) when generating the outbound request for the upstream service.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +For example, a scenario where the Tyk base address is `http://acme.com/', the listen path is `example/` and the upstream URL is `http://httpbin.org/`:
```suggestion
For example, consider the scenario where the Tyk base address is `http://acme.com/', the listen path is `example/` and the upstream URL is `http://httpbin.org/`:
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `securitySchemes` ([SecuritySchemes](#securityschemes))**
Security schemes is included below but not expanded with config attributes

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **HMAC**
Has this section still been included?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `allowlist` (`[]string`)**
Should this field have an equivalent Tyk classic API definition?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables use of segment tags.
Should an equivalent Tyk classic API definition be added for this field?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tags is a list of segment tags
Should an equivalent Tyk classic API definition be added for this field?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled allow/disallow the usage of the domain.
Should an equivalent Tyk classic API definition be added for this field and what is the default?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Name is the name of the domain.
Should an equivalent Tyk classic API definition be added for this field?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +that the Gateway can utilize to dynamically load certificates for your custom domain.
```suggestion
that the Gateway can utilise to dynamically load certificates for your custom domain.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables detailed tracing.
Should a Tyk Classic configuration also be documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PluginConfig contains the common configuration for custom plugins.
Should the Tyk Classic equivalent be documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition: `global_headers`/`global_headers_remove`.
Would need peer review to check that these are the correct equivalent Tyk Classic API definitions for transformRequestHeaders

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition: `global_response_headers`/`global_response_headers_remove`.
```suggestion
Would need peer review to check that these are the correct equivalent Tyk Classic API definitions for transformResponseHeaders
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +and reads the value from algorithm header.
```suggestion
and reads the value from the algorithm header.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SegregateByClientId is a boolean flag. If set to `true, the policies will be applied to a combination of Client ID and User ID.
Not sure if I understand correctly, so double checking. Does it mean that policies are applied to keys owned by a given client or user?

```suggestion
SegregateByClientId is a boolean flag. If set to `true, the policies will be applied to a combination of keys owner by a given Client ID and User ID.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Providers contains a list of authorised providers and their Client IDs, and matched policies.
```suggestion
Providers contains a list of authorised providers, their Client IDs and matched policies.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Scopes contains the defined scope claims.
Should there be a Tyk Classic equivalent config parameter documented for Scopes?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `config` ([AuthenticationPlugin](#authenticationplugin))**
Instead of config could it be renamed to auth_plugin or something similar?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SecuritySchemes holds security scheme values, filled with Import().
Need to generate the attributes for security schemes

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition: `custom_middleware.auth_check`.
Would need peer review to check that this is the correct equivalent for Tyk Classic

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +The value should be set to one of the following:
Does it have a Tyk Classic equivalent?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +OptionsPassthrough is a boolean flag. If set to `true`, it will proxy the CORS OPTIONS pre-flight
Is it possible to prevent line breaks in this paragraph?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PrePlugin configures pre stage plugins.
```suggestion
PrePlugin configure pre request plugins. These are executed before the request is sent to your upstream target and before any authentication information is extracted from the header or parameter list of the request. 
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `plugins` ([CustomPlugins](#customplugins))**
Could this be renamed to pre_auth_plugins and should there be a Tyk classic equivalent config documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `plugins` ([CustomPlugins](#customplugins))**
Should there be a Tyk classic equivalent config documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `plugins` ([CustomPlugins](#customplugins))**
Should there be a Tyk classic equivalent config documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +by explicitly setting the endpoint cache middleware.
Can the line break be prevented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +applies across versions.
Can the line break be prevented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables Header Transform for the given path and method.
Should there be a Tyk classic equivalent config documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Remove specifies header names to be removed from the request/response.
Should there be a Tyk classic equivalent config documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Add specifies headers to be added to the request/response.
Should there be a Tyk classic equivalent config documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables Header Transform for the given path and method.
Should there be a Tyk classic equivalent config documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Remove specifies header names to be removed from the request/response.
Should there be a Tyk classic equivalent config documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Add specifies headers to be added to the request/response.
Should there be a Tyk classic equivalent config documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Domain contains the domain name.
Should there be a Tyk classic equivalent config documented for domain name and public keys?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ClientToPolicyMapping contains mappings of Client IDs to Policy IDs.
Is it a mapping or a list?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `scopeToPolicyMapping` ([[]ScopeToPolicy](#scopetopolicy))**
Is it a mapping or list?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +AuthenticationPlugin holds the configuration for custom authentication plugin.
Should there be a Tyk classic equivalent config documented for these attributes?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path is the path to shared object file in case of gopluign mode or path to js code in case of otto auth plugin.
```suggestion
Path is the path to shared object file in case of goplugin mode or path to JS code in case of otto auth plugin.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +RawBodyOnly if set to true, do not fill body in request or response object.
Not sure understand how this attribute relates to authentication, If set to true it does not include what information in request or response object? What information is passed into request or response object if false?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +IDExtractor configures ID extractor with coprocess custom authentication.
Can a link be added to IDExtractor? Does the IDExtractor cache authenticated IDs so that a call does not have to be made to upstream GRPC server? If so could add the benefit here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path will be suffixed to `bundle_base_url` in gateway config.
Is there an equivalent Tyk Classic API definition

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PluginConfigData configures config data for custom plugins.
Should there be Tyk classic equivalent configs documented here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CustomPlugins is a list of CustomPlugin.
```suggestion
CustomPlugins is a list of CustomPlugin instances.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as array of `CustomPlugin` values, see [CustomPlugin](#customplugin) definition.
Do we need to mention the type is defined as array of CustomPlugin values again?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
Do we need Tyk classic equivalents documented here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ClientToPolicy contains a 1-1 mapping between Client ID and Policy ID.
Do we need Tyk classic equivalents documented here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ScopeToPolicy contains a single scope to policy ID mapping.
Do we need Tyk classic equivalents documented here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +IDExtractor configures ID Extractor.
Do we need Tyk classic equivalents documented here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path is the path to shared object file in case of gopluign mode or path to js code in case of otto auth plugin.
```suggestion
Path is the path to shared object file in case of goplugin mode or path to JS code in case of otto auth plugin.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CustomPlugin configures custom plugin.
Do we need to add Tyk Classic config equivalents here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +RawBodyOnly if set to true, do not fill body in request or response object.
as per commented earlier.

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +IDExtractorConfig specifies the configuration for ID extractor.
Do we need to add Tyk Classic config equivalents here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **OAuthProvider**
Fields missing description and do we need to add Tyk Classic config equivalents here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **JWTValidation**
Do we need to add Tyk Classic config equivalents here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Source is the secret to verify signature, it could be one among:
```suggestion
Source is the secret to verify signature. Valid values are:
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Introspection**
Are there Tyk Classic equivalents that can be included here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **IntrospectionCache**
Are there Tyk Classic equivalents that can be included here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ClientSecret is a secret known only to the client and the authorization server, acquired from the third party.
```suggestion
ClientSecret is a secret known only to the client and the authorisation server, acquired from the third party.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **ExternalOAuth**
Missing field descriptions

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as array of `EndpointPostPlugin` values, see [EndpointPostPlugin](#endpointpostplugin) definition.
Missing field descriptions

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Allowance**
Are there Tyk Classic equivalents that can be added here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +AllowanceType holds the valid allowance types values.
Missing fields/attributes?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +user credentials can be passed via request body.
Can the line break be prevented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CachePlugin holds the configuration for the cache plugins.
Are there Tyk Classic equivalents that can be added here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +EndpointPostPlugin contains endpoint level post plugin configuration.
Are there Tyk Classic equivalents that can be added here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +EnforceTimeout holds the configuration for enforcing request timeouts.
Are there Tyk Classic equivalents that can be added here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ExtractCredentialsFromBody configures extracting credentials from the request body.
Are there equivalent Tyk Classic OAS examples that can be added here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +FromOASExamples configures mock responses should be returned from OAS example responses.
```suggestion
FromOASExamples configures mock responses that should be returned from OAS example responses.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **FromOASExamples**
FromOASExamples configures mock responses should be returned from OAS example responses.

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled if set to true makes the endpoint available only for internal requests.
Is there a Tyk Classic equivalent config?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **JWT**
Missing descriptions

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `notBeforeValidationSkew` (`uint64`)**
Missing descriptions for some fields here

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +accidentally misidentifying the use of one of these IDPs if one of their standard values is configured in your JWT.
Can the line breaks be prevented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the mock response middleware.
```suggestion
Enabled activates the mock response middleware.
```

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **MockResponse**
Are there Tyk Classic API equivalents that should be documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Notifications holds configuration for updates to keys.
How are the key updates notified, via webhooks and are there Tyk Classic configuration equivalents?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **OAuth**
Missing descriptions for the attributes in this section

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Path**
Missing descriptions for attributes in this section

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Operation holds a request operation configuration, allowances, tranformations, caching, timeouts and validation.
Are there Tyk classic equivalents that should be documented here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Allow request by allowance.
What is the allowance, is it total allowed requests etc?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the Request Size Limit functionality.
Tyk classic equivalents?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SecurityScheme defines an Importer interface for security schemes.
Can this section be expanded with further details?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `enabled` (`boolean`)**
Missing descriptions

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `format` (`string`)**
Is this a breaking change?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **TransformRequestMethod**
Is there equivalent Tyk Classic API config params to be documented here?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `UpstreamURL` (`string`)**
Missing description etc.

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **TykExtensionConfigParams**
Missing descriptions

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +URLRewriteInput defines the input for an URL rewrite rule.
Missing a field or attribute for the description

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Name is the index in the input identified in `in` that should be used to
Not sure understand, can an example be added?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **URLRewriteTrigger**
Are there Tyk Classic equivalents that can be documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ValidateRequest holds configuration required for validating requests.
Are there Tyk Classic equivalents that can be documented?

2024-02-20 18:22 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +VirtualEndpoint contains virtual endpoint configuration.
Missing fields and associated descriptions

2024-02-22 21:10 UTC, maciejwojciechowski commented on tyk-docs/content/shared/dashboard-config.md
> +ENV: <b>TYK_DB_USESHARDEDANLAYTICS</b><br />
typo , ANLAYTICS > ANALYTICS

2024-02-27 11:23 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        - APIs
No, this one is not OAS specific

2024-02-27 12:24 UTC, titpetric commented on tyk-docs/content/shared/dashboard-config.md
> +Redis SSL Max version
leaving this alone:

the default value and accepted values are a technical problem as it changes and drifts, it should come from a secondary step (out of scope)

resolving similar comments.

2024-02-27 12:47 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                $ref: '#/components/schemas/ApiModifyKeySuccess'
I'm more inclined to rename it back, we have also:

apiAllKeys
apiStatusMessage
pkixName
pkixAttributeTypeAndValue
pkixAttributeTypeAndValueSET

There was no reason to change the key name here for now.

2024-02-27 13:12 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      - description: The categories serve as identifiers for the API definitions, subsequently enabling the filtering of API listings based on these categories on the API list page.
```suggestion
      - description: API definitions can be assigned to user defined categories, thus allowing APIs to be filtered on the API list page.
```

2024-02-27 13:17 UTC, titpetric commented on tyk-docs/assets/others/gateway-swagger.yml
> +  version: 5.3.0
tyk/oauth/tokens was removed in december 7, no changes since.

2024-02-27 13:22 UTC, titpetric commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +              apis:
Unfortunately out of scope due to the effort required to fix. We will need a technical way to address this, docs from source or source from docs, so we ensure that the definitions match, and not duplicate the effort in documenting them

2024-02-27 13:29 UTC, titpetric commented on tyk-docs/content/shared/gateway-config.md
> +ENV: <b>TYK_GW_STORAGE_MAXVERSION</b><br />
@matiasinsaurralde @sredxny are we still in a position to rename this? It should contain TLS in the key name.

Dashboard has `redis_ssl_min_version`, but this should also be `redis_tls_min_version`.

2024-02-28 10:05 UTC, titpetric commented on tyk-docs/content/shared/dashboard-config.md
> +ENV: <b>TYK_DB_USESHARDEDANLAYTICS</b><br />
filed tx on platform as discussed

2024-02-28 10:09 UTC, titpetric commented on tyk-docs/content/shared/gateway-config.md
> +See more details https://tyk.io/docs/tyk-configuration-reference/kv-store/
Filed a feature request against tyk-config-info-generator:
https://github.com/TykTechnologies/tyk-config-info-generator/issues/7

2024-02-28 10:29 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +VirtualEndpoint contains virtual endpoint configuration.
Unclear, closing

2024-02-28 10:30 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **URLRewriteTrigger**
out of scope (resolving all)

2024-02-28 10:32 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `format` (`string`)**
It's incorrect docs fix, no

2024-02-28 10:44 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +`This API version does not seem to exist` error in this scenario.
New codegen

2024-02-28 10:45 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **VersionToID**
It's moved.

2024-02-28 10:50 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ClientToPolicyMapping contains mappings of Client IDs to Policy IDs.
It's a list of mappings as denoted by the `[]` (list) hint, and each ClientToPolicy is an individual mapping.

"list of mappings" => "mappings".

2024-02-28 11:04 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +RawBodyOnly if set to true, do not fill body in request or response object.
preexisting, no change

2024-02-28 11:15 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the mock response middleware.
Applied the same everywhere

2024-02-28 11:28 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Tyk classic API definition: `custom_middleware.auth_check`.
It's preexisting, you don't

2024-02-28 11:38 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **HMAC**
ctrl+f `**hmac` says yes

2024-02-29 12:19 UTC, dcs3spp commented
@titpetric Closing this PR and have linked to it in the new Dashboard config PR.

2024-02-29 12:19 UTC, closed without merging