[TT-11273] Update documentation for 5.0 LTS
TykTechnologies/tyk-docs-hugo pull request #4153
Opened 2024-02-15 08:04 UTC by buger

Triggered by: lghiur

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: 5.0 LTS
Config info generator branch: main

Note: Docs updates for 5.0.11

JIRA: https://tyktech.atlassian.net/browse/TT-11273

2024-02-22 12:45 UTC, dcs3spp requested changes
@lghiur I have completed the review for 5.0LTS config and OAS schema updates

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +      description: Update Organisation details. This operation will replace the existing Organisation details with those provided in the request payload. It is important to provide the entire object
```suggestion
      description: Update Organisation details. This operation will replace the existing Organisation details with those provided in the request payload. It is important to provide the entire OrganisationDocument object - for example include linked APIs - to avoid overwriting existing data with empty values.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +      description: Update Organisation details. This operation will replace the existing Organisation details with those provided in the request payload. It is important to provide the entire object
Should the version be bumped in this file also and should there be any changes in dashboard-swagger for 5 LTS?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +              apis:
Following the statement given in the description, include full example of sub objects, e.g. languages, login_page etc

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +    ApiDocument:
For each schema type ensure that each property has a description, description and also mention where applicable default value and if it is readonly.

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +that match this path will have the rules defined in the API definition applied.
Is there a way to avoid the line break?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **Upstream**
Have checked, this is not removed and has been included above

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **VersionToID**
Have checked, this is not removed and has been included below

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ParentDataPath is the namespace of the where to find the nested
Is there any way in which the line breaks can be avoided?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -PortDataPath is the port of the data path. In the above nested example, we can see that there is a separate `port` value for the service in the nested JSON. In this case, you can set the `portDataPat
Is there any way in which the line breaks could be avoided?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +UseTargetList should be set to `true`, if you are using load balancing. Tyk will treat the data path as a list and
Is there any way in which the line breaks can be avoided?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +failures are not recovered from quickly enough.
Is there are any way in which the line break can be avoided?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +only provide host and port data. It is important to be able to target a specific resource on that host.
Is there any way in which line break can be avoided?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **ServiceDiscoveryCache**
Have checked and this has not been removed, it is included below

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +MutualTLS holds configuration related to mTLS on APIs, domain to certificate mappings.
```suggestion
MutualTLS holds configuration related to mTLS on APIs, mapping domains to certificates.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **Server**
This is not removed, but has been included above

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **DomainToCertificate**
Is there any way in which this section can be still located here to ease readability adjacent next to Mutual TLS? If not we have it linked to anyway

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as array of `PinnedPublicKey` values, see [PinnedPublicKey](#pinnedpublickey) definition.
Should there be an accompanying field and description here?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **DomainToCertificate**
Should there be equivalent Tyk Classic API fields included here?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **VersionToID**
Should Tyk classic API equivalent fields be included here?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Operations**
Should there be field(s) explanation here?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Strip removes the inbound listen path in the outgoing request. e.g. `http://acme.com/httpbin/get` where `httpbin`
Is there anyway in which the line breaks could be avoided?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `securitySchemes` ([SecuritySchemes](#securityschemes))**
Does it have a Tyk Classic API equivalent?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ClientCertificates holds a list of client certificates which are allowed to make requests against the server.
Are there Tyk Classic API equivalent fields that should be included?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **GatewayTags**
Are there classic API fields that should be included?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Domain**
Are there equivalent Tyk Classic fields that should be included?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Global holds configuration applies globally: CORS and caching.
Plugins was missing in description.
Caching is included in the description but field is missing.

```suggestion
Global holds configuration that applies globally, related to CORS, plugins and caching.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PluginConfig contains the configuration related custom plugin bundles/driver.
```suggestion
PluginConfig contains the configuration related to custom plugins, such as bundles and driver.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CORS contains the configuration related to cross origin resource sharing.
```suggestion
CORS contains the configuration related to Cross Origin Resource Sharing.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Global**
For each field are there Tyk Classic equivalents that should be included in this section?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CustomPluginAuthentication holds configuration for custom plugins.
```suggestion
CustomPluginAuthentication holds configuration for custom plugins authentication.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SecuritySchemes holds security scheme values, filled with Import().
Should there be field descriptions included for this type?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Driver configures which custom plugin to be used.
```suggestion
Driver configures the target language for the custom plugin.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
Is there a way to remove the additional line space here and in occurences in the fields below

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Debug is a boolean flag, If set to `true`, this option produces log files for the CORS middleware.
```suggestion
Debug is a boolean flag. If set to `true`, this option produces log files for the CORS middleware.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +AllowedMethods holds a list of methods to allow access via.
```suggestion
AllowedMethods holds a list of methods to allow access from in inbound requests.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Plugins configures custom plugins to be run on pre authentication stage.
```suggestion
Plugins configures custom plugins to be run on post authentication stage.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Plugins configures custom plugins to be run on post stage.
```suggestion
Plugins configures custom plugins to be run on response stage.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +by explicitly setting the endpoint cache middleware.
Is there any way to avoid the line break and linking to config for endpoint cache middleware?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CacheAllSafeRequests caches responses to (`GET`, `HEAD`, `OPTIONS`) requests overrides per-path cache settings in versions,
Not sure understood. Is versions part of the APIDefinition? So it means that if there are any per-path cache settings included in the versions section of the APIDefinition then they are overridden by this configuration section. Not sure what means by across versions? Overrides all configured per-path cache settings in all versions of config? 

```suggestions
CacheAllSafeRequests caches responses to (`GET`, `HEAD`, `OPTIONS`) requests. This overrides any per-path cache settings that are configured in versions configuration section.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **PinnedPublicKey**
Should there by Tyk Classic equivalents included for these fields?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Provider**
Are there Tyk Classic equivalent fields that can be included?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `clientToPolicyMapping` ([[]ClientToPolicy](#clienttopolicy))**
Is this a mapping of client IDs to policy fields

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `scopeToPolicyMapping` ([[]ScopeToPolicy](#scopetopolicy))**
Is this a list of mappings from scopes to policy IDs?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Scopes**
Are the Tyk Classic equivalent fields that can be provided?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path will be suffixed to `bundle_base_url` in gateway config.
```suggestion
Path will be appended to `bundle_base_url` in gateway config.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path will be suffixed to `bundle_base_url` in gateway config.
is there a Tyk classic equivalent field?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CustomPlugins is a list of CustomPlugin.
```suggestion
CustomPlugins is a list of CustomPlugin instances.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PluginConfigData configures config data for custom plugins.
Could add examples of config data for custom plugins in the description?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **PluginConfigData**
Is there Tyk Classic equivalent fields that can be included in this section?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **ClientToPolicy**
Is there Tyk Classic equivalent fields that can be included in this section?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **ScopeToPolicy**
Is there Tyk Classic equivalent fields that can be included in this section?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CustomPlugin configures custom plugin.
```suggestion
CustomPlugin configures a custom plugin.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the custom pre plugin.
```suggestion
Enabled enables the custom plugin.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path is the path to shared object file in case of gopluign mode or path to js code in case of otto auth plugin.
Removed reference to auth plugin, since the type signifies generic custom plugin configuration.

```suggestion
Path is the path to a shared object file for a Go plugin. Alternatively, for an otto plugin it represents the path to aJS source code file.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **CustomPlugin**
Is there Tyk classic equivalent fields that can be included here?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +FunctionName is the name of authentication method.
```suggestion
FunctionName is the name of the function that implements the plugin.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +RawBodyOnly if set to true, do not fill body in request or response object.
Not sure understand this, does it mean that if this is set to true then the text of the request or response body is not filled in an object property?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +RequireSession is used only with JSVM custom middleware.
Does it also get sent for [gRPC custom middleware](https://tyk.io/docs/plugins/supported-languages/rich-plugins/rich-plugins-data-structures/#sessionstate-session_stateproto)?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **OAuthProvider**
Missing summary description and field descriptions

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SigningMethod to verify signing method used in jwt - allowed values HMAC/RSA/ECDSA.
```suggestion
SigningMethod to verify signing method used in JWT - allowed values HMAC/RSA/ECDSA.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Source is the secret to verify signature, it could be one among:
```suggestion
Source is the secret used to verify the signature. Valid values are:
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **JWTValidation**
Missing summary description. Are there Tyk classic equivalent fields that can be included in this section?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Introspection**
Missing summary description. Is there Tyk Classic equivalent config fields that can be added to this section?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ClientSecret is a secret known only to the client and the authorization server, acquired from the third party.
```suggestion
ClientSecret is a secret known only to the client and the authorisation server, acquired from the third party.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +IdentityBaseField is the key showing where to find the user id in the claims. If it is empty, the `sub` key is looked at.
```suggestion
IdentityBaseField is the key for the field in the claims that contains the user id. If it is empty, the default behaviour is to inspect the `sub` key.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Cache is the caching mechanism for introspection responses.
```suggestion
Cache is the caching mechanism that is used for introspection responses.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **IntrospectionCache**
Missing summary description. Is there Tyk Classic equivalent config fields that can be added to this section?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Timeout is the duration in seconds of how long the cached value stays.
```suggestion
Timeout represents the duration in seconds for how long a values remains in the cache.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **ExternalOAuth**
Missing summary description and field descriptions.

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Allowance**
Are there Tyk classic equivalent fields that can be provided here?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +AllowanceType holds the valid allowance types values.
Could this be expanded to mention the valid type of allowance values?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +AuthSource defines an authentication source.
This type is used to configure an authentication source such as a cookie, token in header field etc?

```suggestion
AuthSource allows an authentication source (cookie, header or query parameter) to be specified and activated.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **AuthSource**
Is there Tyk Classic equivalent fields that can be included?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Basic type holds configuration values related to http basic authentication.
```suggestion
Basic type holds configuration values related to HTTP basic authentication.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ExtractCredentialsFromBody helps to extract username and password from body. In some cases, like dealing with SOAP,
Does this have a Tyk Classic equivalent and can the line break be removed?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path is the path to plugin.
```suggestion
Path is the path to the plugin.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +UserRegexp is the regex for username e.g. `<User>(.*)</User>`.
```suggestion
UserRegexp is the regex used to extract the username e.g. `<User>(.*)</User>`.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PasswordRegexp is the regex for password e.g. `<Password>(.*)</Password>`.
```suggestion
PasswordRegexp is the regex used to extract the password e.g. `<Password>(.*)</Password>`.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **FieldDocError**
Should this type be FieldDocErrors or FieldDocErrorList?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +FieldDocError holds a list of errors.
How is the list of errors used?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +FieldInfo holds details about a field.
What does the field relate to (JSON, database, header field etc.) and are there Tyk classic equivalents that can be included in this section?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +FromOASExamples configures mock responses should be returned from OAS example responses.
```suggestion
FromOASExamples configures mock responses to be returned using OAS example responses.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Header**
Is there Tyk classic equivalents than can be included?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `enabled` (`boolean`)**
Missing description.

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **JWT**
Missing field descriptions.

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +IDPClientIDMappingDisabled prevents Tyk from automatically detecting the use of certain IDPs based on standard claims
Can the line breaks be avoided?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **MockResponse**
Are there Tyk Classic equivalent fields that can be included in this section?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **OAuth**
Missing field descriptions

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Path**
Missing field descriptions

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Plugins configures common settings for each plugin, allowances, transforms, caching and timeouts.
```suggestion
Plugins configures common settings for each plugin, relating to allowances, transforms, caching and timeouts.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **SecurityScheme**
Can there be further fields included and explained in this type?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Signature**
Missing field descriptions

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **StructInfo**
Should this type be included? Is a type related to config docs generation using godoc?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Token holds the values related to authentication tokens.
```suggestion
Token configures behaviour relating to authentication tokens.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Token**
Are there Tyk Classic equivalent fields that can be included?

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **TykExtensionConfigParams**
Missing field descriptions

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +If unset or zero, the response will returned with http status 422 Unprocessable Entity.
```suggestion
If unset or zero, the response will returned with HTTP status 422 Unprocessable Entity.
```

2024-02-22 12:45 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **XTykDoc**
Should this section be included? Is it specific to godoc generation?

2024-03-04 12:48 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **XTykDoc**
https://github.com/TykTechnologies/tyk/pull/6089 Proposal to resolve, needs a review

2024-03-05 11:53 UTC, closed without merging

2024-03-05 11:53 UTC, dcs3spp commented
Closing PR since separate PRs have been created for GW & Dashboard