DX-1122 MDCB 2.4.3 Release notes update
TykTechnologies/tyk-docs-hugo pull request #4166
Opened 2024-02-26 20:05 UTC by carolwkc

## **User description**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

[MDCB-2.4](https://deploy-preview-4166--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-mdcb/release-notes/version-2.4)

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

___

## **Type**
enhancement, documentation

___

## **Description**
- Added 2.4.3 Release Notes to the MDCB documentation.
- Highlighted the resolution of an issue causing partial outages in Tyk Cloud Hybrid gateways due to a blocked stats channel.
- Provided upgrade instructions and download links for the 2.4.3 release.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>version-2.4.md</strong><dd><code>MDCB 2.4.3 Release Notes Update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.4.md
<li>Added 2.4.3 Release Notes section.<br> <li> Detailed the release date, breaking changes, deprecations, upgrade <br>instructions, release highlights, and download links.<br> <li> Included a changelog with a fix for a blockage in the stats channel <br>causing partial outages in Tyk Cloud Hybrid gateways.

</details>
    

  </td>
  <td><a href="https:/TykTechnologies/tyk-docs/pull/4166/files#diff-864186a874168f7c49c27f1dfcc8ca739ae09ca6299354b8f01b0e7089d31e71">+34/-0</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

2024-02-26 20:12 UTC, sredxny approved these changes
lgtm

2024-02-27 10:44 UTC, dcs3spp requested changes
Hi @caroltyk Carol, PR LGTM. Left a comment to update download docker image link. Are there any deprecations, and what are the [dependencies](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2131918959/Guidelines+For+Writing+Tyk+Release+Notes#Dependencies) (3rd party dependencies and compatibility) for MDCB?

2024-02-27 10:44 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.4.md
> +- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-mdcb-docker/v2.4.3/images/sha256-xxxxxx) TBD
Remember to add docker image link for this release

2024-02-27 16:15 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.4.md
> +- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-mdcb-docker/v2.4.3/images/sha256-xxxxxx) TBD
```suggestion
- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-mdcb-docker/v2.4.3/images/sha256-832f461782fbc6182382798a89025b0489f529427521f92683f33df1ebbd4218?context=explore)
```

2024-02-27 16:23 UTC, carolwkc commented
@dcs3spp information updated. It is ready for release once approved.

2024-02-28 12:14 UTC, dcs3spp approved these changes

2024-02-28 12:17 UTC, merged

2024-02-28 12:18 UTC, dcs3spp commented
/release to release-5.2

2024-02-28 12:20 UTC, dcs3spp commented
/release to release-5.1