Update redis docs for 5.3
TykTechnologies/tyk-docs-hugo pull request #4167
Opened 2024-02-26 23:30 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

1. Add Redis v7 version support
2. Update docs on redis sentinel
3. Update docs on redis connection over SSL/TLS

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-02-27 11:12 UTC, dcs3spp approved these changes
@caroltyk PR LGTM and I have approved the PR. I left a comment/suggestion for adding an example of _use_ssl: true_. Once peer reviews approved will merge and release.

2024-02-27 11:12 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-sentinel.md
> +`"use_ssl": true` alongside any Redis configuration settings within Tyk's config files.
Is it worthwhile adding an example for use_ssl true in a configuration file:

```suggestion
`"use_ssl": true` alongside any Redis configuration settings within Tyk's config files. An example within the Gateway configuration is listed below:

```json
"storage": {
  "type": "redis",
  "addrs": [
    "server1:26379",
    "server2:26379",
    "server3:26379"
  ],
  "master_name": "mymaster",
  "username": "",
  "password": "",
  "database": 0,
  "optimisation_max_idle": 2000,
  "optimisation_max_active": 4000,
  "use_ssl": true
}
```
```

2024-02-27 13:09 UTC, caroltyk commented
@mativm02 please add docs for Redis SSL configurations

2024-02-28 09:54 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-sentinel.md
> +As we do support Amazon ElastiCache, we recommend using this with Redis Sentinel. For more details on Amazon ElastiCache, see [here](https://aws.amazon.com/elasticache/).
I realise this was copied from another paragraph but this sentence is a little unclear for me.  It reads like we are suggesting Sentinel is the preferred/recommended configuration for Elasticache.  I could be wrong but don't think Elasticache supports Sentinel architecture - it has cluster mode but no concept of sentinels to my knowledge

2024-02-28 09:54 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-sentinel.md
> +[SSL/TLS](https://redis.io/topics/encryption) is supported by Redis starting with version 6 as an optional feature that needs to be enabled at compile time. Should you wish to turn on encryption betw
Suggest we also mention that TLS is supported on Amazon ElastiCache as well

2024-02-28 13:27 UTC, mativm02 commented on tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-sentinel.md
> +As we do support Amazon ElastiCache, we recommend using this with Redis Sentinel. For more details on Amazon ElastiCache, see [here](https://aws.amazon.com/elasticache/).
@rewsmith Indeed, I haven't found any docs saying that ElastiCache supports Sentinel architecture. I'd delete this paragraph.

2024-02-28 13:30 UTC, mativm02 commented
@dcs3spp @caroltyk @rewsmith I've updated the docs with more info + suggested comments - could you take a look at it again, please?

2024-02-28 15:16 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-sentinel.md
> +[SSL/TLS](https://redis.io/topics/encryption) is supported by Redis starting with version 6 as an optional feature that needs to be enabled at compile time. Should you wish to turn on encryption betw
Ignore this comment as ElastiCache doesn't offer a sentinel based architecture

2024-02-28 15:16 UTC, rewsmith approved these changes
LGTM

2024-02-28 15:21 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-cluster.md
>  ### Redis Encryption
Should this part be moved to "Redis Cluster with TLS" section above?

2024-02-28 15:26 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-cluster.md
>  ### Redis Encryption
Thats a good call.  Maybe it should be pulled out into a separate page and then both the Redis Cluster and Redis Sentinel pages reference it.  Otherwise we'd have to duplicate content .  Not sure why the Cluster page has sections for `Redis Cluster with TLS` and `Redis Encryption`

2024-02-29 13:11 UTC, mativm02 commented on tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-cluster.md
>  ### Redis Encryption
@caroltyk I removed the redundant title and moved its content.

@rewsmith Yes, I thought that, but the content differs a little bit between pages (for example, the sentinel one doesn't mention ElastiCache)

2024-02-29 19:00 UTC, dcs3spp requested changes
@caroltyk Thanks for submitting PR. I have added preview links.

Could you please raise a Jira ticket for the PR and add the ticket ID to the PR title.
 
Redis Sentinel page menu requires right nav menu [headings](https://deploy-preview-4167--tyk-docs.netlify.app/docs/nightly/tyk-stack/tyk-gateway/configuration/redis-sentinel/) displayed correctly

2024-02-29 19:02 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-cluster.md
>  ### Redis Encryption
@caroltyk @mativm02 @rewsmith Might be able to refactor in a separate iteration if possible?

2024-03-01 12:51 UTC, mativm02 commented
@dcs3spp good catch! 

I've fixed the right nav issue and added a link to the Jira ticket. Thanks!

2024-03-01 12:54 UTC, mativm02 approved these changes

2024-03-05 16:14 UTC, dcs3spp approved these changes

2024-03-05 16:18 UTC, merged