[TT-11185] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #4176
Opened 2024-02-28 13:50 UTC by buger

Triggered by: titpetric

Included:

Tyk Gateway: false
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: master
Config info generator branch: 

Note: TT-11185, DX-1104, dashboard only (branch suffix: docs-dashboard)

JIRA: https://tyktech.atlassian.net/browse/TT-11185

2024-02-28 14:16 UTC, titpetric commented
@dcs3spp this one addresses the dashboard feedback in scope. One part of raised up feedback is still in progress via the following PRs:

- https://github.com/TykTechnologies/tyk-analytics/pull/3766
- https://github.com/TykTechnologies/tyk/pull/6078

When those two are merged to release-5.3.0, we can retrigger this and merge.

Please review this for critical issues only, as the previous review has been extensive. Notable changes include:

- propper naming for some redis config options (gateway and dashboard, still in flight)
- fixes for tags references in swagger docs, indenting
- various improvements of config field docs,
- various suggested fixes by simon (no-oxford-comma, text rewordings, grammar, typos, i applied most as they were)

The tyk-docs action has been updated to:

- enable adding a branch suffix for PRs, so we can open multiple against same jira ticket (dashboard, gateway), this will make review easier due to more explicit scopes,
- updated the PR action to a newer version, as the old one did not update PR anymore (fix),
- minor PR description updates, added info about the source branch (release-5.3.0)

2024-02-29 12:10 UTC, dcs3spp requested changes
Thanks @titpetric for raising Dashboard changes in a separate PR which makes reviewing easier! 

I have reviewed only the changes as suggested in the PR description. For the dashboard OAS files I also made some minor suggestions for refining some OAS endpoints description and capitalising OAS endpoint / attribute descriptions in PR https://github.com/TykTechnologies/tyk-docs/pull/4152.

I will close the previous PR (https://github.com/TykTechnologies/tyk-docs/pull/4152).Can you raise a Jira ticket in the DX space and add to PR description?

2024-02-29 12:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      type: boolean
Will this be a breaking change for existing clients who have generated SDKs and using string values "true" or "false"? Should this change be documented in release notes?

2024-02-29 12:10 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      description: Enable/disable the authentication mechanism in your Tyk Gateway for your OAS API
Is this the correct description and schema reference for TemplateID?

2024-02-29 12:10 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
> +a connection to redis, Tyk will use this to verify server certificates.
```suggestion
a connection to Redis, Tyk will use this to verify server certificates.
```

2024-02-29 12:10 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
> +The certificate is presented when establishing a connection to redis.
```suggestion
The certificate is presented when establishing a connection to Redis.
```

2024-02-29 12:10 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
> +The certificate is presented when establishing a connection to redis.
```suggestion
The certificate is presented when establishing a connection to Redis.
```

2024-03-01 14:38 UTC, titpetric commented on tyk-docs/content/shared/dashboard-config.md
> +The certificate is presented when establishing a connection to redis.
https://tyktech.atlassian.net/browse/TT-11421, resolving this and similar comments as out of scope.

2024-03-01 14:40 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      description: Enable/disable the authentication mechanism in your Tyk Gateway for your OAS API
https://github.com/TykTechnologies/tyk-analytics/pull/3777 follow up, if you can PTAL as a correction.

2024-03-01 15:26 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      type: boolean
I'm very ambivalent, I feel it could be omitted as it's a correction that comes with a minor 5.3 release. If we have an upgrade notes, we can explicitly mention that client SDKs should be regenerated to get updates to schema and new functionality. It's a permanent entry in such a release notes section :)

2024-03-04 08:26 UTC, titpetric commented
@dcs3spp latest swagger schema updated

2024-03-04 13:20 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +      type: boolean
Good call @titpetric

2024-03-05 10:13 UTC, dcs3spp approved these changes
PR LGTM, requires peer review before merge and release

2024-03-19 16:01 UTC, dcs3spp commented
@titpetric I have approved would you be able to approve also and I will merge to main branch

2024-03-19 16:02 UTC, dcs3spp commented
@titpetric I have approved PR, would you be able to approve also and I will merge to main branch

2024-03-21 14:00 UTC, andyo-tyk reviewed
I've suggested some changes for incorrect use of the term "OAS" in comments in the dashboard-swagger file - however for expediency, if these require changes to the source code, we can fix these in a later patch.

2024-03-21 14:00 UTC, andyo-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                The content of the file should be the OAS document in JSON format (without x-tyk-api-gateway extension).
```suggestion
                The content of the file should be the OpenAPI document in JSON format (without x-tyk-api-gateway extension).
```

2024-03-21 14:00 UTC, andyo-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        For use with an existing OAS API document that you want to expose via your Tyk Gateway. (New)
```suggestion
        For use with an existing OpenAPI document that you want to expose via your Tyk Gateway. (New)
```

2024-03-21 14:00 UTC, andyo-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        Create a new Tyk OAS format API from a generic OAS (OpenAPI Spec) document (without `x-tyk-gateway` extension).
```suggestion
        Create a new Tyk OAS API from an OpenAPI document.
```

2024-03-21 14:00 UTC, andyo-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        The payload can contain either a fully fledged OAS document or an URL pointing to an OAS document.
```suggestion
        The payload can contain either a fully fledged OpenAPI document or a URL pointing to an OpenAPI document.
```

2024-03-21 14:00 UTC, andyo-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +          description: The URL from which to import the OAS definition.
```suggestion
          description: The URL from which to import the OpenAPI document.
```

2024-03-21 14:33 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        For use with an existing OpenAPI document that you want to expose via your Tyk Gateway. (New)
```suggestion
        For use with an existing OpenAPI document that you want to expose via your Tyk Gateway.
```

2024-03-21 14:34 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        Create a new Tyk OAS API from an OpenAPI document.
```suggestion
        Create a new Tyk OAS API from an OpenAPI document (without x-tyk-api-gateway extension).
```

2024-03-21 14:35 UTC, titpetric commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        Create a new Tyk OAS API from an OpenAPI document (without x-tyk-api-gateway extension).
```suggestion
        Create a new Tyk OAS API from an OpenAPI document in JSON format (without x-tyk-api-gateway extension).
```

2024-03-22 09:03 UTC, andyo-tyk approved these changes
LGTM, thanks.

2024-03-22 11:30 UTC, merged