Updated analytics pages and middleware
TykTechnologies/tyk-docs-hugo pull request #4177
Opened 2024-02-28 15:11 UTC by andyo-tyk

### Preview Link

### Description
Added documentation of the track and do-not-track middleware
This led to improvements to the explanations of analytics generation (in Gateway) and display (in Dashboard)
Moved some pages to more appropriate locations in the docs

2024-02-28 16:02 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-classic.md
> +                "method": "GET",
```suggestion
                "method": "GET"
```

2024-02-29 17:20 UTC, dcs3spp requested changes
Thanks @andyo-tyk for updating the analytics content!!!

I have reviewed some of the content with minor suggestions. I know you already explained about images/video etc. I will review the remaining content next week.

As you mentioned yesterday a peer review is also required

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint.md
> +date: 2017-03-24T15:49:11Z
update date in front matter header

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint.md
> +To get a tabular view of how your API traffic is performing at the endpoint level, you can select the Activity by endpoint option in the navigation and see a tabular view of your API endpoints. This
```suggestion
To get a tabular view of how your API traffic is performing at the endpoint level, you can select the Activity by Endpoint option in the navigation and see a tabular view of your API endpoints. This table will list your API endpoints by their traffic volume and you’ll be able to see when they were last accessed:
```

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint.md
> +In this example the track endpoint middleware has been configured for HTTP `GET` requests to the `/anything` endpoint. Any such calls will appear in the Endpoint Popularity analytics.
```suggestion
In this example the track endpoint middleware has been configured for HTTP `GET` requests to the `/anything` endpoint. These requests will appear in the Endpoint Popularity analytics within the Dashboard.
```

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint.md
> + < placeholder for video >
Remember to add placeholder video

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint.md
> +### Selecting Tyk Classic APIs endpoints to be tracked
```suggestion
### Selecting Tyk Classic API endpoints to be tracked 
```

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint.md
> +In this example the track endpoint middleware has been configured for HTTP `GET` requests to the `/anything` endpoint. Any such calls will appear in the Endpoint Popularity analytics.
```suggestion
In this example the track endpoint middleware has been configured for HTTP `GET` requests to the `/anything` endpoint. These requests will appear in the Endpoint Popularity analytics area in the Dashboard.
```

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint.md
> +#### Step 1: Add an endpoint for the path and select the plugin
```suggestion
##### Step 1: Add an endpoint for the path and select the plugin
```

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint.md
> +#### Step 2: Save the API
```suggestion
##### Step 2: Save the API
```

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +i.e. Tyk will first check whether the API definition has detailed recording enabled to determine whether to log the request and response bodies. If it does not, then it will check the key being used
```suggestion
Consequently, Tyk will first check whether the API definition has detailed recording enabled to determine whether to log the request and response bodies. If it does not, then it will check the key being used in the request and finally it will check the Gateway configuration.
```

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +Tyk Cloud users can enable detailed recording per-API following the instructions on this page or, if required at the Gateway level, via a support request. The traffic analytics are subject to the sub
Is there a link that could be added to Tyk Cloud helpdesk support?

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +< placeholder for image >
Remember to add image here

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +< placeholder for image >
Remember to add image here

2024-02-29 17:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +```
Could give a JSON fragment here or link to an existing page?

2024-03-05 10:04 UTC, dcs3spp requested changes
Thanks for updating the analytics and middle ware pages Andy. PR LGTM, made some minor suggestions and peer review required before merge and release.

Is it worthwhile briefly mentioning performance configurations related to analytics:
- Using [analytics_config.enable_multiple_analytics_keys](https://deploy-preview-4018--tyk-docs.netlify.app/docs/nightly/tyk-oss-gateway/configuration/#analytics_configenable_multiple_analytics_keys) to distribute keys to nodes in a Redis cluster?
- Using a separate storage for analytics in high traffic systems https://tyk.io/docs/tyk-stack/tyk-pump/separated-analytics-storage/

2024-03-05 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/logging-api-traffic.md
> +The transaction records generated by the gateway are stored in Redis, from which Tyk Pump can be configured to transfer them to the desired persistent storage. When using Tyk Dashboard, the [Aggregat
```suggestion
The transaction records generated by the Gateway are stored in Redis, from which Tyk Pump can be configured to transfer them to the desired persistent storage. When using Tyk Dashboard, the [Aggregate Pump]({{< ref "tyk-pump/configuration#tyk-dashboard">}}) can be used to collate aggregated data that is presented in the [analytics]({{< ref "tyk-dashboard-analytics">}}) screens of the Tyk Dashboard.
```

2024-03-05 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-middleware.md
> +You can enable the do-not-track middleware on whichever endpoints for which you do not want to generate logs. This will instruct the Gateway not to generate any transaction records for those endpoint
```suggestion
You can enable the do-not-track middleware on whichever endpoints for which you do not want to generate logs. This will instruct the Gateway not to generate any transaction records for those endpoints or APIs. As no record of these transactions will be generated by the Gateway, there will be nothing created in Redis and hence nothing for the pumps to transfer to the persistent storage and these endpoints will not show traffic in the Dashboard's analytics screens.
```

2024-03-05 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-middleware.md
> +<!-- proposed "summary box" to be shown graphically on each middleware page
Remember to add summary box

2024-03-05 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-middleware.md
> +When [transaction logging]({{< ref "product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/logging-api-traffic" >}}) is enabled in the Tyk Gateway, a transaction record will be gener
Add link to do-not-track middleware

2024-03-05 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-classic.md
> +The [Do-Not-Track]({{< ref "product-stack/tyk-gateway/middleware/do-not-track-middleware" >}}) middleware provides the facility to disable generation of transaction records (which are used to track r
Ensure case consistency for do-not-track

2024-03-05 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-oas.md
> +When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}) either manually within the `.json` file
```suggestion
When working with Tyk OAS APIs the middleware is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}), either manually, within the `.json` file, or from the API Designer in the Tyk Dashboard.
```

2024-03-05 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-oas.md
> + < placeholder for video >
Remember to add video

2024-03-05 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/logging-api-traffic.md
> +You can suppress the generation of transaction records for any endpoint by enabling the [do-not-track middleware]({{< ref "product-stack/tyk-gateway/middleware/do-not-track-middleware" >}}) for that
Is it worthwhile briefly mentioning performance of analytics somewhere here? For example:
- Using [analytics_config.enable_multiple_analytics_keys](https://deploy-preview-4018--tyk-docs.netlify.app/docs/nightly/tyk-oss-gateway/configuration/#analytics_configenable_multiple_analytics_keys) to distribute keys to nodes in a Redis cluster? 
- Using a separate storage for analytics in high traffic systems https://tyk.io/docs/tyk-stack/tyk-pump/separated-analytics-storage/

2024-03-15 14:23 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +An alternative approach to controlling detailed recording is to enable only for specific [access keys]({{< ref "getting-started/key-concepts/what-is-a-session-object" >}}). This is particularly usefu
shouldn't there be an "it" after "enable" ?

2024-03-15 14:25 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +This will enable detailed recording only for API transactions where the key is used in the request.
"API transaction" sounds a bit wrong to me; maybe "API calls" ?

2024-03-15 14:33 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-oas.md
> +The design of the Tyk OAS API Definition takes advantage of the `operationID` defined in the OpenAPI Document that declares both the path and method for which the middleware should be added.
casing of "operationID" should be "operationId" to comply with examples and code

2024-03-15 14:35 UTC, andrei-tyk commented on tyk-docs/content/tyk-dashboard-analytics.md
> +In Tyk v5.1 (and LTS patches v4.0.14 and v5.0.3) we introduced [User Owned Analytics]({{< ref "basic-config-and-security/security/dashboard/user-roles#user-owned-analytics" >}}) which can be used to
the sentence "Due to the way that the analytics data are aggregated, not all statistics can be filtered by API and so may be inaccessible to users with the Owned Analytics permission." is confusing me. should it be "inaccessible to users without the Owned Analytics permission"?

2024-03-19 11:04 UTC, dcs3spp commented
@andyo-tyk I've resolved most comments, comments remaining relate to adding link, case consistency for do-not-track, [question](https://github.com/TykTechnologies/tyk-docs/pull/4177#discussion_r1512544634) and reminder to add placeholder video and images

2024-03-27 18:17 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-classic.md
> +                "method": "GET",
I'll apply this in wider update

2024-03-27 18:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +Tyk Cloud users can enable detailed recording per-API following the instructions on this page or, if required at the Gateway level, via a support request. The traffic analytics are subject to the sub
I don't know - do we have one elsewhere in the docs? Can we consider adding this in a future PR, so as to get this update out?

2024-03-27 19:05 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +```
There's a link to the keys section of the docs in the paragraph above

2024-03-27 19:05 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
> +This will enable detailed recording only for API transactions where the key is used in the request.
A transaction is request & response -> and we log both parts

2024-03-27 19:11 UTC, andyo-tyk reviewed
Explained reasons for not making changes in response to review comments

2024-03-27 19:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/logging-api-traffic.md
> +You can suppress the generation of transaction records for any endpoint by enabling the [do-not-track middleware]({{< ref "product-stack/tyk-gateway/middleware/do-not-track-middleware" >}}) for that
This is just a restructure of the existing docs (and adding detail on the middleware). Yes, should be added but that ought to be planned to ensure the information is accurate and useful.

2024-03-27 19:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-middleware.md
> +When [transaction logging]({{< ref "product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/logging-api-traffic" >}}) is enabled in the Tyk Gateway, a transaction record will be gener
I don't understand.... this is the do-not-track middleware page.

2024-03-27 19:11 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-classic.md
> +The [Do-Not-Track]({{< ref "product-stack/tyk-gateway/middleware/do-not-track-middleware" >}}) middleware provides the facility to disable generation of transaction records (which are used to track r
Here it is capitalised because it is the name of the middleware

2024-03-27 19:11 UTC, andyo-tyk commented on tyk-docs/content/tyk-dashboard-analytics.md
> +In Tyk v5.1 (and LTS patches v4.0.14 and v5.0.3) we introduced [User Owned Analytics]({{< ref "basic-config-and-security/security/dashboard/user-roles#user-owned-analytics" >}}) which can be used to
No - the point is that "Owned Analytics" doesn't grant access to ALL aggregated data because of the way the aggregation works (we cannot split out just the owned APIs)

2024-03-27 23:04 UTC, andrei-tyk approved these changes

2024-03-28 12:20 UTC, dcs3spp approved these changes
@andyo-tyk PR LGTM

2024-03-28 14:49 UTC, merged