Updated virtual endpoint and JS docs
TykTechnologies/tyk-docs-hugo pull request #4186
Opened 2024-03-01 14:08 UTC by andyo-tyk

### Preview Link

### Description
Updated Virtual Endpoint documentation to include Tyk OAS.
This led to a restructuring / tidy-up of both Virtual Endpoint and JavaScript pages

2024-03-01 21:52 UTC, JRWu commented
Any chance we could also mention what JavaScript version is supported in the Javascript Middleware section?

2024-03-04 12:17 UTC, andyo-tyk reviewed
Adjusted for new contract

2024-03-04 12:17 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
> + - `name`: the name of the JavaScript function that will be executed when the virtual endpoint is triggered
```suggestion
 - `functionName`: the name of the JavaScript function that will be executed when the virtual endpoint is triggered
```

2024-03-04 12:17 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
> +                        "name": "myVirtualHandler",
```suggestion
                        "functionName": "myVirtualHandler",
```

2024-03-04 12:20 UTC, andyo-tyk commented on tyk-docs/content/plugins/supported-languages/javascript-middleware.md
> +Before you can use JavaScript customisation in any component you will need to enable the JSVM.
```suggestion
The JavaScript Virtual Machine (JSVM) provided in the Gateway is a traditional ECMAScript5 compatible environment.

Before you can use JavaScript customisation in any component you will need to enable the JSVM.
```

2024-03-04 12:22 UTC, andyo-tyk commented
> Any chance we could also mention what JavaScript version is supported in the Javascript Middleware section?

@JRWu I've added a line in the javascsript_middleware page, where we give the instruction on how to enable the JSVM.

2024-03-05 11:58 UTC, dcs3spp commented
@Andy can you raise a Jira ticket in DX space and add link in PR title and description

2024-03-05 12:41 UTC, andyo-tyk commented
> @andyo-tyk can you raise a Jira ticket in DX space and add link in PR title and description

I created a ticket at the time, but evidently Github didn't save the updated title, I'll add it again.

2024-03-05 16:02 UTC, dcs3spp requested changes
Thanks for updating the virtual endpoint & JS documentation Andy. PR LGTM and will require peer approval before release.

Nice! I notice that an alias has been setup for the removed sample-batch-funtion.md file.  Has the file been deleted?

Has an alias also been setup for the install-middleware.md file and have existing links to that file been updated to refer to the new content file?

CI status error relates to this path /advanced-configuration/compose-apis not existing in the menu.yaml

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +  - /advanced-configuration/compose-apis/sample-batch-funtion/
Nice! I noticed that you have added an alias since the sample-batch-function.md has been removed

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +1. Enable the Virtual Endpoint middleware on an endpoint of your API and paste this JavaScript into the API Designer (or save in a file and reference it from the middleware config):
Is there a link to existing content that can be used to show virtual endpoint in middleware config?

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +  log("param-1: " + request.Params["param1"]) // case matters
```suggestion
  log("param-1: " + request.Params["param1"]) // case sensitive
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +  log("auth Header: " + request.Headers["Authorization"]) // case matters
```suggestion
  log("auth Header: " + request.Headers["Authorization"]) // case sensitive
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +log("Virtual Test initialised")
Is this valid, since it is outside of the JS function?

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +```
Should it also include log message "Virtual Test initialised"?

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +```{.json}
```suggestion
```json
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +```.js
```suggestion
```js
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +2. Enable the Virtual Endpoint middleware on an endpoint of your API and paste this JavaScript into the API Designer (or save in a file and reference it from the middleware config):
Is there an example middleware config can link to or add here for saving in a file and referencing in middleware config? Is the procedure for Tyk OAS endpoint the same?

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +Create a new Tyk Classic API using that API definition and then run the following command to send a request to the API endpoint where the :
Sentence incomplete

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/sample-batch-funtion.md
> ----
Double checking, the file has been deleted, yes?

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/virtual-endpoints.md
> +From a virtual endpoint, you can make calls out to other internal and upstream APIs. You can then aggregate and process the responses, returning a single response object to the originating client. Th
```suggestion
From a virtual endpoint, you can make calls out to other internal and upstream APIs. You can then aggregate and process the responses, returning a single response object to the originating client. This allows you to configure a single externally facing API to simplify interaction with multiple internal services, leaving the heavy lifting to Tyk rather than starting up an aggregation service within your stack.
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/virtual-endpoints.md
> +#### Dynamic Routing
```suggestion
#### Dynamic routing
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/compose-apis/virtual-endpoints.md
> +<!-- proposed "summary box" to be shown graphically on each middleware page
Remember to add this later

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware.md
> +2. **Dynamic event handlers**: These components fire on certain API events (see the event handlers section), these are fired Async and do not have a cooldown timer. These are documented [here]({{< re
add link to event handlers section

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-classic.md
> +If we set `proxy_on_error` to `true` and keep the error in the Javascript, the request will be forwarded to the upstream and Tyk will return the response received that service.
```suggestion
If we set `proxy_on_error` to `true` and keep the error in the Javascript, the request will be forwarded to the upstream and Tyk will return the response received from that service. 
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
> + - `proxyOnError`: [optional] a boolean that determines the behaviour of the gateway if an error occurs during the execution of the virtual endpoint's function; if set to `true` the request will be p
```suggestion
 - `proxyOnError`: [optional] a boolean that determines the behaviour of the gateway if an error occurs during the execution of the virtual endpoint's function; if set to `true` the request will be proxied to upstream if the function errors, if set to `false` the request will not be proxied and Tyk will return an error response. Defaults to `false`
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
> + - `requireSession`: [optional] a boolean that indicates whether the virtual endpoint should have access to the session object; if `true` then the key session data will be provided to the function as
```suggestion
 - `requireSession`: [optional] a boolean that indicates whether the virtual endpoint should have access to the session object; if `true` then the key session data will be provided to the function as the `session` variable. Defaults to `false`
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
> +``` .json
```suggestion
```json
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
> +``` .js
```suggestion
```js
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +Tyk injects a `TykJS` namespace into the JSVM, this namespace can be used to initialise a new middleware component. The JS for each middleware component should be in its own `*.js` file.
```suggestion
Tyk injects a `TykJS` namespace into the JSVM, which can be used to initialise a new middleware component. The JS for each middleware component should be in its own `*.js` file.
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> + - For Custom JS plugins and Dynamic Event Handlers, the filename of the file containing the source code must match the function name
```suggestion
 - For Custom JS plugins and Dynamic Event Handlers, the source code filename must match the function name
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +``` .js
```suggestion
```js
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +### Returning from the middleware
```suggestion
### Returning data from the middleware
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +#### Returning from Custom JS plugin
```suggestion
#### Returning data from Custom JS plugin
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +#### Returning from Virtual Endpoint
```suggestion
#### Returning data from a Virtual Endpoint
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +``` .go
```suggestion
```go
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +- `DeleteParams`: these parameters will be removed from the request as they pass through the middleware; note `DeleteParams` happens before `AddParams`
Could the order be changed so that this list item appears before the AddParams list item?

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +- `ReturnOverrides`: values stored here are used to stop or halt middleware execution and return an error code
Could it also be used to return a mock response?

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +Tyk uses an internal [session object]({{< ref "getting-started/key-concepts/what-is-a-session-object" >}}) to handle the quota, rate limits, access allowances and auth data of a specific key. JS midd
```suggestion
Tyk uses an internal [session object]({{< ref "getting-started/key-concepts/what-is-a-session-object" >}}) to handle the quota, rate limits, access allowances and auth data of a specific key. JS middleware can be granted access to the session object but there is also the option to disable it as deserialising it into the JSVM is computationally expensive and can add latency. Other than the `meta_data` field, the session object itself cannot be directly edited as it is crucial to the correct functioning of Tyk.
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> + - Custom JS plugins at the [pre-]({{< ref "" >}}) stage do not have access to the session object (as it has not been created yet)
Missing ref link

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +A new JSVM instance is created for _each_ API that is managed, this means that inter-API communication is not possible via shared methods (they have different bounds), however it _is_ possible using
```suggestion
A new JSVM instance is created for _each_ API that is managed. Consequently, inter-API communication is not possible via shared methods, since they have different bounds. However, it _is_ possible using the session object if a key is shared across APIs.
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +In addition to our Tyk JavaScript API functions, you also have access to all the functions from the http://underscorejs.org/ library.
```suggestion
In addition to our Tyk JavaScript API functions, you also have access to all the functions from the [underscore](http://underscorejs.org) library.
```

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +In this basic example, we show the creation and initialisation of a middleware object. Note how the three Tyk data objects (`request`, `session`, `config`) are made available to the function and the
Explain what the two objects represent that are returned from the function

2024-03-05 16:02 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-classic.md
> +``` {linenos=true, linenostart=1}
Can use ```bash or ```console here?

2024-03-05 16:03 UTC, dcs3spp reviewed
@andyo-tyk Is this related to 5.3 only?

2024-03-05 17:28 UTC, andyo-tyk commented
> @andyo-tyk Is this related to 5.3 only?

As with all of these PRs, some is strictly 5.3, most is general improvement to the docs - but we should release together with 5.3

2024-03-19 11:30 UTC, dcs3spp commented
@andyo-tyk I have resolved most comments. Comments remaining are questions and other comments relate to incomplete sentence, missing ref links, [potential code and logging error](https://github.com/TykTechnologies/tyk-docs/pull/4186#discussion_r1512977779)  and adding link to event handler section

2024-03-19 20:06 UTC, JRWu reviewed
LGTM, no changes required from me beyond what Simon commented on. I primarily reviewed styling & content- did not get a chance to test every example and flavour of the supplied JS code.

2024-03-22 15:29 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-classic.md
> +``` {linenos=true, linenostart=1}
used `http` as it's a HTTP request being highlighted

2024-03-22 16:44 UTC, titpetric commented on tyk-docs/assets/img/dashboard/endpoint-designer/virtual-endpoint-inline.png
@andyo-tyk can you update this screenshot with the corrected API definition? The code snippet had a double-space, which was modified in the markdown ; I've chosen to update the example apidef to match the code block.

2024-03-22 17:21 UTC, titpetric commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +log("Virtual Test initialised")
yes, documented in javascript-api.md

2024-03-22 17:22 UTC, titpetric commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +```
No, that only happens once, this is just a request/response example. The initialization will be higher up in the logs. I wouldn't add it in the example

2024-03-22 17:32 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
> +                                " key": 3
@andyo-tyk do we want to remove the space in the example? It checks out, usually json keys however don't include spaces; would also need a correction on L113

2024-03-22 17:35 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
> +                        "body": "ZnVuY3Rpb24gbXlWaXJ0dWFsSGFuZGxlciAocmVxdWVzdCwgc2Vzc2lvbiwgY29uZmlnKSB7ICAgICAgCiAgdmFyIHJlc3BvbnNlT2JqZWN0ID0gewogICAgQm9keTogIlZpcnR1YWwgRW5kcG9pbnQgIitjb25maWcuY2
Function has been corrected to match code example on L123

2024-03-22 17:36 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-classic.md
> +                "function_source_uri": "ZnVuY3Rpb24gbXlVbmlxdWVGdW5jdGlvbk5hbWUocmVxdWVzdCwgc2Vzc2lvbiwgY29uZmlnKSB7CiB2YXIgcmVzcG9uc2VPYmplY3QgPSB7IAogIEJvZHk6ICJUSElTIElTIEEgVklSVFVBTCBSRVNQT05TRSI
Function has been corrected to match code example given on L60; and response example on L71.
This requires updating a screenshot to match.

2024-03-22 18:19 UTC, titpetric commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +There are also more specialised goodies, including:
Goodies doesn't seem like a technical term.

```suggestion
There are also more specialised helpers available, including:
```

2024-03-22 18:33 UTC, titpetric approved these changes
Technical review of the contents checks out, left a few comments due to minor corrections.

In addition to the technical review, I've made some reasonable formatting changes:

- made sure the code blocks are syntax highlighted properly, it was a mess
- whitespace improvements around headings, lists, paragraphs
- removed x-ratelimit header responses for less noisy examples

Logged the automation scripts for it in a PR #4321 so the same formatting can be enforced/applied to existing docs in the future. Each automated change was carefully reviewed to not degrade the docs.

2024-03-31 14:27 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
> +1. Enable the Virtual Endpoint middleware on an endpoint of your API and paste this JavaScript into the API Designer (or save in a file and reference it from the middleware config):
I've added links to the instructions for Tyk Classic and Tyk OAS APIs.

2024-03-31 14:32 UTC, andyo-tyk commented on tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
> +In this basic example, we show the creation and initialisation of a middleware object. Note how the three Tyk data objects (`request`, `session`, `config`) are made available to the function and the
I agree this needs to be added, but as part of a wider update to these pages - the scope for this PR was simply to improve the structure of the docs as part of the Virtual Endpoint middleware for Tyk OAS.

2024-04-03 09:43 UTC, dcs3spp approved these changes
@andyo-tyk PR LGTM. @JRWu would you be able to peer review changes made and approve if then ok? Then will merge ready for release

2024-04-03 14:06 UTC, dcs3spp commented
Merging PR, GHub web interface does not display the outdated conversations for resolving.

2024-04-03 14:07 UTC, merged