Edp 1.8.4 docs
TykTechnologies/tyk-docs-hugo pull request #4187
Opened 2024-03-01 19:49 UTC by slega

### For internal users - Please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/TT-11278
<br>

---

### Preview Link

<br>

### Description
- Release notes for 1.8.4.
- Updated OAS for the portal.
- Update documentation for the email customization section.
- Update the env vars configuration section.
- Update documentation for the custom attributes for the User model.
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2024-03-04 13:15 UTC, dcs3spp commented
@slega Could you raise a Jira ticket in the DX space so that this can be reviewed

2024-03-05 18:09 UTC, dcs3spp requested changes
PR LGTM, have made minor suggestions. Could you also arrange a peer review

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +        - description: If set to true, will force user deletion of the user and all their applications and credentials and ignore any errors from the credential providers such as OAuth2.0 IdPs and Ty
```suggestion
If set to true, will force deletion of the user with all their applications and credentials and ignore any errors from the credential providers such as OAuth2.0 IDPs and Tyk Dashboard.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: Markdown version of content for this content block
```suggestion
          description: Markdown content for this content block
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +          description: If true, the portal will display the markdown version of content of this content block.
```suggestion
          description: If true, the portal will display the markdown for this content block.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
> +**Description**: Controls the value of the `SameStie` attribute for the portal’s cookie. The portal adds the `SameStie` attribute with the value specified in `PORTAL_SESSION_SAMESITE` to the `Set-Coo
```suggestion
**Description**: Controls the value of the `SameSite` attribute for the portal’s cookie. The portal adds the `SameStie` attribute with the value specified in `PORTAL_SESSION_SAMESITE` to the `Set-Cookie` header in all responses from the portal's backend, except for the admin APIs.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +In this section, you will learn how to customize the User model and the sign-up form for your API consumers.
```suggestion
In this section, you will learn how to customise the User model and the sign-up form for your API consumers.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +Customizing the User model enables the storage of custom data attributes in the User profile.
```suggestion
Customising the User model enables the storage of custom data attributes in the User profile.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +For example, it is particularly useful when the quota for API calls needs to be distributed among all developers of consumer organizations.
```suggestion
For example, it is particularly useful when the quota for API calls needs to be distributed among all developers of consumer organisations.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +To customise the User model by adding new data attributes to it, navigate to the **Custom attributes** menu and the select the **User** model. Currently, it is possible to extend only the User model.
```suggestion
To customise the User model by adding new data attributes to it, navigate to the **Custom attributes** menu and then select the **User** model. Currently, it is possible to extend only the User model. In future releases we will add the same capabilities to other models.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +Exercise caution when dealing with personally identifiable information (PII). The available default attributes include:
```suggestion
Exercise caution when dealing with personally identifiable information (PII). Additional default attributes include:
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +| Teams name        | TeamNames                             | Array of team name to which the developer, who created the application, belongs     |
```suggestion
| Teams name        | TeamNames                             | Array of team names to which the developer, who created the application, belongs     |
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Added a fallback mechanism for referencing assets that searches for assets, such as images referenced in the rich text editor or markdown editor, in the container's filesystem whenever the portal c
Does the fallback mechanism autofill potential asset references and does it allow the user to check and validate the suggested references it has autofilled?

```suggestion
- Added a fallback mechanism for referencing assets. This searches for assets, such as images, referenced in the rich text editor or markdown editor. It searches the container's filesystem whenever the portal can't find the referenced asset in the `PORTAL_STORAGE`.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Renamed subject for the new developer registration request from "Registering email - subject" to "Developer registration approval request - subject".
Explain briefly why this was done

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Changed the behavior of the developers UI in the admin app. Now, when an admin tries to remove a developer profile and some of their credentials have been removed from the credentials provider, or
```suggestion
- Changed the behaviour of removing a developer profile within the developers UI in the admin app. Now, when an admin tries to remove a developer profile and some of their credentials have been removed from the credentials provider, or if the provider itself is down or unreachable, the portal asks the admin if they still want to remove the developer profile by displaying a modal window.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Extended the `DELETE /users/:id` API endpoint by adding the [?force]({{< ref "/product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api" >}}) parameter to remove a user anyway ev
```suggestion
- Extended the `DELETE /users/:id` API endpoint by adding the [?force]({{< ref "/product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api" >}}) parameter to force removal of a user even if some of their credentials have been removed from the credentials provider, or if the provider itself is down or unreachable.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Extended [filesize limit]({{< ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/file-structure-concepts#part-1-create-a-new-theme" >}})
```suggestion
- Extended [filesize limit]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/file-structure-concepts#part-1-create-a-new-theme" >}}) for individual files in themes to 5 MB.
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Made the organisation invite email's subject configurable via [the emails settings section]({{< ref "/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-cus
```suggestion
- Made the organisation invite email's subject configurable via [the emails settings section]({{< ref "tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/email-customization#list-of-email-notifications" >}}).
```

2024-03-05 18:09 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/file-structure-concepts.md
> +4. To upload the theme as an admin user, navigate to **Themes** and click on the **Add new theme** button. Please note that the size of individual files should not exceed 5 MB and the total size of a
```suggestion
4. To upload the theme as an admin user, navigate to **Themes** and click on the **Add new theme** button. Please note that the size of individual files should not exceed 5 MB and the total size of all files in the theme should not exceed `PORTAL_MAX_UPLOAD_SIZE`. This parameter is [configurable]({{< ref "product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_max_upload_size" >}}).
```

2024-03-05 22:02 UTC, JRWu requested changes
Content looks great to me, just requesting a few minor changes

2024-03-05 22:02 UTC, JRWu commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Changed the behavior of the `Secure` cookie attribute that is set by [PORTAL_SESSION_SECURE]({{ ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration/#portal_session_secure" }})
This formatting block doesn't seem to be rendering correctly

 [PORTAL_SESSION_SECURE]({{ ref “/product-stack/tyk-enterprise-developer-portal/deploy/configuration/#portal_session_secure” }})

2024-03-05 22:02 UTC, JRWu commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Extended the `DELETE /users/:id` API endpoint by adding the [?force]({{< ref "/product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api" >}}) parameter to force removal of a user
is ?force intentional here?

2024-03-05 22:02 UTC, JRWu commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +If you are interested in getting access, contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
Maybe remove the Beta tag here now that the Portal is generally available

2024-03-05 22:02 UTC, JRWu commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +  - **Write once read many**: Determines if the value of the attribute can be changed after a user profile is created.
This statement is slightly ambiguous- if I check this box does it mean that the field is now write once read many? (i.e. uneditable?)

2024-03-06 15:33 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Extended the `DELETE /users/:id` API endpoint by adding the [?force]({{< ref "/product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api" >}}) parameter to force removal of a user
Yep.

2024-03-06 15:35 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +If you are interested in getting access, contact us at [support@tyk.io](<mailto:support@tyk.io?subject=Tyk Enterprise Portal Beta>)
Well, we will need to update it in other pages as well, so I'm keeping it for now with intention to remove it on all the other pages in H1.

2024-03-06 15:46 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +  - **Write once read many**: Determines if the value of the attribute can be changed after a user profile is created.
In this section admins configure behavior of fields, not the values. The values of custom attributes for the user model are editable from the user menu. In other words, to set a value of an attribute for a specific user, you need to go to the Users menu, select the user, and change the required attributes. Write once read many in this case means that you can't do that after a user profile is created.

2024-03-06 15:50 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
> +  - **Write once read many**: Determines if the value of the attribute can be changed after a user profile is created.
Added that to the doc.

2024-03-06 15:50 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
> +- Changed the behavior of the `Secure` cookie attribute that is set by [PORTAL_SESSION_SECURE]({{ ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration/#portal_session_secure" }})
Fixed

2024-03-07 10:41 UTC, dcs3spp approved these changes
PR LGTM @slega 
Thanks for the peer review @JRWu. Would you be able to approve if changes made by @slega are ok?

2024-03-07 13:54 UTC, JRWu approved these changes
LGTM!

2024-03-07 14:28 UTC, merged

2024-03-07 14:28 UTC, dcs3spp commented
/release to release-5.2

2024-03-07 14:32 UTC, dcs3spp commented
/release to release-5.1