[TT-11185] Update documentation for 5.3
TykTechnologies/tyk-docs-hugo pull request #4188
Opened 2024-03-04 08:23 UTC by buger

Triggered by: titpetric

Included:

Tyk Gateway: true
Tyk Dashboard: false
Tyk MDCB false
Tyk Pump false

Intended for: 5.3
Changes sourced from: release-5.3
Config info generator branch: main

Note: TT-11185, gateway changes only (branch suffix: docs-gateway)

JIRA: https://tyktech.atlassian.net/browse/TT-11185

2024-03-04 18:17 UTC, dcs3spp requested changes
@titpetric Thanks for raising separate PR for GW. I've had a look through and review summary is:
- Missing field descriptions for:
    - OAuthProvider
    - External OAUth
    - JWT
    - OAuth
    - Path
    - Signature
    - TykExtensionConfigParams
    
  - Some line breaks introduced in descriptions/explanations. is there anyway of preventing the line breaks?
  
  - Minor grammar suggestions.
 - Peer review required before merge and release

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +should be sent. Tyk listens out for any requests coming into the host at
```suggestion
should be sent. Tyk listens for any requests coming into the host at
```

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SecuritySchemes holds security scheme values, filled with Import().
Checking to understand what this means. Does this mean that security schemes are populated from Go package imports somehow?

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CacheAllSafeRequests caches responses to (`GET`, `HEAD`, `OPTIONS`) requests overrides per-path cache settings in versions,
```suggestion
CacheAllSafeRequests caches responses to (`GET`, `HEAD`, `OPTIONS`) requests overrides per-path cache settings in versions. Applies across versions.
```

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +applies across versions.
remove this after applying above suggestion

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `jwt` ([JWTValidation](#jwtvalidation))**
Missing description for jwt and introspection

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SigningMethod to verify signing method used in jwt - allowed values HMAC/RSA/ECDSA.
```suggestion
SigningMethod to verify signing method used in jwt-allowed values HMAC/RSA/ECDSA.
```

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `enabled` (`boolean`)**
Missing field descriptions

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **JWT**
Missing field descriptions

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **OAuth**
Missing field descriptions

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Path**
Missing field descriptions

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Signature**
Missing field descriptions

2024-03-04 18:17 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +TykExtensionConfigParams holds the essential configuration required for the Tyk Extension schema.
Missing descriptions

2024-03-21 14:08 UTC, andyo-tyk approved these changes
Whilst there are some empty fields, I think we can publish this and then correct those in a future update.

2024-03-21 14:13 UTC, dcs3spp approved these changes

2024-03-21 14:14 UTC, dcs3spp commented
Merging. Comments unresolved to make it easier to track fixes requested in future patch as discussed in https://tyktech.atlassian.net/browse/TT-11665

2024-03-21 14:29 UTC, merged