[TT-11273] Update documentation for 5.0 LTS
TykTechnologies/tyk-docs-hugo pull request #4189
Opened 2024-03-04 08:35 UTC by buger

Triggered by: titpetric

Included:

Tyk Gateway: true
Tyk Dashboard: false
Tyk MDCB false
Tyk Pump false

Intended for: 5.0 LTS
Changes sourced from: release-5-lts
Config info generator branch: main

Note: 5.0.11, gateway (branch suffix: docs-gateway-lts)

JIRA: https://tyktech.atlassian.net/browse/TT-11273

2024-03-05 11:51 UTC, dcs3spp requested changes
Thanks for raising Gateway conifg & OAS changes in separate PR. Summary of review is as follows:
- Some types missing summary and/or field descriptions
- Is it possible to remove the line breaks introduced in some of the type summaries and field descriptions?
- Double check that fields are not missing Tyk Classic equivalent fields. Reviewed [here](https://github.com/TykTechnologies/tyk-docs/pull/4153)
- Remove additional line spaces that have been introduced in some types
- Requires peer review

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +MutualTLS holds configuration related to mTLS on APIs, domain to certificate mappings.
```suggestion
MutualTLS holds configuration related to mTLS on APIs, mapping domains to certificates.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -### **DomainToCertificate**
Is there any way in which this section can be still located here to ease readability adjacent next to Mutual TLS? If not we have it linked to anyway

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Global holds configuration applies globally: CORS and caching.
Plugins was missing in description.
Caching is included in the description but the field is missing in global.

```suggestion
Global holds configuration that applies globally, related to CORS, plugins and caching.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PluginConfig contains the configuration related custom plugin bundles/driver.
```suggestion
PluginConfig contains the configuration related to custom plugins, such as bundles and driver.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CORS contains the configuration related to cross origin resource sharing.
```suggestion
CORS contains the configuration related to Cross Origin Resource Sharing.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Operations holds Operation definitions.
Should there be field(s) added and explained here? Is Operations a list type containing instances of Operation?

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as array of `PinnedPublicKey` values, see [PinnedPublicKey](#pinnedpublickey) definition.
```suggestion
The list contains instances of `PinnedPublicKey`. See [PinnedPublicKey](#pinnedpublickey) definition.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CustomPluginAuthentication holds configuration for custom plugins.
```suggestion
CustomPluginAuthentication holds configuration for authentication custom plugins.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SecuritySchemes holds security scheme values, filled with Import().
Should there be field descriptions included for this type? Does this mean that security scheme values are auto populated from a golang import?

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Driver configures which custom plugin to be used.
```suggestion
Driver configures the target language for the custom plugin.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +
Is there a way to remove the additional line space here and in occurrences in the fields below?

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Debug is a boolean flag, If set to `true`, this option produces log files for the CORS middleware.
```suggestion
Debug is a boolean flag. If set to `true`, this option produces log files for the CORS middleware.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +AllowedMethods holds a list of methods to allow access via.
```suggestion
AllowedMethods holds a list of methods to allow access from in inbound requests.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Plugins configures custom plugins to be run on pre authentication stage.
```suggestion
Plugins configures custom plugins to be run on post authentication stage.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Plugins configures custom plugins to be run on post stage.
```suggestion
Plugins configures custom plugins to be run on response stage.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +by explicitly setting the endpoint cache middleware.
Add link to config for endpoint cache middleware.

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CacheAllSafeRequests caches responses to (`GET`, `HEAD`, `OPTIONS`) requests overrides per-path cache settings in versions,
Not sure I understand this correctly, so checking. Is versions part of the APIDefinition? So it means that if there are any per-path cache settings included in the versions section of the APIDefinition then they are overridden by this configuration section. Not sure what means by across versions? Overrides all configured per-path cache settings in all versions of config? 

```suggestion
CacheAllSafeRequests caches responses to (`GET`, `HEAD`, `OPTIONS`) requests. This overrides any per-path cache settings that are configured in versions configuration section.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path will be suffixed to `bundle_base_url` in gateway config.
```suggestion
Path will be appended to `bundle_base_url` in gateway config.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PluginConfigData configures config data for custom plugins.
Add explanation and example of config data for custom plugins in the description.

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CustomPlugins is a list of CustomPlugin.
```suggestion
CustomPlugins is a list of CustomPlugin instances.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +CustomPlugin configures custom plugin.
```suggestion
CustomPlugin configures a custom plugin.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Enabled enables the custom pre plugin.
```suggestion
Enabled enables the custom plugin.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +FunctionName is the name of authentication method.
```suggestion
FunctionName is the name of the function that implements the plugin.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path is the path to shared object file in case of gopluign mode or path to js code in case of otto auth plugin.
Typo and sentence refactor

```suggestion
Path is the path to a shared object file for a Go plugin. Alternatively, for an otto plugin it represents the path to aJS source code file.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +RawBodyOnly if set to true, do not fill body in request or response object.
Not sure understand this, does it mean that if this is set to true then the text of the request or response body is not filled in an object property?

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +RequireSession is used only with JSVM custom middleware.
Does it also get sent for [gRPC custom middleware](https://tyk.io/docs/plugins/supported-languages/rich-plugins/rich-plugins-data-structures/#sessionstate-session_stateproto)?

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **OAuthProvider**
Missing summary description and field descriptions

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Type defined as array of `EndpointPostPlugin` values, see [EndpointPostPlugin](#endpointpostplugin) definition.
```suggestion
Type defined as array of `EndpointPostPlugin` instances, see [EndpointPostPlugin](#endpointpostplugin) definition.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **JWTValidation**
Missing summary description.

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +SigningMethod to verify signing method used in jwt - allowed values HMAC/RSA/ECDSA.
```suggestion
SigningMethod to verify signing method used in JWT - allowed values HMAC/RSA/ECDSA.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Source is the secret to verify signature, it could be one among:
```suggestion
Source is the secret used to verify the signature. Valid values are:
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Introspection**
Missing summary description.

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +ClientSecret is a secret known only to the client and the authorization server, acquired from the third party.
```suggestion
ClientSecret is a secret known only to the client and the authorisation server, acquired from the third party.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +IdentityBaseField is the key showing where to find the user id in the claims. If it is empty, the `sub` key is looked at.
```suggestion
IdentityBaseField is the key for the field in the claims that contains the user id. If it is empty, the default behaviour is to inspect the `sub` key.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Cache is the caching mechanism for introspection responses.
```suggestion
Cache is the caching mechanism that is used for introspection responses.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **IntrospectionCache**
Missing summary description.

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Timeout is the duration in seconds of how long the cached value stays.
```suggestion
Timeout represents the duration in seconds for how long a value remains in the cache.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **ExternalOAuth**
Missing summary description and field descriptions.

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +AllowanceType holds the valid allowance types values.
Could this be expanded to mention the valid type of allowance values?

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +AuthSource defines an authentication source.
This type is used to configure an authentication source such as a cookie, token in header field etc?

```suggestion
AuthSource allows an authentication source (cookie, header or query parameter) to be specified and activated.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Basic type holds configuration values related to http basic authentication.
```suggestion
Basic type holds configuration values related to HTTP basic authentication.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Path is the path to plugin.
```suggestion
Path is the path to the plugin.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +UserRegexp is the regex for username e.g. `<User>(.*)</User>`.
```suggestion
UserRegexp is the regex used to extract the username e.g. `<User>(.*)</User>`.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +PasswordRegexp is the regex for password e.g. `<Password>(.*)</Password>`.
```suggestion
PasswordRegexp is the regex used to extract the password e.g. `<Password>(.*)</Password>`.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **FieldInfo**
Explain what this field relate to (JSON, database, header field etc.)

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +FromOASExamples configures mock responses should be returned from OAS example responses.
```suggestion
FromOASExamples configures mock responses to be returned using OAS example responses.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **JWT**
Missing field descriptions.

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +**Field: `enabled` (`boolean`)**
Missing description.

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **OAuth**
Missing field descriptions

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **Path**
Missing field descriptions

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Plugins configures common settings for each plugin, allowances, transforms, caching and timeouts.
```suggestion
Plugins configures common settings for each plugin, relating to allowances, transforms, caching and timeouts.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **SecurityScheme**
Can there be further fields included and explained in this type?

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Signature holds the configuration for signature validation.
Missing field descriptions

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **StructInfo**
Should this type be removed? Is it a type related to config docs generation using godoc?

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Token holds the values related to authentication tokens.
```suggestion
Token configures behaviour relating to authentication tokens.
```

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **TykExtensionConfigParams**
Missing field descriptions

2024-03-05 11:51 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **XTykDoc**
Should this section be included? Is it specific to godoc generation?

Have seen the [PR](https://github.com/TykTechnologies/tyk/pull/6089) to resolve in tyk repository.
Why is this file apidef/oas/schema/x-tyk-gateway.md being deleted? Will that effect docs generation?

2024-03-06 06:10 UTC, titpetric commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **XTykDoc**
The old docgen is not in use anymore. The removal gets rid of the symbols that were previously exposed by the docgen. The .md file is not in use for docs sync anymore, the generator runs directly.

2024-03-06 09:12 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +### **XTykDoc**
Thanks @titpetric I've approved PR

2024-03-19 15:58 UTC, dcs3spp commented
@andyo-tyk @titpetric Resolved most comments. The following types do not have field descriptions. 

- ExternalOAuth
- JWT
- OAuth
- Signature
- TykExtensionConfigParams

The types above are currently not visible in 5 LTS docs https://tyk.io/docs/5.0/tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc 
If merged the types listed above would not have field descriptions

2024-03-21 14:21 UTC, andyo-tyk approved these changes
Whilst there are further improvements that could be made to the x-tyk-gateway part, this is in a good enough shape for publication.

2024-03-26 16:16 UTC, dcs3spp approved these changes
PR LGTM, as discussed will raise ticket for bug fixes

2024-04-11 10:15 UTC, dcs3spp commented
Merging. Comments unresolved to make it easier to track fixes requested in future patch as discussed in [ticket](https://tyktech.atlassian.net/browse/TT-11664)

2024-04-11 10:15 UTC, merged