[TT-11273] Update documentation for 5.0 LTS
TykTechnologies/tyk-docs-hugo pull request #4190
Opened 2024-03-04 08:36 UTC by buger

Triggered by: titpetric

Included:

Tyk Gateway: false
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: 5.0 LTS
Changes sourced from: release-5-lts
Config info generator branch: main

Note: 5.0.11, dashboard only (branch suffix: docs-dashboard-lts)

JIRA: https://tyktech.atlassian.net/browse/TT-11273

2024-03-05 10:41 UTC, dcs3spp requested changes
Thanks for raising the Dashboard 5 LTS PR separately to facilitate review. Summary of review is as follows:
- Should the version be bumped in dashboard-admin-swagger.yml OAS file also?  
- For each new schema type ensure:
       - each property has a description and, where applicable (default value and readonly status
       - example documented. The example given in schemas appears in the OAS swagger web interface for request and response payloads for all endpoints that use that schema, resulting in better DX.
- Move Organisation example to schema rather than at the endpoint level. Expand the example to include nested type examples, e.g. in ui, event_options and org_options_meta
- Peer review required

2024-03-05 10:41 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +    ApiDocument:
For new schema types ensure that each property has a description. Document examples at the schema level. The example given in schemas appears in the OAS swagger web interface for request and response payloads for all endpoints that use that schema, resulting in better DX. 
Document (where applicable) default value and readonly status of new schema properties.

2024-03-05 10:41 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-admin-swagger.yml
> +              apis:
Following the statement given in the description, include full example of sub objects, e.g. languages, login_page etc

2024-03-19 14:42 UTC, dcs3spp approved these changes
@andyo-tyk @titpetric Approved, will raise a ticket relating to this ticket

2024-03-21 14:16 UTC, andyo-tyk approved these changes
LGTM

2024-04-11 10:01 UTC, merged