Updated per-endpoint Go plugin & Golang guide
TykTechnologies/tyk-docs-hugo pull request #4193
Opened 2024-03-04 14:54 UTC by andyo-tyk

### Preview Link
TBC

### Description
Added documentation for the per-endpoint custom Go plugin
Restructured and tidied up the "Go lanaguage" pages

2024-03-05 14:15 UTC, dcs3spp requested changes
PR LGTM, have made minor suggestions and peer review required

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/plugins/plugin-types/response-plugins.md
> + - `response.path`: is the full or relative (to the Tyk binary) path to the file with the plugin implementation (make sure Tyk has read access to this file)
```suggestion
 - `response.path`: is the full or relative (to the Tyk binary) path to the plugin source file. Ensure Tyk has read access to this file.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +Golang plugins are a very flexible and powerful way to extend the functionality of Tyk by attaching custom logic (written in Golang) to certain [hooks]({{< ref "plugins/plugin-types/plugintypes" >}})
```suggestion
Golang plugins are a very flexible and powerful way to extend the functionality of Tyk by attaching custom logic (written in Golang) to certain [hooks]({{< ref "plugins/plugin-types/plugintypes" >}}) in the Tyk [middleware chain]({{< ref "concepts/middleware-execution-order" >}}). The chain of middleware is specific to an API and gets created at API re-load time. When Tyk Gateway performs an API re-load it also loads any custom middleware and "injects" them into a chain to be called at different stages of the HTTP request life cycle.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> + - **Post-Auth** - supports an array of middleware to be run after authentication; at this point, we have authenticated the session API key for the given key (in the request context) so we can perfor
```suggestion
 - **Post-Auth** - supports an array of middleware to be run after authentication; at this point, we have authenticated the session API key for the given key (in the request context) so we can perform any extra checks. This can be used only if the API definition has both:
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +All of Tyk's [custom middleware hooks]({{< ref "plugins/plugin-types/plugintypes" >}}) support Go plugins. They represent different stages in the request and response middleware chain where custom fu
Is there an image for the request / response middleware chain that could link to here?

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/golang.md
> +These fields are populated automatically with the correct values when you change the authentication method for the API in the Tyk Dashboard.
Which fields are populated automatically and how do they relate to the PR, Post, Response etc. plugin types?

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +If your plugin depends on third-party libraries, ensure to vendor them, before building. If you are using [Go modules](https://blog.golang.org/using-go-modules), it should be as simple as running `go
Is vendoring still needed when building plugins for GW 5.1+?

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-compiler.md
> +The plugin compiler is not supported on Ubuntu 16.04 (Xenial Xerus) as it uses glibc 2.23 which is incompatible with our standard build environment. If you absolutely must have Goplugin support on Xe
Add link to Tyk support

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-compiler.md
> +These environment options are only available in the latest gateway and plugin compiler versions. They are unsupported and are provided to aid development and
```suggestion
These environment options are only available in the latest gateway and plugin compiler versions. They are unsupported and are provided to aid development and testing workflows.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-examples.md
> +Here we provide some worked example for performing specific functionality with a custom Go plugin.
```suggestion
Here we provide some worked examples for performing specific functionality with a custom Go plugin.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-examples.md
> +Let's build the plugin by running this command in the plugin project folder:
Could we summarise the steps of the example using sub sections:
- Example - Writing A Plugin To Send Current Time
    - Build the plugin
    - Edit API definition
    - Test
    
    Is there a Tyk OAS configuration example also?

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-examples.md
> +Let's have a look at the code example. Imagine we need to implement a very trivial authentication method when only one key is supported (in the real world you would want to store your keys in some st
Could we summarise the steps of the example using sub sections:

- Example - Writing A Custom Auth Plugin
    - Build the plugin
    - Edit API definition
    - Test

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-examples.md
> +func MyPluginAuthCheck(rw http.ResponseWriter, r *http.Request) {
update code example for consistent comment style to have spacing, e.g. _// spaced comment_

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
> +For development purposes, we going to load the plugin from local files. For production, you can use [bundles](#loading-a-tyk-golang-plugin-from-a-bundle) to deploy plugins to multiple gateways.
```suggestion
For development purposes, we are going to load the plugin from local file storage. For production, you can use [bundles](#loading-a-tyk-golang-plugin-from-a-bundle) to deploy plugins to multiple gateways.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
> +```json
Is there a Tyk OAS equivalent example?

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
> +* `"driver"` - Set this to `goplugin` (no value created for this plugin) which says to Tyk that this custom middleware is a Golang native plugin.
```suggestion
* `"driver"` - Set this to `goplugin` to inform Tyk that this custom middleware is a Golang native plugin.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
> +* `post.path` - is the full or relative (to the Tyk binary) path to `.so` file with plugin implementation (make sure Tyk has read access to this file)
```suggestion
* `post.path` - is the full or relative (to the Tyk binary) path to the shared object (`.so`) file containing the plugin implementation. Ensure Tyk has read access to this file.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
> +Also, let's set fields `"use_keyless": true` and `"target_url": "http://httpbin.org/"` - for testing purposes (we need to see what request arrives to our upstream target and `httpbin.org` is a perfec
```suggestion
Also, let's set fields `"use_keyless": true` and `"target_url": "http://httpbin.org/"` - for testing purposes. We will test what request arrives to our upstream target and `httpbin.org` is a perfect fit for that.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
> +So far we have loaded Golang plugins only directly from the file system. However, when you have multiple gateway instances, you need a more dynamic way to load plugins. Tyk offer bundle instrumentati
```suggestion
So far we have loaded Golang plugins only directly from the file system. However, when you have multiple gateway instances, you need a more dynamic way to load plugins. Tyk offer bundle instrumentation [Plugin Bundles]({{< ref "plugins/how-to-serve-plugins/plugin-bundles" >}}). Using the bundle command creates a zipped archive with your plugin, which you can deploy to the HTTP server (or an AWS S3 bucket) and then your plugins will be fetched and loaded from that HTTP endpoint.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
> +### Loading a Tyk Golang plugin from a bundle
Is it worth mentioning how to sign bundled plugins in this section?

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/writing-go-plugins.md
> +  "github.com/TykTechnologies/tyk/ctx"
Future idea, Is it possible to use something like godoc to generate a static website for Tyk go plugins SDK?

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/writing-go-plugins.md
> +Here is an [example]({{ < ref "https://github.com/TykTechnologies/custom-plugin-examples/blob/master/plugins/go-auth-multiple_hook_example/main.go#L135" >}}) custom Go plugin that makes use of the se
External GHub link

```suggestion
Here is an [example](https://github.com/TykTechnologies/custom-plugin-examples/blob/master/plugins/go-auth-multiple_hook_example/main.go#L135) custom Go plugin that makes use of the session object.
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/writing-go-plugins.md
> +To do so you just need to import the package `"github.com/TykTechnologies/tyk/log"` and use the exported public method `Get()`:
```suggestion
To do so you just need to import the package `"github.com/TykTechnologies/tyk/log"` and use the exported public method `Get() to get a logging instance`:
```

2024-03-05 14:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-plugin-tyk-oas.md
> + < placeholder for video >
Remember to add placeholder video

2024-03-19 11:15 UTC, dcs3spp commented
@andyo-tyk I have resolved most comments. Remaining comments relate to questions, link, reminder to add placeholders and adding subsection headings for worked examples

2024-03-21 07:45 UTC, titpetric approved these changes
I made some technical corrections (plugins are not concurrency safe - removed that bit of text).

Added some general markdown updates:

- consistent use of `-` for bullet lists
- spacing around headings, code blocks, after a colon, lists
- use of "Go plugins" (Golang should be avoided, it's named Go)
- updated some code blocks for syntax highlighting
- updated some code blocks for brevity

LGTM

2024-03-29 16:40 UTC, andyo-tyk reviewed
Added responses to comments - will commit changes separately

2024-03-29 16:40 UTC, andyo-tyk commented on tyk-docs/content/plugins/supported-languages/golang.md
> +All of Tyk's [custom middleware hooks]({{< ref "plugins/plugin-types/plugintypes" >}}) support Go plugins. They represent different stages in the request and response middleware chain where custom fu
We have an image for the request middleware chain, but not for response - I'll add a link (though it's not great and should definitely be on the list for improvement as part of docs restructuring).

2024-03-29 16:40 UTC, andyo-tyk commented on tyk-docs/content/plugins/supported-languages/golang.md
> +These fields are populated automatically with the correct values when you change the authentication method for the API in the Tyk Dashboard.
Good question.... I'm not sure it really makes sense in the existing docs either, but must refer to the custom auth and/or post-auth plugin.

2024-03-29 16:40 UTC, andyo-tyk commented on tyk-docs/content/plugins/supported-languages/golang.md
> +These fields are populated automatically with the correct values when you change the authentication method for the API in the Tyk Dashboard.
I'll change this note to say:

_The `use_keyless` and `use_go_plugin_auth` fields are populated automatically with the correct values if you add a plugin to the **Auth** or **Post-Auth** hooks when using the Tyk Dashboard._

@titpetric please would you confirm this is technically correct, or have I misunderstood and misrepresented this?

2024-03-29 16:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-compiler.md
> +The plugin compiler is not supported on Ubuntu 16.04 (Xenial Xerus) as it uses glibc 2.23 which is incompatible with our standard build environment. If you absolutely must have Goplugin support on Xe
I'll add the green button and link from the RBAC page.

2024-03-29 16:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-examples.md
> +Let's build the plugin by running this command in the plugin project folder:
Sorry, I consider this out-of-scope. In this PR, I've just restructured the existing content and added the detail for the Tyk OAS per-endpoint plugin. I think these pages need to be updated by someone with knowledge of Go Plugins.

2024-03-29 16:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-examples.md
> +Let's have a look at the code example. Imagine we need to implement a very trivial authentication method when only one key is supported (in the real world you would want to store your keys in some st
Out of scope for this PR

2024-03-29 16:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
> +### Loading a Tyk Golang plugin from a bundle
Yes, but out of scope

2024-03-31 14:34 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
>  {{< img src="/img/dashboard/api-designer/tyk-oas-validate-request-config.png" alt="Configuring the Request Validation error resposne" >}}
```suggestion
{{< img src="/img/dashboard/api-designer/tyk-oas-validate-request-config.png" alt="Configuring the Request Validation error response" >}}
```

2024-04-03 08:15 UTC, titpetric approved these changes

2024-04-03 08:15 UTC, titpetric commented
LGTM, thank you @andyo-tyk

2024-04-03 09:54 UTC, dcs3spp approved these changes
PR LGTM but merge conflicts to fix before this can be merged ready for release

2024-04-03 12:17 UTC, merged