Updated request size limit
TykTechnologies/tyk-docs-hugo pull request #4198
Opened 2024-03-05 12:38 UTC by andyo-tyk

### Preview Link

### Description
Updated Request Size Limit documentation, adding Tyk OAS and aligning structure with other 5.3.0 changes

2024-03-07 10:05 UTC, dcs3spp requested changes
PR LGTM, made suggestions and requires peer review

2024-03-07 10:05 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +A GraphQL API endpoint might be susceptible to complex queries that can lead to performance issues. By setting a request size limit for the GraphQL endpoint, you ensure that overly complex queries ar
For GraphQL does max_query_depth also improve performance?

2024-03-07 10:05 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +```
For JSON fragments in this PR, does``` yaml render ok?

```suggestion
```yaml
```

2024-03-07 10:05 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +<!-- proposed "summary box" to be shown graphically on each middleware page
Remember to revisit this later

2024-03-07 10:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-classic.md
> +The [request size limit]({{< ref "basic-config-and-security/control-limit-traffic/request-size-limits" >}}) middleware enables you to apply limits to the size of requests made to your HTTP APIs. You
```suggestion
The [request size limit]({{< ref "basic-config-and-security/control-limit-traffic/request-size-limits" >}}) middleware enables you to apply limits to the size of requests made to your HTTP APIs. You might use this feature to protect your Tyk Gateway or upstream services from excessive memory usage or brute force attacks.
```

2024-03-07 10:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-classic.md
> +You can configure a request size limit (in bytes) to an API by configuring the `global_size_limit` to the `version` element of the API Definition, for example:
```suggestion
You can configure a request size limit (in bytes) to an API by configuring the `global_size_limit` within the `version` element of the API Definition, for example:
```

2024-03-07 10:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-classic.md
> +In this example the endpoint-level Request Size Limit middleware has been configured for HTTP `POST` requests to the `/anything` endpoint. For any call made to this endpoint, Tyk will check the size
```suggestion
In this example the endpoint-level Request Size Limit middleware has been configured for HTTP `POST` requests to the `/anything` endpoint. For any call made to this endpoint, Tyk will check the size of the request body and, if it is larger than 100 bytes, will reject the request, returning `HTTP 400 Request is too large`.
```

2024-03-07 10:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-oas.md
> + < placeholder for video >
remember to add placeholder video

2024-03-15 14:43 UTC, andrei-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +A specific API is designed to handle lightweight, fast transactions and is not equipped to process large payloads. You can set an API-level size limit that ensures the microservice behind this API is
wouldn't "and is generally not equipped to" so we don't sound categorical?

2024-03-15 14:46 UTC, andrei-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +An API endpoint is designed to accept file uploads, but to prevent abuse, you want to limit the size of uploads to 1MB. You can configure the Request Size Limit middleware for this endpoint with a li
"You can configure the Request Size Limit middleware for this endpoint with a limit of 1MB." tells you about what the user can do but is not linked with the preceding or the next statement in terms of reasoning. Wouldn't it be better if the sentence would start with "To achieve this, you can configure the Request..."

2024-03-15 14:56 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-oas.md
> +The [request size limit]({{< ref "basic-config-and-security/control-limit-traffic/request-size-limits" >}}) middleware enables you to apply limits to the size of requests made to your HTTP APIs. You
"avoid" seems out of place here too

2024-03-15 14:57 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-oas.md
> +The design of the Tyk OAS API Definition takes advantage of the `operationID` defined in the OpenAPI Document that declares both the path and method for which the middleware should be added.
I think it's "operationId" (at least that's what I found in the code )

2024-03-19 10:48 UTC, dcs3spp commented
@andyo-tyk I've resolved most comments. Unresolved comments relate to question concerning [max_query_depth](https://github.com/TykTechnologies/tyk-docs/pull/4198#discussion_r1514146324), reminders re placeholder video and yaml formatting for JSON fragment

2024-03-25 18:09 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +A GraphQL API endpoint might be susceptible to complex queries that can lead to performance issues. By setting a request size limit for the GraphQL endpoint, you ensure that overly complex queries ar
I have to admit, I have no idea. I think that's a potential enhancement to these docs to be added later.

2024-03-25 18:11 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +```
![image](https://github.com/TykTechnologies/tyk-docs/assets/99968932/a0d061ce-8488-4e01-94f8-c1a9b1978eff)

Looks OK to me - I'll add this.

2024-03-25 18:12 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
> +A specific API is designed to handle lightweight, fast transactions and is not equipped to process large payloads. You can set an API-level size limit that ensures the microservice behind this API is
This is meant to be "in the scenario where you have an API that is not equipped to process large payloads"... so I'll tweak the wording.

2024-03-25 18:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-oas.md
> +The [request size limit]({{< ref "basic-config-and-security/control-limit-traffic/request-size-limits" >}}) middleware enables you to apply limits to the size of requests made to your HTTP APIs. You
Yes, that's a typo - good spot. Thanks.

2024-03-25 18:16 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-oas.md
> +The design of the Tyk OAS API Definition takes advantage of the `operationID` defined in the OpenAPI Document that declares both the path and method for which the middleware should be added.
Argh.... that's in all of the middleware pages... good spot... I'll correct it here and then sweep up the others elsewhere.

2024-03-26 12:39 UTC, dcs3spp approved these changes
@andyo-tyk PR LGTM

@andrei-tyk would you be able to peer review and once approved will merge and release

2024-03-26 14:43 UTC, andrei-tyk approved these changes

2024-03-26 14:58 UTC, merged