Added API category docs
TykTechnologies/tyk-docs-hugo pull request #4215
Opened 2024-03-08 11:33 UTC by andyo-tyk

### Preview Link

### Description
Added documentation of the API Templating feature

2024-03-12 11:39 UTC, dcs3spp requested changes
@andyo-tyk PR LGTM, I've added minor suggestions. @andrei-tyk would you be able to add a peer review for Andy?

2024-03-12 11:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
> +| `PUT`  | `/api/apis/oas/{apiId}/categories`   | Assign a list of categories to the specified API                                       |
```suggestion
| `PUT`  | `/api/apis/oas/{apiID}/categories`   | Assign a list of categories to the specified API   
```

2024-03-12 11:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
> +| `PUT`  | `/api/apis/{apiId}`                  | Update the API definition for the specified API - CRUD category tags in the `name` field |
```suggestion
| `PUT`  | `/api/apis/{apiID}`                  | Update the API definition for the specified API - CRUD category tags in the `name` field |
```

2024-03-12 11:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
> +When working with Tyk Classic APIs, you manage categories for an API by modifying the `name` field in the API definition and then updating the API in Tyk with that using these endpoints:
```suggestion
When working with Tyk Classic APIs, you can manage categories for an API using these endpoints:
```

2024-03-12 11:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
> +If you are a super-user on a multi-tenant deployment - the admin user where [role-based access control]({{< ref "tyk-dashboard/rbac" >}}) is being used to give different users or teams of users acces
```suggestion
Multi-tenant deployments with [role-based access control]({{< ref "tyk-dashboard/rbac" >}}) enabled allows an admin user to give different users or groups access to a sub-set of the entire API portfolio. Categories can be aligned with the API ownership rules that you have deployed to allow filtering the list of APIs for those visible to each separate user group/team.
```

2024-03-27 19:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
> +When working with Tyk Classic APIs, you manage categories for an API by modifying the `name` field in the API definition and then updating the API in Tyk with that using these endpoints:
This information is important so I'd rather leave as-is.

2024-03-27 23:12 UTC, andrei-tyk approved these changes

2024-03-28 09:06 UTC, dcs3spp approved these changes

2024-03-28 09:09 UTC, merged