MDCB 2.5 release notes
TykTechnologies/tyk-docs-hugo pull request #4216
Opened 2024-03-08 14:31 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-03-11 16:55 UTC, sredxny approved these changes
lgtm 🚀

2024-03-12 09:07 UTC, dcs3spp commented
@caroltyk to enable DX review could you kindly raise a Jira ticket in the DX project space and include the ticket ID in the PR title and description

@letzya

2024-03-14 10:33 UTC, dcs3spp requested changes
PR LGTM have made minor suggestions

2024-03-14 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> + <summary>Fixed relaying per-API access rights to gateways</summary>
```suggestion
 <summary>Fixed relaying per-API access rights to gateways for MongoDB deployments</summary>
```

2024-03-14 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +Note: This bug affected MongoDB users only. PostgreSQL users were not affected.
```suggestion
Note: This bug affected deployments using MongoDB. PostgreSQL deployments were not affected.
```

2024-03-14 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> + <summary>TT-10651</summary>
Should this be removed?

2024-03-14 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +   Migrate MDCB JWT library to golang-jwt v4.5.0 to address CVE-2020-26160 (NVD)
Add link to CVE https://nvd.nist.gov/vuln/detail/CVE-2020-26160

2024-03-14 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +   which integrates with [go-redis](https://github.com/redis/go-redis) v9 underneath which added support to
```suggestion
   which integrates with [go-redis](https://github.com/redis/go-redis) v9. Subsequently, this fix adds support for 
```

2024-03-14 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +##### Release date TBC <<to be updated>>
Remember to add release date when available

2024-03-14 10:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-mdcb-docker/v2.5.0/images/sha256-TBC?context=explore) <<to be updated>>
Remember to update docker image when available

2024-03-21 21:38 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +   Migrate MDCB JWT library to golang-jwt v4.5.0 to address CVE-2020-26160 (NVD)
added

2024-03-21 21:38 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> + <summary>TT-10651</summary>
updated

2024-03-26 12:59 UTC, dcs3spp requested changes
Thanks @caroltyk I've made minor suggestions and then ready for merge and release. Should this appear in 5.3+ docs only?

2024-03-26 12:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +MDCB supports Tyk API definitions up to Tyk Gateway v5.3.0. Please use this version with Tyk Gateway v5.3.0+.
```suggestion
MDCB 2.4.x supports Tyk API definitions up to Tyk Gateway v5.3.0. Please use MDCB 2.5.x with Tyk Gateway v5.3.0+.
```

2024-03-26 12:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +We have upgraded redis driver [go-redis](https://github.com/redis/go-redis) to v9. Subsequently, Tyk 5.3 is compatible with Redis v7.x.
```suggestion
We have upgraded Redis driver [go-redis](https://github.com/redis/go-redis) to v9. Subsequently, Tyk 5.3 is compatible with Redis v7.x.
```

2024-03-26 15:20 UTC, caroltyk commented
Yes, it can be merged to 5.3 only.

Waiting for release date confirmation.

2024-04-05 11:24 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +##### Release date TBC <<to be updated>>
```suggestion
##### Release date  5 Apr 2024
```

2024-04-05 11:30 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +- [Docker image to pull](https://hub.docker.com/layers/tykio/tyk-mdcb-docker/v2.5.0/images/sha256-TBC?context=explore) <<to be updated>>
```suggestion
- [Docker image v2.5.0](https://hub.docker.com/r/tykio/tyk-mdcb-docker/tags?page=&page_size=&ordering=&name=v2.5.0) - ```bash
docker pull tykio/tyk-mdcb-docker:v2.5.0``` 
```

2024-04-05 11:34 UTC, letzya approved these changes

2024-04-05 11:41 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +##### Release date  5 Apr 2024
```suggestion
##### Release date 5 Apr 2024
```

2024-04-05 11:44 UTC, dcs3spp approved these changes
Thanks @letzya PR LGTM

2024-04-05 11:46 UTC, merged