Updated User Management, RBAC and API Ownership
TykTechnologies/tyk-docs-hugo pull request #4236
Opened 2024-03-12 12:24 UTC by andyo-tyk

### Preview Link

### Description
Restructured and tidied up User Management section (including RBAC)
Moved API Ownership to a separate page and added Tyk OAS

2024-03-12 13:06 UTC, dcs3spp commented
@andyo-tyk Can you create a ticket in the DX space for review and add to PR title and description?

2024-03-14 10:12 UTC, dcs3spp requested changes
PR LGTM @andyo-tyk , I have suggested minor changes and requires peer review from @andrei-tyk

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/dashboard/create-user-groups.md
> +**Note**
Remove additional space

```suggestion
**Note**
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/dashboard/create-user-groups.md
> +{{< button_left href="https://tyk.io/contact/" color="green" content="Contact us" >}}
Like the CTA added here!!!

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/dashboard/create-user-groups.md
> -{{< note success >}}
Why was the Additional Permissions API details removed?

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/dashboard/create-users.md
> +Dashboard users are not the same as developer portal users ([developers]({{< ref "tyk-developer-portal/tyk-portal-classic/portal-concepts#developers" >}})), the user records are stored completely sep
Dashboard users are not the same as developer portal users ([developers].....

What is meant by developer portal users developers?

```suggestion
Dashboard users are not the same as developer portal users ([developers]({{< ref "tyk-developer-portal/tyk-portal-classic/portal-concepts#developers" >}})). The credentials are stored independently and have different mechanics relating to registration, management and access. For example, it is not possible to log into the developer portal using a dashboard account.
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/dashboard/create-users.md
> +``` .json
```suggestion
```json
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/dashboard/dashboard-admin-api.md
> +  - /basic-config-and-security/security/dashboard/dashboard-api-security/
Nice! Used an alias again

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/dashboard/dashboard-admin-api.md
> +The Tyk Dashboard Admin API provides the following administrator level functions:
```suggestion
The Tyk Dashboard Admin API provides the following administrative functions:
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/dashboard/organisations.md
> +A user that does not belong to an Organisation is sometimes referred to as an *unbounded user*. These users have visibility across all Organisations, but should be granted read-only access.
Is there a way to restrict an unbounded user from viewing all APIs across Organisations, for security purposes?

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/dashboard/user-roles.md
> +You can also configure these custom permissions in the `security.additional_permissions` map in the Tyk Dashboard configuration file.
Link to the security.additional_permissions config

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/dashboard-api.md
> +The [Tyk Dashboard API]({{< ref "/content/tyk-dashboard-api.md" >}}) is a superset of the Tyk Gateway API, enabling (almost) all of the core features and adding many more. The Dashboard API is also m
```suggestion
The [Tyk Dashboard API]({{< ref "tyk-dashboard-api" >}}) is a superset of the Tyk Gateway API, enabling (almost) all of the core features and adding many more. The Dashboard API is also more granular and supports [Role Based Access Control]({{< ref "tyk-dashboard/rbac" >}}) (RBAC) on both a multi-tenant, and user basis.
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +API Ownership is the concept of Role Based Access Control applied to the portfolio of APIs deployed on your Tyk Gateeways and managed from your Tyk Dashboard. Each user or user group can be granted a
```suggestion
API Ownership is the concept of Role Based Access Control (RBAC) applied to the portfolio of APIs deployed on your Tyk Gateeways and managed from your Tyk Dashboard. Each user or user group can be granted access to a subset of the portfolio and, for example, have no visibility of any other APIs deployed on the platform.
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +A Dashboard User (or User Group) can be assigned as *owner* of an API, granting them visibility of and - given appropriate permissions - the ability to manage all the Tyk objects relating to that API
_Assigning an owner to an API restricts visibility of that API and its related objects to other users who will not be able to view or manage it._
 
 Should this read:
 
 Assigning an owner to an API allows the visibility of the API and it's associated objects to be managed to a restricted set of users.

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +When using Tyk Classic APIs, the option to assign owner(s) to an API is provided on the **Access** tab in the API Designer. You simply select the owner (or owners) that you wish to assign to the API
The section heading is Using Tyk OAS APIs so sentence should start with When using Tyk OAS APIs

```suggestion
When using Tyk OAS APIs, the option to assign owner(s) to an API is provided on the **Access** tab in the API Designer. You simply select the owner (or owners) that you wish to assign to the API from the drop-down boxes:
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +| `PUT`  | `/apis/{apiId}/access`  | Assign a list of owners to the specified API                                           |
Is apiId & apiID different or is this a typo?

```suggestion
| `PUT`  | `/apis/{apiID}/access`  | Assign a list of owners to the specified API                                           |
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +``` json
```suggestion
```json
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +| `PUT`  | `/api/apis/{apiId}` | Update the API definition for the specified API - CRUD API owners in the `user_owners` and `user_group_owners` fields |
Is apiId & apiID different or is this a typo?

```suggestion
| `PUT`  | `/api/apis/{apiID}` | Update the API definition for the specified API - CRUD API owners in the `user_owners` and `user_group_owners` fields |
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +| `GET`  | `/api/apis/{apiID}` | Retrieve the API definition for the specified API - ownership details in `user_owners` and `user_group_owners` fields |
```suggestion
| `GET`  | `/api/apis/{apiID}` | Retrieve the API definition for the specified API - ownership details are included in `user_owners` and `user_group_owners` fields |
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/rbac.md
> +You can create additional "users" for yuor colleagues who need to access Dashboard features. These additional users can be assigned [granular permissions]({{< ref "basic-config-and-security/security/
```suggestion
You can create additional "users" for your colleagues who need to access Dashboard features. These additional users can be assigned [granular permissions]({{< ref "basic-config-and-security/security/dashboard/user-roles" >}}) so that they only have access to the Dashboard pages (and corresponding Dashboard API endpoints) that they require. For each permission (or "role") you can "deny access", make it "read only", or allow "write access".
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/rbac.md
> +If you have multiple teams, where each team maintains its own APIs and you want to limit access of the dashboard to the team level, you should use our [API ownership]({{< ref "product-stack/tyk-dashb
```suggestion
If you have multiple teams, where each team maintains its own APIs and you want to limit access of the dashboard to the team level, you should use our [API ownership]({{< ref "product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership" >}}) feature. For each API, you can assign owners, where an owner can be either an individual user or user group. Only owners have access to these APIs and associated objects such as policies or analytics. **This functionality requires a specific Tyk licence.**
```

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/rbac.md
> -For Tyk SaaS users SSO functionality is a separate paid for add-on. For Self-Managed installations, SSO functionality is available for all license types.
Is it still a separate paid for add-on for Tyk SaaS or is this no longer the case?

2024-03-14 10:12 UTC, dcs3spp commented on tyk-docs/content/tyk-dashboard/rbac.md
> +You must then create a *user* in the Dashboard with the required permissions and matching email address. During the SSO login flow, if a user with the same email address is found in the existing orga
Did not understand this sentence in line 61. _During the SSO login flow, if a user with the same email address is found in the existing organisation, their permissions are applied_

- Existing Dashboard user (A) with the same email address pre-exists and has permissions created
- New Dashboard user (B) with same email address is created with a different set of permissions 

When user A is created then user B's permissions are silently assigned?

2024-03-15 15:16 UTC, andrei-tyk commented on tyk-docs/content/tyk-dashboard/rbac.md
> +If, however, you have multiple users who require the same set of permissions and you have the appropriate option in your Tyk licence, you can create a *user group* to apply and [manage user permissio
```suggestion
If, however, you have multiple users who require the same set of permissions and you have the appropriate option in your Tyk licence, you can create a *user group* to apply and [manage user permissions for multiple users]({{< ref "basic-config-and-security/security/dashboard/create-user-groups" >}}) from the same place. If you update the permissions of the user group, all the users assigned to it will automatically get those updated permissions. Additionally, if you deactivate the user group, all users in it will be disabled as well. **This functionality requires a specific Tyk licence.**
```

2024-03-19 10:41 UTC, dcs3spp commented
Thanks for peer review @andrei-tyk Could you check if your requested changes are ok and if so approve the PR?
@andyo-tyk I have resolved some comments. Comments remaining are questions, adding a link and a fix for removing Tyk Classic API and replacing with Tyk OAS API in a section relating to Tyk OAS API

2024-03-21 13:10 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/dashboard/create-user-groups.md
> -{{< note success >}}
I've moved this to the new Permissions [page](https://deploy-preview-4236--tyk-docs.netlify.app/docs/nightly/basic-config-and-security/security/dashboard/user-roles/#custom-user-permissions) - it doesn't make sense to explain this concept here.

2024-03-28 16:38 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/dashboard/create-users.md
> +Dashboard users are not the same as developer portal users ([developers]({{< ref "tyk-developer-portal/tyk-portal-classic/portal-concepts#developers" >}})), the user records are stored completely sep
```suggestion
Dashboard users are not the same as developer portal users (a.k.a. [developers]({{< ref "tyk-developer-portal/tyk-portal-classic/portal-concepts#developers" >}})). The credentials are stored independently and have different mechanics relating to registration, management and access. For example, it is not possible to log into the developer portal using a dashboard account.
```

2024-03-28 16:39 UTC, andyo-tyk commented on tyk-docs/content/tyk-dashboard/rbac.md
> -For Tyk SaaS users SSO functionality is a separate paid for add-on. For Self-Managed installations, SSO functionality is available for all license types.
I believe this referred to the old Tyk Cloud Classic

2024-03-28 16:42 UTC, andyo-tyk commented on tyk-docs/content/tyk-dashboard/rbac.md
> +You must then create a *user* in the Dashboard with the required permissions and matching email address. During the SSO login flow, if a user with the same email address is found in the existing orga
My understanding is:
If user (A) exists with email address bob@enterprise.co and a set of permissions, if another user (B) registers an account with the same email address (bob@enterprise.co) then B will inherit A's permissions.

Note that the bulk of this PR is restructuring the existing RBAC/user management/permissions documentation - not adding new functionality.

2024-03-28 16:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +A Dashboard User (or User Group) can be assigned as *owner* of an API, granting them visibility of and - given appropriate permissions - the ability to manage all the Tyk objects relating to that API
```suggestion
By default, APIs and associated objects (such as policies and Dashboard analytics) are visible to all Tyk Dashboard users.

A Dashboard User (or User Group) can be assigned as the *owner* of an API, granting that user (or user group) exclusive visibility of and - given appropriate permissions - the ability to manage all the Tyk objects relating to that API, such as policies, key requests and Dashboard analytics.

Once an API has been assigned an *owner*, all non-owning users will lose visibility of - and access to - that API in the Tyk Dashboard.
```

2024-03-28 16:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +When there is no owner assigned to an API, it and objects using it are visible to all users.
```suggestion
```

2024-03-28 16:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +
```suggestion
```

2024-03-28 16:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +| `PUT`  | `/apis/{apiId}/access`  | Assign a list of owners to the specified API                                           |
Typo

2024-03-28 16:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
> +| `PUT`  | `/api/apis/{apiId}` | Update the API definition for the specified API - CRUD API owners in the `user_owners` and `user_group_owners` fields |
Typo

2024-03-28 16:52 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/dashboard/organisations.md
> +A user that does not belong to an Organisation is sometimes referred to as an *unbounded user*. These users have visibility across all Organisations, but should be granted read-only access.
I don't think so

2024-03-28 16:52 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/dashboard/user-roles.md
> +You can also configure these custom permissions in the `security.additional_permissions` map in the Tyk Dashboard configuration file.
```suggestion
You can also configure these custom permissions in the `security.additional_permissions` [map]({{< ref "tyk-dashboard/configuration#securityadditional_permissions" >}}) in the Tyk Dashboard configuration file. 
```

2024-03-28 17:10 UTC, dcs3spp approved these changes
@andyo-tyk PR LGTM and have approved. @andrei-tyk Could peer review and once approved will merge to main branch ready for release.

2024-04-04 08:04 UTC, andrei-tyk approved these changes

2024-04-04 09:29 UTC, merged