[TT-11474] Document the new data source import API implementation
TykTechnologies/tyk-docs-hugo pull request #4250
Opened 2024-03-14 09:37 UTC by buraksezer

PR for [TT-11474](https://tyktech.atlassian.net/browse/TT-11474).

I preferred to add a new page for the new version of the data source import endpoint. I tried to add the new document to the previous one, but the resulting document was complex. There may be two ways to document the new features:

* Removing the old document and mentioning the old API version as "legacy" in the new document. We can simply put a link to the old one. Such as "The legacy endpoint document can be seen [here](https://tyk.io/docs/tyk-apis/tyk-dashboard-api/data-graphs-api/)."
* Both versions can live together but we can mark the old version as "legacy" by renaming its title or adding a warning message to the first line.

What do you think?

2024-03-18 09:40 UTC, agata-wit approved these changes

2024-03-18 09:42 UTC, agata-wit commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +| ContentType  | `application/vnd.tyk.udg.v2.asyncapi`  |
```suggestion
| Content-Type  | `application/vnd.tyk.udg.v2.asyncapi`  |
```

2024-03-18 09:45 UTC, agata-wit commented
> I preferred to add a new page for the new version of the data source import endpoint. I tried to add the new document to the previous one, but the resulting document was complex. There may be two ways to document the new features:
> 
> * Removing the old document and mentioning the old API version as "legacy" in the new document. We can simply put a link to the old one. Such as "The legacy endpoint document can be seen [here](https://tyk.io/docs/tyk-apis/tyk-dashboard-api/data-graphs-api/)."
> * Both versions can live together but we can mark the old version as "legacy" by renaming its title or adding a warning message to the first line.
> 
> What do you think?

Is it possible to have the doc change depending on which version is chosen from the dropdown on the docs page?

2024-03-18 09:46 UTC, buraksezer commented
> > I preferred to add a new page for the new version of the data source import endpoint. I tried to add the new document to the previous one, but the resulting document was complex. There may be two ways to document the new features:
> > 
> > * Removing the old document and mentioning the old API version as "legacy" in the new document. We can simply put a link to the old one. Such as "The legacy endpoint document can be seen [here](https://tyk.io/docs/tyk-apis/tyk-dashboard-api/data-graphs-api/)."
> > * Both versions can live together but we can mark the old version as "legacy" by renaming its title or adding a warning message to the first line.
> > 
> > What do you think?
> 
> Is it possible to have the doc change depending on which version is chosen from the dropdown on the docs page?

Yes, it should be possible. This is basically what I proposed.

2024-03-18 18:10 UTC, dcs3spp requested changes
Hi @buraksezer, thanks for submitting the PR with the new data source import API implementation.

Does the content of this PR relate to 5.3.0 release only?

If so then we can update the content in the original file _tyk-apis/tyk-dashboard-api/data-graphs-api.md_ and merge and release only to release-5.3.0.

The legacy version will then only be available in earlier release versions / branches, e.g. release 5.2, 5.1. etc. This way we can allow the user to use the version drop down list to view earlier versions of the document as suggested by @agata-wit 

For example:
- URL for latest version is https://tyk.io/docs/tyk-apis/tyk-dashboard-api/data-graphs-api/ 
- URL for historic version, e.g. 5.1, is https://tyk.io/docs/5.1/tyk-apis/tyk-dashboard-api/data-graphs-api/

Note, the content path is the same, but the base URL is different and versioned.

@buraksezer Would you be able to create a Jira ticket in the DX project space for the review and add the DX ticket ID, e.g. DX-9999, to the PR title and description?

2024-03-18 18:10 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +The Dashboard exposes the `/api/data-graphs/data-sources/import` Dashboard API which allows you to import an [AsyncAPI](https://www.asyncapi.com/docs/reference/specification/v3.0.0) or [OpenAPI](http
```suggestion
The Dashboard exposes the `/api/data-graphs/data-sources/import` endpoint which allows you to import an [AsyncAPI](https://www.asyncapi.com/docs/reference/specification/v3.0.0) or [OpenAPI](https://swagger.io/specification/) document.
```

2024-03-18 18:10 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +### Load the document from a remote resource and import it.
```suggestion
### Import a document from a remote resource
```

2024-03-18 18:10 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +It returns an error if it fails to determine the format and the document type.
What error status code is returned?

2024-03-18 18:10 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +The same as in other endpoints.
```suggestion
The response is structure is consistent with other endpoints, as shown in the table below:
```

2024-03-18 18:10 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +| Meta         | API Id for success and `null` with error (not in use) |
```suggestion
| Meta         | API ID for success and `null` with error (not in use) |
```

2024-03-20 09:21 UTC, buraksezer commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +It returns an error if it fails to determine the format and the document type.
It depends on what went wrong during the processing. It may return HTTP 500 if a programming or network error occurs, and it returns HTTP 400 if the fetched request body is malformed.

2024-03-20 09:28 UTC, buraksezer commented
Hey @dcs3spp thank you for your comment. 

> Does the content of this PR relate to 5.3.0 release only?
> If so then we can update the content in the original file tyk-apis/tyk-dashboard-api/data-graphs-api.md and merge and release only to release-5.3.0.

This improvement only merged into the `master` branch in tyk-analytics. It relates to 5.4.0. The fix version is 5.4.0. https://tyktech.atlassian.net/browse/TT-11248. Can we still merge the new document with the old one?

2024-03-21 09:08 UTC, buraksezer commented
@dcs3spp ping

2024-03-21 17:58 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +It returns an error if it fails to determine the format and the document type.
@buraksezer 

Is this suggestion ok?

```suggestion
It returns an error if it fails to determine the format and the document type. HTTP 500 is returned if a programming or network error occurs. If the fetched request body is malformed then HTTP 400 is returned. 
```

2024-03-21 18:04 UTC, dcs3spp commented
> Hey @dcs3spp thank you for your comment.
> 
> > Does the content of this PR relate to 5.3.0 release only?
> > If so then we can update the content in the original file tyk-apis/tyk-dashboard-api/data-graphs-api.md and merge and release only to release-5.3.0.
> 
> This improvement only merged into the `master` branch in tyk-analytics. It relates to 5.4.0. The fix version is 5.4.0. https://tyktech.atlassian.net/browse/TT-11248. Can we still merge the new document with the old one?

@buraksezer 
If the page will not change in 5.2.0 or 5.3.0 then why not update the content for 5.4.0 within file _tyk-apis/tyk-dashboard-api/data-graphs-api.md_? Then when it is time for release of 5.4.0 it only gets released to release-5.4 branch and historic versions for the samepage can be viewed using the drop down versions selector. This will render the page contents for whatever version of the page is required, e.g. 5.3, 5.2.

2024-03-22 08:48 UTC, buraksezer commented
> > Hey @dcs3spp thank you for your comment.
> > > Does the content of this PR relate to 5.3.0 release only?
> > > If so then we can update the content in the original file tyk-apis/tyk-dashboard-api/data-graphs-api.md and merge and release only to release-5.3.0.
> > 
> > 
> > This improvement only merged into the `master` branch in tyk-analytics. It relates to 5.4.0. The fix version is 5.4.0. https://tyktech.atlassian.net/browse/TT-11248. Can we still merge the new document with the old one?
> 
> @buraksezer If the page will not change in 5.2.0 or 5.3.0 then why not update the content for 5.4.0 within file _tyk-apis/tyk-dashboard-api/data-graphs-api.md_? Then when it is time for release of 5.4.0 it only gets released to release-5.4 branch and historic versions for the samepage can be viewed using the drop down versions selector. This will render the page contents for whatever version of the page is required, e.g. 5.3, 5.2.

I merged two documents. Now, everything is in `data-graphs-api.md` file.

2024-03-22 15:00 UTC, dcs3spp requested changes, later dismissed
Thanks for updating. From a DX perspective why was the Postman example removed and do all the import endpoints in this PR require stringification?

2024-03-22 15:00 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graphs-api.md
> +The document can be in JSON or YAML format. The import API can determine the type and parse it.
Should this be stringified also like in the previous case?

2024-03-22 15:00 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graphs-api.md
> -### Suggestion for "stringifying" with *Postman*
From a DX perspective, why has this been removed?

2024-03-22 15:39 UTC, buraksezer commented
> Thanks for updating. From a DX perspective why was the Postman example removed and do all the import endpoints in this PR require stringification?

The improved endpoint's purpose is to remove stringification from this API, which is no longer required.

2024-03-22 15:41 UTC, buraksezer commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graphs-api.md
> +The document can be in JSON or YAML format. The import API can determine the type and parse it.
Stringification was a required for the previous version of this endpoint. This step was removed. Please see my test guideline(the first comment) in this ticket: https://tyktech.atlassian.net/browse/TT-11248

2024-03-26 09:44 UTC, buraksezer commented
@dcs3spp I'm not authorized to merge this pull request. Could you please merge this PR if everything is OK?

2024-03-26 14:23 UTC, dcs3spp approved these changes
@buraksezer Thanks for updating the changes. PR LGTM and is ready for targeted 5.4.0 release as discussed in PR conversation. 

Currently, if this PR gets merged to main branch it will be released with 5.3.0. I have approved the PR and suggest closing the PR, tagging the PR on the ticket and reopening nearer the time of 5.4.0 release. This way the PR does not inadvertently get released with a 5.3.x release.  @letzya

2024-03-27 11:31 UTC, agata-wit commented
Closing for now. Will reopen in time for 5.4 docs creation and release.

2024-06-21 11:44 UTC, dcs3spp commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +The response is structure is consistent with other endpoints, as shown in the table below:
@buraksezer Should this be:

```suggest
The response structure is consistent with other endpoints, as shown in the table below:
```

2024-06-21 11:59 UTC, buraksezer commented on tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graph-api-new.md
> +The response is structure is consistent with other endpoints, as shown in the table below:
Fixed now

2024-06-21 13:39 UTC, dcs3spp commented
@buraksezer I can merge this to main branch now ready for release, yes?

2024-06-21 13:50 UTC, buraksezer commented
> @buraksezer I can merge this to main branch now ready for release, yes?

Yes, you can merge it into master and release-5.4 branches. This improvement has released as a part of 5.4

2024-06-21 15:00 UTC, merged