Updated KV storage docs
TykTechnologies/tyk-docs-hugo pull request #4288
Opened 2024-03-18 15:35 UTC by andyo-tyk

### Preview Link

### Description
Moved KV storage section to Deployment and Operations > Deployment Phase
Created separate pages for Consul and Vault
Updated content for usability and to include new capability in 5.3.0

2024-03-19 09:59 UTC, dcs3spp requested changes
@andyo-tyk PR LGTM, Is this a duplicate of this [PR](https://github.com/TykTechnologies/tyk-docs/pull/4247)?

I've made some minor suggestions and left comments on adding if time related config fields are measured in seconds or milliseconds. 

Can understand why the environment variables section was removed from the Tyk Gateway configuration section. If removing the environment variables section then add links to the relevant config sections for each list item in the Tyk Gateway configuration file section to make it easier for the users to find the corresponding config environment variable

2024-03-19 09:59 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +| wait_time | |
What is the wait time measured in? Seconds or milliseconds?

2024-03-19 09:59 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +| timeout | |
Timeout to connect to the server is in seconds or milliseconds?

2024-03-19 09:59 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/vault.md
> +| timeout | |
Timeout is in seconds or milliseconds?

2024-03-19 09:59 UTC, dcs3spp commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> +[Consul](https://www.consul.io) from Hashicorp is a distributed, highly available, and data centre aware solution to connect and configure applications across dynamic, distributed infrastructure. It
Can remove the repeated use of distributed?

[Consul](https://www.consul.io) from Hashicorp is a highly available and data centric solution to connect and configure applications across a dynamic, distributed infrastructure. It can be used to store and retrieve Tyk Gateway configuration across multiple data centers.

2024-03-19 09:59 UTC, dcs3spp commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> -TYK_GW_SECRET
If removing the environment variables section then add links to the relevant config sections for each list item in the Tyk Gateway configuration file section

2024-03-19 09:59 UTC, dcs3spp commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +[Consul](https://www.consul.io) from Hashicorp is a distributed, highly available, and data centre aware solution to connect and configure applications across dynamic, distributed infrastructure. It
Can remove the repeated use of distributed?

[Consul](https://www.consul.io/) from Hashicorp is a highly available and data centric solution to connect and configure applications across a dynamic, distributed infrastructure

2024-03-19 17:27 UTC, andyo-tyk commented
It's not a duplicate of https://github.com/TykTechnologies/tyk-docs/pull/4247, it's a replacement (the other one was a draft)

2024-03-21 09:37 UTC, jeffy-mathew commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +From Tyk Gateway v5.3 onwards, you can store **any `string` field** from the API definition in Consul; for earlier versions of Tyk Gateway only the **Target URL** and **Listen Path** fields were supp
`v5.3.0` onwards?

2024-03-21 09:37 UTC, jeffy-mathew commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> +When the Gateway starts, Tyk will read the *Value* from the `secrets` section in the API definition and use this as the [Target URL]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#upstream" >}})
In the case of API definition, key values are replaced during a hot reload as well (not just when gateway starts)

2024-03-21 15:06 UTC, andyo-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +[Consul](https://www.consul.io) from Hashicorp is a distributed, highly available, and data centre aware solution to connect and configure applications across dynamic, distributed infrastructure. It
```suggestion
HashiCorp [Consul](https://www.consul.io) is a service networking solution that is used to connect and configure applications across dynamic, distributed infrastructure. Consul KV is a simple Key-Value store provided as a core feature of Consul that can be used to store and retrieve Tyk Gateway configuration across multiple data centres.
```

2024-03-21 15:06 UTC, andyo-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +From Tyk Gateway v5.3 onwards, you can store **any `string` field** from the API definition in Consul; for earlier versions of Tyk Gateway only the **Target URL** and **Listen Path** fields were supp
```suggestion
From Tyk Gateway v5.3.0 onwards, you can store **any `string` field** from the API definition in Consul; for earlier versions of Tyk Gateway only the **Target URL** and **Listen Path** fields were supported. 
```

2024-03-21 15:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> +[Consul](https://www.consul.io) from Hashicorp is a distributed, highly available, and data centre aware solution to connect and configure applications across dynamic, distributed infrastructure. It
```suggestion
HashiCorp [Consul](https://www.consul.io) is a service networking solution that is used to connect and configure applications across dynamic, distributed infrastructure. Consul KV is a simple Key-Value store provided as a core feature of Consul that can be used to store and retrieve Tyk Gateway configuration across multiple data centres.
```

2024-03-21 15:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> -TYK_GW_SECRET
The problem with this is that our docs style sheet won't allow `code` format within a hyperlink, so the list of fields will not be clearly identifiable as such.
I have provided a link to the page containing all the fields, I believe this is sufficient. I have deliberately removed the environment variables section as it does not add anything other than potential for confusion (given the reference to environment variables as an option for the KV store).

2024-03-21 15:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> +When the Gateway starts, Tyk will read the *Value* from the `secrets` section in the API definition and use this as the [Target URL]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#upstream" >}})
I'd mentioned this on the next line. To make this clearer, however, I will move it further up the page.

2024-03-21 15:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> +These references are read (and replaced with the values read from the KV location) when the API is loaded to the Gateway.
```suggestion
```

Moved this line above the example for clarity.

2024-03-21 15:06 UTC, andyo-tyk commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> + - Environment variables: `env://key`
```suggestion
 - Environment variables: `env://key`

These references are read (and replaced with the values read from the KV location) when the API is loaded to the Gateway (either when Gateway restarts or when there is a hot-reload).
```

2024-03-21 15:08 UTC, jeffy-mathew commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> + - Vault: `vault://path/to/secret.key`
When using `vault` and `consul`, the secrets are expected to be stored under path `tyk-apis`.
https://github.com/TykTechnologies/tyk/blob/6ab2b56930ce9e625a6aacfeb2938ad48c55e349/gateway/api_definition.go#L559.
The API path for vault in this case would look like `/v1/secret/data/tyk-apis`

2024-03-21 15:22 UTC, andyo-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +[Consul](https://www.consul.io) from Hashicorp is a distributed, highly available, and data centre aware solution to connect and configure applications across dynamic, distributed infrastructure. It
I've updated this with a non-repetitive alternative.

2024-03-21 15:23 UTC, andyo-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/vault.md
> +| timeout | |
@jeffy-mathew can you check this, please?

2024-03-21 16:00 UTC, jeffy-mathew commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> + - Vault: `vault://path/to/secret.key`
Confirmed that this is the case for consul as well.
`tyk-apis/` is the expected folder in which keys are to be present

2024-03-21 16:02 UTC, jeffy-mathew commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> + - Vault: `vault://path/to/secret.key`
when it comes to usage in API definition it can be simply.
`vault://foo` and `consul://foo`. 
NOTE: this is a requirement only with newly added feature where all fields can have secrets.

For existing supported fields, such as listen path and upstream url, this is not a requirement, the key can be under any path.

2024-03-21 16:22 UTC, jeffy-mathew commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> +                      "rewriteTo": "/api/v1/users/$secret_consul.user_id",
We have a limitation wrt replacing secrets with url rewrite middlewares. 
The secret to be used has to be the last part in rewriteTo url fragment. 
For example, I have a key named `rewriteTo` with value `foo` in path `tyk-secrets` in consul, to access that we have to specify rewriteTo to be something like `/api/v1/users/$secret_consul.tyk-secrets/rewriteTo`. It will redirect to  `/api/v1/users/foo`, this works only when the secret is the last part of the url. 
If there is a user case where we want to have another path part after resolving secret from consul/vault, that won't work, for eg. if the rewriteTo url is something like`/api/v1/users/$secret_consul.tyk-secrets/rewriteTo/action` with an expectation to redirect to  `/api/v1/users/foo/action` but it will actually redirect to  `/api/v1/users/` since the resolution failed to get key `$secret_consul.tyk-secrets/rewriteTo/action`.

2024-03-22 10:02 UTC, jeffy-mathew commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> + - Vault: `vault://path/to/secret.key`
We also cannot use a subfolder inside `tyk-apis`

2024-04-02 14:35 UTC, andyo-tyk commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> +                      "rewriteTo": "/api/v1/users/$secret_consul.user_id",
Thanks - I will raise a separate PR to add this to the URL rewrite docs.

2024-04-03 11:35 UTC, jeffy-mathew commented on tyk-docs/content/tyk-configuration-reference/kv-store.md
> +Most Key-Value references are only retrieved when the configuration object (Gateway or API) is loaded, as explained above: changes to the externally stored value will not be detected until a subseque
```suggestion
Most Key-Value references are only retrieved when the configuration object (Gateway or API) is loaded, as explained above: changes to the externally stored value will not be detected until a subsequent gateway hot-reload.
```

2024-04-03 11:35 UTC, jeffy-mathew approved these changes

2024-04-03 12:04 UTC, andyo-tyk reviewed
Jeff has confirmed the Vault and Consul time units

2024-04-03 12:04 UTC, andyo-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +| wait_time  | Limits how long a [watch will block](https://developer.hashicorp.com/consul/api-docs/features/blocking) (if enabled in your Consul service) |
```suggestion
| wait_time  | Limits how long a [watch will block](https://developer.hashicorp.com/consul/api-docs/features/blocking) in milliseconds (if enabled in your Consul service) |
```

2024-04-03 12:04 UTC, andyo-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/vault.md
> +| timeout      | The maximum time that Tyk will wait for a response from Vault                                          |
```suggestion
| timeout      | The maximum time that Tyk will wait for a response from Vault (in nanoseconds, if set to 0 (default) will be interpreted as 60 seconds)                                         |
```

2024-04-03 12:05 UTC, andyo-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +| wait_time | |
milliseconds

2024-04-03 12:05 UTC, andyo-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
> +| timeout | |
N/A - this field isn't present for Consul

2024-04-03 12:05 UTC, andyo-tyk commented on tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/vault.md
> +| timeout | |
Value is in nanoseconds.

2024-04-03 14:19 UTC, dcs3spp approved these changes
@andyo-tyk PR LGTM I'll merge ready for release

2024-04-03 14:29 UTC, merged