[TT-11699] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #4317
Opened 2024-03-21 17:13 UTC by buger

Triggered by: sredxny

Included:

Tyk Gateway: false
Tyk Dashboard: false
Tyk MDCB true
Tyk Pump false

Intended for: master
Changes sourced from: release-2.5
Config info generator branch: main

Note: <none> (branch suffix: docs)

JIRA: https://tyktech.atlassian.net/browse/TT-11699

2024-03-22 15:13 UTC, dcs3spp requested changes
@sredxny Thanks for raising the config update for MDCB 2.5.0. I have reviewed with minor suggestions. If you rerun the config generator GHub action with the same parameters, including your TT ticket ID it will update this PR and incorporate the changes.

2024-03-22 15:13 UTC, dcs3spp commented on tyk-docs/content/shared/mdcb-config.md
> +Set a custom timeout for Redis network operations. Default value 5 seconds.
```suggestion
Set a custom timeout for Redis network operations. Default value is 5 seconds.
```

2024-03-22 15:13 UTC, dcs3spp commented on tyk-docs/content/shared/mdcb-config.md
> +Enable SSL/TLS connection between your Tyk MDCB & Redis.
```suggestion
Enable SSL/TLS connection between Tyk MDCB & Redis.
```

2024-03-22 15:13 UTC, dcs3spp commented on tyk-docs/content/shared/mdcb-config.md
> +Disable TLS verification
```suggestion
Disable TLS verification.
```

2024-03-22 15:13 UTC, dcs3spp commented on tyk-docs/content/shared/mdcb-config.md
> +Determines the driver used by the storage. It could be `mongo-go` to use the official mongo driver for go or `mgo` to use the old driver.
```suggestion
Use `mongo-go` to use the official mongo driver. Alternatively, use `mgo` to use the old driver.
```

2024-03-22 15:13 UTC, dcs3spp commented on tyk-docs/content/shared/mdcb-config.md
> +Set a custom timeout for Redis network operations. Default value 5 seconds.
```suggestion
Set a custom timeout for Redis network operations. Default value is 5 seconds.
```

2024-03-22 15:13 UTC, dcs3spp commented on tyk-docs/content/shared/mdcb-config.md
> +Disable TLS verification
```suggestion
Disable TLS verification.
```

2024-03-24 23:10 UTC, sredxny commented
@dcs3spp check again please. Suggestions has been addressed

2024-03-26 12:57 UTC, dcs3spp approved these changes
Thanks @sredxny I've approved PR. Before merging could you request a peer review? Once peer approved will merge to main branch. Should this be released with 5.3 only?

2024-04-05 11:57 UTC, merged