Tyk OAS launch notices and restructuring for 5.3
TykTechnologies/tyk-docs-hugo pull request #4382
Opened 2024-04-05 15:30 UTC by andyo-tyk

### For internal users - Please add a Jira DX PR ticket to the subject!

---

### Preview Link

### Description
This seems quite big, but is basically a reordering of pages in the Tyk Gateway and Tyk Dashboard docs, removing some that are no longer required and applying changes for Tyk OAS maturity to improve usability of the docs. Unfortunately a lot of this had to happen together. No technical content changes.

2024-04-08 13:39 UTC, dcs3spp requested changes
@andyo-tyk PR LGTM, I have made minor suggestions and commented reagrding if Tyk GW automatically migrates Tyk OAS API Definitions to new format or if this is just Dashboard

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
> +An example of the sort of flow we envisage can be seen below. One of the great things about working with Tyk OAS is that you can have a single file that you deploy across your workflow. You then iter
```suggestion
An example of the sort of flow we envisage can be seen below. One of the great things about working with Tyk OAS is that you can have a single file that you deploy across your workflow. You then iterate on that one file until you are totally happy. At this point, you can publish the ‘public’ part of the API Definition to your developer portal (i.e. exactly what a Developer needs to use the API and nothing they don’t need to see like Tyk configuration details). You can also put the whole document into source control. Since you are using a single file for the whole flow, you can add in automation such as automatically trigger deploying an updated API when a new version is committed into your source control. This model is very popular in GitOps and CI/CD environments.
```

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
> +The picture below shows the same flow, making it clear when the API Definition includes the Tyk-specific information needed to configure Tyk Gateway vs when it is just the OpenAPI information describ
```suggestion
The illustration below shows the same flow, highlighting that the API Definition includes the Tyk-specific information needed to configure Tyk Gateway, compared to when it is just the OpenAPI information describing your upstream service (required by an API Developer to create a service client).
```

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
> +The key question is whether there is anything you currently use in your Tyk Classic APIs that isn’t yet supported by our Tyk OAS APIs. Whilst we have reached *feature maturity* for Tyk OAS, some Tyk
```suggestion
The key question is whether there is anything you currently use in your Tyk Classic APIs that isn’t yet supported by our Tyk OAS APIs. Whilst we have reached *feature maturity* for Tyk OAS, some Tyk Gateway features are not yet supported. You can see the status of what is and isn't yet supported [here]({{< ref "getting-started/using-oas-definitions/oas-reference" >}}).
```

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
> +In Tyk Gateway release 5.3.0, Tyk OAS APIs gained feature maturity. Tyk will automatically migrate any pre-5.3.0 Tyk OAS APIs to the feature mature standard when you upgrade to 5.3.0 or later. Featur
Tyk Dashboard automatically migrates older Tyk OAS APIs, does Tyk Gateway also do automated migration or does this need to be done manually?

_In Tyk Gateway release 5.3.0, Tyk OAS APIs gained feature maturity. Tyk Dashboard will automatically migrate any pre-5.3.0 Tyk OAS APIs to the feature mature standard when you upgrade to 5.3.0 or later. Tyk OAS APIs prior to v5.3.0 must be manully migrated for Tyk OSS Gateway. Feature mature Tyk OAS APIs may not work with pre-5.3.0 versions of Tyk Gateway._

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
> +For further details, please refer to the [release notes]({{< ref "product-stack/tyk-gateway/release-notes/overview" >}}) for Tyk Gateway v5.3.0.
```suggestion
For further details, please refer to the [release notes]({{< ref "product-stack/tyk-gateway/release-notes/version-5.3" >}}) for Tyk Gateway v5.3.0.
```

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
> +If you already have a standard [OpenAPI document]({{< ref "getting-started/using-oas-definitions/oas-glossary#openapi-document" >}}) for your API, you can very easily [import it into Tyk]({{< ref "ge
```suggestion
If you already have a standard [OpenAPI document]({{< ref "getting-started/using-oas-definitions/oas-glossary#openapi-document" >}}) for your API, you can very easily [import it into Tyk]({{< ref "getting-started/using-oas-definitions/import-an-oas-api" >}}) and have it running in seconds. During the import Tyk will generate the required Tyk extension based on the OpenAPI description in the OpenAPI document and optional parameters you set in the import command. It will also try to establish the right place to send requests to and update the ‘public’ part of the API Definition to tell users how to send requests to the API gateway. It is also possible to [automatically configure some Tyk middleware]({{< ref "api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware" >}}) from the OpenAPI description, configuring how Tyk will handle requests to the API. An import takes in an *OpenAPI document* file and turns it into a *Tyk OAS API Definition*.
```

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
> +Tyk Gateway is extremely flexible with a great many features that you can use to configure and optimise the handling of requests to your APIs. During the [Early Access]({{< ref "/frequently-asked-que
```suggestion
Tyk Gateway is extremely flexible with a great many features that you can use to configure and optimise the handling of requests to your APIs. During the [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}) phase, we gradually rolled out support for the configuration that is available through Tyk Classic API definitions into the new Tyk OAS API Definition format.
```

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/plugins/supported-languages/rich-plugins/python/python.md
> +Whilst Python plugins are still supported by Tyk Gateway, if you want to use them you must extend the image to add support for Python. For further details, please refer to the [release notes]({{< ref
```suggestion
Whilst Python plugins are still supported by Tyk Gateway, if you want to use them you must extend the image to add support for Python. For further details, please refer to the [release notes]({{< ref "product-stack/tyk-gateway/release-notes/version-5.3" >}}) for Tyk Gateway `v5.3.0`.
```

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/first-api.md
> +In Tyk Gateway release 5.3.0, Tyk OAS APIs gained feature maturity. Tyk will automatically migrate any pre-5.3.0 Tyk OAS APIs to the feature mature standard when you upgrade to 5.3.0 or later. Featur
Is it only Tyk Dashboard that automatically migrates older Tyk OAS APIs to v5.3.0? Does Tyk Gateway require manual update of Tyk OAS API format?

2024-04-08 13:39 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/first-api.md
> +For further details, please refer to the [release notes]({{< ref "product-stack/tyk-gateway/release-notes/overview" >}}) for Tyk Gateway v5.3.0.
tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md

```suggestion
For further details, please refer to the [release notes]({{< ref "product-stack/tyk-gateway/release-notes/version-5.3" >}}) for Tyk Gateway v5.3.0.
```

2024-04-08 16:50 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
> +In Tyk Gateway release 5.3.0, Tyk OAS APIs gained feature maturity. Tyk will automatically migrate any pre-5.3.0 Tyk OAS APIs to the feature mature standard when you upgrade to 5.3.0 or later. Featur
Yes, Dashboard performs the migration, not Gateway. This page is now part of the API Management section, not Product Stack, so can talk about both components.

2024-04-08 16:50 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
> +In Tyk Gateway release 5.3.0, Tyk OAS APIs gained feature maturity. Tyk will automatically migrate any pre-5.3.0 Tyk OAS APIs to the feature mature standard when you upgrade to 5.3.0 or later. Featur
```suggestion
In Tyk Gateway release 5.3.0, Tyk OAS APIs gained feature maturity. Tyk Dashboard will automatically migrate any pre-5.3.0 Tyk OAS APIs to the feature mature standard when you upgrade to 5.3.0 or later. Tyk OAS APIs prior to v5.3.0 must be manually migrated if you are using Tyk OSS Gateway. Feature mature Tyk OAS APIs may not work with pre-5.3.0 versions of Tyk Gateway.
```

2024-04-08 16:53 UTC, andyo-tyk commented on tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/first-api.md
> +In Tyk Gateway release 5.3.0, Tyk OAS APIs gained feature maturity. Tyk will automatically migrate any pre-5.3.0 Tyk OAS APIs to the feature mature standard when you upgrade to 5.3.0 or later. Featur
Correct, it's Dashboard that performs migration. This page is in the "using Tyk Cloud" section, so I feel reference to OSS Gateway is irrelevant here as all Tyk Cloud users have Dashboard. I will add the word "Dashboard" for clarity.

2024-04-08 16:53 UTC, andyo-tyk commented on tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/first-api.md
> +In Tyk Gateway release 5.3.0, Tyk OAS APIs gained feature maturity. Tyk will automatically migrate any pre-5.3.0 Tyk OAS APIs to the feature mature standard when you upgrade to 5.3.0 or later. Featur
```suggestion
In Tyk Gateway release 5.3.0, Tyk OAS APIs gained feature maturity. Tyk Dashboard will automatically migrate any pre-5.3.0 Tyk OAS APIs to the feature mature standard when you upgrade to 5.3.0 or later. Feature mature Tyk OAS APIs may not work with pre-5.3.0 versions of Tyk Gateway.
```

2024-04-09 10:56 UTC, dcs3spp reviewed
Hi @andyo-tyk PR LGTM and thanks for updating PR from suggestions. I have had a final look through the PR.

The menu items have been [renamed](https://deploy-preview-4382--tyk-docs.netlify.app/docs/nightly/getting-started/key-concepts/openapi-specification/) in _Product Stack->Tyk Gateway (Open Source) -> Key Concepts->Tyk OAS & Tyk Classic._

Do the submenus relate to API Definitions or APIs or both? Should they be renamed as Tyk OAS API Definitions & Tyk Classic API Definitions or we could create a virtual subfolder in key concepts, something like? 

Tyk API Definitions
|
|——What Is An API Definition?
|——Tyk OAS??? 
|——Tyk Classic API???

The key concepts overview page is a [small page](https://deploy-preview-4382--tyk-docs.netlify.app/docs/nightly/getting-started/key-concepts/) and for this reason has been hidden via the menu.yaml in the PR.

Maybe it should be removed and create an alias to either: 
1. Product Stack -> Tyk Gateway (Open Source) -> Overview
2. Product Stack -> Tyk Gateway (Open Source) -> Key Concepts -> What is an API Definition?
or....
3. Keep visible and expand overview content at a later date

2024-04-09 11:59 UTC, andyo-tyk commented
> Hi @andyo-tyk PR LGTM and thanks for updating PR from suggestions. I have had a final look through the PR.
> 
> The menu items have been [renamed](https://deploy-preview-4382--tyk-docs.netlify.app/docs/nightly/getting-started/key-concepts/openapi-specification/) in _Product Stack->Tyk Gateway (Open Source) -> Key Concepts->Tyk OAS & Tyk Classic._
> 
> Do the submenus relate to API Definitions or APIs or both? Should they be renamed as Tyk OAS API Definitions & Tyk Classic API Definitions or we could create a virtual subfolder in key concepts, something like? 
> 
> Tyk API Definitions | |——What Is An API Definition? |——Tyk OAS???  |——Tyk Classic API???
> 
> The key concepts overview page is a [small page](https://deploy-preview-4382--tyk-docs.netlify.app/docs/nightly/getting-started/key-concepts/) and for this reason has been hidden via the menu.yaml in the PR.
> 
> Maybe it should be removed and create an alias to either: 
> 
> 1. Product Stack -> Tyk Gateway (Open Source) -> Overview
> 2. Product Stack -> Tyk Gateway (Open Source) -> Key Concepts -> What is an API Definition?
>    or....
> 3. Keep visible and expand key cooncepts overview content at a later date

I'm trying to work as much as possible within the docs structure provided by the DX team as I don't think it's right for me to propose wholesale change in this PR.

I've moved pages where they are in the wrong part of the docs structure, but otherwise trying to work with what's already there.

As it happens, the (existing) content of the `Tyk Classic` folder appears to be (mostly, but not entirely) a description of the fields of the Tyk Classic API Definition (for which there is no godocs-generated page, unlike Tyk OAS API Definition which is automatically documented).

The content of the `Tyk OAS` folder is pages that provide high level explanation of some concepts used when working with Tyk OAS - however it is neither descriptions of the Tyk OAS API definition nor of "Tyk OAS APIs" (which are instances of Tyk OAS API definitions loaded into Tyk).

Perhaps rename these to:
- Tyk OAS concepts
- Tyk Classic concepts

(though for the latter, I think the docs need some TLC - out of scope for the Tyk OAS work I've been doing)

2024-04-09 13:34 UTC, dcs3spp approved these changes
@andyo-tyk I've approved PR and renamed the menu items Tyk OAS Concepts and Tyk Classic Concepts and will merge and release.

2024-04-09 13:35 UTC, merged

2024-04-09 13:35 UTC, dcs3spp commented
/release to release-5.3