Update the numbered list to match the graphic
TykTechnologies/tyk-docs-hugo pull request #439
Opened 2018-06-05 07:59 UTC by marksou

2018-06-06 19:43 UTC, letzya commented on tyk-docs/content/security/your-apis/openid-connect.md
> +7.  The Gateway Checks the OIDC token signature against Auth0's public key set.
check not Check?

2018-06-06 19:45 UTC, letzya commented on tyk-docs/content/security/your-apis/openid-connect.md
> +3.  The Identity Provider generates OAuth token set and OIDC ID Token The ID Token is signed by provider with their public key. This is then returned to the user.
Where's the comma?

2018-06-06 19:48 UTC, letzya commented on tyk-docs/content/security/your-apis/openid-connect.md
> +3.  The Identity Provider generates OAuth token set and OIDC ID Token The ID Token is signed by provider with their public key. This is then returned to the user.
Where's the comma? also doesn't read well.

Maybe:
The Identity Provider generates OIDC  `id_token` which is signed by provider with their public key and return it to the user

2018-06-06 19:53 UTC, letzya requested changes

2018-06-06 19:53 UTC, letzya commented on tyk-docs/content/security/your-apis/openid-connect.md
> +1.  A User logs in via a supported OIDC Provider to request access to their resource.
The original line is preferred

2018-06-06 19:53 UTC, letzya commented on tyk-docs/content/security/your-apis/openid-connect.md
> +2.  The User gains access to the Provider and uses their service.
The original line is preferred

2018-06-06 19:53 UTC, letzya commented on tyk-docs/content/security/your-apis/openid-connect.md
> +9.  Tyk then validates the users session according to the quotas, rate limits and access rules for the matching policy for **either** the bearer of the token across all clients they use from this IDP
this change is fine

2018-06-07 08:11 UTC, marksou commented on tyk-docs/content/security/your-apis/openid-connect.md
> +1.  A User logs in via a supported OIDC Provider to request access to their resource.
Change made

2018-06-07 08:11 UTC, marksou commented on tyk-docs/content/security/your-apis/openid-connect.md
> +2.  The User gains access to the Provider and uses their service.
Done

2018-06-07 08:11 UTC, marksou commented on tyk-docs/content/security/your-apis/openid-connect.md
> +3.  The Identity Provider generates OAuth token set and OIDC ID Token The ID Token is signed by provider with their public key. This is then returned to the user.
Done

2018-06-07 08:11 UTC, marksou commented on tyk-docs/content/security/your-apis/openid-connect.md
> +7.  The Gateway Checks the OIDC token signature against Auth0's public key set.
Changed

2018-06-07 08:12 UTC, merged