Gateway release notes 5.3.1
TykTechnologies/tyk-docs-hugo pull request #4399
Opened 2024-04-09 16:29 UTC by andyo-tyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

2024-04-19 12:14 UTC, dcs3spp requested changes
@andyo-tyk @Eopayemi I have made minor suggestions and uploaded some changes on  the branch to remove Sentence Casing from the change-log summary headings

Requires TBC fields for release date, download links and dependencies

2024-04-19 12:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Fixed a panic scenario occurring when JSVM is utilised alongside require_session:true and ignore auth middleware. While the JSVM middleware expects a valid session, the configuration flag doesn't gua
```suggestion
Fixed a panic scenario occurring when JSVM is utilised alongside require_session:true and ignore auth middleware. While the JSVM middleware expects a valid session, the `require_session` configuration flag doesn't guarantee its presence, only that it is passed if available.
```

2024-04-19 12:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Gateway panics when arguments are missing in persist GraphQL endpoint operations</summary>
```suggestion
<summary>Gateway panics when arguments are missing in persist GraphQL endpoints</summary>
```

2024-04-19 14:52 UTC, andyo-tyk reviewed
Added some suggested improvements to Core APIM changes. Spotted one that should be in Dashboard RN and flagged for removal.

2024-04-19 14:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Security enhancement: rejecting unsigned plugin bundles in Gateway</summary>
```suggestion
<summary>Security enhancement: don't load APIs into Gateway if custom plugin bundle fails to load</summary>
```

2024-04-19 14:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Resolved quota limit issue with API URL Rewrite to Self and Policy-Created Key</summary>
```suggestion
<summary>URL Rewrite middleware did not always correctly observe quotas for requests using keys created from policies</summary>
```

2024-04-19 14:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Fixed two bugs related to quota limits not being applied and incorrect reporting of remaining quota value in the X-RateLimitRemaining header when the API had URL rewrite middleware configured with a
```suggestion
Fixed two bugs in the handling of usage quotas by the URL rewrite middleware when it was configured to rewrite to itself (e.g. to `tyk://self`). Quota limits were not observed and the quota related response headers always contained `0`. 
```

2024-04-19 14:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Policy-API link deletion code updated to ensure DocumentDB compatibility</summary>
```suggestion
```

This is a Dashboard change - shouldn't be in this release note

2024-04-19 14:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Gateway panics addressed due to JSVM usage with ignore plugin</summary>
```suggestion
<summary>Fixed a Gateway panic that could occur when using custom JavaScript plugins with the Ignore Authentication middleware</summary>
```

2024-04-19 14:52 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Fixed a panic scenario occurring when JSVM is utilised alongside require_session:true and ignore auth middleware. While the JSVM middleware expects a valid session, the configuration flag doesn't gua
```suggestion
Fixed a panic scenario that occurred when a custom JavaScript plugin that requests access to the session metadata (`require_session:true`) is assigned to the same endpoint as the Ignore Authentication middleware. While the custom plugin expects access to a valid session, the configuration flag doesn't guarantee its presence, only that it's passed if available. As such, the custom plugin should be coded to verify that the session metadata is present before attempting to use it.
```

2024-04-23 16:15 UTC, dcs3spp requested changes
Thanks for updating change-log items @Eopayemi. I have made minor suggestions to update sentence case of change-log items.
Before approval dependencies, downloads and release date needs adding before release

2024-04-23 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Incorrect MDCB Gateway Counter on License Statistics Page</summary>
```suggestion
<summary>Incorrect MDCB Gateway Counter on License Statistics page</summary>
```

2024-04-23 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Missing GraphQL OTel Attributes in Spans on Request Validation Failure</summary>
```suggestion
<summary>Missing GraphQL OTel attributes in Spans on Request Validation failure</summary>
```

2024-04-23 16:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>API Cache Clearing from Dashboard Not Propagated to Edge Deployments</summary>
```suggestion
<summary>API cache clearing from Dashboard not propagated to edge deployments</summary>
```

2024-04-23 17:38 UTC, andyo-tyk reviewed
Proposed wording improvements

2024-04-23 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Issues were addressed where Tyk failed to properly reject custom plugin bundles with signature verification failures, allowing APIs to load without necessary plugins, potentially exposing upstream se
```suggestion
Issues were addressed where Tyk failed to properly reject custom plugin bundles with signature verification failures, allowing APIs to load without necessary plugins, potentially exposing upstream services. With the fix, if the plugin bundle fails to load (for example, due to failed signature verification) the API will not be loaded and an error will be logged in the Gateway.
```

2024-04-23 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +GraphQL APIs were returning incorrect responses when simultaneous GQL calls with different inputs were made, which looked as if caching was mixed up. This was related to a setting in the GraphQL engi
```suggestion
GraphQL APIs were returning incorrect responses when simultaneous GraphQL calls with different inputs were made, which looked as if caching was mixed up. This was related to a setting in the GraphQL engine, that has now been turned off, so simultaneous calls won't return an incorrect response.
```

2024-04-23 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +In some instances users were noticing gateway panics when using "Persist GQL operation middleware" without arguments defined. This issue has been fixed and the gateway will not throw panics in these
```suggestion
In some instances users were noticing gateway panics when using the "Persist GQL" middleware without arguments defined. This issue has been fixed and the gateway will not throw panics in these cases anymore.
```

2024-04-23 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Incorrect MDCB Gateway Counter on License Statistics Page</summary>
```suggestion
<summary>Tyk Dashboard License Statistics page could display incorrect number of data plane gateways</summary>
```

2024-04-23 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Resolved an issue where the MDCB gateway counter inaccurately incremented when a gateway was stopped and restarted.
```suggestion
Resolved an issue in distributed deployments where the MDCB data plane gateway counter was inaccurately incremented when a Gateway was stopped and restarted.
```

2024-04-23 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Missing GraphQL OTel Attributes in Spans on Request Validation Failure</summary>
```suggestion
<summary>Missing GraphQL OTel attributes in spans when requests fail validation</summary>
```

2024-04-23 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +In cases where detailed_tracing was set to false and client was sending a malformed request to a GQL API the traces were missing GQL attributes (operation name, type and document). This has been corr
```suggestion
In cases where `detailed_tracing` was set to `false` and the client was sending a malformed request to a GraphQL API, the traces were missing GraphQL attributes (operation name, type and document). This has been corrected and debugging GraphQL with OTel will be easier for users.
```

2024-04-23 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>API Cache Clearing from Dashboard Not Propagated to Edge Deployments</summary>
```suggestion
<summary>Unable to clear the API cache in distributed data plane Gateways from the control plane Dashboard</summary>
```

2024-04-23 17:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Addressed a bug where clearing the API cache from the Tyk Dashboard UI failed to invalidate the cache in distributed data plane gateways.
```suggestion
Addressed a bug where clearing the API cache from the Tyk Dashboard failed to invalidate the cache in distributed data plane gateways.
```

2024-04-24 14:43 UTC, andyo-tyk reviewed
Tweak to wording to improve comprehension

2024-04-24 14:43 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Resolved Gateway crashes with Python Plugin storage APIs</summary>
```suggestion
<summary>Gateway could crash when custom Python plugins attempted to access storage</summary>
```

2024-04-24 14:43 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Fixed a bug causing Python plugin storage APIs store_data and get_data to fail due to connection issues with configured storage.
```suggestion
Fixed a bug where the Gateway could crash when using custom Python plugins that access the Redis storage. The Tyk Python API methods `store_data` and `get_data` could fail due to connection issues with the Redis. With this fix, the Redis connection will be created if required, avoiding the crash.
```

2024-04-25 08:14 UTC, dcs3spp approved these changes
@andyo-tyk PR LGTM, I have added dependencies section with statement that links to 5.3.0 dependencies

2024-04-25 09:50 UTC, caroltyk requested changes

2024-04-25 09:50 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +If you are using 5.3.0 we advise you to upgrade ASAP and if you are on an older version you should skip 5.3.0 and upgrade directly to this release. Go to the [Upgrading Tyk](#upgrading-tyk) section f
If user is upgrading from older version and skip 5.3.0, they need to review and follow 5.3.0 upgrade instructions too.

2024-04-25 09:50 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +  - [tyk-charts GH Repo](https://github.com/TykTechnologies/tyk-charts/releases)
Latest helm chart release notes is in Docs: /product-stack/tyk-charts/release-notes/version-1.3

2024-04-25 10:00 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Addressed a bug where clearing the API cache from the Tyk Dashboard failed to invalidate the cache in distributed data plane gateways.
@andyo-tyk This one requires MDCB 2.5.1 is it? Should we note the dependency here?

2024-04-25 11:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +If you are using 5.3.0 we advise you to upgrade ASAP and if you are on an older version you should skip 5.3.0 and upgrade directly to this release. Go to the [Upgrading Tyk](#upgrading-tyk) section f
@caroltyk I have updated, if this and other comments are ok could you approve for release?

2024-04-25 11:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Addressed a bug where clearing the API cache from the Tyk Dashboard failed to invalidate the cache in distributed data plane gateways.
@caroltyk I have updated PR to mention MDCB 2.5.1. If ok and other comments ok would be to approve for release?

2024-04-25 11:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +  - [tyk-charts GH Repo](https://github.com/TykTechnologies/tyk-charts/releases)
@caroltyk I have updated PR to mention MDCB 2.5.1. If ok and other comments ok would be to approve for release?

2024-04-25 11:36 UTC, caroltyk approved these changes
LGTM

2024-04-25 11:56 UTC, merged

2024-04-25 11:56 UTC, dcs3spp commented
/release to release-5.3