Dashboard release notes 5.3.1
TykTechnologies/tyk-docs-hugo pull request #4400
Opened 2024-04-09 16:33 UTC by andyo-tyk

### For internal users - Please add a Jira DX PR ticket to the subject!

### Preview Link

2024-04-24 11:11 UTC, dcs3spp requested changes
Hi @Eopayemi , Thanks for updating the changelog items to Dashboard PR.
PR reads ok, minor change suggested relating to release summary. When copying over the release summaries from the confluence table does each release summary have every word capitalised?
- Enhanced Dashboard Privacy: Users Search Method Transitioned to POST => Enhanced - Dashboard privacy: Users search method transition to POST

I've had a read through and before release would need:
- peer review
- release date adding
- dependencies section added
- download links adding - formatted similar to release notes for 5.3.0

2024-04-25 08:13 UTC, dcs3spp approved these changes
@andyo-tyk PR LGTM I have added dependencies section with statement that links to dependencies for 5.3.0

2024-04-25 09:47 UTC, caroltyk requested changes

2024-04-25 09:47 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +If you are using 5.3.0 we advise you to upgrade ASAP and if you are on an older version you should skip 5.3.0 and upgrade directly to this release. Go to the [Upgrading Tyk](#upgrading-tyk) section f
If user is skipping 5.3.0, they should take note of the Upgrade Instructions in 5.3.0 too.

2024-04-25 09:47 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - [tyk-charts GH Repo](https://github.com/TykTechnologies/tyk-charts/releases)
The latest release notes for Helm Chart is in docs: product-stack/tyk-charts/release-notes/version-1.3

2024-04-25 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +  - [tyk-charts GH Repo](https://github.com/TykTechnologies/tyk-charts/releases)
Thanks @caroltyk I have updated. If ok with other comments and changes would you be able to approve?

2024-04-25 11:01 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +If you are using 5.3.0 we advise you to upgrade ASAP and if you are on an older version you should skip 5.3.0 and upgrade directly to this release. Go to the [Upgrading Tyk](#upgrading-tyk) section f
Thanks @caroltyk I have updated. If ok with other comments and changes would you be able to approve?

2024-04-25 11:37 UTC, caroltyk approved these changes
LGTM

2024-04-25 11:59 UTC, merged

2024-04-25 12:00 UTC, dcs3spp commented
/release to release-5.3