MDCB helm chart installation
TykTechnologies/tyk-docs-hugo pull request #4405
Opened 2024-04-11 13:47 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

1. tyk-control-plane moving out from Beta to Stable
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-04-16 10:55 UTC, dcs3spp commented
@caroltyk Is the PR ready for review?

2024-04-23 00:33 UTC, caroltyk commented
@komalsukhani could you help to peer review?

2024-04-24 12:34 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +2. Set `tyk-mdcb.mdcb.tls.secretName to the name of the Kubernetes secret containing TLS certificates for the Tyk MDCB, in this case, `mdcb-tls-secret`.
```suggestion
2. Set `tyk-mdcb.mdcb.tls.secretName` to the name of the Kubernetes secret containing TLS certificates for the Tyk MDCB, in this case, `mdcb-tls-secret`.
```

2024-04-24 12:37 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +      useSSL: false
```suggestion
      useSSL: true
```

2024-04-24 12:37 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +      useSSL: false
Shouldn't it be true?

2024-04-24 12:39 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +      privateCertificateEncodingSecret: ""
This field is located under `global.mtls` section according to https://github.com/TykTechnologies/tyk-charts/blob/7691c47451c54d9c8afb2e1b1d9f59fd92739793/components/tyk-mdcb/values.yaml#L134-L138C5

2024-04-25 13:44 UTC, komalsukhani requested changes, later dismissed

2024-04-25 13:44 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +By default, the chart would expose MDCB service at `mdcb-svc-tyk-control-plane-tyk-mdcb.tyk.svc:9091`. If you would like to access the control plane from outside the cluster, please change the servic
Should this section be placed after the `Follow the installation output` below.
As service name is based on the namespace and name of your helm release.

2024-04-25 13:44 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +Configure `global.mongo.mongoURL` and `global.storageType` as below. You should replace password in the connection string with the MONGODB_ROOT_PASSWORD you obtain from the installation output notes.
```suggestion
Configure `global.mongo.mongoURL` and `global.storageType` as below. You should replace `pass` in the connection string with the MONGODB_ROOT_PASSWORD you obtain from the installation output notes.
```

2024-04-25 13:44 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +If Tyk Dashboard or Developer Portal bootstrapping is enabled, the admin user will be created according to the `global.adminUser` field.
Admin user is created only when Dashboard bootstrapping is enable.

2024-04-25 20:12 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +By default, the chart would expose MDCB service at `mdcb-svc-tyk-control-plane-tyk-mdcb.tyk.svc:9091`. If you would like to access the control plane from outside the cluster, please change the servic
Good point, updated

2024-04-25 20:16 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +If Tyk Dashboard or Developer Portal bootstrapping is enabled, the admin user will be created according to the `global.adminUser` field.
@komalsukhani what happens if I have already bootstrapped Dashboard, but run helm upgrade to bootstrap dev portal?

2024-04-30 13:10 UTC, dcs3spp reviewed
Hi @caroltyk I have reviewed and have left a question relating to potential installation output

2024-04-30 13:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +=== Tyk Control Plane Details ===
Why formatted is this section formatted in between ```?

2024-04-30 13:10 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +3- Refer this Kubernetes secret (tyk-data-plane-details) while installing worker gateways through
If this is in installation output then text needs updating there also 

```suggestion
3- Refer to this Kubernetes secret (tyk-data-plane-details) while installing worker gateways through
```

2024-04-30 19:05 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +=== Tyk Control Plane Details ===
It is the terminal output. Should I remove it?

2024-05-02 07:24 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +    helm install tyk-data-plane tyk-helm/tyk-data-plane -n tyk-dp --create-namespace -f values.yaml
```suggestion
helm install tyk-data-plane tyk-helm/tyk-data-plane -n tyk-dp --create-namespace -f values.yaml
```

2024-05-02 11:57 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +of tyk-control-plane installation output.
```suggestion
of tyk-control-plane installation output, as listed below.
```

2024-05-02 11:58 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
> +=== Tyk Control Plane Details ===
Thanks Carol, I've updated sentence above and have resolved the comment

2024-05-02 12:05 UTC, dcs3spp approved these changes
@caroltyk PR LGTM and approved. Once @buraksekili has approved is the PR ready for release? I think there was a comment from @komalsukhani relating to dashboard admin on bootstrap? 

Should this be released to 5.x or only 5.3?

2024-05-06 09:13 UTC, buraksekili approved these changes
lgtm

2024-05-08 08:19 UTC, merged

2024-05-08 08:19 UTC, dcs3spp commented
/release to release-5.3