[DX-1258] - Adding missed tickets into the RN
TykTechnologies/tyk-docs-hugo pull request #4407
Opened 2024-04-11 16:08 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!

[DX-1258](https://tyktech.atlassian.net/browse/DX-1258)
---

### Preview Link

<br>

### Description

Missed out some tickets while compiling the RN, added this in the fixed section of changelog. 

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-04-16 10:34 UTC, dcs3spp requested changes
Thanks for submitting PR update @Eopayemi 

I have added a minor suggestion and asked question relating to mock response descriptions:

Does the change-log item for mock response descriptions relate to:
- Removed mandatory (required) status of mock response description - detailed in summary OR
- Removing validation formatting etc. of mock response descriptions - detailed in description

Once changes updated and peer reviewed by @andyo-tyk then will merge and release

2024-04-16 10:34 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Organisation Name Update via cURL Enhancement</summary>
```suggestion
Updated OAS documentation for updating the organisation name
```

2024-04-16 10:34 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Eliminated the necessity of mock response descriptions</summary>
@andyo-tyk @Eopayemi 

Does the change-log item refer to:
- Removed mandatory (required) status of mock response description OR
- Removing validation formatting etc. of mock response descriptions

2024-04-17 12:54 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Organisation Name Update via cURL Enhancement</summary>
Do we usually tag docs improvements in release notes? Not sure if this one is required if it's just a docs change (even if it is resolving a user reported issue).

2024-04-17 13:09 UTC, andyo-tyk requested changes

2024-04-17 13:09 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Organisation Name Update via cURL Enhancement</summary>
Ah, sorry, I misread: it's the Tyk Dashboard Admin API OpenAPI docs, not "just" Tyk docs... but still not a functional change so perhaps not required in change log.
Looking at the Jira ticket, it's flagged as "don't include in change log", so I think we already made that decision.

2024-04-17 13:09 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Eliminated the necessity of mock response descriptions</summary>
```suggestion
<summary>Removed the need for a Description to be provided in the OpenAPI schema when autogenerating a Tyk OAS mock response</summary>
```

2024-04-17 13:09 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +Removed strict validation for the description field in mock responses when utilising Tyk OAS, ensuring flexibility for response status codes and headers.
```suggestion
Relaxed the strict validation for mock response so that the `Description` field is now optional for `response`, `responses` and `schema` within the OpenAPI description. Automatically configuring mock responses when using [Tyk OAS APIs]({{< ref "product-stack/tyk-gateway/middleware/mock-response-openapi" >}}) is now even easier.
```

2024-04-17 13:09 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +Improved the documentation to explain the usage of *PUT /admin/organisations/{ORG_ID}*
I don't think this is required (per comment above).

2024-04-17 14:50 UTC, dcs3spp approved these changes

2024-04-17 16:26 UTC, andyo-tyk approved these changes
Thanks, looks good to me.

2024-04-18 09:35 UTC, merged

2024-04-18 09:35 UTC, dcs3spp commented
/release to release-5.3