Update partitioned-policies.md with note about ACL
TykTechnologies/tyk-docs-hugo pull request #4411
Opened 2024-04-12 13:52 UTC by behcio

When partitioned policies are assigned to a token, at least of these policies needs to enforce ACL - this part was missing.

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-04-15 07:55 UTC, agata-wit approved these changes

2024-04-15 08:25 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/security-policies/partitioned-policies.md
>  *   The Access Control Limit (ACL)
I thought ACL is "access control list"

2024-04-15 08:56 UTC, behcio commented on tyk-docs/content/basic-config-and-security/security/security-policies/partitioned-policies.md
>  *   The Access Control Limit (ACL)
That's a valid question I posted on Manage Squad's slack channel. Let's see what they have to say.

2024-04-15 09:24 UTC, behcio commented on tyk-docs/content/basic-config-and-security/security/security-policies/partitioned-policies.md
>  *   The Access Control Limit (ACL)
Yup, should be "List". I'll change it.

2024-04-15 09:34 UTC, dcs3spp commented
Hi @behcio thanks for contributing the fix. Would you be able to add a preview link and a label for which release this targets.

2024-04-16 07:55 UTC, behcio commented
@dcs3spp Preview link added. As for labels... which label should I add if it's something that applies all the way back to 3.0? :)

2024-04-16 08:14 UTC, dcs3spp commented
> @dcs3spp Preview link added. As for labels... which label should I add if it's something that applies all the way back to 3.0? :)

Thanks @behcio , 🤔 maybe for that use case add a new label, all?

2024-04-16 08:56 UTC, dcs3spp requested changes
Thanks @behcio for submitting updated content fix. PR LGTM, I have made some minor suggestions and then think we can release

2024-04-16 08:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/security-policies/partitioned-policies.md
> +    *   When applying partitioned policies to a key, at least one of these policies needs to enforce ACL
Does ACL mean something like this, relating to the APIs that the policies apply to? 

```json
 "accessRights": {
      "20bef4a405564d8c6f74fb9531432e4b": {
        "apiName": "UpstreamTLS",
        "apiId": "20bef4a405564d8c6f74fb9531432e4b",
        "versions": [
          "Default"
        ]
      },
      "accbdd1b89e84ec97f4f16d4e3197d5c": {
        "apiName": "Basic Protected API",
        "apiId": "accbdd1b89e84ec97f4f16d4e3197d5c",
        "versions": [
          "Default"
        ]
      }
}
```

If so maybe it would be best to add a short JSON example and/or screenshot of Dashboard or link to examples.

2024-04-16 08:56 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/security-policies/partitioned-policies.md
> +*   The Access Control List (ACL)
```suggestion
Access Rights: The Access Control List (ACL)
```

2024-04-16 09:06 UTC, behcio commented on tyk-docs/content/basic-config-and-security/security/security-policies/partitioned-policies.md
> +    *   When applying partitioned policies to a key, at least one of these policies needs to enforce ACL
Actually, there are examples on the same page just a bit lower, right here:
https://tyk.io/docs/basic-config-and-security/security/security-policies/partitioned-policies/#applying-partitioned-policies-to-a-key-with-the-same-segments-enforced

So I think we don't need to add another JSON snippet here

2024-04-16 09:18 UTC, behcio commented on tyk-docs/content/basic-config-and-security/security/security-policies/partitioned-policies.md
> +*   The Access Control List (ACL)
The `*` should definitely stay. Let me edit the suggestion a bit

2024-04-16 11:04 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/security-policies/partitioned-policies.md
> +*   The Access Rights aka the Access Control List (ACL)
```suggestion
*   The Access Control List (ACL), configured using the `access_rights` field
```

2024-04-16 11:05 UTC, dcs3spp approved these changes

2024-04-16 11:08 UTC, merged

2024-04-16 11:08 UTC, dcs3spp commented
/release to release-5.3

2024-04-16 11:09 UTC, dcs3spp commented
/release to release-5.2

2024-04-16 11:14 UTC, dcs3spp commented
/release to release-5.1

2024-04-16 11:15 UTC, dcs3spp commented
/release to release-5

2024-04-16 11:17 UTC, dcs3spp commented
/release to release-4.3

2024-04-16 11:22 UTC, dcs3spp commented
/release to release-4.2

2024-04-16 11:24 UTC, dcs3spp commented
/release to release-4.1

2024-04-16 11:25 UTC, dcs3spp commented
/release to release-4

2024-04-16 11:30 UTC, dcs3spp commented
/release to release-3.2

2024-04-16 11:36 UTC, dcs3spp commented
/release to release-3.1

2024-04-16 11:43 UTC, dcs3spp commented
/release to release-3-lts