Clarification of Go template behaviour
TykTechnologies/tyk-docs-hugo pull request #4486
Opened 2024-04-22 15:23 UTC by andyo-tyk

### Preview Link

### Description
Added a note to explain behaviour of Go Templating with context variables and session metadata

2024-04-23 09:32 UTC, dcs3spp requested changes
PR LGTM, asked question why only first item of key/values array processed and made suggestion for note.

2024-04-23 09:32 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/request-body.md
> +The request body transform middleware can iterate through list indices in dynamic data so, for example, calling `{{ index ._tyk_context.request_data.variablename 0 }}` in a template will expose the f
Why is only the first entry in the key/value array and not the other list indices in the array?

2024-04-23 09:32 UTC, dcs3spp commented on tyk-docs/content/transform-traffic/request-body.md
> +As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided al
Is it just the response body in this PR?

```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided with the response body in the data structure to which the template is applied and will be merged if the template applies a transformation to the entire data structure.
```

2024-04-23 15:51 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/request-body.md
> +The request body transform middleware can iterate through list indices in dynamic data so, for example, calling `{{ index ._tyk_context.request_data.variablename 0 }}` in a template will expose the f
Dunno, this is just the way it is.

2024-04-23 15:51 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/request-body.md
> +As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided al
Separate PRs, all linked to the same DX ticket

2024-04-23 15:52 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/request-body.md
> +As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided al
```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided with the request body in the data structure to which the template is applied and so will be processed accordingly if, for example, the template applies a transformation to the entire data structure.
```

2024-04-23 15:52 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/request-body.md
> +As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided al
I think "merged" is more likely to cause confusion.

2024-04-23 17:44 UTC, titpetric commented on tyk-docs/content/transform-traffic/request-body.md
> +As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided wi
```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. As the template applies a transformation to the entire data structure it receives, context variables and session metadata will be available if enabled, along with the request body. Otherwise, just the request body is available.
```

Same as on the response PR, changed with "request body".

2024-04-23 17:44 UTC, titpetric approved these changes

2024-04-24 16:25 UTC, andyo-tyk commented on tyk-docs/content/transform-traffic/request-body.md
> +As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided wi
```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. The template receives the decoded JSON or XML of the request body. If session variables or meta data are enabled, additional fields will be provided: `_tyk_context` and `_tyk_meta` respectively.
```

2024-04-25 09:28 UTC, dcs3spp approved these changes

2024-04-25 09:29 UTC, merged

2024-04-25 09:29 UTC, dcs3spp commented
/release to release-5.3