Clarification of Go template behaviour - response transform
TykTechnologies/tyk-docs-hugo pull request #4487
Opened 2024-04-22 15:30 UTC by andyo-tyk

### For internal users - Please add a Jira DX PR ticket to the subject!

### Preview Link

### Description
Added a note to explain behaviour of Go Templating with context variables and session metadata (to match the edit proposed for Request Body Transform)

2024-04-23 09:27 UTC, dcs3spp requested changes
PR LGTM, commented relating to why only first item in key/value array is exposed and made suggestion for note

2024-04-23 09:27 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> +The response body transform middleware can iterate through list indices in dynamic data so, for example, calling `{{ index ._tyk_context.request_data.variablename 0 }}` in a template will expose the
Why is only the first entry in the key/value array and not the other list indices in the array?

2024-04-23 09:27 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> + As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided a
```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided with the response body in the data structure to which the template is applied and will be merged if the template applies a transformation to the entire data structure.
```

2024-04-23 15:53 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> +The response body transform middleware can iterate through list indices in dynamic data so, for example, calling `{{ index ._tyk_context.request_data.variablename 0 }}` in a template will expose the
Same question as the request body PR, same answer :)

2024-04-23 15:53 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> + As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided a
```suggestion
 As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided with the response body in the data structure to which the template is applied and so will be processed accordingly if, for example, the template applies a transformation to the entire data structure.
```

2024-04-23 17:37 UTC, titpetric commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> + **Note**
```suggestion
**Note**  
```

Whitespace

2024-04-23 17:41 UTC, titpetric commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> + As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided w
```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. As the template applies a transformation to the entire data structure it receives, context variables and session metadata will be available if enabled, along with the response body. Otherwise, just the response body is available.
```

While technically correct, I found the second sentence nearly impossible to consume. I tried breaking apart into a few sentences to be easier to read, but if you can reword it, please.

2024-04-23 17:42 UTC, titpetric approved these changes
Left some suggestions, LGTM

2024-04-24 13:58 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> + As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided w
@andyo-tyk @titpetric 

```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided with the response body in the data structure to which the template is applied. Subsequently, these will be merged if the template applies a transformation to the entire data structure.
```

2024-04-24 14:57 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> + As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided w
```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. This data structure consists of the request context variables (`_tyk_context`) and session metadata (`_tyk_meta`) - if enabled for the middleware - concatenated with the response body.
```

2024-04-24 14:59 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> + As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. Context variables and session metadata are, if enabled, provided w
I've proposed alternative, simpler wording - see latest commit.

2024-04-24 15:45 UTC, titpetric commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> +As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. This data structure consists of the request context variables (`_ty
```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. This data structure consists of the request context variables (`_tyk_context`) and session metadata (`_tyk_meta`) - if enabled for the middleware - together with the response body.
```

2024-04-24 15:47 UTC, titpetric approved these changes

2024-04-24 16:20 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> +As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. This data structure consists of the request context variables (`_ty
```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. The template receives the decoded JSON or XML of the request body. If session variables or meta data are enabled, additional fields will be provided: `_tyk_context` and `_tyk_meta` respectively.
```

2024-04-24 16:41 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
> +As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. The template receives the decoded JSON or XML of the request body.
```suggestion
As explained in the [documentation](https://pkg.go.dev/text/template), templates are executed by applying them to a data structure. The template receives the decoded JSON or XML of the response body. If session variables or meta data are enabled, additional fields will be provided: `_tyk_context` and `_tyk_meta` respectively.
```

2024-04-25 09:34 UTC, dcs3spp approved these changes
PR LGTM will merge and release

2024-04-25 09:39 UTC, dcs3spp approved these changes
PR LGTM, will merge and release

2024-04-25 09:39 UTC, merged

2024-04-25 09:39 UTC, dcs3spp commented
/release to release-5.3