Setup MDCB control plane with Helm Chart
TykTechnologies/tyk-docs-hugo pull request #4491
Opened 2024-04-23 09:54 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-04-23 11:14 UTC, dcs3spp requested changes
PR LGTM @caroltyk I have added suggestions to:
- Maybe include subsections for RPM + Debian Linux package installation
- Replace numbered installation steps with subsection headings for helm installation
- Explain Tyk Data Plane in introduction section
- Made suggestion for link to installing Tyk Data Plane
- Requires peer review for helm

2024-04-23 11:14 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +## Installing MDCB Component with package
Is this a Link RPM, Debian package? Should the section be named: _Installing MDCB Component On Linux_ and then have subsections for installing using RPM and Debian packages?

2024-04-23 11:14 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +The MDCB component will however, by default, expose an RPC service on port 9091, to which the Tyk Data Plane (Worker gateway(s)) data centres will need connectivity.
Add an brief sentence or two to explain Tyk Data Plane, similar to what has been done for Tyk Control Plane in introduction

2024-04-23 11:14 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +for multi data centre API management from a single Dashboard with the MDCB component.
remove line break

2024-04-23 11:14 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +Before installation, you need to prepare the followings:
Remove sentence and list pre-requisites

2024-04-23 11:14 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +### Quick Start
Convert number steps to numbered section headings #### 1. Step 1, #### 2. Step 2 etc.

2024-04-23 11:14 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +You can get MDCB connection details from the installation output, to prepare installation of [setup MDCB Data Plane]({{<ref "product-stack/tyk-charts/tyk-data-plane-chart">}}):
```suggestion
You can use the MDCB connection details included in the installation output, to install the [MDCB Data Plane]({{<ref "product-stack/tyk-charts/tyk-data-plane-chart">}}):
```

2024-04-23 14:29 UTC, caroltyk commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +The MDCB component will however, by default, expose an RPC service on port 9091, to which the Tyk Data Plane (Worker gateway(s)) data centres will need connectivity.
Added

2024-04-23 14:31 UTC, caroltyk commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +### Quick Start
Updated

2024-04-25 14:16 UTC, komalsukhani requested changes, later dismissed

2024-04-25 14:16 UTC, komalsukhani commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +Follow the notes from the installation output to get connection details and password. The DNS name of your Redis as set by Bitnami is `tyk-redis-master.tyk.svc:6379` (Tyk needs the name including the
Since you are setting namespace as `tyk-cp`
```suggestion
Follow the notes from the installation output to get connection details and password. The DNS name of your Redis as set by Bitnami is `tyk-redis-master.tyk-cp.svc:6379` (Tyk needs the name including the port) 
```

2024-04-25 14:16 UTC, komalsukhani commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +helm upgrade tyk-redis oci://registry-1.docker.io/bitnamicharts/redis -n $NAMESPACE --install --version 19.0.2
Should we also add a note to install supported redis version like you have done for postgres?

2024-04-25 14:16 UTC, komalsukhani commented on tyk-docs/content/tyk-multi-data-centre/setup-worker-data-centres.md
> +If you deployed Gateway with `tyk-data-plane` Chart, you don't need to go through following steps to configure Tyk Gateway. The necessary configurations has been set in `tyk-data-plane` chart templat
```suggestion
If you have deployed Gateway with `tyk-data-plane` Chart, you don't need to go through following steps to configure Tyk Gateway. The necessary configurations has been set in `tyk-data-plane` chart templates.
```

2024-04-25 20:08 UTC, caroltyk commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +helm upgrade tyk-redis oci://registry-1.docker.io/bitnamicharts/redis -n $NAMESPACE --install --version 19.0.2
Added

2024-04-25 20:08 UTC, caroltyk commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +## Installing MDCB Component with package
Updated

2024-04-25 20:09 UTC, caroltyk commented
Hi @dcs3spp @komalsukhani , the comments has been incorporated. Thanks a lot!

2024-04-30 11:57 UTC, dcs3spp approved these changes
Thanks @caroltyk Changes look good to me, I've approved the PR 

@komalsukhani would you be able to approve changes made by @caroltyk if ok?

@caroltyk Should this be released to any historic docs versions or just 5.3?

2024-05-02 07:27 UTC, buraksekili commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +For the complete installation guide and configuration options, please see [Tyk Control Plane Helm Chart]({{<ref "product-stack/tyk-charts/tyk-control-plane-chart">}}).
Just an opinion, maybe we can mention the complete installation guide beforehand, right under the `## Installing in a Kubernetes Cluster with our Helm Chart` What do you think?

2024-05-02 07:47 UTC, caroltyk commented
@dcs3spp Please release it for 5.x +

2024-05-02 07:54 UTC, caroltyk commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +For the complete installation guide and configuration options, please see [Tyk Control Plane Helm Chart]({{<ref "product-stack/tyk-charts/tyk-control-plane-chart">}}).
Thanks, updated as suggested

2024-05-02 08:06 UTC, buraksekili approved these changes

2024-05-08 08:12 UTC, merged

2024-05-08 08:12 UTC, dcs3spp commented
/release to release-5.3