[DX-1288] EDP 1.9.0 docs
TykTechnologies/tyk-docs-hugo pull request #4492
Opened 2024-04-24 04:41 UTC by slega

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>
[DX-1288](https://tyktech.atlassian.net/browse/DX-1288)

---

### Preview Link

- Release notes: https://deploy-preview-4492--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.9.0/
- Webhooks docs: https://deploy-preview-4492--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks/
- OAS updates: https://deploy-preview-4492--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-enterprise-developer-portal/api-documentation/tyk-edp-api/

<br>

### Description
- Add release notes for 1.9.0
- Add docs for the webhooks
- Updates OAS for the portal
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

[DX-1288]: https://tyktech.atlassian.net/browse/DX-1288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-04-25 09:07 UTC, edsonmichaque commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +This event is fired whenever an access request is approved or auto-approved via teh admin APIs or admin UI.
I think there's a typo here: teh

2024-04-25 09:07 UTC, edsonmichaque commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +This event is fired whenever a new organisation request is created via the admin APIs, the live portal (the become an org flow) or the admin UI.
Hi @slega I believe we cannot create an `Organisation Request` from API

2024-04-25 09:41 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.9.0.md
> +- Fixed the following vulnerabilities related to Go 1.19 by upgrading Go version:
Maybe add the upgraded Go version here? (1.21)

2024-04-25 09:44 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.9.0.md
> +  - [CVE-2023-45284](https://scout.docker.com/vulnerabilities/id/CVE-2023-45284).
CVEs Missing :

- CVE-2023-48795 [CVE-2023-48795](https://scout.docker.com/v/CVE-2023-48795)
- CVE-2023-39326 [CVE-2023-39326](https://scout.docker.com/v/CVE-2023-39326)
- CVE-2024-3094 [CVE-2024-3094](https://scout.docker.com/vulnerabilities/id/CVE-2024-3094)

2024-04-25 09:48 UTC, tbuchaillot commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
@slega `per_page` and `page` params to cover this https://tyktech.atlassian.net/browse/TT-11120?

2024-04-25 09:49 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
@slega @edsonmichaque pair a little bit to add some info on the security header and how customer can validate that.

2024-04-25 09:50 UTC, tbuchaillot requested changes
@slega left some comments - new configuration options/envs related to webhooks are missing

2024-04-25 13:12 UTC, dcs3spp requested changes
Thanks @slega PR LGTM, I have add minor suggestions and once peer approvals given will merge and release.

2024-04-25 13:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +### Configure the Target endpoint
```suggestion
### Configure the target endpoint
```

2024-04-25 13:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +This event is fired whenever a user account is activated via APIs or the admin UI.
Should this be when the user account is deactivated (User account deactivation)?

2024-04-25 13:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +Sample payload:
Why do the even payloads have a mixture of lower case and and Sentence case attributes?

2024-04-25 13:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +This event is fired whenever a new credential is created via APIs, the admin UI (creation after approval), and the live portal UI.
```suggestion
This event is fired whenever a new credential is created via APIs, the admin UI (creation after approval) and the live portal UI.
```

2024-04-25 13:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +This event is fired whenever a new consumer organisation is created via the admin APIs, the live portal (the become an organisation flow) or the admin UI.
What is the become an organisation flow? Add a brief explanation of what the become and organisation flow is

2024-04-25 13:12 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks:
Why has this line been added to menu.yaml?

2024-04-25 19:40 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.9.0.md
> +- Fixed the following vulnerabilities related to Go 1.19 by upgrading Go version:
Done

2024-04-25 19:40 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.9.0.md
> +  - [CVE-2023-45284](https://scout.docker.com/vulnerabilities/id/CVE-2023-45284).
Done

2024-04-25 19:40 UTC, slega commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
Done

2024-04-25 19:42 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +This event is fired whenever a user account is activated via APIs or the admin UI.
Fixed

2024-04-25 19:42 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +This event is fired whenever an access request is approved or auto-approved via teh admin APIs or admin UI.
Fixed

2024-04-25 19:45 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +This event is fired whenever a new consumer organisation is created via the admin APIs, the live portal (the become an organisation flow) or the admin UI.
Fixed

2024-04-25 19:46 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +This event is fired whenever a new organisation request is created via the admin APIs, the live portal (the become an org flow) or the admin UI.
Fixed

2024-04-25 19:55 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +Sample payload:
Fixed

2024-04-25 19:57 UTC, slega commented on tyk-docs/data/menu.yaml
> +tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks:
That was a typo. It's fixed now.

2024-04-26 08:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.9.0-list-of-endpoints.md
> +### Admin APIs
@slega Is it worthwhile adding a column that lists the methods available for each endpoint, e.g. GET, POST, PATCH/PUT?

2024-04-26 08:10 UTC, dcs3spp approved these changes
PR LGTM @slega and I have approved.

Is it worthwhile adding a column that lists the methods available for each endpoint in the portal 1.90 list of endpoints, e.g. GET, POST, PATCH/PUT?

Before merging and releasing requires peer approval

2024-04-26 18:36 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.9.0-list-of-endpoints.md
> +### Admin APIs
No, it's not. It's a list of endpoints for configuring firewalls specifically asked for by Bottomline. We don't need verbs for that.

2024-04-26 18:37 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
We will postpone until we have a good idea of configuring it in the cloud so that we won't need to deprecate anything.

2024-04-26 18:52 UTC, JRWu submitted a review, later dismissed
LGTM just requesting feedback on minor changes!

2024-04-26 18:52 UTC, JRWu commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.9.0.md
> +- [Docker image v1.9.0](https://hub.docker.com/r/tykio/portal/tags?page=&page_size=&ordering=&name=v1.9.0)
Somehow this is rendering strangely for me (Google Chrome)
![image](https://github.com/TykTechnologies/tyk-docs/assets/5810874/cff04f60-17ee-4c29-b6a7-eb77ee0f46d5)

2024-04-26 18:52 UTC, JRWu commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +        parent: "Customise the portal"
Nitpick, but are we standardizing on British english or Amer english? The tags in this page have Customization and the menu items are labeled as Customisation

2024-04-26 18:52 UTC, JRWu commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +### Events
Just a minor suggestion, could we add all the supported Events as a list here and provide anchor links to each one down the page? It makes it a bit more obvious to the developer and improves their experience instead of having to scroll to read each Event separately

2024-04-29 14:04 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +### Events
Done.

2024-04-29 14:05 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +        parent: "Customise the portal"
In general in the docs we use British english.

2024-04-29 14:05 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.9.0.md
> +- [Docker image v1.9.0](https://hub.docker.com/r/tykio/portal/tags?page=&page_size=&ordering=&name=v1.9.0)
Fixed.

2024-04-29 15:23 UTC, tbuchaillot approved these changes

2024-04-29 15:43 UTC, edsonmichaque commented on tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/edp-new-user-registration-webhook-events.png
Hi @slega, I believe this image needs to be updated to use the new event name

2024-04-29 15:43 UTC, edsonmichaque commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +    "Event": "OrganizationRequestCreated",
Hi @slega, I believe we are still mixing UK and US spelling, see the sample payload for `OrganisationRequestApproved`

2024-04-29 21:16 UTC, edsonmichaque approved these changes
LGTM

2024-04-30 02:05 UTC, slega commented on tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/edp-new-user-registration-webhook-events.png
Done

2024-04-30 02:05 UTC, slega commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
> +    "Event": "OrganizationRequestCreated",
Done

2024-04-30 02:05 UTC, slega commented
@dcs3spp the PR is approved. Could you please merge it?

2024-04-30 11:15 UTC, merged

2024-04-30 11:24 UTC, dcs3spp commented
/release to release-5.3

2024-04-30 11:28 UTC, dcs3spp commented
Thanks @slega I have merged and released

2024-04-30 12:06 UTC, dcs3spp commented
/release to release-5.2

2024-04-30 13:44 UTC, dcs3spp commented
/release to release-5.2

2024-04-30 14:01 UTC, dcs3spp commented
/release to release-5.2

2024-04-30 14:27 UTC, dcs3spp commented
/release to release-5.1