Update tyk-stack-chart.md
TykTechnologies/tyk-docs-hugo pull request #4493
Opened 2024-04-24 08:36 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

Example of how to load secret values in environment variables and access them through Tyk configuration files or API Definitions.

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-04-25 09:56 UTC, dcs3spp requested changes
Thanks for submitting PR @caroltyk, I have made minor suggestions in Tyk Control Plane chart that are applicable to the other charts in the PR. 

@sedkis Would you be able to peer review for @caroltyk ?

2024-04-25 09:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +Example of setting extra [environment variable using ConfigMap data](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-con
Added suggestion to remove duplication of example, applicable to other chart content (tyk-control-plane-chart, tyk-data-plane-chart, tyk-oss-chart, tyk-stack-chart) files

```suggestion
An example is listed below for setting extra [environment variable using ConfigMap data](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data), using gateway:
```

2024-04-25 09:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +Example of setting extra [environment variable using Secret data](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-
```suggestion
An example is listed below for setting extra [environment variable using secret data](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data), using gateway:
```

2024-04-25 09:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +In the above example, an extra environment variable `SECRET_USERNAME` will be added to gateway container, taking value from `backend-username` value defined in the Secret `backend-user`. It is useful
```suggestion
In the above example, an extra environment variable `SECRET_USERNAME` will be added to the Gateway container, with a value of `backend-username` associated with the secret `backend-user`. It is useful if you want to access secret data from [Tyk Gateway configuration file (tyk.conf) or API definitions]({{<ref "tyk-configuration-reference/kv-store#how-to-access-the-externally-stored-data">}}).
```

2024-04-25 16:04 UTC, sedkis approved these changes

2024-04-25 16:51 UTC, caroltyk commented
Thank you @dcs3spp . I have applied the suggestions to all charts.

2024-04-30 09:46 UTC, dcs3spp approved these changes
Many thanks @caroltyk, PR LGTM! I'll merge and release

2024-04-30 10:16 UTC, merged

2024-04-30 10:16 UTC, dcs3spp commented
/release to release-5.3

2024-04-30 14:44 UTC, dcs3spp commented
/release to release-5.2

2024-04-30 15:03 UTC, dcs3spp commented
/release to release-5.2