Tyk Charts 1.4. release notes
TykTechnologies/tyk-docs-hugo pull request #4495
Opened 2024-04-24 09:46 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-04-24 10:25 UTC, dcs3spp reviewed
Thanks @caroltyk for submitting Tyk Charts release notes. Not sure if this is ready for review yet but have added some comments/suggestions:
- Should Tyk Charts 1.3 be replace with Tyk Charts 1.4 in the release highlights section?
- For the changelog items that refer to making service port name configurable, what are the valid values, http, https etc? Should the change-log item be renamed to make it clearer that it relates to configuring the service protocol or does this relate to something else other than http or https?
- Does Tyk Charts 1.3.0 have a release tag?

2024-04-24 10:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +<summary>Dashboard: Customise ServiceAccount to be used</summary>
```suggestion
<summary>Dashboard: Customise ServiceAccount</summary>
```

2024-04-24 10:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +Users can configure Tyk Dashboard service port name. Default is `http`.
What are the valid values, http, https etc? Should the changelog item be renamed to make it clearer that relates to the service protocol or does this relate to something else?

2024-04-24 10:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +Users can configure Tyk Pump service port name. Default is `http`.
Same comment as for Dashboard service port name above and applicable to items below where service port name is configurable.

2024-04-24 10:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +<summary>Portal: Customise ServiceAccount to be used</summary>
```suggestion
<summary>Portal: Customise ServiceAccount</summary>
```

2024-04-24 10:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +Tyk Charts 1.4.0 uses `mongo-go` as the default driver to connect to MongoDB. `mongo-go` driver is compatible with MongoDB 4.4.x and above. For MongoDB versions prior to 4.4, please change `global.mo
```suggestion
Tyk Charts 1.4.0 uses `mongo-go` as the default driver to connect to MongoDB. `mongo-go` driver is compatible with MongoDB 4.4.x and above. For MongoDB versions prior to 4.4, please change `global.mongo.driver` to `mgo`. We recommend reading [choose a MongoDB driver]({{<ref "planning-for-production/database-settings/mongodb#choose-a-mongodb-driver">}}) when you need to change driver setting.
```

2024-04-24 10:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +#### Release Highlights
should Tyk Charts 1.3 be replace with Tyk Charts 1.4 in this section?

2024-04-24 10:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +For users currently on v1.2.x, we strongly recommend promptly upgrading to the latest release.
What about upgrade instructions from Tyk Charts 1.3 also?

2024-04-24 10:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +For MongoDB users: Tyk Charts 1.4.0 uses `mongo-go` as the default driver to connect to MongoDB. `mongo-go` driver is compatible with MongoDB 4.4.x and above. For MongoDB versions prior to 4.4, pleas
```suggestion
For MongoDB users: Tyk Charts 1.4.0 uses `mongo-go` as the default driver to connect to MongoDB. `mongo-go` driver is compatible with MongoDB 4.4.x and above. For MongoDB versions prior to 4.4, please set `global.mongo.driver` to `mgo`. We recommend reading [choose a MongoDB driver]({{<ref "/planning-for-production/database-settings/mongodb#choose-a-mongodb-driver">}}) when you need to change driver setting.
```

2024-04-29 10:51 UTC, caroltyk commented
@dcs3spp This PR is still WIP. Will update status to "Ready for review" when it's ready. Thanks!

2024-05-01 15:22 UTC, dcs3spp requested changes
PR LGTM Carol, I've made minor suggestion and then after peer approval, ready for release

2024-05-01 15:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +<summary>OSS: Simplify Tyk Operator Setup with Kubernetes Secret Creation</summary>
make Setup lowercase and Creation lower case

2024-05-01 15:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +<summary>Gateway/Pump: Enhanced Pod security with `runAsNonRoot`</summary>
Make Pod lowercase in summary headings here and below

2024-05-01 15:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +The `dashboard.hashKeys` field is now deprecated. Instead, users should utilize the `global.hashKeys` field to set key hashing. This ensures configuration alignment across gateway, dashboard, and MDC
Capitalise gateway and dashboard for consistency here with other usage in this release note

2024-05-01 15:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +##### Release Date -- XX Apr 2024
Remember to update release date and to tag the release for Tyk Charts in GHub repository when released

2024-05-01 15:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +- In `tyk-dashboard` chart, `dashboard.hashKeys` field is deprecated and be replaced with `.global.hashKeys`. This is to ensure Dashboard, Gateway, and MDCB always get the same hashKeys configuration
```suggestion
- In the `tyk-dashboard` chart, the `dashboard.hashKeys` field is deprecated and has been replaced with `.global.hashKeys`. This is to ensure Dashboard, Gateway, and MDCB always get the same hashKeys configurations. Setting `dashboard.hashKeys` will no longer take effect. Please only use `.global.hashKeys` field.
```

2024-05-01 15:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +##### GA release of tyk-control-plane chart and tyk-mdcb chart
By GA do you mean General Availability?

```suggestion
##### General availability release of tyk-control-plane chart and tyk-mdcb chart
```

2024-05-02 07:47 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +| [PostgreSQL](https://www.postgresql.org/download/)         | 11.x - 15.x LTS        | 11.x - 15.x            | Used by Tyk Dashboard |
aren't Mongo and postgres used by other components like pump?

2024-05-02 07:47 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +To harden security, we have added `runAsNonRoot: true` in the pod's securityContext. This prevents the Pods from running as root users, ensuring compatibility with the [*Restricted* Pod Security Poli
```suggestion
To harden security, we have added `runAsNonRoot: true` in the pod's `securityContext`. This prevents the Pods from running as root users, ensuring compatibility with the [*Restricted* Pod Security Policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted).
```

2024-05-02 07:47 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +Now, you have the flexibility to customize podLabels in all component charts. Simply populate the `podLabels` field with your desired content, and it will be added as pod labels.
What do you think? i might be wrong
```suggestion
Now, you have the flexibility to customize pod labels in all component charts. Simply populate the `podLabels` field with your desired content, and it will be added as pod labels.
```

2024-05-02 07:47 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +We've added a `podAnnotations` field to the `tyk-dev-portal` chart, allowing you to customize pod annotations. Fill in the podAnnotations field with your specific content, and it will be added as pod
```suggestion
We've added a `podAnnotations` field to the `tyk-dev-portal` chart, allowing you to customize pod annotations. Fill in the `podAnnotations` field with your specific content, and it will be added as pod annotations.
```

2024-05-02 07:47 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +We've corrected a typo in the values.yaml file within the "global.redis" section. The fields `sslMinVersion` and `sslMaxVersion` have been updated to `tlsMinVersion` and `tlsMaxVersion`, respectively
I could not get this log. Please correct me if I am wrong but did we have `sslMinVersion` and `sslMaxVersion` on values.yaml file at all? I mean, we've added `tlsMinVersion` and `tlsMaxVersion` to values.yaml file; however, the change only affected underlying environment variables. If I am not wrong, `tlsMinversion` and `tlsMaxVersion` were only added to support the new Redis configuration on Tyk - not to fix typo in values.yaml file as stated in the changelog

2024-05-02 09:20 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +Now, you have the flexibility to customize podLabels in all component charts. Simply populate the `podLabels` field with your desired content, and it will be added as pod labels.
Good spot @buraksekili 👍 I think podLabels is a field in a chart so the first sentence might be a typo? @caroltyk are you ok with the suggestion made by @buraksekili?

2024-05-03 12:19 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +<summary>OSS: Simplify Tyk Operator Setup with Kubernetes Secret Creation</summary>
updated

2024-05-03 12:20 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +<summary>Gateway/Pump: Enhanced Pod security with `runAsNonRoot`</summary>
@dcs3spp Pod is a Kubernetes special term (like Secret), maybe we should keep them as upper case?

2024-05-03 12:21 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +The `dashboard.hashKeys` field is now deprecated. Instead, users should utilize the `global.hashKeys` field to set key hashing. This ensures configuration alignment across gateway, dashboard, and MDC
updated

2024-05-03 12:21 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +##### GA release of tyk-control-plane chart and tyk-mdcb chart
updated

2024-05-03 12:22 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +To harden security, we have added `runAsNonRoot: true` in the pod's securityContext. This prevents the Pods from running as root users, ensuring compatibility with the [*Restricted* Pod Security Poli
updated

2024-05-03 12:22 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +| [PostgreSQL](https://www.postgresql.org/download/)         | 11.x - 15.x LTS        | 11.x - 15.x            | Used by Tyk Dashboard |
updated

2024-05-03 12:23 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +Now, you have the flexibility to customize podLabels in all component charts. Simply populate the `podLabels` field with your desired content, and it will be added as pod labels.
changes made

2024-05-03 12:29 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +We've corrected a typo in the values.yaml file within the "global.redis" section. The fields `sslMinVersion` and `sslMaxVersion` have been updated to `tlsMinVersion` and `tlsMaxVersion`, respectively
@buraksekili this PR: https://github.com/TykTechnologies/tyk-charts/pull/267/files

2024-05-03 16:36 UTC, dcs3spp approved these changes

2024-05-03 16:38 UTC, dcs3spp commented
Thanks @caroltyk I have approved the PR and once peer approval given by @buraksekili we can merge and release

2024-05-06 09:25 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
> +We've corrected a typo in the values.yaml file within the "global.redis" section. The fields `sslMinVersion` and `sslMaxVersion` have been updated to `tlsMinVersion` and `tlsMaxVersion`, respectively
thanks!!

2024-05-06 09:25 UTC, buraksekili approved these changes
lgtm!

2024-05-08 08:08 UTC, merged

2024-05-08 08:08 UTC, dcs3spp commented
/release to release-5.3