MDCB 2.5.1 Release Notes
TykTechnologies/tyk-docs-hugo pull request #4496
Opened 2024-04-24 11:43 UTC by n2linux

Release notes for MDCB 2.5.1

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-04-24 11:58 UTC, dcs3spp commented
@n2linux PR LGTM, will require peer review from @caroltyk before approval

2024-04-25 09:00 UTC, dcs3spp approved these changes
PR LGTM, @caroltyk could you peer review?

2024-04-25 10:08 UTC, caroltyk requested changes

2024-04-25 10:08 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +  When clearing the API cache from the Tyk Dashboard UI, the cache in distributed data plane gateways was not being invalidated.
Please add a note that this fix requires upgrading Gateway to 5.3.1 too.

2024-04-25 11:09 UTC, n2linux commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +  When clearing the API cache from the Tyk Dashboard UI, the cache in distributed data plane gateways was not being invalidated.
@caroltyk @dcs3spp Added the note.

2024-04-25 11:34 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
> +  When clearing the API cache from the Tyk Dashboard UI, the cache in distributed data plane gateways was not being invalidated.
@caroltyk could you approve if ok and then I will merge and release to 5.3 docs

2024-04-25 11:39 UTC, caroltyk approved these changes
Thanks! LGTM

2024-04-25 12:07 UTC, merged

2024-04-25 12:07 UTC, dcs3spp commented
/release to release-5.3