[DX-1297, TT-11697] Add documentation on how monitoring works in Tyk Cloud
TykTechnologies/tyk-docs-hugo pull request #4518
Opened 2024-04-25 15:12 UTC by komuw

## **User description**
### For internal users - Please add a Jira DX PR ticket to the subject!
- https://tyktech.atlassian.net/browse/DX-1297
- https://tyktech.atlassian.net/browse/TT-11697

### Preview Link

- https://deploy-preview-4518--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments--deployments/monitoring-usage/
- https://deploy-preview-4518--tyk-docs.netlify.app/docs/nightly/tyk-cloud/environments--deployments/monitoring-how-it-works/

### Description

- Add documentation on how monitoring works in Tyk Cloud
  There have been a number of queries on how monitoring works, this documentation update tries to address that.
  I have tried to give a high level view of how monitoring works without going too much into implementation details(since the implementation might change in the future). There is an [internal documentation](https://tyktech.atlassian.net/wiki/spaces/EN/pages/2400878648/Tyk+cloud+monitoring) on how monitoring works that goes into the implementation detail.

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

___

## **Type**
documentation, enhancement

___

## **Description**
- Added new detailed documentation on how monitoring works in Tyk Cloud, including specifics on traffic types and storage metrics.
- Introduced a new guide on how to access and interpret monitoring data in Tyk Cloud.
- Updated the site menu to reflect the new structure of the monitoring documentation, enhancing navigation and user experience.
- Removed outdated content from the old monitoring overview page to avoid redundancy and confusion.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>monitoring-how-it-works.md</strong><dd><code>Add Detailed Monitoring Mechanics Documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
<li>Introduced a new documentation page detailing how monitoring works in <br>Tyk Cloud.<br> <li> Explained the calculation of throughput metrics and the distinction <br>between charged and uncharged traffic.<br> <li> Included an image to visually represent traffic pricing in monitoring.<br> <br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4518/files#diff-efaa7ee1572e085b039ac1a54036c426d947000476e03ddf33900740abbdb6c2">+38/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>monitoring-usage.md</strong><dd><code>New Guide on Monitoring Usage in Tyk Cloud</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
<li>Created a new page to guide users on how to view throughput and <br>storage usage in Tyk Cloud.<br> <li> Provided instructions on how to access and interpret monitoring data.<br> <li> Added images to illustrate the monitoring interface and data filtering <br>options.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4518/files#diff-76d327612711fd0e977d8471fbba283f5fc9ea8bb4aa03d1d2040f690611a5c9">+35/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>monitoring.md</strong><dd><code>Remove Old Monitoring Overview Content</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring.md
- Removed the original monitoring page content.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4518/files#diff-25bf4aa967368d03384792484323a495340354a1bdb08729a06bf6417fc597dd">+0/-17</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>menu.yaml</strong><dd><code>Update Menu Structure for Monitoring Documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/data/menu.yaml
<li>Updated the menu structure to include new pages under the monitoring <br>section.<br> <li> Changed the 'Monitoring' menu entry from a page to a directory.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4518/files#diff-a6789c66bfa0660f7fdbe4796002ab4777677bae59a0276689c840100ff0b0b2">+10/-2</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

2024-04-25 15:17 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +Not all traffic is included in throughput calculation. Only external traffic is charged, whereas internal traffic is not. Monitoring service sum-sup traffic between different services:
Is it better to say `Only external traffic is charged` or `Only external traffic is priced`?

2024-04-25 15:24 UTC, komuw commented
The docs bible; https://tyktech.atlassian.net/wiki/spaces/EN/pages/1888976900/The+Docs+Bible+-+Docs+Contributors+Guide#Label-PR says;
```
For future releases, label it with -

- Future-release
- {release vX.Y.Z} - intended version number, e.g. release-6.1.
```

I have already added the `future-release` label. 
I have also added a new label `Ara 1.18.0` since we would like this to be released when Tyk Cloud v1.18.0 is released. Let me know if that's the right way, or if you already have pre-existing labels for Tyk Cloud.

2024-04-26 13:55 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +Not all traffic is included in throughput calculation. Only external traffic is charged, whereas internal traffic is not. Monitoring service sum-sup traffic between different services:
@komu Would this suggestion be ok?

```suggestion
External traffic is subject to billing, while internal traffic is exempt. The monitoring service aggregates traffic between different services:
```

2024-04-26 13:57 UTC, dcs3spp commented
> The docs bible; https://tyktech.atlassian.net/wiki/spaces/EN/pages/1888976900/The+Docs+Bible+-+Docs+Contributors+Guide#Label-PR says;
> 
> ```
> For future releases, label it with -
> 
> - Future-release
> - {release vX.Y.Z} - intended version number, e.g. release-6.1.
> ```
> 
> I have already added the `future-release` label. I have also added a new label `Ara 1.18.0` since we would like this to be released when Tyk Cloud v1.18.0 is released. Let me know if that's the right way, or if you already have pre-existing labels for Tyk Cloud.

Many thanks @komuw Ara 1.18.0 is perfect

2024-04-26 16:02 UTC, dcs3spp requested changes
Many thanks @komuw for submitting this much needed content!! I like the billing diagram overview and structure.

I have made some minor suggestions for section headings and suggest moving the billing diagram so that it appears before the billed and unbilled traffic example list

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +Charged Traffic:
```suggestion
### Billed traffic
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> + - Traffic between User → Control Plane
Make User lower case (user) in these list items

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +Uncharged traffic:
```suggestion
### Unbilled traffic
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +When a client makes a request to a Tyk Gateway deployment, the details of the request and response are captured and [stored in Redis]({{< ref "tyk-dashboard-analytics/" >}}). Tyk Pump processes the r
On a Tyk Cloud deployment is MongoDB the only configuration option for persistent storage or can PostgreSQL also be configured?

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +description: "How monitoring works"
```suggestion
description: "Explains the metrics that are monitored"
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +title: "How it works"
```suggestion
title: "What Metrics Are Monitored?"
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +Tyk Cloud keeps a counter of the total request/response sizes for traffic transferred through a deployment. We then calculate the difference between the throughput usage at the current time less the
```suggestion
Tyk Cloud counts the total request/response sizes for traffic transferred through a deployment. Throughput metrics are displayed for the current day. These are calculated as the difference between the throughput usage at the current time and the throughput at last midnight.
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +### Storage metric.
```suggestion
### Storage
```

In this section explain the unit of measurement for the storage metric, e.g. GB, TB

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +Toggle on _Storage_ to see throughput metrics
```suggestion
Enable *Storage* to display throughput metrics
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +Login to Tyk Cloud and click on the _Monitoring_. Toggle on _Throughput_ to see throughput metrics
```suggestion
Login to Tyk Cloud and click on *Monitoring* within the *Operations* menu. Enable *Throughput* to display throughput metrics.
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +You can also optionally filter for metrics by date
```suggestion
You can also optionally filter for metrics by date.
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +And you can see the metrics broken down per environment & a list of the top 5 control and cloud data planes
```suggestion
Here you can see the metrics broken down per environment and a list of the top 5 control and cloud data planes.
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +title: "Usage"
```suggestion
How to view usage
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +            - title: "How it works"
Maybe have _How it works_ as the first menu item and rename menu item to _What Metrics Are Monitored?_

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> +            - title: "Usage"
```suggestion
How to view usage
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +(a) Throughput: This is the total amount of data that has been transfered(ingress/egress) through a deployment.
```suggestion
**Throughput** - This is the total amount of data that has been transferred(ingress/egress) through a deployment. 
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +(b) Storage: This is the total amount of data stored as [analytics by Tyk Dashboard]({{< ref "tyk-dashboard-analytics/" >}}). An example is per request statistics containing information about each re
```suggestion
**Storage** - This is the total amount of data stored as [analytics by Tyk Dashboard]({{< ref "tyk-dashboard-analytics/" >}}). An example is *per request* statistics containing information about each request, like path or status.
```

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +
Move the diagram up to here, before charged traffic.

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +
Before the metrics section add a couple of sentences that explain the purpose of this page.

2024-04-26 16:02 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +### Throughput metric.
```suggestion
### Throughput
```

2024-04-28 19:05 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> + - Traffic between User → Control Plane
fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/7fe9433e5d58e50b5969e7c44067cef7418990ce

2024-04-28 19:10 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +
fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/213289023924b3e3a43969cffaf3eebe13891423

2024-04-28 19:16 UTC, komuw commented on tyk-docs/data/menu.yaml
> +            - title: "How it works"
fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/2d248b7c0be85fe73b67719d4db590008b13d481

2024-04-28 19:17 UTC, komuw commented on tyk-docs/data/menu.yaml
> +            - title: "Usage"
fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/09b63d32eab5d476128fb34678decfa64d82287d

2024-04-28 19:17 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +title: "Usage"
fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/09b63d32eab5d476128fb34678decfa64d82287d

2024-04-28 19:28 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +
fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/f6535b02735211f6add25f047c4f6090fd4a7fff

2024-04-28 19:31 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +### Storage metric.
fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/0b580b7600168bcde18512035198f5bc762e3a2e

2024-04-28 19:32 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +When a client makes a request to a Tyk Gateway deployment, the details of the request and response are captured and [stored in Redis]({{< ref "tyk-dashboard-analytics/" >}}). Tyk Pump processes the r
Mongo is the only option so far. It might change in the future. Maybe I shouldn't mention Mongo at all?

2024-04-29 07:57 UTC, komuw commented
> Many thanks @komuw for submitting this much needed content!! I like the billing diagram overview and structure.
> 
> I have made some minor suggestions for section headings and suggest moving the billing diagram so that it appears before the billed and unbilled traffic example list

Thanks for the review! I have addressed your feedback in subsequent commits.

2024-04-30 09:27 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +When a client makes a request to a Tyk Gateway deployment, the details of the request and response are captured and [stored in Redis]({{< ref "tyk-dashboard-analytics/" >}}). Tyk Pump processes the r
Ok thanks @komuw I think we can leave this unchanged and I will resolve the comment

2024-04-30 09:40 UTC, dcs3spp approved these changes

2024-04-30 09:41 UTC, dcs3spp commented
Thanks @komuw I have approved the PR and will merge and release once approved by @mitjaziv and @imogenkraak

2024-04-30 11:26 UTC, komuw commented
> Thanks @komuw I have approved the PR

Thanks  

> once approved by @mitjaziv and @imogenkraak

During todays stand-up, Mitja elected not to review the PR. Instead it will be Imogen who will do the review.

> will merge and release

Will this show up in the public docs? We would want to wait until the release of `Ara 1.18.0`, since this PR is made in the context of some monitoring changes that will only be available on Tyk cloud v1.18.0

cc @dcs3spp

2024-04-30 11:34 UTC, dcs3spp commented
> > Thanks @komuw I have approved the PR
> 
> Thanks
> 
> > once approved by @mitjaziv and @imogenkraak
> 
> During todays stand-up, Mitja elected not to review the PR. Instead it will be Imogen who will do the review.
> 
> > will merge and release
> 
> Will this show up in the public docs? We would want to wait until the release of `Ara 1.18.0`, since this PR is made in the context of some monitoring changes that will only be available on Tyk cloud v1.18.0
> 
> cc @dcs3spp

@komuw When is Ara 1.18.0 scheduled for release? We can either:
- merge to main branch once approved and then release when Ara 1.18.0 scheduled or
- merge PR when 1.18.0 is scheduled (in which case we close the PR once approved and re-open ready for release of Ara 1.18.0)

2024-04-30 13:12 UTC, imogenkraak commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +### How to check metrics?
Should remove the question mark here as it's not really a question

2024-04-30 13:13 UTC, imogenkraak commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +title: "What Metrics Are Monitored?"
Might be best to make `metrics are monitored` lowercase to match most of the other titles like this in the docs

2024-04-30 13:42 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +title: "What Metrics Are Monitored?"
@imogenkraak fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/b29886b4d147bd5cbd5ecb36970bc440a672949b

2024-04-30 13:42 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +### How to check metrics?
fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/b29886b4d147bd5cbd5ecb36970bc440a672949b

2024-04-30 14:05 UTC, imogenkraak commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +### Billed traffic
I'm not sure about this so just a suggestion, but it feels like `Billed traffic` and `Unbilled traffic` sections shouldn't be in the middle of `Throughput` and `Storage`. Could this belong as it's own `### Traffic billing` section, with `#### Billed traffic` and `####  Unbilled traffic` subsections?

2024-04-30 14:21 UTC, imogenkraak commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +title: "How to view usage"
Could also just be `Viewing usage`

2024-04-30 14:21 UTC, imogenkraak commented on tyk-docs/data/menu.yaml
> +            - title: "How to view usage"
Could also just be `Viewing usage`

2024-04-30 14:45 UTC, imogenkraak commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +Enable *Storage* to display throughput metrics
fix to display `display storage metrics` instead of `throughput`

2024-05-01 14:53 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +Enable *Storage* to display throughput metrics
Fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/87f3eb33f22a1ee3c6029a238cf4046094307fa2 
Thanks.

2024-05-01 14:53 UTC, komuw commented on tyk-docs/data/menu.yaml
> +            - title: "How to view usage"
Fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/87f3eb33f22a1ee3c6029a238cf4046094307fa2

2024-05-01 14:53 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +title: "How to view usage"
Fixed in https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/87f3eb33f22a1ee3c6029a238cf4046094307fa2

2024-05-01 14:55 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +### Billed traffic
@imogenkraak It is under the throughput section because it is only for throughput where we have a distinction where some traffic is billed and others is not. This is not the case for storage.

2024-05-01 14:58 UTC, komuw commented
@dcs3spp 

> When is Ara 1.18.0 scheduled for release? 

Tentatively, in three weeks time.

> We can either:
> - merge to main branch once approved and then release when Ara 1.18.0 scheduled or
> - merge PR when 1.18.0 is scheduled (in which case we close the PR once approved and re-open ready for release of Ara 1.18.0)

I'm fine with either option, though I would prefer the first so that I don't have to deal with merge conflicts in the future. But I'll let you make the call.

2024-05-02 08:43 UTC, imogenkraak commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +### Billed traffic
maybe it should be a subsection under throughput? Or have the titles of billed traffic and unbilled be a bit smaller? But can also keep it like this, I'm just being pedantic, I will approve :)

2024-05-02 08:52 UTC, imogenkraak commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +Enable *Storage* to display storage metrics
Tiny comment: need a dot at the end of this sentence to match the others.

2024-05-02 08:53 UTC, imogenkraak approved these changes

2024-05-02 08:58 UTC, komuw commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
> +Enable *Storage* to display storage metrics
fixed https://github.com/TykTechnologies/tyk-docs/pull/4518/commits/8e9f3f871e5f4eec6a05072f2eea790050528a44

2024-05-02 09:00 UTC, dcs3spp commented
Thanks for approving @imogenkraak 👍 

@komuw If you can address the [tiny comment ](https://github.com/TykTechnologies/tyk-docs/pull/4518#discussion_r1587286681) found by @imogenkraak then I will merge to the main branch ready for release. When Ara 1.18.0 is released then if you could tag me I will then release to live docs.

2024-05-02 11:36 UTC, komuw commented
> Thanks for approving @imogenkraak 👍
> 
> @komuw If you can address the [tiny comment ](https://github.com/TykTechnologies/tyk-docs/pull/4518#discussion_r1587286681) found by @imogenkraak then I will merge to the main branch ready for release. When Ara 1.18.0 is released then if you could tag me I will then release to live docs.

Fixed in https://github.com/TykTechnologies/tyk-docs/commit/8e9f3f871e5f4eec6a05072f2eea790050528a44

2024-05-02 13:32 UTC, dcs3spp commented on tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
> +### Billed traffic
Thanks @imogenkraak for raising the issue 👍 I have pushed changes to the branch so that titles for billed traffic and unbilled are smaller within the throughput section.

@komuw @imogenkraak if you are both ok with the change I will merge to the main branch ready for release

2024-05-03 09:02 UTC, merged

2024-05-21 08:09 UTC, dcs3spp commented
/release to release-5.3

2024-05-21 08:48 UTC, dcs3spp commented
/release to release-5.2

2024-05-21 08:49 UTC, dcs3spp commented
/release to release-5.1

2024-05-21 08:50 UTC, dcs3spp commented
/release to release-5