Create demo page and move batch function section
TykTechnologies/tyk-docs-hugo pull request #452
Opened 2018-06-11 14:15 UTC by marksou

Created demo page and moved the Batch Aggregate function section of Virtual Endpoints to its own page.

2018-06-12 08:28 UTC, asoorm commented on tyk-docs/content/compose-apis/demo-virtual-endpoint.md
> +  log('response type: ' + typeof response);
mix of single quotes & double quotes in same code snippet. Could look a bit neater

2018-06-12 08:30 UTC, asoorm commented on tyk-docs/content/compose-apis/demo-virtual-endpoint.md
> +  log("Request Headers:"+ JSON.stringify(request.Headers))
Some lines look like this: `: " + JSON` and some lines look like this: `:"+ JSON` - spacing inconsistencies.

2018-06-12 08:32 UTC, asoorm commented on tyk-docs/content/compose-apis/sample-batch-funtion.md
> +        {
lint: remove 1 level of indentation here.

2018-06-12 08:40 UTC, letzya commented on tyk-docs/content/compose-apis/demo-virtual-endpoint.md
> +  log("Request Headers:"+ JSON.stringify(request.Headers))
Thanks. Mark - please check that my content is inconsistent and looks good for the company's docs.

2018-06-12 09:53 UTC, asoorm commented on tyk-docs/content/compose-apis/sample-batch-funtion.md
> +    Body: ""
missing comma `,`

2018-06-12 14:58 UTC, marksou commented on tyk-docs/content/compose-apis/sample-batch-funtion.md
> +    Body: ""
@letzya Can you check the code for the batch function. It doesn't validate.

2018-06-21 14:17 UTC, asoorm commented on tyk-docs/content/compose-apis/demo-virtual-endpoint.md
> +3. From the Vrtual Endpoint settings, add a unique name in the **JS function to call** option. You should also use the same name inside the function code. For this demo, we will use `myVirtualHandler
typo: Vrtual

2018-06-21 14:21 UTC, asoorm commented on tyk-docs/content/compose-apis/demo-virtual-endpoint.md
> +3. From the Vrtual Endpoint settings, add a unique name in the **JS function to call** option. You should also use the same name inside the function code. For this demo, we will use `myVirtualHandler
`From the` repeated too many times on 3 consecutive lines.

2018-06-21 16:06 UTC, letzya requested changes

2018-06-21 16:06 UTC, letzya commented on tyk-docs/content/compose-apis/demo-virtual-endpoint.md
> +3. From the Vrtual Endpoint settings, add a unique name in the **JS function to call** option. You should also use the same name inside the function code. For this demo, we will use `myVirtualHandler
Can you please add the following text:

```
Every line in the script gives an example of a functionality usage:

How to get form param
How to get specific key inside json variable
The structure of request object with Body, Headers, (need to add session object examples)
Using TykMakeHttpRequest, and the json it returns - .Code and .Body
```

2018-06-21 16:06 UTC, letzya commented on tyk-docs/content/compose-apis/demo-virtual-endpoint.md
> +The virtual function is `base64` encoded in the `function_source_uri` field.
Please put it in a new line

2018-06-21 16:06 UTC, letzya commented on tyk-docs/content/compose-apis/demo-virtual-endpoint.md
> +> **NOTE**: Another option, instead of the steps above, you can use this link to import the api definition:
Instead of the steps above, you can actually import the [api definition](https://gist.github.com/letzya/5b5edb3f9f59ab8e0c3c614219c40747) we have created for you

2018-06-21 16:06 UTC, letzya commented on tyk-docs/content/compose-apis/demo-virtual-endpoint.md
> +
Please change the content of the log with the following:

```
[Jun 13 14:45:21] DEBUG jsvm: Running: myVirtualHandlerGetHeaders
Virtual Test running
[Jun 13 14:45:21]  INFO jsvm-logmsg: Request Session: {"access_rights":null,"alias":"","allowance":0,"apply_policies":null,"apply_policy_id":"","basic_auth_data":{"hash_type":"","password":""},"certificate":"","data_expires":0,"enable_detail_recording":false,"expires":0,"hmac_enabled":false,"hmac_string":"","id_extractor_deadline":0,"is_inactive":false,"jwt_data":{"secret":""},"last_check":0,"last_updated":"","meta_data":null,"monitor":{"trigger_limits":null},"oauth_client_id":"","oauth_keys":null,"org_id":"","per":0,"quota_max":0,"quota_remaining":0,"quota_renewal_rate":0,"quota_renews":0,"rate":0,"session_lifetime":0,"tags":null} type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: API Config:{"APIID":"57d72796c5de45e649f22da390d7df43","OrgID":"5afad3a0de0dc60001ffdd07","config_data":{"bar":{"y":3},"foo":4}} type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: Request object: {"Body":"","Headers":{"Accept":["*/*"],"Location":["/get"],"User-Agent":["curl/7.54.0"]},"Params":{"param1":["I-am-param-1"]},"URL":"/testvirtualendpoint2/headers"} type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: Request Body: "" type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: Request Headers:{"Accept":["*/*"],"Location":["/get"],"User-Agent":["curl/7.54.0"]} type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: param-1:I-am-param-1 type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: Request header type:[object Object] type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: Request header: ["/get"] type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: Request location type: object type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: Request location type: string type=log-msg
[Jun 13 14:45:21]  INFO jsvm-logmsg: Request location: /get type=log-msg
--- before get to upstream ---
--- After get to upstream ---
[Jun 13 14:45:22]  INFO jsvm-logmsg: response type: string type=log-msg
[Jun 13 14:45:22]  INFO jsvm-logmsg: response: {"Code":200,"Body":"{\"headers\":{\"Accept-Encoding\":\"gzip\",\"Connection\":\"close\",\"Host\":\"httpbin.org\",\"Location\":\"/get\",\"User-Agent\":\"Go-http-client/1.1\"}}\n","Headers":{"Access-Control-Allow-Credentials":["true"],"Access-Control-Allow-Origin":["*"],"Content-Length":["133"],"Content-Type":["application/json"],"Date":["Wed, 13 Jun 2018 13:45:21 GMT"],"Server":["gunicorn/19.8.1"],"Via":["1.1 vegur"]},"code":200,"body":"{\"headers\":{\"Accept-Encoding\":\"gzip\",\"Connection\":\"close\",\"Host\":\"httpbin.org\",\"Location\":\"/get\",\"User-Agent\":\"Go-http-client/1.1\"}}\n","headers":{"Access-Control-Allow-Credentials":["true"],"Access-Control-Allow-Origin":["*"],"Content-Length":["133"],"Content-Type":["application/json"],"Date":["Wed, 13 Jun 2018 13:45:21 GMT"],"Server":["gunicorn/19.8.1"],"Via":["1.1 vegur"]}} type=log-msg
Virtual Test ended
[Jun 13 14:45:22] DEBUG JSVM Virtual Endpoint execution took: (ns) 191031553
```

2018-06-21 16:06 UTC, letzya commented on tyk-docs/content/compose-apis/sample-batch-funtion.md
> +> **NOTE**: Virtual endpoints are not available in the Tyk Cloud Edition.
it's a batch example

2018-06-21 16:06 UTC, letzya commented on tyk-docs/content/compose-apis/virtual-endpoints.md
>  > **NOTE**: Virtual endpoints are not available in the Tyk Cloud Edition.
Doesn't it look a bit to much?
![image](https://user-images.githubusercontent.com/3155222/41730655-3b58d3e2-7574-11e8-8ed8-a161629b0c1f.png)

2018-06-21 16:06 UTC, letzya commented on tyk-docs/content/compose-apis/sample-batch-funtion.md
> +The above code is pretty self explanatory, so we won't go into great detail - the batch object here is the same object that is fed into our batch request method `TykBatchRequest` that is exposed as p
@asoorm Do you thing we should write ` so we won't go into great detail`?

2018-06-21 16:06 UTC, letzya commented on tyk-docs/content/compose-apis/sample-batch-funtion.md
> +
add title - "Batch using /tyk/batch endpoint"

2018-06-25 08:03 UTC, marksou commented on tyk-docs/content/compose-apis/virtual-endpoints.md
>  > **NOTE**: Virtual endpoints are not available in the Tyk Cloud Edition.
I'll move the first note into the text. The others should stay.

2018-06-26 08:10 UTC, marksou commented
All requested changes made.

2018-06-26 08:10 UTC, merged