[TT-9514] Include tyk-operator chart as optional components in the umbrella chart
TykTechnologies/tyk-docs-hugo pull request #4548
Opened 2024-04-30 11:57 UTC by buraksekili

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>
https://tyktech.atlassian.net/browse/TT-9514
---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-04-30 13:33 UTC, olamilekan000 approved these changes

2024-04-30 15:31 UTC, dcs3spp requested changes
Hi @buraksekili Thanks for submitting PR, I have reviewed and made suggestions to fix the line breaks and once peer approved then will merge and release.

2024-04-30 15:31 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +to `true`.
move onto same line in line 478

2024-04-30 15:31 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +> official documentation: [Installing Tyk Operator]({{<ref "tyk-stack/tyk-operator/installing-tyk-operator">}}).
remove line break, include as line 483

2024-04-30 15:31 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +to `true`.
same comments as above

2024-04-30 15:31 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +`tyk-operator-system` namespace.
remove line break so sentence part of line 196

2024-04-30 15:34 UTC, dcs3spp reviewed
@buraksekili Could you add a label to the PR to indicate the version of docs (5.3, 5.2 etc) that you wish to release to? Does this relate to Tyk Charts 1.4.0?

@carol would you be able to peer review?

2024-05-04 08:49 UTC, caroltyk approved these changes
Looks good to me!

2024-05-06 09:11 UTC, buraksekili commented
thanks for suggestions @dcs3spp! I applied code suggestions accordingly. Could you please have a look once again?

This PR is for tyk-charts 1.5.0 release, not for 1.4.0. So, we need to wait for 1.5.0

2024-05-08 15:56 UTC, dcs3spp approved these changes
Thanks @buraksekili Will release PR when Tyk Charts 1.5.0 released

2024-05-09 11:48 UTC, merged