Add docs for the custom rate limit keys
TykTechnologies/tyk-docs-hugo pull request #4563
Opened 2024-05-01 00:27 UTC by slega

### For internal users - Please add a Jira DX PR ticket to the subject!
https://tyktech.atlassian.net/browse/DX-1310
<br>

---

### Preview Link

<br>

### Description
Add docs for configuring custom rate limit keys
<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [X] I **labelled** the PR

2024-05-01 15:33 UTC, dcs3spp requested changes
PR LGTM @slega I have made minor suggestions. Once peer review and approval given then PR is ready for merging and release

2024-05-01 15:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +Different business models may require applying rate limits and quotas not only by credentials but also by other entities, such as per application, per developer, per organization, and so on.
```suggestion
Different business models may require applying rate limits and quotas not only by credentials but also by other entities, e.g. per application, per developer, per organization etc.
```

2024-05-01 15:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +
remove additional blank line

2024-05-01 15:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +For instance, if an API Product is sold to a B2B customer, the quota of API calls is usually applied to all developers and their respective applications combined, and to a specific credential.
```suggestion
For example, if an API Product is sold to a B2B customer, the quota of API calls is usually applied to all developers and their respective applications combined, in addition to a specific credential.
```

2024-05-01 15:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +Custom rate limit keys are applied at a policy level. When a custom rate limit key is specified, quota, rate limit, and throttling will be calculated against the specified value and not against a cre
```suggestion
Custom rate limit keys are applied at a policy level. When a custom rate limit key is specified, quota, rate limit and throttling will be calculated against the specified value and not against a credential ID.
```

2024-05-01 15:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +For instance, to specify a rate limit pattern to calculate rate limit for a combination of developers and plans (thus, all credentials of a developer that use the same plan would share the same rate
maybe reduce the length of the sentence. The bracketed sentence makes the sentence too long and difficult to read

2024-05-01 15:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +To achieve this, the portal, by default, populates the following attributes in the credential metadata:
Add a blank line before this line, i.e. before line 55

2024-05-01 15:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +
Remove additional blank line

2024-05-01 15:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +{{< img src="/img/dashboard/portal-management/enterprise-portal/credential-metadata.png" alt="Credential's metadata" >}}
Add blank line before the img

2024-05-01 15:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +This approach allows the portal to seamlessly apply rate limits based on any combination of the aforementioned fields and other custom metadata objects defined in policies used for plans or products,
```suggestion
This approach allows the portal to seamlessly apply rate limits based on any combination of the aforementioned fields and other custom metadata objects defined in policies used for plans or products. This is in addition to credentials.
```

2024-05-01 16:26 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +
Done

2024-05-01 16:26 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +For instance, to specify a rate limit pattern to calculate rate limit for a combination of developers and plans (thus, all credentials of a developer that use the same plan would share the same rate
Done

2024-05-01 16:26 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +To achieve this, the portal, by default, populates the following attributes in the credential metadata:
Done

2024-05-01 16:26 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +
Done

2024-05-01 16:26 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +{{< img src="/img/dashboard/portal-management/enterprise-portal/credential-metadata.png" alt="Credential's metadata" >}}
Done

2024-05-02 08:06 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +The `rate_limit_pattern` syntax support referencing session metadata using `$tyk_meta.FIELD_NAME` reference.
The `rate_limit_pattern` field supports referencing session metadata using `$tyk_meta.FIELD_NAME` syntax.

2024-05-02 08:06 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +
Needs a space between the image and the Note

2024-05-02 08:06 UTC, rewsmith commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +- **TeamIDs**: A list of team IDs to which the developer belongs.
If a developer belongs to multiple teams, do we track RLs, quota etc for each team individually?  Maybe worth explaining how that works with an example.

2024-05-02 13:17 UTC, dcs3spp requested changes
Thanks @slega PR LGTM. Once changes requested from @rewsmith have been approved we can merge and release.

2024-05-02 13:46 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +The `rate_limit_pattern` syntax support referencing session metadata using `$tyk_meta.FIELD_NAME` reference.
Fixed

2024-05-02 13:49 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +- **TeamIDs**: A list of team IDs to which the developer belongs.
We don't track ratelimits for individual team - the RL key is always a string. So if a developer belongs to multiple teams, the RL key will a combination of IDs of those team. We populate this field in the credentials metadata for other purposes e.g. sending it to 3rd party systems through custom plugins. I will remove that for now so that developers won't be confused.

2024-05-02 15:53 UTC, slega commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
> +
Fixed

2024-05-02 15:58 UTC, dcs3spp approved these changes

2024-05-02 15:58 UTC, merged

2024-05-02 15:58 UTC, dcs3spp commented
/release to release-5.3

2024-05-02 16:01 UTC, dcs3spp commented
/release to release-5.2