operator release 0.17.1
TykTechnologies/tyk-docs-hugo pull request #4603
Opened 2024-05-03 23:50 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-05-06 09:04 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +<summary>Fixed: CVE </summary>
we fixed two CVEs: CVE-2023-45288 and CVE-2024-24786
```suggestion
<summary>Fixed CVE-2023-45288 and CVE-2024-24786 </summary>
```

2024-05-08 07:59 UTC, buraksekili approved these changes

2024-05-08 08:47 UTC, dcs3spp requested changes
Thanks for submitting release notes for operator 0.17.1 @caroltyk I have made minor suggestions before merge and release. Is this targetted for release 5.3.0 only?

2024-05-08 08:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +Go to the [Upgrading Tyk Operator]({{<ref "tyk-stack/tyk-operator/installing-tyk-operator#upgrading-tyk-operator">}}) section for detailed upgrade Instructions.
Update to make instructions lower case

2024-05-08 08:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +<summary>Fixed ApiDefinition CRs generated by the Ingress Controller used a wrong certiciate</summary>
update typo for certificate and expand CR abbreviation

2024-05-08 08:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +When using Tyk as Ingress Controller with TLS enabled, the ApiDefinition CRs generated by the Ingress Controller is missing OrgID field. As a result, Tyk Gateway used a wrong certificate when serving
Expand CR abbreviation

```suggestion
When using Tyk as an Ingress Controller with TLS enabled, the ApiDefinition CRs generated by the Ingress Controller is missing the OrgID field. As a result, Tyk Gateway used a wrong certificate when serving a request. It is fixed by adding back OrgID field to ApiDefinition CRs created by Ingress Controller.</summary>
```

2024-05-08 08:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +<summary>Addressed security vulnerabilities CVE-2024-24786 </summary>
remove extra space before ending summary tag

2024-05-08 08:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
> +Addressed security vulnerabilities [CVE-2024-24786](https://nvd.nist.gov/vuln/detail/CVE-2024-24786) where the protojson.Unmarshal function can enter an infinite loop when unmarshaling certain forms
Add backticks, e.g. protojson.Unmarshal etc.

2024-05-08 08:56 UTC, caroltyk commented
Thanks for the review @dcs3spp . Docs updated as per comments.

2024-05-08 08:58 UTC, dcs3spp approved these changes
Thanks @caroltyk PR LGTM, I'll merge and release to 5.3.0

2024-05-08 09:00 UTC, merged

2024-05-08 09:00 UTC, dcs3spp commented
/release to release-5.3