Erase the Support Message for EDP
TykTechnologies/tyk-docs-hugo pull request #4628
Opened 2024-05-09 16:53 UTC by vverbani

The previous message about contact support to get access is false. We don't give anyone access - especially when it comes  to the EDP. So getting rid of this message as it's false advertising. Please approve.

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

2024-05-14 11:00 UTC, dcs3spp requested changes
Thanks @vverbani PR LGTM. I have made minor suggestion relating to removal of Installing Tyk Enterprise Developer Portal:

If we remove this heading then bump the style for the sub heading Installation steps up a level, e.g. ### Installation steps becomes ## Installation steps

2024-05-14 11:00 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
> -## Installing Tyk Enterprise Developer Portal
If we remove this heading then bump the style for the sub heading _Installation steps_ up a level, e.g. _###  Installation steps_ becomes _## Installation steps_

2024-05-14 16:57 UTC, slega approved these changes
LGTM

2024-05-16 08:47 UTC, dcs3spp approved these changes

2024-05-16 08:48 UTC, dcs3spp approved these changes
PR LGTM, I have updated heading style for Installation steps to be H2. Thanks @vverbani

2024-05-16 08:49 UTC, merged

2024-05-16 08:49 UTC, dcs3spp commented
/release to release-5.3

2024-05-16 08:50 UTC, dcs3spp commented
/release to release-5.2

2024-05-16 08:51 UTC, dcs3spp commented
/release to release-5.1

2024-05-16 08:53 UTC, dcs3spp commented
/release to release-5