Add Community Edition section
TykTechnologies/tyk-docs-hugo pull request #463
Opened 2018-06-20 10:01 UTC by marksou

2018-06-28 11:41 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +* [The Tyk Identity Broker](https://tyk.io/docs/concepts/tyk-components/identity-broker/): Tyk's third-party IDP integration service.
I would remove TIB from this tutorial. That's not getting started and confuses the issue.

2018-06-28 11:41 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +* [The Tyk Pump](https://tyk.io/docs/concepts/tyk-components/pump/): Tyk's analytics data sink, used to send analytics data to platforms such as StatsD, ElasticSearch and InfluxDB.
I would remove Tyk Pump from this tutorial - It is not required for Tyk CE

2018-06-28 11:42 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +*   You have MongoDB installed and running.
MongoDB is not required for Tyk CE

2018-06-28 11:42 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +### Install MongoDb 3.2
remove references to Mongo

2018-06-28 11:42 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +#### Install the Tyk Pump First
remove tyk pump

2018-06-28 11:44 UTC, asoorm requested changes
I would suggest that we remove any mention of Mongo & Tyk Pump or Tyk Identity Broker from this guide.

2018-06-28 12:22 UTC, marksou commented
Updated following review

2018-06-28 13:07 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +### Install MongoDb 3.2
@marksou ^^

2018-07-04 11:34 UTC, buger commented
@asoorm pls check again

2018-07-04 11:55 UTC, asoorm requested changes

2018-07-04 11:55 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +    sudo /opt/tyk-gateway/install/setup.sh --listenport=8080 --redishost=localhost --redisport=6379 --domain=""
remove tab for consistency

2018-07-04 11:55 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +    sudo service tyk-gateway start
remove tab

2018-07-04 11:55 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +#### Pro Tip: Domains with Tyk Gateway
Pro Tip just below introduction to `What is Tyk Community Edition`? Maybe move this section to bottom of the page?

2018-07-04 11:55 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +Tyk Community Edition is the open-source API Gateway that is developed by our community and supported by our community members and advocates (with some help from the Tyk Technologies team). The Tyk C
Probably a separate issue, but we definitely need to include more info on what Tyk CE is before we dive deep into installation of.

2018-07-04 11:55 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +
Please create new issue/ticket - Need a guide on compiling Tyk CE from source & Also with Docker / Docker Compose.

2018-07-04 11:55 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +    ssudo /opt/tyk-gateway/install/setup.sh --listenport=8080 --redishost=localhost --redisport=6379 --domain=""
`ssudo` should be `sudo`

2018-07-04 11:55 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/tutorials/tutorials.md
> +* Create an API
To add a bit more value, maybe provide direct links to each section of the tutorials for each of the three options.

2018-07-04 11:55 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/tutorials/create-api.md
Add `Prerequisites` section to top of this page. Something along lines of: 

> In order to follow along with this tutorial, we will assume that you have successfully installed Tyk CE.

(Providing direct link to install guide)

2018-07-04 11:55 UTC, asoorm commented on tyk-docs/content/get-started/with-tyk-community-edition/tutorials/create-security-policy.md
>  ## <a name="what-is-a-security-policy"></a>What is a security policy ?
In this page, please fix/standardise example code spacing. 

1. remove first indentation.
2. 2-space tabs for json
3. I cannot add comments, but there are a few `mmark` files which need updating.

2018-07-04 11:57 UTC, asoorm commented
@marksou Mostly cleanup suggestions

2018-07-09 09:04 UTC, marksou commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +
#486

2018-07-09 09:05 UTC, marksou commented on tyk-docs/content/get-started/with-tyk-community-edition/with-tyk-community-edition.md
> +Tyk Community Edition is the open-source API Gateway that is developed by our community and supported by our community members and advocates (with some help from the Tyk Technologies team). The Tyk C
#485

2018-07-12 11:11 UTC, asoorm approved these changes

2018-07-12 11:13 UTC, merged