[TT-12124] Update rate limiter docs with Fixed Window Rate Limiter
TykTechnologies/tyk-docs-hugo pull request #4630
Opened 2024-05-13 16:10 UTC by titpetric

- Capitalize Redis, Redis Rate Limiter
- Add Redis impact notes for each option
- Add Fixed Window Rate Limiter section

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-05-14 06:16 UTC, lghiur commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This is the default rate limiter in Tyk. It is the most performant but has a trade-off that the limit applied is approximate, not exact. To use a less performant, exact rate limiter, review the Redis
@titpetric I think we should mention it's limitation, in that this doesn't work with keep-alive setting, when all traffic goes to only one GW.

2024-05-14 06:52 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +- Using Redis lets any gateways respect a cluster-wide rate limit
```suggestion
- Using Redis lets any gateway respect a cluster-wide rate limit
```

2024-05-14 06:53 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +responses stop and normal traffic resumes.
```suggestion
responses stop and normal behaviour resumes.
```

2024-05-14 06:56 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +usage increases with traffic and shorter `per` values are recommended to
```suggestion
usage increases with traffic therefore shorter `per` values are recommended to
```

2024-05-14 06:57 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +- Each request for the sliding log is written in background, including blocked requests
The last bullet point sounds weird, maybe @andyo-tyk  can come up with a better rephrasing.

2024-05-14 07:17 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +responses stop and normal traffic resumes.
```suggestion
responses stop and traffic is resumed.
```

2024-05-14 07:21 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +- Each request for the sliding log is written in background, including blocked requests
```suggestion
- Requests, including blocked requests, are written to the sliding log in a background thread
```

2024-05-14 10:48 UTC, dcs3spp requested changes
Thanks @titpetric PR LGTM, I have made minor suggestions and once peer approved then ready for release. Would you be able to add label to the PR indicating which release this targets?

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +The Distributed Rate Limiter will be used automatically unless one of the
```suggestion
The Distributed Rate Limiter (DRL) will be used automatically unless one of the
```

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +The Redis Rate Limiter implements a sliding log:
```suggestion
The Redis Rate Limiter (RRL) implements a sliding window log algorithm:
```

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +The Redis Sentinel Rate Limiter option will enable:
Is there an abbreviation for Redis Sentinel Rate Limiter and Fixed Window Rate Limiter?

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This algorithm can be enabled using the following configuration option [enable_redis_rolling_limiter]({{< ref "tyk-oss-gateway/configuration.md#enable_redis_rolling_limiter" >}}).
```suggestion
This algorithm can be enabled via the [enable_redis_rolling_limiter]({{< ref "tyk-oss-gateway/configuration.md#enable_redis_rolling_limiter" >}}) configuration option.
```

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +Please see the [Fixed Window Rate Limiter]({{< ref "#fixed-window-rate-limiter" >}}) if you don't want spike arrest behaviour.
```suggestion
Please consult our [Fixed Window Rate Limiter]({{< ref "#fixed-window-rate-limiter" >}}) documentation if you wish to avoid spike arrest behaviour.
```

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +effect for a minimum of the configured `per` duration. Gateway and Redis
```suggestion
effect for a minimum of the configured window duration (`per`). Gateway and Redis
```

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +Please see the [Fixed Window Rate Limiter]({{< ref "#fixed-window-rate-limiter" >}}) as an alternative, if Redis performance is an issue.
```suggestion
Please consider the [Fixed Window Rate Limiter]({{< ref "#fixed-window-rate-limiter" >}}) algorithm as an alternative, if Redis performance is an issue.
```

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +### DRL Threshold
```suggestion
### Distributed Rate Limiter (DRL) Threshold
```

In the section below expand DRL and RRL abbreviations and add backticks consistently for `drl_threshold`

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +minimum number of requests per gateway that triggers the Redis rate
Captialise Redis Rate Limiter

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +- The counter expires every configured `per` duration.
```suggestion
- The counter expires after every configured window (`per`) duration.
```

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +The implementation does not handle traffic busts within a window. For any
```suggestion
The implementation does not handle traffic bursts within a window. For any
```

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +the rate limit is reached and requests blocked for the remainder of the
```suggestion
the rate limit is reached and requests are blocked for the remainder of the
```

2024-05-14 10:48 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +window.
```suggestion
window duration.
```

2024-05-14 13:33 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +The Redis Sentinel Rate Limiter option will enable:
@dcs3spp there isn't, and I'm reverting the RRL one

2024-05-14 13:48 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +The Distributed Rate Limiter will be used automatically unless one of the
dismissed, DRL is an abbreviation acronym which shouldn't be repeated with the full name

2024-05-14 13:52 UTC, titpetric commented
@dcs3spp done and done, just give it another read if you're happy (~20 feedback items applied, DRL consistently used as acronym, RRL acronym removed as unused with a single reference)

2024-05-14 15:11 UTC, dcs3spp approved these changes
Thanks @titpetric PR LGTM, once all have peer approved then ready for release

2024-05-14 16:12 UTC, andyo-tyk requested changes
Suggested changes - and request to reorder the page.

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +algorithms are explicitly enabled via configuration.
```suggestion
algorithms is explicitly enabled via configuration.
```

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +rate limiting.
Does this mean "this algorithm will yield approximate results due to the lack of a shared request counter, with accuracy reducing as the maximum request rate for each gateway decreases"?

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +implemented using a token bucket implementation that does not use Redis.
Could we add a link to definition of token bucket algorithm?

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This rate limiter implements a sliding window log algorithm:
Could we include a link to a definition of the sliding log algorithm?

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +- Requests, including blocked requests, are written to the sliding log
```suggestion
- A record of each request, including blocked requests that return `HTTP 429`, is written to the sliding log in Redis
```

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +- The log is always trimmed to the duration of the defined window
```suggestion
- The log is constantly trimmed to the duration of the defined window
- Requests are blocked if the count in the log exceeds the configured rate limit
```

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +have to be reduced below 3000 for a whole minute before the HTTP 429
```suggestion
have to be reduced below 3000 requests/minute for a whole minute before the `HTTP 429`
```

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +limit. For example, if the rate limit is 3000/minute the call rate would
```suggestion
limit. For example, if the configured rate limit is 3000 requests/minute the call rate would
```

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This behaviour is called spike arrest. As the complete request log is
```suggestion
This behaviour is called Spike Arrest and is used to force clients to reduce their request rate as no requests will be accepted until the "spike" ends. As the complete request log is
```
Could we add a link to a definition of Spike Arrest?

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +Even during traffic blocking, Redis will use significant resources to
```suggestion
This algorithm will use significant resources on Redis even when blocking requests, as it must
```

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +wait for the sliding log write to complete. The behaviour still has spike
```suggestion
wait for the sliding log write to complete. This algorithm exhibits spike
```

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +arrest behaviour, however recovery may take longer as the blocking is in
```suggestion
arrest behaviour the same as the basic Redis Rate Limiter, however recovery may take longer as the blocking is in
```

2024-05-14 16:12 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  ## Rate limiting levels
Can you please move this section (and "When might you want to use rate limiting?") above "Types of Rate Limiting"?

Then we have a standard flow:
- What is it 
- Why would you use it
- How does it work

2024-05-15 08:15 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +implemented using a token bucket implementation that does not use Redis.
above

2024-05-15 08:18 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +rate limiting.
basically, can reword further if you'd like to

2024-05-15 08:18 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This rate limiter implements a sliding window log algorithm:
above

2024-05-15 09:43 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This behaviour is called spike arrest. As the complete request log is
We can't link a spike arrest definition without linking to a competitor it seems (no wiki, etc.), but the previous paragraph explains it well. The suggested change doesn't add value, Spike Arrest should not be capitalized (spike = traffic spike, arrest = stop, english).

2024-05-15 10:31 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +rate limiting.
Yes, please - I think just saying "due to the nature of local rate limiting" makes an assumption that the reader is aware of that nature/the limitations. Perhaps expand a little on this?

2024-05-15 10:41 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +This behaviour is called spike arrest. As the complete request log is
OK... I think I can see the problem here and it's going to need a further overhaul of the page once these technical changes are added. The page needs to be restructured to flow better from a user perspective in terms of what rate limiting is, the different behaviours we offer and when/why a user might choose to use each one. I think we need to change the focus of the terminology away from the implementation/traditional naming and towards the behaviour of each ption. I'll pick this up later, once this PR is merged.

2024-05-15 10:41 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
>  ## Rate limiting levels
Ignore this - I'll work on this in a future PR

2024-05-15 10:41 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +rate limiting.
Ignore this.

2024-05-15 10:42 UTC, andyo-tyk commented
PR looks good to me. Thanks.

2024-05-15 10:42 UTC, andyo-tyk approved these changes
PR looks good to me, thanks.

2024-05-16 07:50 UTC, jeffy-mathew approved these changes

2024-05-16 08:14 UTC, dcs3spp commented
@andrei-tyk @lghiur Are you ok to approve this ready for merge and release?

2024-05-16 08:33 UTC, andyo-tyk commented
@dcs3spp I don't think everyone on the list needs to approve this - there's technical approval from @jeffy-mathew and I've given approval so should be OK to go IMHO. 🙏

2024-05-17 15:16 UTC, dcs3spp commented
> @dcs3spp I don't think everyone on the list needs to approve this - there's technical approval from @jeffy-mathew and I've given approval so should be OK to go IMHO. 🙏

👌 Thanks @andyo-tyk I will merge to main branch now

2024-05-17 15:17 UTC, merged