[DX-1332] Update content where possible for inclusivity of primary/secondary
TykTechnologies/tyk-docs-hugo pull request #4641
Opened 2024-05-16 14:25 UTC by dcs3spp

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-05-17 08:48 UTC, andyo-tyk requested changes
Some suggested changes to use the word "gateway" rather than "node".

2024-05-17 08:48 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
> +The Management and worker environments usually do not share any secrets; thus a certificate with private keys encoded with secret in management Gateway will not be accessible to workers.
```suggestion
The Control Plane and Data Plane environments usually do not share any secrets; thus a certificate with private keys encoded with secret in the Control Plane will not be accessible to Data Plane gateways. 
```

2024-05-17 08:48 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
> +Mutual TLS configuration in an MDCB environment has specific requirements. An MDCB environment usually consists of a management environment and workers who, using MDCB, sync configuration.
```suggestion
Mutual TLS configuration in an MDCB environment has specific requirements. An MDCB environment consists of a Control Plane and multiple Data Planes that, using MDCB, sync configuration. 
```

The agreed MDCB terminology is Control Plane and Data Plane. I thought we were moving away from describing the Gateways deployed in each as "management gw" and "worker gw" (though accept the page I wrote a long time ago still uses the "worker" term - https://tyk.io/docs/tyk-multi-data-centre/mdcb-components/#data-plane)

2024-05-17 08:48 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
> +send them to client without password. Using a secure connection between worker Gateways and MDCB is required in this case. See MDCB setup page for use_ssl usage.
```suggestion
send them to client without password. Using a secure connection between Data Plane Gateways and MDCB is required in this case. See MDCB setup page for use_ssl usage.
```

2024-05-17 08:48 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
> +When uptime tests are added into a Tyk cluster, a single node will elect itself as primary. Primary nodes stay in this state using a dead man's switch, by keeping a key active in Redis. Primaries are
```suggestion
When uptime tests are added into a Tyk cluster, a single Gateway will elect itself as primary. Gateways remain as primary using a dead man's switch, by keeping a key active in Redis. Primaries are re-elected or confirmed every few seconds. If one Gateway stops or fails, another can detect the failure and elect itself as the primary.
```

Try to move away from the term "node" as it is not defined anywhere - use Gateway.

2024-05-17 08:48 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
> +The primary node will then run the uptime tests allocated to the cluster (shard group).
```suggestion
The primary Gateway will then run the uptime tests allocated to the cluster (shard group).
```

2024-05-17 08:48 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
>  The node running the uptime test will have a worker pool defined so that it can execute tests simultaneously every few seconds determined by a node-configurable interval loop. Depending on how many u
```suggestion
The Gateway running the uptime test will have a worker pool defined so that it can execute tests simultaneously every few seconds determined by a Gateway-configurable interval loop. Depending on how many uptime tests are being run, this worker pool should be increased or decreased as needed.
```

2024-05-17 08:48 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
>  *   `disable`: When set to `false` this tells Tyk to run uptime tests, if you do not want any uptime tests to run on a node, set it to `true` and they will be disabled on those nodes (this could be u
```suggestion
*   `disable`: When set to `false` this tells Tyk to run uptime tests, if you do not want any uptime tests to run on a Gateway, set it to `true` and they will be disabled on those Gateways (this could be useful if you are running uptime tests in a separate group of Tyk instances).
```

2024-05-17 08:48 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
> +*   `poller_group`: This field is used to define a different group of uptime tests. All the gateways that have the same `poller_group`, will be candidate to be elected as the primary node of its grou
```suggestion
*   `poller_group`: This field is used to define a different group of uptime tests. All the gateways that have the same `poller_group`, will be candidate to be elected as the primary Gateway of its group. This could be useful if you are running uptime tests in a segmented or sharded group of Tyk instances.
```

2024-05-17 08:48 UTC, andyo-tyk commented on tyk-docs/content/planning-for-production/redis.md
> +Tyk uses Redis to store API tokens and OAuth clients, so it is advisable to *not* treat Redis instances as ephemeral. The exception to this is when you are using Tyk Multi Data Center Bridge, but you
"Redis master" is the Redis terminology: they appear to use master-replica (ref: https://redis.io/docs/latest/operate/oss_and_stack/management/replication/)

2024-05-17 09:20 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
> +Mutual TLS configuration in an MDCB environment has specific requirements. An MDCB environment usually consists of a management environment and workers who, using MDCB, sync configuration.
👌 Thanks @andyo-tyk for this 🙇 Have read through the link and yep can see from the glossary that using Control Plane and Data Planes as terminology for the deployment types. I'll commit the suggestion

2024-05-17 09:30 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
> +The Management and worker environments usually do not share any secrets; thus a certificate with private keys encoded with secret in management Gateway will not be accessible to workers.
@andyo-tyk Should I use deployments instead of environments?

```suggestion
The Control Plane and Data Plane deployments usually do not share any secrets; thus a certificate with private keys encoded with secret in the Control Plane will not be accessible to Data Plane gateways. 
```

2024-05-17 09:43 UTC, dcs3spp commented on tyk-docs/content/planning-for-production/redis.md
> +Tyk uses Redis to store API tokens and OAuth clients, so it is advisable to *not* treat Redis instances as ephemeral. The exception to this is when you are using Tyk Multi Data Center Bridge, but you
Thanks @andyo-tyk I had a look at Redis docs and they use primary only if the context is a cluster:

- They use master-replica in their [replication docs](https://redis.io/docs/latest/operate/oss_and_stack/management/replication/), [Redis Sentinel](https://redis.io/docs/latest/operate/oss_and_stack/management/sentinel/) and for [fail over](https://redis.io/docs/latest/commands/failover/)
- For [Redis Clusters](https://redis.io/redis-enterprise/technology/redis-enterprise-cluster-architecture/) they use primary and replica.

As a precaution for the context of this [page](https://tyk.io/docs/nightly/planning-for-production/redis#protection-of-redis-data) I have replaced _primary_ back to _master_

2024-05-17 10:04 UTC, dcs3spp commented
Thanks for reviewing and giving feedback on this @andyo-tyk

I have committed your suggestions. Should I use [deployments instead of environments](https://github.com/TykTechnologies/tyk-docs/pull/4641#discussion_r1604635353) for the MDCB content?

2024-05-20 11:21 UTC, dcs3spp commented
@caroltyk Are you ok with the suggestions made in tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md

@andyo-tyk Thanks, I have committed suggestions with suggested changes for review

2024-05-21 14:51 UTC, andyo-tyk approved these changes

2024-05-22 16:26 UTC, dcs3spp commented
@caroltyk Are you ok with the suggestions made in [https://deploy-preview-4641--tyk-docs.netlify.app/docs/nightly/basic-config-and-security/security/mutual-tls/concepts](https://deploy-preview-4641--tyk-docs.netlify.app/docs/nightly/basic-config-and-security/security/mutual-tls/concepts/#mdcb)

2024-05-22 20:56 UTC, caroltyk approved these changes

2024-05-24 15:57 UTC, sredxny approved these changes

2024-05-24 16:02 UTC, merged

2024-05-24 16:02 UTC, dcs3spp commented
/release to release-5.3

2024-05-24 16:03 UTC, dcs3spp commented
/release to release-5.2

2024-05-24 16:15 UTC, dcs3spp commented
/release to release-5.1

2024-05-24 16:22 UTC, dcs3spp commented
/release to release-5