add release notes 5.4
TykTechnologies/tyk-docs-hugo pull request #4662
Opened 2024-05-21 09:12 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description
 
Release notes 5.4.0

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-06-20 10:29 UTC, dcs3spp requested changes
PR LGTM, with following minor suggestions:

- @agata-wit @andyo-tyk @caroltyk  @slega Could you check and update compatibility matrix, 3rd party dependencies and upgrade section in relation to release 5.4.0
- @Eopayemi Could you remove the changed section in the changelog if there no changes logged for this release

2024-06-20 10:29 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
> +#### Compatibility Matrix For Tyk Components
@agata-wit @andyo-tyk @caroltyk @slega I have updated the recommended releases column where possible. Could you update if incorrect and update backwards compatibility column and any 3rd party dependencies for release 5.4?

2024-06-20 10:29 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
> +  - [tyk-charts v1.3]({{< ref "product-stack/tyk-charts/release-notes/version-1.3.md" >}})
@caroltyk this should be Tyk Charts 1.5, yes?

2024-06-20 10:29 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
> +#### Changed
@Eopayemi Are there any changes to document in the changelog? If there are no changes to. document in the release then could you remove the changed section?

2024-06-20 10:29 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
> +We've added the `use_immutable_headers` option to the GraphQL API configuration, offering advanced header transformation capabilities. When enabled, users can add new headers, rewrite existing ones,
@agata-wit have use_immutable_headers, manual schema addition and features object included in API definition been documented?

2024-06-20 14:50 UTC, andyo-tyk commented
> Should Tyk Streams Beta be mentioned?

Tyk Streams Beta is not included in the official 5.4.0, it is still in Tyk Labs

2024-06-21 16:25 UTC, andyo-tyk approved these changes

2024-06-26 22:37 UTC, caroltyk approved these changes
compatibility matrix updated

2024-07-01 09:07 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
> +We've added the `use_immutable_headers` option to the GraphQL API configuration, offering advanced header transformation capabilities. When enabled, users can add new headers, rewrite existing ones,
I'm working on it.

2024-07-01 09:08 UTC, agata-wit approved these changes

2024-07-02 12:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
> +We've added the `use_immutable_headers` option to the GraphQL API configuration, offering advanced header transformation capabilities. When enabled, users can add new headers, rewrite existing ones,
@agata-wit when raise a PR for the feature, remember to include the links in the changelog - updated in the release notes

2024-07-02 12:12 UTC, dcs3spp approved these changes

2024-07-02 12:59 UTC, merged