Dashboard release notes 5.4.0
TykTechnologies/tyk-docs-hugo pull request #4663
Opened 2024-05-21 09:33 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

Dashboard release notes 5.4.0

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-06-20 10:42 UTC, dcs3spp requested changes
PR LGTM, with following minor suggestions:

@agata-wit @andyo-tyk @caroltyk @slega Could you check and update compatibility matrix, 3rd party dependencies and upgrade section in relation to release 5.4.0
@Eopayemi Could you add change log and release highlights

2024-06-25 15:47 UTC, andyo-tyk approved these changes

2024-06-25 15:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
> +Our minor releases are supported until our next minor comes out.
Not sure why, but this is appearing as a title in the preview

2024-06-26 08:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
> +Our minor releases are supported until our next minor comes out.
Thanks @andyo-tyk good spot, I've updated and once preview generated should be fixed

2024-06-26 22:42 UTC, caroltyk approved these changes
table updated

2024-06-26 22:42 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
> +| 5.3.1 | MDCB v2.5.1     | MDCB v2.5.1 |
For Dashboard 5.4, please update to
- MDCB v2.6.0
- Operator 0.18
- Sync 1.5
- Helm chart 1.5
- Pump 1.10

2024-06-26 22:42 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
> +| [PostgreSQL](https://www.postgresql.org/download/)         | 11.x - 15.x LTS        | 11.x - 15.x            | Used by Tyk Dashboard |
PostgreSQL 12.x - 16.x

2024-06-26 22:42 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
> +  - [tyk-charts v1.3]({{< ref "product-stack/tyk-charts/release-notes/version-1.3.md" >}})
```suggestion
  - [tyk-charts v1.5]({{< ref "product-stack/tyk-charts/release-notes/version-1.5.md" >}})
```

2024-07-01 09:05 UTC, agata-wit approved these changes

2024-07-02 12:12 UTC, dcs3spp approved these changes

2024-07-02 13:02 UTC, merged