[DX-1137] Add Missing H1 Headings
TykTechnologies/tyk-docs-hugo pull request #4673
Opened 2024-05-23 16:07 UTC by dcs3spp

### **User description**
### For internal users - Please add a Jira DX PR ticket to the subject!

[DX-1137](https://tyktech.atlassian.net/browse/DX-1137)

---

### Preview & Description

This PR adds missing H1 headers to the following content in docs:

[API Observability](https://deploy-preview-4673--tyk-docs.netlify.app/docs/nightly/api-management/manage-apis/api-operations/api-observability)
[Deploy APIS Overview](https://deploy-preview-4673--tyk-docs.netlify.app/docs/nightly/api-management/manage-apis/deploy-apis/deploy-apis-overview)
[OPA Permissions Example](https://deploy-preview-4673--tyk-docs.netlify.app/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example)

#### Screenshots (if appropriate)
<br>

## Checklist

- [x] I have added a **preview link** to the PR description.
- [x] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [x] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [x] Make sure you have started *your change* off *our latest `master`*.
- [x] I **labelled** the PR

[DX-1137]: https://tyktech.atlassian.net/browse/DX-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
documentation

___

### **Description**
- Added front matter with title, date, description, and tags to `api-observability.md`, `deploy-apis-overview.md`, and `opa-permissions-example.md`.
- Updated headings from H2 to H1 in the mentioned files to ensure proper structure and consistency.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>api-observability.md</strong><dd><code>Add front matter and update headings in API Observability.</code></dd></summary>
<hr>

tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
<li>Added front matter with title, date, description, and tags.<br> <li> Changed H2 headings to H1.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4673/files#diff-e5521b4d957b75b5ff1413fcea788ea10fa510b62bde7747d7f1399d4fc9b6c3">+9/-4</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>deploy-apis-overview.md</strong><dd><code>Add front matter and update headings in Deploy APIs Overview.</code></dd></summary>
<hr>

tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
<li>Added front matter with title, date, description, and tags.<br> <li> Changed H2 headings to H1.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4673/files#diff-244967d18fbda933168bf960d327122e601387828aafe79dfc765a0f7e7a03d0">+16/-12</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>opa-permissions-example.md</strong><dd><code>Add front matter and update heading in OPA Permissions Example.</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
<li>Added front matter with title, date, description, and tags.<br> <li> Changed H2 heading to H1.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4673/files#diff-e23f3bbef860e0a0346951234be14ca2ea0d00650aa3dc8c328dab1191619e82">+6/-3</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

2024-05-24 11:56 UTC, andyo-tyk requested changes, later dismissed

2024-05-24 11:56 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
> +description: "Explains how to configure Open Policy Agent (OPA) rules with additional permissions"
This should be a description of the example - I don't think this page explains how to configure OPA if in fact it's a worked example

2024-05-24 11:56 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
> +tags: [ "Open Policy Agent", "OPA", "additional permissions", "Open Policy Agent permissons" ]
Perhaps a tag to indicate there's a worked example? Might be useful tag to apply to all pages with examples.

2024-05-24 11:56 UTC, andyo-tyk commented on tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
> +tags: [ "API Observability", "Distributed Tracing", "Metrics", "Logs", "Logging", "Open Telemetry", "OTel" ]
These tags seem to be incorrect

2024-05-24 11:56 UTC, andyo-tyk commented on tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
> +title: API Deployment Options
Probably better to use "methods" or something like that, rather than "options"? I don't feel this is quite the right title (or description) but can't think of an alternative right now... :(

2024-05-24 11:56 UTC, andyo-tyk commented on tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
> +description: "Explains how to achieve API observaility through Open Telemetry signals such as traces, metrics and logs"
```suggestion
description: "Explains how to achieve API observability through Open Telemetry signals such as traces, metrics and logs"
```

2024-05-29 10:58 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
> +description: "Explains how to configure Open Policy Agent (OPA) rules with additional permissions"
updated

2024-05-29 10:58 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
> +tags: [ "Open Policy Agent", "OPA", "additional permissions", "Open Policy Agent permissons" ]
updated

2024-05-29 11:02 UTC, dcs3spp commented on tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
> +title: API Deployment Options
updated

2024-05-29 11:03 UTC, dcs3spp commented
Thanks @andyo-tyk I have made requested changes ready for review

2024-05-29 11:04 UTC, dcs3spp commented
@caroltyk Would you be able to review of API Observability changes content in the PR?

2024-05-29 12:16 UTC, dcs3spp commented on tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
> +tags: [ "API Observability", "Distributed Tracing", "Metrics", "Logs", "Logging", "Open Telemetry", "OTel" ]
updated

2024-05-29 13:03 UTC, caroltyk reviewed
LGTM. Just one suggestion on page tags for "Deploy APIs"

2024-05-29 13:03 UTC, caroltyk commented on tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
> +tags: [ "API Deployment", "API", "Deployment", "Deployment Methods" ]
Please also add Tyk Sync and Tyk Operator

2024-06-03 10:50 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
> +tags: [ "API Deployment", "API", "Deployment", "Deployment Methods" ]
@caroltyk you can also add it quickly via the browser

2024-06-03 10:51 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
> +tags: [ "API Deployment", "API", "Deployment", "Deployment Methods" ]
```suggestion
tags: [ "API Deployment", "API", "Deployment", "Deployment Methods", "Tyk Sync", "Tyk Operator" ]
```

2024-06-03 10:54 UTC, letzya commented on tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
> +tags: [ "API Deployment", "API", "Deployment", "Deployment Methods", "Tyk Sync", "Tyk Operator" ]
```suggestion
tags: [ "API Deployment", "API", "Deployment", "Deployment Methods", "Deploy APIs", "Tyk Sync", "Tyk Operator" ]
```

2024-06-03 10:54 UTC, letzya approved these changes

2024-06-03 12:04 UTC, merged

2024-06-03 12:04 UTC, dcs3spp commented
/release to release-5.3

2024-06-03 12:05 UTC, dcs3spp commented
/release to release-5.2