Gateway release notes 5.3.2
TykTechnologies/tyk-docs-hugo pull request #4690
Opened 2024-05-28 09:29 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

Release notes 5.3.2

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-05-29 10:37 UTC, dcs3spp requested changes
PR LGTM. Following needs to be updated before release:

- Release Date
- Compatibility Matrix and 3rd Party Dependencies neede considering if anything needs updated for 5.3.2 release
- Left a comment/query if link to Tyk Charts 1.4 needs to be added in downloads section, instead of Tyk Charts 1.3

2024-05-29 10:37 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +  - [tyk-charts v1.3]({{< ref "product-stack/tyk-charts/release-notes/version-1.3.md" >}})
Should this be Tyk charts 1.4? @caroltyk ?

2024-05-29 10:37 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<!-- Required. Version compatibility with other components in the Tyk stack. This takes the form of a compatibility matrix and is only required for Gateway and Portal.
@andyo-tyk @caroltyk @slega Are there any changes to compatibility matrix required for release 5.3.2?

2024-05-29 10:37 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +| Third Party Dependency                                       | Tested Versions        | Compatible Versions    | Comments |
@andyo-tyk @caroltyk Are there any changes to 3rd party dependencies for release 5.3.2?

2024-06-03 10:00 UTC, dcs3spp reviewed
@elizabeth Thanks for submitting changelog. Remember to remove capitilaisation of words in changelog

2024-06-03 10:00 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Custom Domain Handling Enhancement</summary>
Remove capitalisations for summary headings

2024-06-03 12:14 UTC, dcs3spp approved these changes

2024-06-03 12:16 UTC, dcs3spp commented
@andyo-tyk @agata-wit Ok to release?

2024-06-04 14:34 UTC, agata-wit requested changes, later dismissed

2024-06-04 14:34 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Resolved UDG Nested Field Mapping Issue</summary>
```suggestion
<summary>Resolved Universal Data Graph Nested Field Mapping Issue</summary>
```

2024-06-04 15:26 UTC, andyo-tyk requested changes

2024-06-04 15:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Improved error handling in event handler template tests</summary>
Remove this one

2024-06-04 15:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Addressed an issue where APIs with custom domains weren't prioritised correctly, potentially causing conflicts with APIs lacking custom domains on the same listen path. APIs with custom domain names
```suggestion
Addressed an issue where an API with a custom domain might not be invoked if another API with the same listen path but no custom domain was also deployed on the Gateway. Now APIs with custom domain names are loaded first, so requests will be checked against these first before falling back to APIs without custom domains.
```

2024-06-04 15:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Addressed an issue in service discovery where IP:port returned by Consul wasn't parsed correctly on the Gateway side, leading to errors when proxying requests to the service. The issue primarily occu
```suggestion
Addressed an issue in service discovery where an IP:port returned by Consul wasn't parsed correctly on the Gateway side, leading to errors when proxying requests to the service. The issue primarily occurred with IP:port responses, while valid domain names were unaffected.
```

2024-06-04 15:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Added control for context variables in OAS API definition</summary>
```suggestion
<summary>Added control over access to context variables from middleware when using Tyk OAS APIs</summary>
```

2024-06-04 15:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +Introduced control over context variables in OAS API Definitions, allowing users to enable or disable access to context variables in middleware and plugins.
```suggestion
Addressed a potential issue when working with Tyk OAS APIs where request context variables are automatically made available to relevant Tyk and custom middleware. We have introduced a control in the Tyk OAS API definition to disable this access if required.
```

2024-06-04 15:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Custom domain handling enhancement</summary>
```suggestion
<summary>APIs with common listen paths but different custom domains</summary>
```

2024-06-04 16:12 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +| Third Party Dependency                                       | Tested Versions        | Compatible Versions    | Comments |
Not from a Core perspective - this is a bug fix release.

2024-06-04 16:12 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<!-- Required. Version compatibility with other components in the Tyk stack. This takes the form of a compatibility matrix and is only required for Gateway and Portal.
N/A for Core

2024-06-04 16:13 UTC, andyo-tyk approved these changes
Thanks for making the changes. 👍

2024-06-05 09:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<!-- Required. Version compatibility with other components in the Tyk stack. This takes the form of a compatibility matrix and is only required for Gateway and Portal.
none from platform

2024-06-05 09:35 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +| Third Party Dependency                                       | Tested Versions        | Compatible Versions    | Comments |
No changes

2024-06-05 09:39 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +  - [tyk-charts v1.3]({{< ref "product-stack/tyk-charts/release-notes/version-1.3.md" >}})
updated

2024-06-05 09:43 UTC, caroltyk approved these changes

2024-06-05 15:51 UTC, merged

2024-06-05 15:52 UTC, dcs3spp commented
/release to release-5.3