[DX-1382] Dashboard release notes 5.3.2
TykTechnologies/tyk-docs-hugo pull request #4697
Opened 2024-05-29 13:59 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

Release notes 5.3.2

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-05-29 14:22 UTC, dcs3spp requested changes
PR LGTM, with the following suggestions
- Update release date
- Add any updates to compatibility matrix and dependencies tables for 5.3.2

2024-05-29 14:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +### Release Date xxx
Remember to update release date

2024-05-29 14:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.2 | MDCB v2.5.1     | MDCB v2.5.1 |
@andyo-tyk @caroltyk does anything need updating for the compatibility matrix for 5.3.2?

2024-05-29 14:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| Third Party Dependency                                     | Tested Versions        | Compatible Versions    | Comments |
@andyo-tyk @caroltyk does anything need updating for the 3rd party dependencies for 5.3.2?

2024-05-29 14:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + - [tyk-charts v1.3]({{< ref "product-stack/tyk-charts/release-notes/version-1.3.md" >}})
@carol should this link to Tyk Charts 1.4 for 5.3.2?

2024-06-03 10:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Resolved PostgreSQL Dashboard Analytics Issue</summary>
```suggestion
<summary>Resolved PostgreSQL Dashboard Analytics issue</summary>
```

2024-06-03 10:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Fixed Dashboard analytics for PostgreSQL</summary>
```suggestion
<summary>Fixed Dashboard Analytics for PostgreSQL</summary>
```

2024-06-03 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Improved Labelling on OAS UI Mock Response Middleware Screen</summary>
```suggestion
<summary>Improved Labelling on OAS UI Mock Response Middleware screen</summary>
```

2024-06-03 10:04 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Enhanced Dashboard UI Language</summary>
```suggestion
<summary>Enhanced Dashboard UI language</summary>
```

2024-06-03 10:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Improved Labelling on OAS UI Mock Response Middleware screen</summary>
```suggestion
<summary>Improved labelling on OAS UI Mock Response Middleware screen</summary>
```

2024-06-03 10:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Enhanced Password Reset Security</summary>
```suggestion
<summary>Enhanced Password Reset security</summary>
```

2024-06-03 10:09 UTC, dcs3spp approved these changes
Thanks @Eopayemi PR LGTM!

@agata-wit @andyo-tyk @caroltyk could you peer review ready for release

2024-06-04 14:36 UTC, agata-wit requested changes, later dismissed

2024-06-04 14:36 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Fixed UDG Schema Editor Import Issue</summary>
```suggestion
<summary>Fixed Universal Data Graph Schema Editor Import Issue</summary>
```

2024-06-04 15:50 UTC, andyo-tyk requested changes

2024-06-04 15:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Enhanced Dashboard UI language</summary>
I think this should go in Fixed

2024-06-04 15:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Improved labelling on OAS UI Mock Response Middleware screen</summary>
Delete this

2024-06-04 15:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +Modified default OPA rules to prevent unauthorised admins from modifying other admins' passwords, mitigating potential 'rogue admin' behaviour. Tyk Dashboard clients using OPA rules should update the
```suggestion
Modified default OPA rules to prevent unauthorised admins from modifying other admins' passwords, mitigating potential 'rogue admin' behaviour. Tyk Dashboard clients using custom OPA rules should update their rule set accordingly. Contact your assigned Tyk representative for assistance.
```

2024-06-04 16:13 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.2 | MDCB v2.5.1     | MDCB v2.5.1 |
N/A for Core

2024-06-04 16:13 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| Third Party Dependency                                     | Tested Versions        | Compatible Versions    | Comments |
N/A for Core

2024-06-04 16:14 UTC, andyo-tyk approved these changes
Thanks, looks good to me. 👍

2024-06-05 09:42 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| 5.3.2 | MDCB v2.5.1     | MDCB v2.5.1 |
updated helm chart version

2024-06-05 09:43 UTC, caroltyk approved these changes

2024-06-05 15:55 UTC, merged

2024-06-05 15:56 UTC, dcs3spp commented
/release to release-5.3