Add new regexp settings to tyk.conf
TykTechnologies/tyk-docs-hugo pull request #470
Opened 2018-06-26 09:07 UTC by marksou

2018-06-27 17:49 UTC, dencoded commented on tyk-docs/content/configure/tyk-gateway-configuration-options.md
> +If you set `disable_regexp_cache` to true, you can use this setting to limit how long the regular expression cache is kept for in seconds. The default is `60` seconds. This must be a positive value.
looks like a typo:
If you set `disable_regexp_cache` **to false**

2018-06-27 17:50 UTC, dencoded requested changes
left one comment in section for `regexp_cache_expire`

2018-06-28 07:50 UTC, marksou commented
Changed `true` to `false`

2018-06-28 18:48 UTC, dencoded approved these changes

2018-07-04 11:32 UTC, merged