[DX-1395] Tyk Streaming Docs
TykTechnologies/tyk-docs-hugo pull request #4706
Opened 2024-05-31 13:23 UTC by dcs3spp

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1395](https://tyktech.atlassian.net/browse/DX-1395)

---

### Preview Link

[preview - to add]()

### Description

Docs for Tyk Streaming

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-05-31 15:36 UTC, letzya commented on tyk-docs/data/menu.yaml
> +    - title: "Event Streaming"
```suggestion
    - title: "Tyk Streams"
```

2024-06-03 21:24 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/overview.md
> +title: Overview
```suggestion
title: Tyk Streams
```

2024-06-04 11:17 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +  inputs:
```suggestion
```

2024-06-05 11:21 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/overview.md
> +
```suggestion
We are excited to introduce our new product, *Tyk Streams*! 
```

2024-06-05 11:22 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/overview.md
> +Tyk Streams is a powerful new feature in the Tyk API Management platform that enables organisations to securely expose, manage and monetise real-time event streams and asynchronous APIs. With Tyk Str
```suggestion
*Tyk Streams* is a powerful new feature in the Tyk API management platform that enables organisations to securely expose, manage and monetise real-time event streams and asynchronous APIs. With *Tyk Streams*, you can easily connect to various event brokers and streaming platforms, such as Apache Kafka, MQTT, AMQP etc. and expose them as managed API endpoints to internal and external consumers.
```

2024-06-05 11:23 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/overview.md
> +Tyk Streams is a powerful new feature in the Tyk API Management platform that enables organisations to securely expose, manage and monetise real-time event streams and asynchronous APIs. With Tyk Str
```suggestion
*Tyk Streams* currently in beta stage, is a powerful new feature in the Tyk API Management platform that enables organisations to securely expose, manage and monetise real-time event streams and asynchronous APIs. With Tyk Streams, you can easily connect to various event brokers and streaming platforms, such as Apache Kafka, MQTT, AMQP etc. and expose them as managed API endpoints to internal and external consumers.
```

2024-06-05 13:15 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +Once the demo has downloaded, checkout the stream branch by issuing the following command:
```suggestion
Once the repo has downloaded, checkout the `stream` branch by issuing the following command:
```

2024-06-05 15:04 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +- When prompted enter your Tyk license key. Login credentials will then be provided in the console output.
```suggestion
```

2024-06-05 15:06 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +```text
```suggestion
```env
```

2024-06-05 15:09 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +In the Tyk Dashboard, create a new API and select the *Open API* option.
```suggestion
In the Tyk Dashboard, create a new API. We'll the *Open API* option which is already selected by default. Click the *+CONFIGURE API* button to continue.
```

2024-06-05 15:15 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +This guide will walk you through setting up Tyk Streams and configuring your first async API.
```suggestion
In this guide, you'll learn how to set up Tyk Streams and configure your first asynchronous API. By the end of this guide, you will have a fully functional API that allows you to subscribe to a WebSocket and see the messages you post to Tyk (REST) in real-time.

Let's get started and unlock the power of Tyk for your asynchronous API needs!

```

2024-06-05 15:17 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +Subscribe to the WebSocket using wscat:
```suggestion
1. Subscribe to the WebSocket using wscat:
```

2024-06-05 15:17 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +Post a message to the `/post` endpoint using curl:
```suggestion
2. Post a message to the `/post` endpoint using curl:
```

2024-06-05 15:18 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +Verify that the message posted in step 1 is received in the *wscat* terminal.
```suggestion
3. Verify that the message posted in step 1 is received in the *wscat* terminal.
```

2024-06-05 15:21 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +- Ensure all Docker containers are running correctly
```suggestion
- Ensure all Docker containers are running correctly
- In case you used this repo before, ensure all Docker images are as defined in the [example env]({{< ref "#post-download" >}}) above.
```

2024-06-05 15:22 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +- Check the Tyk Gateway logs for any error messages
```suggestion
- Check the Tyk Gateway logs for any error messages. Most of the time it'll be syntax errors in the stream configuration.
```

2024-06-05 16:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +In the Tyk Dashboard, create a new API and select the *Open API* option.
I am not sure if `We'll the *Open API* option which is already selected by default.` reads correctly.

If OpenAPI is selected by default is it ok to remove theat sentence and have it like this?

```suggestion
In the Tyk Dashboard, create a new API. Click the *+CONFIGURE API* button to continue.
```

2024-06-05 18:26 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +### Post Download
```suggestion
### Configure the installation
```

2024-06-05 18:28 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +Tyk Streams is currently an [Early Access]({{< ref "frequently-asked-questions/using-early-access-features" >}}) feature. If a crash or an issue is encountered then Tyk Gateway can be restarted and t
```suggestion
Tyk Streams is currently in [Lab release ]({{< ref "frequently-asked-questions/dddd" >}}) feature. If a crash or an issue is encountered then Tyk Gateway can be restarted and the logs can be inspected as follows:
```

2024-06-05 18:36 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/deployment-considerations.md
> +Under the hood, Tyk Streams utilises Redis Streams for efficient and reliable message distribution within the Tyk Gateway cluster. This enables:
```suggestion
Under the hood, Tyk Streams utilises [Redis Streams](https://redis.io/docs/latest/develop/data-types/streams/) for efficient and reliable message distribution within the Tyk Gateway cluster. This enables:
```

2024-06-05 18:40 UTC, letzya commented on tyk-docs/content/api-management/async-apis/use-cases.md
> +## Security
@dcs3spp this is not use case, it's a capability

2024-06-05 18:42 UTC, letzya requested changes
fix the use case

2024-06-06 15:16 UTC, letzya commented on tyk-docs/data/menu.yaml
> +      - title: "Use Cases"
```suggestion
      - title: "Capabilities"
```

2024-06-07 09:10 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
> +<Tabs defaultValue="Path Switching" values={[
```suggestion
```

2024-06-07 09:10 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
> +{ label: 'Path Switching', value: 'Path Switching', },
```suggestion
```

2024-06-07 09:10 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
> +{ label: 'Mock OAuth 2.0 Server', value: 'Mock OAuth 2.0 Server', },
```suggestion
```

2024-06-07 09:10 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
> +]}>
```suggestion
```

2024-06-07 11:02 UTC, davegarvey commented on tyk-docs/content/product-stack/tyk-streaming/getting-started.md
> +
```suggestion
**Note**: For this example, the *Upstream URL* will not be used, as the streaming server will handle the requests and responses directly. However, a value is still needed to comply with the API definition schema.
```

2024-06-07 14:00 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/overview.md
> +*Tyk Streams* is currently in the *Lab Release* phase. It is under active development and testing, and is not intended for production use. For more details and to provide your feedback, please visit
```suggestion
*Tyk Streams* is currently in the *Lab Release* phase. It is under active development and testing, and is not intended for production use. For more details and to provide your feedback, please visit our [Lab Release Information Page]({{< ref "developer-support/special-releases-and-features/lab-releases" >}}).

```

2024-06-07 14:10 UTC, letzya commented on tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
> +Please note tha components within a Benthos config will register their respective endpoints in a non-deterministic order. This means that establishing precedence of endpoints that are registered via
```suggestion
Please note that components within a Benthos config will register their respective endpoints in a non-deterministic order. This means that establishing precedence of endpoints that are registered via multiple `http_server` inputs or outputs (either within brokers or from cohabiting streams) is not possible in a predictable way.
```

2024-06-07 14:48 UTC, dcs3spp commented
DX releasing Tyk streams via force push

2024-06-07 14:48 UTC, merged

2024-06-07 14:48 UTC, dcs3spp commented
/release to release-5.3