Restructured SSO pages to improve clarity
TykTechnologies/tyk-docs-hugo pull request #4736
Opened 2024-06-07 10:15 UTC by andyo-tyk

### Preview Link

### Description
Restructured the SSO / 3rd Party IdP integration pages to make them easier to find and work with.

2024-06-07 10:59 UTC, andyo-tyk reviewed
Add precision for Tyk Classic Developer Portal

2024-06-07 10:59 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +Tyk Identity Broker can act as the go-between for the Tyk Dashboard and Portal and a third party identity provider. Tyk Identity broker can also interpret and pass along information about the user wh
```suggestion
Tyk Identity Broker can act as the go-between for the Tyk Dashboard and Tyk Classic Developer Portal and a third party identity provider. Tyk Identity broker can also interpret and pass along information about the user who is logging in such as Name, Email and group or role metadata for enforcing role based access control in the Tyk Dashboard.
```

2024-06-07 10:59 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +This makes use of the [Tyk Identity Broker]({{< ref "tyk-identity-broker" >}}) (TIB) which provides a service-level component that enables delegated identities to be authorised and provide authentica
```suggestion
This makes use of the [Tyk Identity Broker]({{< ref "tyk-identity-broker" >}}) (TIB) which provides a service-level component that enables delegated identities to be authorised and provide authenticated access to various Tyk components such as the Tyk Dashboard, the [Tyk Classic Developer Portal]({{< ref "tyk-developer-portal/tyk-portal-classic" >}}) and Tyk Gateway API.
```

2024-06-07 10:59 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +SAML authentication is a way for a service provider, such as the Tyk Dashboard or Portal, to assert the Identity of a User via a third party.
```suggestion
SAML authentication is a way for a service provider, such as the Tyk Dashboard or Tyk Classic Developer Portal, to assert the Identity of a User via a third party.
```

2024-06-07 11:11 UTC, OldStubbsy approved these changes
A huge improvement!

2024-06-10 21:07 UTC, sredxny commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +4. Set the `Callback URL` generated by Tyk on your IdP
if this is specific for `open-id` then worth to let the user know that they need to add `openid` and `email` in the scopes if they want to pull the user information? (so we can check if the user already exists in the dashboard, display the correct name etc)

2024-06-10 21:07 UTC, sredxny commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +[Tyk Identity Broker]({{< ref "tyk-identity-broker" >}}) is an open-source project that can be used to integrate Tyk Dashboard and Classic Portal with 3rd party identity providers (IDPs). TIB has bee
`no configuration is required and it is readily available for use.` is not 100% accurate, even tought it's simpler now anyway customers need to ensure that TIB is enabled in the configs: `identity_broker.enabled`

2024-06-10 21:07 UTC, sredxny commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +## How SSO works with Tyk Dashboard
I think we must mention that sso must be enabled for the organisation, we enable this in the database and set `sso_enabled:true` for the given org

2024-06-10 21:07 UTC, sredxny commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +You may not want all SSO users to assume administrator rights to your Tyk Dashboard, so you can configure alternative [default permissions](#setting-default-sso-permissions) that will be inherited in
also, you can limit that only registered users (in the dashboard database) can use and perform the authentication flow with a profile by setting `SSOOnlyForRegisteredUsers:true`, this only works for sso into the dashboard, not classic portal.

2024-06-10 21:07 UTC, sredxny commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +You may not want all SSO users to assume administrator rights to your Tyk Dashboard, so you can configure alternative [default permissions](#setting-default-sso-permissions) that will be inherited in
so, if someone doesn't exists in the dashboard database but they logged in successfully into the idp anyway the dashboard will deny the access

2024-06-10 21:07 UTC, sredxny commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +## SSO user permissions
maybe here is a good place to talk about user groups mapping? and `custom_user_group_field`?

2024-06-11 07:35 UTC, carlostyk commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +4. Set the `Callback URL` generated by Tyk on your IdP
@sredxny @andyo-tyk This is a very good point - I was not aware of this since in the UI the scopes are placed as optional and I was getting a generic email and not the one from the user I was logging in with.

2024-06-11 08:06 UTC, carlostyk submitted a review, later dismissed
I would add some raw schema examples. I was not aware of some of the configurations like the scopes ones as those were optional. @sredxny share one with me that was pretty interesting. 

I haven't been using a lot SSO so I am not able to give much feedback on missing things like the ones shared by @sredxny. 

I can say that the information looks much better. 

We also just found out some feedback from Dentsply brought by Ataimo that they were missing SAML configuration steps apart from the video that we have.

2024-06-11 08:08 UTC, carlostyk reviewed
I would add some raw schema examples. I was not aware of some of the configurations like the scopes ones as those were optional. @sredxny share one with me that was pretty interesting. 

I haven't been using a lot SSO so I am not able to give much feedback on missing things like the ones shared by @sredxny. 

I can say that the information looks much better. 

We also just found out some feedback that we are missing SAML configuration steps apart from the video that we have.

2024-06-11 08:20 UTC, letzya commented
@andyo-tyk looks like there are lots of unresolved conversations (haven't checked them TBH), please let us know when it's ready for a DX review. We might not have time to accommodate it today but please let us know if it's an urgent matter.

2024-06-12 19:29 UTC, JRWu requested changes
Content looks good, requesting minor changes.

2024-06-12 19:29 UTC, JRWu commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +`SAMLBaseURL` - The host of TIB that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IDP. The redirects configured
Nitpicking here but IDP has been referenced as IdP in other documents, might be best to just replace IDP with IdP

2024-06-12 19:29 UTC, JRWu commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +This makes use of the [Tyk Identity Broker]({{< ref "tyk-identity-broker" >}}) (TIB) which provides a service-level component that enables delegated identities to be authorised and provide authentica
Does this statement imply that TIB can be used to provide identity management for the Tyk-Gateway API specifically? Should we clarify the ambiguity here

2024-06-12 19:29 UTC, JRWu commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +`SAMLForenameClaim` - Key for looking up the forename claim in the SAML assertion form the IDP. Defaults to: `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/forename`
These schemas seem to reference broken links on xmlsoap

2024-06-12 19:29 UTC, JRWu commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +`SAMLEmailClaim` - Key for looking up the email claim in the SAML assertion form the IDP. Defaults to: `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress`
These schemas seem to reference broken links on xmlsoap

2024-06-12 19:29 UTC, JRWu commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +`SAMLSurnameClaim` - Key for looking up the surname claim in the SAML assertion form the IDP. Defaults to: `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname`
These schemas seem to reference broken links on xmlsoap

2024-06-14 15:38 UTC, dcs3spp requested changes
PR LGTM, I have made minor suggestions and where possible committed them to the PR. Once peer approval given will merge and release

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +This makes use of the [Tyk Identity Broker]({{< ref "tyk-identity-broker" >}}) (TIB) which provides a service-level component that enables delegated identities to be authorised and provide authentica
Is there an external an internal TIB component and should it be mentioned here?

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +Tyk Identity Broker can act as the go-between for the Tyk Dashboard and Tyk Classic Developer Portal and a third party identity provider. Tyk Identity broker can also interpret and pass along informa
```suggestion
Tyk Identity Broker can act as the go-between for the Tyk Dashboard and Tyk Classic Developer Portal and a third party identity provider. Tyk Identity broker can also interpret and provide information about the user who is logging in such as Name, Email and group or role metadata for enforcing role based access control in the Tyk Dashboard.
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +`SAMLBaseURL` - The host of TIB that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IDP. The redirects configured
```suggestion
`SAMLBaseURL` - The Tyk Identity Broker host that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IdP. The redirects configured in the IdP must match the expected host and URI configured in the metadata document made available by Tyk Identity Broker.
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +`FailureRedirect` - Where to redirect failed login requests.
Is this a URL?

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +`IDPMetaDataURL` - The metadata URL of your IDP which will provide Tyk Identity Broker with information about the IDP such as EntityID, Endpoints (Single Sign On Service Endpoint, Single Logout Servi
```suggestion
`IDPMetaDataURL` - The metadata URL of your IDP which will provide Tyk Identity Broker with information such as EntityID, Endpoints (Single Sign On Service Endpoint, Single Logout Service Endpoint), its public X.509 cert, NameId Format, Organisation info and Contact info.
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +`CertLocation`: An X.509 certificate and the private key for signing your requests to the IDP, this should be one single file with the cert and key concatenated. When using internal identity broker,
```suggestion
`CertLocation`: An X.509 certificate and the private key for signing your requests to the IDP, this should be one single file with the cert and key concatenated. When using the internal Identity Broker, this value should be the ID of the certificate uploaded via the certificate manager in Tyk Dashboard. Alternatively, it should be the absolute path of the certificate in the file system of Tyk Gateway.
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +```
```suggestion
```json
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +We have a video that walks you through getting Tyk Dashboard SSO Access via SAML using Microsoft Azure as IDP and our internal Dashboard TIB.
```suggestion
We have a video that explains how to provide Tyk Dashboard SSO Access via SAML using Microsoft Azure as an IDP and our internal Dashboard TIB.
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/ldap.md
> +This is an example of a TIB profile could be used to log a user into the Dashboard using an LDAP pass-through provider:
```suggestion
This is an example of a TIB profile that could be used to log a user into the Dashboard using an LDAP pass-through provider:
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/ldap.md
> +To perform and advanced LDAP search, you need to specify three additional attributes in the profile configuration file:
```suggestion
To perform an advanced LDAP search, you need to specify three additional attributes in the profile configuration file:
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/ldap.md
> +```.json
```suggestion
```json
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/ldap.md
> +```.json
```suggestion
```json
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/social.md
> +In short, all you need to do is as follow:
```suggestion
Follow the steps below to configure your social IdP in Tyk Dashboard:
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/social.md
> +3. Get the `client_id` + `secret` that are defined on your IdP
```suggestion
3. Retrieve the `client_id` and `secret` defined on your IdP
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/social.md
> +7. More documentation of the flow can be found on our [GitHub TIB repo README](https://github.com/TykTechnologies/tyk-identity-broker)
```suggestion
7. Further documentation of the flow can be found on our [GitHub TIB repo README](https://github.com/TykTechnologies/tyk-identity-broker)
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +[OpenID Connect]({{< ref "basic-config-and-security/security/authentication-authorization/openid-connect" >}}) (OIDC) and Security Assertion Markup Language (SAML) enable an application (such as Tyk
```suggestion
[OpenID Connect]({{< ref "basic-config-and-security/security/authentication-authorization/openid-connect" >}}) (OIDC) and Security Assertion Markup Language (SAML) enables an application (such as Tyk Dashboard) to verify the identity of users without having to manage usernames and passwords locally, by offloading the identification process and secure storage of user credentials to a dedicated Identity Provider (IdP). The Authorisation server of the IdP identifies the users for a pre-registered and approved application (`client` in OAuth and OIDC terminology).
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +TIB allows you to implement single sign-on and use of your existing user directory for login to the Tyk products.It has been designed as a glue-code solution, so it can integrate with almost any IdP.
Not sure whether the sentence reads ok, should it be:

```suggestion
TIB allows you to implement single sign-on and use your existing user directory for login to the Tyk products. It has been designed as a glue-code solution, so it can integrate with almost any IdP.
```

2024-06-14 15:38 UTC, dcs3spp commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +```.http
```suggestion
```http
```

2024-06-17 08:15 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
> +`SAMLBaseURL` - The host of TIB that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IDP. The redirects configured
Simon has resolved this.

2024-06-17 08:18 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +[OpenID Connect]({{< ref "basic-config-and-security/security/authentication-authorization/openid-connect" >}}) (OIDC) and Security Assertion Markup Language (SAML) enable an application (such as Tyk
@dcs3spp I think "enable" should be singular, not plural, as (to the best of my knowledge - but I'm no expert) they are used separately, i.e. each of OIDC and SAML can enable Tyk Dashboard to verify the identity of users. They don't have to be used together (which would lead to pluralisation of "enable").

2024-06-17 08:19 UTC, andyo-tyk commented on tyk-docs/content/advanced-configuration/integrate/sso.md
> +TIB allows you to implement single sign-on and use of your existing user directory for login to the Tyk products.It has been designed as a glue-code solution, so it can integrate with almost any IdP.
Makes sense to me - note that this PR is largely a restructuring, not rewrite, so I didn't touch the bulk of the content.

2024-08-02 09:37 UTC, letzya commented on tyk-docs/content/advanced-configuration/integrate.md
> +In this section we provide examples that use the [Tyk Identity Broker]({{< ref "tyk-identity-broker" >}}) component embedded in the Tyk Dashboard, to integrate with common Identity Providers to offer
@dcs3spp would we be good to explain what sso means or do we have it somewhere else and I missed it?

2024-08-02 09:39 UTC, letzya commented on tyk-docs/content/advanced-configuration/integrate.md
> +In this section we provide examples that use the [Tyk Identity Broker]({{< ref "tyk-identity-broker" >}}) component embedded in the Tyk Dashboard, to integrate with common Identity Providers to offer
Also we put it under the planning phase but it's not really clear why. We should explain what is the JTBD and how it's part of the planning phase. (could be in a separate PR but it's needed as when one read it it's not trivial to connect the dots.

2024-10-14 12:32 UTC, letzya commented
@andyo-tyk will you have time to go through Sredny's @sredxny  suggestions? this is very old and has conflicts now

2025-03-04 14:00 UTC, letzya commented
@andyo-tyk  Closing: it can’t be used as is since we have updated the structure. Could you please take the content and create a new pr?

2025-03-04 14:00 UTC, closed without merging