DX-1404 TT-12126 Tyk Charts 1.5 Release notes [Requires release date to be added before merging]
TykTechnologies/tyk-docs-hugo pull request #4760
Opened 2024-06-10 12:56 UTC by caroltyk

### **User description**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

[DX-1404](https://tyktech.atlassian.net/browse/DX-1404)

---

### Preview Link

[preview](https://deploy-preview-4760--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-charts/release-notes/version-1.5)

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

[DX-1404]: https://tyktech.atlassian.net/browse/DX-1404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
Documentation

___

### **Description**
- Added comprehensive release notes for Tyk Charts version 1.5, including breaking changes, deprecations, upgrade instructions, and release highlights.
- Documented new features such as fixed window rate limiter, init containers resources parameters, SSL configurations for MDCB HTTP server, and more.
- Fixed issues related to Dashboard log display, Gateway control port, and Developer Portal bootstrapping.
- Updated the menu to include a link to the Tyk Charts 1.5 release notes.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>version-1.5.md</strong><dd><code>Add Tyk Charts 1.5 release notes with detailed changelog</code>&nbsp; </dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md

<li>Added release notes for Tyk Charts version 1.5.<br> <li> Documented breaking changes, deprecations, upgrade instructions, and <br>release highlights.<br> <li> Included changelog with added features and fixed issues.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4760/files#diff-d93618cb60360981d4cdf8496293eefa2d8a655cd105a2cf975ebb070c1cc178">+385/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>menu.yaml</strong><dd><code>Update menu to include Tyk Charts 1.5 release notes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/data/menu.yaml

- Added menu entry for Tyk Charts 1.5 release notes.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4760/files#diff-a6789c66bfa0660f7fdbe4796002ab4777677bae59a0276689c840100ff0b0b2">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

2024-06-11 09:33 UTC, dcs3spp requested changes
PR LGTM @caroltyk I have made minor suggestions. Is this to be released as part of 5.4.0 and if so could you add a label to indicate release target

2024-06-11 09:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +##### Release Date -- TBD
Remember to add release date

2024-06-11 09:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +| 5.3 LTS | Helm v2.2     | Helm vX - vY |
Do we need to add 5.4 to this table if Tyk Charts 1.5 is going to be released with Tyk 5.4.0?

2024-06-11 09:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +##### MDCB: Deprecated Healthcheck Port and added HTTP Port
```suggestion
##### MDCB: Deprecated healthcheck_port and replaced with http_port
```

2024-06-11 09:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +###### Changes in MDCB v2.6.0:
Remove the Changes in MDCB v2.6.0 section heading and first 2 bullet points, since it duplicates content in the introductory sentence. Then integrate the helm chart update details with the inroductary content.

2024-06-11 09:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +  - /health - Provides the health status of MDCB.
italicise the endpoints

2024-06-11 09:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +Starting with MDCB v2.6.0, the configuration parameter `http_port` has been introduced to replace the original `healthcheck_port`. This new HTTP port is designed to expose various endpoints for monit
Has the healthcheck_port being removed? If it has not maybe add an explanation of when it will be removed and no longer supported here.

2024-06-11 09:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +This feature allows users to enable fixed window rate limiting in the Gateway. The fixed window rate limiting feature permits requests up to the configured rate limit within a specified time window,
replace limiting with limiter

2024-06-11 09:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +##### Changed
Remove changed section if there are no changelog entries for this section

2024-06-12 10:54 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +| 5.3 LTS | Helm v2.2     | Helm vX - vY |
This part is commented. Compatibility table is only present in the GW/Dashboard release notes.

2024-06-12 10:56 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +Starting with MDCB v2.6.0, the configuration parameter `http_port` has been introduced to replace the original `healthcheck_port`. This new HTTP port is designed to expose various endpoints for monit
healthcheck_port will not be removed to support people using the old version of MDCB.

2024-06-14 07:57 UTC, komalsukhani requested changes

2024-06-14 07:57 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +Starting with MDCB v2.6.0, the configuration parameter `http_port` has been introduced to replace the original `healthcheck_port`. This new HTTP port is designed to expose various endpoints for monit
I have updated PR such that `healthcheckPort` takes precedence over `httpPort`. Changed this to avoid backward incompatibility.
```suggestion
Starting with MDCB v2.6.0, the configuration parameter `http_port` has been introduced to replace the original `healthcheck_port`. This new HTTP port is designed to expose various endpoints for monitoring and debugging MDCB. For consistency and future compatibility, it is recommended to use `mdcb.probes.httpPort`.
```

2024-06-14 07:57 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +With PostgreSQL v11 reaching [EOL](https://www.postgresql.org/support/versioning/) in November 2023, we can no longer guarantee full compatibility with this version of the database. If you are [using
```suggestion
With PostgreSQL v11 has reach [EOL](https://www.postgresql.org/support/versioning/) on November 2023, we can no longer guarantee full compatibility with this version of the database. If you are [using PostgreSQL]({{<ref "planning-for-production/database-settings/postgresql">}}) we recommend that you upgrade to a version that we have tested with, as indicated below.
```

2024-06-14 07:57 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +This fix addresses a misconfiguration in the Dashboard chart that was causing the Log Browser not showing API activity logs for users utilizing Mongo Pump. The default configuration `dashboard.useSha
```suggestion
This fix addresses a misconfiguration in the Dashboard chart that was causing the Log Browser not showing API activity logs for users utilizing Mongo Pump. The default configuration `dashboard.useShardedAnalytics` is now set to `true`, ensuring proper log visibility. Users who use Mongo Pump will now be able to view the API activity log as expected. Additionally, the correct Dashboard environment variable `TYK_DB_USESHARDEDANLAYTICS` is now set using `dashboard.useShardedAnalytics`. This enhancement ensures accurate log visibility and improves the overall user experience with the Dashboard by properly configuring sharded analytics.
```

2024-06-17 16:41 UTC, dcs3spp commented
@caroltyk @komalsukhani Are there any changes to add in the changes section of the changelog for Tyk Charts 1.5? If not can the changes section of the release notes be removed?

2024-06-18 07:46 UTC, caroltyk commented
> @caroltyk @komalsukhani Are there any changes to add in the changes section of the changelog for Tyk Charts 1.5? If not can the changes section of the release notes be removed?

Changes section removed

2024-06-18 09:18 UTC, dcs3spp approved these changes

2024-06-18 09:19 UTC, dcs3spp commented
@caroltyk I have approved PR. Once a confirmed release date has been added to release notes will merge and release

2024-06-27 06:22 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +We have fixed this issue by not passing required org ID and API key as command option during portal startup. The dev portal is configured after Pod creation via Dev Portal API. Please note now users
I want to check what happens to dev portal if I upgrade. Will it delete my provider.
I will ask Ola to check and post an update here.

2024-06-27 08:01 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
> +We have fixed this issue by not passing required org ID and API key as command option during portal startup. The dev portal is configured after Pod creation via Dev Portal API. Please note now users
We can remove that bit related to Providers now.

2024-07-01 10:11 UTC, komalsukhani approved these changes

2024-07-01 10:46 UTC, merged

2024-07-03 15:19 UTC, brunosabenca commented
Is it normal for the release notes to be merged before the new version is made available?

As far as I can tell, the latest version currently available is 1.4.0 

I had already started the process of upgrading to the latest version when I realised this :face_with_diagonal_mouth:

2024-07-03 16:42 UTC, dcs3spp commented
Thanks @brunosabenca have updated merged Chart release notes to announce releasing soon.