[TT-12266] Add Rate Limit Smoothing Docs (5.4.0)
TykTechnologies/tyk-docs-hugo pull request #4771
Opened 2024-06-10 19:51 UTC by titpetric

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

- Updates rate limiter docs with rate limit smoothing
- Updates key and policy creation examples documenting the value

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-06-11 09:28 UTC, jeffy-mathew approved these changes

2024-06-11 09:39 UTC, letzya commented on tyk-docs/content/getting-started/create-api-key.md
> -description: "Creating an API access key using Tyk"
@titpetric any reason for deleting the description?

2024-06-11 09:40 UTC, letzya commented on tyk-docs/content/getting-started/create-api-key.md
> +```
```suggestion
```curl
```

2024-06-11 09:42 UTC, letzya commented on tyk-docs/content/getting-started/create-api-key.md
> +    "smoothing": {
@titpetric this comment is important! you only added for open source tab, was that your intention?

2024-06-11 09:50 UTC, titpetric commented on tyk-docs/content/getting-started/create-api-key.md
> +    "smoothing": {
It was, but we could expand scope if there are more reasonable suggestions? The creating a key and creating a policy pages are central to the new config, but we may also decrease scope and just consider the rate limiting page.

2024-06-11 09:58 UTC, titpetric commented on tyk-docs/content/getting-started/create-api-key.md
> -description: "Creating an API access key using Tyk"
Nice catch, this was something between human error and automation error. Re-added description, menu, weight.

2024-06-11 11:52 UTC, andrei-tyk approved these changes

2024-06-14 11:47 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +To see how to configure the value on keys or policies:
```suggestion
Please consult the following guides for an explanation of how to configure the value on keys or policies:
```

2024-06-14 11:53 UTC, dcs3spp requested changes
@titpetric PRLGTM I have made some minor suggestions. Why the additional spacing in front matter for aliases?

2024-06-14 11:53 UTC, dcs3spp commented on tyk-docs/content/getting-started/create-security-policy.md
> +    - /getting-started/installation/tutorials/create-security-policy/
@titpetric Why the spacing added?

2024-06-14 11:53 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +  a RateLimitSmoothingUp event is emitted and allowance increases by `step`.
```suggestion
  a *RateLimitSmoothingUp* event is emitted and allowance increases by `step`.
```

2024-06-14 11:53 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +  a RateLimitSmoothingDown event is emitted and allowance decreases by `step`.
```suggestion
  a *RateLimitSmoothingDown* event is emitted and allowance decreases by `step`.
```

2024-06-14 12:13 UTC, dcs3spp commented on tyk-docs/content/getting-started/create-security-policy.md
> +    "smoothing": {
This does not render correctly in preview, with the `:` highlighted

2024-06-14 12:15 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +```json
```suggestion
```yaml
```

2024-06-14 13:19 UTC, dcs3spp commented
@titpetric Is there rate limiting content that needs to be added to Self Managed and Cloud tabs for [create security policies](https://deploy-preview-4771--tyk-docs.netlify.app/docs/nightly/getting-started/create-security-policy/) and [access api keys](http://localhost:1313/docs/nightly/getting-started/create-api-key/)?

2024-06-14 13:21 UTC, letzya commented on tyk-docs/content/getting-started/create-api-key.md
> +    - /with-tyk-community-edition/tutorials/create-api-token/
@titpetric your ide keeps adding these. Is 4 spaces a tyk standard in the code?

2024-06-14 13:40 UTC, letzya commented on tyk-docs/content/getting-started/create-api-key.md
> +```json
```suggestion
```yaml
```

2024-06-14 16:51 UTC, andyo-tyk requested changes
Corrected typos

2024-06-14 16:51 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api-key.md
> +- `smoothing`: The Rate Limit Smooting configuration for Redis Rate Limiter.
```suggestion
- `smoothing`: The Rate Limit Smoothing configuration for Redis Rate Limiter.
```

2024-06-14 16:51 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-security-policy.md
> +- `smoothing`: The Rate Limit Smooting configuration for Redis Rate Limiter.
```suggestion
- `smoothing`: The Rate Limit Smoothing configuration for Redis Rate Limiter.
```

2024-06-14 16:56 UTC, andyo-tyk requested changes
Correcting local links

2024-06-14 16:56 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +2. [Redis Rate Limiter]({{< ref "#Redis-Rate-Limiter" >}}): implements the [sliding window log algorithm](https://developer.redis.com/develop/dotnet/aspnetcore/rate-limiting/sliding-window)
```suggestion
2. [Redis Rate Limiter]({{< ref "#redis-rate-limiter" >}}): implements the [sliding window log algorithm](https://developer.redis.com/develop/dotnet/aspnetcore/rate-limiting/sliding-window)
```

2024-06-14 16:56 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +1. [Distributed Rate Limiter]({{< ref "#Distributed-Rate-Limiter" >}}): recommended for most use cases, implements the [token bucket algorithm](https://en.wikipedia.org/wiki/Token_bucket)
```suggestion
1. [Distributed Rate Limiter]({{< ref "#distributed-rate-limiter" >}}): recommended for most use cases, implements the [token bucket algorithm](https://en.wikipedia.org/wiki/Token_bucket)
```

2024-06-17 14:42 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-api-key.md
> +    "smoothing": {
I would suggest for now we don't include the smoothing controls in these getting started guides, as it's an advanced feature.

2024-06-17 14:44 UTC, letzya commented on tyk-docs/content/getting-started/create-api-key.md
> +    "smoothing": {
good point @andyo-tyk

2024-06-17 14:47 UTC, andyo-tyk requested changes, later dismissed
Recommend not making changes to the getting started guides at this stage.

2024-06-17 14:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-security-policy.md
> +    "smoothing": {
I wouldn't include this

2024-06-17 14:47 UTC, andyo-tyk commented on tyk-docs/content/getting-started/create-security-policy.md
> +- `smoothing`: The Rate Limit Smooting configuration for Redis Rate Limiter.
```suggestion
```

2024-06-17 15:26 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +  a RateLimitSmoothingUp event is emitted and allowance increases by `step`.
This is no longer relevant following re-write of the page. Closing comment.

2024-06-17 15:26 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +  a RateLimitSmoothingDown event is emitted and allowance decreases by `step`.
This is no longer relevant following re-write of the page. Closing comment.

2024-06-18 09:51 UTC, dcs3spp approved these changes

2024-06-18 09:55 UTC, dcs3spp commented
@titpetric I have approved the PR and removed the rate limit smoothing in the examples. @andyo-tyk are you ok with the changes? If so I will merge ready for release

2024-06-18 10:14 UTC, titpetric commented on tyk-docs/content/getting-started/create-api-key.md
> -description: "Creating an API access key using Tyk"
@dcs3spp Is the menu now removed on purpose? I remember re-adding it in, but now doesn't exist in current state of the page

2024-06-18 10:14 UTC, titpetric commented on tyk-docs/content/getting-started/create-security-policy.md
> +    main:
Still missed indentation on `menu` (even after correcting the one in tags)

2024-06-18 10:15 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/rate-limiting.md
> +    - Rate Limit
Whitespace

2024-06-18 10:30 UTC, titpetric commented on tyk-docs/content/getting-started/create-api-key.md
> -description: "Creating an API access key using Tyk"
I've reverted all front matter

2024-06-18 10:35 UTC, titpetric commented on tyk-docs/content/getting-started/create-security-policy.md
> +    - /getting-started/installation/tutorials/create-security-policy/
reverted

2024-06-18 10:44 UTC, titpetric commented
@dcs3spp I've asked @jeffy-mathew to re-approve as a significant section for rate limiting docs was rewritten, which was out of scope for the ticket.

2024-06-18 10:44 UTC, dcs3spp commented on tyk-docs/content/getting-started/create-security-policy.md
> +    main:
Thanks @titpetric fixed

2024-06-18 10:46 UTC, dcs3spp commented
> @dcs3spp I've asked @jeffy-mathew to re-approve as a significant section for rate limiting docs was rewritten, which was out of scope for the ticket.

@titpetric Jeffy has approved, can this now be merged ready for release?

2024-06-18 11:47 UTC, titpetric commented
@dcs3spp that's a stale approval, he needs to review the changes and re-approve due to the rewrites.

2024-06-18 12:08 UTC, dcs3spp commented
@jeffy-mathew I have re-requested a peer review on behalf of @titpetric

2024-06-18 12:22 UTC, jeffy-mathew approved these changes

2024-06-18 12:22 UTC, jeffy-mathew commented
@titpetric @dcs3spp lgtm, I've approved.

2024-06-18 14:55 UTC, andyo-tyk approved these changes

2024-06-18 14:59 UTC, dcs3spp commented
Many thanks @jeffy-mathew I will merge ready for release

2024-06-18 15:02 UTC, merged