Update installation.md
TykTechnologies/tyk-docs-hugo pull request #4827
Opened 2024-06-17 13:34 UTC by letzya

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-06-17 15:08 UTC, letzya commented on tyk-docs/content/getting-started/installation.md
> +tags: ["Tyk Installation Options", “Guide to Tyk installations”, "Tyk Open Source API Gateway", "Tyk Self-Managed Installation", "Tyk Cloud Installation"]
```suggestion
tags: ["installing", "installation", "Tyk Installation Options", “Guide to Tyk installations”, "Tyk Open Source API Gateway", "Tyk Self-Managed Installation", "Tyk Cloud Installation"]
```

2024-06-17 15:10 UTC, letzya commented on tyk-docs/content/getting-started/installation.md
> +title: Guide to tyk installations
```suggestion
title: Guide to Tyk Installations
```

2024-06-17 17:03 UTC, letzya commented on tyk-docs/content/getting-started/installation.md
> +Welcome to the Tyk Installation Guide! Whether you're new to Tyk or an experienced user, this guide will help you find the installation option that best meets your needs. Let's get started!
```suggestion
Welcome to the Tyk Installation Guide! Whether you're new to Tyk or an experienced user, this guide will help you find the installation model that best meets your needs. Let's get started!
```

2024-06-18 14:32 UTC, dcs3spp requested changes
PR LGTM! @letzya

I made some minor changes to add relative paths to button left etc.

What is the URL for the comparison page?

The current link included below gives a 404
[Comparison Page](https://tyk.io/about/contact)

2024-06-18 15:14 UTC, letzya commented on tyk-docs/content/getting-started/installation.md
> +Visit our [Comparison Page](https://tyk.io/about/contact) to understand the different installation types and their benefits.
```suggestion
Visit our [Comparison Page]({{< ref "/apim" >}}) to understand the different installation types and their benefits.
```

2024-06-18 15:15 UTC, letzya commented
> PR LGTM! @letzya
> 
> I made some minor changes to add relative paths to button left etc.
> 
> What is the URL for the comparison page?
> 
> The current link included below gives a 404 [Comparison Page](https://tyk.io/about/contact)

Thanks!!!
I messed up with it. The comparison is from the current page, not my addition, I just messed up while copy/pasting. it's /apim

2024-06-18 15:49 UTC, dcs3spp approved these changes

2024-06-18 15:49 UTC, dcs3spp commented
@sedkis Would you be able to peer review?

2024-06-18 16:53 UTC, merged

2024-06-18 16:53 UTC, letzya commented
/release to release-5.3

2024-06-20 13:23 UTC, sedkis reviewed
LGTM!