[TT-12306] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #4835
Opened 2024-06-18 10:01 UTC by buger

Triggered by: lghiur

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: master
Changes sourced from: release-5.4.0
Config info generator branch: main

Note: Release 5.4.0 Docs update (branch suffix: docs)

JIRA: https://tyktech.atlassian.net/browse/TT-12306

2024-06-18 12:04 UTC, dcs3spp requested changes
PR LGTM left comments relating to dashboard endpoints and status codes. Left a comment regarding Kind and ReadableDuration field regarding import alias. Not sure what is required for user/developer  to enter for these config values

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                              description: Invalid status value
Should this be invalid ID?
Should 404 and 409 be raised also?

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                            '400':
Should this raise 404 and 409 also?

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                              description: Invalid status value
should this be invalid id value? Should 404 and 409 be raised?

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        This endpoint allows you to search for users by providing their email address as a query parameter.
Based on the deprecated parameter, is it worth mentioning in the description the deprecation and alternative endpoint to use etc?

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                query: "user"
shouldn't the example include users email address in the request payload?

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +    post:
Should this be HTTP GET instead of POST?

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                message: "Could not search users"
For a 404 should the error message in the example be something like, could not find a user with email user@your-org.com?

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Redis based rate limiter with sliding log. Provides 100% rate limiting accuracy, but require two additional Redis roundtrip for each request.
```suggestion
Redis based rate limiter with sliding log. Provides 100% rate limiting accuracy, but require two additional Redis roundtrips for each request.
```

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +EnableRateLimitSmoothing enables or disables rate smoothing. The rate smoothing is only supported on the
```suggestion
EnableRateLimitSmoothing enables or disables rate limit smoothing. The rate smoothing is only supported on the
```

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Default: 10 seconds.
Should this value be documented in nano seconds or is the value automatically converted from seconds to nano seconds?

2024-06-18 12:04 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Kind is an alias maintained to be used in imports.
In Kind and ReadableDuration description mentions alias maintain to be used in imports. Are users/developers expected to include a value for these fields and if so what are valid examples?

2024-06-24 09:39 UTC, letzya commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Kind specifies the action to be taken on the event trigger.
what is the action? where can users (or I) read about kind and its meaning as it's new to me

2024-06-24 10:15 UTC, dcs3spp requested changes

2024-06-24 10:15 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  /api/apis/oas/dry-run:
The dry-run endpoint is missing query parameters documented in TT-11981

2024-06-26 06:55 UTC, andrei-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                              description: Invalid status value
409 should not be possible in a GET request

2024-06-26 06:55 UTC, andrei-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                              description: Invalid status value
Added response code entry for 404

2024-06-26 06:57 UTC, andrei-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                            '400':
Added both 404 and 409

2024-06-26 06:57 UTC, andrei-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                              description: Invalid status value
Same asa above, added 404. Did not add 409 as it's a GET request.

2024-06-26 11:20 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                              description: Invalid status value
Thanks @andrei-tyk should the description for 400 status be :  Invalid id value, could not process request?

2024-06-26 12:32 UTC, andrei-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                              description: Invalid status value
Yes,  you're right, it was addressed but not mentioned,  should be visible after I push the changes.

2024-06-26 12:34 UTC, andrei-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +        This endpoint allows you to search for users by providing their email address as a query parameter.
Adressed.

2024-06-26 12:35 UTC, andrei-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                query: "user"
"user" matches both "user@tyk.io" and "user123@tyk.io" so I see no sense in providing an exact match in a search example.

2024-06-26 12:38 UTC, andrei-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                message: "Could not search users"
This would again leak info if this request body is logged.  Furthermore it's the exact string the dashboard API is returning.

2024-06-26 12:39 UTC, andrei-tyk commented on tyk-docs/content/shared/gateway-config.md
> +Redis based rate limiter with sliding log. Provides 100% rate limiting accuracy, but require two additional Redis roundtrip for each request.
Addressed locally.

2024-06-26 12:40 UTC, andrei-tyk commented on tyk-docs/content/shared/gateway-config.md
> +EnableRateLimitSmoothing enables or disables rate smoothing. The rate smoothing is only supported on the
Addressed locally.

2024-06-26 12:42 UTC, andrei-tyk commented on tyk-docs/content/shared/gateway-config.md
> +Default: 10 seconds.
I believe it's pretty clear that we pass the nanoseconds amount but we explain that the default is the equivalent of 10 seconds in nanoseconds.

2024-06-26 12:48 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +                            '400':
Thanks @andrei-tyk @lghiur Can you import the change into the PR?

2024-06-26 12:48 UTC, dcs3spp commented
@andrei-tyk @lghiur Can you import the changes that were made into the PR relating to 404, 409 etc?

2024-06-26 12:49 UTC, andrei-tyk commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Kind is an alias maintained to be used in imports.
This section is autogenerated from the description of these golang aliases:

// Kind is an alias maintained to be used in imports.
type Kind = event.Kind

In this exact case it references the "type" field of and EventHandler. Given it's just autogenerated documentation string of an alias that supposedly needs to be used by developers, I don't think we need to provide explanations/examples for it.

2024-06-26 12:50 UTC, andrei-tyk commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Kind specifies the action to be taken on the event trigger.
https://github.com/TykTechnologies/tyk/blob/8fb9d2ebeefb450bd7dc0577ab731d722b4f79dd/apidef/oas/event.go#L13

and

https://github.com/TykTechnologies/tyk/blob/8fb9d2ebeefb450bd7dc0577ab731d722b4f79dd/apidef/oas/event.go#L25

are the places where this docs come from. Seems it's just an alias that was used to avoid importing the "event" package everywhere.

2024-06-26 12:53 UTC, andrei-tyk commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  /api/apis/oas/dry-run:
The ticket didn't specifically mention separate endpoints for these. All the functionality (CREATE+PATCH like behaviour) is handled via the same endpoint that does different stuff depending on what keys are sent to it

{
     "oas":{"..."},
     "tyk_oas":{"..."}
}

If we have only "oas" the behaviour is like a create, if we have "tyk_oas" as well, it patches the contents of "oas" on to "tyk_oas".

2024-06-26 13:05 UTC, andrei-tyk commented
> @andrei-tyk @lghiur Can you import the changes that were made into the PR relating to 404, 409 etc?

We need to merge 2 PRs in tyk+tyk-analytics for the changes to appear. We'll announce you on slack when everything is merged.

2024-06-26 13:19 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  /api/apis/oas/dry-run:
Why are the query parameters not documented?

2024-07-01 14:25 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +  /api/apis/oas/dry-run:
@andrei-tyk @lghiur _MockResponse_ and _CustomDomain_ parameters are not included on TT-11981 and APIID parameter is missing. 

Are MockResponse and CustomDomain parameters additional and should APIID be included?

2024-07-02 13:26 UTC, dcs3spp commented
@andrei-tyk @lghiur I have created ticket TT-12517 for the issues raised relating to import aliases and query parameters for /dry-run endpoint

2024-07-03 08:07 UTC, dcs3spp approved these changes

2024-07-03 08:11 UTC, merged