US-EN licence --> license
TykTechnologies/tyk-docs-hugo pull request #4865
Opened 2024-06-20 22:10 UTC by letzya

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-06-21 09:31 UTC, dcs3spp requested changes
Thanks Yaara, PR LGTM. I checked through the word replacements in PR and seems ok.

Have made minor suggestion for adding doc comment for usage in the bash script and updated file permissions for script to be executable.

Asked question about + character in csv file for the line containing license

2024-06-21 09:31 UTC, dcs3spp commented on scripts/uk_us_mapping.csv.full-list
> ++ Licence,License
Is the + symbol used to enable that replacement?

2024-06-21 09:31 UTC, dcs3spp commented on scripts/convert_uk_to_us.sh
> +
```suggestion

#===============================================================================
#
#       FILE: convert_uk_to_us.sh
# 
#       USAGE: ./run-menu-gen.sh <csv_file> <directory>
# 
#       DESCRIPTION: This script reads a CSV file containing pairs of UK and US
#                words, then recursively searches through the specified directory
#                to replace all instances of the UK words with their US counterparts
#                in the files found.
# 
#       OPTIONS: 
#.               <csv_file> - Path to the CSV file containing UK and US word pairs.
#                <directory> - Path to the directory where replacements should be made.
#
#       REQUIREMENTS: The CSV file should be formatted with each line containing 
#                two words separated by a comma, where the first word is the UK 
#                word and the second is the US word. The script also requires 
#                write permissions for the files in the target directory.
#  
#       NOTES: The script uses `find` to search for files and `sed` to perform 
#                the replacements. It handles basic error checking and ensures 
#                that the specified CSV file and directory exist before proceeding.
#===============================================================================
```

2024-06-21 16:25 UTC, letzya commented on scripts/uk_us_mapping.csv.full-list
> ++ Licence,License
to mark it as done

2024-06-24 12:17 UTC, dcs3spp approved these changes

2024-06-24 12:17 UTC, merged

2024-06-24 12:17 UTC, dcs3spp commented
/release to release-5.3