update on use of MDCB secret endpoints
TykTechnologies/tyk-docs-hugo pull request #4897
Opened 2024-06-24 16:50 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-06-25 07:09 UTC, komalsukhani requested changes

2024-06-25 07:09 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +In order to set the secret for accessing MDCB secure HTTP endpoints through a Kubernetes secret, please use tyk-mdcb.mdcb.useSecretName, where the secret should contain a key called `securitySecret`.
There should be a new line between `MDCB Secret` heading and description.
Otherwise, they are rendered on same line.
<img width="789" alt="Screenshot 2024-06-25 at 12 29 23 PM" src="https://github.com/TykTechnologies/tyk-docs/assets/5239161/d23703a6-4bb4-472e-ab79-10f33b4f72e9">

2024-06-25 07:09 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +The HTTP port for Tyk MDCB can be configurable via the `tyk-mdcb.mdcb.httpPort` field.
```suggestion
The HTTP port for Tyk MDCB is configurable via the `tyk-mdcb.mdcb.httpPort` field.
```

2024-06-25 07:09 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +This port lets MDCB allow standard HTTP request like health check.
```suggestion
This port enables MDCB to accept standard HTTP requests, such as health checks.
```

2024-06-25 07:57 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +In order to set the secret for accessing MDCB secure HTTP endpoints through a Kubernetes secret, please use tyk-mdcb.mdcb.useSecretName, where the secret should contain a key called `securitySecret`.
```suggestion

In order to set the secret for accessing MDCB secure HTTP endpoints through a Kubernetes secret, please use tyk-mdcb.mdcb.useSecretName, where the secret should contain a key called `securitySecret`.
```

2024-06-25 08:14 UTC, dcs3spp requested changes
PR LGTM @caroltyk I have added minor suggestions and once peer approval given can merge ready for release

2024-06-25 08:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +The HTTP port for Tyk MDCB is configurable via the `tyk-mdcb.mdcb.httpPort` field.
add link to MDCB config field, merged to main branch ready for release

2024-06-25 08:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +MDCB has secured HTTP endpoints, like `/dataplanes` which return list of gateway nodes connected. By default, this endpoint is disabled to avoid unintended leakage of data plane information. To enabl
Add link to MDCB OAS API, merged to main ready for release

2024-06-25 08:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +      useSSL: false
Should this be enabled so that relevant to the example for SSL and TLS and then uncomment the related fields...

2024-06-25 08:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +      # minVersion: 771
Is there a default is TLS is enabled?

2024-06-25 08:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +In order to set the secret for accessing MDCB secure HTTP endpoints through a Kubernetes secret, please use tyk-mdcb.mdcb.useSecretName, where the secret should contain a key called `securitySecret`.
Add an example of using the secret

2024-06-25 08:14 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +In order to set the secret for accessing MDCB secure HTTP endpoints through a Kubernetes secret, please use tyk-mdcb.mdcb.useSecretName, where the secret should contain a key called `securitySecret`.
```suggestion
In order to set the secret for accessing MDCB secure HTTP endpoints through a Kubernetes secret, please use tyk-`mdcb.mdcb.useSecretName`, where the secret should contain a key called `securitySecret`.
```

2024-06-26 15:00 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +      # minVersion: 771
user needs to set it

2024-06-26 15:01 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +      useSSL: false
good call, docs updated

2024-06-26 16:57 UTC, dcs3spp approved these changes
Thanks @caroltyk PR LGTM! @komalsukhani can you approve if you are ok that your requested changes have been addressed?

2024-06-27 06:24 UTC, komalsukhani approved these changes

2024-06-27 08:03 UTC, merged