Manage multi orgs in Operator
TykTechnologies/tyk-docs-hugo pull request #4903
Opened 2024-06-25 08:44 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-06-25 10:14 UTC, dcs3spp requested changes
Thanks @caroltyk PR LGTM! 

While in draft status, I have made minor structure changes to factor out key concepts into separate page and moved the guide into getting started menu folder.

2024-06-25 10:14 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-multiple-organisations.md
> +Tyk Operator is a Kubernetes Controller that manages Tyk Custom Resources (CRs) such as API Definitions and Security Policies. Developers define these resources as CRDs, and Tyk Operator ensures that
Add Custom Resource Definitions (CRDs) into the second sentence and link to K8s - https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

2024-06-25 10:14 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-multiple-organisations.md
> +
Add a summary explanation of what the key spec fields are, e.g mode, auth, org, url, user_owners and user_group_owners

2024-06-25 11:58 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-multiple-organisations.md
> +
modified spec with comments

2024-06-25 11:58 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/tyk-operator-multiple-organisations.md
> +Tyk Operator is a Kubernetes Controller that manages Tyk Custom Resources (CRs) such as API Definitions and Security Policies. Developers define these resources as CRDs, and Tyk Operator ensures that
updated

2024-06-25 12:13 UTC, dcs3spp requested changes
@caroltyk PR LGTM!!!!! Not sure if still in draft have added minor suggestion and asked question if overview page should be removed

2024-06-25 12:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/key-concepts.md
> +During start up, Tyk Operator looks for these keys from `tyk-operator-conf` secret or from the environment variables and use these credentails to connect to Tyk.
```suggestion
During start up, Tyk Operator looks for these keys from `tyk-operator-conf` secret or from the environment variables (listed in the table below) and uses these credentials to connect to Tyk.
```

2024-06-25 12:13 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> -        - title: "Overview"
Should the overview page be removed?

2024-06-25 12:41 UTC, caroltyk commented on tyk-docs/data/menu.yaml
> -        - title: "Overview"
Yes it is removed

2024-06-25 13:52 UTC, dcs3spp commented on tyk-docs/data/menu.yaml
> -        - title: "Overview"
Thanks @caroltyk I've fixed the build errors

2024-06-25 15:25 UTC, sedkis commented
Brilliant Carol.  This is excellent.  Thank you.

One thing we can think about adding:
1. What is the behaviour of the Tyk Operator do if NO Operator Context is provided in a situation where there are multiple orgs in the Tyk Dashboard.
2. What is the behaviour of the Tyk Operator if no ContextRef is provided in a CRD, yet multiple OperatorContexts are defined?

2024-06-26 08:30 UTC, dcs3spp approved these changes
Thanks @caroltyk PR and structure LGTM. Once peer approved and the diagrams have been improved as mentioned in review description, then ready for release.

2024-06-26 13:14 UTC, caroltyk commented
> Brilliant Carol. This is excellent. Thank you.
> 
> One thing we can think about adding:
> 
> 1. What is the behaviour of the Tyk Operator do if NO Operator Context is provided in a situation where there are multiple orgs in the Tyk Dashboard.
> 2. What is the behaviour of the Tyk Operator if no ContextRef is provided in a CRD, yet multiple OperatorContexts are defined?

Added example scenarios [here](https://deploy-preview-4903--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-operator/key-concepts/operator-context/#example-scenarios) to explain this.

2024-06-26 13:17 UTC, sedkis commented
Amazing - Thank you. LGTM

2024-06-27 09:28 UTC, dcs3spp commented
Marked PR as draft until diagrams are added

2024-07-04 08:42 UTC, caroltyk commented
@dcs3spp diagrams updated and updated spelling of "organisation" to "organization"

2024-07-04 11:01 UTC, merged

2024-07-04 11:01 UTC, dcs3spp commented
/release to release-5.4