Revamp Tyk APIs page to Tyk APIs Hub with improved layout
TykTechnologies/tyk-docs-hugo pull request #4908
Opened 2024-06-25 17:30 UTC by letzya

### **User description**
 Changed to tiles to make it a proper landing page and hub for OAS

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link
https://deploy-preview-4908--tyk-docs.netlify.app/docs/nightly/tyk-apis/

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

___

### **PR Type**
Enhancement, Documentation

___

### **Description**
- Updated the Tyk APIs page to a more comprehensive Tyk APIs Hub, including new badges and grid layout for better visual representation.
- Enhanced badge styles in `_docs.scss` for improved text alignment and wrapping.
- Added conditional padding styles to the page content in `baseof.html`.
- Supported inline styles for badge titles in `badge.html`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>_docs.scss</strong><dd><code>Update badge styles for better text alignment and wrapping</code></dd></summary>
<hr>

tyk-docs/assets/scss/_docs.scss
<li>Added new styles for <code>.badge center p</code> to improve text wrapping and font <br>weight.<br> <li> Modified <code>.badge.with_image p</code> to use column-reverse flex direction and <br>justify content to flex-end.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4908/files#diff-d29767519ca2fa4d8fce78b76e949905e03684c9f9d6572ff6b4f23888480e7e">+8/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>baseof.html</strong><dd><code>Add conditional padding styles to page content</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/themes/tykio/layouts/_default/baseof.html
<li>Added inline styles for padding when <code>hasPadding</code> parameter is present.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4908/files#diff-01f093c14a8c6a6225c7fdb89ffc257fec41575c15d18534cd421a33cbf1f605">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>badge.html</strong><dd><code>Support inline styles for badge titles</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/themes/tykio/layouts/shortcodes/badge.html
<li>Added inline style support for badge title using <code>titleStyle</code> parameter.<br> <br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4908/files#diff-0690f93e48f531d7ed293d54aa09945169f3102bd999651bb95e949b510535f3">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>tyk-apis.md</strong><dd><code>Revamp Tyk APIs page to Tyk APIs Hub with improved layout</code></dd></summary>
<hr>

tyk-docs/content/tyk-apis.md
<li>Updated title and description to reflect the new Tyk APIs Hub.<br> <li> Added badges and grid layout for better visual representation of API <br>documentation links.<br> <li> Enhanced content to provide a more comprehensive overview of Tyk APIs <br>and Postman collections.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/4908/files#diff-9b39000d14fb92eb96bb7c2b3b60bbff55102e9cea6cd29d439a95649c461aa7">+46/-24</a>&nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

2024-06-27 11:17 UTC, dcs3spp reviewed
Thanks @letzya, PR landing page LGTM! On the preview the Postman tab renders the text large, I have added review suggestion to try removing the h4 heading. I checked the styling of OSS GW badge and Dashboard which seems to match but somehow the text is displaying differently

2024-06-27 11:17 UTC, dcs3spp commented on tyk-docs/content/tyk-apis.md
> +<h4>Tyk Postman workspace</h4>
What happens if remove h4 styling does it display same text styling as other badges on the landing page?

```suggestion
Tyk Postman workspace
```

2024-06-27 11:17 UTC, dcs3spp commented on tyk-docs/content/tyk-apis.md
> +API to manage your API platform
Styling not displayed as centred for badge title, not sure why, I have checked and the styling seems to match the open source badge

2024-06-27 17:10 UTC, letzya commented on tyk-docs/content/tyk-apis.md
> +API to manage your API platform
not sure i understand

2024-07-01 12:43 UTC, andyo-tyk requested changes, later dismissed
Some suggested tweaks to wording

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +description: Tyk API hub. In this section you will find OpenAPI docs for Tyk API Gateway, Tyk Dashboard and other Tyk products
```suggestion
description: The Tyk API Hub. In this section you will find OpenAPI docs for the APIs for Tyk Gateway, Tyk Dashboard and other Tyk products
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +In this page you will find the full range of Tyk APIs, designed to help you integrate and manage your API ecosystem
```suggestion
All Tyk components are designed with an API that allows you to configure and control the product. On this page you will find documentation for all of these APIs, designed to help you to integrate Tyk into your software stack and then manage your API ecosystem efficiently.
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +efficiently. Explore our comprehensive API documentation and Postman collections to get started quickly.
```suggestion
```

This feels a little unnecessary.

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +Postman collections provide an interactive way to explore and test Tyk APIs. They are designed to help you quickly get
```suggestion
These provide an interactive way to explore and test Tyk components' APIs. They are designed to help you quickly get
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +Tyk Postman workspace
```suggestion
Tyk Public Workspace at Postman
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +## Tyk Enterprise - APIs Documentations
```suggestion
## Tyk Enterprise
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +Access detailed documentation to understand the full capabilities of Tyk products. Our documentation provides all the
```suggestion
Here you can access detailed documentation enabling you to unlock the full capabilities of Tyk's enterprise products. This API documentation provides all the
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +information you need to integrate Tyk Management APIs seamlessly into your projects.
```suggestion
information you need to integrate Tyk's products seamlessly into your projects.
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +Manage Tyk API platform
```suggestion
Manage the Tyk platform
</br>from the Dashboard
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +</br>Tyk Data planes
```suggestion
</br>Tyk Data Planes
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +</br>Managing and controlling
```suggestion
</br>Configure & control
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +## Tyk Open Source - API Documentations
```suggestion
## Tyk Open Source
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +Configure & Control
```suggestion
Configure & control
</br>Open Source deployment
```

2024-07-01 12:43 UTC, andyo-tyk commented on tyk-docs/content/tyk-apis.md
> +</br>Provision and set up
```suggestion
</br>Provision & administrate
```

2024-07-02 17:21 UTC, letzya commented
/release to release-5.3

2024-07-02 17:21 UTC, letzya commented
@andyo-tyk - @Arturas-Salivonas fixed the text-overflow in a separate PR, FYI

2024-07-03 15:02 UTC, dcs3spp approved these changes
PR LGTM

2024-07-03 17:02 UTC, merged

2024-07-03 17:03 UTC, letzya commented
/release to release-5.3

2024-07-04 09:53 UTC, letzya commented
/release to release-5.4