Add release notes for EDP 1.10.0
TykTechnologies/tyk-docs-hugo pull request #4909
Opened 2024-06-26 14:33 UTC by tbuchaillot

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-06-26 16:22 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- [Docker image v1.9.0](https://hub.docker.com/r/tykio/portal/tags?page=&page_size=&ordering=&name=v1.10.0)
```suggestion
- [Docker image v1.10.0](https://hub.docker.com/r/tykio/portal/tags?page=&page_size=&ordering=&name=v1.10.0)
```

2024-06-26 16:39 UTC, dcs3spp requested changes
PR LGTM @tbuchaillot, made minor suggestions and left comments relating to how some of the bug caused an issue.

If the environment variables are new relating to the connection and cache then will need adding and linked to [here](https://tyk.io/docs/product-stack/tyk-enterprise-developer-portal/deploy/configuration/)

2024-06-26 16:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +##### Release Date 27 Jun 2024
Should this be 1 July 2024?

2024-06-26 16:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +The 1.10.0 addresses twenty high-priority bugs and vulnerabilities bugs and introduces three new capabilities:
```suggestion
The 1.10.0 addresses twenty high-priority bugs and vulnerabilities and introduces three new features:
```

2024-06-26 16:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Fixed the bug where accesss requests were not removed when an application is deleted.
```suggestion
- Fixed the bug where access requests were not removed when an application is deleted.
```

2024-06-26 16:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Fixed the bug where stoplight library was blocking the portal's startup if it's not avaialble.
```suggestion
- Fixed the bug where stoplight library was blocking the portal's startup if it's not available.
```

2024-06-26 16:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Fixed the bug where it was possible to create a new access requests from the admin dashboard.
How was this an issue, what problem did it cause?

```suggestion
- Fixed the bug where it was possible to create new access requests from the admin dashboard.
```

2024-06-26 16:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Fixed the bug where carts submissions where affecting other users carts.
Add explanation how carts submissions were affecting other user carts

2024-06-26 16:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Configuration options for database connections.
Briefly explain PORTAL_DATABASE_MAX_OPEN_CONNECTIONS, PORTAL_DATABASE_MAX_IDLE_CONNECTIONS and PORTAL_DATABASE_CONNECTION_MAX_LIFETIME and link to accompanying documentation. If new environment variables then documentation should be added [here](https://tyk.io/docs/product-stack/tyk-enterprise-developer-portal/deploy/configuration/)

2024-06-26 16:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Added an assets cache for improved performance on database-backed themes. This speeds up the portal's pages loading time by 30%. It's enabled by default and you can disable using `PORTAL_ASSETS_CAC
To disable PORTAL_ASSETS_CACHE_DISABLE=True | PORTAL_ASSETS_CACHE_DISABLE=true ?

If new env var then docs needs adding [here](https://tyk.io/docs/product-stack/tyk-enterprise-developer-portal/deploy/configuration/)

2024-06-27 07:54 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Fixed the bug where it was possible to create a new access requests from the admin dashboard.
@dcs3spp it was an operation that shouldn't be possible at all 😆 that's why it was classified as a bug. Commited the suggestion, but won't go into more details.

2024-06-27 08:02 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +##### Release Date 27 Jun 2024
Hopefully we can release it today 😆 I'll modify the date accordingly

2024-06-27 08:21 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Fixed the bug where carts submissions where affecting other users carts.
added!

2024-06-27 08:26 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Added an assets cache for improved performance on database-backed themes. This speeds up the portal's pages loading time by 30%. It's enabled by default and you can disable using `PORTAL_ASSETS_CAC
@dcs3spp the new env vars was already there, added a link to that in the release notes 👌

2024-06-27 08:26 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
> +- Configuration options for database connections.
@dcs3spp the new env vars were already there, linked them to the release notes 👌

2024-06-27 09:06 UTC, dcs3spp approved these changes
@tbuchaillot PR approved, LGTM! @MFCaballero could you peer review and if all ok approve.

Once peer approved will merge and release

2024-06-27 09:30 UTC, edsonmichaque approved these changes
LGTM

2024-06-27 10:35 UTC, MFCaballero approved these changes
lgtm

2024-06-27 16:07 UTC, merged

2024-06-27 16:08 UTC, dcs3spp commented
/release to release-5.3