Operator 0.18.0 Release notes
TykTechnologies/tyk-docs-hugo pull request #4910
Opened 2024-06-26 15:18 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-06-26 16:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.18.md
> +- [Docker image v0.18](https://hub.docker.com/r/tykio/tyk-operator/tags?page=&page_size=&ordering=&name=v0.18.0)
```suggestion
- [Docker image v0.18.0](https://hub.docker.com/r/tykio/tyk-operator/tags?page=&page_size=&ordering=&name=v0.18.0)
```

2024-06-26 16:50 UTC, dcs3spp requested changes
PR LGTM @caroltyk I have reviewed with minor suggestions of expanding the CRD abbreviation and linking to docs pages for supported GraphQL fields.

2024-06-26 16:50 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.18.md
> +Added to ApiDefinition CRD: support of following fields `graphql.proxy.auth_headers` , `graphql.proxy.request_headers`, `graphql.proxy.use_response_extensions`, `graphql.engine.global_headers`.
Expand CRD abbreviation to Custom Resource Definition (CRD) linking to https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

Link the supported fields to docs, e.g. https://tyk.io/docs/universal-data-graph/concepts/header_management/#global-headers-for-udg

2024-06-26 22:30 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.18.md
> +Added to ApiDefinition CRD: support of following fields `graphql.proxy.auth_headers` , `graphql.proxy.request_headers`, `graphql.proxy.use_response_extensions`, `graphql.engine.global_headers`.
thanks. docs updated

2024-06-27 05:57 UTC, komalsukhani requested changes

2024-06-27 05:57 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.18.md
> +Added to ApiDefinition [Custom Resource Definition (CRD)](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/): support of following fields [GraphQL APIs
Following fields were added in Operator

- `introspection` option to enable/disable GraphQL introspection
- features section to graphql proxy config
- AuthHeaders
- SubscriptionType
- RequestHeaders
- UseResponseExtensions 
- RequestHeadersRewrite

2024-06-27 09:00 UTC, dcs3spp commented
@caroltyk Once the [request changes](https://github.com/TykTechnologies/tyk-docs/pull/4910#discussion_r1656504281) have been approved by @komalsukhani I will merge ready for release.

2024-07-01 10:05 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.18.md
> +Added to ApiDefinition [Custom Resource Definition (CRD)](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/): support of following fields [GraphQL APIs
updated

2024-07-01 10:09 UTC, komalsukhani approved these changes

2024-07-01 10:41 UTC, dcs3spp approved these changes

2024-07-01 10:41 UTC, merged