[DX 815] Draft: Plugins Overview
TykTechnologies/tyk-docs-hugo pull request #4918
Opened 2024-06-27 14:46 UTC by dcs3spp

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-815](https://tyktech.atlassian.net/browse/DX-815)

---

### Preview Link

<br>

### Description

- Improve Plugins Overview Page
- Add Plugins API configuration section

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-07-19 18:19 UTC, andyo-tyk requested changes
Started review

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +Plugins are enabled within the *coprocess_options* section of the Gateway configuration file, *tyk.conf*:
Is this just for "coprocess" plugins? You haven't defined this term yet.

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +Please consult our supporting documentation for further details relating to configuring plugins for [Javascript (JVSM)]({{< ref "plugins/supported-languages/javascript-middleware#enabling-the-javascr
It's better to say "JavaScript plugins" and "gRPC plugins" than "plugins for JavaScript and gRPC"

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +Optionally, Tyk Gateway can be [configured]({{< ref "/plugins/how-to-serve-plugins/plugin-bundles" >}}) with the base URL of the webserver that it should use to download plugins from.
First mention of downloading plugins? Probably needs some introduction (the concept of the Gateway loading plugins - when? how?).

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +#### Webserver (optional)
This should probably say something like "Plugin storage server" or something along those lines (depending on what you put in the explanation of how Gateway accesses plugins - see below)

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +So far we have seen that an API can have one or more plugins that are triggered to run at various phases of the API request lifecycle. Plugins for an API are deployed as source code with accompanying
They aren't all Request plugins - so API request lifecycle could be confusing.

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +- **Locally**: The source code is located at the Tyk Gateway file system. The Api Definition allows the source file path and function name to be configured for each type of plugin. Consult [plugin so
Typo: Api Definition > API definition

Not sure about this "source code file" thing - on the linked page you're talking about how plugins are configured in the API definitions.

I suggest following the same model used everywhere else in the docs where we've introduced Tyk OAS, by having a trio of pages:
 1 - overview of concepts, terminology, gateway behaviour
 2 - how to configure with Tyk OAS API definition, anything Tyk OAS specific
 3 - how to configure with Tyk Classic API definition, anything Tyk Classic specific

This way we have progressive disclosure, clarity of terminology and then, when they go to the OAS/Classic specific page it can be fully focused on what's possible without risk of confusion between sections on the page.

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +- **Remotely**: The source code and a *manifest.json* is [bundled]({{< ref "/plugins/how-to-serve-plugins/plugin-bundles" >}}) into a zip file and uploaded to an external remote web server. The *mani
Ah, this is where you mention the webserver... seems a bit back to front to me when reading this. I would put less detail on this introductory page and then have a section (in the trio of pages format) that explains how it all works in detail.

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +- They must run as a single process.
What does this mean to the reader? They "must run".... but doesn't Tyk run them?

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +- They must manage API-specific cases in the same process, only one CoProcess will be managed by a Tyk Instance.
Again, not clear on this - a bit terminology heavy?

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +- To apply a custom plugin to an API you must modify the API definition and configure the plugin for one of the phases of the API Request Lifecycle as mentioned above.
This makes it sound onerous - and I don't think is necessary anyway as a caveat - it's just "how to configure a plugin" (again)

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +- Javascript plugins only support Pre and Post Request phases of the API Request Lifecycle.
Not sure that "support" is the right word here - and should this be mentioned only here in "caveats", or in the JavaScript section? Or perhaps in the Pre/Post sections?

Previously I think we used "hooks" - if moving to "phases" term can you please ensure this is used throughout the docs for consistency?

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +- Get started with your first Go custom plugin using our [tutorial]({{< ref "/plugins/tutorials/quick-starts/go/quickstart" >}}).
Why here do we say "Go custom plugin" when in the rest of the page they are just called "Go plugins"? I see that the docs section is "plugins" whilst the page title is "Custom Plugins". I really think this is one phrase we should tighten up on.

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +## Whats Next?
Not sure about this title, but if used then it should have an apostrophe

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +- Browse our [plugins hub]({{< ref "/plugins/plugin-hub" >}}) for resources that showcase how to develop Tyk Plugins.
Here we've gone to (capitalised) Tyk Plugins... I think this could be confusing for the reader when everywhere else we have avoided a proper noun and just used lower-case plugin or custom plugin.

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/open-source/source-bundles.md
> +description: "This section explains ehow to configure APIs to use plugin bundles deployed on a remote web server"
```suggestion
description: "This section explains how to configure APIs to use plugin bundles deployed on a remote web server"
```

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/open-source/source-bundles.md
> +tags: ["tyk plugins", "API Gateway middleware", "Custom middleware", "Custom API request"]
"Custom API request"?
Tyk should be capitalised - but per comment elsewhere, are we defining a proper noun or just using "plugin" or "custom plugin"?

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/open-source/source-bundles.md
> +For API plugins that are deployed as plugin bundles, the API should be configured with the name of the plugin bundle file to download from your remote web server.
Reader thinks "What's a plugin bundle?" - this page is called "bundle" in the menu, but the page that describes what a bundle is, is hidden away further down in Serving Plugins>Packaging plugins.

I would restructure this - split into Tyk OAS and Tyk Classic implementation details/examples alongside the "what is a bundle? how does it work?" page

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/open-source/source-bundles.md
> +The configuration for an API to fetch the download of a plugin bundle from a remote server is encapsulated wihin the *custom_middleware_bundle* field of the Tyk Classic API Definition. An illustrativ
Is this supposed to be an example API definition? Where does this appear in the Tyk Classic API def? Is there anything else I need to configure?

2024-07-19 18:19 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/open-source/source-bundles.md
> +```yaml
Why yaml and not json? Is this a new style we need to use?
If you look at all the other Tyk OAS examples, they are json with line numbers and the relevant fragment highlighted.
They are also all "working examples" that can be imported to the Dashboard and will work - so need the OpenAPI part and also remove the dbId/id/orgId. See the transformation middleware pages for examples.

2024-07-29 15:31 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +Please consult our supporting documentation for further details relating to configuring plugins for [Javascript (JVSM)]({{< ref "plugins/supported-languages/javascript-middleware#enabling-the-javascr
updated

2024-07-29 15:39 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +- To apply a custom plugin to an API you must modify the API definition and configure the plugin for one of the phases of the API Request Lifecycle as mentioned above.
remove list item at line 95

2024-07-29 15:51 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +- Javascript plugins only support Pre and Post Request phases of the API Request Lifecycle.
Update to use hooks and replaced support with allow. The caveat is already mentioned in the [JavaScript](https:/tyk.io/docs/plugins/supported-languages/javascript-middleware/) and [supported languages](https:/tyk.io/docs/nightly/plugins/supported-languages) section

2024-07-29 16:11 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +- Get started with your first Go custom plugin using our [tutorial]({{< ref "/plugins/tutorials/quick-starts/go/quickstart" >}}).
Update menu item and page title. Replaced Go custom plugin with Go plugin

2024-07-29 16:11 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +## Whats Next?
Replaced with Supporting Resources

2024-07-30 14:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/open-source/source-bundles.md
> +```yaml
updated with Tyk OAS example with line numbers and fragment highlighted

2024-07-30 14:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/open-source/source-bundles.md
> +The configuration for an API to fetch the download of a plugin bundle from a remote server is encapsulated wihin the *custom_middleware_bundle* field of the Tyk Classic API Definition. An illustrativ
Updated example so included with line numbers and fragment highlighted. Added sentence explaining that will need to configure the Gateway to download plugins from a secured webserver, with accompanying link

2024-07-30 14:38 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +- They must manage API-specific cases in the same process, only one CoProcess will be managed by a Tyk Instance.
Updated to:

- Tyk Gateway manages plugins for each API within the same process.
- For [gRPC plugins]({{< ref "plugins/supported-languages/rich-plugins/grpc" >}}), Tyk Gateway can only be configured to integrate with one gRPC server.
- Javascript plugins only allow Pre and Post Request hooks of the API Request Lifecycle.

2024-07-30 14:39 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +- They must run as a single process.
See comment below

2024-07-30 15:07 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +So far we have seen that an API can have one or more plugins that are triggered to run at various phases of the API request lifecycle. Plugins for an API are deployed as source code with accompanying
Updated as follows:

So far we have seen that an API can have one or more plugins that can execute at various phases of the [API request/response lifecycle]({{< ref "plugins/plugin-types/plugintypes" >}}).

2024-09-05 15:02 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +- **Locally**: The source code is located at the Tyk Gateway file system. The Api Definition allows the source file path and function name to be configured for each type of plugin. Consult [plugin so
Updated via separate PR that has been merged into this PR

2024-09-05 15:03 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +- **Remotely**: The source code and a *manifest.json* is [bundled]({{< ref "/plugins/how-to-serve-plugins/plugin-bundles" >}}) into a zip file and uploaded to an external remote web server. The *mani
Addressed by separate PR that has been merged into this PR

2024-09-05 15:03 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +Optionally, Tyk Gateway can be [configured]({{< ref "/plugins/how-to-serve-plugins/plugin-bundles" >}}) with the base URL of the webserver that it should use to download plugins from.
Addressed by separate PR

2024-09-05 15:34 UTC, dcs3spp commented
@andyo-tyk I have merged the structural changes that adds sections for API configuration (overview, Tyk classic API config, Tyk OAS API config) and plugin bundles (overview, Tyk classic API config, Tyk OAS API config). Are you ok for the PR to be published?

@letzya

2024-09-05 16:12 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +Plugins are enabled within the *coprocess_options* section of the Gateway configuration file, *tyk.conf*:
Updated to:

### Tyk Gateway Configuration

#### Coprocess Plugins

In the context of Tyk, *coprocess* plugins refer to external plugins that run alongside the main Tyk Gateway process. These plugins allow for custom logic to be executed within the API lifecycle without modifying the core gateway. Essentially, *coprocess* plugins act as independent services that communicate with Tyk via APIs, enabling the integration of custom functionality written in various languages such as Python, or any other supported gRPC language.

To enable these coprocess plugins, Tyk Gateway needs to be configured accordingly. This is done in the `tyk.conf` file under the `coprocess_options` section, where the option `enable_coprocess` must be set to `true`:

```json
{
    "coprocess_options": {
        "enable_coprocess": true
    }
}
```

#### Plugin Bundles

If you're using [plugin bundles]({{< ref "plugins/how-to-serve-plugins/plugin-bundles#gateway-configuration" >}}) you'll need to configure Tyk Gateway with the URL of the webserver from which it should download the plugin bundles.

#### Javascript and gRPC Plugins

Please consult the supporting documentation for further details on configuring Tyk Gateway when using [Javascript]({{< ref "plugins/supported-languages/javascript-middleware#enabling-the-javascript-virtual-machine-jsvm" >}}) or [gRPC]({{< ref "plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin#configure-tyk-gateway" >}}) plugins.

2024-09-06 15:53 UTC, andyo-tyk requested changes
Improvements suggested from review of updated content, including suggestions on menu naming

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +A plugin bundle is a ZIP file that contains your plugin source code files and associated configuration. A [manifest.json](#manifest) file must be included within the bundle containing a list of the s
```suggestion
For Tyk Gateway to execute local custom plugins during the processing of API requests and responses, the plugin source code must be loaded into the Gateway. The source is usually stored in files and the API definition is used to point the Gateway at the correct file for each [plugin type]({{< ref "plugins/plugin-types/plugintypes" >}}). To simplify the management of plugins, you can group (or *bundle*) multiple plugin files together in a ZIP file that is referred to as a *plugin bundle*.
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +### Caching
```suggestion
### Caching plugin bundles
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +The source code and a [manifest.json](#manifest) file are bundled into a zip file and uploaded to an external remote web server. The [manifest.json](#manifest) file references the source code file pa
```suggestion
The source code and a [manifest file](#manifest) are bundled into a zip file and uploaded to an external remote web server. The manifest file references the source code file path and the function name within the code that should be invoked for each [plugin type]({{< ref "plugins/plugin-types/plugintypes" >}}). Within the API definition, custom plugins are configured simply using the name of the bundle (zip file). Tyk Gateway downloads, caches, extracts and executes plugins from the downloaded bundle according to the configuration in the manifest file. 
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +Tyk downloads a plugin bundle on startup, e.g. `http://my-bundle-server.com/bundles/bundle-latest.zip`. A plugin bundle will be cached after its initial download, if a Tyk reload event occurs, the sa
```suggestion
Tyk downloads a plugin bundle on startup based on the configuration in the API definition, e.g. `http://my-bundle-server.com/bundles/bundle-latest.zip`. The bundle contents will be cached so that, when a Tyk reload event occurs, the Gateway does not have to retrieve the bundle from the server again each time. If you want to use a different bundle then you must update your API to retrieve a different bundle filename and then trigger a reload. It is not sufficient simply to replace the bundle file on your server with an updated version with the same name - the caching ensures this will not be retrieved during a reload event.
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
> +Issue the following command below to see more details on the `bundle` command:
```suggestion
Issue the following command to see more details on the `bundle` command:
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
> +The resulting file will contain all your specified files and a modified `manifest.json` with the right checksum and signature (if required), in ZIP format.
```suggestion
The resulting file will contain all your specified files and a modified `manifest.json` with the checksum and signature (if required) applied, in ZIP format.
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +This page provides an overview for configuring one or more API-level custom plugins that can be optionally setup to execute for each of the following [hooks]({{< ref "plugins/plugin-types/plugintypes
```suggestion
This page provides an overview on how to register one or more custom plugins to be executed at different stages or [hooks]({{< ref "plugins/plugin-types/plugintypes#plugin-and-hook-types" >}}) in the API request/response lifecycle. If you wish to learn how to register custom plugins to be executed on the traffic logs generated by the Gateway please refer to the [analytics plugins]({{< ref "plugins/plugin-types/analytics-plugins" >}}) page. 
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +If you desire fine grained control at the endpoint level then it is also possible to configure [per-endpoint plugins]({{< ref "product-stack/tyk-gateway/middleware/endpoint-plugin" >}}). These are cu
```suggestion
If you need fine-grained control at the endpoint level then it is also possible to configure [per-endpoint plugins]({{< ref "product-stack/tyk-gateway/middleware/endpoint-plugin" >}}). These are custom Golang plugins that are triggered at the end of the request processing chain before API-level *Post* plugins are executed.
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +2. **Plugin bundles**: The plugin source code and configuration are bundled into a zip file that is served by a remote web server. For further details see the [plugin bundles]({{< ref "plugins/how-to
I would swap (2) and (3)

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +If you’re using the legacy Tyk Classic APIs, then check out the [configuring plugins for Tyk Classic APIs]({{< ref "/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic" >}})
Please swap these and put Tyk OAS first

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Pre   | Executed at the start of the request processing chain | pre    |
```suggestion
| Pre   | Executed at the start of the request processing chain | `pre`    |            
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Auth  | Executed during the authentication step | auth_check |
```suggestion
| Auth  | Executed during the authentication step | `auth_check` |  
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Post Auth | Executed after the requester has been authenticated | post_key_auth |
```suggestion
| Post Auth | Executed after the requester has been authenticated | `post_key_auth` |
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Post | Executed at the end of the request processing chain | post |
```suggestion
| Post | Executed at the end of the request processing chain | `post` |       
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Response | Executed on the response received from the upstream | response |
```suggestion
| Response | Executed on the response received from the upstream | `response` |   
```

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/data/menu.yaml
> +        - title: "Developing plugins"
```suggestion
        - title: "Custom plugins"
```

I would go with "custom plugins" here because that's consistently the term used to describe them and so is more obvious to the reader to find.

2024-09-06 15:53 UTC, andyo-tyk commented on tyk-docs/data/menu.yaml
> +          - title: "Serving plugins"
```suggestion
          - title: "Plugin bundles"
```

This section is exclusively about plugin bundles, so again I would use the obvious name.

2024-09-06 16:07 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +If you’re using the legacy Tyk Classic APIs, then check out the [configuring plugins for Tyk Classic APIs]({{< ref "/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic" >}})
Thanks Andy, updating

2024-09-06 16:07 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +2. **Plugin bundles**: The plugin source code and configuration are bundled into a zip file that is served by a remote web server. For further details see the [plugin bundles]({{< ref "plugins/how-to
Thanks Andy, updated

2024-09-06 16:12 UTC, dcs3spp commented
Thanks @andyo-tyk I have committed review suggestions and updated suggested ordering

2024-09-06 16:21 UTC, merged

2024-09-06 16:22 UTC, dcs3spp commented
/release to release-5.5

2024-09-10 14:39 UTC, dcs3spp commented
/release to release-5.4

2024-09-10 14:40 UTC, dcs3spp commented
/release to release-5.3