{DX-1499} Gateway 5.5 release notes
TykTechnologies/tyk-docs-hugo pull request #5043
Opened 2024-07-09 14:40 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
(https://tyktech.atlassian.net/browse/DX-1499)

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-07-30 09:08 UTC, dcs3spp requested changes
PR LGTM @Eopayemi I have made suggestions/observations relating to captialisation of some changelog items and suggested moving some changelog items to a different changelog section.

Where possible add links to new documentation in the changelog section

2024-07-30 09:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +| 5.5.0 | MDCB v2.6     | MDCB v2.4.2 |
Update recommended release versions and backwards compatibility versions for this release

2024-07-30 09:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Add upgrade steps here if necessary.
Remember to remove this sentence if there are no specific upgrade steps or add specific upgrade instructions here

2024-07-30 09:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +We are thrilled to introduce Tyk Gateway 5.5, bringing advanced rate-limiting capabilities, enhanced certificate authentication, and performance optimizations. For a comprehensive list of changes, pl
Add link to the changelog below. Use release notes for v5.4.0 as a guide/example

2024-07-30 09:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +<summary>Corrected ordering of OAS API paths to prevent middleware misapplication</summary>
Should this be moved to fixed section?

2024-07-30 09:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +<summary>Enhanced API versioning with Fallback option for 'First of Path' version data location<summary>
```suggestion
<summary>Enhanced API versioning with fallback option for *First of Path* version data location<summary>
```

2024-07-30 09:08 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Introduced a new configuration for API versioning with 'url_versioning_pattern'. This regex-based field helps identify if the first part of a URL is a version pattern, improving control over 'strip_v
```suggestion
Introduced a new configuration for API versioning with `url_versioning_pattern`. This regex-based field helps identify if the first part of a URL is a version pattern, improving control over `strip_versioning_data` and `fallback_to_default` functionalities.
```

2024-08-07 14:40 UTC, andyo-tyk requested changes
Review suggestions

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Simplify certificate management with support for root Certificate Authority (CA) certificates, enabling client authentication via certificates signed by the configured root CA.
```suggestion
Simplify certificate management with support for root Certificate Authority (CA) certificates, enabling clients to authenticate using certificates signed by the configured root CA.
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +We've added support for using root Certificate Authority (CA) certificates as client certificates in API definitions. The system now authenticates clients with certificates signed by the configured r
```suggestion
We've added support for you to [register]({{< ref "https://tyk.io/docs/basic-config-and-security/security/mutual-tls/client-mtls#can-i-register-a-root-certificate-authority-ca-certificate-with-tyk-so-that-tyk-will-validate-requests-with-certificates-signed-by-this-ca" >}}) Certificate Authority (CA) certificates in your API definitions when using static mutual TLS (mTLS). Tyk can now authenticate clients presenting certificates signed by the registered root CA, simplifying certificate management for multiple clients sharing a common CA.
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Now configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs, providing granular protection for upstream services against abuse.
```suggestion
Now configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs, providing granular protection for upstream services against overloading and abuse.
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Introduced new controls to configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs. This feature allows for more granular protection of upstream services from abuse, similar
```suggestion
Introduced new more granular controls for request rate limiting. Rate limits can now be configured at the endpoint level in [Tyk OAS]({{ ref "product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas#advanced-endpoint-rate-limit" >}}) and [Tyk Classic]({{ ref "product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic#advanced-endpoint-rate-limit" >}}) API definitions.
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +<summary>Enhanced API versioning with fallback option for <i>First of Path</i> version data location</summary>
```suggestion
<summary>Improved handling of requests to non-existent versions of APIs when using URL path versioning</summary>
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Introduced a new configuration for API versioning with `url_versioning_pattern`. This regex-based field helps identify if the first part of a URL is a version pattern, improving control over `strip_v
```suggestion
When using the URL path to indicate the API version (for example `/v1/my-api`) it is common to strip the version identifier (e.g. `/v1`) from the path before proxying the request to the upstream. If the client doesn't provide any version identifier this could lead to an invalid target URL and failed requests, rather than correctly redirecting to the default version. We have introduced an optional configuration `url_versioning_pattern` where you can specify a regex that Tyk will use to identify if the URL contains a version identifier and avoiding the accidental stripping of valid upstream path. For more detail, see [here]({{< ref "product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning#stripping-url-path-version-and-default-fallback" >}}).
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +<summary>Corrected ordering of OAS API paths to prevent middleware misapplication</summary>
```suggestion
<summary>Fixed an issue where transformation middleware could incorrectly be applied to Tyk OAS API endpoints with nested paths</summary>
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Fixed an issue where nested API endpoints, such as '/test' and '/test/abc', might incorrectly apply middleware from the parent path to the nested path. The fix ensures that API endpoint definitions a
```suggestion
Fixed an issue when using Tyk OAS APIs where nested API endpoints, such as '/test' and '/test/abc', might incorrectly apply middleware from the parent path to the nested path. The fix ensures that API endpoint definitions are correctly ordered so that the standard behaviour of Tyk is followed, whereby path matching is performed starting from the longest path, preventing middleware misapplication and ensuring both the HTTP method and URL match accurately.
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> + Resolved an issue where Host and Latency fields (Total and Upstream) were not correctly reported for edge gateways in MDCB setups. The fix ensures accurate Host values and Latency measurements are n
```suggestion
 Resolved an issue where Host and Latency fields (Total and Upstream) were not correctly reported for Tyk Gateways in MDCB data planes. The fix ensures accurate Host values and Latency measurements are now captured and displayed in the generated traffic logs.
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +  <summary>Fixed Analytics Latency Reporting for MDCB Setups</summary>
```suggestion
<summary>Fixed analytics latency reporting for MDCB setups</summary>
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +  <details>
```suggestion
<details>
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> + </details>
```suggestion
</details>
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> + </li>
```suggestion
</li>
```

2024-08-07 14:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Previously, key creation or reset led to an exponential number of Redis DeleteRawKey commands, especially problematic for access lists with over 100 entries. The key creation sequence now runs only o
```suggestion
Previously, key creation or reset led to an exponential number of Redis `DeleteRawKey` commands,; this was especially problematic for access lists with over 100 entries. The key creation sequence now runs only once, eliminating redundant deletion of non-existent keys in Redis. This optimization significantly reduces deletion events, enhancing performance and stability for larger access lists.
```

2024-08-07 14:44 UTC, andyo-tyk requested changes
Further improvements - inconsistent capitalisation of headings

2024-08-07 14:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +<summary>Optimised key creation process to reduce Redis DeleteRawKey commands</summary>
```suggestion
<summary>Optimised key creation process to avoid unnecessary Redis `DeleteRawKey` commands</summary>
```

2024-08-07 14:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +<summary>Resolved SSE Streaming issue</summary>
```suggestion
<summary>Resolved SSE streaming issue</summary>
```

2024-08-07 14:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +<summary>Implemented upstream Endpoint rate limits</summary>
```suggestion
<summary>Implemented upstream endpoint rate limits</summary>
```

2024-08-07 15:11 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Introduced new controls to configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs. This feature allows for more granular protection of upstream services from abuse, similar
Updated wording in the change log item but discovered that the links are rendered within the HTML block as raw markdown so have removed the links. I have added the links to the release highlights block for endpoint request rate limiting

2024-08-07 15:13 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Now configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs, providing granular protection for upstream services against abuse.
Reworded and included links in this release highlights paragraph

2024-08-07 15:15 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +We've added support for using root Certificate Authority (CA) certificates as client certificates in API definitions. The system now authenticates clients with certificates signed by the configured r
Updated wording in the HTML section but the links display as raw markdown links. Have incorporated suggested wording and added links to release highlights paragraph.

2024-08-07 15:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Simplify certificate management with support for root Certificate Authority (CA) certificates, enabling client authentication via certificates signed by the configured root CA.
updated wording and included links

2024-08-07 15:21 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +Introduced a new configuration for API versioning with `url_versioning_pattern`. This regex-based field helps identify if the first part of a URL is a version pattern, improving control over `strip_v
Updated with suggestion but had to remove links since the raw markdown link is displayed in the HTML.

2024-08-07 15:22 UTC, dcs3spp commented
API Versioning is missing from release highlights

2024-08-07 16:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +| [Go](https://go.dev/dl/)                                     | 1.19 (GQL), 1.21 (GW)  | 1.19 (GQL), 1.21 (GW)  | [Go plugins]({{< ref "/plugins/supported-languages/golang" >}}) must be built using
```suggestion
| [Go](https://go.dev/dl/)                                     | 1.21  |  1.21  | [Go plugins]({{< ref "/plugins/supported-languages/golang" >}}) must be built using Go 1.21 | 
```

I understand that GQL library has now been built with Go 1.21.

2024-08-08 09:09 UTC, dcs3spp approved these changes

2024-08-08 09:10 UTC, dcs3spp commented
Thanks @andyo-tyk I have approved PR for GW release notes

2024-08-08 14:06 UTC, andyo-tyk requested changes
The release highlights are at the wrong header level, otherwise LGTM

2024-08-08 14:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +### Per Endpoint Rate Limiting
```suggestion
#### Per Endpoint Rate Limiting
```

2024-08-08 14:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +### Root CA Support for Client Certificates
```suggestion
#### Root CA Support for Client Certificates
```

2024-08-08 14:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +### Optimised AST Document Handling
```suggestion
#### Optimised AST Document Handling
```

2024-08-08 14:44 UTC, dcs3spp commented
> The release highlights are at the wrong header level, otherwise LGTM

Thanks @andyo-tyk good spot! I have committed the suggestions

2024-08-08 15:26 UTC, andyo-tyk approved these changes
Thanks - happy to approve :)

2024-08-12 15:31 UTC, merged

2024-08-12 15:31 UTC, dcs3spp commented
/release to release-5.5