[DX-1499] Dashboard 5.5 release notes
TykTechnologies/tyk-docs-hugo pull request #5045
Opened 2024-07-09 17:21 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

[DX-1499]((https://tyktech.atlassian.net/browse/DX-1499))

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-07-10 13:09 UTC, dcs3spp requested changes
Thanks @Eopayemi Could you remove the empty release notes file at 

tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md

2024-07-30 09:28 UTC, dcs3spp requested changes
Thanks @Eopayemi for adding changelog for release 5.5.0. I have made minor suggestions, regarding capitailisation of summary items and moving 2 changelog items to fixed and changed sections. I pushed some changes to the remote branch to add sub headings for release highlights section. Before making anyupdates remember to pull latest changes into your local copy

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Add upgrade steps here if necessary.
Remember to either remove this sentence if there are no upgrade steps or remember to add any specific upgrade instructions for the release

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +We are excited to announce Tyk Dashboard 5.5, featuring a brand-new dashboard identity, advanced rate-limiting capabilities, and enhanced security options. For a comprehensive list of changes, please
Add a link to the changelog below, same as for 5.4.0. Use release notes for 5.4.0 as a guide/example

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Experience a refreshed and modern look with our updated dashboard brand identity. The new design enhances usability and provides a cleaner, more intuitive interface for managing your APIs.
Add screenshot below the sentence to showcase the new UI of the Dashboard or link to a page including new UI

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> + Introduced new controls to configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs. This feature allows for more granular protection of upstream services from abuse, simila
Remove space at start of sentence and use italics for the keywords:

```suggestion
Introduced new controls to configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs. This feature allows for more granular protection of upstream services from abuse, similar to Tyk’s traditional *API-level* or *Global* rate limits but applied specifically at the endpoint level.
```

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Dashboard support for upstream endpoint rate limits Added</summary>
make added lowercase Added -> added

```suggestion
<summary>Dashboard support for upstream endpoint rate limits added</summary>
```

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Added new controls to configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs. This feature aims to protect upstream services from abuse, providing the same functionality as
```suggestion
Added new controls to configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs. This feature aims to protect upstream services from abuse, providing the same functionality as Tyk’s traditional *API-level* or *Global* rate limits but at a more granular level.
```

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<details>
Should this be in the changed section?

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<details>
Should this be in fixed section?

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Fixed an issue where nested API endpoints, such as '/test' and '/test/abc', might incorrectly apply middleware from the parent path to the nested path. The fix ensures that API endpoint definitions a
```suggestion
Fixed an issue where nested API endpoints, such as `/test` and `/test/abc`, might incorrectly apply middleware from the parent path to the nested path. The fix ensures that API endpoint definitions are correctly ordered, preventing this middleware misapplication and ensuring both the HTTP method and URL match accurately.
```

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Enhanced API versioning with fallback option for 'First of Path' version data location</summary>
```suggestion
<summary>Enhanced API versioning with fallback option for *First of Path* version data location</summary>
```

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Introduced a new configuration for API versioning with 'url_versioning_pattern'. This regex-based field helps identify if the first part of a URL is a version pattern, improving control over 'strip_v
Surround config params with backticks:

```suggestion
Introduced a new configuration for API versioning with `url_versioning_pattern`. This regex-based field helps identify if the first part of a URL is a version pattern, improving control over `strip_versioning_data` and `fallback_to_default` functionalities.
```

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Improved Schema editor functionality for GQL APIs</summary>
```suggestion
<summary>Improved schema editor functionality for GQL APIs</summary>
```

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +### Release Date xxx
Remember to add release date

2024-07-30 09:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +| 5.5.0 | MDCB v2.6.0     | MDCB v2.5.1 |
Update recommended releases and backwards compatibility for this release

2024-08-07 16:06 UTC, andyo-tyk requested changes
Feedback from review - some duplicate entries, some that are Gateway only.

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +#### Root CA support for client certificate authentication
```suggestion
```

This is a Gateway feature

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +We've added support for using root Certificate Authority (CA) certificates as client certificates in API definitions. This enhancement simplifies certificate management by allowing the system to auth
```suggestion
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Experience a refreshed and modern look with our updated dashboard brand identity. The new design enhances usability and provides a cleaner, more intuitive interface for managing your APIs.
```suggestion
Experience a refreshed and modern look with our updated brand identity. The new design enhances usability and provides a cleaner, more intuitive interface for managing your APIs.
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +#### New Dashboard brand identity
```suggestion
#### New Tyk brand identity
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Introduced new controls to configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs. This feature allows for more granular protection of upstream services from abuse, similar
```suggestion
Now configure rate limits at the endpoint level for both [Tyk OAS]({{< ref "product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas" >}}) and [Tyk Classic APIs]({{< ref "product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic" >}}), providing granular protection for upstream services against overloading and abuse.
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +#### Implemented Upstream Endpoint rate limits
```suggestion
#### Per Endpoint Rate Limiting
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Introduced a UI for configuring the new upstream endpoint rate limit middleware in the OAS Designer.
```suggestion
Rate limits can now be configured at the endpoint level in Tyk OAS and Tyk Classic API definitions. Configure these new more granular controls from the API Designer. 
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Dashboard support for upstream endpoint rate limits added</summary>
```suggestion
<summary>Configure the new endpoint level rate limits in API Designer</summary>
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Enhancement: Root CA Support for client certificate authentication</summary>
```suggestion
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +We've added support for using root Certificate Authority (CA) certificates as client certificates in API definitions. The system now authenticates clients with certificates signed by the configured r
```suggestion

```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary> Implemented upstream endpoint rate limits</summary>
```suggestion
```

Duplicate

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Added new controls to configure rate limits at the endpoint level for both Tyk OAS and Tyk Classic APIs. This feature aims to protect upstream services from abuse, providing the same functionality as
```suggestion
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Enhanced API versioning with fallback option for *First of Path* version data location</summary>
```suggestion
<summary>Improved handling of requests to non-existent versions of APIs when using URL path versioning</summary>
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<details>
Yes please!

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Updated npm packages for the Dashboard UI application to support React v18.
```suggestion
Updated npm package dependencies of Dashboard, to address security vulnerabilities.
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<details>
No, this is a new feature

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Introduced a new configuration for API versioning with `url_versioning_pattern`. This regex-based field helps identify if the first part of a URL is a version pattern, improving control over `strip_v
```suggestion
When configuring API versioning settings for Tyk OAS APIs, you can now set a *Version Identifier Pattern* when using the URL path to indicate the API version (for example `/v1/my-api`). This will be used to avoid accidentally stripping part of the target URL (and failed upstream proxy) if the client doesn't provide any version identifier. If you're using Tyk Classic APIs you can set the `url_versioning_pattern` field in the API definition using the raw API editor.
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Corrected ordering of OAS API paths to prevent Middleware misapplication</summary>
```suggestion
```

Gateway feature

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Fixed an issue where nested API endpoints, such as `/test` and `/test/abc`, might incorrectly apply middleware from the parent path to the nested path. The fix ensures that API endpoint definitions a
```suggestion
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Resolved SSE streaming issue</summary>
```suggestion
```

Gateway feature

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Addressed a bug that caused Server Side Event (SSE) streaming responses to be considered for caching, which required buffering the response and prevented SSE from being correctly proxied.
```suggestion
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Classic raw editor gains Endpoint rate limiter configuration</summary>
```suggestion
```

Duplicate

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Added functionality for users to configure rate limits per endpoint using the raw API definition for classic Tyk APIs.
```suggestion
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Save API button now visible for all users</summary>
```suggestion
<summary>Save API button now visible for SSO users</summary>
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +Addressed an issue in SSO where user permissions were not correctly applied, ensuring the Save API button is visible to all users in the Dashboard UI.
```suggestion
Addressed an issue for SSO users where user permissions were not correctly applied. This led to the Save API button not being visible to all appropriate users in the API Designer.
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> + <summary>Empty Endpoint popularity page issue resolved in version 5.3.1</summary>
```suggestion
 <summary>Resolved issue with no analytics data showing on Endpoint Popularity page</summary>
```

2024-08-07 16:06 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> + Addressed an issue where the Dashboard displayed an empty page when accessing Activity by Endpoint information after upgrading to Tyk 5.3.1. Users can now see all necessary information.
```suggestion
Addressed an issue where the Dashboard displayed a blank pane when accessing the Activity by Endpoint page after upgrading to Tyk 5.3.1.
```

2024-08-08 09:38 UTC, dcs3spp approved these changes
PR LGTM, approved, need to update release date once confirmed and requires peer approval from available PM

2024-08-08 13:53 UTC, andyo-tyk requested changes
Please can you move the NPM change to the "Changed" section and tweak this change log title?

2024-08-08 13:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Updated NPM packages for React v18</summary>
Please move this to the Changed section

2024-08-08 13:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Response Plugins Issue with OAS API Definition Resolved</summary>
```suggestion
<summary>Resolved an issue seen when using reponse plugins with Tyk OAS APIs</summary>
```

2024-08-08 14:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +<summary>Updated NPM packages for React v18</summary>
@andyo-tyk @Eopayemi 

moved and updated

2024-08-08 15:28 UTC, andyo-tyk approved these changes
Thanks - happy to approve :)

2024-08-12 16:15 UTC, merged

2024-08-12 16:15 UTC, dcs3spp commented
/release to release-5.5