Large update to event handling
TykTechnologies/tyk-docs-hugo pull request #5051
Opened 2024-07-10 15:36 UTC by andyo-tyk

### Preview Link

### Description
Restructured event handling, moved some other pages for clarity (e.g. logging -> observability)
Added new page for existing logging event handler (previously undocumented)
Overhauled webhook event handler docs including new support in Tyk OAS

2024-07-11 04:44 UTC, lghiur commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +title: Event handling with webhooks
in the UI this is too long IMO. Just webhooks would do it

2024-07-11 04:44 UTC, lghiur commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +## When to use webhook event handlers
can we make it clear that these are just a few exapmples?

2024-07-11 04:44 UTC, lghiur approved these changes

2024-07-11 08:52 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +title: Event handling with webhooks
The key terminology that I've adopted throughout this PR is that it refers to event handling... and in this case, with webhooks. I want to avoid any risk of confusion with API webhooks - here we are talking only about system events, not business logic.

2024-07-11 08:56 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +## When to use webhook event handlers
I've adopted this approach in various pages - I guess we could add a short statement under this header to say "there are many occasions when you might use webhooks for event handling, here are a few examples...". Something like this?

2024-07-11 09:06 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +## When to use webhook event handlers
I've added this line.

2024-07-15 13:14 UTC, jeffy-mathew approved these changes

2024-07-15 13:14 UTC, jeffy-mathew commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/custom-handlers-javascript.md
> +A custom event handler consists of a function that accepts two variables ()`event` and `context`) and has no return value.
```suggestion
A custom event handler consists of a function that accepts two variables (`event` and `context`) and has no return value.
```

2024-07-15 13:14 UTC, jeffy-mathew commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
> +- `RateLimitSmoouthingDown`: the [intermediate rate limit allowance]({{< ref "getting-started/key-concepts/rate-limiting#rate-limit-smoothing" >}}) has been decreased for a specific key
```suggestion
- `RateLimitSmoothingDown`: the [intermediate rate limit allowance]({{< ref "getting-started/key-concepts/rate-limiting#rate-limit-smoothing" >}}) has been decreased for a specific key
```

2024-07-15 13:51 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
> +## Token lifecycle events
```suggestion
### Token lifecycle events
```

2024-07-23 13:28 UTC, dcs3spp requested changes
PR LGTM @andyo-tyk , made some minor suggestions/observations

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events.md
> +In response to an API, token lifecycle or custom event occuring, at the API-level you can:
What  does it refer to when mentioning in response an API, is it an API request?

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events.md
> +When an API event is fired, if there is an event handler registered for that combination of API and event then the handler will be provided with a rich set of [metadata]({{< ref "basic-config-and-sec
```suggestion
When an API event is fired, if there is an event handler registered for an event from that API then the handler will be provided with a rich set of [metadata]({{< ref "basic-config-and-security/report-monitor-trigger-events/event-data" >}}) that can be used by the external system (webhook) or custom (JavaScript) code to determine the action to be taken.
```

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/custom-handlers-javascript.md
> +It is important to note that unlike custom JavaScript [plugins]({{< ref "plugins/supported-languages/javascript-middleware" >}}), custom event handlers execute in a *global* JavaScript environment. T
```suggestion
It is important to note that unlike custom JavaScript [plugins]({{< ref "plugins/supported-languages/javascript-middleware" >}}), custom event handlers execute in a *global* JavaScript environment. This means that you need to be careful when naming the event handlers: if you use the same event handler name for different event handling code across two APIs, only one of them will execute, as the other will be overridden when loaded.
```

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/custom-handlers-javascript.md
> +It is populated with the the API ID and Org ID of the request that your custom function can use together with the `event` metadata to interact with the Tyk REST API functions, for example:
Fix typo:

```suggestion
It is populated with the API ID and Org ID of the request that your custom function can use together with the `event` metadata to interact with the Tyk REST API functions, for example:
```

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-data.md
> +The `OriginatingRequest` metadata is a Base64-encoded wire-protocol representation of the original request to the event handler, if you are running a service bus or queue that stores failed, throttle
```suggestion
The `OriginatingRequest` metadata is a Base64-encoded wire-protocol representation of the original request to the event handler. If you are running a service bus or queue that stores failed, throttled or other types of requests, you can decode this object and parse it in order to re-create the original intent of the request (e.g. for post-processing).
```

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
> +- `BreakerTriggered`: a circuit breaker has changed state, this is generated when either a `BreakerTripped`, or a `BreakerReset` event occurs; a status code in the metadata passed to the webhook will
Is there duplicate events created? Could _BreakerTripped_ and _BreakerReset_ events be deprecated and _BreakerTriggered_ event updated to include the details in the event payload? Or, deprecated the BreakerTriggered event?

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/instrumentation.md
> +`statsd_connection_string` is a formatted string that specifies how to connect to the StatsD server. It typically includes information such as the host address, port number, and sometimes additional
Add example of statsd connection string or link to an example

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/instrumentation.md
> +Tyk Gateway has been instrumented for NewRelic metrics since v2.5. Simply add the following config section to `tyk.conf` to enable the instrumentation and generation of data:
In addition to integrating Tyk with [New Relic Application Performance Monitoring](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/introduction-apm/) agents, can Tyk Gateway integrate with an Open Telemetry Collector?
- https://docs.newrelic.com/docs/opentelemetry/get-started/opentelemetry-get-started-intro/
- https://github.com/open-telemetry/opentelemetry-collector-contrib

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/monitors.md
> +You can set user- or organisation-specific trigger levels by adding a `monitor` section to the user's access key ([Session Object]({{< ref "getting-started/key-concepts/what-is-a-session-object" >}})
Is *user-* a typo?

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +In the context of Tyk Gateway, webhooks are event handlers that can be registered against API Events. The webhook will be triggered when the corresponding event is fired and will send a customisable
```suggestion
In the context of Tyk Gateway, webhooks are event handlers that can be registered against API Events. The webhook will be triggered when the corresponding event is fired and will send a customizable fixed payload to any open endpoint.
```

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +It is very likely that an `AuthFailure` event will fire on the same endpoint more than once if the requesting client is automated. If this event triggered a webhook that caused an email to be sent, t
Is there an example that can be added or linked to here?

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +*Global webhook definitions* are registered with the Dashboard using the [UI](#creating-a-global-webhook-definition-using-tyk-dashboard) or [Dashboard API]({{< ref "tyk-apis/tyk-dashboard-api/web-hoo
What link should be used for the empty link [Dashboard API]({{< ref "" >}})?

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/observability.md
> +- Metrics: quantitative measurements of system performance and behavior over time
```suggestion
- **Metrics**: quantitative measurements of system performance and behavior over time
```

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/observability.md
> +- Logs: detailed records of events and state changes within the system
```suggestion
- **Logs**: detailed records of events and state changes within the system
```

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/observability.md
> +- Traces: end-to-end tracking of requests as they flow through distributed systems
```suggestion
- **Traces**: end-to-end tracking of requests as they flow through distributed systems
```

2024-07-23 13:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/report-monitor-and-trigger-events/event-webhook-tyk-oas.md
> +[Webhooks]({{< ref "basic-config-and-security/report-monitor-trigger-events/webhooks" >}}) are event handlers that can be registered against API Events. The webhook will be triggered when the corresp
```suggestion
[Webhooks]({{< ref "basic-config-and-security/report-monitor-trigger-events/webhooks" >}}) are event handlers that can be registered against API Events. The webhook will be triggered when the corresponding event is fired and will send a customizable fixed payload to any open endpoint.
```

2024-08-05 16:16 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events.md
> +In response to an API, token lifecycle or custom event occuring, at the API-level you can:
This is a list of different event types: API event, token lifecycle event, custom event. I'll reword this to improve clarity (as I agree this is open to misinterpretation).

2024-08-05 16:52 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events.md
> +When an API event is fired, if there is an event handler registered for that combination of API and event then the handler will be provided with a rich set of [metadata]({{< ref "basic-config-and-sec
I'll apply this change.

2024-08-05 16:55 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
> +- `BreakerTriggered`: a circuit breaker has changed state, this is generated when either a `BreakerTripped`, or a `BreakerReset` event occurs; a status code in the metadata passed to the webhook will
Yes, multiple events are triggered. Theoretically this could be simplified, but would be a breaking change so needs to be carefully managed.

2024-08-05 16:56 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/instrumentation.md
> +`statsd_connection_string` is a formatted string that specifies how to connect to the StatsD server. It typically includes information such as the host address, port number, and sometimes additional
Improved

2024-08-05 17:02 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/instrumentation.md
> +Tyk Gateway has been instrumented for NewRelic metrics since v2.5. Simply add the following config section to `tyk.conf` to enable the instrumentation and generation of data:
This PR is about event handling - this page was in the wrong place in the docs so I've moved it into the appropriate section (Observability). To my understanding we don't yet have OpenTelemetry metrics support.

2024-08-05 17:20 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/monitors.md
> +You can set user- or organisation-specific trigger levels by adding a `monitor` section to the user's access key ([Session Object]({{< ref "getting-started/key-concepts/what-is-a-session-object" >}})
This was intended to be short for "user-specific or organisation-specific". I'll rework this section slightly to improve ligibility.

2024-08-05 17:22 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +It is very likely that an `AuthFailure` event will fire on the same endpoint more than once if the requesting client is automated. If this event triggered a webhook that caused an email to be sent, t
Examples are provided in the Tyk OAS and Tyk Classic specific pages. This page is an introduction to the concepts.

2024-08-05 17:23 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
> +*Global webhook definitions* are registered with the Dashboard using the [UI](#creating-a-global-webhook-definition-using-tyk-dashboard) or [Dashboard API]({{< ref "tyk-apis/tyk-dashboard-api/web-hoo
Link added.

2024-08-06 08:13 UTC, dcs3spp approved these changes

2024-08-06 08:14 UTC, merged

2024-08-06 08:14 UTC, dcs3spp commented
/release to release-5.4