Operator docs revamp
TykTechnologies/tyk-docs-hugo pull request #5053
Opened 2024-07-10 16:24 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-07-11 08:23 UTC, dcs3spp requested changes
PR LGTM @caroltyk I have made some minor comments and suggestions

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/custom-resources.md
> +## What is a Custom Resource?
Remove this section heading so that paragraph is an intro paragraph

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/operator-user.md
> +For the Tyk Dashboard, Tyk Operator functions as a system user, bound by Organization and RBAC rules.
Should include a diagram to illustrate this concept?

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/version-compatibility.md
> +---
Q: will there be other reference guides added here in the future?

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/release-notes/overview.md
> +## Operator Releases
Remove _Operator Releases_ heading duplicates the page title. Maybe replace with an introduction sentence.

I think this new page is good to have since it paves the way to add some UI in future, similar to the [release notes landing page ](https://tyk.io/docs/developer-support/tyk-release-summary/overview/).

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/tyk-operator.md
> +4. [As Kubernetes Ingress Controller]({{< ref "product-stack/tyk-operator/tyk-ingress-controller">}})
```suggestion
4. [Kubernetes Ingress Controller]({{< ref "product-stack/tyk-operator/tyk-ingress-controller">}})
```

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/version-compatibility.md
> +## Compatibility with Tyk
Remove heading that duplicates page title

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/version-compatibility.md
> +| Tyk Version          | 3.2 | 4.0 | 4.1 | 4.2 | 4.3 | 5.0 | 5.2 | 5.3 | 5.4 |
Q: Should replace Y with check marks like in this [page](https://tyk.io/docs/nightly/plugins/plugin-types/request-plugins/)?

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/tyk-operator.md
> +Tyk Operator is a Kubernetes Operator designed to simplify the management of Tyk API configurations both inside and outside of Kubernetes environments. With our [custom resources]({{<ref "product-sta
Add links to Argo CD and Flux CD and insert space for ArgoCD as shown in suggestion:

```suggestion
Tyk Operator is a Kubernetes Operator designed to simplify the management of Tyk API configurations both inside and outside of Kubernetes environments. With our [custom resources]({{<ref "product-stack/tyk-operator/key-concepts/custom-resources">}}), Tyk Operator simplifies the processes of deploying and configuring API resources, allowing you to focus more on application development and less on infrastructure management. It is ideal for those who like to manage configurations declaratively or with GitOps workflows via tools such as Argo CD and Flux CD.
```

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/operator-user.md
> +| `TYK_MODE` | “ce” for OSS or "pro" for licensed users |
```suggestion
| `TYK_MODE` | "ce" for OSS or "pro" for licensed users |
```

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/operator-user.md
> +These would be the default credentials Tyk Operator use to connect to Tyk.
```suggestion
These would be the default credentials Tyk Operator uses to connect to Tyk.
```

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/operator-user.md
> +Tyk Operator is a cluster resource, and it is not safe to run multiple Tyk Operator deployment in a single cluster. However, this raises the question of how to handle scenarios where multiple teams o
```suggestion
Tyk Operator is a cluster resource, and it is not safe to run multiple Tyk Operator deployments in a single cluster. However, this raises the question of how to handle scenarios where multiple teams or departments need to manage their own API configurations using different credentials.
```

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/custom-resources.md
> +| Kind               | Group       | Version   | Description                                                                                       |
If all the values are the same for the group and version column maybe remove these columns and mention in a sentence that introduces the table. Same with the other table below

2024-07-11 08:23 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/key-concepts.md
> -## Operator User
Is there any other overview information that could be added to the page to make the content longer, or should the page now be removed?

2024-07-11 10:32 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/custom-resources.md
> +| Kind               | Group       | Version   | Description                                                                                       |
they may be different in future

2024-07-11 10:35 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/version-compatibility.md
> +## Compatibility with Tyk
Because there are 2 kinds of "version compatibility", 1 on compatibility with Tyk version, 1 on compatibility with Kubernetes version

2024-07-11 10:41 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/key-concepts.md
> -## Operator User
Nothing to add at the moment.

2024-07-11 10:42 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/version-compatibility.md
> +---
yes

2024-07-11 14:50 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/key-concepts.md
> -## Operator User
Ok thanks @caroltyk I have updated so that this page is removed and redirects to tyk-operator overview page. I have updated the overview page so that add key concepts links in getting started section

2024-07-11 14:55 UTC, dcs3spp approved these changes

2024-07-11 14:55 UTC, dcs3spp commented
@caroltyk Once peer approved will merge and release to 5.4 release

2024-07-16 06:55 UTC, komalsukhani requested changes

2024-07-16 06:55 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/key-concepts/custom-resources.md
> +Tyk follows standard practices for naming and versioning custom resources as outlined by the Kubernetes Custom Resource Definition [versioning guidelines](https://kubernetes.io/docs/tasks/extend-kube
```suggestion
Tyk follows standard practices for naming and versioning custom resources as outlined by the Kubernetes Custom Resource Definition [versioning guidelines](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/). Although we are currently on the `v1alpha1` version, no breaking changes will be introduced to existing Custom Resources without a version bump. This means that any significant changes or updates that could impact existing resources will result in a new version (e.g., `v1beta1` or `v1`) and Operator will continue supporting all CRD versions for a reasonable time before deprecating an older version. This ensures a smooth transition and compatibility, allowing you to upgrade without disrupting your current configurations and workflows.
```

2024-07-16 08:45 UTC, komalsukhani approved these changes

2024-07-16 09:51 UTC, merged

2024-07-16 09:53 UTC, yurisasuke commented
/release to release-5.4