[DX-1507] Dashboard 5.3.3 release notes
TykTechnologies/tyk-docs-hugo pull request #5056
Opened 2024-07-11 11:07 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1507](https://tyktech.atlassian.net/browse/DX-1507)

---

### Preview Link

<br>

### Description

5.3.3 release notes for Dashboard

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-07-11 12:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +
@Eopayemi Can you add sections in the changelog for changed and added

2024-07-29 12:00 UTC, Eopayemi commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +
Added in

2024-07-29 13:12 UTC, dcs3spp requested changes
Thanks @Eopayemi PR LGTM, as you have mentioned we need to add release date once confirmed. I have made minor suggestions to PR concerning captilisations, otherwise all good

2024-07-29 13:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Dashboard blank page issue when retrieving key for API with mTLS and Dynamic JWT Auth fixed</summary>
make Dynamic lowercase (Dynamic -> dynamic)

2024-07-29 13:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Save API Button now visible for all users</summary>
Update so that Button is lowercase (Button -> button)

2024-08-01 16:47 UTC, dcs3spp approved these changes
Thanks @Eopayemi I have approved and once release date added and approved by PM will merge and release

2024-08-02 10:42 UTC, lghiur approved these changes

2024-08-02 10:53 UTC, merged

2024-08-02 10:53 UTC, dcs3spp commented
/release to release-5.4

2024-08-02 10:55 UTC, dcs3spp commented
/release to release-5.3