[DX-1507] Gateway 5.3.3 release notes
TykTechnologies/tyk-docs-hugo pull request #5057
Opened 2024-07-11 11:23 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1507](https://tyktech.atlassian.net/browse/DX-1507)

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-07-11 12:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +
@Eopayemi Can you add changelog sections for add and changed?

2024-07-29 11:52 UTC, Eopayemi commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +
Added in.

2024-07-29 13:09 UTC, dcs3spp requested changes
Thanks @Eopayemi PR LGTM, as you have mentioned, PR needs updating with release date once available. I have made minor observations/suggestions on the PR relating to captilisation of changelog items in fixes section

2024-07-29 13:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> + <summary>Optimised Key Creation to Reduce Redundant Redis Commands</summary>
Only Optimised and Redis should have capitals

2024-07-29 13:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Resolved SSE Streaming Issue</summary>
Only Resolved and SSE should have capitals

2024-08-01 16:46 UTC, dcs3spp approved these changes
Thanks @Eopayemi I have approved and once release date added and PM approved will merge and release

2024-08-01 16:46 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +### Release Date xxx
Remember to add release date

2024-08-02 10:42 UTC, lghiur approved these changes

2024-08-02 10:49 UTC, merged

2024-08-02 10:49 UTC, dcs3spp commented
/release to release-5.4

2024-08-02 10:51 UTC, dcs3spp commented
/release to release-5.3