[DX-1437] organise --> organize (PR 1)
TykTechnologies/tyk-docs-hugo pull request #5065
Opened 2024-07-11 16:58 UTC by Roeegg2

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-07-11 18:43 UTC, letzya commented on tyk-docs/content/shared/dashboard-config.md
@dcs3spp we need to open a pr for this change

2024-07-11 18:44 UTC, letzya commented on tyk-docs/content/shared/dashboard-config.md
@Roeegg2 can you please remove this change as it's an auto-gen file from code so we'll change the source

2024-07-11 18:44 UTC, letzya commented on tyk-docs/content/tyk-on-premises/bootstrapper-cli.md
> +         --create-org           Create a new organization.
This is output of a cli, we can't change it here. Please remove these changes

2024-07-12 08:16 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
> +1. From the **API Consumers > Organizations** menu, click **Add**.
cannot be changed as it's in the product (in the UI)

2024-07-12 08:16 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
> +{{< img src="/img/dashboard/portal-management/enterprise-portal/organisations-menu.png" alt="Portal Organizations menu" >}}
You can't change the path of existing URL

2024-07-12 08:29 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
> +1. From the **API Consumers > Organizations** menu, click **Add**.
```suggestion
1. From the **API Consumers > Organisations** menu, click **Add**.

**Note:** We are transitioning from GB to US notation. Some terms (e.g., UI, config files, APIs) still use GB notation. In this case, we use *organisation* with an *s* as appears in the source.
```

2024-07-12 09:00 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md
> +{{< img src="/img/dashboard/portal-management/enterprise-portal/become_an_organisation_navbar.png" alt="Become an organization button" >}}
please fix the change in the url

2024-07-12 09:37 UTC, Roeegg2 commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
> +{{< img src="/img/dashboard/portal-management/enterprise-portal/organisations-menu.png" alt="Portal Organizations menu" >}}
I only changed the alt tag, not the path. Should I revert the changes anyway?

2024-07-12 09:38 UTC, Roeegg2 commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md
> +{{< img src="/img/dashboard/portal-management/enterprise-portal/become_an_organisation_navbar.png" alt="Become an organization button" >}}
> I only changed the alt tag, not the path. Should I revert the changes anyway?
Same here

2024-07-12 09:52 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
https://github.com/TykTechnologies/tyk-analytics/pull/4072

2024-07-12 12:17 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
> +1. From the **API Consumers > Organizations** menu, click **Add**.
deleting this

2024-07-12 12:28 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/email-customization.md
Please remove this file from the PR. We'll change it all together

2024-07-12 12:29 UTC, letzya requested changes
Remove tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/email-customization.md from the pr

2024-07-12 15:29 UTC, letzya approved these changes

2024-07-12 17:13 UTC, letzya approved these changes

2024-07-12 17:24 UTC, merged

2024-07-12 17:24 UTC, letzya commented
/release to release-5.4