[TT-12648] Migrate API Definition and policy feature list to docs
TykTechnologies/tyk-docs-hugo pull request #5102
Opened 2024-07-16 12:42 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labelled** the PR

2024-07-23 15:25 UTC, dcs3spp requested changes
@caroltyk PR looking good to me. I have noticed the PR is in draft status and have performed an initial review with minor suggestions / observations:

- Expand abbreviation instances for CR and CRD Add an introduction paragraph that explains the objectives of the quick start and what the user will achieve
- Summarise what each Quickstart does before the yaml file is included
- Fix links in Quickstart and supported features table in content file tyk-docs/content/product-stack/tyk-operator/reference/security-policy.md
- Fix links in tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +# Introduction
Remove # Introduction section heading and start with the introduction paragraph to avoid duplicating the H1 heading

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +kubectl apply -f config/samples/federation/users-subgraph.yaml
Before each example, briefly explain where the sample yaml files originate from, e.g. are they in the operator or the tyk Gateway repository?

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +SubGraph CRD takes `schema` and `sdl` values for your subgraph. However, creating SubGraph CRD is inadequate to use it as
Expand CRD abbreviation instances, e.g. Custom Resource Definitions (CRD). Not sure what is meant by _However, creating SubGraph CRD is inadequate to use it as regular ApiDefinition_

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +regular ApiDefinition. SubGraph must be referred by ApiDefinition object through `graphql.graph_ref` field, as follows:
Add additional explanation here. For example, is the subgraph in field _graphql.graph_ref_ referenced through the _metadata.name_ field and is that field specified dynamically by the user or fixed statically?

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +3. `graphql.graph_ref` must be set to the name of the SubGraph resource that you would like to refer.
Maybe expand this to mention that it is the name included in the metadata section.

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +3. `graphql.graph_ref` must be set to the name of the SuperGraph resource that you would like to refer.
update to mention that the name field is located within the metadata section of the SuperGraph resource

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +- Subgraph CR,
Always try to expand abbreviation instances, e.g. Custom Resource (CR)

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +1. Update Users SubGraph CRD,
Why will Tyk Operator update the Users Subgraph CRD when it has been updated by the developer?

Explain what details will be updated by Tyk Operator

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +In order to delete this subgraph, corresponding ApiDefinition CR must be updated, such that it has no reference to the
```suggestion
In order to delete this subgraph, the corresponding ApiDefinition CR must be updated, such that it has no reference to the
```

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +In order to delete this subgraph, SuperGraph CR should not have reference to corresponding subgraph in the `subgraph_ref`.
```suggestion
In order to delete this subgraph, SuperGraph CR should not have reference to corresponding subgraph in the `subgraph_ref`.
```

Does Tyk provide a linter to detect this scenario?

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +If the supergraph is not referenced in any ApiDefinition CRD, it can be deleted as follows:
Add blank line before example

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +In order to delete this supergraph, ApiDefinition that has a reference to the supergraph must de-reference the supergraph
```suggestion
In order to delete this supergraph, the ApiDefinition that has a reference to the supergraph must de-reference the supergraph
```

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +or be deleted.
Does this mean that the APIDefinition or the SuperGraph should be deleted?

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/management-of-api.md
> +For Tyk Classic API, you can specify the category name using the `spec.name` field with a `#` qualifier. This will categorize the API in the Tyk Dashboard.
```suggestion
For a Tyk Classic API, you can specify the category name using the `spec.name` field with a `#` qualifier. This will categorize the API in the Tyk Dashboard.
```

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/management-of-api.md
> +To configure API versions in the `ApiDefinition` custom resource, use the `spec.version_datas` object.
Expand sentence to mention that an API version can be specified in the header, url or url parameter

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-graphql.md
> +
Add an intro paragraph explaining what the objectives are of the quick start and what the user will achieve

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-http.md
> +
Add an introduction paragraph that explains the objectives of the quick start and what the user will achieve

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-http.md
> +# Delete a secret
Does the content represented by the comments need explaining in the introduction for the HTTPS Proxy section?

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-tcp.md
> +
Add an introduction paragraph that explains the objectives of the quick start and what the user will achieve

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-udg.md
> +
Add an introduction paragraph that explains the objectives of the quick starts in this page and what the user will achieve

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-udg.md
> +
Add a summary that explains what this example does

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-udg.md
> +If you are on Tyk 3.1, you can use the following manifest to create an UDG API.
Expand with a summary that explains what example does

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/security-policy.md
> +Please visit [one of the examples](./policies/api_access.md) from the Supported Feature list below to get started
Fix links here and in supported features table

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/access-an-api.md
> +Tyk Operator supported authentication types are listed in [API Definition features]({{<ref "product-stack/tyk-operator/reference/api-definition">}}) page.
```suggestion
Tyk Operator supported authentication types are listed in the [API Definition features]({{<ref "product-stack/tyk-operator/reference/api-definition">}}) page.
```

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/create-an-api.md
> +Creating an API takes the same approach whether you are using Tyk Open Source or Self Managed. First, specify the details of your API using the [ApiDefinition CRD]({{<ref "product-stack/tyk-operator/
```suggestion
Creating an API takes the same approach whether you are using Tyk Open Source or Self Managed. First, specify the details of your API using the [ApiDefinition CRD]({{<ref "product-stack/tyk-operator/reference/api-definition">}}), then deploy it to create the corresponding Kubernetes resource. Tyk Operator will take control of the CRD and create the actual API in the Tyk data plane.
```

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/create-an-api.md
> +You can visit [ApiDefinition CRD]({{<ref "product-stack/tyk-operator/reference/api-definition">}}) page to see all the latest API Definitions fields and features we support.
```suggestion
You can visit the [ApiDefinition CRD]({{<ref "product-stack/tyk-operator/reference/api-definition">}}) page to see all the latest API Definitions fields and features we support.
```

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
> +title: Protect an API with Policy
```suggestion
title: Protect an API with a Security Policy
```

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
> +You can go to the [Security Policy features]({{<ref "product-stack/tyk-operator/reference/security-policy">}}) page to see all the latest Security Policies fields and features Operator support.
```suggestion
You can visit the [Security Policy features]({{<ref "product-stack/tyk-operator/reference/security-policy">}}) page to see all the latest Security Policies fields and features Tyk Operator supports.
```

2024-07-23 15:25 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
> +You can do so either by applying the above manifest:
What is the alternative to applying the above manifest implied by _either_

2024-08-20 13:58 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/reference/security-policy.md
> +| Per API limit              | ❌ |
@caroltyk I have raised a PR to add support of API limits in Operator https://github.com/TykTechnologies/tyk-operator-internal/pull/45.

2024-08-23 12:20 UTC, dcs3spp commented
@caroltyk I have merged the API global and endpoint level feature examples included in the Google Spreadsheet into this PR. I have added preview links and summary of potential missing examples to this PR description

2024-08-23 15:41 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +1. Update Users SubGraph CRD,
@buraksekili could you explain what will be updated by Tyk Operator?

2024-08-23 15:41 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +In order to delete this subgraph, SuperGraph CR should not have reference to corresponding subgraph in the `subgraph_ref`.
@buraksekili can you confirm?

2024-08-23 15:42 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +or be deleted.
The ApiDefinition

2024-08-23 16:14 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/management-of-api.md
> +To configure API versions in the `ApiDefinition` custom resource, use the `spec.version_datas` object.
Migrated this example to http://localhost:1313/docs/nightly/getting-started/key-concepts/versioning/#configuring-api-versioning-in-tyk-operator

2024-08-23 16:34 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/security-policy.md
> +| Per API limit              | ❌ |
to be updated when we release it

2024-08-23 17:07 UTC, dcs3spp commented
@caroltyk [commit](https://github.com/TykTechnologies/tyk-docs/pull/5102/commits/69dab4d39f58890f22f92625f8ff79aa18d2298b) removes file tyk-docs/content/product-stack/tyk-operator/advanced-configurations/api-versioning.md

That content file is currently referenced from the API definition table in file tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md

For the Hugo build and CI checks to succeed the API definition table should be updated to remove the link to the deleted file (api versioning) and we should also setup a redirect to an alternative location if users visit that URL for the removed file.

Which URL should _product-stack/tyk-operator/advanced-configurations/api-versioning_ redirect to in order to avoid 404 page not found errors?

2024-08-27 08:54 UTC, caroltyk commented
> @caroltyk [commit](https://github.com/TykTechnologies/tyk-docs/pull/5102/commits/69dab4d39f58890f22f92625f8ff79aa18d2298b) removes file tyk-docs/content/product-stack/tyk-operator/advanced-configurations/api-versioning.md
> 
> That content file is currently referenced from the API definition table in file tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> 
> For the Hugo build and CI checks to succeed the API definition table should be updated to remove the link to the deleted file (api versioning) and we should also setup a redirect to an alternative location if users visit that URL for the removed file.
> 
> Which URL should _product-stack/tyk-operator/advanced-configurations/api-versioning_ redirect to in order to avoid 404 page not found errors?

I've fixed the link in last commit.

2024-08-28 11:03 UTC, dcs3spp requested changes
Added review to versioning and made minor suggestions

2024-08-28 11:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
> +To create a SuperGraph API in Tyk, you can reference the supergraph's metadata name through graphql.graph_ref field, as follows:
```suggestion
To create a SuperGraph API in Tyk, you can reference the supergraph's metadata name through `graphql.graph_ref field`, as follows:
```

2024-08-28 11:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/management-of-api.md
> +To configure API versions in the `ApiDefinition` custom resource, use the `spec.version_datas` object.
@caroltyk remember to remove the API Versioning tag and update the description of the markdown file in front matter / header section of - tyk-docs/content/product-stack/tyk-operator/advanced-configurations/management-of-api.md - so that it it does not reference API versioning in the description.

2024-08-28 11:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-http.md
> +
Similar to the other examples should we summarise what the example does for HTTPS proxy and explain the certificate section with domains.

2024-08-28 11:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-http.md
> +In thiis example, requests to `httpbin.tyk.io` will be proxied to upstream URL `http://httpbin.org`
```suggestion
In this example, requests to `httpbin.tyk.io` will be proxied to upstream URL `http://httpbin.org`
```

2024-08-28 11:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-http.md
> +    kind: Issuer
Are these comments needed? If so is it better to add the valid Kinds and explain in accompanying content?

2024-08-28 11:03 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +```yaml
Add syntax highlighting and add accompanying explanation similar to other examples, e.g. explain that the version information in the example is contained in the header x-api-version and give other valid location values, e.g. url-param and url. Explain that versions are included in versions section

2024-08-29 11:31 UTC, dcs3spp commented
@caroltyk I have added explanation to example of Tyk Operator API versioning and linked from Tyk Operator API Management section:

- [API Versioning](https://deploy-preview-5102--tyk-docs.netlify.app/docs/nightly/getting-started/key-concepts/versioning/#tyk-operator)
- [Link to API Versioning from Tyk Operator Managing APIs](https://deploy-preview-5102--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-operator/advanced-configurations/management-of-api/#api-versioning)

2024-08-30 08:46 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +- A *pre* plugin hook configuration block is specified at line 16, containing the *name* and *path* for our plugin. The name matches the name of the middleware variable in the source file. The path c
List and explain the different options of "driver" and plugin type (pre / post / ...)

So that this page can be a reference for all types of custom plugins.

2024-08-30 08:49 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Custom Plugins - Python              | ⚠️         | v0.1           | Untested                                                               |
We can combine all the different custom plugins into one row, and restructure the example to explain what users need to do to configure different plugin languages (driver)

2024-08-30 08:56 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-classic.md
> +## Configuring the middleware in Tyk Operator {#tyk-operator}
add an example for Config Data here too.
https://github.com/TykTechnologies/tyk-operator/blob/master/config/samples/config_data_virtual_endpoint.yaml

2024-08-30 09:14 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
> +For further examples check out the [internal looping]({{< ref "/product-stack/tyk-operator/advanced-configurations/internal-looping" >}}) page.
Example for advanced trigger:

          "extended_paths": {
            "url_rewrites": [
              {
                "disabled": false,
                "path": "asf",
                "method": "GET",
                "match_pattern": "asf",
                "rewrite_to": "",
                "triggers": [
                  {
                    "on": "any",
                    "options": {
                      "query_val_matches": {
                        "aaa": {
                          "match_rx": "ggg",
                          "reverse": false
                        }
                      },
                      "header_matches": {},
                      "path_part_matches": {},
                      "session_meta_matches": {},
                      "request_context_matches": {},
                      "payload_matches": {
                        "match_rx": ""
                      }
                    },
                    "rewrite_to": "dsdgsdg"
                  }
                ]
              }
            ]
          }

2024-08-30 09:15 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| URL Rewrite (Advanced Trigger)    | ❌        | -              | -                                              | |
We should support. To be tested and confirm.

2024-08-30 09:19 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Go Plugin                         | ❌        | -              | -                                              |  |
rename to Per-Endpoint Plugin (go)

2024-08-30 09:20 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Analytics API Tagging (Tag Headers)  | ✅        | v0.10.0        | Untested                                                               |
remove "Untested"

2024-08-30 09:23 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Looping                              | ⚠️         | v0.6           | Untested                                                               | [Internal Looping]({{< ref "advanced-configuration/tran
Example links should be product-stack/tyk-operator/advanced-configurations/internal-looping/. We can change it to "supported"

2024-08-30 09:24 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/internal-looping.md
> +Tyk Operator simplifies the management and transformation of API traffic within Kubernetes environments. The concept of [internal looping]({{< ref "advanced-configuration/transform-traffic/looping" >
confirm we document this behavior:

Currently the support for looping with the operator is inconsistent/not supported. 
Customers can use looping in the operator only because we allow API names to be used in a looping call. This creates inconstancies because in the operator context we want users to user the namespace/name combo for the API/policy names. 
Its a very small change and an easy win.  
 
Current behaviour:
traget_url: tyk://namespace/api_name
Expected:
traget_url: tyk://base64(namespace/api_name)
The encode function does not get run on the target_url value. This is used in the case of looping calls

2024-08-30 09:26 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Rate Limit                        | ?         | -              | -                                              | [Rate Limit]({{<ref "product-stack/tyk-gateway/middleware/endpoint-rate-limit-class
Don't support

2024-08-30 11:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Go Plugin                         | ❌        | -              | -                                              |  |
updated

2024-08-30 11:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Analytics API Tagging (Tag Headers)  | ✅        | v0.10.0        | Untested                                                               |
updated

2024-08-30 11:33 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Looping                              | ⚠️         | v0.6           | Untested                                                               | [Internal Looping]({{< ref "advanced-configuration/tran
updated

2024-08-30 16:50 UTC, dcs3spp commented
@caroltyk as discussed I will wait to review / update etc. I did not realise that Komal and you had done a code review together. Let me know when changes have been committed from the code review that you performed with Komal and I will review / update.

2024-08-30 17:04 UTC, caroltyk commented
> @caroltyk as discussed I will wait to review / update etc. I did not realise that Komal and you had done a code review together. Let me know when changes have been committed from the code review that you performed with Komal and I will review / update.

Thank you @dcs3spp 

I have committed an update for:
- Update API definition feature support status
- Add internal looping for proxy example
- Fix Config Data example link
- Update URL rewrite example to align with Classic API Definition examples, and add example for URL rewrite triggers

2024-08-30 17:10 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +- A *pre* plugin hook configuration block is specified at line 16, containing the *name* and *path* for our plugin. The name matches the name of the middleware variable in the source file. The path c
All different types of custom plugins (go / javascript / ...) can be supported by Tyk Operator using the same fields. Users just need to provide different values for "driver" and configure the type of plugins to use pre / post / etc. The details of what Gateway support is documented here: https://tyk.io/docs/plugins/supported-languages/

@dcs3spp can you help with adding an Introduction paragraph to explain this?

2024-08-30 17:37 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Analytics API Tagging (Tag Headers)  | ✅        | v0.10.0        |                                                             |
Add link to the example at "tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics/#tyk-operator"

2024-08-30 17:39 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Do not track Analytics (per API)     | ✅        | v0.1.0         | -                                                                      |
Add link to example /product-stack/tyk-gateway/middleware/do-not-track-tyk-classic/

2024-09-02 11:17 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Analytics API Tagging (Tag Headers)  | ✅        | v0.10.0        |                                                             |
updated

2024-09-02 11:17 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Do not track Analytics (per API)     | ✅        | v0.1.0         | -                                                                      |
Updated

2024-09-02 12:17 UTC, dcs3spp commented
Thanks @caroltyk I have added an introduction section to [custom plugins](https://deploy-preview-5102--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-operator/advanced-configurations/custom-plugins) for review. In the introduction section I have explained the parameters for configuring plugins (to reference local source code functions that implement plugins) and linked to how configure [custom analytics plugins](https://deploy-preview-5102--tyk-docs.netlify.app/docs/nightly/plugins/plugin-types/analytics-plugins). I also added a note explaining that [per-endpoint](https://deploy-preview-5102--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/middleware/endpoint-plugin/) plugins are unsupported by Tyk Operator as illustrated in the [API Definition](https://deploy-preview-5102--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-operator/reference/api-definition/#endpoint-level-features) table.

Do we have examples for how to configure Tyk Operator to use plugin bundles (fetch bundled zip file containing source code and config) and using plugin bundles with gRPC plugins?

2024-09-03 10:25 UTC, dcs3spp commented
@caroltyk I have updated Tyk Operator PR with a note of examples that are not yet documented with a link to contact us form. I added[introduction to the custom plugins example](https://deploy-preview-5102--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-operator/advanced-configurations/custom-plugins/) as requested in review.

Would you and Komal be able to review again to enable the merge and release today.

This is a [link](https://github.com/TykTechnologies/tyk-docs/pull/5102/commits/0c9dc7ad6bfa682f000ad620918a672e425bf8e4) to the commit that includes updates to the API Definition table with a note for undocumented examples:
- context variables
- custom plugins (mentions plugin bundles do not have examples)
- detailed recording (in Log Browser)
- internal API (not exposed by Gateway)

The commit also includes an update o the gRPC page to [mention that plugin bundles example not yet documented for gRPC](https://deploy-preview-5102--tyk-docs.netlify.app/docs/nightly/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin/#tyk-operator-1)

2024-09-03 13:43 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +Using [Tyk Classic APIs]({{< ref "plugins/supported-languages/rich-plugins/rich-plugins-work#basic-usage" >}}) developers can implement API-level custom plugins that can be optionally setup to execut
Why do we link to "plugins/supported-languages/rich-plugins/rich-plugins-work#basic-usage"? Should we point users to more generic page like https://tyk.io/docs/plugins?

2024-09-03 13:53 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +Please refer to [Analytics Plugins]({{< ref "plugins/plugin-types/analytics-plugins" >}}) to learn how to configure Analytics plugins using Tyk Operator.
```suggestion
This document explains how to configure following plugin types with different drivers (plugin languages):
- Pre (Request)
- Authentication
- Post-Auth (Request)
- Post (Request)
- Response

Please refer to [Analytics Plugins]({{< ref "plugins/plugin-types/analytics-plugins" >}}) to learn how to configure Analytics plugins using Tyk Operator.
```

2024-09-03 13:56 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +## Tyk Operator Example
```suggestion
## Example: configure custom plugin (JavaScript) with Tyk Operator
```

2024-09-03 14:00 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
>  | Custom Plugins                       | ✅       | v0.1           | Currently this feature is not documented for plugin bundles. For further details please [contact us](https://tyk.io/contact) | [Cus
Can we move this comment to "product-stack/tyk-operator/advanced-configurations/custom-plugins"?

2024-09-03 14:01 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Custom Plugins                       | ✅       | v0.1           | Currently this feature is not documented for plugin bundles. For further details please [contact us](https://tyk.io/contact) | [Cus
can we move the comments to page "product-stack/tyk-operator/advanced-configurations/custom-plugins"?

2024-09-03 14:02 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +
Add a note that plugin bundle is also supported by Tyk Operator. Example documentation is not available at the moment.

2024-09-03 14:05 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Analytics API Tagging (Tag Headers)  | ✅        | v0.10.0        | - | [Custom Analytics]({{< ref "tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics#tyk-operator" >}}) |
```suggestion
| Custom Analytics Tags (Tag Headers)  | ✅        | v0.10.0        | - | [Custom Analytics Tags (Tag Headers)]({{< ref "tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics#tyk-operator" >}}) |
```

2024-09-03 14:13 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
> +| Custom Plugins                       | ✅       | v0.1           | Currently this feature is not documented for plugin bundles. For further details please [contact us](https://tyk.io/contact) | [Cus
Custom Plugin --> Custom Plugins

2024-09-03 16:05 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +Using [Tyk Classic APIs]({{< ref "plugins/supported-languages/rich-plugins/rich-plugins-work#basic-usage" >}}) developers can implement API-level custom plugins that can be optionally setup to execut
Discussed in meeting earlier, removed link since equivalent Tyk Classic API example is included on this page

2024-09-03 16:48 UTC, dcs3spp approved these changes

2024-09-04 12:19 UTC, komalsukhani requested changes

2024-09-04 12:19 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +Tyk Operator also supports configuring custom plugins to use plugin bundles, where the source code and associated configuration is packaged into a zip file and uploaded to a remote webserver. Tyk Gat
```suggestion
Tyk Operator also supports configuring custom plugins using plugin bundles, where the source code and associated configuration is packaged into a zip file and uploaded to a remote webserver. Tyk Gateway will then download, extract, cache and execute the plugin bundles for each of the configured phases of the [API request lifecycle]({{< ref "concepts/middleware-execution-order" >}}).
```

2024-09-04 12:19 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +Using Tyk Classic APIs developers can implement API-level custom plugins that can be optionally setup to execute for each of the following [hooks]({{< ref "plugins/plugin-types/plugintypes#plugin-and
```suggestion
Using Tyk Classic APIs, developers can implement API-level custom plugins that can be optionally setup to execute for each of the following [hooks]({{< ref "plugins/plugin-types/plugintypes#plugin-and-hook-types" >}}) in the API request lifecycle: [Pre (Request)]({{< ref "plugins/plugin-types/request-plugins" >}}), [Authentication]({{< ref "plugins/plugin-types/auth-plugins/auth-plugins" >}}), [Post (Request)]({{< ref "plugins/plugin-types/request-plugins" >}}), [Post Authentication]({{< ref "plugins/plugin-types/request-plugins" >}}), [Response]({{< ref "plugins/plugin-types/response-plugins" >}}) and [Analytics]({{< ref "plugins/plugin-types/analytics-plugins" >}}). Subsequently, users can execute, or “hook”, their plugin into these phases of the API request lifecycle based on their specific use case.
```

2024-09-04 12:19 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +In Tyk Classic APIs, the *custom_middleware* section of the Tyk Classic API Definition is where you configure plugins that will run at different points during the lifecycle of an API request.
```suggestion
In Tyk Classic APIs, the *custom_middleware* section is where you configure plugins that will run at different points during the lifecycle of an API request.
```

2024-09-04 12:19 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +                "disabled": false,
We don't have `disabled` field in Operator.

2024-09-04 12:19 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +The example API Definition resource listed below listens on path */httpbin* and forwards requests upstream to *http://httpbin.org*.
```suggestion
The example API Definition resource listed below listens on path */httpbin* and forwards requests to upstream *http://httpbin.org*.
```

2024-09-04 12:25 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +                "disabled": false,
removed `disabled` fields.

2024-09-04 13:29 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +                "disabled": false,
Also removed `disabled` field from fields explanation list below example

2024-09-04 13:32 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +In Tyk Classic APIs, the *custom_middleware* section of the Tyk Classic API Definition is where you configure plugins that will run at different points during the lifecycle of an API request.
@komalsukhani This section is intended to give a Tyk Classic API API Definition for configuring plugins. The subsequen section then shows a Tyk Operator API Definition resources

2024-09-04 13:36 UTC, dcs3spp commented
@caroltyk I have moved the unsupported and undocumented features as subsections of the _How it works section_

2024-09-04 13:47 UTC, dcs3spp commented
@komalsukhani if you are ok with the changes and comment response would you be able to approve and I will merge and release

2024-09-05 06:23 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
> +In Tyk Classic APIs, the *custom_middleware* section of the Tyk Classic API Definition is where you configure plugins that will run at different points during the lifecycle of an API request.
@dcs3spp I removed that bit as since already starts with In Tyk Classic APIs.
Anyway, not a major issue.

2024-09-05 06:26 UTC, komalsukhani approved these changes

2024-09-05 08:03 UTC, merged

2024-09-05 08:03 UTC, dcs3spp commented
/release to release-5.5

2024-09-05 08:08 UTC, dcs3spp commented
/release to release-5.5

2024-09-05 08:18 UTC, dcs3spp commented
/release to release-5.5

2024-09-05 08:21 UTC, yurisasuke commented
/release to release-5.5