Reworked API versioning
TykTechnologies/tyk-docs-hugo pull request #5109
Opened 2024-07-16 15:51 UTC by andyo-tyk

@dcs3spp please wait for peer review before DX review.

### Preview Link

### Description
Reworked the API versioning pages to improve clarity and consistency between Tyk Classic and Tyk OAS APIs.
A couple of minor changes in other pages where I spotted typos.

2024-07-16 16:07 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +The Base API is a working version of the API and is usually the only one configured as an *External API*, so that client requests and initially handled (and routed) according to the configuration set
```suggestion
The Base API is a working version of the API and is usually the only one configured as an *External API*, so that client requests are handled (and routed) according to the configuration set in the Base API.
```

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +When you implement versioning for a **Tyk OAS API**, you're essentially creating distinct iterations of your API, each with its own API definition file, allowing almost complete differentiation of co
just visually I think would be good to have subtitles for tyk OAS and classic, and not just bold

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +Here's a comparison of some of the features that can be configured per-version (✅) or only per-API (❌️) between Tyk OAS and Tyk Classic APIs. Note that this is not a comprehensive list - to see all t
the only things that you can configure for a version in classic API are endpoint middleware. Maybe a phrase stating that would clarify it? I think exceptions might be global header transform and upstream url. Not sure about request size limit?

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +Typically Tyk will pass all request headers and parameters to the upstream service when proxying the request. The upstream (target) URL will be constructed by combining the configured `targetURL` wit
targetUrl is a clasic definition field, and it's not written like this. If you want to refer to api definition fields I suggest to use just OAS ones, and in square brackets to place the classic API Def corespondent?

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +Typically Tyk will pass all request headers and parameters to the upstream service when proxying the request. The upstream (target) URL will be constructed by combining the configured `targetURL` wit
in OAS is upstream.url

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +Typically Tyk will pass all request headers and parameters to the upstream service when proxying the request. The upstream (target) URL will be constructed by combining the configured `targetURL` wit
`stripVersioningData (strip_versioning_data for Tyk Classic APIs)` this one I like it

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +You can explicitly grant access to specific version(s) of an API by specifying only those version(s) in the [key]({{< ref "tyk-apis/tyk-gateway-api/token-session-object-details" >}}) (also known as a
For OAS Ones, they would need to select another API from the list basically, we need also to improve the UX for OAS APIs in that area.

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +You can explicitly grant access to specific version(s) of an API by specifying only those version(s) in the [key]({{< ref "tyk-apis/tyk-gateway-api/token-session-object-details" >}}) (also known as a
This phrase won't work for OAS APIs, since you don't metion the versiosn of an OAS API in the key, you use the API itself

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +When using Tyk OAS APIs there are some subtleties to the propagation of access control between versions of an API due to the sharing of one API definition for all versions:
yup :D this one is good, a bit conflicting with the above phrase

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +- a *key* will only have access to the `default` version if it explicitly has access to that version (e.g. if `v2` is set as default, a *key* must have access to `v2` to be able to fallback to the de
this bullet point is relevant for classic apis

2024-07-17 05:52 UTC, lghiur commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +- `name`: an identifier for this version of the API, for example `default` or `v1`
I think, the string `self` also is accepted.

2024-07-17 15:32 UTC, andyo-tyk reviewed
Responded to comments - will make changes locally and push to github

2024-07-17 15:32 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +When you implement versioning for a **Tyk OAS API**, you're essentially creating distinct iterations of your API, each with its own API definition file, allowing almost complete differentiation of co
I'll revise this

2024-07-17 15:32 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +Here's a comparison of some of the features that can be configured per-version (✅) or only per-API (❌️) between Tyk OAS and Tyk Classic APIs. Note that this is not a comprehensive list - to see all t
I've based this on the fields available in the API definition (i.e. those that are in the versions section). I prefer the visual impact of this table which should help to encourage users to transition to Tyk OAS.

2024-07-17 15:32 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +Typically Tyk will pass all request headers and parameters to the upstream service when proxying the request. The upstream (target) URL will be constructed by combining the configured `targetURL` wit
Yes, I aim to use the Tyk OAS field names, with a reference to the Classic alternative. I'll correct this.

2024-07-17 15:32 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +You can explicitly grant access to specific version(s) of an API by specifying only those version(s) in the [key]({{< ref "tyk-apis/tyk-gateway-api/token-session-object-details" >}}) (also known as a
Yes we do - but I think the docs are sufficient here. The fact that for Tyk OAS a version is an API whilst for Tyk Classic it's a "name" within a single API def should be understood by this point.

2024-07-17 15:32 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +You can explicitly grant access to specific version(s) of an API by specifying only those version(s) in the [key]({{< ref "tyk-apis/tyk-gateway-api/token-session-object-details" >}}) (also known as a
I'll clarify this.

2024-07-17 15:32 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +When using Tyk OAS APIs there are some subtleties to the propagation of access control between versions of an API due to the sharing of one API definition for all versions:
Oops, copy/paste error. Will correct.

2024-07-17 15:32 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +- a *key* will only have access to the `default` version if it explicitly has access to that version (e.g. if `v2` is set as default, a *key* must have access to `v2` to be able to fallback to the de
I determined these bullet points by experimentation, so I think this is OK (and the same for the notes on the classic API page)

2024-07-17 15:32 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +- `name`: an identifier for this version of the API, for example `default` or `v1`
I think this comment is supposed to be against the next line `default`?

2024-07-22 08:44 UTC, rewsmith requested changes
Wow, that is some PR @andyo-tyk.  You've explaining a really complex topic very well. Just a couple of things to clarify and a typo to fix

2024-07-22 08:44 UTC, rewsmith commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +- [Request heade](#request-header)
Typo - should be Request header

2024-07-22 08:44 UTC, rewsmith commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- if a *key* is granted access to the `default` version of an API, then it will inherit access to all other versions of the API (including new versions as they are created)
Is this really the case??  Perhaps I am misunderstanding but I tested (in 5.4) adding a new version where a key already existed with access to default.  I observed a 403 when trying to access the new version with the existing key

2024-07-22 08:44 UTC, rewsmith commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +When you first create a Tyk Classic API, it will not be "versioned" (i.e. `not_versioned` will be set to `true`) and there will be a single `Default` version created in the `version_data` section of
Perhaps clarify this is only the case when you "Design from scratch".  If you import from OAS, versioning is enabled.

2024-07-23 10:37 UTC, dcs3spp requested changes
PR LGTM @andyo-tyk I have made minor suggestions and spotted some broken internal links.

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +API versioning is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
Which endpoints in the Tyk Dashboard API or add a link to the section that explains them.

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +Tyk OAS introduces the concept of a **Base API**, which acts as a "parent" API version that acts as a router for requests to the different versions of the API. The Base API definition stores the info
Remove duplication of acts as:

```suggestion
Tyk OAS introduces the concept of a **Base API**, which acts as a "parent" API version that routes requests to the different versions of the API. The Base API definition stores the information required for Tyk Gateway to locate and route requests to the appropriate "child" API version.
```

Mention that the Base API stores the API ID and version identifier for child APIs and routes requests to the required child API version using the version provided by the client in the header, url or url parameter.

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +- `versions`: a list of key-value pairs storing details of the *child APIs*
Include an example here, e.g. { "version-id-1": "v1" }

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +The Base API is a working version of the API and is usually the only one configured as an *External API*, so that client requests are handled (and routed) according to the configuration set in the Ba
routed via the version identifier included in the header, url or url parameter

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `not_versioned`: set to `true` to treat this as a versioned API
for config key name not_versioned should this be set to false to treat it as a versioned API?

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `expires`: an optional expiry date for the API after which Tyk will reject any access request
Maybe explain the required date format for the expiry date here

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `global_*`: configuration of [API-level middleware]({{< ref "advanced-configuration/transform-traffic" >}})
Add examples to give context to the global parameter wildcard, e.g. global_size_limit etc.

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `default`: not used by versioning
Should the default, enabled, name, strip_path and versions fields be removed from the list because they are not used by versioning? Or alternatively in the sentence above add a sentence explaining these fields are not used but should be present with empty default values, e.g. _versions: {}_ etc?

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +You'll be taken to the API designer view for the new version - remember that this will be a completely separate Tyk OAS API Definition for the new version. By default, Tyk Dashboard will have given t
link to step 1 is broken

2024-07-23 10:37 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +- `default`: the `name` of the API definition that shall be treated as *default* (for [access control](#ccontrolling-access-to-tyk-oas-api-versions) and [default fallback]({{< ref "product-stack/tyk-
access control link is broken, think it is because of a typo in the link

2024-07-24 07:25 UTC, andrei-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
> +- [Request heade](#request-header)
Fixed

2024-07-24 07:27 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- if a *key* is granted access to the `default` version of an API, then it will inherit access to all other versions of the API (including new versions as they are created)
I believe this is only specific to Tyk Clasic APIs , have you tested with that or in a different setup?

2024-07-24 07:30 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +When you first create a Tyk Classic API, it will not be "versioned" (i.e. `not_versioned` will be set to `true`) and there will be a single `Default` version created in the `version_data` section of
Added

2024-07-24 07:53 UTC, rewsmith commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- if a *key* is granted access to the `default` version of an API, then it will inherit access to all other versions of the API (including new versions as they are created)
I tested with Tyk Classic APIs in 5.4

2024-07-24 08:06 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +API versioning is configured in the [Tyk OAS API Definition]({{< ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}}). You can do this via the Tyk Dashboard API or in the API Designer.
Fixed

2024-07-24 08:06 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +Tyk OAS introduces the concept of a **Base API**, which acts as a "parent" API version that acts as a router for requests to the different versions of the API. The Base API definition stores the info
Fixed

2024-07-24 08:09 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +- `versions`: a list of key-value pairs storing details of the *child APIs*
Added list example

2024-07-24 08:39 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +The Base API is a working version of the API and is usually the only one configured as an *External API*, so that client requests are handled (and routed) according to the configuration set in the Ba
Added

2024-07-24 08:39 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `not_versioned`: set to `true` to treat this as a versioned API
Fixed

2024-07-24 08:40 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `expires`: an optional expiry date for the API after which Tyk will reject any access request
Added

2024-07-24 08:42 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `global_*`: configuration of [API-level middleware]({{< ref "advanced-configuration/transform-traffic" >}})
Added

2024-07-24 09:10 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `default`: not used by versioning
I think here there was a confusion; those fields are actually used; will rewrite this

2024-07-24 09:15 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `default`: not used by versioning
Rewritten

2024-07-24 09:16 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +You'll be taken to the API designer view for the new version - remember that this will be a completely separate Tyk OAS API Definition for the new version. By default, Tyk Dashboard will have given t
Fixed

2024-07-24 09:17 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +- `default`: the `name` of the API definition that shall be treated as *default* (for [access control](#ccontrolling-access-to-tyk-oas-api-versions) and [default fallback]({{< ref "product-stack/tyk-
Fixed

2024-07-25 11:31 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `default`: not used by versioning
Thanks @andrei-tyk I think the rewrite should be peer reviewed also.

I see that _strip_path_ is deprecated, does it default to _strip_path: ""_. Is this automatically generated in the API Definition or does the user have to manually include it as empty in the API Definition?

Same question for the _versions_ field.

2024-07-25 11:59 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/oas-versioning.md
> +The Base API is a working version of the API and is usually the only one configured as an *External API*, so that client requests are handled (and routed) according to the configuration set in the Ba
Thanks @andrei-tyk

2024-07-25 12:36 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `default`: not used by versioning
<img width="652" alt="image" src="https://github.com/user-attachments/assets/03d5f32e-c317-41a4-841e-a7170d07535a">
This has been added yesterday, for some reason github still shows the old variant here in the review comment even tough it has been modfieid.

2024-07-26 10:47 UTC, andrei-tyk commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- if a *key* is granted access to the `default` version of an API, then it will inherit access to all other versions of the API (including new versions as they are created)
Removed this zone as I couldn't find the pieces of logic @andyo-tyk  was reffering to.

2024-07-26 12:05 UTC, rewsmith approved these changes
LGTM

2024-07-26 13:05 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/versioning.md
> +- `default`: not used by versioning
Thanks as discussed remove full stop after strip_path then will resolve

2024-07-29 05:54 UTC, titpetric approved these changes

2024-07-30 10:06 UTC, dcs3spp approved these changes

2024-07-30 10:09 UTC, merged