[TT-12662] endpoint rate limit
TykTechnologies/tyk-docs-hugo pull request #5110
Opened 2024-07-18 08:00 UTC by titpetric

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-07-18 09:39 UTC, andyo-tyk submitted a review, later dismissed
Lots of suggestions, trying to match the style of other middleware pages as closely as possible. Corrected a couple of errors (e.g. OAS contract) and proposed change to the advanced example.

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                    "rate_limit": {
```suggestion
                    "rateLimit": {
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +The `rate_limit` object has the following configuration:
```suggestion
The `rateLimit` object has the following configuration:
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +The rate limit middleware can be added to the `operations` section of the
```suggestion
The rate limit middleware (`rateLimit`) can be added to the `operations` section of the
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +title: Using the Rate Limit Middleware with Tyk Classic APIs
```suggestion
title: Using the Rate Limit middleware with Tyk Classic APIs
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +
```suggestion

If you’re using the newer Tyk OAS APIs, then check out the [Tyk OAS](https://tyk.io/docs/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas/) page.
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +~~~
```suggestion
```json  {linenos=true, linenostart=1}
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +~~~
```suggestion
```
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +~~~
This should  be ``` according to the style guide (and for consistency with other pages). Sadly Github "suggested change" turned this into a line delete. :(

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +    "use_extended_paths": true,
I haven't typically included this line in the other middleware examples, though I guess it does no harm (and should probably be added to the other pages), just a minor inconsistency.

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +`rate_limit` array. For example, to limit POST requests to `/user/login`
```suggestion
`rate_limit` array. For example, if you wanted to limit the rate of `POST` requests to
your API allowing a higher rate to one specific endpoint you could configure the API definition as follows: 
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +to 100 requests per second and apply a regex pattern for other endpoints:
```suggestion
```

I don't think we need this detail here, as it's covered in the explanation after the example.

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +In this advanced example, the first rule limits POST requests to
```suggestion
In this example, the first rule limits `POST` requests to
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +`/user/login` to 100 requests per second. Any other GET request matching
```suggestion
`/user/login` to 100 requests per second (rps). Any other `POST` request matching
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +                "method": "GET",
```suggestion
                "method": "POST",
```

Wouldn't this example work better if these are both POST? There's no conflict (AFAIK) between a POST /user/login and a GET /.* -> the order of these would not matter, as a GET request won't match the regex due to the different HTTP method used.

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +title: Using the Rate Limit Middleware with Tyk OAS APIs
```suggestion
title: Using the Rate Limit middleware with Tyk OAS APIs
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +on specific endpoints. This middleware is configured in the Tyk OAS API
```suggestion
on specific endpoints. This middleware is configured in the [Tyk OAS API
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +Definition, either via the Tyk Dashboard API or in the API Designer.
```suggestion
Definition](https://tyk.io/docs/tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc/#operation), either via the Tyk Dashboard API or in the API Designer.
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +## Configuring a Rate Limit in the Tyk OAS API Definition
```suggestion
## Configuring a rate limit in the Tyk OAS API Definition
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +## Configuring the Rate Limit Middleware in the Tyk Classic API Definition
```suggestion
## Configuring a rate limit in the Tyk Classic API Definition
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +- `rate`: the number of requests allowed
```suggestion
- `rate`: the maximum number of requests that will be permitted during the interval (window)
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +- `per`: the time period in seconds
```suggestion
- `per`: the length of the interval (window) in time duration notation (e.g. 10s)
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +- `rate`: the number of requests allowed
```suggestion
- `rate`: the maximum number of requests that will be permitted during the interval (window)
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +- `per`: the time period in seconds
```suggestion
- `per`: the length of the interval (window) in seconds
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                        "per": 1
```suggestion
                        "per": "1s"
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +~~~
```suggestion
```
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +~~~
Again, this should be ```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +In this example Tyk OAS API definition, the rate limit has been
```suggestion
In this example, a rate limit has been
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +
```suggestion

The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the Per-endpoint Rate Limiter middleware.
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +paths. The order of evaluation matches the order defined in the
```suggestion
paths. The order of evaluation matches the order that endpoints are defined in the
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +~~~
```suggestion
```json {hl_lines=["39-43"],linenos=true, linenostart=1}
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +`rate_limit` array. For example, to limit POST requests to `/user/login`
```suggestion
`paths` section of the OpenAPI description. For example, if you wanted to limit the rate of `POST` requests to your API allowing a higher rate to one specific endpoint you could configure the API definition as follows: 
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +to 100 requests per second and apply a regex pattern for other endpoints:
```suggestion
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +~~~
```suggestion
```json {hl_lines=["47-51", "54-58"],linenos=true, linenostart=1}
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                    "rate_limit": {
```suggestion
                    "rateLimit": {
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                    "rate_limit": {
```suggestion
                    "rateLimit": {
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                        "per": 1
```suggestion
                        "per": "1s"
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                        "per": 1
```suggestion
                        "per": "1s"
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +In this advanced example, the first rule limits POST requests to
```suggestion
In this example, the first rule limits requests to the
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +`/user/login` to 100 requests per second. Any other GET request matching
```suggestion
`POST /user/login` endpoint to 100 requests per second (rps). Any other `POST` request to an endpoint path that matches
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +the regex pattern `/{any}` will be limited to 60 requests per second. The
```suggestion
the regex pattern `/{any}` will be limited to 60 rps. The
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +order of evaluation ensures that the specific `/user/login` endpoint is
```suggestion
order of evaluation ensures that the specific `POST /user/login` endpoint is
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                "anyget": {
```suggestion
                "anypost": {
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +            "get": {
```suggestion
            "post": {
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                "operationId": "anyget",
```suggestion
                "operationId": "anypost",
```

2024-07-18 09:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +matched and evaluated before the regex pattern.
```suggestion
matched and evaluated before the regex pattern.

The configuration above is a complete and valid Tyk OAS API Definition that you can import into Tyk to try out the Per-endpoint Rate Limiter middleware.
```

2024-07-19 07:25 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +    "use_extended_paths": true,
just added as it's required for extended_paths to work, no deeper purpose. As it's +1 line, it doesn't hurt

2024-07-19 07:29 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +~~~
@andyo-tyk just to clarify, you want to intentionally highlight lines 39-43, should a similar highlight block be defined for classic?

2024-07-19 07:32 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +the regex pattern `/{any}` will be limited to 60 requests per second. The
rejecting this, should be RPS but i don't feel it adds something by abbreviating

2024-07-19 15:58 UTC, andyo-tyk reviewed
Sorry, missed a couple of things.

2024-07-19 15:58 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +```json {hl_lines=["47-51", "54-58"],linenos=true, linenostart=1}
```suggestion
```json {hl_lines=["49-53", "56-60"],linenos=true, linenostart=1}
```

2024-07-19 15:58 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +
```suggestion

IIf you’re using the legacy Tyk Classic APIs, then check out the [Tyk Classic](https://tyk.io/docs/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic/) page.

```

2024-07-19 15:58 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                "operationId": "user/loginget",
```suggestion
                "operationId": "user/loginpost",
```

Sorry, think I missed this before - the operationId usually merges path with method

2024-07-19 15:58 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +                "user/loginget": {
```suggestion
                "user/loginpost": {
```

To match the correction above

2024-07-22 08:44 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +regex pattern `/.*/` will be limited to 60 requests per second. The order
the configured pattern is `/.*`, but it says it would match `/.*/`, is that right?

2024-07-22 08:44 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +60 rps. The order of evaluation ensures that the specific `POST
Is this order of evaluation taken care of by the library?

2024-07-22 09:45 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +regex pattern `/.*/` will be limited to 60 requests per second. The order
```suggestion
regex pattern `/.*` will be limited to 60 requests per second. The order
```

2024-07-22 09:50 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +60 rps. The order of evaluation ensures that the specific `POST
It's OAS.Paths, as they get extracted into tyk classic. Can remove the note if confusing?

2024-07-23 11:07 UTC, dcs3spp requested changes
PR LGTM @titpetric

I have made minor suggestions to fix broken links and add section for configuring via the API designer if rate limits can be configured that way also

2024-07-23 11:07 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +`/status/{code}`. These wildcards are so they are human-readable and do
So variable substitution is not used here: `/status/abcd` would select this endpoint path because of the wildcard (.*) under the hood, yes?

2024-07-23 11:07 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +[Tyk OAS](https://tyk.io/docs/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas/) page.
broken link:

```suggestion
[Tyk OAS]({{< ref "/tyk-gateway/middleware/endpoint-rate-limit-oas" >}}) page.
```

2024-07-23 11:07 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
> +on specific endpoints. This middleware is configured in the [Tyk OAS API
broken link, remove line break in link name and use the following link:

[Tyk OAS API Definition]({{< ref "/tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc#operation" >}})

2024-07-23 11:07 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +and evaluated before the regex pattern.
Can rate limits be configured using the Classic API Designer or only via the raw API definition?

2024-07-23 12:58 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +and evaluated before the regex pattern.
only raw api for classic, no UI if that's what you're asking

2024-07-23 13:55 UTC, dcs3spp approved these changes

2024-07-23 13:58 UTC, dcs3spp commented
Thanks @titpetric I have approved PR. @andyo-tyk @jeffy-mathew could you approve if changes are ok?

2024-07-23 16:44 UTC, jeffy-mathew approved these changes

2024-07-24 15:46 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
> +
brilliant addition!

2024-07-26 09:58 UTC, merged