add RBAC info
TykTechnologies/tyk-docs-hugo pull request #512
Opened 2018-07-31 09:17 UTC by marksou

2018-08-01 10:35 UTC, asoorm requested changes
minor change

2018-08-01 10:35 UTC, asoorm commented on tyk-docs/content/security/dashboard/create-user-groups.md
> +
Remove extra new-line

2018-08-02 08:34 UTC, marksou commented
@asoorm Removed line. @davegarvey can you review?

2018-08-02 08:35 UTC, asoorm approved these changes

2018-08-02 08:37 UTC, merged