MDCB healthcheck
TykTechnologies/tyk-docs-hugo pull request #5121
Opened 2024-07-25 14:52 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-07-25 16:18 UTC, dcs3spp requested changes
@carol PR LGTM. I have made suggestions/observations:
- Suitable name for HTTP label
- Should config and env endpoint examples be updated to use https instead of http?
- Explain where the config should be added for secured HTTP /conf endpoint and /env endpoint (if secured also??), e.g. values.yaml, tyk.conf etc.

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/mdcb-configuration-options.md
> +|HTTP                     |      8181      |
From the preview it shows that healthcheck is now deprecated and port 8181 is used for:
- /healthcheck
- /dataplanes
- /debug/pprof/*

Could the label be renamed to include the endpoints, e.g. _HTTP (/healthcheck, /dataplanes and /debug/pprof/*)_. Or alternatively could the label be renamed to _HTTP endpoints_? Could also have _RPC Listen_ renamed to _RPC services_?

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +Health checks is available via the HTTP port. This is defined by `http_port` configuration setting, and defaults to `8181`. Do **not** use the standard MDCB listen port (`listen_port`) for MDCB healt
```suggestion
Health checks are available via the HTTP port. This is defined by `http_port` configuration setting and defaults to `8181`. Do **not** use the standard MDCB listen port (`listen_port`) for MDCB health checks.
```

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +From MDCB v2.7.0, there are 2 health check services available.
```suggestion
From MDCB v2.7.0, there are 2 health check services available:
```

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +2. `/readiness` endpoint returns a `HTTP 200 OK` response when MDCB is ready to accept request. It ensures that dependent components such as Redis and data store are connected, and grpc server is rea
```suggestion
2. `/readiness` endpoint returns a `HTTP 200 OK` response when MDCB is ready to accept request. It ensures that dependent components such as Redis and data store are connected, and the gRPC server is ready for connection.
```

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +In MDCB v2.6.0 or earlier, MDCB only offers one health check endpoint at `/health` via port defined by the `healthcheck_port` configuration setting. The default port is `8181`.
```suggestion
In MDCB v2.6.0 or earlier, MDCB only offers one health check endpoint at `/health` via the port defined by the `healthcheck_port` configuration setting. The default port is `8181`.
```

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +Please note that an HTTP 200 OK response from `/health` endpoint merely indicates that the MDCB service is operational. However, it is important to note that the service may not yet be ready for use
```suggestion
Please note that an HTTP 200 OK response from the `/health` endpoint merely indicates that the MDCB service is operational. However, it is important to note that the service may not yet be ready for use if it is unable to establish a connection with its dependent components (such as Redis and Data store) or if they are offline. Upgrade to v2.6.0 and later to have more accurate health checking.
```

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +From MDCB v2.7.0, a secured HTTP endpoint `/config` can be enabled that allow you to query configuration of MDCB.
```suggestion
From MDCB v2.7.0, a secured HTTP endpoint `/config` can be enabled that allows you to query configuration of MDCB.
```

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +To enable the secured HTTP endpoint, make sure you have following config:
Explain where the config should be added to. Should it be added to tyk.conf or a K8s deployment or values.yaml?

For example:
To enable the secured HTTP endpoint, make sure you have the following in your values.yaml config file:

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +curl -H "x-tyk-authorization: <secured-endpoint-secret>" http://my-mdcb-host:8181/config
update the example to use https

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +curl -H "x-tyk-authorization: <secured-endpoint-secret>" http://my-mdcb-host:8181/env
Does /env also require a secured endpoint, if so should this example be updated to use https instead of http?

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +Then you can query MDCB config at `/config` to return a json representation of MDCB config
```suggestion
Subsequently, you can issue a request to the `/config` endpoint to return a json representation of your MDCB config:
```

2024-07-25 16:18 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +Alternatively, you can query MDCB config at `/env` to return config in the form of environment variables settings
```suggestion
Alternatively, you can issue a request to the `/env` endpoint to return your MDCB config in the form of environment variables settings:
```

2024-07-25 16:29 UTC, dcs3spp commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +2. `/readiness` endpoint returns a `HTTP 200 OK` response when MDCB is ready to accept request. It ensures that dependent components such as Redis and data store are connected, and the gRPC server is
```suggestion
2. `/readiness` endpoint returns a `HTTP 200 OK` response when MDCB is ready to accept requests. It ensures that dependent components such as Redis and data store are connected, and the gRPC server is ready for connection.
```

2024-07-25 18:21 UTC, caroltyk commented on tyk-docs/content/tyk-multi-data-centre/mdcb-configuration-options.md
> +|HTTP                     |      8181      |
updated

2024-07-25 18:21 UTC, caroltyk commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +To enable the secured HTTP endpoint, make sure you have following config:
updated

2024-07-25 18:21 UTC, caroltyk commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +curl -H "x-tyk-authorization: <secured-endpoint-secret>" http://my-mdcb-host:8181/config
updated

2024-07-25 18:21 UTC, caroltyk commented on tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
> +curl -H "x-tyk-authorization: <secured-endpoint-secret>" http://my-mdcb-host:8181/env
updated

2024-07-26 09:56 UTC, dcs3spp approved these changes

2024-07-26 09:57 UTC, dcs3spp commented
Thanks @caroltyk changes approved

@mativm02 @sredxny could you peer review to enable PR to be merged ready for release?

2024-07-26 21:54 UTC, sredxny approved these changes

2024-07-28 17:14 UTC, mativm02 approved these changes

2024-07-29 14:10 UTC, dcs3spp commented
@carol is MDCB 2.7.0 scheduled for release with v5.5.0?

2024-07-29 14:15 UTC, caroltyk commented
> @caroltyk is MDCB 2.7.0 scheduled for release with v5.5.0?

Yes

2024-07-30 09:58 UTC, merged