Create pump-1.11.md
TykTechnologies/tyk-docs-hugo pull request #5126
Opened 2024-07-26 11:08 UTC by JoanCamosTyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-07-26 11:59 UTC, dcs3spp requested changes
Hi @JoanCamosTyk thanks for creating the release notes for Tyk Pump 1.11 👍 

If there is a new content file(s) created then include the menu.yaml update(s) in the same PR. 

Can you include the menu.yaml change in the branch of this PR (JoanCamosTyk-patch-1) and I will close the second [PR](https://github.com/TykTechnologies/tyk-docs/pull/5127).

2024-07-26 11:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +### Downloads
Update docker image link label from v1.10.0 to v1.11.0.

near time of release the docker URL and source code tarball URL needs updating to refer to v1.11.0

2024-07-26 11:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +#### Changed
Remove the Changed section if nothing has changed

2024-07-26 11:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +<summary>Fixed: Tyk Pump Splunk Integration using http_proxy and https_proxy Environment Variables</summary>
Update so that Environment Variables are lower case

2024-07-26 11:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +<li>PRISMA-2021-0108</li>
Can add links to PRISMA CVEs?

2024-07-26 11:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +### Release Date 3 July 2024
Remember to update release date near time of release

2024-07-26 11:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +date: 2024-02-02T26:33:11Z
Update the description so that it refers to 1.11.X series

2024-07-29 14:17 UTC, JoanCamosTyk commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +date: 2024-02-02T26:33:11Z
Done

2024-07-29 14:17 UTC, JoanCamosTyk commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +### Release Date 3 July 2024
We are still unsure about the release date, this will be updated once the date is clear.

2024-07-29 14:17 UTC, JoanCamosTyk commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +### Downloads
Done

2024-07-29 14:17 UTC, JoanCamosTyk commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +#### Changed
Done

2024-07-29 14:17 UTC, JoanCamosTyk commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +<summary>Fixed: Tyk Pump Splunk Integration using http_proxy and https_proxy Environment Variables</summary>
Changed the section to Edit as we did not fixed anything in this release. This will be updated with new information about feature implementations

2024-07-29 14:17 UTC, JoanCamosTyk commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +<li>PRISMA-2021-0108</li>
Removed this section as we did not do any security fixes

2024-07-30 08:49 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +<summary>Fixed: Tyk Pump Splunk Integration using http_proxy and https_proxy Environment Variables</summary>
Thanks @JoanCamosTyk Do you mean that there are more changelog items to add to the PR and that the fixed Tyk Pump Splunk Integration changelog item should be removed? 

The changelog sections in the release notes should be Added, Changed or Fixed

2024-07-30 10:10 UTC, JoanCamosTyk commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +<summary>Fixed: Tyk Pump Splunk Integration using http_proxy and https_proxy Environment Variables</summary>
Exactly! I've committed the changes

2024-07-30 11:09 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
> +<summary>Fixed: Tyk Pump Splunk Integration using http_proxy and https_proxy Environment Variables</summary>
Ok thanks @JoanCamosTyk, let me know when changelog is ready for review

2024-08-01 16:22 UTC, dcs3spp commented
@mativm02 @caroltyk @JoanCamosTyk are off this week and @sredxny will be off next week. Can you add the changelog for Tyk Pump release notes?

2024-08-08 09:54 UTC, dcs3spp approved these changes

2024-08-08 09:56 UTC, dcs3spp commented
Thanks @JoanCamosTyk for updating the changelog, I have approved PR and requested peer review from @mativm02 since other reviewers are on vacation

2024-08-08 13:19 UTC, mativm02 approved these changes
LGTM

2024-08-13 15:18 UTC, merged

2024-08-13 15:18 UTC, dcs3spp commented
/release to release-5.5