TT-12681 added mdcb 2.7 release notes
TykTechnologies/tyk-docs-hugo pull request #5133
Opened 2024-07-30 23:48 UTC by sredxny

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-07-31 09:01 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +- Introduced `/config` endpoint for secure, real-time access to MDCB instance configuration.
```suggestion
- Introduced `/config` and `/env` endpoint for secure, real-time access to MDCB instance configuration.
```

2024-07-31 09:03 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +A new `/config` endpoint has been implemented, allowing developers to access the current configuration state of the MDCB instance in real-time. This feature provides:
```suggestion
A new `/config` and `/env` endpoint has been implemented, allowing developers to access the current configuration state of the MDCB instance in real-time. This feature provides:
```

2024-07-31 09:53 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +- Migrate to new healthcheck endpoints in order to get more detailed information.
```suggestion
- Migrate to new health check endpoints in order to get more detailed information. For Kubernetes users, using Helm Charts v1.6 to upgrade MDCB to set liveness and readiness probes of MDCB deployment to the new health check  endpoints.
```

2024-07-31 09:56 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +Two new health check endpoints have been added to improve monitoring and diagnostics:
##### New Health check probes

2024-07-31 09:59 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +- Introduced `/config` endpoint for secure, real-time access to MDCB instance configuration.
I think we can move this part to #### Changelog {#Changelog-v2.7.0} section

2024-07-31 10:15 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +
I think we can remove this part put it into #### Changelog {#Changelog-v2.7.0} section

2024-07-31 10:27 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +   Adding a `/dataplanes` endpoint that offers a comprehensive view of all data plane nodes connected to MDCB. This endpoint provides crucial metadata and status information for each connected node,
```suggestion
 <summary> Added `/liveness` endpoint for quick checks on MDCB application status </summary>
   Added `/liveness` endpoint that report if MDCB is running. It returns status 200 if MDCB is alive. It returns status 503 if MDCB is not operational. In that case, a restart is recommended. For more details, see [MDCB Health check]({{<ref "tyk-multi-data-centre/setup-controller-data-centre#health-check">}}) section.
    </details>
  </li>
   <li>
  <details>
   <summary> Implemented `/readiness` endpoint to detail status of critical components and dependencies </summary>
   Added `/readiness` endpoint that report if MDCB is ready to serve request. It returns status 200 if MDCB is ready. It returns status 503 if MDCB or one of the dependencies is not ready. For more details, see [MDCB Health check]({{<ref "tyk-multi-data-centre/setup-controller-data-centre#health-check">}}) section.
      </details>
  </li>
   <li>
  <details>
   <summary> Introduced `/config` endpoint for secure, real-time access to MDCB instance configuration </summary>
   Added `/config` endpoint that returns MDCB instance configuration in JSON format. It requires an administrative key provided in the `x-tyk-authorization` header for access, ensuring secure and controlled usage. Successful requests return MDCB JSON configurations with passwords and sensitive information redacted.
      </details>
  </li>
   <li>
  <details>
   <summary> Introduced `/env` endpoint for secure, real-time access to MDCB instance configuration </summary>
      Added `/env` endpoint that returns MDCB instance configuration as a list of environment variable keys and values. It requires an administrative key provided in the `x-tyk-authorization` header for access, ensuring secure and controlled usage. Successful requests returns a list of environment variable keys and values with passwords and sensitive information redacted.
      </details>
  </li>
```

2024-07-31 10:28 UTC, caroltyk commented
Thank you @sredxny for raising this. I've added some comments.

2024-07-31 17:24 UTC, sredxny commented
@caroltyk thanks for the review. I pushed the changes

2024-07-31 22:03 UTC, caroltyk approved these changes

2024-08-01 08:38 UTC, dcs3spp requested changes
Thanks @sredxny PR LGTM I have made minor suggestions relating to added links and some and some minor grammar suggestions

2024-08-01 08:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +##### Release date 01 August 2024
Remember to add release date

2024-08-01 08:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +   Added `/readiness` endpoint that report if MDCB is ready to serve request. It returns status 200 if MDCB is ready. It returns status 503 if MDCB or one of the dependencies is not ready. For more d
```suggestion
   Added `/readiness` endpoint that reports if MDCB is ready to serve request. It returns status 200 if MDCB is ready. It returns status 503 if MDCB or one of the dependencies is not ready. For more details, see [MDCB Health check]({{<ref "tyk-multi-data-centre/setup-controller-data-centre#health-check">}}) section.
```

2024-08-01 08:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +   Added `/liveness` endpoint that report if MDCB is running. It returns status 200 if MDCB is alive. It returns status 503 if MDCB is not operational. In that case, a restart is recommended. For mor
```suggestion
   Added `/liveness` endpoint that reports if MDCB is running. It returns status 200 if MDCB is alive. It returns status 503 if MDCB is not operational. In that case, a restart is recommended. For more details, see [MDCB Health check]({{<ref "tyk-multi-data-centre/setup-controller-data-centre#health-check">}}) section.
```

2024-08-01 08:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +   Added `/config` endpoint that returns MDCB instance configuration in JSON format. It requires an administrative key provided in the `x-tyk-authorization` header for access, ensuring secure and con
Add links to config and env endpoint sections in docs for the config and env endpoint changelog items, similar to what has been done for the healthcheck endpoints

2024-08-01 08:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +
Add links to healthcheck endpoint docs here and in release highlights section

2024-08-01 08:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +aliases:
Do we need aliases (redirects for a url) for a new content file?

2024-08-07 08:43 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +aliases:
removed

2024-08-07 09:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +   Added `/config` endpoint that returns MDCB instance configuration in JSON format. It requires an administrative key provided in the `x-tyk-authorization` header for access, ensuring secure and con
added

2024-08-07 09:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +
added

2024-08-07 09:23 UTC, dcs3spp approved these changes

2024-08-13 11:16 UTC, merged

2024-08-13 11:16 UTC, dcs3spp commented
/release to release-5.5