Tyk Sync 1.5.1 release notes
TykTechnologies/tyk-docs-hugo pull request #5134
Opened 2024-07-31 11:09 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-07-31 11:21 UTC, dcs3spp requested changes
Thanks @caroltyk for submitting release notes. If Tyk Sync is now a private repository update the Open Source license statement at line 6 of the release notes so that it is reflective of a private repository, e.g as included on the [MDCB release notes 2.6](https://tyk.io/docs/product-stack/tyk-enterprise-mdcb/release-notes/version-2.6/)

2024-07-31 11:21 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.5.md
> +##### Release date XX August 2024
Remember to update release date

2024-07-31 11:21 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.5.md
> +There are no deprecations in this release.
Should the deprecations of slugs be mentioned here?

2024-07-31 17:09 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.5.md
> +There are no deprecations in this release.
slug deprecation is on Dashboard

2024-08-01 07:52 UTC, komalsukhani approved these changes

2024-08-01 14:17 UTC, dcs3spp approved these changes
PR LGTM, thanks @caroltyk. Thanks for peer review @komalsukhani 

Approved subject to release date being added before merge and release. Marking as draft until release date added

2024-08-14 08:05 UTC, merged

2024-08-14 08:05 UTC, dcs3spp commented
/release to release-5.5