Charts 1.6
TykTechnologies/tyk-docs-hugo pull request #5136
Opened 2024-07-31 15:15 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-08-01 09:40 UTC, dcs3spp requested changes
Thanks for submitting release notes PR @caroltyk @komalsukhani 

PR LGTM. I have fixed the CI checks and reviewed

2024-08-01 09:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.6.md
> +##### Release Date XX August 2024
Remember to add release date once confirmed

2024-08-01 09:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.6.md
> +MDCB v2.7.0 release introduces /liveness and /readiness probes which give more accurate and detail health check information. MDCB dpeloyment has been updated to use the new endpoints. See [MDCB Healt
surround endpoints by backticks ` `, e.g. `/liveness` and check done in remaining content of release notes

2024-08-01 09:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.6.md
> +#### Deprecations
Should the MDCB deprecations of health check endpoints be added here?

2024-08-01 09:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.6.md
> +Added `mdcb.healthcheck.cache_renewal_period` which configures the time interval (in seconds) at which the healthchecker refreshes its cached health status information (redis and DB). Default to 10 (
Capitalise Redis

2024-08-01 09:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.6.md
> +Updated MDCB liveness and readiness probes to /liveness and /readiness respectively. These endpoints are available from MDCB v2.7.0. If you are deploying an earlier version of MDCB, please update the
Add link to new healthcheck docs here, links have been added to  MDCB 2.7 release notes PR as an example

2024-08-01 09:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.6.md
> +Fixed the issue that when Developer Portal component is enabled, an Ingress resource is being created, although portal ingress is not enabled.
Capitalise portal

2024-08-01 10:00 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.6.md
> +#### Deprecations
New endpoints are added in MDCB v2.7.0. Old endpoints are still needed for older version.

2024-08-01 10:10 UTC, komalsukhani commented
@dcs3spp I have implemented the changes. Just release date is missing. I will confirm with team and update it.

2024-08-01 14:12 UTC, dcs3spp requested changes
Thanks @caroltyk PR LGTM subject to release date being added. @komalsukhani Could you be able to peer review?

2024-08-01 14:13 UTC, dcs3spp approved these changes
Approved subject to release date being added

2024-08-06 06:29 UTC, komalsukhani approved these changes

2024-08-14 09:25 UTC, merged

2024-08-14 09:25 UTC, dcs3spp commented
/release to release-5.5