[TT-12681] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #5138
Opened 2024-07-31 17:32 UTC by buger

Triggered by: sredxny

Included:

Tyk Gateway: false
Tyk Dashboard: false
Tyk MDCB true
Tyk Pump false

Intended for: master
Changes sourced from: master
Config info generator branch: main

Note: <none> (branch suffix: docs)

JIRA: https://tyktech.atlassian.net/browse/TT-12681

2024-08-01 08:57 UTC, dcs3spp requested changes
PR LGTM @sredxny I have made suggestions relating to OAS and config missing items. Peer review required to check that required options are present in MDCB config for the new functionality

2024-08-01 08:57 UTC, dcs3spp commented on tyk-docs/assets/others/mdcb-swagger.yml
> +  /config:
Include example requests for config and env endpoints since they are secure requests

2024-08-01 08:57 UTC, dcs3spp commented on tyk-docs/content/shared/mdcb-config.md
> +### healthcheck
Why is EnableHTTPSecureEndpoints and Secrets not included from Security struct?

Peer review required to check correct options are included for functionality

2024-08-01 16:59 UTC, mativm02 commented on tyk-docs/assets/others/mdcb-swagger.yml
> +  /config:
@dcs3spp Hey Simon! I created this draft PR to modify the Swagger file with the change you're suggesting. Could you please take a look at it? I'll update its description and name before merging it, but I want to be sure that it's aligned with the change you want to make.

2024-08-02 16:10 UTC, dcs3spp commented on tyk-docs/assets/others/mdcb-swagger.yml
> +  /config:
Hi Matias! Thanks @mativm02 I have made a suggestion to improve formatting display in OAS rendering. See this [comment](https://github.com/TykTechnologies/tyk-sink/pull/565#pullrequestreview-2215949666) in the draft PR

2024-08-08 12:26 UTC, mativm02 approved these changes

2024-08-08 12:26 UTC, mativm02 commented on tyk-docs/content/shared/mdcb-config.md
> +### healthcheck
I manually added the required fields. This will require a future fix in the docs generator script

2024-08-08 13:45 UTC, dcs3spp reviewed
@mativm02 If paste the yml file into [swagger editor](https://editor.swagger.io/) and then view the example then the example shows success with status 200 instead of an error with status 503

2024-08-08 13:45 UTC, dcs3spp commented on tyk-docs/assets/others/mdcb-swagger.yml
> +        "503":
If paste the yml file into [swagger editor](https://editor.swagger.io/) and then view the example then the example shows success with status 200 instead of an error with status 503

2024-08-13 13:38 UTC, dcs3spp commented on tyk-docs/assets/others/mdcb-swagger.yml
> +        "503":
Thanks @mativm02 I will publish the PR

2024-08-13 13:39 UTC, dcs3spp approved these changes
Thanks @mativm02 changes LGTM, I will publish PR for release

2024-08-13 14:24 UTC, merged

2024-08-13 14:24 UTC, dcs3spp commented
/release to release-5.5