Change links
TykTechnologies/tyk-docs-hugo pull request #517
Opened 2018-07-31 12:24 UTC by marksou

2018-08-01 10:31 UTC, asoorm commented on tyk-docs/content/security/security-policies/policies-guide.md
> +[See here](https://tyk.io/docs/get-started/with-tyk-on-premise/tutorials/tyk-on-premises-pro/create-security-policy/#a-namewithapiatutorial-create-a-security-policy-with-the-api)
Change anchor text from `See here` to `tutorial create security policy via api`

2018-08-01 10:31 UTC, asoorm commented on tyk-docs/content/security/security-policies/policies-guide.md
> +[See here](https://tyk.io/docs/with-tyk-community-edition/tutorials/create-security-policy/#a-name-create-a-file-based-policy-a-tutorial-create-a-policy-with-the-gateway-api).
same as above

2018-08-01 10:31 UTC, asoorm commented on tyk-docs/content/security/security-policies/policies-guide.md
> +[See here](https://tyk.io/docs/get-started/with-tyk-on-premise/tutorials/tyk-on-premises-pro/create-security-policy/#a-namewithdashboardatutorial-create-a-security-policy-with-the-dashboard)
same as above

2018-08-01 10:32 UTC, asoorm requested changes
Anchor links should provide context & description - rather than `see here` or similar.

2018-08-02 08:25 UTC, marksou commented
@asoorm I've changes the links section completely.

2018-08-02 08:25 UTC, asoorm approved these changes

2018-08-02 08:35 UTC, merged