fix link and other typos
TykTechnologies/tyk-docs-hugo pull request #518
Opened 2018-08-01 09:09 UTC by marksou

2018-08-01 10:29 UTC, asoorm requested changes

2018-08-01 10:29 UTC, asoorm commented on tyk-docs/content/configure/tyk-dashboard-configuration-options.md
> +*   `sso_permission_defaults`: As of v1.4, you can specify permissions of the user who logged using Admin SSO API (for example Tyk Identity Broker). See more info [here](https://tyk.io/docs/dashboard
Instead of `here` the anchor text should be a description of the content of the page. e.g. `guide to enabling single sign-on with the dashboard admin api`

2018-08-02 08:13 UTC, marksou commented
@asoorm Changes made.

2018-08-02 08:26 UTC, asoorm approved these changes

2018-08-02 08:35 UTC, merged