[TT-12589] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #5183
Opened 2024-08-08 12:49 UTC by buger

Triggered by: mativm02

Included:

Tyk Gateway: false
Tyk Dashboard: false
Tyk MDCB false
Tyk Pump true

Intended for: master
Changes sourced from: master
Config info generator branch: main

Note: Pump Config Generator (branch suffix: TT-12589)

JIRA: https://tyktech.atlassian.net/browse/TT-12589

2024-08-08 13:32 UTC, dcs3spp requested changes
Thanks for submitting PR @JoanCamosTyk @mativm02 

PR LGTM! Made small grammar suggestions and some minor suggestions / question:
- replace ```{.json} with ```json
- should _ORGS_IDS and _ORGSIDS in env var names be _ORG_IDS and _ORG_IDS?

2024-08-08 13:32 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +Sets the pump type. This is needed when the pump key does not equal to the pump name type.
```suggestion
Sets the pump type. This is needed when the pump key does not equal the pump name type.
```

2024-08-08 13:32 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +```{.json}
Replace this instance and remaining instances with 

```suggestion
```json
```

2024-08-08 13:32 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +The fields api_ids, org_ids and response_codes works as allow list (APIs and orgs where we
Add backticks to the fields, something like:

The fields `api_ids`, `org_ids` and `response_codes` represent an allow list (APIs and orgs where we want to send the analytics records). The fields `skip_api_ids`, `skip_org_ids` and
`skip_response_codes` represent a block list.

2024-08-08 13:32 UTC, dcs3spp commented on tyk-docs/content/shared/pump-config.md
> +ENV: <b>TYK_PMP_PUMPS_KINESIS_FILTERS_ORGSIDS</b><br />
should __ORGS_IDS_ in this and other config fields be __ORG_IDS_?

2024-08-13 13:20 UTC, mativm02 commented on tyk-docs/content/shared/pump-config.md
> +ENV: <b>TYK_PMP_PUMPS_KINESIS_FILTERS_ORGSIDS</b><br />
@dcs3spp the "_" separator indicates when a field is a child of a parent struct. In this case, ORGSIDS is a child of FILTERS struct

2024-08-13 13:29 UTC, dcs3spp approved these changes
Thanks @mativm02 PR LGTM I will merge and release when Pump 1.11 release has been announced

2024-08-13 15:14 UTC, merged

2024-08-13 15:14 UTC, dcs3spp commented
/release to release-5.5