[TT-12823] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #5187
Opened 2024-08-12 12:26 UTC by buger

Triggered by: lghiur

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: master
Changes sourced from: release-5.5.0
Config info generator branch: main

Note: Docs updates for 5.5.0 (branch suffix: docs)

JIRA: https://tyktech.atlassian.net/browse/TT-12823

2024-08-12 13:15 UTC, dcs3spp requested changes
@lghiur Thanks for raising the 5.5 PR @lghiur, PR LGTM! Have raised minor suggestions/questions/observations

2024-08-12 13:15 UTC, dcs3spp commented on tyk-docs/assets/others/dashboard-swagger.yml
> +    RateLimitMeta:
Where is RateLimitMeta linked from? should there be an endpoint in this PR or should this be linked to from an existing endpoint?

2024-08-12 13:15 UTC, dcs3spp commented on tyk-docs/content/shared/dashboard-config.md
> +This secret is to be used by a special set of endpoints that we call “Admin APIs”. This API is part of the super-admin context and therefore has a separate endpoint prefix `/admin`. It also requires
```suggestion
This secret is to be used by a special set of endpoints that we call “Admin APIs”. This API is part of the super-admin context and therefore has a separate endpoint prefix `/admin`. It also requires a special auth header called admin-auth. The purpose of these endpoints is to allow functionality that regular Dashboard users should not have, such as create new organizations, create super users etc. See the [Admin API](https://tyk.io/docs/dashboard-admin-api/) for more information on these endpoints.
```

2024-08-12 13:15 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> -By default, it uses `url` as the input source.
Why have details concerning the default and valid values been removed? Is it better to include them?

2024-08-12 13:15 UTC, dcs3spp commented on tyk-docs/content/shared/x-tyk-gateway.md
> +Condition indicates the logical combination that will be applied to the rules for an advanced trigger.
Why have valid values been removed, is it better to include them?

2024-08-12 13:30 UTC, dcs3spp commented on tyk-docs/content/shared/gateway-config.md
> +Defines the ports that will be available for the API services to bind to in the format
@lghiur The patch should also be present on 5.3.3 released https://tyk.io/docs/5.3/tyk-oss-gateway/configuration/#ports_whitelist

https://tyk.io/docs/5.3/tyk-oss-gateway/configuration/#ports_whitelist

2024-08-12 14:02 UTC, lghiur commented on tyk-docs/content/shared/gateway-config.md
> +Defines the ports that will be available for the API services to bind to in the format
@dcs3spp 5.3.3 is out, I propose to update this with 5.3.4

2024-08-14 09:43 UTC, dcs3spp approved these changes

2024-08-14 09:46 UTC, merged

2024-08-14 09:46 UTC, dcs3spp commented
/release to release-5.5