Fix broken links
TykTechnologies/tyk-docs-hugo pull request #519
Opened 2018-08-01 09:25 UTC by marksou

2018-08-01 10:25 UTC, asoorm requested changes

2018-08-01 10:25 UTC, asoorm commented on tyk-docs/content/customise-tyk/plugins/rich-plugins/python/python.md
> +The project implements a simple middleware for header injection, using a Pre hook (see [Tyk custom middleware hooks](https://tyk.io/docs/customise-tyk/plugins/javascript-middleware/middleware-scripti
New link points to javascript middleware. But the docs are about python plugins.

2018-08-01 10:40 UTC, marksou commented on tyk-docs/content/customise-tyk/plugins/rich-plugins/python/python.md
> +The project implements a simple middleware for header injection, using a Pre hook (see [Tyk custom middleware hooks](https://tyk.io/docs/customise-tyk/plugins/javascript-middleware/middleware-scripti
@matiasinsaurralde Is the link to the JavaScript Middleware correct? We also link to it from the Lua Docs.

2018-08-07 09:30 UTC, matiasinsaurralde commented on tyk-docs/content/customise-tyk/plugins/rich-plugins/python/python.md
> +The project implements a simple middleware for header injection, using a Pre hook (see [Tyk custom middleware hooks](https://tyk.io/docs/customise-tyk/plugins/javascript-middleware/middleware-scripti
We can link to this hooks page: https://tyk.io/docs/customise-tyk/plugins/rich-plugins/rich-plugins-work/#coprocess-dispatcher-hooks
The other links look fine!

2019-04-23 10:52 UTC, merged