[WIP] EDP v1.11.0
TykTechnologies/tyk-docs-hugo pull request #5289
Opened 2024-08-21 07:56 UTC by tbuchaillot

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<be>

Adding docs for:
- TLS config
- 
#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-23 10:10 UTC, MFCaballero approved these changes
LGTM

2024-09-23 12:08 UTC, sharadregoti requested changes

2024-09-23 12:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
> +**Description**: The lifetime of the portal's session in seconds. The default value is 604800 seconds.
```suggestion
**Description**: The lifetime of the portal's session in seconds. The default value is 604800 seconds (7 days).
```

2024-09-23 12:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
> +**Description**: Minimum TLS version. Defaults to 769 (TLS 1.0).
```suggestion
### PORTAL_TLS_MIN_VERSION
**Config file:** TLSConfig.MinVersion <br/>
**Type:** `string` <br/>
**Description**: Minimum TLS version. Defaults to 769 (TLS 1.0).

Values for TLS Versions:

| TLS Version   | Value to Use   |
|---------------|----------------|
|      1.0      |      769       |
|      1.1      |      770       |
|      1.2      |      771       |
|      1.3      |      772       |
```

I know the table exists just below another variable, but I believe it will be overlooked

2024-09-23 12:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
> +**Description**: Defines the maximum lifetime of a connection in Milliseconds. Optional, the default value is unlimited meaning connections are reused indefinitely as long as they are not closed due
```suggestion
**Description**: Defines the maximum lifetime of a connection in milliseconds. This setting is optional. If not specified, the default value is 1800000 milliseconds (30 minutes). If set to `0`, the connection lifetime is unlimited, meaning connections are reused indefinitely unless closed due to errors or manually by the application.
```

Ambiguity while reading:

1. The statement says "the default value is unlimited," but later it mentions "Defaults to 1800000 milliseconds." These two default values contradict each other.

2. The phrase "Optional" is somewhat out of place. It could be clearer if we explicitly referred to the configuration setting rather than being inserted without a clear link.

2024-09-23 12:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
> +**Description**: The idle timeout of the portal's session in seconds. The default value is 3600 seconds.
```suggestion
**Description**: The duration in seconds before a portal session is considered idle. A session is deemed idle when there is no user activity, such as clicks, navigation, or input. Once the idle timeout is reached, the session will expire, requiring the user to log in again. The default value is 3600 seconds (1 hour).
```

What is meant by idle is clearly defined.

2024-09-23 12:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +For reference, with 2 pods, `PORTAL_DATABASE_MAX_OPEN_CONNECTIONS` set to 30 and `PORTAL_DATABASE_MAX_IDLE_CONNECTIONS` set to 15, we could handle 90 active users.
```suggestion
#### Performance Optimizations
To improve stability under high loads, we conducted performance testing and identified that improper database configurations can cause unexpected portal restarts. To prevent this and ensure optimal performance, we recommend the following database settings:

**Recommended Configuration:**
- [PORTAL_DATABASE_MAX_OPEN_CONNECTIONS]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_database_max_open_connections" >}}): Set this value based on your database’s maximum connection limit divided by the number of portal instances. For example, if your database allows 200 connections and you are running 4 portal instances, set PORTAL_DATABASE_MAX_OPEN_CONNECTIONS to 50 per instance. This ensures that all instances can share the available connections without exceeding the database's limit, which could otherwise lead to performance degradation or errors.
- [PORTAL_DATABASE_MAX_IDLE_CONNECTIONS]({{< ref "/product-stack/tyk-enterprise-developer-portal/deploy/configuration#portal_database_max_idle_connections" >}}): Set to 15 or a lower value based on your expected load. This setting keeps a reasonable number of connections readily available without tying up resources unnecessarily.

For reference, with 2 portal instances, `PORTAL_DATABASE_MAX_OPEN_CONNECTIONS` set to 30 and `PORTAL_DATABASE_MAX_IDLE_CONNECTIONS` set to 15, we could handle 90 active users.
```

2024-09-23 12:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +To upgrade the portal's theme please follow the [upgrade instructions]({{< ref "product-stack/tyk-enterprise-developer-portal/upgrading/theme-upgrades" >}}) for the portal's themes.
Did we modify themes in this release?

If no, then remove this line or add the below line.

`This release doesn’t introduce any changes to the theme, so a theme upgrade is not required.`

2024-09-23 12:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- 22 bugs fixed.
```suggestion
- [22 bugs fixed]({{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0/#fixed" >}})
```

2024-09-23 12:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- 19 CVEs fixed.
```suggestion
- [19 CVEs fixed]({{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0/#fixed" >}})
```

2024-09-23 12:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- Closer to API Parity: APIs for Tags, Blogposts, Product images, Webhooks, and rotate credentials. A total of 23 new endpoints.
Can you clarify whether the 23 endpoints include only the listed ones or if there are others.

2024-09-23 12:16 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +To upgrade the portal's theme please follow the [upgrade instructions]({{< ref "product-stack/tyk-enterprise-developer-portal/upgrading/theme-upgrades" >}}) for the portal's themes.
Yes - minor themes changes in these release.

2024-09-23 12:17 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- Closer to API Parity: APIs for Tags, Blogposts, Product images, Webhooks, and rotate credentials. A total of 23 new endpoints.
not sure if I understand @sharadregoti

2024-09-23 12:35 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- Closer to API Parity: APIs for Tags, Blogposts, Product images, Webhooks, and rotate credentials. A total of 23 new endpoints.
Just to clarify, when you mention 23 new endpoints, do those include only the ones listed (Tags, Blogposts, Product images, Webhooks, and rotate credentials), or are there additional endpoints not mentioned?

2024-09-23 12:36 UTC, sharadregoti requested changes

2024-09-23 12:36 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- [19 CVEs fixed]({{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0/#fixed" >}})
```suggestion
- [22 bugs fixed]({{< ref "/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0#fixed" >}})
- [19 CVEs fixed]({{< ref "/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0#fixed" >}})
```
I think the CI is failing because of this.

2024-09-23 13:01 UTC, sharadregoti requested changes

2024-09-23 13:01 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- [19 CVEs fixed]({{< ref "/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0#fixed" >}})
```suggestion
- [22 bugs fixed]({{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0#fixed" >}})
- [19 CVEs fixed]({{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0#fixed" >}})
```

2024-09-23 13:05 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- Closer to API Parity: APIs for Tags, Blogposts, Product images, Webhooks, and rotate credentials. A total of 23 new endpoints.
Yes - they are the listed ones.

2024-09-23 13:11 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- 22 bugs fixed.
@sharadregoti I think these links broke the linters 😆

2024-09-23 13:20 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- 19 CVEs fixed.
@sharadregoti same link format that breaks the CI linters.

2024-09-23 14:43 UTC, edsonmichaque approved these changes
LGTM

2024-09-24 06:09 UTC, sharadregoti requested changes

2024-09-24 06:09 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- [19 CVEs fixed]({{< ref "product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0/#fixed" >}})
```suggestion
- [22 bugs fixed](#fixed)
- [19 CVEs fixed](#fixed)
```

2024-09-24 06:17 UTC, sharadregoti approved these changes

2024-09-25 14:15 UTC, letzya commented on tyk-docs/data/releases/portal.json
> +    "date": "23/09/2024",
@tbuchaillot shou
```suggestion
    "date": "25/09/2024",
```

2024-09-25 14:19 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- Fixed the 19 CVEs, among which are:
We need to add here the collapse/expand option

2024-09-25 14:20 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- Fixed the 19 CVEs, among which are:
why @letzya ?

2024-09-25 14:22 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- Fixed the 19 CVEs, among which are:
it's toooooo long

2024-09-25 14:22 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
> +- Fixed the 19 CVEs, among which are:
we can merge and then add it

2024-09-25 15:24 UTC, letzya approved these changes

2024-09-25 15:24 UTC, merged

2024-09-25 15:24 UTC, letzya commented
/release to release-5.6

2024-09-25 15:25 UTC, letzya commented
/release to release-5.5