Simplify Tyk Operator installation instructions
TykTechnologies/tyk-docs-hugo pull request #5306
Opened 2024-08-23 15:06 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-08-23 15:41 UTC, dcs3spp requested changes
PR LGTM, have made minor suggestions. Once peer reviewed we can then merge merge and release

2024-08-23 15:41 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +If you are using [Tyk Stack]({{<ref "product-stack/tyk-charts/tyk-stack-chart">}}), [Tyk Control Plane]({{<ref "product-stack/tyk-charts/tyk-control-plane-chart">}}), or [Tyk Open Source Chart]({{<re
```suggestion
If you are using [Tyk Stack]({{<ref "product-stack/tyk-charts/tyk-stack-chart">}}), [Tyk Control Plane]({{<ref "product-stack/tyk-charts/tyk-control-plane-chart">}}), or [Tyk Open Source Chart]({{<ref "product-stack/tyk-charts/tyk-oss-chart">}}), you can install Tyk Operator alongside other Tyk components by setting value `global.components.operator` to `true`.
```

2024-08-23 15:41 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +Tyk Operator configurations are set via Kubernetes secret. The default K8s secret name is `tyk-operator-conf`. The secret should contain following keys:
Is there a way to change the default secret name? If so should we link to section that explains how to use a different secret name other than `tyk-operator-conf`?

```suggestion
Tyk Operator configurations are set via a Kubernetes secret. The default K8s secret name is `tyk-operator-conf`. The secret should contain the following keys: 
```

2024-08-23 15:41 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +| `WATCH_NAMESPACE` |No |  `foo,bar` |`foo,bar` | Comma separated list of namespaces for Operator to operate on. The default is to all namespaces if not specified.|
```suggestion
| `WATCH_NAMESPACE` |No |  `foo,bar` |`foo,bar` | Comma separated list of namespaces for Operator to operate on. The default is to operate on all namespaces if not specified.|
```

2024-08-23 15:41 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +| `WATCH_INGRESS_CLASS` |No |  `customclass` |`customclass` | Define the ingress class Tyk Operator to watch for. Default is `tyk`|
```suggestion
| `WATCH_INGRESS_CLASS` |No |  `customclass` |`customclass` | Define the ingress class Tyk Operator should watch. Default is `tyk`|
```

2024-08-23 15:41 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +If you install Tyk using Helm Chart, `tyk-operator-conf` will have been created with the following keys: `TYK_AUTH, TYK_MODE, TYK_ORG`, and `TYK_URL` by default. If you didn't use Helm Chart for inst
```suggestion
If you install Tyk using Helm Chart, `tyk-operator-conf` will have been created with the following keys: `TYK_AUTH, TYK_MODE, TYK_ORG`, and `TYK_URL` by default. If you didn't use Helm Chart for installation, please prepare `tyk-operator-conf` secret yourself using the commands below:
```

2024-08-23 15:41 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +For licensed users, user API key and Organization ID can be found under "Add / Edit User" page within Tyk Dashboard. TYK_AUTH` corresponds to `Tyk Dashboard API Access Credentials`. `TYK_ORG` corresp
In the preview, the note renders corresponds etc. incorrectly using backticks. 

Move the explanation of Tyk_AUTH and TYK_ORG outside of the note below the commands above to create tyk-operator-conf secret

2024-08-23 15:41 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +You can configure [Tyk Operator as Ingress Controller]({{<ref "product-stack/tyk-operator/tyk-ingress-controller">}}) so that [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress
Link the reader to the table above so that they can can see accompanying explanation of WATCH_INGRESS_CLASS

2024-08-23 15:41 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +#### Step 2: Installing Tyk Operator and CRDs
```suggestion
#### Step 2: Installing Tyk Operator and Custom Resource Definitions (CRDs)
```

2024-08-26 10:15 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/troubleshooting/tyk-operator-changes-not-applied.md
> +If you experience issues with the behavior of the Tyk Operator (e.g. API changes not being applied), to investigate, you can check the logs of the tyk-operator-controller-manager pod in your cluster
```suggestion
If you experience issues with the behavior of the Tyk Operator (e.g. API changes not being applied), to investigate, you can check the logs of the tyk-operator-controller-manager Deployment's pod in your cluster with the following command:
```

2024-08-26 10:15 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/troubleshooting/tyk-operator-changes-not-applied.md
> +$ kubectl logs <tyk-controller-manager-pod-name> -n tyk-operator-system manager
Maybe it might be clearer to parameterize the namespace of the Operator as it can be downloaded into different namespaces.
```suggestion
$ kubectl logs <tyk-controller-manager-pod-name> -n $TYK_OPERATOR_NS manager
```

2024-08-26 10:15 UTC, buraksekili commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +Tyk Operator supports any Tyk installation whether it is on Tyk Cloud, Hybrid, or self-managed on VMs and K8s. You only need to make sure that the control plane URL is accessible by Tyk Operator.
Do we need to mention specifically "VMs *and* K8s" here? Any self-managed installation would work fine as far as Tyk Operator can connect to it.

2024-08-27 08:45 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +Tyk Operator supports any Tyk installation whether it is on Tyk Cloud, Hybrid, or self-managed on VMs and K8s. You only need to make sure that the control plane URL is accessible by Tyk Operator.
```suggestion
Tyk Operator supports any Tyk installation whether it is on Tyk Cloud, Hybrid, or self-managed. You only need to make sure that the control plane URL is accessible by Tyk Operator.
```

2024-08-27 08:48 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +Tyk Operator configurations are set via Kubernetes secret. The default K8s secret name is `tyk-operator-conf`. The secret should contain following keys:
updated

2024-08-27 12:29 UTC, buraksekili approved these changes

2024-08-28 16:12 UTC, dcs3spp approved these changes
Thanks for peer review @buraksekili 

@caroltyk PR LGTM and if you are ok with updates to the table in installing Tyk Operator to make the description column wider then I will merge and release. Does the PR target latest docs v5.5, yes?

2024-08-28 17:11 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/troubleshooting/tyk-operator-changes-not-applied.md
> +$ kubectl logs <tyk-controller-manager-pod-name> -n $TYK_OPERATOR_NS manager
```suggestion
$ kubectl logs $TYK_CONTROLLER_MANAGER_POD_NAME -n $TYK_OPERATOR_NS manager
```

2024-08-29 08:02 UTC, merged

2024-08-29 08:02 UTC, dcs3spp commented
/release to release-5.5