Import draft of url matching
TykTechnologies/tyk-docs-hugo pull request #5311
Opened 2024-08-28 11:15 UTC by titpetric

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

I'm adding an url matching key concepts page

Ideally:

- [ ] link it from relevant other pages,
- [ ] use shortcode or somehow ensure backlinks to/from key-concepts (nobody will maintain an inline list of references that frequently change, ensure it's covered with hugo/otherwise)

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-08-29 19:04 UTC, dcs3spp submitted a review, later dismissed
Thanks for submitting draft url matching. I have done an initial content review with the following minor suggestions

2024-08-29 19:04 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +below. Mux supports named parameters, which are typically also documented
Add external link to mux

2024-08-29 19:04 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +## Errata
Rename section headings supported versions

2024-08-29 19:04 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +match `.*/user.*`, also matching deeper URLs. This may have lead to
give an example of deeper URL that would be matched for this expression

2024-08-29 19:04 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +The input has full go regex (RE2) support.
Add link to go regex docs

2024-08-29 19:04 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +For a demonstation, if user input provides a pattern like `/users*.`, it
```suggestion
For a demonstration, if user input provides a pattern like `/users*.`, it
```

2024-08-29 19:04 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- `/usera` (`s*` matches any number of s, including 0, `.` matches `a`)
so even if no `s`, `r` etc. is present then a match is made for pattern `/users*.`? So the pattern expression is not interpreted that it will try to match 0 or more occurrences of the `/users` block?

2024-08-29 19:04 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +> **Note:** The `{id}`, `{path}`, `{file}`, `{orderId}`, and `{itemId}` in the
Use *note* shortcode, e.g:

{{< note >}}
**Note**

Note paragraph text
{{</ note >}}

2024-08-30 07:50 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +> **Note:** The `{id}`, `{path}`, `{file}`, `{orderId}`, and `{itemId}` in the
Why? this is markdown, shortcodes are a hugo feature

2024-09-10 10:00 UTC, dcs3spp requested changes
PR LGTM, have made minor suggestions and once peer approved can merge ready for release. Does the PR target release 5.6.0?

2024-09-10 10:00 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- [Secure Your APIs by Method and Path](https://tyk.io/docs/security/security-policies/secure-apis-method-path/)
Replace URL links with relative URLs in this format so that links to content becomes associated with version in release branch instead of current live content:

For example:

```suggestion
- [Secure Your APIs by Method and Path]({{< ref "security/security-policies/secure-apis-method-path" >}})
```

Ensure that pages listed in usage section link to new url-matching page

2024-09-10 10:00 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- [Middleware](https://tyk.io/docs/product-stack/tyk-gateway/middleware/)
Middleware is broken link

2024-09-10 10:00 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- [Middleware](https://tyk.io/docs/product-stack/tyk-gateway/middleware/)
Does [URL Rewrites](https://tyk.io/docs/product-stack/tyk-gateway/middleware/url-rewrite-middleware/#pattern) use URL matching also?

2024-09-10 10:00 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +`/path/json`. However, `json` would. For more examples on how to
```suggestion
`/path/json`. However, `json` would match. For more examples on how to
```

2024-09-10 10:00 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +For a non-trivial example of regex pattern matching, one can configure a
```suggestion
For a non-trivial example of regex pattern matching, one can configure a
complex expression to match [ULID](https://github.com/ulid/spec) values:
```

2024-09-10 10:00 UTC, dcs3spp commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +| `/items/{itemID:[0-9]+}/details/{detail}`    | `^/items/(?P<v0>[0-9]+)/details/(?P<v1>[^/]+)`    | Matches paths like `/items/45/details/overview`, where `itemID` is a number and `detail` is dynami
```suggestion
| `/items/{itemID:[0-9]+}/details/{detail}`    | `^/items/(?P<v0>[0-9]+)/details/(?P<v1>[^/]+)`    | Matches paths like `/items/45/details/overview`, where `itemID` is a number and `details` is dynamic.     |
```

2024-09-10 10:00 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> -### Endpoint parsing
If the content is being removed should it link to new url matching page here or in the tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md page?

2024-09-12 21:13 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> -### Endpoint parsing
honestly not sure why i removed this one; @andyo-tyk any opinions, revert?

2024-09-12 21:37 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- [Middleware](https://tyk.io/docs/product-stack/tyk-gateway/middleware/)
Removed/corrected middleware,
explained URL rewrites are regex only

2024-09-17 16:29 UTC, andyo-tyk requested changes
Sorry, lots of comments...

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
> -### Endpoint parsing
Please revert this change, as AFAIK it's not related to the path matching algorithm.

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
> +- [Tyk classic mock response tutorial]({{< ref "product-stack/tyk-gateway/middleware/mock-response-tyk-classic" >}}).
```suggestion
If you’re using Tyk Classic APIs, then you can find details and examples of how to configure the response body transformation middleware [here]({{< ref "product-stack/tyk-gateway/middleware/mock-response-tyk-classic" >}}).
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
>  ## Tutorials
```suggestion
```

Not sure when this was added, but these are NOT tutorial pages, there's no reason not to follow the same pattern used everywhere else.

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
> +- [Tyk OAS mock response tutorial]({{< ref "product-stack/tyk-gateway/middleware/mock-response-tyk-oas" >}}) or
```suggestion
If you’re using Tyk OAS APIs, then you can find details and examples of how to configure the mock response middleware [here]({{< ref "product-stack/tyk-gateway/middleware/mock-response-tyk-oas" >}}).
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
> +## Configuring the block list
Please bring back the "case sensitivity" section. This has nothing to do with the URL matching changes, but refers to an option specific to this middleware.

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
> +For detailed documentation on URL matching behavior, please refer to [URL Matching in Tyk]({{< ref "getting-started/key-concepts/url-matching" >}}).
Please bring back the "endpoint parsing section" and add this new line (with link to the new page) at the end. We could cut this section down, making reference to the different path matching options, but I think it's important to have it.

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
> +For detailed documentation on URL matching behavior, please refer to [URL Matching in Tyk]({{< ref "getting-started/key-concepts/url-matching" >}}).
```suggestion
```

Not required here - this page is specifically for "how to configure the middleware with Tyk OAS". The "how the middleware works" is on a separate page.

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +For detailed documentation on URL matching behavior, please refer to [URL Matching in Tyk]({{< ref "getting-started/key-concepts/url-matching" >}}).
Please bring back the "endpoint parsing section" and add this new line (with link to the new page) at the end. We could cut this section down, making reference to the different path matching options, but I think it's important to have it.

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
> +For detailed documentation on URL matching behavior, please refer to [URL Matching in Tyk]({{< ref "getting-started/key-concepts/url-matching" >}}).
Not required here - this page is specifically for "how to configure the middleware with Tyk Classic". The "how the middleware works" is on a separate page.

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +## Configuring the allow list
Please bring back the "case sensitivity" section. This has nothing to do with the URL matching changes, but refers to an option specific to this middleware.

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +Some components, like [URL Rewriting]({{< ref"transform-traffic/url-rewriting/" >}}),
And Mock Response?

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +URL matching is fundamental to many components of the system, including:
```suggestion
URL matching is fundamental to the behavior of many Tyk middleware, including:
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- [Securing APIs by Method and Path]({{< ref"security/security-policies/secure-apis-method-path/" >}})
```suggestion
- [Granular access control]({{< ref "security/security-policies/secure-apis-method-path" >}})
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- [Allow List Middleware]({{< ref"product-stack/tyk-gateway/middleware/allow-list-middleware/" >}})
```suggestion
- [Allow List]({{< ref "product-stack/tyk-gateway/middleware/allow-list-middleware" >}})
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- [Block List Middleware]({{< ref"product-stack/tyk-gateway/middleware/block-list-middleware/" >}})
```suggestion
- [Block List]({{< ref "product-stack/tyk-gateway/middleware/block-list-middleware" >}})
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- [Request and Response Middleware]({{< ref"advanced-configuration/transform-traffic/" >}})
```suggestion
- [Request and Response transformation]({{< ref "advanced-configuration/transform-traffic" >}})
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +Some components, like [URL Rewriting]({{< ref"transform-traffic/url-rewriting/" >}}),
```suggestion
Some middleware, such as [URL Rewriting]({{< ref "transform-traffic/url-rewriting" >}}),
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +prefix/suffix modes (explained further below), allowing for flexible or
```suggestion
prefix/suffix modes (explained further [below](#url_matching_configuration_options), allowing for flexible or
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +### Configuration Parameters for Matching Behavior
```suggestion
### URL matching configuration options
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +### Why URL Matching Matters
```suggestion
### Why URL matching matters
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +### Pattern Matching Overview
```suggestion
### Introduction to pattern matching
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +Advanced matching supports more complex regular expressions, enabling
```suggestion
Advanced pattern matching supports more complex regular expressions, enabling
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +example, a route like `/users/{id}` would match any URL of the form
```suggestion
example, the pattern `/users/{id}` would match any URL of the form
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +developers to define granular rules that handle varied use cases like
```suggestion
developers to define granular rules that handle varied use cases such as
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +Several configuration flags are available to control URL matching
```suggestion
Tyk Gateway can be configured to perform URL matching in one of four modes:

- [wildcard match](#wildcard_match)
- [prefix match](#prefix_match)
- [suffix match](#suffix_match)
- [exact match](#exact_match)

```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +behavior. Here's a detailed explanation of how these flags influence
```suggestion
This configuration can be set in the Gateway config file (`tyk.conf`) or using the equivalent environment variables, as described below.

**Tyk recommends the use of exact path matching for most use cases.**
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +matching:
```suggestion
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +#### `EnablePathPrefixMatching`
```suggestion
#### Prefix match
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +By enabling this flag, URL matching switches from a wildcard mode to
```suggestion
By enabling the `EnablePathPrefixMatching` flag, Tyk will adopt the prefix matching method.
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +prefix matching. This means that a URL pattern like `/json` is
```suggestion
This means that a URL pattern like `/json` will be
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +#### `EnablePathSuffixMatching`
```suggestion
#### Suffix match
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +This flag adjusts the behavior to match URLs by their suffix. When suffix
```suggestion
Enabling the `EnablePathSuffixMatching` option adjusts the behavior to match URLs by their suffix. When suffix
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +#### Combining Prefix and Suffix Matching
```suggestion
#### Exact match
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +
```suggestion

#### Wildcard match

The default behavior of Tyk if neither of the configuration options is set to `true` is to perform wildcard matching. In this mode, Tyk will attempt to match the pattern with any part of the URL path.

For example, the pattern `/user` will match all of the following URLs:
- `/my-api/user`
- `/my-api/users`
- `/my-api/v2/user/12345`
- `/my-api/groups/12/username/abc`
```

(or something to this effect :)

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +For exact URL matching, you can combine both prefix and suffix matching.
```suggestion
Exact URL matching combines prefix and suffix matching, to ensure that the URL exactly matches the required pattern.
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +For example, enabling both flags would result in `/json` being matched as
```suggestion
For example, enabling both flags would result in `/json` being treated as
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +### Practical Use Cases for URL Matching
```suggestion
### Practical use cases for URL matching
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +Understanding these behaviors is essential in scenarios where:
```suggestion
Understanding these behaviors is essential in scenarios such as:
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- **API Versioning**: You may want to allow different versions of an API, like `/v1/users` and `/v2/users`, while still matching certain common paths or endpoints.
```suggestion
- **API Versioning**: You may want to allow different versions of an API, such as `/v1/users` and `/v2/users`, while still matching certain common paths or endpoints.
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- **Middleware Control**: Middleware often relies on URL matching to determine when specific behaviors, like rate limiting or authentication, should be applied.
```suggestion
- **Middleware Control**: Middleware often relies on URL matching to determine when specific behaviors, such as rate limiting or authentication, should be applied.
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +Before these versions, the matching is done against the full request
```suggestion
Prior to these versions, the matching is done against the full request
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +expression. Depending on your setup, you could use the `[^/]+` for any of
```suggestion
expression. Depending on your setup, you could use `[^/]+` for any of
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +path to the url, and use a regex as `^/listen-path/users`, and consider
```suggestion
path to the URL, and use a regex such as `^/listen-path/users`, and consider
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +matches, if desired, are still available in recent versions, by either
Does this bit mean "if the Gateway is configured for prefix/suffix/exact matching then you can still achieve wildcard matching for an endpoint"?

Does the Gateway now automatically ignore the configured restriction if you write "special" regex characters in the endpoint path (pattern)? What about if you use a named parameter /users/{id} ? Does this override the GW config?

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +The explicit behaviour of the pattern match is to match the pattern by
```suggestion
The explicit behavior of the pattern match is to match the pattern by
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +The input has full go regex (RE2) support. See
Don't understand this - is it explaining the regex "engine" or rules that we use? Is it specific to this ULID use case?

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +#### Named And Unnamed Route Parameters
```suggestion
#### Named and unnamed route parameters
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +specific parts can be variable and populated from the OpenAPI
Is this strictly related to OpenAPI definitions?

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +1. Matches paths like `/users/123`, where `id` is dynamic.
Perhaps add these as a third column in the table (given they aren't numbered in the table)?

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +#### Advanced Pattern Matching
```suggestion
#### Advanced pattern matching
```

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +1. Matches paths where `id` is dynamic, and `type` only includes alphabetic characters.
Again, can this go into the table? If not, we should add a number to the table entries - belt and braces approach to minimise risk of misunderstanding.

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +Patterns like these only work on listen paths and endpoints.
Is this specific only to this section of the page - or should it be emphasised earlier?

2024-09-17 16:29 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +| `/products/{productId}/reviews/{rating:\d+}` | `^/products/([^/]+)/reviews/([^/]+)` |
Now I'm lost... :(

2024-09-18 10:27 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +1. Matches paths where `id` is dynamic, and `type` only includes alphabetic characters.
Lets add the numbers, I've shrunk the table from 3 to 2 columns to not line-wrap in preview

2024-09-18 13:56 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +### Migration notes
```suggestion
## Migration notes
```

2024-09-19 15:03 UTC, andyo-tyk requested changes
Typos

2024-09-19 15:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +Tyk recommended's that you use [exact]({{< ref "getting-started/key-concepts/url-matching#exact-match" >}}) matching for maximum security, though prefix and wildcard strategies might also apply for y
```suggestion
Tyk recommends that you use [exact]({{< ref "getting-started/key-concepts/url-matching#exact-match" >}}) matching for maximum security, though prefix and wildcard strategies might also apply for your particular deployment or use case.
```

2024-09-19 15:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
> +Tyk recommended's that you use [exact]({{< ref "getting-started/key-concepts/url-matching#exact-match" >}}) matching for maximum security, though prefix and wildcard strategies might also apply for y
```suggestion
Tyk recommends that you use [exact]({{< ref "getting-started/key-concepts/url-matching#exact-match" >}}) matching for maximum security, though prefix and wildcard strategies might also apply for your particular deployment or use case.
```

2024-09-19 15:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
> +Tyk recommended's that you use [exact]({{< ref "getting-started/key-concepts/url-matching#exact-match" >}}) matching for maximum security, though prefix and wildcard strategies might also apply for y
```suggestion
Tyk recommends that you use [exact]({{< ref "getting-started/key-concepts/url-matching#exact-match" >}}) matching for maximum security, though prefix and wildcard strategies might also apply for your particular deployment or use case.
```

2024-09-19 15:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
> +## Configuring the allow list
```suggestion
<hr>
```

2024-09-19 15:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
> +## Configuring the block list
```suggestion
<hr>
```

2024-09-20 06:12 UTC, lghiur approved these changes

2024-09-20 06:12 UTC, lghiur commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +This document explains how user inputs are converted into regular
This page should also explain that we're not breaking backwards compatibility, regardless of how they configured their endpoints

2024-09-20 08:23 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +This document explains how user inputs are converted into regular
I've added a note for this, thanks.

2024-09-20 08:28 UTC, andyo-tyk approved these changes
Approved 👍

2024-09-20 09:01 UTC, titpetric commented
Github doesn't allow me to approve, but everything still LGTM from the technical perspective. Thanks for the improvements/detail @andyo-tyk ; consider :heavy_check_mark:

2024-09-20 12:12 UTC, sharadregoti approved these changes

2024-09-20 15:44 UTC, merged

2024-09-20 15:45 UTC, sharadregoti commented
/release to release-5.5

2024-09-20 15:48 UTC, sharadregoti commented
/release to release-5.3

2024-09-20 15:49 UTC, sharadregoti commented
/release to release-5