[DX-1644] Gateway 5.6.0 Release notes
TykTechnologies/tyk-docs-hugo pull request #5318
Opened 2024-08-28 14:45 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

[1644](https://tyktech.atlassian.net/browse/DX-1644)

### Preview Link

<br>

### Description

5.6.0 release notes for gateway 

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-12 09:18 UTC, dcs3spp reviewed
Requires changleog for review and peer reviewers to check compatibility matrix is correct

2024-09-25 11:04 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We have introduced support for configuring endpoint-level rate limits in keys and policies. This new feature allows for more granular control over client consumption of API resources, enabling you to
@Eopayemi this needs to be linked to the docs with that content after we release the content

2024-10-07 14:22 UTC, andyo-tyk requested changes
Aligned wording with 5.3.6, added links for rate limiting

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We have enhanced the Tyk Gateway's synchronization with MDCB to ensure more reliable loading of policies and APIs. A synchronous initialization process has been implemented to prevent startup failure
```suggestion
We have enhanced the initial synchronization of Data Plane gateways with the Control Plane to ensure more reliable loading of policies and APIs on start-up. A synchronous initialization process has been implemented to avoid sync failures and reduce the risk of service disruptions caused by failed loads. This update ensures smoother and more consistent syncing of policies and APIs in distributed deployments.
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +<summary>Improved Gateway Synchronization with MDCB for Policies and APIs</summary>
```suggestion
<summary>Data plane gateways sometimes didn't synchronise policies and APIs on start-up</summary>
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +<summary>Quota Limit Respected During Spike Tests</summary>
```suggestion
<summary>uota wasn't respected under extreme load</summary>
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We have fixed an issue where the quota limit was not being consistently respected during spike tests, especially in deployments with multiple gateways. The problem occurred when multiple gateways cac
```suggestion
We have fixed an issue where the quota limit was not being consistently respected during request spikes, especially in deployments with multiple gateways. The problem occurred when multiple gateways cached the current and remaining quota counters at the end of quota periods. To address this, a distributed lock mechanism has been implemented, ensuring coordinated quota resets and preventing discrepancies across gateways.
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +<summary>Performance Improvement: Restored Key Creation Speed in Gateway 4.0.13 and Later</summary>
```suggestion
<summary>Restored key creation performance to Gateway 4.0.12/4.3.3 levels</summary>
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We have addressed a performance regression in gateway versions 4.0.13 and later, where key creation for policies with a large number of APIs (100+) became significantly slower. The operation, which p
```suggestion
We have addressed a performance regression where key creation for policies with a large number of APIs (100+) became significantly slower in Tyk 4.0.13/5.0.1. The operation, which previously took around 1.5 seconds, has been taking over 20 seconds since versions 4.0.13/5.0.1. This issue has been resolved by optimizing Redis operations during key creation, restoring the process to the previous duration, even with a large number of APIs in the policy.
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +<!-- <ul>
```suggestion
<ul>
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +</ul> -->
```suggestion
</ul>
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +<summary>Add a new CVE list</summary>
```suggestion
<summary>High priority CVEs fixed</summary>
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +- [CVE to add](https://nvd.nist.gov/vuln/detail/CVE-2023-39325)
```suggestion
- [CVE-2024-6104](https://nvd.nist.gov/vuln/detail/CVE-2024-6104)
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +The Tyk Gateway now supports logging in JSON format. To enable this feature, set the environment variable TYK_GW_LOGFORMAT to json. If a different value is provided, the logs will default to the stan
```suggestion
The Tyk Gateway now supports logging in JSON format. To enable this feature, set the environment variable `TYK_GW_LOGFORMAT` to `json`. If a different value is provided, the logs will default to the standard format. This enhancement allows for improved log processing and integration with various monitoring tools.
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +<summary>JSON Format for Gateway Logs</summary>
```suggestion
<summary>New option to generate Gateway system logs in JSON format</summary>
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +<summary>Endpoint-Level Rate Limits for Client Control</summary>
```suggestion
<summary>Per endpoint client rate limiting </summary>
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We have introduced support for configuring endpoint-level rate limits in keys and policies. This new feature allows for more granular control over client consumption of API resources, enabling you to
```suggestion
Building on the [per-endpoint upstream rate limits]({{< ref "getting-started/key-concepts/rate-limiting#api-level-rate-limiting" >}}) introduced in Tyk 5.5.0 we have now added [per-endpoint client rate limits]({{< ref "getting-started/key-concepts/rate-limiting#key-level-rate-limiting" >}}). This new feature allows for more granular control over client consumption of API resources by associating the rate limit with the access key, enabling you to manage and optimize API usage more effectively.
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We’ve introduced client-level per-endpoint rate limits. Rate limits can now be configured in security policies and keys, and are applicable to both Tyk OAS and Tyk Classic APIs, offering greater cont
```suggestion
Now you can configure rate limits at the [endpoint level per client]({{< ref "getting-started/key-concepts/rate-limiting#key-level-rate-limiting" >}}), using new configuration options in the access key. Use Tyk's powerful [security policies]({{< ref "getting-started/key-concepts/what-is-a-security-policy" >}}) to create templates to set appropriate rate limits for your different categories of user.
```

2024-10-07 14:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +| [Go](https://go.dev/dl/)                                     | 1.21  |  1.21  | [Go plugins]({{< ref "/plugins/supported-languages/golang" >}}) must be built using Go 1.21 |
```suggestion
| [Go](https://go.dev/dl/)                                     | 1.22  |  1.22  | [Go plugins]({{< ref "/plugins/supported-languages/golang" >}}) must be built using Go 1.22 | 
```

2024-10-07 14:38 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +</ul>
@Eopayemi please add the fix TT-13011 (which was incorrectly tagged as Dashboard).

The summary/title should be:
Rate limits were incorrectly combined when multiple policies were applied to a key

Details should be:
We have fixed an issue where API-level rate limits set in multiple policies were not correctly applied to the same key. With this update, when multiple policies configure rate limits for a key, the key will now receive the highest rate limit from the combined policies, ensuring proper enforcement of limits.

2024-10-08 08:25 UTC, caroltyk commented
Updated compatibility matrix. TBC pump version.

2024-10-08 10:15 UTC, andyo-tyk approved these changes
Thanks

2024-10-08 13:42 UTC, caroltyk approved these changes

2024-10-09 07:41 UTC, sharadregoti requested changes

2024-10-09 07:41 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We’ve upgraded the Tyk Gateway to Golang 1.22, bringing improved performance, better security, and enhanced stability to the core system.
```suggestion
```
@andyo-tyk Any reason for explicitly specifying this? Because the same thing is present in the changelog (we also have a reference to changelog in the 1st sentence) . If not we can remove it.

2024-10-09 07:41 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +<!-- #### Security Fixes -->
```suggestion
#### Security Fixes
```
Security fixes header is missing. 
![image](https://github.com/user-attachments/assets/c254fbfc-4f53-46e3-a1b8-66fdc2379b69)

2024-10-09 07:41 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +| | TIB (if using standalone) v1.5.1 | TIB all versions |
@caroltyk I guess we can remove the TBP prefix?

Can you incorporate the same in Dashboard RN PR

2024-10-09 07:41 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +  TBP (To Be Published separately after the release)
@caroltyk Remove TBP and add the required to link helm chart 2.1 (I guess)

Can you incorporate the same in Dashboard RN PR

2024-10-09 07:41 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +### Release Date xxx
```suggestion
### Release Date 10 October 2024
```
@sharadregoti For me

2024-10-09 07:41 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +date: 2024-03-27T15:51:11Z
```suggestion
date: 2024-10-10T15:51:11Z
```

2024-10-09 07:45 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +date: 2024-10-10T15:51:11Z
```suggestion
date: 2024-10-08T15:51:11Z
```

2024-10-09 14:39 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We’ve upgraded the Tyk Gateway to Golang 1.22, bringing improved performance, better security, and enhanced stability to the core system.
@sharadregoti these are the release highlights, so yes. This is the design of the release notes template: we provide high level summary of the key changes and then there's a detailed change log further down (which must, by definition, include the items mentioned in the release highlights). cc. @letzya

2024-10-09 14:49 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +  TBP (To Be Published separately after the release)
@sharadregoti Just to confirm, we'll first release ALL components, and then publish all release notes as the last steps, is it?

If so, we can remove TBP

2024-10-09 17:26 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We’ve upgraded the Tyk Gateway to Golang 1.22, bringing improved performance, better security, and enhanced stability to the core system.
Well, the ToV should be completely different. Highlights are more for everyone to see what are the latest and greatest in our release, in a simple and clear language, using industry words and not technical. The changelog is for the engineers who will need to action on the release or, learn to use new feature or understand bugs. It needs to be user-focused - what is the change, what is the bug, what does it enble you to achieve now or what did it fixed and link to the full doc page.

2024-10-09 19:58 UTC, agata-wit approved these changes

2024-10-10 06:34 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +  TBP (To Be Published separately after the release)
Yes

2024-10-10 06:39 UTC, sharadregoti approved these changes

2024-10-10 12:25 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +We’ve upgraded the Tyk Gateway to Golang 1.22, bringing improved performance, better security, and enhanced stability to the core system.
```suggestion
Added per-endpoint client rate limiting, enabling more granular control over API consumption by associating limits with access keys, optimizing resource management. Added support for Gateway system logs in JSON format, enhancing log processing and integration with monitoring tools. Updated to Go 1.22 for improved performance and security. Fixed synchronization issues between Data Plane gateways and Control Plane during start-up, ensuring more reliable policy and API loading. Resolved quota inconsistencies under heavy load and restored key creation performance to previous levels, enhancing overall system reliability.
```

2024-10-10 12:28 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +Now you can configure rate limits at the [endpoint level per client]({{< ref "getting-started/key-concepts/rate-limiting#key-level-rate-limiting" >}}), using new configuration options in the access k
```suggestion
Building on the [per-endpoint upstream rate limits]({{< ref "getting-started/key-concepts/rate-limiting#api-level-rate-limiting" >}}) introduced in Tyk 5.5.0 we have now added [per-endpoint client rate limits]({{< ref "getting-started/key-concepts/rate-limiting#key-level-rate-limiting" >}}). This new feature allows for more granular control over client consumption of API resources by associating the rate limit with the access key, enabling you to manage and optimize API usage more effectively.
```

2024-10-10 12:35 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +Building on the [per-endpoint upstream rate limits]({{< ref "getting-started/key-concepts/rate-limiting#api-level-rate-limiting" >}}) introduced in Tyk 5.5.0 we have now added [per-endpoint client ra
```suggestion
Building on the [per-endpoint upstream rate limits]({{< ref "getting-started/key-concepts/rate-limiting#api-level-rate-limiting" >}}) introduced in Tyk 5.5.0 we have added [per-endpoint client rate limits]({{< ref "getting-started/key-concepts/rate-limiting#key-level-rate-limiting" >}}). This new feature provided users with more precise control over API resource consumption by linking rate limits to access keys, allowing for better management and optimization of API usage.
```

2024-10-10 12:40 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
> +  - [tyk-charts v2.1.0]({{<ref "product-stack/tyk-charts/release-notes/version-2.1">}})
```suggestion
  - [tyk-charts v2.1.0]({{<ref "product-stack/tyk-charts/release-notes/version-2.1.md">}})
```

2024-10-10 12:44 UTC, merged