[DX-1644] Dashboard 5.6.0 release notes
TykTechnologies/tyk-docs-hugo pull request #5319
Opened 2024-08-28 15:15 UTC by Eopayemi

### **User description**
### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

[DX-1644](https://tyktech.atlassian.net/browse/DX-1644)

### Preview Link

[Preview](https://deploy-preview-5319--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-dashboard/release-notes/version-5.6)

### Description

Dashboard 5.6.0 release notes 

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

[DX-1644]: https://tyktech.atlassian.net/browse/DX-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
Documentation

___

### **Description**
- Added comprehensive release notes for Tyk Dashboard version 5.6.0, detailing new features, updates, fixes, and security enhancements.
- Introduced per-endpoint rate limiting for clients, Go upgrade to 1.22, and strengthened RBAC controls.
- Updated documentation to reflect changes in API schema and improved usability.
- Fixed various UI and functionality issues, including display problems and policy mappings.
- Enhanced security by addressing privilege escalation risks and ensuring sensitive information is not exposed in logs.
- Updated the menu to include a link to the new release notes.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>version-5.6.md</strong><dd><code>Add Tyk Dashboard 5.6.0 release notes with detailed changelog</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md

<li>Added release notes for Tyk Dashboard version 5.6.0.<br> <li> Documented new features, changes, fixes, and security updates.<br> <li> Included upgrade instructions and compatibility information.<br> <li> Provided links to relevant documentation and resources.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5319/files#diff-cc15e8898e7bad2601f58ad9bbc70879a3924e7e2153e44048adf25abc34b564">+272/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>menu.yaml</strong><dd><code>Update menu to include Tyk Dashboard v5.6 release notes</code>&nbsp; &nbsp; </dd></summary>
<hr>

tyk-docs/data/menu.yaml

- Added menu entry for Tyk Dashboard v5.6 release notes.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5319/files#diff-a6789c66bfa0660f7fdbe4796002ab4777677bae59a0276689c840100ff0b0b2">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

2024-09-12 09:16 UTC, dcs3spp reviewed
Awaiting changelog and requires peer reviewers to check compatibility matrix has correct versions

2024-10-07 15:00 UTC, andyo-tyk requested changes
Aligning wording with 5.3.6

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +| [GoLang](https://go.dev/dl/)                               | 1.21       | 1.21       | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go 1.21 |
```suggestion
| [GoLang](https://go.dev/dl/)                               | 1.22       | 1.22       | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go 1.22 | 
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We’ve introduced client-level per-endpoint rate limits. Rate limits can now be configured in security policies and keys, and are applicable to both Tyk OAS and Tyk Classic APIs, offering greater cont
```suggestion
Now you can configure rate limits at the [endpoint level per client]({{< ref "getting-started/key-concepts/rate-limiting#key-level-rate-limiting" >}}), using new configuration options in the access key. Use Tyk's powerful [security policies]({{< ref "getting-started/key-concepts/what-is-a-security-policy" >}}) to create templates to set appropriate rate limits for your different categories of user.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We’ve upgraded the Tyk Gateway and Tyk Dashboard to Golang 1.22, bringing improved performance, better security, and enhanced stability to the core system.
```suggestion
We’ve upgraded the Tyk Dashboard to Golang 1.22, bringing improved performance, better security, and enhanced stability to the core system.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>Endpoint-Level Rate Limits for Client Control</summary>
```suggestion
<summary>Per endpoint client rate limiting</summary>
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have introduced support for configuring endpoint-level rate limits in keys and policies. This new feature allows for more granular control over client consumption of API resources, enabling you to
```suggestion
Building on the [per-endpoint upstream rate limits]({{< ref "getting-started/key-concepts/rate-limiting#api-level-rate-limiting" >}}) introduced in Tyk 5.5.0 we have now added [per-endpoint client rate limits]({{< ref "getting-started/key-concepts/rate-limiting#key-level-rate-limiting" >}}). This new feature allows for more granular control over client consumption of API resources by associating the rate limit with the access key, enabling you to manage and optimize API usage more effectively.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>Swagger Update: Enhanced Documentation and Schema for Dashboard</summary>
```suggestion
<summary>Improved documentation and schema for Tyk Dashboard API</summary>
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have updated the swagger.yml schema for the Dashboard to reflect the latest changes in product endpoints, payloads, and responses. This update includes new fields and endpoints, improved examples,
```suggestion
We have updated the swagger.yml schema for Tyk Dashboard API to reflect the latest changes in product endpoints, payloads, and responses. This update includes new fields and endpoints, improved examples, documentation adjustments, and fixes for schema issues. These enhancements aim to improve usability and ensure that the documentation accurately represents the current code state.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>UI Update: Renamed "Playground" Tab to "Playgrounds"</summary>
```suggestion
<summary>Renamed GraphQL "Playground" tab to "Playgrounds"</summary>
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +The "Playground" tab in the API Designer has been renamed to "Playgrounds." This change consolidates access to both internal and external playgrounds within a single section, offering a more streamli
```suggestion
The "Playground" tab in the GraphQL API Designer has been renamed to "Playgrounds." This change consolidates access to both internal and external playgrounds within a single section, offering a more streamlined and intuitive experience for API design and testing.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>Correct Combination of Client Endpoint Rate Limits in Policies</summary>
```suggestion
```

Gateway change

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have fixed an issue where API-level rate limits set in multiple policies were not correctly applied to the same key. With this update, when multiple policies configure rate limits for a key, the k
```suggestion
```
Gateway change

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>UI Fix: Tyk Dashboard Keys Page Now Displays with 10+ Policies</summary>
```suggestion
<summary>Dashboard didn't display correctly if more than 10 policies assigned to a key</summary>
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have resolved an issue in the Tyk Dashboard where the Keys page would display a blank screen if more than 10 policies were associated with a key. The UI has been updated to correctly handle and di
```suggestion
We have resolved an issue where the Keys page would display a blank screen if a key was associated with more than 10 policies. The UI has been fixed to display the page properly, regardless of the number of policies attached to a key.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>UI Fix: Prevented Multiple Versions of the Same Tyk Classic API from Being Added to a Policy</summary>
```suggestion
<summary>Dashboard UI did not prevent multiple versions of a Tyk Classic API from being assigned to a policy</summary>
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have fixed an issue in the Dashboard UI that allowed users to attach the same version of a Tyk Classic API multiple times to a policy. The UI now correctly restricts duplicate API versions, ensuri
```suggestion
When working with Tyk Classic APIs, you cannot permit access to multiple versions of the same API from a single policy. We have fixed an issue in the Dashboard UI where users were able to attach multiple versions to a policy leading to an unusable policy. The UI now correctly prevents the addition of multiple versions of an API to a single policy.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>UI Fix: Corrected JWT Scope to Policy Mapping in Dashboard</summary>
```suggestion
<summary>Dashboard didn't correctly record scope to policy mappings for JWTs</summary>
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have resolved an issue in the Dashboard UI where the scope name was incorrectly recorded instead of the policy ID for subsequent JWT scope mappings. The UI now accurately associates the defined sc
```suggestion
We have fixed an issue in the Dashboard UI when assigning multiple claim to policy mappings while configuring JWT auth for an API. The scope name was incorrectly recorded instead of the policy ID for the second and subsequent JWT scope mappings. The UI now correctly associates the defined claim with the appropriate policy, ensuring accurate JWT scope to policy mappings.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>Dashboard and Postgres Average Usage Per API</summary>
```suggestion
<summary>Addressed some display issues in Dashboard Analytics and Classic Portal when using PostgreSQL storage</summary>
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +- Resolved an issue where 429 status codes were not being displayed on the Activity Overview page.
```suggestion
- Resolved an issue where HTTP 429 status codes were not being displayed on the Activity Overview page.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +- Fixed portal graphs when using Postgres by adding a default "day" grouping resolution to the query.
```suggestion
- Fixed portal graphs by adding a default "day" grouping resolution to the query.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>Gateway Secret No Longer Logged in Dashboard Logs</summary>
```suggestion
<summary>Gateway secret could be exposed in debug logs</summary>
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have addressed a security issue where the Gateway secret was appearing in the Dashboard system logs when the /api/keys endpoint was called while in debug mode. This fix prevents the Gateway secret
```suggestion
Resolved an issue where the Gateway secret was inadvertently included in the log generated by the Dashboard for a call to the `/api/keys` endpoint when in debug mode. This issue has been fixed to prevent sensitive information from appearing in system logs. We do not recommend running production environments in debug mode.
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +#### Enhanced Role-Based Access Controls (RBAC) in Tyk Dashboard
```suggestion
#### Strengthened Role-Based Access Controls (RBAC) to combat privilege escalation risks
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We’ve enhanced Role-Based Access Controls (RBAC) in the Tyk Dashboard to improve security. Now, only super-admins can create new admins, admin roles can't be assigned to user groups, and password res
```suggestion
We’ve tightened up the rules that govern a user's ability to create admin users and to reset other users' passwords when using Tyk's RBAC function. Now, only super-admins can create new admins, admin roles can't be assigned to user groups, and only admin users can reset another user's password (and only within their Tyk Organisation).
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have fixed a privilege escalation vulnerability where a user with certain permissions could potentially reset other users' passwords, including admin accounts. The following changes have been made
```suggestion
We have fixed a privilege escalation vulnerability where a user with certain permissions could potentially reset other users' passwords, including admin accounts. The following changes have been made to tighten the behavior of the password reset permission:
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +- All users can reset their own passwords, but resetting other users' passwords now requires a specific ResetPassword permission.
```suggestion
- All users can reset their own passwords
- A specific permission is required to reset the password of another user within the same Tyk Organisation
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +- The ResetPassword permission can only be assigned by super-admins, directly to admin users (not user groups).
```suggestion
- This permission can only be assigned by an admin or super-admin
- This permission can only be assigned to an admin and cannot be assigned to a user group
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +- The allow_admin_reset_password configuration ensures that all admin users automatically receive the ResetPassword permission.
```suggestion
- The allow_admin_reset_password configuration option automatically grants this permission to all admin users
- Super-admins always have the password reset permission across all Tyk Organisations
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +- The scope of the ResetPassword permission is limited to the Tyk Organization (OrgId) for which the user is an admin.
```suggestion
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +- Only super-admins or admins can assign admin status to a user, and this cannot be assigned to user groups.
```suggestion
```

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have fixed a privilege escalation vulnerability where a user with certain permissions could potentially reset other users' passwords, including admin accounts. The following changes have been made
Applying wording from the 5.3.6 RN

2024-10-07 15:00 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>Strengthened ResetPassword Permission Behavior</summary>
```suggestion
<summary>Strengthened RBAC password reset permissions</summary>
```

2024-10-08 08:25 UTC, carolwkc commented
Updated compatibility matrix. TBC pump version.

2024-10-08 13:17 UTC, andyo-tyk approved these changes
Thanks

2024-10-08 13:42 UTC, caroltyk approved these changes

2024-10-09 07:51 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +</li>
```suggestion
```

2024-10-09 07:53 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +date: 2024-03-27T15:51:11Z
```suggestion
date: 2024-10-09T15:51:11Z
```

2024-10-09 07:54 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +### Release Date xxx
```suggestion
### Release Date 10 October 2024
```

2024-10-09 07:56 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +date: 2024-10-09T15:51:11Z
```suggestion
date: 2024-10-08T15:51:11Z
```

2024-10-09 19:53 UTC, agata-wit approved these changes

2024-10-10 06:39 UTC, sharadregoti approved these changes

2024-10-10 07:21 UTC, sharadregoti commented
The CI is failing, because some links are not live yet. Once #5460 gets merged this will pass

2024-10-10 12:38 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +  - [tyk-charts v2.1.0]({{<ref "product-stack/tyk-charts/release-notes/version-2.1">}})
```suggestion
  - [tyk-charts v2.1.0]({{<ref "product-stack/tyk-charts/release-notes/version-2.1.md">}})
```

2024-10-10 12:41 UTC, merged