Add example of using secretRef for sensitive information in OperatorContext
TykTechnologies/tyk-docs-hugo pull request #5326
Opened 2024-08-30 12:24 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-08-30 15:41 UTC, dcs3spp requested changes
Thanks @caroltyk PR LGTM! I have added minor suggestion for improving description of what the table and example shows

2024-08-30 15:41 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
> +
In preview, before the table |————|———–| is rendered

2024-08-30 15:41 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
> +Mappings between `.spec.env` properties and secret `.spec.data` keys
We should update the sentence that describes what the table shows so that it is clearer for the following reasons:

- _tyk-operator-conf_ is a secret that contains `TYK_AUTH` and `TYK_ORG` keys. However, in the table below there are additional keys, e.g. `TYK_TLS_INSECURE_SKIP_VERIFY` etc. Are these also in the *tyk-operator-conf* secret or are they defined elsewhere?
- In the example where is `.spec.data` displayed? Is it contained within the tyk-operator-conf secret?
- Does the *Secret key* column refer to `.spec.data`

2024-08-30 15:41 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
> +For better security, you can also replace sensitive data with values contained within a referenced secret with `.spec.secretRef`.
Add code highlighting on both examples and expand the description of this example:

- Not sure how it works but does it mean that all the attributes: mode, auth, url and org etc. can be specified within the secret outlined by `secretRef`.
- For those attributes that are not specified in the secret then Tyk Operator will take the values from `spec.env`?
- What happens if there values configured in both the secret and OperatorContext CRD? Which takes precedence?

Summarise with explanation of what is configured in the secret and what is configured in the OperatorContext.

2024-09-03 11:45 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
> +In this example, API access key `auth` and organization ID `org` are not specified in the manifest. They are provided through a Kubernetes secrets named `tyk-operator-conf` in `alpha` namespace. The
```suggestion
In this example, API access key `auth` and organization ID `org` are not specified in the manifest. They are provided through a Kubernetes secret named `tyk-operator-conf` in `alpha` namespace. The secret contains keys `TYK_AUTH` and `TYK_ORG` which corresponds to the `auth` and `org` field respectively.
```

2024-09-03 12:55 UTC, dcs3spp approved these changes

2024-09-03 12:55 UTC, dcs3spp commented
Thanks @caroltyk I have approved the PR, if peer approval is performed then I will merge and release

2024-09-04 07:58 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
> +In this example, API access key `auth` and organization ID `org` are not specified in the manifest. They are provided through a Kubernetes secret named `tyk-operator-conf` in `alpha` namespace. The s
```suggestion
In this example, API access key `auth` and organization ID `org` are not specified in the manifest. They are provided through a Kubernetes secret named `tyk-operator-conf` in `alpha` namespace. The secret contains keys `TYK_AUTH` and `TYK_ORG` which correspond to the `auth` and `org` fields respectively.
```

2024-09-04 08:46 UTC, buraksekili approved these changes

2024-09-04 15:54 UTC, dcs3spp commented
@caroltyk which release version does this target?

2024-09-04 16:24 UTC, caroltyk commented
all versions please

2024-09-05 14:21 UTC, merged

2024-09-05 14:21 UTC, dcs3spp commented
/release to release-5.5

2024-09-05 14:27 UTC, dcs3spp commented
/release to release-5.4

2024-09-05 14:28 UTC, dcs3spp commented
/release to release-5.3