TIB profile documentation
TykTechnologies/tyk-docs-hugo pull request #5327
Opened 2024-08-30 13:34 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-08-30 15:03 UTC, dcs3spp requested changes
PR LGTM @caroltyk I have reviewed and provided suggestive updates for table entires to avoid introducing formatting issues on the tables.

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| ID                                        | Id of the profile, is a string, use the name of the profile
```suggestion
| ID                                        | ID of the profile, is a string, use the name of the profile  
```

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| ActionType                                | Which action is expected to be executed while using this profile, valid values are:<ul><li>`GenerateOrLoginDeveloperProfile`: sso portal</li><li>`Generat
Capitalise SSO

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| IdentityHandlerConfig.DashboardCredential | Api Key that will be used to consume the dashboard api to issue nonce codes and validate user data
Capitalise Api -> API

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| ReturnURL                                 | Where to redirect and send the claims from the idp on login. For dashboard SSO it would be `http://dashboard-host/tap`. For classic portal SSO it would b
Capitalise idp -> IDP here and in UserGroupMapping

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPServer             | Server address                                                                                                                  | yes                           |
Capitalise yes instances to Yes or make No instances lowercase also

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPUseSSL             | Wether to connect with the LDAP server via TLS                                                                                  | No                            |
```suggestion
| LDAPUseSSL             | Whether to connect with the LDAP server via TLS                                                                                  | No                            |
```

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPSearchScope        | the scope determines how deep into the directory hierarchy the search should go. Its an int value                               | No                            |
```suggestion
| LDAPSearchScope        | The scope is an integer value that determines the depth of the search in the directory hierarchy                            | No                            |
```

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| FailureRedirect        | On fail in login where to redirect the user to                                                                                  | yes                           |
Something like....

In the event of a login failure this is the URL that the user will be redirected to.

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| GetAuthFromBAHeader    | On handle the request, wether to gather the user and password from the Authorization header in the request. Its a boolean value | No                            |
Update description to be something like:

_A boolean value that, when set to true, instructs TIB to gather the user and password from the Authorization header  when handling the request._

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| SlugifyUserName        | If its required to make the username url friendly.This is a boolean value                                                       | No                            |
Update description to be something like:

_When set to true enhance the username so that is URL friendly._

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| OKResponse                         | This field specifies a particular string that should match with the  response body to be considered successful.
remove additional space here (_the  response body_) and list the response fields for which one of which should be filled

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| OKCode                             | Is used to determine if the response from the target service was successful. If the response code matches this value, the identity broker treats it as a success
Update the description to be something like:

_This is an integer represents the HTTP status code that represents a successful response from the target service. If the response code matches this value the identity broker treats it as a successful interaction._

List the Ok fields in the required column for which one of them should be required/filled in this field. Do the same for other related fields in the table

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| AccessTokenField                   | Field where the access token comes
Update the description to be something like:

_The name of the field that contains the access token_

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| UsernameField                      | Name of the field in which the username comes
Update the description to be something like:

_The name of the field that contains the username_

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| ExrtactUserNameFromBasicAuthHeader | On handle the request, wether to gather the user and password from the Authorization header in the request. Its a boolean value
Update the description to be something like:

_A boolean value that, when set to true, instructs TIB to gather the user and password from the Authorization header when handling the request._

Is this a duplicate of field _GetAuthFromBAHeader_ ?

ExrtactUserNameFromBasicAuthHeader - should it be ExtactUserNameFromBasicAuthHeader or is this what the field name is in the source code?

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| UseProviders.Scopes              | Specify the level of access or permissions a client is requesting from the user and the authorization server.
Is the scopes a comma separated list, e.g. "openid, profile".  Update description to be something like that below with an example:

_Specifies the level of access or permissions a client is requesting from the user and the authorization server. For example....._

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| UseProviders.SkipUserInfoRequest | Determines whether to bypass the UserInfo endpoint request, improving performance by relying on the ID token alone for user details.
Italicise *UserInfo*

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPPort               | Server address                                                                                                                  | yes                           |
Update description to represent Server port and give example for LDAPServer and LDAPPort fields

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPEmailAttribute     | Where the email comes                                                                                                           | No                            |
Not sure if understand the descriptions for LDAPEmailAttribute, LDAPFirstNameAttribute and LDAPLastNameAttribute 

For example does LDAPEmailAttribute represent the name of the field in the LDAP schema that represents the user's email? Are there default values for these fields?

2024-08-30 15:03 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPAttributes         | To select which attributes do you want to be returned on the record found                                                       | Yes. It can be an empty array |
Update description to be something like below including an example list:

_List of attributes to return when a matching LDAP record is found, for example ...._

Update description in required field to be:

_Yes. It can be an empty list_

2024-08-30 17:24 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| ActionType                                | Which action is expected to be executed while using this profile, valid values are:<ul><li>`GenerateOrLoginDeveloperProfile`: sso portal</li><li>`Generat
```suggestion
| ActionType                                | Which action is expected to be executed while using this profile, valid values are:<ul><li>`GenerateOrLoginDeveloperProfile`: SSO portal</li><li>`GenerateOrLoginUserProfile`: SSO dashboard</li><li>`GenerateOAuthTokenForClient`: generate OAuth tokens</li></ul> | Yes      |
```

2024-08-30 17:24 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| IdentityHandlerConfig.DashboardCredential | Api Key that will be used to consume the dashboard api to issue nonce codes and validate user data
```suggestion
| IdentityHandlerConfig.DashboardCredential | API Key that will be used to consume the dashboard API to issue nonce codes and validate user data                                                                                                                                            | yes      |
```

2024-08-30 17:24 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| ReturnURL                                 | Where to redirect and send the claims from the idp on login. For dashboard SSO it would be `http://dashboard-host/tap`. For classic portal SSO it would b
```suggestion
| ReturnURL                                 | Where to redirect and send the claims from the IDP on login. For dashboard SSO it would be `http://dashboard-host/tap`. For classic portal SSO it would be `http://{portal-host}/sso`                                                     | yes      |
```

2024-08-30 17:25 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| UserGroupMapping                          | Map that contains the matching between tyk groups and idp group.
```suggestion
| UserGroupMapping                          | Map that contains the matching between Tyk groups and IDP group.                                                                                                                                                                              | No       |
```

2024-08-30 17:26 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| UseProviders.SkipUserInfoRequest | Determines whether to bypass the UserInfo endpoint request, improving performance by relying on the ID token alone for user details.
```suggestion
| UseProviders.SkipUserInfoRequest | Determines whether to bypass the *UserInfo* endpoint request, improving performance by relying on the ID token alone for user details.                                          | No                                                               |
```

2024-08-30 20:23 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| UseProviders.Scopes              | Specify the level of access or permissions a client is requesting from the user and the authorization server.
yes, its a list separated by commas, something like: `["openid","email"]`

2024-08-30 20:26 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPPort               | Server address                                                                                                                  | yes                           |
LDAPServer is a regular URL `ldap://hostname`
LDAPUseSSL just a true or false
LDAPPort just a integer that represents a port

2024-08-30 20:28 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPEmailAttribute     | Where the email comes                                                                                                           | No                            |
correct, and these are the defaults:

- LDAPLastNameAttribute = "sn"
- LDAPFirstNameAttribute = "givenName"
- LDAPEmailAttribute = "mail"

2024-08-30 20:30 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPAttributes         | To select which attributes do you want to be returned on the record found                                                       | Yes. It can be an empty array |
Example for this list: `attributes=['cn', 'mail', 'ou']`

2024-09-02 13:34 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| UseProviders.Scopes              | Specify the level of access or permissions a client is requesting from the user and the authorization server.
thanks @sredxny I have updated the description to include examples

2024-09-02 13:38 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPAttributes         | To select which attributes do you want to be returned on the record found                                                       | Yes. It can be an empty array |
Thanks @sredxny I have updated the description to include example list

2024-09-02 13:43 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPEmailAttribute     | Where the email comes                                                                                                           | No                            |
Thanks @sredxny I have updated the LDAP descriptions and included default values

2024-09-02 13:49 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| LDAPPort               | Server address                                                                                                                  | yes                           |
Thanks @sredxny I have updated with examples

2024-09-02 14:07 UTC, dcs3spp commented
Thanks @caroltyk I have committed changes to resolve some review comments also. Remaining review comments are for the following fields:

- [ExrtactUserNameFromBasicAuthHeader](https://github.com/TykTechnologies/tyk-docs/pull/5327#discussion_r1738822832)
- [OkCode & associated fields](https://github.com/TykTechnologies/tyk-docs/pull/5327#discussion_r1738797922)
- [OkResponse](https://github.com/TykTechnologies/tyk-docs/pull/5327#discussion_r1738795732)

Once remaining review comments are resolved and PR has peer approval we can merge and release

2024-09-02 15:29 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| ExrtactUserNameFromBasicAuthHeader | On handle the request, wether to gather the user and password from the Authorization header in the request. Its a boolean value
Is not exactly a duplicate, `GetAuthFromBAHeader` is for LDAP while `ExrtactUserNameFromBasicAuthHeader` is for proxy provider. The name contains a typo but this is how we have it exposed so we cannot fix it otherwise it would be a breaking change.

2024-09-02 16:29 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| ExrtactUserNameFromBasicAuthHeader | On handle the request, wether to gather the user and password from the Authorization header in the request. Its a boolean value
updated description

2024-09-02 16:31 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| OKCode                             | Is used to determine if the response from the target service was successful. If the response code matches this value, the identity broker treats it as a success
updated

2024-09-02 16:33 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| OKResponse                         | This field specifies a particular string that should match with the  response body to be considered successful.
updated

2024-09-02 16:37 UTC, caroltyk commented
Thank you @dcs3spp and @sredxny . The document is updated with SAML required fields, and resolving remaining comments.

2024-09-03 11:36 UTC, dcs3spp requested changes
Thanks @caroltyk I have reviewed the new SAML content added to the PR:

- Will the examples be integrated in Tyk Operator docs?
- Made suggestions relating to adding links and examples for the SAML config fields

2024-09-03 11:36 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| EntityId            | It is used to distinguish between different entities (IDP & SP) and ensure proper routing and validation of SAML assertions and requests. Defaults to metadataURL
Should this be _Defaults to the value in IDPMetadataURL_ or is it the value "metadataURL"?

2024-09-03 11:36 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +## Examples
Will these examples be integrated in docs for TIB?

2024-09-03 11:36 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| SAMLBaseURL         | The host of TIB that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IDP. The redirects co
Add example value to description

2024-09-03 11:36 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| CertLocation        | An X.509 certificate and the private key for signing your requests to the IDP. This should be one single file with the cert and key concatenated. When used in an embedded TIB
Update description to clarify the following issues to the reader:
- Is the value of this field a file path to a file containing _cert + key_ concatenated or is it the file contents?
- When using embedded TIB instance give an example of _certId_ and include link to content for certificate manager

2024-09-03 11:36 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| IDPMetadataURL      | Metadata is an XML document which contains information necessary for interaction with SAML-enabled identity or service providers. The document contains example URLs of endpoin
```suggestion
| IDPMetadataURL      | Metadata is an XML document which contains information necessary for interaction with SAML-enabled identity or service providers. The document contains example URLs of endpoints, information about supported bindings, identifiers and public keys. Once you create your TIB profile you can find the Service Point (SP) metadata file under *{Dashboard HOST}/auth/{TIB Profile Name}/saml/metadata* | Yes |
```

- Update with link to metadata XML document example.
- Is there a link to content that can be added to this description that explains how to create TIB Profile or can a section be added to this page?

2024-09-09 14:16 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| EntityId            | It is used to distinguish between different entities (IDP & SP) and ensure proper routing and validation of SAML assertions and requests. Defaults to metadataURL
@sredxny can you confirm?

2024-09-09 14:17 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +## Examples
Yes, ideally. I'm not sure if there's any helping resources from Docs team on migration?

2024-09-09 14:19 UTC, carolwkc commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| SAMLBaseURL         | The host of TIB that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IDP. The redirects co
@sredxny please advice any example value we can add

2024-09-09 14:20 UTC, carolwkc commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| CertLocation        | An X.509 certificate and the private key for signing your requests to the IDP. This should be one single file with the cert and key concatenated. When used in an embedded TIB
@sredxny can you help?

2024-09-09 14:22 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| IDPMetadataURL      | Metadata is an XML document which contains information necessary for interaction with SAML-enabled identity or service providers. The document contains example URLs of endpoin
@sredxny can you help?

2024-09-09 14:24 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| EntityId            | It is used to distinguish between different entities (IDP & SP) and ensure proper routing and validation of SAML assertions and requests. Defaults to metadataURL
it defaults to the value that the customer has set inn the field `IDPMetadataURL`

2024-09-09 14:25 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +## Examples
correct, ideally but we need help to migrate

2024-09-09 14:33 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| SAMLBaseURL         | The host of TIB that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IDP. The redirects co
Examples

- IDPMetadataURL: This URL is given by the IDP. It is just an url, however these are some examples: https://login.microsoftonline.com/your-tenant-id/federationmetadata/2007-06/federationmetadata.xml
https://your-domain.okta.com/app/exk1ab2cd3fghIJKLM4/sso/saml/metadata
https://www.google.com/a/your-domain.com/acs

- CertLocation: as it can be an id of the cert loaded via certmanager or a filepath then examples are:

1.66cf7f8db0418b1fbe91852b0a903986875b14f3526ed0c9fa8ff00096e8ed4aa91a7a0f83cfa213de8dd22c
2./etc/ssl/certs/example_cert.pem

- SAMLBaseURL: http://tyk-dashboard:3000/

2024-09-09 14:42 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| CertLocation        | An X.509 certificate and the private key for signing your requests to the IDP. This should be one single file with the cert and key concatenated. When used in an embedded TIB
The cert details and what is required is here already: https://tyk.io/docs/advanced-configuration/integrate/sso/#sso-with-saml

I added above an example of certID, not sure if makes sense to add an id as example

2024-09-09 14:48 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| IDPMetadataURL      | Metadata is an XML document which contains information necessary for interaction with SAML-enabled identity or service providers. The document contains example URLs of endpoin
we cannot provide a metadata xml example, each SAML provider will have to ensure that they implement standard SAML and the content of the file is not something that people usually go an change, however we can provide the link to the RFC that defines the structure of the xml metadata: https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf

2024-09-09 14:49 UTC, carolwkc commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| EntityId            | It is used to distinguish between different entities (IDP & SP) and ensure proper routing and validation of SAML assertions and requests. Defaults to metadataURL
thx 👍 
table updated

2024-09-09 14:52 UTC, carolwkc commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| SAMLBaseURL         | The host of TIB that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IDP. The redirects co
@dcs3spp what kind of example value are you looking for?

2024-09-12 09:51 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| IDPMetadataURL      | Metadata is an XML document which contains information necessary for interaction with SAML-enabled identity or service providers. The document contains example URLs of endpoin
Thanks @sredxny I have updated to include the link

2024-09-12 10:02 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| CertLocation        | An X.509 certificate and the private key for signing your requests to the IDP. This should be one single file with the cert and key concatenated. When used in an embedded TIB
Thanks @sredxny I have added link to SSO with SAML section of the docs

2024-09-12 10:33 UTC, dcs3spp commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| SAMLBaseURL         | The host of TIB that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IDP. The redirects co
Thanks @sredxny

@caroltyk I have updated _IPDMetaURL_, _CertLocation_ and _SAMLBaseURL_ descriptions to include example values

2024-09-12 10:38 UTC, dcs3spp commented
@sredxny I have updated _IPDMetaURL_, _CertLocation_ and _SAMLBaseURL_ descriptions to include example values. Would you be able to do final peer review before I publish the PR

2024-09-12 10:40 UTC, dcs3spp approved these changes

2024-09-17 13:00 UTC, sredxny approved these changes

2024-09-17 14:15 UTC, letzya commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +## Examples
Please create a separate ticket

2024-09-17 15:19 UTC, merged

2024-09-17 15:19 UTC, yurisasuke commented
/release to release-5.5