[DX-1647} 5.3.5 Dashboard release notes
TykTechnologies/tyk-docs-hugo pull request #5328
Opened 2024-08-30 15:25 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

[DX-1647](https://tyktech.atlassian.net/browse/DX-1647)

### Preview Link

<br>

### Description

Dashboard release notes for 5.3.5

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-02 14:41 UTC, dcs3spp reviewed
Thanks for creating Release notes for Dashboard 5.3.5 @Eopayemi. Let me know once changelog has been added and I will review

2024-09-17 13:49 UTC, andyo-tyk requested changes
Confirmed change log (no changes - just a version bump), moved Release Highlights higher for visibility. Needs the release date and Helm links etc to be completed.

2024-09-18 11:54 UTC, caroltyk approved these changes
Helm chart version to be updated when it is released.

2024-09-20 10:19 UTC, andyo-tyk approved these changes

2024-09-24 18:31 UTC, letzya commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +There are no breaking changes in this release, however, if moving from a version of Tyk older than 5.3.0 please read the explanation provided with [5.3.0 release]({{< ref "#TykOAS-v5.3.0">}}).
```suggestion

There are no breaking changes in this release, however, if moving from a version of Tyk older than 5.3.0 please read the explanation provided with [5.3.0 release]({{< ref "#TykOAS-v5.3.0">}}).
```

2024-09-26 13:12 UTC, sharadregoti approved these changes

2024-09-26 13:15 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +### Release Date 24 September 2024
```suggestion
### Release Date 26 September 2024
```

2024-09-26 13:15 UTC, sharadregoti approved these changes

2024-09-26 13:36 UTC, merged

2024-09-26 13:37 UTC, sharadregoti commented
/release to release-5.5

2024-09-26 13:40 UTC, sharadregoti commented
/release to release-5.3