[DX-1647] 5.3.5 Gateway release notes
TykTechnologies/tyk-docs-hugo pull request #5329
Opened 2024-08-30 15:49 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!

[DX-1647](https://tyktech.atlassian.net/browse/DX-1647)

---

### Preview Link

<br>

### Description

Gateway 5.3.5 release notes

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-02 14:40 UTC, dcs3spp reviewed
Thanks for creating Release notes for 5.3.5 @Eopayemi. Let me know once changelog has been added and I will review

2024-09-17 13:28 UTC, andyo-tyk requested changes
Added change log, promoted Release Highlights section for visibility. Just needs release date to be added.

2024-09-18 11:54 UTC, caroltyk approved these changes
Helm chart version to be updated when it is released.

2024-09-20 10:16 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +</details>
```suggestion

The example Gateway configuration file `tyk.conf.example` has been updated to set exact matching with:

- `http_server_options.enable_path_prefix_matching = true`
- `http_server_options.enable_path_suffix_matching = true`
- `http_server_options.enable_strict_routes = true`
</details>
```

2024-09-20 10:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +The example Gateway configuration file `tyk.conf.example` has been updated to set exact matching with:
```suggestion
The example Gateway configuration file `tyk.conf.example` has been updated to set the recommended exact matching with:
```

2024-09-20 10:21 UTC, andyo-tyk approved these changes

2024-09-24 12:18 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +**Attention**: Please read this section carefully.
```suggestion
```

2024-09-25 10:46 UTC, andyo-tyk approved these changes

2024-09-26 13:10 UTC, sharadregoti approved these changes

2024-09-26 13:12 UTC, sharadregoti approved these changes

2024-09-26 13:14 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +### Release Date 24 September 2024
```suggestion
### Release Date 26 September 2024
```

2024-09-26 13:15 UTC, sharadregoti approved these changes

2024-09-26 13:31 UTC, merged

2024-09-26 13:32 UTC, sharadregoti commented
/release to release-5.5

2024-09-26 13:34 UTC, sharadregoti commented
/release to release-5.3