[DX-815] Plugins Overview Refactor
TykTechnologies/tyk-docs-hugo pull request #5330
Opened 2024-08-30 16:39 UTC by dcs3spp

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-815]()

---

### Preview Link

[preview - to add](/docs/nightly)

### Description

Refactor plugins PR with structural changes suggested in code review.

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-03 14:53 UTC, andyo-tyk requested changes
That's a monster PR (that I wasn't expecting 😄). Some suggestions, corrections and observations...

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +| Post | Occurs after the main request processing but bfore the response is sent. | postplugin |
```suggestion
| Post | Executed at the end of the request processing chain | postPlugins |       
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +| Pre   | Occurs before main request processing. | prePlugins |
```suggestion
| Pre   | Executed at the start of the request processing chain | prePlugins |            
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +| Post Auth | Occurs after key authentication | postAuthenticationPlugins |
```suggestion
| Post Auth | Executed after the requester has been authenticated | postAuthenticationPlugins |
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Pre   | Occurs before main request processing. | pre    |
```suggestion
| Pre   | Executed at the start of the request processing chain | pre    |            
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Auth  | Custom authentication can be handled during this phase. | auth_check |
```suggestion
| Auth  | Executed during the authentication step | auth_check |  
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Post Auth | Occurs after key authentication | post_key_auth |
```suggestion
| Post Auth | Executed after the requester has been authenticated | post_key_auth |
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Post | Occurs after the main request processing but bfore the response is sent. | post |
```suggestion
| Post | Executed at the end of the request processing chain | post |       
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +| Response | Occurs after the main request processing but before the response is sent. | response |
```suggestion
| Response | Executed on the response received from the upstream | response |   
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +Plugins provide a powerful and flexible way to extend Tyk’s API Gateway capabilities. They allow API developers to write custom middleware, in various programming languages, that can modify the behav
```suggestion
When Tyk receives an API request, it works through a [chain]({{< ref "middleware-execution-order" >}}) of processing *middleware* that is configured using the API definition. There are a large number of built-in middleware in the processing chain that are dedicated to performing [client authentication]]({{< ref "basic-config-and-security/security/authentication&authorization" >}}), [request transformation]({{< ref "advanced-configuration/transform-traffic" >}}), [caching]({{< ref "basic-config-and-security/reduce-latency/caching" >}}) and many other processes before proxying the request to the upstream.

Tyk's custom plugin facility provides a powerful and flexible way to extend the middleware chain. It allows API developers to write custom middleware, in various programming languages, that can perform additional processing of requests and responses.

For example, a custom authentication scheme can be implemented and executed on API requests, custom plugins can be used to provide integration with external services and databases, or additional processing can be performed on the response returned from the upstream.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +Tyk supports a variety of different [plugin types]({{< ref "plugins/plugin-types/plugintypes" >}}) that developers can implement to enrich the behavior of requests and/or responses for their APIs. Us
```suggestion
There are several different stages of the [API request lifecycle]({{< ref "/concepts/middleware-execution-order" >}}) where custom plugins can be attached (or *hooked*) into the middleware chain allowing significant customisation to meet your specific requirements.

Custom plugins are usually referred to by the location where they can be *hooked* into the middleware processing chain as follows:
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +Subsequently, plugins can be used to customize and enhance the capabilities of your APIs through integration with external services and databases to perform operations such as data transformation, cu
```suggestion
```

Recommend moving this to the top of page.

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +The plugin source code and associated configuration is co-located on Tyk Gateway's file system. The configuration is located within the API Definition. For further details please consult [API configu
```suggestion
The plugin source code and associated configuration are co-located with Tyk Gateway in the same file system. The configuration is located within the API Definition. For further details please consult [API configuration]({{< ref "/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview" >}}).
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +The plugin source code and associated configuration is bundled into a zip file and uploaded to a remote webserver. These types of plugins are termed *plugin bundles*. Tyk Gateway will download, extra
```suggestion
The plugin source code and associated configuration are bundled into a zip file and uploaded to a remote webserver. Multiple plugins can be stored in a single *plugin bundle*. Tyk Gateway will download the plugin bundle from the remote webserver and then extract, cache and execute plugins for each of the configured phases of the API request / response lifecycle. For further details on plugin bundles and how to configure them, please refer to the [plugin bundles]({{< ref "plugins/how-to-serve-plugins/plugin-bundles" >}}) page.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +It is possible to integrate Tyk Gateway with a gRPC server. Develop your gRPC server, using your preferred language, to handle requests from Tyk Gateway for each of the configured phases of the API r
```suggestion
Custom plugins can be hosted on a remote server and executed from the Tyk Gateway middleware chain via gRPC. These plugins can be written in any language you prefer, as they are executed on the gRPC server. You'll configure your API definition so that Tyk Gateway will send requests to your gRPC server at the appropriate points in the API request / response lifecycle. For further details please consult our [gRPC]({{< ref "plugins/supported-languages/rich-plugins/grpc" >}}) documentation.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +Optionally, Tyk Gateway can also be configured with the URL of the webserver that it should download plugin bundles from. For further details please consult the [Gateway configuration]({{< ref "plugi
```suggestion
If you're using [plugin bundles]({{< ref "plugins/how-to-serve-plugins/plugin-bundles#gateway-configuration" >}}) you'll need to configure Tyk Gateway with the URL of the webserver from which it should download the plugin bundles.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +Please consult our supporting documentation for further details relating to configuring Tyk Gateway for [Javascript]({{< ref "plugins/supported-languages/javascript-middleware#enabling-the-javascript
```suggestion
Please consult the supporting documentation for further details on configuring Tyk Gateway when using [Javascript]({{< ref "plugins/supported-languages/javascript-middleware#enabling-the-javascript-virtual-machine-jsvm" >}}) or [gRPC]({{< ref "plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin#configure-tyk-gateway" >}}) plugins.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +A plugin bundle is a ZIP file that contains your plugin source code files and associated configuration block. A [manifest.json](#manifest) file is included with the bundle and contains the source cod
```suggestion
A plugin bundle is a ZIP file that contains your plugin source code files and associated configuration. A [manifest.json](#manifest) file must be included within the bundle containing a list of the source code files and plugin configuration. 
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +The idea behind plugin bundles is to enhance the process of attaching and loading custom middleware. It allows to avoid duplicating plugin configuration onto each of your APIs definitions, which is s
```suggestion
Plugin bundles are intended to simplify the process of attaching and loading custom middleware. Multiple API definitions can refer to the same plugin bundle (containing the source code and configuration) if required. Having this common, shared resource avoids you from having to duplicate plugin configuration for each of your APIs definitions. 
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +## How Plugin Bundles Works with Tyk
```suggestion
## How Plugin Bundles Work
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +The source code and a [manifest.json](#manifest) is bundled into a zip file and uploaded to an external remote web server. The [manifest.json](#manifest) file references the source code file path and
```suggestion
The source code and a [manifest.json](#manifest) file are bundled into a zip file and uploaded to an external remote web server. The [manifest.json](#manifest) file references the source code file path and the function name within the code that should be invoked for each [plugin type]({{< ref "plugins/plugin-types" >}}). Within the API definition, custom plugins are configured simply using the name of the bundle (zip file). Tyk Gateway downloads, caches, extracts and executes plugins from the downloaded bundle according to the configuration in the manifest file. 
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +- `bundle_base_url`: A base URL that will be used to download the bundle. For example if we have `bundle-latest.zip` specified in the API settings, Tyk will fetch the following URL: `http://my-bundle
```suggestion
- `bundle_base_url`: A base URL that will be used to download the bundle. For example if we have `bundle-latest.zip` specified in the API definition, Tyk will fetch the following file: `http://my-bundle-server.com/bundles/bundle-latest.zip` (see the next section for details).
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +Remember to set `"enable_coprocess": true` in your `tyk.conf` when using rich plugins!
Probably need to add a link to definition of rich plugins - unless you're getting rid of that terminology (which I think would be a good step)...

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +A plugin bundle must include a manifest file (called `manifest.json`). The manifest file contains important information like the configuration block and the list of source code files that will be inc
What is "the configuration block"? I think this deserves a proper description. Looking at the example manifest file one would assume that it's the `custom_middleware` part of the JSON. I see there's also a checksum field - which doesn't appear to be documented.

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +If you're using Tyk Classic APIs, then you find details of how to your API to use plugin bundles [here]({{< ref "/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic" >}}).
```suggestion
If you're using Tyk Classic APIs, then you can find details of how to configure your API to use plugin bundles [here]({{< ref "/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic" >}}).
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +description: "This section explains how to configure Tyk Classic APIs to use plugin bundles deployed on a remote web server"
Is this exclusively about using "plugin bundles"?

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +An API can be configured so that one or more of its associated plugins can execute at different phases of the request life cycle. Each plugin configuration serves to identify the plugin source file p
Request and response

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/plugins.md
> +### Plugin Deployment
Is it a deliberate choice to capitalise all words in titles/sub-titles? There's some inconsistency going through this PR...

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +The table below illustrates the Tyk OAS API configuration parameters that correspond to each phase of the API request lifecycle:
```suggestion
This table illustrates the different phases of the API request lifecycle where custom plugins can be executed:
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +The example configuration below illustrates how to set up multiple plugins for different phases of the request lifecycle:
```suggestion
This example configuration illustrates how to set up plugins for different phases of the request lifecycle:
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +It can be seen that each plugin is configured with the specific function name and associated source file path of the file that contains the function. Furthermore, each lifecycle phase can have a list
```suggestion
It can be seen that each plugin is configured with the specific function name and associated source file path of the file that contains the function. Furthermore, each lifecycle phase (except `auth`) can have a list of plugins configured, allowing for complex processing workflows. For example, you might develop one plugin for logging and another for modifying the request in the pre request phase. When multiple plugins are configured for a phase they will be executed in the order that they appear in the API definition.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +- `disabled`: When true, disables the plugin.
This bullet style (capitalised after the `:` with fullstop at the end of the bullet) is not consistent through the docs. not sure which it should be

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +- `require_session`: When true, indicates that the plugin requires an active session. This is applicable only for post, post authentication and response plugins.
I'm not sure this is correct.... I think it means that the plugin requires the session metadata (i.e. by setting `require_session` that metadata will be available within the plugin itself)

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +This section explains how to configure Plugins for a Tyk Classic API using Tyk Dashboard. It specifically covers the use case where the source files of your plugins are deployed on the Tyk Gateway fi
Why capitalised "Plugins"?

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +To configure plugins for Tyk Classic APIs, click on the APIs item in the *API Management* menu of Dashboard and select your API to display the API editor screen. Subsequently, following the steps bel
```suggestion
Select your API from the list of *Created APIs* to reach the API designer and then follow these steps:
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +Click on the *View Raw Definition* button to display an editor for updating the Tyk Classic API Definition.
```suggestion
Click on the **View Raw Definition** button to display an editor for updating the Tyk Classic API Definition.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +Use the editor to edit the *custom_middleware* section of the [Tyk Classic API Definition]({{< ref "/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic" >}}).
```suggestion
Use the editor to edit the `custom_middleware` section of the [Tyk Classic API Definition]({{< ref "/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic" >}}).
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +An API can be configured so that one or more of its associated plugins can execute at different phases of the request life cycle. Each plugin configuration serves to identify the plugin source file p
As for the Tyk Classic page - request & response

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +The table below illustrates the Tyk OAS API configuration parameters that correspond to each phase of the API request lifecycle:
```suggestion
This table illustrates the different phases of the API request lifecycle where custom plugins can be executed:
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +The example configuration below illustrates how to set up multiple plugins for different phases of the request lifecycle:
```suggestion
This example configuration illustrates how to set up plugins for different phases of the request lifecycle:
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +We can see from the example above that the `global` object within the `middleware` section of the `x-tyk-api-gateway` configuration is used to configure plugins in a Tyk OAS API. The `pluginConfig` s
In other sections of the docs, we describe the objects that need to be configured, then given the fully working example API definition followed by a summary of what that API def will do - following this model: tell them what we're going to do, do it, tell them what we've done.

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +Click on the APIs menu item in the *API Management* menu of Dashboard and select your OAS API to display the OAS API editor screen. Subsequently, follow the steps below:
```suggestion
Select your API from the list of *Created APIs* to reach the API designer and then follow these steps:
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +Scroll down until the *Plugins Configuration* section is displayed with the option to configure a plugin driver and a list of plugin types, e.g. *Pre Plugin*, *Post Plugin* etc.
```suggestion
In the *Plugins Configuration* section, select the *Plugin Driver*, which tells Tyk which type of plugin to expect: Go, gRPC, JavaScript (OTTO), Lua or Python.

You can configure custom data that will be made available to your plugin function as a JSON formatted object in the *Config Data* option.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +#### Step 1: Configure implementation language for your plugin
```suggestion
#### Step 1: Configure plugin type and custom data
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +Select the implementation language of your plugins.
```suggestion
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +#### Step 2: Add plugins
```suggestion
#### Step 2: Configure the custom plugins
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +For each type of plugin to configure, click on the *Add Plugin* button to display a plugin configuration section:
```suggestion
For each plugin that you wish to register with the API, click on the **Add Plugin** button to display a plugin configuration section:
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +- `Function Name`: Enter the function name that implements the required behavior for your plugin.
```suggestion
- `Function Name`: Enter the name of the function within your plugin code that Tyk should invoke.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +- `Raw Body Only`: Optionally, toggle the *Raw Body Only* switch to true when you do not wish to fill body in request or response object for your plugins.
```suggestion
- `Raw Body Only`: toggle this to true when you do not wish to fill body in request or response object for your plugins.
```

Not sure about this, doesn't really make sense - checking

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +All plugins for an API should be implemented using **one** of the [supported target languages]({{< ref "plugins/supported-languages" >}}). We configure the plugin implementation language for an API b
I think this is only for Local plugins and Bundled plugins - gRPC can use any language.

The "driver" isn't just used for language, as it also indicates if it's gRPC - so I suggest a little more detail here on the driver options (this [link](https://tyk.io/docs/plugins/supported-languages/#plugin-driver-names) isn't descriptive and really only provides a reference table)

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +## Plugin configuration
Typically in these overview pages we cover the concepts rather than the detail of the configuration (that's then in the Tyk OAS/Tyk Classic pages to ensure clear scope of terminology).

So I would remove this section but add:
- a section that covers how Tyk Gateway finds/identifies the correct code to run (path/function name/driver (note that the "driver" for JavaScript is "Otto"))
- another section that covers what data is actually passed to the plugin function (raw body/session state)

You've already got a section (below) for language that mentions "driver".

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +There are three scenarios for configuring Pre, Authentication, Post Authentication and Response plugins for an API:
These aren't scenarios - these are locations where Tyk Gateway can find the plugin function. What about `Post` plugins? Are these deliberately missing? I'm not sure you need to list the different hooks here.

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +2. **Plugin bundles**: The plugin source code and configuration is bundled into a zip file that is served by a remote web server. For further details and how to configure, checkout the [plugin bundle
```suggestion
2. **Plugin bundles**: The plugin source code and configuration are bundled into a zip file that is served by a remote web server. For further details see the [plugin bundles]({{< ref "plugins/how-to-serve-plugins/plugin-bundles" >}}) page.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
> +Run the following command to create the bundle:
Probably ought to tell people what they need to have to run the `build` command - for example, do they need to hand craft a manifest.json first? Where should the plugin files be? Where should the certificate be?

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
> +By default, the bundles are signed, if no private key is specified, the program will prompt for a confirmation.
```suggestion
By default, Tyk will attempt to sign plugin bundles for improved security. If no private key is specified, the program will prompt for a confirmation. 
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
> +Usage for creating plugin bundles is displayed by issuing the following command:
Do you mean "Instructions on how to create plugin bundles..."?

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +title: Tyk OAS API Configuring Plugin Bundles
```suggestion
title: Tyk Classic API Configuring Plugin Bundles
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +description: "This section explains how to configure Tyk OAS APIs to use plugin bundles deployed on a remote web server"
```suggestion
description: "This section explains how to configure Tyk Classic APIs to use plugin bundles deployed on a remote web server"
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +tags: ["tyk plugins", "API Gateway middleware", "Custom middleware", "Custom API request"]
```suggestion
tags: ["Tyk plugins", "API Gateway middleware", "Custom middleware", "Custom API request", "Tyk Classic API"]
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +For API plugins that are deployed as [plugin bundles]({{< ref "/plugins/how-to-serve-plugins/plugin-bundles" >}}), the API should be configured with the name of the plugin bundle file to download fro
```suggestion
For custom plugins that are deployed as [plugin bundles]({{< ref "/plugins/how-to-serve-plugins/plugin-bundles" >}}), the API should be configured with the name of the plugin bundle file to download from your remote web server. Furthermore, the Gateway should be [configured]({{< ref "/plugins/how-to-serve-plugins/plugin-bundles#gateway-configuration" >}}) to enable downloading plugin bundles.
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +```json {hl_lines=["33"], linenos=true, linenostart=1}
Typically for the Tyk Classic API examples we provide a snippet of the API definition - just the relevant fields (because a full API definition is HUGE). I would delete most of these fields, just leave the lines pertaining to plugin bundles.

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +Tyk Gateway should be configured for downloading plugin bundles from a secured web server. Please consult the [plugin bundles]({{< ref "/plugins/how-to-serve-plugins/plugin-bundles" >}}) documentatio
I would be inclined to include a reminder of the settings here, so that you can say something along the lines of "with this configuration calls to the API will invoke the custom plugins defined in the manifest.json in bundle-latest.zip located at http://x.y.z/blah"
Really spell it out.

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +To configure plugin bundles for Tyk Classic APIs click on the APIs menu item in the *API Management* menu of Dashboard and select your API to display the API editor screen. Subsequently, follow the s
As for the other pages, this can be simplified and made more consistent with similar pages elsewhere. We use **bold** for labels in the UI.

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
> +tags: [ "tyk plugins", "API Gateway middleware", "Custom middleware", "Custom API request" ]
```suggestion
tags: [ "Tyk plugins", "API Gateway middleware", "Custom middleware", "Custom API request", "Tyk OAS API" ]
```

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
> +The configuration for a Tyk OAS API to fetch the download of a plugin bundle from a remote web server is encapsulated within the *middleware* configuration section of the *x-tyk-api-gateway* part of
Actually, the configuration is in the `pluginConfig` section within the `middleware.global` section of the `x-tyk-api-gateway` extension... and normally we then provide a breakdown of the fields in that section before giving the example.

With Tyk OAS, because the API definition is minimal, you can strip out everything unnecessary - just ensure that a user can click on the "copy" icon in the docs and then paste that in as a new API... and it should "just work" (though of course here they would need to provide a valid bundle file 😄 )

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
> +In the example above we can see that the *pluginConfig* section contains a *bundle* JSON entity that contains the following configuration parameters:
So this explanation of fields usually goes before the example - and afterwards there's some standard wording we use to say "this is a valid Tyk OAS API definition... blah blah..."

2024-09-03 14:53 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
> +To configure plugin bundles for Tyk OAS APIs click on the APIs menu item in the *API Management* menu of Dashboard and select your OAS API to display the OAS API editor screen. Subsequently, follow t
As for the Tyk Classic API page - this could be improved and made closer to the existing pages for other middleware.
Note never to use the term "OAS API" please (regardless of bugs in the UI 🙈 )

2024-09-04 10:29 UTC, dcs3spp commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +Remember to set `"enable_coprocess": true` in your `tyk.conf` when using rich plugins!
For time being adding link to _plugins/how-to-serve-plugins/plugin-bundles_

Review of terminology for rich plugins could be done in another iteration

2024-09-04 10:30 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +Subsequently, plugins can be used to customize and enhance the capabilities of your APIs through integration with external services and databases to perform operations such as data transformation, cu
updated

2024-09-04 10:56 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +description: "This section explains how to configure Tyk Classic APIs to use plugin bundles deployed on a remote web server"
updated

2024-09-04 10:59 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +An API can be configured so that one or more of its associated plugins can execute at different phases of the request life cycle. Each plugin configuration serves to identify the plugin source file p
Updated to _An API can be configured so that one or more of its associated plugins can execute at different phases of the request / response lifecycle. Each plugin configuration serves to identify the plugin source file path and the name of the corresponding function, triggered at each request / response lifecycle stage._

2024-09-04 11:26 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +- `require_session`: When true, indicates that the plugin requires an active session. This is applicable only for post, post authentication and response plugins.
Updated

2024-09-04 11:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +This section explains how to configure Plugins for a Tyk Classic API using Tyk Dashboard. It specifically covers the use case where the source files of your plugins are deployed on the Tyk Gateway fi
updated

2024-09-04 11:30 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +An API can be configured so that one or more of its associated plugins can execute at different phases of the request life cycle. Each plugin configuration serves to identify the plugin source file p
An API can be configured so that one or more of its associated plugins can execute at different phases of the request / response life cycle. Each plugin configuration serves to identify the plugin source file path and the name of the corresponding function, triggered at each request / response lifecycle stage.

2024-09-04 11:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +There are three scenarios for configuring Pre, Authentication, Post Authentication and Response plugins for an API:
Updated to with _There are three locations where Tyk Gateway can find plugin functions:_

2024-09-04 11:50 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
> +Usage for creating plugin bundles is displayed by issuing the following command:
Updated, replaced with _Instructions on how to create plugin bundles is displayed by issuing the following command:_

2024-09-04 12:03 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +```json {hl_lines=["33"], linenos=true, linenostart=1}
Included full example based on previous [review](https://github.com/TykTechnologies/tyk-docs/pull/4918#discussion_r1684788265). Is the following fragment ok?

```json
{
  ...
  "custom_middleware_bundle": "bundle-latest.zip"
}
```

2024-09-04 13:16 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
> +The configuration for a Tyk OAS API to fetch the download of a plugin bundle from a remote web server is encapsulated within the *middleware* configuration section of the *x-tyk-api-gateway* part of
Thanks Andy, I have updated explanation of config section and added breakdown of fields in the section before the example. I updated the example API Definition based on [previous review comment](https://github.com/TykTechnologies/tyk-docs/pull/4918#discussion_r1684788265). Which fields should be removed and which fields should be kept in the example?

2024-09-04 13:57 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
> +In the example above we can see that the *pluginConfig* section contains a *bundle* JSON entity that contains the following configuration parameters:
Updated with standard sentence

2024-09-04 14:28 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +All plugins for an API should be implemented using **one** of the [supported target languages]({{< ref "plugins/supported-languages" >}}). We configure the plugin implementation language for an API b
Updated with:

_For local and bundle plugins a [plugin driver]({{< ref "plugins/supported-languages#plugin-driver-names" >}}) is configured to specify the plugin implementation language. If using gRPC plugins a `grpc` plugin driver should be used to instruct Tyk to request execution of plugins from within a gRPC server that is external to the Tyk process. This offers additional language support since Tyk can integrate with a gRPC server that is implemented using any supported [gRPC language](https://grpc.io/docs/)._

2024-09-04 15:39 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +We can see from the example above that the `global` object within the `middleware` section of the `x-tyk-api-gateway` configuration is used to configure plugins in a Tyk OAS API. The `pluginConfig` s
updated

2024-09-04 15:47 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +Tyk Gateway should be configured for downloading plugin bundles from a secured web server. Please consult the [plugin bundles]({{< ref "/plugins/how-to-serve-plugins/plugin-bundles" >}}) documentatio
Updated as follows:

_With the configuration given in the example above, calls to the API will invoke the custom plugins defined in the `manifest.json` file contained within `bundle-latest.zip` uploaded to your remote webserver, e.g. `http://your-example-plugin-server.com/plugins`._

2024-09-05 11:46 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
> +Run the following command to create the bundle:
Thanks @andyo-tyk I have created a [ticket](https://tyktech.atlassian.net/browse/DX-1652) to address the issue in a  separate iteration

@letzya

2024-09-05 12:17 UTC, dcs3spp commented on tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
> +A plugin bundle must include a manifest file (called `manifest.json`). The manifest file contains important information like the configuration block and the list of source code files that will be inc
Created a separate [ticket](https://tyktech.atlassian.net/browse/DX-1654) to expand content that explains manifest.json file and documents checksum

2024-09-05 13:12 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
> +To configure plugin bundles for Tyk OAS APIs click on the APIs menu item in the *API Management* menu of Dashboard and select your OAS API to display the OAS API editor screen. Subsequently, follow t
Removed term OAS API to read:

_To configure plugin bundles for Tyk OAS APIs click on the APIs menu item in the *API Management* menu of Dashboard and select your API to display the editor screen. Subsequently, follow the steps below:_

Have created [ticket](https://tyktech.atlassian.net/browse/DX-1653) to address consistency of style for UI review comment 

@letzya

2024-09-05 13:24 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
> +To configure plugin bundles for Tyk Classic APIs click on the APIs menu item in the *API Management* menu of Dashboard and select your API to display the API editor screen. Subsequently, follow the s
Thanks Andy, I have created [ticket](https://tyktech.atlassian.net/browse/DX-1653) to address consistency of style for UI review comment.

@letzya

2024-09-05 13:27 UTC, dcs3spp commented on tyk-docs/content/plugins.md
> +### Plugin Deployment
Thanks Andy, I have created a [ticket](https://tyktech.atlassian.net/browse/DX-1656) to address in separate iteration.

@letzya

2024-09-05 13:27 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
> +- `disabled`: When true, disables the plugin.
Thanks Andy, I have created a [ticket](https://tyktech.atlassian.net/browse/DX-1656) to address in separate iteration.

@letzya

2024-09-05 13:37 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
> +## Plugin configuration
Thanks Andy, I have raised a [ticket](https://tyktech.atlassian.net/browse/DX-1657) to cover in separate iteration

@letzya

2024-09-05 13:40 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
> +- `Raw Body Only`: Optionally, toggle the *Raw Body Only* switch to true when you do not wish to fill body in request or response object for your plugins.
Thanks Andy I have created a [ticket](https://tyktech.atlassian.net/browse/DX-1658) to update in another iteration.

@letzya

2024-09-05 13:51 UTC, dcs3spp commented
Thanks @andyo-tyk for the full review. I have created another [ticket](https://tyktech.atlassian.net/browse/DX-1651) with subtasks to address review issues in another iteration. We will merge this into the parent [PR](https://github.com/TykTechnologies/tyk-docs/pull/4918) and then publish.

2024-09-05 14:56 UTC, merged