[DX-1655, TT-12355] added docs on gateway log format
TykTechnologies/tyk-docs-hugo pull request #5346
Opened 2024-09-05 13:20 UTC by LLe27

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>
[FR - Add the option for JSON format in Gateway log](https://tyktech.atlassian.net/browse/TT-12355)
[Add JSON format to log docs](https://tyktech.atlassian.net/browse/DX-1655)
---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-05 13:28 UTC, LLe27 commented
@dcs3spp not sure what the reasoning is but in our main docs page this page in particular doesn't even show up in the search which is a bit unfortunate since it is quite a key feature. Please let me know how we can improve the search of this page. Thanks

2024-09-05 13:37 UTC, titpetric commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway version `v5.6.0`, you can control log format using the `TYK_GW_LOGFORMAT` environment variable. By default, logs are in standard format, but setting `TYK_GW_LOGFORMAT` to `json` wil
This needs adjustment to list the 5.3 LTS release as well

2024-09-05 13:38 UTC, titpetric commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway version `v5.6.0`, you can control log format using the `TYK_GW_LOGFORMAT` environment variable. By default, logs are in standard format, but setting `TYK_GW_LOGFORMAT` to `json` wil
Document as above, TYK_LOGFORMAt / TYK_LOGLEVEL (`_GW` prefix isn't in use in this doc)

2024-09-05 13:43 UTC, LLe27 commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway version `v5.6.0`, you can control log format using the `TYK_GW_LOGFORMAT` environment variable. By default, logs are in standard format, but setting `TYK_GW_LOGFORMAT` to `json` wil
Gotcha I wasn't sure cause I only saw `v5.6.0` listed in the fixed versions. Just to confirm both LTS `v5.3` and `v5.6.x` will include these changes?

2024-09-05 13:44 UTC, LLe27 commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway version `v5.6.0`, you can control log format using the `TYK_GW_LOGFORMAT` environment variable. By default, logs are in standard format, but setting `TYK_GW_LOGFORMAT` to `json` wil
Will update the configs accordingly

2024-09-05 14:11 UTC, dcs3spp requested changes
Thanks @LLe27 I have made suggestions relating to additional search tags and made suggestions to add section headings for the examples

2024-09-05 14:11 UTC, dcs3spp commented on tyk-docs/content/log-data.md
> +tags: ["logging", "observability", "system events", "logs", "json", "log format"]
@LLe27 The tags are used for search indexing and headings. Maybe also add tags for JSON, logging, logging format. In a separate comment I have made suggestions for sub headings for Standard and JSON format logging

2024-09-05 14:11 UTC, dcs3spp commented on tyk-docs/content/log-data.md
> +**Standard Format:**
```suggestion
##### Standard logging format
```

2024-09-05 14:11 UTC, dcs3spp commented on tyk-docs/content/log-data.md
> +**JSON Format:**
```suggestion
##### JSON logging format
```

2024-09-05 15:05 UTC, LLe27 commented on tyk-docs/content/log-data.md
> +tags: ["logging", "observability", "system events", "logs", "json", "log format"]
Gotcha thanks! Will remove json for now but I think log format for search indexing would be worth keeping.

2024-09-10 09:28 UTC, dcs3spp approved these changes
Thanks @LLe27 I have approved changes and once link has been added to env var when config synced into docs we can merge and release. @titpetric if the changes requested from @LLe27 are ok would you be able to peer approve?

2024-09-12 20:12 UTC, titpetric commented on tyk-docs/content/log-data.md
> +
```suggestion
As a general performance tuning note, the `json` output provides less allocation overhead than the standard logger. When tuning for performance, it's recommended to use the JSON logging format.
```

2024-09-12 21:35 UTC, titpetric commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway version `v5.6.0`, you can control log format using the `TYK_GW_LOGFORMAT` environment variable. By default, logs are in standard format, but setting `TYK_GW_LOGFORMAT` to `json` wil
@LLe27 for now, how about opening a dashboard PR? :)

2024-09-13 12:27 UTC, LLe27 commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway version `v5.6.0`, you can control log format using the `TYK_GW_LOGFORMAT` environment variable. By default, logs are in standard format, but setting `TYK_GW_LOGFORMAT` to `json` wil
@titpetric that's on my todo list, with your guidance of course! ;)

2024-09-20 08:38 UTC, sharadregoti requested changes
Can you add a section regarding log_format at the TYK gateway configuration options?

Just below `log_level`

https://deploy-preview-5346--tyk-docs.netlify.app/docs/nightly/tyk-oss-gateway/configuration/#log_level

2024-09-20 08:38 UTC, sharadregoti commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway versions LTS `v5.3` and `v5.6.0`, you can control log format using the `TYK_LOGFORMAT` environment variable. By default, logs are in standard format, but setting `TYK_LOGFORMAT` to
```suggestion
As of Tyk Gateway versions LTS `v5.3` and `v5.6.0`, you can control log format using the `TYK_LOGFORMAT` environment variable. By default, logs are in `default` format, but setting `TYK_LOGFORMAT` to `json` will output logs in JSON format.
```
This environment variable accepts only two options: `default` or `json`. Let's refer the standard format as the default format.

Reference Code: https://github.com/TykTechnologies/tyk/blob/master/log/log.go#L71

2024-09-20 08:38 UTC, sharadregoti commented on tyk-docs/content/log-data.md
> +##### Standard logging format
```suggestion
##### Default logging format
```

2024-09-20 08:38 UTC, sharadregoti commented on tyk-docs/content/log-data.md
> +As a general performance tuning note, the `json` output provides less allocation overhead than the standard logger. When tuning for performance, it's recommended to configure the JSON logging format.
```suggestion
{{< note >}}
**Note**  
As a general performance tip, the `json` output format incurs less memory allocation overhead than the default logger. For optimal performance, it's recommended to configure logging in the JSON format.
{{< /note >}}
```

@LLe27 When you are referring to less allocation, it is with respect to `memory` right?

2024-09-20 13:00 UTC, LLe27 commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway versions LTS `v5.3` and `v5.6.0`, you can control log format using the `TYK_LOGFORMAT` environment variable. By default, logs are in standard format, but setting `TYK_LOGFORMAT` to
@sharadregoti correct! Thanks for the review.

2024-09-20 13:00 UTC, LLe27 commented on tyk-docs/content/log-data.md
> +As a general performance tuning note, the `json` output provides less allocation overhead than the standard logger. When tuning for performance, it's recommended to configure the JSON logging format.
@sharadregoti correct!

2024-09-25 07:29 UTC, sharadregoti approved these changes

2024-10-01 12:58 UTC, sharadregoti requested changes

2024-10-01 12:58 UTC, sharadregoti commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway versions LTS `v5.3` and `v5.6.0`, you can control log format using the `TYK_LOGFORMAT` environment variable. By default, logs are in `default` format, but setting `TYK_LOGFORMAT` to
```suggestion
As of Tyk Gateway versions LTS `v5.3.6` and `v5.6.0`, you can control log format using the `TYK_LOGFORMAT` environment variable. By default, logs are in `default` format, but setting `TYK_LOGFORMAT` to `json` will output logs in JSON format.
```

2024-10-02 15:06 UTC, LLe27 commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway versions LTS `v5.3` and `v5.6.0`, you can control log format using the `TYK_LOGFORMAT` environment variable. By default, logs are in `default` format, but setting `TYK_LOGFORMAT` to
I think it's slotted for `v5.6.0` now. @titpetric can you confirm which version of `v5.3.x` it is merged to? Thankjs

2024-10-10 12:13 UTC, letzya commented on tyk-docs/content/log-data.md
> +As of Tyk Gateway versions LTS `v5.3` and `v5.6.0`, you can control log format using the `TYK_LOGFORMAT` environment variable. By default, logs are in `default` format, but setting `TYK_LOGFORMAT` to
we'll put 5.3.6 based on the changelog of 5.3.6 FYI @andyo-tyk @lghiur

2024-10-10 12:14 UTC, sharadregoti approved these changes

2024-10-10 12:14 UTC, letzya commented on tyk-docs/content/log-data.md
> +```
```suggestion
```json
```

2024-10-10 12:20 UTC, merged