Update custom-resources.md
TykTechnologies/tyk-docs-hugo pull request #5382
Opened 2024-09-09 14:43 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-10 09:18 UTC, dcs3spp requested changes
Thanks @caroltyk PR LGTM,  I have reviewed pages in the PR that are marked ready for review with minor suggestions

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-api-overview.md
> +## Creating an API with Tyk Operator
In keeping with other sections, e.g.[ allow list middleware](https://tyk.io/docs/product-stack/tyk-gateway/middleware/allow-list-middleware/), make style of linking to tutorials for OAS and Classic sections consistent.

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +This step-by-step tutorial will guide you through the process of creating a Tyk OAS API using the Tyk Operator in your Kubernetes environment. The Tyk Operator allows you to manage your APIs declarat
should remove the Tyk Operator and replace without using the, for example:

- Tyk OAS API ising Tyk Operator in your Kubernetes environment......
- Tyk Operator allows you to.....

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +```json
Add line break before the JSON example and add line nums and syntax highlighting

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +{{< note success >}}
Similar to other [sections](https://tyk.io/docs/product-stack/tyk-gateway/middleware/allow-list-tyk-oas/#configuring-the-allow-list-in-the-api-designer) add a subsection with accompanying screenshots to highlight how to configure in Dashboard

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +To verify that the API has been successfully created:
Replace with

```suggestion
To verify that the API has been successfully created, check the status of the TykOasApiDefinition resource:
```

and remove line 115

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +```
```suggestion
```bash
```

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +curl curl "TYK_GATEWAY_URL/petstore/store/inventory"
remove duplicate curl command

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +kubectl create configmap tyk-oas-api-config --from-file=oas-api-definition.json -n tyk --dry-run=client -o yaml | kubectl replace -f -
should the file name be `oas-api-definition.yaml`?

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-oas.md
> +title: Sample Tyk OAS API
Should the title be updated to reflect that it is a quick start guide and then add sections for each step of the quickstart? Or alternatively, should the file be renamed to example-tyk-oas-api and the page title be updated Example Tyk OAS API?

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/tyk-oas-api-definition.md
> +The TykOasApiDefinition custom resource definition (CRD) manages [Tyk OAS API Definition object]({{<ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc">}}) within a Kubernetes environment. This CRD enab
```suggestion
The TykOasApiDefinition Custom Resource Definition (CRD) manages [Tyk OAS API Definition object]({{<ref "tyk-apis/tyk-gateway-api/oas/x-tyk-oas-doc">}}) within a Kubernetes environment. This CRD enables the integration and management of Tyk API definitions using Kubernetes-native tools, simplifying the process of deploying and managing OAS APIs on the Tyk Dashboard.
```

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/tyk-oas-api-definition.md
> +- **categories** (`array` of `string`): Identifiers for API definitions that enable filtering based on these categories.
Should we conclude with an example so that the reader can see examples of the list fields?

2024-09-10 09:18 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/reference/tyk-oas-api-definition.md
> +The status (`status`) of a `TykOasApiDefinition` resource provides the observed state of the API definition.
Should we conclude with an example?

2024-09-10 12:46 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-api-overview.md
> +## Creating an API with Tyk Operator
updated

2024-09-10 12:47 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +This step-by-step tutorial will guide you through the process of creating a Tyk OAS API using the Tyk Operator in your Kubernetes environment. The Tyk Operator allows you to manage your APIs declarat
updated at https://github.com/TykTechnologies/tyk-docs/pull/5382/commits/e91ebcf6eaa21639be8a6844f6303187dc5ae82e

2024-09-10 12:48 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +```json
updated at https://github.com/TykTechnologies/tyk-docs/pull/5382/commits/e91ebcf6eaa21639be8a6844f6303187dc5ae82e

2024-09-10 12:51 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +curl curl "TYK_GATEWAY_URL/petstore/store/inventory"
updated

2024-09-10 12:57 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +kubectl create configmap tyk-oas-api-config --from-file=oas-api-definition.json -n tyk --dry-run=client -o yaml | kubectl replace -f -
no configmap is in Json form

2024-09-10 12:58 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-oas.md
> +title: Sample Tyk OAS API
file renamed

2024-09-10 12:59 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-operator/reference/tyk-oas-api-definition.md
> +- **categories** (`array` of `string`): Identifiers for API definitions that enable filtering based on these categories.
examples to be added when we create examples of the different features later

2024-09-10 13:01 UTC, carolwkc commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +To verify that the API has been successfully created:
updated at https://github.com/TykTechnologies/tyk-docs/pull/5382/commits/e91ebcf6eaa21639be8a6844f6303187dc5ae82e

2024-09-10 16:25 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +kubectl create configmap tyk-oas-api-config --from-file=oas-api-definition.json -n tyk --dry-run=client -o yaml | kubectl replace -f -
ok thanks @caroltyk I'll resolve the comment

2024-09-10 16:38 UTC, dcs3spp reviewed
Added review comments for example Tyk OAS API

2024-09-10 16:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +You need to create a [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object) in Kubernetes to store your OAS API definition. The Tyk Operator will reference this Co
Update OAS API Definition to Tyk OAS API definition to have consistent with other pages in the site

2024-09-10 16:38 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/getting-started/example-tyk-oas-api.md
> +
Before the concluding paragraph maybe summarise the example to explain/remind the reader that a `ConfigMap` should be created that contains the Tyk OAS API Definition with the `data` field. Then explain that this is linked to from a `TykOasApiDefinition` resource via `spec.tykOAS.configmapRef` and add syntax highlighting to the yaml example highlighting the relevant lines.

2024-09-11 13:30 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +You need to create a [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object) in Kubernetes to store your OAS API definition. The Tyk Operator will reference this Co
```suggestion
You need to create a [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object) in Kubernetes to store your Tyk OAS API definition. The Tyk Operator will reference this ConfigMap to retrieve the API configuration.
```

2024-09-12 08:53 UTC, dcs3spp requested changes
Review for Tyk as ingress controller content:

2024-09-12 08:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +To implement these routing rules, Kubernetes relies on an [Ingress Controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/). The Ingress Controller is a component tha
Add external links for NGINX & HAProxy

2024-09-12 08:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +```yaml
add syntax highlighting

2024-09-12 08:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +  In the given example, Tyk Operator is designated as the Ingress Controller for this Ingress resource. Tyk Operator reads this Ingress definition and automatically creates a corresponding API in the
```suggestion
In the given example, Tyk Operator is designated as the Ingress Controller for this Ingress resource. Tyk Operator reads this Ingress definition and automatically creates a corresponding API in the Tyk Gateway. The API will have:
```

2024-09-12 08:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +  In the given example, there are two important annotations in the Ingress metadata:
```suggestion
In the given example, there are two important annotations in the Ingress metadata:
```

2024-09-12 08:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +  Note that `ApiDefinition` or `TykOasApiDefinition` created for use as a template for Ingress resources should have a label `template: "true"` so that Tyk Operator would not manage it as ordinary AP
Remove spaces before this paragraph and in similar instances below

2024-09-12 08:53 UTC, dcs3spp commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +```yaml
Add syntax highlighting

2024-09-12 12:41 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/getting-started/example-tyk-oas-api.md
> +
Update at https://github.com/TykTechnologies/tyk-docs/pull/5382/commits/a985b3d456b1d45370726da58416873effa8ba74

2024-09-12 12:42 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +To implement these routing rules, Kubernetes relies on an [Ingress Controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/). The Ingress Controller is a component tha
I don't think we need to because users do not need to learn from other products.

2024-09-12 12:45 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +  Note that `ApiDefinition` or `TykOasApiDefinition` created for use as a template for Ingress resources should have a label `template: "true"` so that Tyk Operator would not manage it as ordinary AP
I have added spaces because I want it to be indented with the bullet point.

2024-09-12 12:48 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +```yaml
Updated at https://github.com/TykTechnologies/tyk-docs/pull/5382/commits/45ea9c026413a3c5b1e174b4a1e22e1aef8fba23

2024-09-12 12:48 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +```yaml
Updated at https://github.com/TykTechnologies/tyk-docs/pull/5382/commits/45ea9c026413a3c5b1e174b4a1e22e1aef8fba23

2024-09-16 11:43 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/api-categories.md
> +For a Tyk Classic API, you can specify the category name using the `name` field with a `#` qualifier. This will categorize the API in the Tyk Dashboard. See [How API categories work]({{<ref "product-
```suggestion
For a Tyk Classic API, you can specify the category name using the `name` field with a `#` qualifier. This will categorize the API in the Tyk Dashboard. See [How API categories work]({{<ref "product-stack/tyk-dashboard/advanced-configurations/api-categories#tyk-classic-apis">}}) to learn about limitations on API names.
```

2024-09-16 11:43 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +2. Tyk Operator installed in your Kubernetes cluster.
maybe we can give the link of operator installation page here

2024-09-16 11:43 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +kubectl create configmap tyk-oas-api-config --from-file=oas-api-definition.json -n tyk
Given Kubernetes' annotation size limitations, I wondered if we could discuss the use of 'create' instead of 'apply' while creating confimap for tykoas. It might be helpful to mention that if the ConfigMap content exceeds a certain size, the 'apply' command may fail. We've noted something similar below, but perhaps we could address it here from a Kubernetes perspective. what do you think?

2024-09-16 11:43 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-api-ownership.md
> +In this example, the `ApiDefinition` object references the `team-alpha` context, ensuring that it is managed under the ownership of the specified users and user groups.
Please ignore the suggestion if i am wrong 😄 
```suggestion
In this example, the `TykOasApiDefinition` object references the `team-alpha` context, ensuring that it is managed under the ownership of the specified users and user groups.
```

2024-09-16 11:43 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +  Note that `ApiDefinition` or `TykOasApiDefinition` created for use as a template for Ingress resources should have special label set so that Tyk Operator would not manage it as ordinary APIs. Here
```suggestion
  Note that `ApiDefinition` or `TykOasApiDefinition` created for use as a template for Ingress resources should have a special label set so that Tyk Operator would not manage it as ordinary APIs. Here is the required label for `ApiDefinition` and `TykOasApiDefinition` respectively:
```

2024-09-16 18:41 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +2. Tyk Operator installed in your Kubernetes cluster.
```suggestion
2. [Tyk Operator]({{<ref "tyk-stack/tyk-operator/installing-tyk-operator">}}) installed in your Kubernetes cluster.
```

2024-09-16 19:07 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +kubectl create configmap tyk-oas-api-config --from-file=oas-api-definition.json -n tyk
Thanks - I've updated with another notes regarding use of kubectl apply

2024-09-20 13:48 UTC, letzya commented
@sharadregoti Once @caroltyk changes this PR to ready, and message us to publish it, as long as the CI is green you can merge it to  5.6

2024-09-26 09:41 UTC, buraksekili approved these changes
lgtm

2024-09-26 09:43 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
> +    tyk.io/template: "true"
```suggestion
    tyk.io/ingress-template: "true"
```

2024-10-07 16:33 UTC, caroltyk commented
The changes in this PR is included in #5460

2024-10-07 16:33 UTC, closed without merging