Release Notes 5.5.1 Gateway
TykTechnologies/tyk-docs-hugo pull request #5398
Opened 2024-09-11 16:01 UTC by dcs3spp

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1682](https://tyktech.atlassian.net/browse/DX-1682)

---

### Preview Link

[preview - to add](/docs/nightly)

### Description

Add Gateway release notes for Gateway 5.5.1

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-11 16:05 UTC, dcs3spp commented
@caroltyk Please check Tyk charts version associated with release notes 5.5.1 is correct and update accordingly.

After this PR has been published please create a separate PR to include a download link for Tyk Charts when released.

2024-09-17 11:22 UTC, andyo-tyk requested changes
Added change log content, moved Release Highlights to the top of each section for improved visibility. Just needs to have release date added and downloads section to be completed.

2024-09-20 10:20 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +</details>
```suggestion

The example Gateway configuration file `tyk.conf.example` has been updated to set the recommended *exact matching* with:

 - `http_server_options.enable_path_prefix_matching = true`
 - `http_server_options.enable_path_suffix_matching = true`
 - `http_server_options.enable_strict_routes = true`
 </details>
```

2024-09-20 10:22 UTC, andyo-tyk approved these changes

2024-09-24 12:16 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +### Release Date ?? September 2024
```suggestion
### Release Date 18 September 2024
```

2024-09-24 14:46 UTC, caroltyk approved these changes
LGTM

2024-09-26 12:43 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +### Release Date 24 September 2024
```suggestion
### Release Date 26 September 2024
```

2024-09-26 13:14 UTC, sharadregoti approved these changes

2024-09-26 13:22 UTC, merged

2024-09-26 13:22 UTC, sharadregoti commented
/release to release-5.5