Tyk Charts v2.0 release notes
TykTechnologies/tyk-docs-hugo pull request #5459
Opened 2024-09-24 14:17 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-24 16:18 UTC, andyo-tyk requested changes

2024-09-24 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
> +
```suggestion

From this version of Tyk Charts we also set the following configuration option to `true` by default as part of the stricter path matching:

- `http_server_options.enable_strict_routes`
```

2024-09-24 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
> +- The change is **backward-compatible** for users upgrading their Tyk Gateway directly (i.e. not via Helm Chart), because by default, the new options are set to `false`. This ensures that existing co
```suggestion
- The change is **backward-compatible** for users upgrading their Tyk Gateway directly (i.e. not via Helm Chart), because by default, these features will not be active. This ensures that existing configurations are not affected if you update the Gateway manually.
```

2024-09-24 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
> +MDCB v2.7.0 release introduces `/liveness` and `/readiness` probes which give more accurate and detail health check information. MDCB deployment has been updated to use the new endpoints. See [MDCB H
```suggestion
The default Gateway configuration in the Helm chart will set Tyk's URL path matching to **exact** mode. This ensures that the request URL must exactly match the listen path and endpoint patterns configured in the API definition. 
```

2024-09-24 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
> +- `gateway.enablePathSuffixMatching` (default to `true`)
```suggestion
- `gateway.enablePathSuffixMatching` (default to `true`)
- `gateway.enableStrictRoutes` (default to `true`)
```

2024-09-24 16:18 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
> +The options are configurable using these `tyk-gateway` chart's parameters:
```suggestion
URL path matching mode is configurable using these `tyk-gateway` chart parameters:
```

2024-09-24 16:20 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
> +Tyk Charts 1.6 will install the following Tyk component versions by default.
```suggestion
Tyk Charts 2.0 will install the following Tyk component versions by default.
```

2024-09-25 07:35 UTC, komalsukhani requested changes

2024-09-25 07:35 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
> +- `http_server_options.enable_strict_routes`
<img width="836" alt="Screenshot 2024-09-25 at 12 59 06 PM" src="https://github.com/user-attachments/assets/9a48da8c-947f-406b-8bdd-3951d2462fa7">
Impact on existing users and this option is appearing on same line

2024-09-25 09:08 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
> +- `http_server_options.enable_strict_routes`
```suggestion
- `http_server_options.enable_strict_routes`

```

2024-09-25 11:50 UTC, komalsukhani approved these changes

2024-09-26 12:30 UTC, andyo-tyk approved these changes
LGTM

2024-09-26 13:27 UTC, carolwkc commented
Release date updated

2024-09-26 14:03 UTC, merged

2024-09-26 14:04 UTC, sharadregoti commented
/release to release-5.5

2024-09-26 14:04 UTC, sharadregoti commented
/release to release-5.3