Operator release
TykTechnologies/tyk-docs-hugo pull request #5460
Opened 2024-09-25 15:17 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-09-30 22:11 UTC, letzya commented on tyk-docs/content/tyk-oss/ce-kubernetes-ingress.md
> ----
@caroltyk when you delete a page you need to add an alias for it in another page otherwise calling it tyk.io/docs/tyk-oss/ce-kubernetes-ingress will cause a 404 for the user or a bot-crawler so we have a CI test against that.

2024-10-07 09:39 UTC, komalsukhani requested changes

2024-10-07 09:39 UTC, komalsukhani commented on tyk-docs/content/tyk-operator.md
> +Starting from Tyk Operator v1.0, a license key is required to use the Tyk Operator. [Sign up here](https://tyk.io/sign-up), and choose “Get in touch” to receive a guided evaluation of the Tyk Operato
I don't see a signup option on the https://tyk.io/sign-up.
Just `Get in touch` button

2024-10-07 09:39 UTC, komalsukhani commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +{{< button_left href="https://tyk.io/sign-up" color="green" content="Free Trial" >}}
Free trial button and the `Sign up here` link are both pointing to same link.
Is it intended?

2024-10-07 09:39 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-2.0.md
> +As of Tyk Sync v2.0, support for the **Open Source Tyk Gateway** has been removed. Tyk Sync v2.0 is now compatible exclusively with licensed Tyk Dashboard. This change means that Tyk Sync can no long
Should we say support for OSS has been deprecated instead of removed?

2024-10-07 09:39 UTC, komalsukhani commented on tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
> +#### Define via Tyk Operator (Tyk Classic){#tyk-operator-classic}
@caroltyk I don't think this is right place for custom domain example.
This page explains how to set domain for dashboard/gateway. Operator examples are for setting custom domain for an API.

2024-10-07 09:39 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
> +There are inherent size limit of a ConfigMap. The data stored in a ConfigMap cannot exceed 1 MiB. In case your OpenAPI document exceeds this size limit, it is recommended to split your API into small
```suggestion
There is inherent size limit to a ConfigMap. The data stored in a ConfigMap cannot exceed 1 MiB. In case your OpenAPI document exceeds this size limit, it is recommended to split your API into smaller sub-APIs for easy management. For details, please consult [Best Practices for Describing Large APIs](https://learn.openapis.org/best-practices.html#describing-large-apis) from the OpenAPI initiative.
```

2024-10-07 09:39 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/getting-started/example-tyk-oas-api.md
> +Here, a `ConfigMap` is created that contains the Tyk OAS API Definition with the `data` field with key `test_oas.json`. This is linked to from a `TykOasApiDefinition` resource via `spec.tykOAS.config
```suggestion
Here, a `ConfigMap` is created that contains the Tyk OAS API Definition with the `data` field with key `test_oas.json`. This is linked to `TykOasApiDefinition` resource via `spec.tykOAS.configmapRef`.
```

2024-10-07 09:39 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-operator/getting-started/secure-an-oas-api.md
> +In this example, we added the following sections to configure API key authentication for this API.
```suggestion
In this example, we added the following sections to configure key authentication for this API. 
```

2024-10-07 11:59 UTC, caroltyk commented on tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
> +#### Define via Tyk Operator (Tyk Classic){#tyk-operator-classic}
@komalsukhani This page also talks about API level settings:

> If you include certificateID or certificate path to an API definition certificates field, Gateway will dynamically load this ceritficate for your custom domain, so you will not need to restart the process. You can do it from the Dashboard UI too, in the custom domain section

I think operator is setting the same certificates field in API Def?

Let me know if you found another page more appropriate to the examples.

2024-10-07 12:01 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-operator/getting-started/example-tyk-oas-api.md
> +Here, a `ConfigMap` is created that contains the Tyk OAS API Definition with the `data` field with key `test_oas.json`. This is linked to from a `TykOasApiDefinition` resource via `spec.tykOAS.config
```suggestion
Here, a `ConfigMap` is created that contains the Tyk OAS API Definition with the `data` field with key `test_oas.json`. This is linked to from a `TykOasApiDefinition` resource via `spec.tykOAS.configmapRef`.
```

2024-10-07 16:35 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-2.0.md
> +As of Tyk Sync v2.0, support for the **Open Source Tyk Gateway** has been removed. Tyk Sync v2.0 is now compatible exclusively with licensed Tyk Dashboard. This change means that Tyk Sync can no long
We no longer support the use of it.

2024-10-07 17:41 UTC, buraksekili commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +{{< button_left href="https://tyk.io/sign-up" color="green" content="Free Trial" >}}
I actually took this statement from https://github.com/TykTechnologies/tyk-docs/blob/87ac38ce38cebfd3dd988c32cb25dba2861f7460/tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md?plain=1#L33-L34. I am not sure if it is intended as is for some purposes or not

2024-10-08 09:15 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +Starting from Tyk Operator v1.0, a license key is required to use the Tyk Operator. You can provide it while installing Tyk Stack or Tyk OSS helm chart by setting `global.license.operator` field. You
@komalsukhani how about control plane chart?

2024-10-08 09:17 UTC, carolwkc commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
>  #### Step 1: Create tyk-operator-conf secret
```suggestion
#### Step 1: Configure Tyk Operator via environment variable or tyk-operator-conf secret
```

2024-10-08 09:18 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +    value: "8080"
Please list all the mandatory envVars in the example

2024-10-08 09:21 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +Tyk Operator configurations can be set using `envVars` field of helm chart.
```suggestion
Tyk Operator configurations can be set using `envVars` field of helm chart. See the table below for a list of expected environment variable names and example values.
```

2024-10-08 09:22 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +| Key                                         | Type   | Default                                |
@komalsukhani please add license key configuration here too

2024-10-08 09:25 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +To provide the license key for Tyk Operator, Kubernetes secret used to configure Tyk Operator (typically named tyk-operator-conf as described above) requires an additional field called `TYK_OPERATOR_
@komalsukhani @buraksekili Can I set through global.license.operator or global.secrets.useSecretName field during upgrade?

2024-10-09 07:55 UTC, komalsukhani commented on tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
> +#### Define via Tyk Operator (Tyk Classic){#tyk-operator-classic}
I missed that section. I thought that page was for Gateway/Dashboard configuration settings.

2024-10-09 07:57 UTC, komalsukhani commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +Starting from Tyk Operator v1.0, a license key is required to use the Tyk Operator. You can provide it while installing Tyk Stack or Tyk OSS helm chart by setting `global.license.operator` field. You
Opps missed control plane chart. I will update this part.

2024-10-09 07:57 UTC, komalsukhani commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +To provide the license key for Tyk Operator, Kubernetes secret used to configure Tyk Operator (typically named tyk-operator-conf as described above) requires an additional field called `TYK_OPERATOR_
Yes

2024-10-09 10:27 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +To provide the license key for Tyk Operator, Kubernetes secret used to configure Tyk Operator (typically named tyk-operator-conf as described above) requires an additional field called `TYK_OPERATOR_
So user can use the global field with tyk-operator chart too is it?

```suggestion
To provide the license key for Tyk Operator, you can set through `global.license.operator` or `global.secrets.useSecretName` field during upgrade. You can also update the Kubernetes secret used to configure Tyk Operator (typically named tyk-operator-conf as described above) with an additional field called `TYK_OPERATOR_LICENSEKEY`. Populate this field with your Tyk Operator license key. 
```

2024-10-09 10:33 UTC, komalsukhani commented on tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
> +To provide the license key for Tyk Operator, Kubernetes secret used to configure Tyk Operator (typically named tyk-operator-conf as described above) requires an additional field called `TYK_OPERATOR_
No. `global` field is only part of umbrella charts. 
In the operator chart, they can set it only via `envVars` or in the operator secret.

2024-10-09 12:02 UTC, komalsukhani approved these changes

2024-10-09 12:04 UTC, caroltyk commented
@sharadregoti ready for review

2024-10-09 17:39 UTC, letzya commented on tyk-docs/content/apim/open-source.md
> +{{< img src="/img/diagrams/oss-flow-2.png" alt="OSS-Guide" >}}
@sharadregoti should we just replace the new with the older image instead of creating a new file?

2024-10-09 17:47 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
> +### Define via Tyk Operator (Tyk Classic){#tyk-operator-classic}
What does it mean "Tyk Classic"?

2024-10-09 17:50 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
> +### Define via Tyk Operator (Tyk Classic){#tyk-operator-classic}
```suggestion
### Setup via Tyk Operator (Tyk Classic){#tyk-operator-classic}
```

2024-10-09 18:00 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
> +### Define via Tyk Operator (Tyk OAS){#tyk-operator-oas}
```suggestion
### Setup Static mTLS with Tyk Operator (Tyk OAS API Definition){#tyk-operator-oas}
```

2024-10-09 19:10 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
> +For Tyk OAS APIs, client certificates are managed using the `TykOasApiDefinition` CRD. You can reference Kubernetes secrets that store client certificates in your API definitions.
```suggestion
In Tyk OAS API Definition, client certificates are managed using the `TykOasApiDefinition` CRD. You can reference Kubernetes secrets that store client certificates in your API definitions.
```

2024-10-09 19:12 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
> +In this example, the `clientCertificate` section allows you to enable client certificate management and specify a list of Kubernetes secrets (`tls-cert`) that store allowed client certificates.
@caroltyk in my opinion, since the code snippet is long, it's better to explain the example beforehand, so users don't have to search on their own what it means. Moving the text before the code should sort it this ux

2024-10-09 19:14 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/upstream-mtls.md
> +### Via Tyk Operator (for Tyk Classic){#tyk-operator-classic}
@sharadregoti can you bring my suggestion for static mtls over to this section please

2024-10-09 19:17 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/upstream-mtls.md
> +   mutualTLS:
can we add highlight here @caroltyk

2024-10-09 19:18 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
> +#### Define via Tyk Operator (Tyk Classic){#tyk-operator-classic}
@sharadregoti can you bring my suggestion for static mtls over to this section please

2024-10-09 19:18 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
> +#### Define via Tyk Operator (Tyk OAS){#tyk-operator-oas}
@sharadregoti can you bring my suggestion for static mtls over to this section please

2024-10-09 19:23 UTC, letzya commented on tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
> +#### Define via Tyk Operator (Tyk Classic){#tyk-operator-classic}
```suggestion
#### Setup in Tyk Operator using Tyk Classic API Definition {#tyk-operator-classic}
```

2024-10-09 20:17 UTC, letzya commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Prior to installing Tyk Operator, ensure that a valid license key is provided by setting `global.license.operator` field in values.yaml file. You can set license key via a Kubernetes secret using `gl
@caroltyk can be fixed in another pr but I was trying to find where `useSecretName` is defined and couldn't find it (I wanted to add a link)

2024-10-09 20:32 UTC, letzya commented on tyk-docs/content/product-stack/tyk-operator/advanced-configurations/api-versioning.md
> +## Configuring API Version in Tyk OAS API{#tyk-oas-api}
```suggestion
## Configuring API Version in Tyk OAS API Definition{#tyk-oas-api}
```

2024-10-09 21:08 UTC, letzya requested changes
THe page here shows 5.3.5 while the prod has already 5.3.6 https://deploy-preview-5460--tyk-docs.netlify.app/docs/nightly/developer-support/tyk-release-summary/overview/ so needs rebase

2024-10-09 21:10 UTC, letzya commented
@caroltyk the helm chart shows v1.6 not 2.1 https://deploy-preview-5460--tyk-docs.netlify.app/docs/nightly/developer-support/tyk-release-summary/overview/

2024-10-09 21:13 UTC, letzya commented on tyk-docs/content/tyk-oss/ce-kubernetes-ingress.md
@sharadregoti @caroltyk we can't delete a file without adding an alias somewhere else - this is the reason the CI is red.

2024-10-10 06:07 UTC, sharadregoti commented
> @sharadregoti THe page here shows 5.3.5 while the prod has already 5.3.6 https://deploy-preview-5460--tyk-docs.netlify.app/docs/nightly/developer-support/tyk-release-summary/overview/ so needs rebase

I cannot see `5.3.5`. it looks good to me.

![image](https://github.com/user-attachments/assets/110df739-48f3-42ae-b835-2a6b99c6bbe4)

2024-10-10 07:21 UTC, sharadregoti commented on tyk-docs/content/apim/open-source.md
> +{{< img src="/img/diagrams/oss-flow-2.png" alt="OSS-Guide" >}}
Yes

2024-10-10 08:05 UTC, caroltyk commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/upstream-mtls.md
> +   mutualTLS:
updated at https://github.com/TykTechnologies/tyk-docs/pull/5460/commits/04e3c9468357bbdee459d9d232455f2edb0553d5

2024-10-10 08:05 UTC, caroltyk commented on tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
> +#### Define via Tyk Operator (Tyk OAS){#tyk-operator-oas}
updated at https://github.com/TykTechnologies/tyk-docs/pull/5460/commits/04e3c9468357bbdee459d9d232455f2edb0553d5

2024-10-10 08:07 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
> +Prior to installing Tyk Operator, ensure that a valid license key is provided by setting `global.license.operator` field in values.yaml file. You can set license key via a Kubernetes secret using `gl
No we don't have a generated docs for all the helm parameters so there's no link we can reference to.

2024-10-10 08:09 UTC, caroltyk commented on tyk-docs/content/tyk-oss/ce-kubernetes-ingress.md
@sharadregoti can you add alias? I don't know how to do this.

2024-10-10 08:14 UTC, caroltyk commented
> @caroltyk the helm chart shows v1.6 not 2.1 https://deploy-preview-5460--tyk-docs.netlify.app/docs/nightly/developer-support/tyk-release-summary/overview/

Updated for Helm Chart.

@letzya Who should update the version here for every release? TBH it's the first time I update this file (only for moving operator and sync up to a different section). @sharadregoti I didn't check versions for other components.

2024-10-10 08:15 UTC, caroltyk commented on tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
> +#### Define via Tyk Operator (Tyk OAS){#tyk-operator-oas}
done

2024-10-10 08:22 UTC, caroltyk commented on tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
> +#### Define via Tyk Operator (Tyk Classic){#tyk-operator-classic}
updated

2024-10-10 08:24 UTC, caroltyk commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/upstream-mtls.md
> +### Via Tyk Operator (for Tyk Classic){#tyk-operator-classic}
updated

2024-10-10 08:24 UTC, caroltyk commented on tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
> +In this example, the `clientCertificate` section allows you to enable client certificate management and specify a list of Kubernetes secrets (`tls-cert`) that store allowed client certificates.
updated

2024-10-10 09:07 UTC, sharadregoti requested changes

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
> +You can make use of Tyk Operator custom resources to configure Tyk OAS API in a Kubernetes environment, starting with a [Tyk OAS API Definition]({{<ref "getting-started/using-oas-definitions/oas-glos
```suggestion
You can make use of Tyk Operator custom resources to configure [Tyk OAS API]({{<ref "getting-started/using-oas-definitions/oas-glossary#tyk-oas-api-definition">}}) in a Kubernetes environment.
```

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +## 2.1.0 Release Notes
@caroltyk This RN does not follow the style guide that we follow others. Can you please refer the latest Gateway RN?

All headings (`breaking changes, highlights`) should follow under the release tag. 

![image](https://github.com/user-attachments/assets/27072f57-721b-49ad-8bc2-3a91333877ab)
![image](https://github.com/user-attachments/assets/d2353986-f02d-4937-8cf2-60e0b72292a5)

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +#### Release Highlights
This should come after the release date. Refer Gateway RN

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +#### Downloads
This should come at the end. Refer Gateway RN

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +<summary>Update default Tyk versions</summary>
```suggestion
<summary>Updated default versions of Tyk components</summary>
```

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +Added optional `loadBalancerIP` parameter that allows users to set a static IP for Tyk Gateway and Dashboard services when using the `LoadBalancer` service type. This update provides enhanced control
```suggestion
Added an optional `loadBalancerIP` parameter in the chart that allows users to set a static IP for Tyk Gateway and Dashboard services when using the `LoadBalancer` service type. This update provides enhanced control over IP configuration, useful for network stability in environments with multiple load balancers.
```

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +helm upgrade [RELEASE_NAME] tyk-helm/[CHART_NAME]
@caroltyk  I think we can replace `[CHART_NAME]` with the actual chart name here.

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +- Tyk Operator v1.0.0
I think this needs to be rephrased to a more generic statement.

Refer @letzya comment: https://github.com/TykTechnologies/tyk-docs/pull/5318#discussion_r1793899657

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +<summary>Operator: license key configuration</summary>
```suggestion
<summary>From v1.0 Tyk Operator Requires License Key</summary>
```

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +<summary>Dashboard: container port configuration</summary>
```suggestion
<summary>Ability to configure Dashboard container port</summary>
```

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +<summary>Gateway and Dashboard: new LoadBalancer IP service parameters</summary>
```suggestion
<summary>Ability to specify static IP for Kubernetes LoadBalancer service</summary>
```

2024-10-10 09:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +**_Tyk Dashboard and Developer Portal Admin_**
@caroltyk  There are multiple similar changes in this file. Was this the result of a search & replace operation or code - formmater?

2024-10-10 09:54 UTC, letzya commented on tyk-docs/content/tyk-oss/ce-kubernetes-ingress.md
Which file should it be redirected to instead? (so if google has it in its results, where do you want users to go? )

2024-10-10 10:01 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
> +A [Security Policy]({{<ref "basic-config-and-security/security/security-policies">}}) in Tyk defines the rules and limitations that control how an API can be accessed, protecting it from abuse and mi
```suggestion
A [Security Policy]({{<ref "basic-config-and-security/security/security-policies">}}) in Tyk defines the rules that control how an API can be accessed, protecting it from abuse. These rules include rate limits, quotas, throttling, and access restrictions. Using Tyk Operator, you can configure and manage security policies in a Kubernetes environment by defining them in custom resource definitions (CRDs). This guide will walk you through the process of creating a security policy that protect access to your APIs with rate limits and quota using Tyk Operator.
```

2024-10-10 10:14 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +**_Tyk Dashboard and Developer Portal Admin_**
I don't know, I didn't make that change.

2024-10-10 10:20 UTC, carolwkc commented on tyk-docs/content/tyk-oss/ce-kubernetes-ingress.md
/product-stack/tyk-operator/tyk-ingress-controller/

2024-10-10 10:24 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +## 2.1.0 Release Notes
This is based on the template at /assets/others/release-notes-template.md :(

2024-10-10 10:30 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
> +- Tyk Operator v1.0.0
updated

2024-10-10 11:41 UTC, sharadregoti commented on tyk-docs/content/tyk-oss/ce-kubernetes-ingress.md
Updated.

2024-10-10 11:46 UTC, sharadregoti approved these changes

2024-10-10 11:51 UTC, letzya approved these changes

2024-10-10 12:02 UTC, letzya approved these changes

2024-10-10 12:03 UTC, merged