[DX-1691] Gateway Release Notes 5.3.6
TykTechnologies/tyk-docs-hugo pull request #5478
Opened 2024-09-30 11:36 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1691](https://tyktech.atlassian.net/browse/DX-1691)

---

### Preview Link

<br>

### Description

Gateway release notes for 5.3.6 

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-10-01 14:03 UTC, sharadregoti requested changes

2024-10-01 14:03 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Upgrade to Go 1.22 for Tyk Dashboard</summary>
```suggestion
<summary>Upgrade to Go 1.22 for Tyk Gateway</summary>
```

2024-10-01 14:03 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Fix for Response Plugins Not Working with Tyk OAS API Definition</summary>
```suggestion
<summary>Fix: Response Plugins Not Working with Tyk OAS API Definition</summary>
```

2024-10-01 14:03 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +</li>
I think this can be removed, as it is similar to the last point of performance improvement

2024-10-01 14:03 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This release fixes some issues related to the way that Tyk performs URL path matching, introducing two new Gateway configuration options to control path matching strictness. For a comprehensive list
The release highlight does not match with changelog detailed below, Please rephrase it ( It seems it is copied from previous release)

2024-10-01 14:04 UTC, sharadregoti commented
@andyo-tyk Can you verify the compatibility matrix & the release highlights?

2024-10-02 09:08 UTC, caroltyk approved these changes
verified compatibility matrix and dependency

2024-10-03 07:37 UTC, sharadregoti commented
@JoanCamosTyk @Eopayemi Can you incorporate the suggestions?

2024-10-03 09:03 UTC, andyo-tyk requested changes

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Fix for Response Plugins Not Working with Tyk OAS API Definition</summary>
```suggestion
<summary>Custom Response Plugins not working for Tyk OAS APIs</summary>
```

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +We have resolved an issue where Response Plugins were not being triggered for Tyk OAS API definitions. This fix ensures that Response Plugins now function correctly, allowing for consistent response
```suggestion
We have resolved an issue where custom [response plugins]({{< ref "plugins/plugin-types/response-plugins" >}}) were not being triggered for Tyk OAS APIs. This fix ensures that all [supported]({{< ref "getting-started/using-oas-definitions/oas-reference" >}}) custom plugins are invoked as expected when using Tyk OAS APIs.
```

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Fix for Response Plugins Not Working with Tyk OAS API Definition</summary>
This is in the "Fixed" section - we don't need to preface the summary with "Fix"

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +</li>
Yes, this is a duplicate

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Fix: Quota Limit Respected During Spike Tests</summary>
```suggestion
<summary>Quota wasn't respected under extreme load</summary>
```

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +We have fixed an issue where the quota limit was not being consistently respected during spike tests, especially in deployments with multiple gateways. The problem occurred when multiple gateways cac
```suggestion
We have fixed an issue where the quota limit was not being consistently respected during request spikes, especially in deployments with multiple gateways. The problem occurred when multiple gateways cached the current and remaining quota counters at the end of quota periods. To address this, a distributed lock mechanism has been implemented, ensuring coordinated quota resets and preventing discrepancies across gateways.
```

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Enhancement: Improved Gateway Synchronization with MDCB for Policies and APIs</summary>
```suggestion
<summary>Data plane gateways sometimes didn't synchronise policies and APIs on start-up</summary>
```

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +We have enhanced the Tyk Gateway's synchronization with MDCB to ensure more reliable loading of policies and APIs. A synchronous initialization process has been implemented to prevent startup failure
```suggestion
We have enhanced the initial synchronization of Data Plane gateways with the Control Plane to ensure more reliable loading of policies and APIs on start-up. A synchronous initialization process has been implemented to avoid sync failures and reduce the risk of service disruptions caused by asynchronous operations. This update ensures smoother and more consistent syncing of policies and APIs in distributed deployments.
```

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +We have addressed a performance regression in gateway versions 4.0.13 and later, where key creation for policies with a large number of APIs (100+) became significantly slower. The operation, which p
```suggestion
We have addressed a performance regression identified in Tyk Gateway versions 4.0.13 and later, where key creation for policies with a large number of APIs (100+) became significantly slower. The operation, which previously took around 1.5 seconds in versions 4.0.0 to 4.0.12, was taking over 20 seconds in versions 4.0.13 and beyond. This issue has been resolved by optimizing Redis operations during key creation, restoring the process to its expected speed of approximately 1.5 seconds, even with a large number of APIs in the policy.
```

2024-10-03 09:03 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This release fixes some issues related to the way that Tyk performs URL path matching, introducing two new Gateway configuration options to control path matching strictness. For a comprehensive list
```suggestion
This release fixes a number of performance and reliability issues. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.3.6">}}).
```

2024-10-03 10:42 UTC, andyo-tyk requested changes

2024-10-03 10:42 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Response Plugins Not Working with Tyk OAS API Definition</summary>
```suggestion
<summary>Custom Response Plugins not working for Tyk OAS APIs</summary>
```

2024-10-03 10:42 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Quota Limit Respected During Spike Tests</summary>
```suggestion
<summary>Quota wasn't respected under extreme load</summary>
```

2024-10-03 10:42 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Improved Gateway Synchronization with MDCB for Policies and APIs</summary>
```suggestion
<summary>Data plane gateways sometimes didn't synchronise policies and APIs on start-up</summary>
```

2024-10-03 10:42 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +We have enhanced the Tyk Gateway's synchronization with MDCB to ensure more reliable loading of policies and APIs. A synchronous initialization process has been implemented to prevent startup failure
```suggestion
We have enhanced the initial synchronization of Data Plane gateways with the Control Plane to ensure more reliable loading of policies and APIs on start-up. A synchronous initialization process has been implemented to avoid sync failures and reduce the risk of service disruptions caused by failed loads. This update ensures smoother and more consistent syncing of policies and APIs in distributed deployments.
```

2024-10-03 10:47 UTC, andyo-tyk requested changes

2024-10-03 10:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +In this release, we've enhanced the security of the Tyk 5-LTS image by changing the build process to support distroless containers. This significant update addresses critical CVEs associated with Deb
```suggestion
In this release, we've enhanced the security of the Tyk Gateway image by changing the build process to support [distroless](https://github.com/GoogleContainerTools/distroless) containers. This significant update addresses critical CVEs associated with Debian, ensuring a more secure and minimal runtime environment. Distroless containers reduce the attack surface by eliminating unnecessary packages, which bolsters the security of your deployments.
```

2024-10-03 10:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Debian CVE Fix for 5.3-LTS: Introducing Distroless Containers for Tyk 5-LTS</summary>
```suggestion
<summary>Introducing Distroless Containers for Tyk Gateway (2024 LTS)</summary>
```

2024-10-03 10:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Debian CVE Fix for 5.3-LTS: Introducing Distroless Containers for Tyk 5-LTS</summary>
This section should be in the "changed" section

2024-10-03 10:47 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +There are no breaking changes in this release, however if moving from an version of Tyk older than 5.3.0 please read the explanation provided with [5.3.0 release]({{< ref "#TykOAS-v5.3.0">}}).
```suggestion
Docker images are now based on [distroless](https://github.com/GoogleContainerTools/distroless). No shell is shipped in the image.

If moving from an version of Tyk older than 5.3.0 please read the explanation provided with [5.3.0 release]({{< ref "#TykOAS-v5.3.0">}}).
```

2024-10-03 10:48 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Introducing Distroless Containers for Tyk Gateway (2024 LTS)</summary>
This section should be in "changes", not "fixed"

2024-10-03 10:50 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +| [Go](https://go.dev/dl/)                                     | 1.19 (GQL), 1.21 (GW)  | 1.19 (GQL), 1.21 (GW)  | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using G
```suggestion
| [Go](https://go.dev/dl/)                                     | 1.19 (GQL), 1.22 (GW)  | 1.19 (GQL), 1.22 (GW)  | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go 1.22 |
```

2024-10-03 11:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Introducing Distroless Containers for Tyk Gateway (2024 LTS)</summary>
Done

2024-10-03 11:08 UTC, sharadregoti approved these changes

2024-10-03 11:13 UTC, andyo-tyk approved these changes
Thanks - approved

2024-10-03 13:44 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +| [Go](https://go.dev/dl/)                                     | 1.19 (GQL), 1.22 (GW)  | 1.19 (GQL), 1.22 (GW)  | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using G
```suggestion
| [Go](https://go.dev/dl/)                                     | 1.22  | 1.22  | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go 1.22 |
```

GQL team confirms the same Go version is used for GQL engine as for the rest of the Gateway.

2024-10-04 09:33 UTC, merged

2024-10-04 09:34 UTC, sharadregoti commented
/release to release-5.5

2024-10-04 09:35 UTC, sharadregoti commented
/release to release-5.3