[DX-1691] Dashboard Release Notes 5.3.6
TykTechnologies/tyk-docs-hugo pull request #5479
Opened 2024-09-30 11:49 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1691](https://tyktech.atlassian.net/browse/DX-1691)

---

### Preview Link

<br>

### Description

Dashboard release notes for 5.3.6

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-10-02 09:07 UTC, caroltyk requested changes

2024-10-02 09:07 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +|         | Helm Chart (tyk-stack, tyk-oss, tyk-dashboard, tyk-gateway) v1.4.0 | Helm all versions |
```suggestion
|         | Helm Chart (tyk-stack, tyk-oss, tyk-dashboard, tyk-gateway) v2.0.0 | Helm all versions |
```

2024-10-02 09:07 UTC, caroltyk approved these changes

2024-10-03 09:01 UTC, sharadregoti requested changes

2024-10-03 09:01 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +If you are using 5.3.0 we advise you to upgrade ASAP and if you are on an older version you should first [upgrade to 5.3.0](#upgrade-5.3.0) and then upgrade directly to this release. Go to the [Upgra
This does not comply with the release note style guide.

First, we should have `Release Highlights` section then breaking changes section

2024-10-03 09:01 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| [GoLang](https://go.dev/dl/)                               | 1.21       | 1.21       | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go 1.21 |
```suggestion
| [GoLang](https://go.dev/dl/)                               | 1.21       | 1.21       | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go 1.21 |
```

@andyo-tyk @caroltyk In the changelog we mentioned that we upgraded to go 1.22, Do we have to change this table as well?

2024-10-03 09:01 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +- [CVE-2024-6104](https://nvd.nist.gov/vuln/detail/CVE-2024-6104)
This link is not rendered in the preview.

![image](https://github.com/user-attachments/assets/588c8aa9-7ec9-4012-9866-ce7d15d4461e)

2024-10-03 09:16 UTC, sharadregoti requested changes

2024-10-03 09:16 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +### Dependencies {#dependencies-5.3.0}
```suggestion
### Dependencies {#dependencies-5.3.6}
```

2024-10-03 09:16 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +With PostgreSQL v11 reaching [EOL](https://www.postgresql.org/support/versioning/) in November 2023, we can no longer guarantee full compatibility with this version of the database. If you are [using
```suggestion
With MongoDB 4.4 reaching [EOL](https://www.mongodb.com/legal/support-policy/lifecycles) in February 2024, we can no longer guarantee full compatibility with this version of the database. If you are [using MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}) we recommend that you upgrade to a version that we have tested with, as indicated [below](#3rdPartyTools-v5.3.6).


With PostgreSQL v11 reaching [EOL](https://www.postgresql.org/support/versioning/) in November 2023, we can no longer guarantee full compatibility with this version of the database. If you are [using PostgreSQL]({{< ref "planning-for-production/database-settings/postgresql" >}}) we recommend that you upgrade to a version that we have tested with, as indicated [below](#3rdPartyTools-v5.3.6).
```

2024-10-03 09:29 UTC, sharadregoti requested changes

2024-10-03 09:29 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +We have fixed a privilege escalation vulnerability where a user with certain permissions could potentially reset other users' passwords, including admin accounts. The following changes have been made
```suggestion
We have fixed a privilege escalation vulnerability where a user with certain permissions could reset other users' passwords, including admin accounts. The following changes have been made to tighten the behavior of the ResetPassword permission within the Dashboard's Role-Based Access Control (RBAC) system:
```

2024-10-03 09:29 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +- The ResetPassword permission can only be assigned by super-admins, directly to admin users (not user groups).
Isn't this the same as the first one? We can remove this I guess. But I like this sentence over the 1st one.

2024-10-03 09:39 UTC, sharadregoti requested changes

2024-10-03 09:39 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Gateway Secret Exposed in Logs When Accessing /api/keys
```suggestion
<summary>Gateway Secret Exposed in Logs During Access to `/api/keys` Endpoint
```

2024-10-03 09:39 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +Resolved an issue where the Gateway secret was inadvertently logged by the Dashboard in debug mode. This issue has been fixed to prevent sensitive information from appearing in system logs, especiall
```suggestion
Resolved an issue where the Gateway secret was inadvertently logged by the Dashboard in debug mode. This issue has been fixed to prevent sensitive information from appearing in system logs.
```

2024-10-03 09:39 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Tyk Dashboard Keys Page No Longer Blank with 10+ Policies
```suggestion
<summary>Tyk Dashboard Keys Page Now Displays Correctly with More Than 10 Policies
```

2024-10-03 09:39 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +We have resolved an issue in the Tyk Dashboard where the Keys page would display a blank screen if a key was associated with more than 10 policies. The UI has been fixed to properly display the page,
```suggestion
We have resolved an issue in the Tyk Dashboard where the Keys page would display a blank screen if a key was associated with more than 10 policies. The UI has been fixed to properly display the page, regardless of the number of policies attached to a key.
```

2024-10-03 09:39 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +We have fixed an issue in the Dashboard UI where users were able to attach multiple versions of the same Tyk Classic API to a policy. The UI now correctly prevents the addition of duplicate API versi
```suggestion
We have fixed an issue in the Dashboard UI where users were able to attach multiple versions of the same Tyk Classic API to a policy. The UI now correctly prevents the addition of duplicate API versions to a single policy.
```

2024-10-03 11:14 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| [GoLang](https://go.dev/dl/)                               | 1.21       | 1.21       | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go 1.21 |
Yes

2024-10-03 13:23 UTC, andyo-tyk approved these changes

2024-10-03 13:23 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +If you are using 5.3.0 we advise you to upgrade ASAP and if you are on an older version you should first [upgrade to 5.3.0](#upgrade-5.3.0) and then upgrade directly to this release. Go to the [Upgra
Agreed - please would you move the Release Highlights to the top?

2024-10-03 13:23 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + - [tyk-charts v1.4]({{< ref "product-stack/tyk-charts/release-notes/version-1.4.md" >}})
@caroltyk should this be 2.0?

2024-10-03 13:23 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +If you are using 5.3.0 we advise you to upgrade ASAP and if you are on an older version you should first [upgrade to 5.3.0](#upgrade-5.3.0) and then upgrade directly to this release. Go to the [Upgra
I've done this.

2024-10-04 08:26 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + - [tyk-charts v1.4]({{< ref "product-stack/tyk-charts/release-notes/version-1.4.md" >}})
```suggestion
 - [tyk-charts v2.0]({{< ref "product-stack/tyk-charts/release-notes/version-2.0.md" >}})
```

2024-10-04 08:28 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + - [tyk-charts v1.4]({{< ref "product-stack/tyk-charts/release-notes/version-1.4.md" >}})
yes, the download link should follow previous minor version which has updated to 2.0 already.

2024-10-04 09:00 UTC, sharadregoti approved these changes

2024-10-04 09:39 UTC, merged

2024-10-04 09:39 UTC, sharadregoti commented
/release to release-5.5

2024-10-04 09:40 UTC, sharadregoti commented
/release to release-5.3