Push UI updates
TykTechnologies/tyk-docs-hugo pull request #5488
Opened 2024-09-30 21:01 UTC by DavidRollins

### For internal users - Please add a Jira DX PR ticket to the subject!

---

### Preview Link

### Description
1. Describe your changes in detail. Why is this change required? What problem does it solve?
     2. Please explain the change to the reviewer. Pay special attention to changes that are hard to spot, 
       for example:
       2.1. Updating menu.yaml file to new IA structure, should not lose any content from master.
       2.2. Updating html, css, and js objects to fix mobile platform and UI for new IA.
     3. @mentions of the person to review the proposed changes. They need to be able to know the topic well in order to approve it.

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-10-03 12:28 UTC, sharadregoti requested changes

2024-10-03 12:28 UTC, sharadregoti commented on tyk-docs/static/js/docs-navigation.js
> +				window.open("https://github.com/TykTechnologies/tyk-docs/tree/master/tyk-docsdocumentation.md", "_blank");
```suggestion
				window.open("https://github.com/TykTechnologies/tyk-docs/tree/master/tyk-docs/documentation.md", "_blank");
```

2024-10-07 06:25 UTC, Keithwachira commented
@DavidRollins . One ui issue.The left navigation is too squeezed (the width seems too small)

![image](https://github.com/user-attachments/assets/4839b588-dfe1-480a-906b-e7905fdebaef)

2024-10-08 16:55 UTC, buger commented on tyk-docs/static/css/docs.css
> +toc-label {
Was the goal to just disable those styles, by removing the dot?

2024-10-08 16:56 UTC, buger commented on tyk-docs/static/css/docs.css
> +toc-label {
Was the goal to just disable those styles, by removing the dot?

2024-10-15 12:08 UTC, letzya commented on tyk-docs/static/css/docs.css
> +  padding-left: 20px;
i think we've done that

2024-10-29 18:12 UTC, letzya commented
@DavidRollins closing it so it's not in our queue, thanks

2024-10-29 18:12 UTC, closed without merging