[DX-1697] Gateway Release Notes 5.5.2
TykTechnologies/tyk-docs-hugo pull request #5496
Opened 2024-10-01 14:36 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1697](https://tyktech.atlassian.net/browse/DX-1697)

---

### Preview Link

<br>

### Description

Gateway release notes 5.5.2

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-10-02 14:48 UTC, andyo-tyk requested changes

2024-10-02 14:48 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +This release fixes some issues identified in 5.5.1 which have now been effected in this release.
```suggestion
This release addresses [CVE-2023-45853](https://nvd.nist.gov/vuln/detail/CVE-2023-45853) which was accidentally reintroduced in 5.5.1 due to an incorrectly included library. The dependency has been corrected and the CVE removed.
```

2024-10-03 07:23 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +This release fixes some issues identified in 5.5.1 which have now been effected in this release.
@andyo-tyk Let's remove the anchor tag, seems irrelevant to me. 

FYI, the way you have referenced anchor tag (`#breaking-changes-1)` is not a good practice, because in future if we release `5.5.3` this anchor tag will refer to the breaking changes of that release. I suggest adding explicit anchor id if required `(### Breaking Changes {#breaking-changes-5.5.2})`

2024-10-03 07:24 UTC, sharadregoti commented
LGTM, need to merge after 5.5.2 release & date has to be changed.

2024-10-03 07:24 UTC, sharadregoti approved these changes

2024-10-03 09:07 UTC, andyo-tyk approved these changes

2024-10-03 13:14 UTC, merged

2024-10-03 13:14 UTC, sharadregoti commented
/release to release-5.5

2024-10-03 13:21 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
> +This release fixes some issues identified in 5.5.1 which have now been effected in this release.
I only did that because I wanted to have the link, but there wasn't an anchor id on that line and I wasn't sure how to add one, given that it wasn't part of the PR that I was reviewing....