[DX-1697] Dashboard Release Notes 5.5.2
TykTechnologies/tyk-docs-hugo pull request #5497
Opened 2024-10-01 15:22 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1697](https://tyktech.atlassian.net/browse/DX-1697)

---

### Preview Link

<br>

### Description

Dashboard release notes for 5.5.2

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-10-02 14:48 UTC, andyo-tyk requested changes

2024-10-02 14:48 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
> +This is a version bump to align with Gateway v5.5.2, no changes have been implemented in this release.
```suggestion
This release addresses [CVE-2023-45853](https://nvd.nist.gov/vuln/detail/CVE-2023-45853) which was accidentally reintroduced in 5.5.1 due to an incorrectly included library. The dependency has been corrected and the CVE removed.
```

2024-10-03 07:10 UTC, sharadregoti approved these changes
LGTM, need to merge after 5.5.2 release

2024-10-03 09:06 UTC, andyo-tyk approved these changes

2024-10-03 13:10 UTC, merged

2024-10-03 13:10 UTC, sharadregoti commented
/release to release-5.5