[TT-13088] Update documentation for master
TykTechnologies/tyk-docs-hugo pull request #5531
Opened 2024-10-08 10:24 UTC by buger

Triggered by: lghiur

Included:

Tyk Gateway: true
Tyk Dashboard: true
Tyk MDCB false
Tyk Pump false

Intended for: master
Changes sourced from: release-5.6.0
Config info generator branch: main

Note: Update 5.6.0 docs (branch suffix: docs)

JIRA: https://tyktech.atlassian.net/browse/TT-13088

2024-10-09 08:07 UTC, sharadregoti requested changes

2024-10-09 08:07 UTC, sharadregoti commented on tyk-docs/content/shared/gateway-config.md
> +Combining EnablePathSuffixMatching with EnablePathPrefixMatching will result in exact URL matching, with `/json` being evaluated as `^/json$`.
@lghiur This has to be fixed.

2024-10-10 11:50 UTC, sharadregoti approved these changes

2024-10-10 12:46 UTC, lghiur approved these changes

2024-10-10 12:51 UTC, merged