Create two-gateways-with-docker-compose.md
TykTechnologies/tyk-docs-hugo pull request #554
Opened 2018-09-17 19:05 UTC by letzya

Per clients request.
Fix #553

2018-10-29 17:46 UTC, buger commented
Note that we do not mention docker pro demo anywhere in docs, except this one :)

Don't you think better to place this docs to README of docker pro demo repo?

2018-10-29 17:47 UTC, asoorm requested changes

2018-10-29 17:47 UTC, asoorm commented on tyk-docs/content/frequently-asked-questions/two-gateways-with-docker-compose.md
> +     - tyk-gateway
Why does pump depend on gateway? Pump doesn't connect to the gateway

2018-10-29 17:47 UTC, asoorm commented on tyk-docs/content/frequently-asked-questions/two-gateways-with-docker-compose.md
> +2. Add the following to docker-compose.yml (after _tyk-gateway2_ definition):
after `tyk-gateway` definition. Not `tyk-gateway2` definition.

Also, I would prefer using backticks `` ` `` rather than underscore `_`. markdown parser will know to put the backticked content inside code block.

2018-10-29 18:54 UTC, buger commented on tyk-docs/content/frequently-asked-questions/two-gateways-with-docker-compose.md
> +     - tyk-gateway
I think it was just taken from our existing docker compose files. But in general yes, this link does not makes much sense, however it does not make much harm as well too :)

2018-10-29 20:19 UTC, letzya commented
> Note that we do not mention docker pro demo anywhere in docs, except this one :)
> 
> Don't you think better to place this docs to README of docker pro demo repo?

I just think it'll have less visability. When it's in the docs people can search for it.

2018-10-29 20:20 UTC, letzya commented
@asoorm done

2018-10-30 09:28 UTC, marksou commented
@asoorm Are you happy with the changes now?

2018-10-30 09:36 UTC, asoorm commented on tyk-docs/content/frequently-asked-questions/two-gateways-with-docker-compose.md
> +All you need to do is add a few lines to docker-compose.yml and docker-compose.yml and `up` your docker-compose as usual.
I would just tweak the wording of this, plus you have used `docker-compose.yml` twice instead of mentioning `docker-local.yml`:

> Managing a second Tyk Gateway with our [tyk-pro-docker-demo](https://github.com/TykTechnologies/tyk-pro-docker-demo) is a case of mounting the config file into a new volume and declaring a new gateway service but exposed on a different port.
> You will need to make some minor modifications to `docker-compose.yml` and `docker-local.yml` and start your services as usual `docker-compose up -f docker-compose.yml -f docker-local.yml up`.

2018-10-30 09:44 UTC, marksou commented
@asoorm Made those changes.

2018-10-30 09:55 UTC, asoorm approved these changes

2018-10-30 10:02 UTC, merged