[DX-1709] Updated Change log Dashboard 5.6.0
TykTechnologies/tyk-docs-hugo pull request #5563
Opened 2024-10-11 10:21 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1709](https://tyktech.atlassian.net/browse/DX-1709)

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-10-11 10:26 UTC, sharadregoti approved these changes

2024-10-11 10:27 UTC, andyo-tyk requested changes

2024-10-11 10:27 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +<summary>Gateway Logs Page Not Displaying Correctly</summary>
```suggestion
<summary>Gateway logs page not displaying correctly</summary>
```

2024-10-11 10:27 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We have fixed an issue in the Dashboard UI where the Gateway Logs page was not displaying correctly. The page is now rendered properly, ensuring users can view and manage Gateway logs as expected.
```suggestion
We have fixed an issue in the Monitoring section of the Dashboard UI where the *Gateway logs* page was not displaying correctly. The page is now rendered properly, ensuring users with appropriate permissions can view and manage *Gateway logs* as expected.
```

2024-10-14 08:36 UTC, andyo-tyk approved these changes
Thanks

2024-10-14 08:46 UTC, merged

2024-10-14 08:47 UTC, sharadregoti commented
/release to release-5.6