[TT-13263/TT-13264] Add plugin development docs update
TykTechnologies/tyk-docs-hugo pull request #5565
Opened 2024-10-11 12:12 UTC by titpetric

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

Updates local development docs for the latest releases, documenting go workspaces.

Task: https://tyktech.atlassian.net/browse/TT-13263
Parent: https://tyktech.atlassian.net/browse/TT-13264

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-10-14 13:05 UTC, letzya commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +---
In general, we need to add new files to menu.yaml.
In this case, why not add the content in this to the bottom of the other file?

2024-10-21 06:18 UTC, sharadregoti requested changes

2024-10-21 06:18 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> -Go plugins must be compiled before they can be run. This applies to custom code that you want Tyk to run during the processing of API requests and responses in [custom plugins]({{< ref "plugins" >}})
@titpetric regarding the steps shown in this page, is it for all versions of gateway or only for version `tyk-release-5.3.6`?

Because the live version of this doc has different initialization method for each version. Especially versions #[prior to 4.2](https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow/#initialise-plugin-for-tyk-gateway-versions-prior-to-v42)

2024-10-21 10:33 UTC, letzya commented
@titpetric The missing bit for me is when do I use this vs when to use the compiler

2024-10-22 09:12 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> -Go plugins must be compiled before they can be run. This applies to custom code that you want Tyk to run during the processing of API requests and responses in [custom plugins]({{< ref "plugins" >}})
It's valid for the latest 5.3 LTS; previous versions would remain documented on their respective release branches. 5.3.6 is likely the minimum, due to the Go version bump, but this should apply to 5.3.7 and future 5.3 releases.

2024-10-25 08:09 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +## Setting up your environment
Note supported architectures/OS for the environment, native go plugins have limited env support

2024-10-25 08:12 UTC, titpetric commented
> @titpetric The missing bit for me is when do I use this vs when to use the [compiler](https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-compiler/)

Does the "plugin compiler" section answer some of those questions? Cross compilation, matching to an official release tag? I could reword it to make those details clearer.

2024-10-25 10:57 UTC, andyo-tyk requested changes

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +For effectively developing go plugins, familiarize yourself with the following:
```suggestion
We recommend that you familiarize yourself with the following official Go documentation to help you work effectively with Go plugins:
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +Plugins need to be compiled to native shared object code, which are then loaded by Gateway. For best results, knowing the restrictions of plugins is recommended. For maximum compatibility, Go workspa
```suggestion
Plugins need to be compiled to native shared object code, which can then be loaded by Tyk Gateway. For best results it's important to understand the need for plugins to be compiled using exactly the same environment and [build flags]({{< ref "product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow#build-flag-restrictions" >}}) as the Gateway. To simplify this and minimise the risk of compatibility problems, we strongly recommend the use of  [Go workspaces]({{< ref "https://go.dev/blog/get-familiar-with-workspaces" >}}), to provide a consistent environment.
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +- Go based on the gateway version (from go.mod)
```suggestion
- Go (matching the version used in the Gateway, which you can determine using `go.mod`)
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +- Git to check out gateway source code
```suggestion
- Git to check out Tyk Gateway source code
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +- A folder with plugins to build
```suggestion
- A folder with the code that you want to build into plugins
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +Set up a workspace, which, at the end, is going to look like:
```suggestion
We recommend that you set up a *Go workspace*, which, at the end, is going to contain:
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +- `/tyk-release-5.3.6` - the checkout
```suggestion
- `/tyk-release-x.y.z` - the Tyk Gateway source code
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +- `/go.work` - the go workspace file
```suggestion
- `/go.work` - the *Go workspace* file
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +- `/go.work.sum` - workspace package checksums
```suggestion
- `/go.work.sum` - *Go workspace* package checksums
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +Using the workspace ensures build compatibility, matching plugin restrictions.
```suggestion
Using the *Go workspace* ensures build compatibility, matching plugin restrictions.
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +### 1. Checking out tyk
```suggestion
### 1. Checking out Tyk Gateway source code
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +The example checkout uses a particular `release-5.3.6` branch, to match a release. With newer `git` version, you may pass `--branch v5.3.6` and it would use the tag. In case you want to use the tag i
```suggestion
This example uses a particular `release-5.3.6` branch, to match Tyk Gateway release 5.3.6. With newer `git` versions, you may pass `--branch v5.3.6` and it would use the tag. In case you want to use the tag it's also possible to navigate into the folder and issue `git checkout tags/v5.3.6`.
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +### 2. Preparing the workspace - plugins
```suggestion
### 2. Preparing the Go workspace
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +The plugin workspace can be very simple. Generally you would:
```suggestion
Your Go workspace can be very simple.

Generally you would:
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +1. create a .go file with code for your plugin
```suggestion
1. create a `.go` file containing the code for your plugin
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +2. create a go.mod for the plugin
```suggestion
2. create a `go.mod` file for the plugin
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +3. ensure the correct go version is in use
```suggestion
3. ensure the correct Go version is in use
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +4. add gateway dependency with `go get`, using the commit hash
```suggestion
4. add a Tyk Gteway dependency with `go get`, using the commit hash
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +For implementation examples, see [CustomGoPlugin.go](https://github.com/TykTechnologies/custom-go-plugin/blob/master/go/src/CustomGoPlugin.go). We'll be using this as the source for our plugin as sho
```suggestion
As an example, we can use the [CustomGoPlugin.go](https://github.com/TykTechnologies/custom-go-plugin/blob/master/go/src/CustomGoPlugin.go) sample as the source for our plugin as shown:
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +2. set go.mod go version to what's set in gateway,
```suggestion
2. set the Go version of `go.mod` to match the one set in the Gateway,
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +1. create a plugin, create go.mod,
What do you mean by "create a plugin"? Do you mean "create a folder called `plugins`" or do you mean "create a file containing the plugin code" (which also seems to be step 3)... or something else?

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +At this point, we don't have a workspace yet. In order to share the gateway dependency across go modules we'll create a Go workspace next.
```suggestion
At this point, we don't have a *Go workspace* but we will create one next so that we can effectively share the Gateway dependency across Go modules.
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +From the folder that contains the gateway checkout and the plugins folder, do:
```suggestion
From the folder that contains the Gateway checkout and the plugins folder, you will update `go.mod` with the Gateway commit hash that corresponds to the checkout and then run `go mod tidy`, creating the `go.work` workspace file.

Follow these commands:
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +These are the final steps on how to create the workspace. The last step is used to update go.mod with the gateway commit corresponding to the checkout. After this step you're able to use `go mod tidy
```suggestion
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +With this step, the `go.work` file is created. It should look like this:
```suggestion
The Go workspace file (`go.work`) should look like this:
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +### 4. Testing out the plugin
```suggestion
### 4. Building and validating the plugin
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +To test out the gateway/plugin build, you can now to the following:
```suggestion
Now that your *Go workspace* is ready, you can build your plugin as follows:
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +The above few steps build gateway, and the plugin. To test plugin loading:
```suggestion
These steps build both the Gateway and the plugin.

You can use the Gateway binary that you just built to test that your new plugin loads into the Gateway without having to configure and then make a request to an API using this command:
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +The command should output something similar to:
```suggestion
You should see an output similar to:
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +We can use the built gateway binary to test plugin loading without invoking the plugin symbol like a request would. However, as demonstrated, the plugins `init` function is invoked, printing to the l
```suggestion
The log shows that the plugin has correctly loaded into the Gateway and that its `init` function has been successfully invoked.
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +We've put together an end-to-end build environment for both the gateway and the plugin. However, runtime environments have additional restrictions which the plugin developer must pay attention to.
```suggestion
In the preceding steps we have put together an end-to-end build environment for both the Gateway and the plugin. Bear in mind that runtime environments have additional restrictions to which the plugin developer must pay attention.
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +Compatibility in general is a big concern around plugins; since the plugins are tightly coupled to gateway, they need to be built with some consideration to the restrictions around them.
```suggestion
Compatibility in general is a big concern when working with Go plugins: as the plugins are tightly coupled to the Gateway, they must be built with consideration to the restrictions around them.
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +We provide a plugin build environment to manage compatibility restrictions for plugins. The plugin compiler ensures compatibility between the system architecture and the go version for your target en
```suggestion
We provide a plugin build environment to manage compatibility restrictions for plugins. The plugin compiler ensures compatibility between the system architecture and the Go version for your target environment.
```

2024-10-25 10:57 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +It's a requirement that build flags for gateway match build flags for the plugin. One such flag that need to be included in builds is `-trimpath`:
```suggestion
It's a requirement that build flags for plugins match the build flags for the Gateway. One such flag that must be included in builds is `-trimpath`:
```

2024-10-25 11:07 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +Using the *Go workspace* ensures build compatibility, matching plugin restrictions.
```suggestion
Using the *Go workspace* ensures build compatibility between the plugins and Gateway.
```

2024-10-25 11:07 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +In the preceding steps we have put together an end-to-end build environment for both the Gateway and the plugin. Bear in mind that runtime environments have additional restrictions to which the plugi
```suggestion
In the preceding steps we have put together an end-to-end build environment for both the Gateway and the plugin. Bear in mind that runtime environments may have additional restrictions beyond Go version and build flags to which the plugin developer must pay attention.
```

2024-10-25 11:07 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +Compatibility in general is a big concern when working with Go plugins: as the plugins are tightly coupled to the Gateway, they must be built with consideration to the restrictions around them.
```suggestion
Compatibility in general is a big concern when working with Go plugins: as the plugins are tightly coupled to the Gateway, consideration must always be made for the build restrictions enforced by environment and configuration options.
```

2024-10-25 11:07 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +### Build flag restrictions
```suggestion
### Build flags
```

2024-10-25 11:07 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +Plugins need to be compiled to native shared object code, which can then be loaded by Tyk Gateway. For best results it's important to understand the need for plugins to be compiled using exactly the
```suggestion
Plugins need to be compiled to native shared object code, which can then be loaded by Tyk Gateway. For best results it's important to understand the need for plugins to be compiled using exactly the same environment and [build flags]({{< ref "product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow#build-flags" >}}) as the Gateway. To simplify this and minimise the risk of compatibility problems, we strongly recommend the use of  [Go workspaces]({{< ref "https://go.dev/blog/get-familiar-with-workspaces" >}}), to provide a consistent environment.
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +Plugins are native go code compiled to a binary shared object file. The code may depend on CGO and require libraries like libc provided by the runtime environment. The following are some debugging st
```suggestion
Plugins are native Go code compiled to a binary shared object file. The code may depend on `cgo` and require libraries like `libc` provided by the runtime environment. The following are some debugging steps for diagnosing issues arising from using plugins.
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +The [plugin package - Warnings](https://pkg.go.dev/plugin#hdr-Warnings) section outlines several requirements which can't be ignored. The most important restriction is the following:
```suggestion
The [Plugin package - Warnings](https://pkg.go.dev/plugin#hdr-Warnings) section in the Go documentation outlines several requirements which can't be ignored when working with plugins. The most important restriction is the following:
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +We provide a Plugin Compiler docker image, which should be used to build plugins compatible with the official gateway releases and their architectures. It provides the cross compilation toolchain, Go
```suggestion
We provide the *Tyk Plugin Compiler* docker image, which we strongly recommend is used to build plugins compatible with the official Gateway releases. This tool provides the cross compilation toolchain, Go version used to build the release, and ensures that compatible flags are used when compiling plugins, like `-trimpath`, `CC`, `CGO_ENABLED`, `GOOS`, `GOARCH`.
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +The plugin compiler also works around known Go issues.
```suggestion
The *Plugin Compiler* also works around known Go issues such as:
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +The argument plugin_id ensures the same plugin can be rebuilt. The plugin compiler does this by replacing the plugin go.mod module path.
```suggestion
Supplying the argument `plugin_id` to the *Plugin Compiler* ensures the same plugin can be rebuilt. The *Plugin Compiler* does this by replacing the plugin `go.mod` module path.
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +Continue with [Go Plugin Compiler](https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-compiler/).
```suggestion
Continue with [Tyk Plugin Compiler](https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-compiler/).
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +When working with Go plugins, it's easy to miss the restriction that the plugin at the very least requires to be built with the same Go version, and the same flags, notably `-trimpath`, which is part
```suggestion
When working with Go plugins, it's easy to miss the restriction that the plugin at the very least must be built with the same Go version, and the same flags (notably `-trimpath`) as the Tyk Gateway on which it is to be used.
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +If you miss an argument like forgetting `-trimpath` for the plugin build, you'll get a load error like the one below. Usually when the error hints at a standard library package, the build flags betwe
```suggestion
If you miss an argument (for example `-trimpath`) when building the plugin, the Gateway will report an error when your API attempts to load the plugin, for example:
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +
```suggestion
Usually when the error hints at a standard library package, the build flags between the Gateway and plugin binaries don't match.

```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +Other error messages may occur, depending on what triggered the issue. For example, if you omitted `-race` in the plugin but the gateway was built with `-race`, the error reported is:
```suggestion
Other error messages may be reported, depending on what triggered the issue. For example, if you omitted `-race` in the plugin but the gateway was built with `-race`, the following error will be reported:
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +Stricly speaking:
```suggestion
Strictly speaking:
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- go toolchain / build env needs to be exactly the same
```suggestion
- Go toolchain / build env needs to be exactly the same
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- matching `CGO_ENABLED=1`, `GOOS`, `GOARCH` with runtime
```suggestion
- `CGO_ENABLED=1`, `GOOS`, `GOARCH` must match with runtime
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- cross compilation means using the same `CC` value for the build (CGO)
```suggestion
- for cross compilation you must use the same `CC` value for the build (CGO)
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +When something is off, proofing these can be done with `go version -m tyk` and `go version -m plugin.so` for the plugin, inspecting and comparing the output of `build` tokens usually yields the diffe
```suggestion
When something is off, you can check what is different by using the `go version -m` command for the Gateway (`go version -m tyk`) and plugin (`go version -m plugin.so`). Inspecting and comparing the output of `build` tokens usually yields the difference that caused the compatibility issue.
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- A gateway dependency does not have a go.mod and plugin wants to use it,
```suggestion
- A Gateway dependency does not have a `go.mod` and the plugin wants to use it,
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- A gateway dependency has a shared dependency, same version must be used,
```suggestion
- Gateway and plugin have a shared dependency: the same version must be used by the plugin
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- Plugin uses gateway as a dependency and wants to use a shared dependency
```suggestion
- Plugin uses Gateway as a dependency and wants to use a shared dependency
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- Plugin uses gateway as a dependency but wants to use A
```suggestion
- Plugin uses Gateway as a dependency but wants to use *A*
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- A does not have a go.mod, so a pseudo version is generated on both ends of the build
```suggestion
- *A* does not have a `go.mod`, so a pseudo version is generated on both ends of the build
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +Fix: update to remove dependency A, or use a version with go.mod;
```suggestion
Fix: update to remove dependency *A*, or use a version with `go.mod`
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- As the dependency has go.mod, the version matches
```suggestion
- As the dependency has `go.mod`, the version matches
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- Dependency is promoted to direct in go.mod
```suggestion
- Dependency is promoted to *direct* in `go.mod`
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- Expect: user has to keep dependency in sync with gateway
```suggestion
- Expect: you have to keep the dependency in sync with Gateway
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +- Plugin uses gateway as a dependency but wants to use a different version of a dependency
```suggestion
- Plugin uses Gateway as a dependency but wants to use a different version of a shared dependency
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +It's definitely recommended that all dependencies would follow go package metaversion, however the reality is most gateway dependencies follow a basic v1 semver which doesn't break import paths for e
```suggestion
We recommend that all dependencies should follow Go package metaversion, however the reality is most Gateway dependencies follow a basic v1 semver which doesn't break import paths for every release.
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +The command prints other symbols that are part of the binary. In the worst case, a build compatibility issue may cause a crash in the gateway due to an unrecoverable error and this can be used to fur
```suggestion
This command prints other symbols that are part of the binary. In the worst case, a build compatibility issue may cause a crash in the Gateway due to an unrecoverable error and this can be used to further debug the binaries produced.
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +A very basic check to ensure gateway/plugin compatibility is using the built in `go version -m <file>`:
```suggestion
A very basic check to ensure Gateway/plugin compatibility is using the built in `go version -m <file>`:
```

2024-10-25 11:26 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +It's typical that these options should match between the gateway binary and the plugin, and you can use the command for both binaries.
```suggestion
These options should match between the Gateway binary and the plugin. You can use the command for both binaries and then compare the outputs.
```

2024-10-25 11:29 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +1. create a plugin, create go.mod,
```suggestion
1. create a plugin folder, create a go.mod for it,
```

2024-10-25 11:32 UTC, andyo-tyk approved these changes
Thanks, this looks great. A real positive addition to the docs.

2024-10-25 12:08 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +4. add a Tyk Gteway dependency with `go get`, using the commit hash
```suggestion
4. add a Tyk Gateway dependency with `go get`, using the commit hash
```

2024-10-25 12:08 UTC, jeffy-mathew commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +git clone --branch release-5.3.6 https://github.com/TykTechnologies/tyk.git tyk-release-5.3.6 || true
is it a must to have the directory named with version? eg. `tyk-release-5.3.6`?

2024-10-28 13:18 UTC, jeffy-mathew approved these changes

2024-10-29 11:10 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +git clone --branch release-5.3.6 https://github.com/TykTechnologies/tyk.git tyk-release-5.3.6 || true
the version prefix yes (as discussed) ; illustration purposes, migration purposes...

2024-10-29 13:33 UTC, sharadregoti requested changes

2024-10-29 13:33 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +Supplying the argument `plugin_id` to the *Plugin Compiler* ensures the same plugin can be rebuilt. The *Plugin Compiler* does this by replacing the plugin `go.mod` module path.
```suggestion
Supplying the argument `build_id` to the *Plugin Compiler* ensures the same plugin can be rebuilt. The *Plugin Compiler* does this by replacing the plugin `go.mod` module path.
```

The plugin compiler talks about [build_id](https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-compiler/#compiler-options), Is this a typo?

2024-10-29 13:33 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +This should be used to ensure the version matches between gateway and the plugin. The commit is used to `go get` the dependency in later steps.
> The commit is used to `go get` the dependency in later steps.

Can you elaborate on this, seem it requires a little context as previous command does have anything related to commit.

2024-10-29 13:33 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +
This is confusing, can you rephrase/elaborate on it? 

I think a table would be a much better option to represent this.

2024-10-29 16:10 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +
feel free to rework to table as long as the essence remains

2024-10-29 16:49 UTC, letzya commented
@sharadregoti can you please  move the new content to another one? (maybe bottom od this https://deploy-preview-5565--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/plugins/golang/writing-go-plugins/)

2024-10-30 12:18 UTC, andyo-tyk commented
> @sharadregoti can you please move the new content to another one? (maybe bottom od this https://deploy-preview-5565--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/plugins/golang/writing-go-plugins/)

That doesn't feel like the right place - the suggested location is guidance on how to *write* the plugin, not how to *build* it.

This new content is basically an elaboration on this content: https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow/

2024-10-30 15:59 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/debugging-go-plugins.md
> +
let's actually go with no

2024-10-30 16:00 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
> +This should be used to ensure the version matches between gateway and the plugin. The commit is used to `go get` the dependency in later steps.
editing issue, should be resolved

2024-10-31 08:17 UTC, sharadregoti commented
> > @sharadregoti can you please move the new content to another one? (maybe bottom od this https://deploy-preview-5565--tyk-docs.netlify.app/docs/nightly/product-stack/tyk-gateway/advanced-configurations/plugins/golang/writing-go-plugins/)
> 
> That doesn't feel like the right place - that suggested location is guidance on how to _write_ the plugin, not how to _build_ it.
> 
> The new content in this PR is basically an elaboration on this content: https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow/

The page highlighted by @letzya is the best option compared to other pages. I am moving ahead with this page.

Also, the plugins section will restructured again in the upcoming months

2024-10-31 08:44 UTC, sharadregoti approved these changes

2024-10-31 13:29 UTC, merged

2024-10-31 13:29 UTC, sharadregoti commented
/release to release-5.6