[TT-13186/TT-13275] document upstream basic authentication
TykTechnologies/tyk-docs-hugo pull request #5566
Opened 2024-10-11 13:48 UTC by jeffy-mathew

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-05 18:09 UTC, letzya requested changes
@jeffy-mathew @sharadregoti we are in a process of consolidating content. Is there another topic this can be part of? maybe upstream mTLS?

2024-11-06 08:36 UTC, sharadregoti requested changes

2024-11-06 08:36 UTC, sharadregoti commented on tyk-docs/content/basic-config-and-security/security/upstream-authentication/basic-authentication.md
> +`x-tyk-api-gateway.upstream.authentication.enabled` needs to be true to enable upstream authentication.
```suggestion
`x-tyk-api-gateway.upstream.authentication. basicAuth.enabled` needs to be true to enable upstream authentication.
```

> Inside your OAS API definition you should configure `x-tyk-api-gateway.upstream.authentication.basicAuth` field.
My understanding is that this field holds a JSON object with 4 values.

2024-11-06 08:36 UTC, sharadregoti commented on tyk-docs/content/basic-config-and-security/security/upstream-authentication/basic-authentication.md
> +- `headerName` is the header to be used.
```suggestion
- `headerName` is the header to be used. Defaults to `Authorization` if not specified.
```

2024-11-06 08:36 UTC, sharadregoti commented on tyk-docs/content/basic-config-and-security/security/upstream-authentication/basic-authentication.md
> +Inside your OAS API definition you should configure `x-tyk-api-gateway.upstream.authentication.basicAuth` field.
```suggestion
In your OAS API definition, configure the `x-tyk-api-gateway.upstream.authentication.basicAuth` field, which is an object containing the following properties:
```

2024-11-06 08:39 UTC, sharadregoti commented
> @jeffy-mathew @sharadregoti we are in a process of consolidating content. Is there another topic this can be part of? maybe upstream mTLS?

@letzya In our new IA, we can include a section on the Authentication & Authorization page to cover this new feature.

2024-11-06 10:38 UTC, andyo-tyk commented
> @jeffy-mathew @sharadregoti we are in a process of consolidating content. Is there another topic this can be part of? maybe upstream mTLS?



> > @jeffy-mathew @sharadregoti we are in a process of consolidating content. Is there another topic this can be part of? maybe upstream mTLS?
> 
> @letzya In our new IA, we can include a section on the Authentication & Authorization page to cover this new feature.

This should not be part of the Client>GW AuthN/AuthZ page.
This is GW>Upstream AuthN and we must mitigate the risk of confusion, so please allow a separate section for this.

2024-11-14 13:37 UTC, jeffy-mathew commented on tyk-docs/content/basic-config-and-security/security/upstream-authentication/basic-authentication.md
> +`x-tyk-api-gateway.upstream.authentication.enabled` needs to be true to enable upstream authentication.
This is a prerequisite, `x-tyk-api-gateway.upstream.authentication.basicAuth.enabled` is already mentioned. 
`x-tyk-api-gateway.upstream.authentication.enabled` decides if upstream authentication needs to be performed at all.

2024-11-18 06:13 UTC, sharadregoti commented
Marking it as draft. As @andyo-tyk will use this content to create a new PR.

2025-03-25 11:09 UTC, andyo-tyk commented
Closing this, as the feature has been documented in the Upstream Auth page.

2025-03-25 11:09 UTC, closed without merging