[DX-1720] Gateway release notes 5.7.0
TykTechnologies/tyk-docs-hugo pull request #5620
Opened 2024-10-17 12:07 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1720](https://tyktech.atlassian.net/browse/DX-1720)

---

### Preview Link

<br>

### Description

Gateway release notes 5.7.0

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-27 16:59 UTC, andyo-tyk requested changes
Added some suggestions - deprecations, wording, non-inclusion of one change.

Is Streams already in 5.6 or is this the first time it's been released? If the latter, then how can we include "improvement" or "simplification" of Streams in the change log? If it's a new feature, then THAT is the change, not each individual Jira ticket.

2024-11-27 16:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +Our minor releases are supported until our next minor comes out.
```suggestion
Minor releases are supported only until the next minor comes out.
```

2024-11-27 16:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +There are no deprecations in this release.
I think we should mention the EOL of support for sqlite and also deprecation of the two auth middleware!

2024-11-27 16:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +<summary>Support for Custom OAuth Server Response Fields</summary>
```suggestion
```

No, this is not for inclusion in the RN

2024-11-27 16:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +This update enables the Tyk API Gateway to handle custom data fields from non-standard OAuth 2.0 token responses, like Salesforce’s instance_url. Users can now specify which custom fields to extract
```suggestion
```

2024-11-27 16:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +<summary>Enhanced OAS Schema Flexibility</summary>
```suggestion
<summary>Improved backwards compatibility when working with Tyk OAS APIs</summary>
```

2024-11-27 16:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +Fixed a backwards compatibility issue with schema validation. When downgrading from a Tyk version, schema validation could fail as it didn't allow additional properties. This change relaxes schema st
```suggestion
Fixed a backwards compatibility issue with Tyk OAS API schema validation. When downgrading from a Tyk version, schema validation could fail if new fields had been added to the Tyk OAS API definition. This change relaxes the strictness of validation to allow additional properties.
```

2024-11-27 16:59 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +Fixed a regression that increased memory consumption when proxying large response payloads, even with enable_detailed_recording disabled. The Gateway now handles large payloads more efficiently in te
```suggestion
Fixed an issue that caused increased memory consumption when proxying large response payloads. The Gateway now handles large payloads more efficiently in terms of speed and memory usage.
```

2024-11-28 11:44 UTC, agata-wit requested changes

2024-11-28 11:44 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +#### Add release highlight summary
```suggestion
#### Tyk Streams - asynchronous API management with Tyk
```

2024-11-28 11:44 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +Add release highlight description
```suggestion
Tyk is now entering the asynchronous API management space with a bang by delivering Tyk Streams to our users!
Many API management solutions fail to fully support event-driven architectures, causing fragmented management, inconsistent security practices, and increased operational complexity. With event-driven architectures on the rise recently, keeping everything under control and enforcing standards at the organizational level has become a challenge.

**Tyk Streams** is an event streaming solution available within the Tyk API Management Platform, which applies proven API management principles to simplify event and streams handling. 
This release brings capabilities to stream data and events using Kafka, Websocket, SSE and HTTP protocols. It also becomes possible to mediate the message format between Avro and JSON on the fly.

- Merge together various sources of events to present to consumers as a unified stream.
- Apply authentication and authorization to streams of messages, just as you do for your RESTful APIs
- Expose async APIs via Tyk Portal, so that they are easily discoverable

All of this possible in self-managed and k8s deployments of Tyk!

```

2024-11-28 11:44 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +<summary>Enhanced Stream Analytics Error Handling</summary>
```suggestion
<summary>Added Stream Analytics Error Handling</summary>
```

2024-11-28 11:44 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +Expanded Streams analytics to capture and report common error scenarios, including broker connectivity issues and standard HTTP errors, ensuring comprehensive request tracking for Streams-processed r
```suggestion
Added to Streams analytics capability to capture and report common error scenarios, including broker connectivity issues and standard HTTP errors, ensuring comprehensive request tracking for Streams-processed requests.
```

2024-11-28 11:44 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +<summary>Improved Streams Analytics Integration</summary>
```suggestion

```

2024-11-28 11:44 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +Expanded Streams analytics to capture and report common error scenarios, including broker connectivity issues and standard HTTP errors, ensuring comprehensive request tracking for Streams-processed r
```suggestion
```

2024-11-28 11:44 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +<summary>Improved Logging for Streams</summary>
```suggestion
<summary>Added Logging for Streams</summary>
```

2024-11-28 16:16 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +  - [tyk-charts v2.1.0]({{<ref "product-stack/tyk-charts/release-notes/version-2.1.md">}})
```suggestion
  - [tyk-charts v2.2.0]({{<ref "product-stack/tyk-charts/release-notes/version-2.2.md">}})
```

2024-11-29 09:02 UTC, sharadregoti requested changes

2024-11-29 09:02 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +In 5.7.0, we have deprecated the dedicated [External OAuth]({{< ref "" >}})  (Tyk Classic: `external_oauth`, Tyk OAS: `server.authentication.securitySchemes.externalOAuth`) and [OpenID Connect]({{< r
```suggestion
In 5.7.0, we have deprecated the dedicated [External OAuth]({{< ref "add-url-here"" >}})  (Tyk Classic: `external_oauth`, Tyk OAS: `server.authentication.securitySchemes.externalOAuth`) and [OpenID Connect]({{< ref "add-url-here"" >}})  (Tyk Classic: `auth_configs.oidc`, Tyk OAS: `server.authentication.oidc`) authentication methods. We advise users to switch to [JWT Authentication]({{< ref "add-url-here"" >}}) .
```

2024-11-29 09:02 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +  - [tyk-charts v2.2.0]({{<ref "" >}})
For Sharad: This needs to be updated when this PR is merged https://github.com/TykTechnologies/tyk-docs/pull/5719

2024-11-29 09:02 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +### Release Date xxx
TODO: Update release date when merged.

2024-11-29 09:22 UTC, sharadregoti requested changes

2024-11-29 09:22 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +</li>
This seems unnecessary. Remove it.

![image](https://github.com/user-attachments/assets/18b1a1e1-020d-49e6-acbd-9ba04d2cde34)

2024-11-29 09:22 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +Add CVE summary
Remove this if not required.

2024-11-29 09:32 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +In 5.7.0, we have deprecated the dedicated [External OAuth]({{< ref "" >}})  (Tyk Classic: `external_oauth`, Tyk OAS: `server.authentication.securitySchemes.externalOAuth`) and [OpenID Connect]({{< r
@Eopayemi Change the URL. Replace `add-url-here` with actual URL

2024-11-29 13:40 UTC, andyo-tyk approved these changes

2024-12-02 10:10 UTC, sharadregoti approved these changes

2024-12-02 11:13 UTC, caroltyk approved these changes
LGTM

2024-12-03 13:09 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
> +  - [tyk-charts v2.2.0]({{<ref "" >}})
```suggestion
  - [tyk-charts v2.2.0]({{<ref "product-stack/tyk-charts/release-notes/version-2.1.md" >}})
```

2024-12-03 13:19 UTC, sharadregoti approved these changes

2024-12-03 13:20 UTC, merged