[DX-1720] Dashboard release notes 5.7.0
TykTechnologies/tyk-docs-hugo pull request #5621
Opened 2024-10-17 12:37 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1720](https://tyktech.atlassian.net/browse/DX-1720)

---

### Preview Link

<br>

### Description

Dashboard release notes 5.7.0

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-05 10:53 UTC, letzya commented
@sharadregoti @Eopayemi  Do we need separate PRs? I suggest merging this pr with the GWs as they are all in one release and go to the same branch. This should make the work on the release day simpler and faster with less errors.

2024-11-20 16:21 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +In 5.7.0, we have deprecated the dedicated [External OAuth]({{< ref “” >}})  (Tyk Classic: `external_oauth`, Tyk OAS: `securitySchemes.externalOAuth`) and [OpenID Connect]({{< ref “” >}})  (Tyk Class
```suggestion
In 5.7.0, we have deprecated the dedicated [External OAuth]({{< ref “” >}})  (Tyk Classic: `external_oauth`, Tyk OAS: `server.authentication.securitySchemes.externalOAuth`) and [OpenID Connect]({{< ref “” >}})  (Tyk Classic: `auth_configs.oidc`, Tyk OAS: `server.authentication.oidc`) authentication methods. We advise users to switch to [JWT Authentication]({{< ref “” >}}) .
```

2024-11-20 16:22 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +In 5.7.0, we have deprecated the dedicated [External OAuth]({{< ref “” >}})  (Tyk Classic: `external_oauth`, Tyk OAS: `securitySchemes.externalOAuth`) and [OpenID Connect]({{< ref “” >}})  (Tyk Class
Docs references can be taken from the deprecation pre-announcement in 5.6 release notes

2024-11-21 15:17 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +A new API endpoint, /audit-logs, has been introduced to provide programmatic access to stored audit logs. This allows users to retrieve, filter, and analyze logs more effectively. The API supports fi
should we mention here that it will only retrieve logs if the store is a db and not file?

2024-11-21 15:24 UTC, sredxny approved these changes

2024-11-21 15:59 UTC, caroltyk requested changes

2024-11-21 15:59 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +| | TIB (if using standalone) v1.5.1 | TIB all versions |
@Eopayemi 
These are the latest recommended versions with 5.7
MDCB 2.7.2
Operator 1.1
Sync 2.0.1
Helm Chart 2.2
Pump 1.11.1
TIB 1.6.1
EDP 1.12

2024-11-27 17:15 UTC, andyo-tyk requested changes
As with the Gateway - if Streams is new, there's no need to give detail of "fixes" within the new functionality.

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +<summary>Implemented backend Telemetry tracking with configurable option</summary>
I think for this we need to explain what this is, why it's been added, and the user impact.

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +<summary>Implemented HubSpot form for Contacting Tyk during trial period</summary>
```suggestion
<summary>Easily contact Tyk Support during Tyk Cloud trial</summary>
```

I think this is just for Tyk Cloud trials - probably worth being specific - and no need to mention HubSpot.

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +Introduced a HubSpot form on the Tyk Dashboard, allowing users to easily contact Tyk support during their trial period.
```suggestion
Introduced a form on the Tyk Dashboard that allows users to easily contact Tyk support during their trial period.
```

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +<summary>Displayed path parameters in UI for request validation during Import/Patch</summary>
```suggestion
<summary>Automatic configuration of request validation for path-level parameters during import of OpenAPI description</summary>
```

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +Path-level parameters are now displayed in the UI for the validate request middleware during import or patch. This update allows the middleware to be applied with just the defined path-level paramete
```suggestion
Tyk will now detect path-level parameters in the OpenAPI description and can be set to enable and configure the [Request Validation]({{< ref "product-stack/tyk-gateway/middleware/validate-request-tyk-oas" >}}) middleware automatically for these. Previously this automatic detection only worked for method-level parameters in the OpenAPI description.
```

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +<summary>Updated NPM dependencies for Tyk-Analytics-UI</summary>
```suggestion
<summary>Updated NPM package dependencies</summary>
```

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +Updated the NPM dependencies for the Dashboard UI to ensure compatibility.
```suggestion
Updated NPM package dependencies of Dashboard, to address security vulnerabilities.
```

(wording taken from previous NPM package update in release 5.5)

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +<summary>Fixed request validation for Path Parameters During Import/Patch</summary>
```suggestion
```

I think we can skip this, as it's covered in the "Added" section

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +Resolved a bug where enabling validate request middleware during import/patch OAS requests did not trigger validation when only common parameters were specified. Now, path parameters are properly val
```suggestion
```

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +<summary>User group dropdown limitations in Dashboard</summary>
```suggestion
<summary>Unable to see all *user groups* in Dashboard dropdown</summary>
```

2024-11-27 17:15 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +Fixed an issue with the user group dropdown in the Dashboard UI, ensuring that all available user groups are displayed when creating a new user.
```suggestion
Fixed an issue with the *user group* dropdown in the Dashboard UI, ensuring that all available user groups are displayed when creating a new user.
```

2024-11-28 11:49 UTC, agata-wit requested changes

2024-11-28 11:49 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +#### Add release highlight summary
```suggestion
#### Tyk Streams can be configured through Tyk Dashboard
```

2024-11-28 11:49 UTC, agata-wit commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +Add release highlight summary
```suggestion
With this release we are adding a possibility for users to configure their Stream & Events APIs using Tyk Dashboard. 
The new API designer leads users step-by-step to create a new Stream configuration easily. Pre-filled stream configurations for different inputs and outputs make it easy to make sure that the Stream is configured correctly.
```

2024-11-28 16:13 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +  - [tyk-charts v2.1.0]({{<ref "product-stack/tyk-charts/release-notes/version-2.1.md">}})
```suggestion
  - [tyk-charts v2.2.0]({{<ref "product-stack/tyk-charts/release-notes/version-2.2.md">}})
```

2024-11-29 08:54 UTC, sharadregoti requested changes

2024-11-29 08:54 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +In 5.7.0, we have deprecated the dedicated [External OAuth]({{< ref "" >}})  (Tyk Classic: `external_oauth`, Tyk OAS: `server.authentication.securitySchemes.externalOAuth`) and [OpenID Connect]({{< r
```suggestion
In 5.7.0, we have deprecated the dedicated [External OAuth]({{< ref "add-url-here" >}})  (Tyk Classic: `external_oauth`, Tyk OAS: `server.authentication.securitySchemes.externalOAuth`) and [OpenID Connect]({{< ref "add-url-here" >}})  (Tyk Classic: `auth_configs.oidc`, Tyk OAS: `server.authentication.oidc`) authentication methods. We advise users to switch to [JWT Authentication]({{< ref "add-url-here" >}}).
```

2024-11-29 08:54 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +  - [tyk-charts v2.2.0]({{< ref "" >}})
```suggestion
  - [tyk-charts v2.2.0]({{< ref "" >}})
```
This needs to be updated when this PR is merged #5719

2024-11-29 08:54 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +### Release Date xxx
TODO: Update release date when merged.

2024-11-29 09:09 UTC, sharadregoti requested changes

2024-11-29 09:09 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +Add CVE summary
Anything to be added here? If not then remove this section.

2024-11-29 12:35 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +Rolled out the /streams endpoint to the Tyk Dashboard API, dedicated to creating Stream and Events APIs in Tyk Streams. Documentation for the endpoint and its methods is available in the Tyk Docs.
```suggestion
Rolled out the `/streams` endpoint to the Tyk Dashboard API, dedicated to creating Stream and Events APIs in Tyk Streams. Documentation for the endpoint and its methods is available in the Tyk Docs.
```

We usually put endpoint paths in `code` format - but I don't know if this has changed?

2024-11-29 12:35 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +A new API endpoint, /audit-logs, has been introduced to provide programmatic access to audit logs stored in database. This allows users to retrieve, filter, and analyze logs more effectively. The API
```suggestion
A new API endpoint, `/audit-logs`, has been introduced to provide programmatic access to audit logs stored in database. This allows users to retrieve, filter, and analyze logs more effectively. The API supports filtering logs by key attributes like action, IP address, URL accessed, date range, user, and page number.
```

2024-11-29 12:35 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
> +For detail usage of the /audit-logs endpoint, please see [Dashboard API documentation]({{< ref "tyk-dashboard-api" >}}).
```suggestion
For detail usage of the `/audit-logs` endpoint, please see [Dashboard API documentation]({{< ref "tyk-dashboard-api" >}}).
```

2024-11-29 12:36 UTC, andyo-tyk approved these changes

2024-12-02 10:08 UTC, sharadregoti approved these changes

2024-12-02 11:12 UTC, caroltyk approved these changes
LGTM

2024-12-03 13:53 UTC, sharadregoti approved these changes

2024-12-03 14:15 UTC, merged

2024-12-03 14:16 UTC, sharadregoti commented
/release to release-5.7