Added release notes for Tyk cloud
TykTechnologies/tyk-docs-hugo pull request #5622
Opened 2024-10-18 03:51 UTC by sharadregoti

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-05 18:00 UTC, letzya commented on tyk-docs/content/tyk-cloud/release-notes/overview.md
> +
@sharadregoti please check if we want to add this new page with the new IA

2024-11-05 18:00 UTC, letzya commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +title: Tyk Cloud 1.23 Release Notes
Should the name be 1.23?

2024-11-05 18:03 UTC, letzya requested changes, later dismissed
1. With the new IA and since these RNs will not be very long, I think the RN of tyk cloud can be a single page.
2. Also the location of the file is incorrect `/tyk-cloud/release-notes/` - it's under the product stack... and as a rule, our file path is the same as our URL.

2024-11-06 07:24 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/overview.md
> +
Yes, we have should. I have updated the IA.

2024-11-06 07:26 UTC, sharadregoti commented
> 1. With the new IA and since these RNs will not be very long, I think the RN of tyk cloud can be a single page.
> 2. Also the location of the file is incorrect `/tyk-cloud/release-notes/` - it's under the product stack... and as a rule, our file path is the same as our URL.

Instead of following the old structure (where we need to create `tyk-cloud` directory in product-stack). Should we add this page as per the new IA under `community-support` section

2024-11-06 12:51 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +        Security Update: Bumped Vulnerable Dependencies in ARA Components
```suggestion
        Bumped Vulnerable Dependencies in Cloud Components
```

Also what is a cloud component? May use a generic term like library?

2024-11-06 13:10 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +  </li>
Can we use `free` & `paid` term instead of `trial` & `non-trial`

2024-11-06 13:10 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +        UI Update: "Add Portal Deployment" Widget Hidden for Team Members
```suggestion
        `Add Portal Deployment` Widget Hidden for Team Members

```

2024-11-06 13:10 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +        UI Fix: "Delete User" Button Hidden for Org Admin on Org+Billing Admin Profiles
```suggestion
        `Delete User` Button Hidden for Org Admin on Org+Billing Admin Profiles

```

2024-11-06 13:10 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +        UI Consistency Fix: Standardized Behavior for 'Upgrade' and 'Account & Billing' Buttons
```suggestion
        Standardized Behavior for `Upgrade` and `Account & Billing` Buttons

```

2024-11-06 13:10 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +        Direct Access to /password-reset Page Now Accessible Without Redirect
```suggestion
        Direct Access to `/password-reset` Page Now Accessible Without Redirect

```

2024-11-06 13:10 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +        UI Fix: Billing Sidebar Display Corrected When No Subscriptions Are Present
```suggestion
        Billing Sidebar Display Corrected When No Subscriptions Are Present

```

2024-11-06 13:10 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +An embedded interactive product tour has been added within the deployment screen to guide users through the Tyk Dashboard while they wait for their deployment to complete. This tour provides an overv
```suggestion
```

Not required, As we have pointed to the changelog in the release highlights

2024-11-06 15:09 UTC, excieve requested changes, later dismissed
Thanks! Left a few comments, mainly wording.

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +We are thrilled to announce new updates and improvements in Tyk Cloud 1.23.0, ... For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-1.23.0">}}) below.
```suggestion
We are thrilled to announce new updates and improvements in Tyk Cloud 1.23.0. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-1.23.0">}}) below.

```

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +### Dependencies {#dependencies-1.23.0}
```suggestion
### Compatibility {#compatibility-1.23.0}

```

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +      MServ now supports multiple plugin bundles, allowing users to manage and deploy various binaries for different plugins. This enhancement provides greater flexibility in plugin configuration and
```suggestion
      Tyk Cloud now supports multiple plugins in a bundle, allowing users to manage and deploy various binaries for the same plugin bundle. This enhancement provides greater flexibility in plugin configuration and deployment using `mservctl`.

```

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +        Support for Multiple Plugin Bundles in MServ
```suggestion
        Support for Bundles with Multiple Plugins

```

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +      An embedded interactive product tour has been added within the deployment screen to guide users through the Tyk Dashboard while they wait for their deployment to complete. This tour provides an
```suggestion
      An embedded interactive product tour has been added within the deployment screen to guide users through the Tyk Dashboard while they wait for their free trial on-boarding to complete. This tour provides an overview of key features, helping users explore what they can do on Tyk Cloud during their trial.

```

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +        Fix for NodesVisibility Logic to Manage Node Data Retention
```suggestion
        Fix for Hybrid Nodes Visibility Logic to Manage Node Data Retention

```

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +This update addresses a critical bug in the NodesVisibility logic, which previously retained all connected node data indefinitely. The fix ensures that the NodesData array only contains records from
```suggestion
This update addresses a critical bug in the Hybrid nodes visibility logic, which previously retained all connected node data for the Hybrid Data Planes indefinitely. The fix ensures that we only contains records from the last 7 days. This enhancement improves system performance at all stages within the Tyk Cloud UI for organizations with Hybrid Data Planes, especially those with multiple connected gateways.

```

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +  </li>
I'm fine with `paid`, but please keep the `free trial` as a term.

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +        Security Update: Bumped Vulnerable Dependencies in ARA Components
I don't think this needs to say "vulnerable" either since this is just a normal periodic libraries update, according to our SDLC.

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/overview.md
> +## Release 1
Can we remove this? It looks weird as Tyk Cloud doesn't need the varied policy-based versioning other Tyk products do, so it's likely to be "release 1" for many years ahead.

2024-11-06 15:09 UTC, excieve commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +An embedded interactive product tour has been added within the deployment screen to guide users through the Tyk Dashboard while they wait for their deployment to complete. This tour provides an overv
@sharadregoti How do we highlight major changes then?

2024-11-07 08:40 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/overview.md
> +## Release 1
This page is not required & will be deleted during restructuring (I working on it).

2024-11-07 08:46 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +### Dependencies {#dependencies-1.23.0}
@excieve We follow this [release note template](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md#dependencies) for all release notes across Tyk. Is this specific to tyk-cloud?

Also, I don't see the value of adding links to the LTS page. We can remove it and keep this section empty or remove it.

2024-11-07 08:52 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +  </li>
Ok.

2024-11-07 09:55 UTC, letzya commented on tyk-docs/data/menu.yaml
> +        - title: "Cloud"
I wonder if "Tyk Cloud" would be better as cloud sounds a bit random?

2024-11-07 09:58 UTC, letzya commented on tyk-docs/content/developer-support/release-notes/cloud.md
> +Here you can find the link to [Long-Term Support Releases](https://tyk.io/docs/developer-support/special-releases-and-features/long-term-support-releases/)
Can we rephrase this?

2024-11-07 10:06 UTC, letzya commented on tyk-docs/content/developer-support/release-notes/cloud.md
> +        Contact Form for PoC Requests on Trial Expiration
Can we avoid capitalizing every word of the summary? it looks odd on the page

2024-11-07 10:08 UTC, letzya commented on tyk-docs/content/developer-support/release-notes/cloud.md
> +This release adds new features to Tyk Cloud, including Support for **Multiple Plugin Bundles** in MServ for greater flexibility in plugin management, and an **Embedded Product Tour** during deploymen
@sharadregoti we need content that explains what mserv is and be able to link to it

2024-11-07 10:09 UTC, letzya commented on tyk-docs/content/developer-support/release-notes/cloud.md
> +This release adds new features to Tyk Cloud, including Support for **Multiple Plugin Bundles** in MServ for greater flexibility in plugin management, and an **Embedded Product Tour** during deploymen
```suggestion
This release adds new features to Tyk Cloud, including Support for **Multiple plugin bundles** in *MServ* for greater flexibility in plugin management, and an **Embedded Product Tour** during deployment wait times, offering users a guided overview of Tyk Dashboard features.

```

2024-11-07 10:18 UTC, letzya commented on tyk-docs/content/developer-support/release-notes/cloud.md
> +This release adds new features to Tyk Cloud, including Support for **Multiple plugin bundles** in *MServ* for greater flexibility in plugin management and an **Embedded product tour** during deployme
```suggestion
This Tyk Cloud update introduces features that improve both flexibility in plugin management and user onboarding. Now, *Mserv* (a Tyk CLI Tool, used as a file server for plugin definitions),  supports **multiple plugin bundles**, allowing greater customization and easier deployment of plugin configurations. Additionally, we added an **embedded product tour* to enhance the deployment experience, offering a guided walkthrough of Tyk Dashboard’s features, ideal for users familiarizing themselves with the platform during onboarding.

```

2024-11-07 10:19 UTC, letzya commented on tyk-docs/content/developer-support/release-notes/cloud.md
> +For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-1.23.0">}}) below.
```suggestion
For a comprehensive list of improvements and fixes, please check the detailed [changelog]({{< ref "#Changelog-1.23.0">}}) below.
```

2024-11-12 08:36 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/cloud.md
> +This release adds new features to Tyk Cloud, including Support for **Multiple Plugin Bundles** in MServ for greater flexibility in plugin management, and an **Embedded Product Tour** during deploymen
We will use this [explanation](tyk-cloud/configuration-options/using-plugins/uploading-bundle/).

2024-11-12 08:42 UTC, sharadregoti commented on tyk-docs/content/tyk-cloud/release-notes/version-1.23.md
> +An embedded interactive product tour has been added within the deployment screen to guide users through the Tyk Dashboard while they wait for their deployment to complete. This tour provides an overv
Restructured the content, you can have a look at it.

2024-11-12 09:12 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/cloud.md
> +Here you can find the link to [Long-Term Support Releases](https://tyk.io/docs/developer-support/special-releases-and-features/long-term-support-releases/)
Removed this section. As it does add any value.

2024-11-12 09:15 UTC, sharadregoti commented
Approving the PR.

2024-11-15 10:42 UTC, merged

2024-11-15 10:42 UTC, sharadregoti commented
/release to release-5.6