Left sidebar arrows Update
TykTechnologies/tyk-docs-hugo pull request #5627
Opened 2024-10-18 11:07 UTC by Arturas-Salivonas

Left sidebar arrows Update

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

1. Arrows on the left sidebar moved to the Right side.

2. Updated left sidebar arrow logic.
Closed state: Arrows point to the Right.
Open state: Arrows point to the bottom.

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-10-18 17:29 UTC, letzya commented on tyk-docs/assets/scss/_side-menu.scss
> +      background-position: right;
```suggestion
      background-position: left;
```

2024-10-21 07:32 UTC, sharadregoti requested changes
Can you also incorporate the following changes

1. Currently the arrow pointing in the right direction is not aligned with the center of the starting text. Can we align it horizontally
2. Reduce the spacing between the arrow and the starting of text by 4 to 8 pixels

2024-10-21 07:32 UTC, sharadregoti commented on tyk-docs/assets/scss/_side-menu.scss
> +      block-size:35px;
```suggestion
      block-size: 30px;
```
Can we make the caret size smaller as we reduced the text size of side nav options during the restructuring?
Currently the caret looks the same size of text.

2025-02-05 12:17 UTC, sharadregoti commented
This will be resolved in the latest Docs UI re-design

2025-02-05 12:17 UTC, closed without merging