[DX-1722]  Deprecation announcement
TykTechnologies/tyk-docs-hugo pull request #5643
Opened 2024-10-21 13:02 UTC by Eopayemi

### **User description**
### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1722](https://tyktech.atlassian.net/browse/DX-1722)

---

### Preview Link

<br>

### Description

[<br>](https://tyktech.atlassian.net/browse/TT-13323) [Add deprecation warning message for External Oauth and OIDC](https://github.com/TykTechnologies/tyk-docs/pull/5643)

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

[DX-1722]: https://tyktech.atlassian.net/browse/DX-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
documentation

___

### **Description**
- Announced the deprecation of support for SQLite, External OAuth Middleware, and OpenID Connect (OIDC) in Tyk Dashboard, effective from version 5.7.0.
- Explained the reasons for deprecating each feature to simplify the platform and enhance performance.
- Recommended transitioning to PostgreSQL, MongoDB, and JWT Authentication as alternatives.
- Included a link to the documentation for further details on the changes.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>version-5.6.md</strong><dd><code>Announce deprecation of SQLite, OAuth, and OIDC in Tyk Dashboard</code></dd></summary>
<hr>

tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md

<li>Added deprecation notice for SQLite, External OAuth Middleware, and <br>OpenID Connect (OIDC).<br> <li> Explained reasons for deprecating each feature.<br> <li> Recommended alternatives for deprecated features.<br> <li> Provided a link to documentation for more information.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk-docs/pull/5643/files#diff-cc15e8898e7bad2601f58ad9bbc70879a3924e7e2153e44048adf25abc34b564">+21/-1</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

2024-10-22 10:21 UTC, andyo-tyk requested changes
Be clear that we are deprecating the dedicated OIDC _middleware_.

2024-10-22 10:21 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
> +We are deprecating support for SQLite, External OAuth Middleware, and OpenID Connect (OIDC) in Tyk Dashboard to simplify the platform and enhance overall performance. These changes will take effect f
```suggestion
We are deprecating support for SQLite, External OAuth Middleware, and OpenID Connect (OIDC) Middleware in Tyk Dashboard to simplify the platform and enhance overall performance. These changes will take effect from 5.7.0.
```

2024-10-30 09:40 UTC, andyo-tyk requested changes
Expanded the deprecation notices, including links to the JWT page

2024-10-30 09:40 UTC, andyo-tyk commented on tyk-docs/content/tyk-dashboard/database-options.md
> +Starting from 5.7.0, SQLite support will be deprecated. To avoid disrputions, please transition to either PostgreSQL or MongoDB as alternative database options
```suggestion
SQLite support will be deprecated from Tyk 5.7.0. To avoid disrupution, please transition to PostgreSQL, MongoDB or one of the listed compatible alternatives.
```

2024-10-30 09:40 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> +This will be deprecated from 5.7.0. To avoid any disruptions, please switch to JSON Web Token (JWT) for authentication.
```suggestion
Tyk's dedicated External OAuth middleware will be deprecated from Tyk 5.7.0. Tyk's [JSON Web Token (JWT)]({{< ref "basic-config-and-security/security/authentication-authorization/json-web-tokens#about-jwts" >}}) authentication method also allows you to integrate with a third party OAuth provider, so the dedicated middleware will be deprecated to reduce duplication and potential for misconfiguration.
```

2024-10-30 09:40 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/openid-connect.md
> +This will be deprecated from 5.7.0. To avoid any disruptions, please switch to JSON Web Token (JWT) for authentication.
```suggestion
Tyk's dedicated OpenID Connect Authentication middleware will be deprecated from Tyk 5.7.0. Tyk's [JSON Web Token (JWT)]({{< ref "basic-config-and-security/security/authentication-authorization/json-web-tokens#about-jwts" >}}) authentication method also allows you to integrate with an OIDC provider, so the dedicated OIDC middleware will be deprecated to reduce duplication and potential for misconfiguration.
```

2024-10-31 09:49 UTC, andyo-tyk approved these changes
Looks good, thanks. Please publish ASAP

2024-10-31 17:08 UTC, sharadregoti requested changes

2024-10-31 17:08 UTC, sharadregoti commented on 5.6
> +Merge branch 'update-5.6' of github.com:TykTechnologies/tyk-docs into update-5.6
What is this file? Looks unnecessary. Please remove it

2024-10-31 17:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +SQLite support will be deprecated from Tyk 5.7.0. To avoid disrupution, please transition to PostgreSQL, MongoDB or one of the listed compatible alternatives.
Can we add reference links to relevant documentation for  mongodb & postgresql

2024-10-31 17:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +SQLite support will be deprecated from Tyk 5.7.0. To avoid disrupution, please transition to PostgreSQL, MongoDB or one of the listed compatible alternatives.
Same as previous and do this wherever it is repeated. If not available we can skip it

2024-10-31 17:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/data-storage-configuration.md
> +
These deprecation notes have been duplicated too many times. It would be nice if we defined it once & used it's reference everywhere.

2024-11-01 08:33 UTC, merged

2024-11-01 08:34 UTC, letzya commented
/release to release-5.6