[DX-1726] Gateway release notes 5.3.8
TykTechnologies/tyk-docs-hugo pull request #5658
Opened 2024-10-23 10:55 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1726](https://tyktech.atlassian.net/browse/DX-1726)

---

### Preview Link

<br>

### Description

Gateway release notes for 5.3.8

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-06 12:34 UTC, sharadregoti requested changes

2024-11-06 12:34 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This update fixes a bug that caused increased memory usage when proxying large response payloads in version 5.3.1, restoring memory requirements to the levels seen in version 5.0.6. Users experiencin
Does this mean that memory issue was only present in version `5.3.1` or all the versions after `5.3.1`?

Please rephrase if incorrect.

2024-11-06 12:34 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +A backwards compatibility issue in the OAS API Definitions JSON schema has been addressed by reinstating support for 'additionalProperties'. Previously, version 5.3 enforced strict validation, causin
```suggestion
A backwards compatibility issue in the OAS API Definitions JSON schema has been addressed by reinstating support for `additionalProperties`. Previously, version 5.3 enforced strict validation, causing problems for users downgrading from version 5.6. With this change, Tyk customers can move between versions seamlessly, ensuring their APIs remain functional and avoiding system performance issues.
```

2024-11-06 12:34 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This update resolves an issue where API keys were lost on worker gateways if the keyspace synchronization process was interrupted. The solution now enforces a resynchronization whenever a connection
Can you add reference documentation that elaborates more on `keyspace synchronization` feature? Ignore if not available.

2024-11-06 12:34 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +A deprecation notice for External OAuth and OpenID Connect (OIDC) authentication mechanisms has been added to the Gateway logs starting from version 5.3.8. This provides advanced notification to user
```suggestion
A [deprecation notice](#<add-deprecation-notice>) for External OAuth and OpenID Connect (OIDC) authentication mechanisms has been added to the Gateway logs starting from version 5.3.8. This provides advanced notification to users regarding any APIs configured with these authentication methods in preparation for future upgrades where these middleware options may be removed in version 5.7.0.
```

Add deprecation notice fragment

2024-11-06 12:34 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This is an advanced notice that External OAuth, OpenID Connect (OIDC) authentication methods, and SQLite support will be deprecated starting in version 5.7.0. Please review your API configurations, a
Please add relevant reference links to `External OAuth, OpenID Connect, Sqlite`

2024-11-06 12:36 UTC, sharadregoti requested changes

2024-11-06 12:36 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +There are no breaking changes in this release, however if moving from an version of Tyk older than 5.3.0 please read the
Please follow the [RN](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md#breaking-changes) format

2024-11-06 12:36 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +If you are upgrading to 5.3.8, please follow the detailed [upgrade instructions](#upgrading-tyk).
Please follow the [RN](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md#upgrading-tyk) format

2024-11-06 12:58 UTC, sharadregoti requested changes

2024-11-06 12:58 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Deprecation notice for External OAuth and OpenID Connect options</summary>
I think this should not come in the `fixed` section. Used [added](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md#added) instead.

2024-11-06 17:19 UTC, Eopayemi commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This update fixes a bug that caused increased memory usage when proxying large response payloads in version 5.3.1, restoring memory requirements to the levels seen in version 5.0.6. Users experiencin
Only present in 5.3.1

2024-11-06 17:20 UTC, Eopayemi commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This update resolves an issue where API keys were lost on worker gateways if the keyspace synchronization process was interrupted. The solution now enforces a resynchronization whenever a connection
@caroltyk Please can you help here.

2024-11-06 17:21 UTC, Eopayemi commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +A deprecation notice for External OAuth and OpenID Connect (OIDC) authentication mechanisms has been added to the Gateway logs starting from version 5.3.8. This provides advanced notification to user
The notice hasn't been posted anywhere in particular. However, we have added warning messages to all the pages that mention both authentication in Tyk docs.

2024-11-07 10:08 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +### Release Date XXX
```suggestion
### Release Date 07 November 2024
```

2024-11-07 10:12 UTC, sharadregoti requested changes

2024-11-07 10:12 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +| [Go](https://go.dev/dl/)                                      | 1.19 (GQL), 1.22 (GW) | 1.19 (GQL), 1.22 (GW) | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go
Does `1.19 (GQL)` has to be removed? It is not present in previous release.

2024-11-07 10:33 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This is an advanced notice that External OAuth, OpenID Connect (OIDC) authentication methods, and SQLite support will be deprecated starting in version 5.7.0. Please review your API configurations, a
Can you incorporate suggestion from @andyo-tyk review in dashboard PR

2024-11-07 12:24 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This update resolves an issue where API keys were lost on worker gateways if the keyspace synchronization process was interrupted. The solution now enforces a resynchronization whenever a connection
```suggestion
This update resolves an issue where API keys were lost on worker gateways if the [keyspace synchronization]({{<ref "product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser">}}) process was interrupted. The solution now enforces a resynchronization whenever a connection is re-established between MDCB and a Worker Gateway, ensuring key data integrity and seamless API access.
```

2024-11-07 12:41 UTC, sharadregoti approved these changes

2024-11-07 14:30 UTC, andyo-tyk reviewed
Some suggestions/observations

2024-11-07 14:30 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +<summary>Enhanced flexibility in OAS JSON Schema: Additional Properties no longer enforced</summary>
```suggestion
<summary>Enhanced flexibility in Tyk OAS schema validation</summary>
```

2024-11-07 14:30 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +A backwards compatibility issue in the OAS API Definitions JSON schema has been addressed by reinstating support for `additionalProperties`. Previously, version 5.3 enforced strict validation, causin
```suggestion
A backwards compatibility issue in the way that the Gateway handles Tyk OAS API definitions has been addressed by reducing the strictness of validation against the expected schema. Since Tyk version 5.3, the Gateway has enforced strict validation, potentially causing problems for users downgrading from newer versions. With this change, Tyk customers can move between versions seamlessly, ensuring their APIs remain functional and avoiding system performance issues.
```
What about this?

2024-11-07 14:30 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
> +This update resolves an issue where API keys were lost on worker gateways if the [keyspace synchronization]({{<ref "product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser">}}) process
```suggestion
This update resolves an issue where API keys could be lost if the [keyspace synchronization]({{<ref "product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser">}}) between control and data planes was interrupted. The solution now enforces a resynchronization whenever a connection is re-established between MDCB and the data plane, ensuring key data integrity and seamless API access.
```
Please check with Platform squad, but I think this is perhaps better, since we are being consistent with control/data plane terminology rather than highlighting individual gateways.

2024-11-07 20:26 UTC, caroltyk approved these changes

2024-11-08 11:31 UTC, andyo-tyk approved these changes
Great, thanks.

2024-11-12 15:21 UTC, merged

2024-11-12 15:21 UTC, sharadregoti commented
/release to release-5.6

2024-11-12 15:22 UTC, sharadregoti commented
/release to release-5.3