[DX-1726] Dashboard release notes 5.3.8
TykTechnologies/tyk-docs-hugo pull request #5659
Opened 2024-10-23 11:24 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1726](https://tyktech.atlassian.net/browse/DX-1726)

---

### Preview Link

<br>

### Description

Dashboard release notes 5.3.8

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-05 17:58 UTC, letzya commented
@Eopayemi the label now is for PRs that fix something and the content needs to be published straight away (not urgently, just once it is approved). PRs for future releases you do not want us to merge, till the release actually happens. 
I'm removing the "now" label

2024-11-06 10:45 UTC, letzya commented
@Eopayemi in order to avoid errors, can I please confirm this was created using the template?

2024-11-06 12:44 UTC, sharadregoti requested changes

2024-11-06 12:44 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +This is an advanced notice that External OAuth, OpenID Connect (OIDC) authentication methods, and SQLite support will be deprecated starting in version 5.7.0. Please review your API configurations, a
Please add relevant reference links to External OAuth, OpenID Connect, Sqlite

2024-11-06 12:44 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +There are no breaking changes in this release, however, if moving from a version of Tyk older than 5.3.0 please read the explanation provided with [5.3.0 release]({{< ref "#TykOAS-v5.3.0">}}).
Please follow the [RN](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md#breaking-changes) format

2024-11-06 12:44 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +If you are upgrading to 5.3.8, please follow the detailed [upgrade instructions](#upgrading-tyk).
Please follow the [RN](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md#upgrading-tyk) format

2024-11-06 12:44 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +|         | Helm Chart (tyk-stack, tyk-oss, tyk-dashboard, tyk-gateway) v1.4.0 | Helm all versions |
Shouldn't the version for helm be `v2`?

2024-11-06 12:44 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + - ```bash
This is not rendered as a sub point

2024-11-06 12:44 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + - [tyk-charts v1.4]({{< ref "product-stack/tyk-charts/release-notes/version-1.4.md" >}})
This is not rendered as a sub point

2024-11-06 12:44 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + - [tyk-charts v1.4]({{< ref "product-stack/tyk-charts/release-notes/version-1.4.md" >}})
This should also be `v2`

2024-11-06 12:44 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +A deprecation notice for External OAuth and OpenID Connect (OIDC) authentication mechanisms has been implemented in the UI starting from version 5.3.8. This provides advanced notification to users re
Add a reference to the notice.

2024-11-06 12:44 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +| [GoLang](https://go.dev/dl/)                               | 1.21       | 1.21       | [Go plugins]({{< ref "plugins/supported-languages/golang" >}}) must be built using Go 1.21 |
This should be `1.22`? i guess. Please check with previous release.

Please check both the tables with previous release & If necessary confirm from @caroltyk

2024-11-06 12:58 UTC, sharadregoti requested changes

2024-11-06 12:58 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Deprecation notice of External OAuth and OpenID Connect options</summary>
I think this should not come in the `fixed` section. Used [added](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-template.md#added) instead.

2024-11-06 17:04 UTC, Eopayemi commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +This is an advanced notice that External OAuth, OpenID Connect (OIDC) authentication methods, and SQLite support will be deprecated starting in version 5.7.0. Please review your API configurations, a
We haven't created a deprecation log yet so we don't have one single reference page that has all the info in. We have placed warning messages on all pages in the docs that have these authentication methods mentioned.

2024-11-07 09:40 UTC, andyo-tyk reviewed
Suggested clarifications

2024-11-07 09:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Rate Limiting not saved with Upstream Certificates enabled for OAS API</summary>
```suggestion
<summary>Rate Limiting settings not saved when Upstream Certificates enabled for Tyk OAS API</summary>
```

Please remember always to use "Tyk OAS API" never abbreviate to "OAS API" as that can lead to uncertainty/confusion.

2024-11-07 09:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +This update resolves an issue with the user group dropdown, ensuring that all created user groups are displayed when creating a new user.
```suggestion
Fixed an issue with the user group dropdown in the Dashboard UI, ensuring that all available user groups are displayed when creating a new user.
```

2024-11-07 09:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +<summary>Deprecation notice of External OAuth and OpenID Connect options</summary>
```suggestion
<summary>Advanced notice of deprecation of dedicated External OAuth and OpenID Connect auth options</summary>
```

Trying to soften the blow a bit here - don't want to scare users into thinking that they can no longer use OAuth or OIDC.

2024-11-07 09:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +A deprecation notice for External OAuth and OpenID Connect (OIDC) authentication mechanisms has been implemented in the UI starting from version 5.3.8. This provides advanced notification to users re
```suggestion
The UI now displays a deprecation notice for the dedicated [External OAuth]({{< ref "basic-config-and-security/security/authentication-authorization/ext-oauth-middleware" >}}) and [OpenID Connect (OIDC)]({{< ref "basic-config-and-security/security/authentication-authorization/openid-connect" >}}) authentication mechanisms. This provides advanced notification that these authentication options will be deprecated in version 5.7.0. Users are advised to migrate to the [JWT Auth]({{< ref "basic-config-and-security/security/authentication-authorization/json-web-tokens#about-jwts" >}}) method, which supports integration with both OAuth and OIDC providers, in preparation for future upgrade.
```

Proposed rewording with links into the docs.

2024-11-07 09:40 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +This is an advanced notice that External OAuth, OpenID Connect (OIDC) authentication methods, and SQLite support will be deprecated starting in version 5.7.0. Please review your API configurations, a
```suggestion
This is an advanced notice that the dedicated External OAuth, OpenID Connect (OIDC) authentication options, and SQLite support will be deprecated starting in version 5.7.0. We recommend that users of the [External OAuth]({{< ref "basic-config-and-security/security/authentication-authorization/ext-oauth-middleware" >}}) and [OpenID Connect]({{< ref "basic-config-and-security/security/authentication-authorization/openid-connect" >}}) methods migrate to Tyk's dedicated [JWT Auth]({{< ref "basic-config-and-security/security/authentication-authorization/json-web-tokens#about-jwts" >}}) method. Please review your API configurations, as the Gateway logs will provide notifications for any APIs utilizing these methods.
```

I'm thinking we should provide reassurance here that there is a recommended alternative (JWT Auth). WDYT?

2024-11-07 10:05 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + - ```bash
This is not resolved yet.

2024-11-07 10:06 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> + - [tyk-charts v1.4]({{< ref "product-stack/tyk-charts/release-notes/version-1.4.md" >}})
This is also not resolved yet.

2024-11-07 10:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
> +### Release Date xxx
```suggestion
### Release Date 07 November 2024
```

2024-11-07 12:51 UTC, sharadregoti approved these changes

2024-11-07 14:39 UTC, andyo-tyk approved these changes
Looks good, thanks.

2024-11-12 15:17 UTC, merged