Documented JWE config options
TykTechnologies/tyk-docs-hugo pull request #5681
Opened 2024-10-30 15:04 UTC by sredxny

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-05 09:23 UTC, sharadregoti requested changes

2024-11-05 09:23 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| JWE.Private_key_location         | Specifies the path or identifier (certid) for the certificate that contains the private key used to decrypt the ID token when JWE is enabled. This certificate mus
Can you confirm that this is snake case `JWE.Private_key_location` and not PascalCase `JWE.PrivateKeyLocation`. Because `UseProviders.SkipUserInfoRequest` is following pascal case

2024-11-08 14:35 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
> +| JWE.Private_key_location         | Specifies the path or identifier (certid) for the certificate that contains the private key used to decrypt the ID token when JWE is enabled. This certificate mus
Fixed!! It was an issue in our side, its now `JWE.PrivateKeyLocation`

2024-11-08 16:50 UTC, carolwkc approved these changes

2024-11-12 10:58 UTC, sharadregoti requested changes

2024-11-12 10:58 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +### JWE step-by-step guide
Change the title to reflect what we will be doing & also add a 2 line description of what this guide will accomplish.

2024-11-12 10:58 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +- A public key file for the IdP (used to encrypt the ID token)
These two steps does not provide much context on what exactly has to be done.

Can you clarify the following:
1. The algorithm to be used for asymmetric keys & it's size. RS-256, RS-512
2. Will self-signed certificate work? Or an official certificate is required
3. In which format the cerificate & other keys are expected. (`.pem` etc...)

2024-11-12 10:58 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +   - For embedded TIB in Dashboard: Use Tyk Dashboard's certificate manager
Add an image of dashboard showing the above.

2024-11-12 10:58 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +3.1. Create a new TIB profile:
Add an image of dashboard for the same.

2024-11-12 10:58 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +- An Identity Provider (IdP) that supports JSON Web Encryption (JWE)
We should write this document with a specific IDP, such as `Keycloak`, in mind. Currently, the information provided about the IDP is too generic. While users will adjust the steps according to their chosen IDP, we should at least develop this document with `Keycloak` or other relevant IDPs as references.

2024-11-12 10:58 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +2.1. Create a new client in your IdP for Tyk Identity Broker
Also add what things to be noted down after creating the client. Client ID, Client Secret.

2024-11-12 10:58 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +     "ProviderConfig": {
```suggestion
     ...
     "ProviderConfig": {
```

2024-11-14 14:32 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +- A public key file for the IdP (used to encrypt the ID token)
@sharadregoti we do not limit to which certificates algos to use, you can use whatever you want 🤔  so not sure if we should mention this, this looks more like documentation for the certificate manager rather than TIB.
#2 self signed cert will work.
#3 The ones supported by the certificate manager

2024-11-14 14:35 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +- An Identity Provider (IdP) that supports JSON Web Encryption (JWE)
Indeed, however currently there is not free software to test JWE, only keycloak but is broken. In order for us to test we had to built keycloack from source from a branch that is fixing their issues but not released yet. I consider that put screenshots or base the example on a third party app that is currently broken will not be 100% helpful as they will experience issues. Eg: I write the example using keycloack, then you in your local will follow those steps but it will not work because keycloak is broken... How do you think we should proceed with this one? knowing that at some point anyway keycloak will release the fix

2024-11-14 14:36 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +2.1. Create a new client in your IdP for Tyk Identity Broker
wdym? which things are important to copy from the client? only client secret, cliend id and the `wellknownopenidconfiguration` url

2024-11-15 11:12 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +1.2. Load the public key into your IdP for ID token encryption (process varies by IdP)
Need an extra line space.

```suggestion

1.2. Load the public key into your IdP for ID token encryption (process varies by IdP)
```

2024-11-19 10:15 UTC, sharadregoti requested changes
Thanks for creating `.gif` files. It's great. Only thing, I want to point out next time take full screen recording.

2024-11-19 10:15 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +- An Identity Provider (IdP) that supports JSON Web Encryption (JWE)
You can either use `auth0`—the free tier should suffice for the purpose of writing the article—or opt for `keycloak`. If you choose `keycloak`, we'll include a note detailing the steps we took to make it work and link to the relevant GitHub issues.

2024-11-19 10:15 UTC, sharadregoti commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +- A public key file for the IdP (used to encrypt the ID token)
Got it, I'll rephrase the above.

2024-11-21 14:20 UTC, caroltyk commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +- An Identity Provider (IdP) that supports JSON Web Encryption (JWE)
If the steps and instructions can be applied for all Identity Provider (IdP) that supports JSON Web Encryption (JWE), we don't need to provide tool-specific guidance is it?

I'm afraid we cannot and would not keep track of changes that happen on other tools. What is working today may be changed in another release if the instruction is too detailed.

2024-11-21 15:30 UTC, sredxny commented on tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
> +- An Identity Provider (IdP) that supports JSON Web Encryption (JWE)
@sharadregoti unfortunately the free tier of oauth0 doesnt allow us to enable JWE, its a regulated and paid feature (this was our nightmare to test the feature)

2024-11-27 06:22 UTC, sharadregoti approved these changes

2024-11-27 06:23 UTC, merged

2024-11-27 06:23 UTC, sharadregoti commented
/release to release-5.6