Update the getting started pages
TykTechnologies/tyk-docs-hugo pull request #5687
Opened 2024-10-31 21:43 UTC by DavidRollins

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description
1. Describe your changes in detail. Why is this change required? What problem does it solve?
Update the Getting started section with how to create an account, how to configure your first api, and how to use the tyk dashboard pages. This will tutorialize the basic usage of Tyk for a new user.

     2. Please explain the change to the reviewer. Pay special attention to changes that are hard to spot, 
       for example:
       2.1. Add the three pages to the menu.yaml
       2.2. Develop the content for the tutorial pages
     4. @mentions of the person to review the proposed changes. They need to be able to know the topic well in order to approve it.

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-05 18:16 UTC, letzya commented on tyk-docs/assets/img/getting-started/api-management-apis.png
@DavidRollins @sharadregoti is it me or the font is quite small?

2024-11-11 14:14 UTC, sharadregoti requested changes

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/create-account.md
> +For this guide, we'll focus on creating an account for Tyk Cloud, which offers a free 14-day trial.
It's not 14 day trial, 2 day or 48 hours

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/create-account.md
> +{{< img src="/img/2.10/create-account-setup-choice.png" alt="Create Account Setup" >}}
Let's give some context on what to select?

For example, in the personalized set-up we can include, what personalization he can expect. In the `autoamtic` setup, we can explain what is being setup automatically in the background

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/create-account.md
> +Once your account is set up, you can access the Tyk Developer Portal. This portal allows you to manage your APIs, view analytics, and customize your API consumer experience.
I think terminology has to be fixed here.

Is it the `portal` or `dashboard`? I believe we access `portal` from dashboard & that also requires [setup](https://tyk.io/docs/tyk-cloud/initial-portal-config/).

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/create-account.md
> +2. Set up your account on the free 14-day Tyk Cloud trial plan.
It's 2 day trial

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/create-account.md
> +
Let's also add the things that it has created automatically for us?

1. May be samples APis are created?
2. Default gateways & edges (what's the difference between them)?
3. Anything else...

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/create-account.md
> +
Let's add a note using the `short-code` explaining what happens to the created infrastructure after the free trial ends.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +- A Tyk Cloud account.
Add a reference to `create account` page

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +- A backend service that your API will proxy (e.g., a RESTful API).
The `httpbin` is a readily available service that we can use. Let's not make this a compulsory step. Let's rephrase it as, If you have existing restful API, that is well & good, or you can use`httpbin`

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +  {{< img src="/img/getting-started/apis-connect-gateways.png" alt="Connect Gateways" >}}
I think it would be good to explain the diff between two options shown in the image (edge and other one). When I saw the image, that's the first question came to mind.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/using-tyk-dashboard.md
> +* **Classic Portal**: In Classic Portal, you can affect permissions and configurations related to your developer portal. The Tyk Developer Portal is a platform that enables you to publish, manage, an
These items are not visible in the above reference image, would be better to close all options to make it visible or keep only one open & remaining close. So that everything is composed in a single image.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/using-tyk-dashboard.md
> +If you are new here, we suggest that you start with an example API and see how our pre-configured APIs are setup- we have examples for GraphQL, OAS, and UDG (Universal Data Graph) APIs. If you have a
```suggestion
If you are new here, we suggest that you start with an example API and see how our pre-configured APIs are setup- we have examples for GraphQL, Tyk OAS, and UDG (Universal Data Graph) APIs. If you have a specific API that you that you have already setup, you can import it using an OpenAPI document, a Tyk API document, or through a WSDL/XML file. 
```

Whenever referencing`OAS`, use `Tyk OAS`. Because there is difference between them. Where `Tyk OAS` is fully compatible with `OAS`

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/data/menu.yaml
> +    show: True
These three pages should come under a field called `menu`.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/using-tyk-dashboard.md
> +* **Classic Portal**: In Classic Portal, you can affect permissions and configurations related to your developer portal. The Tyk Developer Portal is a platform that enables you to publish, manage, an
These items are not visible in the above image. I suggest you take a screenshot with all options closed or keep one open & the remaining all closed. Just ensuring all the options listed here are available in the image.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/using-tyk-dashboard.md
> +{{< img src="/img/getting-started/tabs-api-management.png" alt="API Management Side Bar" >}}
These side nav images look awful. I suggest you take the screenshot of complete window similar `overview` & `sidebar` image. And highlight section you are explaining using a red box marker. Here is a sample.

Please do this for all the sidenav image in this page

 
![final-image](https://github.com/user-attachments/assets/035fe9b8-e48b-4ecb-aabc-f79f4af2f4e9)

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +   - **Target URL**: Provide the URL of your backend service (e.g., `https://my-backend-service.com`).
The URL should be httpbin

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +  {{< img src="/img/getting-started/apis-configure-settings.png" alt="Configure Settings" >}}
Change the image, have a full window screenshot & highlight this section.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +6. **Authentication**: Choose the desired authentication method (e.g., **API Key**).
Please add some text (go here, go there, press button, scroll etc..), only heading & images is breaking flow.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +6. **Authentication**: Choose the desired authentication method (e.g., **API Key**).
Add an image here.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +```
Remove this. I don't see any value from this example. It is abrupt & out of context.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +6. **Authentication**: Choose the desired authentication method (e.g., **API Key**).
Also, the last step of saving the API is missing. Maybe you can combine it in this point itself.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +   {{< img src="/img/getting-started/apis-sidebar-security.png" alt="Keys Menu" >}}
Please change all the images like this & add a full window snippet with highlight. I have provided a sample in of the review comments.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +     - Or **Group by Authentication Type** or **Category** to filter APIs.
Please reference the `My First API` created in the first step.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +   {{< img src="/img/getting-started/apis-create-key.png" alt="APIs Create Key" >}}
Unnecessary image. We can remove it & combine these two points into one.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +   {{< img src="/img/getting-started/apis-keys-success.png" alt="Key Success" >}}
Please highlight what key to be copied. The `hash` or the `id`. Clarify the same in the text as well.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +## Monitor Traffic and Analyze API Performance
Why there is no section for the testing the API that is just created? Isn't the purpose of getting started to test things out?

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +```
Hmm, How does use get this? This just comes up suddenly with no previous steps.

2024-11-11 14:14 UTC, sharadregoti commented on tyk-docs/data/menu.yaml
> +  - title: "Using Tyk Dashboard"
Also, I think after `create account`. We should have `using Tyk Dashboard` & then `configure your first API`. Because in `configure your first API` we are using tyk dashboard.

2024-11-11 17:26 UTC, DavidRollins commented on tyk-docs/content/getting-started/using-tyk-dashboard.md
> +{{< img src="/img/getting-started/tabs-api-management.png" alt="API Management Side Bar" >}}
good idea, will do

2024-11-19 13:29 UTC, sharadregoti requested changes

2024-11-19 13:29 UTC, sharadregoti commented on tyk-docs/content/getting-started/create-account.md
> +## Further Portal Configuration
Did you try creating a cloud account from scratch? I tried it today. It is different what is mentioned here.

After getting the login email, here are SS for the next steps.
![Screenshot 2024-11-19 at 6 26 38 PM](https://github.com/user-attachments/assets/f85ce2df-7c3d-441f-a42c-3934263af075)

Also, there is quick tutorial of dashboard while it is being deployed.
![Screenshot 2024-11-19 at 6 26 52 PM](https://github.com/user-attachments/assets/2d319689-e7fd-4344-95c2-58ca6504f1eb)

![Screenshot 2024-11-19 at 6 34 17 PM](https://github.com/user-attachments/assets/d583dc6b-b79b-4364-b361-91a51aa0e01b)
![Screenshot 2024-11-19 at 6 35 29 PM](https://github.com/user-attachments/assets/7ca1d734-50db-465f-bcf1-40e711075711)

2024-11-19 13:29 UTC, sharadregoti commented on tyk-docs/content/getting-started/create-account.md
> +### Step 4: Choose Your Setup
This is also a invalid step, After step 3, you directly go to step 5

2024-11-19 13:29 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +2. **Navigate to APIs** and click **Create New API**.
There is no, `create New API` button. If you are creating an API for the first time. here is the reference image.

So `Design from scratch` is best for first timers.

![image](https://github.com/user-attachments/assets/cc3e528c-e8b0-48cd-bda8-9f6a204a0d77)

2024-11-19 13:29 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +  {{< img src="/img/getting-started/apis-create-new-api.png" alt="Create New API" >}}
This is not the latest image. Here is the new image. According to this, our textual explanation will also change.

Note: Image provided below are just for references, The image should not have browser tabs, and bookmarks being shown.

![image](https://github.com/user-attachments/assets/b14dcb05-40e9-4161-babb-60dc1bcda139)

2024-11-19 13:29 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +  {{< img src="/img/getting-started/apis-connect-gateways.png" alt="Connect Gateways" >}}
Always add full window images.

2024-11-19 13:29 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +4. **Connect to Your Desired Gateway**
Also, it will be good to add that, `edge` and `gateway` is already created for you.

2024-11-19 13:29 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +  {{< img src="/img/getting-started/apis-configure-settings.png" alt="Configure Settings" >}}
The bullet points are not rendered properly.

![image](https://github.com/user-attachments/assets/4f887dbe-2a2f-499b-8d13-01fcdffaff37)

2024-11-19 13:29 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +5. **Configure Settings**
Let's say these are available options, but not necessary to configure in this demo. Good to explore

2024-11-19 13:29 UTC, sharadregoti commented on tyk-docs/content/getting-started/configure-first-api.md
> +Save your API configuration once complete.
I cannot create an API, if the options highlighted in red are not configured. We haven't explained this.

![image](https://github.com/user-attachments/assets/5d6de24d-fb03-473a-8f9c-5f320744c15a)

2024-11-20 15:56 UTC, sharadregoti approved these changes

2024-11-25 07:49 UTC, merged

2024-11-25 07:49 UTC, sharadregoti commented
/release to release-5.6