Automations new ia
TykTechnologies/tyk-docs-hugo pull request #5689
Opened 2024-11-01 17:40 UTC by DavidRollins

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description
1. Describe your changes in detail. Why is this change required? What problem does it solve?
Add automations page to highlight Tyk operator, streams, and mdcb features - api lifecycle automations

2. Please explain the change to the reviewer. Pay special attention to changes that are hard to spot, 
       for example:
       2.1. Name change in the file name or directory name - please flag it out since it’s hard 
            to compare text after such a change 
       2.2. Terminology change - flag it out to make sure the reviewer is aware before approving

     4. @mentions of the person to review the proposed changes. They need to be able to know the topic well in order to approve it.

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-04 13:33 UTC, sharadregoti requested changes

2024-11-04 13:33 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +- **Tyk Dashboard access and API credentials**
For this pre-requisite also, can you specify for which section this is applicable, similar to what you have done for the above pre-requisites?

2024-11-04 13:33 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +You can also use other sample files from `our repository`.
```suggestion
You can also use other sample files from our [repository](<some-link>).
```

2024-11-04 13:33 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +Creating an API takes the same approach whether you are using Tyk Open Source or Self Managed. First, specify the details of your API using the ApiDefinition CRD, then deploy it to create the corresp
```suggestion
Creating an API takes the same approach whether you are using Tyk Open Source or Self Managed. First, specify the details of your API using the [ApiDefinition CRD](<add-some-reference>), then deploy it to create the corresponding Kubernetes resource. Tyk Operator will take control of the CRD and create the actual API in the Tyk data plane.
```

2024-11-04 13:33 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +}%
```suggestion
```curl
curl -i localhost:8080/httpbin/get
HTTP/1.1 401 Unauthorized
Content-Type: application/json
X-Generator: tyk.io
Date: Thu, 03 Mar 2022 15:47:30 GMT
Content-Length: 46

{
    "error": "Authorization field missing"
}
```

2024-11-04 13:33 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +- `meta_data`: Metadata key and values.
```suggestion
```

I think we can remove it & point to the definition docs instead. Because we haven't explained the same for `ApiDefinition` CRD

2024-11-04 13:33 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +## Getting Started
This page defines 4 sections for automation, It seems this `getting started` guide is only intended for Tyk operators & it has no relation with the other 3 sections. Can we move this part into `Automate API Management in Kubernetes Environments`

2024-11-04 13:33 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +## Introduction
Any reason that we did not follow the exact structure that was discussed in [IA](https://docs.google.com/document/d/1-ngEX98p7m8I9Z5v328ASN4aQ-B8MgVcasKnzQiULZY/edit?tab=t.0#heading=h.c2iy6qzeswnu)

For example:
For `Synchronize Tyk Configurations Across Environments` section, these topics were missing `Automated Configuration Backups`, `Cross-Environment Synchronization`, `Version-Controlled API Definitions`

Similary for `Using Tyk APIs to Manage Resources` and `Automate Multi-Environment Deployments`

or Am I missing something?

2024-11-05 09:03 UTC, sharadregoti requested changes

2024-11-05 09:03 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +##### API Definition and Security Policy
The heading is misleading with respect to the content below

2024-11-05 09:03 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +Tyk Operator manages two custom resources to help users create and maintain their API configurations:
We need to rephrase this as we don't have only `two` custom resources. As there is an entire table after this explanation.

2024-11-07 13:17 UTC, letzya requested changes
@DavidRollins Pages which had a link to a specific page like sync overview cannot now send readers to the new automation page, it needs to be more specific like it was, to keep the good user experience. 

(Also this is the reason the ci is breaking)

2024-11-08 10:17 UTC, sharadregoti requested changes
Overall content looks good to me.

2024-11-08 10:17 UTC, sharadregoti commented on tyk-docs/content/advanced-configuration/manage-multiple-environments/move-apis-between-environments.md
> +You can also use our new Tyk-Sync tool which allows you to sync your APIs (and Policies) with a Version Control System (VCS). You can then move your APIs between environments. See [Tyk-Sync]({{< ref
Let's remove the double slash prefix `//` and only use a single slash.

I see this at some places, Do ctlr+f and replace it

2024-11-08 10:17 UTC, sharadregoti commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
> +Please consult the Tyk Operator supporting documentation for an example of how to [enable basic authentication]({{< ref "/api-management/automations#set-up-tyk-classic-api-authentication#basic-authen
This URL does not work. A URL cannot have double fragments `#` in it.

Please check & do this change everywhere.

2024-11-08 10:17 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +| Upstream mTLS | ✅ [Upstream mTLS via Operator]({{<ref "basic-config-and-security/security/mutual-tls/upstream-mtls#tyk-operator-classic">}}) | ✅ [Upstream mTLS via Operator]({{<ref "basic-config-an
This is not part of IA, may be this comes under the `TLS certificates` section just above?

2024-11-08 10:17 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +#### Set Up Manifest for GraphQL
This is not rendered correctly because of the above code block not getting closed correctly.

![image](https://github.com/user-attachments/assets/737fefcd-f147-4c08-8dc3-6bc7b37bb292)

2024-11-08 10:17 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +``
Add a single back tick here.

2024-11-08 10:17 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +### Publish Your API to Dev Portal
This is not added in IA, Can you check & update accordingly. May be part of previous section?

2024-11-08 10:17 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +### Tyk Sync Features
Update the IA docs accordingly

2024-11-08 10:17 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +### API Ownership
As per IA, this seem a sub heading of `Manage API MetaData`

2024-11-08 17:40 UTC, DavidRollins commented on tyk-docs/content/api-management/automations.md
> +| Upstream mTLS | ✅ [Upstream mTLS via Operator]({{<ref "basic-config-and-security/security/mutual-tls/upstream-mtls#tyk-operator-classic">}}) | ✅ [Upstream mTLS via Operator]({{<ref "basic-config-an
Yes, heading level was wrong- fixed

2024-11-12 06:16 UTC, sharadregoti requested changes

2024-11-12 06:16 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +* **Multi-Environment Deployments**: Simplify deployments across various staging, testing, and production environments.
```suggestion
```

Remove this.

2024-11-12 09:24 UTC, carolwkc commented on tyk-docs/content/api-management/automations.md
> +Tyk Operator integrates directly with Kubernetes, allowing you to define and manage APIs as code. This means you can deploy, update, and secure APIs using the same declarative configuration approach
```suggestion
Tyk Operator is a native Kubernetes Operator, allowing you to define and manage APIs as code. This means you can deploy, update, and secure APIs using the same declarative configuration approach Kubernetes uses for other application components. 
```

2024-11-12 09:24 UTC, carolwkc commented on tyk-docs/content/api-management/automations.md
> +##### Single source of Truth for API configurations
```suggestion
##### Single source of truth for API configurations
```

2024-11-12 09:24 UTC, carolwkc commented on tyk-docs/content/api-management/automations.md
> +Tyk Operator will reconcile any divergence between Git and the actual state in [Tyk Gateway](/tyk-oss-gateway/) or [Tyk Dashboard](/tyk-dashboard/). Therefore, you should maintain the API definition
```suggestion
Tyk Operator will reconcile any divergence between Kubernetes desired state and the actual state in [Tyk Gateway](/tyk-oss-gateway/) or [Tyk Dashboard](/tyk-dashboard/). Therefore, you should maintain the API definition manifests in Kubernetes as the single source of truth for your system. If you update your API configurations using Tyk Dashboard, those changes would be reverted by Tyk Operator eventually.
```

2024-11-12 09:24 UTC, carolwkc commented on tyk-docs/content/api-management/automations.md
> +You can install Argo CD, Flux CD or the GitOps tool of your choice in a cluster, and connect it to the Git repository where you version control your API manifests. The tool can alert on any divergenc
```suggestion
You can install Argo CD, Flux CD or the GitOps tool of your choice in a cluster, and connect it to the Git repository where you version control your API manifests. The tool can synchronise changes from Git to your cluster. The API manifest updates in cluster would be detected by Tyk Operator, which has a Kubernetes controller to automatically reconcile the API configurations on your Tyk Gateway or Tyk Dashboard. 
```

2024-11-12 09:24 UTC, carolwkc commented on tyk-docs/content/api-management/automations.md
> +
We should include a description of SecurityPolicy CRD here too.

2024-11-12 09:24 UTC, carolwkc commented on tyk-docs/content/api-management/automations.md
> +##### Install and Configure Tyk Operator
is this meant to be at the same level as "Key Concepts"?

2024-11-12 09:24 UTC, carolwkc commented on tyk-docs/content/api-management/automations.md
> +#### Migrate Existing APIs to Tyk Operator
This section is not part of "Set up OAS API". It should follow "Set Up Tyk Classic API".

2024-11-12 09:24 UTC, carolwkc commented on tyk-docs/content/api-management/automations.md
> +#### Add a Security Policy to your OAS API
It applies to both OAS and Tyk Classic API. Please move this section out.

2024-11-12 18:29 UTC, DavidRollins commented on tyk-docs/content/api-management/automations.md
> +##### Install and Configure Tyk Operator
nope, fixed this thanks

2024-11-19 10:30 UTC, caroltyk requested changes

2024-11-19 10:30 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +4. Gradually replace Classic definitions with OAS definitions in your Tyk installation.
@sharadregoti Where does this come from? 
@andyo-tyk are you aware of these steps?

2024-11-19 10:30 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +- **GraphQL Support**: You can learn more about how to support GraphQL resources via Tyk Operator [here](/product-stack/tyk-operator/advanced-configurations/custom-plugins)
Wrong link. Also, it leads to 404 not found.

2024-11-19 10:30 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +- **Advanced Tyk API Management**: Leverage more of Tyk’s API capabilities for custom integrations and further automation possibilities. You can learn more about Tyk's custom integrations [here](/pro
The link does not work

2024-11-19 10:30 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +- **CI/CD Integrations**: Learn how to embed Tyk automation into your CI/CD pipeline, enabling continuous deployment and reducing release cycle times.
Any link for this one?

2024-11-19 10:30 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +```
```suggestion
2. Configure Tyk Operator to point to your external Tyk installation, e.g. via `tyk-operator-conf`, environment variable, or OperatorContext:

```yaml
    TYK_MODE: pro
    TYK_URL: http://external-tyk-dashboard
    TYK_AUTH: api-access-key
    TYK_ORG: org-id
```

2024-11-19 10:30 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +    TYK_URL: http://tyk-gateway-prod:8080
```suggestion
    TYK_URL: http://tyk-dashboard-prod
```

2024-11-19 10:30 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +    TYK_URL: http://tyk-gateway-staging:8080
```suggestion
    TYK_URL: http://tyk-dashboard-staging
```

2024-11-19 10:30 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +
Where is it from? I don't think we have this feature.

2024-11-19 10:30 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +   This command shows logs from the Tyk Operator pod, which may contain error messages or other useful information.
I followed this instructions but get nothing. Does it really work? 

I'd suggest rename "Reconciliation Troubleshooting" to "Tyk Operator changes not applied" because they are addressing same issue. We should use content from Reconciliation Troubleshooting because that is more operator specific.

2024-11-19 10:47 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +- **CI/CD Integrations**: Learn how to embed Tyk automation into your CI/CD pipeline, enabling continuous deployment and reducing release cycle times.
I think CI/CD part has to be removed.

2024-11-19 10:48 UTC, sharadregoti commented on tyk-docs/content/api-management/automations.md
> +- **GraphQL Support**: You can learn more about how to support GraphQL resources via Tyk Operator [here](/product-stack/tyk-operator/advanced-configurations/custom-plugins)
@DavidRollins We need to use `<ref>` syntax for internal links.

2024-11-19 14:18 UTC, caroltyk commented on tyk-docs/content/api-management/automations.md
> +- **CI/CD Integrations**: Learn how to embed Tyk automation into your CI/CD pipeline, enabling continuous deployment and reducing release cycle times.
There's a few blogs we can point readers to
https://tyk.io/blog/a-practical-guide-using-tyk-operator-argocd-and-kustomize/
https://tyk.io/blog/gitops-enabled-api-management-in-kubernetes/

2024-11-25 08:27 UTC, sharadregoti approved these changes

2024-11-25 08:28 UTC, merged

2024-11-25 08:29 UTC, sharadregoti commented
/release to release-5.6

2024-11-25 09:02 UTC, sharadregoti commented
/release to release-5.6

2024-11-29 15:21 UTC, andyo-tyk commented on tyk-docs/content/api-management/automations.md
> +4. Gradually replace Classic definitions with OAS definitions in your Tyk installation.
Er.... no, we don't have such a tool. Not sure where this came from!

2024-11-29 15:22 UTC, andyo-tyk commented on tyk-docs/content/api-management/automations.md
> +4. Gradually replace Classic definitions with OAS definitions in your Tyk installation.
@sharadregoti can we get this removed from the docs please ASAP?