Authn new ia
TykTechnologies/tyk-docs-hugo pull request #5690
Opened 2024-11-01 17:41 UTC by DavidRollins

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description
1. Describe your changes in detail. Why is this change required? What problem does it solve?
Update the authentication and authorization page to consolidate content around authentication types and how to secure your apis in Tyk

     2. Please explain the change to the reviewer. Pay special attention to changes that are hard to spot, 
       for example:
       2.1. Name change in the file name or directory name - please flag it out since it’s hard 
            to compare text after such a change 
       2.2. Terminology change - flag it out to make sure the reviewer is aware before approving
     3. @mentions of the person to review the proposed changes. They need to be able to know the topic well in order to approve it.

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-04 15:54 UTC, letzya commented
@DavidRollins the PR has conflicts and also I don't see that the deleted pages have been added as aliases

2024-11-08 13:13 UTC, sharadregoti requested changes

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/api-management/authentication-authorization.md
> +}
In the [original response](https://tyk.io/docs/basic-config-and-security/security/authentication--authorization/oauth2-0/username-password-grant/#response), it contains an extra field called `refresh_token`

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/api-management/authentication-authorization.md
> +  -d 'grant_type=client_credentials&client_id=ed59158fa2344e94b3e6278e8ab85142'
Client secret is also passed in the [original doc](https://tyk.io/docs/basic-config-and-security/security/authentication--authorization/oauth2-0/client-credentials-grant/#token-request). Need to verify once which one is correct.

The `data` table below also has to be modified.

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/api-management/authentication-authorization.md
> +  -d 'grant_type=refresh_token&refresh_token=NWQzNGVhMTItMDE4Ny00MDFkLTljOWItNGE4NzI1ZGI1NGU2&client_id=ed59158fa2344e94b3e6278e8ab85142'
Same as below, client_secret missing

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/api-management/authentication-authorization.md
> +   {{< img src="/img/2.10/client_mtls_add_cert.png" alt="Add Key Certificate" >}}
It seems we are not using the correct image here. The original has a different [image](https://tyk.io/docs/basic-config-and-security/security/mutual-tls/client-mtls/#developer-portal---self-serve-cert-trust).

In the original docs, this image is used in the previous [step](https://tyk.io/docs/basic-config-and-security/security/mutual-tls/client-mtls/#quickstart).

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/basic-config-and-security/security.md
> +As part of using Mutual TLS, you can create a list of [trusted certificates]({{< ref "/api-management/authentication-authorization#concepts#certificates" >}}).
Multiple fragments do not work. Please check and correct everywhere.

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/getting-started/key-concepts/authentication.md
> +For more configuration options check the [JWT documentation]({{< ref "/api-management/authentication-authorization#use-json-web-tokens-jwt.md" >}}).
`.md` prefix at the end also does not work. Please check & fix everywhere.

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/api-management/authentication-authorization.md
> +| **Authorization** | Basic authorization using base64 encoded credentials, e.g., `dXNlcm5hbWU6cGFzc3dvcmQ=`. |
For basic authentication, we missed some important section from the [docs](https://tyk.io/docs/basic-config-and-security/security/authentication-authorization/basic-auth/#protect-your-api-with-basic-authentication). Is there any rationale behind it?

The same has not been conveyed in the IA as well.

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/api-management/authentication-authorization.md
> +### Integrate External OAuth Middleware
We missed some important section from the [docs](https://tyk.io/docs/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware/#introspection). Is there any rationale behind it?

The same has not been conveyed in the IA as well.

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/api-management/authentication-authorization.md
> +### Sign Requests with HMAC
We missed some important section from the [docs](https://tyk.io/docs/basic-config-and-security/security/authentication-authorization/hmac-signatures/#a-sample-signature-generation-snippet). Is there any rationale behind it?

The same has not been conveyed in the IA as well.

2024-11-08 13:13 UTC, sharadregoti commented on tyk-docs/content/api-management/authentication-authorization.md
> +### Multiple (Chained) Authentication
Let's add this [reference](https://tyk.io/docs/basic-config-and-security/security/authentication-authorization/multiple-auth/#enable-multi-chained-authentication-with-tyk-operator), which is missing in ours.

2024-11-21 13:45 UTC, sharadregoti commented on tyk-docs/content/api-management/authentication-authorization.md
> +
```suggestion
```

2024-11-25 11:37 UTC, sharadregoti approved these changes

2024-11-25 11:38 UTC, merged

2024-11-25 11:38 UTC, sharadregoti commented
/release to release-5.6