added documentation of support of db audit logs
TykTechnologies/tyk-docs-hugo pull request #5697
Opened 2024-11-06 14:39 UTC by sredxny

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-07 10:31 UTC, sharadregoti requested changes

2024-11-07 10:31 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +In addition to file storage, audit logs can now be stored in the main database (MongoDB or Postgres), this feature is available since Tyk 5.7.0. To enable database storage set `audit.storage_type` to
```suggestion
In addition to file storage, audit logs can be stored in the main database (MongoDB or Postgres), this feature has been available since Tyk 5.7.0. To enable database storage set `audit.storage_type` to `db`:
```

2024-11-07 10:31 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +When `storage_type` is set to `db`, audit logs will be stored in the main Dashboard storage instead of a file.
```suggestion
When `storage_type` is set to `db`, audit logs will be stored in the main database storage instead of a file.
```
Was that a typo?

2024-11-07 10:31 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. For comprehensive details on the API specifications, including all availa
```suggestion
Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. To know more about the API specifications, check out the swagger [documentation]({{ref "tyk-dashboard-api"}}).
```

2024-11-07 10:31 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +To access the audit logs through the API ensure that your user account or group has been granted the "Audit Logs" RBAC group. If you do not have the necessary permissions, please contact your system
```suggestion
To access the audit logs through the API ensure that your user account or group has been granted the `Audit Logs` RBAC group.
```
Can you elaborate more on the `Audit Logs` RBAC group? Is it permission or what? It feels like the sentence is abruptly ended & something is missing.

2024-11-07 14:22 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +When `storage_type` is set to `db`, audit logs will be stored in the main Dashboard storage instead of a file.
no really a typo, but sounds better as "database"

2024-11-07 14:23 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +To access the audit logs through the API ensure that your user account or group has been granted the "Audit Logs" RBAC group. If you do not have the necessary permissions, please contact your system
yes, is a permission, the same as its for api access, policies access, etc. But this time audit permission

2024-11-07 20:28 UTC, caroltyk approved these changes
LGTM

2024-11-07 20:46 UTC, caroltyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. To know more about the API specifications, check out the swagger [documen
```suggestion
Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. To know more about the API specifications, check out the swagger [documentation]({{ref <"tyk-dashboard-api">}}).
```

2024-11-07 20:49 UTC, caroltyk commented
@sredxny I saw both "storage_type" and "store_type" in the document... which one is correct?

2024-11-08 17:52 UTC, sredxny commented
> @sredxny I saw both "storage_type" and "store_type" in the document... which one is correct?

`store_type` is the correct one, I pushed a fix. Good catch!

2024-11-12 06:00 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. To know more about the API specifications, check out the swagger [documen
```suggestion
Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. To know more about the API specifications, check out the swagger [documentation]({{ref "tyk-dashboard-api"}}).
```

2024-11-12 06:03 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. To know more about the API specifications, check out the swagger [documen
```suggestion
Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. To know more about the API specifications, check out the swagger [documentation]({{<ref "tyk-dashboard-api" >}}).
```

2024-11-12 06:10 UTC, sharadregoti approved these changes

2024-11-12 06:10 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. To know more about the API specifications, check out the swagger [documen
@sredxny Can you confirm that the API is introduced in dashboard.

2024-11-12 13:01 UTC, sredxny commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
> +Since Tyk 5.7.0 a new API endpoint has been added to allow authorized users to retrieve audit logs from the database storage. To know more about the API specifications, check out the swagger [documen
yes, confirmed

2024-11-14 06:32 UTC, merged