EDP 1.12.0 Release notes
TykTechnologies/tyk-docs-hugo pull request #5698
Opened 2024-11-06 16:23 UTC by tbuchaillot

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-07 08:07 UTC, sharadregoti requested changes

2024-11-07 08:07 UTC, sharadregoti commented on tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
> +    description: OpenAPI specs for APIs included into the API Prodcuts
```suggestion
    description: OpenAPI specs for APIs included into the API Products
```

2024-11-07 08:07 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.12.0.md
> +</ul>
@alienor This has to be removed right?

2024-11-07 08:09 UTC, sharadregoti commented on tyk-docs/data/page_available_since.json
> +        },
```suggestion
```

2024-11-07 08:10 UTC, tbuchaillot commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.12.0.md
> +</ul>
@sharadregoti let me change Tyk Gateway mention for EDP here- Why we would want to remove this section?

2024-11-07 10:22 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.12.0.md
> +{{< img src="/img/dashboard/portal-management/enterprise-portal/1.12.0-embedded-tib.png" width=500px alt="SSO profiles">}}
I cannot read this text 
<img width="654" alt="image" src="https://github.com/user-attachments/assets/22c51e26-cdff-41e3-89eb-9361ebc397a5">

2024-11-07 10:25 UTC, letzya commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.12.0.md
> +{{< img src="/img/dashboard/portal-management/enterprise-portal/1.12.0-embedded-tib.png" width=500px alt="SSO profiles">}}
I love the use of images! is so helpful. However, I struggle reading the content @sharadregoti . If we can improve it with a separate iteration, we can keep this.

2024-11-07 14:00 UTC, sharadregoti approved these changes

2024-11-12 05:54 UTC, sharadregoti commented
TODO: Change the release date when merged.

2024-11-13 13:52 UTC, merged

2024-11-13 13:53 UTC, sharadregoti commented
/release to release-5.6