Sync 2.0.1 RN
TykTechnologies/tyk-docs-hugo pull request #5717
Opened 2024-11-14 16:41 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-19 08:00 UTC, sharadregoti requested changes

2024-11-19 08:00 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-2.0.md
> +#### Updated
```suggestion
#### Changed
```

2024-11-19 08:01 UTC, sharadregoti approved these changes

2024-11-27 09:14 UTC, komalsukhani approved these changes

2024-12-06 06:56 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-sync/release-notes/sync-2.0.md
> +### Release Date DD Mon YYYY <<update>>
```suggestion
### Release Date 05 December 2024
```

2024-12-06 07:12 UTC, merged

2024-12-06 07:13 UTC, sharadregoti commented
/release to release-5.7