MDCB 2.7.2 RN
TykTechnologies/tyk-docs-hugo pull request #5718
Opened 2024-11-14 17:18 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-19 07:57 UTC, sharadregoti requested changes

2024-11-19 07:57 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
> +## 2.7.2 Release Notes
@caroltyk This is not following the [RN](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-condensed-template.md) template style. Please change it.

2024-11-21 15:24 UTC, sredxny approved these changes

2024-11-26 11:44 UTC, sharadregoti approved these changes
TODO: Change date on merge date.

2024-12-03 12:42 UTC, merged

2024-12-09 13:24 UTC, sharadregoti commented
/release to release-5.7