Tyk Chart 2.2 release
TykTechnologies/tyk-docs-hugo pull request #5719
Opened 2024-11-14 22:58 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-19 07:45 UTC, sharadregoti requested changes

2024-11-19 07:45 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.2.md
> + Tyk Charts 2.1 will install the following Tyk component versions by default.
```suggestion
 Tyk Charts 2.2 will install the following Tyk component versions by default.
```

2024-11-19 07:45 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.2.md
> +Users can now define custom HPA behavior settings directly in the Helm values file via a new field a new field: `.Values.gateway.autoscaling.behavior`.
```suggestion

Users can now define custom HPA behavior settings directly in the Helm values file via a new field a new field: `.Values.gateway.autoscaling.behavior`.
```
Added a new line, for proper rendering of code block

2024-11-21 08:21 UTC, sharadregoti approved these changes

2024-11-21 08:25 UTC, sharadregoti approved these changes

2024-11-21 08:26 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.2.md
> +### Release Date DD Mon YYYY <<update>>
```suggestion
### Release Date 24 Nov 2024
```

2024-11-27 09:02 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.2.md
> +Tyk Operator manifests used ControllerManagerConfig CRD to configure Operator Manager. However, the ControllerManagerConfig CRD has been deprecated in Tyk Operator v1.0 when we upgraded controller-ru
@caroltyk This change is not included. Am I right @buraksekili ?

2024-11-27 09:11 UTC, komalsukhani requested changes

2024-11-27 09:11 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +- `auditLogs.type`: Specifies the storage type for audit logs (`db` or `file`). It sets corresponding Dashboard environment variable `TYK_DB_AUDIT_TYPE`. Set to `file` by default.
```suggestion
- `auditLogs.type`: Specifies the storage type for audit logs (`db` or `file`). It sets corresponding Dashboard environment variable `TYK_DB_AUDIT_STORETYPE`. Set to `file` by default.
```

2024-11-27 09:11 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +- `auditLogs.type`: Specifies the storage type for audit logs (`db` or `file`). It sets corresponding Dashboard environment variable `TYK_DB_AUDIT_TYPE`. Set to `file` by default.
```suggestion
- `auditLogs.type`: Specifies the storage type for audit logs (`db` or `file`). It sets corresponding Dashboard environment variable `TYK_DB_AUDIT_STORETYPE`. Set to `file` by default.
```

2024-11-27 09:11 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +- `auditLogs.enabled`: Enables or disables audit logging. It sets corresponding Dashboard environment variable `TYK_DB_AUDIT_ENABLED`. Enabled by default.
```suggestion
- `auditLogs.enabled`: Enables or disables audit logging. It sets corresponding Dashboard environment variable `TYK_DB_AUDIT_ENABLED`. Disabled by default.
```

2024-11-27 09:11 UTC, komalsukhani commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +- `auditLogs.enabled`: Enables or disables audit logging. It sets corresponding Dashboard environment variable `TYK_DB_AUDIT_ENABLED`. Enabled by default.
```suggestion
- `auditLogs.enabled`: Enables or disables audit logging. It sets corresponding Dashboard environment variable `TYK_DB_AUDIT_ENABLED`. Disabled by default.
```

2024-11-27 15:14 UTC, buraksekili commented on tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.2.md
> +Tyk Operator manifests used ControllerManagerConfig CRD to configure Operator Manager. However, the ControllerManagerConfig CRD has been deprecated in Tyk Operator v1.0 when we upgraded controller-ru
yes, you are right @komalsukhani. the change has not been merged yet.

2024-12-09 11:24 UTC, sharadregoti approved these changes

2024-12-09 11:31 UTC, komalsukhani approved these changes

2024-12-09 11:33 UTC, merged

2024-12-09 11:33 UTC, sharadregoti commented
/release to release-5.7