New section & guide on the UI for Streams
TykTechnologies/tyk-docs-hugo pull request #5721
Opened 2024-11-15 10:39 UTC by jay-deshmukh

Docs for creating streaming API using dashboard UI

2024-11-19 07:55 UTC, buraksezer approved these changes

2024-11-21 08:16 UTC, sharadregoti requested changes

2024-11-21 08:16 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-streaming/streams-configuration-using-ui.md
> +1. Click on **Streams & Events** from the sidebar. This will open a form for creating the Streams API.
After clicking on `Streams & Events` tab, are we sure there is no `add API` button? or this is true only for first time & during second time. There will be `add api` button.

You may update the below images accordingly.

2024-11-21 08:16 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-streaming/streams-configuration-using-ui.md
> +
Please add a section for Testing the API. There should be some option using curl or postman to test the created API. Also update the overview at the top accordingly.

2024-11-21 08:16 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-streaming/streams-configuration-using-ui.md
> +   - **Configuration**: Provide a policy name and set a key expiration interval.
Add an image for this section.

2024-11-22 03:36 UTC, jay-deshmukh commented on tyk-docs/content/product-stack/tyk-streaming/streams-configuration-using-ui.md
> +1. Click on **Streams & Events** from the sidebar. This will open a form for creating the Streams API.
The `+ Add API` button has been deprecated in the new UI changes @sharadregoti

2024-11-22 03:45 UTC, jay-deshmukh commented on tyk-docs/content/product-stack/tyk-streaming/streams-configuration-using-ui.md
> +
This guide focuses primarily on the configuration steps and does not include details on any specific APIs, as none have been configured yet. A separate documentation will be provided for API configuration and testing `(Input / Output / Processor)`. Since testing an API without configured streams would not yield meaningful results, this section has been omitted from the current guide.

2024-11-22 03:51 UTC, jay-deshmukh commented on tyk-docs/content/product-stack/tyk-streaming/streams-configuration-using-ui.md
> +   - **Configuration**: Provide a policy name and set a key expiration interval.
adressed.

2024-11-26 12:03 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-streaming/streams-configuration-using-ui.md
> +---
```suggestion
```

2024-11-26 12:03 UTC, sharadregoti approved these changes

2024-11-27 07:02 UTC, merged