[TT-13567] Review & update developer portal integration for streams
TykTechnologies/tyk-docs-hugo pull request #5732
Opened 2024-11-19 09:10 UTC by buraksezer

PR for https://tyktech.atlassian.net/browse/TT-13567

2024-11-21 08:41 UTC, sharadregoti requested changes

2024-11-21 08:41 UTC, sharadregoti commented on tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
> +Simply create a Tyk Streams API, create a Policy which protects it, and then publish it to the Developer Portal Catalog.
We should add a reference to create streams API page (I this is the [PR](https://github.com/TykTechnologies/tyk-docs/pull/5721)) & also add reference to publish API to developer portal catalog. If not available we should write it here.

2024-11-22 11:29 UTC, pvormste approved these changes

2024-11-27 07:30 UTC, sharadregoti approved these changes

2024-11-27 07:31 UTC, sharadregoti approved these changes

2024-11-27 07:31 UTC, merged