Update 5.7.0
TykTechnologies/tyk-docs-hugo pull request #5734
Opened 2024-11-19 11:53 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-26 11:25 UTC, sharadregoti approved these changes

2024-11-27 16:45 UTC, andyo-tyk commented on tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
> -We've deprecated the External OAuth middleware in Tyk 5.7.0 to simplify configurations and avoid redundancy. For third-party OAuth integration, please switch to Tyk’s [JSON Web Tokens (JWT)]({{< ref
I don't think this was supposed to be removed.

2024-11-27 16:51 UTC, andyo-tyk requested changes
Suggested a more direct wording. Also, where there's a specific tab/section for sqlite we should remove it and replace with the "this is no longer supported" notice.

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
```suggestion
Tyk no longer supports SQLite as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}), or one of the listed compatible alternatives.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
```suggestion
Tyk no longer supports SQLite as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}), or one of the listed compatible alternatives.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/data-storage-configuration.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
```suggestion
Tyk no longer supports SQLite as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}), or one of the listed compatible alternatives.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
```suggestion
Tyk no longer supports SQLite as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}), or one of the listed compatible alternatives.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
>  Yes, since 1.4.0 version of the Enterprise Developer Portal, it supports SQL databases (MariaDB, SQLite, MySQL, and PostgreSQL) for storing the portal's CMS assets.
```suggestion
The Enterprise Developer Portal supports SQL databases (MariaDB, MySQL, and PostgreSQL) for storing the portal's CMS assets.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
```suggestion
Tyk no longer supports SQLite as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}), or one of the listed compatible alternatives.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
Can we actually just remove this <tab> and put the "not supported" message above the tab section?

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
```suggestion
Tyk no longer supports SQLite as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}), or one of the listed compatible alternatives.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
```suggestion
Tyk no longer supports SQLite as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}), or one of the listed compatible alternatives.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/tyk-dashboard/database-options.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
```suggestion
Tyk no longer supports SQLite as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}), or one of the listed compatible alternatives.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/tyk-dashboard/database-options.md
>  * For PoC installations, you can use any of the following platforms (SQLite, PostgreSQL or MongoDB).
```suggestion
* For PoC installations, you can use PostgreSQL or MongoDB.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/tyk-pump/configuration.md
> +SQLite support has reached end of life as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoD
```suggestion
Tyk no longer supports SQLite as of Tyk 5.7.0. To avoid disruption, please transition to [PostgreSQL]({{< ref"planning-for-production/database-settings/postgresql#introduction" >}}), [MongoDB]({{< ref "planning-for-production/database-settings/mongodb" >}}), or one of the listed compatible alternatives.
```

2024-11-27 16:51 UTC, andyo-tyk commented on tyk-docs/content/tyk-pump/configuration.md
>  In v4.0 of the Tyk Dashboard, we have added support for the following SQL platforms:
```suggestion
In v4.0 of the Tyk Dashboard, we added support for the following SQL platforms:
```

2024-12-02 10:35 UTC, andyo-tyk approved these changes
Thanks

2024-12-03 12:43 UTC, sharadregoti approved these changes

2024-12-03 12:44 UTC, merged