Operator 1.1 RN
TykTechnologies/tyk-docs-hugo pull request #5741
Opened 2024-11-21 15:32 UTC by caroltyk

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-11-26 10:52 UTC, sharadregoti requested changes
TODO: Change Release Date When merged.

2024-11-26 10:52 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-1.1.md
> +Learn More: TBD
```suggestion
```

Anything pending?

2024-11-26 10:57 UTC, sharadregoti approved these changes

2024-11-27 08:49 UTC, komalsukhani approved these changes

2024-12-09 10:54 UTC, sharadregoti commented on tyk-docs/content/product-stack/tyk-operator/release-notes/operator-1.1.md
> +### Release Date XX Nov 2024 (TBD)
```suggestion
### Release Date 09 December 2024
```

2024-12-09 11:24 UTC, merged

2024-12-09 11:24 UTC, sharadregoti commented
/release to release-5.7