Initial draft
TykTechnologies/tyk-docs-hugo pull request #5812
Opened 2024-12-09 15:49 UTC by andyo-tyk

### Preview Link

### Description
Initial draft of adding explanation of URL ordering algorithm

2024-12-20 16:50 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- **Similar paths**: If you deploy multiple APIs with similar paths (e.g. `/project` and `/project-management`) you will want to ensure that the [correct path](#pattern-ordering) is matched to reques
```suggestion
- **Similar paths**: If you deploy multiple APIs with similar paths (e.g. `/project` and `/project-management`) you will want to ensure that the [correct path](#path-ordering) is matched to requests.
```

2024-12-20 18:03 UTC, titpetric commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +If a match is found, no further checks will be perfomed, so it is important to understand how Tyk orders the patterns to ensure there is no accidental routing to the wrong endpoint.
```suggestion
Having created the ordered list, Tyk will attempt to match the request against the paths (patterns) in the list, starting from the top and moving down the list. If a match is found, no further checks will be perfomed, so it is important to understand how Tyk orders the patterns to ensure there is no accidental routing to the wrong endpoint.
```

2024-12-20 18:04 UTC, titpetric approved these changes

2024-12-31 07:04 UTC, sharadregoti requested changes

2024-12-31 07:04 UTC, sharadregoti commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +On receipt of an API request Tyk firstly creates a list of all APIs and then iterates through the list for each of the following steps:
I think this statement is incorrect.

Does `Ordering` (making a list) happens for every API request, or does it happen when the gateway starts?

If it happens for every request, isn't that inefficient?

2024-12-31 07:04 UTC, sharadregoti commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +- for equal length paths, lexicographical order is applied - e.g. `/api/aba` before `/api/abc`
Though, this lays out all the conditions. A better experience would be adding an embedded app here. Similar to the storage calculator app.

I am creating a Ticket for it.

2025-01-06 09:15 UTC, andyo-tyk commented on tyk-docs/content/getting-started/key-concepts/url-matching.md
> +On receipt of an API request Tyk firstly creates a list of all APIs and then iterates through the list for each of the following steps:
```suggestion
The APIs loaded on the Gateway are ordered as follows:
```

2025-01-06 09:24 UTC, sharadregoti approved these changes

2025-01-06 09:28 UTC, merged

2025-01-06 09:28 UTC, sharadregoti commented
/release to release-5.7