TT-13671: add Telemetry docs for Cloud
TykTechnologies/tyk-docs-hugo pull request #5816
Opened 2024-12-11 08:23 UTC by umit

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-12-12 11:22 UTC, excieve requested changes
Thanks @umit! There are a couple of comments. Also, could you please add a paragraph somewhere in the overview section that this is an add-on feature that can be enabled by contacting Tyk.

2024-12-12 11:22 UTC, excieve commented on tyk-docs/content/tyk-cloud/telemetry.md
> +Telemetry in Tyk Cloud helps you monitor and understand how your APIs are performing. Think of it as a health monitoring system for your APIs - it collects data about response times, error rates, and
Monitoring isn't a major part of this currently. Tyk only supports tracing atm, while some metrics may be derived from it. So I would instead highlight tracing here.

2024-12-12 11:22 UTC, excieve commented on tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
> +- API Token: Your New Relic license key
This section is about Dynatrace, but it mentions New Relic?

2024-12-12 11:22 UTC, excieve commented on tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
> +- API Token: Your New Relic license key
I don't think it's called a `license key`?

2024-12-12 11:22 UTC, excieve commented on tyk-docs/content/tyk-cloud/telemetry.md
> +Telemetry in Tyk Cloud helps you monitor and understand how your APIs are performing. Think of it as a health monitoring system for your APIs - it collects data about response times, error rates, and
Could you please also add a link to the [underlying Tyk Gateway feature](https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview/), which provides a bit more details about the functionality and its usage?

2024-12-12 11:23 UTC, excieve commented
@mitjaziv Could you please give it a quick review too?

2024-12-12 14:05 UTC, umit commented on tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
> +- API Token: Your New Relic license key
I checked New Relic documentation in this link: https://docs.newrelic.com/docs/data-apis/ingest-apis/telemetry-sdks-report-custom-telemetry-data/#requirements.

They are called `license key`.

2024-12-12 14:15 UTC, umit commented on tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
> +- API Token: Your New Relic license key
@excieve it's fixed.

2024-12-12 14:35 UTC, umit commented on tyk-docs/content/tyk-cloud/telemetry.md
> +Telemetry in Tyk Cloud helps you monitor and understand how your APIs are performing. Think of it as a health monitoring system for your APIs - it collects data about response times, error rates, and
@excieve I've updated description and added [Tyk Gateway feature](https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview/) link.

2024-12-12 17:08 UTC, excieve commented on tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
> +- API Token: Your New Relic license key
@umit Oh, I see. They call the header `api-key`, but it's actually their license key as mentioned here: https://docs.newrelic.com/docs/opentelemetry/best-practices/opentelemetry-otlp/#api-key

2024-12-12 17:10 UTC, excieve approved these changes
LGTM, thanks @umit!

2024-12-12 17:16 UTC, mitjaziv commented on tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
> +- Exporter: Choose gRPC (currently the supported protocol)
Both HTTP and gRPC are supported with Custom provider.

2024-12-12 17:16 UTC, mitjaziv commented on tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
> +- Provider Endpoint: Your monitoring system's URL
`Your monitoring system URL`

2024-12-12 17:19 UTC, mitjaziv approved these changes
Looks good to me.

I would suggest just maybe to add info, if general Telemetry settings are changed, that cloud data planes need to be redeployed for changes to take effect.

2024-12-13 06:05 UTC, umit commented on tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
> +- Provider Endpoint: Your monitoring system's URL
@mitjaziv done.

2024-12-13 06:07 UTC, umit commented on tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
> +- Exporter: Choose gRPC (currently the supported protocol)
@mitjaziv It's done.

2024-12-13 06:07 UTC, umit commented
> Looks good to me.
> 
> I would suggest just maybe to add info, if general Telemetry settings are changed, that cloud data planes need to be redeployed for changes to take effect.

@mitjaziv I've added this information in `Telemetry Export in Cloud Data Plane Deployments` section.

2024-12-16 13:21 UTC, sharadregoti approved these changes

2024-12-16 13:21 UTC, merged

2024-12-16 13:21 UTC, sharadregoti commented
/release to release-5.7