[DX-1781] Release notes for 5.3.9
TykTechnologies/tyk-docs-hugo pull request #5826
Opened 2024-12-16 15:46 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1781](https://tyktech.atlassian.net/browse/DX-1781)
---

### Preview Link

<br>

### Description

Release notes for 5.3.9 

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-12-17 08:05 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +### 5.3.9 Release Notes
```suggestion

### 5.3.9 Release Notes
```

2024-12-17 08:07 UTC, sharadregoti requested changes

2024-12-17 08:07 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +This release focuses mainly on bug fixes. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.3.9">}}) below.
```suggestion
This release contains a bug fix. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.3.9">}}) below.
```

2024-12-17 08:07 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +This release focuses mainly on bug fixes. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.3.9">}}) below.
```suggestion
This release contains a bug fix. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.3.9">}}) below.
```

2024-12-18 17:27 UTC, andyo-tyk requested changes

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +This release contains a bug fix. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.3.9">}}) below.
```suggestion
This release contains bug fixes. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.3.9">}}) below.
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +We have deprecated 'http_server_options.prefer_server_ciphers' in Tyk dashboard due due to its obsolescence in upstream dependencies.Users are advised to remove this configuration from their setups a
```suggestion
We have deprecated the obsolescent `http_server_options.prefer_server_ciphers` configuration option. This legacy control no longer has any effect on the underlying library and users are advised to remove this setting from their configurations.
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +<summary>Duplicate text in hint box for path-based permissions</summary>
I don't think this needs to be picked out in the change log - it's a very minor UI bug fix that has no impact on users. I would leave it out.

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +<summary>Blank screen on restore zoom in API activity dashboard</summary>
What do we mean by "restore zoom"?

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +<summary>Search icon non-responsive on keys page</summary>
```suggestion
<summary>Search icon unresponsive on API Keys page</summary>
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +Fixed the search functionality on the Keys page, enabling the search button to work independently of the Enter or Return key.
```suggestion
Fixed the search functionality on the API Keys page, enabling the search button to work independently of the Enter or Return key.
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +<summary>Keys remain active even after all linked partitioned policies are deleted</summary>
```suggestion
<summary>API Keys remain active after all linked partitioned policies are deleted</summary>
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +Resolved an issue where keys remained valid even after all associated policies were deleted. The Gateway now applies all available linked policies to a key during request validation and logs warnings
```suggestion
Resolved an issue where API access keys remained valid even if all associated policies were deleted. The Gateway now attempts to apply all linked policies to the key when it is presented with a request. Warning logs are generated if any policies cannot be applied (for example, if they are missing). If no linked policy can be applied, the Gateway will reject the key to ensure no unauthorized access.
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +This option has been marked as deprecated due to its obsolescence in upstream dependencies. Users are advised to remove this configuration from their setups as it will no longer have any effect in fu
```suggestion
This option has been marked as deprecated due to its obsolescence in the underlying library functions used by Tyk. Users are advised to remove this configuration from their setups as it no longer has any effect.
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +This release contains a bug fix. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.3.9">}}) below.
```suggestion
This release contains bug fixes. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.3.9">}}) below.
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>Resolved analytics data trimming with custom plugins</summary>
From the perspective of the Gateway, we refer to Traffic Logs, not analytics. I think this could be:

```suggestion
<summary>Incomplete traffic logs generated if custom response plugin adjusts the payload length</summary>
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +Resolved an issue where analytics data was incorrectly trimmed when a custom response plugin (coprocess) modified the response body to exceed the upstream content length.
```suggestion
Resolved an issue where the response body could be only partially recorded in the traffic log if a custom response plugin modified the payload. This was due to Tyk using the original, rather than the modified, content-length of the response when identifying the data to include in the traffic log.
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>Skip loading API security feature adjustments for Cloud users</summary>
I don't understand this summary - and it probably wouldn't make sense to a user.

This should describe the user impact, which was that it wasn't possible to create OAuth clients for APIs that use custom plugin bundles in multi-data plane deployments (such as Tyk Cloud).

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +Fixed a bug that prevented management gateways from loading plugin bundles due to a security feature introduced in v5.3.1.
```suggestion
Fixed a bug that prevented the control plane Gateway from loading APIs that use custom plugin bundles. The control plane Gateway is used to register OAuth clients and generate access tokens so this could result in an API being loaded to the data plane Gateways but clients unable to obtain access tokens. This issue was introduced in v5.3.1 as a side-effect of a change to address a potential security issue where APIs could be loaded without their custom plugins.
```

Does this make sense to you?

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>Debug log accuracy restored for middlewares</summary>
The issue here was that the system log stopped differentiating between different middleware, making it very difficult to debug issues.

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +Addressed an issue where shared loggers caused misreported debug logs for middlewares. Loggers are now explicitly copied to ensure accurate and distinct logging.
I think the first sentence is fine, but for the second I think we just need to make it clear that the log entries will now correctly identify the source of the log entry (i.e. which middleware generated the log).

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>Otel E2E Tests Issue After Upgrading to v1.29</summary>
This feels very much like an internal fix

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>Resolved API routing issue with trailing slashes and overlapping listen paths</summary>
Perhaps here the summary should just state that we've fixed some inconsistencies in the routing algorithm that led to incorrect API URL matching.

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>SSE streaming reliability enhanced</summary>
I think here we can be explicit - we've not enhanced SSE streaming reliability, we've fixed a bug where the Gateway would panic if SSE was used with OTel

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +Fixed an issue where upstream server-sent events (SSE) were not sent when OpenTelemetry was enabled.Resolved a gateway panic triggered when detailed recording was enabled and upstream sent SSE.
From my reading of the ticket, the issue was that the Gateway would panic (crash) - probably worth checking with @jeffy-mathew, as the release note on the ticket does mention two fixes, but the ticket description only mentions the panic.

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>OAuth 2.0 token issuance now supported in Emergency mode</summary>
I don't see "Emergency Mode" anywhere in the docs - so would recommend something like:

```suggestion
<summary>Fixed an issue where OAuth 2.0 access tokens would not be issued if the data plane was disconnected from the control plane</summary>
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +OAuth 2.0 tokens can now be issued even when data plane gateways are in emergency mode. This is achieved by saving OAuth clients locally when they are pulled from RPC.
```suggestion
OAuth 2.0 access tokens can now be issued even when data plane gateways are disconnected from the control plane. This is achieved by saving OAuth clients locally within the data plane when they are pulled from RPC.
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>Request size limit Middleware no longer breaks GET or DELETE requests</summary>
"Breaks" is a bit vague - I would suggest something like:

```suggestion
<summary>Request size limit middleware would block any request without a payload (for example GET, DELETE)</summary>
```

2024-12-18 17:27 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +Resolved a problem where the request size limit middleware was incorrectly breaking GET and DELETE requests.
I think we can explain here that the middleware would expect to see a request body (payload) and fail validation if none was found, effectively blocking GET and DELETE methods.

2024-12-19 15:11 UTC, andyo-tyk requested changes
Need to double check that issues appear in the correct change log (GW / Dash)

2024-12-19 15:11 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +This option has been marked as deprecated due to its obsolescence in the underlying library functions used by Tyk. Users are advised to remove this configuration from their setups as it no longer has
This description is wrong - it's a copy/paste from above, doesn't relate to this fix.

2024-12-20 10:25 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +Resolved CVE-2020-8911 by updating the Tyk Dashboard's email driver to use AWS SDK v2, addressing a medium-severity security vulnerability identified in version 5.3.8. This update ensures enhanced se
```suggestion
Resolved CVE-2020-8911 by updating the Tyk Dashboard's email driver to use AWS SDK v2, addressing a medium-severity security vulnerability identified in version 5.3.8. This update ensures enhanced security for the Dashboard while maintaining functionality.
```

2024-12-20 10:29 UTC, andyo-tyk approved these changes

2024-12-20 10:35 UTC, sharadregoti requested changes

2024-12-20 10:35 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<!-- Required. The change log should include the following ordered set of sections below that briefly summarise the features, updates and fixed issues of the release.
Remove the comments & follow the standard template

2024-12-20 10:35 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>Resolved API routing issue with trailing slashes and overlapping listen paths</summary>
Does this bug fix specific to `5.3.9`? I cannot find the same in `5.7.1`

2024-12-20 10:43 UTC, Eopayemi commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +<summary>Resolved API routing issue with trailing slashes and overlapping listen paths</summary>
It was in 5.7.0 so it only need to be 5.3.9

2024-12-20 14:20 UTC, caroltyk approved these changes

2024-12-31 05:13 UTC, sharadregoti approved these changes

2024-12-31 05:20 UTC, merged

2024-12-31 05:21 UTC, sharadregoti commented
/release to release-5.7