[DX-1781] Release notes for 5.7.1
TykTechnologies/tyk-docs-hugo pull request #5827
Opened 2024-12-16 16:42 UTC by Eopayemi

### For internal users - Please add a Jira DX PR ticket to the subject!
[DX-1781](https://tyktech.atlassian.net/browse/DX-1781)

---

### Preview Link

<br>

### Description

Release notes for 5.7.1

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-12-17 08:05 UTC, sharadregoti requested changes

2024-12-17 08:05 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +This fix focuses mainly on bug fix.For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.7.1" >}}) below.
```suggestion
This release contains a bug fix. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.7.1" >}}) below.
```

2024-12-17 08:05 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +<!-- Required. Use the following statement if there are no breaking changes, or explain if there are -->
```suggestion
```

Please remove all the commented stuff. [Condensed template](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/assets/others/release-notes-condensed-template.md?plain=1) does not have any comments in it.

Do the same in gateway RN

2024-12-17 08:05 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +Add changelog description
Please update the change log with the bug fix & remove sections which are not required.

Do the same in gateway

2024-12-17 08:05 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/gateway.md
> +This fix focuses mainly on bug fixes. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.7.1">}}) below.
```suggestion
This release contains a bug fix. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.7.1">}}) below.
```

2024-12-18 15:13 UTC, andyo-tyk commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +This fix focuses mainly on bug fix.For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.7.1" >}}) below.
@sharadregoti should this be "....contains bug fixes."? (same for both files)

2024-12-20 10:28 UTC, sharadregoti approved these changes
TODO: Update release date while merging

2024-12-20 10:28 UTC, sharadregoti commented on tyk-docs/content/developer-support/release-notes/dashboard.md
> +This release focuses mainly on bug fixes.For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.7.1" >}}) below.
```suggestion
This release focuses mainly on bug fixes. For a comprehensive list of changes, please refer to the detailed [changelog]({{< ref "#Changelog-v5.7.1" >}}) below.
```

2024-12-20 10:33 UTC, andyo-tyk approved these changes

2024-12-20 14:23 UTC, caroltyk approved these changes

2024-12-31 05:12 UTC, merged

2024-12-31 05:12 UTC, sharadregoti commented
/release to release-5.7