[TT-13731] Fixes bundle plugin sub-directory problem.
TykTechnologies/tyk-docs-hugo pull request #5831
Opened 2024-12-18 08:03 UTC by sharadregoti

### For internal users - Please add a Jira DX PR ticket to the subject!
<br>

---

### Preview Link

<br>

### Description

<br>

#### Screenshots (if appropriate)
<br>

## Checklist

- [ ] I have added a **preview link** to the PR description.
- [ ] I have reviewed the suggestions made by our AI (PR Agent) and updated them accordingly (spelling errors, rephrasing, etc.)
- [ ] I have [reviewed the guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING.md) for contributing to this repository.
- [ ] I have [read the technical guidelines](https://github.com/TykTechnologies/tyk-docs/blob/master/CONTRIBUTING-TECHNICAL-GUIDE.md) for contributing to this repository.
- [ ] Make sure you have started *your change* off *our latest `master`*.
- [ ] I **labeled** the PR

2024-12-24 08:41 UTC, OldStubbsy requested changes
Lines 61 and 62 made sense when the bundles where in subdirectories, they don't when they're not.

Also their reference to Python doesn't make sense when the default in the docs is golang. I don't think a  language needs to be mentioned, they're just "plugin source files"

An example manifest to go with each example directory would make things much more clear. There's an example manifest at https://tyk.io/docs/plugins/how-to-serve-plugins/plugin-bundles/#manifest which could be used as a starting place

2025-01-07 13:43 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
> +plugins based on the paths defined in the `manifest.json` file.
```suggestion
The `manifest.json` will reference the files located in the `bundle-directory`, ensure plugin source files are organized relative to the manifest. The Tyk Gateway will load and execute these plugins based on the paths defined in the `manifest.json` file.
```

Unnecessary newline.

2025-01-07 13:43 UTC, titpetric commented on tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
> +Subdirectory are not supported in the `bundle-directory`
```suggestion
Subdirectories are not supported in the `bundle-directory`.

```

2025-01-08 12:05 UTC, OldStubbsy approved these changes
A huge improvement, thanks

2025-01-14 07:59 UTC, titpetric approved these changes

2025-01-14 08:36 UTC, merged

2025-01-14 08:36 UTC, sharadregoti commented
/release to release-5.7

2025-01-14 08:37 UTC, sharadregoti commented
/release to clone-master-before-major-ia-change