First Draft JWT examples
TykTechnologies/tyk-docs-hugo pull request #754
Opened 2019-04-22 18:21 UTC by marksou

Fixes #719

2019-07-27 03:45 UTC, letzya commented
@marksou

2019-09-20 10:02 UTC, letzya requested changes

2019-09-20 10:02 UTC, letzya commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +3. For the JWT Signing method, select HAMAC from the drop-down list as in [Step 2](/docs/security/your-apis/json-web-tokens/#step-2-set-the-jwt-signing-method) above.
not hamac

2019-09-20 10:02 UTC, letzya commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +3. For the JWT Signing method, select HAMAC from the drop-down list as in [Step 2](/docs/security/your-apis/json-web-tokens/#step-2-set-the-jwt-signing-method) above.
We should say which hmac we are using

2019-09-20 10:02 UTC, letzya commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +4. Enter `sub` as the Identity Source, as in [Step 3](/docs/security/your-apis/json-web-tokens/#step-3-set-the-identity-source-and-policy-field-name) above. The Policy field can be left blank.
Change to
“Set policy field to the name of the claim you will be using in your jwt when referring to the policy. For instance “pol” “

2019-09-20 10:02 UTC, letzya commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +8. Enter the following cURL command. ```curl -k https://tyk123.cloudv2.tyk.io/jwt-test/ip```
Remove tyk123 and put a placeholder “{tyk-gateway}

2019-09-20 10:02 UTC, letzya commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +3. For the JWT Signing method, select HAMAC from the drop-down list as in [Step 2](/docs/security/your-apis/json-web-tokens/#step-2-set-the-jwt-signing-method) above.
“Create an API from the Designer. For this example `jwt-test`” —> I don’t understand this wording. Did you mean to write “Create an API using the UI and name it `jwt-test`”
@mark

2019-09-20 10:02 UTC, letzya commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +### JWT with Header
Jwt with header?
Is it “Authenticate an api with user’s unique signing jwt”?

2019-10-11 09:08 UTC, marksou commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +3. For the JWT Signing method, select HAMAC from the drop-down list as in [Step 2](/docs/security/your-apis/json-web-tokens/#step-2-set-the-jwt-signing-method) above.
Have changed this

2019-10-11 09:23 UTC, marksou commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +4. Enter `sub` as the Identity Source, as in [Step 3](/docs/security/your-apis/json-web-tokens/#step-3-set-the-identity-source-and-policy-field-name) above. The Policy field can be left blank.
Added

2019-10-11 09:24 UTC, marksou commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +8. Enter the following cURL command. ```curl -k https://tyk123.cloudv2.tyk.io/jwt-test/ip```
As we have used **tyk123** to create the example, this should stay in the command to allow the example to work.

2019-10-11 09:35 UTC, marksou commented on tyk-docs/content/security/your-apis/json-web-tokens.md
> +### JWT with Header
Changed

2020-04-08 04:09 UTC, closed without merging