Response body update
TykTechnologies/tyk-docs-hugo pull request #770
Opened 2019-05-01 08:55 UTC by marksou

First draft

2019-11-10 20:56 UTC, letzya requested changes
The context var in body trans is repeated about 3 times out of which two mention iterating through a list (each had different syntax which makes it even more confusing).
(Just search the word “unlike” and see for yourself)
From brief review of the changes I think this page needs a bit of love - consolidate all the related info in one place and not in 3 different places in the same page but might be wrong.

2019-11-10 20:56 UTC, letzya commented on tyk-docs/content/transform-traffic/request-body.md
> +As of version 2.2 Tyk also allows context variables to be injected into the body using the `._tyk_context.` namespace. Unlike the context exposed to the URL rewriter and header injector, the body tra
Not sure [0] is the right syntax.

2019-11-11 11:34 UTC, marksou commented on tyk-docs/content/transform-traffic/request-body.md
> +As of version 2.2 Tyk also allows context variables to be injected into the body using the `._tyk_context.` namespace. Unlike the context exposed to the URL rewriter and header injector, the body tra
`do we just nee do remove the brackets?

2020-03-14 23:56 UTC, asoorm commented on tyk-docs/content/transform-traffic/request-body.md
> +As of version 2.2 Tyk also allows context variables to be injected into the body using the `._tyk_context.` namespace. Unlike the context exposed to the URL rewriter and header injector, the body tra
@marksou please try it - I think you need to specify `index key 0`

2021-03-02 09:34 UTC, marksou commented on tyk-docs/content/transform-traffic/request-body.md
> +As of version 2.2 Tyk also allows context variables to be injected into the body using the `._tyk_context.` namespace. Unlike the context exposed to the URL rewriter and header injector, the body tra
Fixed

2021-03-02 09:39 UTC, merged