Changes to Hashed Keys sections for Add/Update
TykTechnologies/tyk-docs-hugo pull request #771
Opened 2019-05-01 12:49 UTC by marksou

First draft

2019-05-01 15:37 UTC, letzya commented on tyk-docs/content/tyk-rest-api/token-management.md
> +When using in a hashed key environment, you should be aware of the following [Hashed Key Environment](/docs/security/#using-hashed-keys-endpoints) settings.
@marksou I actually think it makes more sense to move the content of the link over here and put a link in /docs/security/#using-hashed-keys-endpoints since this page has the list of our gateway endpoints

2019-05-01 15:41 UTC, letzya requested changes

2019-05-01 15:41 UTC, letzya commented on tyk-docs/content/security/security.md
> +See [Add/Update Keys](/docs/tyk-rest-api/token-management/#add-update-keys) for more details on using these endpoints with the Tyk Gateway API.
See my comment below

2019-05-02 09:59 UTC, marksou commented on tyk-docs/content/tyk-rest-api/token-management.md
> +When using in a hashed key environment, you should be aware of the following [Hashed Key Environment](/docs/security/#using-hashed-keys-endpoints) settings.
Do we put the Hashed Keys info at the top of the page and link to the relevant endpoint further down the page. They are not all relevant to the Add/Update endpoint.

2019-06-07 07:25 UTC, marksou commented
Updated in other commits.

2019-06-07 07:25 UTC, closed without merging