JWT Scopes
TykTechnologies/tyk-docs-hugo pull request #847
Opened 2019-07-16 15:55 UTC by sedkis

Add section about how to manage scopes and associate them with policies when using a JWT protected API and JWT tokens

2019-07-16 15:58 UTC, sedkis commented
Yikes, this was forked off another feature branch.  Which is why it includes that CSS update section.  Please ignore that while I fix it.

2019-07-17 15:59 UTC, letzya commented on tyk-docs/content/tyk-developer-portal/customise/customising-using-dashboard.md
> +-H "Authorization:<DASHBOARD API KEY>"
@marksou what is our recommended notation for variables? 
 -H "Authorization:<DASHBOARD API KEY>"  
or 
 -H "Authorization:{DASHBOARD API KEY}" 
or something else?

2019-07-17 16:11 UTC, sedkis commented on tyk-docs/content/tyk-developer-portal/customise/customising-using-dashboard.md
> +-H "Authorization:<DASHBOARD API KEY>"
This is a good question.. we definitely need to define a standard.

2019-07-17 16:22 UTC, marksou commented on tyk-docs/content/tyk-developer-portal/customise/customising-using-dashboard.md
> +-H "Authorization:<DASHBOARD API KEY>"
I've been using (for example):

-H "Authorization:{DASHBOARD_API_KEY}"

So using uppercase and underscores with curly brackets.

2019-07-17 17:30 UTC, letzya requested changes
Remove jwt completely (will be part of 2.9 release).

2019-07-17 17:31 UTC, sedkis commented
@letzya perhaps we can leave this open until we merge the CSS change in its own PR:
https://github.com/TykTechnologies/tyk-docs/pull/842
once 842 gets merged we can leave this PR open until 2.9, then we can merge it

2019-07-17 18:53 UTC, letzya commented
@sedkis a bit confused and don’t want to compare. Can you maybe just  remove the css changes from here and add them to the other pr?

2019-07-19 19:26 UTC, closed without merging

2019-07-19 19:26 UTC, sedkis commented
Closing so we don't accidentally merge.  but we can use this to build onto

2019-07-20 07:57 UTC, letzya commented
I’ll write something next week