add docs for distributed tracing
TykTechnologies/tyk-docs-hugo pull request #860
Opened 2019-07-29 11:19 UTC by gernest

2019-07-30 14:45 UTC, buger commented
@gernest can you add a bit more "educational" part here? What is distributed tracing, why it is needed, and how our users can leverage it.

2019-07-31 08:52 UTC, marksou approved these changes
Made a few minor amendments.

2019-07-31 09:23 UTC, asoorm commented on tyk-docs/content/distributed-tracing/distributed-tracing.md
> +        "name": "${tracer_name}",
I would reduce indentation. + for JS, 2-space tabs.

2019-07-31 09:24 UTC, asoorm commented on tyk-docs/content/distributed-tracing/jaeger.md
> +Jaeger is a distributed tracing system.It is used for monitoring and troubleshooting microservices-based distributed systems. To lean more about jaeger [visit their website](https://www.jaegertracing
`stem.It` Space required after full-stop.

2019-07-31 09:25 UTC, asoorm commented on tyk-docs/content/distributed-tracing/jaeger.md
> +    "tracing": {
Formatting of json. as per comment above.

2019-07-31 09:26 UTC, asoorm commented on tyk-docs/content/distributed-tracing/jaeger.md
> +    "tracing": {
formatting

2019-07-31 09:27 UTC, asoorm commented on tyk-docs/content/distributed-tracing/zipkin.md
> +    "tracing": {
formatting + syntax highlight annotation missing

2019-07-31 09:28 UTC, asoorm commented on tyk-docs/content/distributed-tracing/zipkin.md
> +    "tracing": {
formatting

2019-07-31 09:29 UTC, asoorm requested changes
minor nits

2019-07-31 10:30 UTC, asoorm approved these changes
LGTM - Agree with @buger about educational piece

2019-08-01 09:16 UTC, merged