improving ulimit docs
TykTechnologies/tyk-docs-hugo pull request #867
Opened 2019-08-02 15:11 UTC by asoorm

2019-08-02 15:17 UTC, excieve requested changes
In addition to this, possibly mention how to change it for docker.

2019-08-02 15:17 UTC, excieve commented on tyk-docs/content/deploy-tyk-premise-production/deploy-tyk-premise-production.mmark
> +* Gateway `/usr/lib/systemd/system/tyk-gateway.service`
Shouldn't recommend modifying these as they'll get overwritten on package upgrade. Instead suggest systemd unit overrides (`systemctl edit`).

2019-08-02 16:10 UTC, asoorm commented
@excieve PTAL

2019-08-02 18:57 UTC, excieve reviewed
I'd still add a note for containers, even if it's just about changing the container runtime's (such as Docker) unit file.

2019-08-02 18:57 UTC, excieve commented on tyk-docs/content/deploy-tyk-premise-production/deploy-tyk-premise-production.mmark
> +for the current session using `echo 120000 > /proc/sys/fs/file-max`.
`160000`?

2019-08-02 18:57 UTC, excieve commented on tyk-docs/content/deploy-tyk-premise-production/deploy-tyk-premise-production.mmark
> +Please note that a single file, with associated inode & dcache consumes approximately 1kb RAM. As such, setting
Nit: `KB` or `kB` and `MB` (`kb` is kilobit and `Mb` is megabit) :)

2019-08-05 08:57 UTC, excieve approved these changes
LGTM

2019-08-05 09:41 UTC, merged