Tidy up OpenID Connect info
TykTechnologies/tyk-docs-hugo pull request #927
Opened 2019-10-24 13:52 UTC by marksou

2019-10-24 18:27 UTC, sedkis requested changes

2019-10-24 18:27 UTC, sedkis commented on tyk-docs/content/security/your-apis/openid-connect.md
> +For more details about our OpenID Connect support see [OpenID Integration](http://localhost:1313/docs/integrate/api-auth-mode/open-id-connect/).
the link says "localhost", surely this isn't accurate?

2019-10-24 21:09 UTC, marksou commented on tyk-docs/content/security/your-apis/openid-connect.md
> +For more details about our OpenID Connect support see [OpenID Integration](http://localhost:1313/docs/integrate/api-auth-mode/open-id-connect/).
Fixed in new push

2019-10-25 13:25 UTC, sedkis approved these changes

2019-10-25 13:25 UTC, merged